### PR TITLE
IntersectSorted: Change logic to use IntersectWith

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/676)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: One comment.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[algo/uidlist.go, line 186 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-KegvTnm6yNpg3hRxY4y:-KegvTnnmmtXUaRRPgsa:b2hm34q) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a25f7bed69793c9b5bfa36fe221bbc663e97782/algo/uidlist.go#L186)):*
> ```Go
> 	})
> 	out := &task.List{Uids: make([]uint64, ls[0].length)}
> 	copy(out.Uids, ls[0].l.Uids)
> ```

This copy seems unnecessary. Can we avoid it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-:-Kegvl8yhBmAVIuO3_qP:bpjwta0)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[algo/uidlist.go, line 186 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-KegvTnm6yNpg3hRxY4y:-KelI-pfX63ko25oLC88:b-sp2yuh) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a25f7bed69793c9b5bfa36fe221bbc663e97782/algo/uidlist.go#L186)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This copy seems unnecessary. Can we avoid it?
</blockquote></details>

We don't want to modify the original lists in this function. So I can't think of a way to avoid this here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676)*

**Comment by manishrjain** [comment]
I think this needs work. We should also rethink the way we output to our Intersect function, given the new functions are not compatible with using the first list as the output always.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[algo/uidlist.go, line 186 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-KegvTnm6yNpg3hRxY4y:-KelPny3Hhz1GTf6SHmU:b-pvwg55) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a25f7bed69793c9b5bfa36fe221bbc663e97782/algo/uidlist.go#L186)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We don't want to modify the original lists in this function. So I can't think of a way to avoid this here.
</blockquote></details>

Can't you have Intersect functions take in a list for output?

Intersect(a, b, *out). So, if we just want to reuse one of these lists, we can just do: Intersect(a, b, &a) -- That way, it's clear what we're expecting to be changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-:-KelQ5N_sdHwwR_pEg2w:b3hho4s)*

**Comment by ashishnegi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-:-KelQiNG0Df_e4AqvEp3:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[algo/uidlist.go, line 186 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-KegvTnm6yNpg3hRxY4y:-KelkSKHuOIgfG_pn9n0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a25f7bed69793c9b5bfa36fe221bbc663e97782/algo/uidlist.go#L186)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can't you have Intersect functions take in a list for output?

Intersect(a, b, *out). So, if we just want to reuse one of these lists, we can just do: Intersect(a, b, &a) -- That way, it's clear what we're expecting to be changed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676)*

**Comment by ashishnegi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[algo/uidlist.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-KelpGLSnLgFtH6L7Yhw:-KelpGLTAXeuhkTABtn2:bmgih73) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L173)):*
> ```Go
> }
> 
> func IntersectSorted(lists []*task.List) *task.List {
> ```

as we changed the interface for intersectwith, should not we have the *out here as well ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[algo/uidlist.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-KelpGLSnLgFtH6L7Yhw:-KemLnDyu_7snUB2p8Fy:bjbhd4y) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L173)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

as we changed the interface for intersectwith, should not we have the *out here as well ?
</blockquote></details>

This is already returning a List and not modifying an existing list. So this should be okay I feel. But we can change it if you think it'd have some advantage over this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676)*

**Comment by ashishnegi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[algo/uidlist.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-KelpGLSnLgFtH6L7Yhw:-KemeE8RnRxIODexWp6O:bln3o5r) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L173)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This is already returning a List and not modifying an existing list. So this should be okay I feel. But we can change it if you think it'd have some advantage over this.
</blockquote></details>

I just thought about consistency of function signature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676)*

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[algo/uidlist.go, line 34 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4gwxYmRgN6ZNQ4gHJ:-Kf4gwxYmRgN6ZNQ4gHK:b-zcvhj6) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L34)):*
> ```Go
> 	if o.Uids == nil {
> 		o.Uids = make([]uint64, n)
> 	}
> ```

dst := o.Uids[:0]

IntersectWithLin(u, v, dst)
...

o.Uids = dst

---

*[algo/uidlist.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4ha6lSxCDwpVGSAsT:-Kf4ha6lSxCDwpVGSAsU:b-k57qd6) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L41)):*
> ```Go
> 	ratio := float64(m) / float64(n)
> 	if ratio < 100 {
> 		IntersectWithLin(u, v, o)
> ```

(u.Uids, v.Uids, dst)

---

*[algo/uidlist.go, line 190 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4i_rkk6xqxpVHV40c:-Kf4i_rkk6xqxpVHV40d:b-l6ibnv) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L190)):*
> ```Go
> 	out := &task.List{Uids: make([]uint64, ls[0].length)}
> 	if len(ls) == 1 {
> 		copy(out.Uids, ls[0].l.Uids)
> ```

return

---

*[algo/uidlist.go, line 191 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4iawWfB-ECx5eZQSr:-Kf4iawWfB-ECx5eZQSs:bn4bj0h) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L191)):*
> ```Go
> 	if len(ls) == 1 {
> 		copy(out.Uids, ls[0].l.Uids)
> 	} else {
> ```

You don't need else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676)*

**Comment by ashwin95r** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[algo/uidlist.go, line 34 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4gwxYmRgN6ZNQ4gHJ:-Kf4rcrMe6pPx0vf7G2H:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L34)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

dst := o.Uids[:0]

IntersectWithLin(u, v, dst)
...

o.Uids = dst
</blockquote></details>

Done.

---

*[algo/uidlist.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4ha6lSxCDwpVGSAsT:-Kf4rcXqy-m7Lg3FoIYW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

(u.Uids, v.Uids, dst)
</blockquote></details>

Done.

---

*[algo/uidlist.go, line 190 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4i_rkk6xqxpVHV40c:-Kf4reAJ54bJBF4FO3Mm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L190)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return
</blockquote></details>

Done.

---

*[algo/uidlist.go, line 191 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-Kf4iawWfB-ECx5eZQSr:-Kf4rfL1p-6XExlYywLT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/93043d93bb41d3eb03ea2c4177bb3aa5c84b0f94/algo/uidlist.go#L191)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need else.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/676#-:-Kf5MBtQ02MxfsYinjYP:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
