### PR TITLE
Move connection pool to its own package, so we can use it from dgraph…

### PR DESCRIPTION
**Pull request by manishrjain**
…zero.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1394)

### CODE REVIEW

**Comment by srh** [comment]
dgraph... zero?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394#-:-Kt8wr4yOZzv2theBW1q:b-6byove)*

**Comment by janardhan1993** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[conn/pool.go, line 172 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394#-Kt9AwHfe9eQ-rEAuyvk:-Kt9AwHfe9eQ-rEAuyvl:bq7n49g) ([raw file](https://github.com/dgraph-io/dgraph/blob/9579c50009a58b1c99a4518005b3d1cd2b2509fe/conn/pool.go#L172)):*
> ```Go
> 
> // NewPool creates a new "pool" with one gRPC connection, refcount 0.
> func NewPool(addr string) (*Pool, error) {
> ```

Does this need to be exported ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[conn/pool.go, line 172 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394#-Kt9AwHfe9eQ-rEAuyvk:-Kt9GMAvqn0cnLYxarIw:b-s8otyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/9579c50009a58b1c99a4518005b3d1cd2b2509fe/conn/pool.go#L172)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Does this need to be exported ?
</blockquote></details>

Being used in worker/predicate_test.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394)*

**Comment by srh** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394#-:-Kt9PWImfP1lO7Wz0uMj:bg7igkv)*

**Comment by srh** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1394#-:-Kt9R6RU2F4a0lLXHUwY:bnfp4nl)*

**Pull request closed without merging**
