### PR TITLE
Add fix for panic

### LINKED ISSUE #1284: panic: runtime error: invalid memory address or nil pointer dereference
**Query**
{
  h(func: eq(path_id, uid(0x1))) @filter(eq(user_id, uid(0x2)) AND eq(sha512, uid(0x3)))
}

**Output**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb74acf]

goroutine 10744 [running]:
github.com/dgraph-io/dgraph/query.ProcessGraph(0x1302e80, 0xc424debaa0, 0xc420074900, 0x0, 0xc424debb00)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1604 +0xbf
created by github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2204 +0x4a9

**Server**
Docker image dgraph/dgraph as of Jul, 31st, 2017.
Using default tag: latest
latest: Pulling from dgraph/dgraph
Digest: sha256:00b0a5a4ee1cbf48a2321bb2a89a1580fbcc55d09d75e6659e72537cf4155490
Status: Image is up to date for dgraph/dgraph:latest

**Database contents**
Half-way through dgraph tour, I haven't added any schema or data to support the query yet.

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #1284. 

We disallow functions other than `val` and `count` within other functions. Earlier the query below didn't result in an error but panics in ProcessGraph.
```
{
  me(func: eq(path_id, uid(0x1))) {
    ...
  }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1298)

### CODE REVIEW

**Comment by tzdybal** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 1413 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-KqWcAThp_fptQENgQ42:-KqWcAThp_fptQENgQ43:blykz2j) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b503141b8dde14f2b7242233d71b7b9040c60ed/gql/parser.go#L1413)):*
> ```Go
> 						g.NeedsVar[0].Typ = VALUE_VAR
> 					} else {
> 						if f.Name != "count" {
> ```

Where is the handling for `val`?

---

*[query/query_test.go, line 8563 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-KqWbo9adqsgNdHzo52s:-KqWbo9adqsgNdHzo52t:b-wv8a09) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b503141b8dde14f2b7242233d71b7b9040c60ed/query/query_test.go#L8563)):*
> ```Go
> }
> 
> func TestEqUidFunctionErr(t *testing.T) {
> ```

Such test should be implemented in parser package, not in query. We don't need the entire processing to get the error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298)*

**Comment by pawanrawal** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 1413 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-KqWcAThp_fptQENgQ42:-KqWgAt_JajYpOsNLupJ:b-pct75r) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b503141b8dde14f2b7242233d71b7b9040c60ed/gql/parser.go#L1413)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Where is the handling for `val`?
</blockquote></details>

It's in the if block above.

---

*[query/query_test.go, line 8563 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-KqWbo9adqsgNdHzo52s:-KqWgELkLpDIh1hJko2h:b-9yy7en) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b503141b8dde14f2b7242233d71b7b9040c60ed/query/query_test.go#L8563)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Such test should be implemented in parser package, not in query. We don't need the entire processing to get the error.
</blockquote></details>

Right, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298)*

**Comment by tzdybal** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gql/parser.go, line 1404 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-KqWhzV-zGT8Llk13vO2:-KqWhzV-zGT8Llk13vO3:b-2jws86) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b503141b8dde14f2b7242233d71b7b9040c60ed/gql/parser.go#L1404)):*
> ```Go
> 					}
> 					seenFuncArg = true
> 					if f.Name == VALUE {
> ```

Just btw - this const (I guess it's const) name is against Go naming convention. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-:-KqWiO-zxwBhQ35U21Fn:bg7igkv)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 1415 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-Kq_QEluzgF0NFh_SG88:-Kq_QEluzgF0NFh_SG89:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/d554b8a6c418348de977afb51a317d26eea46e44/gql/parser.go#L1415)):*
> ```Go
> 						if f.Name != "count" {
> 							return nil,
> 								x.Errorf("Only val/count allowed as function within another. Got: %s", f.Name)
> ```

100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1298#-:-Kq_QTplJzf9MXrXNQHo:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
