### PR TITLE
Fix/blockcache

### PR DESCRIPTION
**Pull request by jchiu0**
1) Use NewStore instead of new(...) and init.
2) Check returned errors.
3) Properly initialize blockCachedOptions (RocksDB) and propagate it.
4) Add flags for blockCache.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/175)

### CODE REVIEW

**Comment by jchiu0** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 47 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPqrtErnqlOxfoEIuG--r1-47:-KPrLK_kY9er44bgS01W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ade945a8992ddaa0800c16aa2bff54f961152542/store/store.go#L47)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported type Options should have comment or be unexported
</details>
Done.

---

*[store/store.go, line 52 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPqrtErnqlOxfoEIuG--r1-52:-KPrLRxtoPM1sYQ_KXDE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ade945a8992ddaa0800c16aa2bff54f961152542/store/store.go#L52)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function NewDefaultOptions should have comment or be unexported
</details>
Done.

---

*[store/store.go, line 90 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPqrtErnqlOxfoEIuG--r1-90:-KPrLSsaxgIAVqIYOJty:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ade945a8992ddaa0800c16aa2bff54f961152542/store/store.go#L90)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function NewStore should have comment or be unexported
</details>
Done.

---

*[store/store.go, line 100 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPqrtErnqlOxfoEIuG--r1-100:-KPrLTqciHURT8_z3YWs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ade945a8992ddaa0800c16aa2bff54f961152542/store/store.go#L100)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function NewReadOnlyStore should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/175)*

**Comment by manishrjain** [comment]
Looks like a good PR. The main question I have is, what's the actual measured impact of block cache flags? IIRC, the tests were indecisive about the impact of it on performance.

---

Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 35 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlxt2nw4P7OzBLqhJ:-KPwlxt2nw4P7OzBLqhK:b7a6exp) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L35)):*
> ```Go
> 	// quite a bit of typing and it should be clear (and remain clear) that all
> 	// RocksDB flags are found here and here only.
> 	enableBlockCache = flag.Bool("enableBlockCache", false, "use block cache for RocksDB")
> ```

I assume that if you disable the block cache there's some performance benefit? If so, please provide details in wiki or here.

---

*[store/store.go, line 36 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlqTHBvQ4MkSv8U7l:-KPwlqTHBvQ4MkSv8U7m:b5jpuof) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L36)):*
> ```Go
> 	// RocksDB flags are found here and here only.
> 	enableBlockCache = flag.Bool("enableBlockCache", false, "use block cache for RocksDB")
> 	blockCacheSize   = flag.Int("blockCacheSize", 8<<20, "block cache size for RocksDB")
> ```

How did you choose 8MB? What's the impact of changing this value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-:-KPwmSQ7MrblCYCRVWUB:b-vmdkhw)*

**Comment by manishrjain** [comment]
Ping?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-:-KQIn2ZF1zO4PW2wTf_l:b-82oq9k)*

**Comment by jchiu0** [comment]
Sorry for the late reply. I didn't manage to arrive at anything conclusive. Sometimes it is slower, sometimes it is faster with blockcache. However, I still think we should fix store.go such that blockopt is actually used. May I submit?

One thing might be to change the flag to "disableBlockCache" so that the default value is false and block cache is enabled. Wonder what you think about this?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 35 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlxt2nw4P7OzBLqhJ:-KQJKich3VrEH8ISJFc8:b-8jo1v8) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I assume that if you disable the block cache there's some performance benefit? If so, please provide details in wiki or here.
</details>
Now I am uncertain if there is any benefit to turning it on or off, as there is huge variance in the measurements.

---

*[store/store.go, line 36 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlqTHBvQ4MkSv8U7l:-KQJKULVHy9lZdGC33iN:bo58plj) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L36)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> How did you choose 8MB? What's the impact of changing this value?
</details>
8M is the current default value set in RocksDB. I found that the running time can vary quite a lot even as I try not to use my machine, as I turn on and off block cache. I think it might be hard to measure its impact accurately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-:-KQJKsTxeqZMDUsh9JHC:b-s1x37p)*

**Comment by manishrjain** [comment]
I think if we  are not convinced about improvements with block cache, then we shouldn't touch them. Have a look at my comments, and once addressed, we should be closer to submitting.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 35 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlxt2nw4P7OzBLqhJ:-KQQ4rrSUPJtNUNQFKuL:b-59niqw) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L35)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Now I am uncertain if there is any benefit to turning it on or off, as there is huge variance in the measurements.
</details>
If there's no benefit, then we should remove this flag.

---

*[store/store.go, line 36 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlqTHBvQ4MkSv8U7l:-KQQ4vJSybsnySPes0yT:benh7f5) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L36)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> 8M is the current default value set in RocksDB. I found that the running time can vary quite a lot even as I try not to use my machine, as I turn on and off block cache. I think it might be hard to measure its impact accurately.
</details>
If we are not convinced about the impact, then there's no need to have this flag.

---

*[store/store.go, line 49 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KQQ5_NrWzbrOEbMs7Na:-KQQ5_Ns6h--2pRu4rLF:bfw0maj) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L49)):*
> ```Go
> 
> // Options is a set of options to configure RocksDB usage in Dgraph only.
> type Options struct {
> ```

Don't need this.

---

*[store/store.go, line 55 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KQQ5dAcCyxaI4wLfOWa:-KQQ5dAcCyxaI4wLfOWb:b3ubgkc) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L55)):*
> ```Go
> 
> // NewDefaultOptions creates default options for RocksDB in Dgraph.
> func NewDefaultOptions() *Options {
> ```

Don't need this either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-:-KQQ5lAy5nZIUbwVgAdh:b1r6kg9)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 35 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlxt2nw4P7OzBLqhJ:-KQQgsnZMilc0ny4EwXH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> If there's no benefit, then we should remove this flag.
</details>
Done.

---

*[store/store.go, line 36 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KPwlqTHBvQ4MkSv8U7l:-KQQgluVJw1eKCc51btO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L36)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> If we are not convinced about the impact, then there's no need to have this flag.
</details>
Done.

---

*[store/store.go, line 49 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KQQ5_NrWzbrOEbMs7Na:-KQQgmTfrH6XwZbY0mHP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L49)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Don't need this.
</details>
Done.

---

*[store/store.go, line 55 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-KQQ5dAcCyxaI4wLfOWa:-KQQgndFSRfDxhrFscfl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdbf3f697944c998c5cc97f9f648a81c36d7f6ef/store/store.go#L55)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Don't need this either.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/175)*

**Comment by manishrjain** [comment]
:lgtm: Awesome. Feel free to submit.

---

Reviewed 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/175#-:-KQTSq38j4TDm3JiyJgb:b-jaxlov)*

**Pull request closed without merging**
