### PR TITLE
docs: Fix typos. Update backup policy section.

### PR DESCRIPTION
**Pull request by danielmai**
* Fix typos in upsert and deploy docs.
* Update backup policy section to link to docs for backups (enterprise feature) and data exports (open-source feature).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7088)

### CODE REVIEW

**Comment by anand-chandrashekar** [comment]
👍

**Review by OmarAyo — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7088)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Review by aaroncarey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7088)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai and @MichaelJCompton)

___
*[wiki/content/deploy/production-checklist.md, line 93 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7088#-MO3lnp8DGPXy1cB84UX:-MO3lnp978V-Oyt0uFKT:bprt15a) ([raw file](https://github.com/dgraph-io/dgraph/blob/c54d07647d14e86139ccc5fa7b08031d63747ac3/wiki/content/deploy/production-checklist.md#L93)):*
> ```
> corruption, or a system outage
> ```

**Review by danielmai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7088)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @aaroncarey, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/production-checklist.md, line 93 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7088#-MO3lnp8DGPXy1cB84UX:-MO3syn701aAchaisQ2A:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c54d07647d14e86139ccc5fa7b08031d63747ac3/wiki/content/deploy/production-checklist.md#L93)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> corruption, or a system outage
> ```

</blockquote></details>

Done.

**Pull request merged**
