### PR TITLE
docs: (new) Add documentation for count feature in GraphQL

### PR DESCRIPTION
**Pull request by bucanero**
Add count GraphQL aggregation
This PR adds a new article for the `count` aggregation feature in GraphQL

Fixes GRAPHQL-729

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)

 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-8711c6a673-105198.surge.sh)

### CODE REVIEW

**Review by vmrajas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

*[a discussion](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKET0Tg99senJgeLWKV:-MKET0Tg99senJgeLWKW:b5zjf6o) (no related file):*
We can also avoid writing the DataAggregateResult input type and the query format. Let's try to keep this page about Aggregation Queries similar to the flow of pattern of Search and Filtering (https://dgraph.io/docs/graphql/queries/search-filtering/). Both pages are about describing queries and it will be good to be consistent.

With request to naming of the document, we can do either of 2 things:
1. Either we can rename it as Count Queries.
2. We can keep the name as Aggregate Queries and mention about the other aggregate functions which will be added 
    later like Average, Sum .
I will prefer Approach 1. 

This page about Aggregation or Count should ideally come after Search and Filtering.

---
___
*[wiki/content/graphql/queries/aggregation.md, line 20 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKEQrKzESVf1sxW75VM:-MKEQrL-CQv0uIkUfkSf:b-g0pdmg) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L20)):*
> ```Markdown
> type Data {
> 	id: ID!
>     name: String!
> ```

The allignment of name field is wrong in the generated Docs preview.
___
*[wiki/content/graphql/queries/aggregation.md, line 25 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKES-El5sTo1BT_9XHX:-MKES-El5sTo1BT_9XHY:b83ai0q) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L25)):*
> ```Markdown
>  	metaData: [Data]
> }
> ```
> ```

The names of types and fields were written like this for simplicity in RFC. I believe it will be better to have more consistent names for Types and Fields like 'Author', 'Post' etc. as other GraphQL docs.
___
*[wiki/content/graphql/queries/aggregation.md, line 33 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKESORQ75WOZ65_6Egc:-MKESORQ75WOZ65_6Egd:b38c25s) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L33)):*
> ```Markdown
>   count: Int
>   ... 
>   ...
> ```

The ... part was meant to be for other aggregate queries. As currently only count is going to be added, we can remove this.
___
*[wiki/content/graphql/queries/aggregation.md, line 54 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKERGdb3fGtkYyMXYz-:-MKERGdb3fGtkYyMXYz0:bv7d403) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L54)):*
> ```Markdown
>     }
> }
> ```
> ```

The DQL query to which the GraphQL query gets rewritten to are implementation details. This should not be part of docs.
___
*[wiki/content/graphql/queries/aggregation.md, line 91 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKERpIT-SHPen9nu4sp:-MKERpIT-SHPen9nu4sq:bc6jccv) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L91)):*
> ```Markdown
>     }
> }
> ```
> ```

Remvoe this as the DQL query rewriting are internal details.
___
*[wiki/content/graphql/queries/aggregation.md, line 97 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKERe_e40dRYVcJy3K9:-MKERe_e40dRYVcJy3KA:buhs47s) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L97)):*
> ```Markdown
> This approach is similar to how aggregation queries are handled by other GraphQL providers.
> {{% /notice %}}
> ```

Remove this note. It was in RFC to show differences from the earlier approach.

**Review by bucanero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

*[a discussion](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKET0Tg99senJgeLWKV:-MKHkrni3amJAunO6eKL:b-auuxba) (no related file):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

We can also avoid writing the DataAggregateResult input type and the query format. Let's try to keep this page about Aggregation Queries similar to the flow of pattern of Search and Filtering (https://dgraph.io/docs/graphql/queries/search-filtering/). Both pages are about describing queries and it will be good to be consistent.

With request to naming of the document, we can do either of 2 things:
1. Either we can rename it as Count Queries.
2. We can keep the name as Aggregate Queries and mention about the other aggregate functions which will be added 
    later like Average, Sum .
I will prefer Approach 1. 

This page about Aggregation or Count should ideally come after Search and Filtering.


</blockquote></details>

Hi @vmrajas 
I renamed the article to "count queries", and also moved it after "search and filtering".

If you want to focus more on the aggregation queries, could you provide more query examples so I can use them to match a closer "style" like Search and filtering?

Let's talk on Slack so we can adjust these changes. Thanks!

---
___
*[wiki/content/graphql/queries/aggregation.md, line 20 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKEQrKzESVf1sxW75VM:-MKHZUP8240EZqV5LZlq:bt2vr1b) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L20)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

The allignment of name field is wrong in the generated Docs preview.
</blockquote></details>

Fixed.
___
*[wiki/content/graphql/queries/aggregation.md, line 33 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKESORQ75WOZ65_6Egc:-MKHZPnm4v0vgf-eW1qn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L33)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

The ... part was meant to be for other aggregate queries. As currently only count is going to be added, we can remove this.
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/aggregation.md, line 54 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKERGdb3fGtkYyMXYz-:-MKHYnZr-TONPS9PjAE8:bd5sh9a) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L54)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

The DQL query to which the GraphQL query gets rewritten to are implementation details. This should not be part of docs.
</blockquote></details>

Thanks for the feedback. DQL removed.
___
*[wiki/content/graphql/queries/aggregation.md, line 91 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKERpIT-SHPen9nu4sp:-MKHYtLw0gfTQfUPWK-j:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L91)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Remvoe this as the DQL query rewriting are internal details.
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/aggregation.md, line 97 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKERe_e40dRYVcJy3K9:-MKHYk1k04G9ek-7a4v0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L97)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Remove this note. It was in RFC to show differences from the earlier approach.
</blockquote></details>

Done.

**Review by bucanero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/aggregation.md, line 25 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKES-El5sTo1BT_9XHX:-MKHno1GDcIn7cLVgmXT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9fafe51935e685841a32056735ad6587714c673d/wiki/content/graphql/queries/aggregation.md#L25)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

The names of types and fields were written like this for simplicity in RFC. I believe it will be better to have more consistent names for Types and Fields like 'Author', 'Post' etc. as other GraphQL docs.
</blockquote></details>

Done.

**Review by vmrajas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

*[a discussion](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKET0Tg99senJgeLWKV:-MKeXvMJBfHlKUpBnHLh:bbzumo4) (no related file):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

Hi @vmrajas 
I renamed the article to "count queries", and also moved it after "search and filtering".

If you want to focus more on the aggregation queries, could you provide more query examples so I can use them to match a closer "style" like Search and filtering?

Let's talk on Slack so we can adjust these changes. Thanks!
</blockquote></details>

Its good to see that you have changed the example schema. I have provided some examples of the query on slack.

---

**Review by vmrajas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/count.md, line 11 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKjuXG26aHzoapIjv2F:-MKjuXG26aHzoapIjv2G:bev4hf4) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8fa315b9cea0205c2a935e524ad4f927d0b39ee/wiki/content/graphql/queries/count.md#L11)):*
> ```Markdown
> In this article you'll learn how to use GraphQL queries to aggregate data from a Dgraph database.
> 
> Dgraph automatically generates count queries for a given GraphQL schema, enabling you to `count` on predicates, edges, and other aggregation fields.
> ```

enabling you to `count` on predicates, edges and to count nodes satisfying certain criteria specified using a filter.
___
*[wiki/content/graphql/queries/count.md, line 33 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKjup0YCLogzi-1aeG0:-MKjup0YCLogzi-1aeG1:bik0kx) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8fa315b9cea0205c2a935e524ad4f927d0b39ee/wiki/content/graphql/queries/count.md#L33)):*
> ```
> ```graphql
> type Post {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

>     id: ID!
>     title: String!
>     body: String
>     score: Int
</details>
> }
> type Author {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

>     id: ID!
>     name: String!
>     reputation: [Int]
>     posts: [Post]
</details>
> }
> ```
> ```
Remove this type description as it is not there in other docs.
___
*[wiki/content/graphql/queries/count.md, line 37 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKjv3OD8AZy0glvK2BM:-MKjv3OD8AZy0glvK2BN:b4ds08t) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8fa315b9cea0205c2a935e524ad4f927d0b39ee/wiki/content/graphql/queries/count.md#L37)):*
> ```Markdown
> #### Examples
> 
> 1. Root count query without a filter:
> ```

No need to have numbering in examples. Can we follow the same pattern of description and query as https://dgraph.io/docs/graphql/queries/search-filtering/

**Review by bucanero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @vmrajas)

___
*[wiki/content/graphql/queries/count.md, line 11 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKjuXG26aHzoapIjv2F:-MKkeT0j8vsC0K5ielB1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8fa315b9cea0205c2a935e524ad4f927d0b39ee/wiki/content/graphql/queries/count.md#L11)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

enabling you to `count` on predicates, edges and to count nodes satisfying certain criteria specified using a filter.
</blockquote></details>

Done.
___
*[wiki/content/graphql/queries/count.md, line 33 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKjup0YCLogzi-1aeG0:-MKkervw6woaS1T32sUB:b-21vmrp) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8fa315b9cea0205c2a935e524ad4f927d0b39ee/wiki/content/graphql/queries/count.md#L33)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

> ```
> ```graphql
> type Post {
>     id: ID!
>     title: String!
>     body: String
>     score: Int
> }
> type Author {
>     id: ID!
>     name: String!
>     reputation: [Int]
>     posts: [Post]
> }
> ```
> ```
Remove this type description as it is not there in other docs.
</blockquote></details>

Done. Removed type definitions.
___
*[wiki/content/graphql/queries/count.md, line 37 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKjv3OD8AZy0glvK2BM:-MKkf-j09su5vmwjrER2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8fa315b9cea0205c2a935e524ad4f927d0b39ee/wiki/content/graphql/queries/count.md#L37)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

No need to have numbering in examples. Can we follow the same pattern of description and query as https://dgraph.io/docs/graphql/queries/search-filtering/
</blockquote></details>

Done.

**Review by vmrajas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6770)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/count.md, line 9 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKp-nxnAb1S1njd29iA:-MKp-nxnAb1S1njd29iB:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/97a868034ecf09313d5968723026967de4eaf049/wiki/content/graphql/queries/count.md#L9)):*
> ```Markdown
> +++
> 
> In this article you'll learn how to use GraphQL queries to aggregate data from a Dgraph database.
> ```

Remove this.
___
*[wiki/content/graphql/queries/count.md, line 46 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6770#-MKp-hSu4yUazoW-a3tn:-MKp-hSu4yUazoW-a3to:bs64z6e) ([raw file](https://github.com/dgraph-io/dgraph/blob/97a868034ecf09313d5968723026967de4eaf049/wiki/content/graphql/queries/count.md#L46)):*
> ```Markdown
> ### Count for a child
> 
> Besides the `aggregate<type name>` query, Dgraph defines `aggregate_<predicate_name>` fields inside `query<type name>` queries, allowing you to do a `count` of predicate edges and other aggregation fields.
> ```

`count` of predicate edges.

**Pull request merged**
