### PR TITLE
Chore(backups): Consolidate the backup manifests

### PR DESCRIPTION
**Pull request by ahsanbarkati**
Before this change, the new backup manifest was created for each backup (i.e. for each full or incremental backup).
After this change, we will have only one backup manifest, which will contain information about all the backups. This 
change is backwards compatible. For the older backup directories, when a new backup will be taken then all the 
manifests will be consolidated and a master manifest will be written.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7506)

### CODE REVIEW

**Review by manishrjain — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-:-MUnrTd5Ag9gwtZYjic0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ahsanbarkati and @vvbalaji-dgraph)

___
*[worker/file_handler.go, line 433 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUnqUya394Bfp-iqz7N:-MUnqUya394Bfp-iqz7O:b-u8k5kz) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28d98d434650313b32bd14cb81c58861528b53e/worker/file_handler.go#L433)):*
> ```Go
> }
> 
> func (h *fileHandler) getConsolidatedManifest(uri *url.URL) (*MasterManifest, error) {
> ```

Add a comment and just keep it here.

**Review by NamanJain8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7506)* status: 10 of 13 files reviewed, 9 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, and @vvbalaji-dgraph)

___
*[systest/backup/encryption/backup_test.go, line 299 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrEHe61QgdLmqaRDbs:-MUrEHe61QgdLmqaRDbt:bqhr1a3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1b4c437076ff892d3899bec5fbc375e7fcff121/systest/backup/encryption/backup_test.go#L299)):*
> ```Go
> 	manifests := x.WalkPathFunc(backupDir, func(path string, isdir bool) bool {
> 		return !isdir && strings.Contains(path, "manifest.json")
> 	})
> ```

Add a check here for number of backups.
___
*[worker/backup_handler.go, line 50 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrNsU65Xya_20nNDr2:-MUrNsU65Xya_20nNDr3:bhl44vn) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/backup_handler.go#L50)):*
> ```Go
> 	// "since" is the read timestamp used at the backup request. This value is called "since"
> 	// because it used by subsequent incremental backups.
> 	// "groups" are the group IDs that participated.
> ```

Update the description.
___
*[worker/backup_handler.go, line 67 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrG1o2ANMGVV4aS9Dx:-MUrG1o2ANMGVV4aS9Dy:b-ekmdp6) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/backup_handler.go#L67)):*
> ```Go
> 
> 	// GetManifest returns the master manifest, containing information about all the
> 	// backups. If the backup directory is using old formats of manifests, then it will
> ```

mention old ==  < 21.03 
___
*[worker/backup_handler.go, line 84 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrGDvK32bbjiZdwlmP:-MUrGDvK32bbjiZdwlmQ:bb7phvt) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/backup_handler.go#L84)):*
> ```Go
> 	CreateBackupFile(*url.URL, *pb.BackupRequest) error
> 
> 	// CreateManifest writes the creates the given manifest.
> ```

typo
___
*[worker/file_handler.go, line 189 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrIdbK-3aKPyWyZc5I:-MUrIdbK-3aKPyWyZc5J:b-f1bsgc) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/file_handler.go#L189)):*
> ```Go
> 
> 	var manifest MasterManifest
> 	path := filepath.Join(uri.Path, backupManifest)
> ```

Maybe refactored with the above code in GetManifest()
___
*[worker/file_handler.go, line 233 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrKJdt1U6_bEH1AAz4:-MUrKJdt1U6_bEH1AAz5:by2hh95) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/file_handler.go#L233)):*
> ```Go
> 
> 		path := manifests[i].Path
> 		path = filepath.Join(uri.Path, path)
> ```

Make it in single line
___
*[worker/s3_handler.go, line 167 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrO6Mj0HcL-x07KKgC:-MUrO6Mj0HcL-x07KKgD:bejdshz) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/s3_handler.go#L167)):*
> ```Go
> 			return errors.Wrap(err, "CreateManifest failed to create dstInfo")
> 		}
> 		if err := h.mc.CopyObject(dst, src); err != nil {
> ```

Please check if this is atomic. If it is not, we would need to manually move temporary manifest -> masterManifest.
Add a comment and retries?
___
*[worker/s3_handler.go, line 224 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrNkey-osjGGpXkCu7:-MUrNkey-osjGGpXkCu8:b-4fns8v) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/s3_handler.go#L224)):*
> ```Go
> 		if err := h.readMasterManifest(&manifest); err != nil {
> 			return nil, errors.Wrap(err, "Get manifests failed: ")
> 		}
> ```

Refactor this as well. Don't we need filtering here as we do in file_handler?

**Review by jarifibrahim — COMMENTED** [review]
Got some minor comments. We still have to deal with case when the copy of the temp file to the master manifest file fails.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-:-MUs48ovDBtqdAWbm5Mw:b3bbvfd)* status: 4 of 13 files reviewed, 17 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, and @vvbalaji-dgraph)

___
*[worker/backup_handler.go, line 71 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs3P__--37NrZwfqU4:-MUs3P_a6TAiRBTaxawG:bdase9s) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/backup_handler.go#L71)):*
> ```Go
> 	GetManifest(*url.URL) (*MasterManifest, error)
> 
> 	// GetManifests returns the list of manfiests for the given backup series ID
> ```

manfiests => manifests
___
*[worker/file_handler.go, line 130 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs3iG05HfPq-U579c-:-MUs3iG05HfPq-U579c0:b818e4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/file_handler.go#L130)):*
> ```Go
> 	// Move the tmpManifest to backupManifest
> 	path := filepath.Join(uri.Path, backupManifest)
> 	if err = os.Rename(tmpPath, path); err != nil {
> ```

return os.Rename ...
___
*[worker/file_handler.go, line 147 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs3mG1-ZDAPG6FE61v:-MUs3mG1-ZDAPG6FE61w:bew1y4o) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/file_handler.go#L147)):*
> ```Go
> 		return nil, errors.Wrap(err, "GetManifest failed to get consolidated manifest: ")
> 	}
> 	return manifest, nil
> ```

return manifest, errors.Wrap(err, "GetManifest failed to get consolidated manifest: ")
___
*[worker/s3_handler.go, line 138 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs28UD-lCXL11eFZpz:-MUs28UD-lCXL11eFZq-:b-vf7fe2) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L138)):*
> ```Go
> 		// A new handler is required to create the temporary manifest and then wait for the
> 		// upload to be completed. Close() waits for the upload to finish.
> 		tmpHandler, err := NewS3Handler(uri, h.creds)
> ```

You don't need to create a new handler.
___
*[worker/s3_handler.go, line 144 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2FquEmbF3QSNJIte:-MUs2FquEmbF3QSNJItf:b1rty1g) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L144)):*
> ```Go
> 		tmpHandler.createObject(tmpHandler.mc, tmpManifest)
> 		if err := json.NewEncoder(tmpHandler).Encode(manifest); err != nil {
> 			return err
> ```

wrap err
___
*[worker/s3_handler.go, line 165 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2C9u0A8ghoMOkPiC:-MUs2C9u0A8ghoMOkPiD:b-1gj4m2) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L165)):*
> ```Go
> 			return errors.Wrap(err, "CreateManifest failed to remove temporary manifest")
> 		}
> 	}
> ```

return nil
___
*[worker/s3_handler.go, line 168 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2DWb4yxnGshlivNP:-MUs2DWb4yxnGshlivNQ:b1rty1g) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L168)):*
> ```Go
> 	h.createObject(h.mc, backupManifest)
> 	if err := json.NewEncoder(h).Encode(manifest); err != nil {
> 		return err
> ```

wrap err
___
*[worker/s3_handler.go, line 181 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2hXw5W6acWlY16KS:-MUs2hXw5W6acWlY16KT:b-yqb5y3) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L181)):*
> ```Go
> 		errors.Wrap(err, "GetManifest failed to get consolidated manifests: ")
> 	}
> 	return manifest, nil
> ```

return manifest, errors.Wrap(err, "GetManifest failed to get consolidated manifests: ")

**Review by jarifibrahim — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-:-MUx1TpV6L-1QtEahNgM:bnfp4nl)* status: 4 of 13 files reviewed, 17 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, and @vvbalaji-dgraph)

___
*[worker/backup_handler.go, line 71 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs3P__--37NrZwfqU4:-MUx15C21yA_3k3RvVpf:b-2fc8k4) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/backup_handler.go#L71)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

manfiests => manifests
</blockquote></details>

manfests => manifest

**Review by ahsanbarkati — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7506)* status: 4 of 13 files reviewed, 17 unresolved discussions (waiting on @ahsanbarkati, @jarifibrahim, @manishrjain, @NamanJain8, and @vvbalaji-dgraph)

___
*[systest/backup/encryption/backup_test.go, line 299 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrEHe61QgdLmqaRDbs:-MUx1OVf9dqr9AEOnu4x:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1b4c437076ff892d3899bec5fbc375e7fcff121/systest/backup/encryption/backup_test.go#L299)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Add a check here for number of backups.
</blockquote></details>

Done.
___
*[worker/backup_handler.go, line 50 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrNsU65Xya_20nNDr2:-MUx1Q7uDfWJkAv4X_sY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/backup_handler.go#L50)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Update the description.
</blockquote></details>

Done.
___
*[worker/backup_handler.go, line 67 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrG1o2ANMGVV4aS9Dx:-MUx1QUi69KeU3UlLI8S:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/backup_handler.go#L67)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

mention old ==  < 21.03 
</blockquote></details>

Done.
___
*[worker/backup_handler.go, line 84 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrGDvK32bbjiZdwlmP:-MUx1RfbEYkXVPy3vmLD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/backup_handler.go#L84)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[worker/backup_handler.go, line 71 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs3P__--37NrZwfqU4:-MUx1RL4EsmTF8hQSYyi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/backup_handler.go#L71)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

manfiests => manifests
</blockquote></details>

Done.
___
*[worker/file_handler.go, line 189 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrIdbK-3aKPyWyZc5I:-MUx1WTVCYUTATEGqABq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/file_handler.go#L189)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Maybe refactored with the above code in GetManifest()
</blockquote></details>

Done.
___
*[worker/file_handler.go, line 233 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrKJdt1U6_bEH1AAz4:-MUx1X4y62rEQObXtnZs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/file_handler.go#L233)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Make it in single line
</blockquote></details>

Done.
___
*[worker/file_handler.go, line 130 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs3iG05HfPq-U579c-:-MUx1STF5R_Ll9i4Tn9v:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/file_handler.go#L130)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

return os.Rename ...
</blockquote></details>

Done.
___
*[worker/s3_handler.go, line 224 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUrNkey-osjGGpXkCu7:-MUx1szf8WsfmCYrWLG_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c1e80297386c1819fb71a4cc1aa5dc5687cedc6b/worker/s3_handler.go#L224)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Refactor this as well. Don't we need filtering here as we do in file_handler?
</blockquote></details>

Done.
___
*[worker/s3_handler.go, line 138 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs28UD-lCXL11eFZpz:-MUx1luU1CNPpTtqFHNK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L138)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

You don't need to create a new handler.
</blockquote></details>

Done.
___
*[worker/s3_handler.go, line 144 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2FquEmbF3QSNJIte:-MUx1mqN88ZNROfGV4Qa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L144)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

wrap err
</blockquote></details>

Done.
___
*[worker/s3_handler.go, line 165 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2C9u0A8ghoMOkPiC:-MUx1qqw9bKCn6jX9dvn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L165)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

return nil
</blockquote></details>

Done.
___
*[worker/s3_handler.go, line 168 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2DWb4yxnGshlivNP:-MUx1rBkDDMJHTB2wrPD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L168)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

wrap err
</blockquote></details>

Done.
___
*[worker/s3_handler.go, line 181 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7506#-MUs2hXw5W6acWlY16KS:-MUx1rV2Euj6OH0IZTBP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f34375d0bede91700e008064042976acd5ef7b83/worker/s3_handler.go#L181)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

return manifest, errors.Wrap(err, "GetManifest failed to get consolidated manifests: ")
</blockquote></details>

Done.

**Pull request merged**
