### PR TITLE
feat(flags): Add query timeout as a limit config

### PR DESCRIPTION
**Pull request by rohanprasad**
In the case of a multi-tenant environment, long-running queries by tenants can consume all the resources, starving the request from other tenants. The change adds query-timeout as a config which will be applied to all the query requests sent without timeout param.

Fixes DGRAPH-3184

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7599)

### CODE REVIEW

**Review by ahsanbarkati — APPROVED** [review]
Looks good.

**Review by ahsanbarkati — CHANGES_REQUESTED** [review]
Actually, setting 500ms as timeout is causing various tests to fail.

**Review by NamanJain8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7599)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jarifibrahim and @rohanprasad)

___
*[dgraph/cmd/alpha/http.go, line 137 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7599#-MW3KkH1CfdVNJcRNAsX:-MW3KkH1CfdVNJcRNAsY:b-82q9ub) ([raw file](https://github.com/dgraph-io/dgraph/blob/b04579c4878f82e7a8bec15e91ce5be2b189de3b/dgraph/cmd/alpha/http.go#L137)):*
> ```Go
> // parses it into time.Duration, empty string is converted into zero value
> func parseDuration(r *http.Request, name string, defaultVal time.Duration) (time.Duration, error) {
> 	value := r.URL.Query().Get(name)
> ```

I think we want to over-ride the query timeout set by the user if it is greater than the default value in a multi-tenant setup. @rohanprasad can you confirm this please?
___
*[dgraph/cmd/alpha/http.go, line 162 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7599#-MW3KeSXBKBxvV_1aYqW:-MW3KeSYEwDXo72Kt_0L:b-yg01h5) ([raw file](https://github.com/dgraph-io/dgraph/blob/b04579c4878f82e7a8bec15e91ce5be2b189de3b/dgraph/cmd/alpha/http.go#L162)):*
> ```Go
> 		return
> 	}
> 	queryTimeout, err := parseDuration(r, "timeout", x.Config.QueryTimeout)
> ```

This will timeout the query made via HTTP endpoint `/query`. But the queries made via GRPC (see `Server.Query`) will not timeout. 
I think in a multi-tenant system it will be useful to have a timeout there as well.

**Review by rohanprasad — COMMENTED** [review]
Default set to 0

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7599#-:-MW98LJN46wmN54xYiIA:b-nsg4zn)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jarifibrahim, @NamanJain8, and @rohanprasad)

___
*[dgraph/cmd/alpha/http.go, line 137 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7599#-MW3KkH1CfdVNJcRNAsX:-MW98XQS5sSLA7ks41fY:b271ud1) ([raw file](https://github.com/dgraph-io/dgraph/blob/b04579c4878f82e7a8bec15e91ce5be2b189de3b/dgraph/cmd/alpha/http.go#L137)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

I think we want to over-ride the query timeout set by the user if it is greater than the default value in a multi-tenant setup. @rohanprasad can you confirm this please?
</blockquote></details>

Confirmed, we don't want to override if the timeout is set by the user
___
*[dgraph/cmd/alpha/http.go, line 162 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7599#-MW3KeSXBKBxvV_1aYqW:-MW98kl5-plmph2A1T8Q:bebrt1w) ([raw file](https://github.com/dgraph-io/dgraph/blob/b04579c4878f82e7a8bec15e91ce5be2b189de3b/dgraph/cmd/alpha/http.go#L162)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

This will timeout the query made via HTTP endpoint `/query`. But the queries made via GRPC (see `Server.Query`) will not timeout. 
I think in a multi-tenant system it will be useful to have a timeout there as well.
</blockquote></details>

Will do

**Review by NamanJain8 — COMMENTED** [review]
Looks good to me.

**Review by jarifibrahim — APPROVED** [review]

**Pull request merged**
