### PR TITLE
Count filter at root

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/691)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/schema_scalar, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfArh-LACKQErG0Z7iQ:-KfArh-NuwHyum4gfxXU:bam8bwe) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/cmd/dgraph/schema_scalar#L1)):*
> ```
> scalar (
> ```

scalar should also go away.
can you rebase on master ?

---

*[gql/parser.go, line 955 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfExBPG0HuTi0M5MIJQ:-KfExBPHDdSuJHU-Q1Fz:b-77afle) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser.go#L955)):*
> ```Go
> 		buf.WriteString("NOT")
> 	default:
> 		x.Errorf("Unknown operator: %q", t.Op)
> ```

return ?
or should write to buffer : `unknown operator`

---

*[gql/parser.go, line 1403 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfF-Umy4KjV0v49FrH-:-KfF-Umy4KjV0v49FrH0:bp90odt) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser.go#L1403)):*
> ```Go
> 				return gq, err
> 			}
> 			/*
> ```

where will this be tested now ?

---

*[gql/parser_test.go, line 1135 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEy9bTnxm5jPUQ079U:-KfEy9bUjnvSpThnNvnM:b-14ajbk) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser_test.go#L1135)):*
> ```Go
> 	require.NotNil(t, res.Query[0].Func)
> 	require.Equal(t, []string{"friends", "hometown"}, childAttrs(res.Query[0]))
> 	require.Equal(t, []string{"name"}, childAttrs(res.Query[0].Children[0]))
> ```

what are we testing here ? 
Query[0].Func ?
Should we test that its name is `gt` and more ?

---

*[query/query_test.go, line 473 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEyRNSFJtylBKc0RU9:-KfEyRNSFJtylBKc0RUA:b-a0jrua) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/query/query_test.go#L473)):*
> ```Go
> 	query := `
>     {
> 			me(func: gt(count(friend), 2)) {
> ```

tabs and spaces formatting.. 

---

*[query/query_test.go, line 488 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEyOZKX-9dS6yx71wL:-KfEyOZLp_L1FleSJrq-:b-a0jrua) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/query/query_test.go#L488)):*
> ```Go
> 	query := `
>     {
> 			me(func: geq(count(friend), 1)) {
> ```

tabs and spaces formatting.. 

---

*[worker/task.go, line 390 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEykaMjJPJ1vJtYUDh:-KfEykaMjJPJ1vJtYUDi:bys526u) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L390)):*
> ```Go
> 			pl, decr := posting.GetOrCreate(key, gid)
> 			count := int64(pl.Length(0))
> 			decr()
> ```

we are using `pl` below and `decr()` before that..

---

*[worker/task.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfF-KjCcvZ-g5NqAaKD:-KfF-KjCcvZ-g5NqAaKE:b-ot5prc) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L395)):*
> ```Go
> 				x.AssertTruef(pk.IsData() && pk.Attr == q.Attr,
> 					"Invalid key obtained for comparison")
> 				fmt.Println(pk.Uid, pk.Attr, pl.Uids(opts))
> ```

should we use `log` ?

---

*[worker/task.go, line 397 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfF-CDS1VTuxKXAaDcC:-KfF-CDS1VTuxKXAaDcD:b-m1xqqe) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L397)):*
> ```Go
> 				fmt.Println(pk.Uid, pk.Attr, pl.Uids(opts))
> 				tlist := &task.List{[]uint64{pk.Uid}}
> 				out.UidMatrix = append(out.UidMatrix, tlist)
> ```

will it be better if we insert all uids in one list and put that list in uidMatrix ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/691)*

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1405 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFDqP5eqcyJmZ--RKA:-KfFDqP5eqcyJmZ--RKB:b-zfk101) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser.go#L1405)):*
> ```Go
> 			/*
> 				if !schema.State().IsIndexed(gen.Attr) {
> 					return nil, x.Errorf(
> ```

Delete this code.

---

*[worker/task.go, line 214 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFEvVP0WeqFsVSYHip:-KfFEvVP0WeqFsVSYHiq:b-yknwhc) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L214)):*
> ```Go
> 			isCompareAtRoot = true
> 		} else {
> 			n = len(q.Uids.Uids)
> ```

Bad naming, find some better naming for this.

---

*[worker/task.go, line 386 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFGArI_A8FXsNslQlX:-KfFGArI_A8FXsNslQlY:b-9hyk5u) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L386)):*
> ```Go
> 		dataPrefix := pk.DataPrefix()
> 
> 		for it.Seek(dataPrefix); it.ValidForPrefix(dataPrefix); it.Next() {
> ```

Create a new posting.Iterate function, which can give us the posting list. We should not store these posting lists in lhmap; only do getter ops on it.

---

*[worker/task.go, line 392 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFGXyBmSkgAhpp0y1a:-KfFGXyCa3WR15ci_Rjp:bv2oznn) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L392)):*
> ```Go
> 			decr()
> 			if EvalCompare(f, count, threshold) {
> 				pk := x.Parse(key)
> ```

This should be at the top, in the for loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/691)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[gql/parser.go, line 955 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfExBPG0HuTi0M5MIJQ:-KfFdBzcK60VXjIQGdfe:bnlg2ux) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser.go#L955)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

return ?
or should write to buffer : `unknown operator`
</blockquote></details>

Made it Fatal.

---

*[gql/parser.go, line 1403 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfF-Umy4KjV0v49FrH-:-KfFdEHaDQi1quXtd1OV:bcdn6pi) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser.go#L1403)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

where will this be tested now ?
</blockquote></details>

Will be tested while execution due to changes in schema.

---

*[gql/parser.go, line 1405 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFDqP5eqcyJmZ--RKA:-KfFdJ_elRCeY8F_sx5r:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser.go#L1405)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Delete this code.
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 1135 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEy9bTnxm5jPUQ079U:-KfFe0eECFoQGAvfW6Cp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/gql/parser_test.go#L1135)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

what are we testing here ? 
Query[0].Func ?
Should we test that its name is `gt` and more ?
</blockquote></details>

Done.

---

*[query/query_test.go, line 473 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEyRNSFJtylBKc0RU9:-KfFf1n77S-mAoIZwHVi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/query/query_test.go#L473)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

tabs and spaces formatting.. 
</blockquote></details>

Done.

---

*[query/query_test.go, line 488 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEyOZKX-9dS6yx71wL:-KfFf1U6bCaeSEnOeW0T:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/query/query_test.go#L488)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

tabs and spaces formatting.. 
</blockquote></details>

Done.

---

*[worker/task.go, line 214 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFEvVP0WeqFsVSYHip:-KfFfv4bMmLo_Mt3L5fm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L214)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Bad naming, find some better naming for this.
</blockquote></details>

Done.

---

*[worker/task.go, line 386 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFGArI_A8FXsNslQlX:-KfFlDa3nwJPlDjumqEK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L386)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a new posting.Iterate function, which can give us the posting list. We should not store these posting lists in lhmap; only do getter ops on it.
</blockquote></details>

Done.

---

*[worker/task.go, line 390 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfEykaMjJPJ1vJtYUDh:-KfFe4n9rxPohWOXtGet:b32n8ta) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L390)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

we are using `pl` below and `decr()` before that..
</blockquote></details>

Removed it.

---

*[worker/task.go, line 392 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfFGXyBmSkgAhpp0y1a:-KfFeDkFQSixTDKd4Vgk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L392)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should be at the top, in the for loop.
</blockquote></details>

Done.

---

*[worker/task.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfF-KjCcvZ-g5NqAaKD:-KfFeET6oXat5hAbUREU:bss4a2b) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L395)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

should we use `log` ?
</blockquote></details>

Removed.

---

*[cmd/dgraph/schema_scalar, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfArh-LACKQErG0Z7iQ:-KfFcwmcxIyDrCviPZGu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/cmd/dgraph/schema_scalar#L1)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

scalar should also go away.
can you rebase on master ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/691)*

**Comment by ashishnegi** [comment]
:lgtm: just one comment.

---

Review status: 0 of 10 files reviewed at latest revision, 14 unresolved discussions.

---

*[posting/lists.go, line 419 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfG4CE6ge7GUlMNoR1d:-KfG4CE7XMtHHAQCVpds:bt8e8qk) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7578b500cb547da679e4e6da3ca0478114de5be/posting/lists.go#L419)):*
> ```Go
> 	defer stopTheWorld.RUnlock()
> 
> 	lp, _ := lhmap.Get(fp)
> ```

ignoring second argument ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-:-KfG6QG-ewIL05IRcB60:b-nngxwy)*

**Comment by ashwin95r** [comment]
Review status: 0 of 10 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 419 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfG4CE6ge7GUlMNoR1d:-KfJVXpFO6JkbG4gFY9D:bqwmebs) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7578b500cb547da679e4e6da3ca0478114de5be/posting/lists.go#L419)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

ignoring second argument ?
</blockquote></details>

lp != nil and the second argument are the same. We're using it this way at GetOrCreate. So keeping it consistent.

---

*[worker/task.go, line 397 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfF-CDS1VTuxKXAaDcC:-KfJUdVw-VYgrbA4grFX:b5mdhbw) ([raw file](https://github.com/dgraph-io/dgraph/blob/18f9fc0f4f556da42e1e7b627a45f90b7d3aff96/worker/task.go#L397)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

will it be better if we insert all uids in one list and put that list in uidMatrix ?
</blockquote></details>

Yeah, that'd have the same effect, but this would keep the logic consistent, as we already do it in query package for other of functions. Adding a TODO, if we want to look at this later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/691)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 9 of 11 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 419 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfG4CE6ge7GUlMNoR1d:-KfL-cx1YhOUDbcsjYm1:b180uvk) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7578b500cb547da679e4e6da3ca0478114de5be/posting/lists.go#L419)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

lp != nil and the second argument are the same. We're using it this way at GetOrCreate. So keeping it consistent.
</blockquote></details>

Remove ok from lhmap.Get then.

---

*[posting/lists.go, line 414 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfL-FQE9ZxCzLsgjHpr:-KfL-FQE9ZxCzLsgjHps:bb25rv7) ([raw file](https://github.com/dgraph-io/dgraph/blob/6a418446d756805b7ef9c63016d011a6a8daefe8/posting/lists.go#L414)):*
> ```Go
> // updated value and returns it if it exists or it unmarshals the value passed and returns
> // the list.
> func GetOrUnmarshal(key []byte, itVal []byte, group uint32) (rlist *List, decr func()) {
> ```

key, val []byte, .. You don't need group.

---

*[posting/lists.go, line 418 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfL-Sgkz6O7oc4zfhGg:-KfL-Sgkz6O7oc4zfhGh:b-ctumyd) ([raw file](https://github.com/dgraph-io/dgraph/blob/6a418446d756805b7ef9c63016d011a6a8daefe8/posting/lists.go#L418)):*
> ```Go
> 
> 	stopTheWorld.RLock()
> 	defer stopTheWorld.RUnlock()
> ```

Move this out of this func, including the lhmap.Get(..). Or unlock it after the Get.

---

*[posting/lists.go, line 431 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfL013vubJ0tMvqq3zX:-KfL013vubJ0tMvqq3zY:brk96lo) ([raw file](https://github.com/dgraph-io/dgraph/blob/6a418446d756805b7ef9c63016d011a6a8daefe8/posting/lists.go#L431)):*
> ```Go
> 	// to the map, any other goroutine can retrieve it.
> 	lp = getNew(key, pstore) // This retrieves a new *List and sets refcount to 1.
> 	lp.water = marks.Get(group)
> ```

Remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-:-KfL1OcF_Asa9K0l8a94:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 419 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfG4CE6ge7GUlMNoR1d:-KfL517zS5EMqiV0sY3h:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7578b500cb547da679e4e6da3ca0478114de5be/posting/lists.go#L419)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove ok from lhmap.Get then.
</blockquote></details>

Done.

---

*[posting/lists.go, line 414 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfL-FQE9ZxCzLsgjHpr:-KfL50UiQRDow4UnxHOg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6a418446d756805b7ef9c63016d011a6a8daefe8/posting/lists.go#L414)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

key, val []byte, .. You don't need group.
</blockquote></details>

Done.

---

*[posting/lists.go, line 418 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfL-Sgkz6O7oc4zfhGg:-KfL45ao5yVcatWLCZbI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6a418446d756805b7ef9c63016d011a6a8daefe8/posting/lists.go#L418)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this out of this func, including the lhmap.Get(..). Or unlock it after the Get.
</blockquote></details>

Done.

---

*[posting/lists.go, line 431 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/691#-KfL013vubJ0tMvqq3zX:-KfL51pv8OJuIcJcmkqc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6a418446d756805b7ef9c63016d011a6a8daefe8/posting/lists.go#L431)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/691)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
