### PR TITLE
Support multiple queries in one block.

### PR DESCRIPTION
**Pull request by ashwin95r**
Supports:
```
{
      me(anyof("name", "Michonne")) {
        name
        gender
      }

      you(anyof("name", "Andrea")) {
        name
      }
}
Result: 
{"me":[{"gender":"female","name":"Michonne"}], "you":[{"name":"Andrea"}]}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/474)

### CODE REVIEW

**Comment by jchiu0** [comment]
:lgtm: Two small comments.

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 344 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-KaGcCgzCp0PAOtw5US-:-KaGcCh-Dl_-bmZm6Jak:b-wxozh5) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a4fb74c6a9f7f81d54bba5c36cadbe1e09b8434/gql/parser.go#L344)):*
> ```Go
> 
> 	if len(res.Query) != 0 {
> 		for _, qu := range res.Query {
> ```

Looks like two queries can share the same fragment. Maybe add a simple fragment test with two queries?

---

*[gql/parser_test.go, line 51 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-KaGc4Wv3_y4XdROwNBu:-KaGc4Wv3_y4XdROwNBv:b-b1g64t) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a4fb74c6a9f7f81d54bba5c36cadbe1e09b8434/gql/parser_test.go#L51)):*
> ```Go
> 	require.NotNil(t, res.Query)
> 	require.Equal(t, 2, len(res.Query))
> 	//require.Equal(t, childAttrs(res.Query), []string{"friends", "gender", "age", "hometown"})
> ```

Stray comments? Or maybe you want to test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-:-KaGcKMmvTRQUsVGNUGK:bgzraxq)*

**Comment by ashwin95r** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 344 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-KaGcCgzCp0PAOtw5US-:-Kaa7iqzSCBTOZ_mBU7X:bjkro48) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a4fb74c6a9f7f81d54bba5c36cadbe1e09b8434/gql/parser.go#L344)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Looks like two queries can share the same fragment. Maybe add a simple fragment test with two queries?
</blockquote></details>

Added the test in the other PR. Done.

---

*[gql/parser_test.go, line 51 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-KaGc4Wv3_y4XdROwNBu:-Kaa7x8DxEbH8z0PJZ3s:bwni1om) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a4fb74c6a9f7f81d54bba5c36cadbe1e09b8434/gql/parser_test.go#L51)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Stray comments? Or maybe you want to test?
</blockquote></details>

Removed the comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/474)*

**Comment by ashishnegi** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-KaeScu0xMQLsyqSEMGI:-KaeScu1UvcnzdE8KnKU:b-99tmbz) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a4fb74c6a9f7f81d54bba5c36cadbe1e09b8434/gql/parser.go#L107)):*
> ```Go
> // DebugPrint is useful for debugging.
> func (gq *GraphQuery) DebugPrint(prefix string) {
> 	fmt.Printf("%s[%x %q %q->%q]\n", prefix, gq.UID, gq.Attr, gq.Alias)
> ```

why we moved from `x` to `fmt` ?
i thought x would the work based on environment.

---

*[gql/parser.go, line 343 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-KaeTC5iBZwG2r-Bt-iV:-KaeTC5iBZwG2r-Bt-iW:b-csuqae) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a4fb74c6a9f7f81d54bba5c36cadbe1e09b8434/gql/parser.go#L343)):*
> ```Go
> 	}
> 
> 	if len(res.Query) != 0 {
> ```

do we need `len` check if we are doing a `range` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/474)*

**Comment by ashishnegi** [comment]
:lgtm:  just small comments ; 
also, do not see any tofastjson changes yet. but would be easier to port.

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-:-KaeUg6RdjO8EFlVa8po:b-vzqvy3)*

**Comment by ashwin95r** [comment]
Hey @ashishnegi, it's in the other PR https://reviewable.io/reviews/dgraph-io/dgraph/490#-. Thanks!

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/474#-:-KaeWwXDyR0DYc54_Bgj:b3e0zi7)*

**Comment by ashwin95r** [comment]
Continued in #490.

**Pull request closed without merging**
