### PR TITLE
Feature/resultcount

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/147)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[task.fbs, line 9 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF5Rzw8kBPr-7qDfLH:-KOF5Rzw8kBPr-7qDfLI:-181827938) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/task.fbs#L9)):*
> ```
> 	offset:int;
> 	afterUid:ulong;
> 	isCount:ushort;
> ```

`getCount` is more appropriate here.

---

*[query/query.go, line 203 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF5d5i8VFCPv1bv-7F:-KOF5d5i8VFCPv1bv-7G:736918283) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L203)):*
> ```Go
> 			m := make(map[string]interface{})
> 			if g.IsCount == 1 {
> 				m["count"] = fmt.Sprintf("%d", uid)
> ```

This should be `_count_`, because it's an internal variable.

---

*[query/query.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF7VMhlxDzFnylRRfU:-KOF7VMhlxDzFnylRRfV:-1572070146) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L213)):*
> ```Go
> 			}
> 		}
> 		if g.IsCount == 1 {
> ```

I don't really like this. There's a TODO here as well for len(l) == 1. Addressing that TODO will automatically get this for you, I reckon.

---

*[query/query.go, line 388 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF6BHDrgB9hjVi4IJ4:-KOF6BHDrgB9hjVi4IJ5:-792266326) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L388)):*
> ```Go
> 	// So, we work on the children, and then recurse for grand children.
> 	for _, gchild := range gq.Children {
> 		if gchild.Attr == "count" {
> ```

_count_

---

*[query/query_test.go, line 203 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF65LsTH5m_FyqCvD1:-KOF65LtT7t0NrAU__si:-1099714294) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query_test.go#L203)):*
> ```Go
> 				friend {
> 					name
> 					count
> ```

This should be `_count_`.

---

*[query/query_test.go, line 204 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF799t-pHShs18XGwY:-KOF799t-pHShs18XGwZ:-690759842) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query_test.go#L204)):*
> ```Go
> 					name
> 					count
> 				}
> ```

Also, test a case where `_count_` has children.

---

*[query/query_test.go, line 221 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF6j6FyOH-HHD6CCh4:-KOF6j6GHn05HCqTVtWp:1226476008) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query_test.go#L221)):*
> ```Go
> 	}
> }
> ```

Do a positive test as well.

---

*[task/Query.go, line 78 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOEu8X_H2pMBRTvsql3-r1-78:-KOF6pQuQKq0HOkVAwyJ:5173665) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/task/Query.go#L78)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Query.IsCount should have comment or be unexported
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[task.fbs, line 9 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF5Rzw8kBPr-7qDfLH:-KOFELcvUT3LcTwOeSVZ:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/task.fbs#L9)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> `getCount` is more appropriate here.
</details>
Done.

---

*[query/query.go, line 203 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF5d5i8VFCPv1bv-7F:-KOFEMm3iBN-tG-ozd55:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L203)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should be `_count_`, because it's an internal variable.
</details>
Done.

---

*[query/query.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF7VMhlxDzFnylRRfU:-KOFCXAflVEk3zfzyEWr:-515244140) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L213)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I don't really like this. There's a TODO here as well for len(l) == 1. Addressing that TODO will automatically get this for you, I reckon.
</details>
But will that be a generic case? In case of count, the user would like to access it as m[..][attr][count], but if its a list of uids, you might still want m[..][attr][0][_uid_]. Shall we have a VC somtime to discuss this?

---

*[query/query.go, line 388 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF6BHDrgB9hjVi4IJ4:-KOFE4mxLAsl7Zi4vrzS:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L388)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> _count_
</details>
Done.

---

*[query/query_test.go, line 203 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF65LsTH5m_FyqCvD1:-KOFE5jzywWOGQqmuw2P:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query_test.go#L203)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should be `_count_`.
</details>
Done.

---

*[query/query_test.go, line 204 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF799t-pHShs18XGwY:-KOFGAMG3mqi9nkUYpUI:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query_test.go#L204)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Also, test a case where `_count_` has children.
</details>
Done.

---

*[query/query_test.go, line 221 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF6j6FyOH-HHD6CCh4:-KOFLxCMJdSWFcntf0Ek:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query_test.go#L221)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Do a positive test as well.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by pawanrawal** [comment]
We would also need to support this in preTraverse which the is used by different clients.

**Comment by ashwin95r** [comment]
Added support in preTraverse. Can you have a look @pawanrawal ?

---

Review status: 0 of 5 files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-:-KOJ7xiWvF8zcm04v-Ph:-1844277054)*

**Comment by pawanrawal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 16 unresolved discussions.

---

*[query/query.go, line 304 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOJhq0MCwS0M_6Q_6dO:-KOJhq0NU9LecQc0TiTG:1259343371) ([raw file](https://github.com/dgraph-io/dgraph/blob/54a43ecd5fbb06ad0fb5d5b839505afefcdf1092/query/query.go#L304)):*
> ```Go
> 			return fmt.Errorf("Attribute with uid not found")
> 		}
> ```

Why did you delete this?

---

*[query/query.go, line 333 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOJhfBrlzkYy_w_4AI_:-KOJhfBsqgpaznrzWhUc:-1041957107) ([raw file](https://github.com/dgraph-io/dgraph/blob/38de7a0984f4b7ecc7b14f20ff2532985ba1f47a/query/query.go#L333)):*
> ```Go
> 				uc.Properties = []*graph.Property{p}
> 				children = append(children, uc)
> 			} else {
> ```

Looks fine, did you also verify that it works for a query in which in `_count` is nested two levels?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 16 unresolved discussions.

---

*[query/query.go, line 333 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOJhfBrlzkYy_w_4AI_:-KOJlnSXuDcuYy0IiI-6:-1586031047) ([raw file](https://github.com/dgraph-io/dgraph/blob/38de7a0984f4b7ecc7b14f20ff2532985ba1f47a/query/query.go#L333)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Looks fine, did you also verify that it works for a query in which in `_count` is nested two levels?
</details>
Yeah it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by manishrjain** [comment]
Add a task to update the wiki query page about how to retrieve count.

---

Reviewed 4 of 5 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[task.fbs, line 26 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KONUjNz2Tq2yAW8d4xZ:-KONUjNz2Tq2yAW8d4x_:b-e0cu1x) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3d26900f3717f3dfa56ebac46ac177f85c60027/task.fbs#L26)):*
> ```
> table Result {
> 	uidmatrix:[UidList];
> 	values:[Value];
> ```

Why not add a field here for count? Wouldn't that be cleaner than hacking uidmatrix?

---

*[query/query.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF7VMhlxDzFnylRRfU:-KONULSIcmBBzZd_UBA-:bvaatzf) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L213)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> But will that be a generic case? In case of count, the user would like to access it as m[..][attr][count], but if its a list of uids, you might still want m[..][attr][0][_uid_]. Shall we have a VC somtime to discuss this?
</details>
Not clear what you mean. Okay, let's talk about it today.

---

*[query/query_test.go, line 240 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KONV2MOxLXXw2zQV-ov:-KONV2MOxLXXw2zQV-ow:bjwpyw4) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3d26900f3717f3dfa56ebac46ac177f85c60027/query/query_test.go#L240)):*
> ```Go
> 	resp := mp["_root_"].([]interface{})[0]
> 	friend := resp.(map[string]interface{})["friend"]
> 	count := friend.(map[string]interface{})["_count_"].(string)
> ```

Why string? Why not int?

---

*[query/query_test.go, line 280 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KONVLAlmoIwt5PHaAhQ:-KONVLAlmoIwt5PHaAhR:b-p5yy6u) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3d26900f3717f3dfa56ebac46ac177f85c60027/query/query_test.go#L280)):*
> ```Go
> 			me(_uid_: 0x01) {
> 				friend {
> 					_count_{
> ```

Space between _count_ and {

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-:-KONVWkv7Ug5AmS6pVqO:b-lapq9p)*

**Comment by ashwin95r** [comment]
Added a task: https://app.asana.com/0/110655897041979/164234996002204

---

Review status: 1 of 6 files reviewed at latest revision, 24 unresolved discussions.

---

*[task.fbs, line 26 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KONUjNz2Tq2yAW8d4xZ:-KOOgvGJXT90cNXyWFU8:b-jke8uk) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3d26900f3717f3dfa56ebac46ac177f85c60027/task.fbs#L26)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why not add a field here for count? Wouldn't that be cleaner than hacking uidmatrix?
</details>
True. Modified to reflect this approach

---

*[query/query.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOF7VMhlxDzFnylRRfU:-KOOh-ka8MFd1mpCJHrt:bh3rf8a) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/query/query.go#L213)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Not clear what you mean. Okay, let's talk about it today.
</details>
Taken care of in the new approach

---

*[query/query_test.go, line 240 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KONV2MOxLXXw2zQV-ov:-KOOh3J_h5Je2lEjUPPa:b-j8vbyq) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3d26900f3717f3dfa56ebac46ac177f85c60027/query/query_test.go#L240)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why string? Why not int?
</details>
since uid was being used, it was a hex string. Now its ulong.

---

*[query/query_test.go, line 280 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KONVLAlmoIwt5PHaAhQ:-KOOhAeqNsbfhQN9oKc0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3d26900f3717f3dfa56ebac46ac177f85c60027/query/query_test.go#L280)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Space between _count_ and {
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-:-KOOhM5AxOxLBB6klpet:bptjdmp)*

**Comment by manishrjain** [comment]
Decrease the special handling of the GetCount.

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[task.fbs, line 26 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KONUjNz2Tq2yAW8d4xZ:-KOPjHHbmBnnr7iBCHbx:b32w0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3d26900f3717f3dfa56ebac46ac177f85c60027/task.fbs#L26)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> True. Modified to reflect this approach
</details>
OK

---

*[query/query.go, line 195 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPjYpwMHspU7-Ud1xj:-KOPjYpxo-NJggnOimYa:b9imzu4) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L195)):*
> ```Go
> 	//
> 
> 	if g.GetCount == 1 {
> ```

I don't think you need to check for this. You can instead just iterate over the new count array, just like we do for Uids and Values.

---

*[query/query.go, line 325 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPkCzoTnXSbbDMkBk8:-KOPkCzpAFREzz6VGBZx:bk7vj7m) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L325)):*
> ```Go
> 			return fmt.Errorf("While parsing UidList")
> 		}
> 		if pc.GetCount == 1 {
> ```

Check the result instead of checking the query. To make it closer to how the bottom two conditions work. Also:

Don't do:
if .. else { if .. else .. }

Do:
if .. else if .. else ..

---

*[query/query.go, line 591 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPksYCQ1aDpfXFUbHM:-KOPksYD5cIIZ6wPUBS_:b-rh9ee2) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L591)):*
> ```Go
> 
> 	var sorted []uint64
> 	if sg.GetCount == 0 {
> ```

Handle the smaller condition first.

if sg.GetCount == 1 { ... return }

// rest of the logic remains the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-:-KOPlKUuu_3wVkY3TmFa:b-fhkzy3)*

**Comment by ashwin95r** [comment]
Review status: 4 of 6 files reviewed at latest revision, 21 unresolved discussions.

---

*[query/query.go, line 195 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPjYpwMHspU7-Ud1xj:-KOcCJCwNigLZvelnpra:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L195)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I don't think you need to check for this. You can instead just iterate over the new count array, just like we do for Uids and Values.
</details>
Done.

---

*[query/query.go, line 325 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPkCzoTnXSbbDMkBk8:-KOcGYBSqU0fnTOypUJ9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L325)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Check the result instead of checking the query. To make it closer to how the bottom two conditions work. Also:
> 
> Don't do:
> if .. else { if .. else .. }
> 
> Do:
> if .. else if .. else ..
</details>
Done.

---

*[query/query.go, line 591 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPksYCQ1aDpfXFUbHM:-KOcCv_f4SnYa7KjF6lb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L591)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Handle the smaller condition first.
> 
> if sg.GetCount == 1 { ... return }
> 
> // rest of the logic remains the same.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by ashwin95r** [comment]
Review status: 4 of 6 files reviewed at latest revision, 21 unresolved discussions.

---

*[query/query.go, line 195 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPjYpwMHspU7-Ud1xj:-KOcXPvQZ8dsLa8lAFej:b-a7p2v5) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L195)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Done.
</details>
We need to avoid reaching the Uidmatrix step in case this node has asked for count. Otherwise 
```
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 19 [running]:
panic(0x9b9480, 0xc82000a090)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc820184480)
        /usr/local/go/src/testing/testing.go:467 +0x192
panic(0x9b9480, 0xc82000a090)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/dgraph-io/dgraph/vendor/github.com/google/flatbuffers/go.(*Table).Offset(0xc820111478, 0x4, 0x0)
        /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/vendor/github.com/google/flatbuffers/go/table.go:15 +0x1ae
github.com/dgraph-io/dgraph/task.(*UidList).UidsLength(0xc820111478, 0xc820111478)
        /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/task/UidList.go:27 +0x2f
github.com/dgraph-io/dgraph/query.postTraverse(0xc820131480, 0xc82016f410, 0x0, 0x0)
        /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query.go:209 +0xd2e
github.com/dgraph-io/dgraph/query.postTraverse(0xc820131200, 0xc82016f2c0, 0x0, 0x0)
        /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query.go:151 +0x1ee
github.com/dgraph-io/dgraph/query.(*SubGraph).ToJson(0xc820131200, 0xc820111f08, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query.go:255 +0x6e
github.com/dgraph-io/dgraph/query.TestCount(0xc820184480)
        /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query_test.go:233 +0x4fb
```
Index goes out of range in the uidmatrix block. Also I think we could avoid attaching _uid_ to every node unless it is explicitely requested for. That might solve this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by manishrjain** [comment]
:lgtm: 

---

Reviewed 1 of 5 files at r5, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 195 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPjYpwMHspU7-Ud1xj:-KOcaFAM4WtC4vSTK1sj:b231hh5) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L195)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> We need to avoid reaching the Uidmatrix step in case this node has asked for count. Otherwise 
> ```
> panic: runtime error: index out of range [recovered]
>         panic: runtime error: index out of range
> 
> goroutine 19 [running]:
> panic(0x9b9480, 0xc82000a090)
>         /usr/local/go/src/runtime/panic.go:481 +0x3e6
> testing.tRunner.func1(0xc820184480)
>         /usr/local/go/src/testing/testing.go:467 +0x192
> panic(0x9b9480, 0xc82000a090)
>         /usr/local/go/src/runtime/panic.go:443 +0x4e9
> github.com/dgraph-io/dgraph/vendor/github.com/google/flatbuffers/go.(*Table).Offset(0xc820111478, 0x4, 0x0)
>         /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/vendor/github.com/google/flatbuffers/go/table.go:15 +0x1ae
> github.com/dgraph-io/dgraph/task.(*UidList).UidsLength(0xc820111478, 0xc820111478)
>         /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/task/UidList.go:27 +0x2f
> github.com/dgraph-io/dgraph/query.postTraverse(0xc820131480, 0xc82016f410, 0x0, 0x0)
>         /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query.go:209 +0xd2e
> github.com/dgraph-io/dgraph/query.postTraverse(0xc820131200, 0xc82016f2c0, 0x0, 0x0)
>         /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query.go:151 +0x1ee
> github.com/dgraph-io/dgraph/query.(*SubGraph).ToJson(0xc820131200, 0xc820111f08, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query.go:255 +0x6e
> github.com/dgraph-io/dgraph/query.TestCount(0xc820184480)
>         /home/ubuntu/go_work/src/github.com/dgraph-io/dgraph/query/query_test.go:233 +0x4fb
> ```
> Index goes out of range in the uidmatrix block. Also I think we could avoid attaching _uid_ to every node unless it is explicitely requested for. That might solve this issue.
</details>
If we asked for the count, how come we're seeing this crash? UidmatrixLength should be zero right.

---

*[query/query.go, line 330 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOcxQULUAaIHFbUeWq8:-KOcxQULUAaIHFbUeWq9:b-c98c7p) ([raw file](https://github.com/dgraph-io/dgraph/blob/649c3033a4f84f4e092c2c777fa8c8696cde877a/query/query.go#L330)):*
> ```Go
> 			p := &graph.Property{Prop: "_count_", Val: []byte(count)}
> 			uc.Properties = []*graph.Property{p}
> 			children = append(children, uc)
> ```

Add a vertical space after this.

---

*[query/query_test.go, line 240 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOcxh63iCuownJMzI6J:-KOcxh63iCuownJMzI6K:bpshfa6) ([raw file](https://github.com/dgraph-io/dgraph/blob/649c3033a4f84f4e092c2c777fa8c8696cde877a/query/query_test.go#L240)):*
> ```Go
> 	err = json.Unmarshal(js, &mp)
> 
> 	fmt.Println(mp)
> ```

This should probably be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-:-KOcyBS-2PAueLcoZLBd:bg7igkv)*

**Comment by ashwin95r** [comment]
Review status: 4 of 6 files reviewed at latest revision, 22 unresolved discussions.

---

*[query/query.go, line 195 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPjYpwMHspU7-Ud1xj:-KOcycsSo7TCd0W3Vysr:bbaiu66) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L195)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> If we asked for the count, how come we're seeing this crash? UidmatrixLength should be zero right.
</details>
As discussed, it was due to uid list not being initialized in count nodes. Initializing them to empty lists now.

---

*[query/query.go, line 591 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPksYCQ1aDpfXFUbHM:-KOciZ-c0t5qbiz4nW8I:b-c0fyye) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L591)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Done.
</details>
Should we retain this if condition. It avoids having to go to sortedUniqueUids(). And would anyways return in the next if condition.

---

*[query/query.go, line 330 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOcxQULUAaIHFbUeWq8:-KOd2gzSXsMIv1J2IegN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/649c3033a4f84f4e092c2c777fa8c8696cde877a/query/query.go#L330)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a vertical space after this.
</details>
Done.

---

*[query/query_test.go, line 240 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOcxh63iCuownJMzI6J:-KOd2mDQGYBeGhspV6iu:b-c606kt) ([raw file](https://github.com/dgraph-io/dgraph/blob/649c3033a4f84f4e092c2c777fa8c8696cde877a/query/query_test.go#L240)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should probably be removed.
</details>
Ah yeah. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[query/query.go, line 591 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOPksYCQ1aDpfXFUbHM:-KOd4OevUV9BSuazjyIc:b4z6hem) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f54e0a7301c4f468d2f493fc80c194a132fd324/query/query.go#L591)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Should we retain this if condition. It avoids having to go to sortedUniqueUids(). And would anyways return in the next if condition.
</details>
Yeah, this looks good. Keep the flow clean. OK

---

*[task/Query.go, line 90 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-KOEu8X_H2pMBRTvsql3-r1-90:-KOcybt-DMK2KglxBTsk:b32w0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/ece3519675a4753aee0866d9a7207da057eef03c/task/Query.go#L90)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function QueryStart should have comment or be unexported
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147#-:-KOd4cdgEdGrPtVHRx_j:bnfp4nl)*

**Comment by pawanrawal** [comment]
Reviewed 1 of 5 files at r2, 2 of 5 files at r5, 1 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/147)*

**Comment by ashwin95r** [comment]
Merged to develop with commit edee6a82b30687ab1f957636b3cd094cf759a8b3

**Pull request closed without merging**
