### PR TITLE
Improve HTTP API

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1773)

### CODE REVIEW

**Comment by peterstace** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[dgraph/cmd/server/http.go, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxYResiDPIYbIFjG8a:-KyxYResiDPIYbIFjG8b:b-h91390) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/dgraph/cmd/server/http.go#L52)):*
> ```Go
> 		return ts, nil
> 	}
> 	return 0, nil
> ```

Shouldn't we give an error if the path doesn't have the correct length? I think there should only be two non-error cases, `/blah/x` (gives x) and `/blah` (gives 0).

---

*[dgraph/cmd/server/http.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxZ15Dkje2YhjgFdmU:-KyxZ15Dkje2YhjgFdmV:bx6lafr) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/dgraph/cmd/server/http.go#L247)):*
> ```Go
> 	if ts == 0 {
> 		x.SetStatus(w, x.ErrorInvalidRequest,
> 			"StartTs header is mandatory while trying to commit")
> ```

Error text needs updating, no longer a header.

---

*[dgraph/cmd/server/http.go, line 330 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxZEBbKYAzisrVZQYY:-KyxZEBcrTil16UIHQS4:bfw5al2) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/dgraph/cmd/server/http.go#L330)):*
> ```Go
> 	if ts == 0 {
> 		x.SetStatus(w, x.ErrorInvalidRequest,
> 			"StartTs header is mandatory while trying to abort.")
> ```

Update message text.

---

*[wiki/content/clients/index.md, line 447 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-Kyx_OYhiQuTaVekydBS:-Kyx_OYhiQuTaVekydBT:bexzssw) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/wiki/content/clients/index.md#L447)):*
> ```Markdown
>     "AAALX3ByZWRpY2F0ZV8AAAAAAAAAAAE=",
>     "AAAHYmFsYW5jZQAAAAAAAAAAAQ=="
>   ]' | jq
> ```

Did you run these examples? I tried to indent these nicely before but couldn't get the `$'...'` syntax to work for the keys.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773)*

**Comment by peterstace** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[wiki/content/clients/index.md, line 447 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-Kyx_OYhiQuTaVekydBS:-Kyx_jgoMHqiq_Zbbc_c:b-nd6g5v) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/wiki/content/clients/index.md#L447)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Did you run these examples? I tried to indent these nicely before but couldn't get the `$'...'` syntax to work for the keys.
</blockquote></details>

^^ That may have been because they were part of a header before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773)*

**Comment by peterstace** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773)*

**Comment by manishrjain** [comment]
My comments. Wait for Peter to approve.

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: 7 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[dgraph/cmd/server/http.go, line 38 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxeOI1nM27oASJk_wq:-KyxeOI2-iIZqih7kIdG:b-t967fs) ([raw file](https://github.com/dgraph-io/dgraph/blob/6fd1df9f283bc8d2eb66ac5712f3aba7815ff5b7/dgraph/cmd/server/http.go#L38)):*
> ```Go
> 
> const (
> 	startTsHeader = "X-Dgraph-StartTs"
> ```

Can we make the comparison case-insensitive?

---

*[dgraph/cmd/server/http.go, line 48 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxeaIlfKlMmYdaoAAs:-KyxeaImPD6vGjgxWXjy:by9bo48) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e3d7c81df9708b4e16f40041801fc589e3eacae/dgraph/cmd/server/http.go#L48)):*
> ```Go
> 		ts, err := strconv.ParseUint(params[1], 0, 64)
> 		if err != nil {
> 			return 0, fmt.Errorf("Error while parsing StartTs path parameter as uint64")
> ```

return err as well.

---

*[wiki/scripts/local.sh, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxezNxOu3JLb4SFvS6:-KyxezNxOu3JLb4SFvS7:b-pk76xe) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e3d7c81df9708b4e16f40041801fc589e3eacae/wiki/scripts/local.sh#L17)):*
> ```Shell
> 
> run() {
>   export CURRENT_BRANCH="master"
> ```

Is this supposed to be hardcoded to master?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-:-Kyxf0pvH5BZsBQDk6OF:b-gju98b)*

**Comment by pawanrawal** [comment]
Review status: 6 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[dgraph/cmd/server/http.go, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxYResiDPIYbIFjG8a:-Kyxg00ouIjS8et-ObbA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/dgraph/cmd/server/http.go#L52)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Shouldn't we give an error if the path doesn't have the correct length? I think there should only be two non-error cases, `/blah/x` (gives x) and `/blah` (gives 0).
</blockquote></details>

Done.

---

*[dgraph/cmd/server/http.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxZ15Dkje2YhjgFdmU:-KyxdV-xCapozoNvbciZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/dgraph/cmd/server/http.go#L247)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Error text needs updating, no longer a header.
</blockquote></details>

Done.

---

*[dgraph/cmd/server/http.go, line 330 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxZEBbKYAzisrVZQYY:-KyxdVZ5n3Dq3CPfs92i:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/dgraph/cmd/server/http.go#L330)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Update message text.
</blockquote></details>

Done

---

*[dgraph/cmd/server/http.go, line 38 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxeOI1nM27oASJk_wq:-KyxgYpT_C5mSYKSRLVi:bbye67a) ([raw file](https://github.com/dgraph-io/dgraph/blob/6fd1df9f283bc8d2eb66ac5712f3aba7815ff5b7/dgraph/cmd/server/http.go#L38)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can we make the comparison case-insensitive?
</blockquote></details>

its already case insensitive

---

*[dgraph/cmd/server/http.go, line 48 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxeaIlfKlMmYdaoAAs:-Kyxg6Kuvg9KlMzSBZIU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e3d7c81df9708b4e16f40041801fc589e3eacae/dgraph/cmd/server/http.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return err as well.
</blockquote></details>

Done.

---

*[wiki/content/clients/index.md, line 447 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-Kyx_OYhiQuTaVekydBS:-KyxdXKHzKbEclhzjEaB:bq89615) ([raw file](https://github.com/dgraph-io/dgraph/blob/51526d98a3aeecc65e6325ad41b164278eb0a54a/wiki/content/clients/index.md#L447)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

^^ That may have been because they were part of a header before.
</blockquote></details>

Yeah tried running. They work fine since they are part of the body now.

---

*[wiki/scripts/local.sh, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-KyxezNxOu3JLb4SFvS6:-KyxfNJcdvE1kPOOdqF_:bt5s5p4) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e3d7c81df9708b4e16f40041801fc589e3eacae/wiki/scripts/local.sh#L17)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Is this supposed to be hardcoded to master?
</blockquote></details>

This script is for running docs locally. Docs assume that its only run for `master` or `release` branch otherwise they break, hence hardcoded it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773)*

**Comment by peterstace** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1773#-:-KyxvITecIYcitMKXQG3:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master as of 275f0c4925e422f1b567e6c330933eb482584487.

**Pull request closed without merging**
