### PR TITLE
Add hash tokenizer for strings

### PR DESCRIPTION
**Pull request by pawanrawal**
Also refactor some code to make correct use of `IsLossy()`. We don't fetch and compare the actual values if the `tokenizer.IsLossy()`.

TODO - Add docs

Implements #851

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/908)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query_test.go, line 6125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-Kjb3T5O7Dd5PT-B1a0y:-Kjb3T5O7Dd5PT-B1a0z:bpwf8or) ([raw file](https://github.com/dgraph-io/dgraph/blob/105cf1cd7928442dc42942c3bdd90da06bab3852/query/query_test.go#L6125)):*
> ```Go
> }
> 
> func TestHashTokEq(t *testing.T) {
> ```

Also a test with a name which was not hashed maybe.

---

*[query/query_test.go, line 6161 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-Kjb3OcX9xwuZMeg2N50:-Kjb3OcX9xwuZMeg2N51:by91g57) ([raw file](https://github.com/dgraph-io/dgraph/blob/105cf1cd7928442dc42942c3bdd90da06bab3852/query/query_test.go#L6161)):*
> ```Go
> 	ctx := context.Background()
> 	_, err := ProcessQuery(ctx, res, &l)
> 	require.NotNil(t, err)
> ```

`require.Error()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-:-Kjb2vTZJND2ZXpqURGG:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query_test.go, line 6125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-Kjb3T5O7Dd5PT-B1a0y:-KjbQvjro9NV4l8_7O2r:b-xf1hq4) ([raw file](https://github.com/dgraph-io/dgraph/blob/105cf1cd7928442dc42942c3bdd90da06bab3852/query/query_test.go#L6125)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Also a test with a name which was not hashed maybe.
</blockquote></details>

I see you probably meant another predicate which did not have hash tokenizer? If yes, then done.

---

*[query/query_test.go, line 6161 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-Kjb3OcX9xwuZMeg2N50:-KjbQ0nMQVZVw24kg3u3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/105cf1cd7928442dc42942c3bdd90da06bab3852/query/query_test.go#L6161)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

`require.Error()`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/908)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-:-KjbpnC74KfaZzaAolhW:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 313 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-KjcXHLg5C0ZA6gg_BTV:-KjcXHLg5C0ZA6gg_BTW:b723cwh) ([raw file](https://github.com/dgraph-io/dgraph/blob/db445aa74b6583c08eec287b85db09426492fa88/tok/tok.go#L313)):*
> ```Go
> 		return nil, x.Errorf("Hash tokenizer only supported for string types")
> 	}
> 	return []string{encodeToken(encodeInt(int64(farm.Hash32([]byte(term)))),
> ```

Since we are encoding it as int64, we might be better of taking farm.Hash64

---

*[worker/tokens.go, line 74 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-KjcVnoygbQqI8oF7ZdD:-KjcVnoygbQqI8oF7ZdE:b-curfyx) ([raw file](https://github.com/dgraph-io/dgraph/blob/db445aa74b6583c08eec287b85db09426492fa88/worker/tokens.go#L74)):*
> ```Go
> 		return nil, x.Errorf("Attribute:%s does not have proper index for comparsion",
> 			attr)
> 	}
> ```

This shouldn't happen actually. If attribute is indexed it would have default tokenizer atleast. If there is no default tokenizer, server would panic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/908)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 313 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-KjcXHLg5C0ZA6gg_BTV:-KjeKo196c4dhnL0QmTj:b-fznogt) ([raw file](https://github.com/dgraph-io/dgraph/blob/db445aa74b6583c08eec287b85db09426492fa88/tok/tok.go#L313)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Since we are encoding it as int64, we might be better of taking farm.Hash64
</blockquote></details>

Good idea, done.

---

*[worker/tokens.go, line 74 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/908#-KjcVnoygbQqI8oF7ZdD:-KjePxk4XhUZUEOOW_xw:b-uwp518) ([raw file](https://github.com/dgraph-io/dgraph/blob/db445aa74b6583c08eec287b85db09426492fa88/worker/tokens.go#L74)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This shouldn't happen actually. If attribute is indexed it would have default tokenizer atleast. If there is no default tokenizer, server would panic
</blockquote></details>

That's right, since we already check IsIndexed above, I can leave this check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/908)*

**Pull request closed without merging**
