### PR TITLE
Client/retries

### LINKED ISSUE #796: Make BatchMutation.Flush()'s retry logic tunable for the Go client
Calling `Flush()` on a `BatchMutation` retries forever (every 5ms). It would be nice if this is tunable.

For example, if the batch fails after retrying 5 times, abort and return an error.

### PR DESCRIPTION
**Pull request by pawanrawal**
Add an option to limit the number of max retries performed by the client during doing Batch mutations. This fixes #796.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1182)

### CODE REVIEW

**Comment by manishrjain** [comment]
Haven't looked too carefully. Seems like a lot of changes for just aborting (I could be wrong). Got some initial comments.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/mutations.go, line 300 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1182#-Koz0W1Wj9Lg9YByweKe:-Koz0W1Wj9Lg9YByweKf:bg4yxh0) ([raw file](https://github.com/dgraph-io/dgraph/blob/e70c10342c5d0a3e4b451e48482344bdd5e4ea88/client/mutations.go#L300)):*
> ```Go
> 	counter := atomic.AddUint64(&d.mutations, 1)
> RETRY:
> 	if atomic.LoadUint64(&d.retries) > d.opts.MaxRetry {
> ```

atomic? Each request can only be tried serially right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1182#-:-Koz1IZ6y4zJ8TClRqSu:b9qw0nd)*

**Comment by pawanrawal** [comment]
Yes, that's right, this allows abortion of batch mutations if the number of retries exceeds a number. We were using wait groups earlier so it was not possible to bubble-up the error.
Now we use channels to communicate the error to `batch.Flush()`, which returns the error to the user so that they can abort early if they want to.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/mutations.go, line 300 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1182#-Koz0W1Wj9Lg9YByweKe:-KozSt6IPunt9NKpKB0l:b-brblup) ([raw file](https://github.com/dgraph-io/dgraph/blob/e70c10342c5d0a3e4b451e48482344bdd5e4ea88/client/mutations.go#L300)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

atomic? Each request can only be tried serially right?
</blockquote></details>

We run 100 concurrent requests. So `d.retries` tracks retries for all of them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1182#-:-KozTCpj4vrPYiGQj4Cx:bq05bo5)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1182#-:-Kp-0dtdk9zDwNJUCw7l:bnfp4nl)*

**Comment by manishrjain** [comment]
Let's do the other change first, where you create a request just from one file and do the checkpointing. Once that's done, we can do this. I suspect the former would change the way code executes, and would affect this PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1182#-:-KpLpnbNWggZrh3X6vcj:b-h01nyn)*

**Comment by pawanrawal** [comment]
Closing this as code as changed a lot. Will open a new PR.

**Pull request closed without merging**
