### PR TITLE
Infix math notation in math operators

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/812)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[gql/math.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPujfx6inj06hKjAdI:-KhPujfx6inj06hKjAdJ:b8v3t0d) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L19)):*
> ```Go
> func (s *mathTreeStack) push(t *MathTree) { s.a = append(s.a, t) }
> 
> func (s *mathTreeStack) pop() (*MathTree, error) {
> ```

have another func called `popAssert()`.

---

*[gql/math.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPxFg2cFCggVUS2n8s:-KhPxFg3Lt_FVoYH88Z9:b-w6gzwz) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L64)):*
> ```Go
> 			return x.Errorf("Invalid math statement. Expected 1 operands")
> 		}
> 		topOp.Child = []*MathTree{topVal}
> ```

vertical space.

---

*[gql/math.go, line 69 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPuuks_p699W8-lpEC:-KhPuuks_p699W8-lpED:bbot42p) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L69)):*
> ```Go
> 			return x.Errorf("Invalid Math expression. Expected 3 operands")
> 		}
> 		topVal1, _ := valueStack.pop()
> ```

Never ignore errors. Do something with them.

---

*[gql/math.go, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPv54_Poc0AnztxI1C:-KhPv54_Poc0AnztxI1D:b-q8dvw2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L90)):*
> ```Go
> 	// While adding an op, also add it to the corresponding function type.
> 	return f == "*" || f == "%" || f == "+" || f == "-" || f == "/" ||
> 		f == "exp" || f == "log" || f == "cond" ||
> ```

s/log/ln

---

*[gql/math.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPv6CsZ93a8pnXWh2w:-KhPv6CsZ93a8pnXWh2x:baov1l5) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L94)):*
> ```Go
> 		f == "==" || f == "!=" ||
> 		f == "min" || f == "max" || f == "sqrt" ||
> 		f == "pow" || f == "logbase"
> ```

s/logbase/log

---

*[gql/math.go, line 120 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPxIh3Ppg0smtVreOV:-KhPxIh3Ppg0smtVreOW:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L120)):*
> ```Go
> 			lastItem := it.Item()
> 			it.Next()
> 			if op == "-" && (lastItem.Val == "(" || lastItem.Val == "," || isBinaryMath(lastItem.Val)) {
> ```

100 chars.

---

*[gql/parser_test.go, line 168 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPxyH9qyGcghucf6e0:-KhPxyH9qyGcghucf6e1:b2qgwhr) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/parser_test.go#L168)):*
> ```Go
> 				c as count(relatives)
> 				d as math(exp(a + b + 1) - log(c))
> 		 		q as math(c * -1 + -b + (-b*c))
> ```

extra space. -c -b - (b*c)

---

*[gql/parser_test.go, line 242 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPzF3taGAkGf9M15Wq:-KhPzF3taGAkGf9M15Wr:b-czo5c1) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/parser_test.go#L242)):*
> ```Go
> 				b as count(friends)
> 				c as count(relatives)
> 				d as math(cond(a <= 10, exp(a + b + 1), log(c)))
> ```

math(cond(..) + 20 - ln(a))

since(..)/(3600*24)

// floor, ceil?

---

*[gql/parser_test.go, line 271 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ-VQ5hOtG7tEepWTm:-KhQ-VQ6BIZsbAbYzEfL:b-smer1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/parser_test.go#L271)):*
> ```Go
> 				b as count(friends)
> 				c as count(relatives)
> 				d as math(a + b * c / a + exp(a + b + 1) - log(c))
> ```

test with exp(). Also, max(), and others similarly. Also, math()

---

*[query/query.go, line 841 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ1lj-Hd_GxzH9Lx3i:-KhQ1lj-Hd_GxzH9Lx3j:bc6kq9w) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L841)):*
> ```Go
> }
> 
> func evalMathTree(mNode *gql.MathTree, doneVars map[string]values) (err error) {
> ```

move this outside of query.go

---

*[query/query.go, line 880 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ25An8vaEO82fGSr-:-KhQ25An8vaEO82fGSr0:b-gmrzk2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L880)):*
> ```Go
> 	// Handle ternary conditional operator separately here.
> 	if isTernary(aggName) {
> 		condMap := mNode.Child[0].Val
> ```

helper function for this.

---

*[query/query.go, line 917 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ26YdxkzERGhAQ666:-KhQ26YdxkzERGhAQ667:b-kuv5na) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L917)):*
> ```Go
> 	// Handle binary boolean operators separately here.
> 	if isBinaryBoolean(aggName) {
> 		ch := mNode.Child[1]
> ```

helper func for this.

---

*[query/query.go, line 940 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ28GygWswr_FGciwN:-KhQ28GygWswr_FGciwO:b-kuv5na) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L940)):*
> ```Go
> 	// Handle unary operators here.
> 	if isUnary(aggName) {
> 		ch := mNode.Child[0]
> ```

helper func for this.

---

*[query/query.go, line 962 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ2CEameGV_M1CEwph:-KhQ2CEameGV_M1CEwpi:bavjrll) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L962)):*
> ```Go
> 	}
> 
> 	if isBinary(aggName) {
> ```

Explain what this handles. Show an example. Same for all the other helper functions.

---

*[query/query.go, line 963 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ2AV19t-MojZcOkgZ:-KhQ2AV19t-MojZcOkg_:b-kuv5na) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L963)):*
> ```Go
> 
> 	if isBinary(aggName) {
> 		mpl := mNode.Child[0].Val
> ```

helper func for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/812)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[gql/math.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPujfx6inj06hKjAdI:-KhQPwVwNAHWiatdZevF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

have another func called `popAssert()`.
</blockquote></details>

Done.

---

*[gql/math.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPxFg2cFCggVUS2n8s:-KhQrAHU5dbTQiXiGJWB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L64)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

vertical space.
</blockquote></details>

Done.

---

*[gql/math.go, line 69 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPuuks_p699W8-lpEC:-KhQrCJzRTnyjwv3k1Ww:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L69)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Never ignore errors. Do something with them.
</blockquote></details>

Done.

---

*[gql/math.go, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPv54_Poc0AnztxI1C:-KhQsNG2mXqD9rPwJPlp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L90)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s/log/ln
</blockquote></details>

Done.

---

*[gql/math.go, line 120 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPxIh3Ppg0smtVreOV:-KhQsUTiHrHDTOmxx4lO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/math.go#L120)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 168 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPxyH9qyGcghucf6e0:-KhQsbYtdfsLtx177SeQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/parser_test.go#L168)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

extra space. -c -b - (b*c)
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 271 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ-VQ5hOtG7tEepWTm:-KhQvR69Dbu6sMU4j7th:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/parser_test.go#L271)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

test with exp(). Also, max(), and others similarly. Also, math()
</blockquote></details>

Done.

---

*[query/query.go, line 841 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ1lj-Hd_GxzH9Lx3i:-KhR3A-hahvHZJ_0vCpl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L841)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move this outside of query.go
</blockquote></details>

Done.

---

*[query/query.go, line 880 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ25An8vaEO82fGSr-:-KhRF_MBgaEH-OcmIWYe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L880)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

helper function for this.
</blockquote></details>

Done.

---

*[query/query.go, line 917 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ26YdxkzERGhAQ666:-KhRF_pZuEI5QGp-AIEj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L917)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

helper func for this.
</blockquote></details>

Done.

---

*[query/query.go, line 940 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ28GygWswr_FGciwN:-KhRFa8vzDe4UZxjPcYE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L940)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

helper func for this.
</blockquote></details>

Done.

---

*[query/query.go, line 963 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ2AV19t-MojZcOkgZ:-KhRFcTUYySpwDpbTxm9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L963)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

helper func for this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/812)*

**Comment by ashwin95r** [comment]
Review status: 6 of 13 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 242 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhPzF3taGAkGf9M15Wq:-KhUSRz4rVPwtDUYtZjJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/gql/parser_test.go#L242)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

math(cond(..) + 20 - ln(a))

since(..)/(3600*24)

// floor, ceil?
</blockquote></details>

Done.

---

*[query/query.go, line 962 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhQ2CEameGV_M1CEwph:-KhUebuCQq3MIyrMY4bn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0eb020b8bff3d77317995ce8c4ee21bc254f4014/query/query.go#L962)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Explain what this handles. Show an example. Same for all the other helper functions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/812)*

**Comment by manishrjain** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[gql/math.go, line 133 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhVEzEl0Gt48kX4u205:-KhVEzEl0Gt48kX4u206:b-j8clw3) ([raw file](https://github.com/dgraph-io/dgraph/blob/f793255355bb740f463cf673935e6fd329c27368/gql/math.go#L133)):*
> ```Go
> 			if op == "-" &&
> 				(lastItem.Val == "(" || lastItem.Val == "," ||
> 					isBinaryMath(lastItem.Val)) {
> ```

This can go in line above.

---

*[gql/parser.go, line 143 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhVFLMZx_-wBO6_7x7W:-KhVFLMZx_-wBO6_7x7X:b3uklab) ([raw file](https://github.com/dgraph-io/dgraph/blob/f793255355bb740f463cf673935e6fd329c27368/gql/parser.go#L143)):*
> ```Go
> 		"!=": 25,
> 
> 		"cond":    20,
> ```

This group should be together with the above group.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/812)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[gql/math.go, line 133 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhVEzEl0Gt48kX4u205:-KhVH3aQvVFjGtIbCb3g:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f793255355bb740f463cf673935e6fd329c27368/gql/math.go#L133)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This can go in line above.
</blockquote></details>

Done.

---

*[gql/parser.go, line 143 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-KhVFLMZx_-wBO6_7x7W:-KhVHF1GLSqXWn7Tj_Ad:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f793255355bb740f463cf673935e6fd329c27368/gql/parser.go#L143)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This group should be together with the above group.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/812)*

**Comment by janardhan1993** [comment]
Very big PR. LG to me. I will probably have another look later.

---

Reviewed 5 of 12 files at r1, 2 of 7 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-:-KhWquGnI9iX1pcOU6Ez:bnbkygn)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/812#-:-KhZyaaJbfh4sp1EtCtJ:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
