### PR TITLE
Enable expand(_all_) with recurse

### PR DESCRIPTION
**Pull request by pawanrawal**
Takes care of #1507

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1541)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 1715 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1541#-KuxU4ymDOB-vH6mO57d:-KuxU4ymDOB-vH6mO57e:b6zfm1u) ([raw file](https://github.com/dgraph-io/dgraph/blob/a66f85082213fb352ec94bab1d2574524775dc67/query/query.go#L1715)):*
> ```Go
> }
> 
> func expandSubgraph(ctx context.Context, sg *SubGraph) ([]*SubGraph, error) {
> ```

This has been refactored out from ProcessGraph so that recurse can also use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1541)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1541#-:-KvPJ0CU-TI_CrSraOGY:bnfp4nl)*

**Comment by manishrjain** [comment]
Janardhan's LGTM should be sufficient.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1541#-:-KvPLw8jDeUKVV2G_fSR:ba20b10)*

**Comment by pawanrawal** [comment]
In master as of f3571dfe7ee2a4af783a5f97af7f02714cfe98c6.

**Pull request closed without merging**
