### PR TITLE
Index count like terms

### PR DESCRIPTION
**Pull request by pawanrawal**
- [x] Add RebuildCountIndex function like RebuildIndex.

This would make `gt(count(pred), threshold)` queries at root  faster.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1092)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 168 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqulzpuERwSJHsiwjo:-KnqulzpuERwSJHsiwjp:b-1lc0wo) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/posting/index.go#L168)):*
> ```Go
> 	lenBefore := plist.length(0)
> 	_, err := plist.addMutation(ctx, edge)
> 	if err != nil {
> ```

move this out of the lock block.

---

*[posting/index.go, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnquNoWHMmZY7jSfuZz:-KnquNoWHMmZY7jSfu_-:b-oruv9t) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/posting/index.go#L178)):*
> ```Go
> 
> 	if lenAfter != lenBefore && schema.State().AddCount(t.Attr) {
> 		if err := updateCount(ctx, t.Attr, lenBefore, lenAfter, edge.Entity, true); err != nil {
> ```

Only 4 arguments max.

---

*[worker/task.go, line 1012 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqxjMaLJ8aZnHd5SnG:-KnqxjMaLJ8aZnHd5SnH:b4ok8jn) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1012)):*
> ```Go
> }
> 
> func evaluateThreshold(cp countParams, out *protos.Result) {
> ```

this func can be part of countParams.

---

*[worker/task.go, line 1017 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqyI9_4sBkD_72EKnx:-KnqyI9_4sBkD_72EKny:bfo5a9p) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1017)):*
> ```Go
> 	isLeOrLt := cp.fn == "le" || cp.fn == "lt"
> 	itOpt.Reverse = isLeOrLt
> 	it := pstore.NewIterator(itOpt)
> ```

Don't retrieve values.

---

*[worker/task.go, line 1022 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqxuIbK4PEq_Xgu7GM:-KnqxuIbK4PEq_Xgu7GN:b-1317ap) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1022)):*
> ```Go
> 	it.Seek(countKey)
> 	if it.Valid() {
> 		if cp.fn == "eq" {
> ```

Moved out before iterator stuff.

---

*[worker/task.go, line 1031 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-Knqy-0t1rIuQE_YXD6U:-Knqy-0t1rIuQE_YXD6V:by1shbw) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1031)):*
> ```Go
> 			}
> 			countPrefix := pk.CountPrefix(cp.reverse)
> 			for it.Valid() {
> ```

for it.Seek(..); it.ValidForPrefix(); it.Next() {  ... }

---

*[worker/task.go, line 1036 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqyJpeUlz4aMf2AsSR:-KnqyJpeUlz4aMf2AsSS:b-r2a67s) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1036)):*
> ```Go
> 					break
> 				}
> 				val := it.Item().Value()
> ```

Don't use values. Only keys.

---

*[x/keys.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqwlXp2DJ_QZNcvdMa:-KnqwlXp2DJ_QZNcvdMb:b-hwizmi) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/x/keys.go#L27)):*
> ```Go
> const (
> 	byteData         = byte(0x00)
> 	byteIndex        = byte(0x01)
> ```

Add a TODO to make this 2 byte long.

---

*[x/keys.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqviUd1SSy-Z5TkjE7:-KnqviUd1SSy-Z5TkjE8:b-qzswxu) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/x/keys.go#L30)):*
> ```Go
> 	byteReverse      = byte(0x02)
> 	byteSchema       = byte(0x03)
> 	byteCount        = byte(0x04)
> ```

Make these multiples of 2. Then, `byteCount | byteReverse` would give you byteCountReverse.

---

*[x/keys.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqvhTdKRzHBUutdrAQ:-KnqvhTdKRzHBUutdrAR:byzutd5) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/x/keys.go#L31)):*
> ```Go
> 	byteSchema       = byte(0x03)
> 	byteCount        = byte(0x04)
> 	byteCountReverse = byte(0x05)
> ```

Get rid of this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092)*

**Comment by pawanrawal** [comment]
Review status: 13 of 19 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 168 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqulzpuERwSJHsiwjo:-Knr7LXo3pAxq2s7obCu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/posting/index.go#L168)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move this out of the lock block.
</blockquote></details>

Done.

---

*[posting/index.go, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnquNoWHMmZY7jSfuZz:-Knr8WHWKOY8uOV-rpuX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/posting/index.go#L178)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Only 4 arguments max.
</blockquote></details>

Done.

---

*[worker/task.go, line 1012 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqxjMaLJ8aZnHd5SnG:-KnrBxn3DK27rDzcEOuJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1012)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

this func can be part of countParams.
</blockquote></details>

Done.

---

*[worker/task.go, line 1017 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqyI9_4sBkD_72EKnx:-KnrBxS3e88x0IluIHZj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1017)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't retrieve values.
</blockquote></details>

Done.

---

*[worker/task.go, line 1022 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqxuIbK4PEq_Xgu7GM:-KnrBnJCdfRQSmaPyoEK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1022)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Moved out before iterator stuff.
</blockquote></details>

Done.

---

*[worker/task.go, line 1031 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-Knqy-0t1rIuQE_YXD6U:-KnrBnu0qztfZx9E7h70:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1031)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

for it.Seek(..); it.ValidForPrefix(); it.Next() {  ... }
</blockquote></details>

Done.

---

*[worker/task.go, line 1036 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqyJpeUlz4aMf2AsSR:-KnrBwc1nwkQHQoTck1U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/worker/task.go#L1036)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't use values. Only keys.
</blockquote></details>

Done.

---

*[x/keys.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqwlXp2DJ_QZNcvdMa:-KnrDo3Eda1a9XE2eZPI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/x/keys.go#L27)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a TODO to make this 2 byte long.
</blockquote></details>

Done.

---

*[x/keys.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqviUd1SSy-Z5TkjE7:-KnrD07aPBxqgecFuFpz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/x/keys.go#L30)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make these multiples of 2. Then, `byteCount | byteReverse` would give you byteCountReverse.
</blockquote></details>

Done.

---

*[x/keys.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnqvhTdKRzHBUutdrAQ:-KnrCyxJXF64mLJzBAPs:b-jg9onq) ([raw file](https://github.com/dgraph-io/dgraph/blob/34a171dcb1b1f1182c719e07cdf2b3fe7f60858d/x/keys.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Get rid of this.
</blockquote></details>

Deriving it from other two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 147 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrS8wYRt1G9yGG5ZMz:-KnrS8wYRt1G9yGG5ZN-:b8nqbhv) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L147)):*
> ```Go
> }
> 
> type ucParams struct {
> ```

What is ucParams

---

*[posting/index.go, line 149 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrS0CzEwEsNUcbRCEr:-KnrS0CzEwEsNUcbRCEs:b3wbhvt) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L149)):*
> ```Go
> type ucParams struct {
> 	attr      string
> 	lenBefore int
> ```

countBefore

---

*[posting/index.go, line 150 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrS5A5oXjsyAwjQ_GP:-KnrS5A5oXjsyAwjQ_GQ:btwc89e) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L150)):*
> ```Go
> 	attr      string
> 	lenBefore int
> 	lenAfter  int
> ```

countAfter

---

*[posting/index.go, line 250 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrTzB1Uhrn0_O_bVfS:-KnrTzB1Uhrn0_O_bVfT:b-g81xye) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L250)):*
> ```Go
> 
> func updateCount(ctx context.Context, params ucParams) error {
> 	edge := &protos.DirectedEdge{
> ```

`edge := protos.Dire..`

`&edge` below.

---

*[posting/index.go, line 253 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrT05TSsZaiLOKd77n:-KnrT05TSsZaiLOKd77o:b-hlwpc6) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L253)):*
> ```Go
> 		ValueId: params.entity,
> 		Attr:    params.attr,
> 		Label:   "count",
> ```

Stop using labels.

---

*[posting/index.go, line 385 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrSRJ1Oqnc0Y9ODkoB:-KnrSRJ1Oqnc0Y9ODkoC:b-7qz7q5) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L385)):*
> ```Go
> 
> 		if batchSize >= maxBatchSize {
> 			pstore.BatchSet(wb)
> ```

error

---

*[posting/index.go, line 391 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrSRx5ULoWzRhx5MUj:-KnrSRx5ULoWzRhx5MUk:b-7qz7q5) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L391)):*
> ```Go
> 	}
> 	if len(wb) > 0 {
> 		pstore.BatchSet(wb)
> ```

error

---

*[worker/task.go, line 410 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrVv3vOIyYZNjlO1I2:-KnrVv3vOIyYZNjlO1I3:b-ofn9si) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/worker/task.go#L410)):*
> ```Go
> 			reverse: q.Reverse,
> 		}
> 		cp.evaluateThreshold(&out)
> ```

cp.evaluate(&out)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-:-KnrW7_4VwN6NDd1jiI_:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 17 of 19 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[query/query_test.go, line 7173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrahqcitSZTcg4kWEq:-KnrahqcitSZTcg4kWEr:bzel3k4) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/query/query_test.go#L7173)):*
> ```Go
> func TestCountAtRoot(t *testing.T) {
> 	populateGraph(t)
> 	posting.CommitLists(10, 1)
> ```

We should remove these now. Right? since the count keys would be updated along with the mutation, we don't have to wait for it to sync to disk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092)*

**Comment by ashwin95r** [comment]
:lgtm: Just one comment.

---

Review status: 17 of 19 files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-:-KnrbBuhzF7UidV0mFZ7:b-tjkceq)*

**Comment by pawanrawal** [comment]
Review status: 16 of 19 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 147 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrS8wYRt1G9yGG5ZMz:-KnrWoUSpx0YxLbHyUA2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L147)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What is ucParams
</blockquote></details>

Done.

---

*[posting/index.go, line 149 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrS0CzEwEsNUcbRCEr:-KnrWovEYD58WzAO1GnX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L149)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

countBefore
</blockquote></details>

Done.

---

*[posting/index.go, line 150 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrS5A5oXjsyAwjQ_GP:-KnrWpUzW96yMdxyJCuM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L150)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

countAfter
</blockquote></details>

Done.

---

*[posting/index.go, line 250 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrTzB1Uhrn0_O_bVfS:-KnrXF0JrqtmJp0yIW7Q:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L250)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`edge := protos.Dire..`

`&edge` below.
</blockquote></details>

Done.

---

*[posting/index.go, line 253 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrT05TSsZaiLOKd77n:-KnrXMW0iUxMlqOQCR_W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L253)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Stop using labels.
</blockquote></details>

Done.

---

*[posting/index.go, line 385 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrSRJ1Oqnc0Y9ODkoB:-KnrYuBEKcUmXHCQdvzN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L385)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

error
</blockquote></details>

Done.

---

*[posting/index.go, line 391 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrSRx5ULoWzRhx5MUj:-KnrYuhT84DMNQmC-LZp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/posting/index.go#L391)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

error
</blockquote></details>

Done.

---

*[query/query_test.go, line 7173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrahqcitSZTcg4kWEq:-KnriOaN7cmtbJbiHvJf:bfbq995) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/query/query_test.go#L7173)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We should remove these now. Right? since the count keys would be updated along with the mutation, we don't have to wait for it to sync to disk
</blockquote></details>

Good point, done!

---

*[worker/task.go, line 410 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092#-KnrVv3vOIyYZNjlO1I2:-KnrZMeC0yzO5H6KKowL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f9c5c1978e798eb3ccf15e6c7a2f6b2a037ad5d/worker/task.go#L410)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

cp.evaluate(&out)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1092)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
