### PR TITLE
Facets : use quotes for string values

### PR DESCRIPTION
**Pull request by ashishnegi**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/783)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[types/facets/utils.go, line 73 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/783#-KgSOgQKgqfg2LMCw1DQ:-KgSOgQLmtsdX4ynLjGc:b-lrx2gr) ([raw file](https://github.com/dgraph-io/dgraph/blob/8cc74f2077f31db6a518024489845bc05fdd5f36/types/facets/utils.go#L73)):*
> ```Go
> 	}
> 	// strings should be in quotes.
> 	if len(val) >= 2 && val[0] == '"' && val[len(val)-1] == '"' {
> ```

what happens if val == `"`?

---

*[types/facets/utils.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/783#-KgSONEfkY6j4t23x3dp:-KgSONEfkY6j4t23x3dq:b6ph7ak) ([raw file](https://github.com/dgraph-io/dgraph/blob/8cc74f2077f31db6a518024489845bc05fdd5f36/types/facets/utils.go#L79)):*
> ```Go
> 		return int32(intVal), facetsp.Facet_INT32, nil
> 	} else if numErr := err.(*strconv.NumError); numErr.Err == strconv.ErrRange {
> 		// check if we have one . for floating values.
> ```

is the comment misplaced?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/783)*

**Comment by ashishnegi** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[types/facets/utils.go, line 73 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/783#-KgSOgQKgqfg2LMCw1DQ:-KgSToExXH9481BaDLoh:bboqbm) ([raw file](https://github.com/dgraph-io/dgraph/blob/8cc74f2077f31db6a518024489845bc05fdd5f36/types/facets/utils.go#L73)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

what happens if val == `"`?
</blockquote></details>

`"` will give error as it does not satisfy any of facet type.
user can give `"` as facet value by `key1="\""`

---

*[types/facets/utils.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/783#-KgSONEfkY6j4t23x3dp:-KgSd8KWDl_3qoOAGiBB:b-4qlrk) ([raw file](https://github.com/dgraph-io/dgraph/blob/8cc74f2077f31db6a518024489845bc05fdd5f36/types/facets/utils.go#L79)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

is the comment misplaced?
</blockquote></details>

corrected the comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/783)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/783#-:-KgTidwbJ2DYo7gNOt9y:bnfp4nl)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/783#-:-KgX_w--PUfylz8Ki2-C:bnfp4nl)*

**Pull request closed without merging**
