### PR TITLE
Full text search improvements

### PR DESCRIPTION
**Pull request by tzdybal**
Fixes for multiple issues related to full text search:

- improved `fulltext` indexing of values in multiple languages (#752)
- corrected language handling in full text search functions (#771)
- string index type verification (#768)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/781)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query_test.go, line 1981 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/781#-KgNO-O4Kgqw7miynKi5:-KgNO-O5zLiJRnPJGD9H:b-i2nual) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8cb8ad70bcbc0475983f92d7b07111158e57645/query/query_test.go#L1981)):*
> ```Go
> }
> 
> func TestInvalidStringFilter(t *testing.T) {
> ```

Is there a test which is valid? Also wondering what happens if we say `name@hi:en`?

---

*[types/geofilter.go, line 78 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/781#-KgNOBiuhJ7LrjmLaA3Z:-KgNOBiuhJ7LrjmLaA3_:bkih9yt) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8cb8ad70bcbc0475983f92d7b07111158e57645/types/geofilter.go#L78)):*
> ```Go
> 	case "near":
> 		if len(funcArgs) != 4 {
> 			return nil, nil, x.Errorf("near function requires 4 arguments, but got %d",
> ```

The user still needs to pass only 3 args. So this error wouldn;t be right. same for other functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/781)*

**Comment by tzdybal** [comment]
Review status: 8 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 1981 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/781#-KgNO-O4Kgqw7miynKi5:-KgOJ0L_d16CrfLvWnSE:b-u88gnv) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8cb8ad70bcbc0475983f92d7b07111158e57645/query/query_test.go#L1981)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Is there a test which is valid? Also wondering what happens if we say `name@hi:en`?
</blockquote></details>

Most of the other tests are for valid function case (but with `term` tokenizer).  Added a test for valid full text search index to cover all cases.

`name@hi:en` is not allowed in this place. Error is thrown by parser. Created extra test to show this.

---

*[types/geofilter.go, line 78 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/781#-KgNOBiuhJ7LrjmLaA3Z:-KgOJf-WDuI7MfwUkOWw:bar2b7x) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8cb8ad70bcbc0475983f92d7b07111158e57645/types/geofilter.go#L78)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

The user still needs to pass only 3 args. So this error wouldn;t be right. same for other functions.
</blockquote></details>

I've added 1 everywhere  without much attention. Good point about the actual number of args.

All error messages fixed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/781)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/781#-:-KgRZg5wSNy4TsK4HI1j:bnfp4nl)*

**Comment by tzdybal** [comment]
Merged to release branch.

**Pull request closed without merging**
