### PR TITLE
Corrected function handling when no language is specified.

### PR DESCRIPTION
**Pull request by tzdybal**
This is a fix for #1295.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1309)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Just make sure that the `@.` is the tag required for picking any lang.

---

Reviewed 2 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[wiki/content/query-language/index.md, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-KqfV5RAhRAwd3HSd7GC:-KqfV5RBKsCLrlmHe9RX:b-vd58p4) ([raw file](https://github.com/dgraph-io/dgraph/blob/13ff5b906f8c87b29b5168019d6dfae2d868eb99/wiki/content/query-language/index.md#L178)):*
> ```Markdown
> {{% notice "note" %}}In functions, language lists and `.` notation are not allowed.  In functions, a string edge without a language tag means apply function to all languages, while a single language tag means apply to only the given language.{{% /notice %}}
> 
> {{% notice "note" %}}In case of full text search functions (`alloftext`, `anyoftext`), when no language is specified default (English) Full Text Search tokenizer is used.{{% /notice %}}
> ```

is specified, (comma) default ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-:-Kqjn6ep-GYhbFDn7JHp:bjhku8s)*

**Comment by tzdybal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[wiki/content/query-language/index.md, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-KqfV5RAhRAwd3HSd7GC:-Kqu-LssugPbDTV6PRrL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/13ff5b906f8c87b29b5168019d6dfae2d868eb99/wiki/content/query-language/index.md#L178)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

is specified, (comma) default ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[query/query_test.go, line 6685 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu3mJhFDYA0a7slLPt:-Kqu3mJhFDYA0a7slLPu:b-c1qevi) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/query/query_test.go#L6685)):*
> ```Go
> 	// this case is not trivial, because farmhash of "en" is less than farmhash of "fr"
> 	// so we need to iterate over values in all languages to find a match
> 	// for alloftext, this won't work - we use default/English tokenizer for function parameters,
> ```

we use default/English tokenizer when no language is specified.

---

*[worker/stringfilter.go, line 91 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu2ZKcsBZ6R3E6NuC5:-Kqu2ZKcsBZ6R3E6NuC6:b-8d0n8) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/worker/stringfilter.go#L91)):*
> ```Go
> 		}
> 		return false
> 	} else {
> ```

Can get rid of this else, since you are returning in the `if` above. 
Actually you can handle the smaller `len(filter.eqVals) == 0` block first and then the bigger block doesn't need to be indented. 

---

*[worker/task.go, line 502 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu2yE1kYECx3p9G-3v:-Kqu2yE1kYECx3p9G-3w:b-e201pc) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/worker/task.go#L502)):*
> ```Go
> 
> 	// For string matching functions, check the language.
> 	if (srcFn.fnType == StandardFn || srcFn.fnType == HasFn ||
> ```

This if condition probably needs its own function?

---

*[worker/task.go, line 664 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu0HoT51_oST6YDnE2:-Kqu0HoT51_oST6YDnE3:b-fkk6qw) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/worker/task.go#L664)):*
> ```Go
> 					return false
> 				default:
> 					langs := []string{arg.srcFn.lang}
> ```

What happens when user gives something like `name@en:hi:.` in functions. Do we give an error or just parse the first language?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309)*

**Comment by tzdybal** [comment]
Review status: 2 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/query_test.go, line 6685 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu3mJhFDYA0a7slLPt:-Kqu4_LcJh2CGx4YUd3i:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/query/query_test.go#L6685)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

we use default/English tokenizer when no language is specified.
</blockquote></details>

Done

---

*[worker/stringfilter.go, line 91 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu2ZKcsBZ6R3E6NuC5:-Kqu7KQ8YHH3uotbVoJx:b-gdrfa7) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/worker/stringfilter.go#L91)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can get rid of this else, since you are returning in the `if` above. 
Actually you can handle the smaller `len(filter.eqVals) == 0` block first and then the bigger block doesn't need to be indented. 
</blockquote></details>

Cyclomatic complexity reduced.

---

*[worker/task.go, line 502 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu2yE1kYECx3p9G-3v:-Kqu6wwirYDLAxLqMcR0:b5pone0) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/worker/task.go#L502)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This if condition probably needs its own function?
</blockquote></details>

Good idea. Function introduced.

---

*[worker/task.go, line 664 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-Kqu0HoT51_oST6YDnE2:-Kqu5D4NeF_Wa5cHD-Bk:bkggjqq) ([raw file](https://github.com/dgraph-io/dgraph/blob/68cefd5b9d269d473d3449f875d20977aa5f4550/worker/task.go#L664)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What happens when user gives something like `name@en:hi:.` in functions. Do we give an error or just parse the first language?
</blockquote></details>

We return error, it's tested in `gql/parser_test.go` in `TestLangsFunctionMultipleLangs`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1309#-:-Kqu9TI28BAOo71NNfbY:bnfp4nl)*

**Comment by tzdybal** [comment]
Merged to master.

**Pull request closed without merging**
