### PR TITLE
Return shortest path subgraph with full info

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/667)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query_test.go, line 585 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYFSoQBJAdARA0f81p:-KeYFSoR9-sPfC4Nk2oJ:bbo9prk) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/query_test.go#L585)):*
> ```Go
> 	js := processToFastJSON(t, query)
> 	require.JSONEq(t,
> 		`{"_path_":[{"_uid_":"0x1","path":[{"@facets":{"_":{"weight":0.100000}},"_uid_":"0x1f","path":[{"@facets":{"_":{"weight":0.100000}},"_uid_":"0x3e8","path":[{"@facets":{"_":{"weight":0.100000}},"_uid_":"0x3e9","path":[{"@facets":{"_":{"weight":0.100000}},"_uid_":"0x3ea"}]}]}]}]}],"me":[{"name":"Michonne"},{"name":"Andrea"},{"name":"Alice"},{"name":"Bob"},{"name":"Matt"}]}`,
> ```

will vector have one child always ?

---

*[query/query_test.go, line 622 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYGzZYAh6eBdzuzGod:-KeYGzZZrbHox_aPPMDf:b-pm8s44) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/query_test.go#L622)):*
> ```Go
> 	js := processToFastJSON(t, query)
> 	require.JSONEq(t,
> 		`{"_path_":[{"_uid_":"0x1","path":[{"_uid_":"0x1f","path":[{"_uid_":"0x3e8","path":[{"_uid_":"0x3ea","path":[{"_uid_":"0x3eb"}]}]}]}]}],"me":[{"name":"Michonne"},{"name":"Andrea"},{"name":"Alice"},{"name":"Matt"},{"name":"John"}]}`,
> ```

will it not be much easier for client to process a vector with elements having nodes of path..
`_path_[0] -> _path_[1] -> _path_[2] -> ... destination` ?
rather than nested structure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/667)*

**Comment by ashishnegi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/shortest.go, line 356 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYJ1mXWu_9Yqu7avxX:-KeYJ1mYiqkBtIfd_qLp:bj7icxi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/shortest.go#L356)):*
> ```Go
> 	sg.DestUIDs.Uids = result
> 
> 	shortestSG := new(SubGraph)
> ```

moving to a new function might be helpful.. :)

---

*[query/shortest.go, line 377 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYNVxfA5A28B-0zWat:-KeYNVxgiGz_VEXOUqFw:b-r9cyrg) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/shortest.go#L377)):*
> ```Go
> 		if nodeInfo.facet != nil {
> 			// For consistent later processing.
> 			node.Params.Facet = &facets.Param{}
> ```

node.Params.Facet = sg.Params.Facet ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/667)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 585 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYFSoQBJAdARA0f81p:-Kea6KzKoPTGOUPQgctt:b-dpodxi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/query_test.go#L585)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

will vector have one child always ?
</blockquote></details>

You mean the path? yes, One child per node.

---

*[query/query_test.go, line 622 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYGzZYAh6eBdzuzGod:-Kea6QzbpnRaNds7Bz4w:bie8m29) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/query_test.go#L622)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

will it not be much easier for client to process a vector with elements having nodes of path..
`_path_[0] -> _path_[1] -> _path_[2] -> ... destination` ?
rather than nested structure.
</blockquote></details>

We also return that in a variable. But in order to return the edge information, we add this extra nested structure.

---

*[query/shortest.go, line 356 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYJ1mXWu_9Yqu7avxX:-Kea7G-B4saF5a6K-tH6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/shortest.go#L356)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

moving to a new function might be helpful.. :)
</blockquote></details>

Done.

---

*[query/shortest.go, line 377 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KeYNVxfA5A28B-0zWat:-Kea7HiFliDiUgdgHIeM:ba2z2af) ([raw file](https://github.com/dgraph-io/dgraph/blob/d525438260616080c84295913e37d82227f63283/query/shortest.go#L377)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

node.Params.Facet = sg.Params.Facet ??
</blockquote></details>

sg.Params.Facet would be empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/667)*

**Comment by ashishnegi** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-:-KeahWpGvRpWSpelifHG:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm: Address comments before submitting.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 607 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KebXE-h4s33tqH2s-iU:-KebXE-h4s33tqH2s-iV:b-9390zn) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef94cbd0b94101d704dbbcfaa4bfa3a83c718bc2/query/query.go#L607)):*
> ```Go
> 	var debug bool
> 	// gRPC client passes information about debug as metadata.
> 	if md, ok := metadata.FromContext(ctx); ok {
> ```

Why not as part of the context itself, so we can access it as ctx.Value("debug")?

---

*[query/query.go, line 802 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KebYIaXAbz3Y3pDou-6:-KebYIaXAbz3Y3pDou-7:b-u546rg) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef94cbd0b94101d704dbbcfaa4bfa3a83c718bc2/query/query.go#L802)):*
> ```Go
> 	}
> 
> 	var shortestSg *SubGraph
> ```

It's shortestSg with small g here. Other places it's shortestSG, with capital G. Be consistent. Use small g everywhere.

---

*[query/shortest.go, line 69 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KebXgPPpfKKUZiGFH2P:-KebXgPQGxJOQOHETfcx:b2kbtc5) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef94cbd0b94101d704dbbcfaa4bfa3a83c718bc2/query/shortest.go#L69)):*
> ```Go
> 	cost := 1.0
> 	if sg.Params.Facet == nil {
> 		return cost, nil, nil
> ```

Might be better to set variables in the function return; and just do return here. Go will automatically pick up the values of these vars and return them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-:-KebYSCwBZsieEWzIXcp:b533za0)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 607 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KebXE-h4s33tqH2s-iU:-Keb_QWI07D0dPhG-1Pj:b-pwx9tu) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef94cbd0b94101d704dbbcfaa4bfa3a83c718bc2/query/query.go#L607)):*
> Why not as part of the context itself, so we can access it as ctx.Value("debug")?
gRPC allows passing data only using metadata. Hence we have this I suppose
@pawanrawal 
https://github.com/grpc/grpc-go/issues/130

---

*[query/query.go, line 802 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KebYIaXAbz3Y3pDou-6:-KebZISndKAlmVm-il6t:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef94cbd0b94101d704dbbcfaa4bfa3a83c718bc2/query/query.go#L802)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

It's shortestSg with small g here. Other places it's shortestSG, with capital G. Be consistent. Use small g everywhere.
</blockquote></details>

Done.

---

*[query/shortest.go, line 69 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KebXgPPpfKKUZiGFH2P:-KebZuS2jD10hrYGo5TZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef94cbd0b94101d704dbbcfaa4bfa3a83c718bc2/query/shortest.go#L69)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Might be better to set variables in the function return; and just do return here. Go will automatically pick up the values of these vars and return them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/667)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query.go, line 613 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-KefLgzbcUVOC3wVhJv1:-KefLgzcXpUnsY90f6uZ:bcr7q8r) ([raw file](https://github.com/dgraph-io/dgraph/blob/a79b7623afc87408fd2247882ceb32c3f84fb55c/query/query.go#L613)):*
> ```Go
> 	// HTTP passes information about debug as query parameter which is attached to context.
> 	return debug || ctx.Value("debug") == "true"
> ```

Remove vertical space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/667#-:-KefLqxUejpu7tCBCyda:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
