### PR TITLE
feat(GraphQL): fix multiple alias in query

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6945)

### CODE REVIEW

**Review by vmrajas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6945)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vmrajas)

___
*[graphql/resolve/query_rewriter.go, line 1103 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6945#-MMp1eIR4OU6RyurwHzI:-MMp1eIR4OU6RyurwHzJ:bbl9ojv) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f00ff8f1814cad08f8d20aa3926fd1be8dd2db8/graphql/resolve/query_rewriter.go#L1103)):*
> ```Go
> 
> 		// Handle aggregation queries
> 		if f.IsAggregateField() {
> ```

Add an if condition checking if the field has already been seen (fieldSeenCount > 0) , then continue.

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6945)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton, @pawanrawal, and @vmrajas)

___
*[graphql/resolve/query_rewriter.go, line 1103 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6945#-MMp1eIR4OU6RyurwHzI:-MMp3_FZ358yRfs8-fsF:buc71sy) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f00ff8f1814cad08f8d20aa3926fd1be8dd2db8/graphql/resolve/query_rewriter.go#L1103)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Add an if condition checking if the field has already been seen (fieldSeenCount > 0) , then continue. 
</blockquote></details>

Not necessary here as discussed on the call.

**Comment by danielmai** [comment]
Same commit is in #6951. Closing.

**Review by MichaelJCompton — COMMENTED** [review]
Looks ok.  My only question is about ensuring that those generated names don't collide with something already in the type.

For example if a type contained both posts and posts1 already, then there can be a clash.

Did you consider including a separation character that's legal in Dgraph, but not in GraphQL ( '.' for example) that way you can be sure there is never a clash.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6945#-:-MMr5diu45jJXkdLbpDS:b8uo7kn)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vmrajas)

___
*[graphql/resolve/query_test.yaml, line 2505 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6945#-MMr3dOB67Git5qpiBua:-MMr3dOB67Git5qpiBub:bgvlrnm) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f00ff8f1814cad08f8d20aa3926fd1be8dd2db8/graphql/resolve/query_test.yaml#L2505)):*
> ```YAML
>       queryAuthor(func: type(Author)) {
>         name : Author.name
>         posts : Author.posts @filter(eq(Post.isPublished, true)) {
> ```

how do we know these new names don't collide with something that's already in the query?
___
*[graphql/resolve/query_test.yaml, line 2558 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6945#-MMr3Wny59o0N_V_dOB-:-MMr3Wny59o0N_V_dOB0:b-3pq7dg) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f00ff8f1814cad08f8d20aa3926fd1be8dd2db8/graphql/resolve/query_test.yaml#L2558)):*
> ```YAML
>       queryAuthor {
>         name
>         p1: posts(filter: {isPublished: true}){
> ```

is this case legal in GraphQL ??

**Pull request closed without merging**
