### PR TITLE
Move functions and tokenization to worker

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/334)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 6 files reviewed at latest revision, 19 unresolved discussions.

---

*[task/task.proto, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5Cxf959uRwYSB8-w:-KXF5Cxf959uRwYSB8-x:b-csswlh) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/task/task.proto#L26)):*
> ```protobuf
> 	
> 	// Function to generate or filter UIDs.
> 	repeated string srcFunc = 7;
> ```

src_func. I think proto is snake case.

---

*[task/task.proto, line 33 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5Q8sQRu4ZriBKmUm:-KXF5Q8sQRu4ZriBKmUn:b3frp7u) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/task/task.proto#L33)):*
> ```protobuf
> 	repeated Value values = 2;
> 	repeated uint32 counts = 3;
> 	List destUids = 4;
> ```

We can avoid returning this over the network right, if it can be derived from uidMatrix. Or, if we dont' need uidMatrix, then we can just have uidMatrix with a single element.

---

*[worker/tokens.go, line 9 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5dqDAwyWBlppZddM:-KXF5dqEBz9cLNUTGwBP:bptve2i) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/worker/tokens.go#L9)):*
> ```Go
> )
> 
> func getTokens(Func []string) (*geo.QueryType, []string, bool, error) {
> ```

Args []string, or funcArgs []string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 19 unresolved discussions.

---

*[task/task.proto, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5Cxf959uRwYSB8-w:-KXF7VnLM7bW-kOxNpx9:b-iw471l) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/task/task.proto#L26)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> src_func. I think proto is snake case.
</details>
We do have uidMatrix, afterUid, doCount etc. So I think its okay?

---

*[task/task.proto, line 33 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5Q8sQRu4ZriBKmUm:-KXF8hzh__vHzNYlFbND:b-e8o55d) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/task/task.proto#L33)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> We can avoid returning this over the network right, if it can be derived from uidMatrix. Or, if we dont' need uidMatrix, then we can just have uidMatrix with a single element.
</details>
Returning if we have to intersect or merge. Done.

---

*[worker/tokens.go, line 9 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5dqDAwyWBlppZddM:-KXF7Na5Ia1hxIyp3H71:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/worker/tokens.go#L9)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Args []string, or funcArgs []string
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[task/task.proto, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5Cxf959uRwYSB8-w:-KXFAP9p4DLEHUSbu0ot:bje1e5i) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/task/task.proto#L26)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> We do have uidMatrix, afterUid, doCount etc. So I think its okay?
</details>
oh.. didn't realize. Can you please change them all? 
https://developers.google.com/protocol-buffers/docs/style

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-:-KXFAejtRMNdWYRk-cCZ:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: 1 of 6 files reviewed at latest revision, 18 unresolved discussions.

---

*[worker/tokens.go, line 9 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXFB1ZGUiEHydtwfDgf:-KXFB1ZGUiEHydtwfDgg:bwqd4fi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d06b78c5e7ab027a78050bdb73202f50c485d375/worker/tokens.go#L9)):*
> ```Go
> )
> 
> func getTokens(funcArgs []string) (*geo.QueryType, []string, bool, error) {
> ```

This functions returns too many results. It should only return tokens, nothing else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334)*

**Comment by ashwin95r** [comment]
Review status: 1 of 6 files reviewed at latest revision, 18 unresolved discussions.

---

*[task/task.proto, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5Cxf959uRwYSB8-w:-KXFC7TZjg9pJYw2j69p:b-tne168) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/task/task.proto#L26)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> oh.. didn't realize. Can you please change them all? 
> https://developers.google.com/protocol-buffers/docs/style
</details>
Will do in a separate PR, might lead to lot of changed files. https://app.asana.com/0/110655897041979/218116851736182

---

*[worker/tokens.go, line 9 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXFB1ZGUiEHydtwfDgf:-KXFD6jy_AEXkD4rKEao:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d06b78c5e7ab027a78050bdb73202f50c485d375/worker/tokens.go#L9)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This functions returns too many results. It should only return tokens, nothing else.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334)*

**Comment by jchiu0** [comment]
:lgtm:  My only reservation is that could it be that in the future some generating function might need to call different workers / use different predicates. Otherwise, PR looks good.

---

Review status: 1 of 6 files reviewed at latest revision, 18 unresolved discussions.

---

*[task/task.proto, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXF5Cxf959uRwYSB8-w:-KXFYdCreiStfLwI13jV:bre05xi) ([raw file](https://github.com/dgraph-io/dgraph/blob/118da06b1760908bc465cfdc610f262c4fe66664/task/task.proto#L26)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Will do in a separate PR, might lead to lot of changed files. https://app.asana.com/0/110655897041979/218116851736182
</details>
My bad about the case. Wrote too much Go..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-:-KXFZFWBphvSIIKu47kF:bnzhmuh)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[worker/tokens.go, line 9 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXGH7SxbhTdUfvolHcj:-KXGH7SxbhTdUfvolHck:b-i6xw7z) ([raw file](https://github.com/dgraph-io/dgraph/blob/5371fe7fb57acb26f84bcf548fc028b5aafcd2dc/worker/tokens.go#L9)):*
> ```Go
> 
> func getTokens(funcArgs []string) ([]string, error) {
> 	x.AssertTruef(len(funcArgs) > 1, "Invalid function")
> ```

len == 2 right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-:-KXGHVeCyD2-r_EembIo:bnfp4nl)*

**Comment by ashwin95r** [comment]
Thanks!

---

Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[worker/tokens.go, line 9 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-KXGH7SxbhTdUfvolHcj:-KXGbmlwSGuJsm-TG0dX:b-t4uvmd) ([raw file](https://github.com/dgraph-io/dgraph/blob/5371fe7fb57acb26f84bcf548fc028b5aafcd2dc/worker/tokens.go#L9)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> len == 2 right?
</details>
Yeah for now. For geo it'd be > 1. Will send a PR soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/334#-:-KXGcDWzp-rfg38D65Hk:b-ucfknh)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
