### PR TITLE
feat(graphql): Introducing Nested Filtering for Dgraph GraphQL API with Optimized Query Support

### PR DESCRIPTION
**Pull request by iyinoluwaayoola**
**Description:**

This merge request introduces Nested Filtering to the Dgraph GraphQL API. It allows for comprehensive filtering capabilities that span across queries, aggregations, and authorization functions.

**How Does It Work?**

Nested Filtering leverages Dgraph's `var` block to filter nested objects and selects parent objects through inverse predicates. To enable nested filtering, you need to add the `@search` directive to the nested field (edge) without any arguments. 

Example:

```graphql
type User {
    name: String @search(by: [hash])
    friends: [User] @hasInverse(field: friends) @search
}
```

Given the schema above, you can query users who have friends named "Ben" using the following query:

```graphql
query {
    queryUser(filter: { friends: { name: { eq: "Ben" } } }) {
        name
    }
}
```

**Schema Validation:**

If the `@search` directive is added to an edge, the `@hasInverse` directive must also be set on one of the referenced fields. This validation process includes handling interface fields by checking the implemented types for reverse fields.

**Testing:**

Testing has been conducted locally, showing approximately 50% fewer scanned nodes

**Docs**
RFC -> https://discuss.dgraph.io/t/rfc-nested-filters-in-graphql/13560/37

### CODE REVIEW

**Comment by harshil-goel** [comment]
Can you add some test cases in e2e folder, and one in query_rewriter?

**Comment by iyinoluwaayoola** [comment]
Hi @harshil-goel , added auth to the nested query filters along with a few test cases.

**Comment by iyinoluwaayoola** [comment]
I see an opportunity to improve the auth queries by storing them per type and reusing them each time. This way, if a type is selected multiple times within the same request, we can reuse the auth variable and reduce the number of scans.

**Comment by iyinoluwaayoola** [comment]
Hi @harshil-goel , can you please provide feedback or review in getting this merged? I see some CI failures, but unsure if they are related to the change.

**Comment by mangalaman93** [comment]
closing this PR due to inactivity.

**Comment by iyinoluwaayoola** [comment]
Hi @mangalaman93 @harshil-goel , I'm resuming activities here, please re-open.

**Pull request closed without merging**
