### PR TITLE
Add version flag

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/156)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[x/x.go, line 45 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r1-45:-KOnXNu6PtaaGNmi528f:b-8e159v) ([raw file](https://github.com/dgraph-io/dgraph/blob/2413d6dd4b951b2f8b86be87cedd2f7fbe593eff/x/x.go#L45)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> don't use ALL_CAPS in Go names; use CamelCase
</details>
@ashwin95r Can you please tackle this as well?

---

*[x/x.go, line 49 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r1-49:-KOnXQm0wels8zUl0AeA:bjk6oun) ([raw file](https://github.com/dgraph-io/dgraph/blob/2413d6dd4b951b2f8b86be87cedd2f7fbe593eff/x/x.go#L49)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported var Version should have comment or be unexported
</details>
And this. In fact, does this have to be capital?

---

*[x/x.go, line 65 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r1-65:-KOnXrK5njC5kW2yuhAF:b-gtgba3) ([raw file](https://github.com/dgraph-io/dgraph/blob/2413d6dd4b951b2f8b86be87cedd2f7fbe593eff/x/x.go#L65)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function PrintVersion should have comment or be unexported
</details>
Address the houndci comment. Also, you can check the flag value here, print the version if required, and return a boolean to indicate if the program should continue or not.

Callers might be something like:
```
if ok := x.PrintVersionOnly(); ok {
  return
}
```

Also, notice that version information is a great way to educate the users. For e.g.
```
$ gpg --version                                                                                                    ~
gpg (GnuPG) 2.1.14
libgcrypt 1.7.2
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/mrjn/.gnupg
```

You can tell the users about copyright. And also mention the wiki for documentation. Make it look nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/156)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

*[x/x.go, line 45 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r1-45:-KOnkdRjgRJQaEKrJXCP:b-ti21q4) ([raw file](https://github.com/dgraph-io/dgraph/blob/2413d6dd4b951b2f8b86be87cedd2f7fbe593eff/x/x.go#L45)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> @ashwin95r Can you please tackle this as well?
</details>
Does this look fine?

---

*[x/x.go, line 49 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r1-49:-KOn_Vu-i9uaLElqBehJ:b8ntzie) ([raw file](https://github.com/dgraph-io/dgraph/blob/2413d6dd4b951b2f8b86be87cedd2f7fbe593eff/x/x.go#L49)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> And this. In fact, does this have to be capital?
</details>
Contained within the package. Done.

---

*[x/x.go, line 65 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r1-65:-KOnhDAXTsgBf6zUuW35:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2413d6dd4b951b2f8b86be87cedd2f7fbe593eff/x/x.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Address the houndci comment. Also, you can check the flag value here, print the version if required, and return a boolean to indicate if the program should continue or not.
> 
> Callers might be something like:
> ```
> if ok := x.PrintVersionOnly(); ok {
>   return
> }
> ```
> 
> Also, notice that version information is a great way to educate the users. For e.g.
> ```
> $ gpg --version                                                                                                    ~
> gpg (GnuPG) 2.1.14
> libgcrypt 1.7.2
> Copyright (C) 2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Home: /home/mrjn/.gnupg
> ```
> 
> You can tell the users about copyright. And also mention the wiki for documentation. Make it look nice!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/156)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[x/x.go, line 35 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r2-35:-KOnxDuj9rAkHmA5eImw:bb7dd1n) ([raw file](https://github.com/dgraph-io/dgraph/blob/df69a258db689d164fa8c0a2874226d6ccfb6900/x/x.go#L35)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> don't use underscores in Go names; const E_Ok should be EOk<br>exported const E_Ok should have comment (or a comment on this block) or be unexported
</details>
Should I handle these comments? @manishrjain 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/156)*

**Comment by manishrjain** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[x/x.go, line 45 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r1-45:-KOnymdvBNjlHsA9t8Mc:b-1skrim) ([raw file](https://github.com/dgraph-io/dgraph/blob/2413d6dd4b951b2f8b86be87cedd2f7fbe593eff/x/x.go#L45)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Does this look fine?
</details>
Yup. Actually, I just checked. It's not being used. You can remove it.

---

*[x/x.go, line 35 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r2-35:-KOny-LxvzBSlDD5ivc9:blrftt2) ([raw file](https://github.com/dgraph-io/dgraph/blob/df69a258db689d164fa8c0a2874226d6ccfb6900/x/x.go#L35)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Should I handle these comments? @manishrjain 
</details>
Yeah, would be great to do as much clean up as possible. Btw, E_Ok isn't ideal. Try ErrorOk. ErrorInvalidMethod, ErrorNoData etc.

---

*[x/x.go, line 46 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnyqK3Hfrg1TZTDvYW:-KOnyqK3Hfrg1TZTDvYX:bufucq) ([raw file](https://github.com/dgraph-io/dgraph/blob/588ef2810e14e85e7daff4446cc41f5a0318ca03/x/x.go#L46)):*
> ```Go
> 
> 	DummyUUID     = "00000000-0000-0000-0000-000000000000"
> 	DgraphVersion = "0.4.2"
> ```

Does this need to be exported?

---

*[x/x.go, line 72 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnyNaDlcyU563QGy0T:-KOnyNaDlcyU563QGy0U:b-si6xmk) ([raw file](https://github.com/dgraph-io/dgraph/blob/588ef2810e14e85e7daff4446cc41f5a0318ca03/x/x.go#L72)):*
> ```Go
> 		fmt.Println("\nCopyright 2016 Dgraph Labs, Inc.")
> 		fmt.Println("Licensed under the Apache License, Version 2.0")
> 		fmt.Println("\nFor more information on Dgraph, visit: https://wiki.dgraph.io")
> ```

For Dgraph official documentation, visit https://wiki.dgraph.io.

Without the colon, and with a full stop at end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/156)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[x/x.go, line 35 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnF_PlpPMzrJw9_6M_-r2-35:-KOo0QlQnNvwoS-uy_uD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/df69a258db689d164fa8c0a2874226d6ccfb6900/x/x.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Yeah, would be great to do as much clean up as possible. Btw, E_Ok isn't ideal. Try ErrorOk. ErrorInvalidMethod, ErrorNoData etc.
</details>
Done.

---

*[x/x.go, line 46 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnyqK3Hfrg1TZTDvYW:-KOo0YEkRvy2jLt3DaXy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/588ef2810e14e85e7daff4446cc41f5a0318ca03/x/x.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Does this need to be exported?
</details>
Done.

---

*[x/x.go, line 72 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-KOnyNaDlcyU563QGy0T:-KOo0aKcHGtUtG8NUN3K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/588ef2810e14e85e7daff4446cc41f5a0318ca03/x/x.go#L72)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> For Dgraph official documentation, visit https://wiki.dgraph.io.
> 
> Without the colon, and with a full stop at end.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/156)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/156#-:-KOoLaaat_iijo-vE14t:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to develop with commit dc94fca0821a423cb70c66980d69c360d4c50a68

**Pull request closed without merging**
