### PR TITLE
perf(codec): Use z.Allocator to optimize memory usage

### PR DESCRIPTION
**Pull request by manishrjain**
This PR prints out whether a Dgraph version is using jemalloc or not.
Uses map[uint64]uint64 for Zero keyConflict map to decrease memory usage.
Uses z.Allocator for codec.Encode, to speed up the allocations and optimize memory usage.
Allocators are now put into a singleton map, so we can reference them via integers. This helps keep track of them across various UidPack objects.
Compose tool now allows specifying a limit on the memory usage by the dgraph containers.
Track predicate move task just like snapshot and others.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6452)

### CODE REVIEW

**Review by martinmr — APPROVED** [review]
some minor comments but it :lgtm: 

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-:-MHEYd2gE2dFs8aCCx-v:b-mtbx1k)* status: all files reviewed, 3 unresolved discussions (waiting on @manishrjain and @vvbalaji-dgraph)

___
*[codec/codec.go, line 120 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHEYGBBCF4rj2Ih_mPc:-MHEYGBBCF4rj2Ih_mPd:b2yb5wf) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/codec/codec.go#L120)):*
> ```Go
> 		e.pack = &pb.UidPack{BlockSize: uint32(e.BlockSize)}
> 		e.alloc = z.NewAllocator(1024)
> 		e.alloc.Tag = tagEncoder
> ```

maybe add a comment on what this does because this value is not being used elsewhere in this file.
___
*[dgraph/cmd/zero/oracle.go, line 82 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHEXdCb2pqsiTLjqndT:-MHEXdCc4vng957i5SR7:b-rvw8hf) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/dgraph/cmd/zero/oracle.go#L82)):*
> ```
> ki, err := strconv.ParseUint(k, 36, 64)
> ```
why is this using base 36?
___
*[dgraph/cmd/zero/oracle.go, line 125 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHEXhdl8Ew9rysqbL0c:-MHEXhdl8Ew9rysqbL0d:br5tf89) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/dgraph/cmd/zero/oracle.go#L125)):*
> ```Go
> 	}
> 	for _, k := range src.Keys {
> 		ki, err := strconv.ParseUint(k, 36, 64)
> ```

same question here.

**Review by jarifibrahim — COMMENTED** [review]
Some comments

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-:-MHGBUH5-b-0JAr-2WYa:bv6hrbv)* status: all files reviewed, 10 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[go.mod, line 5 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG6PPQ2aUrviAb8iik:-MHG6PPR5SjDP9wDcC6T:b-3j7nob) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/go.mod#L5)):*
> ```XML
> go 1.12
> 
> replace github.com/dgraph-io/ristretto => /home/mrjn/go/src/github.com/dgraph-io/ristretto
> ```

This should be removed. 
___
*[go.mod, line 25 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHGBXND1LAKg6JPtYmX:-MHGBXND1LAKg6JPtYmY:b-kp7f54) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/go.mod#L25)):*
> ```XML
> 	github.com/dgraph-io/dgo/v200 v200.0.0-20200805103119-a3544c464dd6
> 	github.com/dgraph-io/graphql-transport-ws v0.0.0-20200715131837-c0460019ead2
> 	github.com/dgraph-io/ristretto v0.0.4-0.20200914131613-034d03c09d58
> ```

This should be latest ristretto (after the tag and ref PR is merged).
___
*[go.sum, line 97 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG6Un3-plhWUjAKxwH:-MHG6Un3-plhWUjAKxwI:bvelihl) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/go.sum#L97)):*
> ```
> github.com/dgraph-io/ristretto v0.0.4-0.20200906165740-41ebdbffecfd h1:KoJOtZf+6wpQaDTuOWGuo61GxcPBIfhwRxRTaTWGCTc=
> github.com/dgraph-io/ristretto v0.0.4-0.20200906165740-41ebdbffecfd/go.mod h1:YylP9MpCYGVZQrly/j/diqcdUetCRRePeBB0c2VGXsA=
> github.com/dgraph-io/ristretto v0.0.4-0.20200909123249-578ecae67870 h1:PA5U+Wr71h2zaHjA6aeL3dUjgVmF+rHDpGjnWM5Ope0=
> ```

`go mod tidy`, please
___
*[codec/codec.go, line 50 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG7RMK3XNgo0ePUYKK:-MHG7RMK3XNgo0ePUYKL:b-av2khr) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/codec/codec.go#L50)):*
> ```Go
> 	uids      []uint64
> 	alloc     *z.Allocator
> 	buf       *bytes.Buffer
> ```

why not z.buffer?
___
*[compose/compose.go, line 448 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG8UZQE-3rY7wARvzF:-MHG8UZR7L17sWBVVIb-:b1rjy1o) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/compose/compose.go#L448)):*
> ```Go
> 		"Port to expose Ratel service")
> 	cmd.PersistentFlags().StringVarP(&opts.MemLimit, "mem", "", "",
> 		"Limit memory provided to the docker containers")
> ```

Is this in bytes? would `4G` thing work here as well?
___
*[dgraph/cmd/zero/oracle.go, line 82 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHEXdCb2pqsiTLjqndT:-MHG9Be-C4rX6iUqNSgV:b-rycjvn) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/dgraph/cmd/zero/oracle.go#L82)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

> ```
> ki, err := strconv.ParseUint(k, 36, 64)
> ```
why is this using base 36?
</blockquote></details>

Are src.Keys uint64 integers? If so, why do we store uint64 as strings?
___
*[posting/list.go, line 908 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHGAOZB7Sb2UbcPDMbp:-MHGAOZB7Sb2UbcPDMbq:bow7blx) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/posting/list.go#L908)):*
> ```Go
> 	x.Check(err)
> 	if plist.Pack != nil {
> 		plist.Pack.Allocator = alloc
> ```

There are a bunch of places where we do `list.Marshal()`, don't we need the same code everywhere?

```
dgraph/cmd/bulk/count_index.go|148 col 19| data, err := pl.Marshal()
dgraph/cmd/bulk/reduce.go|694 col 19| val, err := pl.Marshal()
posting/list.go|549 col 19| data, err := pl.Marshal()
posting/list.go|909 col 21| data, err := plist.Marshal()
posting/list_test.go|1088 col 21| data, err := part.Marshal()
posting/mvcc_test.go|87 col 21| data, err := empty.Marshal()
protos/pb/pb.pb.go|8719 col 23| func (m *PostingList) Marshal() (dAtA []byte, err error) {
worker/restore.go|179 col 28| restoreVal, err := pl.Marshal()
```
___
*[worker/predicate_move.go, line 231 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHGAyyV5wJZUVSHhMyP:-MHGAyyV5wJZUVSHhMyQ:b-k347ag) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/worker/predicate_move.go#L231)):*
> ```Go
> func movePredicateHelper(ctx context.Context, in *pb.MovePredicatePayload) error {
> 	// Note: Manish thinks it *should* be OK for a predicate receiver to not have to stop other
> 	// operations like snapshots and rollups.
> ```

This comment looks misleading to me. We're starting a task here which would stop the rollups and I see `ReceivePredicate` call 5 lines below.

What am I missing?

**Review by danielmai — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-:-MHGtvME6emklHKu-kWh:bg7igkv)* status: all files reviewed, 10 unresolved discussions (waiting on @jarifibrahim, @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[go.mod, line 25 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHGBXND1LAKg6JPtYmX:-MHGocvB4OmC0fQCFoMa:b-hottry) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/go.mod#L25)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

This should be latest ristretto (after the tag and ref PR is merged).
</blockquote></details>

I see that the latest Ristretto master https://github.com/dgraph-io/ristretto/commit/5635329445204b4fcffd0eaf8545868b50e115ec has the LDFLAGS change.

```
go get github.com/dgraph-io/ristretto@5635329445204b4fcffd0eaf8545868b50e115ec
```

**Review by jarifibrahim — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-:-MHH8m2n-idhiYK2qXnq:bnfp4nl)* status: 6 of 16 files reviewed, 10 unresolved discussions (waiting on @jarifibrahim, @manishrjain, @martinmr, and @vvbalaji-dgraph)

**Review by manishrjain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6452)* status: 2 of 17 files reviewed, 10 unresolved discussions (waiting on @jarifibrahim, @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[go.mod, line 5 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG6PPQ2aUrviAb8iik:-MHH1zPN7PFrRzZjIZ7p:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/go.mod#L5)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

This should be removed. 
</blockquote></details>

Done
___
*[go.mod, line 25 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHGBXND1LAKg6JPtYmX:-MHH2DSkBQylzqKUZ4OX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/go.mod#L25)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

I see that the latest Ristretto master https://github.com/dgraph-io/ristretto/commit/5635329445204b4fcffd0eaf8545868b50e115ec has the LDFLAGS change.

```
go get github.com/dgraph-io/ristretto@5635329445204b4fcffd0eaf8545868b50e115ec
```
</blockquote></details>

Done.
___
*[go.sum, line 97 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG6Un3-plhWUjAKxwH:-MHH2ICAAlsw2cG79tXM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/go.sum#L97)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

`go mod tidy`, please
</blockquote></details>

Done.
___
*[codec/codec.go, line 50 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG7RMK3XNgo0ePUYKK:-MHH2Kp6Dqtn0rk2aXYb:bj0h3ey) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/codec/codec.go#L50)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

why not z.buffer?
</blockquote></details>

So, we can reuse this over and over again. Avoid Calloc calls.
___
*[codec/codec.go, line 120 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHEYGBBCF4rj2Ih_mPc:-MHH2Yfk5slxbEsor_Zn:bj5zvzz) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/codec/codec.go#L120)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

maybe add a comment on what this does because this value is not being used elsewhere in this file.
</blockquote></details>

This is useful for debugging purposes.
___
*[compose/compose.go, line 448 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHG8UZQE-3rY7wARvzF:-MHH3RYl8Q9iOE_RBnEg:b-fp73re) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/compose/compose.go#L448)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Is this in bytes? would `4G` thing work here as well?
</blockquote></details>

Yes, it does.
___
*[dgraph/cmd/zero/oracle.go, line 82 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHEXdCb2pqsiTLjqndT:-MHH3u261Qo1wyicoHYs:b-f8sf1p) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/dgraph/cmd/zero/oracle.go#L82)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Are src.Keys uint64 integers? If so, why do we store uint64 as strings?
</blockquote></details>

Added a comment.
___
*[dgraph/cmd/zero/oracle.go, line 125 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHEXhdl8Ew9rysqbL0c:-MHH45F0DZRUKF5p37lt:b-f8sf1p) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/dgraph/cmd/zero/oracle.go#L125)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

same question here.
</blockquote></details>

Added a comment.
___
*[worker/predicate_move.go, line 231 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6452#-MHGAyyV5wJZUVSHhMyP:-MHH5NXp2Pw7pCvhLQ-8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea582059ad4464f2a49f611ef93e033b0a2ec73b/worker/predicate_move.go#L231)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

This comment looks misleading to me. We're starting a task here which would stop the rollups and I see `ReceivePredicate` call 5 lines below.

What am I missing?
</blockquote></details>

Done.

**Pull request merged**
