### PR TITLE
Extraction of configuration from packages

### PR DESCRIPTION
**Pull request by tzdybal**
For library usage, individual packages cannot call `flag` to setup configuration options. All the command line parsing should be done in `cmd/dgraph/main`.

This change is related to #673.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1172)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 1 of 24 files at r1.
Review status: 1 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 99 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KooVOFVe8wxlo__IJHs:-KooVOFWSCTV2vXhkeZQ:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/3877f27a86b86903904b47c8e32a1fbd6962d71e/cmd/dgraph/main.go#L99)):*
> ```Go
> 		"Number of pending mutation proposals. Useful for rate limiting.")
> 	flag.Float64Var(&worker.Config.Tracing, "trace", 0.0, "The ratio of queries to trace.")
> 	flag.StringVar(&worker.Config.GroupIds, "groups", "0,1", "RAFT groups handled by this server.")
> ```

100 chars

---

*[worker/groups.go, line 43 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KooWEVyj3CtryrD7jui:-KooWEVyj3CtryrD7juj:bfadpzb) ([raw file](https://github.com/dgraph-io/dgraph/blob/3877f27a86b86903904b47c8e32a1fbd6962d71e/worker/groups.go#L43)):*
> ```Go
> var (
> 	pstore           *badger.KV
> 	workerServer     *grpc.Server
> ```

These variables are used/initialized in worker.go. Shouldn't these stay there ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172)*

**Comment by tzdybal** [comment]
Review status: 1 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 99 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KooVOFVe8wxlo__IJHs:-KooYmRgsPF4MeDsZDHi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3877f27a86b86903904b47c8e32a1fbd6962d71e/cmd/dgraph/main.go#L99)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.

---

*[worker/groups.go, line 43 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KooWEVyj3CtryrD7jui:-KooYTlcODrrCtHUvkao:b-alblrm) ([raw file](https://github.com/dgraph-io/dgraph/blob/3877f27a86b86903904b47c8e32a1fbd6962d71e/worker/groups.go#L43)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

These variables are used/initialized in worker.go. Shouldn't these stay there ?
</blockquote></details>

Variables are used everywhere (for example pstore is accessed in 8 files). Entire var block moved to worker.go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172)*

**Comment by manishrjain** [comment]
Some comments. Otherwise, looks good. I'll defer to @janardhan1993 for the final approval.

---

Reviewed 21 of 24 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/dgraph/main.go, line 666 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-Kord9BFM7K20fFh2Dys:-Kord9BFM7K20fFh2Dyt:b-9z6w9f) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/cmd/dgraph/main.go#L666)):*
> ```Go
> 	// Posting will initialize index which requires schema. Hence, initialize
> 	// schema before calling posting.Init().
> 	schema.Init(dgraph.State.PStore)
> ```

Pstore (small s)

---

*[cmd/dgraphloader/main.go, line 208 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordN3ISI4WCn_7vknk:-KordN3ISI4WCn_7vknl:b-9pga8j) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/cmd/dgraphloader/main.go#L208)):*
> ```Go
> func main() {
> 	flag.Parse()
> 	x.Init()
> ```

Isn't x.Init() calling flag.Parse?

---

*[dgraph/server.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordSF9rO3uFUkJpDIJ:-KordSF9rO3uFUkJpDIK:bxyrkra) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/dgraph/server.go#L41)):*
> ```Go
> 	ShutdownCh chan struct{} // channel to signal shutdown.
> 
> 	PStore   *badger.KV
> ```

Pstore

---

*[dgraph/server.go, line 42 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordSpdvJiSc3qcdb1M:-KordSpdvJiSc3qcdb1N:b-fwsplo) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/dgraph/server.go#L42)):*
> ```Go
> 
> 	PStore   *badger.KV
> 	WALStore *badger.KV
> ```

WALstore

---

*[dgraph/server.go, line 80 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-Kordh4rfaNcxb6EQ3Tn:-Kordh4rfaNcxb6EQ3To:b-yf70p0) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/dgraph/server.go#L80)):*
> ```Go
> 	opt.Dir = Config.PostingDir
> 	opt.ValueDir = Config.PostingDir
> 	opt.MapTablesTo = table.MemoryMap
> ```

Make this a flag, so user can decide how they want this. There're 3 options -- talk to @janardhan1993 .

---

*[posting/config.go, line 20 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordvAkkE2Ey12ifTUc:-KordvAkkE2Ey12ifTUd:b-j7gk0j) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/posting/config.go#L20)):*
> ```Go
> 
> type Options struct {
> 	MaxMemory      float64
> ```

Call it `AllottedMemory` (not allocated).

---

*[posting/lists.go, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KoreWJnjsd5y4AybiI2:-KoreWJnjsd5y4AybiI3:b-j6binc) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/posting/lists.go#L211)):*
> ```Go
> 			x.NumGoRoutines.Set(int64(runtime.NumGoroutine()))
> 			if setLruMemory && inUse > 0.75*(Config.MaxMemory) {
> 				go lcache.UpdateMaxSize()
> ```

This doesn't need to be a goroutine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-:-Koreved5lPKDSUtugxK:bim3ndt)*

**Comment by tzdybal** [comment]
Review status: 14 of 26 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/dgraph/main.go, line 666 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-Kord9BFM7K20fFh2Dys:-KotBbUXy8fhghO41LTY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/cmd/dgraph/main.go#L666)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Pstore (small s)
</blockquote></details>

Done.

---

*[cmd/dgraphloader/main.go, line 208 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordN3ISI4WCn_7vknk:-KotBHnNsPWDgJzMcexv:b75qov4) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/cmd/dgraphloader/main.go#L208)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Isn't x.Init() calling flag.Parse?
</blockquote></details>

Removed it from x.Init(), because we need to call x.Init() in library initialization, and we don't want the library to touch the flag library at all. 

---

*[dgraph/server.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordSF9rO3uFUkJpDIJ:-KotBaTxi-1WIhAp3Rn8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/dgraph/server.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Pstore
</blockquote></details>

Done.

---

*[dgraph/server.go, line 42 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordSpdvJiSc3qcdb1M:-KotBcbWiA14KX4vgRNe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/dgraph/server.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

WALstore
</blockquote></details>

Done.

---

*[dgraph/server.go, line 80 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-Kordh4rfaNcxb6EQ3Tn:-KotBiEbM_hQTF3qzKVz:bjn7o4g) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/dgraph/server.go#L80)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this a flag, so user can decide how they want this. There're 3 options -- talk to @janardhan1993 .
</blockquote></details>

OK, I'll talk to him.

---

*[posting/config.go, line 20 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KordvAkkE2Ey12ifTUc:-KotCoLTAefCX5yfa5K3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/posting/config.go#L20)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Call it `AllottedMemory` (not allocated).
</blockquote></details>

Done.

---

*[posting/lists.go, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-KoreWJnjsd5y4AybiI2:-KotCuDV-5_-Wphy6IRO:b-17gtwp) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a63c2c2a18a8a4e9817c95a0cceb78f37bfa5e/posting/lists.go#L211)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This doesn't need to be a goroutine.
</blockquote></details>

Nothing changed in here, but I'll change it to normal function invocation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 14 of 26 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1172#-:-KotU1Zx8gp6oKOzJEM5:bnfp4nl)*

**Comment by tzdybal** [comment]
Merged to master.

**Pull request closed without merging**
