### PR TITLE
Feature/count root

### PR DESCRIPTION
**Pull request by pawanrawal**
Implements #925

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/936)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Just a thought: Instead of doing:
```
count(me(func: ge(name, 0)))
```
How about: 
```
count(func: ge(name, 0))
```
If the name of that query is `count`, we just return the count of UIDs instead.

**Comment by pawanrawal** [comment]
@ashwin95r , right now response has the key `count(me)` with the actual count. If we decide to go the way you suggest above, we would also need to support alias at root? So that user can fetch multiple counts in different blocks.

**Comment by ashwin95r** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1763 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-Kk9AZRf87RPoFTF3zBt:-Kk9AZRgBYPJekwiVQVp:b-sa4t4f) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a6a07089ae5135448818fa97cfac607c0c9c34a/gql/parser.go#L1763)):*
> ```Go
> 	}
> 
> 	if item.Val == "count" {
> ```

We can peek here and decide if it's a count or not (Instead of doing a prev() later)

---

*[query/query_test.go, line 6458 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-Kk9DbNR_dJU-EmDy0Ja:-Kk9DbNR_dJU-EmDy0Jb:bxbpsmh) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a6a07089ae5135448818fa97cfac607c0c9c34a/query/query_test.go#L6458)):*
> ```Go
> 	query := `
> {
>                         count(me(func:anyofterms(name, "Michonne Rick Daryl")) @filter(le(count(friend), 10)))
> ```

`le(.., 3)` as all of them have <= 10 friends.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/936)*

**Comment by ashwin95r** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/936)*

**Comment by pawanrawal** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 1763 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-Kk9AZRf87RPoFTF3zBt:-KkAdUJ5j9KKbFOuyFax:b-hfpv0l) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a6a07089ae5135448818fa97cfac607c0c9c34a/gql/parser.go#L1763)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We can peek here and decide if it's a count or not (Instead of doing a prev() later)
</blockquote></details>

removed

---

*[query/query_test.go, line 6458 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-Kk9DbNR_dJU-EmDy0Ja:-KkApVnpzlLpgUlM_JDw:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a6a07089ae5135448818fa97cfac607c0c9c34a/query/query_test.go#L6458)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

`le(.., 3)` as all of them have <= 10 friends.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/936)*

**Comment by ashwin95r** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1912 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-KkDWBdJqvUQgalBX3F9:-KkDWBdKRuFedQGO2SBu:bj1mpa0) ([raw file](https://github.com/dgraph-io/dgraph/blob/93bc391bdf40e1a7bdc0b00a9933c10bc90ad866/gql/parser.go#L1912)):*
> ```Go
> const (
> 	notSeen      Count = iota // default value
> 	seen                      // when we see count keyword
> ```

I think we shouldn't allow assigning variables to `count()`

---

*[query/query_test.go, line 6401 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-KkDVtO9wpWnfSfdXifi:-KkDVtO9wpWnfSfdXifj:br6m6at) ([raw file](https://github.com/dgraph-io/dgraph/blob/93bc391bdf40e1a7bdc0b00a9933c10bc90ad866/query/query_test.go#L6401)):*
> ```Go
>                 {
>                         me(func: ge(count(friend), 0)) {
> 				count()
> ```

Some test case with `a as count()`. This should error out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/936)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 1 of 1 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 474 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-KkD_kuZeCnxx46_L_ug:-KkD_ku_I_3bcj2KNmEL:b-ze99zp) ([raw file](https://github.com/dgraph-io/dgraph/blob/93bc391bdf40e1a7bdc0b00a9933c10bc90ad866/query/outputnode.go#L474)):*
> ```Go
> }
> 
> func addCountAtRoot(n outputNode, sg *SubGraph, seedNode outputNode) {
> ```

Make this a func of node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/936#-:-KkDaAO8D1Em1Diddoge:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
