### PR TITLE
Improve Raft loop based on how Etcd folks run it.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1386)

### CODE REVIEW

**Comment by srh** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[worker/draft.go, line 796 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1386#-KsuWT-UWlRy6YWZavMk:-KsuWT-UWlRy6YWZavMl:b-ly9qfa) ([raw file](https://github.com/dgraph-io/dgraph/blob/975034871fdf5b685ec87a70debfbb40efe10bc8/worker/draft.go#L796)):*
> ```Go
> 
> 			if !leader {
> 				// Followers should send messages later.
> ```

Why should followers send them later?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1386)*

**Comment by srh** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1386)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[worker/draft.go, line 796 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1386#-KsuWT-UWlRy6YWZavMk:-Ksug_v1_xiXT6wG4SqV:b-we6b8d) ([raw file](https://github.com/dgraph-io/dgraph/blob/975034871fdf5b685ec87a70debfbb40efe10bc8/worker/draft.go#L796)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Why should followers send them later?
</blockquote></details>

https://github.com/coreos/etcd/blob/e962b0c8498719c8d14c06572c38907ef4919343/etcdserver/raft.go#L249-L275

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1386)*

**Comment by srh** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1386#-:-KsuoDnbEhAJNNcGBXlG:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1386#-:-KsumK819myA0qaQXIM6:bnfp4nl)*

**Comment by manishrjain** [comment]
Submitted to master.

**Pull request closed without merging**
