### PR TITLE
predicate moves

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1506)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 10 files reviewed at latest revision, 13 unresolved discussions, some commit checks broke.

---

*[cmd/dgraphzero/predicate_move.go, line 53 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucI5foccl_N4iB1KIG:-KucI5foccl_N4iB1KIH:bmcdoqm) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L53)):*
> ```Go
> */
> 
> // TODO: Have a flag to disable rebalancing. (Useful on production when users don't want
> ```

Remove the TODO. We don't want to do this now.

---

*[cmd/dgraphzero/predicate_move.go, line 57 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucIWu5yvlrOf8rCBBF:-KucIWu5yvlrOf8rCBBG:bplgjq0) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L57)):*
> ```Go
> //       Have a event log for everything.
> func (s *Server) rebalanceTablets() {
> 	ticker := time.NewTicker(time.Minute)
> ```

Make it 1.5 times of the update time.

---

*[cmd/dgraphzero/predicate_move.go, line 65 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJlzTGecddQplYgd2:-KucJlzTGecddQplYgd3:b-q8ay9f) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L65)):*
> ```Go
> 			if !s.Node.AmLeader() {
> 				if cancel != nil {
> 					cancel()
> ```

cancel = nil

---

*[cmd/dgraphzero/predicate_move.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJrbtjnOKmk9eWy2d:-KucJrbtjnOKmk9eWy2e:b6h19g4) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L87)):*
> ```Go
> 			var ctx context.Context
> 			ctx, cancel = context.WithTimeout(context.Background(), time.Minute*20)
> 			if err := s.movePredicate(ctx, predicate, srcGroup, dstGroup); err != nil {
> ```

moveTablet. Everywhere.

---

*[cmd/dgraphzero/predicate_move.go, line 134 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJv_x70Lza8kmnCP4:-KucJv_x70Lza8kmnCP5:bdw2eaq) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L134)):*
> ```Go
> }
> 
> func (s *Server) choosePredicate() (predicate string, srcGroup uint32, dstGroup uint32) {
> ```

chooseTablet

---

*[cmd/dgraphzero/predicate_move.go, line 167 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucKAs8zOxka7uE5rHs:-KucKAs8zOxka7uE5rHt:b-mw9wkk) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L167)):*
> ```Go
> 		return
> 	}
> 	if size_diff < 50<<20 { // Change limit later
> ```

10% of src, then don't do anything.

---

*[cmd/dgraphzero/predicate_move.go, line 191 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJ_sBtknqBb687b7x:-KucJ_sBtknqBb687b7y:b-6ysu5z) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L191)):*
> ```Go
> 		return nil
> 	}
> ```

Check if you're still the leader. If not, then return. Leader should do the recovery. Or, check the state -- if there's still RO, then do recovery.

---

*[cmd/dgraphzero/raft.go, line 218 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucLrRWbEFBWv1iKsGR:-KucLrRWbEFBWv1iKsGS:b-oox48d) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/raft.go#L218)):*
> ```Go
> 			state.Groups[p.Tablet.GroupId] = group
> 		}
> ```

Add a comment that there's a edge case that we're handling.

Two servers ask to serve the same tablet.
Then, we should check ..

---

*[cmd/dgraphzero/raft.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucL0eU389RcUwWQ7gO:-KucL0eU389RcUwWQ7gP:bbttxnw) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/raft.go#L223)):*
> ```Go
> 				group := state.Groups[tablet.GroupId]
> 				delete(group.Tablets, p.Tablet.Predicate)
> 				group.Space -= p.Tablet.Space
> ```

Remove the space, unnecessary.

---

*[worker/draft.go, line 422 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucOqQBCEDm6b3izvwO:-KucOqQBCEDm6b3izvwP:b19fw2) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/draft.go#L422)):*
> ```Go
> 			// to delete again.
> 			if tablet := groups().Tablet(proposal.CleanPredicate); tablet != nil &&
> 				tablet.ReadOnly {
> ```

Remove the ReadOnly check. If you got a proposal, then you should delete it.

---

*[worker/groups.go, line 174 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucPdWot5njf0gW0xj8:-KucPdWot5njf0gW0xj9:b-b71w4j) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/groups.go#L174)):*
> ```Go
> 				if tablet != nil {
> 					go func(predicate string) {
> 						p := &protos.Proposal{CleanPredicate: predicate}
> ```

Delete directly, if tablet is not read-only.

---

*[worker/groups.go, line 456 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucTUi1PSNG1Gihgmgh:-KucTUi1PSNG1Gihgmgi:ba7nkba) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/groups.go#L456)):*
> ```Go
> 			// where a newly added tablet is not sent.
> 			if g.Node.AmLeader() {
> 				tablets = g.calculateTabletSizes()
> ```

Create another function called cleanupTablets, which should jump between predicates and do the cleanup. calculate shouldn't do any cleanup.

---

*[worker/predicate_move.go, line 150 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucTrpcQ88JmjfNRmEP:-KucTrpcQ88JmjfNRmEQ:bducmom) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/predicate_move.go#L150)):*
> ```Go
> 			pk := x.Parse(kv.Key)
> 			// Delete on all nodes.
> 			p := &protos.Proposal{}
> ```

Don't do it. Create a new proposal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506)*

**Comment by janardhan1993** [comment]
Review status: 0 of 10 files reviewed at latest revision, 14 unresolved discussions.

---

*[cmd/dgraphzero/raft.go, line 218 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucLrRWbEFBWv1iKsGR:-KucXrqpai2SlOiKa7gT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/raft.go#L218)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment that there's a edge case that we're handling.

Two servers ask to serve the same tablet.
Then, we should check ..
</blockquote></details>

Done.

---

*[cmd/dgraphzero/raft.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucL0eU389RcUwWQ7gO:-KucXsQrd0hkctgO_Uta:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/raft.go#L223)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove the space, unnecessary.
</blockquote></details>

Done.

---

*[worker/draft.go, line 422 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucOqQBCEDm6b3izvwO:-KucXIF_N3yX8fz-AzT6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/draft.go#L422)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove the ReadOnly check. If you got a proposal, then you should delete it.
</blockquote></details>

Done.

---

*[worker/groups.go, line 174 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucPdWot5njf0gW0xj8:-Kucc2gb8TyYq2VHwecX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/groups.go#L174)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Delete directly, if tablet is not read-only.
</blockquote></details>

Done.

---

*[worker/groups.go, line 456 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucTUi1PSNG1Gihgmgh:-Kucc4AZ1eA0XiTp42ZL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/groups.go#L456)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create another function called cleanupTablets, which should jump between predicates and do the cleanup. calculate shouldn't do any cleanup.
</blockquote></details>

Done.

---

*[worker/groups.go, line 477 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-Kucg2lXGE67-fuDuGTh:-Kucg2lXGE67-fuDuGTi:bb8i6es) ([raw file](https://github.com/dgraph-io/dgraph/blob/1634a5e2ad89cda1899717f48c35fa0715862920/worker/groups.go#L477)):*
> ```Go
> 				// Delete one at time
> 				if tablet := g.Tablet(pk.Attr); tablet != nil && !tablet.ReadOnly {
> 					// TODO: Keep on checking readonly flag every 100 values and return.
> ```

Will do it as separate PR.

---

*[worker/predicate_move.go, line 150 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucTrpcQ88JmjfNRmEP:-KucX31CL5QHKXtVLZc2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/worker/predicate_move.go#L150)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't do it. Create a new proposal.
</blockquote></details>

Done.

---

*[cmd/dgraphzero/predicate_move.go, line 53 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucI5foccl_N4iB1KIG:-KucVechmZ871dTpiBM2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L53)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove the TODO. We don't want to do this now.
</blockquote></details>

Done.

---

*[cmd/dgraphzero/predicate_move.go, line 57 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucIWu5yvlrOf8rCBBF:-KucVf9j8X3lapSkFmus:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L57)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make it 1.5 times of the update time.
</blockquote></details>

Done.

---

*[cmd/dgraphzero/predicate_move.go, line 65 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJlzTGecddQplYgd2:-KucVhE5ycGe3AzbUffI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

cancel = nil
</blockquote></details>

Done.

---

*[cmd/dgraphzero/predicate_move.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJrbtjnOKmk9eWy2d:-KucViNLo83fFfZAQnz8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L87)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

moveTablet. Everywhere.
</blockquote></details>

Done.

---

*[cmd/dgraphzero/predicate_move.go, line 134 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJv_x70Lza8kmnCP4:-KucVj68Nc9Z8bip5ycl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L134)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

chooseTablet
</blockquote></details>

Done.

---

*[cmd/dgraphzero/predicate_move.go, line 167 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucKAs8zOxka7uE5rHs:-KucXKDxxnc9bvCM7g73:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L167)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

10% of src, then don't do anything.
</blockquote></details>

Done.

---

*[cmd/dgraphzero/predicate_move.go, line 191 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KucJ_sBtknqBb687b7x:-KucW9X5D4-F7Y-fDVFE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e773d45a89a5b2a12a7cead66e1822ba3759821/cmd/dgraphzero/predicate_move.go#L191)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check if you're still the leader. If not, then return. Leader should do the recovery. Or, check the state -- if there's still RO, then do recovery.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 10 files at r1, 1 of 9 files at r2, 5 of 8 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphzero/tablet.go, line 173 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KurAjYDTGGpt4cODl8E:-KurAjYEt8461NLPjXah:b-ayy6l3) ([raw file](https://github.com/dgraph-io/dgraph/blob/765e91f3733f6d8693d564432ee2dccd6d248f22/cmd/dgraphzero/tablet.go#L173)):*
> ```Go
> 		}
> 		if float64(size_diff) < 0.1*float64(groups[0].size) { // Change limit later
> 			return
> ```

continue. Only here, not above.

Add a comment about what's going on here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-:-KurBdhv8xlrENUp2k9M:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphzero/tablet.go, line 173 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506#-KurAjYDTGGpt4cODl8E:-KurO-oTOTinAOYpAHj9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/765e91f3733f6d8693d564432ee2dccd6d248f22/cmd/dgraphzero/tablet.go#L173)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

continue. Only here, not above.

Add a comment about what's going on here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1506)*

**Pull request merged**
