### PR TITLE
Delete schema on deleting predicate incase user didn't set it and other fixes.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1467)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-:-Ku3_CLh_Vba7NrtIXJs:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:.  I have no clue about js files though :)

---

Reviewed 24 of 24 files at r1.
Review status: 23 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[protos/schema.proto, line 56 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3b6sdYtdLCLcc4ami:-Ku3b6sdYtdLCLcc4amj:b1g7jat) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/protos/schema.proto#L56)):*
> ```protobuf
> 	bool count = 5;
> 	bool list = 6;
> 	bool explicit = 7; // whether schema was set by the user.
> ```

Not sure whether exposing this is a good idea. Probably add a check that this should not be false in schema mutation which comes via grpc.

---

*[schema/parse.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3awD6taNPCZIVvWen:-Ku3awD6taNPCZIVvWeo:bzc4ggo) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/schema/parse.go#L31)):*
> ```Go
> 
> func From(s *protos.SchemaUpdate) protos.SchemaUpdate {
> 	if s.Directive == protos.SchemaUpdate_REVERSE {
> ```

I think this from is not needed, this was there when we had two different proto types for storing and in graphrequest

---

*[schema/schema.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3aicgJmFukSsDNWEJ:-Ku3aicgJmFukSsDNWEK:brk3o5u) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/schema/schema.go#L122)):*
> ```Go
> 	defer s.Unlock()
> 
> 	delete(s.predicate, pred)
> ```

Emit begin watermark for posting.syncmark, since it would be done in backgroud

---

*[schema/schema.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3aNXisvE1GRqs2Qt9:-Ku3aNXisvE1GRqs2QtA:b-qg3ivp) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/schema/schema.go#L395)):*
> ```Go
> 		for _, e := range entries {
> 			if e.Schema.Directive == protos.SchemaUpdate_DELETE {
> 				wb = badger.EntriesDelete(wb, x.SchemaKey(e.Attr))
> ```

Modify test in worker/predicate_test.go to check if schema is deleted in snapshot. Most probably you would need to fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-:-Ku3btZwLRbNDF1gWoVx:b-5tzmnh)*

**Comment by pawanrawal** [comment]
Review status: 19 of 27 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[protos/schema.proto, line 56 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3b6sdYtdLCLcc4ami:-KuHRUccw-cRHU9cBjSF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/protos/schema.proto#L56)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Not sure whether exposing this is a good idea. Probably add a check that this should not be false in schema mutation which comes via grpc.
</blockquote></details>

Done.

---

*[schema/parse.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3awD6taNPCZIVvWen:-KuHREs67RMyBhwGr3_W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/schema/parse.go#L31)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

I think this from is not needed, this was there when we had two different proto types for storing and in graphrequest
</blockquote></details>

Done.

---

*[schema/schema.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3aicgJmFukSsDNWEJ:-KuHVcqbenBWmAIdkJWx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/schema/schema.go#L122)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Emit begin watermark for posting.syncmark, since it would be done in backgroud
</blockquote></details>

Done.

---

*[schema/schema.go, line 395 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467#-Ku3aNXisvE1GRqs2Qt9:-KuHVdXOXf7mDnMNX1Bz:bp2jimd) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfcab4d8c4a0a2e1b509f65b734c42e9c00dd361/schema/schema.go#L395)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Modify test in worker/predicate_test.go to check if schema is deleted in snapshot. Most probably you would need to fix it.
</blockquote></details>

Added a TODO for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1467)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
