### PR TITLE
Check tokenizer should be valid for schema type

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/785)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[schema/parse.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/785#-KgRgteTC39w_JuhFO9G:-KgRgteTC39w_JuhFO9H:blorr4o) ([raw file](https://github.com/dgraph-io/dgraph/blob/3ad64ce2ba81efe6cb5877e1ce87a8f0b6e28069/schema/parse.go#L47)):*
> ```Go
> // Overwrites schema blindly - called only during initilization in testing
> func ParseBytes(s []byte, gid uint32) (rerr error) {
> 	pstate.m = make(map[uint32]*stateGroup)
> ```

Travis was failing because of this.
https://travis-ci.org/dgraph-io/dgraph/builds/216572344

Doing a reset makes pstate nil, then in batchSync(which is going on in a goroutine once initialized by Init) we try to access `State().elog` which panic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/785)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[schema/parse.go, line 170 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/785#-KgSHiZVNE2rIzB_W0IV:-KgSHiZVNE2rIzB_W0IW:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/33ac292133d11e9751d0c700c6ed34a9d39b2a1c/schema/parse.go#L170)):*
> ```Go
> 		}
> 		if tokenizer.Type() != typ {
> 			return tokenizers, x.Errorf("Tokenizer: %s isn't valid for predicate: %s of type: %s",
> ```

100 chars

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/785#-:-KgSHgmbMo5Tc7YDXcht:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[schema/parse.go, line 170 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/785#-KgSHiZVNE2rIzB_W0IV:-KgSOoDlGgww_WwwA71h:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/33ac292133d11e9751d0c700c6ed34a9d39b2a1c/schema/parse.go#L170)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/785)*

**Comment by pawanrawal** [comment]
merged

**Pull request closed without merging**
