### PR TITLE
User specified directories for 'postings', 'uids' and 'mutations' are created now, if they dont exist already.

### LINKED ISSUE #130: Create core directories if they do not exist.
Currently, if the directory does not exist for mutation it throws an error, and quits.

```
./dgraph --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u  
2016/07/12 15:55:34 num_cpu: 4. prev_maxprocs: 4. Set max procs to num cpus  
2016/07/12 15:55:34 Unable to find dir: stat /dgraph/m: no such file or directory  
```
Dgraph can instead create the directories and give a slightly better experience. 

Thoughts?

### PR DESCRIPTION
**Pull request by mohitranka**
Fixes #130. 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/138)

### CODE REVIEW

**Comment by mohitranka** [comment]
@dgraph-io/team Please wait for my confirmation before reviewing this PR.

**Comment by mohitranka** [comment]
Please review the PR @dgraph-io/team .

**Comment by pawanrawal** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/dgraph/main.go, line 328 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/138#-KNLyfZN0SdpLLfbPW1q:-KNLyfZN0SdpLLfbPW1r:1630545099) ([raw file](https://github.com/dgraph-io/dgraph/blob/5c908d3272deabaff4520e2ab594bd3ccb3e51ee/cmd/dgraph/main.go#L328)):*
> ```Go
> 	if err != nil {
> 		log.Fatal("Error while creating the filepath: %v", *postingDir)
> 		return
> ```

Is a return needed here? Also `log.Fatal(err)` should be enough? Anyways `err` should be part of the fatal message otherwise user won't know why the command failed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/138)*

**Comment by mohitranka** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraph/main.go, line 328 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/138#-KNLyfZN0SdpLLfbPW1q:-KNTVQt_6b6sMNOY9HVn:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/5c908d3272deabaff4520e2ab594bd3ccb3e51ee/cmd/dgraph/main.go#L328)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Is a return needed here? Also `log.Fatal(err)` should be enough? Anyways `err` should be part of the fatal message otherwise user won't know why the command failed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/138)*

**Comment by pawanrawal** [comment]
:lgtm: @manishrjain could you also have a look at this before its merged?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/138#-:-KNUzXl-ZOhybXS3tYXp:-1790987893)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cmd/dgraph/main.go, line 325 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/138#-KNajVFlNWWhwuq13OmU:-KNajVFmAlxE2PZFdf07:-841724659) ([raw file](https://github.com/dgraph-io/dgraph/blob/81fa0f698b267eaefe6c89ad324e221dbf33850c/cmd/dgraph/main.go#L325)):*
> ```Go
> 	// Create parent directories for postings, uids and mutations
> 	var err error
> 	err = os.MkdirAll(*postingDir, 0700)
> ```

What if the directory already exists?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/138)*

**Comment by mohitranka** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraph/main.go, line 325 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/138#-KNajVFlNWWhwuq13OmU:-KNajw1RWhuHSCAxsIfK:1824151424) ([raw file](https://github.com/dgraph-io/dgraph/blob/81fa0f698b267eaefe6c89ad324e221dbf33850c/cmd/dgraph/main.go#L325)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> What if the directory already exists?
</details>
"If path is already a directory, MkdirAll does nothing and returns nil."
(https://golang.org/pkg/os/#MkdirAll)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/138)*

**Comment by manishrjain** [comment]
:lgtm: You can merge it now.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/138#-:-KNf5_2dCN8mGUNMGnFw:-1309039675)*

**Comment by mohitranka** [comment]
Merged to develop with commit 9d919395a698ed660af73ee9417f96630ed31c7e

**Pull request closed without merging**
