### PR TITLE
Optimize sorting by skipping index search if the number of entities are less

### PR DESCRIPTION
**Pull request by ashwin95r**
```
{
        fan(func:alloftext(name, "steven spielberg"), orderasc:name) {
                name
  	}
}
```
Reduces the query time of such queries from around a minute to a few milliseconds as the index for names is too huge.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/762)

### CODE REVIEW

**Comment by gacharya255** [comment]
:lgtm: One comment.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/sort.go, line 311 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIODybxVuiFKtkA1Dv:-KgIODycvcax4G1FGVof:bsupx69) ([raw file](https://github.com/dgraph-io/dgraph/blob/1502e16bfa01db760e4a751133c7ba3cf69aff69/worker/sort.go#L311)):*
> ```Go
> 	if count < 0 {
> 		// Items from the back of the array, like Python arrays. Do a positive mod n.
> 		return (((n + count) % n) + n) % n, n
> ```

This function looks familiar? Maybe we can reuse? Can move into package x perhaps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-:-KgIOPK2SHKS4ohG3sg9:bpjwta0)*

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[worker/sort.go, line 110 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIgLgfUelBOwrpB7Q8:-KgIgLgfUelBOwrpB7Q9:b36uzz4) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L110)):*
> ```Go
> )
> 
> func sortWithoutIndex(cancelCtx context.Context, ts *taskp.Sort, resCh chan result) {
> ```

ctx. Remove the resCh from here. Make this a blocking function.

---

*[worker/sort.go, line 134 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIgauBbqRx6vFzGy-z:-KgIgauBbqRx6vFzGy0-:b-l6ibnv) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L134)):*
> ```Go
> 					res: r,
> 					err: err,
> 				}
> ```

return

---

*[worker/sort.go, line 146 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIhnXbdHSanNrofnIJ:-KgIhnXbdHSanNrofnIK:b8a5rr0) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L146)):*
> ```Go
> }
> 
> func sortWithIndex(cancelCtx context.Context, ts *taskp.Sort, resCh chan result) {
> ```

ctx. Remove the resCh logic from here.

---

*[worker/sort.go, line 249 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIi7p2bYAOP41mtshL:-KgIi7p2bYAOP41mtshM:b-f4xlez) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L249)):*
> ```Go
> }
> 
> type result struct {
> ```

This can move within the processSort func.

---

*[worker/sort.go, line 323 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIiKp_JU4kLlEEliWa:-KgIiKpaA606KN3h74Bt:b-nl17i2) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L323)):*
> ```Go
> 		// We are within the page. We need to apply sorting.
> 		// Sort results by value before applying offset.
> 		err := sortByValue(attr, ts.Langs, result, scalar, ts.Desc)
> ```

if err := ; err != nil {
  return err
}

---

*[x/x.go, line 157 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIiPkLn6TWHJDaLHu6:-KgIiPkLn6TWHJDaLHu7:bx1lfu1) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/x/x.go#L157)):*
> ```Go
> }
> 
> // pageRange returns start and end indices given pagination params. Note that n
> ```

PageRange

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/762)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[worker/sort.go, line 311 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIODybxVuiFKtkA1Dv:-KgIREKn_X6eH1i44RO6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1502e16bfa01db760e4a751133c7ba3cf69aff69/worker/sort.go#L311)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

This function looks familiar? Maybe we can reuse? Can move into package x perhaps?
</blockquote></details>

Done.

---

*[worker/sort.go, line 110 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIgLgfUelBOwrpB7Q8:-KgIlLEV7rz2YVqJnI0-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L110)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ctx. Remove the resCh from here. Make this a blocking function.
</blockquote></details>

Done.

---

*[worker/sort.go, line 134 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIgauBbqRx6vFzGy-z:-KgIlM8ZMnIo2aBySgkS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L134)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return
</blockquote></details>

Done.

---

*[worker/sort.go, line 146 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIhnXbdHSanNrofnIJ:-KgIlO3HkVkntdHUZGcj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L146)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ctx. Remove the resCh logic from here.
</blockquote></details>

Done.

---

*[worker/sort.go, line 249 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIi7p2bYAOP41mtshL:-KgIlOoiKikESWpq3Gwm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L249)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This can move within the processSort func.
</blockquote></details>

Done.

---

*[worker/sort.go, line 323 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIiKp_JU4kLlEEliWa:-KgIlYt2WKo16oNBQof0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/worker/sort.go#L323)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if err := ; err != nil {
  return err
}
</blockquote></details>

Done.

---

*[x/x.go, line 157 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-KgIiPkLn6TWHJDaLHu6:-KgIlJrNb6vaeqDpviB8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a62343dbf6e63810d71a1dc5e121d9a57b32c43/x/x.go#L157)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

PageRange
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/762)*

**Comment by manishrjain** [comment]
:lgtm: Nice idea!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/762#-:-KgInY4e6hocg_oDkTrC:bcezsra)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
