### PR TITLE
Feature/rdf parse errors

### PR DESCRIPTION
**Pull request by pawanrawal**
Have modified `stripBracketsIfPresent` to support throwing error for `<s> <p> <*>`. Does it cause too much code bloat?

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/166)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[rdf/parse.go, line 115 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPHSWuRuW0zyqW88eth:-KPHSWuRuW0zyqW88eti:b-kc2svq) ([raw file](https://github.com/dgraph-io/dgraph/blob/13993c6945aaf89bec30d3c5871033ca9d3203aa/rdf/parse.go#L115)):*
> ```Go
> func stripBracketsIfPresent(val string) (string, error) {
> 	if val[0] == '<' && val[len(val)-1] == '>' {
> 		if val[1] == '*' {
> ```

Why check this over here? let the function return the IRI, and then check if the IRI != "*". That should be all right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[rdf/parse.go, line 115 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPHSWuRuW0zyqW88eth:-KPHV8nrblKVPHtIRTxa:bhm1af2) ([raw file](https://github.com/dgraph-io/dgraph/blob/13993c6945aaf89bec30d3c5871033ca9d3203aa/rdf/parse.go#L115)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why check this over here? let the function return the IRI, and then check if the IRI != "*". That should be all right?
</details>
Yeah, that would work too. Though that would mean having the check at multiple places(for subject, predicate, object and label). I was thinking would be better to have all IRI checks at one place. When we have more checks in the future, we could just refactor it into another function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[rdf/parse.go, line 115 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPHSWuRuW0zyqW88eth:-KPI0NNcK3tTeyYwQ9uW:b-qczwqo) ([raw file](https://github.com/dgraph-io/dgraph/blob/13993c6945aaf89bec30d3c5871033ca9d3203aa/rdf/parse.go#L115)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Yeah, that would work too. Though that would mean having the check at multiple places(for subject, predicate, object and label). I was thinking would be better to have all IRI checks at one place. When we have more checks in the future, we could just refactor it into another function.
</details>
I see what you mean. stripBracket.. is not the right place for it though. The function is meant to do what it says, i.e. strip brackets if present. This checking should be done by the caller. In fact, it still won't be more than a line of code at the caller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[rdf/parse.go, line 115 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPHSWuRuW0zyqW88eth:-KPI6wD5LQV3BysP6rvp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/13993c6945aaf89bec30d3c5871033ca9d3203aa/rdf/parse.go#L115)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I see what you mean. stripBracket.. is not the right place for it though. The function is meant to do what it says, i.e. strip brackets if present. This checking should be done by the caller. In fact, it still won't be more than a line of code at the caller.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[rdf/parse.go, line 132 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9dE21VFdwhLFFqzY:-KPI9dE21VFdwhLFFqzZ:bmhr8kv) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse.go#L132)):*
> ```Go
> 		if item.Typ == itemSubject {
> 			rnq.Subject = stripBracketsIfPresent(item.Val)
> 			if rnq.Subject[0] == '*' {
> ```

Don't think this is the right place for the check.

---

*[rdf/parse.go, line 192 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9Ua6klmWa5cguxN0:-KPI9Ua7QW_qttAC5L17:bikv9oh) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse.go#L192)):*
> ```Go
> 		return rnq, fmt.Errorf("No Object in NQuad. Input: [%s]", line)
> 	}
> ```

if rnq.Subject == "*" || rnq.Predicate == "*" || rnq.ObjectId == "*" { return error }

Think that's all you need really. Also if you notice the other checks above, this place for checks makes a lot of sense.

---

*[rdf/parse_test.go, line 208 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9q49S7dxg9mVjG8D:-KPI9q4ATd0h5Kf3pIsD:b-a2ovpj) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse_test.go#L208)):*
> ```Go
> 		input:  `_:alice <knows> "stuff"^^<*> .`,
> 		hasErr: true,
> 	},
> ```

Also add another test case, where object is `"*"`. This should be OK and not return an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[rdf/parse_test.go, line 202 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPIA5Mn4uvUJv00BHgK:-KPIA5Mn4uvUJv00BHgL:bb2vx5b) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse_test.go#L202)):*
> ```Go
> 	},
> 	{
> 		input:  `<alice> <*> "stuff" .`,
> ```

Add another test case, with spaces around star. `< * >`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[rdf/parse.go, line 192 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9Ua6klmWa5cguxN0:-KPIIXMmTGsKHh_RpIfZ:b-nxoz0n) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse.go#L192)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> if rnq.Subject == "*" || rnq.Predicate == "*" || rnq.ObjectId == "*" { return error }
> 
> Think that's all you need really. Also if you notice the other checks above, this place for checks makes a lot of sense.
</details>
Done.

Still feel proper checks need to happen for S, O and P for instance <* *> won't throw an error right now.

---

*[rdf/parse.go, line 130 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPIIm-qjrFKoFEhO1uQ:-KPIIm-qjrFKoFEhO1uR:b-p1cq2x) ([raw file](https://github.com/dgraph-io/dgraph/blob/d229f334bd48e0f3e270c60022ec410a1d076b3d/rdf/parse.go#L130)):*
> ```Go
> 	// We read items from the l.Items channel to which the lexer sends items.
> 	for item := range l.Items {
> 		switch item.Typ {
> ```

Switched to switch case to avoid unnecessary comparisons and so that the reader understands they are mutually exclusive.

---

*[rdf/parse_test.go, line 202 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPIA5Mn4uvUJv00BHgK:-KPIIkqIqG9SwXbAfe00:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse_test.go#L202)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add another test case, with spaces around star. `< * >`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[rdf/parse.go, line 192 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9Ua6klmWa5cguxN0:-KPgLx5csLhdBIqlpIPD:b-76snlf) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse.go#L192)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Done.
> 
> Still feel proper checks need to happen for S, O and P for instance <* *> won't throw an error right now.
</details>
Yeah, good point. How about doing a check instead to ensure that we have at least one alphanumeric character, and not all special characters. That'd be a fair sanity check, I think.

---

*[rdf/parse.go, line 130 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPIIm-qjrFKoFEhO1uQ:-KPgKjwpT5Hz1v6IoTe3:b-83sjoh) ([raw file](https://github.com/dgraph-io/dgraph/blob/d229f334bd48e0f3e270c60022ec410a1d076b3d/rdf/parse.go#L130)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Switched to switch case to avoid unnecessary comparisons and so that the reader understands they are mutually exclusive.
</details>
Nice!

---

*[rdf/parse.go, line 182 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPgLD8a9L9NaZAZEURh:-KPgLD8a9L9NaZAZEURi:b2olpkr) ([raw file](https://github.com/dgraph-io/dgraph/blob/d229f334bd48e0f3e270c60022ec410a1d076b3d/rdf/parse.go#L182)):*
> ```Go
> 		return rnq, fmt.Errorf("No Object in NQuad. Input: [%s]", line)
> 	}
> 	if strings.Trim(rnq.Subject, " ") == "*" || strings.Trim(rnq.Predicate, " ") == "*" ||
> ```

I think we should already be trimming these fields, shouldn't we? I checked and can't see any trims going on. So, maybe make the trim part of the stripBracketsIfPresent. Possibly renaming it to stripBracketsAndTrim(..)

---

*[rdf/parse_test.go, line 208 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9q49S7dxg9mVjG8D:-KPgMC8E7bXacD4t64Hv:b32w0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse_test.go#L208)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Also add another test case, where object is `"*"`. This should be OK and not return an error.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[rdf/parse.go, line 132 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9dE21VFdwhLFFqzY:-KPku1s7HhsNzeW2G6K0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse.go#L132)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Don't think this is the right place for the check.
</details>
Done.

---

*[rdf/parse.go, line 192 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9Ua6klmWa5cguxN0:-KPku4N8PPvTlcgAJ_GV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse.go#L192)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Yeah, good point. How about doing a check instead to ensure that we have at least one alphanumeric character, and not all special characters. That'd be a fair sanity check, I think.
</details>
Done.

---

*[rdf/parse.go, line 182 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPgLD8a9L9NaZAZEURh:-KPku2tEzKZ7MVYaeal1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d229f334bd48e0f3e270c60022ec410a1d076b3d/rdf/parse.go#L182)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I think we should already be trimming these fields, shouldn't we? I checked and can't see any trims going on. So, maybe make the trim part of the stripBracketsIfPresent. Possibly renaming it to stripBracketsAndTrim(..)
</details>
Done.

---

*[rdf/parse_test.go, line 208 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPI9q49S7dxg9mVjG8D:-KPku6fVdJdA5hNIGUz6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ed419100e37aad4663db89f18de2408050fe1ec/rdf/parse_test.go#L208)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> OK
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by manishrjain** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[rdf/parse.go, line 129 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPq91RSqVFisyCWqJNA:-KPq91RSqVFisyCWqJNB:bzehpg9) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae499117a8482d6fa2dd5f056358e86942d38c7d/rdf/parse.go#L129)):*
> ```Go
> 	}
> 	// s should have atleast one alphanumeric character.
> 	matched, err := regexp.MatchString("[a-zA-Z0-9]", s)
> ```

regexp matching is slow. Avoid them as much as possible. Particularly here when we have millions and billions of edges to parse. Use runes instead and range over the string. We just need a single alphanumeric rune to accept the string.

---

*[rdf/parse.go, line 200 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPq9pMXmrW8oy8aFs3Q:-KPq9pMXmrW8oy8aFs3R:b-xqx7o3) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae499117a8482d6fa2dd5f056358e86942d38c7d/rdf/parse.go#L200)):*
> ```Go
> 	if !sane(rnq.Subject) || !sane(rnq.Predicate) || !sane(rnq.ObjectId) ||
> 		!sane(rnq.Label) {
> 		return rnq, fmt.Errorf("NQuad: %+v failed sanity check", rnq)
> ```

Sandwiching​ the edge in error statement can be a bit confusing. Instead try: "NQuad failed sanity check: %+v"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by pawanrawal** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[rdf/parse.go, line 129 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPq91RSqVFisyCWqJNA:-KPqEToCcKl5hCGRAYr0:b-83od3n) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae499117a8482d6fa2dd5f056358e86942d38c7d/rdf/parse.go#L129)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> regexp matching is slow. Avoid them as much as possible. Particularly here when we have millions and billions of edges to parse. Use runes instead and range over the string. We just need a single alphanumeric rune to accept the string.
</details>
Noted

---

*[rdf/parse.go, line 200 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPq9pMXmrW8oy8aFs3Q:-KPqEX8FzJu3DD0SdNqc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae499117a8482d6fa2dd5f056358e86942d38c7d/rdf/parse.go#L200)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Sandwiching​ the edge in error statement can be a bit confusing. Instead try: "NQuad failed sanity check: %+v"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by pawanrawal** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[rdf/parse.go, line 129 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPq91RSqVFisyCWqJNA:-KPqGCzuDIHPrMJfCjUl:b-pz447x) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae499117a8482d6fa2dd5f056358e86942d38c7d/rdf/parse.go#L129)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Noted
</details>
Doing some benchmarking shows that regexes are 10 times slower on an average.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166)*

**Comment by manishrjain** [comment]
:lgtm: Thanks for all the iterations. Feel free to submit :-).

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[rdf/parse.go, line 129 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-KPq91RSqVFisyCWqJNA:-KPqcukAU4GAti_LC0Qs:b1qjsah) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae499117a8482d6fa2dd5f056358e86942d38c7d/rdf/parse.go#L129)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Doing some benchmarking shows that regexes are 10 times slower on an average.
</details>
OK. Nice benchmarking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/166#-:-KPqd4vAQxgARrcZ6QcE:bhwuxey)*

**Comment by pawanrawal** [comment]
Merged to master with c96051ee2661b866d3511de88db77368546d46db.

**Pull request closed without merging**
