### PR TITLE
Multi var root

### PR DESCRIPTION
**Pull request by ashwin95r**
```
{
      var(id:0x01) {
        L AS friend {
         B AS friend  
        }
      }

      me([L, B]) {
        name
      }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/505)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 1025 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaocM-MHNEf1Js_TAjY:-KaocM-MHNEf1Js_TAjZ:b-c4adv) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1025)):*
> ```Go
> 
> func parseVarList(gq *GraphQuery, val string) error {
> 	val = strings.Replace(val, " ", "", -1)
> ```

should tabs also be replaced ?

---

*[gql/parser.go, line 1038 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-Kao_I-55z0IxPSUifzJ:-Kao_I-55z0IxPSUifzK:bs7csd8) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1038)):*
> ```Go
> 		if c == ',' || c == ']' {
> 			if buf.Len() == 0 {
> 				continue
> ```

Is two commas `,,` leading to this case also not invalid syntax ?
or we are being more tolerant for these cases.

---

*[query/query.go, line 336 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaoaQa5UTPC5Mu26JI2:-KaoaQa70Nd_9amrEK-p:bg9zx4n) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/query/query.go#L336)):*
> ```Go
> 		sg.SrcFunc = append(sg.SrcFunc, ft.Func.Name)
> 		sg.SrcFunc = append(sg.SrcFunc, ft.Func.Args...)
> 		for _, it := range ft.Func.NeedsVar {
> ```

append supports giving another slice in second args..
`slice = append(slice, anotherSlice...)`
if it works, then we can use the same at other places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 1025 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaocM-MHNEf1Js_TAjY:-KatDoNPXj5qwhBfIiym:b-jfev2l) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1025)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

should tabs also be replaced ?
</blockquote></details>

Yes we should. Done.

---

*[gql/parser.go, line 1038 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-Kao_I-55z0IxPSUifzJ:-KatDCiRaihsgAg6vG3z:bp3sbje) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1038)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Is two commas `,,` leading to this case also not invalid syntax ?
or we are being more tolerant for these cases.
</blockquote></details>

We should throw an error. Catching it in lexer now.

---

*[query/query.go, line 336 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaoaQa5UTPC5Mu26JI2:-KatDWDg_jvTquBeuX0w:b-tuomwa) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/query/query.go#L336)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

append supports giving another slice in second args..
`slice = append(slice, anotherSlice...)`
if it works, then we can use the same at other places.
</blockquote></details>

Right! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505)*

**Comment by manishrjain** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1027 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KatYaKbEfYOKagvNJvY:-KatYaKcT5HHzGgV7dOb:b-jbtjl7) ([raw file](https://github.com/dgraph-io/dgraph/blob/162ae90da99a9e6bea00e7ebfd5fbb3eec7d2d3a/gql/parser.go#L1027)):*
> ```Go
> func parseVarList(gq *GraphQuery, val string) error {
> 	val = strings.Replace(val, " ", "", -1)
> 	val = strings.Replace(val, "\t", "", -1)
> ```

Instead of doing this multiple times, it's better to use map: https://golang.org/pkg/strings/#Map

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1025 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaocM-MHNEf1Js_TAjY:-Katvf-kj3BgmxYWkprs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1025)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Yes we should. Done.
</blockquote></details>

Done.

---

*[gql/parser.go, line 1038 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-Kao_I-55z0IxPSUifzJ:-KatvcWFpdzpaSYQDloH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1038)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We should throw an error. Catching it in lexer now.
</blockquote></details>

Done.

---

*[gql/parser.go, line 1027 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KatYaKbEfYOKagvNJvY:-Katx0ztMIoXUKdexU6r:b-slnp8m) ([raw file](https://github.com/dgraph-io/dgraph/blob/162ae90da99a9e6bea00e7ebfd5fbb3eec7d2d3a/gql/parser.go#L1027)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Instead of doing this multiple times, it's better to use map: https://golang.org/pkg/strings/#Map
</blockquote></details>

Done. Using replacer. https://golang.org/pkg/strings/#NewReplacer

---

*[query/query.go, line 336 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaoaQa5UTPC5Mu26JI2:-KatvdGANQ3JFA-93bjB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/query/query.go#L336)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Right! Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505)*

**Comment by manishrjain** [comment]
:lgtm: Just small comment. Then feel free to submit.

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1025 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaocM-MHNEf1Js_TAjY:-Katz9LGhNHQNrPoOlhn:b7j86l) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1025)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Move this to x. call it WhiteSpace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-:-KatzGR2wHHvnG8M8Sz7:bsar7ej)*

**Comment by ashwin95r** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 1025 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-KaocM-MHNEf1Js_TAjY:-Kau-qLOCDpUqbpAkVdC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6ea3c5939804c0f43e12d3d91a20c38ac285c66/gql/parser.go#L1025)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this to x. call it WhiteSpace
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505)*

**Comment by ashishnegi** [comment]
:lgtm: 

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[gql/parser.go, line 424 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-Kau0LNKO67Yu6knk29z:-Kau0LNL35bDRDyDOF9b:b-qfd2oz) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e60bd90180c8ce26f748833769491412df6faf9/gql/parser.go#L424)):*
> ```Go
> 	}
> 	for _, it := range qu.NeedsVar {
> 		v.Needs = append(v.Needs, it)
> ```

can we 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-:-Kau0bwVv4INZ7Aa7OUk:bg7igkv)*

**Comment by ashwin95r** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 424 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/505#-Kau0LNKO67Yu6knk29z:-Kau1hWFgU2l3621H5_a:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e60bd90180c8ce26f748833769491412df6faf9/gql/parser.go#L424)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

can we 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/505)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
