### PR TITLE
chore: systemd unit six node cluster configuration

### PR DESCRIPTION
**Pull request by darkn3rd**
These are configuration files and instructions to create a six-node dgraph cluster managed by systemd.  There are also tests enclosed that were used to test the instructions.

This was tested on both *Ubuntu* and *CentOS* with firewalls enabled and disabled.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6154)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6154)* status: all files reviewed, 6 unresolved discussions (waiting on @darkn3rd and @MichelDiz)

___
*[contrib/systemd/ha_cluster/dgraph-alpha.service, line 10 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGo-VoyCr5I2slSz7xc:-MGo-VoyCr5I2slSz7xd:b-jcdrin) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/dgraph-alpha.service#L10)):*
> ```
> {{ hostname }}
> ```
myhostname, or something else that doesn't confuse it with the command `hostname`.
___
*[contrib/systemd/ha_cluster/README.md, line 10 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGnyxkP-2VF7BaEePvo:-MGnyxkP-2VF7BaEePvp:b-acux4t) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/README.md#L10)):*
> ```
> . `zero0`
> ```
zero-0, if you want it hyphenated.
___
*[contrib/systemd/ha_cluster/README.md, line 79 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGnzL0R4UIDhXm8gQNe:-MGnzL0R4UIDhXm8gQNf:bpr1nyn) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/README.md#L79)):*
> ```
> # enable external ports
> ufw allow from any to any port 6080 proto tcp
> ```
For **port 6080** specifically, according to the Ports Usage docs:

> <sup>2</sup>: Dgraph Zero’s HTTP-external port is used for admin operations. Access to it is not required by clients.

Probably doesn't need to be firewall'd unless they need to access port 6080 outside of localhost.
___
*[contrib/systemd/ha_cluster/README.md, line 90 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGnzddU9aCU-vj-Tal3:-MGnzddU9aCU-vj-Tal4:bkhck8k) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/README.md#L90)):*
> ```
> firewall-cmd --zone=public --permanent --add-port=6080/tcp
> firewall-cmd --reload
> ```
Same comment above about **port 6080**.
___
*[contrib/systemd/multi-nodes/README.md, line 94 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MEitcFN36SZZCl365ok:-MGnzz2ZA_Q6JgqNjcuT:bh0q39u) ([raw file](https://github.com/dgraph-io/dgraph/blob/eb5b518433db8028dfa04469c14f633217fd432b/contrib/systemd/multi-nodes/README.md#L94)):*
> ```
> zero0:5080,zero0:5080,zero0:5080
> ```
Should be zero0:5080,zero1:5080,zero2:5080

**Comment by danielmai** [comment]
___
*[contrib/systemd/multi-nodes/tests/centos8/provision.sh, line 1 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGo-siNC1OCQzlaZtav:-MGo-siNC1OCQzlaZtaw:bp7erk7) ([raw file](https://github.com/dgraph-io/dgraph/blob/eb5b518433db8028dfa04469c14f633217fd432b/contrib/systemd/multi-nodes/tests/centos8/provision.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Make this file have user-executable permissions.

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6154)* status: 6 of 13 files reviewed, 7 unresolved discussions (waiting on @danielmai, @darkn3rd, and @MichelDiz)

___
*[contrib/systemd/ha_cluster/dgraph-alpha.service, line 10 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGo-VoyCr5I2slSz7xc:-MHD36BEE-RVAsm4Tueq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/dgraph-alpha.service#L10)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> {{ hostname }}
> ```
myhostname, or something else that doesn't confuse it with the command `hostname`.
</blockquote></details>

Done.
___
*[contrib/systemd/ha_cluster/README.md, line 10 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGnyxkP-2VF7BaEePvo:-MHD39As1uo4dRfQMgGW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/README.md#L10)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> . `zero0`
> ```
zero-0, if you want it hyphenated.
</blockquote></details>

Done.
___
*[contrib/systemd/ha_cluster/README.md, line 79 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGnzL0R4UIDhXm8gQNe:-MHD3OKMEn5iwX-GWT3n:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/README.md#L79)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> # enable external ports
> ufw allow from any to any port 6080 proto tcp
> ```
For **port 6080** specifically, according to the Ports Usage docs:

> <sup>2</sup>: Dgraph Zero’s HTTP-external port is used for admin operations. Access to it is not required by clients.

Probably doesn't need to be firewall'd unless they need to access port 6080 outside of localhost.
</blockquote></details>

Done.
___
*[contrib/systemd/ha_cluster/README.md, line 90 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGnzddU9aCU-vj-Tal3:-MHD3Q8M-b6NPB8VCR6s:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa61b7b434a9fa1d97a3344cf606fb528bb3e29f/contrib/systemd/ha_cluster/README.md#L90)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> firewall-cmd --zone=public --permanent --add-port=6080/tcp
> firewall-cmd --reload
> ```
Same comment above about **port 6080**.
</blockquote></details>

Done.

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6154)* status: 6 of 13 files reviewed, 7 unresolved discussions (waiting on @danielmai and @MichelDiz)

___
*[contrib/systemd/multi-nodes/tests/centos8/provision.sh, line 1 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-MGo-siNC1OCQzlaZtav:-MHD3fBu8dPo0vYdeBWs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eb5b518433db8028dfa04469c14f633217fd432b/contrib/systemd/multi-nodes/tests/centos8/provision.sh#L1)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Make this file have user-executable permissions.
</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6154#-:-MHO7poL4vxTZahKdU1x:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MichelDiz)

**Pull request merged**
