### PR TITLE
Change memory_mb => lru_mb

### LINKED ISSUE #2211: memory_mb parameter is not strictly enforced and ignored
memory_mb parameter.  Suggests you set it to half available memory, but I've observed it frequenty uses more than half, making even that a bad suggestion.

**- What version of Dgraph are you using?**

**- Have you tried reproducing the issue with latest release?**

**- What is the hardware spec (RAM, OS)?**

**- Steps to reproduce the issue (command/config used to run Dgraph).**

### PR DESCRIPTION
**Pull request by pawanrawal**
Resolves #2211.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2245)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm: One small comment

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wiki/content/deploy/index.md, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2245#-L80lvWLx3tDUcZuPhD5:-L80lvWLx3tDUcZuPhD6:b7xovn4) ([raw file](https://github.com/dgraph-io/dgraph/blob/32e373e6c55f668d632e9f59307f9db17f0315b4/wiki/content/deploy/index.md#L107)):*
> ```Markdown
> (`SERVER`, `ZERO`, `LIVE`, or `BULK`), and then the name of the flag (in
> uppercase). For example, instead of using `dgraph server --lru_mb=8096`, you
> could use `DGRAPH_SERVER_MEMORY_MB=8096 dgraph server`.
> ```

Change environment variable name also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2245#-:-L80mBI9Px9uMG4u4Dvd:b-k3c0bn)*

**Comment by pawanrawal** [comment]
Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[wiki/content/deploy/index.md, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2245#-L80lvWLx3tDUcZuPhD5:-L81LQDEFWFXvO1wRSnL:b-tqj6nh) ([raw file](https://github.com/dgraph-io/dgraph/blob/32e373e6c55f668d632e9f59307f9db17f0315b4/wiki/content/deploy/index.md#L107)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Change environment variable name also
</blockquote></details>

good catch, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2245)*

**Comment by manishrjain** [comment]
Submit this?

---

Review status: 21 of 22 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2245#-:-L8uIVApB53cM-o-7eTD:bt82kn2)*

**Comment by pawanrawal** [comment]
In master as of db4a40fa8e4225ed2b563dd3f10bb73683d750b4.

**Pull request closed without merging**
