### PR TITLE
Support storing facet values. Allow extracting UIDs from value vars.

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/838)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 1086 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/838#-KheNr-nlzT6I-nG9NTk:-KheNr-nlzT6I-nG9NTl:b-3cy9sf) ([raw file](https://github.com/dgraph-io/dgraph/blob/3c02e41ad571b2316424b7abb5260809e0aec12d/query/query.go#L1086)):*
> ```Go
> 
> AssignStep:
> 	if sg.Params.Var != "" {
> ```

if sg == "" {
return
}

// continue with logic.

---

*[query/query_test.go, line 901 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/838#-KheOp1xY-SWhlmJAo8O:-KheOp1yW1cL3hg4MI7K:b2ugqkv) ([raw file](https://github.com/dgraph-io/dgraph/blob/3c02e41ad571b2316424b7abb5260809e0aec12d/query/query_test.go#L901)):*
> ```Go
> 				L as path @facets(weight) {
> 				name
> 				 friend @filter(var(L)){
> ```

If something doesn't have weight, it should be filtered out here. Test it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/838#-:-KheP9aphnTJuDugBweu:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 1086 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/838#-KheNr-nlzT6I-nG9NTk:-KheQu3KO3YSM1MBADqJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3c02e41ad571b2316424b7abb5260809e0aec12d/query/query.go#L1086)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if sg == "" {
return
}

// continue with logic.
</blockquote></details>

Done.

---

*[query/query_test.go, line 901 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/838#-KheOp1xY-SWhlmJAo8O:-KheTDIyiOOZv1dDqRvQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3c02e41ad571b2316424b7abb5260809e0aec12d/query/query_test.go#L901)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If something doesn't have weight, it should be filtered out here. Test it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/838)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/838#-:-Khf7bQpCar9L72y66as:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
