### PR TITLE
Feature/has func

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/988)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[posting/index.go, line 257 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGzbUbTJZ3H5YbxrNu:-KlGzbUbTJZ3H5YbxrNv:bew2jol) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0db09e0cbadadf041cf3f7ac3339f0737fe9699/posting/index.go#L257)):*
> ```Go
> 	// key is deleted during SyncIfDirty.
> 	if t.Op == protos.DirectedEdge_DEL && l.Length(0) == 0 {
> 		return l.pstore.Delete(l.key)
> ```

Wouldn't this delete the key before SyncIfDirty is called? Also, why this change?

---

*[worker/task.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGxz91OBjJwI1aS9SG:-KlGxz92zSrx75Sb9zPu:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L256)):*
> ```Go
> 	for i := 0; i < srcFn.n; i++ {
> 		var key []byte
> 		if srcFn.fnType == NotAFunction || srcFn.fnType == CompareScalarFn || srcFn.fnType == HasFn {
> ```

100 chars.

---

*[worker/task.go, line 389 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGzFDJqGhkpfFs7u3I:-KlGzFDJqGhkpfFs7u3J:b-asxwtp) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L389)):*
> ```Go
> 		f := func(kv itkv, mu *sync.Mutex) {
> 			pk := x.Parse(kv.key)
> 			tlist := &protos.List{[]uint64{pk.Uid}}
> ```

This is duplicate code.

---

*[worker/task.go, line 402 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGzIQ9_8JGtTf40TnL:-KlGzIQ9_8JGtTf40TnM:bqphq4q) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L402)):*
> ```Go
> 	}
> 
> 	if srcFn.fnType == CompareScalarFn && srcFn.isCompareAtRoot {
> ```

This if and the above if are literally the same, except one provides false as fetchVal and the other provides true.

---

*[worker/task.go, line 959 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGybb0gEfmfcDaJTtQ:-KlGybb0gEfmfcDaJTtR:b-ytxcbo) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L959)):*
> ```Go
> }
> 
> func iterateParallel(ctx context.Context, params iterateParams, f func(itkv, *sync.Mutex)) {
> ```

I wonder with the new store, if we really need this parallel iteration. Add a TODO here to compare this against serial iteration in the new store.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/988)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[gql/parser_test.go, line 3360 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHCsk6C-ZyM103LjuI:-KlHCsk7vnKDCuJqOGOm:b-65azo7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/gql/parser_test.go#L3360)):*
> ```Go
> func TestHasFuncAtRoot(t *testing.T) {
> 	query := `{
> 		me(func: has(name@en)) {
> ```

This would require checking if it has a value in that language, that will require fetching the values. Do we want to support that? Maybe we can disallow lang tag in `has` to keep it clear

---

*[worker/task.go, line 622 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHC3nzO-AJ7dhn8UP1:-KlHC3nzO-AJ7dhn8UP2:br9fha0) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/worker/task.go#L622)):*
> ```Go
> 		// Fetch Uids from Store and populate in q.UidList.
> 		fc.n = 0
> 		fc.isCompareAtRoot = true
> ```

`fc.isFuncAtRoot`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/988)*

**Comment by ashwin95r** [comment]
Reviewed 4 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/988)*

**Comment by pawanrawal** [comment]
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 3360 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHCsk6C-ZyM103LjuI:-KlHMjfsq_TsUaNKQOon:bow19lj) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/gql/parser_test.go#L3360)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This would require checking if it has a value in that language, that will require fetching the values. Do we want to support that? Maybe we can disallow lang tag in `has` to keep it clear
</blockquote></details>

Yeah, but that is filtering and happens in another step. Modified it so that it also happens for HasFn. 

---

*[posting/index.go, line 257 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGzbUbTJZ3H5YbxrNu:-KlHEAf7elDn6f_cJtWX:b-66awah) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0db09e0cbadadf041cf3f7ac3339f0737fe9699/posting/index.go#L257)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Wouldn't this delete the key before SyncIfDirty is called? Also, why this change?
</blockquote></details>

I need to delete the key when the list is empty because otherwise HasFn would be true even though there might not be any postings in the list and we take presence of key to mean HasFn is true. Deleting it later after SyncIfDirty now.

---

*[worker/task.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGxz91OBjJwI1aS9SG:-KlHDNXPAx2Qusjw8NBV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L256)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[worker/task.go, line 389 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGzFDJqGhkpfFs7u3I:-KlHDO5AahiUDt6siLyO:b4g0sx3) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L389)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This is duplicate code.
</blockquote></details>

Moved it out to a function.

---

*[worker/task.go, line 402 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGzIQ9_8JGtTf40TnL:-KlHDSF_GgAyWh32dego:b-xdh5dz) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L402)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This if and the above if are literally the same, except one provides false as fetchVal and the other provides true.
</blockquote></details>

Done. One of them gets a count and compares it. Moved the common part out to a function.

---

*[worker/task.go, line 959 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlGybb0gEfmfcDaJTtQ:-KlHDpLJo3ELm2bO9ASU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b92d08e835c78bce4488761c2fa9eb0b9afd76fc/worker/task.go#L959)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I wonder with the new store, if we really need this parallel iteration. Add a TODO here to compare this against serial iteration in the new store.
</blockquote></details>

Done.

---

*[worker/task.go, line 622 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHC3nzO-AJ7dhn8UP1:-KlHNccUrufkKQBOdsbW:b-9pdx03) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/worker/task.go#L622)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

`fc.isFuncAtRoot`?
</blockquote></details>

Maybe isRoot? because we anyway use the type of function also to decide what to do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/988)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 3360 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHCsk6C-ZyM103LjuI:-KlI2XOyBp-J8iDJbCRO:b-grvg32) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/gql/parser_test.go#L3360)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Yeah, but that is filtering and happens in another step. Modified it so that it also happens for HasFn. 
</blockquote></details>

Okay, as long as we ensure we return true only if the actual language has a value it's okay.

---

*[worker/task.go, line 622 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHC3nzO-AJ7dhn8UP1:-KlI2gY4TaAC__FF6xPr:bkf6axc) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/worker/task.go#L622)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Maybe isRoot? because we anyway use the type of function also to decide what to do?
</blockquote></details>

Yeah, Any of it is okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-:-KlI2ksz8undyc_Fx_kh:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 253 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI5zrESILrPTZXnzuN:-KlI5zrESILrPTZXnzuO:bqzasn) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/posting/index.go#L253)):*
> ```Go
> 		addReverseMutation(ctx, t)
> 	}
> ```

Revert this file.

---

*[posting/list.go, line 589 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI6LHXJdywPNXU98zt:-KlI6LHXJdywPNXU98zu:blmevkd) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/posting/list.go#L589)):*
> ```Go
> 	ce := syncEntry{
> 		key:     l.key,
> 		val:     data,
> ```

Make this nil if posting length is zero.

---

*[posting/list.go, line 593 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI66EbaSCex8D6fG4R:-KlI66EbaSCex8D6fG4S:b-u3ga45) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/posting/list.go#L593)):*
> ```Go
> 		water:   l.water,
> 		pending: l.pending,
> 		count:   count,
> ```

No need for extra field.

---

*[worker/task.go, line 728 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI7DX3bjm_FEUqat1r:-KlI7DX3bjm_FEUqat1s:b-nv5igs) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/worker/task.go#L728)):*
> ```Go
> 		fc.lang = q.SrcFunc[1]
> 	case HasFn:
> 		err = ensureArgsCount(q.SrcFunc, 0)
> ```

if err = ..; err != nil {

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-:-KlI7cJIWSIbNN47Abm0:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 2 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 3360 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHCsk6C-ZyM103LjuI:-KlIB177nC95NBSMU5PR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/gql/parser_test.go#L3360)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Okay, as long as we ensure we return true only if the actual language has a value it's okay.
</blockquote></details>

Done.

---

*[posting/list.go, line 589 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI6LHXJdywPNXU98zt:-KlLqMpZnk_VRNQTHEHL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/posting/list.go#L589)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this nil if posting length is zero.
</blockquote></details>

Done.

---

*[posting/list.go, line 593 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI66EbaSCex8D6fG4R:-KlLqNu1d285Q5QbR_Ta:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/posting/list.go#L593)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for extra field.
</blockquote></details>

Done.

---

*[worker/task.go, line 622 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlHC3nzO-AJ7dhn8UP1:-KlLqPUdF-UlsKIHYKNd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d852b705234905259c5d342754334234b5512894/worker/task.go#L622)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Yeah, Any of it is okay.
</blockquote></details>

Done.

---

*[worker/task.go, line 728 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI7DX3bjm_FEUqat1r:-KlM8Cw83UTzdUVFTwR9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/worker/task.go#L728)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if err = ..; err != nil {
</blockquote></details>

Done.

---

*[posting/index.go, line 253 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/988#-KlI5zrESILrPTZXnzuN:-KlM8DjT36_g_OUvKKP2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15a8696953bae686b20215284d69d1fc9cf0b3fd/posting/index.go#L253)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Revert this file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/988)*

**Comment by pawanrawal** [comment]
Merged to master,

**Pull request closed without merging**
