### PR TITLE
DRAFT: analyze query and dgraph test suite

### PR DESCRIPTION
**Pull request by kevinmingtarja**
## Problem
 
`query` and `dgraph` test suite occasionally had intermittent failures

## Solution
 
Re-run test 10 times to hopefully catch the failures and analyze them. 
Note: This PR is not to be merged.

### CODE REVIEW

**Comment by kevinmingtarja** [comment]
Note: Query test suite has been ran for 40 times (10 on local, 30 on CI), no failures so far.

**Comment by dshekhar95** [comment]
Added schema tests here

**Comment by dshekhar95** [comment]
first schema run ran 10 times all passed

**Comment by skrdgraph** [comment]
@kevinmingtarja - im deleting the branch. when you have sometime - pls see if there are any `kevinmingtarja/*` branches that can also get deleted.

**Pull request closed without merging**
