### PR TITLE
feat: add schema history to graphql

### PR DESCRIPTION
**Pull request by balajijinnah**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6324)

 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-1117948e5b-92351.surge.sh)

### CODE REVIEW

**Comment by gja** [comment]
Why is there so much cors stuff here?

**Comment by balajijinnah** [comment]
I just moved all the graphql related stuff into a different file. @gja

**Comment by balajijinnah** [comment]
I just moved all the graphql related stuff into a different file. @gja

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 3 of 9 files at r2, 1 of 1 files at r3, 13 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6324)* status: all files reviewed, 4 unresolved discussions (waiting on @balajijinnah, @gja, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[edgraph/graphql.go, line 128 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIfI227I0KhH6r_m21:-MGIfI227I0KhH6r_m22:bcl0tk9) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/edgraph/graphql.go#L128)):*
> ```Go
> // UpdateSchemaHistory updates graphql schema history.
> func UpdateSchemaHistory(ctx context.Context, schema string) error {
> 	glog.Info("Updating schema history")
> ```

We don't need this as we already have a call for schema update.
___
*[graphql/admin/admin.go, line 77 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIg_FcA0xtFOcriaub:-MGIg_FcA0xtFOcriauc:b5gckrg) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/graphql/admin/admin.go#L77)):*
> ```Go
> 	type SchemaHistory {
> 		schema: String!
> 		created_at: String!
> ```

created_at should be DateTime
___
*[graphql/admin/schema.go, line 178 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIh_ua4701-ZkyVpRL:-MGIh_ua4701-ZkyVpRM:b-g83rlr) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/graphql/admin/schema.go#L178)):*
> ```Go
> 	}
> 	// Retrive all schema history from dgraph.
> 	histories, err := edgraph.GetSchemaHistory(ctx, limit, offset)
> ```

All this should automatically be done, look at queryUser and endpoints_ee.go to see how to override type and predicate names.
___
*[x/keys.go, line 535 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIiLZwChV_1BnLoAGx:-MGIiLZwChV_1BnLoAGy:bhfsy4h) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/x/keys.go#L535)):*
> ```Go
> 	"dgraph.graphql.schema_created_at": {},
> 	"dgraph.graphql.schema_history":    {},
> }
> ```

It should be possible to mutate it only using internal API and not via Dgraph mutation.

**Review by balajijinnah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6324)* status: 13 of 20 files reviewed, 4 unresolved discussions (waiting on @gja, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/graphql.go, line 128 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIfI227I0KhH6r_m21:-MGNL2Yj9KQ6w8x7dhCI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/edgraph/graphql.go#L128)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We don't need this as we already have a call for schema update.
</blockquote></details>

Done.
___
*[graphql/admin/admin.go, line 77 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIg_FcA0xtFOcriaub:-MGNL3sY6Djy4bD5HmbS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/graphql/admin/admin.go#L77)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

created_at should be DateTime
</blockquote></details>

Done.
___
*[graphql/admin/schema.go, line 178 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIh_ua4701-ZkyVpRL:-MGNL5s129Gk3fi4SNjr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/graphql/admin/schema.go#L178)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

All this should automatically be done, look at queryUser and endpoints_ee.go to see how to override type and predicate names.
</blockquote></details>

Done.
___
*[x/keys.go, line 535 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIiLZwChV_1BnLoAGx:-MGNL8WD1Y5h4jvsMKjQ:b-12den9) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/x/keys.go#L535)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

It should be possible to mutate it only using internal API and not via Dgraph mutation.
</blockquote></details>

I've added the neccesary changes.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6324)* status: all files reviewed, 4 unresolved discussions (waiting on @balajijinnah, @gja, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 983 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGNuI5H2jk9b_1Z64fX:-MGNuI5H2jk9b_1Z64fY:b-gkdp37) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2b1428997abe5c2a3610d86ee268bf845119ba9/edgraph/server.go#L983)):*
> ```Go
> 
> 	if doAuth != AuthorizeGraphqlPredicate {
> 		if rerr = validateGraphqlInternalInMutation(ctx, qc); rerr != nil {
> ```

There is already a function called `validateForGraphql`. I don't understand why you need this. Can you please work with @abhimanyusinghgaur to make sure we are not adding any duplicate functions or variables here.
___
*[graphql/admin/schema.go, line 178 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGIh_ua4701-ZkyVpRL:-MGNsnAD5_sZ0a5uA7Wm:b-157lgu) ([raw file](https://github.com/dgraph-io/dgraph/blob/804336d7c8863c19995204eb9091925404df7663/graphql/admin/schema.go#L178)):*
<details><summary><i>Previously, balajijinnah (Balaji Jinnah) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

looks much better
___
*[x/keys.go, line 533 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGNtZ2q7oglRp_MfojD:-MGNtZ2q7oglRp_MfojE:b-bj2y20) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2b1428997abe5c2a3610d86ee268bf845119ba9/x/keys.go#L533)):*
> ```Go
> 	"dgraph.type":                      {},
> 	"dgraph.cors":                      {},
> 	"dgraph.graphql.schema_created_at": {},
> ```

I think these should not be here rather in `graphReservedPredicate` map. I don't understand why these are here? Do you need them for a `*` query?
___
*[x/x.go, line 175 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGNu0eK8KbFeKemB1wg:-MGNu0eK8KbFeKemB1wh:bo3corr) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2b1428997abe5c2a3610d86ee268bf845119ba9/x/x.go#L175)):*
> ```Go
> 	AcceptedOrigins = atomic.Value{}
> 	// GraphqlReservedPredicate contains graphql reserved predicates.
> 	GraphqlReservedPredicate = map[string]struct{}{"dgraph.cors": struct{}{},
> ```

There is already a function for this, why define another map.

**Review by balajijinnah — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6324)* status: 10 of 20 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @balajijinnah, @gja, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 983 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGNuI5H2jk9b_1Z64fX:-MGg6OmC4eu1cE8EOVAi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2b1428997abe5c2a3610d86ee268bf845119ba9/edgraph/server.go#L983)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

There is already a function called `validateForGraphql`. I don't understand why you need this. Can you please work with @abhimanyusinghgaur to make sure we are not adding any duplicate functions or variables here.
</blockquote></details>

Done.
___
*[x/keys.go, line 533 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGNtZ2q7oglRp_MfojD:-MGgB7lk3IEBrzj8f32_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2b1428997abe5c2a3610d86ee268bf845119ba9/x/keys.go#L533)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I think these should not be here rather in `graphReservedPredicate` map. I don't understand why these are here? Do you need them for a `*` query?
</blockquote></details>

Done.
___
*[x/x.go, line 175 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6324#-MGNu0eK8KbFeKemB1wg:-MGgB8VV2MjyWIn1iQ0S:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2b1428997abe5c2a3610d86ee268bf845119ba9/x/x.go#L175)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

There is already a function for this, why define another map.
</blockquote></details>

Done.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 10 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6324)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gja, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

**Pull request merged**
