### PR TITLE
dgraphzero: lease flag

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1583)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Some comments.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphzero/raft.go, line 243 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-Kva9h07ncIPZ3A_J1I4:-Kva9h07ncIPZ3A_J1I5:bys6n6q) ([raw file](https://github.com/dgraph-io/dgraph/blob/ad2a516fca218262669f30da71c44917e7693cb6/cmd/dgraphzero/raft.go#L243)):*
> ```Go
> 		state.MaxLeaseId = p.MaxLeaseId
> 	}
> 	if p.MaxLeaseId == 0 {
> ```

if p.MaxLeaseId > 0 and < state.MaxLeaseId, we should return an error? Or, at lease log it.

---

*[cmd/dgraphzero/raft.go, line 245 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-Kva9wcUPyC8F0hYV_hk:-Kva9wcUPyC8F0hYV_hl:b-osx85k) ([raw file](https://github.com/dgraph-io/dgraph/blob/ad2a516fca218262669f30da71c44917e7693cb6/cmd/dgraphzero/raft.go#L245)):*
> ```Go
> 	if p.MaxLeaseId == 0 {
> 		// Don't show lease proposals - they occur too frequently to be useful.
> 		x.Printf("Applied proposal: %+v\n", p)
> ```

Not sure why this printf is in the else. or in an if now. We can just print it directly, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-:-KvaA4hmkdUylPTGJ4VG:b-xkzuoz)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphzero/raft.go, line 243 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-Kva9h07ncIPZ3A_J1I4:-KvaBGCQQN3LULa5wqJ3:b-d08hid) ([raw file](https://github.com/dgraph-io/dgraph/blob/ad2a516fca218262669f30da71c44917e7693cb6/cmd/dgraphzero/raft.go#L243)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if p.MaxLeaseId > 0 and < state.MaxLeaseId, we should return an error? Or, at lease log it.
</blockquote></details>

Done. Logging it out.

---

*[cmd/dgraphzero/raft.go, line 245 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-Kva9wcUPyC8F0hYV_hk:-KvaBJriGOOcTiyWTpKo:b-6giy7m) ([raw file](https://github.com/dgraph-io/dgraph/blob/ad2a516fca218262669f30da71c44917e7693cb6/cmd/dgraphzero/raft.go#L245)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not sure why this printf is in the else. or in an if now. We can just print it directly, right?
</blockquote></details>

@janardhan1993 mentioned to me it was occurring too frequently to be useful output. I'll defer to his judgement here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraphzero/raft.go, line 245 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-Kva9wcUPyC8F0hYV_hk:-KvaGMd9lry7ysAC7UA3:bflnau8) ([raw file](https://github.com/dgraph-io/dgraph/blob/ad2a516fca218262669f30da71c44917e7693cb6/cmd/dgraphzero/raft.go#L245)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

@janardhan1993 mentioned to me it was occurring too frequently to be useful output. I'll defer to his judgement here.
</blockquote></details>

Lease changes happen too frequently i couldn't see tablet size update proposals  in middle of them.
Probably better not to print lease proposals. Or may be print only the lease id for proposals which update lease.

---

*[cmd/dgraphzero/raft.go, line 242 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-KvaFxKnhB76tL0E6mvo:-KvaFxKnhB76tL0E6mvp:btuy4xp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6fa62407d225fcd1a71bebe1a016fa5b5dc44f5/cmd/dgraphzero/raft.go#L242)):*
> ```Go
> 	if p.MaxLeaseId > state.MaxLeaseId {
> 		state.MaxLeaseId = p.MaxLeaseId
> 	} else {
> ```

else if p.maxleaseid != 0
This proposal is used for other purposes also- for membership information and tablet sizes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-:-KvaGedPeWarXr-88rDT:bnfp4nl)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraphzero/raft.go, line 245 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583#-Kva9wcUPyC8F0hYV_hk:-KvaLoEuDWkmh85nfjFu:b-jjqy37) ([raw file](https://github.com/dgraph-io/dgraph/blob/ad2a516fca218262669f30da71c44917e7693cb6/cmd/dgraphzero/raft.go#L245)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Lease changes happen too frequently i couldn't see tablet size update proposals  in middle of them.
Probably better not to print lease proposals. Or may be print only the lease id for proposals which update lease.
</blockquote></details>

Hmm, okay I'll leave as is for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1583)*

**Pull request merged**
