### PR TITLE
Added functionality to marshal/unmarshal schema types in binary

### PR DESCRIPTION
**Pull request by kostub**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/229)

### CODE REVIEW

**Comment by manishrjain** [comment]
Clean code. I wonder if it's verbosity can be reduced. Though, I can imagine why it is necessary. So, have a few questions for you, answer them and ping me again. Or, we can have a quick VC to discuss the implementation.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[gql/definitions.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEm8Qh8LiLlyTG_PF8:-KSEm8Qh8LiLlyTG_PF9:b3svxca) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/definitions.go#L37)):*
Go style guide is against long names.

> Variable Names

> Variable names in Go should be short rather than long. This is especially true for local variables with limited scope. Prefer c to lineCount. Prefer i to sliceIndex.

> The basic rule: the further from its declaration that a name is used, the more descriptive the name must be. For a method receiver, one or two letters is sufficient. Common variables such as loop indices and readers can be a single letter (i, r). More unusual things and global variables need more descriptive names.

---

*[gql/definitions.go, line 49 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEpxMsTVu74ugQx0Zk:-KSEpxMtFGhjity03lza:b-pxczy1) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/definitions.go#L49)):*
> ```Go
> 
> // TypeValueUnmarshaler type is for unmarshaling a TypeValue from
> // binary/text format.
> ```

The lines can be 100 characters long. So, you could fit this comment into one line.

---

*[gql/definitions.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEtllgzGt7JlN8cOBK:-KSEtllgzGt7JlN8cOBL:b-9o0gev) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/definitions.go#L50)):*
> ```Go
> // TypeValueUnmarshaler type is for unmarshaling a TypeValue from
> // binary/text format.
> type TypeValueUnmarshaler interface {
> ```

How about just Unmarshaler? Or Encoder or Decoder? A name lot smaller than TypeValueUnmarshaler.

For e.g.

unmarshal := new(Unmarshaler)
unmarshal.Binary(data)
unmarshal.Text(data)

Or, are you trying to implement some interfaces?

---

*[gql/scalar_types.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEwefz7-GmHSQxxdLj:-KSEwefz7-GmHSQxxdLk:brz5sx9) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L37)):*
> ```Go
> 			" numeric values. Int can represent values between -(2^31)" +
> 			" and 2^31 - 1.",
> 		Unmarshaler: int32Unmarsh,
> ```

All this encoding decoding code, this isn't specific to GQL right? We can encode RDF as well, as per our discussions. If so, it shouldn't lie here. It should be in it's own separate package.

Or, maybe just the encoding should lie in a separate package, or maybe in RDF package. And the decoding could be in GQL.

---

*[gql/scalar_types.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEvTcFfPZig_cfLWR_:-KSEvTcFfPZig_cfLWRa:bri6sc6) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L87)):*
> ```Go
> func (v Int32Type) MarshalBinary() ([]byte, error) {
> 	var bs [4]byte
> 	binary.LittleEndian.PutUint32(bs[:], uint32(v))
> ```

do you need this colon? why not just binary.Put..(bs, ..)

---

*[gql/scalar_types.go, line 102 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEw89opu1OmD8Xo4zP:-KSEw89opu1OmD8Xo4zQ:bv4s3xq) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L102)):*
> ```Go
> }
> 
> type int32Unmarshaler struct{}
> ```

Why not one struct with 6 functions? MarshalText, MarshalBinary, MarshalJSON, UnmarshalBinary, UnmarshalText. I reckon UnmarshalJSON is not required?

---

*[gql/scalar_types.go, line 105 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEvp_JQZzb4xyHps1m:-KSEvp_KVrj0RVO_SLqo:b-jr6loc) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L105)):*
> ```Go
> 
> func (v int32Unmarshaler) UnmarshalBinary(data []byte) (TypeValue, error) {
> 	val := binary.LittleEndian.Uint32(data)
> ```

Can't this throw an error? If we pass something invalid?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-:-KSEx3cQtCAaEh3UEklb:bdmhmdc)*

**Comment by kostub** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[types/definitions.go, line 47 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSFjfiWxoABTkg_0evi-r3-47:-KSFkF5fR0WQXqUlQFhx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/80c7b6a9544597852f77a01dbf3589b40d8f82eb/types/definitions.go#L47)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported type Unmarshaler should be of the form "Unmarshaler ..." (with optional leading article)
</details>
Done.

---

*[types/scalar_types.go, line 82 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSFjfiWxoABTkg_0evj-r3-82:-KSFkCzaoB-6sLZZiPwb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/80c7b6a9544597852f77a01dbf3589b40d8f82eb/types/scalar_types.go#L82)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should omit type map[string]Type from declaration of var typeMap; it will be inferred from the right-hand side
</details>
Done.

---

*[gql/definitions.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEm8Qh8LiLlyTG_PF8:-KSFcG1PqFOvows-GE0p:bn8gu6x) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/definitions.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Go style guide is against long names.
> 
> > Variable Names
> 
> > Variable names in Go should be short rather than long. This is especially true for local variables with limited scope. Prefer c to lineCount. Prefer i to sliceIndex.
> 
> > The basic rule: the further from its declaration that a name is used, the more descriptive the name must be. For a method receiver, one or two letters is sufficient. Common variables such as loop indices and readers can be a single letter (i, r). More unusual things and global variables need more descriptive names.
</details>
I disagree. Variable names should be concise but readable. Single letter variable names are bad and makes the code hard to understand. None of my names are very long.

---

*[gql/definitions.go, line 49 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEpxMsTVu74ugQx0Zk:-KSFgfMdlFCoswfwigNv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/definitions.go#L49)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> The lines can be 100 characters long. So, you could fit this comment into one line.
</details>
Done.

---

*[gql/definitions.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEtllgzGt7JlN8cOBK:-KSFcYBDn9y75BDF03wj:b-zf7nkv) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/definitions.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> How about just Unmarshaler? Or Encoder or Decoder? A name lot smaller than TypeValueUnmarshaler.
> 
> For e.g.
> 
> unmarshal := new(Unmarshaler)
> unmarshal.Binary(data)
> unmarshal.Text(data)
> 
> Or, are you trying to implement some interfaces?
</details>
Changed name to Unmarshaler. The method names are consistent with the names in the encoding interfaces and are clearer. Maybe FromBinary(), FromText() might work better?

---

*[gql/scalar_types.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEwefz7-GmHSQxxdLj:-KSFcl5Y1dWMd49Tsqz8:bg7qwnj) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> All this encoding decoding code, this isn't specific to GQL right? We can encode RDF as well, as per our discussions. If so, it shouldn't lie here. It should be in it's own separate package.
> 
> Or, maybe just the encoding should lie in a separate package, or maybe in RDF package. And the decoding could be in GQL.
</details>
No moved it to a separate package.

---

*[gql/scalar_types.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEvTcFfPZig_cfLWR_:-KSFh8TNVWrn3flhDtJn:bcdolvn) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L87)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> do you need this colon? why not just binary.Put..(bs, ..)
</details>
It doesn't compile without the colon. Go does not automatically cast from an array to a slice.

---

*[gql/scalar_types.go, line 102 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEw89opu1OmD8Xo4zP:-KSFcuKI46cm5uMKVAtQ:b8l5y3w) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L102)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why not one struct with 6 functions? MarshalText, MarshalBinary, MarshalJSON, UnmarshalBinary, UnmarshalText. I reckon UnmarshalJSON is not required?
</details>
The reason for the current implementation is two fold:
1. With the current setup, using built in types like Time is easy because they already implement the TypeValue interface.
2. Moving all 5 functions to a single struct{} has the drawback that I have to accept and return interface{} objects since they could be any time. That requires me to do type assertions in the marshaling code. The approach with using the TypeValue interface is cleaner.

A second approach that I had initially implemented was to put the Unmarshal... functions on the TypeValue as well. The advantage of this method is that it matches the encoding interfaces. But the drawback is that since we are writing to the type as well, only *T satisfies the interface and not T. That means the types are all passed around using pointers and that makes simple things like checking for equality (using ==) complicated.

UnmarshalJSON is not required at this point.

---

*[gql/scalar_types.go, line 105 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEvp_JQZzb4xyHps1m:-KSFewUsAUTsI46Wsnbq:bxps473) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/gql/scalar_types.go#L105)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Can't this throw an error? If we pass something invalid?
</details>
It doesn't throw an error, just panics. I added some checks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/229)*

**Comment by manishrjain** [comment]
:lgtm_strong:  Couple of small comments. Just look at them, and then feel free to submit!

---

Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[types/definitions.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEm8Qh8LiLlyTG_PF8:-KSZRZTak33vgf8Rf8HU:b-rqpme4) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/types/definitions.go#L37)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> I disagree. Variable names should be concise but readable. Single letter variable names are bad and makes the code hard to understand. None of my names are very long.
</details>
OK. I can see your POV. But, we're following the Go style guide (with one notable exception, i.e. ID). So, if there's a more "Go" way of doing things, that's what we should be doing.

---

*[types/definitions.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEtllgzGt7JlN8cOBK:-KSZS4WaX2ro80RFQYmn:b-1mc0be) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/types/definitions.go#L50)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Changed name to Unmarshaler. The method names are consistent with the names in the encoding interfaces and are clearer. Maybe FromBinary(), FromText() might work better?
</details>
OK. Yeah, sounds like a good idea. unmarshaler.FromBinary(). Though, I think Decoder is an "easier" name, IMO. `decode.FromBinary()`.

---

*[types/scalar_types.go, line 105 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEvp_JQZzb4xyHps1m:-KSZT9h9dyyJUUMYDyau:b-lc5vct) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/types/scalar_types.go#L105)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> It doesn't throw an error, just panics. I added some checks.
</details>
OK. I was going to tell you to use the binary.Read func, but I think this is faster. 

---

*[types/scalar_types.go, line 120 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSZV27wJHq2_lG1kkyb:-KSZV27wJHq2_lG1kkyc:bfdp5t7) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c430295c8d65f2bf7e6133123e6723b7cf61824/types/scalar_types.go#L120)):*
> ```Go
> type unmarshalInt32 struct{}
> 
> func (v unmarshalInt32) UnmarshalBinary(data []byte) (TypeValue, error) {
> ```

Does this have to return TypeValue? Why not just int32?

---

*[types/scalar_types.go, line 167 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSZUtSwNL5g_hbn-eYQ:-KSZUtSwNL5g_hbn-eYR:bmcuzic) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c430295c8d65f2bf7e6133123e6723b7cf61824/types/scalar_types.go#L167)):*
> ```Go
> 	}
> 	u := binary.LittleEndian.Uint64(data)
> 	val := math.Float64frombits(u)
> ```

BTW Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-:-KSZVh37nG1ZLl21cbgB:b-wb2tnn)*

**Comment by kostub** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[types/definitions.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEtllgzGt7JlN8cOBK:-KS_MykJo5j-RNwikIR4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/types/definitions.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> OK. Yeah, sounds like a good idea. unmarshaler.FromBinary(). Though, I think Decoder is an "easier" name, IMO. `decode.FromBinary()`.
</details>
Done.

---

*[types/scalar_types.go, line 105 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSEvp_JQZzb4xyHps1m:-KS_JushwbhpvR-ee7Eq:b-hbsti0) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3d9fb1ed186a4544d8408c99a873437abcfd035/types/scalar_types.go#L105)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> OK. I was going to tell you to use the binary.Read func, but I think this is faster. 
</details>
binary.Read is 100x slower. See my post on benchmarks on discuss.

---

*[types/scalar_types.go, line 120 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/229#-KSZV27wJHq2_lG1kkyb:-KS_JoUoPJeo2m-Lq9Pk:b-rccx3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c430295c8d65f2bf7e6133123e6723b7cf61824/types/scalar_types.go#L120)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Does this have to return TypeValue? Why not just int32?
</details>
Yes. To obey the interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/229)*

**Pull request closed without merging**
