### PR TITLE
fix(dgraph): Panic because of nil map in groups.go

### PR DESCRIPTION
**Pull request by rahulgurnani**
Fixes DGRAPH-1935

delta.GroupChecksums is nil at this point in the code, so copying keys to this map causes the code to panic with message:
`assignment to entry in nil map`

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5999)

### CODE REVIEW

**Comment by rahulgurnani** [comment]
@martinmr Addressed your review comment.

**Comment by martinmr** [comment]
Can you run your tests locally. Lots of tests are failing so maybe the change is not as benign as we thought. But possible that this is just TeamCity acting up.

**Comment by parasssh** [comment]
All CI tests pass locally.

**Comment by parasssh** [comment]
> Can you run your tests locally. Lots of tests are failing so maybe the change is not as benign as we thought. But possible that this is just TeamCity acting up.

Actually, the code was faulty. Made the fix to do a make on the map just before using it in the for loop as Rahul had it earlier.

**Pull request merged**
