### PR TITLE
Optimize memory usage of bulkloader

### PR DESCRIPTION
**Pull request by xiangzhao632**
This PR optimize memory usage of reduce stage of bulkloader while not harming speed。
Related to https://github.com/dgraph-io/dgraph/pull/4529

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5525)

 
 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-a6a11556eb-69051.surge.sh)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Hi @xiangzhao632 

Thanks for the PR. Could you please merge `dgraph:master` into your fork so that the diff is cleaner. Also, could you share some benchmarking numbers that you were able to observe before and after this change? Things like the memory bulk loader used and the time that it takes to load your dataset.

**Comment by xiangzhao632** [comment]
@pawanrawal Thanks very much for reply! I have  merged dgraph:master into my fork. And I have finished my test. The number is :
About Data: 300million rdf (600million edge)。Before change: load time 38m01s, memory usage 67G; after: load time 14m40s, mem 18G. 
I noticed that since V20.03.1, the reduce stage of bulkloader had changed from a min-heap style to another method. And my optimise is based on previous version, so I switch back.

**Comment by xiangzhao632** [comment]
memory usage before change(total memory is 192G)
image
and the load time
image

**Comment by xiangzhao632** [comment]
memory usage after change
image
and the load time
image

**Comment by xiangzhao632** [comment]
I find something wrong , please waiting for me to fix it.

**Comment by awsl-dbq** [comment]
cool

**Comment by xiangzhao632** [comment]
Hi @pawanrawal, has anyone tested this? Could someone tell me this pr works or not?
OOM is a big issue, for two reason:
1. The largest memory of my machines is 192g (many other teams are 128G). Such memory can only cope with 3 billion rdf, while my team have more than 50 billion rdf. I know some teams who want to try dgraph, but due to the OOM issue, they can't init a cluster by bulkloader and they turned to liveloader.
2. Less memory usage in the reduce stage means that --reducer can be set to a larger value, which can also increase the loading speed.

**Comment by xiangzhao632** [comment]
#5361

**Comment by mangalaman93** [comment]
@xiangzhao632 Thank you for the PR. We are happy to look at the PR again if you can sign the CLA and raise it against the `main` branch. If you need any help, please let me know.

**Pull request closed without merging**
