### PR TITLE
snapshot aggressively

### LINKED ISSUE #2032: Dgraph server terminate when receive predicates
### version

```
Dgraph version   : v1.0.2-dev
Commit SHA-1     : 646e7795
Commit timestamp : 2018-01-18 17:13:04 +1100
Branch           : HEAD
```

### spec
OS: Coreos beta 1632.1.0
RAM: 32GiB (aws ec2 instance m4.xlarge)

### How do I run dgraph

```
$ dgraph zero --my <private_ip>:5080 --port_offset -2000 --idx 1
$ dgraph server --my <private_ip>:7080 --zero <private_ip>:5080 --memory_mb 16384 --idx 11
```

1. Up zero and  execute bulk loading
	* `dgrpah bulk -s schema -r rdf --zero_addr <private_ip>:5080 --http localhost:8000 --reduca_shards 1 --map_shards=2`
1. Up dgraph server  in same instance
2. Add two nodes to above cluster
	* . Each instance running zero and server

After add nodes, first zero try to move predicates that generated with bulk loader.
Bad crash server  by out of memory…
However I set memory config referring to [Get started — Dgraph Doc v1.0.2](https://docs.dgraph.io/get-started/#from-installed-binary).

**server log**
```
2018/01/18 12:27:36 predicate_move.go:52: Writing 147968 keys
2018/01/18 12:27:36 predicate_move.go:52: Writing 148298 keys
2018/01/18 12:27:37 predicate_move.go:52: Writing 147986 keys
2018/01/18 12:27:37 predicate_move.go:52: Writing 148072 keys
2018/01/18 12:27:37 predicate_move.go:52: Writing 148116 keys
2018/01/18 12:27:38 predicate_move.go:52: Writing 147975 keys
2018/01/18 12:27:38 predicate_move.go:52: Writing 148065 keys
2018/01/18 12:27:39 predicate_move.go:52: Writing 147872 keys
2018/01/18 12:27:39 predicate_move.go:52: Writing 148079 keys
2018/01/18 12:27:39 predicate_move.go:52: Writing 148171 keys
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x131661e, 0x16)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xcb8f850000, 0x2010000, 0x0, 0x1aaa658)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x1a91120, 0x2010000, 0x7f77670fa390)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x1a91120, 0x1001, 0x0)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x1a91120, 0x1001, 0x1aaa668, 0x7f7766cf0cb0)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x1a91120, 0x1001, 0x7f76cffe0101, 0x8c585c)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7f76cffe6e10)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x1a91120, 0x1001, 0x7f76cf010101, 0x8c4ec4)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0x2000126, 0x7f7e16ff0101, 0xcb8f53cd06)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/malloc.go:827 +0x98

```

Do you have any idea to avoid crash by out of memory?
Thanks.

### PR DESCRIPTION
**Pull request by janardhan1993**
Fixes #2032 

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2041)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm:

Just verify that incremental snapshotting actually works as expected.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[edgraph/config.go, line 128 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L3QKZ5lnbCh1QEvyqbM:-L3QKZ5lnbCh1QEvyqbN:b-ld13te) ([raw file](https://github.com/dgraph-io/dgraph/blob/189fdd3da091075668e97b7622f974ba154b73db/edgraph/config.go#L128)):*
> ```Go
> 	worker.Config.ZeroAddr = Config.ZeroAddr
> 	worker.Config.RaftId = Config.RaftId
> 	worker.Config.MaxPendingCount = Config.MaxPendingCount
> ```

Is there a flag for this too?

---

*[worker/draft.go, line 610 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L3QKMrCq0J-EcGxEhDy:-L3QKMrCq0J-EcGxEhDz:b-71hdr8) ([raw file](https://github.com/dgraph-io/dgraph/blob/e73751225042d1509274ca659967426bc71afe80/worker/draft.go#L610)):*
> ```Go
> 	// Find last snapshot index
> 	si := existing.Metadata.Index
> 	// Some proposals like KV can consume around 32MB per proposals, so keeping
> ```

like predicate move can ...

---

*[worker/draft.go, line 613 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L3QKbQdVa0tW7a4NyRb:-L3QKbQdVa0tW7a4NyRc:b-oeu8t4) ([raw file](https://github.com/dgraph-io/dgraph/blob/e73751225042d1509274ca659967426bc71afe80/worker/draft.go#L613)):*
> ```Go
> 	// too many proposals would increase the memory usage so snapshot as soon as
> 	// possible
> 	if snapshotIdx <= si+10 { // Ensure we have atleast 10 entries
> ```

If memory_mb < 2048, then we can make this lesser maybe 5?

---

*[worker/worker.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L3QHPx8Bqz9pV9VYAW8:-L3QHPx8Bqz9pV9VYAW9:bew5fee) ([raw file](https://github.com/dgraph-io/dgraph/blob/e73751225042d1509274ca659967426bc71afe80/worker/worker.go#L122)):*
> ```Go
> 	posting.StopLRUEviction()
> 	groups().Node.snapshot()
> }
> ```

We won't always do a snapshot now, if there are less than 10 entries. Shouldn't we always do a snapshot while shutting down?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-:-L3QKiIS0DEAfXJB3cZK:b6mdfqw)*

**Comment by janardhan1993** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[edgraph/config.go, line 128 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L3QKZ5lnbCh1QEvyqbM:-L43kOuz1-pUm0svu8me:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/189fdd3da091075668e97b7622f974ba154b73db/edgraph/config.go#L128)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Is there a flag for this too?
</blockquote></details>

Done.

---

*[worker/draft.go, line 610 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L3QKMrCq0J-EcGxEhDy:-L43kSmeUG7ZGYVr0W6y:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e73751225042d1509274ca659967426bc71afe80/worker/draft.go#L610)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

like predicate move can ...
</blockquote></details>

Done.

---

*[worker/worker.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L3QHPx8Bqz9pV9VYAW8:-L43kTmM21GGmY5ZSmTS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e73751225042d1509274ca659967426bc71afe80/worker/worker.go#L122)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We won't always do a snapshot now, if there are less than 10 entries. Shouldn't we always do a snapshot while shutting down?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041)*

**Comment by pawanrawal** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[posting/mvcc.go, line 79 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L43zaRF3Njj1JDxVcqF:-L43zaRF3Njj1JDxVcqG:b-ejplzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/84c7319ec9e4114a877549a64bcff2d303709ff0/posting/mvcc.go#L79)):*
> ```Go
> 
> type syncMark struct {
> 	index uint64
> ```

Is this raft index? Add a comment.

---

*[posting/mvcc.go, line 80 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L43zcyT1tWy5H6tIYRw:-L43zcyT1tWy5H6tIYRx:b-f9hlx6) ([raw file](https://github.com/dgraph-io/dgraph/blob/84c7319ec9e4114a877549a64bcff2d303709ff0/posting/mvcc.go#L80)):*
> ```Go
> type syncMark struct {
> 	index uint64
> 	ts    uint64
> ```

rename to startTs?

---

*[posting/mvcc.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L43zfq0PrfN5RJvPAGD:-L43zfq0PrfN5RJvPAGE:br0jx92) ([raw file](https://github.com/dgraph-io/dgraph/blob/84c7319ec9e4114a877549a64bcff2d303709ff0/posting/mvcc.go#L87)):*
> ```Go
> 	m         map[uint64]*Txn
> 	syncMarks []syncMark
> }
> ```

Add a comment about what is this for.

---

*[posting/mvcc.go, line 218 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041#-L43zyaFj7VjJ6VJsI46:-L43zyaFj7VjJ6VJsI47:boo38t6) ([raw file](https://github.com/dgraph-io/dgraph/blob/84c7319ec9e4114a877549a64bcff2d303709ff0/posting/mvcc.go#L218)):*
> ```Go
> 	t.Lock()
> 	defer t.Unlock()
> 	// Find max index with timestamp less than minTs
> ```

I am not sure that the loop gives you that. Is syncMarks guaranteed to be sorted by index or ts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2041)*

**Comment by janardhan1993** [comment]
Will open another

**Pull request closed without merging**
