### PR TITLE
Disable stacktrace by default, add stoptimer for benchmarking

### PR DESCRIPTION
**Pull request by jchiu0**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/214)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/main_test.go, line 139 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjX3XkgptdNmebBc0:-KRbjX3XkgptdNmebBc1:bbe6igr) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/cmd/dgraphloader/main_test.go#L139)):*
> ```Go
> 		uidStore.Get(uid.StringKey(it))
> 	}
> 	b.StopTimer()
> ```

Do you need this? It would automatically be stopped right when the function exits.

---

*[store/store.go, line 92 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjlGc_uKZdlnCDDdi:-KRbjlGc_uKZdlnCDDdj:btwwqgw) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/store/store.go#L92)):*
> ```Go
> 	}
> 
> 	val := valSlice.Data()
> ```

return valSlice.Data(), nil

---

*[store/store_test.go, line 146 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjqADE3ulaix4ethg:-KRbjqADE3ulaix4ethh:bm2aps1) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/store/store_test.go#L146)):*
> ```Go
> 		}
> 	}
> 	b.StopTimer()
> ```

I don't think you need this.

---

*[x/error.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjwv0ETGAvnGPuWK1:-KRbjwv0ETGAvnGPuWK2:b-ruxyc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/x/error.go#L40)):*
> ```Go
> 
> var (
> 	stackTrace = flag.Bool("stacktrace", false, "enable stacktrace for errors")
> ```

I was thinking we have an opt flag, and use it at any other places as well, where we can optimize the flow in the live server. If you can't think of any other places, then we keep this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/214)*

**Comment by jchiu0** [comment]
Review status: 7 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/main_test.go, line 139 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjX3XkgptdNmebBc0:-KRcSThByJL__jitiKlS:bf58br9) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/cmd/dgraphloader/main_test.go#L139)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Do you need this? It would automatically be stopped right when the function exits.
</details>
I thought it might include some function calls that have been deferred?

---

*[store/store.go, line 92 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjlGc_uKZdlnCDDdi:-KRcT3vMjZdS8rVThZvJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/store/store.go#L92)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> return valSlice.Data(), nil
</details>
Done.

---

*[store/store_test.go, line 146 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjqADE3ulaix4ethg:-KRcT4hPe4qf_4diwSnM:bm60nub) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/store/store_test.go#L146)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I don't think you need this.
</details>
Same as above. Trying to not include deferred calls.

---

*[x/error.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjwv0ETGAvnGPuWK1:-KRcTRr6Xp_GEdQkP4Z7:bf4y0ye) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/x/error.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I was thinking we have an opt flag, and use it at any other places as well, where we can optimize the flow in the live server. If you can't think of any other places, then we keep this.
</details>
Opt flag? You mean "optimized" I suppose? Sounds more like a "debug" flag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/214)*

**Comment by manishrjain** [comment]
:lgtm_strong:  One small comment about flag. Address that, and feel free to submit.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[x/error.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjwv0ETGAvnGPuWK1:-KRd27H9k19mxpvql4M8:b-62qka1) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/x/error.go#L40)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Opt flag? You mean "optimized" I suppose? Sounds more like a "debug" flag?
</details>
DONE. debug flag should be fine as well. The point is to have one which we can use at any place where we feel we can optimize live execution at the cost of decreased debugging prowess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-:-KRd2S5HYTIOhBQRNsdN:b-p8acxf)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[x/error.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/214#-KRbjwv0ETGAvnGPuWK1:-KRgC2p076y7zlwwnzbG:b-gbs5ib) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3812d081cb8b63b166bca5142fa790ebddcf7dc/x/error.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> DONE. debug flag should be fine as well. The point is to have one which we can use at any place where we feel we can optimize live execution at the cost of decreased debugging prowess.
</details>
I do like "blaze build -c opt" but I feel it is better to keep the default as "no stack trace" as our users wouldn't know, and it is good to let default flag values be false. (Unless we like users to give us their stack trace when they run into errors. Let me proceed with the debug flag and submit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/214)*

**Comment by manishrjain** [comment]
`blaze build -c opt`, ahh.. nice to hear it again!

**Pull request closed without merging**
