### PR TITLE
Simple TLS test suite

### PR DESCRIPTION
**Pull request by tzdybal**
Set of scripts for semi-automatic testing of TLS.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/658)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Nice work. Thanks for integrating it with Travis. A lot of this also needs to go in the Wiki I suppose?

One thing I think is that it doesn't need to run on all feature branches. You could check for current branch (using TRAVIS_BRANCH) and do a regex match to check if its not master or release you could just not run these tests. What do you think?

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/tlstest/Makefile, line 13 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/658#-KepfCx_P0rzpbtxmUXw:-KepfCx_P0rzpbtxmUXx:b-hxys93) ([raw file](https://github.com/dgraph-io/dgraph/blob/e92657e4c28d89ba1e45b1241185a2f83f4dea4a/contrib/tlstest/Makefile#L13)):*
> ```Makefile
> 	@echo "Basic TLS communication, encrypted keys (with password)"
> 	@./test.sh ./server_pass.sh ./client_pass.sh 0
> 	@echo "TLS client authentication, unencrypted key"
> ```

Failure expected because no pass supplied by client and server says REQUIREANDVERIFY?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/658#-:-KepfaAgfZf5HrkFiCpO:bdyz2ih)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/658#-:-KepgkAiEDs5gqaKkdfk:bnfp4nl)*

**Comment by tzdybal** [comment]
Good idea. There is no reason to run this test after every commit on every branch.
Travis configuration updated - TLS testing only on master/release branches.

---

Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/tlstest/Makefile, line 13 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/658#-KepfCx_P0rzpbtxmUXw:-KfBMS8olV3aLQV6pNIN:b-qkvb0o) ([raw file](https://github.com/dgraph-io/dgraph/blob/e92657e4c28d89ba1e45b1241185a2f83f4dea4a/contrib/tlstest/Makefile#L13)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Failure expected because no pass supplied by client and server says REQUIREANDVERIFY?
</blockquote></details>

No certificate provided by client, and server requires valid one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/658#-:-KfBMCXaif4StWU9jFuC:bli3d6t)*

**Comment by tzdybal** [comment]
Changes merged to master.

**Pull request closed without merging**
