### PR TITLE
docs (feature): add documentation for auth on interfaces

### PR DESCRIPTION
**Pull request by bucanero**
This PR adds the documentation for `@auth` on interfaces

Fixes GRAPHQL-750

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6894)

 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-1358cfe3bc-109507.surge.sh)

### CODE REVIEW

**Review by minhaj-shakeel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6894)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @bucanero, @danielmai, @MichaelJCompton, and @minhaj-shakeel)

___
*[wiki/content/graphql/authorization/directive.md, line 145 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6894#-MMJf2fg1GfE3CaojQVD:-MMJf2fg1GfE3CaojQVE:b-gsq6z5) ([raw file](https://github.com/dgraph-io/dgraph/blob/1d98f91c2b74300977cc39a962bcbe1455cca1d8/wiki/content/graphql/authorization/directive.md#L145)):*
> ```Markdown
> When it comes to applying `@auth` rules on interfaces themselves, Dgraph will do a `union` query where it queries all the implementing types, and apply the authorization rules on them. 
> The final query will be an `OR` query joining the results from all the implementing types.
> ```

We can add the sample queries given in RFC for further clarification of Auth query should work on Interfaces.

**Review by minhaj-shakeel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6894)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @minhaj-shakeel)

___
*[wiki/content/graphql/authorization/directive.md, line 152 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6894#-MMOh61qD9I95rHFE1Ym:-MMOh61r1obaqJGK6yjm:bpngw4v) ([raw file](https://github.com/dgraph-io/dgraph/blob/35f13d11ca215bb552d3724260ec0292092fb958/wiki/content/graphql/authorization/directive.md#L152)):*
> ```Markdown
> 			name
> 		}
> 		answered
> ```

No need for the example here. Please remove it.
___
*[wiki/content/graphql/authorization/directive.md, line 171 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6894#-MMOh9oNCjmnkRiBr_9C:-MMOh9oNCjmnkRiBr_9D:b-pd0zx8) ([raw file](https://github.com/dgraph-io/dgraph/blob/35f13d11ca215bb552d3724260ec0292092fb958/wiki/content/graphql/authorization/directive.md#L171)):*
> ```Markdown
>     datePublished
>   }
> }
> ```

Please also add the corresponding DQL translation of this query as given in the RFC.

**Review by bucanero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6894)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @minhaj-shakeel)

___
*[wiki/content/graphql/authorization/directive.md, line 152 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6894#-MMOh61qD9I95rHFE1Ym:-MMQCYdu6anADpe1GqAD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/35f13d11ca215bb552d3724260ec0292092fb958/wiki/content/graphql/authorization/directive.md#L152)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

No need for the example here. Please remove it.
</blockquote></details>

Done.
___
*[wiki/content/graphql/authorization/directive.md, line 171 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6894#-MMOh9oNCjmnkRiBr_9C:-MMQCdN1BtQA1i-dNR7x:b-bjrdrw) ([raw file](https://github.com/dgraph-io/dgraph/blob/35f13d11ca215bb552d3724260ec0292092fb958/wiki/content/graphql/authorization/directive.md#L171)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

Please also add the corresponding DQL translation of this query as given in the RFC. 
</blockquote></details>

I think that the DQL translation shouldn’t be there in the document. It’s an implementation detail (internal)
The article is under the GraphQL section and we are only referring to GraphQL syntax. Adding DQL there out of the blue will bring confusion to the reader.

**Review by minhaj-shakeel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6894)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @minhaj-shakeel)

___
*[wiki/content/graphql/authorization/directive.md, line 171 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6894#-MMOh9oNCjmnkRiBr_9C:-MMQRo_95i1jIvjADcGI:bpqkvv7) ([raw file](https://github.com/dgraph-io/dgraph/blob/35f13d11ca215bb552d3724260ec0292092fb958/wiki/content/graphql/authorization/directive.md#L171)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

I think that the DQL translation shouldn’t be there in the document. It’s an implementation detail (internal)
The article is under the GraphQL section and we are only referring to GraphQL syntax. Adding DQL there out of the blue will bring confusion to the reader.
</blockquote></details>

Okay, then no need to add the example altogether here. We should remove it.

**Review by minhaj-shakeel — APPROVED** [review]

**Pull request merged**
