### PR TITLE
Encapsulate Call within the client pool library, so we don't have to …

### PR DESCRIPTION
**Pull request by manishrjain**
…expose the clients. Also, write tests for conn module.

[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/39)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/worker.go, line 25 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/39#-KBQt6u3tk2FibuItJT9:-KBQt6u3tk2FibuItJTA:1073993612) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab5c9bddaa1d3860837cce2e6dc8b3714a296bd3/worker/worker.go#L25)):*
This and the one below.

---

*[worker/worker.go, line 41 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/39#-KBQt9w_cqTGwNJtK7VG:-KBQt9w_cqTGwNJtK7VH:-484582581) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab5c9bddaa1d3860837cce2e6dc8b3714a296bd3/worker/worker.go#L41)):*
This.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/39)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/worker.go, line 25 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/39#-KBQt6u3tk2FibuItJT9:-KBQu-zmymN0K3LD3DQr:-778123870) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab5c9bddaa1d3860837cce2e6dc8b3714a296bd3/worker/worker.go#L25)):*
Ah.. yeah, my bad.

---

*[worker/worker.go, line 41 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/39#-KBQt9w_cqTGwNJtK7VG:-KBQu2WKtlMXgYOMQ352:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab5c9bddaa1d3860837cce2e6dc8b3714a296bd3/worker/worker.go#L41)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/39)*

**Comment by ashwin95r** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/39)*

**Comment by ashwin95r** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/39#-:-KBQuVfcbu5ScNtGYqg1:980077423)*

**Pull request merged**
