### PR TITLE
Port/wiki

### PR DESCRIPTION
**Pull request by pawanrawal**
Porting over Design Concepts, Dgraph compared to other Databases and Performance page.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/795)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[wiki/content/design-concepts/index.md, line 176 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/795#-Kgm3VF6lwZuMDzRni2Y:-Kgm3VF6lwZuMDzRni2Z:b-ajk10) ([raw file](https://github.com/dgraph-io/dgraph/blob/9e5b652eea6b958372cd8cf32e2b570cc0cb70cb/wiki/content/design-concepts/index.md#L176)):*
> ```Markdown
> from a system crash, by replaying all the mutations since the last write to `Posting List`.
> 
> ### Mutations
> ```

Some of the stuff around here might not be correct. Please suggest the relevant changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/795)*

**Comment by manishrjain** [comment]
:lgtm: A few comments, address them and feel free to submit.

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[wiki/config.toml, line 43 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/795#-KgmFAMvZCfxcInFUlqU:-KgmFAMvZCfxcInFUlqV:b-506qxf) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fd8036c7a7956b85aeb87f333d6777ed28dbeb/wiki/config.toml#L43)):*
> ```TOML
>   url = "/performance/"
>   identifier = "performance"
>   weight = -100
> ```

Are these pages going to be above Getting started and query lang? That shouldn't be the case.

---

*[wiki/content/performance/index.md, line 3 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/795#-KgmFUaeXJF2NfF-KPcG:-KgmFUaeXJF2NfF-KPcH:b-snatcc) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fd8036c7a7956b85aeb87f333d6777ed28dbeb/wiki/content/performance/index.md#L3)):*
> ```Markdown
> +++
> title = "Performance"
> weight = 0
> ```

Do you really have to declare this, if the weight is always set to zero here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/795#-:-KgmF_Miu2so6r045OUd:b-lkld0y)*

**Comment by pawanrawal** [comment]
Merging to release/v0.7.4 and master both.

---

Review status: 1 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[wiki/config.toml, line 43 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/795#-KgmFAMvZCfxcInFUlqU:-KgmmJJdfzkgNdqnuOX6:biceu0p) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fd8036c7a7956b85aeb87f333d6777ed28dbeb/wiki/config.toml#L43)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Are these pages going to be above Getting started and query lang? That shouldn't be the case.
</blockquote></details>

No, lesser weight are on top. Changed the weights to 1, 2, 3, 4 to make it cleaner.

---

*[wiki/content/performance/index.md, line 3 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/795#-KgmFUaeXJF2NfF-KPcG:-KgmmPCnhj5L7itcc6xj:bzi1hnh) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fd8036c7a7956b85aeb87f333d6777ed28dbeb/wiki/content/performance/index.md#L3)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do you really have to declare this, if the weight is always set to zero here?
</blockquote></details>

Nope, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/795#-:-KgmmSIEic6WfwW6HMbn:b-ta79uw)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
