### PR TITLE
Chinese FTS support

### PR DESCRIPTION
**Pull request by windoze**
- Use [Gojieba](https://github.com/yanyiwu/gojieba) as the analyzer implementation for language "zh-hans".
- Analyzers now have indexing and searching mode, which should use different strategies to tokenize CJK languages.
- Uses "zh_hans" in queries as GQL doesn't allow "-" in identifiers, while RDF/mutation are still using "zh-hans".

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1428)

### CODE REVIEW

**Comment by windoze** [comment]
Implemented #1421

**Comment by windoze** [comment]
There are still some packaging issues have not been done, Gojieba needs some [data files](https://github.com/yanyiwu/gojieba/tree/master/dict) to work properly, which need to be packaged with the main program or docker image.

**Comment by konding** [comment]
你好，这个pr放弃了吗

**Comment by manishrjain** [comment]
Hey @konding , 

Yeah, this PR didn't fit into our existing model. Bleve (the underlying library that we use for tokenization) has the same level of support for Chinese like Elastic Search, so we plan to just ensure that it works with Dgraph. And if not, it should be an easy fix to enable that.

**Comment by konding** [comment]
Thank you for your reply.
Is it  already in progress?

**Comment by manishrjain** [comment]
We don't have anyone working on this. Can you please file a Github issue, and we'll get someone to take a look.

**Comment by konding** [comment]
Sure,I can do it.

**Comment by GongZhengMe** [comment]
@windoze 最近刚刚学习使用dgraph，请问下如何在dgraph中使用gojieba作为分词解析器？或者如何使全文搜索支持中文

**Pull request closed without merging**
