### PR TITLE
fix(encoder): Use EncoderAlloc for manual allocations

### PR DESCRIPTION
**Pull request by jarifibrahim**
Based on PR https://github.com/dgraph-io/dgraph/pull/6327 .

The original PR https://github.com/dgraph-io/dgraph/pull/6327 had many conflicts with the base branch and it was easier to create a new PR than to clean up the old PR.

The `codec.Encoder` type and `codec.Encode()` function is used at many places in dgraph and using manually allocated memory in these functions would require all the callers to call `FreePack`. 

This PR creates a new `EncoderAlloc` type and `EncodeAlloc()` function that can be used by the bulk loader to manually allocate memory.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6447)

### CODE REVIEW

**Review by martinmr — COMMENTED** [review]
:lgtm: I think the issue I mentioned in the other PR will not affect us. It would only happen in the case when the list to rollup has no deltas (because we added an optimization to save us from recreating the packs in this case) and the list was read from disk. However, we only add lists to the rollup queue if it has deltas so this should not be the case and we should instead create new packs that are manually allocated.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6447#-:-MHCHYGx1YLgXYDr2UDg:b-w88qae)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

**Review by martinmr — CHANGES_REQUESTED** [review]
One comment that I just noticed.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6447#-:-MHCIblgA7Sj48zcd8op:b-bvg7sq)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @jarifibrahim, @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[posting/list.go, line 1590 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6447#-MHCIQR08wD_LFzeBXk6:-MHCIQR17dI0ZDuOW6IK:b-1vv7mj) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc088ef329014297ebfe58367aae2bf9728c0a70/posting/list.go#L1590)):*
> ```Go
> 	}
> 
> 	l.Pack = codec.EncodeAlloc(bl.Uids, blockSize)
> ```

The usages of this function should deal with the manually allocated memory. I think this was done in the previous PR but I don't see it here.

**Review by jarifibrahim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6447)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[posting/list.go, line 1590 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6447#-MHCIQR08wD_LFzeBXk6:-MHCLs8F5zbnOARX16zN:bz0t8ax) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc088ef329014297ebfe58367aae2bf9728c0a70/posting/list.go#L1590)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

The usages of this function should deal with the manually allocated memory. I think this was done in the previous PR but I don't see it here.
</blockquote></details>

The code is master already does freepack in loadfrombackup function.
See this https://github.com/dgraph-io/dgraph/blob/fc088ef329014297ebfe58367aae2bf9728c0a70/worker/restore.go#L179-L198

**Comment by jarifibrahim** [comment]
we don't need this PR anymore.

**Pull request closed without merging**
