### PR TITLE
Add a directive for ignoring reflexive edges.

### LINKED ISSUE #899: remove reflexive edges from results
Add a directive to remove self edges from results.  For example, in the following query, to remove actors as co actors of themselves.

```
{
  coactors(func:allofterms(name, "Jane Campion")) @cascade @normalize {
    JC_films as director.film {      # JC_films = all Jane Campion's films
      starting_movie: name
      starring {
        JC_actors as performance.actor {      # JC_actors = all actors in all JC films
          actor : name
          actor.film {
            performance.film @filter(not var(JC_films)) {  # find a different film
              film_together : name
              starring {
                # find a coactor who has been in some JC film
                performance.actor @filter(var(JC_actors)) {
                  coactor_name: name
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #899

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1153)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query.go, line 381 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-Koenl9BR7N_lYu9jrnL:-Koenl9CtDRZzPrySn3c:b-l6mwxj) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L381)):*
> ```Go
> 			parentIds := make([]uint64, 0, 10)
> 			sg.Params.parentIds = &parentIds
> ```

remove

---

*[query/query.go, line 387 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-KoeoTggXKhnTwNmX_r0:-KoeoTggXKhnTwNmX_r1:brnrbcr) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L387)):*
> ```Go
> 			return nil
> 		}
> 		// Push to stack.
> ```

Push myself to stack before sending this to children.

---

*[query/query_test.go, line 8239 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-Koeokm5h5cJ4ICFk-Co:-Koeokm5h5cJ4ICFk-Cp:bbvazpi) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query_test.go#L8239)):*
> ```Go
> 	query := `
> 	{
> 		me(func:anyofterms(name, "Michonne Rick Daryl")) @ignoreReflex {
> ```

Casing shouldn't make a difference.

Does this work for normalize.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-:-Koeox1ra6hzRtK_gy0E:bnfp4nl)*

**Comment by ashwin95r** [comment]
:lgtm: some comments

---

Reviewed 6 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/query.go, line 155 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-KoetUCJUPqGaBWLOkm6:-KoetUCJUPqGaBWLOkm7:bo7076x) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L155)):*
> ```Go
> 	uidCount     string
> 	numPaths     int
> 	parentIds    *[]uint64 // This is a stack that is maintained and passed down to children.
> ```

I think this can just be a slice ([]uint64).

---

*[query/query.go, line 364 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-Koev5HZcBtOLEjSb-3u:-Koev5HZcBtOLEjSb-3v:b-azchj7) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L364)):*
> ```Go
> }
> 
> func alreadySeen(parentIds []uint64, uid uint64) bool {
> ```

isPresentInSlice(...)?

---

*[query/query.go, line 380 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-KoesP3vB3rV5V2m2rvf:-KoesP3vB3rV5V2m2rvg:bo066km) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L380)):*
> ```Go
> 		if sg.Params.parentIds == nil {
> 			parentIds := make([]uint64, 0, 10)
> 			sg.Params.parentIds = &parentIds
> ```

Does this have to be a pointer? Slices are pointers by default

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-:-KoevHJGzqdR5yC1D08c:b-h0fntz)*

**Comment by pawanrawal** [comment]
Review status: 3 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 155 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-KoetUCJUPqGaBWLOkm6:-Kof-lxARfCCOnaiOwz1:b-z0q5eo) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L155)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I think this can just be a slice ([]uint64).
</blockquote></details>

yeah, good idea.

---

*[query/query.go, line 364 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-Koev5HZcBtOLEjSb-3u:-Kof-tqDqcPQif4Pa5oQ:b-bncqit) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L364)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

isPresentInSlice(...)?
</blockquote></details>

will punt on this.

---

*[query/query.go, line 380 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-KoesP3vB3rV5V2m2rvf:-Kof-oldHx9Jmv5Lj9X5:b-s5r7fn) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L380)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Does this have to be a pointer? Slices are pointers by default
</blockquote></details>

Yup, doesn't have to be.

---

*[query/query.go, line 381 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-Koenl9BR7N_lYu9jrnL:-Kof-xFc7aNR3dtQtWxi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L381)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[query/query.go, line 387 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-KoeoTggXKhnTwNmX_r0:-Kof-zP0al0xwuZuIMl_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query.go#L387)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Push myself to stack before sending this to children.
</blockquote></details>

Done.

---

*[query/query_test.go, line 8239 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153#-Koeokm5h5cJ4ICFk-Co:-Kof-zqGtVvyUBqT-dRu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f196f0a83f83b0c4816705ace8e65561fc9b83f2/query/query_test.go#L8239)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Casing shouldn't make a difference.

Does this work for normalize.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1153)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
