### PR TITLE
docs: Add a reference to /admin/schema

### PR DESCRIPTION
**Pull request by bucanero**
Fixes GRAPHQL-619

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6608)

 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-0351308705-99698.surge.sh)

### CODE REVIEW

**Review by abhimanyusinghgaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6608)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/admin/index.md, line 347 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIXfpBg0F5jBjqfM-Ah:-MIXfpBh2VX7cG6xxVu5:b-k0vm0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cd425ad24a585334086a676b5ea3243017814a1/wiki/content/graphql/admin/index.md#L347)):*
> ```Markdown
> 
> Given a blank database, running the `/admin` mutation:
> ```

should we add something like this?
```
There are two ways you can add the schema:
1. Using /admin/schema
...
...
2. Using updateGQLSchema mutation on /admin
...
...
```
I feel we should keep /admin/schema above the updateGQLSchema mutation because that is simpler to use and most users would just be looking for that.
___
*[wiki/content/graphql/admin/index.md, line 373 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIXiQ2tAEWZpsgXxUJr:-MIXiQ2tAEWZpsgXxUJs:blxvk8y) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cd425ad24a585334086a676b5ea3243017814a1/wiki/content/graphql/admin/index.md#L373)):*
> ```
> following definition
> ```
following schema definition
___
*[wiki/content/graphql/admin/index.md, line 381 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIXh_NE11INC5cYXQ5S:-MIXh_NF5epjcX-GuZOP:b-lpiz3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cd425ad24a585334086a676b5ea3243017814a1/wiki/content/graphql/admin/index.md#L381)):*
> ```
> the `/admin/schema` endpoint will post back the types it’s currently serving a schema for,
> which should be the same as the input schema
> ```
This endpoint just gives a JSON response with a success code. It doesn't post back the types that it is serving like the updateGQLSchema mutation. Did you mean something else by `post back`?
___
*[wiki/content/graphql/admin/index.md, line 383 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIXi73Q4rwYTSszMQm_:-MIXi73Q4rwYTSszMQma:b-9f1c3a) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cd425ad24a585334086a676b5ea3243017814a1/wiki/content/graphql/admin/index.md#L383)):*
> ```Markdown
> On successful execution, the `/admin/schema` endpoint will post back the types it’s currently serving a schema for, 
> which should be the same as the input schema.
> ```

should we also add this for curl users:
```
If you have the schema definition stored in a file, you can use curl like this:
curl -X POST localhost:8080/admin/schema --data-binary '@schema.graphql'
```

**Comment by bucanero** [comment]
hello @abhimanyusinghgaur, thanks for your feedback

I've made changes to address your comments and corrections. Please validate them when you have a chance.

**Review by bucanero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6608)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/admin/index.md, line 373 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIXiQ2tAEWZpsgXxUJr:-MIZboj0DbcDIoLtvjYe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cd425ad24a585334086a676b5ea3243017814a1/wiki/content/graphql/admin/index.md#L373)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> following definition
> ```
following schema definition
</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 381 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIXh_NE11INC5cYXQ5S:-MIZbyws4RwMwBFRiK7s:b-dagas4) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cd425ad24a585334086a676b5ea3243017814a1/wiki/content/graphql/admin/index.md#L381)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> the `/admin/schema` endpoint will post back the types it’s currently serving a schema for,
> which should be the same as the input schema
> ```
This endpoint just gives a JSON response with a success code. It doesn't post back the types that it is serving like the updateGQLSchema mutation. Did you mean something else by `post back`?
</blockquote></details>

My mistake. I fixed it and noted the JSON response.

**Review by abhimanyusinghgaur — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-:-MIZdqDE-z46PvHc6Vxw:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @danielmai and @MichaelJCompton)

**Review by MichaelJCompton — CHANGES_REQUESTED** [review]
Suggested some changes as bottom sections apply in both cases.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-:-MIuyVCq5nqBQjBi-VXv:b-ibj3a3)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/graphql/admin/index.md, line 27 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIutMaHEx_pPxnOg9UR:-MIutMaHEx_pPxnOg9US:bt1upn3) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L27)):*
> ```
>  to build an App
> ```

Let's cut this.  Deploy docs don't have anything to do with building an app.
___
*[wiki/content/graphql/admin/index.md, line 348 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuv3Z25IW62pW8sume:-MIuv3Z25IW62pW8sumf:b-owic55) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L348)):*
> ```
> add a schema
> ```

modify the GraphQL schema
___
*[wiki/content/graphql/admin/index.md, line 356 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuw4Cw8zj_OxvRxTHO:-MIuw4Cw8zj_OxvRxTHP:b-ks20w4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L356)):*
> ```
> Given a blank database, t
> ```

see note below, this can be deleted.
___
*[wiki/content/graphql/admin/index.md, line 375 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuw02g8rV54XsvZQfD:-MIuw02g8rV54XsvZQfE:bfkadnx) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L375)):*
> ```
> Given a blank database, r
> ```

see the note below.  This can go.
___
*[wiki/content/graphql/admin/index.md, line 390 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuuJF50Y4NDObi64_6:-MIuuJF50Y4NDObi64_7:bera2u4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L390)):*
> ```
> would cause the following:
> ```

the following discussion applies no mater what way you add the schema, so we probably need to restructure a bit to allow for both options .

How about:

Adding a Schema -> Modifying the Schema
   This just talks about the two different endpoints options and gives a quick example.

Then at about this point in the doc we add a section like "Initial Schema" or similar and say something like ...

Regardless of the method used to upload the schema, on a black database, adding this schema

```graphql
type Person {
	name: String
}
```

would cause the following...
___
*[wiki/content/graphql/admin/index.md, line 401 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuy6Nx3K7eGrqwW24v:-MIuy6Nx3K7eGrqwW24w:bgt7ube) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L401)):*
> ```
> running an `updateGQLSchema` mutation with the following input
> ```

then we need a few touchups in here to say something like just "updating the schema to the following"
___
*[wiki/content/graphql/admin/index.md, line 421 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuyFBiC2U8dYak_H_y:-MIuyFBiC2U8dYak_H_z:bc2z96w) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L421)):*
> ```
> `updateGQLSchema` 
> ```

again touchup to remove reference to updateGQLSchema here

**Review by bucanero — COMMENTED** [review]
Thank you Michael, I'll work on these suggestions.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-:-MJ-BkXV0ESKZQIk5X5D:bcnrv3l)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @danielmai and @MichaelJCompton)

___
*[wiki/content/graphql/admin/index.md, line 27 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIutMaHEx_pPxnOg9UR:-MJ-6Mpj3s7V6EqgW28J:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L27)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
>  to build an App
> ```

Let's cut this.  Deploy docs don't have anything to do with building an app.
</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 348 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuv3Z25IW62pW8sume:-MJ-BXyU2td3Cweld4Lv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L348)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> add a schema
> ```

modify the GraphQL schema
</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 356 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuw4Cw8zj_OxvRxTHO:-MJ-He_z-cO9uuoN9sQJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L356)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> Given a blank database, t
> ```

see note below, this can be deleted.
</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 375 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuw02g8rV54XsvZQfD:-MJ-HfMl6XerZA9bUWpd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L375)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> Given a blank database, r
> ```

see the note below.  This can go.
</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 390 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuuJF50Y4NDObi64_6:-MJ-Hg04BgQQiiFrcQGz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L390)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> would cause the following:
> ```

the following discussion applies no mater what way you add the schema, so we probably need to restructure a bit to allow for both options .

How about:

Adding a Schema -> Modifying the Schema
   This just talks about the two different endpoints options and gives a quick example.

Then at about this point in the doc we add a section like "Initial Schema" or similar and say something like ...

Regardless of the method used to upload the schema, on a black database, adding this schema

```graphql
type Person {
	name: String
}
```

would cause the following...



</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 401 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuy6Nx3K7eGrqwW24v:-MJ-Hgex9cd5eQTIzBTh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L401)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> running an `updateGQLSchema` mutation with the following input
> ```

then we need a few touchups in here to say something like just "updating the schema to the following"
</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 421 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-MIuyFBiC2U8dYak_H_y:-MJ-HhcTE6bVQQ3K6fEm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a147db56efadc702abbbb1b2c19c492ee6e2cb9c/wiki/content/graphql/admin/index.md#L421)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> `updateGQLSchema` 
> ```

again touchup to remove reference to updateGQLSchema here
</blockquote></details>

Done.

**Review by MichaelJCompton — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6608#-:-MJ-NRyw3OEOMKhsSen7:bg7igkv)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @danielmai and @MichaelJCompton)

**Pull request merged**
