### PR TITLE
fix(/commit): protect the commit endpoint via acl

### PR DESCRIPTION
**Pull request by NamanJain8**
`/commit` endpoint was not ACL protected. In a multi-tenant system, it could be disastrous where a malicious user can commit or abort the transactions of any namespace. This PR fixes this.

Fixes DGRAPH-3129

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7608)

### CODE REVIEW

**Review by NamanJain8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7608)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 1471 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7608#-MW5JPOm7TG4x-BPaOsq:-MW5JPOm7TG4x-BPaOsr:b-s5ipf7) ([raw file](https://github.com/dgraph-io/dgraph/blob/0a1e6d01882a02eafcac92d1025d70cd32febcd5/edgraph/server.go#L1471)):*
> ```Go
> 
> 	txn := posting.Oracle().GetTxn(startTs)
> 	if txn == nil {
> ```

TODO: Check if this `nil` check is necessary. Currently, added it as a failsafe.

**Review by aman-bansal — DISMISSED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7608)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @manishrjain, @martinmr, @NamanJain8, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 1490 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7608#-MW5NNub5MZ928sGsFuv:-MW5NMSl7WOO4oNE-5Xs:bha54iv) ([raw file](https://github.com/dgraph-io/dgraph/blob/0a1e6d01882a02eafcac92d1025d70cd32febcd5/edgraph/server.go#L1490)):*
> ```Go
> 	}
> 
> 	if x.WorkerConfig.AclEnabled {
> ```

I believe this wont work. you need to wait for all the raft entries to catchup. 
see this `if err := posting.Oracle().WaitForTs(ctx, m.StartTs); err != nil {
		return err
	}`

then only you can ensure that txn would be there

**Review by manishrjain — APPROVED** [review]
:lgtm: Do address @aman-bansal 's review comments.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7608#-:-MW5PJJf5qNzzYEnFlUd:bx71v2z)* status: all files reviewed, 4 unresolved discussions (waiting on @martinmr, @NamanJain8, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/http.go, line 507 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7608#-MW5Oohn-2iDLP9V4Hru:-MW5Oohn-2iDLP9V4Hrv:b-lscwfq) ([raw file](https://github.com/dgraph-io/dgraph/blob/0a1e6d01882a02eafcac92d1025d70cd32febcd5/dgraph/cmd/alpha/http.go#L507)):*
> ```Go
> 	tctx, err := (&edgraph.Server{}).CommitOrAbort(ctx, tc)
> 	switch {
> 	case tctx.Aborted == true:
> ```

no need to say == true.
___
*[edgraph/server.go, line 1476 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7608#-MW5Ow0a9XdA_Z9Ao0Qy:-MW5Ow0a9XdA_Z9Ao0Qz:bllbu2w) ([raw file](https://github.com/dgraph-io/dgraph/blob/0a1e6d01882a02eafcac92d1025d70cd32febcd5/edgraph/server.go#L1476)):*
> ```Go
> 
> 	if txn.Namespace != ns {
> 		return errors.New("Please log in into correct namespace.")
> ```

Mention the namespace that the user has. Don't mention the namespace that the txn has.

**Review by manishrjain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7608)* status: all files reviewed, 4 unresolved discussions (waiting on @aman-bansal, @martinmr, @NamanJain8, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 1471 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7608#-MW5JPOm7TG4x-BPaOsq:-MW5PdX48l1RqZ60LGsX:b-h6nwh2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0a1e6d01882a02eafcac92d1025d70cd32febcd5/edgraph/server.go#L1471)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

TODO: Check if this `nil` check is necessary. Currently, added it as a failsafe.
</blockquote></details>

we can return an error, that txn is not there.
___
*[edgraph/server.go, line 1490 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7608#-MW5NNub5MZ928sGsFuv:-MW5QUtZ4GkEvLIE-QdU:b-kxgfmi) ([raw file](https://github.com/dgraph-io/dgraph/blob/0a1e6d01882a02eafcac92d1025d70cd32febcd5/edgraph/server.go#L1490)):*
<details><summary><i>Previously, aman-bansal (aman bansal) wrote…</i></summary><blockquote>

I believe this wont work. you need to wait for all the raft entries to catchup. 
see this `if err := posting.Oracle().WaitForTs(ctx, m.StartTs); err != nil {
		return err
	}`

then only you can ensure that txn would be there
</blockquote></details>

That won't help. Because StartTs is assigned before mutations are applied. So, a server could be already at startTs, but not have the mutations.

Typically, the server which does the mutations, also gets the commit request. That way, the txn would be in the cache.

**Review by ahsanbarkati — APPROVED** [review]
Looks good

**Pull request merged**
