### PR TITLE
fix(GraphQL): Allow multiple aliases of Non Scalar field inside query.

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6918)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6918)* status: all files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton and @minhaj-shakeel)

___
*[graphql/e2e/common/query.go, line 2934 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZmqN167U_OJkJwNS3:-MMZmqN167U_OJkJwNS4:bi3qgfe) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/e2e/common/query.go#L2934)):*
> ```Go
> 				name
> 				ag1: statesAggregate(filter: {xcode: {in: ["ka", "mh"]}}) {
>                 	count   
> ```

remove spaces at end
___
*[graphql/resolve/query_rewriter.go, line 973 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZltAL1gfAH8mWE-1J:-MMZltAL1gfAH8mWE-1K:b-xc2xib) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L973)):*
> ```Go
> }
> 
> // Generated Unique Dgraph Alias for the field based on number of time we it has been
> ```

Generate unique Dgraph alias 
___
*[graphql/resolve/query_rewriter.go, line 974 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZlzZSA9cgi-o_zCro:-MMZlzZSA9cgi-o_zCrp:b-dnza20) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L974)):*
> ```Go
> 
> // Generated Unique Dgraph Alias for the field based on number of time we it has been
> // seen till now. If it is seen first time then simply returns the field's DgraphAlias,
> ```

till now in the given query at the current level.
___
*[graphql/resolve/query_rewriter.go, line 1025 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZkWAdDEdsmJnx4p-o:-MMZkWAeBwDytA4PurB0:b-4qfqti) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L1025)):*
> ```Go
> 	fieldSeenCount := make(map[string]int)
> 
> 	for _, f := range field.SelectionSet() {
> ```

This loop is not required because default value is 0 for Go maps and that would be used. 
___
*[graphql/resolve/query_rewriter.go, line 1100 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZkvNh3MywHe7ob2CB:-MMZkvNi9bqSdkMnoGZt:b-rvmj88) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L1100)):*
> ```Go
> 
> 		// if field is InbuiltType and it has already been added then skip
> 		if f.Type().IsInbuiltType() && (fieldSeenCount[f.DgraphAlias()] > 0) {
> ```

Can you verify that we can request ENUM multiple times with different aliases? Add a unit test for it.
___
*[graphql/resolve/resolver.go, line 1335 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZmFXk0EK7qcr0_0TP:-MMZmFXk0EK7qcr0_0TQ:bgktfj7) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/resolver.go#L1335)):*
> ```Go
> 	fieldSeenCount := make(map[string]int)
> 	for _, f := range fields {
> 		fieldSeenCount[f.DgraphAlias()] = 0
> ```

loop not required
___
*[graphql/resolve/resolver.go, line 1420 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZmf_V38geo_35HgV-:-MMZmf_V38geo_35HgV0:b232h18) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/resolver.go#L1420)):*
> ```Go
> 		x.Check2(buf.Write(completed))
> 		comma = ", "
> 		fieldSeenCount[f.DgraphAlias()]++
> ```

How does this work for scalar with different alias?

```
queryUser {
  n1: name
  n2: name
}
```

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6918)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/e2e/common/query.go, line 2934 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZmqN167U_OJkJwNS3:-MMZsYS_E-IMKJ-K4mDY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/e2e/common/query.go#L2934)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

remove spaces at end
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 973 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZltAL1gfAH8mWE-1J:-MMZsZKI2HV9u4SoxC4c:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L973)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Generate unique Dgraph alias 
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 974 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZlzZSA9cgi-o_zCro:-MMZseCS8MoNktN8DkXo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L974)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

till now in the given query at the current level.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 1025 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZkWAdDEdsmJnx4p-o:-MMZsevM4LG4VWS2DVOp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L1025)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This loop is not required because default value is 0 for Go maps and that would be used. 
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 1100 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZkvNh3MywHe7ob2CB:-MM_8uTw6v4fji37rxDJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/query_rewriter.go#L1100)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can you verify that we can request ENUM multiple times with different aliases? Add a unit test for it.
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 1335 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZmFXk0EK7qcr0_0TP:-MMZsfwG9e-kTvSrDOME:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/resolver.go#L1335)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

loop not required
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 1420 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZmf_V38geo_35HgV-:-MMZtrfFBJe13UeDIp7J:bav3i6b) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/resolve/resolver.go#L1420)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

How does this work for scalar with different alias?

```
queryUser {
  n1: name
  n2: name
}
```
</blockquote></details>

Updated The code according to this.

**Review by pawanrawal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6918)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/e2e/common/query.go, line 2959 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_AJ2q8N1VaDFNGfR6:-MM_AJ2q8N1VaDFNGfR7:b-b4974p) ([raw file](https://github.com/dgraph-io/dgraph/blob/6af51bd6e1ec355cdf3d5250b4eadc0d73446803/graphql/e2e/common/query.go#L2959)):*
> ```Go
> }
> 
> func queryCountAtChildLevelWithMultipleAliasOnScalarField(t *testing.T) {
> ```

It's not a count query. The test case should be `queryChildMultipleTimesWithDifferentAlias`

**Review by vmrajas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6918)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/e2e/common/query.go, line 2934 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MMZmqN167U_OJkJwNS3:-MM_QoMX02VcmMIzbxKN:bsjorv5) ([raw file](https://github.com/dgraph-io/dgraph/blob/c28a1dda5ccf55de99a450c01955a4430ae199e4/graphql/e2e/common/query.go#L2934)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fix indentation for count
___
*[graphql/e2e/common/query.go, line 1919 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_QjGE36TXKK_f5iGY:-MM_QjGE36TXKK_f5iGZ:b-dlj0cn) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/e2e/common/query.go#L1919)):*
> ```Go
> 		`{
> 		"queryAuthor": [
>       {
> ```

Fix indentation
___
*[graphql/resolve/query_rewriter.go, line 900 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_Qu-74uotUmrGXKIG:-MM_Qu-74uotUmrGXKIH:buhzesb) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/resolve/query_rewriter.go#L900)):*
> ```Go
> func buildAggregateFields(
> 	f schema.Field,
> 	fieldSeenCount map[string]int,
> ```

I see that the only use for fieldSeenCount in buildAggregateFields function is to obtain the alias for the field name. Instead of passing fieldSeenCount, can you just pass
the alias and add a comment as to why the alias has been passed.
___
*[graphql/resolve/query_rewriter.go, line 1045 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_RJ255j6jwh7s-7dF:-MM_RJ255j6jwh7s-7dG:b6segqh) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/resolve/query_rewriter.go#L1045)):*
> ```Go
> 		if f.IsAggregateField() {
> 
> 			aggregateChildren, aggregateAuthQueries := buildAggregateFields(f, fieldSeenCount, auth)
> ```

The alias to be passed to buildAggregateFields function will have to be generated just above this line.
___
*[graphql/resolve/query_test.yaml, line 2569 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_Relz-wop-VIo70E7:-MM_Relz-wop-VIo70E8:b-lm18vc) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/resolve/query_test.yaml#L2569)):*
> ```YAML
>         count_postsAggregate1 : count(Author.posts) @filter(gt(Post.tags, "abc"))
>         count_postsAggregate2 : count(Author.posts) @filter(le(Post.tags, "xyz"))
>         dgraph.uid : uid
> ```

Can you use the same filter `filter: {tags: {gt: "abc"}}` for both aliases, p1 and p2. I can see that even if there are two fields with the same filter, two different fields will be generated in the DQL query.  Adding test with same filter will make this behaviour clear.
This behaviour could later on be optimised to just generated a single field in case of the same filter. File a JIRA for this fix and if possible link it in the code with a TODO comment. Something like
// TODO(JIRA Number): Description of JIRA

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6918)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @MichaelJCompton, @pawanrawal, and @vmrajas)

___
*[graphql/e2e/common/query.go, line 2959 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_AJ2q8N1VaDFNGfR6:-MM__A2gA7-qu5L3pqvt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6af51bd6e1ec355cdf3d5250b4eadc0d73446803/graphql/e2e/common/query.go#L2959)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

It's not a count query. The test case should be `queryChildMultipleTimesWithDifferentAlias`
</blockquote></details>

Done.
___
*[graphql/e2e/common/query.go, line 1919 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_QjGE36TXKK_f5iGY:-MM_gIUs2dbal9NP_-4j:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/e2e/common/query.go#L1919)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Fix indentation
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 900 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_Qu-74uotUmrGXKIG:-MM_a0Al-nGmviYBbmEf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/resolve/query_rewriter.go#L900)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

I see that the only use for fieldSeenCount in buildAggregateFields function is to obtain the alias for the field name. Instead of passing fieldSeenCount, can you just pass
the alias and add a comment as to why the alias has been passed.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 1045 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_RJ255j6jwh7s-7dF:-MM_gFLp0FqKcmfQowux:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/resolve/query_rewriter.go#L1045)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

The alias to be passed to buildAggregateFields function will have to be generated just above this line.
</blockquote></details>

Done.
___
*[graphql/resolve/query_test.yaml, line 2569 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6918#-MM_Relz-wop-VIo70E7:-MM_gEXJ7raViEjIKZ7Z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6470d3e2db914c0c265a94ad6d6f708d142248c/graphql/resolve/query_test.yaml#L2569)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Can you use the same filter `filter: {tags: {gt: "abc"}}` for both aliases, p1 and p2. I can see that even if there are two fields with the same filter, two different fields will be generated in the DQL query.  Adding test with same filter will make this behaviour clear.
This behaviour could later on be optimised to just generated a single field in case of the same filter. File a JIRA for this fix and if possible link it in the code with a TODO comment. Something like
// TODO(JIRA Number): Description of JIRA  
</blockquote></details>

Done.

**Review by vmrajas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6918)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton, @pawanrawal, and @vmrajas)

**Comment by minhaj-shakeel** [comment]
Unable to merge this PR due to inability to Pass CLA because some commits are not linked to github account( things messed up).

**Pull request closed without merging**
