### PR TITLE
fix(GRAPHQL): Added support for exact index on field having @id directive.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Currently we add `hash` index on a field of type `String! @id` by default. And as index exact and `hash` are not compatible , user can't add exact index on such field and can't take advantage of comparator functions like` lt,le,gt,ge.`

To allow this we now changing that behavior, i.e. for a field of type String!` @id @search(by:[exact])` , we don't generate default `hash` index and only generate `exact` index.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534)

### CODE REVIEW

**Review by vmrajas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534)* status: all files reviewed, 4 unresolved discussions (waiting on @JatinDevDG and @pawanrawal)

___
*[graphql/schema/gqlschema.go, line 1652 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN5_iICx8DFRTjuii7:-MVN5_iICx8DFRTjuii8:b-i58z09) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/gqlschema.go#L1652)):*
> ```Go
> 		// If @id directive is applied along with @search, we check if the search has hash as an
> 		// arg. If it doesn't and there is no exact arg, then we add hash in it.
> 		if !hasIndex(indexes, "hash") && !hasIndex(indexes, "exact") {
> ```

This logic will still give an error if both hash and exact index have been specified in @search. Eg @search (by: [exact, hash]) . Can we also handle this case over here ?
___
*[graphql/schema/gqlschema.go, line 1660 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN5RBW1SH9DUCL8us8:-MVN5RBW1SH9DUCL8us9:b9vv280) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/gqlschema.go#L1660)):*
> ```Go
> 
> func hasIndex(indexes []string, index string) bool {
> 	for i := range indexes {
> ```

for _, index := range indexes .
You may have to change the name of `index` argument to the function.
___
*[graphql/schema/schemagen.go, line 661 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN8K0a0AgVvIbs-6y7:-MVN8K0a0AgVvIbs-6y8:b-lgmn5m) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/schemagen.go#L661)):*
> ```Go
> 							if !hasIndex(indexes, "exact") {
> 								indexes = append(indexes, "hash")
> 							}
> ```

Should we also be checking for hash over here. I wonder what will happen in case hash is added to search directive. I believe it will get added twice to generated DQL schema.
Example: @id @search(by: [hash])

This could be existing bug.
___
*[graphql/schema/testdata/schemagen/input/exact-index-on-id-field.graphql, line 1 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN8vIBA9wYfJ_WqXCj:-MVN8vIBA9wYfJ_WqXCk:bf70v52) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/testdata/schemagen/input/exact-index-on-id-field.graphql#L1)):*
> ```GraphQL
> # This will add exact index on content field, overwriting the default "hash" index for field of type "String! @id".
> ```

Let's try to keep the number of files in schemagen/input as minimum as possible. I believe this change does not warrant a new files of its own. Can you change some existing String! @id in some existing input file to String! @id @search(by: [exact])

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @id, @pawanrawal, and @vmrajas)

___
*[graphql/schema/gqlschema.go, line 1652 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN5_iICx8DFRTjuii7:-MVPjy0H4jhRVcbCT7Zg:b3v01d) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/gqlschema.go#L1652)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

This logic will still give an error if both hash and exact index have been specified in @search. Eg @search (by: [exact, hash]) . Can we also handle this case over here ?
</blockquote></details>

yeah, that should give an error. Because we can't allow both indexes. But if a user gives only the exact index then he should not get any error .
___
*[graphql/schema/gqlschema.go, line 1660 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN5RBW1SH9DUCL8us8:-MVPo3rp9Li8UZWWdDBo:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/gqlschema.go#L1660)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

for _, index := range indexes .
You may have to change the name of `index` argument to the function.
</blockquote></details>

changed.
___
*[graphql/schema/schemagen.go, line 661 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN8K0a0AgVvIbs-6y7:-MVPrrpK7LSV3AtIZr9k:bmhguuy) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/schemagen.go#L661)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Should we also be checking for hash over here. I wonder what will happen in case hash is added to search directive. I believe it will get added twice to generated DQL schema.
Example: @id @search(by: [hash])

This could be existing bug.
</blockquote></details>

no, it won't get added multiple time because we store indexes on dgraph predicate in a map as below.
                    pred = dgPred{
				typ:     typStr,
				indexes: make(map[string]bool),
				upsert:  upsertStr,
			}
___
*[graphql/schema/testdata/schemagen/input/exact-index-on-id-field.graphql, line 1 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN8vIBA9wYfJ_WqXCj:-MVPwxMWCnixegMw6ykV:b-eoifk5) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/testdata/schemagen/input/exact-index-on-id-field.graphql#L1)):*
<details><summary><i>Previously, vmrajas wrote…</i></summary><blockquote>

Let's try to keep the number of files in schemagen/input as minimum as possible. I believe this change does not warrant a new files of its own. Can you change some existing String! @id in some existing input file to String! @id @search(by: [exact])
</blockquote></details>

changed existing files.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-:-MVQCOLx-yEhFYL9pmle:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @id, @pawanrawal, and @vmrajas)

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
let's also add a test in `dgraph_schemagen_test.yml` after this existing test `Field with @id directive and a hash arg in search directive generates correct schema.` to make sure that the correct dgraph schema is generated for this case too.

> Reviewed 1 of 5 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-:-MVQOncu5JOr9XoFF5te:b-q456uo)* status: all files reviewed, 6 unresolved discussions (waiting on @id, @JatinDevDG, @pawanrawal, and @vmrajas)

___
*[graphql/schema/gqlschema.go, line 1652 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVN5_iICx8DFRTjuii7:-MVQRSpsBFFRs2RQYwcb:bql26ub) ([raw file](https://github.com/dgraph-io/dgraph/blob/7feab026f9474b289c5e8e5d728a9db6c6749a3d/graphql/schema/gqlschema.go#L1652)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

yeah, that should give an error. Because we can't allow both indexes. But if a user gives only the exact index then he should not get any error .
</blockquote></details>

Yeah! if explicitly both hash and exact have been specified we should give an error as is happening currently.
___
*[graphql/schema/gqlschema.go, line 1659 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVQQnAz9hifuKbzSonR:-MVQQnAz9hifuKbzSonS:b-b7goo7) ([raw file](https://github.com/dgraph-io/dgraph/blob/df7ec74b6da30b6da540217930eb780bb1e4ab01/graphql/schema/gqlschema.go#L1659)):*
> ```Go
> }
> 
> func hasIndex(indexes []string, indexName string) bool {
> ```

we already have a function in `x` pkg: `x.HasString()` which does the same thing. Use that in place of this.
___
*[graphql/schema/gqlschema_test.yml, line 2840 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVQQLUU3xci9FCeNJeb:-MVQQLUU3xci9FCeNJec:b-29pr78) ([raw file](https://github.com/dgraph-io/dgraph/blob/df7ec74b6da30b6da540217930eb780bb1e4ab01/graphql/schema/gqlschema_test.yml#L2840)):*
> ```YAML
>         f2: String! @id
>       }
> ```

Let's also add an `invalid_schemas` test which applies both hash and exact in `@search` and should give appropriate error.

**Review by vmrajas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534)* status: all files reviewed, 2 unresolved discussions (waiting on @JatinDevDG and @pawanrawal)

**Review by vmrajas — APPROVED** [review]
LGTM. With Abhimanyu's requested changes, this should be good to go.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @danielmai, @pawanrawal, and @vmrajas)

___
*[graphql/schema/gqlschema.go, line 1659 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVQQnAz9hifuKbzSonR:-MVQnGGQCRoU3QiapjI_:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/df7ec74b6da30b6da540217930eb780bb1e4ab01/graphql/schema/gqlschema.go#L1659)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we already have a function in `x` pkg: `x.HasString()` which does the same thing. Use that in place of this.
</blockquote></details>

changed.
___
*[graphql/schema/gqlschema_test.yml, line 2840 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7534#-MVQQLUU3xci9FCeNJeb:-MVQnI4o7xNuUa_-9y02:b-xlqccl) ([raw file](https://github.com/dgraph-io/dgraph/blob/df7ec74b6da30b6da540217930eb780bb1e4ab01/graphql/schema/gqlschema_test.yml#L2840)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

Let's also add an `invalid_schemas` test which applies both hash and exact in `@search` and should give appropriate error.
</blockquote></details>

There is already a test for it. 
"Search doesn't allow hash and exact together"

**Review by abhimanyusinghgaur — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7534)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pawanrawal)

**Pull request merged**
