### PR TITLE
fix(test): porting test driver changes

### PR DESCRIPTION
**Pull request by skrdgraph**
## Problem
Port `t.go` diffs from `master` -> `main`. 

## Solution
- I was initially planning to do this by cherry-picking commits for git-tracking purposes
- BUT the commits are squashed, and I will also have to bring in non-test code changes. I am only porting the `diffs` because of this. 
- Most of these `diffs` are coming from this https://github.com/dgraph-io/dgraph/commit/1017c4ed1f9a8521efd318665642408b6280609e 
- These changes don't affect the test-driver code (I have tested it locally)
- The fixes brought into this PR creates a `log` file for test runs and also prints to console

### CODE REVIEW

**Comment by skrdgraph** [comment]
@joshua-goldstein this is cherry-picking `t.go` changes from `master` -> `main`.... it dumps the results of `t.go` to a `log` file locally. That was the only difference which I am porting over to `main`.

**Review by dshekhar95 — APPROVED** [review]
straightforward log file changes

**Review by joshua-goldstein — APPROVED** [review]
Looks good 👍

**Review by sanjayk-github-dev — APPROVED** [review]
Looks good

**Pull request merged**
