### PR TITLE
Introduce geo functions

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/335)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 86 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXK2P5IQFO-7Sr3BQ25:-KXK2P5JsDeEFIaCmY2k:b-m50hly) ([raw file](https://github.com/dgraph-io/dgraph/blob/56e5c31435c0b0601b83ddd0be4793951b0e8ae1/worker/task.go#L86)):*
> ```Go
> 	if useFunc {
> 		// Tokenize here.
> 		tokens, geoQuery, err = getTokens(q.SrcFunc)
> ```

geoQuery is obtained while forming the tokens for geo data. So it has been added to getTokens function. If we want to make it separate, we can. But it'll be a lot of repeated code as both of them follow the same code path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/335)*

**Comment by ashwin95r** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[geo/filter.go, line 54 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXK-8NFbD5irCnsSd3--r3-54:-KXL4FmJTcEoStC-5luD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b01f9b043144eb074c6380311430a39c9489755/geo/filter.go#L54)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function IsGeoFunc should have comment or be unexported
</details>
Done.

---

*[geo/filter.go, line 69 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXK-8NFbD5irCnsSd3--r3-69:-KXL4KJtCw1vaQxQ13jC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b01f9b043144eb074c6380311430a39c9489755/geo/filter.go#L69)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function GetTokens should have comment or be unexported
</details>
Done.

---

*[geo/filter.go, line 275 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXK-8NFbD5irCnsSd3--r3-275:-KXL4N-ZopvNDOnzTXW2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b01f9b043144eb074c6380311430a39c9489755/geo/filter.go#L275)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function FilterUids should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/335)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 8 files at r1, 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[geo/filter.go, line 81 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL5CdFXhCdxQ2dG4VY:-KXL5CdFXhCdxQ2dG4VZ:bbkkak4) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/geo/filter.go#L81)):*
> ```Go
> 				len(funcArgs))
> 		}
> 		return queryTokens(QueryTypeNear, funcArgs[1], funcArgs[2])
> ```

parse the distance here.

---

*[geo/filter.go, line 87 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL5EE2G8mUSzRw308c:-KXL5EE2G8mUSzRw308d:b-2eaa4m) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/geo/filter.go#L87)):*
> ```Go
> 				len(funcArgs))
> 		}
> 		return queryTokens(QueryTypeWithin, funcArgs[1], "0")
> ```

send 0.0, not "0" -- In general, try to parse arguments as early as possible, so internal functions can have clear static types.

---

*[geo/filter.go, line 106 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL4x5RdAwv4eWlazA-:-KXL4x5RdAwv4eWlazA0:b-5logsx) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/geo/filter.go#L106)):*
> ```Go
> 
> // queryTokens returns the tokens to be used to look up the geo index for a given filter.
> func queryTokens(qt QueryType, data string, maxDist string) ([]string, *QueryData, error) {
> ```

Why not take in float: maxDist float?

---

*[query/geo_test.go, line 77 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL7tqvoa0i2QYHUrNN:-KXL7tqvoa0i2QYHUrNO:bfaf51e) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/query/geo_test.go#L77)):*
> ```Go
> 	addGeoData(t, ps, 4, poly, "SF Bay area")
> 	poly = geom.NewPolygon(geom.XY).MustSetCoords([][]geom.Coord{
> 		{{-122.06, 37.37}, {-122.1, 37.36}, {-122.12, 37.4}, {-122.11, 37.43}, {-122.04, 37.43}, {-122.06, 37.37}},
> ```

Over 100 chars in many places in this file. Fix all.

---

*[query/geo_test.go, line 132 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL7rD7AC4WqmSK7Czd:-KXL7rD86tJaxoLUC2Mb:b-mq0bg9) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/query/geo_test.go#L132)):*
> ```Go
> 		Alias: "me",
> 		Func: &gql.Function{Attr: "geometry", Name: "within", Args: []string{
> 			`{"Type":"Polygon", "Coordinates":[[[-122.06, 37.37], [-122.1, 37.36], [-122.12, 37.4], [-122.11, 37.43], [-122.04, 37.43], [-122.06, 37.37]]]}`},
> ```

Over 100 chars.

---

*[worker/task.go, line 167 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL7zUc394EQXb5RSvO:-KXL7zUc394EQXb5RSvP:b1defy1) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/worker/task.go#L167)):*
> ```Go
> 		}
> 
> 		uidsNew := geo.FilterUids(uids, values, geoQuery)
> ```

filtered := 

---

*[worker/tokens.go, line 15 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL8L0Vk4ba2wdh6zlP:-KXL8L0Vk4ba2wdh6zlQ:bho9x2j) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/worker/tokens.go#L15)):*
> ```Go
> 	switch funcName {
> 	case "anyof":
> 		if len(funcArgs) != 2 {
> ```

You can just fallthrough in this. The logic is the same.

---

*[worker/tokens.go, line 16 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL8Nq2o7VYCvprNOqQ:-KXL8Nq2o7VYCvprNOqR:buuov33) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/worker/tokens.go#L16)):*
> ```Go
> 	case "anyof":
> 		if len(funcArgs) != 2 {
> 			return nil, x.Errorf("anyof function requires 2 arguments, but got %d",
> ```

Just don't mention the function name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-:-KXL8V0chTkqglSstGS7:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 3 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[geo/filter.go, line 81 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL5CdFXhCdxQ2dG4VY:-KXLGPTyQffqJMOjp4SE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/geo/filter.go#L81)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> parse the distance here.
</details>
Done.

---

*[geo/filter.go, line 87 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL5EE2G8mUSzRw308c:-KXLGQ4vd6gBWY6CV0XE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/geo/filter.go#L87)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> send 0.0, not "0" -- In general, try to parse arguments as early as possible, so internal functions can have clear static types.
</details>
Done.

---

*[geo/filter.go, line 106 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL4x5RdAwv4eWlazA-:-KXLH1vVvlD1Dd2_HNUj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/geo/filter.go#L106)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why not take in float: maxDist float?
</details>
Done.

---

*[query/geo_test.go, line 77 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL7tqvoa0i2QYHUrNN:-KXLClqhGjEuBf2CV0c5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/query/geo_test.go#L77)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Over 100 chars in many places in this file. Fix all.
</details>
Done.

---

*[query/geo_test.go, line 132 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL7rD7AC4WqmSK7Czd:-KXLCmo5oojPFCVX9UG3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/query/geo_test.go#L132)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Over 100 chars.
</details>
Done.

---

*[worker/task.go, line 167 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL7zUc394EQXb5RSvO:-KXLCxFoWVUb5QIcM7Tc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/worker/task.go#L167)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> filtered := 
</details>
Done.

---

*[worker/tokens.go, line 15 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL8L0Vk4ba2wdh6zlP:-KXLDuzisahcW0eCKyHQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/worker/tokens.go#L15)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can just fallthrough in this. The logic is the same.
</details>
Done.

---

*[worker/tokens.go, line 16 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXL8Nq2o7VYCvprNOqQ:-KXLDveSpPbRGxcVDULs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/204b77cea1d2751516bd9f71e861090bf91a8842/worker/tokens.go#L16)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Just don't mention the function name.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/335)*

**Comment by jchiu0** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[worker/task.go, line 155 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXNfeHgE0uTEi7biztb:-KXNfeHgE0uTEi7biztc:b-122ugp) ([raw file](https://github.com/dgraph-io/dgraph/blob/44acf7f7d4f53b0b1fa52be9df212dbce5f9046c/worker/task.go#L155)):*
> ```Go
> 			key := posting.Key(uid, attr)
> 			pl, decr := posting.GetOrCreate(key)
> 			defer decr()
> ```

Might be better to decr at end of loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/335)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-:-KXNmpE_J3uxYKk6A5zO:bnfp4nl)*

**Comment by ashwin95r** [comment]
Thanks for the review!

---

Review status: 7 of 8 files reviewed at latest revision, 13 unresolved discussions.

---

*[worker/task.go, line 155 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-KXNfeHgE0uTEi7biztb:-KXOWRHkiW-WcEaevRU5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/44acf7f7d4f53b0b1fa52be9df212dbce5f9046c/worker/task.go#L155)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Might be better to decr at end of loop.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/335#-:-KXOWV5fA0OWx_XP_d4D:b-9qdoz3)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
