### PR TITLE
Multiple/sort

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1409)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 9 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[gql/parser.go, line 56 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUmxhTm8msuAvMZ3vO:-KtUmxhTm8msuAvMZ3vP:b-qa7gsi) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/gql/parser.go#L56)):*
> ```Go
> 	Args map[string]string
> 	// Query can have multiple sort parameters.
> 	OrderAttr    []string
> ```

Create a struct around these two fields.

---

*[query/query.go, line 1932 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUp9lELIH-u2ewXq7B:-KtUp9lELIH-u2ewXq7C:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/query/query.go#L1932)):*
> ```Go
> 	for _, it := range sg.Params.NeedsVar {
> 		// TODO(pawan) - Return error if user uses var order with predicates.
> 		if len(sg.Params.OrderAttr) > 0 && it.Name == sg.Params.OrderAttr[0] && (it.Typ == gql.VALUE_VAR) {
> ```

100 chars.

---

*[types/sort.go, line 52 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUpmt5D57bcX5wjrlN:-KtUpmt5D57bcX5wjrlO:b-s69guy) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L52)):*
> ```Go
> // Less compares two elements
> func (s byValue) Less(i, j int) bool {
> 	if len(s.values[i]) == 0 || len(s.values[j]) == 0 {
> ```

assign the i'th and j'th element to vars upfront.

---

*[types/sort.go, line 59 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUq4lF6c2LOmYYEWi3:-KtUq4lF6c2LOmYYEWi4:bb7qfpo) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L59)):*
> ```Go
> 	}
> 
> 	for idx, _ := range s.values[i] {
> ```

vidx

---

*[types/sort.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUqGmgs2wzmvDFkZFD:-KtUqGmgs2wzmvDFkZFE:b-f8zjcs) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L63)):*
> ```Go
> 		// and at last place while doing ascending sort.
> 		if s.values[i][idx].Value == nil {
> 			if s.desc[idx] {
> ```

return s.desc[idx]

---

*[worker/sort.go, line 321 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUqtb8ZurZVw8ECMjH:-KtUqtb8ZurZVw8ECMjI:b-37ntad) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L321)):*
> ```Go
> 
> 	// SrcUids for other queries are all the uids present in the response of the first sort.
> 	destUids := destUids(r.reply.UidMatrix)
> ```

Refactor this logic out into a separate function.

---

*[worker/sort.go, line 445 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUrqjI0u8aNCbPwhRB:-KtUrqjI0u8aNCbPwhRC:byhmgrl) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L445)):*
> ```Go
> 	}
> 	r, err := ProcessTaskOverNetwork(ctx, in)
> 	select {
> ```

No need for select here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-:-KtUrzNYWZMzDaCf76zi:bnfp4nl)*

**Comment by janardhan1993** [comment]
Reviewed 3 of 9 files at r1, 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[gql/parser.go, line 2128 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUpRkStYSccAfbfKnv:-KtUpRkT4tfiyQB7A87L:b-3inxup) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/gql/parser.go#L2128)):*
> ```Go
> 
> 	expectArg := true
> 	order := make(map[string]bool)
> ```

map[string]struct{}

---

*[query/query.go, line 1932 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUqq_CmkyA2gUHGViA:-KtUqq_CmkyA2gUHGViB:b-xhgmqo) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/query/query.go#L1932)):*
> ```Go
> 	for _, it := range sg.Params.NeedsVar {
> 		// TODO(pawan) - Return error if user uses var order with predicates.
> 		if len(sg.Params.OrderAttr) > 0 && it.Name == sg.Params.OrderAttr[0] && (it.Typ == gql.VALUE_VAR) {
> ```

Check this at the top level itself, either all var or all predicates.

---

*[query/query.go, line 2033 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUr5AiVFK9U-BVMqUW:-KtUr5AiVFK9U-BVMqUX:b2ap4xd) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/query/query.go#L2033)):*
> ```Go
> func (sg *SubGraph) sortAndPaginateUsingVar(ctx context.Context) error {
> 	if sg.Params.uidToVal == nil {
> 		return x.Errorf("Variable: [%s] used before definition.", sg.Params.OrderAttr[0])
> ```

We don't do multiple var ??

---

*[types/sort.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUt05MrsMRiUJ5we3J:-KtUt05MrsMRiUJ5we3K:b-wogsw4) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L55)):*
> ```Go
> 		return false
> 	}
> 	if s.values[i][0].Tid != s.values[j][0].Tid {
> ```

Everything should be converted to schema type before calling this. So ideally they shouldn't be of different type for same predicate.

---

*[types/sort.go, line 62 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUtK80qc8T7F5fiWEu:-KtUtK80qc8T7F5fiWEv:btd2hkm) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L62)):*
> ```Go
> 		// Null value is considered greatest hence comes at first place while doing descending sort
> 		// and at last place while doing ascending sort.
> 		if s.values[i][idx].Value == nil {
> ```

Do we have same behaviour in sortandpaginateusing vars ?, keep all the uids with null value at the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[worker/sort.go, line 45 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUwaIUXfZVT6yhete-:-KtUwaIUXfZVT6yhete0:b-rna56q) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L45)):*
> ```Go
> type sortresult struct {
> 	reply *protos.SortResult
> 	vals  [][]types.Val
> ```

We don't need this if it's single attribute ?

---

*[worker/sort.go, line 364 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUy_s5uuERzYSdyM7Q:-KtUy_s5uuERzYSdyM7R:b-btx9rb) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L364)):*
> ```Go
> 	for i := 1; i < len(ts.Attr); i++ {
> 		or := <-och
> 		if or.err != nil && oerr == nil {
> ```

shouldn't it be break ?

---

*[worker/sort.go, line 371 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUyjMv7jff1fVfN8Rv:-KtUyjMv7jff1fVfN8Rw:b-aan3he) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L371)):*
> ```Go
> 		result := or.r
> 		x.AssertTrue(len(result.ValueMatrix) == len(destUids.Uids))
> 		seen = map[uint64]bool{}
> ```

aren't destUids deduplicated ? why do we need seen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[gql/parser.go, line 56 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUmxhTm8msuAvMZ3vO:-KtjCb3oqcQVe2S2q0hN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/gql/parser.go#L56)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a struct around these two fields.
</blockquote></details>

Done.

---

*[gql/parser.go, line 2128 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUpRkStYSccAfbfKnv:-KtipKsGrYwCEwdTHKlG:b-9rnqk7) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/gql/parser.go#L2128)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

map[string]struct{}
</blockquote></details>

Is that better? I think thats more useful if I have some starting values.

---

*[query/query.go, line 1932 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUqq_CmkyA2gUHGViA:-Ktiv1hjj4yLjV1W4mrR:b-sk74kf) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/query/query.go#L1932)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Check this at the top level itself, either all var or all predicates.
</blockquote></details>

Will do this later. Have a TODO for it.

---

*[query/query.go, line 1932 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUp9lELIH-u2ewXq7B:-KtjCbqZUzNRv_Aa20yL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/query/query.go#L1932)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[query/query.go, line 2033 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUr5AiVFK9U-BVMqUW:-Ktiv9nlaTADgIuhwe6x:b32w12) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/query/query.go#L2033)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We don't do multiple var ??
</blockquote></details>

No

---

*[types/sort.go, line 52 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUpmt5D57bcX5wjrlN:-KtjCclMLolCc4YhT2Sz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L52)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

assign the i'th and j'th element to vars upfront.
</blockquote></details>

Done.

---

*[types/sort.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUt05MrsMRiUJ5we3J:-KtjCd4l1OSwnkrztqHX:b-ucqwhh) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L55)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Everything should be converted to schema type before calling this. So ideally they shouldn't be of different type for same predicate.
</blockquote></details>

Yeah we dont need this check

---

*[types/sort.go, line 59 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUq4lF6c2LOmYYEWi3:-KtjAQelM4S-wOKiTnfq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L59)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

vidx
</blockquote></details>

Done.

---

*[types/sort.go, line 62 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUtK80qc8T7F5fiWEu:-KtjASDQFNTgh6rvHQYF:b-g3weya) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L62)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Do we have same behaviour in sortandpaginateusing vars ?, keep all the uids with null value at the end.
</blockquote></details>

I think we just dont consider them.

---

*[types/sort.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUqGmgs2wzmvDFkZFD:-KtjAREr5f41ZXI6k68J:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return s.desc[idx]
</blockquote></details>

Done.

---

*[worker/sort.go, line 45 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUwaIUXfZVT6yhete-:-KtjAWc8EUU51xBAOJOK:bl1euf5) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L45)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We don't need this if it's single attribute ?
</blockquote></details>

Yes but I need to have a common API.

---

*[worker/sort.go, line 321 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUqtb8ZurZVw8ECMjH:-KtjE4YXItdEzxVuDMcm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L321)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Refactor this logic out into a separate function.
</blockquote></details>

Done.

---

*[worker/sort.go, line 364 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUy_s5uuERzYSdyM7Q:-KtjCAgShiusWsoHQlw5:br1ivis) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L364)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

shouldn't it be break ?
</blockquote></details>

Waiting for all of them to finish, else trace issue.

---

*[worker/sort.go, line 371 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUyjMv7jff1fVfN8Rv:-KtjCMoEyNuLUQ2rzu5G:bhz3os6) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L371)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

aren't destUids deduplicated ? why do we need seen.
</blockquote></details>

Actually we dont need it here.

---

*[worker/sort.go, line 445 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUrqjI0u8aNCbPwhRB:-KtjC_Hpxcj6HfsOtXQQ:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L445)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for select here.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409)*

**Comment by janardhan1993** [comment]
Review status: 1 of 11 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[types/sort.go, line 62 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUtK80qc8T7F5fiWEu:-KtjG8q-bwytTyWPiGC2:b9p2jhl) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/types/sort.go#L62)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I think we just dont consider them.
</blockquote></details>

Shouldn't we have same behaviour there also with multiple vars.

---

*[worker/sort.go, line 364 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-KtUy_s5uuERzYSdyM7Q:-KtjGRFXdjMXtEBD93yf:b-tg54sr) ([raw file](https://github.com/dgraph-io/dgraph/blob/72e7b4f60b30c5de2e123e871fe4a23c6ae03983/worker/sort.go#L364)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Waiting for all of them to finish, else trace issue.
</blockquote></details>

We continue on first error but on next error we do processing which we don't need to
if oerr != nil {
continue 
} ??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 1 of 11 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1409#-:-KtjGiSKXU13Leo3bUOT:bnfp4nl)*

**Comment by pawanrawal** [comment]
This was merged to master.

**Pull request closed without merging**
