### PR TITLE
Update/badger

### PR DESCRIPTION
**Pull request by pawanrawal**
Use the new API for `item.Value` and use TableLoadingMode.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1436)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 45 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/list.go, line 182 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1436#-KtnSXmCqEKdhJUdI_nu:-KtnSXmCqEKdhJUdI_nv:b8wqthd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a2ec2a0d707ccd801c841c8d85366f433dcb5c67/posting/list.go#L182)):*
> ```Go
> 	if item.UserMeta() == bitUidPostings {
> 		l.plist.Uids = make([]byte, len(val))
> 		copy(l.plist.Uids, val)
> ```

Copying the value here because this might be modified. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1436)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 48 files at r1.
Review status: 1 of 46 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1436#-:-KtndAXUB2XeSZnl2m2P:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Comment by deepakjois** [comment]
Review status: 1 of 46 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 397 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1436#-KtoW80ZL4u6Cn6I_Eet:-KtoVwWzDEjDmTS-6SLB:b-2lyund) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea359205a4ae90dda677f0fcfe9803cec7915392/posting/index.go#L397)):*
> ```Go
> func deleteEntries(prefix []byte) error {
> 	iterOpt := badger.DefaultIteratorOptions
> 	iterOpt.FetchValues = false
> ```

You have removed this line. in the new code, which changes the behavior of the iterator. Was that deliberate?

If the intention is to keep the same behavior, then you should be setting `iterOpt.PrefetchValues = false`.

---

*[raftwal/wal.go, line 90 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1436#-KtoWXyZZbKTcr4pAJ8r:-KtoWXyZZbKTcr4pAJ8s:b2nreh6) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea359205a4ae90dda677f0fcfe9803cec7915392/raftwal/wal.go#L90)):*
> ```Go
> 	last := w.entryKey(gid, s.Metadata.Term, s.Metadata.Index)
> 	opt := badger.DefaultIteratorOptions
> 	opt.FetchValues = false
> ```

Same as above.

---

*[raftwal/wal.go, line 148 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1436#-KtoW_MDh2WKXZl0HwMM:-KtoW_MDh2WKXZl0HwMN:b2nreh6) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea359205a4ae90dda677f0fcfe9803cec7915392/raftwal/wal.go#L148)):*
> ```Go
> 		prefix := w.prefix(gid)
> 		opt := badger.DefaultIteratorOptions
> 		opt.FetchValues = false
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1436)*

**Pull request closed without merging**
