### PR TITLE
Allow mutation vars with blank nodes

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1175)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm Would be great if we can some test for the new feature that is enabled because of this change.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraph/main.go, line 366 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-KopMZnbEzgxyPU-vaVg:-KopMZnbEzgxyPU-vaVh:b9yx363) ([raw file](https://github.com/dgraph-io/dgraph/blob/3455dc64c2a476f5ae2869bc690e038c63280d7a/cmd/dgraph/main.go#L366)):*
> ```Go
> 	}
> 	tempMap := make(map[string]uint64)
> 	for k, v := range newUids {
> ```

Could we add a simple test for this endpoint?

---

*[query/mutation.go, line 243 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-KopMqMcwmRdBbqNG86f:-KopMqMcwmRdBbqNG86g:b-nvjprg) ([raw file](https://github.com/dgraph-io/dgraph/blob/59b2fd5c448a629394b900e1171391e90388dd17/query/mutation.go#L243)):*
> ```Go
> }
> 
> // ConvertAndApply materializes edges defined by the mutation
> ```

This isnt used anywhere?

---

*[query/query.go, line 2333 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-KopO3ZSiqJK_oSr4QIj:-KopO3ZSiqJK_oSr4QIk:bi20hhi) ([raw file](https://github.com/dgraph-io/dgraph/blob/3455dc64c2a476f5ae2869bc690e038c63280d7a/query/query.go#L2333)):*
> ```Go
> 		}
> 
> 		er.Allocations = make(map[string]uint64)
> ```

We are doing this in shareHandler as well. Could we extract into a function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-:-KopOqT91Y5hrqgppOIo:bxdhfo0)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraph/main.go, line 366 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-KopMZnbEzgxyPU-vaVg:-KopXj9WXjlM1JnaC4G5:b-4yvk3s) ([raw file](https://github.com/dgraph-io/dgraph/blob/3455dc64c2a476f5ae2869bc690e038c63280d7a/cmd/dgraph/main.go#L366)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Could we add a simple test for this endpoint?
</blockquote></details>

This needs to be done from Travis. Will add a task on github.

---

*[query/mutation.go, line 243 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-KopMqMcwmRdBbqNG86f:-KopV3vFCKMSj6yFsmDd:bplqoup) ([raw file](https://github.com/dgraph-io/dgraph/blob/59b2fd5c448a629394b900e1171391e90388dd17/query/mutation.go#L243)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This isnt used anywhere?
</blockquote></details>

Yes, it's not used.

---

*[query/query.go, line 2333 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-KopO3ZSiqJK_oSr4QIj:-KopXTYHaOwJ5nS90RAY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3455dc64c2a476f5ae2869bc690e038c63280d7a/query/query.go#L2333)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We are doing this in shareHandler as well. Could we extract into a function?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1175#-:-KopdY-bxMaBxtGf7-24:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
