### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by yalamber**
Made some grammar update

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2477)

### CODE REVIEW

**Comment by manishrjain** [comment]
Happy to accept this PR. Can you please sign the CLA, before I can merge it?

**Comment by manishrjain** [comment]
@yalamber : Do you intend to sign the CLA, so I could pull this PR in?

**Comment by yalamber** [comment]
@manishrjain signed 👍

**Comment by manishrjain** [comment]
Thanks for your contribution!

**Pull request merged**
