### PR TITLE
Switch to gogo protobuf

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/141)

### CODE REVIEW

**Comment by manishrjain** [comment]
So, doesn't look like there's any code change here. Did you do documentation to show how to build gogo protobuf?

---

Reviewed 23 of 24 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/141#-:-KOAPDTTE9-hybfxncrl:903221234)*

**Comment by ashwin95r** [comment]
Added a task for wiki documentation: https://app.asana.com/0/110655897041979/162695193447119

---

Review status: 23 of 46 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/141#-:-KOE-uEpm8_k5N9XCu_d:1218398980)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: 23 of 46 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/141#-:-KOE06tdTDLwhpvQLnlJ:1417088721)*

**Comment by manishrjain** [comment]
Can you confirm one thing? Do we still need normal golang/protobuf if we're using gogo? If not, we should delete that dep. :lgtm_strong: 

---

Review status: 23 of 46 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/141#-:-KONWry2WO3saZ53Aj5d:1403457671)*

**Comment by ashwin95r** [comment]
The pb.go file generated by gogo proto does import the golang/protobuf: 
```
   1 // Code generated by protoc-gen-gogo.
   2 // source: graphresponse.proto
   3 // DO NOT EDIT!
   4 
   5 /*
   6   Package graph is a generated protocol buffer package.
   7 
   8   It is generated from these files:
   9     graphresponse.proto
  10 
  11   It has these top-level messages:
  12     Request
  13     Latency
  14     Property
  15     Node
  16     Response
  17 */
  18 package graph
  19 
  20 import proto "github.com/golang/protobuf/proto"
  21 import fmt "fmt"
```

So we should keep it in our deps.

---

Review status: 23 of 46 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/141#-:-KOOTCKCyK9i7ZEre23J:b-6lz9rt)*

**Comment by ashwin95r** [comment]
Merged to develop with commit 552556c35d10f26bb1289e59e0dc4c738611cc70

**Pull request closed without merging**
