### PR TITLE
chore: fix imports order across the repo

### PR DESCRIPTION
**Pull request by mangalaman93**
This is the command I ran at the root of the repo:

```
tree -f -P "*.go" -i | xargs gosimports -d -w -v -local "github.com/dgraph-io"  -
```

This required installing gosimports like this:
```
go install github.com/rinchsan/gosimports/cmd/gosimports@latest
```

### CODE REVIEW

**Review by sanjayk-github-dev — COMMENTED** [review]
Curious to know what specific issue prompted this change?

**Review by anurags92 — APPROVED** [review]

**Comment by anurags92** [comment]
> github.com/rinchsan/gosimports

This particular issue highlights problem with goimports: https://github.com/golang/go/issues/20818 

Mostly a syntactic issue.

**Comment by mangalaman93** [comment]
Just best practices. I am also looking at other go vet issues and fixed some of those in #8620

**Review by sanjayk-github-dev — DISMISSED** [review]
LGTM

**Review by sanjayk-github-dev — APPROVED** [review]
Changes for best practices

**Review by anurags92 — APPROVED** [review]

**Pull request merged**
