### PR TITLE
Refactor/init

### PR DESCRIPTION
**Pull request by jchiu0**
Tiny PR to have something like GoogleInit.

If you want a singleton initialized using a flag, you can do:

```
func init() {
  x.AddInit(func() {
    someGlobalVar = NewObject(*someFlag)
  }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/184)

### CODE REVIEW

**Comment by jchiu0** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[x/init.go, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/184#-KQQ1oOEOCAjCh2zm5ST-r1-1:-KQQ2PeQ83JduQ_6koiV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f3a86ff726e32dfe7b08e81698227f088e2065c3/x/init.go#L1)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> package comment should be of the form "Package x ..."<br>package comment should not have leading space
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/184)*

**Comment by manishrjain** [comment]
:lgtm: Nice small change! One tiny nitpick, so fix that before submitting.

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[x/init.go, line 15 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/184#-KQTR__JYQxrb7jefR51:-KQTR__JYQxrb7jefR52:bkjciw1) ([raw file](https://github.com/dgraph-io/dgraph/blob/69ea976b59e1eda73efd050ea8d11988669a862d/x/init.go#L15)):*
> ```Go
>  * See the License for the specific language governing permissions and
>  * limitations under the License.
>  */
> ```

Add a space here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/184#-:-KQTRiHIxyKU1zZfvwBz:bk63s8l)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[x/init.go, line 15 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/184#-KQTR__JYQxrb7jefR51:-KQU4ViRWsW3JewFqTbQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/69ea976b59e1eda73efd050ea8d11988669a862d/x/init.go#L15)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a space here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/184)*

**Comment by jchiu0** [comment]
Thanks!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/184#-:-KQU4ahfqeF1BNywmtIG:b-ucfknh)*

**Pull request closed without merging**
