### PR TITLE
Language filtering for inequality functions

### PR DESCRIPTION
**Pull request by tzdybal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/963)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/stringfilter.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/963#-Kki87ws--oqNLvU1CBo:-Kki87ws--oqNLvU1CBp:b-j5r33a) ([raw file](https://github.com/dgraph-io/dgraph/blob/0c37ff788a2ebeb84db36cbaa6d91c4d34c0b59f/worker/stringfilter.go#L39)):*
> ```Go
> type matchFn func(types.Val, stringFilter) bool
> 
> func matchStrings(uids *protos.List, values []types.Val, filter stringFilter, match matchFn) *protos.List {
> ```

We shouldn't exceed 3 arguments in a function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/963)*

**Comment by tzdybal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/stringfilter.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/963#-Kki87ws--oqNLvU1CBo:-KkiGyOXXlBdTYUsOki2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0c37ff788a2ebeb84db36cbaa6d91c4d34c0b59f/worker/stringfilter.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We shouldn't exceed 3 arguments in a function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/963)*

**Comment by pawanrawal** [comment]
:lgtm: Please merge to release branch.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/963#-:-KkiXV2cb179TPcJjIbk:b-1jfrpf)*

**Comment by tzdybal** [comment]
Merged to release branch (03d8cc379f9472e2a966a4d8c1b6de75f96c4196).

**Pull request closed without merging**
