### PR TITLE
Automate/release

### PR DESCRIPTION
**Pull request by pawanrawal**
Use travis to upload release assets when

1. A new tag is pushed.
2. Release branch is updated and the release has already been done(a tag exists for the release).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/953)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[dashboard/play/deploy.sh, line 4 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/953#-KkOlt7k60A_RcEOQf6s:-KkOlt7mIKp3_haacs8R:bnk87ha) ([raw file](https://github.com/dgraph-io/dgraph/blob/29ba9d56d215d58d25fae784f83068be9b96c050/dashboard/play/deploy.sh#L4)):*
> ```Shell
> 
> # This command is used to run Dgraph on play.dgraph.io
> sudo ~/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/dgraph --port 80 --workerport 12345 --debugmode=true --nomutations=true --ui ~/go/src/github.com/dgraph-io/dgraph/dashboard/build --bindall=true 2>&1 | tee -a dgraph.log
> ```

Shouldn't this be from the released version? in `/usr/local/bin` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/953#-:-KkOmJA6HkjZ2w5r0I2C:bnfp4nl)*

**Comment by tzdybal** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/953#-:-KkOyd6sSEZgEUxGgrvY:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[dashboard/play/deploy.sh, line 4 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/953#-KkOlt7k60A_RcEOQf6s:-KkTUH18hLfJLLsu_Tk-:b-kxtsli) ([raw file](https://github.com/dgraph-io/dgraph/blob/29ba9d56d215d58d25fae784f83068be9b96c050/dashboard/play/deploy.sh#L4)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Shouldn't this be from the released version? in `/usr/local/bin` ?
</blockquote></details>

It typically starts from that but then we end up compiling from source incase there are bugs. Maybe once we verify that travis is uploading assets correctly when we do bugfixes to release, then I can change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/953)*

**Comment by pawanrawal** [comment]
Merged to release branch

**Pull request closed without merging**
