### PR TITLE
[docs] added example to export to a custom path within the graphql mutation

### PR DESCRIPTION
**Pull request by OmarAyo**
Clarified in the docs how to specify a custom path when sending the export request

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7000)

### CODE REVIEW

**Review by aaroncarey — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7000)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/dgraph-administration.md, line 115 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7000#-MNPGevh0Qhq_K7xTx56:-MNPGevh0Qhq_K7xTx57:b-b0laav) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2d0b2cbeae5162be5c2e1d2e2e196920bd690ab/wiki/content/deploy/dgraph-administration.md#L115)):*
> ```
> on the `/admin`
> ```
___
*[wiki/content/deploy/dgraph-administration.md, line 146 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7000#-MNPGuRT1KvdfHRr9OWM:-MNPGuRT1KvdfHRr9OWN:b-9c32wa) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2d0b2cbeae5162be5c2e1d2e2e196920bd690ab/wiki/content/deploy/dgraph-administration.md#L146)):*
> ```
> Starting in Dgraph v20.11.0 you can provide an absolute path to the directory where you want to export data in the GraphQL mutation request, as follows:
> ```

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/dgraph-administration.md, line 115 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7000#-MNPGevh0Qhq_K7xTx56:-MNPNyZX3qQvy8SxvrRU:b-5xrcjw) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2d0b2cbeae5162be5c2e1d2e2e196920bd690ab/wiki/content/deploy/dgraph-administration.md#L115)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> on the `/admin`
> ```

</blockquote></details>

Not sure why we should markdown only /admin and not the entire url

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/dgraph-administration.md, line 146 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7000#-MNPGuRT1KvdfHRr9OWM:-MNPOykt0QIwx3hmbRX7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2d0b2cbeae5162be5c2e1d2e2e196920bd690ab/wiki/content/deploy/dgraph-administration.md#L146)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Starting in Dgraph v20.11.0 you can provide an absolute path to the directory where you want to export data in the GraphQL mutation request, as follows:
> ```

</blockquote></details>

Done.

**Review by aaroncarey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7000)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/dgraph-administration.md, line 115 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7000#-MNPGevh0Qhq_K7xTx56:-MNPP2pC3LdpKT90eqtk:bm31jb3) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2d0b2cbeae5162be5c2e1d2e2e196920bd690ab/wiki/content/deploy/dgraph-administration.md#L115)):*
<details><summary><i>Previously, OmarAyo (OmarAyo) wrote…</i></summary><blockquote>

Not sure why we should markdown only /admin and not the entire url
</blockquote></details>

Feel free to use backticks (`like this`) anywhere it would add clarity. Which line has the URL you would like to format differently?

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/dgraph-administration.md, line 115 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7000#-MNPGevh0Qhq_K7xTx56:-MNPQ0Ee-HC9yQwtdV7l:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2d0b2cbeae5162be5c2e1d2e2e196920bd690ab/wiki/content/deploy/dgraph-administration.md#L115)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

Feel free to use backticks (`like this`) anywhere it would add clarity. Which line has the URL you would like to format differently?
</blockquote></details>

Done.

**Review by aaroncarey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7000)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @aaroncarey, @danielmai, and @MichaelJCompton)

**Pull request merged**
