### PR TITLE
Allow live loader to use existing nodes

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1848)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1848#-:-L-0PRwcHvFeK82-1HRb:bnfp4nl)*

**Comment by manishrjain** [comment]
Sorry, I was too quick. Actually, this can cause an issue if a user just hands Dgraph UIDs, which are not assigned yet. We should verify either at Dgraph end, or via live loader, that the UID passed in is below the max threshold UID assigned by Zero.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1848#-:-L-0Pf0uE54o1YyvLjpE:b-ag59bt)*

**Comment by peterstace** [comment]
There's an existing check to make sure inbound UIDs are below the current max lease, but it doesn't work in all cases. I'll fix that check before submitting here.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1848#-:-L-0TL_NZlp2JZzO7JTm:b-4dohnz)*

**Comment by peterstace** [comment]
UID check has been improved at master at 363bf922.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1848#-:-L-4ekmbA74cgtn6n8Ev:b-2522io)*

**Pull request merged**
