### PR TITLE
Fix a bug which caused us to return no results.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/115)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Lets add a test like this to our `TestToJson` method in `query_test.go`. Apart from that looks fine. 
```
	if !strings.Contains(string(js), "Michonne") {
		t.Error("The response doesn't contain the value of name attribute.")
	}
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/115#-:-KKqj-VEX8z4cpmWsEHO:-1580267177)*

**Comment by manishrjain** [comment]
Really good point. Added.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/115#-:-KKqk3V8Glmbs2GOWy3q:-683299843)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/115#-:-KKqkYrlp1QxYCnfteAB:1417088721)*

**Comment by pawanrawal** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/115)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
