### PR TITLE
Support for delete operation in mutations

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/143)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/mutation.go, line 147 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/143#-KOA6mF1qfy7okWP2e44:-KOA6mF1qfy7okWP2e45:212430445) ([raw file](https://github.com/dgraph-io/dgraph/blob/eda8d4de93897b64b80bda5e3a8bb7532e249aab/worker/mutation.go#L147)):*
> ```Go
> // MutateOverNetwork checks which instance should be running the mutations
> // according to fingerprint of the predicate and sends it to that instance.
> func MutateOverNetwork(ctx context.Context, setEdges []x.DirectedEdge,
> ```

Can't you pass Mutation struct here? Also, return Mutation, because some of the SETs and DELs wouldn't have been applied and they need to be differentiated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/143)*

**Comment by pawanrawal** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/mutation.go, line 147 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/143#-KOA6mF1qfy7okWP2e44:-KODnUMkgUMzMw3z5wPn:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/eda8d4de93897b64b80bda5e3a8bb7532e249aab/worker/mutation.go#L147)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Can't you pass Mutation struct here? Also, return Mutation, because some of the SETs and DELs wouldn't have been applied and they need to be differentiated.
</details>
Done.

---

*[worker/mutation.go, line 98 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/143#-KODnWsES_LaOU0tr_SP:-KODnWsES_LaOU0tr_SQ:1741159497) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b87ce2fb5d63ab4d5366be94026bacad416ee26/worker/mutation.go#L98)):*
> ```Go
> 	var err error
> 	if idx == int(instanceIdx) {
> 		if err = mutate(ctx, m, left); err != nil {
> ```

I think this wasn't being handled earlier. The mutations left on the instance which received the mutation request ​were not returned earlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/143)*

**Comment by pawanrawal** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/mutation.go, line 147 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/143#-KOA6mF1qfy7okWP2e44:-KODwnSAT87FDSX2Ty7X:-1726679308) ([raw file](https://github.com/dgraph-io/dgraph/blob/eda8d4de93897b64b80bda5e3a8bb7532e249aab/worker/mutation.go#L147)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Done.
</details>
I was thinking how could I abstract it out in a struct, didn't realise the abstraction was always there. That's another thing to learn, how to abstract out things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/143)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/143#-:-KODze0amF1KqWdHTjCO:1417088721)*

**Comment by pawanrawal** [comment]
Merged to develop with commit a844b78190b884f25bfd506a96b53a531ee77fa4.

**Pull request closed without merging**
