### PR TITLE
Support/groupby

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/893)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/groupby.go, line 35 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1tY1d7trc5f_wQ3hc:-Kj1tY1d7trc5f_wQ3hd:btcemfj) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L35)):*
> ```Go
> }
> 
> type groups struct {
> ```

Move this below GroupInfo. groupResults

---

*[query/groupby.go, line 39 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1tbdbWK3UuJddHJGd:-Kj1tbdbWK3UuJddHJGe:b10g7bj) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L39)):*
> ```Go
> }
> 
> type GroupInfo struct {
> ```

make it private. groupResult

---

*[query/groupby.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1uMThXAxNynjXG7GE:-Kj1uMThXAxNynjXG7GF:buo2gfk) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L40)):*
> ```Go
> 
> type GroupInfo struct {
> 	values     []groupPair
> ```

keys []groupPair

---

*[query/groupby.go, line 47 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1sNGNlFxKBvRBw9Bb:-Kj1sNGNlFxKBvRBw9Bc:bq28w4m) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L47)):*
> ```Go
> type groupElements struct {
> 	entities *taskp.List
> 	val      types.Val
> ```

key types.Val

---

*[query/groupby.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1t4ZtnUxTMZuuBgCU:-Kj1t4ZtnUxTMZuuBgCV:b-19tuk2) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L51)):*
> ```Go
> 
> type dedup struct {
> 	mp    []map[string]groupElements
> ```

Move mp and attrs out to a new struct. So, dedup would only have a list of that struct.

```
type S struct {
  mp map[string]groupElements
  attr string
}
```

---

*[query/groupby.go, line 191 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1xAfSBQZuy_b5ZA6u:-Kj1xAfT8uge-VNiVMt8:b-xf0b60) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L191)):*
> ```Go
> 	// Go over the groups and aggregate the values.
> 	for i := range res.group {
> 		grp := &res.group[i]
> ```

grp := res.group[i]. So, you don't need `(*grp)`.

---

*[query/groupby.go, line 218 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1vu9Ptixz7J7zsRSt:-Kj1vu9Ptixz7J7zsRSu:ba3dfna) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L218)):*
> ```Go
> 		}
> 	}
> 	sort.Slice(res.group, func(i, j int) bool {
> ```

Remove?

---

*[query/query.go, line 999 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1SXGkOI4VwehRNcWr:-Kj1SXGkOI4VwehRNcWs:b-a1wjk8) ([raw file](https://github.com/dgraph-io/dgraph/blob/ee5e8d5377894e99f79c70482e246966a98b6c70/query/query.go#L999)):*
> ```Go
> 	mp := make(map[string]GroupInfo)
> 	_ = mp
> 	dedupMap := make([]map[string][]idVal, len(sg.Params.groupbyAttrs))
> ```

Make this a struct, with functions to aid what you're trying to achieve here.

attrList can be done via this struct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/893)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[query/groupby.go, line 35 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1tY1d7trc5f_wQ3hc:-Kj1y3ktohM2jZV5FPQ2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this below GroupInfo. groupResults
</blockquote></details>

Done.

---

*[query/groupby.go, line 39 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1tbdbWK3UuJddHJGd:-Kj1yKURm7wtIUPrwFl4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

make it private. groupResult
</blockquote></details>

Done.

---

*[query/groupby.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1uMThXAxNynjXG7GE:-Kj1zJbuzfBCns10ehEZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

keys []groupPair
</blockquote></details>

Done.

---

*[query/groupby.go, line 47 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1sNGNlFxKBvRBw9Bb:-Kj1yxX9vT1xKLtcfZWl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L47)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

key types.Val
</blockquote></details>

Done.

---

*[query/groupby.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1t4ZtnUxTMZuuBgCU:-Kj21KGrQ6AJ0Zrl7BQ2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move mp and attrs out to a new struct. So, dedup would only have a list of that struct.

```
type S struct {
  mp map[string]groupElements
  attr string
}
```
</blockquote></details>

Done.

---

*[query/groupby.go, line 191 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1xAfSBQZuy_b5ZA6u:-Kj21_4Sq1JcQPzA_cda:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L191)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

grp := res.group[i]. So, you don't need `(*grp)`.
</blockquote></details>

Done.

---

*[query/groupby.go, line 218 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1vu9Ptixz7J7zsRSt:-Kj1yyc7eavAavjfK6UR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88d10d208fb40f345ac3e1eb8cc3bc54058a2733/query/groupby.go#L218)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

---

*[query/query.go, line 999 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-Kj1SXGkOI4VwehRNcWr:-Kj1z0102H8J-8Qk_Cq-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ee5e8d5377894e99f79c70482e246966a98b6c70/query/query.go#L999)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this a struct, with functions to aid what you're trying to achieve here.

attrList can be done via this struct.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/893)*

**Comment by manishrjain** [comment]
:lgtm: Fix the comments, and wait for @janardhan1993 to have a look as well.

---

Reviewed 2 of 5 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[query/groupby.go, line 44 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB1qh_1ymRPI1jwTMK:-KjB1qh_1ymRPI1jwTML:bhdlgd2) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L44)):*
> ```Go
> func (grp *groupResult) aggregateChild(child *SubGraph) {
> 	if child.Params.DoCount {
> 		(*grp).aggregates = append((*grp).aggregates, groupPair{
> ```

grp.aggregates? here and elsewhere.

---

*[query/groupby.go, line 50 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB24TFxOyCrRIjxlj5:-KjB24TFxOyCrRIjxlj6:b-l6ibnv) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L50)):*
> ```Go
> 				Value: int64(len(grp.uids)),
> 			},
> 		})
> ```

return

---

*[query/groupby.go, line 51 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB2FXLYXR7mRJv_zCb:-KjB2FXLYXR7mRJv_zCc:b32wo2) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L51)):*
> ```Go
> 			},
> 		})
> 	} else if len(child.SrcFunc) > 0 && isAggregatorFn(child.SrcFunc[0]) {
> ```

if

---

*[query/groupby.go, line 85 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB2kcLEotklwBGdjHn:-KjB2kcLEotklwBGdjHo:b-sklukv) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L85)):*
> ```Go
> 	idx := -1
> 	// Going last to first as we'll always add new ones to last and
> 	// would access it till we add a new entry.
> ```

This could be reworded.

---

*[query/groupby.go, line 100 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB31r_N4AdCKOq-DND:-KjB31r_N4AdCKOq-DNE:b-3tawrd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L100)):*
> ```Go
> 		})
> 		idx = len(d.groups) - 1
> 	}
> ```

Refactor this part in a separate function, which would return `uniq` instance.

---

*[query/groupby.go, line 122 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB38nq4A8W2Roc6sNs:-KjB38nq4A8W2Roc6sNt:b-7n1183) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L122)):*
> ```Go
> 		}
> 	}
> 	cur := d.groups[idx].elements[strKey].entities
> ```

You don't need the idx, just use the uniq instance from above.

---

*[query/groupby.go, line 125 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB3mwo25YLLu9MO_vT:-KjB3mwo25YLLu9MO_vU:b-b411ym) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L125)):*
> ```Go
> 	cur.Uids = append(cur.Uids, uid)
> }
> ```

Add a comment.

---

*[query/groupby.go, line 233 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB5WvreIiL9DMAXGDl:-KjB5WvsyMikIZZFSWa8:b-3har64) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L233)):*
> ```Go
> }
> 
> func groupLess(a, b *groupResult) bool {
> ```

Let's remove any group which has zero results proactively.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-:-KjB6WjyqBauC9iJxs4p:bc1iwis)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1462 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBKEqRIkyQQKEW3nTT:-KjBKEqSIpU3HMF7DojU:b-jx87uv) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/gql/parser.go#L1462)):*
> ```Go
> 		} else if item.Typ == itemName {
> 			if !expectArg {
> 				return x.Errorf("Expected a variable but got comma")
> ```

expected a comma or right round ?

---

*[gql/parser.go, line 1472 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBKoN-NwbfJxkTQKic:-KjBKoN-NwbfJxkTQKid:bwj4a3p) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/gql/parser.go#L1472)):*
> ```Go
> 	}
> 	if count == 0 {
> 		return x.Errorf("Expected atleast one attribute in groupby")
> ```

Count is never incremented, so it would be always zero ?

---

*[query/groupby.go, line 52 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBNPTpdJ9bP_imqj3p:-KjBNPTpdJ9bP_imqj3q:b-urtcjf) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L52)):*
> ```Go
> 		})
> 	} else if len(child.SrcFunc) > 0 && isAggregatorFn(child.SrcFunc[0]) {
> 		fieldName := fmt.Sprintf("%s(%s)", child.SrcFunc[0], child.Attr)
> ```

Off the topic, in normal query(without group by) fieldname would be same for both ? Wouldn't that give wrong results if we have both in the query
count(abc)
count(abc @filter())

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-:-KjBRDHWchCDuAqwfCnw:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 933 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBYC1jRjlfpWZ_ejYP:-KjBYC1kk_C6hwkpv2sL:b9vne19) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/query_test.go#L933)):*
> ```Go
> 		{
> 			me(id: 1) {
> 				friend @groupby(friend,name) {
> ```

Does it make sense to group by friend?

---

*[query/query_test.go, line 941 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBYFkPVqxSExkuSTbV:-KjBYFkPVqxSExkuSTbW:byhgziv) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/query_test.go#L941)):*
> ```Go
> 	js := processToFastJSON(t, query)
> 	require.JSONEq(t,
> 		`{"me":[{"friend":{"@groupby":[{"count":0,"friend":"0x1","name":"Andrea"},{"count":0,"friend":"0x1","name":"Daryl Dixon"},{"count":0,"friend":"0x1","name":"Glenn Rhee"},{"count":0,"friend":"0x18","name":"Daryl Dixon"},{"count":0,"friend":"0x18","name":"Glenn Rhee"},{"count":0,"friend":"0x18","name":"Rick Grimes"},{"count":1,"friend":"0x1","name":"Rick Grimes"},{"count":1,"friend":"0x18","name":"Andrea"}]}}]}`,
> ```

There are 5  friends in total, but the output is showing only 2 ?(2 friends * 4 names)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/893)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 917 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBcP0TVld85W8onMbZ:-KjBcP0TVld85W8onMb_:b591jo4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/query_test.go#L917)):*
> ```Go
> 			me(id: 1) {
> 				friend @groupby(age) {
> 					max(name)
> ```

Add a test case with age stored as both int and float may be

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/893)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1462 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBKEqRIkyQQKEW3nTT:-KjBm2HwWoL16Q82RQ4J:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/gql/parser.go#L1462)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

expected a comma or right round ?
</blockquote></details>

Done.

---

*[gql/parser.go, line 1472 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBKoN-NwbfJxkTQKic:-KjBm2lOyLd4fLJBDhbk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/gql/parser.go#L1472)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Count is never incremented, so it would be always zero ?
</blockquote></details>

Done.

---

*[query/groupby.go, line 44 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB1qh_1ymRPI1jwTMK:-KjBklntowff7oNhtbvS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L44)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

grp.aggregates? here and elsewhere.
</blockquote></details>

Done.

---

*[query/groupby.go, line 50 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB24TFxOyCrRIjxlj5:-KjBkxGPzg4GpNgf5hCd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return
</blockquote></details>

Done.

---

*[query/groupby.go, line 51 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB2FXLYXR7mRJv_zCb:-KjBkxiTmc-G5JJd_8jb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if
</blockquote></details>

Done.

---

*[query/groupby.go, line 52 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBNPTpdJ9bP_imqj3p:-KjBm6go-vuLCAJxWsDU:b9d02yx) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L52)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Off the topic, in normal query(without group by) fieldname would be same for both ? Wouldn't that give wrong results if we have both in the query
count(abc)
count(abc @filter())
</blockquote></details>

count of the same attribute isn't allowed twice.

---

*[query/groupby.go, line 85 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB2kcLEotklwBGdjHn:-KjBl5GTghseQlS2IZAD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L85)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This could be reworded.
</blockquote></details>

Done.

---

*[query/groupby.go, line 100 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB31r_N4AdCKOq-DND:-KjBl5n6Sn11hu-GYMmp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L100)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Refactor this part in a separate function, which would return `uniq` instance.
</blockquote></details>

Done.

---

*[query/groupby.go, line 122 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB38nq4A8W2Roc6sNs:-KjBl6IJd-PeZYM8JGJg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L122)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need the idx, just use the uniq instance from above.
</blockquote></details>

Done.

---

*[query/groupby.go, line 125 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB3mwo25YLLu9MO_vT:-KjBmWZD2eaWQIiRdP24:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L125)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment.
</blockquote></details>

Done.

---

*[query/groupby.go, line 233 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjB5WvreIiL9DMAXGDl:-KjBl8OU_zsd9fV781Ur:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/groupby.go#L233)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Let's remove any group which has zero results proactively.
</blockquote></details>

Done.

---

*[query/query_test.go, line 917 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBcP0TVld85W8onMbZ:-KjBmjPgGkgtG1uVuci5:b78khpf) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/query_test.go#L917)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Add a test case with age stored as both int and float may be
</blockquote></details>

This operates on the value `age` which would be converted to schema type before groupby is applied. So it shouldn't affect the working.

---

*[query/query_test.go, line 933 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBYC1jRjlfpWZ_ejYP:-KjBmz3Iv5NRT9u6bXrS:bpirzd6) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/query_test.go#L933)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Does it make sense to group by friend?
</blockquote></details>

Just for testing, wouldn't make much sense in reality.

---

*[query/query_test.go, line 941 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/893#-KjBYFkPVqxSExkuSTbV:-KjBn5UD8lEkwl1T8nzP:b-8ehjko) ([raw file](https://github.com/dgraph-io/dgraph/blob/a44eb76d288bfc8ab4489de9f85c4e676a906cd0/query/query_test.go#L941)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

There are 5  friends in total, but the output is showing only 2 ?(2 friends * 4 names)
</blockquote></details>

yeah, Its friend of the first level friend. Groupby operates on the child predicates of the current level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/893)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
