### PR TITLE
Support 'S * *' deletion

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/884)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/dgraph/main.go, line 259 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-Kidq22sreDBSkdHSEIN:-Kidq22tu0tAX_h7ZBmL:b-9q1y95) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/cmd/dgraph/main.go#L259)):*
> ```Go
> 			}
> 		} else {
> 			newEdges = append(newEdges, mu)
> ```

There's only set and del? we should x.fatalf here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-:-KidtI_4RMsNNbK3yuEL:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm: Some comments. Address those before submitting.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-Kigfv1LkUfLsNdJeQYa:-Kigfv1LkUfLsNdJeQYb:b2qwi0s) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/cmd/dgraph/main.go#L247)):*
> ```Go
> 				}
> 				for _, pred := range preds {
> 					edge := &taskp.DirectedEdge{
> ```

When we delete all objects for any predicate, we should also delete the `node <_predicate_> pred` relationships stored. And we should do this for `s p *` deletes as well.

---

*[cmd/dgraph/main.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-KigerxMOB2vEZlU4Xob:-KigerxMOB2vEZlU4Xoc:bx11obl) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/cmd/dgraph/main.go#L256)):*
> ```Go
> 				}
> 			} else {
> 				newEdges = append(newEdges, mu)
> ```

The smaller cond should be done first, then the longer one.

---

*[x/x.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-KigfDCZWFADJfFdevjA:-KigfDC_-6iBlSXDovmp:b-7bbsm5) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/x/x.go#L46)):*
> ```Go
> 	ErrorNoPermission    = "ErrorNoPermission"
> 	ErrorInvalidMutation = "ErrorInvalidMutation"
> 	DeleteAll            = "_DELETE_POSTING_"
> ```

DeleteAllObjects

---

*[x/x.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-KigfICujM6R_-DqvQj7:-KigfICujM6R_-DqvQj8:bdfddkd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/x/x.go#L47)):*
> ```Go
> 	ErrorInvalidMutation = "ErrorInvalidMutation"
> 	DeleteAll            = "_DELETE_POSTING_"
> 	AllPredicates        = "_ALL_PREDICATES_"
> ```

DeleteAllPredicates

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-:-KiggekKsoLkJo7gLWFh:b-pwwqdz)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-Kigfv1LkUfLsNdJeQYa:-Kih6IVMa6ylHZJTf6Vt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/cmd/dgraph/main.go#L247)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

When we delete all objects for any predicate, we should also delete the `node <_predicate_> pred` relationships stored. And we should do this for `s p *` deletes as well.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-KigerxMOB2vEZlU4Xob:-Kih6JFZWvuIyqD2wsAx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/cmd/dgraph/main.go#L256)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The smaller cond should be done first, then the longer one.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 259 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-Kidq22sreDBSkdHSEIN:-Kih6JjIcpk2kWEfkpfG:b-xqazn0) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/cmd/dgraph/main.go#L259)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

There's only set and del? we should x.fatalf here
</blockquote></details>

Done. Have an assert.

---

*[x/x.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-KigfDCZWFADJfFdevjA:-Kih8M0nJC-ljtYbbJrT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/x/x.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

DeleteAllObjects
</blockquote></details>

Done.

---

*[x/x.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/884#-KigfICujM6R_-DqvQj7:-Kih8LiaKQ7Tnubnxf4Z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d180edf6140d081e742ccad70182a9fb9465d4a2/x/x.go#L47)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

DeleteAllPredicates
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/884)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
