### PR TITLE
Follow GraphQL specs in query result

### PR DESCRIPTION
**Pull request by ashwin95r**
Should fix: https://github.com/dgraph-io/dgraph/issues/114

We have to decide if we want to return server_latency stats in the JSON result.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/154)

### CODE REVIEW

**Comment by manishrjain** [comment]
Looks really nice change. Is there a way to retrieve _uid_ on demand? Can you add a test case for that?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 188 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/154#-KOiYp0SA4xN3lyEZdfh:-KOiYp0U5dumRLbGrvSJ:b-yemun) ([raw file](https://github.com/dgraph-io/dgraph/blob/1bdf5579835b13ec73c5c24c8bf27d56ac21c899/gql/parser.go#L188)):*
> ```Go
> 
> 	gq.Attr = item.Val
> ```

Remove vertical space here.

---

*[query/query.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/154#-KOiZ9C9LKpsn7pTH4aM:-KOiZ9C9LKpsn7pTH4aN:b-b0o83n) ([raw file](https://github.com/dgraph-io/dgraph/blob/ace8f3acb6927520331749a6095cc31e523e591d/query/query.go#L213)):*
> ```Go
> 			uid := ul.Uids(j)
> 			m := make(map[string]interface{})
> 			m["_uid_"] = fmt.Sprintf("%#x", uid)
> ```

Is there a way to retrieve `_uid_` on demand?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/154#-:-KOiZdvFCdUQOzwqGgp2:b-jlwux7)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 188 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/154#-KOiYp0SA4xN3lyEZdfh:-KOia-xdp8hZxP6QxZu6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1bdf5579835b13ec73c5c24c8bf27d56ac21c899/gql/parser.go#L188)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove vertical space here.
</details>
Done.

---

*[query/query.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/154#-KOiZ9C9LKpsn7pTH4aM:-KOimHPOzN-kjtX6JGUI:bwe29f2) ([raw file](https://github.com/dgraph-io/dgraph/blob/ace8f3acb6927520331749a6095cc31e523e591d/query/query.go#L213)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Is there a way to retrieve `_uid_` on demand?
</details>
Required some more changes for that. Done now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/154)*

**Comment by manishrjain** [comment]
:lgtm: Good job!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[query/query.go, line 121 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/154#-KOiLWkm2cCWql7AEtyC-r2-121:-KOjGai7FJb50i16J1wg:b32w0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/8e3e689a928a892f8ee78b50a10b110755d37cf0/query/query.go#L121)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> struct field GetUid should be GetUID
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/154#-:-KOjIEQqF1NL61-dh3x3:b-el6syw)*

**Comment by ashwin95r** [comment]
Addresses issue #114. Merged to develop with commmit 73b8ea2ff80cb6a91e9d6edd4261d6281236f73e

**Pull request closed without merging**
