### PR TITLE
Support attribute name in checkpwd

### PR DESCRIPTION
**Pull request by tzdybal**
This is a fix for #693.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/701)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 1521 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfFyZHEtk50E1P6AgTD:-KfFyZHFeU4T__7a1Idl:b2rb0s0) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/gql/parser.go#L1521)):*
> ```Go
> 				if item.Val == "checkpwd" {
> 					child.Func.Args = append(child.Func.Args, child.Func.Attr)
> 					child.Attr = child.Func.Attr
> ```

if item.Val == "checkpwd" { func.args = ... } child.Attr = child.Func.Attr

---

*[query/query_test.go, line 1156 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfFze1jcRdgGc94BgWl:-KfFze1jcRdgGc94BgWm:bk8jph9) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/query/query_test.go#L1156)):*
> ```Go
>                         me(id:0x01) {
>                                 name
>                                 checkpwd(pass, "654123")
> ```

Can you also check what happens when a query looks for `pass` directly? We should not return that field.

---

*[query/query_test.go, line 1163 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfFz7Iii_M1uISAEG33:-KfFz7Iii_M1uISAEG34:b-fuveu3) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/query/query_test.go#L1163)):*
> ```Go
> 	require.EqualValues(t,
> 		`{"me":[{"name":"Rick Grimes","password":[{"checkpwd":true}]}]}`,
> 		js)
> ```

same line as above. In fact, the whole thing might fit into one line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/701)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 1162 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfGDX0Z26foaLXgVooY:-KfGDX0aH_CChqVOSw49:b-1ia9lb) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/query/query_test.go#L1162)):*
> ```Go
> 	js := processToFastJSON(t, query)
> 	require.EqualValues(t,
> 		`{"me":[{"name":"Rick Grimes","password":[{"checkpwd":true}]}]}`,
> ```

Would the key name always be `password`? or should it be the name of attribute that we are checking for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-:-KfGDSXRem3RkkqaDhtE:bnfp4nl)*

**Comment by tzdybal** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[gql/parser.go, line 1521 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfFyZHEtk50E1P6AgTD:-KfGqrvACF4mKMkIVGb5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/gql/parser.go#L1521)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if item.Val == "checkpwd" { func.args = ... } child.Attr = child.Func.Attr
</blockquote></details>

Done.

---

*[query/query_test.go, line 1156 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfFze1jcRdgGc94BgWl:-KfHGya_kAVm8hyo3__j:b2qe79g) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/query/query_test.go#L1156)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can you also check what happens when a query looks for `pass` directly? We should not return that field.
</blockquote></details>

More tests added. Restriction changed to more secure.

---

*[query/query_test.go, line 1162 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfGDX0Z26foaLXgVooY:-KfHGoXNpTQhjyBXizkW:b-2l5det) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/query/query_test.go#L1162)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Would the key name always be `password`? or should it be the name of attribute that we are checking for?
</blockquote></details>

It should reflect attribute name. Fixed.

---

*[query/query_test.go, line 1163 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfFz7Iii_M1uISAEG33:-KfGzP1ajg29lJncUlkY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/query/query_test.go#L1163)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same line as above. In fact, the whole thing might fit into one line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/701)*

**Comment by manishrjain** [comment]
:lgtm: One small nitpick from before. Feel free to submit after.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1521 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-KfFyZHEtk50E1P6AgTD:-KfJakzBrVG2NwQdVHik:b-11f1f2) ([raw file](https://github.com/dgraph-io/dgraph/blob/489012ae37f275ed0e6858550f4baee5a0ae937e/gql/parser.go#L1521)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/701#-:-KfJazXQtV7z2V6FDwFb:by1u72m)*

**Comment by tzdybal** [comment]
Merged to master.

**Pull request closed without merging**
