### PR TITLE
feat(GraphQL): Support authorization with jwk_url

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
Fixes GRAPHQL-693.

This PR extends support for authorization with `jwk_url`. Now users can give `jwkUrl` for their project in the `Dgraph.Authorization` JSON in their schema.
```
#Dgraph.Authorization 
{"VerificationKey":"",
      "Header":"header",
     "Namespace":"your-namespace",
    "jwkurl": "your-jwk-url-",
    "Algo":"",
    "Audience":["your-audience"]
}
```

When `jwkurl` is provided, keep `VerificationKey` and `Algo` empty as they are not needed.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6564)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6564)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/authorization/auth.go, line 58 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINr5LN2N4Isi0HeBH4:-MINr5LO4g-iDpsXcPNN:bmn2t0d) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L58)):*
> ```Go
> 	VerificationKey string
> 	JWKUrl          string
> 	JWKSet          *jose.JSONWebKeySet
> ```

Does this need to be public or can it be internal like `jwkSet`?
___
*[graphql/authorization/auth.go, line 59 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvXxSEYyDMFHo_mhR:-MINvXxSEYyDMFHo_mhS:b-48go6i) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L59)):*
> ```Go
> 	JWKUrl          string
> 	JWKSet          *jose.JSONWebKeySet
> 	RefreshTime     time.Duration `json:"-"` // Ignoring this field for now (might later include in the input JSON)
> ```

set it to an internal field for now
___
*[graphql/authorization/auth.go, line 75 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvSpW7Hhdf0RRBxB_:-MINvSpW7Hhdf0RRBxBa:b-n1jred) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L75)):*
> ```Go
> 	// If JWKUrl is provided, we don't expect (VerificationKey, Algo),
> 	// they are needed only if JWKUrl is not present there.
> 	if a.JWKUrl != "" {
> ```

Needs some tests for these error scenarios?
___
*[graphql/authorization/auth.go, line 309 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINv1-oETRTY9Cux1Ag:-MINv1-pCRLsDpsBzBpn:bkypymm) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L309)):*
> ```Go
> 		token, err =
> 			jwt.ParseWithClaims(jwtStr, &CustomClaims{}, func(token *jwt.Token) (interface{}, error) {
> 				kid := token.Header["kid"].(string)
> ```

What if the `kid` header is null or is it always present?
___
*[graphql/authorization/auth.go, line 315 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvbS2Ey7NeU8sIwNX:-MINvbS2Ey7NeU8sIwNY:b-dzgeiz) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L315)):*
> ```Go
> 				}
> 				return signingKeys[0].Key, nil
> 			}, jwt.WithoutAudienceValidation())
> ```

We need a test for this as well. 
___
*[graphql/authorization/auth.go, line 372 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINsKVB49qTVKV5Xuw5:-MINsKVB49qTVKV5Xuw6:b-knhx05) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L372)):*
> ```Go
> 	}
> 
> 	data, _ := ioutil.ReadAll(resp.Body)
> ```

Why not handle this error?
___
*[graphql/authorization/auth.go, line 391 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINsSzxBJkQ2v7YNeJS:-MINsSzxBJkQ2v7YNeJT:b-9htnlr) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L391)):*
> ```Go
> 
> 	if resp.Header["Expires"] != nil {
> 		maxAge, err = ParseExpires(resp.Header["Expires"][0])
> ```

These errors are not handled, they should be. Which one out of the Expires or the Cache-Control header does the firebase SDK use?
___
*[graphql/authorization/auth.go, line 395 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINsjbC59lr5QLT1ECf:-MINsjbC59lr5QLT1ECg:bumdmr6) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L395)):*
> ```Go
> 
> 	if resp.Header["Cache-Control"] != nil {
> 		maxAge, err = ParseMaxAge(resp.Header["Cache-Control"][0])
> ```

error not handled
___
*[graphql/authorization/auth.go, line 397 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINscef9vf2LThTzezA:-MINscef9vf2LThTzezB:b99ou06) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L397)):*
> ```Go
> 		maxAge, err = ParseMaxAge(resp.Header["Cache-Control"][0])
> 	}
> 	a.RefreshTime = time.Duration(maxAge) * time.Second
> ```

Don't we need a lock here and above where we are modifying properties of `a`?
___
*[graphql/authorization/auth.go, line 407 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvJk_2duYQksPbm8B:-MINvJk_2duYQksPbm8C:b-3zd5mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L407)):*
> ```Go
> 		select {
> 		case <-a.ticker.C:
> 			if a.RefreshTime == 0 {
> ```

When is this set to 0?
___
*[graphql/authorization/auth.go, line 414 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINrs7w0tAtigcYSzKA:-MINrs7w0tAtigcYSzKB:b-llcr2x) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L414)):*
> ```Go
> 			for {
> 				a.Lock()
> 				err := a.fetchJWKs()
> ```

Is this error logged? We should not try infinitely here as we have a false loop outside already. We should have a number of max attempts here, say 3.
What is the behavior initially when the user has not given a schema with a JWK_URL?

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6564)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/authorization/auth.go, line 58 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINr5LN2N4Isi0HeBH4:-MIOBZMA8JQp5P2e6F1G:byge3no) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L58)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Does this need to be public or can it be internal like `jwkSet`?
</blockquote></details>

It should be internal. I have changed it to `jwkSet`.
___
*[graphql/authorization/auth.go, line 59 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvXxSEYyDMFHo_mhR:-MIOBjGm2wwkHGLVXO5V:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L59)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

set it to an internal field for now
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 75 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvSpW7Hhdf0RRBxB_:-MIOBmby9G3INVlUgLYP:b-dgl4em) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L75)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Needs some tests for these error scenarios?
</blockquote></details>

We can include them. These can be easily verified.
___
*[graphql/authorization/auth.go, line 309 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINv1-oETRTY9Cux1Ag:-MIOBvkg9en3q1SQa9fx:b-n9zhkq) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L309)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What if the `kid` header is null or is it always present?
</blockquote></details>

It is always present in the `jwk`.
___
*[graphql/authorization/auth.go, line 315 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvbS2Ey7NeU8sIwNX:-MIOE6KW52bEtXCpB59F:b-80tlqk) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L315)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We need a test for this as well. 
</blockquote></details>

Sure.
___
*[graphql/authorization/auth.go, line 372 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINsKVB49qTVKV5Xuw5:-MIOC73i-iddWtSbxCfA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L372)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why not handle this error?
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 391 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINsSzxBJkQ2v7YNeJS:-MIOCDK9-LLJwvmARnAk:b1yyovq) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L391)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

These errors are not handled, they should be. Which one out of the Expires or the Cache-Control header does the firebase SDK use?
</blockquote></details>

Actually, Firebases uses both the headers. We can extract any one of them. I will remove one after the discussion.
___
*[graphql/authorization/auth.go, line 395 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINsjbC59lr5QLT1ECf:-MIOCc2sC22NojVzpDql:bujekvt) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L395)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

error not handled
</blockquote></details>

Error in parsing the Headers means that we were not able to find any meaning value for the expiration time. In this case, it just sets `maxAge` to `0`. There is no need behind handling this error. 
___
*[graphql/authorization/auth.go, line 397 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINscef9vf2LThTzezA:-MIOCziADtQhETucZj57:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L397)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't we need a lock here and above where we are modifying properties of `a`?
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 407 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINvJk_2duYQksPbm8B:-MIOD-yl8tTQJ3_kBIKK:b9j5r21) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L407)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

When is this set to 0?
</blockquote></details>

By default, it is set to 0. See the `maxAge`in `fetchJWKs()` function.
___
*[graphql/authorization/auth.go, line 414 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINrs7w0tAtigcYSzKA:-MIODNLR9-t6J5ZfznOy:b-o34oke) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L414)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Is this error logged? We should not try infinitely here as we have a false loop outside already. We should have a number of max attempts here, say 3.
What is the behavior initially when the user has not given a schema with a JWK_URL?
</blockquote></details>

Added retry only for 3 attempts. Also added the case if no `JWK_URL` is given.

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6564)* status: 0 of 6 files reviewed, 16 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/authorization/auth.go, line 414 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MINrs7w0tAtigcYSzKA:-MI_0jQl-V9ysX9hTk7K:b-h2anfd) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c9733db90b81790d2df6158aed1de1d049e9e76/graphql/authorization/auth.go#L414)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`a.fetchJWKs`
</blockquote></details>

FetchJWKs is called from the `schema` package.
___
*[graphql/authorization/auth.go, line 387 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIYe4ps5NSZdfCL5NLp:-MI_0V6l94HJKya6axLS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c3c3c528ebd476bc7a744be80ba154d36d42a0a7/graphql/authorization/auth.go#L387)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

error not handled
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 160 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZk4jaAAlIun317UBr:-MI_0Jpm2QeEYnRthoN6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L160)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

remove please
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 307 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZkRIdB3e9wuCzqAG2:-MI_0L187TJxNtpbd-6T:b-z15la9) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L307)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Does this need to be a public function?
</blockquote></details>

No. Changed it.
___
*[graphql/authorization/auth.go, line 309 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZkAGSCzr23uSYyEwR:-MI_0OV2B7F_AC6Io2Eh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L309)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

use `errors.Wrap(err, "while refreshing JWK from the URL")`. It gives context about the error.
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 370 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZki-k7jM9hW4tmznb:-MI_0P4M-LTCi1p676_H:bh69prf) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L370)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

fetchJWKs
</blockquote></details>

But this function is called in the `schema` package so need to make it public.
___
*[graphql/authorization/auth.go, line 416 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZks3zC-kD_KSnReHV:-MI_0dUH3ZjWC0PyECsk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L416)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 418 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZnAbI2dp0DL0G4fH1:-MI_0eCx2emCkmFNsm_H:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L418)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

RLock needed to access this
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 437 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZl2o-ACrvzxrQHcWo:-MI_0iSqBszmxIC8R6fv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L437)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

If `a.expiryTime.IsZero()` is better.
</blockquote></details>

Done.
___
*[graphql/resolve/auth_test.go, line 255 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZlzpI20RWEH1Pt8sT:-MI_0tpq1ej8nMmgBbgS:bfs9run) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/resolve/auth_test.go#L255)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Are you going to add this as well like a success case?
</blockquote></details>

Yeah, Actually I need to figure out minting a token with a long expiry date. Then I will do that.
___
*[graphql/schema/schemagen.go, line 226 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZmIBhB-LhTG5aewVo:-MI_12gcAM7t1-h8fdQq:b499q7j) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/schema/schemagen.go#L226)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Should be a RWLock because you are setting some values in there
</blockquote></details>

Changed

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6564)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @minhaj-shakeel, and @vvbalaji-dgraph)

___
*[graphql/authorization/auth.go, line 307 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZkRIdB3e9wuCzqAG2:-MIrir0ZDErezrMC4Fcy:bd070uf) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L307)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

No. Changed it.
</blockquote></details>

Hmm, this function already has a `RLock` and then another lock is acquired within refreshJWK. This must be having a deadlock. How does this work?
___
*[graphql/authorization/auth.go, line 370 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZki-k7jM9hW4tmznb:-MIriTGMDkZiYEFIHKeV:b-x6j4hn) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/authorization/auth.go#L370)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

But this function is called in the `schema` package so need to make it public.
</blockquote></details>

I see ok
___
*[graphql/resolve/auth_test.go, line 255 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6564#-MIZlzpI20RWEH1Pt8sT:-MIrjB1r5vOmArLMd3lS:b2ni9b3) ([raw file](https://github.com/dgraph-io/dgraph/blob/bde2adebd435ae52ad455126b547a468927a5628/graphql/resolve/auth_test.go#L255)):*
<details><summary><i>Previously, minhaj-shakeel wrote…</i></summary><blockquote>

Yeah, Actually I need to figure out minting a token with a long expiry date. Then I will do that.
</blockquote></details>

ok

**Pull request merged**
