### PR TITLE
Add option to ignore index conflicts

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1855)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dgraph/cmd/root.go, line 60 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9vizyTvVWvkvYvAwZ:-L-9vizyTvVWvkvYvAw_:b-ioccuh) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/dgraph/cmd/root.go#L60)):*
> ```Go
> 	}
> 	// Flags are parsed in RootCmd.Execute
> 	runtime.SetBlockProfileRate(blockRate)
> ```

These won't get called then.

---

*[posting/list.go, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9wQDvholonf1Cxg7Q:-L-9wQDvholonf1Cxg7R:b-hwspxc) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/posting/list.go#L358)):*
> ```Go
> 	ignoreConflict := t.Attr == "_predicate_" ||
> 		(txn.IgnoreIndexConflict && !x.Parse(l.key).IsData())
> 	if !ignoreConflict && (hasPendingDelete || txn.StartTs < l.commitTs) {
> ```

doAbort := hasPending...
if t.Attr == "_pre." { doAbort = false } else if txn.... { doAbort = false }.

if doAbort { txn... }

---

*[protos/api.proto, line 63 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9woSaHj_tZboAQCIq:-L-9woSaHj_tZboAQCIr:b6nmrbb) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/protos/api.proto#L63)):*
> ```protobuf
> 	uint64 start_ts = 13;
> 	bool commit_now = 14;
> 	bool ignoreIndexConflict = 15;
> ```

ignore_index_conflict

---

*[protos/internal.proto, line 185 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9wrHlc_sVqx2oyqAe:-L-9wrHlc_sVqx2oyqAf:b-5h08c7) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/protos/internal.proto#L185)):*
> ```protobuf
> 	repeated SchemaUpdate schema = 4;
> 	bool DropAll = 5;
> 	bool ignoreIndexConflict = 6;
> ```

same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-:-L-9wv1oen6fqGdFupWX:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 8 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[dgraph/cmd/root.go, line 60 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9vizyTvVWvkvYvAwZ:-L-9yd-Ou0nnjY8YgRSd:b-mqz0us) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/dgraph/cmd/root.go#L60)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

These won't get called then.
</blockquote></details>

Peter is going to fix this in his PR, i will add a todo for now. Flags are parsed before calling cmd.execute

---

*[posting/list.go, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9wQDvholonf1Cxg7Q:-L-9zovROmmjXIujk5Ax:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/posting/list.go#L358)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

doAbort := hasPending...
if t.Attr == "_pre." { doAbort = false } else if txn.... { doAbort = false }.

if doAbort { txn... }
</blockquote></details>

Done.

---

*[protos/api.proto, line 63 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9woSaHj_tZboAQCIq:-L-9yp2F_tsDb6hew7F9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/protos/api.proto#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ignore_index_conflict
</blockquote></details>

Done.

---

*[protos/internal.proto, line 185 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-9wrHlc_sVqx2oyqAe:-L-9z1nLo0zjrEM2T-Bt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4eb3c310f757d15adc2e02664a047022a11c9e5d/protos/internal.proto#L185)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 8 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[dgraph/cmd/server/http.go, line 194 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-ABwCQD1v73G4wrcYc:-L-ABwCQD1v73G4wrcYd:bnvno54) ([raw file](https://github.com/dgraph-io/dgraph/blob/f7e82d49a0b5c8bd43a702d9fe09a6c2ade01cf9/dgraph/cmd/server/http.go#L194)):*
> ```Go
> 	}
> 
> 	ignoreIndexConflict := r.Header.Get("X-Dgraph-IgnoreIndexConflict")
> ```

Add to accepted headers in CORS.

---

*[posting/list.go, line 230 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-ACd5ntr16mjUQtrGh:-L-ACd5ntr16mjUQtrGi:bkeza6a) ([raw file](https://github.com/dgraph-io/dgraph/blob/f7e82d49a0b5c8bd43a702d9fe09a6c2ade01cf9/posting/list.go#L230)):*
> ```Go
> 	size := atomic.LoadInt32(&l.estimatedSize)
> 	if size < 0 {
> 		return 0
> ```

I don't usually like it but should we assert here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-:-L-AERI6xlY-5mhZbxgR:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 8 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[dgraph/cmd/server/http.go, line 194 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-ABwCQD1v73G4wrcYc:-L-ANx7z6c-rcw59rU4K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f7e82d49a0b5c8bd43a702d9fe09a6c2ade01cf9/dgraph/cmd/server/http.go#L194)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add to accepted headers in CORS.
</blockquote></details>

Done.

---

*[posting/list.go, line 230 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855#-L-ACd5ntr16mjUQtrGh:-L-ANy-imyiX4zJmFUAp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f7e82d49a0b5c8bd43a702d9fe09a6c2ade01cf9/posting/list.go#L230)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I don't usually like it but should we assert here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1855)*

**Pull request closed without merging**
