### PR TITLE
improve/serialintersect

### PR DESCRIPTION
**Pull request by jchiu0**
Intersect results serially.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/317)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 1080 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWacAUVP-815G8En5qt:-KWacAUW1gExhmLmFKjD:boobizb) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1080)):*
> ```Go
> 	// First, get UIDs for child filters in parallel.
> 	type resultPair struct {
> 		uid *algo.UIDList
> ```

Can be uidList or uids to denote its a list.

---

*[query/query.go, line 1083 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWabOu6tKdVqthBMnzH:-KWabOu7il_LKlhCKqmx:b-gfyu6j) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1083)):*
> ```Go
> 		err error
> 	}
> 	resultChan := make(chan resultPair)
> ```

Is it intended to make it a blocking channel? Better of its size is len(filter.Child).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/317)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query.go, line 1061 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWafx7hLOmZz2QL7Yga:-KWafx7hLOmZz2QL7Ygb:b-1ufvhw) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1061)):*
> ```Go
> 	if filter.Op == "&" {
> 		// For intersect operator, we process the children serially.
> 		x.AssertTrue(filter.Op == "&")
> ```

The if does the assertion already?

---

*[query/query.go, line 1064 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWagYlceKWJIL2dydQa:-KWagYlceKWJIL2dydQb:b-wb56i3) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1064)):*
> ```Go
> 		for _, c := range filter.Child {
> 			var err error
> 			destUIDs, err = runFilter(ctx, destUIDs, c)
> ```

Not sure if you prefer this but we could save a line there for FWIW
```
if destUIDs, err = runFilter(ctx, destUIDs, c); err != nil {
  return nil, err
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-:-KWaguPWpDzUJ3QryY4c:bnfp4nl)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query.go, line 1061 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWafx7hLOmZz2QL7Yga:-KWbys-a1JHdmm-9O7FU:bl217mv) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1061)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> The if does the assertion already?
</details>
Copy and paste failure.. deleted.

---

*[query/query.go, line 1064 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWagYlceKWJIL2dydQa:-KWbz9r2c2bV4jFCKH0W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1064)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Not sure if you prefer this but we could save a line there for FWIW
> ```
> if destUIDs, err = runFilter(ctx, destUIDs, c); err != nil {
>   return nil, err
> }
> ```
</details>
Done.

---

*[query/query.go, line 1080 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWacAUVP-815G8En5qt:-KWbzFDrvIvzClHcZdqQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1080)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Can be uidList or uids to denote its a list.
</details>
Done.

---

*[query/query.go, line 1083 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-KWabOu6tKdVqthBMnzH:-KWbzImcsPMchQpABTI-:b-be679s) ([raw file](https://github.com/dgraph-io/dgraph/blob/311894e0fd730b95f3de293b8c4b6a53f27481d0/query/query.go#L1083)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Is it intended to make it a blocking channel? Better of its size is len(filter.Child).
</details>
My bad. Could lead to goroutine leaks. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/317)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-:-KWbzuf4sU4lWfURjfYr:bnfp4nl)*

**Comment by ashwin95r** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/317)*

**Comment by jchiu0** [comment]
Thanks guys!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/317#-:-KWc4F5p4u_BtdsVcgNw:b7n8lk7)*

**Pull request closed without merging**
