### PR TITLE
Issues/GitHub

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1266)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraph/main.go, line 716 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq1vXTbcpQDDmQdYw14:-Kq1vXTbcpQDDmQdYw15:b-nhkz11) ([raw file](https://github.com/dgraph-io/dgraph/blob/24cc2c4d131bc28dc6e76dfc9098cc7777616f9e/cmd/dgraph/main.go#L716)):*
> ```Go
> 			select {
> 			case _, ok := <-sdCh:
> 				if ok {
> ```

No need for ok.

---

*[cmd/dgraph/main.go, line 717 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq1w1Snt3uX45_E8c30:-Kq1w1Sokq7W7s5zP0kV:b-w01k0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/24cc2c4d131bc28dc6e76dfc9098cc7777616f9e/cmd/dgraph/main.go#L717)):*
> ```Go
> 			case _, ok := <-sdCh:
> 				if ok {
> 					numShutDownSig++
> ```

After this line, print "Caught ctrl+c. Terminating now (this may take a few seconds)... "

---

*[cmd/dgraph/main.go, line 721 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq1wET7dSyKrzciVu6f:-Kq1wET7dSyKrzciVu6g:b-3zke1e) ([raw file](https://github.com/dgraph-io/dgraph/blob/24cc2c4d131bc28dc6e76dfc9098cc7777616f9e/cmd/dgraph/main.go#L721)):*
> ```Go
> 						shutdownServer()
> 					} else if numShutDownSig == 3 {
> 						os.Exit(1)
> ```

"Signaled thrice. Aborting!"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266)*

**Comment by janardhan1993** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraph/main.go, line 716 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq1vXTbcpQDDmQdYw14:-Kq20ks_Dh4Jx8Buz2qm:bo4xg1m) ([raw file](https://github.com/dgraph-io/dgraph/blob/24cc2c4d131bc28dc6e76dfc9098cc7777616f9e/cmd/dgraph/main.go#L716)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for ok.
</blockquote></details>

We need ok, i checked after a channel is closed this will get triggered and even on clean exit we would end up printing aborted.

---

*[cmd/dgraph/main.go, line 717 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq1w1Snt3uX45_E8c30:-Kq20lfOFTP5ipXLLaui:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/24cc2c4d131bc28dc6e76dfc9098cc7777616f9e/cmd/dgraph/main.go#L717)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

After this line, print "Caught ctrl+c. Terminating now (this may take a few seconds)... "
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 721 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq1wET7dSyKrzciVu6f:-Kq20mYlD4FjeGkLdIzp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/24cc2c4d131bc28dc6e76dfc9098cc7777616f9e/cmd/dgraph/main.go#L721)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

"Signaled thrice. Aborting!"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[cmd/dgraph/main.go, line 716 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5r2oOffQDuRXZqQEq:-Kq5r2oOffQDuRXZqQEr:b-qgp4ma) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/cmd/dgraph/main.go#L716)):*
> ```Go
> 			select {
> 			case _, ok := <-sdCh:
> 				if ok {
> ```

if !ok {  // channel is closed.
return
}

---

*[cmd/dgraph/main.go, line 718 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5rARWGrBceagol4_r:-Kq5rARWGrBceagol4_s:b-d61wba) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/cmd/dgraph/main.go#L718)):*
> ```Go
> 				if ok {
> 					numShutDownSig++
> 					fmt.Printf("Caught Ctrl-C. Terminating now (this may take a few seconds)...\n")
> ```

Println

---

*[cmd/dgraph/main.go, line 722 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5rCBGd0hXD6eHY0Kj:-Kq5rCBGd0hXD6eHY0Kk:b-d61wba) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/cmd/dgraph/main.go#L722)):*
> ```Go
> 						shutdownServer()
> 					} else if numShutDownSig == 3 {
> 						fmt.Printf("Signaled thrice. Aborting!\n")
> ```

Println

---

*[worker/draft.go, line 245 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5rpis7dMpY7CFiSpK:-Kq5rpis7dMpY7CFiSpL:b10mr29) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/worker/draft.go#L245)):*
> ```Go
> 			HeartbeatTick:   1,
> 			Storage:         store,
> 			MaxSizePerMsg:   128 << 10,
> ```

256 << 10.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-:-Kq5rtPGfQuNy1F5n6Rl:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dgraph/main.go, line 716 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5r2oOffQDuRXZqQEq:-Kq5siG6jmbUQ_rOK-hh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/cmd/dgraph/main.go#L716)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if !ok {  // channel is closed.
return
}
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 718 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5rARWGrBceagol4_r:-Kq5svVONum6uqUxZtSD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/cmd/dgraph/main.go#L718)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Println
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 722 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5rCBGd0hXD6eHY0Kj:-Kq5swBerfmdhahKYa9n:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/cmd/dgraph/main.go#L722)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Println
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266)*

**Comment by janardhan1993** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/draft.go, line 245 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266#-Kq5rpis7dMpY7CFiSpK:-Kq5t26doxvGEr_x8OYz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fccf53af261991668d39a4424414971a79d91eb7/worker/draft.go#L245)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

256 << 10.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1266)*

**Pull request merged**
