### PR TITLE
fix(Dgraph): check for deleteBelowTs in pIterator.valid

### PR DESCRIPTION
**Pull request by ajeetdsouza**
Fixes DGRAPH-2705.

To reproduce, first insert a large number of edges of the form:

```
<0x1> <follows> <0x2> .
<0x1> <follows> <0x3> .
<0x1> <follows> <0x4> .
...
```

and then delete all of them:

```
<0x1> <follows> * .
```

After this, we can still see a few edges left despite the delete succeeding.

The reason this happens is that each `part` in a `pIterator` is initialized with a `valid` function, which checks if the iterator is currently on a valid block of UIDs, and skips to the next valid block if not. In contrast, the `next` function advances to the next valid block regardless of whether the current block is valid or not.

The `next` function checks the `deleteBelowTs` to ensure that we don't end up reading deleted data from the disk, however, the `valid` function did not earlier include that check. As a result, we would end up reading one deleted UID from each part in the split posting list, after which we would call `next`, which would discard the rest of the part. This PR adds the same `deleteBelowTs` check to the `valid` function as well, to ensure that this does not happen.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7288)

### CODE REVIEW

**Review by pawanrawal — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain and @martinmr)

**Review by pawanrawal — APPROVED** [review]
Can you add a test for this?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7288#-:-MQvldjW67wt5rnKjnOB:bhzkhcg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain and @martinmr)

**Review by jarifibrahim — APPROVED** [review]
This PR needs a better description.

**Review by manishrjain — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7288#-:-MR5qZT92WQkrrObk7Jg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @martinmr and @vvbalaji-dgraph)

**Pull request merged**
