### PR TITLE
Fix/parser

### LINKED ISSUE #1311: Fix bad parsing logic
Once sam/parsertest gets merged, some test cases will be named "Bad" and they represent bad parser behavior (not bad test cases).  They should be fixed

- TestParseQueryWithVarValAggBad - `me(func: val(L), orderasc: val(n))` should not be permitted
- TestParseIdListBad - `uid( [0x1, 0x1, 2, 3, 0x34])` is obsolete
- TestParseFilter_unknowndirectiveBad - `@filtererr` should not be tolerated
- TestParseGeneratorErrorBad - okay parsing, bad error message
- TestParseGraphQLVarIdBad - `uid($a,$b,$c)` rejected with "Invalid use of comma"

Also maybe the message for "Expected 3 periods ("..."), got 2.'." could be improved.

### PR DESCRIPTION
**Pull request by pawanrawal**
This resolves #1311. 

The code change might look too much but actually, it's just a refactoring to handle the error first and return and then handle the bigger block in `parseFunction` and `parseDirective`. Apart from that, I have just added some sanity checks to check key and function names.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1315)

### CODE REVIEW

**Comment by srh** [comment]
OK.  It :lgtm:  For future reference I have one question about the three dots -- was lexing "..." differently something you considered?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1315#-:-KqywCfbxtC3-BYOXTtO:b-aifk5y)*

**Comment by srh** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1315)*

**Comment by pawanrawal** [comment]
Thanks! Yes, I did try it but it broke a bunch of stuff. So thought that handling it in parser would be easier.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1315#-:-KqzMtv2jAEQYHNtsab3:b7j53wa)*

**Comment by manishrjain** [comment]
IIRC, we used to lex three dots separately, but changed that to simplify our lexer -- it's job is just to convert to tokens. Parser is the right place for interpreting tokens.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1315#-:-Kr-0LBwuttNaW2g0y6i:bh86cat)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
