### PR TITLE
Improvement/uid postings

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1262)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[posting/index.go, line 416 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0l-SeVXQzjwp5PsfC:-Kq0l-SeVXQzjwp5PsfD:b-yy6rf6) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L416)):*
> ```Go
> 
> func UnmarshalPostingList(item *badger.KVItem) ([]*protos.Posting, []byte) {
> 	if item.UserMeta() == BitUidPostings {
> ```

BitUidPostings can be internal to posting package.

---

*[posting/index.go, line 419 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0l7SYlKssdBC8L-UI:-Kq0l7SYlKssdBC8L-UJ:b-umcpw6) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L419)):*
> ```Go
> 		return nil, item.Value()
> 	}
> 	pl := new(protos.PostingList)
> ```

use a sync pool.

---

*[posting/index.go, line 457 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0lWDdRJhXKxzm-uiQ:-Kq0lWDdRJhXKxzm-uiR:bt1giqx) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L457)):*
> ```Go
> 		pki := x.Parse(key)
> 		_, uids := UnmarshalPostingList(iterItem)
> ```

Need to deal with ownership of kv.Item().

---

*[posting/list.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0ltsHJh2OwkRy_FB2:-Kq0ltsHJh2OwkRy_FB3:bt7bwdi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/list.go#L64)):*
> ```Go
> 	// Add means add new element in mutation layer. It contributes 1 in Length.
> 	Add            uint32 = 0x03
> 	BitUidPostings byte   = 0x01
> ```

can be internal const.

---

*[posting/list.go, line 152 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0nH13RQOL9-GodPHH:-Kq0nH13RQOL9-GodPHI:bazvnm) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/list.go#L152)):*
> ```Go
> type PIterator struct {
> 	postings   []*protos.Posting
> 	uids       []byte
> ```

Just make it part of the pl above. Would decrease the amount of code change here.

---

*[posting/list.go, line 162 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0mXKp5KMManBjuox2:-Kq0mXKp5KMManBjuox3:b-jfhm0p) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/list.go#L162)):*
> ```Go
> 
> func findUidIndex(uids []byte, afterUid uint64) int {
> 	ulen := len(uids) / 8
> ```

We need ints to be fixed width, but we can adjust the fixed width based on the max uint in the list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262)*

**Comment by janardhan1993** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[posting/index.go, line 416 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0l-SeVXQzjwp5PsfC:-Kq1RQ53aPdhph2gGQul:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L416)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

BitUidPostings can be internal to posting package.
</blockquote></details>

Done.

---

*[posting/index.go, line 419 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0l7SYlKssdBC8L-UI:-Kq1RQmF-rm6wRReIiV8:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L419)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

use a sync pool.
</blockquote></details>

done

---

*[posting/index.go, line 457 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0lWDdRJhXKxzm-uiQ:-Kq1RVhkslI9C7_YN57u:b-dcoger) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L457)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Need to deal with ownership of kv.Item().
</blockquote></details>

This function is only called when we don't have the ownership and it copies internally

---

*[posting/list.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0ltsHJh2OwkRy_FB2:-Kq1RaHkyD58WGJuPk8E:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/list.go#L64)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can be internal const.
</blockquote></details>

Done.

---

*[posting/list.go, line 152 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0nH13RQOL9-GodPHH:-Kq1RavwuqPVukd2GH84:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/list.go#L152)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just make it part of the pl above. Would decrease the amount of code change here.
</blockquote></details>

Done.

---

*[posting/list.go, line 162 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0mXKp5KMManBjuox2:-Kq1RbPNBRq0Trs2B_OZ:bytask1) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/list.go#L162)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We need ints to be fixed width, but we can adjust the fixed width based on the max uint in the list.
</blockquote></details>

Doing it in sharded pl PR. I am storing the starting uid and diff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262)*

**Comment by manishrjain** [comment]
:lgtm: Few comments.

---

Reviewed 3 of 8 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/index.go, line 457 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0lWDdRJhXKxzm-uiQ:-Kq1S2KMpRUoBMQbyDiG:btt815n) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L457)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This function is only called when we don't have the ownership and it copies internally
</blockquote></details>

UnmarshalWithCopy

---

*[posting/list.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq1S9s5xkW0e-qFzN7i:-Kq1S9s5xkW0e-qFzN7j:b-uo97pp) ([raw file](https://github.com/dgraph-io/dgraph/blob/c94462336e4d7e0e26384d215cc23da30748fc18/posting/list.go#L63)):*
> ```Go
> 	Del uint32 = 0x02
> 	// Add means add new element in mutation layer. It contributes 1 in Length.
> 	Add            uint32 = 0x03
> ```

Separate the following by a space. Add a comment about what it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-:-Kq1UQI3WvJhCbRSrIO7:b-2g5n99)*

**Comment by janardhan1993** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/index.go, line 457 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq0lWDdRJhXKxzm-uiQ:-Kq1Uesb37hIpw7f7ijH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6c4af13d3fd987c015f317b7deea86e06186fcc/posting/index.go#L457)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

UnmarshalWithCopy
</blockquote></details>

Done.

---

*[posting/list.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262#-Kq1S9s5xkW0e-qFzN7i:-Kq1UtDiUSQwqQi-uEw7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c94462336e4d7e0e26384d215cc23da30748fc18/posting/list.go#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Separate the following by a space. Add a comment about what it is.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1262)*

**Pull request merged**
