### PR TITLE
feat(cmd/debuginfo) add new metrics to be collected

### PR DESCRIPTION
**Pull request by OmarAyo**
- This PR adds 5 new metrics (/jemalloc, /state, /health, /debug/vars, /metrics) to be collected when running  the `debuginfo` 
- the flag `-p` has been changed to `-m` to reflect the change. This new flag will let you pick up one or multiple metrics/pprof to be collected:
```
-m, --metrics strings    List of metrics & profile to dump in the report. (default [jemalloc,state,health,vars,metrics,heap,cpu_profile,trace,goroutine,threadcreate,block,mutex])
```
- default value of `-s` flag is now 30sec since it requires 30s to collect a cpu profile
- when saving the metric/profile - it will log the metric/profile name and the path where it's saving to.
- added new flag for time based profiles that are cpu and trace profiles:
```
-c, --cron_pprof strings   time-based pprof (default [cpu_profile,trace])
```

output of running the `debuginfo` command:
```
 dgraph debuginfo -s 30
I0305 21:01:44.730085   10587 run.go:126] using directory /tmp/dgraph-debuginfo041885197 for debug info dump.
I0305 21:01:44.730251   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/jemalloc
I0305 21:01:44.730261   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.731077   10587 debugging.go:51] saving jemalloc metric in /tmp/dgraph-debuginfo041885197/alpha_jemalloc.gz
I0305 21:01:44.731086   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/state
I0305 21:01:44.731092   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.731720   10587 debugging.go:51] saving state metric in /tmp/dgraph-debuginfo041885197/alpha_state.gz
I0305 21:01:44.731731   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/health
I0305 21:01:44.731736   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.732048   10587 debugging.go:51] saving health metric in /tmp/dgraph-debuginfo041885197/alpha_health.gz
I0305 21:01:44.732058   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/vars
I0305 21:01:44.732065   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.732557   10587 debugging.go:51] saving vars metric in /tmp/dgraph-debuginfo041885197/alpha_vars.gz
I0305 21:01:44.732568   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/metrics
I0305 21:01:44.732573   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.734904   10587 debugging.go:51] saving metrics metric in /tmp/dgraph-debuginfo041885197/alpha_metrics.gz
I0305 21:01:44.734912   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/pprof/heap
I0305 21:01:44.734917   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.738036   10587 debugging.go:51] saving heap metric in /tmp/dgraph-debuginfo041885197/alpha_heap.gz
I0305 21:01:44.738048   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/pprof/goroutine?debug=2
I0305 21:01:44.738057   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.739136   10587 debugging.go:51] saving goroutine metric in /tmp/dgraph-debuginfo041885197/alpha_goroutine.gz
I0305 21:01:44.739145   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/pprof/threadcreate
I0305 21:01:44.739151   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.740182   10587 debugging.go:51] saving threadcreate metric in /tmp/dgraph-debuginfo041885197/alpha_threadcreate.gz
I0305 21:01:44.740192   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/pprof/block
I0305 21:01:44.740198   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.741154   10587 debugging.go:51] saving block metric in /tmp/dgraph-debuginfo041885197/alpha_block.gz
I0305 21:01:44.741163   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/pprof/mutex
I0305 21:01:44.741169   10587 debugging.go:76] please wait... (30s)
I0305 21:01:44.742330   10587 debugging.go:51] saving mutex metric in /tmp/dgraph-debuginfo041885197/alpha_mutex.gz
I0305 21:01:44.742341   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/pprof/profile?seconds=30s
I0305 21:01:44.742348   10587 debugging.go:76] please wait... (30s)
I0305 21:02:14.812492   10587 debugging.go:63] saving cpu_profile metric in /tmp/dgraph-debuginfo041885197/alpha_cpu_profile.gz
I0305 21:02:14.812570   10587 debugging.go:74] fetching information over HTTP from http://localhost:8080/debug/pprof/trace?seconds=30s
I0305 21:02:14.812596   10587 debugging.go:76] please wait... (30s)
I0305 21:02:15.816449   10587 debugging.go:63] saving trace metric in /tmp/dgraph-debuginfo041885197/alpha_trace.gz
I0305 21:02:15.842375   10587 run.go:159] Debuginfo archive successful: dgraph-debuginfo041885197.tar.gz

```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7439)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7439)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @manishrjain, @OmarAyo, and @vvbalaji-dgraph)

___
*[dgraph/cmd/debuginfo/debugging.go, line 42 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MUEXrJ041TlBMxa7siF:-MUEXrJ16FKKT2zYVneV:bbp150n) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ea48c58a527d71a363469a5b127cf0c38e238e/dgraph/cmd/debuginfo/debugging.go#L42)):*
> ```Go
> }
> 
> var metricTypes = []string{
> ```

This can be a struct for the metric types. It can have a name and its endpoint. Something like

```
type debugMetric struct {
	name     string
	endpoint string
}

var metricTypes = []debugMetric{
	{
		name:     "jemalloc",
		endpoint: "/jemalloc",
	},
	{
		name:     "state",
		endpoint: "/state",
	},
	{
		name:     "health",
		endpoint: "/health",
	},
	{
		name:     "vars",
		endpoint: "/debug/vars",
	},
	{
		name:     "metrics",
		endpoint: "/metrics",
	},
}
```

Then the `name` and `endpoint` can be used separately.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/debuginfo/debugging.go, line 42 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MUEXrJ041TlBMxa7siF:-MUP2mCG-SujDe5eSr8F:bmle7ey) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ea48c58a527d71a363469a5b127cf0c38e238e/dgraph/cmd/debuginfo/debugging.go#L42)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

This can be a struct for the metric types. It can have a name and its endpoint. Something like

```
type debugMetric struct {
	name     string
	endpoint string
}

var metricTypes = []debugMetric{
	{
		name:     "jemalloc",
		endpoint: "/jemalloc",
	},
	{
		name:     "state",
		endpoint: "/state",
	},
	{
		name:     "health",
		endpoint: "/health",
	},
	{
		name:     "vars",
		endpoint: "/debug/vars",
	},
	{
		name:     "metrics",
		endpoint: "/metrics",
	},
}
```

Then the `name` and `endpoint` can be used separately.
</blockquote></details>

Addressed this by using a map instead

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7439)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @danielmai, @manishrjain, @OmarAyo, and @vvbalaji-dgraph)

___
*[dgraph/cmd/debuginfo/run.go, line 55 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2oFDa3pkVxBAW8TP-:-MV2oFDa3pkVxBAW8TP0:b-7nw5xx) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a9261cbed6855246eed8e6d45e0f362ff6fcff8/dgraph/cmd/debuginfo/run.go#L55)):*
> ```Go
> 	"cpu_profile":  "/debug/pprof/profile",
> 	"trace":        "/debug/pprof/trace",
> 	"goroutine":    "/debug/pprof/goroutine",
> ```

This should be `/debug/pprof/goroutine?debug=2` for the right goroutine stack format: https://dgraph.io/docs/howto/retrieving-debug-information/#goroutine-stack
___
*[dgraph/cmd/debuginfo/debugging.go, line 55 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2nqiY2TTQoy36JoA8:-MV2nqiY2TTQoy36JoA9:b5ao55b) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a9261cbed6855246eed8e6d45e0f362ff6fcff8/dgraph/cmd/debuginfo/debugging.go#L55)):*
> ```
> the debug
> ```
the debug info
___
*[dgraph/cmd/debuginfo/debugging.go, line 75 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2nuOiC1gNrdbWmfdA:-MV2nuOiC1gNrdbWmfdB:b40y5je) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a9261cbed6855246eed8e6d45e0f362ff6fcff8/dgraph/cmd/debuginfo/debugging.go#L75)):*
> ```
> dump file
> ```
debug file
___
*[dgraph/cmd/debuginfo/pprof.go, line 53 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2oAuL0qJE9F7Wc5Pe:-MV2oAuL0qJE9F7Wc5Pf:b-f6axwz) ([raw file](https://github.com/dgraph-io/dgraph/blob/589bc548e7f02c65c6bd209c5ff25cfb7ba1a98d/dgraph/cmd/debuginfo/pprof.go#L53)):*
> ```Go
> 
> 	for _, profileType := range profiles {
> 		source := fmt.Sprintf("%s/debug/pprof/%s?duration=%d", u.String(),
> ```

Are we still setting ?duration in the new one?

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/debuginfo/debugging.go, line 42 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MUEXrJ041TlBMxa7siF:-MV3D3d29ru-vi7vNjgK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ea48c58a527d71a363469a5b127cf0c38e238e/dgraph/cmd/debuginfo/debugging.go#L42)):*
<details><summary><i>Previously, OmarAyo (OmarAyo) wrote…</i></summary><blockquote>

Addressed this by using a map instead
</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/debuginfo/pprof.go, line 53 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2oAuL0qJE9F7Wc5Pe:-MV3D72-8d3jeW8QHNql:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/589bc548e7f02c65c6bd209c5ff25cfb7ba1a98d/dgraph/cmd/debuginfo/pprof.go#L53)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Are we still setting ?duration in the new one?
</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/debuginfo/debugging.go, line 55 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2nqiY2TTQoy36JoA8:-MV3D8PsB95oQGXQEzli:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a9261cbed6855246eed8e6d45e0f362ff6fcff8/dgraph/cmd/debuginfo/debugging.go#L55)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> the debug
> ```
the debug info
</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/debuginfo/debugging.go, line 75 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2nuOiC1gNrdbWmfdA:-MV3D9Ww4-fUN9HS6gYJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a9261cbed6855246eed8e6d45e0f362ff6fcff8/dgraph/cmd/debuginfo/debugging.go#L75)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> dump file
> ```
debug file
</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/debuginfo/run.go, line 55 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7439#-MV2oFDa3pkVxBAW8TP-:-MVa6WAb0Qb0q4iPqVGq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a9261cbed6855246eed8e6d45e0f362ff6fcff8/dgraph/cmd/debuginfo/run.go#L55)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

This should be `/debug/pprof/goroutine?debug=2` for the right goroutine stack format: https://dgraph.io/docs/howto/retrieving-debug-information/#goroutine-stack
</blockquote></details>

Done.

**Review by OmarAyo — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7439)* status: all files reviewed, 5 unresolved discussions (waiting on @danielmai, @manishrjain, and @vvbalaji-dgraph)

**Pull request merged**
