### PR TITLE
Edges : adding arbitrary key values

### PR DESCRIPTION
**Pull request by ashishnegi**
1. Added `dproto/facets.proto` file.
2. Import it in `tasks.proto, types.proto, graphresponse.proto`
3. Move the facet from NQuad to DirectedEdge to Posting

For issue #549 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/561)

### CODE REVIEW

**Comment by gacharya255** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[dproto/facets.proto, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-Kbx1BECsTKY1CY2TMM7:-Kbx1BECsTKY1CY2TMM8:bnew5tp) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/dproto/facets.proto#L1)):*
> ```protobuf
> // To compile this file, in dgraph directory :
> ```

Maybe it is easier not to create a new proto file?

---

*[posting/index.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-Kbx0Qr-p-VZIgd2P3Aa:-Kbx0Qr-p-VZIgd2P3Ab:b-ld84n0) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/posting/index.go#L76)):*
> ```Go
> 		Label:   "idx",
> 		Op:      op,
> 		Facets:  t.Facets,
> ```

I thought this is only for normal edges, not index or reverse edges?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/561)*

**Comment by ashishnegi** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[dproto/facets.proto, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-Kbx1BECsTKY1CY2TMM7:-Kbx3AoEQskQgv4V0w6q:b-tecy4q) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/dproto/facets.proto#L1)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Maybe it is easier not to create a new proto file?
</blockquote></details>

It looks something like this if we don't have one common proto file :
https://github.com/dgraph-io/dgraph/compare/master...ashishnegi:edges/key-values-temp?expand=1
We will have 3 facet grpc messages and will convert from one to another..

---

*[posting/index.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-Kbx0Qr-p-VZIgd2P3Aa:-Kbx5w4J9i9_PTDnPIsp:b-tinzm8) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/posting/index.go#L76)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

I thought this is only for normal edges, not index or reverse edges?
</blockquote></details>

Is it because `index` mutations are per predicate+token and not subject specific ? So, these edge weights don't make sense there..
And similarly for ReverseEdge, it is for   predicate+objectid. Subject's edge specific weights should not be part of that edge..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/561)*

**Comment by manishrjain** [comment]
LGTM. A few comments, so address them before submitting.

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[dproto/facets.proto, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-KbxA-UnyX4nDMscWo20:-KbxA-UnyX4nDMscWo21:bxi7ai3) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/dproto/facets.proto#L5)):*
> ```protobuf
> syntax = "proto3";
> 
> package dproto;
> ```

Maybe find a better package for this. Can this be moved to types?

---

*[dproto/facets.proto, line 15 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-KbxARthG-3_psn6ZAvi:-KbxARthG-3_psn6ZAvj:b-824dwl) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/dproto/facets.proto#L15)):*
> ```protobuf
> 	DATE = 5;
> 	DATETIME = 6;
> 	GEO = 7;
> ```

We can't really support GEO here. Also, UID and BINARY can be removed as well.

---

*[posting/index.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-Kbx0Qr-p-VZIgd2P3Aa:-KbxB2RrvBJJR0IpLJp4:bj98nck) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/posting/index.go#L76)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Is it because `index` mutations are per predicate+token and not subject specific ? So, these edge weights don't make sense there..
And similarly for ReverseEdge, it is for   predicate+objectid. Subject's edge specific weights should not be part of that edge..
</blockquote></details>

I think the weights still make sense for reverse edges. Though, not sure how useful they are for token indexing. So, for now, remove them. Only use them for reverses.

---

*[query/graph/graphresponse.proto, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-KbxBRDgsFSemP_lQ0MV:-KbxBRDhWHHGLNvMhA9w:b-p4vk4m) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/query/graph/graphresponse.proto#L2)):*
> ```protobuf
> // To compile this file, in dgraph directory :
> // protoc --gofast_out=plugins=grpc,Mdproto/facets.proto=github.com/dgraph-io/dgraph/dproto:. query/graph/graphresponse.proto
> ```

Any way to simplify this command?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-:-KbxC7xcaHW6D1RR78Ok:b2gfnp1)*

**Comment by ashishnegi** [comment]
Review status: 1 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/graph/graphresponse.proto, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-KbxBRDgsFSemP_lQ0MV:-KbxKR41hGW4I_KCNA2U:bir4lh6) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/query/graph/graphresponse.proto#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Any way to simplify this command?
</blockquote></details>

currently no. :(
i have raised an issue in `gogo` lib https://github.com/gogo/protobuf/issues/257. but it seems that problem is in main protoc itself and is unsolved for years. 

---

*[dproto/facets.proto, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-KbxA-UnyX4nDMscWo20:-KbxL-6wK6Thz8aCVWWE:blg61d3) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/dproto/facets.proto#L5)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe find a better package for this. Can this be moved to types?
</blockquote></details>

Moved to types/facets.
Could not make it part of `types/`.
Same problem of import paths issues.

---

*[dproto/facets.proto, line 15 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-KbxARthG-3_psn6ZAvi:-KbxL6cwhCPn5Oa07OT9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/dproto/facets.proto#L15)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We can't really support GEO here. Also, UID and BINARY can be removed as well.
</blockquote></details>

Done.

---

*[posting/index.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-Kbx0Qr-p-VZIgd2P3Aa:-KbxTHsv6VaU1xl6Ubod:bgy2kze) ([raw file](https://github.com/dgraph-io/dgraph/blob/3d28d86067b1e1e1b5cd1b2938a73b07292f8ba2/posting/index.go#L76)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I think the weights still make sense for reverse edges. Though, not sure how useful they are for token indexing. So, for now, remove them. Only use them for reverses.
</blockquote></details>

Removing facets from index and reverse edges for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/561)*

**Comment by gacharya255** [comment]
:lgtm:

---

Review status: 1 of 10 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/561#-:-Kbxj9AnAP0tj3vJKG35:bnfp4nl)*

**Pull request closed without merging**
