### PR TITLE
Query: Refactor query to have same logic for filters and generators

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/324)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 821 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrB-0O7U47nr1N9oYs:-KWrB-0PcIz3bkH7luzL:bgjorfa) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/gql/parser.go#L821)):*
> ```Go
> 
> 	item = <-l.Items
> 	if item.Typ == itemGenerator {
> ```

Should we change the naming of generator in state.go as well?

---

*[query/query.go, line 317 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrDgc3a5Wn_F8yU0Ax:-KWrDgc4JW7Uw1uqdQnX:b7hhj60) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L317)):*
> ```Go
> 		sg.Attr = ft.Func.Attr
> 		sg.SrcFunc = append(sg.SrcFunc, ft.Func.Name)
> 		sg.SrcFunc = append(sg.SrcFunc, ft.Func.Args...)
> ```

Would it be cleaner if we have SrcFunc and SrcArgs separately?

---

*[query/query.go, line 469 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrF2mrBFbBDfCby_TE:-KWrF2mrBFbBDfCby_TF:b-w4nh6g) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L469)):*
> ```Go
> 		sg.Attr = gq.Func.Attr
> 		sg.SrcFunc = append(sg.SrcFunc, gq.Func.Name)
> 		sg.SrcFunc = append(sg.SrcFunc, gq.Func.Args...)
> ```

Here too. SrcArgs.

---

*[query/query.go, line 560 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrFmi_aMSo8Iq6FRQR:-KWrFmi_aMSo8Iq6FRQS:bljo1b) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L560)):*
> ```Go
> 
> 	if len(sg.SrcFunc) > 0 {
> 		if len(sg.SrcFunc) < 2 {
> ```

Having SrcArgs would make this easier to grasp.

---

*[query/query.go, line 710 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrHwz94N1QqYDONHbH:-KWrHwz94N1QqYDONHbI:bqzhtm5) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L710)):*
> ```Go
> 		}
> 	}
> ```

Shouldn't we trim the result matrix here based on the destUIDs? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/324)*

**Comment by jchiu0** [comment]
Offset with filtering is not working?

---

Review status: 5 of 7 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 36 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3UGa546nV2i4Ga4r-:-KX3UGa546nV2i4Ga4r0:b-rsc2bi) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/gql/parser.go#L36)):*
> ```Go
> 	Attr  string
> 	Alias string
> 	Func  *Function
> ```

Function or Func may not be very good words to use. You can't use "func" for instance. Maybe later can rename to something else.

---

*[query/query.go, line 214 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3gGwkD6o0ZwozdPgO:-KX3gGwkD6o0ZwozdPgP:b-evrr92) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L214)):*
> ```Go
> 		idx := pc.SrcUIDs.IndexOf(uid)
> 		if idx < 0 {
> 			continue
> ```

This can now happen? We used to filter and cut down as much as possible before expanding along predicates. This is no longer true?

---

*[query/query.go, line 586 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3bHAs8G8HJ2ZhZeYQ:-KX3bHAs8G8HJ2ZhZeYR:b4dh95q) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L586)):*
> ```Go
> 		switch sg.SrcFunc[0] {
> 		case "anyof":
> 			// TODO: Why only one argument, why not multiple terms?
> ```

Currently we take just one argument and split it into tokens, so the terms are all in one string.

Agree that we could handle multiple args here and just append all the tokens.

---

*[query/query.go, line 626 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3eiBcJjbie8Oiq24p:-KX3eiBcJjbie8Oiq24q:b3dxavt) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L626)):*
> ```Go
> 	} else {
> 		sg.DebugPrint("CREATE ")
> 		_ = intersect
> ```

intersect is unused?

---

*[query/query.go, line 689 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3fCRHaa9dA2IlT-vz:-KX3fCRIV6LoeonJiTe6:bupdopd) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L689)):*
> ```Go
> 		filterChan := make(chan error, len(sg.Filters))
> 		for i := 0; i < len(sg.Filters); i++ {
> 			filter := sg.Filters[i]
> ```

for _, filter := range

---

*[query/query_test.go, line 679 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3e90xDTsj-8pM-gLy:-KX3e90yy9C_GtEt8Hus:b-hq3csk) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query_test.go#L679)):*
> ```Go
> 				name
> 				gender
> 				friend(offset:0) @filter(anyof("name", "Andrea") || anyof("name", "Glenn Rhee") || anyof("name", "Daryl Dixon")) {
> ```

Why change this? (If temporary, can add TODO)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-:-KX3i4dsKvagAQIBHp4E:bxeopt5)*

**Comment by manishrjain** [comment]
Review status: 5 of 7 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 821 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrB-0O7U47nr1N9oYs:-KX4_xwITv-oX3PuDGtk:b-1a04h9) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/gql/parser.go#L821)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Should we change the naming of generator in state.go as well?
</details>
emm.. maybe. These are independent; so I don't care as much.

---

*[gql/parser.go, line 36 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3UGa546nV2i4Ga4r-:-KX4_t5Ca01YTszxmn2E:bxcuqmz) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/gql/parser.go#L36)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Function or Func may not be very good words to use. You can't use "func" for instance. Maybe later can rename to something else.
</details>
Yeah, wasn't sure what would be a good name here. Didn't want to use generator.

---

*[query/query.go, line 317 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrDgc3a5Wn_F8yU0Ax:-KX4chQwqOGOu0XP1hLA:be8mhty) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L317)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Would it be cleaner if we have SrcFunc and SrcArgs separately?
</details>
I thought about it -- and concluded that having just one field was better.

---

*[query/query.go, line 469 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrF2mrBFbBDfCby_TE:-KX4coMKx9Go_oSwZ6ZW:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L469)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Here too. SrcArgs.
</details>
Same here.

---

*[query/query.go, line 560 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrFmi_aMSo8Iq6FRQR:-KX4cqTcu4byXuklyJpL:b-xbc0e6) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L560)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Having SrcArgs would make this easier to grasp.
</details>
I think of it like unix commandline args. The name of the binary is part of the args; this is similar.

---

*[query/query.go, line 710 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrHwz94N1QqYDONHbH:-KX4eI3oO4X8WoDQYxXV:bn6dx5e) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L710)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Shouldn't we trim the result matrix here based on the destUIDs? 
</details>
Do we need to? PreTraverse can just ignore the uids which are not present in the result right?

---

*[query/query.go, line 214 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3gGwkD6o0ZwozdPgO:-KX4cRCuHGb7WUTxLFrQ:bdkhmp6) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L214)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> This can now happen? We used to filter and cut down as much as possible before expanding along predicates. This is no longer true?
</details>
Yeah, this can happen because the uidmatrix isn't modified, but destuids can be filtered.

---

*[query/query.go, line 586 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3bHAs8G8HJ2ZhZeYQ:-KX4cwpZL_CZD9vLjATz:beqqxqc) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L586)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Currently we take just one argument and split it into tokens, so the terms are all in one string.
> 
> Agree that we could handle multiple args here and just append all the tokens.
</details>
Yeah, I think we should do that. So, then we won't need to have 3 anyOfs, using OR operators. Also, anyOf function can then have as many number of args as needed.

---

*[query/query.go, line 626 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3eiBcJjbie8Oiq24p:-KX4dXIjpTCbEgrvXq_q:b7kb0pf) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L626)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> intersect is unused?
</details>
Nope, it can be derived from SrcUids.

---

*[query/query.go, line 689 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3fCRHaa9dA2IlT-vz:-KX4e8DelfXJVNwqs3bb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query.go#L689)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> for _, filter := range
</details>
Done.

---

*[query/query_test.go, line 679 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX3e90xDTsj-8pM-gLy:-KX4eUN-Sx9z06O4nw7U:boa5dwv) ([raw file](https://github.com/dgraph-io/dgraph/blob/449e2158f8f9b755da692a9a0bf36dae4ad33dd7/query/query_test.go#L679)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Why change this? (If temporary, can add TODO)
</details>
Reverted back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/324)*

**Comment by ashwin95r** [comment]
Review status: 2 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 710 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrHwz94N1QqYDONHbH:-KX4rxnCp-h295pS9RFv:bo83os0) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L710)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Do we need to? PreTraverse can just ignore the uids which are not present in the result right?
</details>
Sure. I think I didn't see the corresponding change to preTraverse in that revision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/324)*

**Comment by jchiu0** [comment]
:lgtm: 

---

Review status: 2 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[gql/parser.go, line 113 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4vOfrGdot8c3e-p58:-KX4vOfrGdot8c3e-p59:bqvld5t) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/gql/parser.go#L113)):*
> ```Go
> // DebugPrint is useful for debugging.
> func (gq *GraphQuery) DebugPrint(prefix string) {
> 	fmt.Printf("%s[%x %q %q->%q]\n", prefix, gq.UID, gq.XID, gq.Attr, gq.Alias)
> ```

x.Printf perhaps.

---

*[query/query.go, line 163 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4vAVfPbqm6vGqttRT:-KX4vAVgCf7atsHfKLXr:bqvld5t) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/query/query.go#L163)):*
> ```Go
> 		dst = len(sg.DestUIDs.Uids)
> 	}
> 	fmt.Printf("%s[%q Alias:%q Func:%v SrcSz:%v Op:%q DestSz:%v Dest: %p ValueSz:%v]\n",
> ```

x.Printf perhaps.

---

*[query/query.go, line 638 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4vv-y0VxB1j4E8iz4:-KX4vv-y0VxB1j4E8iz5:bvm9aj0) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/query/query.go#L638)):*
> ```Go
> 			case err = <-filterChan:
> 				if err != nil {
> 					x.TraceError(ctx, x.Wrapf(err, "Error while processing child task"))
> ```

Can perhaps add some info about the filter in the trace, or at least mentioned that this is the filter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-:-KX4wCvVzJ2Gu9hJ7NyH:bg7igkv)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[query/query.go, line 230 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4umZpUD0Q-eAsEwI4:-KX4umZpUD0Q-eAsEwI5:bqvut4f) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/query/query.go#L230)):*
> ```Go
> 			uc.AddValue("_count_", &c)
> 			dst.AddChild(pc.Attr, uc)
> ```

Intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-:-KX4wQ6aSge_-kJpQGXF:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 113 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4vOfrGdot8c3e-p58:-KX4x9lqmU5mEA4tRt31:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/gql/parser.go#L113)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> x.Printf perhaps.
</details>
Done.

---

*[query/query.go, line 710 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KWrHwz94N1QqYDONHbH:-KX4x-Xbexzbdb6-vd3m:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a8619e729c71a062f6b717ebdceae48feded8a2/query/query.go#L710)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Sure. I think I didn't see the corresponding change to preTraverse in that revision.
</details>
Done.

---

*[query/query.go, line 163 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4vAVfPbqm6vGqttRT:-KX4xE4l0ZGgMgt-HSM1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/query/query.go#L163)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> x.Printf perhaps.
</details>
Done.

---

*[query/query.go, line 230 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4umZpUD0Q-eAsEwI4:-KX4xiBVAvao9l7fZbv6:bwzd387) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/query/query.go#L230)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Intended?
</details>
Yeah, intended.

---

*[query/query.go, line 638 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/324#-KX4vv-y0VxB1j4E8iz4:-KX4xrPFq1GKOV-8NJ8A:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8dc9938e88de5179dfad14de501c1ed6f26dfa4/query/query.go#L638)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Can perhaps add some info about the filter in the trace, or at least mentioned that this is the filter.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/324)*

**Pull request closed without merging**
