### PR TITLE
Use blanknode for _new_ and no prefixes for xid/uid

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/437)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Address the comments, then submit.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 151 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_SpFvCIejz_SNJT4IY:-K_SpFvCIejz_SNJT4IZ:b9r71xx) ([raw file](https://github.com/dgraph-io/dgraph/blob/19ce845af30b3f59b6ab60cb6cb7de63fc3845c3/cmd/dgraph/main.go#L151)):*
> ```Go
> 		if strings.HasPrefix(nq.Subject, "_:") {
> 			newUids[nq.Subject] = 0
> 		} else if !strings.HasPrefix(nq.Subject, "_uid_:") {
> ```

Why check for this?

---

*[rdf/parse.go, line 38 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_SphODiM3aT4P84b9P:-K_SphODiM3aT4P84b9Q:btqpzu3) ([raw file](https://github.com/dgraph-io/dgraph/blob/19ce845af30b3f59b6ab60cb6cb7de63fc3845c3/rdf/parse.go#L38)):*
> ```Go
> // Gets the uid corresponding to an xid from the posting list which stores the
> // mapping.
> func GetUid(xid string) (uint64, error) {
> ```

No need to return error here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-:-K_SqIV5JEZGVCyGWQuK:b-727jp7)*

**Comment by ashwin95r** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 151 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_SpFvCIejz_SNJT4IY:-K_StwlWkOSIM_ZZ-mKT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/19ce845af30b3f59b6ab60cb6cb7de63fc3845c3/cmd/dgraph/main.go#L151)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why check for this?
</blockquote></details>

Done.

---

*[rdf/parse.go, line 38 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_SphODiM3aT4P84b9P:-K_StxYpd0eg4ICPQfbF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/19ce845af30b3f59b6ab60cb6cb7de63fc3845c3/rdf/parse.go#L38)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to return error here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/437)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 165 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_T-5ScVm57L9v7hnms:-K_T-5SdIp77bzic618h:b-4f5k4f) ([raw file](https://github.com/dgraph-io/dgraph/blob/f35e34d535302ff7f3dca0239daab6f6c7951c9d/cmd/dgraph/main.go#L165)):*
> ```Go
> 			} else if !strings.HasPrefix(nq.ObjectId, "_uid_:") {
> 				uid := rdf.GetUid(nq.ObjectId)
> 				newUids[nq.ObjectId] = uid
> ```

Maybe combine the two lines?

---

*[rdf/parse.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_SzWuQXKRxO8gdMyum:-K_SzWuQXKRxO8gdMyun:b-9lko11) ([raw file](https://github.com/dgraph-io/dgraph/blob/f35e34d535302ff7f3dca0239daab6f6c7951c9d/rdf/parse.go#L40)):*
> ```Go
> func GetUid(xid string) uint64 {
> 	// If string represents a UID, convert to uint64 and return.
> 	uid, err := strconv.ParseUint(xid[:], 0, 64)
> ```

xid instead of xid[:]?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-:-K_T-90R18DINx2G6_8-:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dgraph/main.go, line 165 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_T-5ScVm57L9v7hnms:-K_T-diJpNe_QnG_sEJn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f35e34d535302ff7f3dca0239daab6f6c7951c9d/cmd/dgraph/main.go#L165)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Maybe combine the two lines?
</blockquote></details>

Done.

---

*[rdf/parse.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/437#-K_SzWuQXKRxO8gdMyum:-K_T0O8htH6ixskWI5j5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f35e34d535302ff7f3dca0239daab6f6c7951c9d/rdf/parse.go#L40)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

xid instead of xid[:]?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/437)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
