### PR TITLE
proto: Fix duplicate registration warning

### PR DESCRIPTION
**Pull request by jarifibrahim**
This commit fixes the following warning by renaming the proto file from `pb.proto` to `dgraph.proto`. Badger also has a `pb.proto` file and that's why protobuf runtime complains about duplicate registration
```
$ dgraph
2020/04/22 17:19:12 WARNING: proto: file "pb.proto" is already registered                                             A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```
This warning was not visible until now because protobuf was updated in commit https://github.com/dgraph-io/dgraph/commit/7b37ddba6d98a5d5e49ecd1e6d76295fba18ddec. This update is a side effect of https://github.com/dgraph-io/dgraph/blob/25c37c823593fe4480ca10e3354336503be3785b/protos/Makefile#L34 which tries to fetch the latest version of protobuf. The latest version of protobuf v1.4.0 was released a week ago and this new version complaints if two files have the same name.

This PR also removes the `sed` commands from the Makefile since they were unnecessary.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5287)

### CODE REVIEW

**Comment by danielmai** [comment]
___
*[protos/dgraphpb.proto, line 28 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/5287#-M5ce65y-YJqDjJxMu8g:-M5ce65y-YJqDjJxMu8h:b-eyub6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/17b9c1fc81f1006d56eca6ceec01672de47c802e/protos/dgraphpb.proto#L28)):*
> ```protobuf
> 
> import "api.proto";
> import "github.com/dgraph-io/badger/pb/pb.proto";
> ```

Don't we need to keep the v2 import path to pick up the badger v2 protos?

**Comment by danielmai** [comment]
___
*[protos/Makefile, line 49 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/5287#-M5ceiIc9hUDUcskmv3D:-M5ceiIc9hUDUcskmv3E:b-baby1a) ([raw file](https://github.com/dgraph-io/dgraph/blob/dc8b80c93eabf955178b0eb406e6c179cca048f6/protos/Makefile#L49)):*
> ```Makefile
> 		pb.proto
> 	@sed -i'' -e 's;github.com/dgraph-io/badger/pb/pb.proto;github.com/dgraph-io/badger/v2/pb/pb.proto;' pb.proto
> 	@sed -i'' -e 's;github.com/dgraph-io/badger/pb;github.com/dgraph-io/badger/v2/pb;' pb/pb.pb.go
> ```

Are these no longer needed to pick up the Go module proto of Badger v2?

**Comment by danielmai** [comment]
___
*[protos/dgraphpb.proto, line 28 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/5287#-M5ce65y-YJqDjJxMu8g:-M5cgBLz7hYcH4nfNfua:b9w3l8v) ([raw file](https://github.com/dgraph-io/dgraph/blob/17b9c1fc81f1006d56eca6ceec01672de47c802e/protos/dgraphpb.proto#L28)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Protobuf import paths are different from golang import paths. If you look at the `sed` command in the makefile, it was replacing the v2 import path with a normal one.
</blockquote></details>

It was replacing the v2 one with the normal one and then putting v2 back. does `make regenerate` put in badger/v2?

**Comment by jarifibrahim** [comment]
We don't need this PR anymore.

**Pull request closed without merging**
