### PR TITLE
WIP - refactoring docs

### PR DESCRIPTION
**Pull request by MichaelJCompton**
Refactor of the GraphQL+- docs.   Trying to make the docs work like reference material - tour, blog etc should be the learning material.

Partly done, opening up for comments if anyone thinks it's not heading the right way.  **The GraphQL+- page is 3/4 done, the rest is not**

Note: docs won't build unless on master or a release branch - quick hack is to change line 3 of wiki/scripts/local.sh to `CURRENT_BRANCH='master'`   (but the examples won't run)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1018)

### CODE REVIEW

**Comment by manishrjain** [comment]
For whatever reason, even with the hack, when I run via hugo, it doesn't show me anything. The page just looks empty.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1018#-:-KlvxTfZoUDoNuQsJr17:b-c4oz2o)*

**Comment by sungwoncho** [comment]
@michaeljcompton Now we can run docs in any branches. Can you rebase on master? Also you will need to pull the latest theme as well. Then @manishrjain will be able to run the docs. Sorry about this.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1018#-:-KmPej8Cpqa7VEs0uH67:b-xxtkjd)*

**Comment by sungwoncho** [comment]
I noticed that 'Schema' section is moved down to the bottom in 'query lanauges'. any reasons for this?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1018#-:-KmPgndBdPSpqsSzjKPp:btjtwmf)*

**Comment by MichaelJCompton** [comment]
I think there are two things going on in this doc: the query language and mutations/schema.  I wanted to start to separate them a bit.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1018#-:-KmTXpcF-xrHAbA6qh8t:b31ag5y)*

**Pull request closed without merging**
