### PR TITLE
Build trigrams from 3-bytes, not 3-runes

### LINKED ISSUE #945: regexp function do not match all language
example:
`query {
  names(func: regexp(name.title@ru, /^артем*$/i)) {
    name.title
  }
}`
empty result

`query {
  names(func: regexp(name.title@en, /^john*$/i)) {
    name.title
  }
}`
all fine

### PR DESCRIPTION
**Pull request by tzdybal**
This change is necessary to be compatible with codesearch library.

This commit fixes #945.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/954)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query_test.go, line 3201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/954#-KkOhZL4tnVYaVywf07q:-KkOhZL4tnVYaVywf07r:b-lwuuyf) ([raw file](https://github.com/dgraph-io/dgraph/blob/25fb92d81420895a46f0995c60bc6316f5a24831/query/query_test.go#L3201)):*
> ```Go
> 	populateGraph(t)
> 	posting.CommitLists(10, 1)
> 	time.Sleep(50 * time.Millisecond)
> ```

Just to be sure, do we need these lines? commitLists and sleep. I think I had it when we were doing a full range scan with exact indices. Since we use trigram indexing now, this might not be required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/954#-:-KkOhu_IF7c7YObfr4EV:bnfp4nl)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tok/tok.go, line 291 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/954#-KkOhSiLSRfB18MZkzTj:-KkOhSiMMN2X1rT2Maw1:bc7wrcw) ([raw file](https://github.com/dgraph-io/dgraph/blob/25fb92d81420895a46f0995c60bc6316f5a24831/tok/tok.go#L291)):*
> ```Go
> 		tokens := make([]string, l)
> 		for i := 0; i < l; i++ {
> 			trigram := string(value[i : i+3])
> ```

`string()` unnecessary now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/954#-:-KkOj53FxfgkZ7zdKuDp:bnfp4nl)*

**Comment by pawanrawal** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/954)*

**Comment by pawanrawal** [comment]
Please merge to `release/v0.7.7`, we will merge release to master soon.

**Comment by tzdybal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query_test.go, line 3201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/954#-KkOhZL4tnVYaVywf07q:-KkOq7LqfsKtiYaVxRGC:b-qu6n94) ([raw file](https://github.com/dgraph-io/dgraph/blob/25fb92d81420895a46f0995c60bc6316f5a24831/query/query_test.go#L3201)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Just to be sure, do we need these lines? commitLists and sleep. I think I had it when we were doing a full range scan with exact indices. Since we use trigram indexing now, this might not be required.
</blockquote></details>

Good point. Done.

---

*[tok/tok.go, line 291 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/954#-KkOhSiLSRfB18MZkzTj:-KkOqAsKpACrm1N7zWy4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/25fb92d81420895a46f0995c60bc6316f5a24831/tok/tok.go#L291)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`string()` unnecessary now?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/954)*

**Comment by tzdybal** [comment]
Changes committed to `release/v0.7.7` (0d73f85154a7c561dbf2efb12ff034da07a2cb88).

**Pull request closed without merging**
