### PR TITLE
Terraform modules for Kubernetes - AWS EKS

### PR DESCRIPTION
**Pull request by slotlocker2**
### Description.
Terraform modules to setup Dgraph on Kubernetes. Supports AWS EKS currently.

### GitHub Issue or Jira number.
1002

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5092)

### CODE REVIEW

**Comment by sleto-it** [comment]
Thanks for working on this

Would be nice to also create a section in our official documentation. Not asking to duplicate the content we have in `contrib/config/terraform/kubernetes/README.md` but we can still say something and add a link

A new doc section will help in case someone is looking for such terraform modules, and if they are searching "terraform" in the search box

Thanks,

**Comment by dmitryyankowski** [comment]
Would love to see a Terraform config for Dgraph on GKE (Google Kubernetes Engine) 😃

**Comment by slotlocker2** [comment]
Will be working on GKE sooner than later - need to get started with setting up the environment to get some testing going on there - can have a holistic documentation around Terraform once that's out. :+1:

**Comment by dmitryyankowski** [comment]
Awesome @sleto-it 😃

**Comment by dmitryyankowski** [comment]
@slotlocker2 another thing I thought of.. was that it would be awesome to have TLS working in this example! Since you're adding the VPC support.. might as well have TLS for extra security right?

**Pull request merged**
