### PR TITLE
Change executable from `dgraph` to `server` to match actual executable

### PR DESCRIPTION
**Pull request by nii236**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/119)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 73 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/119#-KL1Nn3NhSP1auq69gkm:-KL1Nn3NhSP1auq69gkn:1726028380) ([raw file](https://github.com/dgraph-io/dgraph/blob/8628695e8a562976dc0a1c1e9045080d435cce71/README.md#L73)):*
> ```Markdown
> ```
> $ mkdir /dgraph/m # Ensure mutations directory exists.
> $ server --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u
> ```

The executable is actually called dgraph now. Maybe you have an older version of the code (v0.3 might still call it server).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/119)*

**Comment by nii236** [comment]
Thanks for getting back to me! The actual docker image is a month old, which is what those instructions are referring to.

So I guess at this point we either need to update the readme to match what is on Docker hub, or update the Docker image so that the readme is correct.

**Comment by manishrjain** [comment]
Docker image is built from master tag v0.3. So, you could check out that version of README to get the right names of the binaries.

This particular README shows the latest updates to master. While this is confusing, this is the right behavior​.

We do have a discussion about potentially switching to git flow model. That might help with situations like these.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/119#-:-KL3SruSbpfQo4QYSR9P:1538186913)*

**Comment by nii236** [comment]
Makes sense, thank you!

**Pull request closed without merging**
