### PR TITLE
#362: Multiple values in posting lists - partial 

### PR DESCRIPTION
**Pull request by tzdybal**
Part of changes required to enable multiple values in posting lists.

- Lang is added to Posting, DirectedEdge and NQuad
- helper functions to determine Posting/DirectedEdge type (UID/value) instead of relying on ObjectID/ValueId
- small amendments in tests

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/540)

### CODE REVIEW

**Comment by manishrjain** [comment]
Looks really well written and clean. Let's have a chat today about this PR. Ping me when you're available.

---

Reviewed 13 of 13 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[posting/list.go, line 312 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbgxfy9MPN9-v4FO5jh:-Kbgxfy9MPN9-v4FO5ji:bfy62z3) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/posting/list.go#L312)):*
> ```Go
> const (
> 	valueEmpty    valueTypeInfo = iota
> 	valueUid      valueTypeInfo = iota
> ```

The rest don't need to have iota in them.

---

*[posting/list.go, line 318 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbgy5dJJ5qx1PtTh5W5:-Kbgy5dK05rtXOarMdxZ:b-o9cbuv) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/posting/list.go#L318)):*
> ```Go
> 
> func edgeType(t *task.DirectedEdge) valueTypeInfo {
> 	if !bytes.Equal(t.Value, nil) {
> ```

This can be better represented as a switch-case.

---

*[posting/list.go, line 333 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbgyDdresO9g4OneL-f:-KbgyDdresO9g4OneL-g:b-c0c2eu) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/posting/list.go#L333)):*
> ```Go
> }
> 
> func postingType(p *types.Posting) valueTypeInfo {
> ```

Do we have to call this for every posting? If so, it's better to store this information in the Posting message itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-:-Kbgyt4FyEfn8FAGXgqR:b8oawzh)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/state.go, line 317 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbhegj0DQV4mtASb_Hk:-Kbhegj1sfTWLlImG-Xc:bmc3a3f) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/gql/state.go#L317)):*
> ```Go
> 		l.Emit(itemName)
> 
> 		if r == leftRound {
> ```

I think we shouldn't be doing this special handling here. We should just emit the itemName and the parser would check if it's a valid directive or not. No need for the buffer. Though unrealted to this PR, it came up during the review. Would be nice if this can be refactored!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/540)*

**Comment by tzdybal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 318 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbgy5dJJ5qx1PtTh5W5:-KbiyUHln93mP6RBoXtC:b-faqzq7) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/posting/list.go#L318)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This can be better represented as a switch-case.
</blockquote></details>

Do you mean something like this?

    hasVal := !bytes.Equal(t.Value, nil)
    hasId := t.ValueId != 0
    switch {
    case hasVal && hasId:
        return valueTagged
    case hasVal && !hasId:
        return valueUntagged
    case !hasVal && hasId:
        return valueUid
    case !hasVal && !hasId:
        return valueEmpty
    }

---

*[posting/list.go, line 333 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbgyDdresO9g4OneL-f:-KbizY9YgtZ8kBZ3cbyI:bdx8qf2) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/posting/list.go#L333)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do we have to call this for every posting? If so, it's better to store this information in the Posting message itself.
</blockquote></details>

As discussed during VC, I'll focus on this during my later work. This will be refactored in next PRs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/540)*

**Comment by tzdybal** [comment]
Review status: 14 of 17 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/state.go, line 317 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbhegj0DQV4mtASb_Hk:-KbjrZ_RV6FV7OO4g6t3:bz8tyt3) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/gql/state.go#L317)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I think we shouldn't be doing this special handling here. We should just emit the itemName and the parser would check if it's a valid directive or not. No need for the buffer. Though unrealted to this PR, it came up during the review. Would be nice if this can be refactored!
</blockquote></details>

Created an issue for this refactoring - #547. Moreover @jchiu0 is working on lexer refactoring, so I would like to wait for his results, and then fix the directive related code if necessary.

---

*[posting/list.go, line 312 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbgxfy9MPN9-v4FO5jh:-Kbj-SYZFUz239Gv6MN7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8a662189716b5b80aef397758edaea1ff242662b/posting/list.go#L312)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The rest don't need to have iota in them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/540)*

**Comment by manishrjain** [comment]
:lgtm: Awesome work! Have a few comments, address them and then submit.

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[gql/state_test.go, line 161 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmfqLdFr5cBvrX-4ZM:-KbmfqLe1wanb9xjZcCN:b1o9aln) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/gql/state_test.go#L161)):*
> ```Go
> 	input := `
> 	query {
> 		me(_xid_: test) {
> ```

me(id: test). We no longer do _xid_.

---

*[gql/state_test.go, line 178 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbmfs_JVNPrqaLeIerr:-Kbmfs_JVNPrqaLeIers:b-yq3bu8) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/gql/state_test.go#L178)):*
> ```Go
> 	input := `
> 	query {
> 		me(_xid_: test) {
> ```

and here.

---

*[posting/list.go, line 311 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbmg1p3CLFQq-lyL2q8:-Kbmg1p3CLFQq-lyL2q9:bn0jshf) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/posting/list.go#L311)):*
> ```Go
> 
> const (
> 	valueEmpty valueTypeInfo = iota
> ```

Explain in a comment what each of these mean.

---

*[task/task.proto, line 92 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmgQeFeCaq77pfBSz4:-KbmgQeFeCaq77pfBSz5:bxybbol) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/task/task.proto#L92)):*
> ```protobuf
> 	fixed64 value_id = 5;   // Object or destination node / UID.
> 	string label = 6;
> 	string lang = 8;
> ```

Make this 7. Don't worry about backwards compatibility for now.

---

*[task/task.proto, line 97 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmgUhUZEfpkPz2sjtA:-KbmgUhUZEfpkPz2sjtB:bt2twrv) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/task/task.proto#L97)):*
> ```protobuf
> 		DEL = 1;
> 	}
> 	Op op = 7;
> ```

Make this 8.

---

*[types/types.proto, line 21 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmgWZNtobZlge_LqlQ:-KbmgWZNtobZlge_LqlR:bjw9s6u) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/types/types.proto#L21)):*
> ```protobuf
> 	}
> 	ValType val_type = 3;
> 	string lang = 6;
> ```

Keep them sorted in the order of the numbers. Also, don't worry about backwards compatibility.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-:-Kbmgcv5E4ssYQi8gQuA:bqo70fd)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 10 of 13 files at r1, 3 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-:-Kbm_6NtC7SgG2mcCaNv:bnfp4nl)*

**Comment by tzdybal** [comment]
Review status: 11 of 17 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/state_test.go, line 161 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmfqLdFr5cBvrX-4ZM:-KbmwNgdQ3B2KPbOooQg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/gql/state_test.go#L161)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

me(id: test). We no longer do _xid_.
</blockquote></details>

Done.

---

*[gql/state_test.go, line 178 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbmfs_JVNPrqaLeIerr:-KbmwP3uN2s23GiG28Eu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/gql/state_test.go#L178)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

and here.
</blockquote></details>

Done.

---

*[posting/list.go, line 311 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-Kbmg1p3CLFQq-lyL2q8:-KbmwS7swJlP9ZUYy3hp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/posting/list.go#L311)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Explain in a comment what each of these mean.
</blockquote></details>

Done.

---

*[task/task.proto, line 92 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmgQeFeCaq77pfBSz4:-KbmwglJI1f6y7QQgitW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/task/task.proto#L92)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this 7. Don't worry about backwards compatibility for now.
</blockquote></details>

Done.

---

*[task/task.proto, line 97 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmgUhUZEfpkPz2sjtA:-KbmwXY0Ux5WRH7Irca2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/task/task.proto#L97)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this 8.
</blockquote></details>

Done.

---

*[types/types.proto, line 21 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/540#-KbmgWZNtobZlge_LqlQ:-KbmwZH4FoHX_ro-OIPn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bba941e32d73ac2f74e0f85cb2046d365c9b6d3/types/types.proto#L21)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Keep them sorted in the order of the numbers. Also, don't worry about backwards compatibility.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/540)*

**Pull request closed without merging**
