### PR TITLE
Determine variable transformations dynamically

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/907)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[gql/parser.go, line 1953 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfb6AJopnsjH8ueN-M:-Kjfb6AKlGwaV-NytZg6:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/gql/parser.go#L1953)):*
> ```Go
> 				} else {
> 					if it.Item().Val != "var" {
> 						return x.Errorf("Only variables allowed in aggregate functions. Got: %v", it.Item().Val)
> ```

100 chars

---

*[query/math.go, line 199 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfb7_b7fBDkqggjz-U:-Kjfb7_b7fBDkqggjz-V:b-hfpv23) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/math.go#L199)):*
> ```Go
> 		return nil
> 	}
> 	fmt.Println(mNode.Val, mNode.Var, "$$$")
> ```

remove.

---

*[query/math.go, line 204 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfbTy_j3gV0KgwpNTJ:-KjfbTyaUQutVUqJ3h00:b-plc0vg) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/math.go#L204)):*
> ```Go
> 			return x.Errorf("Variable %v not yet populated or missing.", mNode.Var)
> 		}
> 		return nil
> ```

Add a comment about the return here.

---

*[query/query.go, line 891 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjffukCtSk57hulpg_s:-KjffukCtSk57hulpg_t:byhd71p) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L891)):*
> ```Go
> }
> 
> type values struct {
> ```

`type varValue struct { .. }`.

`doneVars: map[string]varValue`

---

*[query/query.go, line 895 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfgLcr60WIBxp6Wh25:-KjfgLcr60WIBxp6Wh26:b-3soph) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L895)):*
> ```Go
> 	vals    map[uint64]types.Val
> 	path    []*SubGraph // This stores the subgraph path from root to var definition.
> 	strList []*protos.TaskValue
> ```

Add a TODO here to take a look at this. Most likely, this isn't required.

---

*[query/query.go, line 943 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfbXtC1iYwihbEiJeD:-KjfbXtC1iYwihbEiJeE:b-4mzm5) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L943)):*
> ```Go
> }
> 
> func recurse(node *gql.MathTree, doneVars map[string]values, nodeList *[]*gql.MathTree) (int, string, error) {
> ```

100 chars. Simplify the function signature. Also, make these funcs part of `mt`.

None of the output is required. The output would be a nodelist. Also don't need doneVars.

---

*[query/query.go, line 967 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjffcuTXotsGGWiXsTO:-KjffcuTXotsGGWiXsTP:b-5vl1wy) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L967)):*
> ```Go
> }
> 
> func transformMap(fromNode, toNode values) (map[uint64]types.Val, error) {
> ```

Attach this function to fromNode struct.

Transform(toNode values)

---

*[query/query.go, line 974 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfgoH0w_oD3Kpwmmpo:-KjfgoH0w_oD3Kpwmmpp:b-wtkaob) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L974)):*
> ```Go
> 	if len(fromNode.path) == len(toNode.path) {
> 		if len(toNode.path) != 0 &&
> 			fromNode.path[len(fromNode.path)-1] != toNode.path[len(toNode.path)-1] {
> ```

Check all nodes. Do this check first, before creating a newMap.

---

*[query/query.go, line 979 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfh4sNQFdiPxNCYj5J:-Kjfh4sNQFdiPxNCYj5K:b32vlw) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L979)):*
>=

---

*[query/query.go, line 985 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfh6VmtAcxyZKq5PzZ:-Kjfh6VmtAcxyZKq5Pz_:b-k8bp3x) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L985)):*
> ```Go
> 			return nil, x.Errorf("Invalid combination of variables in math")
> 		}
> 	}
> ```

if len() == len() { return fromNode.vals } // Even this is not required.

`newMap = fromNode.vals`

---

*[query/query.go, line 1025 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfjw-wd2XWh7YKCPBa:-Kjfjw-wd2XWh7YKCPBb:b-958nt2) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L1025)):*
> ```Go
> 	}
> 	maxNode := doneVars[maxVar]
> 	for _, node := range nodeList {
> ```

for _, mvar := range varList { ... }

// Don't call anything node.

---

*[query/query.go, line 1261 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfkUO01KnLYQJCMk0u:-KjfkUO1fTIfpvXz_A0x:b-1o7nxb) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L1261)):*
> ```Go
> }
> 
> func populateVarMap(sg *SubGraph, doneVars map[string]values, isCascade bool,
> ```

Define this on subgraph.

---

*[query/query.go, line 1404 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfnbnQoaMtlggA-7TD:-KjfnbnQoaMtlggA-7TE:b-732j8i) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L1404)):*
> ```Go
> 		// Note: We ignore the facets if its a value edge as we can't
> 		// attach the value to any node.
> 		for i, uids := range sg.uidMatrix {
> ```

Move this out to a separate function on sg.

---

*[query/query_test.go, line 436 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfoMaWKbWh1u7m2Vzv:-KjfoMaXXzwjJf-WauJd:b-81tlki) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query_test.go#L436)):*
> ```Go
> 			friend(id: 1) {
> 				a as age
> 				path @facets(L1 as weight) {
> ```

`path @facets(L1 as weight) { friend { L2 as math(a + L1) } }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/907)*

**Comment by ashwin95r** [comment]
Review status: 1 of 5 files reviewed at latest revision, 14 unresolved discussions.

---

*[gql/parser.go, line 1953 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfb6AJopnsjH8ueN-M:-KjjaosSPihF1_DdHtIJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/gql/parser.go#L1953)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.

---

*[query/math.go, line 199 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfb7_b7fBDkqggjz-U:-Kjfrvz3J0HGQz4NxbFN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/math.go#L199)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

---

*[query/math.go, line 204 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfbTy_j3gV0KgwpNTJ:-KjfsD_qQCA-H4QY7B-n:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/math.go#L204)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment about the return here.
</blockquote></details>

Done.

---

*[query/query.go, line 891 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjffukCtSk57hulpg_s:-Kjfsrlf8DYg7eF0ZHfo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L891)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`type varValue struct { .. }`.

`doneVars: map[string]varValue`
</blockquote></details>

Done.

---

*[query/query.go, line 895 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfgLcr60WIBxp6Wh25:-Kjft0GxnMhXO1PuIUJw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L895)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a TODO here to take a look at this. Most likely, this isn't required.
</blockquote></details>

Done.

---

*[query/query.go, line 943 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfbXtC1iYwihbEiJeD:-Kjjaq-uShqD0CAHLe8u:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L943)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars. Simplify the function signature. Also, make these funcs part of `mt`.

None of the output is required. The output would be a nodelist. Also don't need doneVars.
</blockquote></details>

Done.

---

*[query/query.go, line 967 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjffcuTXotsGGWiXsTO:-Kjjb0VsG1EIZJ0WgEcm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L967)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Attach this function to fromNode struct.

Transform(toNode values)
</blockquote></details>

Done.

---

*[query/query.go, line 974 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfgoH0w_oD3Kpwmmpo:-KjjbuXyhgsxTnJw-pan:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L974)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check all nodes. Do this check first, before creating a newMap.
</blockquote></details>

Done.

---

*[query/query.go, line 979 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfh4sNQFdiPxNCYj5J:-KjjbvFboNbbYzY3i1kZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L979)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

>=
</blockquote></details>

Done.

---

*[query/query.go, line 985 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfh6VmtAcxyZKq5PzZ:-KjjbNn94jJbqz7uhB_5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L985)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if len() == len() { return fromNode.vals } // Even this is not required.

`newMap = fromNode.vals`
</blockquote></details>

Done.

---

*[query/query.go, line 1025 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-Kjfjw-wd2XWh7YKCPBa:-KjjaZ6S7OiJ-Abk4iBe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L1025)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

for _, mvar := range varList { ... }

// Don't call anything node.
</blockquote></details>

Done.

---

*[query/query.go, line 1261 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfkUO01KnLYQJCMk0u:-KjftJo38pkIeDilOc8L:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L1261)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Define this on subgraph.
</blockquote></details>

Done.

---

*[query/query.go, line 1404 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjfnbnQoaMtlggA-7TD:-KjfurmJgll0B7pAegsK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8175880d28129fd910eff54681ca391213df8822/query/query.go#L1404)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this out to a separate function on sg.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/907)*

**Comment by manishrjain** [comment]
LGTM

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[query/math.go, line 11 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmFVXj_BWEBytxVep:-KjjmFVXj_BWEBytxVeq:b-b411ym) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/math.go#L11)):*
> ```Go
> 	Fn    string
> 	Var   string
> 	Const types.Val
> ```

Add a comment.

---

*[query/query.go, line 537 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmMX5B6Vy-YpB0G1B:-KjjmMX5B6Vy-YpB0G1C:b-q0dak0) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L537)):*
> ```Go
> }
> 
> func mathCopy(mnode *mathTree, mt *gql.MathTree) error {
> ```

dst, src

---

*[query/query.go, line 967 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmoWHIGTj5yQNQepa:-KjjmoWHIGTj5yQNQepb:b-9osou1) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L967)):*
> ```Go
> }
> 
> func (mt *mathTree) recurse() []*mathTree {
> ```

extractVarNodes()

---

*[query/query.go, line 979 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmyQ2jRA7Qajmf64o:-KjjmyQ2jRA7Qajmf64p:bmembdx) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L979)):*
> ```Go
> }
> 
> func (fromNode *varValue) transformMap(toNode varValue) (map[uint64]types.Val, error) {
> ```

Add a comment. What does it mean to "transformMap". Actually call it `transformTo`.

---

*[query/query.go, line 1023 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjnPtsbkarBWD1gpkL:-KjjnPtsbkarBWD1gpkM:bhbzs7m) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L1023)):*
> ```Go
> }
> 
> func transformVars(mNode *mathTree, doneVars map[string]varValue) error {
> ```

Add a comment what does it mean to "transformVars".

---

*[query/query.go, line 1043 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjnoJr4250_L1J42Yt:-KjjnoJr4250_L1J42Yu:b-p3vz0r) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L1043)):*
> ```Go
> 		mt := mvarList[i]
> 		curNode := doneVars[mt.Var]
> 		newMap, err := curNode.transformMap(maxNode)
> ```

curNode.transformTo(maxNode)

---

*[query/query.go, line 1347 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjpHEBaizN8aGt9leC:-KjjpHEBaizN8aGt9leD:b-bw31pt) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L1347)):*
> ```Go
> 		return nil
> 	}
> ```

Copy the sgPath, so it is immutable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-:-KjjwH7QigzlG4ApWVIo:bb6ywmx)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[query/math.go, line 11 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmFVXj_BWEBytxVep:-KjjyYBE9RMHf2uTA6TJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/math.go#L11)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment.
</blockquote></details>

Done.

---

*[query/query.go, line 537 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmMX5B6Vy-YpB0G1B:-Kjjy-yRsws-umC1ZJds:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L537)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

dst, src
</blockquote></details>

Done.

---

*[query/query.go, line 967 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmoWHIGTj5yQNQepa:-KjjyGh-cuUHVo7Jtl6r:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L967)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

extractVarNodes()
</blockquote></details>

Done.

---

*[query/query.go, line 979 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjmyQ2jRA7Qajmf64o:-KjjymJAx6P7CaI6E8-p:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L979)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment. What does it mean to "transformMap". Actually call it `transformTo`.
</blockquote></details>

Done.

---

*[query/query.go, line 1023 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjnPtsbkarBWD1gpkL:-Kjjz9U_ebUPlUiG6q7x:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L1023)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment what does it mean to "transformVars".
</blockquote></details>

Done.

---

*[query/query.go, line 1043 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjnoJr4250_L1J42Yt:-KjjyPItLFzUtivdrWaD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L1043)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

curNode.transformTo(maxNode)
</blockquote></details>

Done.

---

*[query/query.go, line 1347 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-KjjpHEBaizN8aGt9leC:-KjjzxeQPlLnTvuCdzyf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/14de119557c8d5b7c4ccad443fbd1fcbc2aca085/query/query.go#L1347)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Copy the sgPath, so it is immutable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/907)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 3 files at r2, 2 of 5 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/907#-:-KjkBJ6B7hEIpZ-Ux9ha:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
