### PR TITLE
feat(multi-tenancy): add support for multi-tenancy in live loader

### PR DESCRIPTION
**Pull request by NamanJain8**
Makes live-loader work with multi-tenancy.
- Adds a flag `namespace` which complements the flags `user` and `password`, used by ACL
- Adds a flag `force-namespace` which allows the guardian of the galaxy to load data into other namespaces.

- User from guardian of galaxy group can load the data into any namespace.
- Other users can only insert data into the namespace they have access to. They have to specify it via the `namespace` flag.

The `--upsertPredicate` flag only works when loading the data into a namespace you logged into.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7414)

### CODE REVIEW

**Review by ahsanbarkati — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7414)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @manishrjain, @NamanJain8, @pawanrawal, and @vvbalaji-dgraph)

___
*[x/x.go, line 1074 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MT64R8I8onWuD2b-3t1:-MT64R8I8onWuD2b-3t2:by8vr4h) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6273d5644bad159627e6cb2141c509cd22fdb52/x/x.go#L1074)):*
> ```Go
> 	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
> 	defer cancel()
> 	//TODO(Ahsan): What should be the namespace here?
> ```

Remove this TODO

**Review by manishrjain — APPROVED** [review]
:lgtm: Defer to @jarifibrahim for final approval.

> Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-:-MT6Isat4JuIAQnKZ3BJ:bhwknda)* status: all files reviewed, 2 unresolved discussions (waiting on @NamanJain8, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/live/run.go, line 175 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MT6IHca5myuFy5jZ24B:-MT6IHca5myuFy5jZ24C:bdunv95) ([raw file](https://github.com/dgraph-io/dgraph/blob/92817618cf2f8414a3d628bcfd238ca353056c7a/dgraph/cmd/live/run.go#L175)):*
> ```Go
> 		"be used to store blank nodes as an xid")
> 	flag.String("tmp", "t", "Directory to store temporary buffers.")
> 	flag.Uint64("force-namespace", math.MaxUint64,
> ```

Use Super Flags here for namespace, user, password, force as well.

**Review by jarifibrahim — APPROVED** [review]
:lgtm:  Got some questions.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-:-MTAp3z0Ax8AB2LnJaCv:bhbnd54)* status: 12 of 13 files reviewed, 10 unresolved discussions (waiting on @NamanJain8, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/live/run.go, line 472 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAnhjN4ZPJj8MCG8Ms:-MTAnhjN4ZPJj8MCG8Mt:bi64ulk) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/dgraph/cmd/live/run.go#L472)):*
> ```Go
> 				// Sorts the nquads on basis of their predicates, while keeping the
> 				// predicates with count index later than those without it.
> 				// TODO(Naman): Why do we keep count indexes later?
> ```

This can be removed now.
___
*[dgraph/cmd/live/run.go, line 505 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAnmMV0KlJCZV1Nyjo:-MTAnmMV0KlJCZV1Nyjp:b-feoxmb) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/dgraph/cmd/live/run.go#L505)):*
> ```Go
> 				l.allocateUids(nqs)
> 			} else {
> 				// TODO(Naman): Handle this. Upserts UIDs send a single upsert block for multiple
> ```

I don't see anything that would prevent this from running in multiple-namespaces mode. Don't you need to add a check somewhere?
___
*[edgraph/access_ee.go, line 1043 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAo9Qi8beDYX61-Rcw:-MTAo9Qi8beDYX61-Rcx:b-swgqis) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/edgraph/access_ee.go#L1043)):*
> ```Go
> 
> func AuthGuardianOfTheGalaxy(ctx context.Context) error {
> 	if !x.WorkerConfig.AclEnabled {
> ```

Don't you want to return an error if ACL is disabled and this function is called?
___
*[query/mutation.go, line 67 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAobKQC-AVFjAOGn0K:-MTAobKQC-AVFjAOGn0L:b-htt6j5) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/query/mutation.go#L67)):*
> ```Go
> 	// Reset the namespace to the original.
> 	defer func(ns uint64) {
> 		x.AttachNamespace(ctx, ns)
> ```

why do you need to do this? we've only read the namespace from the context, not deleted it.
___
*[query/query.go, line 2881 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAojza-ymbDTjR7TVW:-MTAojzb1_XAU0ZcQoVn:blzmbhm) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/query/query.go#L2881)):*
> ```Go
> 		typeNamespace, typeName := x.ParseNamespaceAttr(update.TypeName)
> 		if typeNamespace != namespace {
> 			continue
> ```

Should we log an error here?
___
*[query/query.go, line 2904 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAomKNA8SVh_gK1x5X:-MTAomKNA8SVh_gK1x5Y:blzmbhm) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/query/query.go#L2904)):*
> ```Go
> 		nodeNamespace, attrName := x.ParseNamespaceAttr(node.Predicate)
> 		if nodeNamespace != namespace {
> 			continue
> ```

Should we log an error here?
___
*[x/x.go, line 288 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAotRu7s6KBoHg92VG:-MTAotRu7s6KBoHg92VH:bsp77ld) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/x/x.go#L288)):*
> ```Go
> 	}
> 	ns := md.Get("galaxy-operation")
> 	return len(ns) > 0 && ns[0] == "true"
> ```

We should check for `True` as well.
___
*[x/x.go, line 457 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAp0Iy9gIGGJE3hOYo:-MTAp0IzBQN6J5PncimN:bmdt86s) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/x/x.go#L457)):*
> ```Go
> 	}
> 	md.Set("galaxy-operation", "true")
> 	ctx = metadata.NewOutgoingContext(ctx, md)
> ```

return metadata...

**Review by NamanJain8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7414)* status: 10 of 13 files reviewed, 10 unresolved discussions (waiting on @ahsanbarkati, @jarifibrahim, @manishrjain, @NamanJain8, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/live/run.go, line 472 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAnhjN4ZPJj8MCG8Ms:-MTB3kI8674PD25gQMDx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/dgraph/cmd/live/run.go#L472)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

This can be removed now.
</blockquote></details>

Done.
___
*[dgraph/cmd/live/run.go, line 505 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAnmMV0KlJCZV1Nyjo:-MTB3la14E3uzDdYezEy:b-hcin7i) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/dgraph/cmd/live/run.go#L505)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

I don't see anything that would prevent this from running in multiple-namespaces mode. Don't you need to add a check somewhere?
</blockquote></details>

Added that.
___
*[edgraph/access_ee.go, line 1043 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAo9Qi8beDYX61-Rcw:-MTB3oeDE1EyGI2e7RV4:b-u3hh3y) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/edgraph/access_ee.go#L1043)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Don't you want to return an error if ACL is disabled and this function is called?
</blockquote></details>

This function is also called from non-ACL part of code(Dropall etc), so we should not return an error here.
We can move this check over there I think.
___
*[query/mutation.go, line 67 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAobKQC-AVFjAOGn0K:-MTB4BTwBsquBlyIEbM1:bfmsyhg) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/query/mutation.go#L67)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

why do you need to do this? we've only read the namespace from the context, not deleted it.
</blockquote></details>

We are modifying the context to execute the query in the context of edge few lines below. So, we should reset it here as well.
___
*[query/query.go, line 2881 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAojza-ymbDTjR7TVW:-MTB4Rxb0kT6cg_mmhKN:b-by1ffl) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/query/query.go#L2881)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Should we log an error here?
</blockquote></details>

No. Dgraph fetches the entire schema and then filter out the predicates of the required namespace. So, this is expected and is not an error.
___
*[query/query.go, line 2904 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAomKNA8SVh_gK1x5X:-MTB4iPW2gBHxFXw1y86:b-s3hmk9) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/query/query.go#L2904)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Should we log an error here?
</blockquote></details>

Not needed.
___
*[x/x.go, line 1074 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MT64R8I8onWuD2b-3t1:-MTB4mxmDLTTr1w4ux02:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d6273d5644bad159627e6cb2141c509cd22fdb52/x/x.go#L1074)):*
<details><summary><i>Previously, ahsanbarkati (Ahsan Barkati) wrote…</i></summary><blockquote>

Remove this TODO
</blockquote></details>

Done.
___
*[x/x.go, line 288 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAotRu7s6KBoHg92VG:-MTB4kGy8wM6lmfcR1bI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/x/x.go#L288)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

We should check for `True` as well.
</blockquote></details>

Done.
___
*[x/x.go, line 457 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MTAp0Iy9gIGGJE3hOYo:-MTB4mKM1oZGVWUlJsil:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1884ea203a8cdf372b536337b3513af1e5f4cdea/x/x.go#L457)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

return metadata...
</blockquote></details>

Done.

**Review by NamanJain8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7414)* status: 10 of 15 files reviewed, 10 unresolved discussions (waiting on @ahsanbarkati, @jarifibrahim, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/live/run.go, line 175 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7414#-MT6IHca5myuFy5jZ24B:-MTEn5Sy5m2SLjjdgri8:b-eilirj) ([raw file](https://github.com/dgraph-io/dgraph/blob/92817618cf2f8414a3d628bcfd238ca353056c7a/dgraph/cmd/live/run.go#L175)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Use Super Flags here for namespace, user, password, force as well.
</blockquote></details>

I have combined user, password and namespace as they are the login credentials. `--force-namespace` is an unrelated flag.

**Pull request merged**
