### PR TITLE
Adopt Go Modules

### PR DESCRIPTION
**Pull request by mangalaman93**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4146)

### CODE REVIEW

**Comment by adg** [comment]
This change appears to be bad.

The `go.sum` file contains at least one entry that differs to the actual hash of the content.

To reproduce:

```
$ git clone https://github.com/dgraph-io/dgraph
$ cd dgraph/chunker
$ go test
go: downloading go.etcd.io/etcd v0.0.0-20190228193606-a943ad0ee4c9
go: downloading github.com/dgraph-io/ristretto v0.0.0-20190903064322-eb48d2f7ca30
verifying github.com/dgraph-io/ristretto@v0.0.0-20190903064322-eb48d2f7ca30: checksum mismatch
	downloaded: h1:2ymRTEtPu60vzv+YTIHHlJ3713Bl3G/MPc2BOc/OkzM=
	go.sum:     h1:FkdGlqxPjfHKdVUzS5dOSMeOkGjEG7PnR1RLbcEqw88=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by adg** [comment]
(And it appears deepsource concurs: https://deepsource.io/gh/dgraph-io/dgraph/run/b952d01d-80d8-4aa3-a01b-e350765e4b7f/#go)

**Comment by mangalaman93** [comment]
@adg thanks for pointing out. Fixed in https://github.com/dgraph-io/dgraph/pull/4153

**Comment by lolcoolkat** [comment]
@mangalaman93 @campoy I've updated my Dgraph version to `master`, but i'm still getting the error.

```
github.com/dgraph-io/dgraph/protos/pb
../../../go/pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191010194828-771f1589e129/protos/pb/pb.pb.go:7146:29: m.Kv[iNdEx].MarshalToSizedBuffer undefined (type *pb.KV has no field or method MarshalToSizedBuffer)
../../../go/pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191010194828-771f1589e129/protos/pb/pb.pb.go:7209:29: m.Kv[iNdEx].MarshalToSizedBuffer undefined (type *pb.KV has no field or method MarshalToSizedBuffer)
```

Any ideas?

**Comment by mangalaman93** [comment]
Could you check if you had the `protos/pb/pb.go` file unmodified? We have seen this issue before and it happens when `protos/pb/pb.go` is generated using an old version of go-protobuf.

**Comment by lolcoolkat** [comment]
I see `api "github.com/dgraph-io/dgo/v2/protos/api"` in the /pb/pb.go file.. does that mean it's updated?

**Comment by mangalaman93** [comment]
Check whether the file that you have locally is same as the on in master branch.

**Comment by lolcoolkat** [comment]
I've confirmed that my `pb/pb.pb.go` file is the same that's on the master branch @mangalaman93 Can you verify for me once on your end.. and see if you can replicate my issue from a fresh install of Dgraph?

**Comment by lolcoolkat** [comment]
@mangalaman93 https://github.com/dgraph-io/dgraph/blob/0c7d1b4774f73fe5bee9fdc274c2e73247fba45c/protos/Makefile#L19

Should this be `PROTO_PATH := ${PROTO_PATH}:${GOPATH}/src/github.com/dgraph-io/dgo/v2/protos` instead?

**Comment by mangalaman93** [comment]
I think we assume that GOPATH is defined, we need to fix this. I think @adg has already created GitHub issues for this. May be, it is using dgo in GOPATH that has older version. I will look into it when I get a chance.

**Comment by lolcoolkat** [comment]
Thank you @mangalaman93 Hope we can get this fixed soon.. really want to start using Go modules with Dgraph soon!

**Pull request merged**
