### PR TITLE
Force move a predicate aborting pending transactions.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2215)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Somehow transactions that return an error while predicate move is happening are not aborted. Hence, after the move, we get these errors. I am investigating, why they are not getting aborted. 

```
2018/03/13 10:51:21 draft.go:653: Couldn't take snapshot, txn watermark: [2140], applied watermark: [4188]
2018/03/13 10:51:51 draft.go:653: Couldn't take snapshot, txn watermark: [2140], applied watermark: [4188]
2018/03/13 10:52:21 draft.go:653: Couldn't take snapshot, txn watermark: [2140], applied watermark: [4188]
2018/03/13 10:52:51 draft.go:653: Couldn't take snapshot, txn watermark: [2140], applied watermark: [4188]
2018/03/13 10:53:21 draft.go:653: Couldn't take snapshot, txn watermark: [2140], applied watermark: [4188]
```

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/scheduler.go, line 177 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2215#-L7RpJZKzVVdtJephhm4:-L7RpJZKzVVdtJephhm5:bmj8n37) ([raw file](https://github.com/dgraph-io/dgraph/blob/51023570134a8b2cc034ca8481c167ed7225c401/worker/scheduler.go#L177)):*
> ```Go
> 	for _, edge := range proposal.Mutations.Edges {
> 		if tablet := groups().Tablet(edge.Attr); tablet != nil && tablet.ReadOnly {
> 			posting.TxnMarks().Done(index)
> ```

The snapshot error message was because TxnMarks were not marked as done. Also, since PutOrMerge is called below, they would never be added to the map and even if the client calls abort, the server won't find the transaction in the map.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2215)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/scheduler.go, line 177 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2215#-L7RpJZKzVVdtJephhm4:-L7RyAk74818atJtdSsc:bmta6lf) ([raw file](https://github.com/dgraph-io/dgraph/blob/51023570134a8b2cc034ca8481c167ed7225c401/worker/scheduler.go#L177)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The snapshot error message was because TxnMarks were not marked as done. Also, since PutOrMerge is called below, they would never be added to the map and even if the client calls abort, the server won't find the transaction in the map.
</blockquote></details>

Ignore comment above, we just add it to the map now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2215)*

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/scheduler.go, line 177 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2215#-L7RpJZKzVVdtJephhm4:-L7STpzVsKAKByi7KKZ5:b-twe7u0) ([raw file](https://github.com/dgraph-io/dgraph/blob/51023570134a8b2cc034ca8481c167ed7225c401/worker/scheduler.go#L177)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Ignore comment above, we just add it to the map now.
</blockquote></details>

Ok. I'm missing a bit of context here. So, I'll let @janardhan1993 review this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2215)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2215#-:-L7SudHxTXAzLUj5Fhgj:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master with 82abcd419eb7ffc3e4e91b8be29a02ce090df269.

**Pull request closed without merging**
