### PR TITLE
Move to go 1.8

### PR DESCRIPTION
**Pull request by ashishnegi**
Dgraph will not compile with go 1.7 after this is merged to master.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/665)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Since, we have custom swap functions.. we can not replace all instances of sort.Sort over slices with sort.Slice..
for e.g.
```
func (s sortBase) Swap(i, j int) {
    s.values[i], s.values[j] = s.values[j], s.values[i]
    data := s.ul
    algo.Swap(data, i, j)
}
```
sort.Slice will not be able to swap like this.
we only give `Less` fn to sort.Slice

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-:-KeX1jy8AcxqH1ud91bj:beelrgk)*

**Comment by pawanrawal** [comment]
Sorry didn't see this comment.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 714 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-KeX2cIjk-vPPGkkoPFF:-KeX2cIkF3pTCW-6bEBr:b-1uw3tr) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fcf686218fd032ae5c765e9ef079d45399fd4d5/cmd/dgraph/main.go#L714)):*
> ```Go
> 		ReadTimeout:  10 * time.Second,
> 		WriteTimeout: 600 * time.Second,
> 		// TODO(Ashwin): Add idle timeout while switching to Go 1.8.
> ```

@ashwin95r - Might want to do this now.

---

*[cmd/dgraph/main.go, line 719 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-KeX402nrobPYb6QZJWR:-KeX402nrobPYb6QZJWS:b-ayshjd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fcf686218fd032ae5c765e9ef079d45399fd4d5/cmd/dgraph/main.go#L719)):*
> ```Go
> 	err := srv.Serve(l)
> 	log.Printf("Stopped taking more http(s) requests. Err: %s", err.Error())
> 	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
> ```

Is there a reason behind chosing this as 2 minutes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-:-KeX49TGFljafSlyd-7j:b-d96pk)*

**Comment by ashishnegi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 719 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-KeX402nrobPYb6QZJWR:-KeXCEnvql2EBRETLhbF:b7bcqll) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fcf686218fd032ae5c765e9ef079d45399fd4d5/cmd/dgraph/main.go#L719)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Is there a reason behind chosing this as 2 minutes?
</blockquote></details>

No.
Should we keep high value for all requests to succeed ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/665)*

**Comment by ashwin95r** [comment]
uint64slice in algo/uidlist_test.go can also be removed. :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 714 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-KeX2cIjk-vPPGkkoPFF:-KeXVVDkVWjkGKx6UZ5u:b-vf8eao) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fcf686218fd032ae5c765e9ef079d45399fd4d5/cmd/dgraph/main.go#L714)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

@ashwin95r - Might want to do this now.
</blockquote></details>

Can we also set an IdealTimeout of 2 minutes?https://beta.golang.org/pkg/net/http/#IdleConnTimeout

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-:-KeXURUBT3WxWdaOupAL:bd0biwf)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 719 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-KeX402nrobPYb6QZJWR:-KeXcI6WveptT8w03rVr:b-nch78p) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fcf686218fd032ae5c765e9ef079d45399fd4d5/cmd/dgraph/main.go#L719)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

No.
Should we keep high value for all requests to succeed ?
</blockquote></details>

Actually, backup request would fail in this case. We have a 600 second write timeout. So we should keep this the same? And then anyway if requests are done before that server would be shutdown.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-:-KeXcf3I8Qzv19vRNoxO:bnfp4nl)*

**Comment by ashishnegi** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 714 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-KeX2cIjk-vPPGkkoPFF:-KeXvIlg68KufVKw0MfS:b-3gi8c8) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fcf686218fd032ae5c765e9ef079d45399fd4d5/cmd/dgraph/main.go#L714)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Can we also set an IdealTimeout of 2 minutes?https://beta.golang.org/pkg/net/http/#IdleConnTimeout
</blockquote></details>

i think it is idletimeout.. https://beta.golang.org/pkg/net/http/#Server
Done.

---

*[cmd/dgraph/main.go, line 719 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/665#-KeX402nrobPYb6QZJWR:-KeXvAYlCAHm6v4RddlO:blo4e5h) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fcf686218fd032ae5c765e9ef079d45399fd4d5/cmd/dgraph/main.go#L719)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Actually, backup request would fail in this case. We have a 600 second write timeout. So we should keep this the same? And then anyway if requests are done before that server would be shutdown.
</blockquote></details>

Done. Giving 630 seconds to finish requests. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/665)*

**Pull request closed without merging**
