### PR TITLE
Feature/auto-assign uid

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/198)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dgraph/main.go, line 165 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2cVC35yNOIagGlCxQ:-KR2cVC4KTY-yOiGeLYj:beayugl) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/cmd/dgraph/main.go#L165)):*
> ```Go
> 		return nil, fmt.Errorf("Unapplied mutations")
> 	}
> 	return allocIds, nil
> ```

This return can't be avoided as the map has to be returned to the user. Convert to edges map could be encoded into DirectedEdges, but that wouldn't be very clean I feel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by manishrjain** [comment]
Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/dgraph/main.go, line 216 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2aMrhWGPy6IL1Shff:-KR2aMrhWGPy6IL1Shfg:b-v5nwkm) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/cmd/dgraph/main.go#L216)):*
> ```Go
> 
> 	if gq == nil || (gq.UID == 0 && len(gq.XID) == 0) {
> 		x.SetStatus(w, x.ErrorOk, "Done", allocIds)
> ```

Instead of changing SetStatus just for this, return a json status back. Create one here.

---

*[query/graph/graphresponse.proto, line 37 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2aWhaS0J9BvQe2VYW:-KR2aWhaS0J9BvQe2VYX:b-w5oo0r) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/query/graph/graphresponse.proto#L37)):*
> ```protobuf
>   Node n = 1;
>   Latency l = 2;
> 	map<string, uint64> Uids = 3;
> ```

tabs vs spaces. Call it AssignedUids.

---

*[uid/assigner.go, line 219 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2b1N3WtE9raLGQuWG:-KR2b1N3WtE9raLGQuWH:b-m2vka7) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/uid/assigner.go#L219)):*
> ```Go
> 
> 	if strings.HasPrefix(xid, "_new_:") {
> 		return allocateUniqueUid(xid, instanceIdx, numInstances)
> ```

Generate a random xid here. Also add a comment about this special case handling.

http://stackoverflow.com/questions/22892120/how-to-generate-a-random-string-of-a-fixed-length-in-golang

Masking code seems interesting (not the improved). We could make it part of the new algo package.

---

*[x/x.go, line 50 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2d3wT3GQYnxVGLW0z:-KR2d3wT3GQYnxVGLW1-:b-vdzfoh) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/x/x.go#L50)):*
> ```Go
> 	Code    string            `json:"code"`
> 	Message string            `json:"message"`
> 	Uids    map[string]uint64 `json:"uids"`
> ```

This doesn't belong here. Status is very tiny for a good reason. What you need is a direct conversion to JSON.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by ashwin95r** [comment]
Review status: 2 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/dgraph/main.go, line 216 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2aMrhWGPy6IL1Shff:-KR2gP73-fJp2DqgPEKO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/cmd/dgraph/main.go#L216)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Instead of changing SetStatus just for this, return a json status back. Create one here.
</details>
Done.

---

*[query/graph/graphresponse.proto, line 37 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2aWhaS0J9BvQe2VYW:-KR2hTg6tCRsUAH0Yu08:b-n20tyq) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/query/graph/graphresponse.proto#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> tabs vs spaces. Call it AssignedUids.
</details>
Ah yeah, didnt have the `expandtab` in .vimrc. Done.

---

*[uid/assigner.go, line 219 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2b1N3WtE9raLGQuWG:-KR2jUVkLXyxSUInxWQk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/uid/assigner.go#L219)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Generate a random xid here. Also add a comment about this special case handling.
> 
> http://stackoverflow.com/questions/22892120/how-to-generate-a-random-string-of-a-fixed-length-in-golang
> 
> Masking code seems interesting (not the improved). We could make it part of the new algo package.
</details>
Done.

---

*[x/x.go, line 50 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2d3wT3GQYnxVGLW0z:-KR2h5i-P8xf93vxZnAM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/x/x.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This doesn't belong here. Status is very tiny for a good reason. What you need is a direct conversion to JSON.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by manishrjain** [comment]
Reviewed 5 of 6 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[algo/other.go, line 3 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2mX-WBKEC_6MTf37b:-KR2mX-WBKEC_6MTf37c:b-vrid7c) ([raw file](https://github.com/dgraph-io/dgraph/blob/727160e5a097b51ff97db9b6a091db53b8e38449/algo/other.go#L3)):*
> ```Go
> package algo
> 
> import "math/rand"
> ```

Use crypto rand.

---

*[cmd/dgraph/main.go, line 165 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2cVC35yNOIagGlCxQ:-KR2maCcv0qVCKvjsq-k:b32w0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/cmd/dgraph/main.go#L165)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> This return can't be avoided as the map has to be returned to the user. Convert to edges map could be encoded into DirectedEdges, but that wouldn't be very clean I feel.
</details>
OK

---

*[cmd/dgraph/main.go, line 225 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2n1R9Y1jxCM6Z0vH3:-KR2n1R9Y1jxCM6Z0vH4:b-llyhaf) ([raw file](https://github.com/dgraph-io/dgraph/blob/727160e5a097b51ff97db9b6a091db53b8e38449/cmd/dgraph/main.go#L225)):*
> ```Go
> 			w.Write(js)
> 		} else {
> 			x.SetStatus(w, "Error", "Unable to Mashal map")
> ```

marshal

---

*[cmd/dgraph/main.go, line 68 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3R-ru-JVKonha3Gvf:-KR3R-ru-JVKonha3Gvg:b-dq9xlt) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/cmd/dgraph/main.go#L68)):*
> ```Go
> )
> 
> type edgesStruct struct {
> ```

`mutationResult`

---

*[cmd/dgraph/main.go, line 70 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3R3JPp0rO0G5uRcTy:-KR3R3JPp0rO0G5uRcTz:b-4z5vb6) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/cmd/dgraph/main.go#L70)):*
> ```Go
> type edgesStruct struct {
> 	edges []x.DirectedEdge
> 	mp    map[string]uint64
> ```

newUids

---

*[cmd/dgraph/main.go, line 140 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3REOCeiPIfb3fhf6z:-KR3REOCeiPIfb3fhf7-:byu30ei) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/cmd/dgraph/main.go#L140)):*
> ```Go
> 
> 	edg = edgesStruct{
> 		edges,
> ```

Always a good idea to have the key also mentioned.

---

*[uid/assigner.go, line 145 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3RaUuVq7w8se8aPXm:-KR3RaUuVq7w8se8aPXn:b-bnhl28) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/uid/assigner.go#L145)):*
> ```Go
> 		// Uid hasn't been assigned yet.
> 		t := x.DirectedEdge{
> 			Value:     []byte(xid), // not txid
> ```

Actually, just realized that the random XID would be stored. So, instead move that part of the logic here and store `_new_` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[algo/other.go, line 3 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2mX-WBKEC_6MTf37b:-KR3Z4-n0EP8j_X0AaQE:bw6gm29) ([raw file](https://github.com/dgraph-io/dgraph/blob/727160e5a097b51ff97db9b6a091db53b8e38449/algo/other.go#L3)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Use crypto rand.
</details>
crypto/rand seems to be quite slow. Shall we stick to this with a seed based on time?

---

*[cmd/dgraph/main.go, line 165 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2cVC35yNOIagGlCxQ:-KR3TSHqUvEBmDuAmpIw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6bf98ae2745d286e2af970dd183e83a51b35f2a/cmd/dgraph/main.go#L165)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> OK
</details>
Done.

---

*[cmd/dgraph/main.go, line 225 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR2n1R9Y1jxCM6Z0vH3:-KR3Wofb6v2YZK-Hf7_N:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/727160e5a097b51ff97db9b6a091db53b8e38449/cmd/dgraph/main.go#L225)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> marshal
</details>
Done.

---

*[cmd/dgraph/main.go, line 68 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3R-ru-JVKonha3Gvf:-KR3TR439MVuJJ_UQ8-n:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/cmd/dgraph/main.go#L68)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> `mutationResult`
</details>
Done.

---

*[cmd/dgraph/main.go, line 70 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3R3JPp0rO0G5uRcTy:-KR3SwdT-sgJJ18obqNa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/cmd/dgraph/main.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> newUids
</details>
Done.

---

*[cmd/dgraph/main.go, line 140 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3REOCeiPIfb3fhf6z:-KR3THMF0nj8vpbTKBEG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/cmd/dgraph/main.go#L140)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Always a good idea to have the key also mentioned.
</details>
Done.

---

*[uid/assigner.go, line 145 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3RaUuVq7w8se8aPXm:-KR3W6rDkDR5A7ElvCwd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/51b1f0640958d1ccb362a9f581db0fd9676c715b/uid/assigner.go#L145)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Actually, just realized that the random XID would be stored. So, instead move that part of the logic here and store `_new_` here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by manishrjain** [comment]
Reviewed 1 of 3 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[algo/other.go, line 15 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3fHBnoAk2Jiq5Se7n:-KR3fHBnoAk2Jiq5Se7o:b-7m74ox) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/algo/other.go#L15)):*
> ```Go
> 		return "", err
> 	}
> 	return base32.StdEncoding.EncodeToString(randomBytes), nil
> ```

nice!

---

*[cmd/dgraph/main.go, line 86 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3fQoNIan4JM1HUbSh:-KR3fQoOIu3JkIvyK4Pr:b-v7dp6u) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/cmd/dgraph/main.go#L86)):*
> ```Go
> 	var edges []x.DirectedEdge
> 	var nquads []rdf.NQuad
> 	var edg mutationResult
> ```

detail :-). `var mr mutationResult`

---

*[cmd/dgraph/main.go, line 153 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3fZAFHJ3gxvI3BoK8:-KR3fZAGGbDVbABHwCHW:bksa8al) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/cmd/dgraph/main.go#L153)):*
> ```Go
> 	var allocIds map[string]uint64
> 	var m worker.Mutations
> 	var edg mutationResult
> ```

var mr ..

---

*[uid/assigner.go, line 133 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3fs0SGId2b_iKdWls:-KR3fs0SGId2b_iKdWlt:b-8387g1) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/uid/assigner.go#L133)):*
> ```Go
> 
> 	for {
> 		txid = txid + " "
> ```

You're adding a space by default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[uid/assigner.go, line 135 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3gXM-aR4Ws4lCFSOI:-KR3gXM-aR4Ws4lCFSOJ:bgvrte6) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/uid/assigner.go#L135)):*
> ```Go
> 		txid = txid + " "
> 
> 		uid1 := farm.Fingerprint64([]byte(txid)) // Generate from hash.
> ```

Actually this takes bytes, so your txid can just be a byte array. In that case, your RandStringBytes.. thing can retrn bytes instead of string, which saves the encoding. In fact, you can ditch the func altogether and do rand.Read() straight up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by ashwin95r** [comment]
Review status: 7 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/dgraph/main.go, line 86 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3fQoNIan4JM1HUbSh:-KR3h02u5byXwIpDh-bG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/cmd/dgraph/main.go#L86)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> detail :-). `var mr mutationResult`
</details>
Done.

---

*[cmd/dgraph/main.go, line 153 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3fZAFHJ3gxvI3BoK8:-KR3h2PZIydVn9Uo0Pgn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/cmd/dgraph/main.go#L153)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> var mr ..
</details>
Done.

---

*[uid/assigner.go, line 133 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3fs0SGId2b_iKdWls:-KR3gQ-rGhFv-WgWDint:b-qel21d) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/uid/assigner.go#L133)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You're adding a space by default?
</details>
Changing it to byte array.

---

*[uid/assigner.go, line 135 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3gXM-aR4Ws4lCFSOI:-KR3jIlWe2BYTtKFVBLV:b-us92ps) ([raw file](https://github.com/dgraph-io/dgraph/blob/fb5ae88409c50191b2792098c5a5e9bdd49c02cf/uid/assigner.go#L135)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Actually this takes bytes, so your txid can just be a byte array. In that case, your RandStringBytes.. thing can retrn bytes instead of string, which saves the encoding. In fact, you can ditch the func altogether and do rand.Read() straight up.
</details>
Yeah, Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198)*

**Comment by manishrjain** [comment]
:lgtm_strong: One last comment. Implement that and then feel free to submit. also, add a task to update wiki. Good job making this look easy!

---

Reviewed 2 of 2 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[uid/assigner.go, line 132 \[r10\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3tfJha51cOTdZqXUk:-KR3tfJi_l4oPZ5UoAD3:b-79t5ut) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ff25fa1b21d6d089215c3c255788c507608ddb8/uid/assigner.go#L132)):*
> ```Go
> 	}
> 
> 	for ; ; txid = append(txid, ' ') {
> ```

Actually instead of space, maybe add another random byte here. This would help alleviate collisions​.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-:-KR3tvfqXwe8UcdZU7Lp:bud05su)*

**Comment by ashwin95r** [comment]
Thanks! Task to add wiki: https://app.asana.com/0/110655897041979/177556942800935

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[uid/assigner.go, line 132 \[r10\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-KR3tfJha51cOTdZqXUk:-KR3uDFS1_HByBLSqE2x:b-liwrv0) ([raw file](https://github.com/dgraph-io/dgraph/blob/9ff25fa1b21d6d089215c3c255788c507608ddb8/uid/assigner.go#L132)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Actually instead of space, maybe add another random byte here. This would help alleviate collisions​.
</details>
Sure. had that in mind, but thought this would be quite rare. But, Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/198#-:-KR3v769dE2PrqXHZoFc:b-8kfhul)*

**Comment by ashwin95r** [comment]
Merged to master with commit 5dad80b23ca0caff57daaa45ac4abab3d123e5f8.

**Pull request closed without merging**
