### PR TITLE
Make field alias work

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/383)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Small comments apart from that :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query.go, line 228 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-eHw57P_PfGbhRJ8e:-KZ-eHw57P_PfGbhRJ8f:b-mlg0ek) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6eeb971d1083169d23b052d54e78f2d2fb0849d/query/query.go#L228)):*
> ```Go
> 		fieldName := pc.Attr
> 		if pc.Params.Alias != "" {
> 			fieldName = pc.Params.Alias
> ```

Can't we just do `pc.Attr = pc.Params.Alias`? I suppose it would give some problems with _xid_. 

---

*[query/query_test.go, line 522 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-dTYpN_SCDlq83Kta:-KZ-dTYpN_SCDlq83Ktb:b-1ash1p) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6eeb971d1083169d23b052d54e78f2d2fb0849d/query/query_test.go#L522)):*
> ```Go
> 				MyName:name
> 				gender
> 			  alive
> ```

some indentation issue.

---

*[query/query_test.go, line 547 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-daBqJFO92tFRcBFj:-KZ-daBqJFO92tFRcBFk:b-2guby3) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6eeb971d1083169d23b052d54e78f2d2fb0849d/query/query_test.go#L547)):*
> ```Go
> 				MyName:name
> 				gender
> 			  alive
> ```

same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-:-KZ-f1YcFo_ejqR1_lxw:bx2gpx3)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query.go, line 228 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-eHw57P_PfGbhRJ8e:-KZ-fQRhTL2lgnsYgnz1:b-7xtei2) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6eeb971d1083169d23b052d54e78f2d2fb0849d/query/query.go#L228)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can't we just do `pc.Attr = pc.Params.Alias`? I suppose it would give some problems with _xid_. 
</blockquote></details>

Yeah.

---

*[query/query_test.go, line 522 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-dTYpN_SCDlq83Kta:-KZ-fkHkxxmq2Y-XK8CE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6eeb971d1083169d23b052d54e78f2d2fb0849d/query/query_test.go#L522)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

some indentation issue.
</blockquote></details>

Done.

---

*[query/query_test.go, line 547 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-daBqJFO92tFRcBFj:-KZ-fkmaH_YAt4cEWuZ0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6eeb971d1083169d23b052d54e78f2d2fb0849d/query/query_test.go#L547)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/383)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 536 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-iWcShj_5-4P-PelO:-KZ-iWcTCHajBedIPaNQ:b-k099by) ([raw file](https://github.com/dgraph-io/dgraph/blob/000712b1df1bcf2baa4171eb4d27f11ad135e060/query/query_test.go#L536)):*
> ```Go
> }
> 
> func TestFieldAliasProto(t *testing.T) {
> ```

Now that preTraverse is used for both JSON and proto, we can probably skip this test. But since you wrote it, let's keep it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-:-KZ-j47k6cXJgbcBBbmj:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 536 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/383#-KZ-iWcShj_5-4P-PelO:-KZ-jGlbeh-DdJvjUVJ0:b-80tlqk) ([raw file](https://github.com/dgraph-io/dgraph/blob/000712b1df1bcf2baa4171eb4d27f11ad135e060/query/query_test.go#L536)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Now that preTraverse is used for both JSON and proto, we can probably skip this test. But since you wrote it, let's keep it.
</blockquote></details>

Sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/383)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
