### PR TITLE
Fix upload.sh

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1764)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1764#-:-KynhU63Yn90qOhzNucO:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1764#-:-KynsgpCJLfNXbtAo3hI:bnfp4nl)*

**Comment by janardhan1993** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1764)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
