### PR TITLE
Fix #1937

### LINKED ISSUE #1937: Insert a new node with custom uid
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
currently i'm using dgraph version 1.0.0

- Have you tried reproducing the issue with latest release?
yes i have tried it, in old and new dgraph version
old version ran smoothly (0.7.x) (0.8.x)
after (0.9.2) release, it couldn't create the node (got an error)
then (1.0.0) came out and the result seems wrong

- What is the hardware spec (RAM, OS)?
RAM 8GB, OS Ubuntu 16.04

- Steps to reproduce the issue (command/config used to run Dgraph).
1. using the example from the docs with custom uid
```
c := client.NewDgraphClient(api.NewDgraphClient(conf.Key.Dgraph.Connection))

p := PersonEdit{
        Uid:      "0xa14222b693e4ba34",
        Name:   "Name",
        Age:      26,
        Married:  true,
        Location: "Jakarta",
        Friend: []Friend{
            {
                Name:           "Bob",
                Age:            24,
                LastUpdateTime: time.Now(),
                ReadStatus:     1,
            },
        },
        School: []School{
            {
                Name: "Crown Public School",
            },
        },
    }

    protosMutation := &api.Mutation{
        CommitNow: true,
    }

    byteData, err := json.Marshal(p)
    if err != nil {
        log.Println(err)
    }
    protosMutation.SetJson = byteData

    newAction := c.NewTxn()
    ctx := context.Background()

    defer newAction.Discard(ctx)
    node, err := newAction.Mutate(ctx, protosMutation)
    if err != nil {
        log.Println(err)
    }
```

- Expected behaviour and actual result.
Expecting the uid response from the dgraph same as the value when inserting
expect: 0xa14222b693e4ba34
got: 0x18 

Actual result:
```
Custom UID: 0xa14222b693e4ba34
Byte data:  {"uid":"0xa14222b693e4ba34","name":"Name","age":26,"married":true,"following":[{"name":"Bob","age":24,"following|read_status":1,"following|last_update_time":"2017-12-19T20:04:52.321873602+07:00"}],"loc":"Jakarta","school":[{"uid":"","name@en":"Crown Public School","school:since":"0001-01-01T00:00:00Z"}]}
2017/12/19 20:04:52 map[blank-0:0x18 blank-1:0x19 blank-2:0x1a]
```

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Return error if user uses a string uid that can't be parsed as `uint64`.
2. Update examples to not use a hardcoded uid as it causes confusion to users.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1941)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1941#-:-L0mDIsE2J7qydm8gyQA:bnfp4nl)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[edgraph/server.go, line 629 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1941#-L0mDTVe5FXbd6A_GzdA:-L0mDTVe5FXbd6A_GzdB:b-de3339) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ac957701d79d4661f9a8e8b8f9aa18dfff2d593/edgraph/server.go#L629)):*
> ```Go
> 		if id, ok := uidVal.(float64); ok {
> 			uid = uint64(id)
> 		} else if id, ok := uidVal.(string); ok && len(id) > 0 {
> ```

I was a bit confused why we want to check len here, but the unit test explains it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1941#-:-L0mEN462xes8H-X8w07:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[edgraph/server.go, line 629 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1941#-L0mDTVe5FXbd6A_GzdA:-L0mQy4zIVlgPHzCGoFS:bkjdn8o) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ac957701d79d4661f9a8e8b8f9aa18dfff2d593/edgraph/server.go#L629)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

I was a bit confused why we want to check len here, but the unit test explains it.
</blockquote></details>

Adding a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1941)*

**Comment by pawanrawal** [comment]
Merged to master with e9865185205aa8293eb64cacf6e350aa5ed28ca1

**Pull request closed without merging**
