### PR TITLE
Make filter work at root

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/447)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Small change first.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 421 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/447#-K_gOJb791Nc0fFlMvFc:-K_gOJb791Nc0fFlMvFd:bainge2) ([raw file](https://github.com/dgraph-io/dgraph/blob/e092a065810bc60cab51b109e19c7f44a8563315/gql/parser.go#L421)):*
> ```Go
> 			return nil, x.Errorf("Unknown directive [%s]", item.Val)
> 		}
> ```

Just jump up. Do check for a double filter.

---

*[gql/parser_test.go, line 588 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/447#-K_gOSvFMJdlgXKb94S9:-K_gOSvFMJdlgXKb94SA:b-qbl0z3) ([raw file](https://github.com/dgraph-io/dgraph/blob/e092a065810bc60cab51b109e19c7f44a8563315/gql/parser_test.go#L588)):*
> ```Go
> 	query := `
> 	query {
> 		me(_uid_:0x0a) @filter(allof(name, "alice")) {
> ```

me(func(..)) @filter..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/447#-:-K_gP2XgQgBGrDEqsfYz:b-73716)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 421 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/447#-K_gOJb791Nc0fFlMvFc:-K_gQ3u8LG-PB5ILxsDF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e092a065810bc60cab51b109e19c7f44a8563315/gql/parser.go#L421)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just jump up. Do check for a double filter.
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 588 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/447#-K_gOSvFMJdlgXKb94S9:-K_gS7nob9A51VlXKY77:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e092a065810bc60cab51b109e19c7f44a8563315/gql/parser_test.go#L588)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

me(func(..)) @filter..
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/447)*

**Comment by jchiu0** [comment]
:lgtm: Nice.

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/447#-:-K_mr-ap0VbVn7feZiej:b-8gk8u6)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
