### PR TITLE
Support index specification in schema

### PR DESCRIPTION
**Pull request by ashwin95r**
We can specifiy which scalars to be indexed in schema file using `@index`. Example:
```
scalar (
  name:string @index
  age:int
)
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/270)

### CODE REVIEW

**Comment by jchiu0** [comment]
Quick and nice work!

This probably will cause some of the index related tests to fail. Wonder if we should wait for the current tests to all pass (particularly worker and query) before trying to submit this.

---

Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNz-YkGYGrdPgwghMe:-KTNz-YkGYGrdPgwghMf:bsyrzh) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7014806fb97bff685a6112d818e2175171a6e46/posting/index.go#L46)):*
> ```Go
> type indexConfig struct {
> 	Attr string `json:"attribute"`
> 	// TODO(jchiu): Add other tokenizer here in future.
> ```

Feel free to delete these TODOs.

---

*[schema/parse.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNysxo6sldg-56jgpY:-KTNysxo6sldg-56jgpZ:b-kcfnjj) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/parse.go#L116)):*
> ```Go
> 						indexedFields[name] = true
> 					} else {
> 						return fmt.Errorf("Invalid index specification")
> ```

x.Errorf. Same as the one below, for potentially more debug info.

---

*[schema/parse_test.go, line 85 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNyoe5T0a8hmIOrqp1:-KTNyoe6QLcAz9S_vTXQ:b4cm67n) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/parse_test.go#L85)):*
> ```Go
> 	str = make(map[string]types.Type)
> 	indexedFields = make(map[string]bool)
> 	err := Parse("testfiles/test_schema_index1")
> ```

require.NoError(Parse(...)) is now possible.

---

*[schema/schema.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNxtMttWLOQKyY8Prq:-KTNxtMttWLOQKyY8Prr:b6x3ln7) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/schema.go#L28)):*
> ```Go
> 
> var str map[string]types.Type
> var indexedFields map[string]bool
> ```

Maybe var (....) will look better with indent. Could add some comments to these "global vars".

---

*[schema/state.go, line 299 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNxnJfohg74_gPMe3r:-KTNxnJfohg74_gPMe3s:b-1i0mks) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/state.go#L299)):*
> ```Go
> 		case r == '@':
> 			l.Emit(itemAt)
> 			isIndexed = true
> ```

Prefer a false default value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-:-KTNzEKsQCiF9Mf3tVnS:b-qjw6j7)*

**Comment by ashwin95r** [comment]
I've tried to fix the two tests related to Index. Sure, we can wait till the other tests in worker are fixed.

---

Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[posting/index.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNz-YkGYGrdPgwghMe:-KTO-UZUQuAbmIOX16Qz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7014806fb97bff685a6112d818e2175171a6e46/posting/index.go#L46)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Feel free to delete these TODOs.
</details>
Done.

---

*[schema/parse.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNysxo6sldg-56jgpY:-KTO01f1velHHiXwMDP9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/parse.go#L116)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> x.Errorf. Same as the one below, for potentially more debug info.
</details>
Done.

---

*[schema/parse_test.go, line 85 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNyoe5T0a8hmIOrqp1:-KTO4Mirc94cOrKEaAmP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/parse_test.go#L85)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> require.NoError(Parse(...)) is now possible.
</details>
Done.

---

*[schema/schema.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNxtMttWLOQKyY8Prq:-KTO0HmyODxX3BoSmTYy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/schema.go#L28)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Maybe var (....) will look better with indent. Could add some comments to these "global vars".
</details>
Done.

---

*[schema/state.go, line 299 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNxnJfohg74_gPMe3r:-KTO0ItO-foORJg4ZYUg:b-o4kvfw) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/state.go#L299)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Prefer a false default value?
</details>
Yeah when the variable is declared above, it'll be false by default. Is that what you meant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-:-KTO4PUOkClb-zpxwaL4:b-9927dq)*

**Comment by ashwin95r** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[schema/parse.go, line 43 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNvs1vi_DPfdCZIbvP-r2-43:-KTO5LYVe1rWl6ev2-cz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3606074f242e2a10f69f89131f23a04462dc8dcd/schema/parse.go#L43)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported function ParseBytes should be of the form "ParseBytes ..."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/270)*

**Comment by jchiu0** [comment]
:lgtm: Thanks!

---

Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[schema/state.go, line 299 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-KTNxnJfohg74_gPMe3r:-KTOE00KlKP4aFazzSOc:buhicfr) ([raw file](https://github.com/dgraph-io/dgraph/blob/1036d655f4e7af93bf7d9a38ac6c725a5e652176/schema/state.go#L299)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Yeah when the variable is declared above, it'll be false by default. Is that what you meant?
</details>
My bad, yes, this is right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/270#-:-KTOEV9h6WdNhGbkDcP7:b-g2a5fb)*

**Comment by ashwin95r** [comment]
Merged to master with commit 6445989f67ef9487ce62f1445b363063ae06e44b.

**Pull request closed without merging**
