### PR TITLE
Backup requests

### PR DESCRIPTION
**Pull request by srh**
Implements backup requests.

Connected to #1121.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1343)

### CODE REVIEW

**Comment by srh** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 69 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-KrntrThHpNc3rDS7hKU:-KrntrThHpNc3rDS7hKV:b-knxkcx) ([raw file](https://github.com/dgraph-io/dgraph/blob/42b6120dcf425cf3562cdd3748349192b20ad019/worker/task.go#L69)):*
> ```Go
> }
> 
> const backupRequestGracePeriod = 10 * time.Millisecond
> ```

I went with 10ms instead of 2ms as a result of my experiments seeing 1-2ms gRPC echo roundtrip times *locally*.  Shorter would make sense if we implement cross-server cancellation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343)*

**Comment by manishrjain** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/groups.go, line 282 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-KsgP4VwvP7nvGlo854t:-KsgP4VwvP7nvGlo854u:bvxr0mk) ([raw file](https://github.com/dgraph-io/dgraph/blob/540c691e5f2d175cffed69c6396bc3d4881d5f44/worker/groups.go#L282)):*
> ```Go
> 	idx1 := rand.Intn(sz)
> 	idx2 := rand.Intn(sz - 1)
> 	if idx2 >= idx1 {
> ```

Does this mean that if idx1 == 0, idx2 would never be 1?

---

*[worker/task.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-KsgUeS9Kq_Oxobb933A:-KsgUeS9Kq_Oxobb933B:bu7y82x) ([raw file](https://github.com/dgraph-io/dgraph/blob/540c691e5f2d175cffed69c6396bc3d4881d5f44/worker/task.go#L54)):*
> ```Go
> 
> func invokeNetworkRequest(
> 	ctx context.Context, addr string, f func(context.Context, protos.WorkerClient) (interface{}, error)) (interface{}, error) {
> ```

interface? Can we avoid this?

---

*[worker/task.go, line 106 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-KsgVFNsrWrihYnugbfl:-KsgVFNsrWrihYnugbfm:bc17lsu) ([raw file](https://github.com/dgraph-io/dgraph/blob/540c691e5f2d175cffed69c6396bc3d4881d5f44/worker/task.go#L106)):*
> ```Go
> 			chResults <- taskresult{reply, err}
> 		}()
> 		select {
> ```

This select can probably be avoided if you GOTO just above the outer select (below defer timer.Stop line).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343)*

**Comment by srh** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/groups.go, line 282 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-KsgP4VwvP7nvGlo854t:-Ksp4O_I8A1OrpufEP2J:b-hqd59o) ([raw file](https://github.com/dgraph-io/dgraph/blob/540c691e5f2d175cffed69c6396bc3d4881d5f44/worker/groups.go#L282)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Does this mean that if idx1 == 0, idx2 would never be 1?
</blockquote></details>

If idx1 is 0 and idx2 was 0, then idx2 will then be incremented so that it equals 1.

idx2 starts being uniformly random in the interval [0, sz - 1), and ends up being a random number in either [0, idx1) or [idx1 + 1, sz).

---

*[worker/task.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-KsgUeS9Kq_Oxobb933A:-Ksp4hHeO6yfc2LxSoUa:b-5slwww) ([raw file](https://github.com/dgraph-io/dgraph/blob/540c691e5f2d175cffed69c6396bc3d4881d5f44/worker/task.go#L54)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

interface? Can we avoid this?
</blockquote></details>

Not without copy/pasting code or reusing the same type for two different kinds of requests.  Or if Go had generics -- this is a purely generic function.

---

*[worker/task.go, line 106 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-KsgVFNsrWrihYnugbfl:-Ksp661CJcDFfIgJO6CL:bya3n7h) ([raw file](https://github.com/dgraph-io/dgraph/blob/540c691e5f2d175cffed69c6396bc3d4881d5f44/worker/task.go#L106)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This select can probably be avoided if you GOTO just above the outer select (below defer timer.Stop line).
</blockquote></details>

That would require some extra flag to tell what has happened, and then different cases would have to branch on these flags to figure out what to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1343#-:-KsqUsk263KQ6xQw2eCM:bnfp4nl)*

**Pull request merged**
