### PR TITLE
Create dgraph/standalone Docker image

### PR DESCRIPTION
**Pull request by campoy**
This will allow us to run dgraph in a single docker command:

```bash
$ docker run -tP dgraph/standalone
```

Please @danielmai, can you modify this so this image is built with each release and nightly too?
This will make our "getting started" much easier!

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3899)

### CODE REVIEW

**Comment by campoy** [comment]
Yeah, this is not the most robust way to run a cluster for sure, but it's maybe the easiest one.

I think that if you run the image with `-t` the `ctrl+c` would actually kill the container, wouldn't it?

**Comment by danielmai** [comment]
> I think that if you run the image with `-t` the `ctrl+c` would actually kill the container, wouldn't it?

It does not. It continues running in the background. This can be verified with `docker ps`.

**Comment by hackintoshrao** [comment]
Hey @danielmai , 

Looks like `docker run -it` solves the issue of the container running in the background.

**Comment by danielmai** [comment]
> Looks like `docker run -it` solves the issue of the container running in the background.

OK. I added a TODO in run.sh. Feel free to merge.

**Comment by campoy** [comment]
LGTM!

**Comment by danielmai** [comment]
___
*[contrib/standalone/run.sh, line 6 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/3899#-LnqISr-8cJo5JYVHVla-r1-6:-LpEyDKsC6KbhUZUJaoD:bun2t6t) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbd5ac22bafea1633fbce573520e9d319df48c18/contrib/standalone/run.sh#L6)):*
<details><summary><i>Previously, pullrequest[bot] wrote…</i></summary><blockquote>

I saw there was a recent PR making `--lru_mb` an optional parameter, is this just in place until that is available and then we can remove?

It seems like currently this will be taking the full total of memory on the system which might be a little bit aggressive if some of it is already in use. It could be worth an inline comment here just to explain what the goal is behind the `lru_mb` size being set
</blockquote></details>

Updated the setting to one-third of available memory, which is typically what we recommend.

**Pull request merged**
