### PR TITLE
Language parsing in functions

### PR DESCRIPTION
**Pull request by tzdybal**
Support for '@lang' notation in attribute specification in functions (and filters).
This is required to enable full text search with language specific stemmers and stop words.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/683)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser_test.go, line 1893 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-Kepi9oSuqf4s3Sj_s4n:-Kepi9oSuqf4s3Sj_s4o:b-badkhu) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1893)):*
> ```Go
> 	query {
> 		me(id:0x0a) {
> 			friends @filter(alloftext("descr@en@de", "something")) {
> ```

Please add a comment that it fails due to multiple langs (or function name can be modified)

---

*[gql/parser_test.go, line 1905 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-KepiM4tkqC7JCxmxGJ9:-KepiM4tkqC7JCxmxGJA:bavkfjp) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1905)):*
> ```Go
> }
> 
> func TestLangsFilter2_error1(t *testing.T) {
> ```

This test is same as above. Something missing?

---

*[gql/parser_test.go, line 1942 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-Kepiho_0ktBllp1E6nx:-Kepiho_0ktBllp1E6ny:b-v4r4wd) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1942)):*
> ```Go
> }
> 
> func TestLangsFunction2(t *testing.T) {
> ```

Repeated test funcition?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683)*

**Comment by tzdybal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser_test.go, line 1893 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-Kepi9oSuqf4s3Sj_s4n:-Keq3-9tOLLjDbrvSSS8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1893)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Please add a comment that it fails due to multiple langs (or function name can be modified)
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 1905 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-KepiM4tkqC7JCxmxGJ9:-Kepzqx1KI-0U00kKebn:b3w45oi) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1905)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This test is same as above. Something missing?
</blockquote></details>

Notice the double-quote around attribute. Functions are almost the same, but in one case `@lang` is a part of a string, and in the second case it's directly exposed to parser (because it's not quoted). 
Comments added in the code.

---

*[gql/parser_test.go, line 1942 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-Kepiho_0ktBllp1E6nx:-Keq-h2Xw9jrrwfvy3jB:b-7z9nqc) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1942)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Repeated test funcition?
</blockquote></details>

Same as before, there is a slight difference in test code, resulting large difference in processing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683)*

**Comment by ashwin95r** [comment]
I have a change which reuses ParseFunction in ParseFilter. We we can combine it with this, it'd be nice: https://github.com/dgraph-io/dgraph/compare/support/countfilterroot. As we're repeating the same logic.

Otherwise, :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser_test.go, line 1905 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-KepiM4tkqC7JCxmxGJ9:-Keq7ewbjWGVxuAHxwfk:b-rgal53) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1905)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Notice the double-quote around attribute. Functions are almost the same, but in one case `@lang` is a part of a string, and in the second case it's directly exposed to parser (because it's not quoted). 
Comments added in the code.
</blockquote></details>

Ah okay!

---

*[gql/parser_test.go, line 1942 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-Kepiho_0ktBllp1E6nx:-Keq7g3hnZMGn-vg5CDC:b-4hvi0m) ([raw file](https://github.com/dgraph-io/dgraph/blob/380f99942c52d07f17ac3ed64383ac3d5e8bcdcf/gql/parser_test.go#L1942)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Same as before, there is a slight difference in test code, resulting large difference in processing.
</blockquote></details>

Got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-:-Keq7pBBHOxcAQYLnmI0:b-5ynk94)*

**Comment by manishrjain** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[gql/parser_test.go, line 1897 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-KeqDu9SzNf3me2WlCU4:-KeqDu9SzNf3me2WlCU5:bge68hg) ([raw file](https://github.com/dgraph-io/dgraph/blob/bb27eaf79e898452697f7e62cbf761750f1cbcd8/gql/parser_test.go#L1897)):*
> ```Go
> 	query {
> 		me(id:0x0a) {
> 			friends @filter(alloftext("descr@en@de", "something")) {
> ```

Shouldn't this be `@en:de`? Like we query for a specific lang for a predicate. Or, we can change both to this.

---

*[gql/parser_test.go, line 1931 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-KeqFKwBL8Yc9TRSN4zE:-KeqFKwCgQHDWa5lmmaP:by3l083) ([raw file](https://github.com/dgraph-io/dgraph/blob/bb27eaf79e898452697f7e62cbf761750f1cbcd8/gql/parser_test.go#L1931)):*
> ```Go
> 	query := `
> 	query {
> 		me(func:alloftext("descr@en", "something")) {
> ```

Do we really need to support these quotes in the predicate? Can't we just support only one way to specify predicates? It would simplify our code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683)*

**Comment by tzdybal** [comment]
@ashwin95r, thanks for your help with refactoring.

The build is failing, because of the issues with `checkpwd` function. I'll fix this in another PR.

---

Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[gql/parser_test.go, line 1897 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-KeqDu9SzNf3me2WlCU4:-Ker9-vQgapj52iOC8Fp:bgs6bh0) ([raw file](https://github.com/dgraph-io/dgraph/blob/bb27eaf79e898452697f7e62cbf761750f1cbcd8/gql/parser_test.go#L1897)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shouldn't this be `@en:de`? Like we query for a specific lang for a predicate. Or, we can change both to this.
</blockquote></details>

It's the error case - test has to ensure, that incorrect attribute/lang is detected. Currently I'm allowing only one language for functions. I can't see any sense in providing multiple different stemmers/stop word lists for the same set of arguments.

---

*[gql/parser_test.go, line 1931 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-KeqFKwBL8Yc9TRSN4zE:-Ker8HRU1Z3zKoy3ljl5:b-mkkgl3) ([raw file](https://github.com/dgraph-io/dgraph/blob/bb27eaf79e898452697f7e62cbf761750f1cbcd8/gql/parser_test.go#L1931)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do we really need to support these quotes in the predicate? Can't we just support only one way to specify predicates? It would simplify our code.
</blockquote></details>

Quoted version removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-:-KerA7Jikb8jgHBXvcey:bbcd7ca)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-:-KfEYdevWTWDS2GEVbUs:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1069 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-Kf9t6FSCTlP_uOEOtAg:-Kf9t6FSCTlP_uOEOtAh:b-qs1i66) ([raw file](https://github.com/dgraph-io/dgraph/blob/651bf384db7b461426fbcab23077ecb3c08facce/gql/parser.go#L1069)):*
> ```Go
> 				if len(g.Attr) == 0 {
> 					if strings.ContainsRune(itemInFunc.Val, '"') {
> 						return nil, x.Errorf("Attribute in function must not be quoted using \": %s", itemInFunc.Val)
> ```

Exceeds line length.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-:-KfG7rO-1oOxkGExrkIy:bnfp4nl)*

**Comment by tzdybal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1069 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/683#-Kf9t6FSCTlP_uOEOtAg:-KfGij-R_gQkGzcnpzwa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/651bf384db7b461426fbcab23077ecb3c08facce/gql/parser.go#L1069)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Exceeds line length.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/683)*

**Comment by tzdybal** [comment]
Merged to master.

**Pull request closed without merging**
