### PR TITLE
Fix a couple of issues regarding RAFT

### PR DESCRIPTION
**Pull request by pawanrawal**
Noticed these issues while exporting data in a cluster mode.

1. AmLeader is called by handleExportForGroup and the server calling it might not be serving the group hence we need to check if n is nil.
2. pool variable was shadowed inside the inner block and when  `defer pools().release(pl)` was called it paniced.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1373)

### CODE REVIEW

**Comment by srh** [comment]
I don't like the idea of having miscellaneous methods of node check if it's nil.  Why shouldn't handleExportForGroup be responsible for that?  It's usually way better to have the default assumption for pointers to be that it can't be nil.  Otherwise you have to chase down all sorts of edge cases everywhere.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1373#-:-KskcMFvykaI9czp5N28:b-t2glez)*

**Comment by srh** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1373)*

**Comment by pawanrawal** [comment]
Fair enough, handleExportForGroup checks that now. Also modified the Travis test to start two Dgraph nodes while loading data and checking for export count.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1373#-:-KskluRv-hkDQI0UYJ1G:bd4awwz)*

**Comment by srh** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1373#-:-Kskni-y0wE0woCuLUe9:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1373#-:-KslW-oQM4RXGwAqDgf_:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master with 96e1132cf9debdd5384294fdd65e7543f77f177d

**Pull request closed without merging**
