### PR TITLE
Replace logrus with net/tracer

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/113)

### CODE REVIEW

**Comment by pawanrawal** [comment]
The log looks pretty sparse now(since we don't have Info logs anymore). Though, great that we have tracing in place now. Couldn't trace the requests on `http://localhost:8080/debug/requests`. Am I doing something wrong?

---

Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 152 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/113#-KKkq73ZPYIoejrw36yK:-KKkq73dQsQytOUza0Pg:-1675700460) ([raw file](https://github.com/dgraph-io/dgraph/blob/afd648703a6ea1fc762d9b6868b95455c669d80b/query/query.go#L152)):*
> ```Go
> 		m, err := postTraverse(child)
> 		if err != nil {
> 			x.Err(glog, err).Error("Error while traversal")
> ```

We don't want to trace this?

---

*[query/query.go, line 259 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/113#-KKkqXXj-pdHnEfz8b4J:-KKkqXXj-pdHnEfz8b4K:285687775) ([raw file](https://github.com/dgraph-io/dgraph/blob/77403627cc5bddde07c24b73b2302524e621ef1d/query/query.go#L259)):*
> ```Go
> 	}
> 
> 	log.Fatal("Shouldn't reach here.")
> ```

We don't need this line and the line below. Maybe something like this could work
```
	if len(r) != 1 {
		log.Fatal("We don't currently support more than 1 uid at root.")
	}
	var m map[string]interface{}
	for _, ival := range r {
		if ival != nil {
			m = ival.(map[string]interface{})
		}
		m["server_latency"] = l.ToMap()
	}
	return json.Marshal(m)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/113#-:-KKkxu-L3kgEvLxY8GfV:2077548137)*

**Comment by manishrjain** [comment]
Good catch. I thought it worked the one time I checked before, but clearly not. It's working now.

---

Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/113#-:-KKkz7IWnlM_fTh1_FNu:618773461)*

**Comment by manishrjain** [comment]
Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 152 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/113#-KKkq73ZPYIoejrw36yK:-KKlD6dPkObvGNrKGhhy:22837318) ([raw file](https://github.com/dgraph-io/dgraph/blob/afd648703a6ea1fc762d9b6868b95455c669d80b/query/query.go#L152)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We don't want to trace this?
</details>
Just didn't have the context here, so I thought the calling function can show the error.

---

*[query/query.go, line 259 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/113#-KKkqXXj-pdHnEfz8b4J:-KKlF4cQWhhHnwGhc-Yw:-407422139) ([raw file](https://github.com/dgraph-io/dgraph/blob/77403627cc5bddde07c24b73b2302524e621ef1d/query/query.go#L259)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We don't need this line and the line below. Maybe something like this could work
> ```
> 	if len(r) != 1 {
> 		log.Fatal("We don't currently support more than 1 uid at root.")
> 	}
> 	var m map[string]interface{}
> 	for _, ival := range r {
> 		if ival != nil {
> 			m = ival.(map[string]interface{})
> 		}
> 		m["server_latency"] = l.ToMap()
> 	}
> 	return json.Marshal(m)
> ```
> 
</details>
Done. Nice one!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/113)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/113#-:-KKlHOlB-pCXvwcWFT8b:1417088721)*

**Comment by pawanrawal** [comment]
Reviewed 23 of 26 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/113)*

**Comment by manishrjain** [comment]
Merged, without fail this time.

**Pull request closed without merging**
