### PR TITLE
Add http query and mutate handler.

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Added `TxnContext` to `protos.Response`. StartTs and LinRead are now returned under TxnContext.
2. Added `GET /query` which proxies the request to `Server.Query()`, adds latency and txninfo to user before returning it to the user.
3. Added `POST /mutate` which accepts `set` and `delete` RDF mutations like queryHandler used to before. Later we can also support mutations using JSON.

TODO - Allow schema mutations, dropall and delete predicate via `/alter` HTTP API?

This requires testing. Waiting for @janardhan1993 to merge his change.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1705)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[cmd/dgraph/main.go, line 229 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-Kxkxd4aY_cRdcQaMF9D:-Kxkxd4bLq5nuC-bxZVb:b-ixnkwx) ([raw file](https://github.com/dgraph-io/dgraph/blob/e5e56c7e3cdd5bafcfb921fa5fdb7e4d8aa3914c/cmd/dgraph/main.go#L229)):*
> ```Go
> 
> 	// TODO - Confirm we want this as get.
> 	if r.Method != "GET" {
> ```

!= POST

---

*[cmd/dgraph/main.go, line 267 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-Kxkxn9KvalykfUUPJRi:-Kxkxn9LzRslyOs44qv7:b7jbxj7) ([raw file](https://github.com/dgraph-io/dgraph/blob/e5e56c7e3cdd5bafcfb921fa5fdb7e4d8aa3914c/cmd/dgraph/main.go#L267)):*
> ```Go
> 	if addLatency {
> 		e := query.Extensions{
> 			Latency: l.ToMap(),
> ```

Txn here.

---

*[cmd/dgraph/main.go, line 308 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxkzqJ56oXfKH_Y_JPE:-KxkzqJ6Qoea92g6sif8:bcxix22) ([raw file](https://github.com/dgraph-io/dgraph/blob/e5e56c7e3cdd5bafcfb921fa5fdb7e4d8aa3914c/cmd/dgraph/main.go#L308)):*
> ```Go
> 	}
> 
> 	mu.CommitImmediatelly = true
> ```

If they supply start ts, then no need to do this.

---

*[cmd/dgraph/main.go, line 321 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxkzwlEFpUxlEC1p8LC:-KxkzwlEFpUxlEC1p8LD:btkob7o) ([raw file](https://github.com/dgraph-io/dgraph/blob/e5e56c7e3cdd5bafcfb921fa5fdb7e4d8aa3914c/cmd/dgraph/main.go#L321)):*
> ```Go
> 	mp["message"] = "Done"
> 	mp["uids"] = query.ConvertUidsToHex(resp.Uids)
> 	response["data"] = mp
> ```

Also pass back lin reads for the groups.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705)*

**Comment by janardhan1993** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[cmd/dgraph/http.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-Kxoexwf_xjDXV6rRf99:-Kxoexwf_xjDXV6rRf9A:b-out3rv) ([raw file](https://github.com/dgraph-io/dgraph/blob/2bd36ebbb2e6dc9395c44f217b29ab0a1a7d24fa/cmd/dgraph/http.go#L63)):*
> ```Go
> 	}
> 
> 	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
> ```

We removed timeout in grpc so probably we can do the same here or pass timeout through get paramas

---

*[cmd/dgraph/http.go, line 66 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxofLbzuD-gM8Nn7usc:-KxofLbzuD-gM8Nn7usd:b-7m9mkf) ([raw file](https://github.com/dgraph-io/dgraph/blob/2bd36ebbb2e6dc9395c44f217b29ab0a1a7d24fa/cmd/dgraph/http.go#L66)):*
> ```Go
> 	defer cancel()
> 	// TODO - Check if debug still works.
> 	resp, err := (&dgraph.Server{}).Query(ctx, &req)
> ```

Don't we have access to this ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 7 of 10 files at r2, 9 of 9 files at r3.
Review status: 13 of 16 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/http.go, line 54 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-Kxpa1y2j4hh0LySkXqC:-Kxpa1y2j4hh0LySkXqD:bbabaz3) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2c199b8cb893e96c2f16ce3afda94ae2dacb37c/cmd/dgraph/http.go#L54)):*
> X-StartTs")
Instead of X, how about `X-Dgraph-StartTs`

---

*[cmd/dgraph/http.go, line 56 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxpYopy62NrEwrFRsuw:-KxpYopy62NrEwrFRsux:b-unqa0l) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2c199b8cb893e96c2f16ce3afda94ae2dacb37c/cmd/dgraph/http.go#L56)):*
> ```Go
> 	startTs := r.Header.Get("X-StartTs")
> 	if startTs != "" {
> 		ts, err := strconv.ParseUint(startTs, 10, 64)
> ```

`strconv.ParseUint(startTS, 0, 64)` to handle all the various kinds, like hex / dec.

---

*[cmd/dgraph/http.go, line 65 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxpaCTYT01JP8GnZNFT:-KxpaCTYT01JP8GnZNFU:bvlhs3i) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2c199b8cb893e96c2f16ce3afda94ae2dacb37c/cmd/dgraph/http.go#L65)):*
> ```Go
> 	}
> 
> 	linRead := r.Header.Get("X-LinRead")
> ```

X-Dgraph-LinRead

---

*[cmd/dgraph/http.go, line 123 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxpaV5we8CFXAe8dHom:-KxpaV5we8CFXAe8dHon:b-l6iyse) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2c199b8cb893e96c2f16ce3afda94ae2dacb37c/cmd/dgraph/http.go#L123)):*
> ```Go
> 		response["data"] = mp
> 	} else {
> 		jsonRes := map[string]interface{}{}
> ```

result

---

*[cmd/dgraph/http.go, line 165 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxpaftduDFCfK9zw9pd:-KxpaftduDFCfK9zw9pe:b2follg) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2c199b8cb893e96c2f16ce3afda94ae2dacb37c/cmd/dgraph/http.go#L165)):*
> ```Go
> 
> 	// Maybe rename it so that default is CommitImmediately.
> 	commit := r.Header.Get("X-Commit")
> ```

`X-Dgraph-CommitNow`

---

*[cmd/dgraph/http.go, line 178 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-KxpajeKF64xRXoKsN2S:-KxpajeKF64xRXoKsN2T:b-d1ovg7) ([raw file](https://github.com/dgraph-io/dgraph/blob/b2c199b8cb893e96c2f16ce3afda94ae2dacb37c/cmd/dgraph/http.go#L178)):*
> ```Go
> 	startTs := r.Header.Get("X-StartTs")
> 	if startTs != "" {
> 		ts, err := strconv.ParseUint(startTs, 10, 64)
> ```

, 0, 64

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1705#-:-Kxpbnt7BFFhdyi0TZjt:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master as I have to do new changes on top of this one. @peterstace feel free to review still and provide feedback.

**Pull request closed without merging**
