### PR TITLE
chore(docs): add Ratel Docs

### PR DESCRIPTION
**Pull request by MichelDiz**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6400)

 

Docs Preview: [Dgraph Preview](https://dgraph-38608bcd59-91848.surge.sh)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
Let's add screenshots with examples for each thing covered for Ratel.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6400#-:-MJhLYGf4ODIwXx51NXA:b-yi1p5c)* status: all files reviewed, 3 unresolved discussions (waiting on @MichaelJCompton and @MichelDiz)

___
*[wiki/content/ratel/backups.md, line 11 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6400#-MJhLe8ABeXLyV-QK7W9:-MJhLe8ABeXLyV-QK7WA:b-9ieelz) ([raw file](https://github.com/dgraph-io/dgraph/blob/38608bcd5981cacaa16040dc2e75d4e1b59c0c74/wiki/content/ratel/backups.md#L11)):*
> ```
> EE feature
> ```
Link to enterprise features page: https://dgraph.io/docs/enterprise-features/binary-backups/
___
*[wiki/content/ratel/connection.md, line 20 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6400#-MJhM8I16XUT6jrYDm-s:-MJhM8I16XUT6jrYDm-t:b-p0lpn0) ([raw file](https://github.com/dgraph-io/dgraph/blob/38608bcd5981cacaa16040dc2e75d4e1b59c0c74/wiki/content/ratel/connection.md#L20)):*
> ```
> . You just need to click on "Connect" that Ratel will be connected with the cluster.
> ```
After this sentence, you can write 'Then, click "Continue" to dismiss the connection box.'
___
*[wiki/content/ratel/connection.md, line 22 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6400#-MJhLrdF08aYaWTHxGQj:-MJhLrdF08aYaWTHxGQk:b-fen3zy) ([raw file](https://github.com/dgraph-io/dgraph/blob/38608bcd5981cacaa16040dc2e75d4e1b59c0c74/wiki/content/ratel/connection.md#L22)):*
> ```
> > Note: Some users confuses at this point. To connect to a basic Dgraph instance, you just need to click on "Connect" nothing else. There are places to login to ACL. Which is an enterpreise feature, if you're not using it, you don't need to login. After all green, finnaly click in "Continue" button.
> ```
You can omit this. We now hide ACL login fields if it's not enabled. Do keep the part about clicking "Continue".

**Comment by bucanero** [comment]
@danielmai @MichelDiz , do we still want to merge this PR?

I can take over and do the missing screenshots, just let me know

**Review by danielmai — COMMENTED** [review]
@bucanero We should have Ratel docs. So, let's finish up what needs to be done in this PR.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6400#-:-MP5cqB6A_9rN4fABVwc:bl9avkv)* status: all files reviewed, 3 unresolved discussions (waiting on @MichaelJCompton and @MichelDiz)

**Comment by MichelDiz** [comment]
Sorry for the delay here, @bucanero feel free to add any commit. Right now I'm focussed in other issues, so I would come back here.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 12 of 14 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6400#-:-MPLzdRvDzaCsY6nemSg:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @MichaelJCompton and @MichelDiz)

**Pull request merged**
