### PR TITLE
Support * P * deletion and lang tags in client.

### LINKED ISSUE #1253: can't set language tags in go client
there's no way to do something like

```
e = n.Edge("name@en")
```

in the go client

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #1253 and #1254.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1256)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1256#-:-KpxK48vRq9b8fn9cv12:bnfp4nl)*

**Comment by janardhan1993** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1256)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1256#-:-KpxN1EmFjIuy_EAWpTO:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
