### PR TITLE
Add byte to track the type of data throughout the pipeline.

### PR DESCRIPTION
**Pull request by kostub**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/231)

### CODE REVIEW

**Comment by kostub** [comment]
Hound is complaining about auto-generated flatbuffer code. Can't do much about it. Can we disable hound for the fb directories?

**Comment by manishrjain** [comment]
Couple of questions. This should be quick after that.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 127 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/231#-KSZVzcv7cd1EXRb3rkC:-KSZVzcxwOSob007_X2b:b-ujops6) ([raw file](https://github.com/dgraph-io/dgraph/blob/c440bf87390ac04dfa2f398f87faec8807b26cc5/posting/list.go#L127)):*
> ```Go
> 	}
> 	if a.ValType() != b.ValType() {
> 		return false
> ```

This should be checked first, it's faster.

---

*[rdf/parse.go, line 38 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/231#-KSZWSKofvhpcucnPTRy:-KSZWSKofvhpcucnPTRz:bt2vdlf) ([raw file](https://github.com/dgraph-io/dgraph/blob/c440bf87390ac04dfa2f398f87faec8807b26cc5/rdf/parse.go#L38)):*
> ```Go
> 	ObjectId    string
> 	ObjectValue []byte
> 	ObjectType  byte
> ```

not uint8?

---

*[x/x.go, line 62 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/231#-KSZWeRearHF0aJqq6Iv:-KSZWeRearHF0aJqq6Iw:b-8zdt1p) ([raw file](https://github.com/dgraph-io/dgraph/blob/c440bf87390ac04dfa2f398f87faec8807b26cc5/x/x.go#L62)):*
> ```Go
> 	Attribute string // Attribute or predicate. Labels the edge.
> 	Value     []byte // Edge points to a value.
> 	ValueType byte   // The type of the value
> ```

Not uint8?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/231#-:-KSZWhdf-wvplXMSaC-r:b-pjod0x)*

**Comment by kostub** [comment]
Review status: 8 of 9 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 127 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/231#-KSZVzcv7cd1EXRb3rkC:-KS_ZWLeIZxGNIU_c5oF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c440bf87390ac04dfa2f398f87faec8807b26cc5/posting/list.go#L127)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should be checked first, it's faster.
</details>
Done.

---

*[x/x.go, line 62 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/231#-KSZWeRearHF0aJqq6Iv:-KS_Zba8LbFPzqrHrjbn:bcpvqab) ([raw file](https://github.com/dgraph-io/dgraph/blob/c440bf87390ac04dfa2f398f87faec8807b26cc5/x/x.go#L62)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Not uint8?
</details>
Is there a difference? go docs say that byte is just an alias for uint8. Should I use one or the other in particular?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/231)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/231#-:-KSeGquRPTdfc9T2U9L6:bnfp4nl)*

**Pull request closed without merging**
