### PR TITLE
fix(fragment): merge the nested fragments fields (#8075)

### PR DESCRIPTION
**Pull request by dshekhar95**
## Problem
Fixes https://discuss.dgraph.io/t/graphql-field-collection-does-not-work-with-dgraph/15646

### CODE REVIEW

**Comment by dshekhar95** [comment]
Have tested locally, fix works. Need to add unit test case still

**Comment by MichelDiz** [comment]
@dshekhar95 Do you have a test proof? that I can run in my end. Looks like you have fixed and send it to the user PoolShark correct? So his example could be a test.

**Comment by matthewmcneely** [comment]
This one definitely needs tests.

**Comment by dshekhar95** [comment]
> @dshekhar95 Do you have a test proof? that I can run in my end. Looks like you have fixed and send it to the user PoolShark correct? So his example could be a test.
> 
> BTW, can you sign the CLA?

**Review by MichelDiz — APPROVED** [review]

**Review by matthewmcneely — APPROVED** [review]

**Review by meghalims — APPROVED** [review]
LGTM. Thanks for adding test. Please go ahead and merge it

**Pull request merged**
