### PR TITLE
fix: Return 404 status on non-existent API calls

### PR DESCRIPTION
**Pull request by vmrajas**
**Motivation**

Currently, making an API call to a non-existent path on alpha HTTP server such as "/admin/test" returns status as 200 (OK). As the path does not exist, status should be 404.
Related discuss issue: https://discuss.dgraph.io/t/dgraph-should-return-404-on-non-existent-api-paths/9574

**Components affected by this PR**
Dgraph alpha http server

**Does this PR break backwards compatibility?**:
No

**Testing**
Added two unit tests in dgraph/cmd/alpha/http_test.go .

This Pull Request fixes this.

**Fixes**
DGRAPH-2335

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6296)

### CODE REVIEW

**Review by arijitAD — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6296)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @arijitAD, @ashish-goswami, @harshil-goel, @manishrjain, @vmrajas, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/http_test.go, line 941 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6296#-MFp-_TO4wtTCaOlJ-EZ:-MFp-_TO4wtTCaOlJ-E_:brexvvy) ([raw file](https://github.com/dgraph-io/dgraph/blob/b75e226a1e19f29904b4bf679fba421b740c5f3d/dgraph/cmd/alpha/http_test.go#L941)):*
> ```Go
> 	resp, err := client.Do(req)
> 	require.NoError(t, err)
> 	require.True(t, resp.StatusCode == 404)
> ```

Use require.Equal()
___
*[dgraph/cmd/alpha/http_test.go, line 942 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6296#-MFp-ewF6UdXocoTNcH7:-MFp-ewF6UdXocoTNcH8:brexvvy) ([raw file](https://github.com/dgraph-io/dgraph/blob/b75e226a1e19f29904b4bf679fba421b740c5f3d/dgraph/cmd/alpha/http_test.go#L942)):*
> ```Go
> 	require.NoError(t, err)
> 	require.True(t, resp.StatusCode == 404)
> 	require.True(t, resp.Status == "404 Not Found")
> ```

Use require.Equal()

**Review by vmrajas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6296)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @arijitAD, @ashish-goswami, @harshil-goel, @manishrjain, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/http_test.go, line 941 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6296#-MFp-_TO4wtTCaOlJ-EZ:-MFpOT4148CBRKshLpIz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b75e226a1e19f29904b4bf679fba421b740c5f3d/dgraph/cmd/alpha/http_test.go#L941)):*
<details><summary><i>Previously, arijitAD (Arijit Das) wrote…</i></summary><blockquote>

Use require.Equal()
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/http_test.go, line 942 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6296#-MFp-ewF6UdXocoTNcH7:-MFpOTYeBNxR4NLf9O8I:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b75e226a1e19f29904b4bf679fba421b740c5f3d/dgraph/cmd/alpha/http_test.go#L942)):*
<details><summary><i>Previously, arijitAD (Arijit Das) wrote…</i></summary><blockquote>

Use require.Equal()
</blockquote></details>

Done.

**Review by vmrajas — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6296#-:-MFpQXAeA00-hgExnf02:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @arijitAD, @ashish-goswami, @harshil-goel, @manishrjain, and @vvbalaji-dgraph)

**Review by arijitAD — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6296#-:-MG4MUeM8nMv5f5hxni3:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @arijitAD, @ashish-goswami, @harshil-goel, @manishrjain, and @vvbalaji-dgraph)

**Pull request merged**
