### PR TITLE
[Breaking] chore(GraphQL): Remove dgraph.graphql.p_sha256hash predicate and merge it into dgraph.graphql.p_query

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes GraphQL-1017

We have also defined a new tokenizer on String of type `sha256` which concatenates the sha256 along with the query. The first 64 chars represent the `sha256` sum which is used to store the token. The second part of the input data is the query for persisted queries.

This change would mean that existing persisted queries don't work as expected unless the data for them is migrated.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7451)

### CODE REVIEW

**Review by jarifibrahim — APPROVED** [review]
:lgtm: would this be a breaking change for existing users?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7451#-:-MToRkXz50sXfOqTzo9y:bx7zmni)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @manishrjain and @vvbalaji-dgraph)

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
> Reviewed 14 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7451)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[ee/acl/acl_test.go, line 2176 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7451#-MToTYyGAYS77OTGPhDc:-MToTYyGAYS77OTGPhDd:b28dzwi) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6a119d7a17e3a0680a5480c47578a8cb2f5e539/ee/acl/acl_test.go#L2176)):*
> ```
> exact
> ```
sha
___
*[worker/export.go, line 651 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7451#-MToUUIyC0FQJuOtD8bg:-MToUUIzAtGtbyxBEYXG:b-5pzttj) ([raw file](https://github.com/dgraph-io/dgraph/blob/2c7de573090f700841b2d9bda2779c48349fedc5/worker/export.go#L651)):*
> ```
> 		case e.attr == "dgraph.graphql.p_sha256hash":
> 			// Ignore this predicate.
> ```
should we still keep this, but move it below together with the `dgraph.cors` and the other removed stuff?

**Review by pawanrawal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7451)* status: 7 of 16 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, and @vvbalaji-dgraph)

___
*[ee/acl/acl_test.go, line 2176 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7451#-MToTYyGAYS77OTGPhDc:-MTp2DQN8RkJOay2bGrx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6a119d7a17e3a0680a5480c47578a8cb2f5e539/ee/acl/acl_test.go#L2176)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> exact
> ```
sha
</blockquote></details>

Done.
___
*[worker/export.go, line 651 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7451#-MToUUIyC0FQJuOtD8bg:-MTp2Xgo1yaLPf9xnPmV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2c7de573090f700841b2d9bda2779c48349fedc5/worker/export.go#L651)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 		case e.attr == "dgraph.graphql.p_sha256hash":
> 			// Ignore this predicate.
> ```
should we still keep this, but move it below together with the `dgraph.cors` and the other removed stuff?
</blockquote></details>

Done.

**Review by abhimanyusinghgaur — APPROVED** [review]
> Reviewed 7 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7451)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/graphql.go, line 138 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7451#-MTp2lHd1gfS9mnG8ClT:-MTp2lHeEsxxvNKIv0V0:b-ujhr6n) ([raw file](https://github.com/dgraph-io/dgraph/blob/42cd7d1af3a628ca0cd820be51619683cc8d59e0/edgraph/graphql.go#L138)):*
> ```
> fmt.Printf("%+v\n", shaQueryRes.Me[0])
> ```
stale
___
*[tok/tok.go, line 393 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7451#-MTp3rEz387-cVO0i8Hq:-MTp3rEz387-cVO0i8Hr:b-npbnoh) ([raw file](https://github.com/dgraph-io/dgraph/blob/42cd7d1af3a628ca0cd820be51619683cc8d59e0/tok/tok.go#L393)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> 	if !ok || str == "" {
> 		return []string{}, nil
> 	}
> 	// The first 32 characters contain the sha256 for a query in hex format so
> 	// lets extract and index that part.
> 	if len(str) >= 64 {
> 		return []string{str[:64]}, nil
> 	}
> 	return []string{}, nil
> ```
</details>

can be simplified a bit:
```
	if !ok || len(str) < 64 {
		return []string{}, nil
	}
	// The first 32 characters contain the sha256 for a query in hex format so
	// lets extract and index that part.
	return []string{str[:64]}, nil

```

**Pull request merged**
