### PR TITLE
Feature/geq

### PR DESCRIPTION
**Pull request by jchiu0**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/382)

### CODE REVIEW

**Comment by jchiu0** [comment]
General idea: Say "geq / greater or equal" filter. We will look for the first token that is geq than value in inequality / right hand side of inequality. Then we iterate and get these all these tokens. This is done in worker. Also in worker, if we determine that the first token is equal to the RHS value, then we will need to do additional work. Namely, we need to actually get the values in PLs and compare against RHS value.

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-:-KYwV8q1s-k_djZ6vm86:b-g9wenr)*

**Comment by jchiu0** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/index.go, line 335 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KYwV1lSUHjcC8OrFAro-r1-335:-KYwVqn5usqtCds0YKU9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/25377c6130ad3e1fb52c467794ca0562c8c49e16/posting/index.go#L335)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

comment on exported method TokensTable.GetNextOrEqual should be of the form "GetNextOrEqual ..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382)*

**Comment by ashwin95r** [comment]
:lgtm: Just couple of minor comments.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query_test.go, line 793 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KYztKCL6wJyatqPRRfH:-KYztKCL6wJyatqPRRfI:bp445dk) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/query/query_test.go#L793)):*
> ```Go
> 
> 	var l Latency
> 	js, err := sg.ToJSON(&l)
> ```

Could use ProcessToJSON function here and tests below.

---

*[worker/task.go, line 236 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KYzw1OZ46foQwn5DyAe:-KYzw1OZ46foQwn5DyAf:b-ezopvc) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L236)):*
> ```Go
> 		return !scalarType.Less(sv, *ineqValue)
> 	}
> 	return !scalarType.Less(*ineqValue, sv)
> ```

Shall we make it `return scalarType.Less(sv, *ineqValue)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-:-KYzy9IN0bIi36_YMAQe:b6wf6m9)*

**Comment by ashwin95r** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382)*

**Comment by jchiu0** [comment]
Thanks for the review @ashwin.

---

Review status: 6 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query_test.go, line 793 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KYztKCL6wJyatqPRRfH:-KZ0TKQ_Mtz_7BEl2D4p:b-ek1haa) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/query/query_test.go#L793)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Could use ProcessToJSON function here and tests below.
</blockquote></details>

Good point. Also fixed other tests.

---

*[worker/task.go, line 236 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KYzw1OZ46foQwn5DyAe:-KZ0TMRHt49TC_1dMCd1:b-eis8j6) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L236)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Shall we make it `return scalarType.Less(sv, *ineqValue)`?
</blockquote></details>

Not quite. We need to return sv <= ineqValue, i.e., !(ineqValue < sv).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-:-KZ0TjF3JfMI1jdVGuDY:btmex5k)*

**Comment by manishrjain** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[types/sort.go, line 106 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0Xwjne21zGTAmyS7o:-KZ0XwjodAcqE1CWTLuQ:b-glzdop) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/types/sort.go#L106)):*
> ```Go
> 
> // Less returns true if a is strictly less than b.
> func (s Scalar) Less(a, b Value) bool {
> ```

This is awesome!

---

*[worker/task.go, line 91 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0V2RZgCC9RjJZYoxl:-KZ0V2RZgCC9RjJZYoxm:b-6w4kbd) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L91)):*
> ```Go
> 	// "2016". If 2016 is not found in TokensTable, ineqValue=nil. Otherwise,
> 	// ineqValue="2016-01-01".
> 	var ineqValue *types.Value
> ```

You could have a function to get just the tokens. Once you have the tokens, then you can call the Less() method to see if the first token is Less than this argument ("2016-01-01"), and if so, get the values for the intersection and compare. 

---

*[worker/task.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0IOoZfqZLhD4vI4MW:-KZ0IOo_NUv2ULD1LMOh:b-2kj5bd) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L94)):*
> ```Go
> 
> 	if useFunc {
> 		isGeq = q.SrcFunc[0] == "geq"
> ```

How about:

f := q.SrcFunc[0]

switch {
  case f == "geq":
    fallthrough
  case f == "leq":
    // logic
   case geo.IsGeoFunc(..):
    // logic
}

This would look better, I think.

---

*[worker/task.go, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0QBBoCEpk069uBnFW:-KZ0QBBoCEpk069uBnFX:b-nk1dfx) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L211)):*
> ```Go
> // checkInequality looks up value given key=(attr, uid). Then checks whether
> // PL's value satisfies the inequality.
> func checkInequality(key []byte, scalarType types.Scalar, isGeq bool,
> ```

I don't like functions which have more than 3 arguments. Seriously think a linter should complain when we have such a function.

To avoid 4 input args here, you could potentially have a function to retrieve the value, convert it; and then do the inequality check in the caller function instead.

---

*[worker/tokens.go, line 34 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0T0Erk-BvXnNBnqOi:-KZ0T0Erk-BvXnNBnqOj:bz4s9ff) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/tokens.go#L34)):*
> ```Go
> // value. Otherwise, we return the parsed value as nil.
> func getInequalityTokens(attr string, geq bool,
> 	funcArgs []string) ([]string, *types.Value, error) {
> ```

What is this types.Value thing? Seems like most of the times it's just nil. Can you avoid returning 3 values? It doesn't look clean when that happens. 2 is ideal, particularly when one of them is error.

In general, I think a function signature should have at max 3 params input and 2 params output at max. Otherwise, there should be a lint warning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382)*

**Comment by jchiu0** [comment]
Review status: 4 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[worker/task.go, line 91 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0V2RZgCC9RjJZYoxl:-KZ0n6_6ynUhC_yJBUIX:b-i9tk8h) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L91)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You could have a function to get just the tokens. Once you have the tokens, then you can call the Less() method to see if the first token is Less than this argument ("2016-01-01"), and if so, get the values for the intersection and compare. 
</blockquote></details>

Done. I will just check for equality.

---

*[worker/task.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0IOoZfqZLhD4vI4MW:-KZ0oz9HbNUyI-ysePzL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L94)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

How about:

f := q.SrcFunc[0]

switch {
  case f == "geq":
    fallthrough
  case f == "leq":
    // logic
   case geo.IsGeoFunc(..):
    // logic
}

This would look better, I think.
</blockquote></details>

Done.

---

*[worker/task.go, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0QBBoCEpk069uBnFW:-KZ0p7tAVty4L0P6v7Wv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L211)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I don't like functions which have more than 3 arguments. Seriously think a linter should complain when we have such a function.

To avoid 4 input args here, you could potentially have a function to retrieve the value, convert it; and then do the inequality check in the caller function instead.
</blockquote></details>

Done.

---

*[worker/task.go, line 236 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KYzw1OZ46foQwn5DyAe:-KZ0p9N2RBgHGCTve63i:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/task.go#L236)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Not quite. We need to return sv <= ineqValue, i.e., !(ineqValue < sv).
</blockquote></details>

Done.

---

*[worker/tokens.go, line 34 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-KZ0T0Erk-BvXnNBnqOi:-KZ0pC0zCdw7nd2N4mY4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab616b763ada01e7e949e524268b1e18b146750c/worker/tokens.go#L34)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What is this types.Value thing? Seems like most of the times it's just nil. Can you avoid returning 3 values? It doesn't look clean when that happens. 2 is ideal, particularly when one of them is error.

In general, I think a function signature should have at max 3 params input and 2 params output at max. Otherwise, there should be a lint warning.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-:-KZ0tvzBdkhYQG_7TVCX:bnfp4nl)*

**Comment by jchiu0** [comment]
Thanks for the suggestions.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/382#-:-KZ4fGwbWehz-W9JiE7_:b-yr7a7d)*

**Pull request closed without merging**
