### PR TITLE
Switch/keys

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1181)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-:-KozzXm9UuMNgka0cmiS:bnfp4nl)*

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/list.go, line 202 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-KpHazGdWcWAfROon8K0:-KpHazGdWcWAfROon8K1:bbrg2rt) ([raw file](https://github.com/dgraph-io/dgraph/blob/97bddd77e5ec9ec96e2bda5bf4795a5a9e92e5ab/posting/list.go#L202)):*
> ```Go
> 	*l = List{}
> 	l.key = key
> 	l.ghash = string(key)
> ```

Waste of memory space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181)*

**Comment by manishrjain** [comment]
@ashwin95r : Are you still working on this?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-:-KpR-UOqsWsC88sm8b9K:b-qm2paz)*

**Comment by ashwin95r** [comment]
Yes. I just switched the uint64 to string. Is there something more that we can do?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/list.go, line 202 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-KpHazGdWcWAfROon8K0:-KpSQLj8Bv-52PAcK94E:b6169gr) ([raw file](https://github.com/dgraph-io/dgraph/blob/97bddd77e5ec9ec96e2bda5bf4795a5a9e92e5ab/posting/list.go#L202)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Waste of memory space.
</blockquote></details>

You mean storing it as a string? If we don't store it'll be a copy every time we cast from []byte to string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-:-KpSQc86OouTe18tqw0F:blpuiyt)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/list.go, line 202 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-KpHazGdWcWAfROon8K0:-KpSSlo3WV0_VzYvwyyv:b7kcpsm) ([raw file](https://github.com/dgraph-io/dgraph/blob/97bddd77e5ec9ec96e2bda5bf4795a5a9e92e5ab/posting/list.go#L202)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

You mean storing it as a string? If we don't store it'll be a copy every time we cast from []byte to string
</blockquote></details>

That would only consume some cpu cycles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/list.go, line 202 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-KpHazGdWcWAfROon8K0:-KpUAcux1uz6SFyrL4PE:br2f38f) ([raw file](https://github.com/dgraph-io/dgraph/blob/97bddd77e5ec9ec96e2bda5bf4795a5a9e92e5ab/posting/list.go#L202)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

That would only consume some cpu cycles.
</blockquote></details>

Okay, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181)*

**Comment by manishrjain** [comment]
Hey @ashwin95r , can you finish up this PR? Address the comments (it says done, but they're not).

---

Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-:-Kq1F7DhKFHAL0VPmDvb:be4deu2)*

**Comment by ashwin95r** [comment]
Updated. 

A TODO to be considered: Sometimes when the strings are too long (For example on exact index on long texts) we might want to suggest the users switch to hash index to avoid keys that are large.

---

Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-:-Kq1JTAa4DTeGVtIaX_g:bh7qpax)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1181#-:-Kq1N6nZIPwA1_QHATRU:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
