### PR TITLE
Feature/admin

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/313)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 482 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyxt40i1d47__VFzdS:-KVyxt40i1d47__VFzdT:b7j0eqa) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L482)):*
> ```Go
> 	ip, _, err := net.SplitHostPort(r.RemoteAddr)
> 	if err != nil || ip != "127.0.0.1" {
> 		x.SetStatus(w, x.ErrorUnauthorized, "")
> ```

Add the IP address in the message. Also, you're not returning.

---

*[cmd/dgraph/main.go, line 491 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyxvaSBBOiujUY33HB:-KVyxvaSBBOiujUY33HC:b7j0eqa) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L491)):*
> ```Go
> 	ip, _, err := net.SplitHostPort(r.RemoteAddr)
> 	if err != nil || ip != "127.0.0.1" {
> 		x.SetStatus(w, x.ErrorUnauthorized, "")
> ```

Add the IP address in the message. Also, you're not returning.

---

*[cmd/dgraph/main.go, line 493 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyxp5S0X1Jo1yDjVGn:-KVyxp5S0X1Jo1yDjVGo:bkkgw3v) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L493)):*
> ```Go
> 		x.SetStatus(w, x.ErrorUnauthorized, "")
> 	}
> 	err = worker.StartBackup()
> ```

This needs to be updated.

---

*[cmd/dgraph/main.go, line 495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyy1VHy-YGQBdZ1uH7:-KVyy1VHy-YGQBdZ1uH8:b-rzocxt) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L495)):*
> ```Go
> 	err = worker.StartBackup()
> 	if err != nil {
> 		x.SetStatus(w, x.Error, "Backup Failed.")
> ```

missing return again! What happened -- if err ... return is like such a common thing.

---

*[contrib/queries.sh, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyyD3Lte34z-bcrYQK:-KVyyD3Lte34z-bcrYQL:ba504io) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/contrib/queries.sh#L37)):*
> ```Shell
> go build . && ./throughputtest --numsec 30 --ip "http://127.0.0.1:8080/query"  --numuser 100
> # shutdown Dgraph server.
> curl 127.0.0.1:8080/admin/shutdown -XPOST 
> ```

You don't really need -XPOST here, do you? Did you test this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/313)*

**Comment by pawanrawal** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 490 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KW0yrv8bpV5N_Lfz8C4:-KW0yrv8bpV5N_Lfz8C5:b-hgwkq) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L490)):*
> ```Go
> func backupHandler(w http.ResponseWriter, r *http.Request) {
> 	ip, _, err := net.SplitHostPort(r.RemoteAddr)
> 	if err != nil || ip != "127.0.0.1" {
> ```

This is fine for now, but would be restrictive later I feel. Client could be on a different machine than the server. Maybe we will move to having a username, password to access the database later like MySQL does.

---

*[contrib/queries.sh, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyyD3Lte34z-bcrYQK:-KW0yN7c8osoFKraJRyx:bblx28j) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/contrib/queries.sh#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You don't really need -XPOST here, do you? Did you test this change?
</details>
By default there are no restrictions on the Method, would be good to return an error if method != GET for both endpoints. We have a similar check for queryHandler to ensure it only responds to POST requests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/313)*

**Comment by manishrjain** [comment]
No updates on this PR?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-:-KW_YUcIQnpQWiCYbvqS:bcczq6k)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 482 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyxt40i1d47__VFzdS:-KWaMCNJnM2wlQM0z35M:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L482)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add the IP address in the message. Also, you're not returning.
</details>
Done.

---

*[cmd/dgraph/main.go, line 490 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KW0yrv8bpV5N_Lfz8C4:-KWaMGFYQNW9eROq8Bjv:b-80tlqk) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L490)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This is fine for now, but would be restrictive later I feel. Client could be on a different machine than the server. Maybe we will move to having a username, password to access the database later like MySQL does.
</details>
Sure.

---

*[cmd/dgraph/main.go, line 491 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyxvaSBBOiujUY33HB:-KWaMOKL3FS3u_X4pDkq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L491)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add the IP address in the message. Also, you're not returning.
</details>
Done.

---

*[cmd/dgraph/main.go, line 493 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyxp5S0X1Jo1yDjVGn:-KWaNmBDTMl2ldil46y9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L493)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This needs to be updated.
</details>
Done.

---

*[cmd/dgraph/main.go, line 495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyy1VHy-YGQBdZ1uH7:-KWaMPUWSUKliGkXrs-c:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/cmd/dgraph/main.go#L495)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> missing return again! What happened -- if err ... return is like such a common thing.
</details>
Done.

---

*[contrib/queries.sh, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KVyyD3Lte34z-bcrYQK:-KWaMWlLyqqtjxsW9Jey:bih6sq4) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4dbe29df6fca8cba35a9cc2d55f02a09c249f9d/contrib/queries.sh#L37)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> By default there are no restrictions on the Method, would be good to return an error if method != GET for both endpoints. We have a similar check for queryHandler to ensure it only responds to POST requests.
</details>
Yeah -XPOST is not compulsory as we dont check for the method. Modified it to GET only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/313)*

**Comment by pawanrawal** [comment]
A couple of small things, apart from that. :lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 505 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KWadYbpE8yH0QZ_0La4:-KWadYbpE8yH0QZ_0La5:b-5zaip8) ([raw file](https://github.com/dgraph-io/dgraph/blob/342a365ee526978258679795a98fea28a0f27565/cmd/dgraph/main.go#L505)):*
> ```Go
> 	ip, _, err := net.SplitHostPort(r.RemoteAddr)
> 	if err != nil || ip != "127.0.0.1" {
> 		x.SetStatus(w, x.ErrorUnauthorized, fmt.Sprintf("Request from IP: %v", ip))
> ```

Could return something like
`Request received from IP: %v. Only requests from 127.0.0.1 are allowed.`

---

*[cmd/dgraph/main.go, line 511 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KWadHmTjl70R5JGuy7I:-KWadHmTjl70R5JGuy7J:bba6ads) ([raw file](https://github.com/dgraph-io/dgraph/blob/342a365ee526978258679795a98fea28a0f27565/cmd/dgraph/main.go#L511)):*
> ```Go
> 	ctx := context.Background()
> 	worker.BackupOverNetwork(ctx)
> 	x.SetStatus(w, x.ErrorOk, "Backup completed.")
> ```

Are we ensured that backup is complete at this step (are there no go routines which we don't wait for) or does this indicate that backup started?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-:-KWadmQrAKe3Lrq9S2wd:b-ari828)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/dgraph/main.go, line 505 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KWadYbpE8yH0QZ_0La4:-KWah7Z7PvrZXBenaQF0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/342a365ee526978258679795a98fea28a0f27565/cmd/dgraph/main.go#L505)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Could return something like
> `Request received from IP: %v. Only requests from 127.0.0.1 are allowed.`
</details>
Done.

---

*[cmd/dgraph/main.go, line 511 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-KWadHmTjl70R5JGuy7I:-KWagYTDjsP4eHJSxomT:bckaq2l) ([raw file](https://github.com/dgraph-io/dgraph/blob/342a365ee526978258679795a98fea28a0f27565/cmd/dgraph/main.go#L511)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Are we ensured that backup is complete at this step (are there no go routines which we don't wait for) or does this indicate that backup started?
</details>
Yeah. The function returns once the backup is completed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/313)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/313#-:-KWeTsD_V4y4JThzP7ka:bnfp4nl)*

**Comment by ashwin95r** [comment]
Thanks for the review. Merged.

**Pull request closed without merging**
