### PR TITLE
Context/checks

### PR DESCRIPTION
**Pull request by ashwin95r**
Check context in processTask to avoid processing after timeout.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1234)

### CODE REVIEW

**Comment by tzdybal** [comment]
One general question - is it really necessary and reasonable to check context in every loop iteration? 
First changed loop can result in IO operations, so it seems reasonable for me, but the later cases are not that clear to me. 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-:-KpmQjpukhvX3NbIkvKy:b-ax7d7c)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 303 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-Kpmpat9I_gKJUhHREWZ:-Kpmpat9I_gKJUhHREW_:b-gj53fw) ([raw file](https://github.com/dgraph-io/dgraph/blob/275e720f5948d3cdc8e85a56b8ba121c8b9132ee/worker/task.go#L303)):*
> ```Go
> 		case AggregatorFn, PasswordFn:
> 			key = x.DataKey(attr, q.UidList.Uids[i])
> 		default:
> ```

we need index key for CompareAttrFn, GeoFn, RegexFn, FullTextSearchFn, StandardFn , so add a case with these  and fatalf in default.

---

*[worker/task.go, line 547 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-KpmqdJSStHmmO8OGZ4b:-KpmqdJSStHmmO8OGZ4c:b-xtdyar) ([raw file](https://github.com/dgraph-io/dgraph/blob/275e720f5948d3cdc8e85a56b8ba121c8b9132ee/worker/task.go#L547)):*
> ```Go
> 	if srcFn.fnType == CompareAttrFn && len(srcFn.tokens) > 0 {
> 		select {
> 		case <-ctx.Done():
> ```

Is this necessary ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234)*

**Comment by ashwin95r** [comment]
Right, makes sense to have the checks only in the loops that might involve IO. Made the changes.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 303 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-Kpmpat9I_gKJUhHREWZ:-KpmxNFLlLMOk8Rga0Bq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/275e720f5948d3cdc8e85a56b8ba121c8b9132ee/worker/task.go#L303)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

we need index key for CompareAttrFn, GeoFn, RegexFn, FullTextSearchFn, StandardFn , so add a case with these  and fatalf in default.
</blockquote></details>

Done.

---

*[worker/task.go, line 547 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-KpmqdJSStHmmO8OGZ4b:-KpmyZL9CNelFzRdrzCt:bcu0kur) ([raw file](https://github.com/dgraph-io/dgraph/blob/275e720f5948d3cdc8e85a56b8ba121c8b9132ee/worker/task.go#L547)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Is this necessary ?
</blockquote></details>

Removing it from places that don't involve a value fetches. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-:-KpmyjWI7w11WK07HOrS:b-auscdy)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/task.go, line 226 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-KpnJF7qKxddrvHqoV0b:-KpnJF7rpJb_umTVvz0X:b-72kfrr) ([raw file](https://github.com/dgraph-io/dgraph/blob/26a8f4a0e512bff1427515d99e6e702e630ef637/worker/task.go#L226)):*
> ```Go
> 	for _, uid := range q.UidList.Uids {
> 		select {
> 		case <-ctx.Done():
> ```

If this is a purely CPU loop, then no need to check context at every iteration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/task.go, line 226 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-KpnJF7qKxddrvHqoV0b:-KpnL_l_hbb-CKUFh5vN:b-s8nwwd) ([raw file](https://github.com/dgraph-io/dgraph/blob/26a8f4a0e512bff1427515d99e6e702e630ef637/worker/task.go#L226)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If this is a purely CPU loop, then no need to check context at every iteration.
</blockquote></details>

There can be disk IO in `getPredList`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234)*

**Comment by tzdybal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-:-KprNHjYjXpGYK279Ayj:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1234#-:-Kprre2Gp6ANKq_KxW_j:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
