### PR TITLE
Add helper functions for sending a mutation

### PR DESCRIPTION
**Pull request by pawanrawal**
The associated code for the Go client is here.
https://github.com/dgraph-io/dgraphgoclient/pull/6

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/203)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 175 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR7jxr7zKaKWnSgJ43y:-KR7jxr7zKaKWnSgJ43z:b-kltxba) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L175)):*
> ```Go
> 	var err error
> 
> 	set := mutationToNQuad(mu.Set)
> ```

Though we already get the mutation as a slice of graph.NQuad, we still have them to convert them to rdf.NQuad. Another way around this would be to define the NQuad struct in a proto file inside the rdf package and then import it into the `graphresponse.proto`. 

Though I would also have to import the rdf package(with its dependencies) into the Go client if I do that. Not sure how to avoid that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/203)*

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 151 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8dg9xQJAfZooT9Nle:-KR8dg9xQJAfZooT9Nlf:b-ek9c2w) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L151)):*
> ```Go
> 
> func mutationToNQuad(nq []*graph.NQuad) []rdf.NQuad {
> 	var resp []rdf.NQuad
> ```

initiate the right size.

---

*[cmd/dgraph/main.go, line 175 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR7jxr7zKaKWnSgJ43y:-KR8ds-WepqluIhUAg5q:bnqullp) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L175)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Though we already get the mutation as a slice of graph.NQuad, we still have them to convert them to rdf.NQuad. Another way around this would be to define the NQuad struct in a proto file inside the rdf package and then import it into the `graphresponse.proto`. 
> 
> Though I would also have to import the rdf package(with its dependencies) into the Go client if I do that. Not sure how to avoid that.
</details>
OK. I think it's alright to keep them separate.

---

*[cmd/dgraph/main.go, line 193 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8jh2D-R_F23SmwoLU:-KR8jh2D-R_F23SmwoLV:b-x0btoj) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L193)):*
> ```Go
> // This function is used to run mutations for the requests received from the
> // http client.
> func mutationHandler(ctx context.Context, mu *gql.Mutation) error {
> ```

This func and above have common stuff going on. share that logic.

---

*[cmd/dgraph/main.go, line 205 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8e5v5vZwrmBVSt_NX:-KR8e5v5vZwrmBVSt_NY:b-pnveuv) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L205)):*
> ```Go
> 		return x.Wrap(err)
> 	}
> ```

Remove vertical spaces in all these if conds.

---

*[cmd/dgraph/main.go, line 330 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8j8yoBv1F7bXQLXji:-KR8j8yoBv1F7bXQLXjj:bha6be4) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L330)):*
> ```Go
> 	l.Start = time.Now()
> 	x.Trace(ctx, "Query received: %v", req.Query)
> 	gq, _, err := gql.Parse(req.Query)
> ```

The mutations can still come in via the query, right? That ability shouldn't be removed. Not all clients might implement such helper functions for mutations.

---

*[query/graph/graphresponse.proto, line 12 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8iroZFTmA4iyQ6yMj:-KR8iroZFTmA4iyQ6yMk:b-c4hxch) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/query/graph/graphresponse.proto#L12)):*
> ```protobuf
> 
> message NQuad {
> 	string sub = 1;
> ```

expand tabs.

---

*[query/graph/graphresponse.proto, line 26 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8i7q2bw8E8R7HOUTD:-KR8i7q32wbt4_TQccUm:b-c1odr) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/query/graph/graphresponse.proto#L26)):*
> ```protobuf
> message Request {
> 	string query = 1;
> 	Mutation m = 2;
> ```

Mutation mutation = 2;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/203)*

**Comment by pawanrawal** [comment]
Please also have a look at https://reviewable.io/reviews/dgraph-io/dgraphgoclient/6#-

---

Review status: 1 of 4 files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 151 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8dg9xQJAfZooT9Nle:-KR9Rnnmk6KKjdJQ1bKP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L151)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> initiate the right size.
</details>
Done.

---

*[cmd/dgraph/main.go, line 193 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8jh2D-R_F23SmwoLU:-KR9Q_YFfCQfNXCL1XWT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L193)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This func and above have common stuff going on. share that logic.
</details>
Done.

---

*[cmd/dgraph/main.go, line 205 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8e5v5vZwrmBVSt_NX:-KR9NtVkbVw_WoQcN9pC:bq09pen) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L205)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove vertical spaces in all these if conds.
</details>
Okay, I thought we followed the convention of having a vertical space after a return.

---

*[cmd/dgraph/main.go, line 330 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8j8yoBv1F7bXQLXji:-KR9Ri3pN-TX9wnW_xXn:byr4flj) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L330)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> The mutations can still come in via the query, right? That ability shouldn't be removed. Not all clients might implement such helper functions for mutations.
</details>
Right.

---

*[query/graph/graphresponse.proto, line 12 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8iroZFTmA4iyQ6yMj:-KR9Rkx1-bevvyMPROy3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/query/graph/graphresponse.proto#L12)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> expand tabs.
</details>
Done.

---

*[query/graph/graphresponse.proto, line 26 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8i7q2bw8E8R7HOUTD:-KR9RlR3Gjx9QwEHixt8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/query/graph/graphresponse.proto#L26)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Mutation mutation = 2;
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-:-KR9Zbyhgicc3BP47gsg:bj0uwin)*

**Comment by manishrjain** [comment]
:lgtm: Feel free to submit!

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 205 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-KR8e5v5vZwrmBVSt_NX:-KRSCaLi6q_FM6TMbFND:bi9oc04) ([raw file](https://github.com/dgraph-io/dgraph/blob/c9f88fbda39c77161b3669e8969550394546a666/cmd/dgraph/main.go#L205)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Okay, I thought we followed the convention of having a vertical space after a return.
</details>
LGTM. Actually, if there's a '}' in a separate vertical line, which generally is the case, we can avoid another vertical space. I think '}' sort of acts like a vertical space itself. But, feel free to ignore. It's probably a personal preference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/203#-:-KRSp9WvnmgM4SoxspI2:b-vq34k3)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
