### PR TITLE
Allow has queries without a count index.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1712)

### CODE REVIEW

**Comment by peterstace** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/task.go, line 1521 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KxuC3zggn-m1apaeiJP:-KxuC3zggn-m1apaeiJQ:b-8vfnjg) ([raw file](https://github.com/dgraph-io/dgraph/blob/71941a4efd618f7935c3dd201bee3086a1ba2472/worker/task.go#L1521)):*
> ```Go
> // Handle languages.
> func handleHasFunction(ctx context.Context, q *protos.Query, out *protos.Result) error {
> 	mu := &sync.Mutex{}
> ```

This doesn't have to be a pointer. Couldn't we just have `var mu sync.Mutex` and capture it in the spawned goroutines?

---

*[worker/task.go, line 1557 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KxuEOImq1Ur55bMhN98:-KxuEOImq1Ur55bMhN99:b-118epv) ([raw file](https://github.com/dgraph-io/dgraph/blob/71941a4efd618f7935c3dd201bee3086a1ba2472/worker/task.go#L1557)):*
> ```Go
> 			for it.Seek(startKey); it.ValidForPrefix(prefix); it.Next() {
> 				pk := x.Parse(it.Item().Key())
> 				if pk.Attr != q.Attr {
> ```

The prefix includes the attribute, so shouldn't this never happen?

---

*[worker/task.go, line 1601 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KxuFIi8nz_RQF4jbHNn:-KxuFIi8nz_RQF4jbHNo:bhuxfnv) ([raw file](https://github.com/dgraph-io/dgraph/blob/71941a4efd618f7935c3dd201bee3086a1ba2472/worker/task.go#L1601)):*
> ```Go
> 				finalErr = err
> 			}
> 		case <-ctx.Done():
> ```

You don't have to check `ctx.Done` here since a cancelled context would cause the goroutines to give an error anyway. We still have to wait for all goroutines to complete in any case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712)*

**Comment by peterstace** [comment]
I'm not sure how effective partitioning for doing the iteration in parallel would be. The first partition would be for uids from 1 to `2^59`. I suspect for most cases, all uids would fall into the first partition since we assign new UIDs somewhat sequentially. So one goroutine would do all the work and the other 31 would do nothing.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-:-KxuGQxPiM-6KkwwP9wB:b-ns307u)*

**Comment by pawanrawal** [comment]
We just have one loop now.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/task.go, line 1521 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KxuC3zggn-m1apaeiJP:-KyEv3Rl8c5fr34ibM3b:b-jefn8q) ([raw file](https://github.com/dgraph-io/dgraph/blob/71941a4efd618f7935c3dd201bee3086a1ba2472/worker/task.go#L1521)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

This doesn't have to be a pointer. Couldn't we just have `var mu sync.Mutex` and capture it in the spawned goroutines?
</blockquote></details>

We don't need the mutex anymore. 

---

*[worker/task.go, line 1557 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KxuEOImq1Ur55bMhN98:-KyEv8fcytygMJzPfxLM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71941a4efd618f7935c3dd201bee3086a1ba2472/worker/task.go#L1557)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

The prefix includes the attribute, so shouldn't this never happen?
</blockquote></details>

Done.

---

*[worker/task.go, line 1601 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KxuFIi8nz_RQF4jbHNn:-KyEvAdr2jf7zNDJu4CM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71941a4efd618f7935c3dd201bee3086a1ba2472/worker/task.go#L1601)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

You don't have to check `ctx.Done` here since a cancelled context would cause the goroutines to give an error anyway. We still have to wait for all goroutines to complete in any case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-:-KyEuv7TiMdHv4lfZkc8:b-43zfkn)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-:-KyFS_jC_e_D-y-EiA9T:bnfp4nl)*

**Comment by peterstace** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[worker/task.go, line 1523 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KxuzUii6ShHAmzQLlMg:-KxuzUii6ShHAmzQLlMh:b-risvlk) ([raw file](https://github.com/dgraph-io/dgraph/blob/71941a4efd618f7935c3dd201bee3086a1ba2472/worker/task.go#L1523)):*
> ```Go
> 	mu := &sync.Mutex{}
> 	tlist := &protos.List{}
> 	numPart := uint64(32)
> ```

No need to do all that.

---

*[worker/task.go, line 1517 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KyPgU8UTt3Z-Qd_matY:-KyPgU8UTt3Z-Qd_matZ:b-3tcgqr) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcb5e7d2d157e86e59d4781337ee38d1d224531/worker/task.go#L1517)):*
> ```Go
> }
> 
> // TODO - Check that on deletion we delete the key-val from Badger.
> ```

Remove this TODO.

---

*[worker/task.go, line 1543 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-KyPgQRKxOJjB6O5bwoF:-KyPgQRKxOJjB6O5bwoG:bgayddc) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcb5e7d2d157e86e59d4781337ee38d1d224531/worker/task.go#L1543)):*
> ```Go
> 	for it.Seek(startKey); it.ValidForPrefix(prefix); it.Next() {
> 		pk := x.Parse(it.Item().Key())
> ```

Add a TODO to check meta for empty PL and skip it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1712#-:-KyPgWohtBY7BbLb177F:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
