### PR TITLE
[WIP] Test setup to run GraphQL layer

### PR DESCRIPTION
**Pull request by hackintoshrao**
- Adding the GraphQL server to the default docker-compose file used for
  unit-tests.
- Adding the service to initialize the GraphQL layer with a simple schema.
- Adding the simple schema file.
- Able to send GraphQL mutations and query requests to the GraphQL service run using the docker compose file.
Screenshot 2019-08-09 at 4 25 40 PM

- Need to finish the tests for sending the GraphQL requests and validate responses. 
- The docker compose file can run in isolation, 
    - Set $GOPATH. 
    - Have the binary build for linux in $GOPATH/bin 
    - Docker compose up

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3782)

### CODE REVIEW

**Comment by hackintoshrao** [comment]
The last two commits contain typo-fixes, will `squash and merge` after the review.

**Comment by mangalaman93** [comment]
This docker-compose file should generally be used for automated testing. Doesn't make a lot sense to modify it for manual testing.

**Comment by hackintoshrao** [comment]
@mangalaman93 : This is actually for the unit tests that will be added to the GraphQL layer. Tests that are similar to the existing `http_test`. When unit tests are run, the modifications made to docker-compose will also start the GraphQL layer, then runs GraphQL queries and validates the response. In the next set of commits will be adding these tests.

**Comment by mangalaman93** [comment]
Where are the tests?

**Comment by hackintoshrao** [comment]
Forgot to mention, it's WIP.

**Comment by hackintoshrao** [comment]
Looks like I've merged this branch with master! Let me fix it.

**Comment by hackintoshrao** [comment]
Closed this PR in favor of a new one.

**Pull request closed without merging**
