### PR TITLE
chore(test): Remove Ratel from tests and example configs.

### PR DESCRIPTION
**Pull request by danielmai**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7738)

### CODE REVIEW

**Review by darkn3rd — APPROVED** [review]
Have all of the contributions been tested as functional:

- [ ] CloudFormation (contrib/config/marketplace)
- [ ] Backups (client, gcp, azure, nfs, s3)
- [ ] Kubernetes (single, ha)
- [ ] Terraform / AWS (contrib/config/terraform/aws)
- [ ] Terraform / GCP (contrib/config/terraform/gcp)
- [ ] Terrafrom / K8S (contrib/config/terraform/kubernetes)
- [ ] Systemd / CentOS (contrib/systemd/centos)
- [ ] Standalone

**Comment by 1Const1** [comment]
Could you please explain why you removed ratel everywhere? If someone want it they can do it by themselves

**Comment by aranwe** [comment]
I assume these configs are used in CI - however they are directly linked from documentation: https://dgraph.io/docs/deploy/kubernetes/ and without Ratel the `Test Single Server Setup`  (and the `Test Dgraph HA Cluster Setup
`) doesn't work :)

**Comment by tonicebrian** [comment]
> I assume these configs are used in CI - however they are directly linked from documentation: https://dgraph.io/docs/deploy/kubernetes/ and without Ratel the `Test Single Server Setup` (and the `Test Dgraph HA Cluster Setup `) doesn't work :)

I'm exactly at this point. Trying to test DGraph following those instructions and stuck because I haven't Ratel. How can I install it in any of those clusters?

**Comment by danhawkins** [comment]
Not sure how to get a browser UI up for docker compose now ratel is moved 😕

**Comment by rzyns** [comment]
If Ratel is removed from all of the example configs, shouldn't the documentation be updated?

**Comment by BrunoPujos** [comment]
Hello,

So I have a small project where I need a graph database and I decided to try and use DGraph for it. I never used it before so please keep in mind that I have no idea how your software works. Anyway I tried to follow your tutorials:

* https://dgraph.io/docs/get-started/
* https://www.youtube.com/watch?v=u73ovhDCPQQ&ab_channel=DgraphLabs

Both of those (which seems the official ones, if I'm correct) encourage to use `Ratel`, however your last release does not seems to include `Ratel`. It seems to have been deleted by this PR. It is absolutely not clear to me why it has been removed or if there is any replacement. I suppose there is a good reason for this but, from a new user point of view, this is really disturbing. If the experience for new user is an important point for you, you may want to either: update your tutorials or make a docker version with `Ratel` specifically for your tutorials.

Anyway for people encountering this same problem, running: `docker run --rm -it -p "8080:8080" -p "9080:9080" -p "8000:8000" -v ~/dgraph:/dgraph "dgraph/standalone:v21.03.0"` (so the release before the last one at the time of this comment) seems to work just fine.

Have a nice day.

**Comment by nlp4whp** [comment]
so how could I use Ratel with the latest(`dgraph/standalone:v21.12.0`) 
or other tools like Ratel?
:(

**Pull request merged**
