### PR TITLE
Switch Raft WAL to use simple files

### PR DESCRIPTION
**Pull request by manishrjain**
This PR switches the way we store Raft write-ahead log. Before we were using Badger, but it caused a bunch of latency issues due to a high number of key deletions. With this change, we are using mmapped files, which can be deleted directly when not needed. This speeds up the Raft execution quite significantly. We no longer see any quorum issues and so on. The exact description of how these files work is in raftwal/storage.go.

This PR also removes a whole bunch of flags around how WAL living on Badger was initialized.

This PR introduces a concept of fault tolerance level. It adds a new flag `--survive`, which can choose between "process" or "filesystem". Most users should be OK with just process crashes and don't need to opt for filesystem crashes. In that case, they can gain huge speedups, because mmaped files can easily survive process crashes without calling expensive msync.

This PR also refactors common flags between Alpha and Zero and how they are parsed.

Fixes DGRAPH-2487

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6572)

 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-c2b2321cfa-97590.surge.sh)

### CODE REVIEW

**Review by manishrjain — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6572)* status: 0 of 25 files reviewed, 17 unresolved discussions

___
*[dgraph/cmd/zero/raft.go, line 749 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPOIff7tMzCOtoECrk:-MIPOIfg14IgZ8fECj_p:boqwrej) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/dgraph/cmd/zero/raft.go#L749)):*
> ```Go
> 			timer.Record("disk")
> 			span.Annotatef(nil, "Saved to storage")
> 			if x.WorkerConfig.HardSync && rd.MustSync {
> ```

Also set this in Alpha.
___
*[dgraph/cmd/zero/run.go, line 55 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPOPkq8jcPnuJBa316:-MIPOPkq8jcPnuJBa317:b-l17bir) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/dgraph/cmd/zero/run.go#L55)):*
> ```Go
> 	w                 string
> 	rebalanceInterval time.Duration
> 	LudicrousMode     bool
> ```

Probably not required either.
___
*[dgraph/cmd/zero/run.go, line 56 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPOOfpA51CdkEniJO6:-MIPOOfpA51CdkEniJO7:b-fraaar) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/dgraph/cmd/zero/run.go#L56)):*
> ```Go
> 	rebalanceInterval time.Duration
> 	LudicrousMode     bool
> 	hardSync          bool
> ```

Not required.
___
*[dgraph/cmd/zero/run.go, line 185 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPOj1R-vCMl_lrXCyU:-MIPOj1R-vCMl_lrXCyV:b-r3blyx) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/dgraph/cmd/zero/run.go#L185)):*
> ```Go
> 
> 	survive := Zero.Conf.GetString("survive")
> 	x.AssertTruef(survive == "process" || survive == "filesystem", "Invalid survival mode: %s", survive)
> ```

overflow.
___
*[dgraph/cmd/zero/run.go, line 187 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPOv7O8OvXld14_GcB:-MIPOv7O8OvXld14_GcC:bvfdvx3) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/dgraph/cmd/zero/run.go#L187)):*
> ```Go
> 	x.AssertTruef(survive == "process" || survive == "filesystem", "Invalid survival mode: %s", survive)
> 
> 	x.WorkerConfig = x.WorkerOptions{
> ```

Can be refactored out.
___
*[dgraph/cmd/zero/run.go, line 298 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPP5Eh-_3uWbJye_5j:-MIPP5Eh-_3uWbJye_5k:b-cak6v0) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/dgraph/cmd/zero/run.go#L298)):*
> ```Go
> 		st.node.trySnapshot(0)
> 		// Stop Raft store.
> 		store.Sync()
> ```

Look at this. Do we still need closer. Maybe we should be doing a close here or below.
___
*[raftwal/log.go, line 76 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPPR6v2nIALGOkPlT0:-MIPPR6v2nIALGOkPlT1:b-a8onpi) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L76)):*
> ```Go
> // entryFile objects.
> type entryLog struct {
> 	// need lock for files and current ?
> ```

Store has the lock. This comment can be removed or clarified.
___
*[raftwal/log.go, line 148 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPPmy30uldolW52QgZ:-MIPPmy30uldolW52Qg_:bmo7zmc) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L148)):*
> ```Go
> }
> 
> func (l *entryLog) rotate(firstIndex uint64) error {
> ```

Add a bunch of comments.
___
*[raftwal/log.go, line 169 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPPyM35ozFw3YFGjP7:-MIPPyM35ozFw3YFGjP8:bplwd64) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L169)):*
> ```Go
> }
> 
> func (l *entryLog) numEntries() int {
> ```

This is incorrect. Remove.
___
*[raftwal/log.go, line 192 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPQYiqDJCCGt-iXhNK:-MIPQYiqDJCCGt-iXhNL:b-aojyuo) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L192)):*
> ```Go
> 		// fmt.Printf("AddEntries: fidx: %d, eidx: %d num: %d\n", fidx, eidx, len(entries))
> 
> 		if fidx == -1 {
> ```

Add a comment about what this is doing.
___
*[raftwal/log.go, line 214 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPQnv68F0jDSGKdXwJ:-MIPQnv68F0jDSGKdXwK:bu7syw3) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L214)):*
> ```Go
> 	}
> 
> 	prev := l.nextEntryIdx - 1
> ```

Add comment about jumping back.
___
*[raftwal/log.go, line 227 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPRB2C9aOT502CyWWr:-MIPRB2C9aOT502CyWWs:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L227)):*
> ```Go
> 		if l.nextEntryIdx >= maxNumEntries {
> 			if err := l.rotate(re.Index); err != nil {
> 				// TODO: see what happens.
> ```

Remove this.
___
*[raftwal/log.go, line 343 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPT1ZOAdFJ6d3BYixZ:-MIPT1ZOAdFJ6d3BYix_:bqdi9l3) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L343)):*
> ```Go
> 		fileIdx = len(l.files) - 1
> 	}
> 	for fileIdx > 0 {
> ```

Add a comment here that some files might not have been initialized, in which case skip those.

Maybe add an Assert here. Because this logic seems unnecessary.
___
*[raftwal/log.go, line 385 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPTeA25C_6yfYFimyx:-MIPTeA25C_6yfYFimyy:b-3qzprq) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L385)):*
> ```Go
> 	zeroOut(l.current.data, 0, entryFileOffset)
> 	var num int
> 	for _, b := range l.current.data[:entryFileOffset] {
> ```

Don't need to do this anymore.
___
*[raftwal/log.go, line 428 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPTr2l91l95d3AjVq1:-MIPTr2l91l95d3AjVq2:b-om60k0) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L428)):*
> ```Go
> 			return entries
> 		}
> 		if re.Index == 0 {
> ```

Add a comment here to explain.
___
*[raftwal/log.go, line 573 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPS5NM69dDHCjSy5X_:-MIPS5NM69dDHCjSy5Xa:b82bxy5) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L573)):*
> ```Go
> 	fi := ef.firstIndex()
> 	// If first index is zero, this raftindex should be in a previous file.
> 	if fi == 0 {
> ```

Combine this and below if.
___
*[raftwal/log.go, line 579 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPSKd38sJtRb245ukk:-MIPSKd38sJtRb245ukl:b-huzuzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L579)):*
> ```Go
> 		return -1
> 	}
> 	if diff := int(raftIndex - fi); diff < maxNumEntries && diff >= 0 {
> ```

Add a comment here saying that this is an optimization.

**Review by martinmr — COMMENTED** [review]
> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6572)* status: 0 of 25 files reviewed, 20 unresolved discussions (waiting on @manishrjain and @martinmr)

___
*[raftwal/log.go, line 76 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPPR6v2nIALGOkPlT0:-MIQJlEDBl3KZHOeIsbr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L76)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Store has the lock. This comment can be removed or clarified.
</blockquote></details>

Done.
___
*[raftwal/log.go, line 169 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPPyM35ozFw3YFGjP7:-MIQL4bX28CPOQnN4wtC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L169)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This is incorrect. Remove.
</blockquote></details>

Done.
___
*[raftwal/log.go, line 192 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPQYiqDJCCGt-iXhNK:-MIQNdDw4aKAkezyJyyI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L192)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment about what this is doing.
</blockquote></details>

Done.
___
*[raftwal/log.go, line 214 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPQnv68F0jDSGKdXwJ:-MIQQMx6Axy07dIXLuqu:bs7wupf) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L214)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add comment about jumping back.
</blockquote></details>

Done.z
___
*[raftwal/log.go, line 227 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPRB2C9aOT502CyWWr:-MIQQLu8EuXiAgi2E2EE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L227)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

Done.
___
*[raftwal/log.go, line 343 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPT1ZOAdFJ6d3BYixZ:-MIQUoH0AQsXXut4lo_x:bnlubtr) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L343)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment here that some files might not have been initialized, in which case skip those.

Maybe add an Assert here. Because this logic seems unnecessary.
</blockquote></details>

Removed this logic and the tests fail. What this is doing is going through the list of files until it finds the right file in which to look for the raftIndex. I've added a comment.
___
*[raftwal/log.go, line 385 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPTeA25C_6yfYFimyx:-MIQVVEDD5qpiz7Fh4Ho:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L385)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't need to do this anymore.
</blockquote></details>

Done.
___
*[raftwal/log.go, line 428 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPTr2l91l95d3AjVq1:-MIQXrtmALP6dRBulRah:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L428)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment here to explain.
</blockquote></details>

Done.
___
*[raftwal/log.go, line 548 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIQbb0YE4t361vedYVr:-MIQbb0YE4t361vedYVs:bx5pbu7) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L548)):*
> ```Go
> 	// This would return the first pos, where e.Index() == 0.
> 	pos := ef.firstEmptySlot()
> 	if pos > 0 {
> ```

this will be a problem if the first empty slot is 0 because `pos--` will be negative.
___
*[raftwal/log.go, line 573 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPS5NM69dDHCjSy5X_:-MIQcW_V-02v7fbSi6CS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L573)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Combine this and below if.
</blockquote></details>

Done.
___
*[raftwal/log.go, line 579 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIPSKd38sJtRb245ukk:-MIQczsb7gXrUD3IhCjt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/log.go#L579)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment here saying that this is an optimization.
</blockquote></details>

Done.
___
*[raftwal/storage.go, line 77 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIQdJJR1R7VE76MeEV5:-MIQdJJR1R7VE76MeEV6:b-d4kt9i) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/storage.go#L77)):*
> ```Go
> // sync would have already flushed the mmap to disk. mmap deals with process crashes just fine. So,
> // we're good there. In case of file system crashes or disk crashes, we might need to replace this
> // node anyway. The new node would get a new WAL.
> ```

remove this comment.
___
*[raftwal/storage.go, line 145 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-MIQdjDA8U4xBhMfMA-W:-MIQdjDB17XDQZXGQiZv:bnjlxgo) ([raw file](https://github.com/dgraph-io/dgraph/blob/dcc7bbdbf01ab8ceb36de571400ed1870ce8c4a2/raftwal/storage.go#L145)):*
> ```Go
> 
> func (m *mmapFile) sync() error {
> 	// TODO: Switch this to z.Msync. And probably use MS_SYNC
> ```

is this todo still needed? it looks like the part about using MS_SYNC is already done.

**Review by martinmr — APPROVED** [review]
:lgtm:

> Reviewed 11 of 25 files at r1, 5 of 7 files at r3, 6 of 9 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6572#-:-MIVQu_t4OZLbJyWaYEO:bnfp4nl)* status: all files reviewed, 20 unresolved discussions (waiting on @manishrjain and @vvbalaji-dgraph)

**Comment by manishrjain** [comment]
Thanks @martinmr , @jarifibrahim , @danielmai for helping with this huge change!

**Pull request merged**
