### PR TITLE
feat(enterprise): audit logs for alpha and zero

### PR DESCRIPTION
**Pull request by aman-bansal**
This PR enables the enterprise feature to enable audit logs. In a nutshell, we are auditing requests over the network. To start the cluster, all you need to do is ```dgraph alpha --audit "dir=/audit_dir"```. Audit logs have the flexibility to be compressed and encrypted. Dgraph audit tool was provided to decrypt old encrypted files.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7295)

### CODE REVIEW

**Review by manishrjain — CHANGES_REQUESTED** [review]
Think we should clean up how we do handling, particularly the GraphQL ones. We need a better way to do middleware. And then do this PR on top.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-:-MR68th1-h_UGTUvwp1p:b-jt512c)* status: 0 of 20 files reviewed, 6 unresolved discussions (waiting on @aman-bansal, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[ee/audit/audit.go, line 1 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64ykC2rsq2zXdhAnK:-MR64ykC2rsq2zXdhAnL:b-adqa32) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/audit.go#L1)):*
> ```Go
> package audit
> ```

license. Also add the build flags.
___
*[ee/audit/interceptor.go, line 1 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64x-R9ZDpnwxPMuMh:-MR64x-R9ZDpnwxPMuMi:b-innwe) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L1)):*
> ```Go
> package audit
> ```

add the license. and build flags.
___
*[ee/audit/interceptor.go, line 26 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64QOy7Ln6ll9OnsZx:-MR64QOy7Ln6ll9OnsZy:bn1ymau) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L26)):*
> ```Go
> 		skipApis := []string{"Heartbeat", "RaftMessage", "JoinCluster", "IsPeer", // raft server
> 			"StreamMembership", "UpdateMembership", "Oracle", // zero server
> 			"Check", "Watch", // health server
> ```

Make this a map.
___
*[ee/audit/interceptor.go, line 30 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64U72-iuf8LPLFrBy:-MR64U72-iuf8LPLFrBz:b-5p06zr) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L30)):*
> ```Go
> 
> 		for _, api := range skipApis {
> 			if strings.HasSuffix(method, api) {
> ```

Just lookup in map. Don't loop over it.
___
*[ee/audit/interceptor.go, line 87 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64pv00Hq5g0SYgnUX:-MR64pv00Hq5g0SYgnUY:b-cuh5pd) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L87)):*
> ```Go
> 		Endpoint:   info.FullMethod,
> 		ReqType:    Grpc,
> 		Req:        fmt.Sprintf("%v", req),
> ```

they have a text marshaller, so perhaps try with that.
___
*[x/jwt_helper.go, line 1 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR68qftEvw1DyQ07t8q:-MR68qfuBhHi4n7gwvy3:b-kdhwj2) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/x/jwt_helper.go#L1)):*
> ```Go
> package x
> ```

license.

**Review by manishrjain — APPROVED** [review]
:lgtm: Get approval from @jarifibrahim as well.

> Reviewed 1 of 20 files at r1, 32 of 32 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-:-MRaF_yqEfzGUimZBMGN:b-cjv020)* status: all files reviewed, 14 unresolved discussions (waiting on @aman-bansal, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 201 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaCrz1CsXV-Wij15tr:-MRaCrz1CsXV-Wij15ts:b-mytvdw) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/dgraph/cmd/alpha/run.go#L201)):*
> ```Go
> 	compress=true/false to enabled the compression of old audit logs (default behaviour is false).
> 	encrypt_file=enc/key/file enables the audit log encryption with the key path provided with the
> 	flag. 
> ```

what's the extra dot here? Is that a space.
___
*[ee/audit/audit_ee.go, line 148 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaDfEMDFHpB_9pbIeB:-MRaDfEMDFHpB_9pbIeC:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/audit_ee.go#L148)):*
> ```Go
> 
> 			if atomic.LoadUint32(&auditEnabled) != 1 {
> 				if auditor.log, err = x.InitLogger(conf.Dir, defaultAuditFilename, conf.EncryptBytes,
> ```

100 chars.
___
*[ee/audit/interceptor_ee.go, line 40 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEAfL8pPp6yXJH8-Q:-MRaEAfL8pPp6yXJH8-R:btes17a) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/interceptor_ee.go#L40)):*
> ```Go
> 	info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
> 	skip := func(method string) bool {
> 		skipApis := map[string]bool{
> ```

this can be out as a var. Not sure how smart Go compiler is about this -- it should only init this once. Putting it in a var is easier on compiler.
___
*[ee/audit/interceptor_ee.go, line 70 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEOwZDRiU4w9KiMDq:-MRaEOwZDRiU4w9KiMDr:b-5h08c7) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/interceptor_ee.go#L70)):*
> ```Go
> 	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
> 		skip := func(method string) bool {
> 			skipEPs := map[string]bool{
> ```

same here.
___
*[ee/audit/run_ee.go, line 88 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEb2k4XyCOTtF9Z0E:-MRaEb2l0qrxuS8irbX0:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/run_ee.go#L88)):*
> ```Go
> 	defer file.Close()
> 
> 	outfile, err := os.OpenFile(decryptCmd.Conf.GetString("out"), os.O_CREATE|os.O_WRONLY|os.O_TRUNC,
> ```

100 chars.
___
*[worker/config.go, line 105 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEoFREaC5ipShukdN:-MRaEoFREaC5ipShukdO:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/worker/config.go#L105)):*
> ```Go
> 		ad, err := filepath.Abs(opt.Audit.Dir)
> 		x.Check(err)
> 		x.AssertTruef(ad != pd, "Posting and Audit Directory cannot be the same ('%s').", opt.Audit.Dir)
> ```

100 chars.
___
*[x/flags.go, line 116 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaF3JO516zVsq7LpRy:-MRaF3JO516zVsq7LpRz:bvxjcle) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/x/flags.go#L116)):*
> ```Go
> 	return sf
> }
> func (sf *SuperFlag) Get(opt string) string {
> ```

GetString
___
*[x/flags.go, line 149 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaF49R0pLXRwW17y6N:-MRaF49R0pLXRwW17y6O:bfjoq95) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/x/flags.go#L149)):*
> ```Go
> 	return uint32(u)
> }
> func (sf *SuperFlag) GetString(opt string) string {
> ```

No need for this.
___
*[x/jwt_helper.go, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaFA-n8K6G4yUOI-sB:-MRaFA-n8K6G4yUOI-sC:b-qp40cc) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/x/jwt_helper.go#L2)):*
> ```Go
> /*
>  * Copyright 2017-2021 Dgraph Labs, Inc. and Contributors
> ```

If this is code move, then OK with the years. Otherwise, if this is new code, then 2021.

**Review by jarifibrahim — APPROVED** [review]
:lgtm: Got some comments

> Reviewed 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-:-MRtRpOx9UBedOm--DaL:bo2v7tp)* status: all files reviewed, 21 unresolved discussions (waiting on @aman-bansal, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 607 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtMjAI2i3n1kDtfdjD:-MRtMjAI2i3n1kDtfdjE:b-r07x3g) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/alpha/run.go#L607)):*
> ```Go
> 	ctype, clevel := x.ParseCompression(Alpha.Conf.GetString("badger.compression"))
> 
> 	conf, err := audit.GetAuditConf(Alpha.Conf.GetString("audit"))
> ```

You can do the x.Check in the GetAuditConf function. We're crashing it anyway.
___
*[dgraph/cmd/alpha/run.go, line 727 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtN7D38ygRetFvRvH-:-MRtN7D38ygRetFvRvH0:b7i2qvr) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/alpha/run.go#L727)):*
> ```Go
> 
> 	// Audit is enterprise feature.
> 	x.Check(audit.InitAuditorIfNecessary(opts.Audit, worker.EnterpriseEnabled))
> ```

Check the error inside the function. Don't need to return it.
___
*[dgraph/cmd/alpha/run.go, line 822 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtNLMP9f_sm7DX_pfV:-MRtNLMP9f_sm7DX_pfW:b7suj11) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/alpha/run.go#L822)):*
> ```Go
> 	glog.Infoln("adminCloser closed.")
> 
> 	audit.Close()
> ```

This will stop the ticker but the trackIfEEValid goroutine will not stop
___
*[dgraph/cmd/zero/run.go, line 240 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtNwnQ-f--bwI1oz7S:-MRtNwnQ-f--bwI1oz7T:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/zero/run.go#L240)):*
> ```Go
> 		ad, err := filepath.Abs(opts.audit.Dir)
> 		x.Check(err)
> 		x.AssertTruef(ad != wd, "WAL and Audit directory cannot be the same ('%s').", opts.audit.Dir)
> ```

100 chars
___
*[dgraph/cmd/zero/run.go, line 240 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtO49PEDcO4QT0fomf:-MRtO49PEDcO4QT0fomg:b-x2cxyx) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/zero/run.go#L240)):*
> ```Go
> 		ad, err := filepath.Abs(opts.audit.Dir)
> 		x.Check(err)
> 		x.AssertTruef(ad != wd, "WAL and Audit directory cannot be the same ('%s').", opts.audit.Dir)
> ```

Why don't we need this check in alpha?
___
*[ee/audit/audit_ee.go, line 27 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtOQ5k4Jf1V07WjK13:-MRtOQ5k4Jf1V07WjK14:bjcgd5o) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/ee/audit/audit_ee.go#L27)):*
> ```Go
> 
> const (
> 	defaultAuditConf     = "dir=;compress=false;encrypt-file="
> ```

Add space after each option.
___
*[ee/audit/interceptor.go, line 87 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64pv00Hq5g0SYgnUX:-MRtPLVQ-8Yc6qBah845:brso5fj) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L87)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

they have a text marshaller, so perhaps try with that.
</blockquote></details>

@aman-bansal is this still valid?
___
*[ee/audit/run_ee.go, line 79 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtRH3t51tYnlyFMpV-:-MRtRH3t51tYnlyFMpV0:b-6ncyzw) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/ee/audit/run_ee.go#L79)):*
> ```Go
> 	x.Check(err)
> 	if key == nil {
> 		return errors.New("no encryption key provided")
> ```

Do you always need an encryption key?
___
*[x/flags.go, line 149 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaF49R0pLXRwW17y6N:-MRtRT8N-cYyX4G_BNYE:b-6f2k50) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/x/flags.go#L149)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this.
</blockquote></details>

@aman-bansal do we need this?

**Review by aman-bansal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7295)* status: 30 of 36 files reviewed, 21 unresolved discussions (waiting on @jarifibrahim, @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 201 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaCrz1CsXV-Wij15tr:-MRto68q0b9kpNuPowVO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/dgraph/cmd/alpha/run.go#L201)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

what's the extra dot here? Is that a space.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 607 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtMjAI2i3n1kDtfdjD:-MRtqzQjAmY1cLl8Rucw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/alpha/run.go#L607)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

You can do the x.Check in the GetAuditConf function. We're crashing it anyway.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 727 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtN7D38ygRetFvRvH-:-MRtr-KlDKQHTH6zBkVK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/alpha/run.go#L727)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Check the error inside the function. Don't need to return it.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 822 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtNLMP9f_sm7DX_pfV:-MRxmO5q1Ch0TbiV8Rbu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/alpha/run.go#L822)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

This will stop the ticker but the trackIfEEValid goroutine will not stop
</blockquote></details>

Done.
___
*[dgraph/cmd/zero/run.go, line 240 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtO49PEDcO4QT0fomf:-MRtoEPZ9DMIm75cmDF8:b-l9lgne) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/zero/run.go#L240)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Why don't we need this check in alpha?
</blockquote></details>

alpha checks are in worker/config.go file.
___
*[dgraph/cmd/zero/run.go, line 240 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtNwnQ-f--bwI1oz7S:-MRtzu1n-p5popU7h4cn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/dgraph/cmd/zero/run.go#L240)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.
___
*[ee/audit/audit.go, line 1 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64ykC2rsq2zXdhAnK:-MRtoNHF4WnfeKzeXvgd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/audit.go#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

license. Also add the build flags.
</blockquote></details>

Done.
___
*[ee/audit/audit_ee.go, line 148 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaDfEMDFHpB_9pbIeB:-MRtooMC8kdhe-EqAE9z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/audit_ee.go#L148)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.
___
*[ee/audit/audit_ee.go, line 27 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtOQ5k4Jf1V07WjK13:-MRtoeOf5f7qzalW4Q84:b-qmlorq) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/ee/audit/audit_ee.go#L27)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Add space after each option.
</blockquote></details>

though not necessary. for better clarity i have fixed this
___
*[ee/audit/interceptor.go, line 26 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64QOy7Ln6ll9OnsZx:-MRtoqV85Mjg0DyUm2K4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L26)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this a map.
</blockquote></details>

Done.
___
*[ee/audit/interceptor.go, line 30 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64U72-iuf8LPLFrBy:-MRtoqp03Yg9lGyY3mli:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L30)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just lookup in map. Don't loop over it.
</blockquote></details>

Done.
___
*[ee/audit/interceptor.go, line 87 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR64pv00Hq5g0SYgnUX:-MRtorsx51XIQ5ZxAjQU:b-6asco5) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/ee/audit/interceptor.go#L87)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

@aman-bansal is this still valid?
</blockquote></details>

No, we can use text marshaller because for text marshaller to work we need to know the type of interface. If works over proto.Message objects only.
___
*[ee/audit/interceptor_ee.go, line 40 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEAfL8pPp6yXJH8-Q:-MRtpvlHBL4f8QkK-N_9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/interceptor_ee.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

this can be out as a var. Not sure how smart Go compiler is about this -- it should only init this once. Putting it in a var is easier on compiler.
</blockquote></details>

Done.
___
*[ee/audit/interceptor_ee.go, line 70 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEOwZDRiU4w9KiMDq:-MRtpwGFEAPDPmlYsVqO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/interceptor_ee.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

Done.
___
*[ee/audit/run_ee.go, line 88 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEb2k4XyCOTtF9Z0E:-MRtq5SrDFBEXNb4DFob:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/ee/audit/run_ee.go#L88)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.
___
*[ee/audit/run_ee.go, line 79 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRtRH3t51tYnlyFMpV-:-MRtpx88ACGHIItZfUhU:bt5sa4d) ([raw file](https://github.com/dgraph-io/dgraph/blob/05ea358d5e970a91365b98aa47359aba4363fd55/ee/audit/run_ee.go#L79)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Do you always need an encryption key?
</blockquote></details>

yes. No benefit of this tool, if not for decrypting audit logs.
___
*[worker/config.go, line 105 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaEoFREaC5ipShukdN:-MRtq6Lq2lYkfHcX1_BD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/worker/config.go#L105)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.
___
*[x/flags.go, line 116 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaF3JO516zVsq7LpRy:-MRtq7PIBMwGXBta8YA3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/x/flags.go#L116)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

GetString
</blockquote></details>

Done.
___
*[x/flags.go, line 149 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaF49R0pLXRwW17y6N:-MRtq8SH47XovDmnMVVK:bng73eq) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/x/flags.go#L149)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

@aman-bansal do we need this?
</blockquote></details>

yes we have refactor Get() method to GetString() method
___
*[x/jwt_helper.go, line 1 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MR68qftEvw1DyQ07t8q:-MRtqGzu-W8xjvntLSZS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7062a4fe95cfc375bc78228d641991ed75ee9ad7/x/jwt_helper.go#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

license.
</blockquote></details>

Done.
___
*[x/jwt_helper.go, line 2 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7295#-MRaFA-n8K6G4yUOI-sB:-MRtqG3YB2owYpil0nVJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/642c296a8f1956cab87042672005144a1af348b4/x/jwt_helper.go#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If this is code move, then OK with the years. Otherwise, if this is new code, then 2021.
</blockquote></details>

Done.

**Pull request merged**
