### PR TITLE
feat(enterpise): Change data capture (CDC) integration with kafka

### PR DESCRIPTION
**Pull request by aman-bansal**
Flag: `cdc` and various sub-options for change data capture are.
	file=/path/to/directory where audit logs will be stored
	kafka=host1,host2 to define comma separated list of host.
	sasl-user=username to define sasl username for kafka.
	sasl-password=password to define sasl password for kafka.
	ca-cert=/path/to/ca/crt/file to define ca cert for tls encryption.
	client-cert=/path/to/client/cert/file to define the client certificate for tls encryption.
	client-key=/path/to/client/key/file to define the client key for tls encryption.

Test Cases Verified:
1. Sink Fails and comes back up. Pending events are sent to the sink 
2. Sink fails and then leader fails. Then sink comes up and events are reaching to the sink
3. Waiting txns are getting sent and pending events are getting cleared with time.
4. Aborted txns are getting cleared
5. In case of leadership changes, old events are not being sent.
6. for live loader we are getting all events,
7. For bulk loader no events.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7395)

### CODE REVIEW

**Review by manishrjain — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7395)* status: 0 of 14 files reviewed, 25 unresolved discussions (waiting on @aman-bansal and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 206 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShvhz_AOW8WssztQID:-MShvhz_AOW8WssztQIE:bfk0auh) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L206)):*
> ```Go
> 	Sample flag could look like --audit dir=aa;encrypt_file=/filepath;compress=true`)
> 
> 	flag.String("change_data", "",
> ```

can be called cdc. In the description you can call it change data capture.

sink should just part of this (no need to call anything sink)

kafka is an option and so on.
file is an option.
___
*[dgraph/cmd/alpha/run.go, line 209 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShrpcn9tTLf1O91oko:-MShrpco7FNvSIu2gA9N:b5my01i) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L209)):*
> ```Go
> 		`Various change data capture options.
> 	enabled=true/false to enable change data capture. Default is false.
> 	max_recovery=N to define the maximum amount of pending txn events can lag behind the
> ```

switch all underscores to dashes.
___
*[dgraph/cmd/alpha/run.go, line 214 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShscz32nWq8KnplwcI:-MShscz4AB5mW7nZmlrc:b5wu6d6) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L214)):*
> ```Go
> 
> 	flag.String("sink", "",
> 		`Various sink config options.
> ```

Various sink options for Change Data Capture.
___
*[dgraph/cmd/alpha/run.go, line 215 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShrzKoCakXVk_GShj-:-MShrzKoCakXVk_GShj0:bi0xwm1) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L215)):*
> ```Go
> 	flag.String("sink", "",
> 		`Various sink config options.
> 	destination=kafka://host1,host2 to define comma separated list of host.
> ```

Use kafka as the key.
Use file as the key.

You can have as many keys as you want. So, no need to have to use a "destination" key for everything.

```
kafka=host1,host2
file=...
```
___
*[dgraph/cmd/alpha/run.go, line 216 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShs_fIAq97yWZkZjE2:-MShs_fIAq97yWZkZjE3:bjbpjdl) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L216)):*
> ```Go
> 		`Various sink config options.
> 	destination=kafka://host1,host2 to define comma separated list of host.
> 	sasl_user=username to define sasl username for kafka.
> ```

`sasl-user=`
___
*[protos/pb.proto, line 321 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShwYa_3cwetGka0Eo-:-MShwYa_3cwetGka0Eo0:b-fsyi53) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/protos/pb.proto#L321)):*
> ```protobuf
> 	uint64 expected_checksum 	= 11; // Block an operation until membership reaches this checksum.
> 	RestoreRequest restore 		= 12;
> 	uint64 CDCMinReadTs 			= 13;
> ```

`CDC_ts`
___
*[systest/change_data/change_data_test.go, line 2 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShwoV88IWDkGMlNPGh:-MShwoV88IWDkGMlNPGi:b-8k8844) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/systest/change_data/change_data_test.go#L2)):*
> ```Go
> /*
>  * Copyright 2017-2021 Dgraph Labs, Inc. and Contributors
> ```

2021.
___
*[worker/change_data.go, line 4 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx1cc6hs5GPwUsdwO:-MShx1cc6hs5GPwUsdwP:bwmzbcj) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data.go#L4)):*
> ```Go
> 
> /*
>  * Copyright 2021 Dgraph Labs, Inc. and Contributors
> ```

instead of calling it change_data. Just call it `cdc.go`.
___
*[worker/change_data_ee.go, line 4 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx5FXBBJa6wIO4BLx:-MShx5FXBBJa6wIO4BLy:b-ch8pn0) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L4)):*
> ```Go
> 
> /*
>  * Copyright 2021 Dgraph Labs, Inc. and Contributors
> ```

cdc_ee.go
___
*[worker/change_data_ee.go, line 34 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx7rr1mfUum8a2Rav:-MShx7rr1mfUum8a2Raw:b-nwng8h) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L34)):*
> ```Go
> const defaultCDCConfig = "enabled=false; max_recovery=10000"
> 
> type ChangeData struct {
> ```

type CDC struct {
___
*[worker/change_data_ee.go, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx9XsBx1pg7-pzFFq:-MShx9XsBx1pg7-pzFFr:b-krjc6f) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L45)):*
> ```Go
> }
> 
> func initChangeDataCapture() *ChangeData {
> ```

Sounds like it's a new object: `newCDC`
___
*[worker/change_data_ee.go, line 113 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShxbh38nbRtTafNKBW:-MShxbh38nbRtTafNKBX:b529t0g) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L113)):*
> ```Go
> 			msgs[i] = SinkMessage{
> 				Meta: SinkMeta{
> 					Topic: "dgraph_cdc",
> ```

use dashes everywhere.
___
*[worker/change_data_ee.go, line 142 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi1DDh4dzBPhkvlXcL:-MSi1DDh4dzBPhkvlXcM:b-3d80np) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L142)):*
> ```Go
> 		// if cdc is lagging behind the current via maxRecoveryEntries,
> 		// skip ahead the cdcIndex to prevent uncontrolled growth of raft logs.
> 		if uint64(len(cd.pendingEvents)) > cd.maxRecoveryEntries {
> ```

if Alpha has taken a snapshot which is beyond what you think you're at, then clear pendingTxns. First index is beyond what you saw last first index or something.
___
*[worker/change_data_ee.go, line 144 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShyPc6AR3rsn8zChpi:-MShyPc6AR3rsn8zChpj:byrn814) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L144)):*
> ```Go
> 		if uint64(len(cd.pendingEvents)) > cd.maxRecoveryEntries {
> 			glog.Info("too many pending cdc events. Skipping for now.")
> 			cd.updateMinReadTs(cd.maxReadTs)
> ```

`cdc.updateTs(...)`

Skip ahead to the latest Timestamp -- MaxAssigned. We're going to lose a bunch of entries here.

Actually, just start from the firstIndex when the instance starts. Don't worry about maxReadTs.

You don't need maxRecoveryEntries. Our snapshots can't progress if we're unable to send. So, when taking a snapshot, we should make a judgement about if we should take a snapshot beyond the send timestamp. If we do, then this logic works here automatically.
___
*[worker/change_data_ee.go, line 160 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShz8PUBBcbu97NciSW:-MShz8PUBBcbu97NciSX:b9hhnqt) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L160)):*
> ```Go
> 			for _, entry := range entries {
> 				if entry.Type != raftpb.EntryNormal || len(entry.Data) == 0 {
> 					cd.cdcIndex = entry.Index
> ```

`cdc.Index`
___
*[worker/change_data_ee.go, line 175 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShzTIqDKC5gVaiA3bk:-MShzTIqDKC5gVaiA3bl:bt0ojhu) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L175)):*
> ```Go
> 				// across the cluster in case of failures.
> 				if proposal.Mutations != nil && proposal.Mutations.StartTs > cd.getCDCMinReadTs() {
> 					events := transformMutationToCDCEvent(entry.Index, proposal.Mutations)
> ```

`toCDCEvent`
___
*[worker/change_data_ee.go, line 176 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShzXDY6CboT58slmao:-MShzXDY6CboT58slmap:b-8s43c5) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L176)):*
> ```Go
> 				if proposal.Mutations != nil && proposal.Mutations.StartTs > cd.getCDCMinReadTs() {
> 					events := transformMutationToCDCEvent(entry.Index, proposal.Mutations)
> 					if events == nil {
> ```

`if len(events) == 0 `
___
*[worker/change_data_ee.go, line 185 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShziOxCg_AFzkO5UT4:-MShziOxCg_AFzkO5UT5:bad4jgf) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L185)):*
> ```Go
> 					// We can set the read ts here only.
> 					if x.WorkerConfig.LudicrousMode {
> 						if err := sendEvents(nil, events); err != nil {
> ```

better to create a batch of events, and then send after you say have a batch of 1000 events.
___
*[worker/change_data_ee.go, line 186 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShzv5H8hwhvasNmtA7:-MShzv5H8hwhvasNmtA8:b-p7aof3) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L186)):*
> ```Go
> 					if x.WorkerConfig.LudicrousMode {
> 						if err := sendEvents(nil, events); err != nil {
> 							return
> ```

always log the error, or return the error. Don't silently ignore.
___
*[worker/change_data_ee.go, line 189 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi-Mc47RwKAbf_G7oY:-MSi-Mc47RwKAbf_G7oZ:b-1cczp7) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L189)):*
> ```Go
> 						}
> 						cd.cdcIndex = entry.Index
> 						cd.updateMinReadTs(proposal.Mutations.StartTs)
> ```

As you're sending the events via a batch system or something, you use a send nested function to send these events. That's the right place to capture the timestamp that you have sent. Also, you should capture it only after it has been successfully sent.

If you're unable to send, retry indefinitely.
___
*[worker/change_data_ee.go, line 192 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi-5Ls4oVE8R9RNIYo:-MSi-5Ls4oVE8R9RNIYp:bwhxiy7) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L192)):*
> ```Go
> 						continue
> 					}
> 					if cd.pendingEvents[proposal.Mutations.StartTs] == nil {
> ```

no need to do this if.
___
*[worker/change_data_ee.go, line 196 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi-6MP0sY5uwgDZard:-MSi-6MP0sY5uwgDZare:b-kp4wyk) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L196)):*
> ```Go
> 					}
> 					cd.pendingEvents[proposal.Mutations.StartTs] =
> 						append(cd.pendingEvents[proposal.Mutations.StartTs], events...)
> ```

Append can take nils.
___
*[worker/change_data_ee.go, line 201 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShyl0Z2Id9iz_GmRPJ:-MShyl0Z2Id9iz_GmRPK:beb74s) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L201)):*
> ```Go
> 				if proposal.Delta != nil {
> 					for _, ts := range proposal.Delta.Txns {
> 						cd.maxReadTs = x.Max(cd.maxReadTs, ts.StartTs)
> ```

`worker.MaxAssigned`?
___
*[worker/change_data_ee.go, line 204 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi1jWK2x7S_eXowfUR:-MSi1jWK2x7S_eXowfUS:b-8xp6im) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L204)):*
> ```Go
> 						pending := cd.pendingEvents[ts.StartTs]
> 						if ts.CommitTs > 0 && len(pending) > 0 {
> 							if err := sendEvents(ts, pending); err != nil {
> ```

you can do batching in sendEvents. Always flush at the end of each run.
___
*[worker/change_data_ee.go, line 210 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi1uih9VQmrvUj-v49:-MSi1uiiEYWRG6YJnCaR:bz5d2jf) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L210)):*
> ```Go
> 						// delete from pending events once events are sent
> 						delete(cd.pendingEvents, ts.StartTs)
> 						_ = cd.evaluateAndSetMinReadTs()
> ```

this should be done via the sendEvents.

**Review by aman-bansal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7395)* status: 0 of 16 files reviewed, 25 unresolved discussions (waiting on @aman-bansal, @manishrjain, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 206 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShvhz_AOW8WssztQID:-MSknyiw5tFfSEZl82LY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L206)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can be called cdc. In the description you can call it change data capture.

sink should just part of this (no need to call anything sink)

kafka is an option and so on.
file is an option.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 209 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShrpcn9tTLf1O91oko:-MSkny7153WgeOWm60aM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L209)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

switch all underscores to dashes.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 214 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShscz32nWq8KnplwcI:-MSknzOa-Aj5Aktf-IeI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L214)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Various sink options for Change Data Capture.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 215 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShrzKoCakXVk_GShj-:-MSko-1062VReA82YKQU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L215)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Use kafka as the key.
Use file as the key.

You can have as many keys as you want. So, no need to have to use a "destination" key for everything.

```
kafka=host1,host2
file=...
```
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 216 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShs_fIAq97yWZkZjE2:-MSko-fP5kD-BmVjKceo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L216)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`sasl-user=`
</blockquote></details>

Done.
___
*[protos/pb.proto, line 321 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShwYa_3cwetGka0Eo-:-MSkoBBX0YD7JtE-N2yz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/protos/pb.proto#L321)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`CDC_ts`
</blockquote></details>

Done.
___
*[systest/change_data/change_data_test.go, line 2 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShwoV88IWDkGMlNPGh:-MSkoCFe7fav194hHg9o:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/systest/change_data/change_data_test.go#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

2021.
</blockquote></details>

Done.
___
*[worker/change_data.go, line 4 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx1cc6hs5GPwUsdwO:-MSkolYEAO_9RcfOgraS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data.go#L4)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

instead of calling it change_data. Just call it `cdc.go`.
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 4 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx5FXBBJa6wIO4BLx:-MSkom722si66GAyZvyZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L4)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

cdc_ee.go
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 34 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx7rr1mfUum8a2Rav:-MSkpJUG0ZKveWAFNCmq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L34)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

type CDC struct {
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShx9XsBx1pg7-pzFFq:-MSkpTJxDLucDkbLJuHB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L45)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Sounds like it's a new object: `newCDC`
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 113 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShxbh38nbRtTafNKBW:-MSkp_4p2Wvpz6iM7GLO:bs7wuoc) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L113)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

use dashes everywhere.
</blockquote></details>

Done.S
___
*[worker/change_data_ee.go, line 160 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShz8PUBBcbu97NciSW:-MSkr_FN0Scqf4CowRfs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L160)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`cdc.Index`
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 175 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShzTIqDKC5gVaiA3bk:-MSkr_tI9VT0MQHUAPXg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L175)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`toCDCEvent`
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 176 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShzXDY6CboT58slmao:-MSkrey14tSRcYr6YgSl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L176)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`if len(events) == 0 `
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 186 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShzv5H8hwhvasNmtA7:-MSlmHU40ylPmODhz24T:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L186)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

always log the error, or return the error. Don't silently ignore.
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 192 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi-5Ls4oVE8R9RNIYo:-MSlmEcW40gXwChcSBDb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L192)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

no need to do this if.
</blockquote></details>

Done.
___
*[worker/change_data_ee.go, line 196 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MSi-6MP0sY5uwgDZard:-MSlmDqZB_vt3ZqH_H0g:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/worker/change_data_ee.go#L196)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Append can take nils.
</blockquote></details>

Done.

**Review by jarifibrahim — APPROVED** [review]
:lgtm: Fix the commented out code.

> Dismissed @manishrjain from a discussion.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-:-MT13Iyr1-n--EMm1qp1:bj4dfk4)* status: 0 of 16 files reviewed, 25 unresolved discussions (waiting on @aman-bansal, @manishrjain, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 214 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MShscz32nWq8KnplwcI:-MT0rHNO4hkQNMKu4lEq:bgxdl6h) ([raw file](https://github.com/dgraph-io/dgraph/blob/02693d3d9e53f13a4591ea31f152edba6abffbef/dgraph/cmd/alpha/run.go#L214)):*
<details><summary><i>Previously, aman-bansal (aman bansal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: missing period.
___
*[worker/sink_handler.go, line 92 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MT1118d1xWE7pUC2TWR:-MT1118eEjYi3svsCR5I:bkw2p63) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cec4b325f2df59e625e4cd9396a4673d4bb6b50/worker/sink_handler.go#L92)):*
> ```Go
> 		caFile, err := ioutil.ReadFile(config.GetString("ca-cert"))
> 		if err != nil {
> 			return nil, err
> ```

wrap the errors

**Review by aman-bansal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7395)* status: 0 of 16 files reviewed, 25 unresolved discussions (waiting on @aman-bansal, @jarifibrahim, @manishrjain, and @vvbalaji-dgraph)

___
*[worker/sink_handler.go, line 92 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7395#-MT1118d1xWE7pUC2TWR:-MT18q0MCPtS0fjn2Ma_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cec4b325f2df59e625e4cd9396a4673d4bb6b50/worker/sink_handler.go#L92)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

wrap the errors
</blockquote></details>

Done.

**Pull request merged**
