### PR TITLE
Break away Raft node functionality, so it can be reused by dgraphzero.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1397)

### CODE REVIEW

**Comment by manishrjain** [comment]
Currently a WIP. So, don't review yet.

**Comment by manishrjain** [comment]
This PR is now ready for review. It sort of breaks the group stuff a bit, but I didn't want to remove local groups completely yet. I've marked where changes need to happen. These would be done right after dgraphzero has the logic to handle membership updates and propagate them to the cluster.

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-:-KtAxwsXwcDd4vE7AI6o:bnfp4nl)*

**Comment by srh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEGCjCYZsambD9aS0G:b5uynkm) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
> ```Go
> }
> 
> var n_ *Node
> ```

What's this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by manishrjain** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEHeZEsNcZoI7AreX5:b5xalp4) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

With dgraph running only one group, we need only one Raft Node. This is the node -- in my upcoming change, this would lie within RaftServer (or be owned by something else).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[worker/draft.go, line 136 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGk2lxCDurUJ6z3Md:-KtEGk2lxCDurUJ6z3Me:b20wx1g) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L136)):*
> ```Go
> 	// The stages are proposed -> committed (accepted by cluster) ->
> 	// applied (to PL) -> synced (to RocksDB).
> 	applied x.WaterMark
> ```

`applied` is a Raft thing.  Does it still belong here?

---

*[worker/draft.go, line 150 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEH7emPXcLSnbArQSV:-KtEH7emPXcLSnbArQSW:bxea2te) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L150)):*
> ```Go
> 
> 	m := conn.NewNode(rc)
> 	n := &node{Node: m}
> ```

Why are we now assigning everything separately?

---

*[worker/draft.go, line 617 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEHO_ljE7dcemigI64:-KtEHO_ljE7dcemigI65:b-5xr517) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L617)):*
> ```Go
> 	x.Printf("Calling JoinCluster")
> 	_, err = c.JoinCluster(n.ctx, n.RaftContext)
> 	// TODO: This should keep on indefinitely trying to join the cluster, instead of crashing.
> ```

I think it should fail (if this is happening at startup) because user misconfigurations get reported back in a straightforward manner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEIyHt6a0I1GWnb5Le:b-19oi99) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

With dgraph running only one group, we need only one Raft Node. This is the node -- in my upcoming change, this would lie within RaftServer (or be owned by something else).
</blockquote></details>

Why is it in some global variable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by manishrjain** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEJExabPGSHSYnXY9N:bammnmw) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Why is it in some global variable?
</blockquote></details>

As I said, in the upcoming change, this would lie within RaftServer for conn.Node portion -- but we still need a place for the node subclass in worker pkg. I've added a TODO for now.

---

*[worker/draft.go, line 136 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGk2lxCDurUJ6z3Md:-KtEIvycNHTmfKc82jrc:b-2a67zy) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L136)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

`applied` is a Raft thing.  Does it still belong here?
</blockquote></details>

I think at least applied (out of applied and synced) can be shared. Moved it to conn.Node.

---

*[worker/draft.go, line 150 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEH7emPXcLSnbArQSV:-KtEIqCYoKb3J7Q-V4yq:bm4vepv) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L150)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Why are we now assigning everything separately?
</blockquote></details>

Done. Ahh.. good point. These can still be assigned together.

---

*[worker/draft.go, line 617 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEHO_ljE7dcemigI64:-KtEJjerSlVd1hHl0s2N:b-g4lymk) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L617)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I think it should fail (if this is happening at startup) because user misconfigurations get reported back in a straightforward manner.
</blockquote></details>

This can fail even if Raft initialization takes longer than expected; in which case, we should just retry. A total failure is only possible if the server explicitly rejects this, or the endpoint isn't present or invalid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEU9YTrUFtYv1FpU2-:bvwwy5e) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

As I said, in the upcoming change, this would lie within RaftServer for conn.Node portion -- but we still need a place for the node subclass in worker pkg. I've added a TODO for now.
</blockquote></details>

I don't follow.  What does the node type in worker have to do with the n_ here?  What is the long term plan?  Is this variable going to go away?

---

*[worker/draft.go, line 150 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEH7emPXcLSnbArQSV:-KtEV2CACU5qZuTOPilY:busn37q) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L150)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Done. Ahh.. good point. These can still be assigned together.
</blockquote></details>

It's not intrinsically worse, because Go doesn't enforce that every field be specified, so there's no big advantage.  (Maybe a small one in terms of implicitly expressing the programmer's intent.)  I was wondering if there was a reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[worker/draft.go, line 152 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEY8t_Lk8qh2-vhVx4:-KtEY8t_Lk8qh2-vhVx5:b-uc9rw5) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L152)):*
> ```Go
> 	n := &node{Node: m}
> 
> 	n.ctx = context.Background()
> ```

Aside comment:  This `context.Background()` has always bothered me.  We're casually using an uncancelable context for things.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by manishrjain** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEaOgmYfdhWx8Gbpxj:beyhxjc) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I don't follow.  What does the node type in worker have to do with the n_ here?  What is the long term plan?  Is this variable going to go away?
</blockquote></details>

n_ is the base class for node in worker. This n_ would a part of RaftServer struct. The node in worker would probably be encapsulated in `groups()`.

---

*[worker/draft.go, line 150 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEH7emPXcLSnbArQSV:-KtEaHYL2s4JEkQPQBlu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L150)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

It's not intrinsically worse, because Go doesn't enforce that every field be specified, so there's no big advantage.  (Maybe a small one in terms of implicitly expressing the programmer's intent.)  I was wondering if there was a reason.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by manishrjain** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/draft.go, line 152 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEY8t_Lk8qh2-vhVx4:-KtElUzwPLk4ltmMi_uP:b-qqwlan) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/worker/draft.go#L152)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Aside comment:  This `context.Background()` has always bothered me.  We're casually using an uncancelable context for things.
</blockquote></details>

We can probably switch this to a cancellable context, and use that to stop the node.Run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtElsdXpP_7N__ZUbIv:b-gl1wah) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

n_ is the base class for node in worker. This n_ would a part of RaftServer struct. The node in worker would probably be encapsulated in `groups()`.
</blockquote></details>

You mean Node is the 'base class' for worker.node?  So this n_ would be removed, and be made part of the RaftServer struct where `unused` is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEmM_kMFXD9Pojz-Nm:bcrsky) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

You mean Node is the 'base class' for worker.node?  So this n_ would be removed, and be made part of the RaftServer struct where `unused` is?
</blockquote></details>

What is stopping us from getting rid of n_ and putting the value in RaftServer right now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtEuXmwoY3SA4pBxyDl:b5x5m6z) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

What is stopping us from getting rid of n_ and putting the value in RaftServer right now?
</blockquote></details>

Before this change, what did we do?  Did we get some node out of groups() in the grpcWorker handlers?  Was it possibly nil?

---

*[conn/node.go, line 420 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEutcw5dplAF1tY_LY:-KtEutcw5dplAF1tY_LZ:bs1xdmn) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L420)):*
> ```Go
> 	var rc protos.RaftContext
> 	x.Check(rc.Unmarshal(msg.Context))
> 	// node := groups().Node(rc.Group)
> ```

Is this commented code new?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[conn/node.go, line 420 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEutcw5dplAF1tY_LY:-KtEvKU00uULsEURsS1i:b3aga6p) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L420)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Is this commented code new?  
</blockquote></details>

I guess it is.  It should be removed?  Is node nil because we have random startup ordering between this code and Raft startup code?

---

*[conn/node.go, line 427 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEvIpMWPlcysZB362O:-KtEvIpMWPlcysZB362P:b-5n31gd) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L427)):*
> ```Go
> 	// }
> 	node := w.GetNode()
> 	if node == nil || node.Raft() == nil {
> ```

What has changed that makes node.Raft() capable of being nil?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtExrseyR40QcBeUD2K:b5m528z) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Before this change, what did we do?  Did we get some node out of groups() in the grpcWorker handlers?  Was it possibly nil?
</blockquote></details>

Okay, it looks like it was.  See my question below about the new Raft() == nil check.

My understanding of this variable is that previously we had the worker server accessing the global variable `groups()` which didn't necessarily contain the `node` and wasn't necessarily fully initialized, period.  Now we've got `RaftServer` accessing this global variable `n_`, which is initialized elsewhere.  Is that correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
If my understanding of n_'s globalness (described in a comment below) is correct, :lgtm:.

---

Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-:-KtEyb2eAIAhT_6UAPpQ:b-ng7oqw)*

**Comment by manishrjain** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[conn/node.go, line 355 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEGCjCYZsambD9aS0F:-KtF-OguplRso8y3vCEh:blivnrn) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd0d5d7d6ed89d539b4075219b4893464fd914df/conn/node.go#L355)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Okay, it looks like it was.  See my question below about the new Raft() == nil check.

My understanding of this variable is that previously we had the worker server accessing the global variable `groups()` which didn't necessarily contain the `node` and wasn't necessarily fully initialized, period.  Now we've got `RaftServer` accessing this global variable `n_`, which is initialized elsewhere.  Is that correct?
</blockquote></details>

Yeah, as answered below, n_ can be created upfront, but init only after WAL is replayed. So, there's a race between accessing it via some GRPC endpoint, and Raft being initialized.

Can I make it part of the RaftServer right now? It is already part of the next PR.

---

*[conn/node.go, line 420 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEutcw5dplAF1tY_LY:-KtF-AsFibMdNmTSYUXJ:bmbawc1) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L420)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I guess it is.  It should be removed?  Is node nil because we have random startup ordering between this code and Raft startup code?
</blockquote></details>

I intend to come here and clean it up -- but I want to do that once I have a working code to handle membership updates in dgraphzero. That'd advice how we deal with `groups()` in general.

---

*[conn/node.go, line 427 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEvIpMWPlcysZB362O:-KtEzefWfGo_WVduNKFY:bjk6z7p) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L427)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

What has changed that makes node.Raft() capable of being nil?
</blockquote></details>

Because this is a grpc method, it can be initialized (/started) independently of the Raft node. So, if we reach here before initializing node, node.Raft() can be nil.

The difference between now and before is that, before groups() would return nil nodes, until they're initialized, so node == nil was being checked. Now, node is created upfront, but fully initialized a bit later (based upon WAL).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[conn/node.go, line 427 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEvIpMWPlcysZB362O:-KtF2AsbAiGOdEBuzHEY:b-pihlnj) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L427)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Because this is a grpc method, it can be initialized (/started) independently of the Raft node. So, if we reach here before initializing node, node.Raft() can be nil.

The difference between now and before is that, before groups() would return nil nodes, until they're initialized, so node == nil was being checked. Now, node is created upfront, but fully initialized a bit later (based upon WAL).
</blockquote></details>

My understanding was that nodes' Raft fields were previously initialized a bit later too -- that's why we had SetRaft.  Where are we creating a node upfront now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Reviewed 8 of 12 files at r1, 2 of 5 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[conn/node.go, line 427 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEvIpMWPlcysZB362O:-KtFHm62NbwTxhNrgjIT:b6062ti) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L427)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

My understanding was that nodes' Raft fields were previously initialized a bit later too -- that's why we had SetRaft.  Where are we creating a node upfront now?
</blockquote></details>

draft.go::newNode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Comment by srh** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[conn/node.go, line 427 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397#-KtEvIpMWPlcysZB362O:-KtFcnxaHjqyjo-eCzi4:b-866v9n) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec152599ee68c0e433d007949c7e536ce62cc586/conn/node.go#L427)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

draft.go::newNode.
</blockquote></details>

But that already existed before, and afaict we're calling it the same way as before -- in groups.go, nothing is changed between newNode and InitAndStartNode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1397)*

**Pull request closed without merging**
