### PR TITLE
Added a seperate store for xid & uid in server

### PR DESCRIPTION
**Pull request by ashwin95r**
[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/38)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/main.go, line 41 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBPzD5w4l_QA74KlXiO:-KBPzD5xrNbfxeEZgd2m:-931692475) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L41)):*
Just call it `uidDir = flag.String("uids", "", "UID posting lists directory")`

---

*[server/main.go, line 46 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ-B69Cwi6oXp7qTBG:-KBQ-B6A9bprpBugzNmK:-786501431) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L46)):*
Instead of having these flags, and then workers flag; we should consolidate them. We could learn from etcd in this case:
`ETCD_INITIAL_CLUSTER="infra0=http://10.0.1.10:2380,infra1=http://10.0.1.11:2380,infra2=http://10.0.1.12:2380"`

So, basically workers flag the way it is right now:
`var cluster = flag.String("cluster", "", "...")` 

For e.g. `10.0.0.1:2380,10.0.1.11:2380,10.0.1.12:2380`

And then an `instanceIdx`. We don't need `numInstances`.

---

*[server/main.go, line 150 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ1kvFswh7Efoa9sY9:-KBQ1kvGCDcnfuTqbJ2v:1894980866) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L150)):*
A space after `//`

---

*[server/main.go, line 153 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ1rme2TtWRgCXERgR:-KBQ1rme2TtWRgCXERgS:-1898606434) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L153)):*
This is small else. Do the else first.

---

*[worker/worker.go, line 29 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ23hPl5yJ3lkCYG11:-KBQ23hPl5yJ3lkCYG12:1627792606) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/worker/worker.go#L29)):*
You don't use it anywhere?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/38)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[server/main.go, line 41 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBPzD5w4l_QA74KlXiO:-KBQxsvzcgI6-BdMlL8k:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L41)):*
Done.

---

*[server/main.go, line 46 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ-B69Cwi6oXp7qTBG:-KBQyByf5J94SopykKIi:1385188939) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L46)):*
Yeah true, can I do that in a separate pull request one I finish the distributed query?

---

*[server/main.go, line 150 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ1kvFswh7Efoa9sY9:-KBQx0XDXyCANWiA5B9k:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L150)):*
Done.

---

*[server/main.go, line 153 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ1rme2TtWRgCXERgR:-KBQxO1Pwibvf2qtgMfn:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L153)):*
Done.

---

*[worker/worker.go, line 29 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ23hPl5yJ3lkCYG11:-KBQxP-upO7-0aN8f1zJ:-527289556) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/worker/worker.go#L29)):*
It will be used in the instance which has xid and uid store, those two attributes will be handled separately. and if the attribute is _xid_ or _uid_, we will query this store

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/38)*

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/main.go, line 46 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ-B69Cwi6oXp7qTBG:-KBQzqqbfgXdNxjq8R3Z:-1599660086) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L46)):*
Why not in this one?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/38)*

**Comment by ashwin95r** [comment]
Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/main.go, line 46 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-KBQ-B69Cwi6oXp7qTBG:-KBR5aVeT7V1bcP65U9I:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e917ef00a05bcfa6c9af3608c460c72e7b678fc/server/main.go#L46)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/38)*

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/38)*

**Comment by manishrjain** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/38#-:-KBR831ZrhHx0t8TPoag:980077423)*

**Pull request merged**
