### PR TITLE
Dont send uid if there are no other children in debug mode

### LINKED ISSUE #1782: The is a difference between graph display and json response
When I run this command in web console:
```
{
  everyone(func: anyofterms(name, "Michael")) {
		expand(_all_)
  }
}
```

I get below result
graph_display

It contains the node information about Michael and his relations, but when I check the json response, it contains only node info:
json_result

That is to say, json response doesn't contain edge information. If the response doesn't contains any edge informations how can the web console display them?

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #1782

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1822)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 371 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822#-KzbPTSDulLE36xpMzU6:-KzbPTSDulLE36xpMzU7:b-lmo9p5) ([raw file](https://github.com/dgraph-io/dgraph/blob/4cf3a1bc434450156f9f6d4db270b84531fcb695/query/query.go#L371)):*
> ```Go
> 		// then we dont return the uids at this level so that UI doesn't render
> 		// nodes without any other properties.
> 		if sg.Params.uidCount == "" || len(sg.Children) != 0 {
> ```

This count() check is no longer required ?

---

*[query/query.go, line 446 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822#-KzbPDXUEApTRM7avgLO:-KzbPDXUEApTRM7avgLP:b7bdg24) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f5855478ba4606b783ffc83cecfce9654bb3ea8/query/query.go#L446)):*
> ```Go
> 				if !uc.IsEmpty() {
> 					if sg.Params.GetUid {
> 						uc.SetUID(childUID, "uid")
> ```

Shouldn't uid be already set, we call pretraverse on childUid and uic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 371 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822#-KzbPTSDulLE36xpMzU6:-KzbWKenHhJjxeN7uT4h:b-oi5r3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/4cf3a1bc434450156f9f6d4db270b84531fcb695/query/query.go#L371)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This count() check is no longer required ?
</blockquote></details>

not very sure what that was for.

---

*[query/query.go, line 446 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822#-KzbPDXUEApTRM7avgLO:-KzbSo4CLQaZ-4MrpdmY:b7k9n4y) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f5855478ba4606b783ffc83cecfce9654bb3ea8/query/query.go#L446)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Shouldn't uid be already set, we call pretraverse on childUid and uic.
</blockquote></details>

But we set facets (right above this) after returning from there. So it could be that when preTraverse was called, node was empty but it is not now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822#-:-KzbXZy0f4NgpaqyNuIa:bnfp4nl)*

**Comment by peterstace** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1822)*

**Comment by pawanrawal** [comment]
In master as of a71e91c7daedb1163acdda67a1c5851fdb37ccbc

**Pull request closed without merging**
