### PR TITLE
[docs] : rephrase + added example to query logging section

### PR DESCRIPTION
**Pull request by OmarAyo**
- rephrased title
- rephrased `-v=3` paragraph
- added "note" box to highlight the fact that these flags require a restart
- added example for query logging output

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7032)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7032)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/log-format.md, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7032#-MNUilS87eDQVwNcDx27:-MNUilS87eDQVwNcDx28:bz7pzpb) ([raw file](https://github.com/dgraph-io/dgraph/blob/4e5365e9efe9ec6bb7247b0afbc063de270ff5fb/wiki/content/deploy/log-format.md#L45)):*
> ```
> it in JSON-like format
> ```
Rephrase to "the original DQL format". Any `\t` characters would need to be replaced with a tab character too.

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7032)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/log-format.md, line 35 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7032#-MNUj0VO2Lhdy3s0LJfQ:-MNUj0VO2Lhdy3s0LJfR:b-icmt4p) ([raw file](https://github.com/dgraph-io/dgraph/blob/4e5365e9efe9ec6bb7247b0afbc063de270ff5fb/wiki/content/deploy/log-format.md#L35)):*
> ```
> it self
> ```
itselff

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7032)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/log-format.md, line 35 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7032#-MNUj0VO2Lhdy3s0LJfQ:-MNUj44P9ezNYEZCwMio:b-a9swi) ([raw file](https://github.com/dgraph-io/dgraph/blob/4e5365e9efe9ec6bb7247b0afbc063de270ff5fb/wiki/content/deploy/log-format.md#L35)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> it self
> ```
itselff
</blockquote></details>

itself*

**Review by OmarAyo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7032)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @danielmai and @MichaelJCompton)

___
*[wiki/content/deploy/log-format.md, line 35 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7032#-MNUj0VO2Lhdy3s0LJfQ:-MNcdf3I6s-3N46Vq8Ct:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4e5365e9efe9ec6bb7247b0afbc063de270ff5fb/wiki/content/deploy/log-format.md#L35)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

itself*
</blockquote></details>

Done.
___
*[wiki/content/deploy/log-format.md, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7032#-MNUilS87eDQVwNcDx27:-MNcdfTvDurVGFU0OmYC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4e5365e9efe9ec6bb7247b0afbc063de270ff5fb/wiki/content/deploy/log-format.md#L45)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> it in JSON-like format
> ```
Rephrase to "the original DQL format". Any `\t` characters would need to be replaced with a tab character too.
</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7032#-:-MNdnu9R-yeg50gBRVFZ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai and @MichaelJCompton)

**Pull request merged**
