### PR TITLE
Fix(GraphQL): This PR adds input coercing for Integers given in variables and fixes e2e error tests.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes GRAPHQL-661

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6732)

 

Docs Preview: [Dgraph Preview](https://dgraph-83be735518-104302.surge.sh)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6732)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 265 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6732#-MK3opks-lz3mMKa_MiC:-MK3opkt5KtlPR7rC9OP:bvzmwpp) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b8b0324183345f925bde22c74824f699e39f0a1/graphql/e2e/common/error_test.yaml#L265)):*
> ```YAML
>     }
>   errors:
>     [ { "message": "strconv.ParseInt: parsing \"180143985094.0\": invalid syntax",
> ```

The error message isn't great. Is this coming from GraphQL or Dgraph?
___
*[graphql/schema/request.go, line 104 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6732#-MK3oxcN0GKPZx22hSZj:-MK3oxcN0GKPZx22hSZk:byrse9) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b8b0324183345f925bde22c74824f699e39f0a1/graphql/schema/request.go#L104)):*
> ```Go
> }
> 
> func variableValidateInt(schema *ast.Schema, op *ast.OperationDefinition, variables map[string]interface{}) *gqlerror.Error {
> ```

Add these as comments.

This function validates the value of variables for fields of type `Int` and `Int64`. Ideally this should happen in the `gqlparser` library. There is an issue created with this https://github.com/vektah/gqlparser/issues/134.  The code here is inspired by https://github.com/vektah/gqlparser/blob/master/validator/vars.go#L76.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6732)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 265 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6732#-MK3opks-lz3mMKa_MiC:-MK4ga5w-QwiEF5ttwQO:b-xybg8t) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b8b0324183345f925bde22c74824f699e39f0a1/graphql/e2e/common/error_test.yaml#L265)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The error message isn't great. Is this coming from GraphQL or Dgraph?
</blockquote></details>

Actually we  don't know the actual type of variable , So, i returned the default value. Changed it.
___
*[graphql/schema/request.go, line 104 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6732#-MK3oxcN0GKPZx22hSZj:-MK4gzIxA6Z7kuDJ-6G1:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b8b0324183345f925bde22c74824f699e39f0a1/graphql/schema/request.go#L104)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add these as comments.

This function validates the value of variables for fields of type `Int` and `Int64`. Ideally this should happen in the `gqlparser` library. There is an issue created with this https://github.com/vektah/gqlparser/issues/134.  The code here is inspired by https://github.com/vektah/gqlparser/blob/master/validator/vars.go#L76.
</blockquote></details>

added.

**Review by pawanrawal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6732)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/error_test.yaml, line 87 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6732#-MK5ZDwD2FU5-w2pu2Lk:-MK5ZDwD2FU5-w2pu2Ll:bk8en2o) ([raw file](https://github.com/dgraph-io/dgraph/blob/712d742e00003495255d7e7a65592b6c461f3843/graphql/e2e/common/error_test.yaml#L87)):*
> ```YAML
>     }
>   gqlvariables: 
>     { "filter": { "reputation": { le: "hi there" } } }
> ```

Try removing `filter` key here so that we still get this same error. Don't remove the test.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6732)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

**Pull request merged**
