### PR TITLE
Feat(GRAPHQL): This PR allows updatable and nullable @id fields.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Currently, @id fields are not updatable and also we enforce them to be non-null.
In this PR we are allowing @id fields to be updatable and nullable.

RFC:https://discuss.dgraph.io/t/rfc-mutable-and-null-able-id-field-in-graphql/13663
Related Posts:
https://discuss.dgraph.io/t/nullable-id-field/13296
https://discuss.dgraph.io/t/editable-id-fields/13295
https://discuss.dgraph.io/t/rfc-allow-multiple-unique-fields-in-graphql-schema/12008

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7736)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7736)* status: all files reviewed, 17 unresolved discussions (waiting on @JatinDevDG)

___
*[graphql/e2e/auth/schema.graphql, line 855 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsImnV7hu7hT5Yxpsy:-MYsImnWCMiGXZQx6CVP:bx5ooib) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/auth/schema.graphql#L855)):*
> ```GraphQL
> ) {
>     company: String! @id
>     company_Id: String @id
> ```

companyId
___
*[graphql/e2e/auth/schema.graphql, line 861 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsIoHj4fkIu3HW9WP7:-MYsIoHj4fkIu3HW9WP8:b-7k2fsg) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/auth/schema.graphql#L861)):*
> ```GraphQL
> 
> type Worker {
>     reg_No: Int @id
> ```

regNo
___
*[graphql/e2e/auth/schema.graphql, line 862 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsIpR-8TePMOkcMKel:-MYsIpR-8TePMOkcMKem:bvbmzld) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/auth/schema.graphql#L862)):*
> ```GraphQL
> type Worker {
>     reg_No: Int @id
>     UniqueID: Int @id
> ```

uniqueID
___
*[graphql/e2e/common/mutation.go, line 6499 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKPdA8NOcYQE11hho:-MYsKPdA8NOcYQE11hhp:b-aah5w0) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/common/mutation.go#L6499)):*
> ```Go
>                     }
>                 }`,
> 			error: "mutation updateEmployer failed because multiple nodes are selected in filter" +
> ```

failed because only one node is allowed in the filter while updating fields with @id directive
___
*[graphql/e2e/directives/schema.graphql, line 384 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKqDk3ONFRd4il4WY:-MYsKqDk3ONFRd4il4WZ:b-7k2fsg) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/directives/schema.graphql#L384)):*
> ```GraphQL
> type Worker {
>     name: String!
>     reg_No: Int @id
> ```

regNo
___
*[graphql/e2e/directives/schema.graphql, line 385 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKp7bDDgX-zOUvtQl:-MYsKp7bDDgX-zOUvtQm:bvbmzm9) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/directives/schema.graphql#L385)):*
> ```GraphQL
>     name: String!
>     reg_No: Int @id
>     UniqueID: Int @id
> ```

uniqueId
___
*[graphql/e2e/directives/schema.graphql, line 391 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKrNc2NoZ9aoArA_I:-MYsKrNd0-4LHFOHSJyP:bx5ooib) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/directives/schema.graphql#L391)):*
> ```GraphQL
> type Employer {
>     company: String! @id
>     company_Id: String @id
> ```

companyId
___
*[graphql/e2e/normal/schema.graphql, line 322 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKvUo5JX6L_vLsWzq:-MYsKvUo5JX6L_vLsWzr:bvbmzm9) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/normal/schema.graphql#L322)):*
> ```GraphQL
>     name: String!
>     reg_No: Int @id
>     UniqueID: Int @id
> ```

uniqueId
___
*[graphql/e2e/normal/schema.graphql, line 323 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKwoX6QAy4QEGwMrW:-MYsKwoY5Z2X7gtPYtl8:b-7r2h2a) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/normal/schema.graphql#L323)):*
> ```GraphQL
>     reg_No: Int @id
>     UniqueID: Int @id
>     emp_Id: String! @id
> ```

empId
___
*[graphql/e2e/normal/schema.graphql, line 328 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKxck1N2NKg4OoVxF:-MYsKxck1N2NKg4OoVxG:bx5ooib) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/normal/schema.graphql#L328)):*
> ```GraphQL
> type Employer {
>     company: String! @id
>     company_Id: String @id
> ```

companyId
___
*[graphql/resolve/mutation_rewriter.go, line 1815 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsMi0qDlfdf5-nG2-X:-MYsMi0qDlfdf5-nG2-Y:b-7wr0vd) ([raw file](https://github.com/dgraph-io/dgraph/blob/69c83890a4511677a17dcb53935fcedf12c8a875/graphql/resolve/mutation_rewriter.go#L1815)):*
> ```Go
> 					// In this case, as obj is the correct definition of the object, we update variableObjMap
> 					oldObj := xidMetadata.variableObjMap[variable]
> 					if len(oldObj) == 1 && len(obj) > 1 {
> ```

if there is a test case that was broken earlier, lets add that here. Otherwise lets keep it as it is
___
*[graphql/resolve/schema.graphql, line 396 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsMuYFE4U7vVEjQXIA:-MYsMuYFE4U7vVEjQXIB:b-1ocm7s) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/resolve/schema.graphql#L396)):*
> ```GraphQL
>     title: String @id
>     ISBN: String @id
>     BookId: Int @id
> ```

bookedId
___
*[graphql/resolve/update_mutation_test.yaml, line 1972 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsMxk37HYLuNOuoFdq:-MYsMxk37HYLuNOuoFdr:btqwcnd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/resolve/update_mutation_test.yaml#L1972)):*
> ```YAML
>     	updateBook(input: $patch) {
>     		book {
>     			title
> ```

spacing seems a bit messed up
___
*[graphql/schema/gqlschema.go, line 1290 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsN56v2i6HkVAMmIUB:-MYsN56v2i6HkVAMmIUC:bh9dwc7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/schema/gqlschema.go#L1290)):*
> ```Go
> 	if len(nonIDFields) == 0 {
> 		// The user might just have an predicate with reverse edge id field and nothing else.
> 		//We don't generate patch type in that case.
> ```

// We 
___
*[graphql/schema/gqlschema_test.yml, line 633 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsNGb228_ZHOhZ8ZeN:-MYsNGb228_ZHOhZ8ZeO:bw8bvyb) ([raw file](https://github.com/dgraph-io/dgraph/blob/69c83890a4511677a17dcb53935fcedf12c8a875/graphql/schema/gqlschema_test.yml#L633)):*
> ```YAML
>     input: |
>       type X {
>         f1: Float! @id
> ```

this should remain?
___
*[graphql/schema/rules.go, line 2076 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsN_xy7iRUUdHrauIA:-MYsN_xy7iRUUdHrauIB:b-hn8i6m) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/schema/rules.go#L2076)):*
> ```Go
> 	dir *ast.Directive,
> 	secrets map[string]x.Sensitive) gqlerror.List {
> 	if field.Type.NamedType == "String" ||
> ```

Isn't this check applicable for non-nullable id fields as well?
___
*[graphql/schema/testdata/schemagen/output/custom-dql-query-with-subscription.graphql, line 439 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsNlgsAMxeDPDjtsvd:-MYsNlgtEOwYe9dSPMvm:b-ugccv8) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/schema/testdata/schemagen/output/custom-dql-query-with-subscription.graphql#L439)):*
> ```GraphQL
> 
> input UserPatch {
> 	screen_name: String
> ```

screenName

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7736)* status: 16 of 31 files reviewed, 17 unresolved discussions (waiting on @id, @JatinDevDG, and @pawanrawal)

___
*[graphql/e2e/auth/schema.graphql, line 855 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsImnV7hu7hT5Yxpsy:-MYuf0v95hS5qb0hShxv:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/auth/schema.graphql#L855)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

companyId
</blockquote></details>

done.
___
*[graphql/e2e/auth/schema.graphql, line 861 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsIoHj4fkIu3HW9WP7:-MYufMqnCaxZFneG8rJa:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/auth/schema.graphql#L861)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

regNo
</blockquote></details>

done
___
*[graphql/e2e/auth/schema.graphql, line 862 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsIpR-8TePMOkcMKel:-MYufxKs26n68WFZqJJh:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/auth/schema.graphql#L862)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

uniqueID
</blockquote></details>

changed.
___
*[graphql/e2e/common/mutation.go, line 6499 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKPdA8NOcYQE11hho:-MYumUSV1BT6AyKYWs2_:b9k5jvv) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/common/mutation.go#L6499)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

failed because only one node is allowed in the filter while updating fields with @id directive
</blockquote></details>

changed.
___
*[graphql/e2e/directives/schema.graphql, line 384 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKqDk3ONFRd4il4WY:-MYuiMAjAf-K1Ek5P4B8:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/directives/schema.graphql#L384)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

regNo
</blockquote></details>

done.
___
*[graphql/e2e/directives/schema.graphql, line 385 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKp7bDDgX-zOUvtQl:-MYuiN-c6znyZOU-KtF2:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/directives/schema.graphql#L385)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

uniqueId
</blockquote></details>

done.
___
*[graphql/e2e/directives/schema.graphql, line 391 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKrNc2NoZ9aoArA_I:-MYuiNsxEJpKDlEV729w:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/directives/schema.graphql#L391)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

companyId
</blockquote></details>

done.
___
*[graphql/e2e/normal/schema.graphql, line 322 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKvUo5JX6L_vLsWzq:-MYuiP-YEXAzdsfpUCDB:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/normal/schema.graphql#L322)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

uniqueId
</blockquote></details>

done.
___
*[graphql/e2e/normal/schema.graphql, line 323 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKwoX6QAy4QEGwMrW:-MYuiPweB-h2et1p6hK3:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/normal/schema.graphql#L323)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

empId
</blockquote></details>

done.
___
*[graphql/e2e/normal/schema.graphql, line 328 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsKxck1N2NKg4OoVxF:-MYulAZr81cgGaLJEBDy:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/e2e/normal/schema.graphql#L328)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

companyId
</blockquote></details>

done.
___
*[graphql/resolve/mutation_rewriter.go, line 1815 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsMi0qDlfdf5-nG2-X:-MYuk5JB1R9jonWaDVXz:bat2g47) ([raw file](https://github.com/dgraph-io/dgraph/blob/69c83890a4511677a17dcb53935fcedf12c8a875/graphql/resolve/mutation_rewriter.go#L1815)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

if there is a test case that was broken earlier, lets add that here. Otherwise lets keep it as it is
</blockquote></details>

currently, it doesn't have any effect, because if we have more than one xid fields and we try to add reference in single mutation then that gives duplicate xid error. That itself is a bug. i have created ticket for it. we need to do some refactoring for this. There are couple of scenarios where duplicate xid error is not behaving correctly. while fixing that we can fix this also. Added TODO for this in code.
___
*[graphql/resolve/schema.graphql, line 396 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsMuYFE4U7vVEjQXIA:-MYuioEQDLGWLRTXDRP-:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/resolve/schema.graphql#L396)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

bookedId
</blockquote></details>

changed.
___
*[graphql/schema/gqlschema.go, line 1290 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsN56v2i6HkVAMmIUB:-MYujystEyucSOqFm08g:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/schema/gqlschema.go#L1290)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

// We 
</blockquote></details>

changed.
___
*[graphql/schema/gqlschema_test.yml, line 633 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsNGb228_ZHOhZ8ZeN:-MYujqr14oCotkG2d1xw:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/69c83890a4511677a17dcb53935fcedf12c8a875/graphql/schema/gqlschema_test.yml#L633)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

this should remain?
</blockquote></details>

added.
___
*[graphql/schema/rules.go, line 2076 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsN_xy7iRUUdHrauIA:-MYujAXUEcbielkiunJR:b-u7voi6) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/schema/rules.go#L2076)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Isn't this check applicable for non-nullable id fields as well?
</blockquote></details>

Actually, NamedType, cover both nullable and non-nullable values.
___
*[graphql/schema/testdata/schemagen/output/custom-dql-query-with-subscription.graphql, line 439 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsNlgsAMxeDPDjtsvd:-MYuoFav8PwZOEVegwa3:b9k5jvv) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/schema/testdata/schemagen/output/custom-dql-query-with-subscription.graphql#L439)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

screenName
</blockquote></details>

changed.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7736)* status: 13 of 31 files reviewed, 17 unresolved discussions (waiting on @id and @pawanrawal)

___
*[graphql/resolve/update_mutation_test.yaml, line 1972 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYsMxk37HYLuNOuoFdq:-MYuufTP15Lw91gZByMB:b-qssebl) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0ca4f49d4b7177a56b39ec4dfd704452038c6fa/graphql/resolve/update_mutation_test.yaml#L1972)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

spacing seems a bit messed up
</blockquote></details>

fixed.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 14 of 15 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7736)* status: all files reviewed, 1 unresolved discussion (waiting on @JatinDevDG)

___
*[graphql/resolve/mutation_rewriter.go, line 1832 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYwE4aL7MruIwU30kAI:-MYwE4aL7MruIwU30kAJ:bs8zask) ([raw file](https://github.com/dgraph-io/dgraph/blob/0380514152a9aed81561bb43a666c91c5c620750/graphql/resolve/mutation_rewriter.go#L1832)):*
> ```Go
> 					// In this case, as obj is the correct definition of the object, we update variableObjMap
> 					oldObj := xidMetadata.variableObjMap[variable]
> 					// TODO(GRAOHQL): This condition also needs to change in accordance with multiple xids.
> ```

TODO(jatin)

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7736)* status: 29 of 31 files reviewed, 1 unresolved discussion (waiting on @pawanrawal)

___
*[graphql/resolve/mutation_rewriter.go, line 1832 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7736#-MYwE4aL7MruIwU30kAI:-MYxdsgcAwdho8mfzo8F:b-n9tkhd) ([raw file](https://github.com/dgraph-io/dgraph/blob/0380514152a9aed81561bb43a666c91c5c620750/graphql/resolve/mutation_rewriter.go#L1832)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

TODO(jatin)
</blockquote></details>

changed

**Pull request merged**
