### PR TITLE
#487: rdf comments is supported

### PR DESCRIPTION
**Pull request by squalfof**
Comment/blank line should not be considered as 'error', while in parse.Parse() you can't express 'empty yet harmless' feedback. 
I just keep that interface intact, with returning len(NQuad.Subject) == 0 indicate 'empty yet harmless'.
Do the comment-filter stuff in dgraphloader.main() is inappropriate.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/506)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraphloader/main.go, line 74 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KaopyRoSK312zrxSEre:-KaopyRoSK312zrxSErf:bd2e2d5) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/cmd/dgraphloader/main.go#L74)):*
> ```Go
> 		if err != nil {
> 			log.Fatal("While parsing RDF: ", err)
> 		} else if len(nq.Subject) == 0 { // empty line
> ```

Instead of returning an empty nquad, we can return an error `error.New("Empty_Line")`

---

*[rdf/parse_test.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kaop5D102hom64k7iUv:-Kaop5D102hom64k7iUw:blfvy2k) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/rdf/parse_test.go#L355)):*
> ```Go
> 	},
> 	{
> 		input: `  `,
> ```

We can check for a specific error here ("EMPTY_LINE")

---

*[rdf/parse_test.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KaolaTydIYQlTwiZigk:-KaolaTzPUHrW69jXh1m:b-nmgjyn) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/rdf/parse_test.go#L363)):*
> ```Go
> 		expectedErr: true,
> 	},
> }
> ```

Can we add one more test in which the comment is at the end of the line?
`<S> <P> <O> . # some comment`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/506)*

**Comment by squalfof** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/main.go, line 74 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KaopyRoSK312zrxSEre:-Kapb5x7_ydtdYP2fAVB:bb7oryy) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/cmd/dgraphloader/main.go#L74)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Instead of returning an empty nquad, we can return an error `error.New("Empty_Line")`
</blockquote></details>

sure

---

*[rdf/parse_test.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kaop5D102hom64k7iUv:-KapbP9OpmuT3mTzvyY4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/rdf/parse_test.go#L355)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We can check for a specific error here ("EMPTY_LINE")
</blockquote></details>

Done.

---

*[rdf/parse_test.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KaolaTydIYQlTwiZigk:-KapabuxBEgEMSsdwsFC:b-ltf4yu) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/rdf/parse_test.go#L363)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Can we add one more test in which the comment is at the end of the line?
`<S> <P> <O> . # some comment`
</blockquote></details>

yep, such case already exist before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/506)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-:-KaqOdEs01vKE-bl5lB_:bnfp4nl)*

**Comment by manishrjain** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/main.go, line 72 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kat7k0OfA3WgDnfqVVk:-Kat7k0OfA3WgDnfqVVl:b-4uiuhm) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/cmd/dgraphloader/main.go#L72)):*
> ```Go
> 		}
> 		nq, err := rdf.Parse(buf.String())
> 		if err != nil && err.Error() == "EMPTY_LINE" { // special case: comment/empty line
> ```

Check for err == ErrEmpty. Mechanism mentioned below.

---

*[rdf/parse.go, line 256 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kat7ZGSep6YaZyZQsyT:-Kat7ZGSep6YaZyZQsyU:b7ujiu5) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/rdf/parse.go#L256)):*
> ```Go
> 	}
> 	if isCommentLine {
> 		return rnq, x.Errorf("EMPTY_LINE")
> ```

Create a const variable. Look at  https://golang.org/pkg/bufio/#pkg-variables. And then pass it down here, instead of creating one every time.

---

*[rdf/parse_test.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kaop5D102hom64k7iUv:-KatBtI1457L1Xi72KaV:b4ja65c) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/rdf/parse_test.go#L355)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't this be an error. We reached EOF without any predicate. And not just EMPTY_LINE. This should be a different error.

---

*[rdf/state.go, line 89 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KatC6yo3aHbMRFTftJz:-KatC6yo3aHbMRFTftK-:b-mr1qip) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/rdf/state.go#L89)):*
> ```Go
> 			return lexObject
> 
> 		case r == '#':
> ```

Do we deal with `\#` somewhere? In that case, we'll have to ignore the rune after the backslash.

---

*[rdf/state.go, line 338 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KatCOYPypgUFOz3Dzpd:-KatCOYPypgUFOz3Dzpe:b-hmtuhe) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/rdf/state.go#L338)):*
> ```Go
> 	}
> 	l.Emit(itemComment)
> 	l.Emit(lex.ItemEOF)
> ```

Shouldn't we look at the next line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/506)*

**Comment by squalfof** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/main.go, line 72 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kat7k0OfA3WgDnfqVVk:-KatR-e0SnKPZJPFgnOE:bxgjch) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/cmd/dgraphloader/main.go#L72)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check for err == ErrEmpty. Mechanism mentioned below.
</blockquote></details>

thx, makes more sense

---

*[rdf/parse.go, line 256 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kat7ZGSep6YaZyZQsyT:-KatS5VShcztJSzLT08l:b-xnwm9k) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/rdf/parse.go#L256)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a const variable. Look at  https://golang.org/pkg/bufio/#pkg-variables. And then pass it down here, instead of creating one every time.
</blockquote></details>

Done. 
Place under package x.error, thought be global available

---

*[rdf/parse_test.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kaop5D102hom64k7iUv:-KatTWSzCW5V4h465BBx:bnjwc75) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1b0321712c932f70b1844130c1a28f103bfc53f/rdf/parse_test.go#L355)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shouldn't this be an error. We reached EOF without any predicate. And not just EMPTY_LINE. This should be a different error.
</blockquote></details>

let me clarify here, Parser will treat this case as an error, which is not an EMPTY error. 
It's actually  l.Errorf("Invalid input: %c at lexText", r)

---

*[rdf/state.go, line 89 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KatC6yo3aHbMRFTftJz:-KatVN9N631pUMTsxEus:b-egoexp) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/rdf/state.go#L89)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do we deal with `\#` somewhere? In that case, we'll have to ignore the rune after the backslash.
</blockquote></details>

the switch-case here stands for start-of-new-term. 
like,  case '<' => start of IRI, case '.' => start of valid end.

if  \\# do appear, then it is handled as part of a term, not here.
and currently, seems each term is processed by separate functions.

---

*[rdf/state.go, line 338 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-KatCOYPypgUFOz3Dzpd:-KatRdRbsoyWoUWNXkgb:bg2iuyt) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/rdf/state.go#L338)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shouldn't we look at the next line?
</blockquote></details>

it's just an one-line parse.
iteration is controlled from outer scope

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/506)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[rdf/parse.go, line 256 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-Kat7ZGSep6YaZyZQsyT:-KatXm-zUc8rKX4ZEL4K:b-ki3per) ([raw file](https://github.com/dgraph-io/dgraph/blob/87dd1565dab501e631eb78813d6b2a0595352feb/rdf/parse.go#L256)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Done. 
Place under package x.error, thought be global available
</blockquote></details>

No, doesn't make sense to be a global variable. This is specific to rdf parsing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/506)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/506#-:-KauWCE1FqN5EB3e48tn:bnfp4nl)*

**Pull request closed without merging**
