### PR TITLE
Gql facets filter

### PR DESCRIPTION
**Pull request by ashishnegi**
Facets filtering is now separate from predicate filtering.
`friend @facets(eq(close, true)) {` instead of `friend @filter(eq(@facets(close), true)) {`

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/602)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gql/parser.go, line 1172 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/602#-KdK2ldOOxVaudwomI0G:-KdK2ldOOxVaudwomI0H:b-cabdgl) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3362ed71339a4c717a6a7766c3e44f3b9a49c27/gql/parser.go#L1172)):*
> ```Go
> 				if facetsFilter.hasVars() {
> 					return x.Errorf(
> 						"variables are not allowed in facets filter.")
> ```

one line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/602#-:-KdK3_6GGl-bXx4EikWP:bnfp4nl)*

**Comment by ashishnegi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gql/parser.go, line 1172 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/602#-KdK2ldOOxVaudwomI0G:-KdKwyKd0PEOJ7RnzQfC:b-m04jll) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3362ed71339a4c717a6a7766c3e44f3b9a49c27/gql/parser.go#L1172)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

one line.
</blockquote></details>

goes over 100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/602)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 1769 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/602#-KdP7MA5wbaTIxRVgEKC:-KdP7MA5wbaTIxRVgEKD:bzksrl) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3362ed71339a4c717a6a7766c3e44f3b9a49c27/gql/parser_test.go#L1769)):*
> ```Go
> 
> // Test facets parsing for filtering..
> func TestFacetsFilterSimple(t *testing.T) {
> ```

We can have a failing test with facets at root.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/602#-:-KdP6eHTBGP3G1WQSCoF:bnfp4nl)*

**Comment by ashishnegi** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 1769 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/602#-KdP7MA5wbaTIxRVgEKC:-KdPLbU70RYpbj3nlEap:be7obq7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d3362ed71339a4c717a6a7766c3e44f3b9a49c27/gql/parser_test.go#L1769)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We can have a failing test with facets at root.
</blockquote></details>

Done. TestFacetsFilterFailRoot

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/602)*

**Pull request closed without merging**
