### PR TITLE
Support alias for var, count, aggregators

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/885)

### CODE REVIEW

**Comment by tzdybal** [comment]
:lgtm: 
I have only one question about error message.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gql/parser.go, line 1900 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/885#-Kid1xYvZ8QHHeh4MrU1:-Kid1xYwXOYteCwrj3lX:b-6yr8q3) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe88f97f88e9a9373f3a5b90274f0b9c9bda84e/gql/parser.go#L1900)):*
> ```Go
> 				}
> 				if alias != "" {
> 					return x.Errorf("expand() cannot have an alias")
> ```

Why error about `expand`, if we're in `isMathBlock` case, not `isExpandFunc`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/885#-:-Kid3SuuE2IjlU3KKn07:b-foe9r0)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gql/parser.go, line 1900 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/885#-Kid1xYvZ8QHHeh4MrU1:-Kid3tCgQGiZ_D3Cu2Ei:bdnuhy3) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe88f97f88e9a9373f3a5b90274f0b9c9bda84e/gql/parser.go#L1900)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Why error about `expand`, if we're in `isMathBlock` case, not `isExpandFunc`?
</blockquote></details>

Ah my bad. Copy paste. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/885)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/885#-:-Kih6qVxcK2l3D7bJO4X:bnfp4nl)*

**Comment by ashwin95r** [comment]
Implements #885. Merged to master.

**Pull request closed without merging**
