### PR TITLE
Discard transaction method

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1731)

### CODE REVIEW

**Comment by peterstace** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/mutation.go, line 522 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-KyJ8_UvSkeokMCNmaM0:-KyJ8_UvSkeokMCNmaM1:bnehfd8) ([raw file](https://github.com/dgraph-io/dgraph/blob/a53785d22eacf2326f16f5b3d1494612f768641b/worker/mutation.go#L522)):*
> ```Go
> 		return 0, err
> 	}
> 	if !tc.Aborted && tctx.Aborted {
> ```

We were always giving a conflict error for aborts here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731)*

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 112 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-KyJKphjR1th3lX2KFzy:-KyJKphjR1th3lX2KFzz:b-y3l73f) ([raw file](https://github.com/dgraph-io/dgraph/blob/a53785d22eacf2326f16f5b3d1494612f768641b/client/txn.go#L112)):*
> ```Go
> 	txn.discarded = true
> 
> 	if txn.context == nil {
> ```

We probably shouldn't be doing this. This must have been set by mutation. And if not set, then we can just skip commitOrAbort call to Dgraph.

---

*[client/txn.go, line 146 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-KyJKMIodkqETgKWJkQg:-KyJKMIodkqETgKWJkQh:b-auo2ba) ([raw file](https://github.com/dgraph-io/dgraph/blob/a53785d22eacf2326f16f5b3d1494612f768641b/client/txn.go#L146)):*
> ```Go
> // In some cases, the transaction can't be discarded, e.g. the grpc connection
> // is unavailable. In these cases, the server will do the transaction clean up.
> func (txn *Txn) Discard(ctx context.Context) error {
> ```

We probably don't need two functions. Just move the abort logic to discard. And at the end of commit, nullify the txn context; so Abort avoids sending out a call to dgraph.

---

*[worker/mutation.go, line 522 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-KyJ8_UvSkeokMCNmaM0:-KyJL9t-pIEeyVGLIM76:briq1ir) ([raw file](https://github.com/dgraph-io/dgraph/blob/a53785d22eacf2326f16f5b3d1494612f768641b/worker/mutation.go#L522)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

We were always giving a conflict error for aborts here.
</blockquote></details>

Yeah, I think that error is the right thing to do here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731)*

**Comment by peterstace** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 112 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-KyJKphjR1th3lX2KFzy:-KyJhYysDDwpglNR8xqY:b-mbpqjo) ([raw file](https://github.com/dgraph-io/dgraph/blob/a53785d22eacf2326f16f5b3d1494612f768641b/client/txn.go#L112)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We probably shouldn't be doing this. This must have been set by mutation. And if not set, then we can just skip commitOrAbort call to Dgraph.
</blockquote></details>

Skipping commitOrAbort using flag now.

---

*[client/txn.go, line 146 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-KyJKMIodkqETgKWJkQg:-KyJhhnW4DqHEdYVyuSY:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/a53785d22eacf2326f16f5b3d1494612f768641b/client/txn.go#L146)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We probably don't need two functions. Just move the abort logic to discard. And at the end of commit, nullify the txn context; so Abort avoids sending out a call to dgraph.
</blockquote></details>

done

---

*[worker/mutation.go, line 522 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-KyJ8_UvSkeokMCNmaM0:-KyJhlunw1ZIUtMke1nb:b3ogo0j) ([raw file](https://github.com/dgraph-io/dgraph/blob/a53785d22eacf2326f16f5b3d1494612f768641b/worker/mutation.go#L522)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Yeah, I think that error is the right thing to do here.
</blockquote></details>

Reverted, but now giving a different error (aborted rather than conflicted).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1731#-:-KyJlWsaFLvR7vOzHtDd:bnfp4nl)*

**Pull request merged**
