### PR TITLE
Refactor/process task

### PR DESCRIPTION
**Pull request by pawanrawal**
This PR breaks the main loop in processTask into two small loops. One operates on posting lists which have uids, the other on those which have values.

Earlier we were calling `pl.ValueFor(lang)` even for index/reverse keys which were unnecessary and probably expensive. Also, the code had all these if/else (`if isValueEdge`) so seemed like a natural candidate for breaking into two functions.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1351)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[task/conversion.go, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7XXlWGPHXOCPULHSa:-Ks7XXlWGPHXOCPULHSb:b287r1q) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/task/conversion.go#L52)):*
> ```Go
> 	if len(val.Val) == 0 {
> 		return false
> 	}
> ```

Is this required ? ToInt would return 0 and we would end up returning false?

---

*[worker/task.go, line 304 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7XsWtTtSrXv772PAh:-Ks7XsWtTtSrXv772PAi:b-5ql04m) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/worker/task.go#L304)):*
> ```Go
> 		default:
> 			x.Fatalf("Unhandled function in handleValuePostings: %s", srcFn.fname)
> 		}
> ```

Replace switch with assert?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-:-Ks7YB7MroTkJxFEVImt:bnfp4nl)*

**Comment by tzdybal** [comment]
Only small comments. :lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 261 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7esjGq9YdiXhBSXzn:-Ks7esjGq9YdiXhBSXzo:b-mpi0ih) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/worker/task.go#L261)):*
> ```Go
> 
> // The function tells us whether we want to fetch value posting lists or uid posting lists.
> func fetchValuePostings(srcFn *functionContext, typ types.TypeID) bool {
> ```

I would rename the function - current name suggests that it actually fetches data.  I would move this to type to `functionContext` and rename to `needsValuePostings` or something similar. So the `if` statement would be like `if srcFn.needsValuePostings(typ) {`. At least rename function.

---

*[worker/task.go, line 304 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7XsWtTtSrXv772PAh:-Ks7gHBmkI5B6d3n9SoQ:b6xbcvo) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/worker/task.go#L304)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Replace switch with assert?
</blockquote></details>

I agree. Or maybe return error, instead of crashing the server?

---

*[worker/task.go, line 416 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7h3v7_hnJeigwbqsM:-Ks7h3v7_hnJeigwbqsN:b2wtnso) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/worker/task.go#L416)):*
> ```Go
> 			key = x.IndexKey(attr, srcFn.tokens[i])
> 		default:
> 			x.Fatalf("Unhandled function in handleUidPostings: %s", srcFn.fname)
> ```

Same as before - why `Fatalf` and not `Errorf`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-:-Ks7hy1Z-69kAlLclVO7:b-ikjyxy)*

**Comment by pawanrawal** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[task/conversion.go, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7XXlWGPHXOCPULHSa:-KsBQLZWB-XsF0P8A1wn:b7cm0oa) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/task/conversion.go#L52)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Is this required ? ToInt would return 0 and we would end up returning false?
</blockquote></details>

`val.Val` could be nil hence its required. 

---

*[worker/task.go, line 261 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7esjGq9YdiXhBSXzn:-KsBNNeN0X-s-cknrfH7:b-xcshhd) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/worker/task.go#L261)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

I would rename the function - current name suggests that it actually fetches data.  I would move this to type to `functionContext` and rename to `needsValuePostings` or something similar. So the `if` statement would be like `if srcFn.needsValuePostings(typ) {`. At least rename function.
</blockquote></details>

Agre. Done both.

---

*[worker/task.go, line 304 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7XsWtTtSrXv772PAh:-KsBNsU6hwuwy51fZkX3:b1jfrud) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/worker/task.go#L304)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

I agree. Or maybe return error, instead of crashing the server?
</blockquote></details>

Returning error. Also, I check unhandled function outside loop.

---

*[worker/task.go, line 416 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351#-Ks7h3v7_hnJeigwbqsM:-KsBO9UGLex35SPIKn4g:bkeh48f) ([raw file](https://github.com/dgraph-io/dgraph/blob/ef8c3c202d6cd3cffa3c7627ea1155e910e6c2f7/worker/task.go#L416)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Same as before - why `Fatalf` and not `Errorf`?
</blockquote></details>

Yup bad idea. Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1351)*

**Comment by pawanrawal** [comment]
Merged to master

**Pull request closed without merging**
