### PR TITLE
purge on delete

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1668)

### CODE REVIEW

**Comment by janardhan1993** [comment]
TODO:
Throw error if user is trying to read very old version,
During predicate move rollup and pass ts
Wait and abort transactions before schema mutation.

---

Review status: 0 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-:-KxGVsWyYSTbFaA1jn-z:bag5ius)*

**Comment by manishrjain** [comment]
Reviewed 12 of 16 files at r1, 17 of 17 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/testtxn/main.go, line 300 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGbW6b1U1PygmSulqI:-KxGbW6b1U1PygmSulqJ:b70d5ly) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/client/testtxn/main.go#L300)):*
> ```Go
> 
> 	time.Sleep(time.Second * 15)
> ```

Try to commit txn.x

---

*[cmd/dgraph-live-loader/main.go, line 140 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGcOuFPqtQ1YvLgj4b:-KxGcOuGDnyd7Z_dpH1z:b-qlgwpx) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/cmd/dgraph-live-loader/main.go#L140)):*
> ```Go
> 
> func (l *loader) uid(val string) (string, error) {
> 	if uid, err := strconv.ParseUint(val, 0, 64); err == nil {
> ```

You can probably remove this.

---

*[posting/index.go, line 543 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGcgaqFhL4NLnoAUOh:-KxGcgaqFhL4NLnoAUOi:byesyld) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/posting/index.go#L543)):*
> ```Go
> 
> 	for i := 0; i < 2; i++ {
> 		select {
> ```

No need for select case.

---

*[protos/task.proto, line 196 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGdPhzUtlSEz4XH_WM:-KxGdPhzUtlSEz4XH_WN:b-tofikt) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/protos/task.proto#L196)):*
> ```protobuf
> 	bytes val = 2;
> 	bytes userMeta = 3;
> 	uint64 ts = 4;
> ```

version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-:-KxGeHUD4K6gUN00n50U:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 24 of 29 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/testtxn/main.go, line 300 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGbW6b1U1PygmSulqI:-KxGejektP0ojcFoM1F0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/client/testtxn/main.go#L300)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Try to commit txn.x
</blockquote></details>

Done.

---

*[cmd/dgraph-live-loader/main.go, line 140 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGcOuFPqtQ1YvLgj4b:-KxGextddFzHD6BbAc-K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/cmd/dgraph-live-loader/main.go#L140)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can probably remove this.
</blockquote></details>

Done.

---

*[posting/index.go, line 543 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGcgaqFhL4NLnoAUOh:-KxGfAp6K8PkoJSPlgur:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/posting/index.go#L543)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for select case.
</blockquote></details>

Done.

---

*[protos/task.proto, line 196 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668#-KxGdPhzUtlSEz4XH_WM:-KxGfGVmHqY24kvowFn8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/15e564d4ba1cd06677bb45f12b41efd871c2349b/protos/task.proto#L196)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

version
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1668)*

**Pull request closed without merging**
