### PR TITLE
Dgraphloader check version and add docs for Go client.

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Loader now checks for the version of server on startup and notifies the user in case there is a mismatch.
2. Added GoDoc's for the client with examples.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/813)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/doc.go, line 18 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5OHgt2LHyYLQ-ZDu4:-Kh5OHgt2LHyYLQ-ZDu5:bxl5n5v) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/client/doc.go#L18)):*
> ```Go
> 	// See https://docs.dgraph.io/master/query-language/#assigning-uid for more details.
> 	// Adding the name attribute to the person.
> 	nq := graphp.NQuad{
> ```

I still don't see an example of batch mutations.

In general, it would be good to keep the 2 use cases separate. One is mutating data, which should be done via batch mutations. And second is querying for data, which should be done via this client.Run(..) method.

---

*[client/doc_test.go, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5OCCOru7ZIwwCj_KV:-Kh5OCCOru7ZIwwCj_KW:bw0rs6e) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/client/doc_test.go#L1)):*
> ```Go
> package client_test
> ```

file doc_test.go doesn't sound good. You can't be testing docs. Call it something else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/813)*

**Comment by janardhan1993** [comment]
Reviewed 9 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[client/doc_test.go, line 16 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5iRQRZI_yF5WQSO5j:-Kh5iRQSVc_4xVY3Sgwu:bb48l7q) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/client/doc_test.go#L16)):*
> ```Go
> 
> func ExampleBatchMutation() {
> 	// Make a connection to Dgraph.
> ```

Add examples for setting and getting schema also ?

---

*[cmd/dgraphloader/main.go, line 193 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5hLRZ4iXhA6o66HTA:-Kh5hLR_w0Luiw9M5mkL:bxdw27g) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/cmd/dgraphloader/main.go#L193)):*
> ```Go
> 	version := x.Version()
> 	if version != "" && v.Tag != "" && version != v.Tag {
> 		fmt.Printf(`
> ```

How about instead of returning latest version, we return the least version of dgraphloader which can work with the current version of dgraph and check that here. Since we make changes to client code rarely, older version of dgraphloader can run with the current version most of the times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/813)*

**Comment by pawanrawal** [comment]
Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/doc.go, line 18 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5OHgt2LHyYLQ-ZDu4:-Kh6KToFmkUjuRpqNn9w:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/client/doc.go#L18)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I still don't see an example of batch mutations.

In general, it would be good to keep the 2 use cases separate. One is mutating data, which should be done via batch mutations. And second is querying for data, which should be done via this client.Run(..) method.


</blockquote></details>

Done.

---

*[cmd/dgraphloader/main.go, line 193 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5hLRZ4iXhA6o66HTA:-Kh6Kc4BGw3F9eOvxw1e:blieoox) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/cmd/dgraphloader/main.go#L193)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

How about instead of returning latest version, we return the least version of dgraphloader which can work with the current version of dgraph and check that here. Since we make changes to client code rarely, older version of dgraphloader can run with the current version most of the times.
</blockquote></details>

We'd have to maintain that manually, the least version of dgraphloader which works with Dgraph. 
The idea is to just let the user know, so that if there is a discrepancy, he has an idea why.

---

*[client/doc_test.go, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5OCCOru7ZIwwCj_KV:-Kh6KaTsbbTTuYiNKRQ3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/client/doc_test.go#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

file doc_test.go doesn't sound good. You can't be testing docs. Call it something else.
</blockquote></details>

Done.

---

*[client/doc_test.go, line 16 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/813#-Kh5iRQRZI_yF5WQSO5j:-Kh6KazJwhLvbQyW5Let:bb74ce2) ([raw file](https://github.com/dgraph-io/dgraph/blob/c480763ac7833d545c8cbfb097264cde52632a39/client/doc_test.go#L16)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Add examples for setting and getting schema also ?
</blockquote></details>

Sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/813)*

**Comment by pawanrawal** [comment]
merged to release.

**Pull request closed without merging**
