### PR TITLE
Intersect DestUids with results from filter

### LINKED ISSUE #1455: Filter may override root query in v0.8.1
Steps to reproduce:

* schema and test data
```
mutation {
  schema {
    test_key: string @index(exact) .
    test_value: string @index(exact) .
  }
  set {
    _:test_1 <test_key> "key1" .
    _:test_1 <test_value> "value1" .
    _:test_2 <test_key> "key2" .
    _:test_2 <test_value> "value2" .
  }
}
```
* query
```
{
  v as var(func: eq(test_key, "key1")) @filter(eq(test_key, "key2"))
}
{
  q(func: uid(v)) {
    test_key
    test_value
  }
}
```
* actual response - should be empty? 
```json
{
  "data": {
    "q": [
      {
        "_uid_": "0x11945",
        "test_key": "key2",
        "test_value": "value2"
      }
    ],
    "server_latency": {
      "processing": "310µs",
      "json": "104µs",
      "total": "604µs",
      "parsing": "184µs"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by pawanrawal**
This fixes #1455.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1456)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 1854 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1456#-KtxmxGpGcus__XAOCAJ:-KtxmxGpGcus__XAOCAK:b-gxtenr) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f902b3688df9c50c4c8b6d4116259e0353c5364/query/query.go#L1854)):*
> ```Go
> 			// DestUIDs.
> 			// me(func: eq(key, "key1")) @filter(eq(key, "key2"))
> 			lists = append(lists, sg.DestUIDs)
> ```

Ideally it should have already been intersected with sg.DestUids.
Say we have a src uid 1, and filter on type comment which is a big list, it seems like we are fetching the whole pl for type comment and intersecting it here, ideally which should be doing the intersection on remote server and get back only the relevant uids. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1456#-:-Ktxkvye2GgAVAoIuZcU:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 1854 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1456#-KtxmxGpGcus__XAOCAJ:-Ktxnau1q4rE1FN4AcOO:b-2en74) ([raw file](https://github.com/dgraph-io/dgraph/blob/1f902b3688df9c50c4c8b6d4116259e0353c5364/query/query.go#L1854)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Ideally it should have already been intersected with sg.DestUids.
Say we have a src uid 1, and filter on type comment which is a big list, it seems like we are fetching the whole pl for type comment and intersecting it here, ideally which should be doing the intersection on remote server and get back only the relevant uids. 
</blockquote></details>

may be Add a todo to look into it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1456)*

**Comment by janardhan1993** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1456)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1456#-:-Ku2HXeenHKYMq0MiQW2:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
