### PR TITLE
[WIP] Initial schema generation from input types.

### PR DESCRIPTION
**Pull request by animesh2049**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3543)

### CODE REVIEW

**Comment by MichaelJCompton** [comment]
Note: we won't merge this yet -> my initial GraphQL branch has to go in first.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 43 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3n9KlBB0bnRZS5p9_:-Lh5MPX-7hqVMscgAmLC:b-p3390j) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L43)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

Can you confirm that the gql lib doesn't allow type names that are the same names as these scalars -> if it allows them, then we need to add a rule to exclude that.
</blockquote></details>

I tried putting 
```
type Bool {
  id: ID!
  name: String
}
```
in schema. gql library didn't raise any error.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 63 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3nbdlA6AAgFs77nAC:-Lh5N5WECCjedg_68Tj9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L63)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

tmpRVal -> gqlErr
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 68 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3o92E0N49ATsgdl8A:-Lh5NEFa04ExuJHFbqCb:bq0w62l) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L68)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

just return errs and when calling check len(..) -> that'll work even for nil slice
</blockquote></details>

If `len(slice) == 0`, slice itself won't be nil. It will have an empty array. It will break the validation
`if err != nil {..}` everywhere.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 103 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3rmG_40L5TevusNbE:-Lh5RnHwC6yAO4ZnIBsM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L103)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

this is different to the way the ones above work - i.e. they return the created object.  Is there a reason for the difference?  Might be better to have this as returning it and adding to the query object in here.
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 108 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3pexV0hQAvoYiS65u:-Lh5SC2d9Zaa8KS5lqt8:b-ujmnh5) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L108)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

Don't think you need to do this.  I think you can safely add straight to the schema.Types.
</blockquote></details>

I am simply merging two maps. I am not sure in what other way it can be done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 151 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3qwZI49BRuSBTnMFo:-Lh5T-nH13fTwq_M-HSu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L151)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

return
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 128 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3qjMp98Z0H1E40LzL:-Lh5SuCD4xFINf0zuD0H:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L128)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

again, just return it
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 119 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3qFne-82VFv4btl54:-Lh5St2M2rTwbF4SzXnT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L119)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

just

return &ast.Definition { ...}
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 164 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3rD39Ey-Tpwwof3NT:-Lh5T8on7K4XgMUvhAWl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L164)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

yep always true
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 169 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3rEuq2TDP1ljDJofI:-Lh5Wh4d1XEvKgW-lP0X:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L169)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

again probably clearer as one return statement
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 182 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3rNiL47KgyyIV18R8:-Lh5WxUP87ozUlshiW6k:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L182)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

always true
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 187 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3rSQCDNXEvWgzDvvG:-Lh5X58N4an1P2CTMSJO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L187)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

again, can we do as one return statement
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 210 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3s8tN1lQMu9yWlh9G:-Lh5XcNr3PAK3hT5OqyM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L210)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

"Query " + defn.Name + " by ID"
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 214 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3s6eL4cY7ALPym-p-:-Lh5XdiuC8Fw--GlQiYR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L214)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

yep should be true
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 230 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3t67c5tQd0fZqZDuH:-Lh5Xrks-Z4DQsybqnEn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L230)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

"Query " + def.Name
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 337 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3qCJs0okBRXecB352:-Lh5YCefEGWXoDGNL8Bo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L337)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

remove old comment
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 371 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3ujc09AL7pTt08ibt:-Lh5YQXF1-nZ2iprKw3B:b-joi03w) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L371)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

shouldn't this return a single field?
</blockquote></details>

This will return a  single field because we can have at max one field with type `ID`. But I have put `break` statement inside the if block.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 446 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh4Cfyq8npNnNfpCDDL:-Lh5ZyLlDDd5rRKDAG1v:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L446)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

might be easier to build a slice with a string for each arg and then strings.join(args, ", ")
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 462 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh4D2oU0Goj_Jb7ZYMK:-Lh5_DKc-zJ6CHfgum2B:b52ckz0) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L462)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

I think you could just write to a single builder.  Doesn't seem to be any reason for all these.
</blockquote></details>

I did this so that I can reorder all types in the final schema string. Should I revert it to use only one ?

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schemarules/single_type_per_id.go, line 12 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh4EWYN-T9ukFMC_k3r:-Lh5ctwOB77c1u1P9HqV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schemarules/single_type_per_id.go#L12)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

I think this should be Types no PossibleTypes
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schemarules/single_type_per_id.go, line 13 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh4EB7N-sklwZgsfOoD:-Lh5cy8KEZxS1lHY-GaJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schemarules/single_type_per_id.go#L13)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

bool and return error as soon as we see a dup ID ?
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 79 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3oqJg2vrHMpaPH6_R:-Lh5dGlSDxll0ARBFrxZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L79)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

add a rule that query and mutation types shouldn't exist in the input schema
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 205 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3rZsq1jhhwbeaK5G9:-Lh5XISq2QW0uCYofQbA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L205)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

again one return
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 245 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3sOLWDCiRDpogrX3X:-Lh5e2rs5Ao1Rm7vmXY2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L245)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

nope, make it true
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 320 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3snTI9YQ2xpwbawPJ:-Lh5kkSU7ZeTdNZiy9Md:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L320)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

again, I'd split into three functions and make each a single return statement.
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 250 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3sT5d2zFkx3FoMP4M:-Lh5kjkEEa09aLh5REMs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L250)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

I'd split this into two functions - one to create get & one to create query.  Then see comment in GenerateCompleteSchema
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 227 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh3sKr01sJ8gmZYalz5:-Lh5kiZI9gCq3PsOucWw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L227)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

again, just one create statement
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schema.go, line 477 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh4DEOy0PKQJmgj2PK4:-Lh5lNNSB1WE_cmjsoTB:bj95pop) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schema.go#L477)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

why aren't these covered by the ast.InputObject case? 
</blockquote></details>

Done. Yeah this is redundant.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schemarules/no_query_mutation_in_initial_schema.go, line 1 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-LhJL29H4JTgBEDkGSbg:-LjZyaPS0t7VuEehXeNX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6415d3a3cd9efa435630ce5066b05b784713a8d8/dgraph/cmd/graphql/schema/schemarules/no_query_mutation_in_initial_schema.go#L1)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

can you pls add tests around these rules.  Something simple like one failing test case for each rule type.  Something like a test of InputSchemaCantIncludeQueryType(...) etc
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
___
*[dgraph/cmd/graphql/schema/schemarules/single_type_per_id.go, line 10 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/3543#-Lh4E-tXEwupfailonJn:-LjZye4DDjrB_zrc6p6l:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f5ce75cb95080531b16d2a0a9057caec1811392b/dgraph/cmd/graphql/schema/schemarules/single_type_per_id.go#L10)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

there's a few more rules in the spec (as well as another mentioned in the review above)
</blockquote></details>

Done.

**Comment by animesh2049** [comment]
Raised another PR.

**Pull request closed without merging**
