### PR TITLE
Migrate index tests to travis

### PR DESCRIPTION
**Pull request by jchiu0**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/476)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm: We seem to be counting only the number of times a particular entity name has occurred. Can't think of a better way to compare them other than storing the JSON results and doing sort of a JSON comparision with the response received.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/476#-:-KaGp8acQdAMaQr5K1YY:b-joo1br)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/476#-:-KaGrsUBf3yt9fQdVg1O:bnfp4nl)*

**Comment by pawanrawal** [comment]
Sorry wait, dgraph is not run with the schemafile. How does this even work?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/476#-:-KaGs503UTPbJUwD_aQM:b87r61k)*

**Comment by jchiu0** [comment]
Thanks Ashwin and Pawan. I have added the schema file.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/476#-:-KaL-cfh3wxjvCemSNcZ:b-aqqgkx)*

**Pull request closed without merging**
