### PR TITLE
feat(tool/decrypt): Add dgraph decrypt tool

### PR DESCRIPTION
**Pull request by OmarAyo**
Create a tool `dgraph tool decrypt` to decrypt encrypted export data.

e.g.
```
$ dgraph tool -h
[Decoder]: Using assembly version of decoder
A suite of Dgraph tools

Usage:
  dgraph tool [command]

Available Commands:
  decrypt     Run Decrypt tool
```

```
$ dgraph tool decrypt -h
[Decoder]: Using assembly version of decoder
A tool to decrypt an export file created by an encrypted Dgraph cluster

Usage:
  dgraph tool decrypt [flags]

Flags:
      --encryption_key_file string   The file that stores the symmetric key of length 16, 24, or 32 bytes. The key size determines the chosen AES cipher (AES-128, AES-192, and AES-256 respectively). Enterprise feature.
  -f, --file string                  Path to file to decrypt.
  -h, --help                         help for decrypt
  -o, --out string                   Path to the decrypted file.
      --vault_addr string            Vault server's address in the form http://ip:port. (default "http://localhost:8200")
      --vault_field string           Vault kv store field whose value is the Base64 encoded encryption key. (default "enc_key")
      --vault_format string          Vault field format. raw or base64 (default "base64")
      --vault_path string            Vault kv store path. e.g. secret/data/dgraph for kv-v2, kv/dgraph for kv-v1. (default "secret/data/dgraph")
      --vault_roleid_file string     File containing Vault role-id used for approle auth.
      --vault_secretid_file string   File containing Vault secret-id used for approle auth.
```

Changes:
* feat: Add `dgraph tool decrypt` command
* chore(ee): Remove glog when reading encryption key file.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7248)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
Use `gofmt` to format the code. The error handling / output can be improved. And, it's time to have a better-organized `--help` output and/or put this under a "tool" subcommand. e.g., this could be "dgraph tool decrypt". There are a lot of `dgraph` subcommands now.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-:-MQIYR6CCy9_5DpTIknT:bkw2rrj)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @danielmai, @manishrjain, @OmarAyo, and @vvbalaji-dgraph)

___
*[dgraph/cmd/decrypt/run.go, line 55 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQIXxtPAgc5OB4NykSG:-MQIXxtPAgc5OB4NykSH:b-8yf2ga) ([raw file](https://github.com/dgraph-io/dgraph/blob/c11d4236ae61a426492612324c46ac6ad59e3e35/dgraph/cmd/decrypt/run.go#L55)):*
> ```
> "keyfile"
> ```
This flag should be `encryption_key_file` so it's consistent with the rest of the subcommand flags.
___
*[dgraph/cmd/decrypt/run.go, line 57 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQIYDm1EZoExIms_1jM:-MQIYCeZDfy4CeYGLtnH:bt98y3z) ([raw file](https://github.com/dgraph-io/dgraph/blob/c11d4236ae61a426492612324c46ac6ad59e3e35/dgraph/cmd/decrypt/run.go#L57)):*
> ```Go
> 	flag.StringVar(&opts.keyfile, "keyfile", "", "Location of the key file to decrypt the schema "+
> 		"and data files")
> 	flag.StringVar(&opts.file, "file", "", "Path to file to decrypt")
> ```

Make this a StringVarP to have a shorthand flag `f`.
___
*[dgraph/cmd/decrypt/run.go, line 58 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQIYJTQ5onDMc-l5yjp:-MQIYJTQ5onDMc-l5yjq:bt994s8) ([raw file](https://github.com/dgraph-io/dgraph/blob/c11d4236ae61a426492612324c46ac6ad59e3e35/dgraph/cmd/decrypt/run.go#L58)):*
> ```Go
> 		"and data files")
> 	flag.StringVar(&opts.file, "file", "", "Path to file to decrypt")
> 	flag.StringVar(&opts.output, "output", "", "Path to output.")
> ```

Make this a StringVarP to have a shorthand flag `o`.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/decrypt/run.go, line 55 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQIXxtPAgc5OB4NykSG:-MQMpQCzDr08GvhH3F_M:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c11d4236ae61a426492612324c46ac6ad59e3e35/dgraph/cmd/decrypt/run.go#L55)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> "keyfile"
> ```
This flag should be `encryption_key_file` so it's consistent with the rest of the subcommand flags.
</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/decrypt/run.go, line 57 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQIYDm1EZoExIms_1jM:-MQMpPYdEVC0QzSkizXq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c11d4236ae61a426492612324c46ac6ad59e3e35/dgraph/cmd/decrypt/run.go#L57)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Make this a StringVarP to have a shorthand flag `f`.
</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[dgraph/cmd/decrypt/run.go, line 58 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQIYJTQ5onDMc-l5yjp:-MQMpQmV69OTmVS4M5e7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c11d4236ae61a426492612324c46ac6ad59e3e35/dgraph/cmd/decrypt/run.go#L58)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Make this a StringVarP to have a shorthand flag `o`.
</blockquote></details>

Done.

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7248)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @danielmai, @manishrjain, @OmarAyo, and @vvbalaji-dgraph)

___
*[dgraph/cmd/decrypt/run.go, line 55 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQIXxtPAgc5OB4NykSG:-MQONQVk24VIzGqa38R3:b-l2toou) ([raw file](https://github.com/dgraph-io/dgraph/blob/c11d4236ae61a426492612324c46ac6ad59e3e35/dgraph/cmd/decrypt/run.go#L55)):*
<details><summary><i>Previously, OmarAyo (OmarAyo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, there's an `enc.RegisterFlags(flag)` that would register this flag. We shouldn't have a short-hand flag.
___
*[dgraph/cmd/tool/decrypt/decrypt.go, line 53 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-MQOMhtC3vJgIOl1pG2t:-MQOMhtDAwSKxuEMvYO7:b-ta3x8e) ([raw file](https://github.com/dgraph-io/dgraph/blob/3dec9d64d34911a6a17042b28b2a8ba7a79c3aec/dgraph/cmd/tool/decrypt/decrypt.go#L53)):*
> ```Go
> 		},
> 	}
> 	Decrypt.EnvPrefix = "DGRAPH_DECRYPT"
> ```

How does this work? I feel like the environment variables should be "DGRAPH_TOOL_DECRYPT".

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7248#-:-MQOeXUn5ekP4GmROnXB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain and @vvbalaji-dgraph)

**Pull request merged**
