### PR TITLE
mark the variables as done even if subgraph is not visited

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/740)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 920 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-KfsVNU843L4Ejxt4d8I:-KfsVNU843L4Ejxt4d8J:barvcma) ([raw file](https://github.com/dgraph-io/dgraph/blob/99524a0cfc648388f2331e1c175d3b4ac3686c9b/query/query.go#L920)):*
> ```Go
> 			for _, v := range res.QueryVars[idx].Defines {
> 				if _, ok := doneVars[v]; !ok {
> 					doneVars[v] = values{}
> ```

This can be moved to populateVarMap's else condition. No need to iterate separately I guess?

---

*[query/query.go, line 1032 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-KfsVbpBgLFSPOJpSgz1:-KfsVbpBgLFSPOJpSgz2:btc5atg) ([raw file](https://github.com/dgraph-io/dgraph/blob/99524a0cfc648388f2331e1c175d3b4ac3686c9b/query/query.go#L1032)):*
> ```Go
> 				doneVars[sg.Params.Var].vals[uid] = val
> 			}
> 		}
> ```

Here.
```
else {
 doneVars[sg.params.Var] = values{}
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/740)*

**Comment by janardhan1993** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 920 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-KfsVNU843L4Ejxt4d8I:-KftIRHolZRvvR8B4uDR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/99524a0cfc648388f2331e1c175d3b4ac3686c9b/query/query.go#L920)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This can be moved to populateVarMap's else condition. No need to iterate separately I guess?
</blockquote></details>

Done.

---

*[query/query.go, line 1032 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-KfsVbpBgLFSPOJpSgz1:-KftIS1FXRBQcmI-rRIc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/99524a0cfc648388f2331e1c175d3b4ac3686c9b/query/query.go#L1032)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Here.
```
else {
 doneVars[sg.params.Var] = values{}
}
```
</blockquote></details>

Done.

---

*[query/query.go, line 847 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-KftIV71-NCBd6PxOGpR:-KftIV71-NCBd6PxOGpS:b-hks8wh) ([raw file](https://github.com/dgraph-io/dgraph/blob/1a0bca20316ca4c91cf95b90069fcea27cd7840c/query/query.go#L847)):*
> ```Go
> 
> 	var shortestSg *SubGraph
> 	for i := 0; i < len(sgl) && numQueriesDone < len(sgl); i++ {
> ```

Just to ensure we don't get stuck in infinite loop for safety. This loop should be executed at most N times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/740)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 920 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-KfsVNU843L4Ejxt4d8I:-KftMbLyXFHYvaPBBRMh:b-z4rd2a) ([raw file](https://github.com/dgraph-io/dgraph/blob/99524a0cfc648388f2331e1c175d3b4ac3686c9b/query/query.go#L920)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We don't need this now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-:-KftMg-9Luu-xe-uDcUI:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query.go, line 920 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-KfsVNU843L4Ejxt4d8I:-KftSs81NiU1d2fZU4-U:b-czunma) ([raw file](https://github.com/dgraph-io/dgraph/blob/99524a0cfc648388f2331e1c175d3b4ac3686c9b/query/query.go#L920)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We don't need this now?
</blockquote></details>

sorry forgot to remove, removed now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/740)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/740#-:-KftTfC0vNO_tWrqhrMm:bnfp4nl)*

**Pull request merged**
