### PR TITLE
Async/writes

### PR DESCRIPTION
**Pull request by pawanrawal**
We get rid of syncCh and call BatchSetAsync for badger. Also, we delete posting list from lru cache after badger callback returns.

Corresponding PR for Badger https://github.com/dgraph-io/badger/pull/101

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1178)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 736 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1CLFy3UFj-dh9ou5:-Kop1CLFy3UFj-dh9ou6:b-ahbngx) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L736)):*
> ```Go
> 		}
> 		if l.water != nil {
> 			l.water.Ch <- x.Mark{Indices: l.pending, Done: true}
> ```

copy l.pending

---

*[posting/list.go, line 746 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1JGlyT1bt_8nnZ7l:-Kop1JGlyT1bt_8nnZ7m:b-3gxnyu) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L746)):*
> ```Go
> 	wb = badger.EntriesSet(wb, l.key, data)
> 	pstore.BatchSetAsync(wb, f)
> 	l.incr()
> ```

no need to incr()

---

*[posting/lists.go, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1PsRgkLZiCSG8QXG:-Kop1PsRgkLZiCSG8QXH:b-qgzv18) ([raw file](https://github.com/dgraph-io/dgraph/blob/07abc9a22252d7a12085c2c563663545f7de1063/posting/lists.go#L119)):*
> ```Go
> 	case pending <- struct{}{}:
> 	default:
> 		elog.Printf("Skipping gentleCommit len(syncCh) %v,\n", len(syncCh))
> ```

keep the printf without len of syncch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 736 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1CLFy3UFj-dh9ou5:-Kop2VSzPfEeI_aS_625:bnxe8fq) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L736)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

copy l.pending
</blockquote></details>

pass reference to l.pending in go routine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[posting/list.go, line 736 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1CLFy3UFj-dh9ou5:-KopAlrzMRydy0EIXEg0:be65wut) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L736)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

pass reference to l.pending in go routine
</blockquote></details>

Done. I hold a ref now.

---

*[posting/list.go, line 746 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1JGlyT1bt_8nnZ7l:-KopAp82vNioTwSaHL1b:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L746)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

no need to incr()
</blockquote></details>

Done.

---

*[posting/lists.go, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1PsRgkLZiCSG8QXG:-KopBCYPSf4JIY9VFpG1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/07abc9a22252d7a12085c2c563663545f7de1063/posting/lists.go#L119)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

keep the printf without len of syncch
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 746 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1JGlyT1bt_8nnZ7l:-Korg7o80RAbVSTWmOug:b-q81usn) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L746)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't fit a square peg into round hole. What you're really doing is `pstore.SetAsync`. Think about what APIs you need, because you control them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[posting/list.go, line 746 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1JGlyT1bt_8nnZ7l:-KottTT9Ap8lJ8hbztSf:b-ryz74b) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L746)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't fit a square peg into round hole. What you're really doing is `pstore.SetAsync`. Think about what APIs you need, because you control them.
</blockquote></details>

Using `SetAsync` now and `DeleteAsync` now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[posting/list.go, line 746 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kop1JGlyT1bt_8nnZ7l:-Kou0JOR-uSffQDkT9bl:b2nhktp) ([raw file](https://github.com/dgraph-io/dgraph/blob/c682ac90d4337854a90219f3ecdfc395bb3f7f78/posting/list.go#L746)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Using `SetAsync` now and `DeleteAsync` now.
</blockquote></details>

OK.

---

*[posting/list.go, line 739 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou1kWVrPC_pW-Cxg8u:-Kou1kWVrPC_pW-Cxg8v:br0qify) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/list.go#L739)):*
> ```Go
> 	maxRetries := 5
> 	retries := 0
> 	pending := l.pending
> ```

Add a comment about why are you dereferencing it here.

---

*[posting/list.go, line 744 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou1R_LnR6Xf9d-pCC4:-Kou1R_LnR6Xf9d-pCC5:biexcbl) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/list.go#L744)):*
> ```Go
> 		if err != nil {
> 			elog.Printf("Got err in while doing async writes in SyncIfDirty: %+v", err)
> 			if retries > maxRetries {
> ```

maxRetries seems to be used only once. So, just hardcode it here. `if retries > 5`

---

*[posting/list.go, line 758 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou0m0Ptzvlm_yqGsWh:-Kou0m0Ptzvlm_yqGsWi:bonoysq) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/list.go#L758)):*
> ```Go
> 		if delFromCache {
> 			lcache.Lock()
> 			delete(lcache.cache, l.ghash)
> ```

I presume it's already deleted from the other things in LRU cache? If so, add a comment.

---

*[posting/lru.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou18tv0M3lGhhOuDo6:-Kou18tv0M3lGhhOuDo7:becj5na) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/lru.go#L173)):*
> ```Go
> 		kv.pl.SetForDeletion()
> 		kv.pl.SyncIfDirty(true)
> 		kv.pl.decr()
> ```

This decr isn't required, right? We should test this change thoroughly before submitting.

@janardhan1993 : Can you (or help Pawan) run this on a big dataset. Maybe the SO data; run this for an hour on one server and see if things crash.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[posting/lru.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou18tv0M3lGhhOuDo6:-KouDC1dqsfCsctt-jBf:b-pyfi6) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/lru.go#L173)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This decr isn't required, right? We should test this change thoroughly before submitting.

@janardhan1993 : Can you (or help Pawan) run this on a big dataset. Maybe the SO data; run this for an hour on one server and see if things crash.
</blockquote></details>

 I have started running this on stackoverflow data. This clear is triggered only when we 
do delete predicate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[posting/lru.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou18tv0M3lGhhOuDo6:-KouE6hktJGHlyyS-7LO:bc2hx2s) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/lru.go#L173)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

 I have started running this on stackoverflow data. This clear is triggered only when we 
do delete predicate.
</blockquote></details>

This extra decr would be caught in our unit tests i think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by pawanrawal** [comment]
Review status: 1 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[posting/list.go, line 739 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou1kWVrPC_pW-Cxg8u:-KouGKEwmMjkI5voXeWl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/list.go#L739)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment about why are you dereferencing it here.
</blockquote></details>

Done.

---

*[posting/list.go, line 744 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou1R_LnR6Xf9d-pCC4:-KouGJnhAQRgK_jNhKDM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/list.go#L744)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

maxRetries seems to be used only once. So, just hardcode it here. `if retries > 5`
</blockquote></details>

Done.

---

*[posting/list.go, line 758 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou0m0Ptzvlm_yqGsWh:-KouH_ur4NdSPYsT5B3k:bgh79mq) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/list.go#L758)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I presume it's already deleted from the other things in LRU cache? If so, add a comment.
</blockquote></details>

Deleting it from list here because it could have been put back.

---

*[posting/lru.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Kou18tv0M3lGhhOuDo6:-KoutVjNdEa1rupo85ss:b-hu0z0s) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9966cbf2838ce2fcd0e61ab500fbfa1710e2873/posting/lru.go#L173)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This extra decr would be caught in our unit tests i think.
</blockquote></details>

We now do it if the callback won't be called, i.e. if SyncIfDirty returns committed false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by pawanrawal** [comment]
We ran it for more than 1 hour with SO data on i3 instance and it worked well.

---

Review status: 1 of 7 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-:-KoymSitMrcy1wedKnFy:b-3f17ux)*

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[posting/list.go, line 757 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-KoyzkTq__SYt5Cs8imv:-KoyzkTq__SYt5Cs8imw:b-snoppi) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/list.go#L757)):*
> ```Go
> 			l.water.Ch <- x.Mark{Indices: pending, Done: true}
> 		}
> 		if delFromCache {
> ```

We should assert that we have marked this list for deletion.

---

*[posting/list.go, line 760 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Koyz3hHwgp1zoJtbvaD:-Koyz3hHwgp1zoJtbvaE:b-2tsdfm) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/list.go#L760)):*
> ```Go
> 			lcache.Lock()
> 			ele := lcache.cache[l.ghash]
> 			// We delete it from link list but if someone calls Get before callback is called it
> ```

linked list (not link list).

If you're doing the whole thing where you're deleting from both map and list, then why not just call an API on the cache itself? The resulting code would be clear and maintainable.

---

*[posting/lru.go, line 114 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Koz-UL9hjhxJyPy3w1R:-Koz-UL9hjhxJyPy3w1S:b-873kuy) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/lru.go#L114)):*
> ```Go
> 		// If length of mutation layer is zero, then we won't call pstore.SetAsync and the
> 		// key wont be deleted from cache. So lets delete it now if SyncIfDirty returns false.
> 		if committed, _ := e.pl.SyncIfDirty(true); !committed {
> ```

This logic could be done from SyncIfDirty itself. Why not there?

---

*[posting/lru.go, line 178 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Koz-jtXG22TlHefM9Wv:-Koz-jtXG22TlHefM9Ww:b-37aexv) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/lru.go#L178)):*
> ```Go
> 		kv.pl.SetForDeletion()
> 		if committed, _ := kv.pl.SyncIfDirty(true); !committed {
> 			delete(c.cache, kv.pl.ghash)
> ```

Again, I think this logic belongs to SyncIfDirty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by pawanrawal** [comment]
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[posting/list.go, line 757 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-KoyzkTq__SYt5Cs8imv:-Koz6t0kFsra2zcKPRYt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/list.go#L757)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We should assert that we have marked this list for deletion.
</blockquote></details>

Done.

---

*[posting/list.go, line 760 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Koyz3hHwgp1zoJtbvaD:-Koz8gQS3aMJ3979o7NB:blne1oc) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/list.go#L760)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

linked list (not link list).

If you're doing the whole thing where you're deleting from both map and list, then why not just call an API on the cache itself? The resulting code would be clear and maintainable.
</blockquote></details>

Sounds good, doing it now.

---

*[posting/lru.go, line 114 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Koz-UL9hjhxJyPy3w1R:-KozCDLcmdkY70aBGM1o:bdikr3k) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/lru.go#L114)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This logic could be done from SyncIfDirty itself. Why not there?
</blockquote></details>

I already hold a lock here so I can delete it from cache. In SyncIfDirty I can't assume I have a lock. I could call an API from SyncIfDirty that asserts lock is held, but we dont have a `SafeMutex` right now.

---

*[posting/lru.go, line 178 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-Koz-jtXG22TlHefM9Wv:-Koz9VMQdBi9JIhZwEv3:b2nreh6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f333b065e071556b04f11f510b50b223e36f44c3/posting/lru.go#L178)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Again, I think this logic belongs to SyncIfDirty.
</blockquote></details>

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 758 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-KozqSuU9zv61FwykffY:-KozqSuU9zv61FwykffZ:b-kuaamq) ([raw file](https://github.com/dgraph-io/dgraph/blob/fcd5a90575c390d7e0438f97f4f926def0c92a19/posting/list.go#L758)):*
> ```Go
> 		}
> 		if delFromCache {
> 			x.AssertTruef(atomic.LoadInt32(&l.deleteMe) == 1,
> ```

can just be assert true. cheaper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-:-KozrEn94saG-ZPh4y7g:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 758 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178#-KozqSuU9zv61FwykffY:-Koztg5offYn0zJV9rPS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fcd5a90575c390d7e0438f97f4f926def0c92a19/posting/list.go#L758)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can just be assert true. cheaper.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1178)*

**Comment by pawanrawal** [comment]
Merged to master

**Pull request closed without merging**
