### PR TITLE
Store node predicates. Support expand(_all_)

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/856)

### CODE REVIEW

**Comment by tzdybal** [comment]
Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 74 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki97PVc5LjlohN-B9km:-Ki97PVc5LjlohN-B9kn:b-n502h) ([raw file](https://github.com/dgraph-io/dgraph/blob/dc6ec2f96d5c5fb23ac956957584976ff6a515ac/gql/parser_test.go#L74)):*
> ```Go
> 	require.NoError(t, err)
> }
> ```

There are no tests for error cases (like multiple vars, etc).

---

*[posting/list.go, line 624 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki980O63-rGt8QzLJIF:-Ki980O7DlYkue9Jv6qC:b-y19j5r) ([raw file](https://github.com/dgraph-io/dgraph/blob/dc6ec2f96d5c5fb23ac956957584976ff6a515ac/posting/list.go#L624)):*
> ```Go
> 
> 	l.iterate(0, func(p *typesp.Posting) bool {
> 		fmt.Println(p.Value, p.PostingType, "...")
> ```

Remove debug `Println`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by ashwin95r** [comment]
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser_test.go, line 74 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki97PVc5LjlohN-B9km:-Ki9F04B_aC_r8mBHLr3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dc6ec2f96d5c5fb23ac956957584976ff6a515ac/gql/parser_test.go#L74)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

There are no tests for error cases (like multiple vars, etc).
</blockquote></details>

Done.

---

*[posting/list.go, line 624 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki980O63-rGt8QzLJIF:-Ki9EySCfJIKPgWuG0Nv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dc6ec2f96d5c5fb23ac956957584976ff6a515ac/posting/list.go#L624)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

Remove debug `Println`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by janardhan1993** [comment]
Reviewed 10 of 12 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[query/outputnode.go, line 210 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9GnVzGaHd-8MbvwDn:-Ki9GnVzGaHd-8MbvwDo:bttnfde) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/outputnode.go#L210)):*
> ```Go
> 			n.AddListChild(sg.Params.Alias, n1)
> 			if sg.Params.Alias == "listpred" {
> 				// For listpred block, we only want to return the list once for all the UIDs.
> ```

Not sure, there might be usecases when you want to listpredicates for all nodes. For example: Say if we are storing list of items, then each node might have different set of predicates even though they might share some predicates. Does it make sense to expand _predicate_ per node ?

Nevertheless,  if listpred contains other predicates it would be expanded for first uid only.
listpred(func:anyofterms(name,"Alice2 Alice")) {
name
_predicate_
}

Similarly for the case for 
listpred(func:anyofterms(name,"Alice2 Alice")) {
name

}
Only single results would be returned(though _predicate_ is not present here)

---

*[query/query.go, line 280 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9LWFJYx2zDTSUYpir:-Ki9LWFJYx2zDTSUYpis:b-czynku) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L280)):*
> ```Go
> 				sv, err := types.Convert(v, v.Tid)
> 				uc := dst.New(pc.Attr)
> 				uc.AddValue("name", sv)
> ```

If we already have a predicate called name, then we would get wrong results when we use normalize. Give it a better name so that it works well with normalize.

---

*[query/query.go, line 514 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9M6aX0FBrESK0nQ6_:-Ki9M6aYoxFDZMGLusLO:bc9j5at) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L514)):*
> ```Go
> 		if _, ok := attrsSeen[key]; ok {
> 			return x.Errorf("%s not allowed multiple times in same sub-query.",
> 				key)
> ```

I think we need to handle the case of expand(_all_), otherwise when both expand(_all_) and predicate is present in the query block, then server would crash due to our assertion in the code that same predicate can't be seen multiple times

---

*[worker/task.go, line 207 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9DrRZ31epf5brlP7O:-Ki9DrRZ31epf5brlP7P:b-nqa4f5) ([raw file](https://github.com/dgraph-io/dgraph/blob/dc6ec2f96d5c5fb23ac956957584976ff6a515ac/worker/task.go#L207)):*
> ```Go
> 			}
> 		}
> 		for pred := range predMap {
> ```

This doesn't return list of predicates per node. And might return different results for same node depending on src uid's.(Should be fine if we don't expand _predicate_ per uid)

Example:
mutation {
set {
<Alice> <name> "Alice 1" .
<Alice2> <name> "Alice2" .
<Alice2> <age> "42"^^<xs:int> .
}
schema {
name:string @index .
}
}

query {
#would return name for <Alice>
me(func:anyofterms(name,"Alice")) {
name
_predicate_
}

#would return name, age for <Alice>
me2(func:anyofterms(name,"Alice2 Alice")) {
name
_predicate_
}

}

---

*[x/values.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki8WwugS34ch6LSuHVg:-Ki8WwugS34ch6LSuHVh:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/eea8d0effb9917415162b17c456f272e618d19ff/x/values.go#L28)):*
> ```Go
> 	ValueUid                          // UID
> 	ValuePlain                        // plain old value without defined language tag
> 	ValueMulti                        // Value which is part of a multi-value posting list (like language).
> ```

100 chars

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[query/query.go, line 1451 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9OJ6Nxs16rt-I0VP3:-Ki9OJ6OW_8YKyMFuWae:bgqwf0) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L1451)):*
> ```Go
> 		}
> 	}
> 	sg.Children = out
> ```

The intention of this PR is to expand on scalar values only ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by ashwin95r** [comment]
Review status: 12 of 13 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 210 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9GnVzGaHd-8MbvwDn:-KiD0rqzbxWiPbKepg9_:b-jg7zqa) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/outputnode.go#L210)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Not sure, there might be usecases when you want to listpredicates for all nodes. For example: Say if we are storing list of items, then each node might have different set of predicates even though they might share some predicates. Does it make sense to expand _predicate_ per node ?

Nevertheless,  if listpred contains other predicates it would be expanded for first uid only.
listpred(func:anyofterms(name,"Alice2 Alice")) {
name
_predicate_
}

Similarly for the case for 
listpred(func:anyofterms(name,"Alice2 Alice")) {
name

}
Only single results would be returned(though _predicate_ is not present here)
</blockquote></details>

This was something I was trying out. It makes sense to return it per UID. But all of them would be a union of predicates for that level. Tracking it per node seems unnecessary.

---

*[query/query.go, line 280 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9LWFJYx2zDTSUYpir:-KiCxMxLAXKh_GprPmzO:b-uuhad0) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L280)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

If we already have a predicate called name, then we would get wrong results when we use normalize. Give it a better name so that it works well with normalize.
</blockquote></details>

How about `_name_`?

---

*[query/query.go, line 514 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9M6aX0FBrESK0nQ6_:-KiCxUPfoD2nWMBQ1hJ9:b4bh13f) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L514)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

I think we need to handle the case of expand(_all_), otherwise when both expand(_all_) and predicate is present in the query block, then server would crash due to our assertion in the code that same predicate can't be seen multiple times
</blockquote></details>

Right. I'm just wondering if we should ignore the duplicate result while doing pretraverse. Though it might lead to multiple fetches, I think it'll be easier to ignore the duplicates than checking upfront for possible duplicates. As we add more and more functionality, duplicates can be reached by different query combinations.

---

*[query/query.go, line 1451 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9OJ6Nxs16rt-I0VP3:-KiCwvK82g82Qdqa8uZg:b40s0tx) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L1451)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

The intention of this PR is to expand on scalar values only ?
</blockquote></details>

Nope, all the predicates.

---

*[worker/task.go, line 207 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9DrRZ31epf5brlP7O:-KiCy3NFlB_-WsRCRXYp:be0ht9m) ([raw file](https://github.com/dgraph-io/dgraph/blob/dc6ec2f96d5c5fb23ac956957584976ff6a515ac/worker/task.go#L207)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This doesn't return list of predicates per node. And might return different results for same node depending on src uid's.(Should be fine if we don't expand _predicate_ per uid)

Example:
mutation {
set {
<Alice> <name> "Alice 1" .
<Alice2> <name> "Alice2" .
<Alice2> <age> "42"^^<xs:int> .
}
schema {
name:string @index .
}
}

query {
#would return name for <Alice>
me(func:anyofterms(name,"Alice")) {
name
_predicate_
}

#would return name, age for <Alice>
me2(func:anyofterms(name,"Alice2 Alice")) {
name
_predicate_
}

}
</blockquote></details>

Yes, the idea is to have a list of predicates per level and not per UID. As our design is more favourable for this.

---

*[x/values.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki8WwugS34ch6LSuHVg:-KiCySbE9Qgj4uO0c1O-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eea8d0effb9917415162b17c456f272e618d19ff/x/values.go#L28)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by tzdybal** [comment]
Reviewed 2 of 2 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query.go, line 514 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9M6aX0FBrESK0nQ6_:-KiUA21_zujcX5gNskhA:bor43r9) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L514)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Right. I'm just wondering if we should ignore the duplicate result while doing pretraverse. Though it might lead to multiple fetches, I think it'll be easier to ignore the duplicates than checking upfront for possible duplicates. As we add more and more functionality, duplicates can be reached by different query combinations.
</blockquote></details>

Yeah makes sense. May be discuss with manish and finalise this.

---

*[query/query.go, line 1451 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9OJ6Nxs16rt-I0VP3:-KiUABzeV5WwNpERK46H:b6zqqqg) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L1451)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Nope, all the predicates.
</blockquote></details>

But in this PR We are not expanding on uid edges recursively. So i guess only the edges with scalar values would be expanded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-:-KiU9yCO41vxQQtb5Ybj:bnfp4nl)*

**Comment by tzdybal** [comment]
I forgot to mark as: :lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-:-KiWCvywkZBjkVb16EyL:b-sa9mxf)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 1451 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9OJ6Nxs16rt-I0VP3:-KiXM2FFxoSO9WMO_uHa:b-pgoxtj) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L1451)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

But in this PR We are not expanding on uid edges recursively. So i guess only the edges with scalar values would be expanded.
</blockquote></details>

Yes, only one level would be expanded. But you can provide child fields as well. `expand(_all_) { _uid_}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by manishrjain** [comment]
:lgtm: small comments.

---

Reviewed 5 of 12 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 3 of 4 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/dgraph/main_test.go, line 305 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiXdgC8jDow22f-AG-R:-KiXdgC8jDow22f-AG-S:b-oh5141) ([raw file](https://github.com/dgraph-io/dgraph/blob/03e602ffa742df4b4f4fe9b559d4c35613ed014f/cmd/dgraph/main_test.go#L305)):*
> ```Go
> 	var mp map[string]interface{}
> 	require.NoError(t, json.Unmarshal([]byte(output), &mp))
> 	require.Equal(t, 3, len(mp["listpred"].([]interface{})[0].(map[string]interface{})["_predicate_"].([]interface{})),
> ```

You could have stored the JSON output in a string and compared that instead. Sort the output from `_predicate_`.

---

*[query/query.go, line 514 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9M6aX0FBrESK0nQ6_:-KiXfpJe2BiYQd59kND3:b-sij5z3) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L514)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Yeah makes sense. May be discuss with manish and finalise this.
</blockquote></details>

Do this at the time when you generate children SubGraphs. Create an equality func for SubGraph.

---

*[query/query.go, line 1453 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiXgfssijNsoDeJLpU7:-KiXgfssijNsoDeJLpU8:b-174gql) ([raw file](https://github.com/dgraph-io/dgraph/blob/03e602ffa742df4b4f4fe9b559d4c35613ed014f/query/query.go#L1453)):*
> ```Go
> 			}
> 			temp.Attr = string(v.Val)
> 			out = append(out, temp)
> ```

Over here you can do the deduplication of children.

---

*[query/query_test.go, line 1073 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiXhAbsvnxWhCBLWvI9:-KiXhAbsvnxWhCBLWvIA:bwg242u) ([raw file](https://github.com/dgraph-io/dgraph/blob/03e602ffa742df4b4f4fe9b559d4c35613ed014f/query/query_test.go#L1073)):*
> ```Go
> 
> 			me(id: var( A)) {
> 				name
> ```

me(id: var(A)) { expand(_all_) }

---

*[worker/task.go, line 206 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiXhnfY0QiOd0XcMOGg:-KiXhnf_774Sp-qaeFpl:b-5xpqmr) ([raw file](https://github.com/dgraph-io/dgraph/blob/03e602ffa742df4b4f4fe9b559d4c35613ed014f/worker/task.go#L206)):*
> ```Go
> 				predMap[string(pred.Value.([]byte))] = struct{}{}
> 			}
> 		}
> ```

convert to a slice then sort.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-:-KiXhvK9Y_f7H_VlzM62:b1kjqmq)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 1451 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9OJ6Nxs16rt-I0VP3:-KiY9b4F4Xhy5zZCGUMR:bs6mcx1) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L1451)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Yes, only one level would be expanded. But you can provide child fields as well. `expand(_all_) { _uid_}`
</blockquote></details>

May be add a test case where we expand child fields for non-scalar edges(e.g. friend, enemy). Btw if i want to specify child node of friend or enemy, how will i do that

---

*[query/query_test.go, line 1069 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiYAPQY705kQk6ibdEK:-KiYAPQY705kQk6ibdEL:bz20azm) ([raw file](https://github.com/dgraph-io/dgraph/blob/b1cff00d9ec627dca9c7985f9d21d4cc9672e621/query/query_test.go#L1069)):*
> ```Go
> 		{
> 			A as shortest(from:0x01, to:101) {
> 				expand(_all_)
> ```

Btw if i specify expand(_all_) inside a var block, will it return only those UID's which has value for all edges. That is the normal behaviour of var block right ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-:-KiY9Q4Mq2TS-JNzGHG0:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 12 of 14 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main_test.go, line 305 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiXdgC8jDow22f-AG-R:-KiY3HWTCgT7vg45u6Lq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/03e602ffa742df4b4f4fe9b559d4c35613ed014f/cmd/dgraph/main_test.go#L305)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You could have stored the JSON output in a string and compared that instead. Sort the output from `_predicate_`.
</blockquote></details>

Done.

---

*[query/query.go, line 514 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9M6aX0FBrESK0nQ6_:-KiYPuF-UHJzsu4EX5Nx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L514)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do this at the time when you generate children SubGraphs. Create an equality func for SubGraph.
</blockquote></details>

Done.

---

*[query/query.go, line 1451 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-Ki9OJ6Nxs16rt-I0VP3:-KiYQ4BDawAdfmCL4Y0b:b-qck61m) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ec31bbb9fde16b2eff2e93ba6d051856f63d8bf/query/query.go#L1451)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

May be add a test case where we expand child fields for non-scalar edges(e.g. friend, enemy). Btw if i want to specify child node of friend or enemy, how will i do that
</blockquote></details>

```
{ me(id: a) {
expand(_all_) {
name
}
}
```

---

*[query/query.go, line 1453 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiXgfssijNsoDeJLpU7:-KiY3E91ylPi0u-HDn7N:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/03e602ffa742df4b4f4fe9b559d4c35613ed014f/query/query.go#L1453)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Over here you can do the deduplication of children.
</blockquote></details>

Done.

---

*[query/query_test.go, line 1069 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiYAPQY705kQk6ibdEK:-KiYQNM8zau3IAHNpFk9:b-gigxer) ([raw file](https://github.com/dgraph-io/dgraph/blob/b1cff00d9ec627dca9c7985f9d21d4cc9672e621/query/query_test.go#L1069)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Btw if i specify expand(_all_) inside a var block, will it return only those UID's which has value for all edges. That is the normal behaviour of var block right ?
</blockquote></details>

Yes, those post processing steps would still hold.

---

*[worker/task.go, line 206 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/856#-KiXhnfY0QiOd0XcMOGg:-KiY3G2HyL4N07Stxw9K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/03e602ffa742df4b4f4fe9b559d4c35613ed014f/worker/task.go#L206)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

convert to a slice then sort.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/856)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
