### PR TITLE
Make count a function on predicate

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/471)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 995 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaAq2rJsWnXxrRllhbf:-KaAq2rJsWnXxrRllhbg:bheohcx) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/parser.go#L995)):*
> ```Go
> 	curp := gq // Used to track current node, for nesting.
> 	for it.Next() {
> 		item := it.Item()
> ```

Make this whole thing a switch case.

---

*[gql/parser_test.go, line 896 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaArNtJSmeJbEuITpAo:-KaArNtJSmeJbEuITpAp:borx4fz) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/parser_test.go#L896)):*
> ```Go
> 			}
> 			gender,age
> 			hometown
> ```

also add count(friends) at this level.

---

*[gql/parser_test.go, line 908 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaAqkLDD78oHVPTxdH6:-KaAqkLDD78oHVPTxdH7:b-fmp8m3) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/parser_test.go#L908)):*
> ```Go
> 	query := `{
> 		me(id:1) {
> 			count(friends, relatives
> ```

count(friends), count(relatives), count(classmates)

---

*[gql/state.go, line 99 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaAqzAAxIsgeHnslw6X:-KaAqzABXy4Y9b8jf9cV:b-m1l9e7) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/state.go#L99)):*
> ```Go
> 	for {
> 		switch r := l.Next(); {
> 		case r == attherate:
> ```

Change the name to at.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/471)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 995 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaAq2rJsWnXxrRllhbf:-KaAtwikrfGhRMCEGaVs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/parser.go#L995)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this whole thing a switch case.
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 896 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaArNtJSmeJbEuITpAo:-KaAuQaGCzwrG_bEL6RI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/parser_test.go#L896)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

also add count(friends) at this level.
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 908 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaAqkLDD78oHVPTxdH6:-KaAvk_xxYMGElk4GvGd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/parser_test.go#L908)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

count(friends), count(relatives), count(classmates)
</blockquote></details>

Done.

---

*[gql/state.go, line 99 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaAqzAAxIsgeHnslw6X:-KaAyCDarxYcFGXkbkKx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/52d166234a17d8029765341773c0e8dbe53010a5/gql/state.go#L99)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Change the name to at.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/471)*

**Comment by manishrjain** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 998 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaB7Mkr7A7kAx3NiZ-i:-KaB7Mkr7A7kAx3NiZ-j:b47b6zz) ([raw file](https://github.com/dgraph-io/dgraph/blob/f332a0dcfec6452854f82ed1c83a9cf248cd6e14/gql/parser.go#L998)):*
> ```Go
> 		switch item.Typ {
> 		case lex.ItemError:
> 			{
> ```

Remove these brackets.

---

*[query/query_test.go, line 816 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaB9z-4vhPAhboinEwT:-KaB9z-50rICdJ76Ko0j:b-len632) ([raw file](https://github.com/dgraph-io/dgraph/blob/f332a0dcfec6452854f82ed1c83a9cf248cd6e14/query/query_test.go#L816)):*
> ```Go
> 	js := processToJSON(t, query)
> 	require.JSONEq(t,
> 		`{"me":[{"friend":[{"_count_":2}, {"name":"Andrea"}],"gender":"female","name":"Michonne"}]}`,
> ```

Remove the underscore around count.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/471)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 998 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaB7Mkr7A7kAx3NiZ-i:-KaBAt5oF892im8K5E51:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f332a0dcfec6452854f82ed1c83a9cf248cd6e14/gql/parser.go#L998)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove these brackets.
</blockquote></details>

Done.

---

*[query/query_test.go, line 816 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-KaB9z-4vhPAhboinEwT:-KaBAsDO9NcvhuozAM-U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f332a0dcfec6452854f82ed1c83a9cf248cd6e14/query/query_test.go#L816)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove the underscore around count.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/471)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-:-KaBDFuYGLjzTmOAXfD4:bnfp4nl)*

**Comment by jchiu0** [comment]
:lgtm LG to use count(predicate) instead of `_count_`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-:-KaBoQ_FBgU1PetzmHKE:bae3k7f)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/471#-:-KaBoaf9iXMQX3hC53M6:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
