### PR TITLE
chore: backup nfs automation scripts and instructions (SUCCESS-23)

### PR DESCRIPTION
**Pull request by darkn3rd**
This demonstrates how use Dgraph binary backups with NFS in either local development environments (**docker**, **minikube**) or production environments (**Kubernetes**) with a few solutions.

### Environments Supported

* Production Environments (**EKS**, **GKE**)
  * External NFS Service from Cloud Provider
     * Google Cloud Filestore (GCFS)
     * Amazon EFS (Elastic File Service)
  * Internal NFS deployed as Kubernetes resources
    * Rook NFS Operator
* Development Environments (**Docker Compose**, **Minikube**)
  * External NFS Service
    * linux kernel nfs server (vagrant)
    * docker-compose using nfs volume
  * Internal NFS Service
    * Rook NFS Operator
    * Dgraph Alpha pod on MiniKube

### Automation Used

This will have a mix of automation to support these solutions:

* Local Environments
  * **docker-compose** environment with external NFS through **Vagrant**
  * **minikube** environment with either Rook or external NFS through **Vagrant** (**helmfile**)
* Production Environments
  * Provision resource with GCFS or EFS (**terraform**)
  * Template configuration for **helmfile** (**terraform**)
  * **Helmfile** to deploy Dgraph with Rook or support for external NFS (**GCFS**, **EFS**)

## Not Included

* researched using NFS container, but nothing popular, other than building one yourself with `Dockerfile` was available.  The later was not a simple solution, require users to build containers and make them available in docker registry for production scenarios.
* researched using once popular `nfs-server-provisioner` or `nfs-client-provisioner`, but both of these projects have become stale and no longer publish releases.
* no support for instructions for host based NFS, such as linux kernel nfs server, user space nfs server, macOS nfsd, open source Windows (Cygwin, WinNFSd), or Windows Server *Server for NFS*, as this would be too many variant configurations, so alternative just used vagrant/virtualbox as that works consistently across all platforms.
* no automation for Rook Ceph Operator in conjunction with Rook NFS Operator, as setting up highly scalable storage with Ceph is beyond the scope of NFS vs. Dgraph Binary Backups.
* no documentation for provisioning cloud based Kubernetes solution.  This would be useful for EFS as this requires some expertise and knowledge into EKS setup to configure access (AWS is strict on security, which increases complexity)
* did not test minikube + vagrant on HyperV (winpro).  It should work, may need some tweaks, can add this later.
* did not test minikube w/ docker driver (like kind, but with Minikube)
* did not test on [KinD](https://kind.sigs.k8s.io/).
* did not investigate problems with minikube using 3 vm nodes where only one node could access NFS (thinking it is networking issue).  This is marked as experimental feature, default settings work.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6806)

### CODE REVIEW

**Comment by darkn3rd** [comment]
@aaroncarey If you can doc check the README and comments that would be great.

**Review by danielmai — APPROVED** [review]
See if we can remove the rook / rook-nfs-operator-kustomize directories, especially if they're copied from somewhere else. If the user just needs to download it, provide a link on how to download it.

And, fix any broken links. Then, :lgtm: 

> Reviewed 15 of 41 files at r1, 3 of 4 files at r3, 8 of 23 files at r4, 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-:-MLVNQYy3am8WaY7yspp:bdomcav)* status: 30 of 42 files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @danielmai, @darkn3rd, and @slotlocker2)

___
*[contrib/config/backups/nfs/README.md, line 51 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MLVJqmZDCgbZsZd5mxK:-MLVJqmZDCgbZsZd5mxL:b3ovy89) ([raw file](https://github.com/dgraph-io/dgraph/blob/0fc113a595f26e5c1559315137d8b074efef5f15/contrib/config/backups/nfs/README.md#L51)):*
> ```
>   * [Google Cloud Filestore](gcfs-cli/README.md) - provision FileStore using `gcloud`
> * Terraform
>   * [Google Cloud Filestore](gcfs-terraform/README.md) - use Filestore as NFS share on GKE.
> ```
Do these links need to be swapped? One says Terraform but doesn't link to `gcfs-terraform`.

The `gcfs-cli` link doesn't work. Rename the directory from `gcsfs-cli` to `gcfs-cli`.
___
*[contrib/config/backups/nfs/charts/dgraph_nfs.yaml, line 16 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MLVLPXlDWzxjHyRQoFz:-MLVLPXmD46LIZ2XbqsN:b-pnn3gj) ([raw file](https://github.com/dgraph-io/dgraph/blob/0fc113a595f26e5c1559315137d8b074efef5f15/contrib/config/backups/nfs/charts/dgraph_nfs.yaml#L16)):*
> ```
>       lru_mb    = 2048
> ```
lru_mb is removed in Dgraph master.

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6806)* status: 22 of 41 files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @danielmai, @darkn3rd, and @slotlocker2)

___
*[contrib/config/backups/nfs/README.md, line 51 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MLVJqmZDCgbZsZd5mxK:-MLsQG8p5TPI-sNYg9xd:b-7ql1td) ([raw file](https://github.com/dgraph-io/dgraph/blob/0fc113a595f26e5c1559315137d8b074efef5f15/contrib/config/backups/nfs/README.md#L51)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>   * [Google Cloud Filestore](gcfs-cli/README.md) - provision FileStore using `gcloud`
> * Terraform
>   * [Google Cloud Filestore](gcfs-terraform/README.md) - use Filestore as NFS share on GKE.
> ```
Do these links need to be swapped? One says Terraform but doesn't link to `gcfs-terraform`.

The `gcfs-cli` link doesn't work. Rename the directory from `gcsfs-cli` to `gcfs-cli`.
</blockquote></details>

fixed

**Review by aaroncarey — APPROVED** [review]
> Reviewed 1 of 41 files at r1, 4 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6806)* status: 26 of 41 files reviewed, 23 unresolved discussions (waiting on @aaroncarey, @danielmai, @darkn3rd, and @slotlocker2)

___
*[contrib/config/backups/nfs/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHARtH66vPJEk4R-Wp:-MMHARtH66vPJEk4R-Wq:b8wf1ur) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L3)):*
> ```
> When using a file system for binary backups, NFS is recommended. NFS provides backups that work seamlessly across *multiple machines and/or containers*.
> ```
This reads better as two sentences
___
*[contrib/config/backups/nfs/README.md, line 30 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHAjQl8qYh_7wInbdU:-MMHAjQmEnF7EBRWynqi:bog1bkq) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L30)):*
> ```
>  of 
> ```
___
*[contrib/config/backups/nfs/README.md, line 32 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHAsu-63LBCqGOysW2:-MMHAsu09eI1eYKVZBzE:b-7m15ky) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L32)):*
> ```
> services where
> ```
___
*[contrib/config/backups/nfs/README.md, line 34 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHAxHHDEf7yojFKbPO:-MMHAxHI332NBAFF0wAB:b-rvb284) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L34)):*
> ```
> his guide provides tips on how to back up Dgraph using NFS. 
> ```
___
*[contrib/config/backups/nfs/README.md, line 49 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHBS0q6j9we0z0OoZ8:-MMHBS0q6j9we0z0OoZ9:bjuyxvr) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L49)):*
> ```
> You can provision external NFS to use with your Dgraph cluster running on Kubernetes using these scripts.
> ```
___
*[contrib/config/backups/nfs/README.md, line 49 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHBbkV81Dqe2kkQEZB:-MMHBbkV81Dqe2kkQEZC:b2le01m) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L49)):*
> ```
> and 
> ```
___
*[contrib/config/backups/nfs/README.md, line 70 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHBuK2CSZxjrEzqPhN:-MMHBuK39za6lkWYZvDy:bgrjkvl) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L70)):*
> ```
> The steps to configure NFS for your local operating system or distro can vary greatly<sup>†</sup>, so a [Vagrant](https://www.vagrantup.com/) example is provided.
> ```
___
*[contrib/config/backups/nfs/README.md, line 72 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHC4Ik8PyAKXXvFf2F:-MMHC4Ik8PyAKXXvFf2G:b-jmai3i) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L72)):*
> ```
> or you can use 
> ```
___
*[contrib/config/backups/nfs/README.md, line 187 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCRo35kV4cArZUhEg:-MMHCRo35kV4cArZUhEh:b-lnr0gn) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L187)):*
> ```
> `libvirt` 
> ```
___
*[contrib/config/backups/nfs/README.md, line 187 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCUtm3-KEEOiwztRj:-MMHCUtm3-KEEOiwztRk:bemkogf) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L187)):*
> ```
> same network.
> ```
___
*[contrib/config/backups/nfs/README.md, line 204 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHC_BT-bC8eJ4gdMeN:-MMHC_BT-bC8eJ4gdMeO:bnvdcs5) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L204)):*
> ```
> Next, verify that the NFS share 
> ```
___
*[contrib/config/backups/nfs/README.md, line 263 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCiqp-Q0WUm1ARU7F:-MMHCiqp-Q0WUm1ARU7G:b-649ugb) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L263)):*
> ```
> backups are scheduled 
> ```
___
*[contrib/config/backups/nfs/README.md, line 263 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCmO41nPIwF5a4rY7:-MMHCmO41nPIwF5a4rY8:b-8i9fk7) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L263)):*
> ```
> a `curl` command.
> ```
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCzAv0TkxPUzmlBS_:-MMHCzAv0TkxPUzmlBSa:bp27hsn) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L3)):*
> ```
> These [Terraform](https://www.terraform.io/) scripts and modules will create the required resources needed to support an NFS server instance using [Amazon Elastic File Services](https://aws.amazon.com/efs/).
> ```
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 13 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDKtNAkIfBCTpEWgU:-MMHDKtNAkIfBCTpEWgV:b5yk05b) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L13)):*
> ```
>To use this automation, you must install the following:
> ```
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 20 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDQDj9JjfdEwKV_ML:-MMHDQDj9JjfdEwKV_MM:buw8afu) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L20)):*
> ```
> You can use the following input variables to configure this automation:
> ```
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 32 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDd436iBcuzCwvaVb:-MMHDd436iBcuzCwvaVc:bmzoomv) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L32)):*
> ```
> Configuring the following values allows this automation to discover the resources used to configure EFS. 
> ```
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 44 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDyR0Av4xdJ-f6-f1:-MMHDyR0Av4xdJ-f6-f2:bfcoh96) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L44)):*
> ```
> You will need to have the appropriate tags per subnets and security groups configured to support the discovery feature. This feature will allow these [Terraform](https://www.terraform.io/) scripts to find the resources required to allow EFS configuration alongside an Amazon EKS cluster and SG configuration to allow EKS worker nodes to access EFS.  If you used `eksctl` to provision your cluster, these tags and keys will be set up automatically.
> ```
___
*[contrib/config/backups/nfs/gcfs-terraform/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHF5pa4UdMvRmKpvsX:-MMHF5pa4UdMvRmKpvsY:bvton65) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/gcfs-terraform/README.md#L3)):*
> ```
> e resources required to create
> ```
___
*[contrib/config/backups/nfs/gcfs-cli/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHEjRQ6pYymeaic9Wp:-MMHEjRQ6pYymeaic9Wq:b8dvlj0) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/gcfs-cli/README.md#L3)):*
> ```
> This shell script creates the resources needed to create an NFS server instance using Google Cloud Filestore.
> ```
___
*[contrib/config/backups/nfs/gcfs-cli/README.md, line 35 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHF-awCB0bHlu1vbMP:-MMHF-awCB0bHlu1vbMQ:bc8il9i) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/gcfs-cli/README.md#L35)):*
> ```
>  an `env.sh`
> ```

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6806)* status: 22 of 41 files reviewed, 23 unresolved discussions (waiting on @aaroncarey, @danielmai, and @slotlocker2)

___
*[contrib/config/backups/nfs/README.md, line 51 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MLVJqmZDCgbZsZd5mxK:-MMME-zd2ph15aZQ3A3h:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0fc113a595f26e5c1559315137d8b074efef5f15/contrib/config/backups/nfs/README.md#L51)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHARtH66vPJEk4R-Wp:-MMMHqHtCmrFO4xilXqp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L3)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> When using a file system for binary backups, NFS is recommended. NFS provides backups that work seamlessly across *multiple machines and/or containers*.
> ```
This reads better as two sentences
</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 30 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHAjQl8qYh_7wInbdU:-MMMHti22yI06eatw4Ie:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L30)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
>  of 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 32 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHAsu-63LBCqGOysW2:-MMMI2Dz9fmqgdHCkmg9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L32)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> services where
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 34 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHAxHHDEf7yojFKbPO:-MMMIAAy25OQ2TwGjMix:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L34)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> his guide provides tips on how to back up Dgraph using NFS. 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 49 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHBS0q6j9we0z0OoZ8:-MMMINV38GbnCjVYSQXQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L49)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> You can provision external NFS to use with your Dgraph cluster running on Kubernetes using these scripts.
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 49 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHBbkV81Dqe2kkQEZB:-MMMIROEDN7uav7M-NcP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L49)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> and 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 70 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHBuK2CSZxjrEzqPhN:-MMMIT_N5eizua_SnAOQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L70)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> The steps to configure NFS for your local operating system or distro can vary greatly<sup>†</sup>, so a [Vagrant](https://www.vagrantup.com/) example is provided.
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 72 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHC4Ik8PyAKXXvFf2F:-MMMK_lT8zipya7j0a9m:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L72)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> or you can use 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 187 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCRo35kV4cArZUhEg:-MMMImNn7h-k5HtfkaAt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L187)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> `libvirt` 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 187 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCUtm3-KEEOiwztRj:-MMMImzG5_jVzjMiap67:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L187)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> same network.
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 204 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHC_BT-bC8eJ4gdMeN:-MMMKZ4D3sY1Wx7fw6mO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L204)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> Next, verify that the NFS share 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 263 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCiqp-Q0WUm1ARU7F:-MMMJ7tS5LHBKd2c-FHV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L263)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> backups are scheduled 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/README.md, line 263 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCmO41nPIwF5a4rY7:-MMMJ8PA3re6g1_bG9rQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/README.md#L263)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> a `curl` command.
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHCzAv0TkxPUzmlBS_:-MMMG4cm2pcD5NvcBLNz:b-l3jstz) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L3)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> These [Terraform](https://www.terraform.io/) scripts and modules will create the required resources needed to support an NFS server instance using [Amazon Elastic File Services](https://aws.amazon.com/efs/).
> ```

</blockquote></details>

The scripts actually create it through AWS API, so not sure support is correct.
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 13 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDKtNAkIfBCTpEWgU:-MMMJmpM4nv60pcoqNfM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L13)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
>To use this automation, you must install the following:
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 20 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDQDj9JjfdEwKV_ML:-MMMJpsQBKAFKd0hFRne:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L20)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> You can use the following input variables to configure this automation:
> ```
</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 32 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDd436iBcuzCwvaVb:-MMMJza696F5tUWUw28L:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L32)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> Configuring the following values allows this automation to discover the resources used to configure EFS. 
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/efs-terraform/README.md, line 44 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHDyR0Av4xdJ-f6-f1:-MMMK0aN31qM0JLnx4wq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/efs-terraform/README.md#L44)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> You will need to have the appropriate tags per subnets and security groups configured to support the discovery feature. This feature will allow these [Terraform](https://www.terraform.io/) scripts to find the resources required to allow EFS configuration alongside an Amazon EKS cluster and SG configuration to allow EKS worker nodes to access EFS.  If you used `eksctl` to provision your cluster, these tags and keys will be set up automatically.
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/gcfs-terraform/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHF5pa4UdMvRmKpvsX:-MMMKCAW7vIE39-7EDVh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/gcfs-terraform/README.md#L3)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> e resources required to create
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/charts/dgraph_nfs.yaml, line 16 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MLVLPXlDWzxjHyRQoFz:-MMMJEIBCrCC8xEro-hF:bld6lh2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0fc113a595f26e5c1559315137d8b074efef5f15/contrib/config/backups/nfs/charts/dgraph_nfs.yaml#L16)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>       lru_mb    = 2048
> ```
lru_mb is removed in Dgraph master.
</blockquote></details>

This guide is for current and past.  Removing this option causes earlier versions to fail completely.
___
*[contrib/config/backups/nfs/gcfs-cli/README.md, line 3 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHEjRQ6pYymeaic9Wp:-MMMK2JM6E9VWActi82I:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/gcfs-cli/README.md#L3)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> This shell script creates the resources needed to create an NFS server instance using Google Cloud Filestore.
> ```

</blockquote></details>

Done.
___
*[contrib/config/backups/nfs/gcfs-cli/README.md, line 35 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/6806#-MMHF-awCB0bHlu1vbMP:-MMMK3yL6J4L3GgQRAgy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e684d5a57f6d91a2ce5aefdcf03be2d05a256ef6/contrib/config/backups/nfs/gcfs-cli/README.md#L35)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
>  an `env.sh`
> ```

</blockquote></details>

Done.

**Pull request merged**
