### PR TITLE
Add JSON mutations to raw HTTP

### PR DESCRIPTION
**Pull request by gpahal**
This adds Json mutations to Dgraph's HTTP server.

Syntax:
```json
{
    "set": [{ "name": "Alice" }],
    "delete": { "uid": "0x1", "name": null }
}
```

Possible limitations/problems:
- Parses the JSON twice: first for veryfing json and separating set and delete and second time to actually perform the mutation on api.Mutation
- Requires header indicating the type is JSON so that error handling is better and json mutations are not slowed down because of first checking for nquad mutations

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2396)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[dgraph/cmd/server/http.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2396#-LCjS8mzEn2dlwWeoG2O:-LCjS8mzEn2dlwWeoG2P:boytom7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0642637ebad792acc8090f1d99e01ad2bd20efa/dgraph/cmd/server/http.go#L173)):*
> ```Go
> 		// Parse JSON.
> 		ms := make(map[string]interface{})
> 		err := json.Unmarshal(m, &ms)
> ```

JSON unmarshal needs to be worked upon. So, let's consolidate that in one place. Can you use the same method that grpc uses to unmarshal JSON; so it's all in one place?

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2396)*

**Comment by gpahal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[dgraph/cmd/server/http.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2396#-LCjS8mzEn2dlwWeoG2O:-LClmtAM24kCX1Gt8yHR:bg5d4om) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0642637ebad792acc8090f1d99e01ad2bd20efa/dgraph/cmd/server/http.go#L173)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

JSON unmarshal needs to be worked upon. So, let's consolidate that in one place. Can you use the same method that grpc uses to unmarshal JSON; so it's all in one place?
</blockquote></details>

This JSON marshal only validates the JSON and checks its `"set"` and `"delete"` keys. It doesn't do anything with the values or numbers. And the rest of the function requires `mu *api.Mutation` which has `SetJson` and `DeleteJson` as unparsed JSON strings, so anyways we need the unparsed JSON. To avoid this, we would need to change the interface of edgraph.Mutate and nquadsToJson.

I didn't change much because I wanted to introduce this change without affecting any other code.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2396)*

**Comment by gpahal** [comment]
@manishrjain ^

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[dgraph/cmd/server/http.go, line 172 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2396#-LDOSdOqB3aPDtYJTYnA:-LDOSdOqB3aPDtYJTYnB:b-y841si) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0642637ebad792acc8090f1d99e01ad2bd20efa/dgraph/cmd/server/http.go#L172)):*
> ```Go
> 	if mType := r.Header.Get("X-Dgraph-MutationType"); mType == "json" {
> 		// Parse JSON.
> 		ms := make(map[string]interface{})
> ```

map[string][]byte? So, you don't need to marshal below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2396)*

**Comment by gpahal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[dgraph/cmd/server/http.go, line 172 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2396#-LDOSdOqB3aPDtYJTYnA:-LDfSBvQ1idgaftKoM04:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d0642637ebad792acc8090f1d99e01ad2bd20efa/dgraph/cmd/server/http.go#L172)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

map[string][]byte? So, you don't need to marshal below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2396)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2396#-:-LDgnE9aDrrF2ErMr7Du:bnfp4nl)*

**Pull request merged**
