### PR TITLE
Fix #1564. Give up determinism in output to avoid crash.

### LINKED ISSUE #1564: Cannot find group when grouping by geo fields
# Problem
DGraph gives an error "wrong groups" and terminates in a single node instance when trying to group by geo fields.

# Reproduce
## When it is working

First I create new clean dgraph instance
```sh
sudo rm -rf ~/dgraph
mkdir -p ~/dgraph
docker rm dgraph
docker run -it -p 8080:8080 -p 9080:9080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph:v0.8.2 dgraph --bindall=true --memory_mb 2048
```

Data set:
```
mutation {
  schema {
    name: string @index(hash) .
    pickupFrom: geo .
    deliverTo: geo .
  }

  set {
    _:company1 <name> "Company B" .
    _:company1 <pickupFrom> "{'type':'Point','coordinates':[0.0,0.0]}" .
    _:company1 <deliverTo> "{'type':'Point','coordinates':[10.0,11.0]}" .

    _:company2 <name> "Company B" .
    _:company2 <pickupFrom> "{'type':'Point','coordinates':[0.0,0.0]}" .
    _:company2 <deliverTo> "{'type':'Point','coordinates':[10.0,11.0]}" .

    _:company3 <name> "Company B" .
    _:company3 <pickupFrom> "{'type':'Point','coordinates':[0.0,0.0]}" .
    _:company3 <deliverTo> "{'type':'Point','coordinates':[13.0,14.0]}" .
  }
}
```

This query works just fine:
```
{
  q(func: eq(name, "Company B")) @groupby(pickupFrom, deliverTo) {
    count(_uid_)
  }
}
```

## When it is not working

I removed previous database and tried with another but similar data set.
``` sh
sudo rm -rf ~/dgraph
mkdir -p ~/dgraph
docker rm dgraph
docker run -it -p 8080:8080 -p 9080:9080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph:v0.8.2 dgraph --bindall=true --memory_mb 2048
```
Data set:
```
mutation {
  schema {
    name: string @index(hash) .
    pickupFrom: geo .
    deliverTo: geo .
  }

  set {
    _:company1 <name> "Company B" .
    _:company1 <pickupFrom> "{'type':'Point','coordinates':[0.0,0.0]}" .
    _:company1 <deliverTo> "{'type':'Point','coordinates':[10.0,11.0]}" .

    _:company3 <name> "Company B" .
    _:company3 <pickupFrom> "{'type':'Point','coordinates':[0.0,0.0]}" .
    _:company3 <deliverTo> "{'type':'Point','coordinates':[13.0,14.0]}" .
  }
}
```

UI returns an error: _Failed to fetch: Could not connect to the server_
```
{
  q(func: eq(name, "Company B")) @groupby(pickupFrom, deliverTo) {
    count(_uid_)
  }
}
```

### Console log
```
Dgraph version   : v0.8.2
Commit SHA-1     : 4269f91f
Commit timestamp : 2017-09-27 14:49:31 +1000
Branch           : HEAD

2017/10/02 07:54:13 draft.go:252: Node with GroupID: 0, ID: 1
2017/10/02 07:54:13 worker.go:112: Worker listening at address: [::]:12345
2017/10/02 07:54:13 gRPC server started.  Listening on port 9080
2017/10/02 07:54:13 HTTP server started.  Listening on port 8080
2017/10/02 07:54:13 draft.go:252: Node with GroupID: 1, ID: 1
2017/10/02 07:54:13 draft.go:1098: Group 0 found 0 entries
2017/10/02 07:54:13 draft.go:1120: New Node for group: 0
2017/10/02 07:54:13 draft.go:1098: Group 1 found 0 entries
2017/10/02 07:54:13 draft.go:1120: New Node for group: 1
2017/10/02 07:54:13 raft.go:567: INFO: 1 became follower at term 0
2017/10/02 07:54:13 raft.go:315: INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017/10/02 07:54:13 raft.go:567: INFO: 1 became follower at term 1
2017/10/02 07:54:13 raft.go:567: INFO: 1 became follower at term 0
2017/10/02 07:54:13 raft.go:315: INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017/10/02 07:54:13 raft.go:567: INFO: 1 became follower at term 1
2017/10/02 07:54:13 raft.go:749: INFO: 1 is starting a new election at term 1
2017/10/02 07:54:13 raft.go:580: INFO: 1 became candidate at term 2
2017/10/02 07:54:13 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
2017/10/02 07:54:13 raft.go:621: INFO: 1 became leader at term 2
2017/10/02 07:54:13 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2
2017/10/02 07:54:13 raft.go:749: INFO: 1 is starting a new election at term 1
2017/10/02 07:54:13 raft.go:580: INFO: 1 became candidate at term 2
2017/10/02 07:54:13 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
2017/10/02 07:54:13 raft.go:621: INFO: 1 became leader at term 2
2017/10/02 07:54:13 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2
2017/10/02 07:54:13 draft.go:629: group: 0 Addr: "localhost:12345" leader: true dead: false
2017/10/02 07:54:13 groups.go:550: ----------------------------
2017/10/02 07:54:13 draft.go:629: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/10/02 07:54:13 groups.go:550: ----------------------------
2017/10/02 07:54:13 draft.go:629: group: 1 Addr: "localhost:12345" leader: false dead: false
2017/10/02 07:54:13 groups.go:550: ----------------------------
2017/10/02 07:54:13 groups.go:551: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:3 PoolOrNil:<nil>}
2017/10/02 07:54:13 groups.go:552: ----------------------------
2017/10/02 07:54:13 groups.go:551: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:6 PoolOrNil:<nil>}
2017/10/02 07:54:13 groups.go:552: ----------------------------
2017/10/02 07:54:13 groups.go:567: Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:3 PoolOrNil:<nil>}]
2017/10/02 07:54:13 draft.go:629: group: 0 Addr: "localhost:12345" leader: true dead: false
2017/10/02 07:54:13 groups.go:551: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:4 PoolOrNil:<nil>}
2017/10/02 07:54:13 groups.go:552: ----------------------------
2017/10/02 07:54:13 groups.go:567: Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:3 PoolOrNil:<nil>}]
2017/10/02 07:54:13 groups.go:567: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:6 PoolOrNil:<nil>}]
2017/10/02 07:54:13 groups.go:550: ----------------------------
2017/10/02 07:54:13 groups.go:567: Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:3 PoolOrNil:<nil>}]
2017/10/02 07:54:13 groups.go:567: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:4 PoolOrNil:<nil>}]
2017/10/02 07:54:13 groups.go:551: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5 PoolOrNil:<nil>}
2017/10/02 07:54:13 groups.go:552: ----------------------------
2017/10/02 07:54:13 groups.go:567: Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5 PoolOrNil:<nil>}]
2017/10/02 07:54:13 groups.go:567: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:false RaftIdx:4 PoolOrNil:<nil>}]
2017/10/02 07:54:23 draft.go:629: group: 1 Addr: "localhost:12345" leader: true dead: false
2017/10/02 07:54:23 groups.go:550: ----------------------------
2017/10/02 07:54:23 groups.go:551: ====== APPLYING MEMBERSHIP UPDATE: {NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7 PoolOrNil:<nil>}
2017/10/02 07:54:23 groups.go:552: ----------------------------
2017/10/02 07:54:23 groups.go:567: Group: 0. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:5 PoolOrNil:<nil>}]
2017/10/02 07:54:23 groups.go:567: Group: 1. List: [{NodeId:1 Addr:localhost:12345 Leader:true RaftIdx:7 PoolOrNil:<nil>}]
2017/10/02 07:54:23 schema.go:109: Setting schema for attr _lease_: int, tokenizer: [], directive: NONE, count: false
2017/10/02 07:54:23 schema.go:109: Setting schema for attr name: string, tokenizer: [hash], directive: INDEX, count: false
2017/10/02 07:54:23 mutation.go:135: Done schema update predicate:"name" value_type:9 directive:INDEX tokenizer:"hash" explicit:true 
2017/10/02 07:54:23 schema.go:109: Setting schema for attr pickupFrom: geo, tokenizer: [], directive: NONE, count: false
2017/10/02 07:54:23 mutation.go:135: Done schema update predicate:"pickupFrom" value_type:6 explicit:true 
2017/10/02 07:54:23 schema.go:109: Setting schema for attr deliverTo: geo, tokenizer: [], directive: NONE, count: false
2017/10/02 07:54:23 mutation.go:135: Done schema update predicate:"deliverTo" value_type:6 explicit:true 
2017/10/02 07:54:37 wrong groups
```

When schema looks like that, then this problem does not occur:
```
  schema {
    name: string @index(hash) .
    pickupFrom: string .
    deliverTo: string .
  }
```

# Environment
Ubuntu: 14.04 LTS
Memory: 15.6 GB
Processor: Intel® Xeon(R) CPU E5-2620 0 @ 2.00GHz × 12
Graphics: Quadro K2000/PCIe/SSE2
OS type: 64-bit
Disc: 233 GB

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1567)

### CODE REVIEW

**Comment by peterstace** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/groupby.go, line 311 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1567#-KvUdhyKVFQjNC_Zp7-u:-KvUdhyKVFQjNC_Zp7-v:b-y45ayg) ([raw file](https://github.com/dgraph-io/dgraph/blob/ad52646aaf9715124a8d5f23b893f15cc32c320d/query/groupby.go#L311)):*
> ```Go
> 	for i := range a.aggregates {
> 		if l, err := types.Less(a.aggregates[i].key, b.aggregates[i].key); err == nil {
> 			if err != nil {
> ```

We already checked for `err == nil` in the line above, so the if statement here would always use the else part. Should just have `l, err := ...` on the line above same as when checking the `keys`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1567)*

**Comment by peterstace** [comment]
What was the part that was erroring that would cause the crash?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1567#-:-KvUeQ3Lu4-YkPJJAOAA:b-r27ezo)*

**Comment by peterstace** [comment]
Are we giving up determinism unnecessarily in some cases? E.g. if we can't sort by keys, but we *could* sort by aggregates, the solution here would not sort deterministically. If we were to just remove the assert before the final return, we would get some level of sorting in that case. Or does a case where we can sort by one but not the other not really come up?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1567#-:-KvUezkUUmKmElSOWpYF:b-koqdpj)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1567#-:-KvUhpgcoa3dwjfVHB13:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master as of fd56b6ac1f011ac739c63b1e138135b022d55091

**Pull request closed without merging**
