### PR TITLE
feat(GraphQL): Add support for Polygon and Multi-Polygon in GraphQL

### PR DESCRIPTION
**Pull request by arijitAD**
Fixes GRAPHQL-662
Fixes GRAPHQL-695

This PR adds support for Polygon and MultiPolygon geo types in GraphQL. See [RFC](https://discuss.dgraph.io/t/implementing-geo-features-in-graphql/7022) for more details.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6618)

 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-efcc6e8453-102892.surge.sh)

### CODE REVIEW

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
should we also add a test to validate that `PointList` can't be specified in input schema as a type for some field?

> Reviewed 21 of 65 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-:-MJQu1s5DZgMByrteTN5:bfn6eve)* status: 21 of 65 files reviewed, 14 unresolved discussions (waiting on @arijitAD, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/common.go, line 384 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQcm4KAd7loeJOzwbA:-MJQcm4LEulFPKA2VwC6:b-jmh15n) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/e2e/common/common.go#L384)):*
> ```Go
> 	t.Run("Check cascade with mutation without ID field", checkCascadeWithMutationWithoutIDField)
> 	t.Run("Geo - Point type", mutationPointType)
> 	t.Run("Geo - Polygon type", mutationPolygonType)
> ```

e2e for MultiPolygon
___
*[graphql/e2e/common/mutation.go, line 3758 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQdIr-5bdAjKtQwBm5:-MJQdIr-5bdAjKtQwBm6:b-qefsfk) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/e2e/common/mutation.go#L3758)):*
> ```Go
> 			  name
> 			  location {
> 				latitude
> ```

we should also put `__typename` check for Point type now that it works
___
*[graphql/resolve/add_mutation_test.yaml, line 36 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQf4uNAIx6vFOM59fo:-MJQf4uNAIx6vFOM59fp:b-x8s949) ([raw file](https://github.com/dgraph-io/dgraph/blob/1003e71bd438b585398e4fb35fd1013b686d3c52/graphql/resolve/add_mutation_test.yaml#L36)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
>   name: "Add mutation with geo without longitude"
>   gqlmutation: |
>     mutation addHotel($hotel: AddHotelInput!) {
>       addHotel(input: [$hotel]) {
>         hotel {
>           name
>           location {
>             latitude
>             longitude
>           }
>         }
>       }
>     }
>   gqlvariables: |
>     { "hotel":
>       { "name": "Taj Hotel",
>         "location": { "latitude": 11.11 }
>       }
>     }
>   explanation: "Add mutation for Point type mutation should have both latitude and longitude"
>   validationerror:
>     { "message": "input: variable.hotel.location.longitude must be defined" }
> ```
</details>

seems we removed this test, should we keep it?
If it is from gqlparser, then we can skip this test, because this check is enforced through our schema.
___
*[graphql/resolve/mutation_rewriter.go, line 1303 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQijSs8geWtOQFBJ--:-MJQijSs8geWtOQFBJ-0:b-5gn6vp) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/mutation_rewriter.go#L1303)):*
> ```
> makePolygon
> ```
rewritePolygon
___
*[graphql/resolve/query_rewriter.go, line 1127 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQkqYs0ovupKCVJa7F:-MJQkqYs0ovupKCVJa7G:bufq0g0) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1127)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 					distance := geoParams["distance"]
> 					coordinate, _ := geoParams["coordinate"].(map[string]interface{})
> 					if coordinate == nil {
> 						return nil
> 					}
> ```
</details>

I was thinking that we can skip this nil check for `coordinate` like we have done for distance, because according to our schema it is non-null. So, if someone gives null or any other value that doesn't conform to our schema, then it should be caught at parser level itself. So, here it should always be a map.
___
*[graphql/resolve/query_rewriter.go, line 1140 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQmwHl0aiztJQv9i6i:-MJQmwHl0aiztJQv9i6j:buxfg1i) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1140)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 					polygon, _ := geoParams["polygon"].(map[string]interface{})
> 					if polygon == nil {
> 						return nil
> 					}
> ```
</details>

can skip this check because of schema validations by parser.
___
*[graphql/resolve/query_rewriter.go, line 1162 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQnrH85z21r3HRf08m:-MJQnrH85z21r3HRf08n:b-4kodji) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1162)):*
> ```Go
> 					} else if point, ok := geoParams["point"].(map[string]interface{}); ok {
> 						res = writePoint(point)
> 					}
> ```

the other case for this where both point and polygon are null in this would be taken care of after my PR for unions is merged with `@oneOf` directive. Which will ensure that always one of the fields should be there.
___
*[graphql/resolve/query_rewriter.go, line 1169 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQoMf66E-o8C0SoBdj:-MJQoMf66E-o8C0SoBdk:b-uiwdag) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1169)):*
> ```
> contains
> ```
intersects
___
*[graphql/resolve/query_rewriter.go, line 1170 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQoXsO2c1j0PKgt2CZ:-MJQoXsO2c1j0PKgt2C_:b-ccgyzn) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1170)):*
> ```
> coordinates:
> ```
polygons:
___
*[graphql/resolve/query_test.yaml, line 296 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQpq3BDuy-1G2HJT1s:-MJQpq3BDuy-1G2HJT1t:b-jr11lf) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_test.yaml#L296)):*
> ```YAML
>       }
>     }
> ```

rewriting tests for MultiPolygon are missing
___
*[graphql/resolve/resolver.go, line 1379 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQqeKq9kk07qUEV6R7:-MJQqeKq9kk07qUEV6R8:bbjsgp4) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/resolver.go#L1379)):*
> ```
> // It returns a bracketed json object like { "longitude" : 12.32 , "latitude" : 123.32 }.
> func completeGeoObject(field schema.Field, val map[string]interface{}, path []interface{}) ([]byte, x.GqlErrorList) {
> ```
comment can be updated to reflect the new behaviour
___
*[graphql/resolve/resolver.go, line 1389 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQr6hNBaijKSrui8cK:-MJQr6hNBaijKSrui8cL:b-i0hp5) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/resolver.go#L1389)):*
> ```Go
> 	typ, _ := val["type"].(string)
> 	var buf bytes.Buffer
> 	var err x.GqlErrorList
> ```

we are not using this, can be removed
___
*[graphql/resolve/update_mutation_test.yaml, line 135 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQrhI45jSeEpD58cj_:-MJQrhI5DaFDyUKWWCW9:bvitu4y) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/update_mutation_test.yaml#L135)):*
> ```
> set
> ```
delete
___
*[graphql/resolve/update_mutation_test.yaml, line 140 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQrmD1CCqLJ9VZsPPP:-MJQrmD1CCqLJ9VZsPPQ:b-gw4d7v) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/update_mutation_test.yaml#L140)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     - deletejson: |
>         { "uid" : "uid(x)",
>           "Hotel.area": {
>             "type": "Polygon",
>             "coordinates": [[[22.22,11.11],[16.16,15.15],[21.21,20.2]],[[22.28,11.18],[16.18,15.18],[21.28,20.28]]]
>           }
>         }
>       cond: "@if(gt(len(x), 0))"
> ```
</details>

should we add an e2e test to check if this rewriting works for `remove` case?
___
*[graphql/schema/dgraph_schemagen_test.yml, line 631 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQs1lG1xxUzRkSlxUE:-MJQs1lG1xxUzRkSlxUF:bbhxe9s) ([raw file](https://github.com/dgraph-io/dgraph/blob/1003e71bd438b585398e4fb35fd1013b686d3c52/graphql/schema/dgraph_schemagen_test.yml#L631)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
>   -
>     name: "custom field shouldn't be part of dgraph schema"
>     input: |
>       type User {
>         id: ID!
>         name: String!
>         bio: String! @lambda
>         friends: [User] @custom(http: {
>           url: "http://mock:8888/users",
>           method: "GET"
>         })
>       }
>     output: |
>       type User {
>         User.name
>       }
>       User.name: string .
> ```
</details>

seems this test got removed in merge

**Review by abhimanyusinghgaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6618)* status: 2 of 66 files reviewed, all discussions resolved (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/common.go, line 384 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQcm4KAd7loeJOzwbA:-MK-WgoGEW9Klp7HSQfY:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/e2e/common/common.go#L384)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

e2e for MultiPolygon
</blockquote></details>

Done
___
*[graphql/e2e/common/mutation.go, line 3758 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQdIr-5bdAjKtQwBm5:-MK-Tq_d47e4vbtdco0z:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/e2e/common/mutation.go#L3758)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should also put `__typename` check for Point type now that it works
</blockquote></details>

Done
___
*[graphql/resolve/add_mutation_test.yaml, line 36 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQf4uNAIx6vFOM59fo:-MJzcFnR3avhFwrPiM6T:b7sb1mu) ([raw file](https://github.com/dgraph-io/dgraph/blob/1003e71bd438b585398e4fb35fd1013b686d3c52/graphql/resolve/add_mutation_test.yaml#L36)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
>   name: "Add mutation with geo without longitude"
>   gqlmutation: |
>     mutation addHotel($hotel: AddHotelInput!) {
>       addHotel(input: [$hotel]) {
>         hotel {
>           name
>           location {
>             latitude
>             longitude
>           }
>         }
>       }
>     }
>   gqlvariables: |
>     { "hotel":
>       { "name": "Taj Hotel",
>         "location": { "latitude": 11.11 }
>       }
>     }
>   explanation: "Add mutation for Point type mutation should have both latitude and longitude"
>   validationerror:
>     { "message": "input: variable.hotel.location.longitude must be defined" }
> ```
seems we removed this test, should we keep it?
If it is from gqlparser, then we can skip this test, because this check is enforced through our schema.
</blockquote></details>

It is from gqlparser, can be skipped.
___
*[graphql/resolve/mutation_rewriter.go, line 1303 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQijSs8geWtOQFBJ--:-MJzcWjP7dNZ8Y6J_0WJ:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/mutation_rewriter.go#L1303)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> makePolygon
> ```
rewritePolygon
</blockquote></details>

Done
___
*[graphql/resolve/query_rewriter.go, line 1127 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQkqYs0ovupKCVJa7F:-MJzde_AEwzU2OFLLrAm:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1127)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 					distance := geoParams["distance"]
> 					coordinate, _ := geoParams["coordinate"].(map[string]interface{})
> 					if coordinate == nil {
> 						return nil
> 					}
> ```
I was thinking that we can skip this nil check for `coordinate` like we have done for distance, because according to our schema it is non-null. So, if someone gives null or any other value that doesn't conform to our schema, then it should be caught at parser level itself. So, here it should always be a map.
</blockquote></details>

Done
___
*[graphql/resolve/query_rewriter.go, line 1140 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQmwHl0aiztJQv9i6i:-MJzegEP1bZEsTlrDBrE:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1140)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 					polygon, _ := geoParams["polygon"].(map[string]interface{})
> 					if polygon == nil {
> 						return nil
> 					}
> ```
can skip this check because of schema validations by parser.
</blockquote></details>

Done
___
*[graphql/resolve/query_rewriter.go, line 1169 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQoMf66E-o8C0SoBdj:-MJzf7VD-1wlL4yHAgAW:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1169)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> contains
> ```
intersects
</blockquote></details>

Done
___
*[graphql/resolve/query_rewriter.go, line 1170 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQoXsO2c1j0PKgt2CZ:-MJzf9EYE7w6UdyNeSOL:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1170)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> coordinates:
> ```
polygons:
</blockquote></details>

Done
___
*[graphql/resolve/query_test.yaml, line 296 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQpq3BDuy-1G2HJT1s:-MK-TPr--9xz8urJsRmg:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_test.yaml#L296)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

rewriting tests for MultiPolygon are missing
</blockquote></details>

Done
___
*[graphql/resolve/resolver.go, line 1379 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQqeKq9kk07qUEV6R7:-MJzwatm3hjHnY7mChhE:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/resolver.go#L1379)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> // It returns a bracketed json object like { "longitude" : 12.32 , "latitude" : 123.32 }.
> func completeGeoObject(field schema.Field, val map[string]interface{}, path []interface{}) ([]byte, x.GqlErrorList) {
> ```
comment can be updated to reflect the new behaviour
</blockquote></details>

Done
___
*[graphql/resolve/resolver.go, line 1389 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQr6hNBaijKSrui8cK:-MJzfpnF3srmHHip1cLe:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/resolver.go#L1389)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we are not using this, can be removed
</blockquote></details>

Done
___
*[graphql/resolve/update_mutation_test.yaml, line 135 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQrhI45jSeEpD58cj_:-MK-OHey2bDfVp7lM1RJ:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/update_mutation_test.yaml#L135)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> set
> ```
delete
</blockquote></details>

Done
___
*[graphql/schema/dgraph_schemagen_test.yml, line 631 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQs1lG1xxUzRkSlxUE:-MK-Qv8A1_sXIqOwdY6B:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/1003e71bd438b585398e4fb35fd1013b686d3c52/graphql/schema/dgraph_schemagen_test.yml#L631)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
>   -
>     name: "custom field shouldn't be part of dgraph schema"
>     input: |
>       type User {
>         id: ID!
>         name: String!
>         bio: String! @lambda
>         friends: [User] @custom(http: {
>           url: "http://mock:8888/users",
>           method: "GET"
>         })
>       }
>     output: |
>       type User {
>         User.name
>       }
>       User.name: string .
> ```
seems this test got removed in merge
</blockquote></details>

Done

**Review by pawanrawal — APPROVED** [review]
> Reviewed 2 of 65 files at r1, 64 of 64 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6618)* status: all files reviewed, 6 unresolved discussions (waiting on @arijitAD and @MichaelJCompton)

___
*[graphql/resolve/mutation_rewriter.go, line 1377 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4F9_F2C8RLTPHZMam:-MK4F9_F2C8RLTPHZMan:bmjll2t) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/mutation_rewriter.go#L1377)):*
> ```Go
> func rewritePolygon(val map[string]interface{}) []interface{} {
> 	var resPoly []interface{}
> 	for _, pointList := range val[schema.Coordinates].([]interface{}) {
> ```

I suppose this typecasting to `[]interface{}` is safe to do and `val[Coordinates]` would never be nil?

Also maybe we can initialize these slices with the correct length in the first place to optimize for memory. 
___
*[graphql/resolve/mutation_rewriter.go, line 1379 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4FNcfB-Fkxp-DoTfN:-MK4FNcfB-Fkxp-DoTfO:b-x23vez) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/mutation_rewriter.go#L1379)):*
> ```Go
> 	for _, pointList := range val[schema.Coordinates].([]interface{}) {
> 		var resPointList []interface{}
> 		for _, point := range pointList.(map[string]interface{})[schema.Points].([]interface{}) {
> ```

again, is this all safe because of the strict GraphQL schema?
___
*[graphql/resolve/query_rewriter.go, line 1162 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQnrH85z21r3HRf08m:-MK4_nbI282SZj_0OSMK:bnw9uk2) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1162)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

the other case for this where both point and polygon are null in this would be taken care of after my PR for unions is merged with `@oneOf` directive. Which will ensure that always one of the fields should be there.
</blockquote></details>

Add comments about the current behavior and what should we do in the future to tackle this properly and also create a JIRA issue about this.
___
*[graphql/resolve/query_test.yaml, line 170 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4LMc11a5QUJrvqqA9:-MK4LMc11a5QUJrvqqAA:bi4wv99) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/query_test.yaml#L170)):*
> ```YAML
>     				polygon: {
>     					coordinates: [{
>     						points: [{
> ```

tabs looks strange here
___
*[graphql/resolve/query_test.yaml, line 413 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4LZP77ZNfDCnfUtO3:-MK4LZP77ZNfDCnfUtO4:b4i9h53) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/query_test.yaml#L413)):*
> ```YAML
>     			intersects: {
>     				polygon: {
>     					coordinates: [{
> ```

tabs should be fixed
___
*[graphql/resolve/query_test.yaml, line 528 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4LcVn6NvSg604byMT:-MK4LcVn6NvSg604byMU:b-txojbk) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/query_test.yaml#L528)):*
> ```YAML
>               coordinates {
>                 points {
>                   latitude
> ```

nice bunch of test cases here
___
*[graphql/schema/testdata/schemagen/input/geo-type.graphql, line 5 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4Zq9GDR7-tLaEJ8CD:-MK4Zq9GDR7-tLaEJ8CE:b-gcbdyk) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/schema/testdata/schemagen/input/geo-type.graphql#L5)):*
> ```GraphQL
>     name: String!
>     location: Point @search
>     area: Polygon @search
> ```

Can we add fields for geo types where `@search` is not there.

**Review by abhimanyusinghgaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6618)* status: 61 of 66 files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @arijitAD, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/mutation_rewriter.go, line 1377 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4F9_F2C8RLTPHZMam:-MK4yZgI-7UmeXB--94W:bkupyr9) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/mutation_rewriter.go#L1377)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I suppose this typecasting to `[]interface{}` is safe to do and `val[Coordinates]` would never be nil?

Also maybe we can initialize these slices with the correct length in the first place to optimize for memory. 
</blockquote></details>

Yeah! Done.
___
*[graphql/resolve/mutation_rewriter.go, line 1379 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4FNcfB-Fkxp-DoTfN:-MK4yc2y-aLB0Qe6kKu6:bb77u1k) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/mutation_rewriter.go#L1379)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

again, is this all safe because of the strict GraphQL schema?
</blockquote></details>

Yeah
___
*[graphql/resolve/query_rewriter.go, line 1162 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MJQnrH85z21r3HRf08m:-MK4yPo9BZO13jLC1nyj:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/42914a76b53a9e11aa29e0b788ed07e2fa38d89c/graphql/resolve/query_rewriter.go#L1162)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add comments about the current behavior and what should we do in the future to tackle this properly and also create a JIRA issue about this.
</blockquote></details>

Done
___
*[graphql/resolve/query_test.yaml, line 170 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4LMc11a5QUJrvqqA9:-MK4yRpj3VzrY8HdmKWR:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/query_test.yaml#L170)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

tabs looks strange here
</blockquote></details>

Done
___
*[graphql/resolve/query_test.yaml, line 413 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4LZP77ZNfDCnfUtO3:-MK4yTk24wFa74Y1chpO:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/resolve/query_test.yaml#L413)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

tabs should be fixed
</blockquote></details>

Done
___
*[graphql/schema/testdata/schemagen/input/geo-type.graphql, line 5 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6618#-MK4Zq9GDR7-tLaEJ8CD:-MK4yXg36ZTAkTN-YgHg:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/bdea0dcca97a3f8aad28d6d8e77e8ef88a47220c/graphql/schema/testdata/schemagen/input/geo-type.graphql#L5)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we add fields for geo types where `@search` is not there.
</blockquote></details>

Done

**Pull request merged**
