### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by jchiu0**
Add docker image that pulls from get.dgraph.io.

Update current docker image for development. (This might not really be used now.)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/283)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/devel/Dockerfile, line 8 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5KyIp2Z_Xky64UPKb:-KU5KyIq24wsPVy90dmI:b-kpc8js) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/devel/Dockerfile#L8)):*
> ```Dockerfile
> 
> FROM golang:1.7
> MAINTAINER Manish Jain <manishrjain@gmail.com>
> ```

Dgraph Labs <contact@dgraph.io>?

---

*[docker/devel/Dockerfile, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5LnGHNV-IxGdP9VEz:-KU5LnGIIr4haWuqiZRE:b-v0pxu5) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/devel/Dockerfile#L50)):*
> ```Dockerfile
> # Some tests are failing. We are looking into it.
> # Let's just run some more critical tests now.
> RUN go test github.com/dgraph-io/dgraph/posting/... && \
> ```

An easier and cleaner thing would be to just add and comment it for now. Also maybe we can add a TODO that uncomment after tests pass.
go test github.com/dgraph-io/dgraph/...

What do you think?

---

*[docker/release/Dockerfile, line 25 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5Kkxxi586_haDh_fv:-KU5KkxylylB-T7s2nMT:bh6s4kk) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/release/Dockerfile#L25)):*
> ```Dockerfile
> # Some sample sequence of commands:
> #   cd /data
> #   wget https://github.com/dgraph-io/benchmarks/raw/master/data/rdf-films.gz
> ```

A comment here that you could do these steps to bulkload data.

---

*[docker/release/Dockerfile, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5MwXjPFhCpsEwWY2A:-KU5MwXjPFhCpsEwWY2B:bd0svht) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/release/Dockerfile#L29)):*
> ```Dockerfile
> #   cd /dgraph
> #   time dgraphassigner -rdfgzips /data/rdf-films.gz -instanceIdx 0 -numInstances 1 -uids u
> #   time dgraphloader   -rdfgzips /data/rdf-films.gz -instanceIdx 0 -numInstances 1 -uids u -postings p
> ```

Ok, I am thinking shouldn't we start Dgraph server here. So that user can just use the docker image directly in a container to use Dgraph?
Also, the Dgraph port should be configurable using environment variables https://docs.docker.com/engine/reference/run/#/env-environment-variables?

The idea is that the user should be able to use the image to run a container and get started with Dgraph. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/283)*

**Comment by jchiu0** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/devel/Dockerfile, line 8 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5KyIp2Z_Xky64UPKb:-KU5OOGewoxUdkAE54C_:b-nbgy1n) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/devel/Dockerfile#L8)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Dgraph Labs <contact@dgraph.io>?
</details>
Replaced with:
MAINTAINER Dgraph Labs <contact@dgraph.io>

---

*[docker/devel/Dockerfile, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5LnGHNV-IxGdP9VEz:-KU5OfFnbZC0qfUiLW5O:bbr3dvq) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/devel/Dockerfile#L50)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> An easier and cleaner thing would be to just add and comment it for now. Also maybe we can add a TODO that uncomment after tests pass.
> go test github.com/dgraph-io/dgraph/...
> 
> What do you think?
</details>
Sounds good. Done.

---

*[docker/release/Dockerfile, line 25 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5Kkxxi586_haDh_fv:-KU5Oq53xK6RRhSm9fbZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/release/Dockerfile#L25)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> A comment here that you could do these steps to bulkload data.
</details>
Done.

---

*[docker/release/Dockerfile, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5MwXjPFhCpsEwWY2A:-KU5Ptrk9Oyg29QhtLKp:b-86cub1) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/release/Dockerfile#L29)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Ok, I am thinking shouldn't we start Dgraph server here. So that user can just use the docker image directly in a container to use Dgraph?
> Also, the Dgraph port should be configurable using environment variables https://docs.docker.com/engine/reference/run/#/env-environment-variables?
> 
> The idea is that the user should be able to use the image to run a container and get started with Dgraph. What do you think?
</details>
I am new to docker. Here is my take, but please correct me if I am wrong.

We can add a CMD here to start dgraph but I think there are a bunch of other parameters that need to be set. The user will probably create his own docker image based off this one, and download / build his own data and then add a CMD with flags set to read his own data. It is more convenient for him to set the port in his own docker image, which could be ENV or hardcoded etc.

We can instead create another image based off this one that will have the loader's output and start dgraph with ENV containing port and number of CPUs etc etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/283)*

**Comment by pawanrawal** [comment]
One small comment apart from the :lgtm: 
We should also push the latest image with the version tag to Docker hub (https://hub.docker.com/r/dgraph/). Maybe add a task for yourself to do that?

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/release/Dockerfile, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5MwXjPFhCpsEwWY2A:-KU5T5PLuN0YRxNvqhji:bqcphbf) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/release/Dockerfile#L29)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> I am new to docker. Here is my take, but please correct me if I am wrong.
> 
> We can add a CMD here to start dgraph but I think there are a bunch of other parameters that need to be set. The user will probably create his own docker image based off this one, and download / build his own data and then add a CMD with flags set to read his own data. It is more convenient for him to set the port in his own docker image, which could be ENV or hardcoded etc.
> 
> We can instead create another image based off this one that will have the loader's output and start dgraph with ENV containing port and number of CPUs etc etc.
</details>
Ok, I think we can avoid all the configs as you said. I just read again about https://docs.docker.com/engine/reference/builder/#/entrypoint.

Do you think we can support that? I am just thinking that the user should be able to start Dgraph with the default options without rebuilding the image. Of course, if he wants to tweak stuff he can modify Dockerfile/create another image but maybe starting Dgraph with default options should be possible without that as it works for nginx image etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-:-KU5TW8yX-vW3I5t05jS:b-phpe2w)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/release/Dockerfile, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/283#-KU5MwXjPFhCpsEwWY2A:-KUD1K7ZpqFmf1IZ4ENT:bha2dvd) ([raw file](https://github.com/dgraph-io/dgraph/blob/916ad636bd801f91e4f25d30bd8237e43217ad71/docker/release/Dockerfile#L29)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Ok, I think we can avoid all the configs as you said. I just read again about https://docs.docker.com/engine/reference/builder/#/entrypoint.
> 
> Do you think we can support that? I am just thinking that the user should be able to start Dgraph with the default options without rebuilding the image. Of course, if he wants to tweak stuff he can modify Dockerfile/create another image but maybe starting Dgraph with default options should be possible without that as it works for nginx image etc.
> 
</details>
I added

EXPOSE 8080
ENTRYPOINT ["dgraph"]

And I tried out the command `docker run -P dgraph/release`

And I tried curling to the port that is mapped (obtained by docker ps and docker port) and it seems to work. I think this is what you have in mind?

I'm going to submit first.. Thanks for the suggestion!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/283)*

**Pull request closed without merging**
