### PR TITLE
Support List of XIDs/UIDs

### PR DESCRIPTION
**Pull request by ashwin95r**
Now we can do:

```
{
      me(id:[1, 23, 0x24, m.0asp]) {
        name
      }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/465)

### CODE REVIEW

**Comment by jchiu0** [comment]
:lgtm: Just one remark about the ordering of UIDs and XIDs.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gql/parser.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6EejoPz3RJdYUQTrl:-Ka6EejpeUGUqgMkR6vE:bu7idzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/be060622d40d91c441b03ab4c61c85f68a29243d/gql/parser.go#L35)):*
> ```Go
> type GraphQuery struct {
> 	UID   []uint64
> 	XID   []string
> ```

If user does a mix of UID and XID, should we somehow remember the order?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-:-Ka6EzWk45Xk2GZYMbvG:bn2m3rc)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gql/parser.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6EejoPz3RJdYUQTrl:-Ka6I7o55Dr_jxbkbc6c:b-i4ocaf) ([raw file](https://github.com/dgraph-io/dgraph/blob/be060622d40d91c441b03ab4c61c85f68a29243d/gql/parser.go#L35)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

If user does a mix of UID and XID, should we somehow remember the order?
</blockquote></details>

Have made some change to address this. Please have a look again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/465)*

**Comment by manishrjain** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 931 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6Kg9AyT5aeSR9m4Hx:-Ka6Kg9B5rxv0x7JaLkJ:bz3ub7u) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/gql/parser.go#L931)):*
> ```Go
> 		for _, p := range args {
> 			if p.Key == "id" {
> 				// Check and parse if its a list.
> ```

parseId(..)

---

*[gql/parser.go, line 943 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6L_a-knvi3bdIIBL1:-Ka6L_a-knvi3bdIIBL2:b6z3ij0) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/gql/parser.go#L943)):*
> ```Go
> 							}
> 
> 							uid, err := strconv.ParseUint(buf.String(), 0, 64)
> ```

this should be a nested function.

func parseId() {
togq := func(string) {
  gq....
}

for .. {
  if no left bracket {
    parse()
    return
  }
  ...
  parse(..)
}
}

---

*[query/query_test.go, line 2030 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6MSJpKqwlNohEPBuY:-Ka6MSJpKqwlNohEPBuZ:bh4x1nt) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/query/query_test.go#L2030)):*
> ```Go
> 	query := `
>     {
> 			me(id:[1, 23, 24]) {
> ```

some formatting issue.

---

*[query/query_test.go, line 2030 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6MWbcf_f4TVLbT3vQ:-Ka6MWbcf_f4TVLbT3vR:b6yvw1w) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/query/query_test.go#L2030)):*
> ```Go
> 	query := `
>     {
> 			me(id:[1, 23, 24]) {
> ```

Have a case where it's a mix of uid and xid in id: [ .. ]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/465)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 931 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6Kg9AyT5aeSR9m4Hx:-Ka6TRhzrN79jQXPfIwY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/gql/parser.go#L931)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

parseId(..)
</blockquote></details>

Done.

---

*[gql/parser.go, line 943 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6L_a-knvi3bdIIBL1:-Ka6TSM-yWjDJmoTxKME:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/gql/parser.go#L943)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

this should be a nested function.

func parseId() {
togq := func(string) {
  gq....
}

for .. {
  if no left bracket {
    parse()
    return
  }
  ...
  parse(..)
}
}
</blockquote></details>

Done.

---

*[query/query_test.go, line 2030 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6MSJpKqwlNohEPBuY:-Ka6N6DVbK9_1dGzx16-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/query/query_test.go#L2030)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

some formatting issue.
</blockquote></details>

Done.

---

*[query/query_test.go, line 2030 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6MWbcf_f4TVLbT3vQ:-Ka6V2cVrS7lXbfbiXVU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6508febb29bcd53ddacb87cea20d86ea3d3e4f8b/query/query_test.go#L2030)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Have a case where it's a mix of uid and xid in id: [ .. ]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/465)*

**Comment by manishrjain** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 2045 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6ZS4R5HiQ8WJk3mEt:-Ka6ZS4R5HiQ8WJk3mEu:bfmaz9e) ([raw file](https://github.com/dgraph-io/dgraph/blob/52c643ea9136d8dce46d77ab9ac4e85f0efa842c/query/query_test.go#L2045)):*
> ```Go
> 	defer os.RemoveAll(dir2)
> 	query := `{
> 	me(id:[1, 23, 24, a.bc]) {
> ```

, 0x01

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/465)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 2045 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6ZS4R5HiQ8WJk3mEt:-Ka6_cBIItZOv7yWqjpC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/52c643ea9136d8dce46d77ab9ac4e85f0efa842c/query/query_test.go#L2045)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

, 0x01
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/465)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 886 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-Ka6clT_hCfDLydUHJeM:-Ka6clTas4kPYu63y3ss:b6mp8oj) ([raw file](https://github.com/dgraph-io/dgraph/blob/47547d6db2325a5f0e1038c0bbc72aff0be8b623/gql/parser.go#L886)):*
> ```Go
> }
> 
> func ParseID(gq *GraphQuery, val string) error {
> ```

make it private.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/465#-:-Ka6dGtSddASgxNbrvR_:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
