### PR TITLE
Add logic for checking max retries

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1239)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/mutations.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnleDXn4ncrGQbOoa9:-KpnleDXn4ncrGQbOoaA:brhoyc9) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L65)):*
> ```Go
> 	Pending:       100,
> 	PrintCounters: false,
> 	MaxRetries:    10,
> ```

Shouldn't default value be infinity ?

---

*[client/mutations.go, line 446 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnmDVsRF1MCVBcJeTn:-Kpnm26bHNqxS3q1OsWx:b-a1iaqw) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L446)):*
> ```Go
> 	for {
> 		select {
> 		case d.nquads <- nq:
> ```

Why don't we simply block here ?

It seems like user wouldn't know about the error until they flush or do a batchset or batch delete ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239)*

**Comment by manishrjain** [comment]
:lgtm: Address comments before submitting.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[client/mutations.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-Kpnjdj4GMbnSrUpsgml:-Kpnjdj4GMbnSrUpsgmm:b-jpa6bm) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L58)):*
> ```Go
> 	Pending       int
> 	PrintCounters bool
> 	MaxRetries    int
> ```

uint32

---

*[client/mutations.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnjewH9pPfpKxlVfVk:-KpnjewH9pPfpKxlVfVl:b-yt8bk4) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L65)):*
> ```Go
> 	Pending:       100,
> 	PrintCounters: false,
> 	MaxRetries:    10,
> ```

math.MaxUint32

---

*[client/mutations.go, line 240 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnjNZRA-nWzbZarWhK:-KpnjNZRA-nWzbZarWhL:bfx29vo) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L240)):*
> ```Go
> 		marks:  make(map[string]waterMark),
> 		reqs:   make(chan *Req, opts.Pending*2),
> 		che:    make(chan error, opts.Pending+2),
> ```

add a comment. Can just be 1.

---

*[cmd/dgraphloader/main.go, line 242 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnnfeFBFbTdm5V1uaP:-KpnnfeFBFbTdm5V1uaQ:bulcwff) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/cmd/dgraphloader/main.go#L242)):*
> ```Go
> 
> func main() {
> 	log.SetFlags(log.LstdFlags | log.Lshortfile)
> ```

Move to the right location.

---

*[cmd/dgraphloader/main.go, line 275 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnnkGySIE34SolUCu5:-KpnnkGySIE34SolUCu6:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/cmd/dgraphloader/main.go#L275)):*
> ```Go
> 		Pending:       *concurrent,
> 		PrintCounters: true,
> 		MaxRetries:    100,
> ```

Remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-:-KpnnpEh3TvCJQoWs-bX:b533za0)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-:-KprNAYBsUl4aomOORMh:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/mutations.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-Kpnjdj4GMbnSrUpsgml:-Kpr_9S3as5G8Akz_Lex:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L58)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

uint32
</blockquote></details>

Done.

---

*[client/mutations.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnjewH9pPfpKxlVfVk:-Kpr_A6sWO2ClkkSEB5b:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

math.MaxUint32
</blockquote></details>

Done.

---

*[client/mutations.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnleDXn4ncrGQbOoa9:-Kpr_A_HjYVBZ1GV-YAC:b-5zpsvg) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L65)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Shouldn't default value be infinity ?
</blockquote></details>

Its math.MaxUint32

---

*[client/mutations.go, line 240 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnjNZRA-nWzbZarWhK:-Kpr_b3Zh3gJFI9TdDWs:b-f8sf1p) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L240)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

add a comment. Can just be 1.
</blockquote></details>

Added a comment.

---

*[client/mutations.go, line 446 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnmDVsRF1MCVBcJeTn:-Kpr_cZRfQLwFUEiTY0e:b-s5ux07) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/client/mutations.go#L446)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Why don't we simply block here ?

It seems like user wouldn't know about the error until they flush or do a batchset or batch delete ?
</blockquote></details>

Yes, that's the flow that user would either do BatchSet or BatchFlush. So we should send error to him in both cases.

---

*[cmd/dgraphloader/main.go, line 242 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnnfeFBFbTdm5V1uaP:-Kprq3279_s_JDiDfdy4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/cmd/dgraphloader/main.go#L242)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move to the right location.
</blockquote></details>

Done.

---

*[cmd/dgraphloader/main.go, line 275 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239#-KpnnkGySIE34SolUCu5:-Kprq3TD8OU72C4cUD-_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/457e396d68b2725139ea01ce8ac4430af961a4f0/cmd/dgraphloader/main.go#L275)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1239)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
