### PR TITLE
Simplify backup logic and make it robust

### PR DESCRIPTION
**Pull request by manishrjain**
- Simplify backup code.
- Just use a single RPC call to handle backup, where each server, if unable to run the backup itself, would transmit the backup RPC to some other server in the cluster. This happens recursively until we find the right server to run the backup.
- Add error handling so we can try to find the right node to run the backup.
- Reuse buffer, instead of creating a new one.
- Various bug fixes from previous backup code, and edge cases from membership logic.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/312)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 10 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 397 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVxlR80pcvKhzNBeL_i:-KVxlR81D5LXUkhu43W8:bvx4u0r) ([raw file](https://github.com/dgraph-io/dgraph/blob/33c042d9de46497d282341d80a28dc5fe7c1fa64/cmd/dgraph/main.go#L397)):*
> ```Go
> 	// TODO(Ashwin): Move to /admin endpoint.
> 	if *backup && q == "BACKUP" {
> 		worker.BackupOverNetwork(ctx)
> ```

Should we increase the timeout for backups to more than a minute?

---

*[worker/backup.go, line 279 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVxm4BkwzqiS9dTpuvi:-KVxm4BkwzqiS9dTpuvj:baqr23d) ([raw file](https://github.com/dgraph-io/dgraph/blob/33c042d9de46497d282341d80a28dc5fe7c1fa64/worker/backup.go#L279)):*
> ```Go
> func BackupOverNetwork(ctx context.Context) {
> 	// Let's first collect all groups.
> 	gids := groups().KnownGroups()
> ```

Should this be done from group zero? since it might have the most upto date group information. Otherwise, we may missout backing up some groups and still return success.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/312)*

**Comment by ashwin95r** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/312)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 397 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVxlR80pcvKhzNBeL_i:-KVxpRWmydw2bSLkKsc_:b66d9oa) ([raw file](https://github.com/dgraph-io/dgraph/blob/33c042d9de46497d282341d80a28dc5fe7c1fa64/cmd/dgraph/main.go#L397)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Should we increase the timeout for backups to more than a minute?
</details>
You'll make the change to switch the handling of backup via a different method right? So, you could change it then. I'll add a TODO.

---

*[worker/backup.go, line 279 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVxm4BkwzqiS9dTpuvi:-KVxmpxR-Eryu6Xb7t6m:bc1gx66) ([raw file](https://github.com/dgraph-io/dgraph/blob/33c042d9de46497d282341d80a28dc5fe7c1fa64/worker/backup.go#L279)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Should this be done from group zero? since it might have the most upto date group information. Otherwise, we may missout backing up some groups and still return success.
</details>
I think every server would know all the present groups -- even if it might miss exactly who's the current leader. I safeguard the logic for the latter. Also, another condition that I introduced here, to block creating RAFT nodes until we have at least a full sync for membership info, that would aid in the former. I extended that to also not run a backup if we haven't had at least one sync for membership info.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/312)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[cmd/dgraph/main.go, line 397 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVxlR80pcvKhzNBeL_i:-KVxqkARh_Ur_T0sViNR:b-bty3uv) ([raw file](https://github.com/dgraph-io/dgraph/blob/33c042d9de46497d282341d80a28dc5fe7c1fa64/cmd/dgraph/main.go#L397)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You'll make the change to switch the handling of backup via a different method right? So, you could change it then. I'll add a TODO.
</details>
Sure. Thanks.

---

*[worker/backup.go, line 279 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVxm4BkwzqiS9dTpuvi:-KVxqnJR3KZDmHuJE90I:b-7lbkgu) ([raw file](https://github.com/dgraph-io/dgraph/blob/33c042d9de46497d282341d80a28dc5fe7c1fa64/worker/backup.go#L279)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I think every server would know all the present groups -- even if it might miss exactly who's the current leader. I safeguard the logic for the latter. Also, another condition that I introduced here, to block creating RAFT nodes until we have at least a full sync for membership info, that would aid in the former. I extended that to also not run a backup if we haven't had at least one sync for membership info.
</details>
Okay, sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-:-KVxr0WOBOk2hjgNqGGm:bnfp4nl)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[worker/groups.go, line 200 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVyuUwW2KzxzWggDPUn:-KVyuUwXtXAvTlVmmZ1-:biuw6dz) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6e7ab0dbb165399c9d87a419b1453a8b0134881/worker/groups.go#L200)):*
> ```Go
> 		gids = append(gids, gid)
> 	}
> 	return
> ```

Redundant return?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-:-KVyujYpRYgnrNe6h1zW:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[worker/groups.go, line 200 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/312#-KVyuUwW2KzxzWggDPUn:-KVyv7eIhUvL-oloo3y7:bmwe8h9) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6e7ab0dbb165399c9d87a419b1453a8b0134881/worker/groups.go#L200)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Redundant return?
</details>
For functions where there's a return value, using the return keyword is mandatory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/312)*

**Pull request closed without merging**
