### PR TITLE
Support for MultiPolygon

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1358)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 41 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[types/geofilter.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-KsMueE2aVP3mb14q5aQ:-KsMueE31_-EsFowRDsD:b-fwplkj) ([raw file](https://github.com/dgraph-io/dgraph/blob/8fd9c5623776c5cdd608b0238ec8d4df919b9912/types/geofilter.go#L48)):*
> ```Go
> type GeoQueryData struct {
> 	pt    *s2.Point  // If not nil, the input data was a point
> 	loops []*s2.Loop // If not nil, the input data was a polygon
> ```

Contains, Intersects and Within queries can now take MultiPolygons, so we change loops to be a slice.

---

*[types/geofilter.go, line 225 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-KsMvmiE4zBmvp9uc9Lb:-KsMvmiE4zBmvp9uc9Lc:b-hvce42) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6acf8f0b9c82fa753c277ae503c9b57e1ffc0f/types/geofilter.go#L225)):*
> ```Go
> // a temporary fix.
> // TODO(Ashwin): Improve this to make it more accurate.
> func WithinPolygon(g1 *s2.Loop, g2 *s2.Loop) bool {
> ```

We don't need this as I added a function which checks whether one loop Contains another.

---

*[types/s2.go, line 32 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-KsMv4ZJJIo6Og8IPM28:-KsMv4ZJJIo6Og8IPM29:b-q5z759) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6acf8f0b9c82fa753c277ae503c9b57e1ffc0f/types/s2.go#L32)):*
> ```Go
> 
> // Make s2.Loop implement s2.Region
> type loopRegion struct {
> ```

Go s2 library added functions to `loop` for ContainsCell and IntersectsCell, so we don't need these.

---

*[types/s2.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-KsMvF1KcE1Ku348keMc:-KsMvF1KcE1Ku348keMd:bk5mmhj) ([raw file](https://github.com/dgraph-io/dgraph/blob/8fd9c5623776c5cdd608b0238ec8d4df919b9912/types/s2.go#L79)):*
> ```Go
> 
> // Contains checks whether loop A contains loop B.
> func Contains(a *s2.Loop, b *s2.Loop) bool {
> ```

I picked this up from the C++ source code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 37 of 41 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[types/geofilter.go, line 245 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-KsaRXjBXh9vjbR9rHTn:-KsaRXjBXh9vjbR9rHTo:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/68bcbe7f71df9cea90c00ce6491a5fc4fd5e2410/types/geofilter.go#L245)):*
> ```Go
> // returns true if the geometry represented by g is within the given loop or cap
> func (q GeoQueryData) isWithin(g geom.T) bool {
> 	x.AssertTruef(q.pt != nil || len(q.loops) > 0 || q.cap != nil, "At least a point, loop or cap should be defined.")
> ```

100 chars.

---

*[types/geofilter.go, line 305 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-KsaSA55iztoWj564w7N:-KsaSA55iztoWj564w7O:b-d3x6c8) ([raw file](https://github.com/dgraph-io/dgraph/blob/68bcbe7f71df9cea90c00ce6491a5fc4fd5e2410/types/geofilter.go#L305)):*
> ```Go
> 			}
> 			return true
> 		}
> ```

Can add an assert here that it shouldn't reach here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-:-KsaSSfPtm1gU_d0jfWu:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 37 of 41 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1358#-:-Ksa_2dcSEvXGjxsDpyn:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
