### PR TITLE
Filtering based on facets.

### PR DESCRIPTION
**Pull request by ashishnegi**
Adds FilterTree to facets.proto
Adds leq, eq, lt, gt and geq compare support for facets filtering.
Adds allof, anyof in facets filtering. Adds tests.
Return error in types.Less

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/607)

### CODE REVIEW

**Comment by manishrjain** [comment]
Refactor task.go.

---

Reviewed 11 of 16 files at r1.
Review status: 11 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query_facets_test.go, line 899 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdQyCBmx0U0bBPoooyS:-KdQyCBmx0U0bBPoooyT:bv5lp4f) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/query/query_facets_test.go#L899)):*
> ```Go
> 		me(id:1) {
> 			friend {
> 				name @facets(eq(origin, french))
> ```

This should be an error, because `french`'s type isn't clear. It should have quotes if it wants to be treated as a string.

---

*[types/conversion.go, line 660 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdQzDThXistoPRvc_hL:-KdQzDTiwKtBbFUdU9XI:bv84jnt) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/types/conversion.go#L660)):*
> ```Go
> 		return BoolID
> 	case facets.DateTimeID:
> 		if facets.OnlyDate(string(f.Value)) {
> ```

We should store date as binary, instead of string. That's more efficient.

---

*[types/facets/facet_types.go, line 103 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdQzlobVh3b8wQpVTg4:-KdQzlobVh3b8wQpVTg5:b-jsgftw) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/types/facets/facet_types.go#L103)):*
> ```Go
> 
> // FacetFor returns Facet for given key and val.
> func FacetFor(key string, val string) (*Facet, error) {
> ```

Store Facets in binary, except string type.

---

*[worker/aggregator.go, line 70 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdR-XZdEM48Xwx7Wpxg:-KdR-XZdEM48Xwx7Wpxh:b-6ze4l7) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/aggregator.go#L70)):*
> ```Go
> 		case "sum":
> 			if typ == types.Int32ID {
> 				va.Value = va.Value.(int32) + vb.Value.(int32)
> ```

Check here if we're able to convert to int and float or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-:-KdR7_k9P-4LSlKE6B5R:b-xlqakq)*

**Comment by gacharya255** [comment]
Review status: 10 of 16 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[types/facets/facet_types.go, line 123 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTLJxja1BUpYo01ISJ:-KdTLJxkPcyEuHvfXKCt:b-wujo7w) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/types/facets/facet_types.go#L123)):*
> ```Go
> }
> 
> func OnlyDate(val string) bool {
> ```

Comment on exported function.

---

*[worker/task.go, line 219 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTAo1bPBrpNm8XKy1U:-KdTAo1bPBrpNm8XKy1V:b6s99t4) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L219)):*
> ```Go
> 
> 	case StandardFn:
> 		tokens, err = getTokens(q.SrcFunc[1:])
> ```

Maybe add a comment / example here on q.SrcFunc?

---

*[worker/task.go, line 457 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTGY3JoaChSJvnZOzv:-KdTGY3JoaChSJvnZOzw:b5ugzi5) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L457)):*
> ```Go
> 
> // we return error only when query has some problems..
> // like Or has 3 arguments, argument facet val overflows integer.
> ```

Comment about the bool return being the filter mask?

---

*[worker/task.go, line 556 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTKzvwgF7lIPtOph8A:-KdTKzvxuYF27CCmvN2L:b-9bsi0k) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L556)):*
> ```Go
> 	}
> 	noError := func(b bool, e error) bool {
> 		return b && e == nil
> ```

Why not return the error?

---

*[worker/task.go, line 569 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTL8zPt7KXTILpz5HQ:-KdTKNG6Cur3Rod17L1w:b-r7cudp) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L569)):*
> ```Go
> 	case "eq":
> 		if arg1.Tid == types.BoolID {
> 			return (arg2.Tid == types.BoolID) &&
> ```

Why such a special treatment here? Can this be moved into types?

---

*[worker/task.go, line 582 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTJtPI79zDvtxa3DvU:-KdTJtPI79zDvtxa3DvV:bn0cu6n) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L582)):*
> ```Go
> }
> 
> func filterOnStandardFn(fname string, fcTokens []string, argTokens []string) (bool, error) {
> ```

Comment that fcTokens, argTokens have to be sorted.

---

*[worker/task.go, line 591 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTK65d5u6uH8CzZF8k:-KdTK65d5u6uH8CzZF8l:b-nts3xz) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L591)):*
> ```Go
> 		aidx := 0
> 		for fidx := 0; aidx < len(argTokens) && fidx < len(fcTokens); {
> 			if fcTokens[fidx] < argTokens[aidx] {
> ```

Can just compare once instead of potentially twice.

c := strings.Compare(...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/607)*

**Comment by ashishnegi** [comment]
Review status: 8 of 18 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[query/query_facets_test.go, line 899 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdQyCBmx0U0bBPoooyS:-KdVhtKXzjVelDlyopnc:b-ybp3ek) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/query/query_facets_test.go#L899)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should be an error, because `french`'s type isn't clear. It should have quotes if it wants to be treated as a string.
</blockquote></details>

Will do this as separate task.

---

*[types/conversion.go, line 660 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdQzDThXistoPRvc_hL:-KdViGJ9NK8SkYntns0z:bafi59k) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/types/conversion.go#L660)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We should store date as binary, instead of string. That's more efficient.
</blockquote></details>

Have added task for this. Will send separate pr.

---

*[types/facets/facet_types.go, line 103 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdQzlobVh3b8wQpVTg4:-KdViMWMeMRkoqhcKI7t:b-dwub4m) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/types/facets/facet_types.go#L103)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Store Facets in binary, except string type.
</blockquote></details>

will do as another task.

---

*[types/facets/facet_types.go, line 123 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTLJxja1BUpYo01ISJ:-KdViPQiBxSuDDEem027:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/types/facets/facet_types.go#L123)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Comment on exported function.
</blockquote></details>

Done.

---

*[worker/aggregator.go, line 70 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdR-XZdEM48Xwx7Wpxg:-KdVg9n7lTpV1W1KaRdd:biynae6) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/aggregator.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check here if we're able to convert to int and float or not.
</blockquote></details>

before calling `accumulate`, caller checks that types are of `typ`.
it is done in for loop below.
error can still come if `Less` operation is not supported on the type.

---

*[worker/task.go, line 219 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTAo1bPBrpNm8XKy1U:-KdVmLUJWogM2NxPpxnG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L219)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Maybe add a comment / example here on q.SrcFunc?
</blockquote></details>

Done.

---

*[worker/task.go, line 457 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTGY3JoaChSJvnZOzv:-KdVgoiiAnsOx6GbXtit:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L457)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Comment about the bool return being the filter mask?
</blockquote></details>

Done.

---

*[worker/task.go, line 556 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTKzvwgF7lIPtOph8A:-KdVh98WmnkTq7yu8shb:b-9mu222) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L556)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Why not return the error?
</blockquote></details>

this function should be used only in filtering fns..
so we if errored, then do not take it. i.e. return false.

---

*[worker/task.go, line 569 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTL8zPt7KXTILpz5HQ:-KdVkwgCBs0SYV91ajLh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L569)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Why such a special treatment here? Can this be moved into types?
</blockquote></details>

Done.

---

*[worker/task.go, line 582 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTJtPI79zDvtxa3DvU:-KdVhl0v8_k9Be8fQCy_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L582)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Comment that fcTokens, argTokens have to be sorted.
</blockquote></details>

Done.

---

*[worker/task.go, line 591 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTK65d5u6uH8CzZF8k:-KdVhm7GT4A5IdQSS2lJ:b-7ulnh0) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L591)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Can just compare once instead of potentially twice.

c := strings.Compare(...)
</blockquote></details>

its the same in strings.Compare as well. Also, they recommend to not call it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/607)*

**Comment by gacharya255** [comment]
:lgtm: Some comments and questions.

---

Review status: 8 of 19 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[types/facets/facet_types.go, line 103 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaCPEIwqaUknDJM6P_:-KdaCPEJrli5xSHGN2Qz:b-usisrb) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/types/facets/facet_types.go#L103)):*
> ```Go
> 
> // FacetFor returns Facet for given key and val.
> func FacetFor(key string, val string) (*Facet, error) {
> ```

nit: key, val string

---

*[types/facets/utils.go, line 50 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaL1yQNTZPYVADK1Fk:-KdaL1yRezFecGiHrqX8:b-6uamqm) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/types/facets/utils.go#L50)):*
> ```Go
> 			fs = append(fs, fcopy)
> 			kidx++
> 			fidx++
> ```

Can there be duplicate keys in param?

---

*[worker/task.go, line 591 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdTK65d5u6uH8CzZF8k:-KdaJMfKe4VXtEm2f7ZF:bqpc8d4) ([raw file](https://github.com/dgraph-io/dgraph/blob/5cb5ab6283accfcd635367f5167eb9153c01158c/worker/task.go#L591)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

its the same in strings.Compare as well. Also, they recommend to not call it.
</blockquote></details>

I went to take a look at the source of strings.Compare. Quite shocked. But yes you are right. No need to do that for strings.

---

*[worker/task.go, line 294 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaLqQzQ5wLLoryES8p:-KdaLqR-zEDx3Vdy52iP:brd02hg) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/worker/task.go#L294)):*
> ```Go
> 				if res {
> 					filteredRes = append(filteredRes, &result{uid: p.Uid,
> 						facets: facets.CopyFacets(p.Facets, q.FacetParam)})
> ```

nit: may be more readable to write

&result{
  uid: ...,
  facets: ...,
}

---

*[worker/task.go, line 396 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaM-CJaym5GckMVDZT:-KdaM-CJaym5GckMVDZU:b5u44v7) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/worker/task.go#L396)):*
> ```Go
> 			}
> 			// Are we making copies of sv and ineqValue ? expensive ?
> 			return compareTypeVals(q.SrcFunc[0], sv, ineqValue)
> ```

String and []byte copies are quite cheap, unless you explicitly do a real copy. I wouldn't worry too much about it.

---

*[worker/task.go, line 500 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaMJB8IRpLNVZNgTNJ:-KdaMJB9tOLqvrahPu0L:b-80ad8t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/worker/task.go#L500)):*
> ```Go
> 				return false, nil
> 			}
> 			sort.Strings(fcTokens)
> ```

Maybe, just maybe, we should just store these tokens in order and avoid re-sorting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-:-KdaM_9RMJ7lvNHVQBNr:b1psxkp)*

**Comment by ashishnegi** [comment]
Review status: 8 of 19 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[types/facets/facet_types.go, line 103 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaCPEIwqaUknDJM6P_:-KddU6J8F6u4xG8WTWA9:bs7wumx) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/types/facets/facet_types.go#L103)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

nit: key, val string
</blockquote></details>

Done. 

---

*[types/facets/utils.go, line 50 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaL1yQNTZPYVADK1Fk:-KdcrFCnAQQv_wP0HQVv:b-yep2yh) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/types/facets/utils.go#L50)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Can there be duplicate keys in param?
</blockquote></details>

ideally, no.
currently, we are not removing duplicates. i have added a bug for that.
even if there are duplicates in param.Keys, we only get one as facet's index (fidx) moves forward.

---

*[worker/task.go, line 294 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaLqQzQ5wLLoryES8p:-KddVLMWRvimiheDWLzB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/worker/task.go#L294)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

nit: may be more readable to write

&result{
  uid: ...,
  facets: ...,
}
</blockquote></details>

Done.

---

*[worker/task.go, line 396 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaM-CJaym5GckMVDZT:-KddVdVf3uFUYNPTJrct:b-kett6j) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/worker/task.go#L396)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

String and []byte copies are quite cheap, unless you explicitly do a real copy. I wouldn't worry too much about it.
</blockquote></details>

thanks for clarifying.

---

*[worker/task.go, line 500 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KdaMJB8IRpLNVZNgTNJ:-KdcqlUZ2RtoMYrS-irR:b-4uaqz3) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e113a5ba982f90eac1bb895b737864d6ff6a20c/worker/task.go#L500)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Maybe, just maybe, we should just store these tokens in order and avoid re-sorting.
</blockquote></details>

yes.. i have a task for optimizing this filtering..
will raise a separate PR for that. as this has become quite big.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/607)*

**Comment by manishrjain** [comment]
:lgtm: some comments.

---

Reviewed 3 of 16 files at r1, 6 of 8 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[types/facets/facets.proto, line 36 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-Kddfhw4xvCNFrX5-icV:-Kddfhw4xvCNFrX5-icW:beq4rwk) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/types/facets/facets.proto#L36)):*
> ```protobuf
> message Function {
> 	string name = 2;          // Name of the function : eq, leq
> 	string key = 1;           // Facet key over which to run the function.
> ```

ordering of the fields.

---

*[worker/task.go, line 287 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KddgQZbmiFbW1d53iME:-KddgQZbmiFbW1d53iMF:bk7kvny) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/worker/task.go#L287)):*
> ```Go
> 				res := true
> 				if q.FacetsFilter != nil {
> 					res, perr = applyFacetFilter(p.Facets, q.FacetsFilter)
> ```

Just make applyFacetFilter handle q.FacetsFilter being nil. It could return (true, nil) in that case. Would make your code here a bit easier to read.

```
res, perr := apply(..)
if perr != nil {
  return false  // break iteration
}
if res {
  fileteredRes = append(...)
}
return true  // continue iteration
```

---

*[worker/task.go, line 302 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-Kddgbn5GIMJxuQZ_Mdh:-Kddgbn5GIMJxuQZ_Mdi:b-lrcfni) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/worker/task.go#L302)):*
> ```Go
> 				return nil, perr
> 			}
> 		} else if q.FacetsFilter != nil {
> ```

It's a bit confusing. Above you seemed to still handle this cond as no problem, still appending results. Here you're returning with error. Add a comment about this code behavior.

---

*[worker/task.go, line 522 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-Kddhk1psE5VVIkVksJ4:-Kddhk1psE5VVIkVksJ5:bzcz7tw) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/worker/task.go#L522)):*
> ```Go
> 	}
> 
> 	switch strings.ToLower(ftree.Op) {
> ```

Shouldn't this be at the top? Looks like a precondition check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-:-Kddi-Rvt5hnYlFrgNvo:b-h0fnsz)*

**Comment by ashishnegi** [comment]
Review status: 17 of 19 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[types/facets/facets.proto, line 36 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-Kddfhw4xvCNFrX5-icV:-KddiXX8hLMs0V2pzxnh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/types/facets/facets.proto#L36)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ordering of the fields.
</blockquote></details>

Done.

---

*[worker/task.go, line 287 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-KddgQZbmiFbW1d53iME:-KddidE7-TUEOskdPVPj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/worker/task.go#L287)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just make applyFacetFilter handle q.FacetsFilter being nil. It could return (true, nil) in that case. Would make your code here a bit easier to read.

```
res, perr := apply(..)
if perr != nil {
  return false  // break iteration
}
if res {
  fileteredRes = append(...)
}
return true  // continue iteration
```
</blockquote></details>

Done.

---

*[worker/task.go, line 302 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-Kddgbn5GIMJxuQZ_Mdh:-KddjEb7LT74Y2lxMJSj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/worker/task.go#L302)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

It's a bit confusing. Above you seemed to still handle this cond as no problem, still appending results. Here you're returning with error. Add a comment about this code behavior.
</blockquote></details>

Done.

---

*[worker/task.go, line 522 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/607#-Kddhk1psE5VVIkVksJ4:-KddjwU09bWbNGnlbD72:b-dr2dm8) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c20e1022de2400aa727885db42f7e832e8fa32/worker/task.go#L522)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shouldn't this be at the top? Looks like a precondition check.
</blockquote></details>

We also want to return the final result here as well.
see `return !res[0], nil`
Otherwise two switch are required and might be verbose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/607)*

**Pull request closed without merging**
