### PR TITLE
Handle predicates better

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1116)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gql/parser.go, line 2194 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-KoBfNDSzs4dZdgXmzRV:-KoBfNDSzs4dZdgXmzRW:b-hsw0nj) ([raw file](https://github.com/dgraph-io/dgraph/blob/8c3b040ea0c91790cfc325f976e3e05b43e04746/gql/parser.go#L2194)):*
> ```Go
> 				varName, alias = "", ""
> 				it.Next()
> 				if item.Typ != itemLeftRound {
> ```

Any test cases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-:-KoBfOD5fR1PME861dR4:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gql/parser.go, line 2194 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-KoBfNDSzs4dZdgXmzRV:-KoFaS0X52hG4MKIK_n3:b-hg9q81) ([raw file](https://github.com/dgraph-io/dgraph/blob/8c3b040ea0c91790cfc325f976e3e05b43e04746/gql/parser.go#L2194)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Any test cases?
</blockquote></details>

Added. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[rdf/parse.go, line 225 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-KoFbVjZjAyZWSSVj3kP:-KoFbVj_rob_ytUmafQs:bf5cg8c) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22334c67bd53af1fc7143f1e902c40a51d4221b/rdf/parse.go#L225)):*
> ```Go
> 		}
> 		nq, err := Parse(ln)
> 		if nq.Predicate != "" && nq.Predicate[0] == '_' &&
> ```

len(nq.Predicate) > 0?

---

*[rdf/parse.go, line 227 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-KoFbZ3ZLI60qFOcb5ax:-KoFbZ3ZLI60qFOcb5ay:ba3dfna) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22334c67bd53af1fc7143f1e902c40a51d4221b/rdf/parse.go#L227)):*
> ```Go
> 		if nq.Predicate != "" && nq.Predicate[0] == '_' &&
> 			nq.Predicate[len(nq.Predicate)-1] == '_' {
> 			fmt.Println(nq.Predicate)
> ```

Remove?

---

*[rdf/parse.go, line 228 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-KoFbc5l23Qky9KfRVDv:-KoFbc5l23Qky9KfRVDw:b-aw4r4j) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22334c67bd53af1fc7143f1e902c40a51d4221b/rdf/parse.go#L228)):*
> ```Go
> 			nq.Predicate[len(nq.Predicate)-1] == '_' {
> 			fmt.Println(nq.Predicate)
> 			return nil, x.Errorf("Predicates starting and ending with _ are not allowed for users")
> ```

... ending with _ are reserved as internal predicates and cannot be set from outside?

---

*[x/x.go, line 46 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-KoFbvlk6Ss82uyAbq_F:-KoFbvlk6Ss82uyAbq_G:b-3hgot1) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22334c67bd53af1fc7143f1e902c40a51d4221b/x/x.go#L46)):*
> ```Go
> 	ErrorInvalidMutation = "ErrorInvalidMutation"
> 	ValidHostnameRegex   = "^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$"
> 	Star                 = "_STAR_ALL"
> ```

This is so that rdf.Parse passes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1116#-:-KoFc6MgQFo8YJOtoj7V:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
