### PR TITLE
Fix(ACL) : Disallow deleting of groot user and guardians group

### PR DESCRIPTION
**Pull request by vmrajas**
Motivation
Currently, it is possible to delete guardians user group and groot user using a simple graphql query. 
This behaviour causes bad user experience as guardians is the admin group and groot user is the primary admin user. 
Once, the group has been deleted, to get back access to groot user, the user has to restart dgraph alpha again. 
This PR adds fixes this. This PR makes it impossible to delete groot user and guardians group.
Related discuss issue: https://discuss.dgraph.io/t/customers-can-delete-guardians-group-and-lose-access/9614

Components affected by this PR:
Dgraph ACL

Does this PR break backwards compatibility?:
No

Fixes DGRAPH-2454

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)

 

Docs Preview: [Dgraph Preview](https://dgraph-77245812ec-100763.surge.sh)

### CODE REVIEW

**Review by animesh2049 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @animesh2049, @manishrjain, @pawanrawal, @vmrajas, and @vvbalaji-dgraph)

___
*[edgraph/access_ee.go, line 49 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIPLxYT-H9_er7WgjUQ:-MIPLxYT-H9_er7WgjUR:b-67g9xc) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/edgraph/access_ee.go#L49)):*
> ```Go
> }
> 
> type groupNode struct {
> ```

They are being used only once. I don't think we should create global type for them. Maybe just define them inside the function.
___
*[ee/acl/acl_test.go, line 3117 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIPLgh5CQp1dD6Qbzva:-MIPLgh5CQp1dD6Qbzvb:b7746o8) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/ee/acl/acl_test.go#L3117)):*
> ```Go
> }
> 
> func TestDeleteGuardiansGroupShouldFail(t *testing.T) {
> ```

Please add tests for mutations with `*` 
___
*[query/mutation.go, line 51 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIOyr5t--DFv9OxvnVJ:-MIOyr5t--DFv9OxvnVK:brz6ueg) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/query/mutation.go#L51)):*
> ```Go
> 	for _, edge := range m.Edges {
> 		// Disallow deleting of guardians group
> 		if edge.Entity == guardianGroupUid && edge.Attr == "dgraph.xid" && edge.Op == pb.DirectedEdge_DEL {
> ```

I think we might miss deletion with `*` operator. 
```
<guardians_id> * * .
```
The above query would still delete the guardians group. 
According to me, better approach will be to allow only password change operation on `groot` and no change for `guardians`.  Block any other operation involving them. 
___
*[x/x.go, line 175 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIOxMin584MvqS0h8zA:-MIOxMin584MvqS0h8zB:becdfrv) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/x/x.go#L175)):*
> ```Go
> 	AcceptedOrigins = atomic.Value{}
> 	// GuardiansGroupUid is Uid of guardians group node.
> 	GuardiansGroupUid = atomic.Value{}
> ```

Any specific reason for using `atomic.Value` ? Can't `GuardiansGroupUid` and `GrootUserUid` simply be 2 `uint64` and we can use `atomic.LoadUint64` and `atomic.StoreUint64` on them?

**Review by animesh2049 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @pawanrawal, @vmrajas, and @vvbalaji-dgraph)

___
*[query/mutation.go, line 51 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIOyr5t--DFv9OxvnVJ:-MIUqWm94W7N0ZWayJzC:bpzixm) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/query/mutation.go#L51)):*
<details><summary><i>Previously, animesh2049 (Animesh Chandra Pathak) wrote…</i></summary><blockquote>

I think we might miss deletion with `*` operator. 
```
<guardians_id> * * .
```
The above query would still delete the guardians group. 
According to me, better approach will be to allow only password change operation on `groot` and no change for `guardians`.  Block any other operation involving them. 
</blockquote></details>

I forgot the fact that start will be expanded before coming here. But I feel later part is still valid.

**Review by vmrajas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @animesh2049, @manishrjain, @pawanrawal, @vmrajas, and @vvbalaji-dgraph)

___
*[edgraph/access_ee.go, line 49 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIPLxYT-H9_er7WgjUQ:-MJRWlaw-RP4QVlQpcnl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/edgraph/access_ee.go#L49)):*
<details><summary><i>Previously, animesh2049 (Animesh Chandra Pathak) wrote…</i></summary><blockquote>

They are being used only once. I don't think we should create global type for them. Maybe just define them inside the function.
</blockquote></details>

Done.
___
*[query/mutation.go, line 51 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIOyr5t--DFv9OxvnVJ:-MJRWs5r4K-IgT8yyFch:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/query/mutation.go#L51)):*
<details><summary><i>Previously, animesh2049 (Animesh Chandra Pathak) wrote…</i></summary><blockquote>

I forgot the fact that start will be expanded before coming here. But I feel later part is still valid. 
</blockquote></details>

Done.
___
*[x/x.go, line 175 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIOxMin584MvqS0h8zA:-MJRWt5iCYvz9dV0p-DR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/x/x.go#L175)):*
<details><summary><i>Previously, animesh2049 (Animesh Chandra Pathak) wrote…</i></summary><blockquote>

Any specific reason for using `atomic.Value` ? Can't `GuardiansGroupUid` and `GrootUserUid` simply be 2 `uint64` and we can use `atomic.LoadUint64` and `atomic.StoreUint64` on them?
</blockquote></details>

Done.

**Review by animesh2049 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-:-MJSKiRi5B3ucGV-4iEb:bg7igkv)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @abhimanyusinghgaur, @animesh2049, @manishrjain, @pawanrawal, @vmrajas, and @vvbalaji-dgraph)

___
*[query/mutation.go, line 259 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJSK48TDdHg7fWsD_zu:-MJSK48U89rZI55yr6iV:b5gsje8) ([raw file](https://github.com/dgraph-io/dgraph/blob/cccd6eddefd199568c4bed6f21f669bd461d6095/query/mutation.go#L259)):*
> ```Go
> 		// Disallow deleting of guardians group
> 		if edge.Entity == guardianGroupUid && edge.Op == pb.DirectedEdge_DEL {
> 			glog.Info("Trying to delete guardians group. Operation not allowed.")
> ```

Minor: `trying to delete guardians group` might not be appropriate every time. Sometimes it might just be trying to delete some edge of `guardian`. Same for groot and the error message being returned.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)* status: 0 of 4 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @animesh2049, @manishrjain, @pawanrawal, @vmrajas, and @vvbalaji-dgraph)

___
*[ee/acl/acl_test.go, line 3117 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIPLgh5CQp1dD6Qbzva:-MJa5vPk7LbrRf4NOBrN:bmif1d9) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/ee/acl/acl_test.go#L3117)):*
<details><summary><i>Previously, animesh2049 (Animesh Chandra Pathak) wrote…</i></summary><blockquote>

Please add tests for mutations with `*` 
</blockquote></details>

Might be hard to test this automatically as we won't have the uid for `groot` or `guardians`. Though worth testing manually.
___
*[query/mutation.go, line 245 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJa6IpKEmKt3ICbL-Ch:-MJa6IpKEmKt3ICbL-Ci:biny048) ([raw file](https://github.com/dgraph-io/dgraph/blob/cccd6eddefd199568c4bed6f21f669bd461d6095/query/mutation.go#L245)):*
> ```Go
> 
> 
> func checkIfDeletingAclOperation(edges []*pb.DirectedEdge) error {
> ```

Can we verify that `drop_data` and `drop_all` should still work?

Currently after drop all/drop data the groot and guardian group are re-added. Are there uids refreshed currently or only after a restart?
___
*[query/mutation.go, line 265 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJa6vDV0RF3FUJp9jQF:-MJa6vDV0RF3FUJp9jQG:b-citayx) ([raw file](https://github.com/dgraph-io/dgraph/blob/cccd6eddefd199568c4bed6f21f669bd461d6095/query/mutation.go#L265)):*
> ```Go
> 		// Disallow deleting of groot user
> 		if edge.Entity == grootUserUid && edge.Op == pb.DirectedEdge_DEL {
> 			glog.Info("Trying to delete groot user. Operation not allowed.")
> ```

I don't think we need these info logs because we are returning an error here.
___
*[query/mutation.go, line 271 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJa6qfi12xmDIcYeNfP:-MJa6qfi12xmDIcYeNfQ:b-4r2snx) ([raw file](https://github.com/dgraph-io/dgraph/blob/cccd6eddefd199568c4bed6f21f669bd461d6095/query/mutation.go#L271)):*
> ```Go
> 	}
> 	if isDeleteAclOperation {
> 		return errors.Errorf("guardians group and groot user cannot be deleted.")
> ```

Properties of guardians group and groot user...

**Review by vmrajas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @abhimanyusinghgaur, @animesh2049, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[ee/acl/acl_test.go, line 3117 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MIPLgh5CQp1dD6Qbzva:-MJax9C38UoMMM1b2sEO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b28f56769692e42773c376acf2b5e72d2530da96/ee/acl/acl_test.go#L3117)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Might be hard to test this automatically as we won't have the uid for `groot` or `guardians`. Though worth testing manually.
</blockquote></details>

Done.
___
*[query/mutation.go, line 245 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJa6IpKEmKt3ICbL-Ch:-MJaxAJa7-xEzSeSplYb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cccd6eddefd199568c4bed6f21f669bd461d6095/query/mutation.go#L245)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we verify that `drop_data` and `drop_all` should still work?

Currently after drop all/drop data the groot and guardian group are re-added. Are there uids refreshed currently or only after a restart?
</blockquote></details>

Done.
___
*[query/mutation.go, line 265 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJa6vDV0RF3FUJp9jQF:-MJaxDN33szmXV3rFuAJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cccd6eddefd199568c4bed6f21f669bd461d6095/query/mutation.go#L265)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I don't think we need these info logs because we are returning an error here.
</blockquote></details>

Done.
___
*[query/mutation.go, line 271 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJa6qfi12xmDIcYeNfP:-MJaxERA7VHDn7oC6oII:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cccd6eddefd199568c4bed6f21f669bd461d6095/query/mutation.go#L271)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Properties of guardians group and groot user...
</blockquote></details>

Done.

**Review by pawanrawal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @animesh2049, @manishrjain, @pawanrawal, @vmrajas, and @vvbalaji-dgraph)

___
*[edgraph/access_ee.go, line 457 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJfI8nJ62XtMIkWOxYS:-MJfI8nJ62XtMIkWOxYT:b-mw2k7s) ([raw file](https://github.com/dgraph-io/dgraph/blob/940a9226b7ae6e051761e168bf6cefb9a645ac04/edgraph/access_ee.go#L457)):*
> ```Go
> 		atomic.StoreUint64(&x.GuardiansGroupUid, guardiansGroupUidUint)
> 
> 		glog.Infof("guardians group uid: %d", guardiansGroupUidUint)
> ```

Don't print this.
___
*[edgraph/access_ee.go, line 526 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJfI3O1-uVKJsi347WR:-MJfI3O1-uVKJsi347WS:bjlktmz) ([raw file](https://github.com/dgraph-io/dgraph/blob/940a9226b7ae6e051761e168bf6cefb9a645ac04/edgraph/access_ee.go#L526)):*
> ```Go
> 		}
> 		atomic.StoreUint64(&x.GrootUserUid, grootUserUidUint)
> 		glog.Infof("groot user uid: %d", grootUserUidUint)
> ```

We don't need to really print this id here.

**Review by vmrajas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6580)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @animesh2049, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/access_ee.go, line 457 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJfI8nJ62XtMIkWOxYS:-MJlKWrC9Cp3y3oiFLBw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/940a9226b7ae6e051761e168bf6cefb9a645ac04/edgraph/access_ee.go#L457)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't print this.
</blockquote></details>

Done.
___
*[edgraph/access_ee.go, line 526 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6580#-MJfI3O1-uVKJsi347WR:-MJlKX9T2AL448zXuFIy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/940a9226b7ae6e051761e168bf6cefb9a645ac04/edgraph/access_ee.go#L526)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We don't need to really print this id here.
</blockquote></details>

Done.

**Review by parasssh — APPROVED** [review]

**Pull request merged**
