### PR TITLE
Return assigned UIDs back in JSON result

### PR DESCRIPTION
**Pull request by ashwin95r**
#580

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/582)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/outputnode.go, line 413 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/582#-KcqLXojJFWkGu0XjhsJ:-KcqLXojJFWkGu0XjhsK:b-ew1coe) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cbedfbc28f4c11188d0ff7b84f0b2636b063167/query/outputnode.go#L413)):*
> ```Go
> 		sl := seedNode.New("uids").(*fastJsonNode)
> 		for k, v := range allocIds {
> 			sl.attrs[k] = []byte(v)
> ```

it is better to call API `Add*` as they check for duplicate keys and so on..
the one above in serverLatency is my fault. will correct later.

---

*[query/outputnode.go, line 422 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/582#-KcqM-QrJVv3oukLpVJb:-KcqM-QsokN6adzAUKln:b-o57vzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cbedfbc28f4c11188d0ff7b84f0b2636b063167/query/outputnode.go#L422)):*
> ```Go
> 			return slw.Flush()
> 		}
> 		n.(*fastJsonNode).attrs["uids"] = slBuf.Bytes()
> ```

is the output like :
` uids : {}` i.e. a map of uids..? There is no support of adding an object to `outputNode` currently.
Then this is ok for now, but newer api of `AddNodeValue` will solve this problem more easily.
Will refactor this after that..

---

*[query/query_test.go, line 3064 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/582#-KcqMyU4CGyznrKWAeE2:-KcqMyU53izNB-ztR88U:b-mawczo) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cbedfbc28f4c11188d0ff7b84f0b2636b063167/query/query_test.go#L3064)):*
> ```Go
> 	var l Latency
> 	var buf bytes.Buffer
> 	err = sg.ToFastJSON(&l, &buf, nil)
> ```

Adding one test for new feature will be helpful, especially when moving to `AddNodeValue`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/582)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/outputnode.go, line 413 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/582#-KcqLXojJFWkGu0XjhsJ:-KcqNv7Gom-ugCdxW21k:b-w7gbin) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cbedfbc28f4c11188d0ff7b84f0b2636b063167/query/outputnode.go#L413)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

it is better to call API `Add*` as they check for duplicate keys and so on..
the one above in serverLatency is my fault. will correct later.
</blockquote></details>

Yeah, I guess we can refactor this after the new change.

---

*[query/outputnode.go, line 422 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/582#-KcqM-QrJVv3oukLpVJb:-KcqNteCiTs4AgQ8X23p:b-837i3v) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cbedfbc28f4c11188d0ff7b84f0b2636b063167/query/outputnode.go#L422)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

is the output like :
` uids : {}` i.e. a map of uids..? There is no support of adding an object to `outputNode` currently.
Then this is ok for now, but newer api of `AddNodeValue` will solve this problem more easily.
Will refactor this after that..
</blockquote></details>

Okay.

---

*[query/query_test.go, line 3064 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/582#-KcqMyU4CGyznrKWAeE2:-KcqRDfXgLDvN0sHaOwj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0cbedfbc28f4c11188d0ff7b84f0b2636b063167/query/query_test.go#L3064)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Adding one test for new feature will be helpful, especially when moving to `AddNodeValue`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/582)*

**Comment by ashishnegi** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/582#-:-KcuXj8_VXFbtmBjWx3l:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
