### PR TITLE
Aggregate/root

### LINKED ISSUE #1330: Dgraph does not allow to do aggregations (i.e. sum) at the top level of a query
I have been trying to do aggregations at the top level of a query but it seems like it only works when the aggregation is done at a sub-level. 
Since aggregation only works on variables, and variables can't be used on the same level, then aggregation does not work at the root level.

### PR DESCRIPTION
**Pull request by pawanrawal**
This resolves #1330.

User can do aggregations and use math functions on them inside empty block.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1333)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query_test.go, line 8859 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1333#-KrUJ88dq5AQ6fUOpZEe:-KrUJ88dq5AQ6fUOpZEf:b3brlwy) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae03850eeb450e30b679b0d93f475fd7710ac6b7/query/query_test.go#L8859)):*
> ```Go
> 
> 			me() {
> 				Sum: math(a + a2)
> ```

Also check what happens when you retrieve a predicate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1333#-:-KrUJEes-JO2SQIsktBR:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 1044 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1333#-KrUU1svHjDre3Q2X571:-KrUU1svHjDre3Q2X572:b-qd28oh) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc51db62750ec375c74b11cf84be874b470921d8/query/query.go#L1044)):*
> ```Go
> 	if parent.Params.IsEmpty {
> 		// The aggregated value doesn't really belong to a uid, we put it in uidToVal map
> 		// corresponding to uid 0 to avoid defining another field in SubGraph.
> ```

What if there are predicates inside aggregation function ? Do we have a check that only variables can be used inside aggregation/math functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1333#-:-KrUUDAsuB8HVjuizpfw:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 1044 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1333#-KrUU1svHjDre3Q2X571:-KrUcjiZVIucp2Z_Fx7M:b-6um0n2) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc51db62750ec375c74b11cf84be874b470921d8/query/query.go#L1044)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

What if there are predicates inside aggregation function ? Do we have a check that only variables can be used inside aggregation/math functions.
</blockquote></details>

Parser checks that only variables are allowed in aggregate functions.
As regards to math function, that would error out at least in the empty block because we won't find a value in mp corresponding to uid 0 if it's not a aggregated variable.

---

*[query/query_test.go, line 8859 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1333#-KrUJ88dq5AQ6fUOpZEe:-KrUPJH3R7PXeKocQxAL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ae03850eeb450e30b679b0d93f475fd7710ac6b7/query/query_test.go#L8859)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Also check what happens when you retrieve a predicate.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1333)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
