### PR TITLE
Adding docs + making changes to rdf module in accordance with go vet and golint.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/155)

### CODE REVIEW

**Comment by manishrjain** [comment]
Nice effort! In fact, the first effort we have made towards better code documentation. Kudos!

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/dgraph/main.go, line 94 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnJx80lZYquXaQkjrW:-KOnJx80lZYquXaQkjrX:b-rfc14n) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/cmd/dgraph/main.go#L94)):*
> ```Go
> 	}
> 
> 	// xidToUid is used to store ids which are not uids. It is sent to the instance which has the xid <-> uid mapping to get uids.
> ```

Line > 100 chars.

---

*[loader/loader.go, line 231 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnK-xjuU7uHlcmVRua:-KOnK-xjuU7uHlcmVRub:b-e03qtx) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/loader/loader.go#L231)):*
> ```Go
> 		}
> 
> 		if len(nq.ObjectID) > 0 &&
> ```

I don't agree with Go view that all `id` has to be capitalized. It's unnecessary. And you have to keep the shift key held up while you type this. It's annoying. IMO, we don't need to change this.

---

*[rdf/parse.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnKJ9YvFO1zQiigZpO:-KOnKJ9YvFO1zQiigZpP:b-elef7y) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/parse.go#L31)):*
> ```Go
> )
> 
> //NQuad is the data structure used for storing rdf N-Quads.
> ```

Space after comment.

---

*[rdf/parse.go, line 52 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnKQ47KASEOEZ3fQ9a:-KOnKQ47KASEOEZ3fQ9b:bbeeh16) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/parse.go#L52)):*
> ```Go
> 
> // ToEdge is useful when you want to find the UID corresponding to XID for
> // just one edge. The method doen't generate a UID for an XID.
> ```

"doesn't automatically"

---

*[rdf/parse.go, line 87 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnUOaRGAnCq6z-LJiU:-KOnUOaRGAnCq6z-LJiV:bauzygy) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/parse.go#L87)):*
> ```Go
> }
> 
> // ToEdgeUsing is useful when you do find the UID corresponding to XID
> ```

You can shorten it to:

ToEdgeUsing determines the UIDs for the provided XIDs, and populates xidToUid map.

---

*[rdf/state.go, line 193 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnVri3Xtj0v5un84mT:-KOnVri3Xtj0v5un84mU:b92ms9m) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L193)):*
> ```Go
> 		l.Depth++
> 		r = l.Next()
> 		//TODO - Remove this, doesn't conform with the spec.
> ```

space after comment. I wonder why gofmt doesn't catch this.

---

*[rdf/state.go, line 297 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnW5BdL7FHCPQNZ8ma:-KOnW5BdL7FHCPQNZ8mb:b-huyylq) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L297)):*
> ```Go
> 		l.Depth++
> 		r = l.Next()
> 		//TODO - Remove this, doesn't conform with the spec.
> ```

space after comment.

---

*[rdf/state.go, line 339 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnWCHtS-jekXSVRnGr:-KOnWCHtS-jekXSVRnGs:b-u2fewl) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L339)):*
> ```Go
> }
> 
> // Checks for tab or space.
> ```

how about:

// isSpace returns true if the rune is a tab or a space.

---

*[rdf/state.go, line 359 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnWGGrRekthcRlLn59:-KOnWGGrRekthcRlLn5A:b-tcfg2b) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L359)):*
> ```Go
> }
> 
> // Checks for language tag according to the spec.
> ```

// isLangTag returns true if the rune is allowed by the RDF spec.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-:-KOnWNDLyyV9du2PQYkv:bufbnty)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/dgraph/main.go, line 94 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnJx80lZYquXaQkjrW:-KOniWPfwkyfrjGsdRXk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/cmd/dgraph/main.go#L94)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Line > 100 chars.
</details>
Done.

---

*[rdf/parse.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnKJ9YvFO1zQiigZpO:-KOnh-WE46sM3CAIIr5o:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/parse.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Space after comment.
</details>
Done.

---

*[rdf/parse.go, line 52 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnKQ47KASEOEZ3fQ9a:-KOngzhtu788xqhCftTT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/parse.go#L52)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> "doesn't automatically"
</details>
Done.

---

*[rdf/parse.go, line 87 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnUOaRGAnCq6z-LJiU:-KOnhoprNWkkNziRRusg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/parse.go#L87)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can shorten it to:
> 
> ToEdgeUsing determines the UIDs for the provided XIDs, and populates xidToUid map.
</details>
Done.

---

*[rdf/state.go, line 193 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnVri3Xtj0v5un84mT:-KOnhkRgUx7AXjAt6U0y:b1wh6ni) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L193)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> space after comment. I wonder why gofmt doesn't catch this.
</details>
Done. Yeah, should be an easy catch.

---

*[rdf/state.go, line 297 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnW5BdL7FHCPQNZ8ma:-KOnhjkfmVyUTJtCwKqZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L297)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> space after comment.
</details>
Done.

---

*[rdf/state.go, line 339 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnWCHtS-jekXSVRnGr:-KOnhj4QBAHHp-cgH5IG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L339)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> how about:
> 
> // isSpace returns true if the rune is a tab or a space.
</details>
Done.

---

*[rdf/state.go, line 359 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-KOnWGGrRekthcRlLn59:-KOnhiYAgJti9GS6aeKw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/95ecadf47c87d91e5319929c1e8a12de8a818808/rdf/state.go#L359)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> // isLangTag returns true if the rune is allowed by the RDF spec.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/155)*

**Comment by manishrjain** [comment]
:lgtm: Looks good. Feel free to submit!

---

Reviewed 2 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/155#-:-KOo04SnMPL2CxdskL_W:b5xxxm0)*

**Comment by pawanrawal** [comment]
Merged to develop with commit 53fd608b25a3e723b04c05e0106dc0cd58de8d82

**Pull request closed without merging**
