### PR TITLE
[docs]: bulk load an enc export into a non enc cluster

### PR DESCRIPTION
**Pull request by OmarAyo**
Adding flags and examples how to import, with bulk loader, and encrypted export into a non-encrypted cluster

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948)

### CODE REVIEW

**Review by aaroncarey — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948)* status: all files reviewed, 5 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 79 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKZ0qBsOEplmiH9ta:-MMqKZ0qBsOEplmiH9tb:b9oqihr) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L79)):*
> ```
> Alpha node
> ```
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 84 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKbQz0c7iaXshy_XI:-MMqKbQz0c7iaXshy_XJ:b-6y4sz9) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L84)):*
> ```
> Alpha
> ```
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 84 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKhQZ4XzOkHtRzt3q:-MMqKhQZ4XzOkHtRzt3r:bhl58ks) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L84)):*
> ```
> you need
> ```
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 89 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKwm0AVHEDDudHOfM:-MMqKwm0AVHEDDudHOfN:bna4sbv) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L89)):*
> ```
> because the exported data has 
> ```
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 89 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqL7_J8-UYSaYdgmRo:-MMqL7_J8-UYSaYdgmRp:b-2djf85) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L89)):*
> ```
> also passing
> ```

**Comment by aaroncarey** [comment]
LGTM after a few minor wording changes.

**Comment by OmarAyo** [comment]
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 79 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKZ0qBsOEplmiH9ta:-MMqMNAK-yfsCIetDLA3:berazfo) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L79)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> Alpha node
> ```

</blockquote></details>

I will rename it from existing Alpha to existing Dgraph Cluster

**Comment by OmarAyo** [comment]
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 84 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKbQz0c7iaXshy_XI:-MMqMdeC94kRcPL93cjh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L84)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> Alpha
> ```

</blockquote></details>

Done.

**Review by OmarAyo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948)* status: all files reviewed, 5 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 84 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKhQZ4XzOkHtRzt3q:-MMqMulp296CpWyo4Gyn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L84)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> you need
> ```

</blockquote></details>

Done.
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 89 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKwm0AVHEDDudHOfM:-MMqMv9T8-TPqG2gTll8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L89)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> because the exported data has 
> ```

</blockquote></details>

Done.
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 89 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqL7_J8-UYSaYdgmRo:-MMqN1-m0WQJAmOYPSr0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L89)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> also passing
> ```

</blockquote></details>

Done.

**Review by aaroncarey — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948)* status: all files reviewed, 1 unresolved discussion (waiting on @aaroncarey, @bucanero, @danielmai, and @MichaelJCompton)

**Review by aaroncarey — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 79 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqOr6c9NFJiGWkq6nB:-MMqOr6c9NFJiGWkq6nC:b-lxc3ox) ([raw file](https://github.com/dgraph-io/dgraph/blob/36e427709334d810cd24f28f3f2c1d009875d916/wiki/content/enterprise-features/encryption-at-rest.md#L79)):*
> ```
> cluster
> ```

**Review by aaroncarey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 79 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKZ0qBsOEplmiH9ta:-MMqOyQlCC2irRVEsVUX:bvvvwpi) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L79)):*
<details><summary><i>Previously, OmarAyo (OmarAyo) wrote…</i></summary><blockquote>

I will rename it from existing Alpha to existing Dgraph Cluster 
</blockquote></details>

Cluster -> cluster

**Review by OmarAyo — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948)* status: all files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @MichaelJCompton)

___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 79 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqKZ0qBsOEplmiH9ta:-MMqPkLTEDPeYy8ZLWyi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c023dcbac3e66925cc124c13b1cb424170b2579b/wiki/content/enterprise-features/encryption-at-rest.md#L79)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

Cluster -> cluster
</blockquote></details>

Done.
___
*[wiki/content/enterprise-features/encryption-at-rest.md, line 79 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-MMqOr6c9NFJiGWkq6nB:-MMqPkdB0OveBI8KvTBN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36e427709334d810cd24f28f3f2c1d009875d916/wiki/content/enterprise-features/encryption-at-rest.md#L79)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> cluster
> ```

</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6948#-:-MN-3TZdExpum682d0t1:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, and @MichaelJCompton)

**Pull request merged**
