### PR TITLE
Uid/extra call

### LINKED ISSUE #1078: dgraph redundant query for _uid_
Every time we query for `_uid_`, we actually already has it. But we still run extra query for `attr` \_uid_.

Tow kind of queries in dgraph:
1. query something, attribute or predicates, directly by id
2. use index or predicates to get an id and then query something by id

To item 1, we query on root by func `id:[id]`. The id is alreay given by the user, so we know it(not matter it's valid or not).
To item 2, the id is query result. Of course we know it, unless the query returns nothing.

For example, a query like this
```Text
query{
	id(func:eq(tag,"device"),first:2){
		_uid_
	}
}
```

will be executed like this,
```Text
--taskquery{
        "attr": "tag",
        "src_func": [
                "eq",
                "",
                "device"
        ]
}

--task query result{
        "uid_matrix": [
                {
                        "uids": [
                                11430041756990,
                                22013783089703,
                                ...
                                ]
                }
        ],
        "values": [
                {}
        ]
    }
    

--taskquery{
	"attr": "_uid_",
	"uid_list": {
		"uids": [
			11430041756990,
			22013783089703
		]
	}
}

--task query result{
	"uid_matrix": [
		{},
		{}
	],
	"values": [
		{
			"val": "Xw=="
		},
		{
			"val": "Xw=="
		}
	]
}
```

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #1078

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1102)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102#-:-Ko9zijcVrQWmNnXf46O:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[query/query.go, line 1775 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102#-KoAaJ2sikf2d0uVy4na:-KoAaJ2sikf2d0uVy4nb:b-23jcjf) ([raw file](https://github.com/dgraph-io/dgraph/blob/756106c683db55adba33a24aac7ca0b57e860882/query/query.go#L1775)):*
> ```Go
> 	// Now get all the results back.
> 	for _, child := range sg.Children {
> 		if child.IsInternal() || child.Attr == "_uid_" {
> ```

Can we mark the node with attr as isInternal? As it satisfies the definition of not needing a network call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[query/query.go, line 1775 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102#-KoAaJ2sikf2d0uVy4na:-KoAaXprzQ4g40Xjs_96:bzam6zy) ([raw file](https://github.com/dgraph-io/dgraph/blob/756106c683db55adba33a24aac7ca0b57e860882/query/query.go#L1775)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Can we mark the node with attr as isInternal? As it satisfies the definition of not needing a network call.
</blockquote></details>

att `_uid_`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102#-:-KoAupY_IdYIAXQCpnCI:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[query/query.go, line 1775 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102#-KoAaJ2sikf2d0uVy4na:-KoAzAQSNNqiMJxQ13je:be4m2zp) ([raw file](https://github.com/dgraph-io/dgraph/blob/756106c683db55adba33a24aac7ca0b57e860882/query/query.go#L1775)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

att `_uid_`
</blockquote></details>

We do lot of stuff for IsInternal like valueVarAggregation and special handling in preTraverse which is not applicate here. So skipping this for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1102)*

**Comment by pawanrawal** [comment]
Merged to master

**Pull request closed without merging**
