### PR TITLE
add basic types, sample schema and dummy schema validation skeleton

### PR DESCRIPTION
**Pull request by akhiltak**
ToDo (before merge to master):
 

- [x] complete validation and execution step
- [x] add tests for new methods
- [ ] squash additional commits (if any)
- [x] fix formatting issues (text editor bugs)
- [x] use git rebase while merging from master branch  
- [ ] get LGTM

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/172)

### CODE REVIEW

**Comment by manishrjain** [comment]
This seems unnecessarily complicated for what we're trying to achieve here. My comments are inlined.

---

Reviewed 1 of 7 files at r1, 3 of 8 files at r5, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 39 unresolved discussions, some commit checks failed.

---

*[types/definitions.go, line 31 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkVkXKpUcNeADFhsn:-KQIkVkXKpUcNeADFhso:b-s42j9t) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L31)):*
> ```Go
> 	Name        string       // name of scalar type
> 	Description string       // short description, could be used for documentation in GraphiQL
> 	Config      ScalarConfig // config struct to construct a custom scalar
> ```

Keep the definition of ScalarConfig close to where it's being called first. In this case, here.

---

*[types/definitions.go, line 36 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIk-y_AdYFCUXMkTzl:-KQIk-y_AdYFCUXMkTzm:bja0wah) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L36)):*
> ```Go
> 
> // SerializeFunc is a function type that serializes GraphQL Scalar types.
> type SerializeFunc func(input interface{}) interface{}
> ```

Avoid using interfaces so heavily. Also, do we need to serialize? All input to Dgraph is in string format, via RDF.

---

*[types/definitions.go, line 39 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkIXc8Wih5thdX-oK:-KQIkIXc8Wih5thdX-oL:b-h7l33q) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L39)):*
> ```Go
> 
> // ParseValueFunc is a function type that parses the value of GraphQL Scalar types.
> type ParseValueFunc func(input interface{}) interface{}
> ```

The input here is most likely a `[]byte`.

---

*[types/definitions.go, line 42 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkN4voNMRvOdjMeX3:-KQIkN4voNMRvOdjMeX4:b-2drmiz) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L42)):*
> ```Go
> 
> // ParseLiteralFunc is a function type that parses literal value of GraphQL Scalar types.
> type ParseLiteralFunc func(input interface{}) interface{}
> ```

Not sure about the difference between this function and the above function.

---

*[types/definitions.go, line 48 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkdlpEOAydzdEay3w:-KQIkdlpEOAydzdEay3x:bt48qrc) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L48)):*
> ```Go
> 	Name        string
> 	Description string
> 	Serialize   SerializeFunc
> ```

GraphQLScalar above already contains Name and Description. Why repeat yourself here? Also, do you really need a separate struct for `Serialize`?

---

*[types/definitions.go, line 63 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIjkICSws2qKVcD8yF:-KQIjkICSws2qKVcD8yG:bqzbgvm) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L63)):*
> ```Go
> // - Boolean
> // - ID
> func MakeScalarType(sc *ScalarConfig) GraphQLScalar {
> ```

Custom types seem like they could have waited for the basic implementation of scalars to be up and running first.

---

*[types/definitions.go, line 127 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkvl6fzFkUdDapkib:-KQIkvl6fzFkUdDapkic:b-g1jsax) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L127)):*
> ```Go
> // Could make it stricter with a wrapper interface
> type Field struct {
> 	Type    interface{}
> ```

Can't Type be defined as a string?

---

*[types/definitions.go, line 128 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIl-DVMjtYKAEuH3FC:-KQIl-DVMjtYKAEuH3FD:bdyr7t5) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L128)):*
> ```Go
> type Field struct {
> 	Type    interface{}
> 	Resolve ResolveFunc
> ```

There is a lot of indirection here. ResolveFunc has ResolveParams, which basically contain a string.

Looking at this code, it occurs to me that if you had defined 5 resolve functions, one for each scalar type, and just stick in there along with a schema mentioning predicate -> type, that would be all you need to achieve this functionality. Given a predicate, you find the type, then given this type, find the resolve function, and try to parse the `[]byte` into the right interface{} for JSON. For PB, you extend it with int, float, bool etc. and set the right object value.

---

*[types/schema.go, line 34 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIj8ECy0wSMIaldVFT:-KQIj8EDAT9PcnLDVKFN:byro00t) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/schema.go#L34)):*
> ```Go
> // QueryType defines sample basic schema.
> // TODO(akhil): move definition to query_test and have a generic schema and QueryType here
> var QueryType = GraphQLObject{
> ```

I'm trying to understand this schema. Why is it defined in code? Shouldn't there be a schema file as we'd discussed?​

---

*[types/schema.go, line 40 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIjJSAGVMN62T2cPUl:-KQIjJSAGVMN62T2cPUm:bnugzuv) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/schema.go#L40)):*
> ```Go
> 		"work": &Field{
> 			Type: String,
> 			Resolve: func(rp ResolveParams) interface{} {
> ```

What's this function for?

---

*[types/type_errors.go, line 19 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIjP5m1v6dbuIiura_:-KQIjP5m1v6dbuIiuraa:b-cldfsw) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/type_errors.go#L19)):*
> ```Go
> package types
> 
> type typeError struct {
> ```

Not sure why you need a special struct to specify errors. Why not `error`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-:-KQIlpM4sHKKLUaIjGur:b-vf4rqj)*

**Comment by akhiltak** [comment]
Done.

---

Review status: all files reviewed at latest revision, 39 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 177 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQBJvlqPKm08plK2HOO-r5-177:-KQJWUetrpLQozWECA6J:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c801bbcc7112295e6c87a7687c93db0c3823bd07/query/query.go#L177)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
</details>
Done.

---

*[query/query_test.go, line 595 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQBJvlrv8SLXA4-aCf9-r5-595:-KQJWi1Fi3G_n0vNDyo8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c801bbcc7112295e6c87a7687c93db0c3823bd07/query/query_test.go#L595)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> don't use underscores in Go names; var actor_map should be actorMap
</details>
Done.

---

*[types/definitions.go, line 26 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KPkukdWB9HNrZlYnG_O-r1-26:-KQJX_XYY9w2e2YgAa0L:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/69cde8627e5c7c5e5b4a70ad32f17fb82aa35333/types/definitions.go#L26)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported type GraphQLScalar should be of the form "GraphQLScalar ..." (with optional leading article)
</details>
Done.

---

*[types/definitions.go, line 25 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KPkukdWB9HNrZlYnG_O-r4-25:-KQJXxuPumOsN7ZOm2FZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc6c7ece5900ca567728b300252967e096388dfc/types/definitions.go#L25)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported type GraphQLScalar should be of the form "GraphQLScalar ..." (with optional leading article)
</details>
Done.

---

*[types/definitions.go, line 31 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkVkXKpUcNeADFhsn:-KQJY_2-E_9fTXPTJQt_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Keep the definition of ScalarConfig close to where it's being called first. In this case, here.
</details>
Done.

---

*[types/definitions.go, line 36 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIk-y_AdYFCUXMkTzl:-KQJi9HgdKtY4q86aR-R:b-9wedg7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L36)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Avoid using interfaces so heavily. Also, do we need to serialize? All input to Dgraph is in string format, via RDF.
</details>
Using interfaces here since we don't know the input/return variable type beforehand. It could be [string -> int] or [float -> int] in case of int coercion or [string -> bool] in case of bool and so on.

For input type, interface type is used to make sure we can use same func for varying input types, for e.g., we use this for type coercion in result string (which could in future be []byte if we are directly inferencing typed values from Result []byte in subGraph.

As for name 'serialize', poor naming on my part, thinking that we could use similar struct and names for complex object types in future (for e.g., we might need to serialize a person type object or a film type object). But it's superfluous here, so changing the name matching it's use here, i.e., type coercion)

As a sidenote, what do you suggest, keep this function as a part of ScalarType definition or move it out as a standalone func (that would mean we could keep stricter input/result types instead of interface{})? 

But then, that would mean we don't have a single method name to call when parsing values of type GraphQLScalar{}. So, I would like to keep this as part of GraphQLScalar{}.

---

*[types/definitions.go, line 39 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkIXc8Wih5thdX-oK:-KQK5f2lzXVv2VvVLyOF:bth4xif) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> The input here is most likely a `[]byte`.
</details>
Agreed. But that's after we do type inference while doing mutations. Removing this for now as it's not used, will move it back with stricter types in input/result.

---

*[types/definitions.go, line 42 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkN4voNMRvOdjMeX3:-KQK6KAsrfPX9jSKrVbu:b-2vmbw9) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Not sure about the difference between this function and the above function.
</details>
redundant for now. Removed.

---

*[types/definitions.go, line 48 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkdlpEOAydzdEay3w:-KQK6TN8qrkMnqnWLmhV:b5e80n7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> GraphQLScalar above already contains Name and Description. Why repeat yourself here? Also, do you really need a separate struct for `Serialize`?
</details>
Created this config struct so that while creating an instance of this type, we can do any book-keeping steps like checking for name validity and presence of serialize func. Facilitating that by calling func MakeScalarType() instead of directly creating an instance of GraphQLScalar{}.

ScalarConfig{} gives a cleaner way to take multiple input variables in one struct. But I agree, there is a repetition since I am storing config again in GraphQLScalar{}. I think I could one of these things:
1. Remove name, desc from GraphQLScalar{} and keep them in ScalarConfig
2. Not store ScalarConfig into GraphQLScalar{} and just store 'serialize' func (now, name changed to 'Parse'  func) into GraphQLScalar{}.

Or could there be a better way still? That would be awesome!

---

*[types/definitions.go, line 63 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIjkICSws2qKVcD8yF:-KQKA7mjgtTptrcMkp7W:b5vjpyh) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Custom types seem like they could have waited for the basic implementation of scalars to be up and running first.
</details>
Had custom types here (even for basic types like int, bool, etc.) to account for some differences in how strconv parses values in golang and what GraphQL spec requires. For e.g., 
1.  In 64 bit systems, 'int' automatically is of type int64 but GraphQL spec says it should be int32 so that our backend implementation serves all architectures.
2.  For 'bool' type, even integers should be allowed to be type-casted.
[GraphQL spec ref.](http://facebook.github.io/graphql/#sec-Boolean)

Having support for custom type means we can quickly add more types.

---

*[types/definitions.go, line 127 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIkvl6fzFkUdDapkib:-KQKC3Qm32ROLExWbkjA:b-dppmp2) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L127)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Can't Type be defined as a string?
</details>
Not if we want to infer the type object directly from Fields. If we define 'type' as string, we'll have to define a map which maps 'string' values to respective types they denote in the type system.
What I plan to do here is have a wrapper type for all object types in type system and use that here instead of a interface{}. Will that be better?

---

*[types/definitions.go, line 128 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIl-DVMjtYKAEuH3FC:-KQKLn2Sfmo1y7mguF1u:bv6pktf) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/definitions.go#L128)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> There is a lot of indirection here. ResolveFunc has ResolveParams, which basically contain a string.
> 
> Looking at this code, it occurs to me that if you had defined 5 resolve functions, one for each scalar type, and just stick in there along with a schema mentioning predicate -> type, that would be all you need to achieve this functionality. Given a predicate, you find the type, then given this type, find the resolve function, and try to parse the `[]byte` into the right interface{} for JSON. For PB, you extend it with int, float, bool etc. and set the right object value.
</details>
Hm, that's a very accurate observation. Indeed, that's what the basic implementation I tried to do but I tried to make it more generic as well so that when we implement complex object types in future, we can use the same skeleton for that.
One thing though, from what I understand, the resolve function here is not what one might think. According to GraphQL spec, it's not the type resolution func but the result generating func for a particular subject->predicate pair (please take a look at Refs below). 

So, if I interpret this correctly, the flow you mentioned will be executed using Parse/serialize function for Scalars.

As for resolve func:
1. For e.g., given a user type in query and and id=1 (as arguement), resolve func is the one responsible for returning the user with id=1 from database.
2. That would mean it's the func for us that returns posting lists given a subject-predicate pair (that we currently do in ProcessTaskOverNetwork() func).
3. It just has string for now, but created this as a struct because for objects (in future), it will have 'arguement' and 'context' to fetch query result from database (IF we decide to impl it at all).
4. That's the reason you will find that resolveFunc is currently not being used.

Ref:
1. [GraphQL in 30 mins](), could just take a look at first 10 minutes or so.
2. [GraphQL spec](http://facebook.github.io/graphql/#sec-Field-entries)

---

*[types/object_type.go, line 20 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KPkukdWB9HNrZlYnG_P-r1-20:-KQKDmJOswP2XlCtw1Rt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/69cde8627e5c7c5e5b4a70ad32f17fb82aa35333/types/object_type.go#L20)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should omit type GraphQLObject from declaration of var User; it will be inferred from the right-hand side
</details>
Done.

---

*[types/schema.go, line 34 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIj8ECy0wSMIaldVFT:-KQKUl5Y85WehenbMknl:b-z6ssru) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/schema.go#L34)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I'm trying to understand this schema. Why is it defined in code? Shouldn't there be a schema file as we'd discussed?​
</details>
Yes, that I wanted to discuss with you, about the best way to implement it in Go. If we have a schema file which defines objects like this:

  type Human : Character {
    id: String!
    name: String
    friends: [Character]
    appearsIn: [Episode]
    homePlanet: String
  }

I was thinking we could write a file parser to generate schema from this (as it is in code right now).
Or would there be a better way? (maybe implement something like a lexer/parser, but that would make it unnecessary complicated)

---

*[types/schema.go, line 40 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIjJSAGVMN62T2cPUl:-KQKXFg5jN2m33cH6Ocg:b4mk3je) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/schema.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> What's this function for?
</details>
As explained in a previous comment, this is for query resolution. Currently not used since we are getting posting lists from ProcessTaskOverNetwork()

---

*[types/type_errors.go, line 19 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQIjP5m1v6dbuIiura_:-KQKYKKag9xS52j5lotP:bx5n6ls) ([raw file](https://github.com/dgraph-io/dgraph/blob/d65f179e42cee0e9fae8035ea17ae1cd88450c65/types/type_errors.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Not sure why you need a special struct to specify errors. Why not `error`?
</details>
Thanks for pointing it out. Wrote this method in my first week when I didn't had complete understanding of golang error framework and how we are using it here.
Thought that we might need to send some meta-data along with errors for better debugging, so added this wrapper. I am a fan of detailed error messages to pin point exactly what went wrong and where but golang 'error' package takes care of that nicely.
Removing it and directly using it instead. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-:-KQJW5HfJKoUfVdK6YnB:b-896fix)*

**Comment by akhiltak** [comment]
Review status: 2 of 9 files reviewed at latest revision, 40 unresolved discussions.

---

*[types/scalar_types.go, line 29 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KPkukdWB9HNrZlYnG_Q-r5-29:-KQLdHRYYhS5Bwg-Flvd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c801bbcc7112295e6c87a7687c93db0c3823bd07/types/scalar_types.go#L29)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported function CoerceInt should be of the form "CoerceInt ..."
</details>
Done.

---

*[types/scalar_types.go, line 30 \[r8\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KPkukdWB9HNrZlYnG_Q-r8-30:-KQLdJBLF_0OIalr0Y_O:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4ed6c520a2dbef94efcc50dba125041fd11b4e3/types/scalar_types.go#L30)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported var Int should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/172)*

**Comment by akhiltak** [comment]
*[cmd/dgraph/main.go, line 351 \[r8\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/172#-KQMZy7goAMpHDlJ4mew:-KQMZy7goAMpHDlJ4mex:b-7sbqjl) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4ed6c520a2dbef94efcc50dba125041fd11b4e3/cmd/dgraph/main.go#L351)):*
> ```Go
> 	}
> }
> ```

will move this init() out to types package

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/172)*

**Comment by akhiltak** [comment]
Closing this PR as this is polluted with too many comments (some of which have become obsolete because of code changes, but comments are in good detail if reference is needed).
New PR link:

**Pull request closed without merging**
