### PR TITLE
Support count with var. Resolves #1011

### LINKED ISSUE #1011: A valid query with `count` and `var` returns "Invalid mention of brackets"
version: 0.7.7

---

*Reproduction*

1. Run the following valid query

```
{
  user as var(id: u3)

  me(id: p1) {
    Upvote {
       u as Author @filter(var(user))
    }
      
    UserUpvoteCount: count(var(u))
  }
}
```

It fails and returns an error `Invalid mention of brackets`

The following query runs:

```
{
  user as var(id: u3)

  me(id: p1) {
    Upvote {
       Author @filter(var(user))
    }
  }
}
```

### PR DESCRIPTION
**Pull request by ashwin95r**
Resolves #1011

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1019)

### CODE REVIEW

**Comment by pawanrawal** [comment]
There are a bunch of Println which you can remove

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[gql/parser.go, line 2263 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-Klx035_TGW40V1yPh0Q:-Klx035aePtdoIlmCW_2:b-yueq5s) ([raw file](https://github.com/dgraph-io/dgraph/blob/5160cddcccae3a856aad1a9696423dfe65d19d2d/gql/parser.go#L2263)):*
> ```Go
> 					child.IsCount = true
> 					// We dont have to process anything for this.
> 					child.IsInternal = true
> ```

This is already set above.

---

*[gql/parser.go, line 2264 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-KlwzqIua5U2N-rqSYQh:-KlwzqIua5U2N-rqSYQi:b-lyzix4) ([raw file](https://github.com/dgraph-io/dgraph/blob/5160cddcccae3a856aad1a9696423dfe65d19d2d/gql/parser.go#L2264)):*
> ```Go
> 					// We dont have to process anything for this.
> 					child.IsInternal = true
> 					it.Next()
> ```

Check its valid?

---

*[query/query.go, line 147 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-Klx1p2fjuKKyCCyI0gl:-Klx1p2fjuKKyCCyI0gm:b7ppoh4) ([raw file](https://github.com/dgraph-io/dgraph/blob/5160cddcccae3a856aad1a9696423dfe65d19d2d/query/query.go#L147)):*
> ```Go
> 	groupbyAttrs []gql.AttrLang
> 	uidCount     string
> 	varVal       varValue
> ```

Add a comment about what this represents

---

*[query/query.go, line 292 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-KlwyBVHz-XfK5dqBCgC:-KlwyBVHz-XfK5dqBCgD:b-z236cx) ([raw file](https://github.com/dgraph-io/dgraph/blob/5160cddcccae3a856aad1a9696423dfe65d19d2d/query/query.go#L292)):*
> ```Go
> func (sg *SubGraph) getVarCount() int {
> 	fmt.Println(sg.Params.varVal)
> 	if sg.Params.varVal.strList != nil {
> ```

When would this be triggered?

---

*[query/query.go, line 332 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-Klwy7RyTS4KvIIJVT3q:-Klwy7RyTS4KvIIJVT3r:b-16hqvz) ([raw file](https://github.com/dgraph-io/dgraph/blob/5160cddcccae3a856aad1a9696423dfe65d19d2d/query/query.go#L332)):*
> ```Go
> 			}
> 			if pc.Params.DoCount {
> 				fieldName := fmt.Sprintf("count(var(%v))", pc.Params.NeedsVar[0].Name)
> ```

Check alias too. Add a test with alias.

---

*[query/query.go, line 1190 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-Klwz8FSEJBb0L1OaznG:-Klwz8FSEJBb0L1OaznH:bphwuff) ([raw file](https://github.com/dgraph-io/dgraph/blob/c49a7bbe59ce89e07f04edb9a137706682b809e2/query/query.go#L1190)):*
> ```Go
> 		srcVar := sg.Params.NeedsVar[0]
> 		srcMap := doneVars[srcVar.Name]
> 		if srcMap.vals == nil {
> ```

Why was this there? Doesn't removing it break something? If you move the new if to the top you can keep this.

---

*[query/query.go, line 1217 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-KlwyHEgNh72E3ShmuiO:-KlwyHEgNh72E3ShmuiP:bl0rfeg) ([raw file](https://github.com/dgraph-io/dgraph/blob/5160cddcccae3a856aad1a9696423dfe65d19d2d/query/query.go#L1217)):*
> ```Go
> 
> 	if len(sg.Params.NeedsVar) == 1 {
> 		sg.Params.varVal = doneVars[sg.Params.NeedsVar[0].Name]
> ```

If not found then used before defined, should we Error? Or is that already taken care of?

Also this needs to be set only when count is requested? I think you could move this to the top of the function. If count is requested then set this variable and return. Would also save all the other unnecessary processing.

---

*[query/query_test.go, line 860 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-Klx0k3S3EqLdATaYsgQ:-Klx0k3S3EqLdATaYsgR:brfwxun) ([raw file](https://github.com/dgraph-io/dgraph/blob/5160cddcccae3a856aad1a9696423dfe65d19d2d/query/query_test.go#L860)):*
> ```Go
> }
> 
> func TestQueryCountVarUids(t *testing.T) {
> ```

Maybe you want to add a new test instead of modifying an old one?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-:-Klx-Jndhy5pttboF4_H:bpj3a92)*

**Comment by pawanrawal** [comment]
The logic seems to be wrong. Try an example with multiple roots to see
```
{
			me(func: anyofterms(name, "Michonne Rick")) {
				f as friend
				count(var(f))
			}
		}

```

Our variables have global information though what we are looking here is local to where we started from. I think you need to aggregate the result in a matrix while walking down sibling tree and then you can put the final results in `counts` and then you don't  need the varVal.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1019#-:-KlzZqtEQ4uIIsRPODkt:b-kydyif)*

**Comment by manishrjain** [comment]
What's the status of this PR?

**Comment by ashwin95r** [comment]
Closing this. Handling the issue in #1127.

**Pull request closed without merging**
