### PR TITLE
Terraform script for running Dgraph on AWS

### PR DESCRIPTION
**Pull request by hackintoshrao**
- Terraform script for single node deployment.
- Added instructions in Readme.md.
- Tf.variable with the default configuration added.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3202)

### CODE REVIEW

**Review by srfrog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3202)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hackintoshrao)

___
*[contrib/config/terraform/aws/standalone/main.tf, line 14 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/3202#-Lape6XW7YcmjzWfM42S:-Lape6XW7YcmjzWfM42T:b-nwxgn7) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd95321e0a776e065c775664ee957dc2639b32c0/contrib/config/terraform/aws/standalone/main.tf#L14)):*
> ```HCL
> 
>   # This EC2 Instance has a public IP and will be accessible directly from the public Internet
>   associate_public_ip_address = true
> ```

IMO this shouldn't be public. Accessing Dgraph instances should be left to the user using their VPC configuration.

**Comment by hackintoshrao** [comment]
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3202)_ status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hackintoshrao)
> 
> _[contrib/config/terraform/aws/standalone/main.tf, line 14 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/3202#-Lape6XW7YcmjzWfM42S:-Lape6XW7YcmjzWfM42T:b-nwxgn7) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd95321e0a776e065c775664ee957dc2639b32c0/contrib/config/terraform/aws/standalone/main.tf#L14)):_
> 
> > ```terraform
> >   # This EC2 Instance has a public IP and will be accessible directly from the public Internet
> >   associate_public_ip_address = true
> > ```
> 
> IMO this shouldn't be public. Accessing Dgraph instances should be left to the user using their VPC configuration.

Sure, I'll leave the default to false.

**Review by manishrjain — APPROVED** [review]
:lgtm: Feel free to merge. Would be good if @danielmai can try this out.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3202#-:-LbzeSzH8bjW9nUVhbj6:b-45nyah)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @hackintoshrao)

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3202)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @hackintoshrao and @srfrog)

___
*[contrib/config/terraform/aws/standalone/main.tf, line 14 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/3202#-Lape6XW7YcmjzWfM42S:-Lbzlvj88u1dGObdF8jm:b-pbdqz3) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd95321e0a776e065c775664ee957dc2639b32c0/contrib/config/terraform/aws/standalone/main.tf#L14)):*
<details><summary><i>Previously, srfrog (Gus) wrote…</i></summary><blockquote>

IMO this shouldn't be public. Accessing Dgraph instances should be left to the user using their VPC configuration.
</blockquote></details>

Agreed.
___
*[contrib/config/terraform/aws/standalone/variables.tf, line 52 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/3202#-LbzlrTy4uNmzFlDQZvZ:-LbzlrTy4uNmzFlDQZv_:b-m9x1t1) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd95321e0a776e065c775664ee957dc2639b32c0/contrib/config/terraform/aws/standalone/variables.tf#L52)):*
> ```HCL
> variable "dgraph_ui_port" {
>     description = "Port number of ratel interface"
>     default="8000"
> ```

The security groups opened up port 8000, but both 8000 and 8080 need to be exposed to really use Dgraph.
___
*[contrib/config/terraform/aws/standalone/creds/aws_secrets, line 3 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/3202#-LbzlcThC-Q27qXdRhZr:-LbzlcTi89RVrNt3GeC8:bw6w6l7) ([raw file](https://github.com/dgraph-io/dgraph/blob/bd95321e0a776e065c775664ee957dc2639b32c0/contrib/config/terraform/aws/standalone/creds/aws_secrets#L3)):*
> ```
> [terraform]
> aws_access_key_id = XXXXXXXXXXXXXXXXXX
> aws_secret_access_key = XXXXXXXXXXXXXX
> ```

We should add this format template to the README and move this file out. Else I might accidentally commit a config with secret keys to the repo. We can keep the empty creds directory checked in with a .gitkeep file.

**Comment by lolcoolkat** [comment]
I'd be interested in building a Terraform example for GKE! @hackintoshrao Nice job on your example!

**Comment by joshua-goldstein** [comment]
We will close this PR because of its age, however we will be referencing this PR when we start work on CD steps.  There is a lot of cleanup currently happening around CI steps, and when we get to CD we will address Terraform, Helm, and Docker.

**Pull request closed without merging**
