### PR TITLE
Changing type of Value

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/86)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/list.go, line 206 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/86#-KHx6lLU9A-_7ADzTfRr:-KHx6lLU9A-_7ADzTfRs:-656236103) ([raw file](https://github.com/dgraph-io/dgraph/blob/67338b853c51d04d727809b2fa99c31b2ac4276b/posting/list.go#L206)):*
> ```Go
> }
> 
> func ParseValue(value []byte) ([]byte, error) {
> ```

You don't really need this function. The small value[0] = 0x00 check is probably not required either -- maybe we can just stop setting the value to 0x00, now that we no longer do json encoding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/86)*

**Comment by manishrjain** [comment]
Reviewed 2 of 8 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/86)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/list.go, line 206 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/86#-KHx6lLU9A-_7ADzTfRr:-KHx8FzheyVu8jXj_tt8:135414774) ([raw file](https://github.com/dgraph-io/dgraph/blob/67338b853c51d04d727809b2fa99c31b2ac4276b/posting/list.go#L206)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You don't really need this function. The small value[0] = 0x00 check is probably not required either -- maybe we can just stop setting the value to 0x00, now that we no longer do json encoding.</details>
I was wondering if we need it anymore. Where do we set the 0x00 value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/86)*

**Comment by pawanrawal** [comment]
Review status: 2 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query_test.go, line 273 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/86#-KHxamA2u6lv60s3r-7N:-KHxamA2u6lv60s3r-7O:-2014841240) ([raw file](https://github.com/dgraph-io/dgraph/blob/726eb2119ddc7852db1d00b8025857af1585270e/query/query_test.go#L273)):*
> ```Go
> 			t.Error("Unable to retrieve value")
> 		}
> 		if !bytes.Equal(tv.ValBytes(), []byte{}) {
> ```

This is the failing test which I changed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/86)*

**Comment by manishrjain** [comment]
:lgtm: Please merge only after squashing your commits, and then merge using commandline.

<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> #### Changing type of Value
> 
> 
> 
> 
> </details>


---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query_test.go, line 273 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/86#-KHxamA2u6lv60s3r-7N:-KHxg_gYLYfvwU1RhpHK:5173665) ([raw file](https://github.com/dgraph-io/dgraph/blob/726eb2119ddc7852db1d00b8025857af1585270e/query/query_test.go#L273)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This is the failing test which I changed now.</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/86#-:-KHxgfyG1UxBAMdj7jf0:1167202436)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
