### PR TITLE
Mlayer/skiplist

### PR DESCRIPTION
**Pull request by ashwin95r**
Initial PR to see skiplist performance in mlayer

```
Current:
$ go test --bench AddMut
BenchmarkAddMutations-4   	  200000	      7683 ns/op

After change (with skiplist):
$ go test --bench AddMut
BenchmarkAddMutations-4   	  500000	      5082 ns/op
```
Using skiplist is ~33% faster. I'll try to benchmark this for more scenarios and update here.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1214)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[posting/list.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQzM_b0JanpMT_8u7a:-KpQzM_b0JanpMT_8u7b:b-vlmidm) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L35)):*
> ryszard/goskiplist

Badger has a skiplist. Can't you use that? We've already optimized it.

---

*[posting/list.go, line 73 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQyDSNkwRCzAwwoHM2:-KpQyDSNkwRCzAwwoHM3:b-26ny7o) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L73)):*
> ```Go
> 	ghash         uint64
> 	plist         *protos.PostingList
> 	mlayer        *skiplist.SkipList //[]*protos.Posting // mutations
> ```

If you're modifying things, you don't need to keep the old code

---

*[posting/list.go, line 74 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQy2SfTR-mp-gI4kPS:-KpQy2SfTR-mp-gI4kPT:b-z6y7yz) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L74)):*
> ```Go
> 	plist         *protos.PostingList
> 	mlayer        *skiplist.SkipList //[]*protos.Posting // mutations
> 	len           int
> ```

len is a reserved keyword for an internal function.

---

*[posting/list.go, line 368 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQzfHa0jz_DKbfQjjq:-KpQzfHa0jz_DKbfQjjr:b9g3uac) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L368)):*
> ```Go
> 			if mpost.Op == Del {
> 				// Undo old post.
> 				l.len--
> ```

Is it expensive to get length from the skiplist? If so, we can modify the skiplist (ours) to keep track of length.

---

*[posting/list.go, line 376 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQzt2fOwMcmlcdpDpY:-KpQzt2fOwMcmlcdpDpZ:b-mrgmf3) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L376)):*
> ```Go
> 		} else if oldPost.Op == Del {
> 			if mpost.Op == Set {
> 				l.len++
> ```

What? Why?

---

*[posting/list.go, line 409 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpR-1dQTzPbQlqbPY3o:-KpR-1dQTzPbQlqbPY3p:b-xa8qu1) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L409)):*
> ```Go
> 	} else {
> 		if psame { // mpost.Op==Del
> 			l.len--
> ```

I'm not liking this length tracking at all. Let's switch the skiplist impl, and get rid of this len stuff.

---

*[posting/list.go, line 628 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpR-KHmGvwpvUozr24E:-KpR-KHmGvwpvUozr24F:b3y9ovh) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L628)):*
> ```Go
> }
> 
> func (l *List) lengthEst() int {
> ```

Why is this an estimate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214)*

**Comment by manishrjain** [comment]
This would also impact the memory usage significantly. Can you benchmark memory allocations as well?

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-:-KpR3J8BfxpHXL5DWafD:b-1d7hyp)*

**Comment by ashwin95r** [comment]
```
With skiplist:
$ go test --benchmem --bench AddMut 
BenchmarkAddMutations-4   	  200000	      5125 ns/op	     765 B/op	       6 allocs/op

With slice:
$ go test --benchmem --bench AddMut 
BenchmarkAddMutations-4   	  300000	     20577 ns/op	     378 B/op	       3 allocs/op
```
Memory usage is ~2x

---

Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions.

---

*[posting/list.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQzM_b0JanpMT_8u7a:-KpSnMRoy9XkPgIOc3IT:bsq8mgn) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

> ryszard/goskiplist

Badger has a skiplist. Can't you use that? We've already optimized it.
</blockquote></details>

I had a look but that library was too specific to Badger, so I used this library for a quick check as the API was simple.

---

*[posting/list.go, line 73 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQyDSNkwRCzAwwoHM2:-KpSnw7i2U85rDs9jLFH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L73)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If you're modifying things, you don't need to keep the old code
</blockquote></details>

Done.

---

*[posting/list.go, line 368 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQzfHa0jz_DKbfQjjq:-KpSnxlMX-RfpUqySwgB:bcb9ewn) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L368)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Is it expensive to get length from the skiplist? If so, we can modify the skiplist (ours) to keep track of length.
</blockquote></details>

It's not the length of the skiplist but the length of the posting list (the mlayer has `add` and `del` ops which affect the lenght). We iterate through the mlayer to see how many add/del posting which is unnecessary. We can track it when an update happens which is this `len`.

---

*[posting/list.go, line 376 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQzt2fOwMcmlcdpDpY:-KpSoUHbvuR4qYHD_mG_:b-5j33lq) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L376)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What? Why?
</blockquote></details>

As mentioned, this is to track the total length based on the ops.

---

*[posting/list.go, line 409 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpR-1dQTzPbQlqbPY3o:-KpSoa_Exliul_rSsgH6:bvpy8hu) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L409)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I'm not liking this length tracking at all. Let's switch the skiplist impl, and get rid of this len stuff.
</blockquote></details>

The skiplist already has a `Len()` but we need to know the contents (hence iterate) to calculate our length. So, this can't be passed on to the skiplist lib.

---

*[posting/list.go, line 628 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpR-KHmGvwpvUozr24E:-KpSot4Ca6PaxWB51ae7:b-au889z) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L628)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why is this an estimate?
</blockquote></details>

Since we don't look at the actual ops in mlayer, this is approximate. At some places, this approximate length is good enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-:-KpSn2LSX7onnElR9xl-:b-9e8spo)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[posting/list.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQzM_b0JanpMT_8u7a:-KpTCCdgZ_DEcxUHGXv6:b-ym5nmp) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L35)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I had a look but that library was too specific to Badger, so I used this library for a quick check as the API was simple.
</blockquote></details>

Also badger skl doesn't have `Delete()` Api

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[posting/list.go, line 74 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214#-KpQy2SfTR-mp-gI4kPS:-KpTDkN_7sMhBnRl1UZq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ef0d88edba2f81f2b397b8a4fc36d4bfbf08548/posting/list.go#L74)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

len is a reserved keyword for an internal function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1214)*

**Comment by ashwin95r** [comment]
Since we're going to shard the PLs and flush them if the size of the mutation layer reaches a threshold, skiplists won't be of much benefit (as it only outperforms insertions on larger lists). So closing this PR.

**Pull request closed without merging**
