### PR TITLE
Basic ordering using vars

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/705)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[gql/parser.go, line 926 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKzkAkLO_wtbdr23Pu:-KfKzkAkLO_wtbdr23Pv:b-jgof0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/gql/parser.go#L926)):*
> ```Go
> 		item = it.Item()
> 		var val string
> 		if item.Val == "var" {
> ```

Have common code to parse var. Don't enforce the number of args here.

---

*[gql/parser.go, line 1495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKzx-dG-EZeiQKOF7f:-KfKzx-ecc8hFN8mgMWe:bj8bld6) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/gql/parser.go#L1495)):*
> ```Go
> 			}
> 			item = it.Item()
> 			if item.Val == "var" {
> ```

same as above.

---

*[gql/parser.go, line 1532 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKzyr1x8URYZoYgrUY:-KfKzyr1x8URYZoYgrUZ:b-yq3bu8) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/gql/parser.go#L1532)):*
> ```Go
> 			}
> 			item := it.Item()
> 			if item.Val == "var" {
> ```

and here.

---

*[query/query.go, line 135 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKwcIVLJ5ZmMh1RXPw:-KfKwcIVLJ5ZmMh1RXPx:bq5hcu3) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/query/query.go#L135)):*
> ```Go
> 	NeedsVar     []string
> 	ParentVars   map[string]*taskp.List
> 	varValMap    map[uint64]types.Val
> ```

uidToVal

---

*[query/query.go, line 759 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKxgzkG9gJOu5l8CDI:-KfKxgzkG9gJOu5l8CDJ:b-2we4tx) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/query/query.go#L759)):*
> ```Go
> 
> 	// doneVars will store the UID list of the corresponding variables.
> 	doneVars := make(map[string]*taskp.List)
> ```

struct which wraps taskp.List and this val map.

---

*[query/query_test.go, line 431 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKvE5fXyvzFMCKGamx:-KfKvE5fXyvzFMCKGamy:bjndxwb) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/query/query_test.go#L431)):*
> ```Go
> 			}
> 
> 			me(id: var([L, B])) {
> ```

Maybe make it `id: var(L, B)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/705)*

**Comment by ashwin95r** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 926 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKzkAkLO_wtbdr23Pu:-KfOgMVwkaMvn5xBwaTV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/gql/parser.go#L926)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Have common code to parse var. Don't enforce the number of args here.
</blockquote></details>

Done.

---

*[gql/parser.go, line 1495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKzx-dG-EZeiQKOF7f:-KfOgM-sMylZZqncG-8m:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/gql/parser.go#L1495)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.

---

*[gql/parser.go, line 1532 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKzyr1x8URYZoYgrUY:-KfOgLmSFeB-FNN4os8R:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/gql/parser.go#L1532)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

and here.
</blockquote></details>

Done.

---

*[query/query.go, line 135 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKwcIVLJ5ZmMh1RXPw:-KfOgL1mieueKj_3mQ6W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/query/query.go#L135)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

uidToVal
</blockquote></details>

Done.

---

*[query/query.go, line 759 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKxgzkG9gJOu5l8CDI:-KfOrQwM1DNCzLsZemUh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/query/query.go#L759)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

struct which wraps taskp.List and this val map.
</blockquote></details>

Done.

---

*[query/query_test.go, line 431 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-KfKvE5fXyvzFMCKGamx:-KfOgR89CqQ54spBN0_M:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2eb7998474eff2c18d62f7541d54bc9b19d47f0f/query/query_test.go#L431)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe make it `id: var(L, B)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/705)*

**Comment by davcdhanesh1** [comment]
Just a quick question. I have recently learnt about usage of
'id(<var-name>)' in queries. Looking at the tests that you have for this
PR, var(<var-name>) feels the same. Or may be I was wrong but I used id()
to achieve the same effect.

So what's exactly the difference ? And when should one prefer one over
another ?

**Comment by ashwin95r** [comment]
@davcdhanesh1 We're replacing `id()` with `var()` as it adds clarity and consistency to the new functionality we're building. So var() would take the place of id() plus some more extra things.

**Comment by davcdhanesh1** [comment]
@Ashwin, Okay. That makes sense. Sorry but can you tell me about the new
functionality and some extra things that you are talking about. You can
direct me to some older relevant discussions, that's fine for me ?

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-:-KfPMycfg6aRidp7OKMs:bnfp4nl)*

**Comment by gacharya255** [comment]
:lgtm:

(I wonder if these vars handling etc can be figured out by a smart query preprocessor such that our backend logic remains as simple as possible.)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-:-KfPOYQO0KdJVFPDcBvY:bxzz4g2)*

**Comment by ashwin95r** [comment]
Yeah, I've tried to keep it as much as possible in the parser, but it may not be completely possible without knowing if it's a  value predicate or an entity. Maybe yeah, we can add something based on the schema (checking types). I'll track it via a task.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/705#-:-KfPQpVKIjvnJYLeV1DO:b-oeujcm)*

**Comment by ashwin95r** [comment]
@davcdhanesh1 We want to support queries like 
```
# To get my friends sorted by popularity (sum of friends and followers)
{
 var(me: alice) {
  f as friend {
   a as count(friend)
   b as count(follower)
  }
  c as sum(a, b)
 } 

 popularFriends(id: var(f), orderdesc: var(c)) {
  name
 }
}
```
This is a move in that direction.

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
