### PR TITLE
Distributed server

### PR DESCRIPTION
**Pull request by ashwin95r**
[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/40)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[:q, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBQ2QzOEIwrLewgyXiE:-KBQ2QzOEIwrLewgyXiF:-1361912334) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bc03c2c12593a8f4f4c44e4d3dc106d8b537237/:q#L1)):*
Really? This file?

---

*[worker/worker.go, line 101 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBQ3AXmy2A71mbPdajc:-KBQ3AXmy2A71mbPdajd:-1821568769) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bc03c2c12593a8f4f4c44e4d3dc106d8b537237/worker/worker.go#L101)):*
Don't put the logic here, put it in the wrapper above.

---

*[worker/worker.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBQ3DWo4T1DQzEs0pLy:-KBQ3DWo4T1DQzEs0pLz:-442254187) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bc03c2c12593a8f4f4c44e4d3dc106d8b537237/worker/worker.go#L174)):*
This should check if the query Attr belongs to this worker or not. If not, it should return error. It shouldn't forward it to another worker.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[:q, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBQ2QzOEIwrLewgyXiE:-KBRIQlF1KCauaWjBP5H:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bc03c2c12593a8f4f4c44e4d3dc106d8b537237/:q#L1)):*
Done.

---

*[worker/worker.go, line 101 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBQ3AXmy2A71mbPdajc:-KBRIRlKc-as05YqQ9Lm:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bc03c2c12593a8f4f4c44e4d3dc106d8b537237/worker/worker.go#L101)):*
Done.

---

*[worker/worker.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBQ3DWo4T1DQzEs0pLy:-KBRIQ4VsqnblQBtKqFK:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bc03c2c12593a8f4f4c44e4d3dc106d8b537237/worker/worker.go#L174)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by ashwin95r** [comment]
Handling xid and uid separately has to be taken care of yet. Should I just check that in ProcessTakOverNetwork function?

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-:-KBRJwEqklg2OjY0IOBV:-711761933)*

**Comment by manishrjain** [comment]
As we discussed y'day, just put both of them on the same instance, instance zero.

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-:-KBRKFIzrjjQSpwFM2Bl:519816187)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/worker.go, line 75 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBRNO1oTLPI-DUxDnCk:-KBRNO1oTLPI-DUxDnCl:1058698191) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L75)):*
Should I put this piece of else in a function called SendRequset(query, idx) ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by manishrjain** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/main.go, line 159 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVgC9w89bZ9DPVjEt2:-KBVgC9w89bZ9DPVjEt3:360805445) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/server/main.go#L159)):*
Did you compile this? `len` is a function

---

*[worker/worker.go, line 25 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVg1CJrzx3Y0rb7qIN:-KBVg1CJrzx3Y0rb7qIO:299124482) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L25)):*
Remove the vertical space

---

*[worker/worker.go, line 31 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVgaDVMB1qie9qzIcq:-KBVgaDVMB1qie9qzIcr:-1886824612) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L31)):*
You don't need to store addrs.

---

*[worker/worker.go, line 36 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVgXjnDijHxoj2_bMt:-KBVgXjnDijHxoj2_bMu:-807709) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L36)):*
Pass the workerList here, not above. Also check that the list has same number of elements as numInstances.

---

*[worker/worker.go, line 72 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVh6OhhmaX8S6rtAWs:-KBVh6OhhmaX8S6rtAWt:-34279842) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L72)):*
You could do it like this:

runHere := false
if attr == "_xid_" || attr == "_uid_" {
  runHere = instanceIdx == 0
} else {
  runHere = instanceIdx == idx
}

if runHere {
  return ProcessTask(qu)
}
// rest of the logic.

---

*[worker/worker.go, line 75 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBRNO1oTLPI-DUxDnCk:-KBVgtGAP6GCj2eCoHId:-438557245) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L75)):*
If you follow the above logic, then there shouldn't be a need.

---

*[worker/worker.go, line 92 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVh2tYRrIapYdqSvoq:-KBVh2tYRrIapYdqSvor:1430113051) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L92)):*
No else.

---

*[worker/worker.go, line 196 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVi8Pf_6rYyB22J5s_:-KBVi8PgTTM52nAIv2nU:1721508234) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L196)):*
Always add more information for log Fatal:
glog.WithField("attr", ...).WithField("idx", instanceIdx).. etc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[server/main.go, line 159 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVgC9w89bZ9DPVjEt2:-KBVyPAD5j6bpYA_uGkw:-1550854899) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/server/main.go#L159)):*
Yes it does compile. I'll change it though

---

*[worker/worker.go, line 25 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVg1CJrzx3Y0rb7qIN:-KBW0HsT1p5Ve7PvDjUL:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L25)):*
Done.

---

*[worker/worker.go, line 31 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVgaDVMB1qie9qzIcq:-KBW0Ieo4UmWiCKpmAjt:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L31)):*
Done.

---

*[worker/worker.go, line 36 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVgXjnDijHxoj2_bMt:-KBW0SYcbXozhlIFhPFg:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L36)):*
Done.

---

*[worker/worker.go, line 72 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVh6OhhmaX8S6rtAWs:-KBW-vbXFNI28w7nT8Rj:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L72)):*
Done.

---

*[worker/worker.go, line 75 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBRNO1oTLPI-DUxDnCk:-KBW-wXOgi4Rb90s7PWl:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L75)):*
Done.

---

*[worker/worker.go, line 92 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVh2tYRrIapYdqSvoq:-KBW01Pfxd8aW54ZGx0Q:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L92)):*
Done.

---

*[worker/worker.go, line 196 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVi8Pf_6rYyB22J5s_:-KBW0GguJEonftwIuhZg:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L196)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by manishrjain** [comment]
Reviewed 1 of 7 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/worker.go, line 92 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVh2tYRrIapYdqSvoq:-KBW8q80PsZhd31GFTr4:-918168453) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L92)):*
It's not done.

---

*[worker/worker.go, line 48 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBW8Yi8oz5OihQcDmxj:-KBW8Yi9_yGsTSWeW9bI:1580504668) ([raw file](https://github.com/dgraph-io/dgraph/blob/357a6599c5ece15506fa4d8f6749a2be30bcada6/worker/worker.go#L48)):*
You don't need to store addresses.

---

*[worker/worker.go, line 110 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBW99vN1p67FUlLj6sn:-KBW99vN1p67FUlLj6so:-40027740) ([raw file](https://github.com/dgraph-io/dgraph/blob/357a6599c5ece15506fa4d8f6749a2be30bcada6/worker/worker.go#L110)):*
Move this right after q.Init(..), so it's part of the `q` block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/worker.go, line 92 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBVh2tYRrIapYdqSvoq:-KBWDJtjPgVWPRWX0SOM:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9dc381ba92999050f57790668b00166f7f376a7/worker/worker.go#L92)):*
Done.

---

*[worker/worker.go, line 48 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBW8Yi8oz5OihQcDmxj:-KBWDDHgYz2VssBQlIO9:241730685) ([raw file](https://github.com/dgraph-io/dgraph/blob/357a6599c5ece15506fa4d8f6749a2be30bcada6/worker/worker.go#L48)):*
The workerList has to be passed to ProcessTaskOvernetwork otherwise

---

*[worker/worker.go, line 110 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBW99vN1p67FUlLj6sn:-KBWD6epQtmOI5NO8LSr:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/357a6599c5ece15506fa4d8f6749a2be30bcada6/worker/worker.go#L110)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by manishrjain** [comment]
Almost there.

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/worker.go, line 48 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBW8Yi8oz5OihQcDmxj:-KBWDx5eDANG5iS4Ma9l:1875421734) ([raw file](https://github.com/dgraph-io/dgraph/blob/357a6599c5ece15506fa4d8f6749a2be30bcada6/worker/worker.go#L48)):*
You only use the addr for debugging purposes. There's no real need otherwise. You can also just expose the Addr from `conn.Pool` if you want.

---

*[worker/worker.go, line 76 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBWEdgyWQHI5wK_uZUZ:-KBWEdgz4DRFBtpAcvX-:1697943158) ([raw file](https://github.com/dgraph-io/dgraph/blob/98e139a593b52c2cabb8bd16cc13213f9cb9de5e/worker/worker.go#L76)):*
Actually, better to say `var runHere bool`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-:-KBWF9nfx6xIgqoapVZQ:-810123401)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/worker.go, line 48 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBW8Yi8oz5OihQcDmxj:-KBWI0hg0J0h3dmufRWi:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/357a6599c5ece15506fa4d8f6749a2be30bcada6/worker/worker.go#L48)):*
Done.

---

*[worker/worker.go, line 76 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBWEdgyWQHI5wK_uZUZ:-KBWI1RUsK_CUKDG305x:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/98e139a593b52c2cabb8bd16cc13213f9cb9de5e/worker/worker.go#L76)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by manishrjain** [comment]
Just one last comment. Otherwise, :lgtm: 

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/worker.go, line 76 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBWEdgyWQHI5wK_uZUZ:-KBWWOeYB6N96cOgJ-Wl:651558859) ([raw file](https://github.com/dgraph-io/dgraph/blob/98e139a593b52c2cabb8bd16cc13213f9cb9de5e/worker/worker.go#L76)):*
It defaults to false. You don't need to set it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-:-KBWWTH2AK-Rb3HCZnnN:-1132543940)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/worker.go, line 76 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/40#-KBWEdgyWQHI5wK_uZUZ:-KBWXT85REUdbWl4fFyO:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/98e139a593b52c2cabb8bd16cc13213f9cb9de5e/worker/worker.go#L76)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/40)*

**Pull request merged**
