### PR TITLE
feat(GraphQL): Auth on Interfaces should work correctly while querying them.

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
Fixes GRAPHQL-660.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6781)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6781)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/auth_query_test.yaml, line 1188 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKJAfM6-DZ1KOBunkZx:-MKJAfM6-DZ1KOBunkZy:b-nkzsvd) ([raw file](https://github.com/dgraph-io/dgraph/blob/74a250d7e8fc85c59807863ddb7ae3e7ad0391ec/graphql/resolve/auth_query_test.yaml#L1188)):*
> ```YAML
>       PostRoot as var(func: uid(Post1)) @filter((uid(PostAuth2) OR (uid(FbPostRoot) OR (uid(AnswerRoot) OR uid(PostAuth3)))))
>       Post1 as var(func: type(Post))
>       PostAuth2 as var(func: uid(Post1)) @filter(eq(Question.answered, true)) @cascade {
> ```

The auth rule for a Question could be something like below. That is it should not apply auth rules of implementing interface because they have already been applied in `PostAuth3`. 

```
QuestionAuth1 as var(func: uid(QuestionRoot)) @filter(eq(Question.answered, true)) @cascade {
  id
}

QuestionRoot as QuestionRoot(func: type(Question))
```

**Review by pawanrawal — CHANGES_REQUESTED** [review]
looking great! Also add some e2e tests here.

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-:-MKhxmzN0dRbVsL3728h:bh8t5fd)* status: 1 of 7 files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/auth_query_test.yaml, line 1171 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhtXU4BgP69idgdgJk:-MKhtXU4BgP69idgdgJl:b-gpcrw9) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/auth_query_test.yaml#L1171)):*
> ```YAML
>   gqlquery: |
>     query {
>       queryPost {
> ```

Add a case where we have filtering, sorting, and pagination 

```
queryPost(filter: {text: {eq: }}, orderasc: ..., first: 10, offset: 10) 
```
___
*[graphql/resolve/auth_query_test.yaml, line 1233 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhuURs3FvkXm2KKj6a:-MKhuURs3FvkXm2KKj6b:b-462bw4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/auth_query_test.yaml#L1233)):*
> ```YAML
>       queryPost()
>     }
> - name: "Query interface should return partial types if the auth rule of interface is not satisfied"
> ```

Add a case where USER is not present in JWTVar.
___
*[graphql/resolve/query_rewriter.go, line 443 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhvhrG75XBNM7TBLeg:-MKhvhrG75XBNM7TBLeh:b-88uk82) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/query_rewriter.go#L443)):*
> ```Go
> 
> 	fldAuthQueries, filter := authRw.rewriteAuthQueries(typ)
> ```

if type.IsInterface() {
  nest all the logic here for constructing query for interface. 
}
___
*[graphql/resolve/query_rewriter.go, line 500 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhvLFp9LHks519AzYq:-MKhvLFp9LHks519AzYr:b-pq3bjf) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/query_rewriter.go#L500)):*
> ```Go
> 		// In this case the query must return all the nodes of this type.
> 		// then simply we need to Put uid(Todo1) with OR in the main query filter.
> 		if len(objAuthQueries) == 0 {
> ```

Add a test case where there are no auth rules on the interface and some implementing types have auth rules and others don't.
___
*[graphql/resolve/query_test.yaml, line 1157 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhwYLT-RDjlxCPWXik:-MKhwYLT-RDjlxCPWXil:bx98ih4) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/query_test.yaml#L1157)):*
> ```YAML
>   gqlquery: |
>     query {
>       getX(id: "0x1") {
> ```

Add some cases for get as well similar to what you have for queryInterface above.
___
*[graphql/schema/auth.go, line 187 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhweKq7kXhaKme9GZt:-MKhweKq7kXhaKme9GZu:bd6mq9u) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/schema/auth.go#L187)):*
> ```Go
> 		if typ.Kind == ast.Object {
> 			for _, intrface := range typ.Interfaces {
> 				interfaceName := typeName(s.Types[intrface])
> ```

`interface`

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6781)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/auth_query_test.yaml, line 1188 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKJAfM6-DZ1KOBunkZx:-MKieL5PA5osLH5CX4_g:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74a250d7e8fc85c59807863ddb7ae3e7ad0391ec/graphql/resolve/auth_query_test.yaml#L1188)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The auth rule for a Question could be something like below. That is it should not apply auth rules of implementing interface because they have already been applied in `PostAuth3`. 

```
QuestionAuth1 as var(func: uid(QuestionRoot)) @filter(eq(Question.answered, true)) @cascade {
  id
}

QuestionRoot as QuestionRoot(func: type(Question))
```
</blockquote></details>

Done.
___
*[graphql/resolve/auth_query_test.yaml, line 1171 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhtXU4BgP69idgdgJk:-MKidyTiERlOsVd9mmtu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/auth_query_test.yaml#L1171)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a case where we have filtering, sorting, and pagination 

```
queryPost(filter: {text: {eq: }}, orderasc: ..., first: 10, offset: 10) 
```


</blockquote></details>

Done.
___
*[graphql/resolve/auth_query_test.yaml, line 1233 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhuURs3FvkXm2KKj6a:-MKieLvm2olHo2eQCnSw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/auth_query_test.yaml#L1233)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a case where USER is not present in JWTVar.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 443 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhvhrG75XBNM7TBLeg:-MKieOhJD5y0RhZqnC2f:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/query_rewriter.go#L443)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

if type.IsInterface() {
  nest all the logic here for constructing query for interface. 
}
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 500 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhvLFp9LHks519AzYq:-MKieO0hBczJZA3lYM7P:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/resolve/query_rewriter.go#L500)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a test case where there are no auth rules on the interface and some implementing types have auth rules and others don't.
</blockquote></details>

Done.
___
*[graphql/schema/auth.go, line 187 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKhweKq7kXhaKme9GZt:-MKiePbu0ieKEU-G0igB:b-vntxru) ([raw file](https://github.com/dgraph-io/dgraph/blob/a800da2a3faf4210f9beb89bf1ec31281d80710c/graphql/schema/auth.go#L187)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`interface`
</blockquote></details>

`interface` is a reserved keyword.

**Review by pawanrawal — APPROVED** [review]
Some minor things here and then this is good to go

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-:-MKnGHSmCPS_JGNLWlfO:bg9h81)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/auth_query_test.yaml, line 1376 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnFRFCE7H0aUHH3-25:-MKnFRFCE7H0aUHH3-26:br1d4qm) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/auth_query_test.yaml#L1376)):*
> ```YAML
>   dgquery: |-
>     query {
>       getPost() @filter(type(Post))
> ```

Would be good if this filter is also cleared about and is not written to the final query.
___
*[graphql/resolve/auth_query_test.yaml, line 1378 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnFC6JAweK9Wy0oKFK:-MKnFC6K4HgbQ2rlgHJ9:b-gi4p81) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/auth_query_test.yaml#L1378)):*
> ```YAML
>       getPost() @filter(type(Post))
>     }
> - name: "Query interface having no Auth Rules but some type have Auth rules and those are satified"
> ```

... no Auth Rules should apply auth rules on implementing types that are satisfied
___
*[graphql/resolve/auth_query_test.yaml, line 1402 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnEy-xEQgZYoDijQ7y:-MKnEy-yE6oNQUJP4Apf:bjcfmvp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/auth_query_test.yaml#L1402)):*
> ```YAML
>       }
>     }
> - name: "Query interface having no Auth Rules but some type have Auth rules and those are not satified"
> ```

mention that auth rules for `type C` are not satisfied hence its excluded.
___
*[graphql/resolve/query_rewriter.go, line 324 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnFj7a4Uc90PYM25F2:-MKnFj7bDKcsYU1-W0Ls:b-3dpz4f) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/query_rewriter.go#L324)):*
> ```Go
> 	// If Get query is for interface and none of the authrules are satisfied, then it is not
> 	// caught here as after merging the interface Auth Rules into the types Interface Auth
> 	// Rules are made empty.
> ```

.... Rules for the interface are made empty. 
___
*[graphql/resolve/query_rewriter.go, line 336 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnFuNq9X6_LmG393-c:-MKnFuNq9X6_LmG393-d:b-8y5jyh) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/query_rewriter.go#L336)):*
> ```Go
> 		addTopLevelTypeFilter(dgQuery, field)
> 
> 		// For interface Get query, empty query will be like
> ```

Instead of returning here, why not just return above before adding top-level filters. So if `dgQuery.Func == nil` return and no need to add the filter in that case. 
___
*[graphql/resolve/query_test.yaml, line 1164 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnGAW617TSuDc9_OxQ:-MKnGAW617TSuDc9_OxR:btozlhp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/query_test.yaml#L1164)):*
> ```YAML
>   dgquery: |-
>     query {
>       getX() @filter(type(X))
> ```

the filter should not be rewritten

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6781)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/auth_query_test.yaml, line 1376 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnFRFCE7H0aUHH3-25:-MKnby79-3_7aNQdib07:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/auth_query_test.yaml#L1376)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Would be good if this filter is also cleared about and is not written to the final query.
</blockquote></details>

Done.
___
*[graphql/resolve/auth_query_test.yaml, line 1402 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnEy-xEQgZYoDijQ7y:-MKnbytP8o_AMcca8lD_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/auth_query_test.yaml#L1402)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

mention that auth rules for `type C` are not satisfied hence its excluded.
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 324 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnFj7a4Uc90PYM25F2:-MKnc0nADXaf6BehLL7C:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/query_rewriter.go#L324)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

.... Rules for the interface are made empty. 
</blockquote></details>

Done.
___
*[graphql/resolve/query_rewriter.go, line 336 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6781#-MKnFuNq9X6_LmG393-c:-MKnc1RdDb0XC9K9IJLt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a41ed7995fc602d6e77dce18b5c1895c642e3952/graphql/resolve/query_rewriter.go#L336)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Instead of returning here, why not just return above before adding top-level filters. So if `dgQuery.Func == nil` return and no need to add the filter in that case. 
</blockquote></details>

Done.

**Pull request merged**
