### PR TITLE
Check context more often while sorting.

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1192)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Many comments. Address them and then submit.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/sort.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koympp1W037RaEy1yYs:-Koympp1W037RaEy1yYt:bw5hfic) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ad5d3b0b5c42adff0b791d84e1566425c76f12c/worker/sort.go#L140)):*
> ```Go
> 			// Copy, otherwise it'd affect the destUids and hence the srcUids of Next level.
> 			tempList := &protos.List{ts.UidMatrix[i].Uids}
> 			if err := sortByValue(ctx, ts.Attr, ts.Langs, tempList, sType, ts.Desc); err != nil {
> ```

This function is accessing so many `ts` values. Why not just give it the ts struct directly?

---

*[worker/sort.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-KoymyIBjKQlNRrfSlU3:-KoymyIBjKQlNRrfSlU4:b57q366) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ad5d3b0b5c42adff0b791d84e1566425c76f12c/worker/sort.go#L232)):*
> ```Go
> 			// Intersect every UID list with the index bucket, and update their
> 			// results (in out).
> 			err := intersectBucket(ctx, ts, ts.Attr, token, out)
> ```

Again, what's the point of giving both ts and then ts.Attr?

If this is simple refactoring, just make it part of this PR.

---

*[worker/sort.go, line 282 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koynh7mcJPFmyuBiWXy:-Koynh7mcJPFmyuBiWXz:bwkx7lu) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ad5d3b0b5c42adff0b791d84e1566425c76f12c/worker/sort.go#L282)):*
> ```Go
> 	go func() {
> 		// Wait for 3ms before starting
> 		time.Sleep(3 * time.Millisecond)
> ```

Check context right after time.Sleep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-:-Koynpfj4HnexVOYyWaQ:b-iycplw)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/sort.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koympp1W037RaEy1yYs:-Koyoq5-lEgTN8127n1j:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ad5d3b0b5c42adff0b791d84e1566425c76f12c/worker/sort.go#L140)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This function is accessing so many `ts` values. Why not just give it the ts struct directly?
</blockquote></details>

Done.

---

*[worker/sort.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-KoymyIBjKQlNRrfSlU3:-Koyoqh8l9kEdEVUAToc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ad5d3b0b5c42adff0b791d84e1566425c76f12c/worker/sort.go#L232)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Again, what's the point of giving both ts and then ts.Attr?

If this is simple refactoring, just make it part of this PR.
</blockquote></details>

Done.

---

*[worker/sort.go, line 282 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koynh7mcJPFmyuBiWXy:-KoypNboXG4LCHAp2cbu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ad5d3b0b5c42adff0b791d84e1566425c76f12c/worker/sort.go#L282)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check context right after time.Sleep.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192)*

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/sort.go, line 284 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-KoyrO-3FS6wMz1SGN9Y:-KoyrO-44sfT2GRTOA2p:b-44te5y) ([raw file](https://github.com/dgraph-io/dgraph/blob/77978717a9db1bb5ed2c0ef57a082c12bce68cfe/worker/sort.go#L284)):*
> ```Go
> 		time.Sleep(3 * time.Millisecond)
> 		select {
> 		case <-ctx.Done():
> ```

select case between time.After(3*time.Millisecond) and ctx.Done. Once you're through it, only then do the sortWithoutIndex (it shouldn't be in default).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192)*

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/sort.go, line 324 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koys-yxbHpHSBRf6wdY:-Koys-yxbHpHSBRf6wdZ:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/77978717a9db1bb5ed2c0ef57a082c12bce68cfe/worker/sort.go#L324)):*
> ```Go
> // intersectBucket intersects every UID list in the UID matrix with the
> // indexed bucket.
> func intersectBucket(ctx context.Context, ts *protos.SortMessage, token string, out []intersectedList) error {
> ```

100 chars.

---

*[worker/sort.go, line 335 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-KoysBJpLcDvIY4F-gy7:-KoysBJpLcDvIY4F-gy8:b-95cyyj) ([raw file](https://github.com/dgraph-io/dgraph/blob/77978717a9db1bb5ed2c0ef57a082c12bce68cfe/worker/sort.go#L335)):*
> ```Go
> 	key := x.IndexKey(attr, token)
> 	// Don't put the Index keys in memory.
> 	pl, decr := posting.Get(key, 1)
> ```

How come the group is always 1?

Anyhow, looks like Get doesn't need group. Can you remove that as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/sort.go, line 284 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-KoyrO-3FS6wMz1SGN9Y:-KoysCGLFsG31GtKLyYT:b-20r03a) ([raw file](https://github.com/dgraph-io/dgraph/blob/77978717a9db1bb5ed2c0ef57a082c12bce68cfe/worker/sort.go#L284)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

select case between time.After(3*time.Millisecond) and ctx.Done. Once you're through it, only then do the sortWithoutIndex (it shouldn't be in default).
</blockquote></details>

Right! Done. 

---

*[worker/sort.go, line 324 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koys-yxbHpHSBRf6wdY:-Koysjo5k3Ytcg98gwOL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/77978717a9db1bb5ed2c0ef57a082c12bce68cfe/worker/sort.go#L324)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[worker/sort.go, line 335 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-KoysBJpLcDvIY4F-gy7:-KoytAjW-F4RtjJBvT4R:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/77978717a9db1bb5ed2c0ef57a082c12bce68cfe/worker/sort.go#L335)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

How come the group is always 1?

Anyhow, looks like Get doesn't need group. Can you remove that as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192)*

**Comment by manishrjain** [comment]
:lgtm: Very important comment. Address before submitting.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/sort.go, line 285 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koytj730bBWPCwHbMQd:-Koytj730bBWPCwHbMQe:b3pjxzc) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3845fd1cc3e2a43fcc4c8472813139e4b2ca689/worker/sort.go#L285)):*
> ```Go
> 			// Wait between ctx chan and time chan.
> 		case <-ctx.Done():
> 			resCh <- result{err: ctx.Err()}
> ```

No return??? Focus, man!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-:-KoyuPUFd9ngvc5IOcdj:b-jyecj9)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/sort.go, line 285 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192#-Koytj730bBWPCwHbMQd:-Koyvvn2LEZrMZlfpJYY:bnhz1qt) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3845fd1cc3e2a43fcc4c8472813139e4b2ca689/worker/sort.go#L285)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No return??? Focus, man!
</blockquote></details>

Ah my bad. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1192)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
