### PR TITLE
Feature/badger

### PR DESCRIPTION
**Pull request by gacharya255**
Add some interfaces to hook up to RocksDB. Badger repo already has some wrapper that satisfy these interfaces.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/902)

### CODE REVIEW

**Comment by szymonm** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[dgs/dgs.go, line 3 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-KjaVq0Twrw8fJyzVogq:-KjaVq0Twrw8fJyzVogr:bnuc1dv) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf92540c0c3385bf18ace81502cdaaa48ab2e865/dgs/dgs.go#L3)):*
> ```Go
> /*
> 
> dgs is dgraph store.
> ```

The name `dgs` seems cryptic to me and the border between packages `dgs` and `store` isn't clear to me. How about having a single package called store with a file store.go that has interface definition and a file badger that has badger implementation of the interface?

RocksDB stuff could stay in the package rdb.

We should also use // to start comment according to this: https://blog.golang.org/godoc-documenting-go-code

---

*[store/store.go, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-KjaZfaHEYp2Y2gihOhc:-KjaZfaIw8YXHxLuexT_:boi6v5r) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf92540c0c3385bf18ace81502cdaaa48ab2e865/store/store.go#L29)):*
> ```Go
> 
> // Store contains some handles to RocksDB.
> type Store struct {
> ```

If we want to use the name Store for interface, we should change the name of RocksDB implementation - this struct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/902)*

**Comment by szymonm** [comment]
Just the confusion of package names.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-:-KjacN4HBqFsDZ4rGne-:b-y78i5r)*

**Comment by manishrjain** [comment]
I agree with Szymon. We already have store/store.go which is an abstraction over RocksDB -- That should have been the place to modify the code. Now we have two layers of abstractions, with little purpose.

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-:-KjfYR6L-7k_9h_lauIW:b8uodfe)*

**Comment by gacharya255** [comment]
Agreed. I removed the orginal store and renamed "dgs" as "store".

However, I am keeping store.Store as rdb.Store as it contains not just one but a few C objects.

Tests are updated and should all pass.

---

Review status: 11 of 30 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-KjaZfaHEYp2Y2gihOhc:-Kjg-rDCMtpQzAw5cU_e:b899jn7) ([raw file](https://github.com/dgraph-io/dgraph/blob/05a9a1c2e3171beb6d8eb714a1fc8319442af14d/store/store.go#L29)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

If we want to use the name Store for interface, we should change the name of RocksDB implementation - this struct.
</blockquote></details>

RocksDB is now rdb.Store, which satisfies store.Store interface.

---

*[dgs/dgs.go, line 3 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-KjaVq0Twrw8fJyzVogq:-KjfzqtFufg0PEpuw8FR:b-tireqf) ([raw file](https://github.com/dgraph-io/dgraph/blob/05a9a1c2e3171beb6d8eb714a1fc8319442af14d/dgs/dgs.go#L3)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

The name `dgs` seems cryptic to me and the border between packages `dgs` and `store` isn't clear to me. How about having a single package called store with a file store.go that has interface definition and a file badger that has badger implementation of the interface?

RocksDB stuff could stay in the package rdb.

We should also use // to start comment according to this: https://blog.golang.org/godoc-documenting-go-code

</blockquote></details>

Added a bunch of comments for the interface and package.

I will move the badger interface over in a separate PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-:-KjfyP1z20Y_gTDheepS:b9ocfwl)*

**Comment by szymonm** [comment]
Reviewed 13 of 28 files at r2.
Review status: 16 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/worker_test.go, line 321 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-Kjkg5lUDO0RGdq29ynJ:-Kjkg5lWzAolrNx35qnA:b-pzee3s) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b042f1ca2c0b1b62174547bd4c6f873ced97f75/worker/worker_test.go#L321)):*
> ```Go
> 
> /*
> <<<<<<< HEAD
> ```

You need to resolve the conflict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/902)*

**Comment by szymonm** [comment]
Reviewed 15 of 28 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/902)*

**Comment by gacharya255** [comment]
Will remove interfaces as @manishrjain suggested, probably in another branch.

---

Review status: 28 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/worker_test.go, line 321 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-Kjkg5lUDO0RGdq29ynJ:-KjqLTZV3H-EycpGC-QA:bt4hg2v) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b042f1ca2c0b1b62174547bd4c6f873ced97f75/worker/worker_test.go#L321)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

You need to resolve the conflict.
</blockquote></details>

Resolved. Didn't see it because this is commented and the test was passing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/902#-:-KjqLcM_Dhyhv_q6ZqMP:b-4dmtu3)*

**Comment by pawanrawal** [comment]
PR #932 takes care of this.

**Pull request closed without merging**
