### PR TITLE
Integrate facets with shortest path

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/595)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/query_test.go, line 481 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd40QkB2tSMYc_qAQBr:-Kd40QkB2tSMYc_qAQBs:bpfnmit) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/query_test.go#L481)):*
> Item
please add failing tests for giving multiple `facets` in query ..
Ignore if they are not part of this PR change ?

---

*[query/shortest.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-Z6iyXXhlNXH056u:-Kd4-Z6iyXXhlNXH056v:b-f0a0ge) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L110)):*
> ```Go
> 				it1 := algo.NewListIterator(sg.uidMatrix[idx])
> 				var fcsList []*facets.Facets
> 				if sg.Params.Facet != nil {
> ```

if user did not supply facet, we will not fetch any weight and shortest path will not be useful..
Will not returning an error be better ? Or if this is general fn, break out of shortest-path logic..

---

*[query/shortest.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-9fm7AfViL2pu3aH:-Kd4-9fm7AfViL2pu3aI:b-a4ouza) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L114)):*
> ```Go
> 				}
> 				// ul := sg.uidMatrix[idx].Uids
> 				idxi := -1
> ```

move idx to for loop init
for idxi := -1; it1.Valid(); ...

---

*[query/shortest.go, line 125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd3xjxeln6pnU9qh-4_:-Kd3xjxeln6pnU9qh-4a:b-yqitga) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L125)):*
> ```Go
> 					if sg.Params.Facet != nil && len(fcsList) > idxi {
> 						fcs := fcsList[idxi]
> 						if len(fcs.Facets) > 1 {
> ```

checking `!= 1` is better and error message of `Expected %d but got %d facets`

---

*[query/shortest.go, line 143 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd3yOCh-h8MqHm1ODqO:-Kd3yOCiZb0IYbtQxIxP:b-gunn6r) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L143)):*
> ```Go
> 						}
> 					}
> 					adjacencyMap[fromUID][toUid] = cost // cost is 1 for now.
> ```

if should not add a cost from `fromUID` to `toUid` ,  if edge does not have required facet / weight.
Adding a test for this will also help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/query_test.go, line 481 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd40QkB2tSMYc_qAQBr:-Kd42mk7LbljhT-78CL4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/query_test.go#L481)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

> Item
please add failing tests for giving multiple `facets` in query ..
Ignore if they are not part of this PR change ?
</blockquote></details>

Done.

---

*[query/shortest.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-Z6iyXXhlNXH056u:-Kd42hvnDoqKb8u0QXbb:b-bvxj6p) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L110)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

if user did not supply facet, we will not fetch any weight and shortest path will not be useful..
Will not returning an error be better ? Or if this is general fn, break out of shortest-path logic..
</blockquote></details>

If there is no facet, we use a default weight of 1.

---

*[query/shortest.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-9fm7AfViL2pu3aH:-Kd42TjTuJt-7iv8g8ZA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L114)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

move idx to for loop init
for idxi := -1; it1.Valid(); ...
</blockquote></details>

Done.

---

*[query/shortest.go, line 125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd3xjxeln6pnU9qh-4_:-Kd42Pv9w5mb-evPzbfE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L125)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

checking `!= 1` is better and error message of `Expected %d but got %d facets`
</blockquote></details>

Done.

---

*[query/shortest.go, line 143 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd3yOCh-h8MqHm1ODqO:-Kd42nZj0dgso5zt1T3s:bknch0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L143)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

if should not add a cost from `fromUID` to `toUid` ,  if edge does not have required facet / weight.
Adding a test for this will also help.
</blockquote></details>

We add a weight of one if the facet is not specified by user. (It'd be based on number of hops)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[query/shortest.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-Z6iyXXhlNXH056u:-Kd5gKbp99Qy4yPp_RBf:b55pt3s) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L110)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

If there is no facet, we use a default weight of 1.
</blockquote></details>

If query specifies facet, and we don't find it in the edge, we ignore that edge right? We should.

---

*[query/shortest.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-9fm7AfViL2pu3aH:-Kd5lHeN86aQSP0I3zZu:b-tzo9wu) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L114)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What does idxi do? It's not clear. All this strange facet stuff should be done via a helper function part of Subgraph.

---

*[query/shortest.go, line 108 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5gnqpHMDPtet6qeN5:-Kd5gnqqnMPewaM_Z1nr:b-cw54i) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L108)):*
> ```Go
> 				idx++
> 				fromUID := it.Val()
> 				it1 := algo.NewListIterator(sg.uidMatrix[idx])
> ```

I think I had told someone (you?) that no variable name should end with a digit. It shows bad naming practice.

---

*[query/shortest.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5j6wRUlVmR_1LBHW3:-Kd5j6wRUlVmR_1LBHW4:b-c982q7) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L111)):*
> ```Go
> 				var fcsList []*facets.Facets
> 				if sg.Params.Facet != nil {
> 					fcsList = sg.FacetsLists[idx].FacetsList
> ```

The API should be `sg.facetMatrix[idx].Facets`.

---

*[query/shortest.go, line 122 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5lCI_FreZ-lbPIbvj:-Kd5lCIaOqcH2V3gfArl:bgp3bsw) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L122)):*
> ```Go
> 					cost := 1.0
> 					if sg.Params.Facet != nil && len(fcsList) > idxi {
> 						fcs := fcsList[idxi]
> ```

Move facet retrieval and checking to a private function part of SubGraph. And simplify this code here.

---

*[query/shortest.go, line 127 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5h6TrCEnPtHOgTbLV:-Kd5h6TrCEnPtHOgTbLW:bdv6w7) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L127)):*
> ```Go
> 							return
> 						}
> 						if tv, err := types.TypeValForFacet(fcs.Facets[0]); err != nil {
> ```

This API should be: `types.TypeValFor(fcs.Facets[0])`.

---

*[query/shortest.go, line 130 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5hLL0KqCa17nAkw1S:-Kd5hLL0KqCa17nAkw1T:b-1soyvc) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L130)):*
> ```Go
> 							rch <- err
> 							return
> 						} else {
> ```

You're better off defining tv, err outside the if, and not having an else here.

---

*[query/shortest.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5hV-0lo_CEoOTFkqY:-Kd5hV-0lo_CEoOTFkqZ:b-1fjo3d) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L136)):*
> ```Go
> 								cost = float64(tv.Value.(float64))
> 							} else {
> 								rch <- x.Errorf("Invalid type of facet for weight.")
> ```

You can ignore the case where we're unable to parse facet. Just skip those edges silently. Assume data isn't totally clean when it comes to graphs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by ashishnegi** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[query/query_test.go, line 476 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5hPsw8DjIXwV5r-Eo:-Kd5hPsxTEnxBBTWzewd:b2om2ch) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/query_test.go#L476)):*
> ```Go
> }
> 
> func TestShortestPathWeightsError(t *testing.T) {
> ```

usually it is good to have reason for why test will fail.
either in name or as a comment.
I think it is because of multiple weights in `facets`. 

---

*[query/shortest.go, line 125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd3xjxeln6pnU9qh-4_:-Kd5iF78PwFYuXoQZoiX:bl93fz4) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L125)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Understanding it more, i think, this case will happen if one of the edge does not have the facet.. 
should we ignore this and continue the processing ?
this will happen a lot in graph dbs..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

*[query/query_test.go, line 476 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5hPsw8DjIXwV5r-Eo:-Kd8ShHifi7iz_9fzu2o:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/query_test.go#L476)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

usually it is good to have reason for why test will fail.
either in name or as a comment.
I think it is because of multiple weights in `facets`. 

</blockquote></details>

Done.

---

*[query/shortest.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-Z6iyXXhlNXH056u:-Kd8U-hSmZheJ4bf_cT1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L110)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If query specifies facet, and we don't find it in the edge, we ignore that edge right? We should.
</blockquote></details>

Done.

---

*[query/shortest.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd4-9fm7AfViL2pu3aH:-Kd8_EFIqAaIH6XOVKVe:bh43wt9) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L114)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What does idxi do? It's not clear. All this strange facet stuff should be done via a helper function part of Subgraph.
</blockquote></details>

idxi is just an index for facets corresponding to UID.

---

*[query/shortest.go, line 125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd3xjxeln6pnU9qh-4_:-Kd8UuioR7i1z1lYLTGe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4aa6e0fd17f518a11f51601dee2cade5bab784d3/query/shortest.go#L125)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Understanding it more, i think, this case will happen if one of the edge does not have the facet.. 
should we ignore this and continue the processing ?
this will happen a lot in graph dbs..
</blockquote></details>

Done.

---

*[query/shortest.go, line 108 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5gnqpHMDPtet6qeN5:-Kd8T7AbgOYbeiVsK_0D:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L108)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I think I had told someone (you?) that no variable name should end with a digit. It shows bad naming practice.
</blockquote></details>

Done.

---

*[query/shortest.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5j6wRUlVmR_1LBHW3:-Kd8_B_wSSr27e4qEqq6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L111)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The API should be `sg.facetMatrix[idx].Facets`.
</blockquote></details>

Done.

---

*[query/shortest.go, line 122 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5lCI_FreZ-lbPIbvj:-Kd93ubQ7uDB5BYlC8Df:b-65tkxq) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L122)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move facet retrieval and checking to a private function part of SubGraph. And simplify this code here.
</blockquote></details>

We need to iterate the Uid and facet matrices and assign the cost. Not sure if we need a generalised function for that.

---

*[query/shortest.go, line 127 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5h6TrCEnPtHOgTbLV:-Kd8aDGXvzSonm-LLf2G:boptoei) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L127)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This API should be: `types.TypeValFor(fcs.Facets[0])`.
</blockquote></details>

Done. Made it `types.ValFor(..facet)`

---

*[query/shortest.go, line 130 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5hLL0KqCa17nAkw1S:-Kd8WkJxaWn2Q7xwlG4B:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L130)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You're better off defining tv, err outside the if, and not having an else here.
</blockquote></details>

Done.

---

*[query/shortest.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5hV-0lo_CEoOTFkqY:-Kd8WwceyN1f00cW4mbK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can ignore the case where we're unable to parse facet. Just skip those edges silently. Assume data isn't totally clean when it comes to graphs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by manishrjain** [comment]
Review status: 0 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[query/shortest.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5j6wRUlVmR_1LBHW3:-Kd96hjHVZFBgdktoJQa:b-bpszw) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L111)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why is the FacetMatrix public? It should be small case f.

---

*[query/shortest.go, line 122 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5lCI_FreZ-lbPIbvj:-Kd96uiTU9vNHZvvWM9n:b-y1f4do) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L122)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We need to iterate the Uid and facet matrices and assign the cost. Not sure if we need a generalised function for that.
</blockquote></details>

But, you can do the facet retrieval in a function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by ashwin95r** [comment]
Review status: 0 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[query/shortest.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5j6wRUlVmR_1LBHW3:-Kd9DnFy7AcXVljpHfS9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L111)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why is the FacetMatrix public? It should be small case f.
</blockquote></details>

Done.

---

*[query/shortest.go, line 122 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd5lCI_FreZ-lbPIbvj:-Kd9DmWndG3JboAmZsd6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53001bf1817bad9f43a57f87e9435b74cf476a73/query/shortest.go#L122)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

But, you can do the facet retrieval in a function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by ashishnegi** [comment]
:lgtm: Just one logic comment. Thanks for refactoring in `Facets`..

---

Review status: 0 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[query/shortest.go, line 63 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd9FketVSN1kJGNCYpJ:-Kd9FketVSN1kJGNCYpK:bygp69c) ([raw file](https://github.com/dgraph-io/dgraph/blob/56dc13031c4ace516858b21bb3b5b752f7cc69d3/query/shortest.go#L63)):*
> ```Go
> 	}
> 	fcsList := sg.facetMatrix[i].FacetsList
> 	if len(fcsList) > j {
> ```

We don't have facet in `else` of this case.
Should we return `cost, ErrFacet` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-:-Kd9HGv1NsFxFrJQN0Gl:b2zb2rl)*

**Comment by ashwin95r** [comment]
Review status: 0 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[query/shortest.go, line 63 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-Kd9FketVSN1kJGNCYpJ:-Kd9Iqg-kUMQKw-j76Zk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/56dc13031c4ace516858b21bb3b5b752f7cc69d3/query/shortest.go#L63)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

We don't have facet in `else` of this case.
Should we return `cost, ErrFacet` ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595)*

**Comment by manishrjain** [comment]
:lgtm: Looks much better now.

---

Reviewed 4 of 7 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/595#-:-KdK8LrK7xKlYBJX7y70:bvss2k0)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
