### PR TITLE
Delete 's p *'

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/846)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[posting/index.go, line 185 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-KhyiovshBxn3vJsmBzy:-Khyiovt6Rab2KPloHsq:b-ug5pb1) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/posting/index.go#L185)):*
> ```Go
> 
> 	if t.Op == taskp.DirectedEdge_DEL && string(t.Value) == x.DeleteAll {
> 		isReversed := schema.State().IsReversed(t.Attr)
> ```

Move this logic outside to it's own function.

---

*[posting/list.go, line 426 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-KhyjUpzw4yAdP6Z1u0p:-KhyjUpzw4yAdP6Z1u0q:b-u9838s) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/posting/list.go#L426)):*
> ```Go
> 	l.AssertLock()
> 
> 	plist := new(typesp.PostingList)
> ```

There is already an emptyList struct that you can use, instead of creating a new one.

---

*[posting/list.go, line 441 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Khyj_EOnRuAg3pW-ewj:-Khyj_EOnRuAg3pW-ewk:b5t67eh) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/posting/list.go#L441)):*
> ```Go
> 	}
> 	if dirtyChan != nil {
> 		dirtyChan <- fingerPrint{fp: l.ghash, gid: gid}
> ```

Note that SyncIfDirty would still need to be changed. Because the mutation layer is empty, when dirty chan runs this key, it would think it's not dirty and just skip it.

Also, write a test for this.

---

*[worker/mutation.go, line 199 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Khyjynec-Xw_XdNvc6f:-Khyjynec-Xw_XdNvc6g:b-3rfy2o) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/worker/mutation.go#L199)):*
> ```Go
> func validateAndConvert(edge *taskp.DirectedEdge, schemaType types.TypeID) error {
> 	if types.TypeID(edge.ValueType) == types.DefaultID &&
> 		string(edge.Value) == x.DeleteAll {
> ```

can go in same line above I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/846)*

**Comment by ashwin95r** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 185 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-KhyiovshBxn3vJsmBzy:-Khz9LC9Rlbe_mxtOf8Z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/posting/index.go#L185)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this logic outside to it's own function.
</blockquote></details>

Done.

---

*[posting/list.go, line 426 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-KhyjUpzw4yAdP6Z1u0p:-Khz9xu9TgYibLJVnrTg:b-j5zsld) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/posting/list.go#L426)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

There is already an emptyList struct that you can use, instead of creating a new one.
</blockquote></details>

It was emptyPosting, created an empthList.

---

*[posting/list.go, line 441 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Khyj_EOnRuAg3pW-ewj:-KhzLw0i-esROgReZ7qX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/posting/list.go#L441)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Note that SyncIfDirty would still need to be changed. Because the mutation layer is empty, when dirty chan runs this key, it would think it's not dirty and just skip it.

Also, write a test for this.
</blockquote></details>

Done.

---

*[worker/mutation.go, line 199 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Khyjynec-Xw_XdNvc6f:-KhzAjoFpWbMDLNn-ssR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/df9d864ac6a425e362b801e4868d13d1279bc800/worker/mutation.go#L199)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can go in same line above I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/846)*

**Comment by janardhan1993** [comment]
Reviewed 4 of 7 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[posting/index.go, line 181 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4VAdZSHxmKY8LEjrX:-Ki4VAdZSHxmKY8LEjrY:buvxs3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/index.go#L181)):*
> ```Go
> 	l.Iterate(0, func(p *typesp.Posting) bool {
> 		if isReversed {
> 			// Delete reverse edge for each posting.
> ```

Reuse addReverseMutation?

---

*[posting/list.go, line 77 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4Pwbrjze8IJUW0koA:-Ki4PwbsK_qg_Q57cxD2:b-op4i7r) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/list.go#L77)):*
> ```Go
> 	deleteMe    int32 // Using atomic for this, to avoid expensive SetForDeletion operation.
> 	refcount    int32
> 	deleteAll   bool
> ```

Use atomic

---

*[posting/list.go, line 554 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4PzBeWqBW1x62Z6oA:-Ki4PzBeWqBW1x62Z6oB:b-oa3fi) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/list.go#L554)):*
> ```Go
> 	defer l.Unlock()
> 
> 	if len(l.mlayer) == 0 && !l.deleteAll {
> ```

atomic ??
Btw this flag is never unset, so set mutations after this delete would be applied in memory but never persisted to memory

---

*[posting/list_test.go, line 640 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4S6CWoPV7dQW2Vl2v:-Ki4S6CWoPV7dQW2Vl2w:b-f6rt6s) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/list_test.go#L640)):*
> ```Go
> 	deletePl(t, ol)
> }
> ```

May be add test case with indexed data also.

---

*[rdf/state.go, line 125 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4OhKMcIa_8BD4G_IN:-Ki4OhKMcIa_8BD4G_IO:b-q6ybek) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/rdf/state.go#L125)):*
> ```Go
> 			}
> 			l.Depth++
> 			l.Emit(itemStar)
> ```

Should we disallow user from storing '*' as object value in set mutations. Otherwise when he tries to delete a single value, all the edges would be deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/846)*

**Comment by ashwin95r** [comment]
Review status: 6 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[posting/index.go, line 181 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4VAdZSHxmKY8LEjrX:-Ki7_DuTuA3vBPiwtcRn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/index.go#L181)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Reuse addReverseMutation?
</blockquote></details>

Done.

---

*[posting/list.go, line 77 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4Pwbrjze8IJUW0koA:-Ki7dFuePASFUF-yExi_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/list.go#L77)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Use atomic
</blockquote></details>

Done.

---

*[posting/list.go, line 554 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4PzBeWqBW1x62Z6oA:-Ki7aOV81q_f1SOK1XpT:b-tuomwa) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/list.go#L554)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

atomic ??
Btw this flag is never unset, so set mutations after this delete would be applied in memory but never persisted to memory
</blockquote></details>

Right! Done.

---

*[posting/list_test.go, line 640 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4S6CWoPV7dQW2Vl2v:-Ki7jdYQS6vCMjTlyXqn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/posting/list_test.go#L640)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

May be add test case with indexed data also.
</blockquote></details>

Done.

---

*[rdf/state.go, line 125 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-Ki4OhKMcIa_8BD4G_IN:-Ki7dF7w0zKmTkmncusw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/395f290058460c4850e9904132724f4e44b62bb9/rdf/state.go#L125)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Should we disallow user from storing '*' as object value in set mutations. Otherwise when he tries to delete a single value, all the edges would be deleted.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/846)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-:-Ki8WWVbOzDZXHJ736yl:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/846#-:-Ki8a4nhdDVvvyBEBClJ:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
