### PR TITLE
Support for Gql variable in arrays

### LINKED ISSUE #2272: DQL variables don't seem to be supported in arrays
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.4

- Steps to reproduce the issue (command/config used to run Dgraph).

```
query all($a: string, $b: string) {
  all(func: eq(whatever, [$a, $b])) {
    uid,
  }
}
```

> Expected comma or language but got: a

- Expected behaviour and actual result.

Either I'm doing something wrong or GraphQL variables that are used in arrays don't work. And since it's not possible to define variable as arrays, it also seems impossible to do something like:

```
query all($a: [string]) {
  all(func: eq(whatever, $a)) {
    uid,
  }
}
```

### PR DESCRIPTION
**Pull request by srfrog**
This change adds support for Gql variables in array arguments of inequality functions.
Argument values are still handled.

Example with variables:
```
query q($name1:string = "Ridley Scott", $name2:string = "Steven Spielberg") {
  me(func: eq(name@en, [$name1, $name2])) {
    name@en
    director.film @filter(lt(initial_release_date, "1980-01-01"))  {
      initial_release_date
      name@en
    }
  }
}
```
Mixed use:
```
query q($name1:string = "Ridley Scott") {
  me(func: eq(name@en, [$name1, "Steven Spielberg"])) {
    name@en
    director.film @filter(lt(initial_release_date, "1980-01-01"))  {
      initial_release_date
      name@en
    }
  }
}
```

Typical use without variables, should yield same result:
```
{
  me(func: eq(name@en, ["Ridley Scott", "Steven Spielberg"])) {
    name@en
    director.film @filter(lt(initial_release_date, "1980-01-01"))  {
      initial_release_date
      name@en
    }
  }
}
```

Closes #2272 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2981)

### CODE REVIEW

**Comment by F21** [comment]
Will this work in the case where we want to pass the array in as a variable?

```
query q($names:string = ["Ridley Scott",  "Steven Spielberg"]) {
  me(func: eq(name@en, $names)) {
    name@en
    director.film @filter(lt(initial_release_date, "1980-01-01"))  {
      initial_release_date
      name@en
    }
  }
}
```
I have a lot of queries that look like this, and having to dynamically generate the place holders: `$name1`, `$name2`, etc in mode makes the query hard to read and is not very nice to implement.

**Comment by MichelDiz** [comment]
This won't work @F21 . And in the last version also don't work as far I can tell.
If you wanna test by yourself. Just install Go Lang and run:
PS. Only macOS or Linux.
>  -  go get github.com/dgraph-io/dgraph/...
>  -  cd ~/go/src/github.com/dgraph-io/dgraph/dgraph
>  -  make

After `make` you gonna have a binary with latest commits ready to use.

**Comment by F21** [comment]
@MichelDiz  Should #2272 or #2726 be reopened? Those issues include support for passing a list as a variable to a query.

**Comment by MichelDiz** [comment]
@F21 not sure. But if would necessary open sure would be only the #2726

**Comment by F21** [comment]
Is this supported on `v1.0.15`? I am using the following query, but it returns this error: `Expected comma or language but got: id1`:

```
query Roles($organizationID: string, $id1: string, $id2: string){
   role(func: has(role)) @filter(eq(organizationID, $organizationID) AND eq(id, [$id1, $id2])){
       uid
   }
}
```

**Comment by MichelDiz** [comment]
I guess this is only in master. I couldn't find any RC with this commit. So it will be in 1.1.

**Comment by hamada969** [comment]
Hey, any updates on the above ?

I am using Dgraph 1.1, the python version and I still can't seem to pass in a str joined list of uids in the variable section against the uid lookup:

`        query = f"""query nodes($uids: string) {{
                          nodes(func: uid($uids)){{
                            uid,
                            nodeType
                        }}
                    }}
                        """
        variables = {f"$uids": f"{','.join([str(uid) for uid in uid_list])}"}
        try:
            result = self._ro_txn(query, variables)
`
error:

`Failed running query (StatusCode.UNKNOWN: strconv.ParseUint: parsing "0xdd6,0xdd6": invalid syntax). See logs for details.`

**Comment by MichelDiz** [comment]
@hamada969  this feels like a bug but you can do like:

```
query test($uids: string = "[0xf468, 0xf468, 0xf468, 0xf468, 0x4f408, 0x8e129]") {
  films(func: uid($uids)) {
    uid
    expand(_all_) {
      expand(_all_)
    }
  }
}
```

In our public dataset should return:

```
{
  "data": {
    "films": [
      {
        "uid": "0xf468",
        "performance.film": [
          {
            "initial_release_date": "2005-07-01T00:00:00Z",
            "netflix_id": "70040924"
          }
        ]
      },
      {
        "uid": "0xf468",
        "performance.film": [
          {
            "initial_release_date": "2005-07-01T00:00:00Z",
            "netflix_id": "70040924"
          }
        ]
      },
      {
        "uid": "0xf468",
        "performance.film": [
          {
            "initial_release_date": "2005-07-01T00:00:00Z",
            "netflix_id": "70040924"
          }
        ]
      },
      {
        "uid": "0xf468",
        "performance.film": [
          {
            "initial_release_date": "2005-07-01T00:00:00Z",
            "netflix_id": "70040924"
          }
        ]
      },
      {
        "uid": "0x4f408",
        "performance.film": [
          {
            "initial_release_date": "2002-01-01T00:00:00Z"
          }
        ]
      },
      {
        "uid": "0x8e129",
        "performance.film": [
          {
            "initial_release_date": "2013-06-01T00:00:00Z"
          }
        ]
      }
    ]
  }
}
```

**Pull request merged**
