### PR TITLE
fix(Dgraph): Subscribe to ACL updates instead of polling.

### PR DESCRIPTION
**Pull request by martinmr**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6459)

 

Docs Preview: [Dgraph Preview](https://dgraph-d62ff1b1f8-94361.surge.sh)

### CODE REVIEW

**Review by jarifibrahim — COMMENTED** [review]
The change looks fine to me but did you test the changes? Can you add a test for it?
Change some ACLs and then run a query?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6459#-:-MHMpoiN14EDTXG8Xzy9:bkfubu5)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[edgraph/access_ee.go, line 322 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6459#-MHMZBR04EFR37TmB8Qd:-MHMZBR04EFR37TmB8Qe:b-83sjo4) ([raw file](https://github.com/dgraph-io/dgraph/blob/b079c9a7bc5ffdcba3db5d837f01b4e23cca5484/edgraph/access_ee.go#L322)):*
> ```Go
> 	var maxRefreshTs uint64
> 	retrieveAcls := func(refreshTs uint64) error {
> 		if refreshTs <= maxRefreshTs {
> ```

Nice.
___
*[edgraph/access_ee.go, line 350 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6459#-MHMYsBBAi5BjZQ06Ccz:-MHMYsBBAi5BjZQ06Cd-:bnwd94f) ([raw file](https://github.com/dgraph-io/dgraph/blob/b079c9a7bc5ffdcba3db5d837f01b4e23cca5484/edgraph/access_ee.go#L350)):*
> ```Go
> 	closer.AddRunning(1)
> 	go worker.SubscribeForUpdates(aclPrefixes, func(kvs *bpb.KVList) {
> 		if kvs == nil || len(kvs.Kv) == 0 {
> ```

Is this even possible? The subscription should be called only when there's data to send.

**Review by martinmr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6459)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @jarifibrahim, @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[edgraph/access_ee.go, line 350 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6459#-MHMYsBBAi5BjZQ06Ccz:-MHMuJLy31pxmYWSAofW:byy7b6o) ([raw file](https://github.com/dgraph-io/dgraph/blob/b079c9a7bc5ffdcba3db5d837f01b4e23cca5484/edgraph/access_ee.go#L350)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Is this even possible? The subscription should be called only when there's data to send.
</blockquote></details>

I don't think so but I added it as a sanity check.

**Review by jarifibrahim — CHANGES_REQUESTED** [review]
I see a lot of acl test in the acl_test.go file using time.sleep. Can you remove all the time.sleep calls from the tests? The tests should without time.sleep after this PR.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6459#-:-MHS4H0P0-cDIvnwfr2O:bsjx0ul)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jarifibrahim, @manishrjain, @martinmr, and @vvbalaji-dgraph)

**Review by martinmr — COMMENTED** [review]
I tried it but there are tests are flaky without any delays. Makes sense to me since the query is not instantaneous. Also, we need to wait for all the alphas to get the update.

I reduced the delay to 5 seconds. Most tests passed if I made the delay smaller but there were a few that were flaky with a value like 3 seconds. Keeping it to five to err on the side of caution.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6459#-:-MHTXBhq8Sp0dAIAane2:b-r1ol54)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jarifibrahim, @manishrjain, @martinmr, and @vvbalaji-dgraph)

**Review by jarifibrahim — APPROVED** [review]

**Pull request merged**
