### PR TITLE
Feature/reverse

### PR DESCRIPTION
**Pull request by jchiu0**
Reverse edges.

Not sure what is the best way to specify in schema. Currently, do it under object definition.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/394)

### CODE REVIEW

**Comment by manishrjain** [comment]
You can just add a `@reverse` keyword after specifying the predicate and it's type (type must be uid or something).

Update: I see that you're using reverses. So, I think the question is about which predicates should have the reverse keyword. We need to support a uid type, if we don't do already. Reverses should only be used for those predicates which do declare the uid type (or an object as you have used in your tests).

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[posting/index.go, line 163 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOFCDG9uMG3_RzRsiy:-KZOFCDG9uMG3_RzRsiz:b1v4j5p) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/posting/index.go#L163)):*
> ```Go
> func addReverseMutation(ctx context.Context, t *task.DirectedEdge) {
> 	key := x.ReverseKey(t.Attr, t.ValueId)
> 	var groupId uint32
> ```

groupId := groups.BelongsTo(t.Attr)

---

*[posting/index.go, line 164 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOFRwOukGrvxUQSyC9:-KZOFRwPTev3-9S5cu50:bfjoq95) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/posting/index.go#L164)):*
> ```Go
> 	key := x.ReverseKey(t.Attr, t.ValueId)
> 	var groupId uint32
> 	if rv, ok := ctx.Value("raft").(x.RaftValue); ok {
> ```

No need for this.

---

*[posting/index.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOG-6mog5j4wZzAadg:-KZOG-6mog5j4wZzAadh:b-clan1) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/posting/index.go#L201)):*
> ```Go
> 	doUpdateIndex := pstore != nil && (t.Value != nil) &&
> 		schema.IsIndexed(t.Attr)
> 	doReverseEdge := pstore != nil && (t.ValueId != 0) &&
> ```

Declare this close to usage.

---

*[query/query.go, line 526 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOGE0fjUOP2KHd3IeW:-KZOGE0fjUOP2KHd3IeX:b-lxexse) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/query/query.go#L526)):*
> ```Go
> }
> 
> func isReversedEdge(attr string) bool {
> ```

Is this func used exactly once? If so, then just inline it.

---

*[query/query.go, line 535 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOGLWN7G98vl_5KUDz:-KZOGLWN7G98vl_5KUE-:b-f55rw5) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/query/query.go#L535)):*
> ```Go
> 	attr := sg.Attr
> 	reverse := isReversedEdge(attr)
> 	if reverse {
> ```

if strings.HasPrefix(attr, "~") { attr = strings.TrimPrefix(attr, "~"); reverse = true }

// I suppose the point about i18n is that we shouldn't just do attr[0] == '~'.

---

*[schema/parse.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOHSVsP7FUaVFX-miM:-KZOHSVsP7FUaVFX-miN:b-zaasmq) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/schema/parse.go#L232)):*
> ```Go
> 
> 				// Check for reverse.
> 				next = <-l.Items
> ```

We already do have an `@index`keyword right? Shouldn't this fit with it. So, the follow up keyword could be `@index` or `@reverse`.

---

*[schema/state.go, line 368 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOHr145z066HA2uS1G:-KZOHr145z066HA2uS1H:b-opqzy0) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/schema/state.go#L368)):*
> ```Go
> L1:
> 	for {
> 		switch r := l.Next(); {
> ```

And here as well. I'm not understanding the need for new logic; given we already handle `@index`.

---

*[x/keys.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOIk5AF0fCoy5I6P6M:-KZOIk5AF0fCoy5I6P6N:b3ctfzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/x/keys.go#L46)):*
> ```Go
> }
> 
> func ReverseKey(attr string, uid uint64) []byte {
> ```

Move this right after DataKey (above IndexKey).

---

*[x/keys.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOIThsN_pr0gEPBH5Q:-KZOITht6e7rEOasqO2X:b-8s8090) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/x/keys.go#L57)):*
> ```Go
> }
> 
> type ParsedKey struct {
> ```

Also handle reverse here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-:-KZOEmqahEXPywzzEAA8:b-4iy1wc)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[schema/parse.go, line 235 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOQSJnUTkqUjiWADnI:-KZOQSJnUTkqUjiWADnJ:b-gr6vyb) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/schema/parse.go#L235)):*
> ```Go
> 				if next.Typ == itemAt {
> 					index := <-l.Items
> 					if index.Typ == itemReverse {
> ```

I think we could add a check here to make sure the type of `name` is not scalar and return an error otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/394)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[x/keys.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZPC0WsK6oNsApmlAfF:-KZPC0WsK6oNsApmlAfG:bxkwcut) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/x/keys.go#L64)):*
> ```Go
> }
> 
> func (p ParsedKey) IsIndex() bool {
> ```

We'd also need an IsReversed() here and use that in backup to skip those edges being written to backup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/394)*

**Comment by jchiu0** [comment]
TODO: Modify query_test to try all equivalent schemas.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[posting/index.go, line 163 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOFCDG9uMG3_RzRsiy:-KZQQcuEnrUaVUoCszmo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/posting/index.go#L163)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

groupId := groups.BelongsTo(t.Attr)
</blockquote></details>

Done.

---

*[posting/index.go, line 164 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOFRwOukGrvxUQSyC9:-KZQQdMTxcnWotq83lcQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/posting/index.go#L164)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this.
</blockquote></details>

Done.

---

*[posting/index.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOG-6mog5j4wZzAadg:-KZQRBIseHpIdXiSZoLd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/posting/index.go#L201)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Declare this close to usage.
</blockquote></details>

Done.

---

*[query/query.go, line 526 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOGE0fjUOP2KHd3IeW:-KZQPumcq1OfvGhJgAyF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/query/query.go#L526)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Is this func used exactly once? If so, then just inline it.
</blockquote></details>

Done.

---

*[query/query.go, line 535 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOGLWN7G98vl_5KUDz:-KZQPvYrROwIUeF9XA8N:b-ye7cr1) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/query/query.go#L535)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if strings.HasPrefix(attr, "~") { attr = strings.TrimPrefix(attr, "~"); reverse = true }

// I suppose the point about i18n is that we shouldn't just do attr[0] == '~'.
</blockquote></details>

Yes, I have modified the comment to make this more clear.

---

*[schema/parse.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOHSVsP7FUaVFX-miM:-KZQi2Hnc6Mk7SSn7kVo:b-j3cd9h) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/schema/parse.go#L232)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We already do have an `@index`keyword right? Shouldn't this fit with it. So, the follow up keyword could be `@index` or `@reverse`.
</blockquote></details>

Added a UID type and modified parser to allow >1 directives for scalar pairs and scalar blocks.

---

*[schema/parse.go, line 235 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOQSJnUTkqUjiWADnI:-KZQi0q2omaSOANZOfyi:bqgc3tg) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/schema/parse.go#L235)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I think we could add a check here to make sure the type of `name` is not scalar and return an error otherwise.
</blockquote></details>

Done. Also checked for UID type.

---

*[schema/state.go, line 368 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOHr145z066HA2uS1G:-KZQRM2FjifszJnmP0MS:beb0gk9) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/schema/state.go#L368)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

And here as well. I'm not understanding the need for new logic; given we already handle `@index`.
</blockquote></details>

This is support @reverse appearing inside an object.

---

*[x/keys.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOIk5AF0fCoy5I6P6M:-KZQGOuNoxFLz49kngFO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/x/keys.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this right after DataKey (above IndexKey).
</blockquote></details>

Done.

---

*[x/keys.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOIThsN_pr0gEPBH5Q:-KZQOQD-FsyyU_Gd-Zf3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/x/keys.go#L57)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Also handle reverse here.
</blockquote></details>

Done.

---

*[x/keys.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZPC0WsK6oNsApmlAfF:-KZQOQl1jEvUg3KbFRq2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/x/keys.go#L64)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We'd also need an IsReversed() here and use that in backup to skip those edges being written to backup.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-:-KZQiDjehKqN1Mq-kzDz:by2meuj)*

**Comment by manishrjain** [comment]
:lgtm: Good job adding the uid type, and making it part of this PR! A well deserved red task. Address the remaining comments and then feel free to submit.

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 526 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOGE0fjUOP2KHd3IeW:-KZQnhidhJTuVkeMRCHp:bi1le7d) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/query/query.go#L526)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The function is still here, remove it as well.

---

*[query/query.go, line 541 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZQntTP0rL6Vp4EV9f2:-KZQntTP0rL6Vp4EV9f3:bj5hbfv) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/query/query.go#L541)):*
> ```Go
> 	out := &task.Query{
> 		Attr:     attr,
> 		Reverse:  reverse, // reverse used here.
> ```

You can remove this comment.

---

*[schema/parse.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOHSVsP7FUaVFX-miM:-KZQoutq1eqk3ronmsY7:bpjvgja) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/schema/parse.go#L232)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Added a UID type and modified parser to allow >1 directives for scalar pairs and scalar blocks.
</blockquote></details>

LGTM. Awesome.

---

*[schema/state.go, line 215 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZQpG8EtP55CtyswBTC:-KZQpG8F8M3hkjmegJ7r:bmj2p4z) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/schema/state.go#L215)):*
> ```Go
> 	// Keep reading for terms that start with @. Keep outputting. If we see
> 	// something that doesn't start with @, we output ItemDummy. It is like
> 	// null-terminatino of C strings.
> ```

null-termination

---

*[x/keys.go, line 62 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZQpotoUwD71SrZ9vWg:-KZQpotpsk3wT7AgBAoU:b-t1xy4o) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/x/keys.go#L62)):*
> ```Go
> 	Uid      uint64
> 	Term     string
> 	Reverse  bool
> ```

This doesn't really need to be stored; because we already have a function for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-:-KZQpv-19Pr8OhUAJpVY:bwb3e9w)*

**Comment by ashwin95r** [comment]
Reviewed 5 of 11 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[schema/parse.go, line 244 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZR5frRbodKgfaaPbd4:-KZR5frRbodKgfaaPbd5:b-vgc5yr) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/schema/parse.go#L244)):*
> ```Go
> 				}
> 				typ = next.Val
> 				t, isScalar := getScalar(typ)
> ```

Since we've made uid a type (it acts as a scalar type as getScalar would return true). I guess it'd be used in expansion of query in treeCopy which may not be right. So I wonder if we should treat it differently?

---

*[schema/state.go, line 311 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZR3B3wLrLtt0vmhi1U:-KZR3B3wLrLtt0vmhi1V:bp2k97g) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/schema/state.go#L311)):*
> ```Go
> 					l.Emit(itemReverse)
> 				} else {
> 					return l.Errorf("Invalid mention of index")
> ```

Could change the error to "Unexpected directive".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/394)*

**Comment by jchiu0** [comment]
Review status: 11 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/query.go, line 526 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZOGE0fjUOP2KHd3IeW:-KZUjg-qX6mJDpwFWo8o:b-3q4udt) ([raw file](https://github.com/dgraph-io/dgraph/blob/fd106e4c4ae5d07b38712efb268379e926e3fa82/query/query.go#L526)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The function is still here, remove it as well.
</blockquote></details>

Oops forgot to delete. Done.

---

*[query/query.go, line 541 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZQntTP0rL6Vp4EV9f2:-KZUjoXdTyoDZw5DZiUo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/query/query.go#L541)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can remove this comment.
</blockquote></details>

Done.

---

*[schema/parse.go, line 244 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZR5frRbodKgfaaPbd4:-KZUkgKrQLI9ZicRaDhG:bnm61jv) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/schema/parse.go#L244)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Since we've made uid a type (it acts as a scalar type as getScalar would return true). I guess it'd be used in expansion of query in treeCopy which may not be right. So I wonder if we should treat it differently?
</blockquote></details>

query_test is passing. I think this is ok. In preTraverse, we check for the object case first and when it hits, we do not process the property value case.

---

*[schema/state.go, line 215 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZQpG8EtP55CtyswBTC:-KZUlXHt9Bq8btuTHUKi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/schema/state.go#L215)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

null-termination
</blockquote></details>

Done.

---

*[schema/state.go, line 311 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZR3B3wLrLtt0vmhi1U:-KZUliIt23by1BanUp1A:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/schema/state.go#L311)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Could change the error to "Unexpected directive".
</blockquote></details>

Done.

---

*[x/keys.go, line 62 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/394#-KZQpotoUwD71SrZ9vWg:-KZUm872FDfeewcTnsSb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/62002350641dccddf219c2d40196a052c41a48f9/x/keys.go#L62)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This doesn't really need to be stored; because we already have a function for this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/394)*

**Pull request closed without merging**
