### PR TITLE
dgraph-converter to convert from geojson => rdf

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Remove support for loading geojson from dgraphloader.

2. Add a new binary to read geojson files, convert to rdf and dump to an output file. This can later be used both by dgraphloader and bulkloader. We could later also add support to convert csv files to rdf as part of the same tool.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1510)

### CODE REVIEW

**Comment by peterstace** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[cmd/dgraphconvert/main.go, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc6_3hJFA99Mi2Ypv6:-Kuc6_3hJFA99Mi2Ypv7:bikkw10) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L37)):*
> ```Go
> 
> var (
> 	geoFile    = flag.String("geo", "", "Location of geo file to convert")
> ```

Are users likely to have multiple geo files? If they are, it could be nice to specify the directory instead of the file. Then we can do a walk to find all of the files.

---

*[cmd/dgraphconvert/main.go, line 87 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc44LYBfMVICyEgUod:-Kuc44LYBfMVICyEgUoe:b2vqled) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L87)):*
> ```Go
> 	}
> 
> 	b, err := ioutil.ReadAll(gz)
> ```

How large are the input files expected to be? Reading the entire input at once might require a lot of memory.

---

*[cmd/dgraphconvert/main.go, line 100 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc5TMhXOhGZvEazDrJ:-Kuc5TMhXOhGZvEazDrK:b30puo5) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L100)):*
> ```Go
> 	}()
> 
> 	fc1 := geojson.NewFeatureCollection()
> ```

What's the significance of the `1`?

---

*[cmd/dgraphconvert/main.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc678Wr8Z8DIpB_80q:-Kuc678Wr8Z8DIpB_80r:b-fsu2a8) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L116)):*
> ```Go
> 		geometry := strings.Replace(string(b), `"`, "'", -1)
> 		bn := fmt.Sprintf("_:%s-%d", name, count)
> 		rdf := fmt.Sprintf("%s <%s> \"%s\"^^<geo:geojson> .\n", bn, *geoPred, geometry)
> ```

I'm not sure of the content of geojson types, but if it could include things like tabs or newlines, then it would be a good idea to use `%q` instead of `"%s"`.

---

*[cmd/dgraphconvert/main.go, line 123 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc6NQOFQUouH88N1JP:-Kuc6NQOFQUouH88N1JQ:bcn1xk) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L123)):*
> ```Go
> 			if str, err := f.PropertyString(k); err == nil {
> 				rdfCount++
> 				rdf = fmt.Sprintf("%s <%s> \"%s\" .\n", bn, k, str)
> ```

Same here for `%q`.

---

*[cmd/dgraphconvert/main.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc38ZnKMjDVtZcTz1E:-Kuc38ZnKMjDVtZcTz1F:bzhhz94) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L140)):*
> ```Go
> func main() {
> 	flag.Parse()
> 	if len(*geoFile) > 0 {
> ```

Error message if the user doesn't supply the `-geo` flag would be nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510)*

**Comment by peterstace** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[cmd/dgraphconvert/main.go, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc6knaJ_MLld-Ub-cm:-Kuc6knaJ_MLld-Ub-cn:b-8vwfkw) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L50)):*
> ```Go
> 	defer f.Close()
> 	x.Check(err)
> 	w := bufio.NewWriterSize(f, 1000000)
> ```

FYI, you can use `1e6` instead of `1000000`. It's a bit easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510)*

**Comment by manishrjain** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[cmd/dgraphconvert/main.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-KucElhQhNYSNg6LAlij:-KucEUwkhU1BiU-R_4Zx:b-rf23uf) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L2)):*
> ```Go
> /*
>  * Copyright (C) 2017 Dgraph Labs, Inc. and Contributors
> ```

How about `dgraph-converter` as the tool name.

Similarly, might make sense to rename `dgraphloader` to `dgraph-live-loader`. And bulk loader to `dgraph-bulk-loader`. @peterstace ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510)*

**Comment by peterstace** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[cmd/dgraphconvert/main.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-KucElhQhNYSNg6LAlij:-KucFShzzxUGsOXIpTIX:biohhd6) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

How about `dgraph-converter` as the tool name.

Similarly, might make sense to rename `dgraphloader` to `dgraph-live-loader`. And bulk loader to `dgraph-bulk-loader`. @peterstace ?
</blockquote></details>

Agreed for `dgraph-live-loader` and `dgraph-bulk-loader`.

For this tool, are we planning to do additional styles of conversions in the same program later on? If so, `dgraph-converter` makes sense. But if this program is just for geojson to rdfs, maybe something more like `geojson2rdf` would be a better name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510)*

**Comment by peterstace** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[cmd/dgraphconvert/main.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-KucElhQhNYSNg6LAlij:-KucG85XD7VkJZ7NfIKd:b-yulqym) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L2)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Agreed for `dgraph-live-loader` and `dgraph-bulk-loader`.

For this tool, are we planning to do additional styles of conversions in the same program later on? If so, `dgraph-converter` makes sense. But if this program is just for geojson to rdfs, maybe something more like `geojson2rdf` would be a better name.
</blockquote></details>

Ticket is #1513

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510)*

**Comment by pawanrawal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/dgraphconvert/main.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-KucElhQhNYSNg6LAlij:-KucPgtwlfLAhsydGoNu:b-pvzsct) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L2)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Ticket is #1513
</blockquote></details>

I can do this as part of the PR if you haven't started it yet @peterstace.

---

*[cmd/dgraphconvert/main.go, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc6_3hJFA99Mi2Ypv6:-KucPDe8LrX3RGZtf-yk:b69byfr) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L37)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Are users likely to have multiple geo files? If they are, it could be nice to specify the directory instead of the file. Then we can do a walk to find all of the files.
</blockquote></details>

For now I have added a TODO. I will revisit this later.

---

*[cmd/dgraphconvert/main.go, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc6knaJ_MLld-Ub-cm:-KucNa-eeZq42F5hiymO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L50)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

FYI, you can use `1e6` instead of `1000000`. It's a bit easier to read.
</blockquote></details>

Done.

---

*[cmd/dgraphconvert/main.go, line 87 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc44LYBfMVICyEgUod:-KucNlQly7d57zgcBCkO:bwbsdc0) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L87)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

How large are the input files expected to be? Reading the entire input at once might require a lot of memory.
</blockquote></details>

Yeah, thats right. Though since a geojson is just a large json I have to write custom decode function for it. I have added a TODO and will address this in another PR.

---

*[cmd/dgraphconvert/main.go, line 100 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc5TMhXOhGZvEazDrJ:-KucNyxA-YCWellDbYhx:bv579y6) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L100)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

What's the significance of the `1`?
</blockquote></details>

removed, had no significance

---

*[cmd/dgraphconvert/main.go, line 116 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc678Wr8Z8DIpB_80q:-KucO-FI6pGjmlfyINde:b-59bw6o) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L116)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

I'm not sure of the content of geojson types, but if it could include things like tabs or newlines, then it would be a good idea to use `%q` instead of `"%s"`.
</blockquote></details>

Shouldn't happen because json strings can't have unescaped newlines/tabs.

---

*[cmd/dgraphconvert/main.go, line 123 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc6NQOFQUouH88N1JP:-KucOTw8pPKVWk7ZtqS9:b-ya81ng) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L123)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Same here for `%q`.
</blockquote></details>

Same as above

---

*[cmd/dgraphconvert/main.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-Kuc38ZnKMjDVtZcTz1E:-KucP83u6oRtsbGhG1Ji:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraphconvert/main.go#L140)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Error message if the user doesn't supply the `-geo` flag would be nice.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510)*

**Comment by peterstace** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraph-converter/main.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-KucElhQhNYSNg6LAlij:-KucRQxiaxw4BpmP90gE:b-w9gaqu) ([raw file](https://github.com/dgraph-io/dgraph/blob/d51aa35a50a1fef21a71643415136ca3694e1e59/cmd/dgraph-converter/main.go#L2)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I can do this as part of the PR if you haven't started it yet @peterstace.
</blockquote></details>

Go for it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-:-KucRyLOjFFOcu60MOfn:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 79 of 80 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1510#-:-Kuce3NT5IorAt1R1lOc:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
