### PR TITLE
RAFT: Applied and Synced watermarks

### PR DESCRIPTION
**Pull request by manishrjain**
- Keep track of RAFT proposals to determine if they have been applied to Posting Lists, and then synced to RocksDB.
- We use one WaterMark per RAFT group to check for applied proposals. This would be used for implement read linearizability.
- We use one WaterMark per RAFT group to check for sync. The sync watermarks would be used for snapshots.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/381)

### CODE REVIEW

**Comment by jchiu0** [comment]
Except two files, all other files seem quite straightforward. Wonder if you have a link or page that summarizes how this is supposed to work? Thanks.

---

Reviewed 8 of 20 files at r1, 10 of 10 files at r2.
Review status: 18 of 20 files reviewed at latest revision, 21 unresolved discussions.

---

*[posting/index.go, line 164 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0Ela59Z0SFY4BXzqp:-KZ0Ela59Z0SFY4BXzqq:byyvw0b) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/index.go#L164)):*
> ```Go
> 	if err != nil {
> 		x.TraceError(ctx, x.Wrapf(err,
> 			"Error deleting %s for attr %s entity %d: %v",
> ```

Error deleting/adding

---

*[posting/list.go, line 354 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0FKAj4TFBifBm0RTY:-KZ0FKAj4TFBifBm0RTZ:b-yn22fv) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/list.go#L354)):*
> ```Go
> 
> 	hasMutated := l.updateMutationLayer(mpost)
> 	if hasMutated {
> ```

Just to check my understanding: The previous IF condition does seem wrong. We should "dirty" this PL only if we just made a mutation.

---

*[posting/lists.go, line 79 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0M_e8G58SnaBSNk9u:-KZ0M_e9ujhin4kriDb6:b-xdejj5) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/lists.go#L79)):*
> ```Go
> 		g.RLock()
> 	}
> 	w := g.m[group]
> ```

Nit: This lookup can probably be avoided if we're careful.

---

*[uid/assigner.go, line 78 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0GY4Z4dGrXOXh6JFJ:-KZ0GY4_AyHEXkaRqNZs:b-ikx6ew) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/uid/assigner.go#L78)):*
> ```Go
> 
> // allocateUniqueUid returns an integer in range:
> // [minIdx, maxIdx] derived based on numInstances and instanceIdx.
> ```

Update comments.

---

*[x/watermark.go, line 29 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0PFjGbatUIAWdCjOh:-KZ0PFjGbatUIAWdCjOi:b-1tizlm) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/x/watermark.go#L29)):*
> ```Go
> 
> type Mark struct {
> 	Index uint64
> ```

Comment about what this Index refers to? RaftIndex?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-:-KZ0QXBAob1piaqML4ih:b-xtiovg)*

**Comment by ashwin95r** [comment]
Reviewed 2 of 20 files at r1, 2 of 10 files at r2.
Review status: 18 of 20 files reviewed at latest revision, 22 unresolved discussions.

---

*[posting/index.go, line 119 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ-ZTjWbLLy6MXz7p05:-KZ-ZTjWbLLy6MXz7p06:bzzg1x) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/index.go#L119)):*
> ```Go
> 
> // addIndexMutations adds mutation(s) for a single term, to maintain index.
> func addIndexMutations(ctx context.Context, t *task.DirectedEdge, p types.Value, op task.DirectedEdge_Op) {
> ```

Could we set the `op` field of `t` in the caller function and get rid of the op argument here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/381)*

**Comment by jchiu0** [comment]
:lgtm: Thanks for the comments.

---

Reviewed 1 of 5 files at r3.
Review status: 16 of 20 files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[x/watermark.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ5C6C9Ejj2yIh1Lm-a:-KZ5C6CAymEUa-I0jZ62:b-gdjbox) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbaacc18408ecbeacdf70c16b3fa7ea21be65209/x/watermark.go#L35)):*
> ```Go
> type Mark struct {
> 	Index uint64
> 	Done  bool
> ```

Comment: As mutations are synced to database, Done is set to true.

---

*[x/watermark.go, line 68 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ5971eRyc4Eg373RKI:-KZ5971eRyc4Eg373RKJ:b-gpdhp0) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbaacc18408ecbeacdf70c16b3fa7ea21be65209/x/watermark.go#L68)):*
> ```Go
> func (w *WaterMark) process() {
> 	var indices uint64Heap
> 	pending := make(map[uint64]int)
> ```

Add comment: pending maps RAFT proposal ID to number of pending mutations for this proposal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-:-KZ5CtjKyzaFnV-A-JKH:b32s1po)*

**Comment by manishrjain** [comment]
Added comments in WaterMark and the two places where committed and synced watermarks are being declared.

---

Review status: 16 of 20 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 119 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ-ZTjWbLLy6MXz7p05:-KZ0fxfzjGBH2XKoM0PC:b-7ncscp) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/index.go#L119)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Could we set the `op` field of `t` in the caller function and get rid of the op argument here?
</blockquote></details>

No, because we're creating more edges with the provided Op within the func. I had the same idea about reducing args before, but then it was cleaner this way to specifically provide Op.

---

*[posting/index.go, line 164 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0Ela59Z0SFY4BXzqp:-KZ0ga4J9qnxtLE4P1n9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/index.go#L164)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Error deleting/adding
</blockquote></details>

Done.

---

*[posting/list.go, line 354 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0FKAj4TFBifBm0RTY:-KZ0hML16OZILzzE_B8V:b-ootqud) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/list.go#L354)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Just to check my understanding: The previous IF condition does seem wrong. We should "dirty" this PL only if we just made a mutation.
</blockquote></details>

Yeah, I think the prev condition wasn't accurate. It send the PL to dirtyChan, even if it wasn't mutated (but was mutated by a previous operation). The new cond makes more sense.

---

*[posting/lists.go, line 79 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0M_e8G58SnaBSNk9u:-KZ0k_qa-EkyQ1MJ9Kxv:b-hupevl) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/posting/lists.go#L79)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Nit: This lookup can probably be avoided if we're careful.
</blockquote></details>

Done. Modified it to avoid the lookup. Thanks for the catch!

---

*[uid/assigner.go, line 78 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0GY4Z4dGrXOXh6JFJ:-KZ0lAgPT1_6hep8TZHh:bd9yrxh) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/uid/assigner.go#L78)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Update comments.
</blockquote></details>

Just removed them. The logic is pretty straightforward.

---

*[x/watermark.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KYwRSmDY9XAYRnqRMnG-r1-28:-KZ0lv0MN2dTBqTJzA-M:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e6fa00e3e7cfcfb442c4fd4d83336400cb40b9f6/x/watermark.go#L28)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

exported type Mark should have comment or be unexported
</blockquote></details>

Done.

---

*[x/watermark.go, line 29 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ0PFjGbatUIAWdCjOh:-KZ0lvw06e6bYMYCCuls:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c0aacc6d971a6fa71becc94e25d5a08f27f58b2/x/watermark.go#L29)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Comment about what this Index refers to? RaftIndex?
</blockquote></details>

Done.

---

*[x/watermark.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ5C6C9Ejj2yIh1Lm-a:-KZJYm-ffDmCEAj5ZxZz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbaacc18408ecbeacdf70c16b3fa7ea21be65209/x/watermark.go#L35)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Comment: As mutations are synced to database, Done is set to true.
</blockquote></details>

Done.

---

*[x/watermark.go, line 68 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-KZ5971eRyc4Eg373RKI:-KZJYvIwVwj8IMmAqZVp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbaacc18408ecbeacdf70c16b3fa7ea21be65209/x/watermark.go#L68)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Add comment: pending maps RAFT proposal ID to number of pending mutations for this proposal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/381#-:-KZ0bOPQ7EA_m1Sxr3YW:b-sy61eq)*

**Pull request closed without merging**
