### PR TITLE
Feat(GraphQL): Add generate directive to graphql schema

### PR DESCRIPTION
**Pull request by vmrajas**
Motivation:
Currently, GraphQL schema exposes all queries (get, query) and mutations (add, update, delete). It has been requested to resolve only some of these resolvers by Users.
This PR adds this feature of adding only specific resolvers to GraphQL schema.
Additionally, one can also control the subscription query using generate directive.
Related Discuss Issue: https://discuss.dgraph.io/t/expose-only-specific-resolvers/10497/12

Testing:
Added tests in graphql/schema/testdata/schemagen

Fixes GRAPHQL-710

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6760)

 

Docs Preview: [Dgraph Preview](https://dgraph-4d70f62d5c-104828.surge.sh)

### CODE REVIEW

**Review by abhimanyusinghgaur — COMMENTED** [review]
I have just got the following points:
1. Let's just keep one file for testing all different bits for `@generate` directive in schemagen tests. We can put all the different cases in one single file using different types. That helps keep the number of those files at a minimum, otherwise, we have to update each file every time we do something with the inbuilt schema, and it just takes unnecessary time.
2. As discussed yesterday, let's also skip adding the following things to schema:
   a. `AddTypeInput` and `AddTypePayload` if add mutation is disabled.
   b. `UpdateTypeInput`, `TypePatch` and `UpdateTypePayload` if update mutation is disabled.
   c. `DeleteTypePayload` if delete mutation is disabled.

> Reviewed 7 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-:-MK3YnyyB28beSWD0UZW:bsnhtgg)* status: 7 of 59 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)

___
*[graphql/schema/gqlschema.go, line 712 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MK3TlAA8qi6M-6vkItd:-MK3TlAA8qi6M-6vkIte:b2gs696) ([raw file](https://github.com/dgraph-io/dgraph/blob/02a68127f2ba87628ae80d551c5896c0a5cee6ea/graphql/schema/gqlschema.go#L712)):*
> ```
> if params.generateUpdateMutation == true {
> ```
this could just be:
```
if params.generateUpdateMutation {
```
Same for all other places like this.
___
*[graphql/schema/schemagen_test.go, line 98 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MK3X21I4BvKPQix6bBx:-MK3X21J-DRGp3vGTUy1:b-3n4ch3) ([raw file](https://github.com/dgraph-io/dgraph/blob/02a68127f2ba87628ae80d551c5896c0a5cee6ea/graphql/schema/schemagen_test.go#L98)):*
> ```Go
> 			if diff := cmp.Diff(string(str2), newSchemaStr); diff != "" {
> 				// fmt.Printf("Generated Schema (%s):\n%s\n", testFile.Name(), newSchemaStr)
> 				_ = ioutil.WriteFile(outputFileName+"tp", []byte(newSchemaStr), 0644)
> ```

stale code

**Review by abhimanyusinghgaur — COMMENTED** [review]
Ah! forgot to mention that we should also make password query configurable using generate directive. Default behaviour is to be generated if the type has a password field.
So,
```
@generate(
  query: {
    ...
    password: true/false
  }
  ...
)
```

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-:-MK3aP3lDE_pZEcZjQPG:blvb7wc)* status: 7 of 59 files reviewed, 2 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vmrajas)

**Review by vmrajas — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-:-MK4t3ITAFG9m8cUg5pL:bb6un1j)* status: 2 of 58 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, and @pawanrawal)

___
*[graphql/schema/gqlschema.go, line 712 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MK3TlAA8qi6M-6vkItd:-MK4sz708BUHASCURKoA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02a68127f2ba87628ae80d551c5896c0a5cee6ea/graphql/schema/gqlschema.go#L712)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> if params.generateUpdateMutation == true {
> ```
this could just be:
```
if params.generateUpdateMutation {
```
Same for all other places like this.
</blockquote></details>

Done.
___
*[graphql/schema/schemagen_test.go, line 98 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MK3X21I4BvKPQix6bBx:-MK55gmg6q9OuI5CxZnm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/02a68127f2ba87628ae80d551c5896c0a5cee6ea/graphql/schema/schemagen_test.go#L98)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

stale code
</blockquote></details>

Done.

**Review by abhimanyusinghgaur — APPROVED** [review]
:lgtm:
Nice set of tests!

There is just one schemagen test failling in CI. Also, make sure to first merge master into this branch before merging it with master and then let the CI pass.

> Reviewed 61 of 65 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-:-MKEnj3K8JEZQgJhbEkq:b-v7yh9w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @MichaelJCompton, and @pawanrawal)

**Review by pawanrawal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6760)* status: all files reviewed, 3 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, and @vmrajas)

___
*[graphql/e2e/schema/generatedSchema.graphql, line 169 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MKJUf3S0WAV1czlp4bi:-MKJUf3TBvCC4tkOKoJH:b-wuyxfd) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac34082ebc2cd41a5933de0d9510a6e154c09554/graphql/e2e/schema/generatedSchema.graphql#L169)):*
> ```GraphQL
> 	get: Boolean
> 	query: Boolean
> 	password: Boolean
> ```

Hope this is ignored for types where this is not applicable?
___
*[graphql/e2e/schema/generatedSchema.graphql, line 173 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MKJUcke8easXyUPvOoX:-MKJUcke8easXyUPvOoY:bq3qqfc) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac34082ebc2cd41a5933de0d9510a6e154c09554/graphql/e2e/schema/generatedSchema.graphql#L173)):*
> ```GraphQL
> 
> input GenerateMutationParams {
> 	add: Boolean
> ```

What happens when add is given for an interface?
___
*[graphql/schema/rules.go, line 1236 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MKJVCRf3TNIvTeUtdcZ:-MKJVCRf3TNIvTeUtdc_:b-25a8f5) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac34082ebc2cd41a5933de0d9510a6e154c09554/graphql/schema/rules.go#L1236)):*
> ```Go
> }
> 
> func generateDirectiveValidation(schema *ast.Schema, typ *ast.Definition) gqlerror.List {
> ```

Strange, we have to do all this validation ourselves? Doesn't happen in the gqlparser library?

**Review by vmrajas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6760)* status: all files reviewed, 3 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/schema/generatedSchema.graphql, line 169 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MKJUf3S0WAV1czlp4bi:-MKj26OpBGkcwY-tdNmA:b-h4tm6l) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac34082ebc2cd41a5933de0d9510a6e154c09554/graphql/e2e/schema/generatedSchema.graphql#L169)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Hope this is ignored for types where this is not applicable?
</blockquote></details>

Yes, it is ignored.
___
*[graphql/e2e/schema/generatedSchema.graphql, line 173 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MKJUcke8easXyUPvOoX:-MKj29s56zxDJCbJF7Qt:b-3p3jh5) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac34082ebc2cd41a5933de0d9510a6e154c09554/graphql/e2e/schema/generatedSchema.graphql#L173)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What happens when add is given for an interface?
</blockquote></details>

It won't generate the add mutation. 
___
*[graphql/schema/rules.go, line 1236 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6760#-MKJVCRf3TNIvTeUtdcZ:-MKj2E0L5VI8xj0427Q3:bta8tws) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac34082ebc2cd41a5933de0d9510a6e154c09554/graphql/schema/rules.go#L1236)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Strange, we have to do all this validation ourselves? Doesn't happen in the gqlparser library?
</blockquote></details>

Yes, we need to do these ourselves. As is the case with other directives.

**Pull request merged**
