### PR TITLE
Created helm chart files for Dgraph Cluster

### PR DESCRIPTION
**Pull request by SandeepVaman**
- Created template for Statefullset of Dgraph Zero
- Created template for headless service of Dgraph Zero
- This has not been tested yet.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3264)

### CODE REVIEW

**Comment by danielmai** [comment]
@SandeepVaman thanks for your PR. Is this ready to review?

**Comment by SandeepVaman** [comment]
@danielmai  I am testing the helm chart now. I will let you know once it is ready for review.

**Comment by SandeepVaman** [comment]
@danielmai I have tested the helm chart and was able to set up the cluster. Please review it.

**Comment by MichelDiz** [comment]
Also, I've tested it using minikube + helm. And it's working great.

**Comment by danielmai** [comment]
Thanks for your PR, @SandeepVaman!

**Pull request merged**
