### PR TITLE
RDF test improvements

### PR DESCRIPTION
**Pull request by anacrolix**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/161)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[rdf/nquad.go, line 4 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/161#-KOxaNa6cbljxNW6MF0G:-KOxaNa6cbljxNW6MF0H:b-ftrb7j) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa20c85e0f1f31d3e17917d64fa929d14ab950e3/rdf/nquad.go#L4)):*
> ```Go
> 
> // NQuad is the data structure used for storing rdf N-Quads.
> type NQuad struct {
> ```

Don't see the value in moving this struct to its own file. Any particular reason why?

---

*[rdf/parse_test.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/161#-KOxag83Zq-gMxxJ7uq6:-KOxag83Zq-gMxxJ7uq7:b-x5xt74) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa20c85e0f1f31d3e17917d64fa929d14ab950e3/rdf/parse_test.go#L61)):*
> ```Go
> 	},
> 	{
> 		input: `_:_uid_:0x01 <predicate> <object_id> .`,
> ```

I see what you're trying to do here but this looks weird. If you really want this to comply with RDF spec, then maybe make it <_uid_:0x01>. But, `_:` are blank nodes, with little value (intermediate nodes), which is not the case with uids.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/161)*

**Comment by anacrolix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[rdf/nquad.go, line 4 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/161#-KOxaNa6cbljxNW6MF0G:-KOxfbcEc38YT0ueCGt9:bo3j6be) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa20c85e0f1f31d3e17917d64fa929d14ab950e3/rdf/nquad.go#L4)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Don't see the value in moving this struct to its own file. Any particular reason why?
</details>
It's unrelated to the parsing code, which I intend to change. The state.go file would go away in this case.

---

*[rdf/parse_test.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/161#-KOxag83Zq-gMxxJ7uq6:-KOxfyzUHh-O_Q0b1KAI:b-ervex8) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa20c85e0f1f31d3e17917d64fa929d14ab950e3/rdf/parse_test.go#L61)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I see what you're trying to do here but this looks weird. If you really want this to comply with RDF spec, then maybe make it <_uid_:0x01>. But, `_:` are blank nodes, with little value (intermediate nodes), which is not the case with uids.
</details>
I don't know enough about the use case for this. But either way I think it needs to change to conform? Changing to <_uid_:0x01> can be a future change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/161)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[rdf/nquad.go, line 4 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/161#-KOxaNa6cbljxNW6MF0G:-KOxgcCTqJKR5hRLh0iH:bwwds9l) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa20c85e0f1f31d3e17917d64fa929d14ab950e3/rdf/nquad.go#L4)):*
<details><summary><i>Previously, anacrolix (Matt Joiner) wrote…</i></summary>
> It's unrelated to the parsing code, which I intend to change. The state.go file would go away in this case.
</details>
Then make it part of the change when you remove state.go. Also, keep in mind that the main motivation of doing this change is to gain a performance improvement. So, you might want to ensure that we have that, before you spend a lot of effort changing the code in master.

---

*[rdf/parse_test.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/161#-KOxag83Zq-gMxxJ7uq6:-KOxgRqqpXGCnQb6d1LI:b-6my1et) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa20c85e0f1f31d3e17917d64fa929d14ab950e3/rdf/parse_test.go#L61)):*
<details><summary><i>Previously, anacrolix (Matt Joiner) wrote…</i></summary>
> I don't know enough about the use case for this. But either way I think it needs to change to conform? Changing to <_uid_:0x01> can be a future change.
</details>
Blank node is still not what UIDs are. I don't see the point of this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/161)*

**Comment by manishrjain** [comment]
If this is not being worked upon, can you please discard this PR? Or, create another PR with BenchmarkParse.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/161#-:-KPgN9jSTAabhyRJhri2:b-xqr76a)*

**Pull request closed without merging**
