### PR TITLE
Fix aggregation functions

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/719)

### CODE REVIEW

**Comment by Motakjuq** [comment]
@ashwin95r the file name parser/aggregator.go is misspelled

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[query/query.go, line 761 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeRpsiuBrmcbEUig3Q:-KfeRpsiuBrmcbEUig3R:bu1cqga) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L761)):*
> ```Go
> 
> func (sg *SubGraph) populateAggregation(parent *SubGraph) error {
> 	var err error
> ```

why this here?

---

*[query/query.go, line 766 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeSLtvkhzmwrSmGkeg:-KfeSLtvkhzmwrSmGkeh:bxu087t) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L766)):*
> ```Go
> 		if err != nil {
> 			return err
> 		}
> ```

if parent == nil { .. }

---

*[query/query.go, line 767 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeR_4tlk9tX04nmgDB:-KfeR_4tlk9tX04nmgDC:bteoobc) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L767)):*
> ```Go
> 			return err
> 		}
> 		if len(child.SrcFunc) > 0 && isAggregatorFn(child.SrcFunc[0]) {
> ```

if !isAggregate(..) {
  return nil
}
// logic

---

*[query/query.go, line 768 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeUICVPI7GuJLqCkXQ:-KfeUICVPI7GuJLqCkXR:b-55mbyx) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L768)):*
> ```Go
> 		}
> 		if len(child.SrcFunc) > 0 && isAggregatorFn(child.SrcFunc[0]) {
> 			temp := new(SubGraph)
> ```

sibling = *child // sibling of sg.

---

*[query/query.go, line 778 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeSpLohi0zJRCBTBYQ:-KfeSpLohi0zJRCBTBYR:b-8c7lrr) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L778)):*
> ```Go
> 			temp.values = make([]*taskp.Value, 0, 1)
> 			temp.Params.Alias = sg.Attr
> 			temp.Params.isPartOfresult = true
> ```

You can remove this child; instead of keeping track of this with a var.

---

*[query/query.go, line 783 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeTGPJkdiFsJcPg75_:-KfeTGPJkdiFsJcPg75a:b-9dttjb) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L783)):*
> ```Go
> 			for _, list := range sg.uidMatrix {
> 				var values []*taskp.Value
> 				var val *taskp.Value
> ```

remove this.

---

*[query/query.go, line 789 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeTjx4HNGJcWHvc2mr:-KfeTjx4HNGJcWHvc2ms:b-42rwux) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L789)):*
> ```Go
> 					})
> 					if idx < len(child.SrcUIDs.Uids) && child.SrcUIDs.Uids[idx] == uid {
> 						values = append(values, child.values[idx])
> ```

instead of creating a list of values; use an aggregator struct. ag.Apply(child.values[idx]); and finally ag.Value()

---

*[query/query_test.go, line 1036 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeUeaw3ZnJuLjAWfU_:-KfeUeaxgU46cmf68PqL:b-fnp7r4) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query_test.go#L1036)):*
> ```Go
> 			name
> 			friend {
> 				min(dob)
> ```

min(dob), dob, max(dob)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[query/aggreagtor.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfeun6nkm6i9OfDaR-b:-Kfeun6nkm6i9OfDaR-c:b-gu07qm) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/aggreagtor.go#L19)):*
> ```Go
> 
> func Aggregate(agrtr string, values []*taskp.Value, typ types.TypeID) (res *taskp.Value, rerr error) {
> 	// va is accumulated. if some error comes in accumulate, we keep va
> ```

Any reason for removing couldapplyaggregatoron on check?

---

*[query/query.go, line 780 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfeu_oLU4sNsOMU0MoB:-Kfeu_oLU4sNsOMU0MoC:beryfhs) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L780)):*
> ```Go
> 			temp.Params.isPartOfresult = true
> 			child.Params.isPartOfresult = false
> 			typ, _ := schema.State().TypeOf(child.Attr)
> ```

Values are converted to appropriate type in worker/task.go now. So no need to convert to schema type here. Schema information might not be present also on this node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by ashwin95r** [comment]
@motakjuq Thanks for the catch!

---

Review status: 4 of 5 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 761 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeRpsiuBrmcbEUig3Q:-KfeWWev0t7kyX25j7t5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L761)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

why this here?
</blockquote></details>

Done.

---

*[query/query.go, line 766 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeSLtvkhzmwrSmGkeg:-KfekRud0lKEZ2tWXZm0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L766)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if parent == nil { .. }
</blockquote></details>

Done.

---

*[query/query.go, line 767 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeR_4tlk9tX04nmgDB:-KfekSaMGN9FK6Q79_R3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L767)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if !isAggregate(..) {
  return nil
}
// logic
</blockquote></details>

Done.

---

*[query/query.go, line 768 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeUICVPI7GuJLqCkXQ:-KfeWkdF6idoy4Yshj3u:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L768)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

sibling = *child // sibling of sg.
</blockquote></details>

Done.

---

*[query/query.go, line 783 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeTGPJkdiFsJcPg75_:-KfeWu749-E5WHFit7c5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L783)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove this.
</blockquote></details>

Done.

---

*[query/query.go, line 789 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeTjx4HNGJcWHvc2mr:-KfeeB8xpIuYYtanCr0N:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L789)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

instead of creating a list of values; use an aggregator struct. ag.Apply(child.values[idx]); and finally ag.Value()
</blockquote></details>

Done.

---

*[query/aggreagtor.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfeun6nkm6i9OfDaR-b:-Kfez_k-UKC7wy4fFtSk:be6dgr2) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/aggreagtor.go#L19)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Any reason for removing couldapplyaggregatoron on check?
</blockquote></details>

Would already be done in worker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-:-KfeW9_t5Ofl6n6QCXjN:b-mdwpso)*

**Comment by ashwin95r** [comment]
Review status: 3 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 778 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeSpLohi0zJRCBTBYQ:-KfiCbRRQ0hQr_kFD_yr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L778)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can remove this child; instead of keeping track of this with a var.
</blockquote></details>

Done.

---

*[query/query.go, line 780 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfeu_oLU4sNsOMU0MoB:-KfiChLAuXMj71hrkMTH:bkpe1n3) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query.go#L780)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Values are converted to appropriate type in worker/task.go now. So no need to convert to schema type here. Schema information might not be present also on this node.
</blockquote></details>

Right. Was waiting for the merge to happen. Will fix.

---

*[query/query_test.go, line 1036 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfeUeaw3ZnJuLjAWfU_:-KfiCcavWmP7CaPg_dVD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74f4a7ea629921f81ce97efc449fcd7dc04dff63/query/query_test.go#L1036)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

min(dob), dob, max(dob)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[query/aggregator.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinD4y4xmSKTdNLszW:-KfinD4y4xmSKTdNLszX:bv68bry) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L17)):*
> ```Go
> 	vh, _ := getValue(from)
> 	va, err := types.Convert(vh, vh.Tid)
> 	if err != nil {
> ```

Move this to assert? Stop returning error.

---

*[query/aggregator.go, line 25 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinEdM8CFS4viz4ybh:-KfinEdM8CFS4viz4ybi:btqt157) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L25)):*
> ```Go
> func (ag *aggregator) Apply(val *taskp.Value) {
> 	if ag.result.Value == nil {
> 		ag.result, _ = convertTo(val)
> ```

Never do this.

Can always do x.Assertf(..).

---

*[query/aggregator.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinaviR_6T6s4_Jocq:-KfinaviR_6T6s4_Jocr:bvx8ukr) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L55)):*
> ```Go
> 		} else if va.Tid == types.FloatID && vb.Tid == types.FloatID {
> 			va.Value = va.Value.(float64) + vb.Value.(float64)
> 		}
> ```

else // add a comment.

---

*[query/aggregator.go, line 58 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfinr0QU8X2Bv8Q7U3k:-Kfinr0QU8X2Bv8Q7U3l:b-bamod6) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L58)):*
> ```Go
> 		res = va
> 	default:
> 		return
> ```

log.Fatalf(..), if it's already checked upstream.

---

*[query/query.go, line 749 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfiqLk2lqTJxJh_UQsz:-KfiqLk2lqTJxJh_UQt-:bof60ei) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/query.go#L749)):*
> ```Go
> 
> func (sg *SubGraph) populateAggregation(parent *SubGraph) error {
> 	var removeChild []int
> ```

filteredChildren := sg.Children[:0]

filteredChildren = append(fc, ..)

---

*[query/query.go, line 776 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfip4O5OPnlCyTPEf7d:-Kfip4O5OPnlCyTPEf7e:b-9dttiu) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/query.go#L776)):*
> ```Go
> 				if idx < len(child.SrcUIDs.Uids) && child.SrcUIDs.Uids[idx] == uid {
> 					ag.Apply(child.values[idx])
> 					if err != nil {
> ```

remove this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[query/aggregator.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinD4y4xmSKTdNLszW:-Kfiqt8vJRd9VkcvRB3I:bn0jcmy) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L17)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this to assert? Stop returning error.
</blockquote></details>

taskp.Value could be a nil byte if schema conversion fails or if no value was present. It could be a either an empty value in which case you can skip or else assert. 

---

*[query/aggregator.go, line 25 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinEdM8CFS4viz4ybh:-KfisX1ROwrrPtp0qGEI:bt7ozc0) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L25)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Never do this.

Can always do x.Assertf(..).
</blockquote></details>

ConvertTo can throw error if taskp.Value is a nil byte, need to handle that case separately

---

*[query/aggregator.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinaviR_6T6s4_Jocq:-KfirftCfFAS6ES2Funy:bwhc1s6) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L55)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

else // add a comment.
</blockquote></details>

I guess it should be log.Fatalf inside else inside sum is allowed only on int and float types, which we would have checked in worker/task.go already

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 368 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfit94u3qD-gme-iMwL:-Kfit94u3qD-gme-iMwM:b8kdhsl) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b74f6cee56880ac9b3e871a2c2f82a580ed4341/worker/task.go#L368)):*
> ```Go
> 	}
> 
> 	// aggregate on the collection out.Values[]
> ```

Just wondering if we could figure out a way to aggregate on the node where data is located instead of sending all the values to the node which received the query.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 785 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfiuYHbLipiU1J495Aa:-KfiuYHbLipiU1J495Ab:b-eyd1a7) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/query.go#L785)):*
> ```Go
> 				return err
> 			}
> 			sibling.values = append(sibling.values, v)
> ```

v can be nil as ag.Value() can return nil. It's safe to return taskp.value with nil byte, which is ignored for  output. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by ashwin95r** [comment]
Review status: 4 of 6 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[query/aggregator.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinD4y4xmSKTdNLszW:-KfizkNaTNFTKSNdkv9U:bdubj6r) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L17)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

taskp.Value could be a nil byte if schema conversion fails or if no value was present. It could be a either an empty value in which case you can skip or else assert. 
</blockquote></details>

Returning error so that we can handle empty values.

---

*[query/aggregator.go, line 25 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinEdM8CFS4viz4ybh:-Kfizeyjk0QbQEamVVTl:b-mtpq1k) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L25)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

ConvertTo can throw error if taskp.Value is a nil byte, need to handle that case separately
</blockquote></details>

Check error as we want to skip empty values

---

*[query/aggregator.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinaviR_6T6s4_Jocq:-Kfix1X-GKslZz3C8Bfv:bhart3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L55)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

I guess it should be log.Fatalf inside else inside sum is allowed only on int and float types, which we would have checked in worker/task.go already
</blockquote></details>

We should pass I think as there sould've been an empty value.

---

*[query/aggregator.go, line 58 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfinr0QU8X2Bv8Q7U3k:-KfiwgmhnK2mGMYtKLxc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L58)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

log.Fatalf(..), if it's already checked upstream.
</blockquote></details>

Done.

---

*[query/query.go, line 749 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfiqLk2lqTJxJh_UQsz:-KfjCjG4uF5SYKNhalTr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/query.go#L749)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

filteredChildren := sg.Children[:0]

filteredChildren = append(fc, ..)
</blockquote></details>

Done.

---

*[query/query.go, line 776 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfip4O5OPnlCyTPEf7d:-Kfiu-ER1_07HfJWcICT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/query.go#L776)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove this?
</blockquote></details>

Done.

---

*[query/query.go, line 785 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfiuYHbLipiU1J495Aa:-KfixdGo00n0BFyeJVzs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/query.go#L785)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

v can be nil as ag.Value() can return nil. It's safe to return taskp.value with nil byte, which is ignored for  output. 
</blockquote></details>

Done.

---

*[worker/task.go, line 368 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-Kfit94u3qD-gme-iMwL:-Kfiu4BfctYVy5yImHhL:bs27e2i) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b74f6cee56880ac9b3e871a2c2f82a580ed4341/worker/task.go#L368)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Just wondering if we could figure out a way to aggregate on the node where data is located instead of sending all the values to the node which received the query.
</blockquote></details>

We'd need the parent information and also attach a node at the parent level. This can't be done cleanly at the worker. Hence we do it at the coordinator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[query/aggregator.go, line 66 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfjDY_3-I9JucRMPpz6:-KfjDY_4LKNogPAU9hS2:byhcimc) ([raw file](https://github.com/dgraph-io/dgraph/blob/5bfa1980249dd7686684f7ea532100df4ff3c308/query/aggregator.go#L66)):*
> ```Go
> 		res = va
> 	default:
> 		log.Fatalf("Unhandled aggregator function")
> ```

Unhandled aggregator function: %v

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-:-KfjE8ruUd0btBdfyNmJ:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 5 of 6 files reviewed at latest revision, 9 unresolved discussions.

---

*[query/aggregator.go, line 66 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfjDY_3-I9JucRMPpz6:-KfjFFvJPwejcE2KWcnB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5bfa1980249dd7686684f7ea532100df4ff3c308/query/aggregator.go#L66)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Unhandled aggregator function: %v
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/aggregator.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinD4y4xmSKTdNLszW:-KfjL0OASOqMRfHenPyq:b-rj58ce) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L17)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Returning error so that we can handle empty values.
</blockquote></details>

Its probably better to do something like 
if bytes.Equal(from.Val, nil) {
		return v, ErrEmptyVal
	}
	
sv, err := types.Convert(v, v.Tid)
Assert for err if it's not empty

And handle errEmptyVal

---

*[query/aggregator.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinaviR_6T6s4_Jocq:-KfjLsTY-nig17599JtB:bhbzr0) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L55)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We should pass I think as there sould've been an empty value.
</blockquote></details>

We return from the function earlier if it's empty value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-:-KfjLfRmv10WGOnT8SKT:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/aggregator.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinD4y4xmSKTdNLszW:-KfjP4yaJgHxY2k-_RBq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L17)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Its probably better to do something like 
if bytes.Equal(from.Val, nil) {
		return v, ErrEmptyVal
	}
	
sv, err := types.Convert(v, v.Tid)
Assert for err if it's not empty

And handle errEmptyVal
</blockquote></details>

Done.

---

*[query/aggregator.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/719#-KfinaviR_6T6s4_Jocq:-KfjQymU79OrjxNo2cnf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ec70295e28777eb463a8e870c8fe3f93aa5de707/query/aggregator.go#L55)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We return from the function earlier if it's empty value.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/719)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
