### PR TITLE
Benchmarking

### PR DESCRIPTION
**Pull request by pawanrawal**
Benchmarking protocol buffer and optimizations.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/81)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[query/query.go, line 346 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhMmOhd88ypSVUsCbu:-KHhMmOhd88ypSVUsCbv:1070898085) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query.go#L346)):*
> ```Go
> 	}
> 
> 	for i, p := range properties {
> ```

You can avoid this loop by making this logic part of the loop above.

---

*[query/query_test.go, line 329 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhMyRxyKlLVCU6bYz3:-KHhMyRxyKlLVCU6bYz4:-1762876019) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L329)):*
> ```Go
> }
> 
> func getProperty(properties []*graph.Property, prop string) (v *graph.Value) {
> ```

v isn't a great name for a return value. In fact, in this case, you can avoid assigning name to the return value.

---

*[query/query_test.go, line 335 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhMvog5Px0OB7Qge3Z:-KHhMvoh492SbHfGKUgc:-88232474) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L335)):*
> ```Go
> 		}
> 	}
> 	return v
> ```

return nil

---

*[query/query_test.go, line 461 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNA-wk2IMgTU2xBwh:-KHhNA-wk2IMgTU2xBwi:554244728) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L461)):*
> ```Go
> }
> 
> func BenchmarkToJson(b *testing.B) {
> ```

Did you forget to push the changes?

---

*[query/query_test.go, line 495 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNCQqjUmyhmUaxrp6:-KHhNCQqjUmyhmUaxrp7:241797349) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L495)):*
> ```Go
> }
> 
> func BenchmarkToProtocolBuffer(b *testing.B) {
> ```

And here as well?

---

*[query/benchmark/actors10.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNHQy04UkywQANzUK:-KHhNHQz7c-8d65EtS8W:879238574) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/benchmark/actors10.txt#L1)):*
> ```
> W��SubGraph��AttrCountOffsetChildren��Query
> ```

Don't name it `.txt`, call it `.bin`. And all the files below this.

---

*[query/benchmark/README.txt, line 28 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNRJvWy4ivDyl-IC3:-KHhNRJwYnFf4YNWp7VR:279149817) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/benchmark/README.txt#L28)):*
> ```
>     }
> }
> ```

Add a date when you ran the benchmark.

---

*[server/main.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNc-fduEjeKJt1vXQ:-KHhNc-fduEjeKJt1vXR:-1055137637) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/server/main.go#L213)):*
> ```Go
> func (s *server) Query(ctx context.Context,
> 	req *graph.Request) (*graph.Response, error) {
> 	node := new(graph.Node)
> ```

Why do you allocate memory for this node, only to overwrite it later?

This should be var node *graph.Node, and close to the point where you actually use it.

---

*[server/main.go, line 214 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNp5gLnYrNgf9Ykmx:-KHhNp5gLnYrNgf9Ykmy:-685618418) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/server/main.go#L214)):*
> ```Go
> 	req *graph.Request) (*graph.Response, error) {
> 	node := new(graph.Node)
> 	gl := new(graph.Latency)
> ```

Declare close to usage. Always.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by pawanrawal** [comment]
Review status: 3 of 13 files reviewed at latest revision, 9 unresolved discussions.

---

*[query/query.go, line 346 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhMmOhd88ypSVUsCbu:-KHi63ScR5N5w8XSRda_:670778830) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query.go#L346)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can avoid this loop by making this logic part of the loop above.</details>
Right, should have observed this.

---

*[query/query_test.go, line 329 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhMyRxyKlLVCU6bYz3:-KHi6CaAePaw1E1JYomx:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L329)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> v isn't a great name for a return value. In fact, in this case, you can avoid assigning name to the return value.</details>
Done.

---

*[query/query_test.go, line 335 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhMvog5Px0OB7Qge3Z:-KHi9RMsfQCN2J6ddab6:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L335)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> return nil</details>
Done.

---

*[query/query_test.go, line 461 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNA-wk2IMgTU2xBwh:-KHi9PMBztxKWT4GhiPY:1956836875) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L461)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Did you forget to push the changes?</details>
Yes, pushed them now.

---

*[query/query_test.go, line 495 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNCQqjUmyhmUaxrp6:-KHi9OsqZHnwY86dpHnf:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/query_test.go#L495)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> And here as well?</details>
Done.

---

*[query/benchmark/README.txt, line 28 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNRJvWy4ivDyl-IC3:-KHi9C1NXUCk13VasRpU:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/benchmark/README.txt#L28)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a date when you ran the benchmark.</details>
Done.

---

*[server/main.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNc-fduEjeKJt1vXQ:-KHi7bFS_UEZowLZeEAx:-2101959111) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/server/main.go#L213)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why do you allocate memory for this node, only to overwrite it later?
> 
> This should be var node *graph.Node, and close to the point where you actually use it.</details>
Yup, this was a bad idea. 

---

*[server/main.go, line 214 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNp5gLnYrNgf9Ykmx:-KHi6sPxQdsx8K9V0sA-:-1221705028) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/server/main.go#L214)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Declare close to usage. Always.</details>
Ok, thanks for bringing this to my notice.

---

*[query/benchmark/actors10.txt, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHhNHQy04UkywQANzUK:-KHi9O5nBH1zx69iuA-3:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f0ee3c97408723f40101e97b0734303fadb1cce/query/benchmark/actors10.txt#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Don't name it `.txt`, call it `.bin`. And all the files below this.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by manishrjain** [comment]
Reviewed 15 of 16 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[query/graph/graphresponse.proto, line 27 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHrPzTFBrMdoFBhu6K7:-KHrPzTFBrMdoFBhu6K8:204200802) ([raw file](https://github.com/dgraph-io/dgraph/blob/33f936dd18cee4b2359e2966d6f8c1acf34cd8c7/query/graph/graphresponse.proto#L27)):*
> ```protobuf
> message Property {
>   string prop = 1;
>   Value val = 2;
> ```

Let's keep it simple and just make it a binary blob. We don't need the message Value in that case.

If this can't happen in this change, make it part of your next change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by pawanrawal** [comment]
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/graph/graphresponse.proto, line 27 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHrPzTFBrMdoFBhu6K7:-KHrWymC3irSwB9i8TXz:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/33f936dd18cee4b2359e2966d6f8c1acf34cd8c7/query/graph/graphresponse.proto#L27)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Let's keep it simple and just make it a binary blob. We don't need the message Value in that case.
> 
> If this can't happen in this change, make it part of your next change.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 330 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHrYXXbvppMnY38j2pg:-KHrYXXbvppMnY38j2ph:1095645365) ([raw file](https://github.com/dgraph-io/dgraph/blob/684e26d21b64d6f80b2c7897432cf68d3808586d/query/query.go#L330)):*
> ```Go
> 			}
> 
> 			var ival interface{}
> ```

You can now avoid this interface conversion, and directly just set the bytes?

v := tv.ValBytes()

if pc.Attr == .. {
  dst.Xid = string(v)
} else {
 ...
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by pawanrawal** [comment]
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 330 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHrYXXbvppMnY38j2pg:-KHrZZK50iGwg51VY4kx:663118220) ([raw file](https://github.com/dgraph-io/dgraph/blob/684e26d21b64d6f80b2c7897432cf68d3808586d/query/query.go#L330)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can now avoid this interface conversion, and directly just set the bytes?
> 
> v := tv.ValBytes()
> 
> if pc.Attr == .. {
>   dst.Xid = string(v)
> } else {
>  ...
> }
> </details>
Ahh, yes.Should have thought about this. 

---

*[query/query_test.go, line 386 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHrbBJzp0q5OzgeE2ht:-KHrbBJzp0q5OzgeE2hu:667225665) ([raw file](https://github.com/dgraph-io/dgraph/blob/4932af81d4d6bfe5a41d7043f5d718278d0df544/query/query_test.go#L386)):*
> ```Go
> 		t.Errorf("Expected uid 1, Got: %v", gr.Uid)
> 	}
> 	if gr.Xid != `"mich"` {
> ```

Though on avoiding interface conversion, the byte slice has `"` at the start and end too. Is this fine or is it related to how Value is stored as an interface instead of a byte slice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by manishrjain** [comment]
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query_test.go, line 386 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHrbBJzp0q5OzgeE2ht:-KHrulmZY338TCujfAZ3:669104425) ([raw file](https://github.com/dgraph-io/dgraph/blob/4932af81d4d6bfe5a41d7043f5d718278d0df544/query/query_test.go#L386)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Though on avoiding interface conversion, the byte slice has `"` at the start and end too. Is this fine or is it related to how Value is stored as an interface instead of a byte slice?</details>
Yeah, I think this is because of the JSON conversion on storage. Add a TODO here, to fix that in a separate change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by pawanrawal** [comment]
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query_test.go, line 386 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-KHrbBJzp0q5OzgeE2ht:-KHrwwLWEKNZ_jwZY7lP:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/4932af81d4d6bfe5a41d7043f5d718278d0df544/query/query_test.go#L386)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Yeah, I think this is because of the JSON conversion on storage. Add a TODO here, to fix that in a separate change.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81)*

**Comment by manishrjain** [comment]
:lgtm:

<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> #### Benchmarking
> 
> Benchmarking protocol buffer and optimizations.
> 
> 
> 
> 
> 
> </details>


---

Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/81#-:-KHs-Q8jgfTV3JaBIt0Z:1417088721)*

**Pull request merged**
