### PR TITLE
System test fixture

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1537)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm: 

Do these now run as part of `go test`?

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[systest/tests_test.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1537#-KuxDrnm6Jpsvpo4QzTy:-KuxDrnm6Jpsvpo4QzTz:b-mji47o) ([raw file](https://github.com/dgraph-io/dgraph/blob/475facf495454d1f86933a15a2f92be8d9bd0c92/systest/tests_test.go#L201)):*
> ```Go
> func TestGoldenData(t *testing.T) {
> 	s := newSuiteFromFile(t,
> 		os.ExpandEnv("$GOPATH/src/github.com/dgraph-io/dgraph/systest/data/goldendata.schema"),
> ```

We can pick these up from dgraph-io/benchmarks/data/goldendata.rdf.gz instead of making it part of this repo. What do you think @peterstace? Otherwise, this would become part of `go get` download by users?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1537#-:-KuxDXp09cSyqT9CE2e4:b-alifgv)*

**Comment by peterstace** [comment]
That's correct. They are a bit slow to run... and can be skipped when running `go test` using the `--test.skip` flag.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[systest/tests_test.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1537#-KuxDrnm6Jpsvpo4QzTy:-KuxFHutmkrt2aBFlxqH:bm49v1e) ([raw file](https://github.com/dgraph-io/dgraph/blob/475facf495454d1f86933a15a2f92be8d9bd0c92/systest/tests_test.go#L201)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We can pick these up from dgraph-io/benchmarks/data/goldendata.rdf.gz instead of making it part of this repo. What do you think @peterstace? Otherwise, this would become part of `go get` download by users?
</blockquote></details>

That's what I was doing originally, but then that required the benchmarks repo to also be cloned in CI. I think either way is fine, most users won't want to `go get` anyway, only contributors. The file is only 12MB anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1537#-:-KuxFeyDSdOjrZrp19lG:b9x6nsa)*

**Comment by manishrjain** [comment]
Defer to @pawanrawal for review. So, :lgtm: from my side.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1537#-:-KuxJVJiwH7tPatAti1-:b9vwjhk)*

**Comment by pawanrawal** [comment]
Feel free to merge

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1537#-:-Kv06SBjPSU6BAdEQeMj:b4dz3oy)*

**Pull request merged**
