### PR TITLE
Allow aggregating over levels. Modify usage of aggregators.

### PR DESCRIPTION
**Pull request by ashwin95r**
```
# To sum the x over relationship
{
  filtered as var(func: eq(type, 1)) {}
  var(id: var(filtered)) {
        relationship @filter(NOT eq(outCount, 0)){
          x as count(outEvent)
        }
        y as sum(var(x))
  }
  start(id: var(filtered)) {
     var(y)
  }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/874)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 1855 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVaGIARD5_lOUpRjVJ:-KiVaGIBf_7gg_nWUNOb:b-pxcl2o) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f76c838e54ab9a19c3ca4134c9baafe713f49f7/gql/parser.go#L1855)):*
> ```Go
> 				it.Next()
> 				if it.Item().Val != "var" {
> 					return x.Errorf("Only variables allowed in aggregate functions.")
> ```

From now inside a var block, we can't specify ?
var(func:allofterms(name,"stephen")) {
     a as min(age)
}

---

*[gql/parser_test.go, line 467 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVasSRUVNVnldQpf0c:-KiVasSRUVNVnldQpf0d:bnu7vsc) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f76c838e54ab9a19c3ca4134c9baafe713f49f7/gql/parser_test.go#L467)):*
> ```Go
> 			}
> 			n as min(var(na))
> 		}
> ```

It would be good if we could specify it in both old and new way.

---

*[wiki/content/query-language/index.md, line 1495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVcdjk6Qab5VX5ZAFP:-KiVcdjk6Qab5VX5ZAFQ:b-jxrkgi) ([raw file](https://github.com/dgraph-io/dgraph/blob/0fbcc5a30f973080ed15aee39c1cef604178665e/wiki/content/query-language/index.md#L1495)):*
> ```Markdown
> ```
> 
> Output:
> ```

We could probably add the output to docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/874)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 1855 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVaGIARD5_lOUpRjVJ:-KiXLRRisMXQqWMafvFM:b-q91hmz) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f76c838e54ab9a19c3ca4134c9baafe713f49f7/gql/parser.go#L1855)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

From now inside a var block, we can't specify ?
var(func:allofterms(name,"stephen")) {
     a as min(age)
}
</blockquote></details>

This anyways would be just same as age. To get the min age among friends, we'd do.
```
var(func:allofterms(name,"stephen")) {
 friend {
  x as age
 }
a as min(var(x))
}
```

---

*[gql/parser_test.go, line 467 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVasSRUVNVnldQpf0c:-KiXLf2bYrlIVEsDXBZK:b-p62x8j) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f76c838e54ab9a19c3ca4134c9baafe713f49f7/gql/parser_test.go#L467)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

It would be good if we could specify it in both old and new way.
</blockquote></details>

The old way was a bit confusing. We moved the aggregate results one level up. This way makes it clear that its at a level above where it is specified.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/874)*

**Comment by manishrjain** [comment]
:lgtm:  Small comments, fix those before submitting.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 820 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXkX7R6Y0k9wnGtUYB:-KiXkX7R6Y0k9wnGtUYC:b-dfk3nz) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query.go#L820)):*
> ```Go
> 	}
> 	if relSG == nil {
> 		return mp, x.Errorf("Invalid variable aggregation. Check the levels.")
> ```

Create a var for all the errors, and just return the var. Don't create them on the fly.

---

*[query/query_test.go, line 1729 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXlXhX5Ef_zBbmqbTl:-KiXlXhX5Ef_zBbmqbTm:b-79j03d) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query_test.go#L1729)):*
> ```Go
> 		minorder(id: var(f), orderasc: var(mindob)) {
> 			name
> 			var(mindob)
> ```

Keep the "var(mindob)" intact.

---

*[query/query_test.go, line 1749 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXl_fiwwx-i8TfEfRp:-KiXl_fiwwx-i8TfEfRq:b-qu1z6z) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query_test.go#L1749)):*
> ```Go
> 				x as dob
> 			}
> 			min(var(x))
> ```

Output should be `min(var(x))`

---

*[query/query_test.go, line 1911 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXle6t-32p0V199dCB:-KiXle6t-32p0V199dCC:bd5d6lg) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query_test.go#L1911)):*
> ```Go
>                                     x as survival_rate
>                                 }
> 																min(var(x))
> ```

indentation

---

*[wiki/content/query-language/index.md, line 1494 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXlphVVrmo1VVhMHTW:-KiXlphW8DmsSbSUV7a7:bbt5d2h) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/wiki/content/query-language/index.md#L1494)):*
> ```Markdown
> 		avg(var(a))			
> 	}
> }' | python -m json.tool | less
> ```

Make it runnable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-:-KiXlsazCrhZtjNLpt0d:b-8o3rux)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 820 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXkX7R6Y0k9wnGtUYB:-KiXqJZyH7A9eGHqD1xp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query.go#L820)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a var for all the errors, and just return the var. Don't create them on the fly.
</blockquote></details>

Done.

---

*[query/query_test.go, line 1729 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXlXhX5Ef_zBbmqbTl:-KiXwH-S5K5giGAqI_8H:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query_test.go#L1729)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Keep the "var(mindob)" intact.
</blockquote></details>

Done.

---

*[query/query_test.go, line 1749 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXl_fiwwx-i8TfEfRp:-KiXwHGmQCxqaTe7Ubc6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query_test.go#L1749)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Output should be `min(var(x))`
</blockquote></details>

Done.

---

*[query/query_test.go, line 1911 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXle6t-32p0V199dCB:-KiXwHmjTYD_ZjyU84Zy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/query/query_test.go#L1911)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

indentation
</blockquote></details>

Done.

---

*[wiki/content/query-language/index.md, line 1495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVcdjk6Qab5VX5ZAFP:-KiXs2WxB0vxYz03fhg_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0fbcc5a30f973080ed15aee39c1cef604178665e/wiki/content/query-language/index.md#L1495)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We could probably add the output to docs.
</blockquote></details>

Done.

---

*[wiki/content/query-language/index.md, line 1494 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiXlphVVrmo1VVhMHTW:-KiXryzjD4fdNhqQaLOU:b-7zhdlc) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a81fb65f8291765ed71dbab002b6077a3bf0a7c/wiki/content/query-language/index.md#L1494)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make it runnable.
</blockquote></details>

This one has a mutation, so retaining the output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/874)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1855 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVaGIARD5_lOUpRjVJ:-KiY8bGkJ8xqpd5Qjd2j:b-tnkc9u) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f76c838e54ab9a19c3ca4134c9baafe713f49f7/gql/parser.go#L1855)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This anyways would be just same as age. To get the min age among friends, we'd do.
```
var(func:allofterms(name,"stephen")) {
 friend {
  x as age
 }
a as min(var(x))
}
```
</blockquote></details>

that would give min age among people having name stephen.
To get that we will have to do the following query ?
A as var(func:allofterms(name,"stephen")) {
}
me(id:Var(A)){
min(age)
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-:-KiY8TmwGf9tgdsRd9aE:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1855 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/874#-KiVaGIARD5_lOUpRjVJ:-KiYYc_bDNOcAtS793Nv:b-6cpaz6) ([raw file](https://github.com/dgraph-io/dgraph/blob/2f76c838e54ab9a19c3ca4134c9baafe713f49f7/gql/parser.go#L1855)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

that would give min age among people having name stephen.
To get that we will have to do the following query ?
A as var(func:allofterms(name,"stephen")) {
}
me(id:Var(A)){
min(age)
}
</blockquote></details>

We weren't supporting it before as well. We could do it if someone asks for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/874)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
