### PR TITLE
feat(Dgraph): add utility to export backup data.

### PR DESCRIPTION
**Pull request by martinmr**
This utility allows to take a single backup (full or incremental) and export the data
and the schema inside it to RDF. Encrypted backups are supported.

Fixes DGRAPH-2465

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6550)

 

Docs Preview: [Dgraph Preview](https://dgraph-6675e947e7-95406.surge.sh)

### CODE REVIEW

**Comment by martinmr** [comment]
Tested this with the example backups in systest/online-restore/backup. I can see the rdf output.

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6550)* status: all files reviewed, 2 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[worker/file_handler.go, line 362 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6550#-MHtSh3AEtLS00qd7I69:-MHtSP9NC9YmUHp86VPd:b-hgszqr) ([raw file](https://github.com/dgraph-io/dgraph/blob/6675e947e76ecc79a04ce81edf7e4065f692dc90/worker/file_handler.go#L362)):*
> ```Go
> 			req := &pb.ExportRequest{
> 				GroupId:     group,
> 				ReadTs:      math.MaxUint64,
> ```

Can ReadTs be the `"since"` from the manifest.json file? Otherwise, the export data always shows `r18446744073709551615` is the export directory, e.g., `./dgraph.r18446744073709551615.u0923.0525/g01.rdf.gz`.
___
*[worker/file_handler.go, line 364 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6550#-MHtSwiK0cJTScExC1Gv:-MHtSwiK0cJTScExC1Gw:b-xyllfa) ([raw file](https://github.com/dgraph-io/dgraph/blob/6675e947e76ecc79a04ce81edf7e4065f692dc90/worker/file_handler.go#L364)):*
> ```
> Format:      "rdf",
> ```
Would be nice to have an option to either export to RDF or JSON.

**Review by martinmr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6550)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @danielmai, @manishrjain, and @vvbalaji-dgraph)

___
*[worker/file_handler.go, line 362 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6550#-MHtSh3AEtLS00qd7I69:-MHwdt6n5XjDwqrN4ywO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6675e947e76ecc79a04ce81edf7e4065f692dc90/worker/file_handler.go#L362)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Can ReadTs be the `"since"` from the manifest.json file? Otherwise, the export data always shows `r18446744073709551615` is the export directory, e.g., `./dgraph.r18446744073709551615.u0923.0525/g01.rdf.gz`.
</blockquote></details>

Done.
___
*[worker/file_handler.go, line 364 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6550#-MHtSwiK0cJTScExC1Gv:-MHwdsqT9ual_g1vgmqI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6675e947e76ecc79a04ce81edf7e4065f692dc90/worker/file_handler.go#L364)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Format:      "rdf",
> ```
Would be nice to have an option to either export to RDF or JSON.
</blockquote></details>

Done.

**Review by pawanrawal — APPROVED** [review]
:lgtm: 

We should add some docs about what this does and when this would be useful.

> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6550#-:-MIKMj5S2iGnxKBVSvQS:b-aa20eh)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai, @manishrjain, and @vvbalaji-dgraph)

**Review by jarifibrahim — APPROVED** [review]
@martinmr please try to add a test for it. Any kind of test that verifies this PR works would be awesome!

**Pull request merged**
