### PR TITLE
Language filtering for string matching

### PR DESCRIPTION
**Pull request by tzdybal**
Language filtering for string matching. Term and full text matching covered. Regex is not included, because regex functionality will be changed soon (in another PR).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/835)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 693 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhWhToKLZ33GyRX0Egv:-KhWhToKLZ33GyRX0Egw:b22iwct) ([raw file](https://github.com/dgraph-io/dgraph/blob/4415c0921790e749ebf97ece24ba10483650cb59/posting/list.go#L693)):*
> ```Go
> 
> func (l *List) valueForTag(tag string) (rval types.Val, rerr error) {
> 	uid := farm.Fingerprint64([]byte(tag))
> ```

We can do l.assetRlock here. 
Can we refactor ValueFor(langs []string) to use valueForTag ?

---

*[worker/stringfilter.go, line 98 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhWif5g0Oz7s7VHbwGP:-KhWif5g0Oz7s7VHbwGQ:b-6pz2dr) ([raw file](https://github.com/dgraph-io/dgraph/blob/4415c0921790e749ebf97ece24ba10483650cb59/worker/stringfilter.go#L98)):*
> ```Go
> 		}
> 	}
> 	return []string{}
> ```

Shouldn't we throw error if ftstokenizer is not found for a language.

---

*[worker/task.go, line 455 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhWi4A3WOf6ZKtFwPSQ:-KhWi4A4j-rTThCe08LW:b-rtg00a) ([raw file](https://github.com/dgraph-io/dgraph/blob/4415c0921790e749ebf97ece24ba10483650cb59/worker/task.go#L455)):*
> ```Go
> 			val, err := pl.ValueForTag(srcFn.lang)
> 			if err != nil {
> 				continue
> ```

decr()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-:-KhWjIEHOgT2gP-6ChgS:bnfp4nl)*

**Comment by tzdybal** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[posting/list.go, line 693 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhWhToKLZ33GyRX0Egv:-KhXPaK1laKPJ6MHx8Yu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4415c0921790e749ebf97ece24ba10483650cb59/posting/list.go#L693)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We can do l.assetRlock here. 
Can we refactor ValueFor(langs []string) to use valueForTag ?
</blockquote></details>

Done.

---

*[worker/stringfilter.go, line 98 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhWif5g0Oz7s7VHbwGP:-KhXDPRKRijhtSXJUGXX:b-olhgqc) ([raw file](https://github.com/dgraph-io/dgraph/blob/4415c0921790e749ebf97ece24ba10483650cb59/worker/stringfilter.go#L98)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Shouldn't we throw error if ftstokenizer is not found for a language.
</blockquote></details>

At this point, it's rather not possible. If we reached that far, tokenizer was used (or error was reported) during index scan. So even if this happens somehow, we can just ignore it.

---

*[worker/task.go, line 455 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhWi4A3WOf6ZKtFwPSQ:-KhXDtiTgbeEMozaAET_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4415c0921790e749ebf97ece24ba10483650cb59/worker/task.go#L455)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

decr()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835)*

**Comment by manishrjain** [comment]
Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[worker/stringfilter.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhyoJBuBpnIPFVOHdkO:-KhyoJBuBpnIPFVOHdkP:bz0mxrh) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/stringfilter.go#L50)):*
> ```Go
> }
> 
> func match(value types.Val, filter stringFilter) bool {
> ```

This function is a bit weirdly written. You don't need filter. You just need the map that filter creates, which you can pass in directly to this function.

match(value types.Val, filterMap map[string]struct{}) bool {
}

---

*[worker/stringfilter.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhyoTUR6OgJnKNADEtN:-KhyoTUR6OgJnKNADEtO:b-8zgv80) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/stringfilter.go#L55)):*
> ```Go
> 	tokenMatch := make(map[string]bool)
> 	for _, token := range filter.tokens {
> 		tokenMatch[token] = false
> ```

As mentioned above, this can be generated by the caller, and passed to this func.

---

*[worker/stringfilter.go, line 59 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhyoX6z-kNy_m4Ri1P7:-KhyoX6z-kNy_m4Ri1P8:b-n5g0sx) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/stringfilter.go#L59)):*
> ```Go
> 
> 	for _, token := range tokens {
> 		_, ok := tokenMatch[token]
> ```

if _, ok := filterMap[token]; ok { cnt++}

---

*[worker/stringfilter.go, line 66 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhyoaVXSgtrEz_A_Zzq:-KhyoaVXSgtrEz_A_Zzr:b-dralmn) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/stringfilter.go#L66)):*
> ```Go
> 
> 	cnt := 0
> 	for _, match := range tokenMatch {
> ```

This loop isn't required.

---

*[worker/stringfilter.go, line 72 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhyomYEaiYzQnSRbi8Q:-KhyomYEaiYzQnSRbi8R:b-jprgrm) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/stringfilter.go#L72)):*
> ```Go
> 	}
> 
> 	all := strings.HasPrefix(value.Value.(string), "allof") // anyofterms or anyoftext
> ```

I thought value was value, not function name. This is confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835)*

**Comment by janardhan1993** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[worker/stringfilter.go, line 98 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KhWif5g0Oz7s7VHbwGP:-Ki4B3qz4qHtvjvr71hD:bircuy1) ([raw file](https://github.com/dgraph-io/dgraph/blob/4415c0921790e749ebf97ece24ba10483650cb59/worker/stringfilter.go#L98)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

At this point, it's rather not possible. If we reached that far, tokenizer was used (or error was reported) during index scan. So even if this happens somehow, we can just ignore it.
</blockquote></details>

If it's not possible, then add an assert may be ?

---

*[worker/task.go, line 465 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-Ki4BjcPENndgHToO5dy:-Ki4BjcPENndgHToO5dz:b-ng8xa0) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/task.go#L465)):*
> ```Go
> 			decr() // Decrement the reference count of the pl.
> 		}
> ```

Just wondering if we could store the language in the index itself. Iterating over the values and filtering might be lot slower than using index when uidmatrix is large. 
Or Probably we could parallelise fetching values for time being. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 448 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-Ki4FXHVVDD99dYtjH-x:-Ki4FXHW-do9sGfkyrrH:b44fw3z) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/task.go#L448)):*
> ```Go
> 	if (srcFn.fnType == StandardFn || srcFn.fnType == FullTextSearchFn) && len(srcFn.lang) > 0 {
> 		uids := algo.MergeSorted(out.UidMatrix)
> 		var values []types.Val
> ```

We can probably fetch values in parallel if length of srcuid's is more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[worker/task.go, line 448 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-Ki4FXHVVDD99dYtjH-x:-Ki8cLkRnei7oP2g1zlt:b-8e0o5t) ([raw file](https://github.com/dgraph-io/dgraph/blob/3898499f05ca2502019d2f3eeaacb6ab57a231e1/worker/task.go#L448)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We can probably fetch values in parallel if length of srcuid's is more.
</blockquote></details>

Yes, I intend to make this a feature in the new KV store.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-:-Ki8cdCz_4MSt80Euzak:bnfp4nl)*

**Comment by tzdybal** [comment]
Merged to master (1e662e17c5011a7d0f789b9fc608597807c0fea8)

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[worker/stringfilter.go, line 55 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KiB7ZO6cKsVTqDKnS8P:-KiB7ZO6cKsVTqDKnS8Q:b-n9lx4j) ([raw file](https://github.com/dgraph-io/dgraph/blob/a952c65526e245fbf843ebaed9bc2c32293c2af1/worker/stringfilter.go#L55)):*
> ```Go
> 	cnt := 0
> 	for _, token := range tokens {
> 		previous, ok := filter.tokenMap[token]
> ```

tokenMap shouldn't be present inside filter, sharing it across uid's would give wrong results.

---

*[worker/task.go, line 457 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KiB7qKjJy8v54MPHZZ4:-KiB7qKjJy8v54MPHZZ5:b-z72bf9) ([raw file](https://github.com/dgraph-io/dgraph/blob/a952c65526e245fbf843ebaed9bc2c32293c2af1/worker/task.go#L457)):*
> ```Go
> 				decr()
> 				continue
> 			}
> ```

In case of err we need to append an nilbyte for value.

---

*[worker/task.go, line 463 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-KiB7jrqcZ8o5NzwIB4w:-KiB7jrqcZ8o5NzwIB4x:b-xnfm7u) ([raw file](https://github.com/dgraph-io/dgraph/blob/a952c65526e245fbf843ebaed9bc2c32293c2af1/worker/task.go#L463)):*
> ```Go
> 				values = append(values, strVal)
> 			}
> 			decr() // Decrement the reference count of the pl.
> ```

You have ignored the error. We should atleast assert instead of ignoring.
Anyhow here In case of err we need to append an nilbyte for value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835)*

**Comment by janardhan1993** [comment]
@tzdybal: sorry i forgot to review again after new commits. There's a bug in code, please fix that.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/835#-:-KiB8FnWN7cU_eqmFu2u:boa04bq)*

**Pull request closed without merging**
