### PR TITLE
Feature/indexupdate

### PR DESCRIPTION
**Pull request by gacharya255**
Incremental index update.

Only add index mutations not delete.
Delete only in a separate goroutine that runs periodically like gentle merge.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/614)

### CODE REVIEW

**Comment by gacharya255** [comment]
Updated to undo some changes in list.go: we will delete oldValue -> uid as before. With this change, we now need a test to check UpdateIndex, and we have added one test in posting.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-:-KdVfC3nmlHhzoVibLev:b-css6sx)*

**Comment by manishrjain** [comment]
@janardhan1993 : I think you're taking this over right? If so, can you close this one?

**Comment by janardhan1993** [comment]
But we would need the function to remove stale index entries. We could merge that part and worry about when to trigger this later when we do scheduler. 
The other part which is not in this PR: Adding index/reverse mutation irrespective of whether the pl has mutated or not  has been done in schema_mutation branch

**Comment by janardhan1993** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[group/conf.go, line 185 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-Kh8RTYRpviNZTW7FDhO:-Kh8RTYRpviNZTW7FDhP:b2b82ch) ([raw file](https://github.com/dgraph-io/dgraph/blob/e38c7d5c2a4046d80caee147da70316de48fc134/group/conf.go#L185)):*
> ```Go
> // Ready returns whether group config is parsed.
> func Ready() bool {
> 	return atomic.LoadInt32(&groupConfig.ready) != 0
> ```

This is no longer needed. Let's keep only a function which cleans stale entries as part of this PR. we would decide when to trigger it as part of another PR.

---

*[posting/index.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-Kh8RobR_GENTKbyZEuc:-Kh8RobR_GENTKbyZEud:bav9om4) ([raw file](https://github.com/dgraph-io/dgraph/blob/e38c7d5c2a4046d80caee147da70316de48fc134/posting/index.go#L35)):*
> ```Go
> const (
> 	maxBatchSize        = 32 * (1 << 20)
> 	updateIndexInterval = time.Second * 10
> ```

No longer needed.

---

*[posting/index.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-Kh8UMziYgW-3J7NATER:-Kh8UMziYgW-3J7NATES:b4nrjz0) ([raw file](https://github.com/dgraph-io/dgraph/blob/e38c7d5c2a4046d80caee147da70316de48fc134/posting/index.go#L64)):*
> ```Go
> func (s *indexUpdater) processUID(ctx context.Context, uid uint64) error {
> 	pl, decr := GetOrCreate(x.DataKey(s.attr, uid), s.groupID)
> 	defer decr()
> ```

The idea is to run this only when we detect crash. Either on restart or when the node has lagged behind the leader and we get a snapshot from the leader. In former case lhmap would be empty and in later case we evict the lhmap before installing snapshot. .
the way we are going to trigger it ensures that they are no dirty pl's and lhmap would be empty.
I was wondering do we need to cache this pl or can we read from rocksdb and use it directly ?

---

*[posting/index.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-Kh8SiT-TgYgPtpfqhC2:-Kh8SiT-TgYgPtpfqhC3:bo5vlhr) ([raw file](https://github.com/dgraph-io/dgraph/blob/e38c7d5c2a4046d80caee147da70316de48fc134/posting/index.go#L94)):*
> ```Go
> 	s.indexPl, decr = GetOrCreate(indexKey, s.groupID) // Get index data.
> 	defer decr()
> ```

Again the way we are going to trigger it ensures that they are no dirty pl's and lhmap would be empty.
So we can use GetOrUnmarshal and pass the data directly(which we got while iterating) instead of doing extra call to rocksdb. 

---

*[posting/index.go, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-Kh8SArKe_N1sQ8GQltk:-Kh8SArKe_N1sQ8GQltl:b-x835p) ([raw file](https://github.com/dgraph-io/dgraph/blob/e38c7d5c2a4046d80caee147da70316de48fc134/posting/index.go#L119)):*
> ```Go
> 	ctx := context.Background()
> 	for _, attr := range schema.State().IndexedFields() {
> 		pk.Attr = attr
> ```

it would be good if we refactor this function to do index update per predicate. I am thinking of detecting which predicates can cause index consistency and run it only on those predicates.

---

*[posting/index.go, line 133 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-Kh8RrhQ6YOu8yKoce_7:-Kh8RrhQ6YOu8yKoce_8:b-s3hmk9) ([raw file](https://github.com/dgraph-io/dgraph/blob/e38c7d5c2a4046d80caee147da70316de48fc134/posting/index.go#L133)):*
> ```Go
> 
> // updateIndex iterates over index entries and delete invalid entries.
> func updateIndex() {
> ```

Not needed.

---

*[posting/lists.go, line 337 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/614#-Kh8R1naAYclA2jtNL2f:-Kh8R1nbIjMl0KqY_9x1:bbyb1gg) ([raw file](https://github.com/dgraph-io/dgraph/blob/e38c7d5c2a4046d80caee147da70316de48fc134/posting/lists.go#L337)):*
> ```Go
> 	go periodicCommit()
> 	go batchSync()
> 	go updateIndex()
> ```

Let's have a function which removes stale index, we will trigger it when we detect a crash.
No need of goroutine.  Running a groutine very often would cause cache invalidation in block cache and our pl cache.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/614)*

**Comment by janardhan1993** [comment]
Closing this, will raise new PR

**Comment by janardhan1993** [comment]
Closing this. Will raise new one.

**Pull request closed without merging**
