### PR TITLE
Support long lines in rdf files.

### PR DESCRIPTION
**Pull request by kostub**
Geo data can be very long and overflows the buffer used by the Scanner.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/217)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 115 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1YIlgbyCvDIENvII8:-KS1YIlgbyCvDIENvII9:b17rc0o) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L115)):*
> ```Go
> 	isPrefix := true
> 	var err error
> 	var buff bytes.Buffer
> ```

var buf bytes.Buffer. Also, you should try to reuse this buffer. We're reading lines in a single goroutine serially, so every line can just reuse the underlying capacity created so far. Remember to do a buf.Reset().

---

*[loader/loader.go, line 118 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1_nJUSg9njmfPefYw:-KS1_nJUSg9njmfPefYx:b-w4laod) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L118)):*
> ```Go
> 	for isPrefix && err == nil {
> 		var line []byte
> 		line, isPrefix, err = r.ReadLine()
> ```

I was concerned that this makes a copy, but checked thta it doesn't. In fact, line would stop being valid in the next call. Can you please add a comment here? This is useful to know, because you're copying it over to buffer, so there is a concern about double copying.

Note that in the existing system, scanner.Text() consumes a lot of memory, because it's called for every line of gzipped rdf file.

---

*[loader/loader.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bbjwKYmr2fpxcFKA:-KS1bbjwKYmr2fpxcFKB:buu4u8u) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L136)):*
> ```Go
> 	for i := 0; i < 1000; i++ {
> 		str, err = readLine(bufReader)
> 		if err == nil {
> ```

if err != nil { log.fatal }
// normal handling.

---

*[loader/loader.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bopuTvTjw-04eIi1:-KS1bopuTvTjw-04eIi2:bvs22r4) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L144)):*
> ```Go
> 	}
> 	ln := len(buf)
> 	for err == nil {
> ```

for {
  ... 
  if err != nil {
    log.Fatal
  }
  // normal execution.
}

---

*[loader/loader.go, line 148 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1asBqbqqa7cWwO6Fx:-KS1asBqbqqa7cWwO6Fy:boqjrfj) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L148)):*
> ```Go
> 		s.input <- buf[k]
> 		str, err = readLine(bufReader)
> 		if err == nil {
> ```

instead of check for nil, check for not nil, and do a log fatal. You can use errors.Errorf("", ..) to generate a stack trace.

 err := errors.Errorf("describe the error: %v", something)
log.Fatalf("%+v", err)

---

*[loader/loader.go, line 154 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1b9GPpywBMfgR-2Vf:-KS1b9GPpywBMfgR-2Vg:b7jdfjm) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L154)):*
> ```Go
> 	}
> 	if err != nil && err != io.EOF {
> 		glog.WithError(err).Fatal("While reading file.")
> ```

Switch this to errors package and log Fatal. to generate a stack trace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217)*

**Comment by kostub** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[loader/loader.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bopuTvTjw-04eIi1:-KS2p6uLmQhXu3CHI1pv:bs85769) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L144)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> for {
>   ... 
>   if err != nil {
>     log.Fatal
>   }
>   // normal execution.
> }
</details>
Done. But this makes the code a little awkward, as I had to add an extra if.

---

*[loader/loader.go, line 154 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1b9GPpywBMfgR-2Vf:-KS2v3VLsDxd90FGRQ6_:bxnx3gw) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L154)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Switch this to errors package and log Fatal. to generate a stack trace.
</details>
Not sure if this change is what you meant. There is no errors.Errorf function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217)*

**Comment by manishrjain** [comment]
Can you please mark the done comments as "Done"?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[loader/loader.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bopuTvTjw-04eIi1:-KS4cHkeBAHSNf45Vytl:b4avpha) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L144)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Done. But this makes the code a little awkward, as I had to add an extra if.
</details>
You can do this after the loop. Also have similar comment below.

---

*[loader/loader.go, line 154 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1b9GPpywBMfgR-2Vf:-KS4ba-d8cMKH4nKBxGe:bp4qnba) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L154)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Not sure if this change is what you meant. There is no errors.Errorf function.
</details>
Actually, use x.Errorf. Though, an ack over the code base should have shown you the usage.

---

*[loader/loader.go, line 148 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS4bxxqviMDZwiuLh91:-KS4bxxqviMDZwiuLh92:blxn39g) ([raw file](https://github.com/dgraph-io/dgraph/blob/2afac65c22c23bca6b4b7aba062c5b10c9ad445d/loader/loader.go#L148)):*
> ```Go
> 		atomic.AddUint64(&s.ctr.read, 1)
> 	}
> 	ln := len(buf)
> ```

You're using this variable only once, from what I can see. If so, remove.

---

*[loader/loader.go, line 163 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS4bnfcofXXSOa7VAk5:-KS4bnfcofXXSOa7VAk6:bzajhdi) ([raw file](https://github.com/dgraph-io/dgraph/blob/2afac65c22c23bca6b4b7aba062c5b10c9ad445d/loader/loader.go#L163)):*
> ```Go
> 		}
> 	}
> 	if err != nil && err != io.EOF {
> ```

Always tackle the smaller condition first, particularly if it's going to fatal or return.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-:-KS4cMp3KER1l734e626:b18f86b)*

**Comment by kostub** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KRgslO5ZlhYx3WAHW0A-r1-114:-KS4wbWOZVtWy00_C2Od:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/171b4f26e4feb9822c324fe59aa547f320e3725e/loader/loader.go#L114)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> should drop = nil from declaration of var err; it is the zero value
</details>
Done.

---

*[loader/loader.go, line 115 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1YIlgbyCvDIENvII8:-KS4wgJXILwgakkHwA25:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L115)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> var buf bytes.Buffer. Also, you should try to reuse this buffer. We're reading lines in a single goroutine serially, so every line can just reuse the underlying capacity created so far. Remember to do a buf.Reset().
</details>
Done.

---

*[loader/loader.go, line 118 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1_nJUSg9njmfPefYw:-KS4wjqv_rJX1lE6Cnbj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L118)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I was concerned that this makes a copy, but checked thta it doesn't. In fact, line would stop being valid in the next call. Can you please add a comment here? This is useful to know, because you're copying it over to buffer, so there is a concern about double copying.
> 
> Note that in the existing system, scanner.Text() consumes a lot of memory, because it's called for every line of gzipped rdf file.
</details>
Done.

---

*[loader/loader.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bbjwKYmr2fpxcFKA:-KS4wnE0FetdpGAsDCa9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> if err != nil { log.fatal }
> // normal handling.
</details>
Done.

---

*[loader/loader.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bopuTvTjw-04eIi1:-KS5o6GedcT15xvdy43f:b2jym9w) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L144)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can do this after the loop. Also have similar comment below.
</details>
I meant I need to wrap the for loop in the if statement. The previous version was clearer.

---

*[loader/loader.go, line 148 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1asBqbqqa7cWwO6Fx:-KS4x78XESokuBMnbY8S:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L148)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> instead of check for nil, check for not nil, and do a log fatal. You can use errors.Errorf("", ..) to generate a stack trace.
> 
>  err := errors.Errorf("describe the error: %v", something)
> log.Fatalf("%+v", err)
</details>
Done.

---

*[loader/loader.go, line 154 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1b9GPpywBMfgR-2Vf:-KS5ov33QnRngHuDHuEs:buf9z0d) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L154)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Actually, use x.Errorf. Though, an ack over the code base should have shown you the usage.
</details>
Done. Though most other places we use fmt.Errorf or glog.

---

*[loader/loader.go, line 148 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS4bxxqviMDZwiuLh91:-KS5pPJMvg6WFx9hhL-G:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/2afac65c22c23bca6b4b7aba062c5b10c9ad445d/loader/loader.go#L148)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You're using this variable only once, from what I can see. If so, remove.
</details>
Done

---

*[loader/loader.go, line 163 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS4bnfcofXXSOa7VAk5:-KS5ouRSgxYD-AnsjvWf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2afac65c22c23bca6b4b7aba062c5b10c9ad445d/loader/loader.go#L163)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Always tackle the smaller condition first, particularly if it's going to fatal or return.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bopuTvTjw-04eIi1:-KS708J158igXRQtlLrh:b-togb2n) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L144)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> I meant I need to wrap the for loop in the if statement. The previous version was clearer.
</details>
Not sure what the prev version was. I think what I'm trying to say is, you can avoid the for loop in the if statement, by checking for err != nil { log.Fatal } first.

---

*[loader/loader.go, line 163 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS4bnfcofXXSOa7VAk5:-KS7-md5q9CIpT0lJ7t2:b-n60azd) ([raw file](https://github.com/dgraph-io/dgraph/blob/2afac65c22c23bca6b4b7aba062c5b10c9ad445d/loader/loader.go#L163)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Done.
</details>
It's not done. This should have been before the `if err == nil { ... }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217)*

**Comment by kostub** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 144 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS1bopuTvTjw-04eIi1:-KS8tNdzWfQjpyJSjvtk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/090027a2952518bb3ce831dd789d7677be82ef99/loader/loader.go#L144)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Not sure what the prev version was. I think what I'm trying to say is, you can avoid the for loop in the if statement, by checking for err != nil { log.Fatal } first.
</details>
Done.

---

*[loader/loader.go, line 163 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS4bnfcofXXSOa7VAk5:-KS8tMfCnYMxRgqPASJy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2afac65c22c23bca6b4b7aba062c5b10c9ad445d/loader/loader.go#L163)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> It's not done. This should have been before the `if err == nil { ... }`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217)*

**Comment by kostub** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 163 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KS4bnfcofXXSOa7VAk5:-KS8tUhEEfz-tHQ2GIiX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2afac65c22c23bca6b4b7aba062c5b10c9ad445d/loader/loader.go#L163)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217)*

**Comment by manishrjain** [comment]
:lgtm: One small comment, and this is good to go!

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 154 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KSAZu-KVul0DQiMT5YV:-KSAZu-KVul0DQiMT5YW:b-hw4yzq) ([raw file](https://github.com/dgraph-io/dgraph/blob/87032877e0b758416c588c0ba3f7ac7ac6465dff/loader/loader.go#L154)):*
> ```Go
> 
> 	// If we haven't yet finished reading the file
> 	// read the rest of the rows.
> ```

You can probably fit this comment in the above line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-:-KSAZyFCQWbSGGqJmXwQ:b-h1ibiv)*

**Comment by kostub** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 154 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/217#-KSAZu-KVul0DQiMT5YV:-KSAwW6VCJPZbFSPMZqM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87032877e0b758416c588c0ba3f7ac7ac6465dff/loader/loader.go#L154)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can probably fit this comment in the above line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/217)*

**Pull request closed without merging**
