### PR TITLE
Support not operator in filters

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/530)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[algo/uidlist.go, line 118 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJHJ4av1Fadpnz2ovj:-KbJHJ4b4khS-PfSYwjZ:b-x0z2la) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/algo/uidlist.go#L118)):*
> ```Go
> }
> 
> func Subtract(u, v *task.List) {
> ```

Difference

---

*[gql/parser.go, line 103 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJHmanIfXzOkyM-QpR:-KbJHmaoGB9DPQ9zXfES:b-97ujps) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L103)):*
> ```Go
> 
> func init() {
> 	filterOpPrecedence = map[string]int{
> ```

map[rune]int

---

*[gql/parser.go, line 106 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJICV4itDQAVxza1rA:-KbJICV4itDQAVxza1rB:byf9wi1) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L106)):*
> ```Go
> 		"&": 3,
> 		"|": 2,
> 		"!": 1,
> ```

! should be 3. Higher is higher precedence.

---

*[gql/parser.go, line 900 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJLGebPFasFTmGf87j:-KbJLGebPFasFTmGf87k:bfsp5qz) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L900)):*
> ```Go
> 			if lval == "or" {
> 				op = "|"
> 			} else if lval == "not" {
> ```

There's no need for conversion from string -> rune. So, keep it string, and use these directly.

---

*[gql/parser.go, line 953 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJLVEu4sFwcDtpMZP1:-KbJLVEu4sFwcDtpMZP2:bsj5li2) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L953)):*
> ```Go
> 				evalStack(opStack, valueStack)
> 			}
> 		} else if item.Typ == itemLeftRound { // Just push to op stack.
> ```

Add comments everywhere.

---

*[gql/state.go, line 129 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJLjeP35gedRRN7YNg:-KbJLjeP35gedRRN7YNh:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/state.go#L129)):*
> ```Go
> 			empty = true
> 			l.Ignore()
> 		/*
> ```

Remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/530)*

**Comment by ashwin95r** [comment]
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[algo/uidlist.go, line 118 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJHJ4av1Fadpnz2ovj:-KbJPb5Yr9BeFYCB-jv3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/algo/uidlist.go#L118)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Difference
</blockquote></details>

Done.

---

*[gql/parser.go, line 103 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJHmanIfXzOkyM-QpR:-KbJNkb8RG-Y0TW0vJxO:b-1rti23) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L103)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

map[rune]int
</blockquote></details>

Having it as string as we decided to use "and", "or", "not"

---

*[gql/parser.go, line 106 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJICV4itDQAVxza1rA:-KbJNsLvSz93NgvVu-d0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L106)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

! should be 3. Higher is higher precedence.
</blockquote></details>

Done.

---

*[gql/parser.go, line 900 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJLGebPFasFTmGf87j:-KbJNtd9INqkQLdluHsd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L900)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

There's no need for conversion from string -> rune. So, keep it string, and use these directly.
</blockquote></details>

Done.

---

*[gql/parser.go, line 953 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJLVEu4sFwcDtpMZP1:-KbJRQjnR_MIFiCl77Tw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/parser.go#L953)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add comments everywhere.
</blockquote></details>

Done.

---

*[gql/state.go, line 129 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJLjeP35gedRRN7YNg:-KbJO3nUodSTsLZgk4wr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7491095b58001becf0147ddb68530afa4e13d17/gql/state.go#L129)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/530)*

**Comment by ashishnegi** [comment]
Review status: 4 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[gql/parser.go, line 795 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJX3NYxhW9FnQyszo5:-KbJX3NZ8-D5jecp8MTl:b678382) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/gql/parser.go#L795)):*
> ```Go
> 		_, err = buf.WriteString("OR")
> 	case "not":
> 		_, err = buf.WriteString("NOT")
> ```

err is always `nil` in bytes.Buffer's Write* fns.
it panics if something is wrong.
https://golang.org/pkg/bytes/#Buffer.Write

---

*[gql/parser.go, line 971 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJaGzA7bj7aUZSWXIk:-KbJaGzBj1nOm-qKVUSp:b1xg27y) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/gql/parser.go#L971)):*
> ```Go
> 				break
> 			}
> 			// If the top operator was a "not" it has to be applied immediately to the
> ```

why do we need special case for "not" ? or anything with highest precedence ?

---

*[gql/parser_test.go, line 1039 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJYpEqJOrA_W20Dl8B:-KbJYpEswjTBOhnD29TN:bnaxun) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/gql/parser_test.go#L1039)):*
> ```Go
> 	query {
> 		me(id:0x0a) {
> 			friends @filter((a("a") Or b("a"))
> ```

Should this be `or` ?

---

*[query/query.go, line 790 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJZ7fCzRF821qikDuJ:-KbJZ7fCzRF821qikDuK:bxobi87) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/query/query.go#L790)):*
> ```Go
> 			algo.Difference(sg.DestUIDs, sg.Filters[0].DestUIDs)
> 		} else {
> 			// If one of the arguments was id so append it once more
> ```

we can remove the comment if code is commented..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/530)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-:-KbJlhkYY_gxO_6NFDAc:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 4 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[gql/parser.go, line 795 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJX3NYxhW9FnQyszo5:-KbJmQ4hmgYAL9HWkIc9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/gql/parser.go#L795)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

err is always `nil` in bytes.Buffer's Write* fns.
it panics if something is wrong.
https://golang.org/pkg/bytes/#Buffer.Write
</blockquote></details>

Done.

---

*[gql/parser.go, line 971 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJaGzA7bj7aUZSWXIk:-KbJnB5ybpCohOYEPkcJ:b7vdnxt) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/gql/parser.go#L971)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

why do we need special case for "not" ? or anything with highest precedence ?
</blockquote></details>

Just realized that this would be automatically handled by the precedence loop. Done.

---

*[gql/parser_test.go, line 1039 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJYpEqJOrA_W20Dl8B:-KbJm-8p0RHu90zfPKP8:b-8dtlrx) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/gql/parser_test.go#L1039)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Should this be `or` ?
</blockquote></details>

it could be anything. We do a ToLowercase() before checking. So this test is intentional to check that feature.

---

*[query/query.go, line 790 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-KbJZ7fCzRF821qikDuJ:-KbJm8EO6My8zUhtfgdK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/53ac07c435a59ebd678b23c24c47f682e1e205f9/query/query.go#L790)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

we can remove the comment if code is commented..
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/530)*

**Comment by ashishnegi** [comment]
:lgtm: :+1: 

---

Review status: 4 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/530#-:-KbJpSTjp1uLbRML-n8C:b-8sos09)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
