### PR TITLE
Fix parsing int. Use SyncPool for pathInfo

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1210)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/shortest.go, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-KpNOIYzawc5nUziXI9k:-KpNOIYzawc5nUziXI9l:bf23k95) ([raw file](https://github.com/dgraph-io/dgraph/blob/857c58fa46a52ce309105e5f06a5d1e368b8d4b4/query/shortest.go#L53)):*
> ```Go
> }
> 
> var pathPool = sync.Pool{
> ```

Do we need to use sync pool for this ?

---

*[query/shortest.go, line 368 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-KpNO9tLjbxVLutErcGt:-KpNO9tLjbxVLutErcGu:b-7vf9md) ([raw file](https://github.com/dgraph-io/dgraph/blob/857c58fa46a52ce309105e5f06a5d1e368b8d4b4/query/shortest.go#L368)):*
> ```Go
> 			if cap(curPath) < len(item.path.route)+1 {
> 				// We can't use it due to insufficient capacity. Put it back.
> 				pathPool.Put(curPath)
> ```

curpath = curpath[:0] before putting it back to pool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-:-KpNOG9p0siaoS2Li_At:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/shortest.go, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-KpNOIYzawc5nUziXI9k:-KpNOqaN0yr4avt1UBio:b-d7jc0j) ([raw file](https://github.com/dgraph-io/dgraph/blob/857c58fa46a52ce309105e5f06a5d1e368b8d4b4/query/shortest.go#L53)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Do we need to use sync pool for this ?
</blockquote></details>

Yes, We create a path slice for each node that we visit, which is a lot. Also, willcj reported  that he saw many allocations for curPath.

---

*[query/shortest.go, line 368 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-KpNO9tLjbxVLutErcGt:-KpNP9B1XBfv-edtQyFq:b-6dxo5a) ([raw file](https://github.com/dgraph-io/dgraph/blob/857c58fa46a52ce309105e5f06a5d1e368b8d4b4/query/shortest.go#L368)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

curpath = curpath[:0] before putting it back to pool
</blockquote></details>

We reset the length when we get from the pool, so it's not required to set it to [:0]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[query/shortest.go, line 372 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-KpNPPtiQu-H8BKir8uJ:-KpNPPtiQu-H8BKir8uK:bmsfzie) ([raw file](https://github.com/dgraph-io/dgraph/blob/857c58fa46a52ce309105e5f06a5d1e368b8d4b4/query/shortest.go#L372)):*
> ```Go
> 			} else {
> 				// Use the curPath from pathPool. Set length appropriately.
> 				curPath = curPath[:len(item.path.route)+1]
> ```

We set the length here while getting from the pool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[worker/mutation.go, line 390 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-KpQwBZUosu4638oQFMe:-KpQwBZUosu4638oQFMf:b8ua8pv) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c4a42589cd9acf4ec75af93e2a18d85d6b1cf18/worker/mutation.go#L390)):*
> ```Go
> 	var e error
> 	for i := 0; i < len(mutationMap); i++ {
> 		if err := <-errors; err != nil {
> ```

Call it errorCh instead of errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-:-KpQwH3zelhs9_kiSm4l:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[worker/mutation.go, line 390 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210#-KpQwBZUosu4638oQFMe:-KpSRk8O2fIJqnzW7wIb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c4a42589cd9acf4ec75af93e2a18d85d6b1cf18/worker/mutation.go#L390)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Call it errorCh instead of errors.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1210)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
