### PR TITLE
k8s manifest files are updated to reflect the new defaults.

### PR DESCRIPTION
**Pull request by sboorlagadda**
* updated manifest files to reflect new defaults
  * removed XID reference as it is now not supported

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2077)

### CODE REVIEW

**Comment by sboorlagadda** [comment]
This change is part of #2042

**Comment by sboorlagadda** [comment]
this should fix #2003

**Comment by pawanrawal** [comment]
:lgtm: nice changes @sboorlagadda! Not sure if we need `type: LoadBalancer` if there is only one replica but one could argue that it allows increasing replicas easily. 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[contrib/config/kubernetes/dgraph-multi.yaml, line 67 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2077#-L4KR3su0yqOUkwxO9ts:-L4KR3su0yqOUkwxO9tt:buqq2a6) ([raw file](https://github.com/dgraph-io/dgraph/blob/93e0ed0cff6112b616fe5b1901288d5d31a83c32/contrib/config/kubernetes/dgraph-multi.yaml#L67)):*
> ```YAML
>     app: dgraph-ratel
> spec:
>   type: LoadBalancer
> ```

LoadBalancer here is not required?

---

*[contrib/config/kubernetes/dgraph-single.yaml, line 9 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2077#-L4KQJJSvPxz3jZ_Qdu7:-L4KQJJSvPxz3jZ_Qdu8:bnvmyyi) ([raw file](https://github.com/dgraph-io/dgraph/blob/93e0ed0cff6112b616fe5b1901288d5d31a83c32/contrib/config/kubernetes/dgraph-single.yaml#L9)):*
> ```YAML
>     app: dgraph
> spec:
>   type: LoadBalancer
> ```

Probably doesn't need to be of type LoadBalancer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2077#-:-L4KRtBkrnoRyfnNWPpK:b-2itvr4)*

**Comment by sboorlagadda** [comment]
Also when deployed on most cloud providers, `LoadBalancer` is the easiest way to expose a service to outside world.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2077#-:-L4MhRKGXB6BggnTmn9q:bq1tw0e)*

**Comment by pawanrawal** [comment]
Let's not merge this yet and do it just before the release(which should happen this week). Otherwise, it would cause confusion for those who are using the latest version.

**Pull request merged**
