### PR TITLE
Support basic variables

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/490)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Fix the comments, then LGTM. Talk to Ashish about the JSON stuff.

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 447 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_OFzcSUIfT_lywzIn:-Ka_OFzcSUIfT_lywzIo:b8ks9eb) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/cmd/dgraph/main.go#L447)):*
> ```Go
> 	}
> 
> 	if len(res.Query) == 0 {
> ```

Add a test to pass in multiple empty blocks in the same query.

---

*[gql/parser.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_P_Ph8OjO9uEmLpKj:-Ka_P_Ph8OjO9uEmLpKk:b6rstay) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L39)):*
> ```Go
> 	Alias      string
> 	IsCount    bool
> 	VarDefList []string
> ```

Remove this for now.

---

*[gql/parser.go, line 40 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_PfAZoOHbDmZDU2Y4:-Ka_PfAZoOHbDmZDU2Y5:b2nhqle) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L40)):*
> ```Go
> 	IsCount    bool
> 	VarDefList []string
> 	VarDef     string
> ```

Var

---

*[gql/parser.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_PhEvTBt7w8K7utAn:-Ka_PhEvTBt7w8K7utAo:b-jfqhzl) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L41)):*
> ```Go
> 	VarDefList []string
> 	VarDef     string
> 	VarUse     string
> ```

NeedsVar

---

*[gql/parser.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Q3PJVuJj00ddca5Q:-Ka_Q3PJVuJj00ddca5R:biyootw) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L110)):*
> ```Go
> // DebugPrint is useful for debugging.
> func (gq *GraphQuery) DebugPrint(prefix string) {
> 	fmt.Printf("%s[%x %q %q->%q]\n", prefix, gq.UID, gq.Attr, gq.Alias)
> ```

x.Printf

---

*[gql/parser.go, line 346 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Qdg1UAVg_FVTDsAI:-Ka_Qdg1UAVg_FVTDsAJ:b-hfpv23) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L346)):*
> ```Go
> 	}
> 
> 	//definedBy := make(map[string]*GraphQuery)
> ```

remove.

---

*[gql/parser.go, line 359 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_QjCtDfLUUVYNpV4Q:-Ka_QjCtDfLUUVYNpV4R:b-hfpv23) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L359)):*
> ```Go
> 			}
> 
> 			// Store variables at root and create dependancy list.
> ```

remove.

---

*[gql/parser.go, line 367 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_QtpoDLKLHnzxPz_c:-Ka_QtppA-4niJLfGzHl:b1ojd6u) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L367)):*
> ```Go
> }
> 
> func collectVariables(root, qu *GraphQuery) {
> ```

remove for now.

---

*[gql/parser.go, line 976 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_R8t6slAOibEP_xkq:-Ka_R8t6slAOibEP_xkr:bcpegs5) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L976)):*
> ```Go
> 	}
> 	if peekItems[1].Typ == itemRightRound {
> 		// Temporary format for using a variable.
> ```

remove the comment.

---

*[gql/parser_test.go, line 38 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_RvkqdodHa5uteokH:-Ka_RvkqdodHa5uteokI:b-1446me) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser_test.go#L38)):*
> ```Go
> 	query := `
> 	{	
> 		me(L) {
> ```

Create a task to support `(L, J, K)` or `([L, J, K])`

---

*[gql/parser_test.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_S9E5cgpV89W-U7F8:-Ka_S9E5cgpV89W-U7F9:b-t1najw) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser_test.go#L94)):*
> ```Go
> 	require.Equal(t, "L", res.Query[1].VarUse)
> 	//	require.Equal(t, 0, len(res.Deps[0]))
> 	//	require.Equal(t, 1, len(res.Deps[1]))
> ```

Remove the comments.

---

*[query/query.go, line 126 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_SRmtOFPNKxSVmE2Z:-Ka_SRmtOFPNKxSVmE2_:b-ee0ulr) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L126)):*
> ```Go
> 	OrderDesc bool
> 	isDebug   bool
> 	VarDef    string
> ```

Var and NeedsVar

---

*[query/query.go, line 529 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_T6T6Rb6zsTUvG-E9:-Ka_T6T6Rb6zsTUvG-EA:b-cl63y3) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L529)):*
> ```Go
> 		for idx := 0; idx < len(sgl); idx++ {
> 			sg := sgl[idx]
> 			if sg.Params.VarUse != "" {
> ```

Don't need this cond check. Move it in the if below.

---

*[query/query.go, line 530 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_TTjT971CkNvI17Yn:-Ka_TTjT971CkNvI17Yo:b-fmtq25) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L530)):*
> ```Go
> 			sg := sgl[idx]
> 			if sg.Params.VarUse != "" {
> 				if _, ok := varUidList[sg.Params.VarUse]; !ok || hasExecuted[idx] {
> ```

doneVars

---

*[query/query.go, line 535 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_T2AsQtGySWAVRaNx:-Ka_T2AsQtGySWAVRaNy:bsfs7gt) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L535)):*
> ```Go
> 				fillUpVariables(sg, varUidList)
> 			}
> 			if hasExecuted[idx] {
> ```

move this up a block.

---

*[query/query.go, line 540 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_TZdJ4cbP__f4y4WT:-Ka_TZdJ4cbP__f4y4WU:ba3dfmt) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L540)):*
> ```Go
> 			hasExecuted[idx] = true
> 			idxList = append(idxList, idx)
> 			count++
> ```

Remove.

---

*[query/query.go, line 541 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Tcf-T89Z26nOAMCT:-Ka_Tcf-T89Z26nOAMCU:b-7ecrd) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L541)):*
> ```Go
> 			idxList = append(idxList, idx)
> 			count++
> 			numQueryExecuted++
> ```

numQueriesDone

---

*[query/query_test.go, line 325 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Tw-5H2u7lfJfUYI3:-Ka_Tw-64FEYjMNjf07W:b-7jbqan) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query_test.go#L325)):*
> ```Go
> 			var(id:0x01) {
> 				L AS friend 
> 				
> ```

space

---

*[query/query_test.go, line 2012 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_TydBDcZSvOlDOc9n:-Ka_TydBDcZSvOlDOc9o:b4qx3r8) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query_test.go#L2012)):*
> ```Go
>         name
>         gender
> 			}
> ```

formatting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-:-Ka_UAGxqHtawXtuNbIZ:bf1qxt)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 447 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_OFzcSUIfT_lywzIn:-Ka_Yj9nhX4jJjm7dd96:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/cmd/dgraph/main.go#L447)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a test to pass in multiple empty blocks in the same query.
</blockquote></details>

Done.

---

*[gql/parser.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_P_Ph8OjO9uEmLpKj:-Ka_UiM89MQURtL88qLB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove this for now.
</blockquote></details>

Done.

---

*[gql/parser.go, line 40 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_PfAZoOHbDmZDU2Y4:-Ka_UoquYpSyA5tl4VW8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Var
</blockquote></details>

Done.

---

*[gql/parser.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_PhEvTBt7w8K7utAn:-Ka_UqKmfCu498akLVu1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

NeedsVar
</blockquote></details>

Done.

---

*[gql/parser.go, line 110 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Q3PJVuJj00ddca5Q:-Ka_UtjqQa4zA2CSdUZA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L110)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

x.Printf
</blockquote></details>

Done.

---

*[gql/parser.go, line 346 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Qdg1UAVg_FVTDsAI:-Ka_Uv78rLqKelIhMDar:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L346)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

---

*[gql/parser.go, line 359 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_QjCtDfLUUVYNpV4Q:-Ka_UvekVGQAY1cJYvEz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L359)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

---

*[gql/parser.go, line 367 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_QtpoDLKLHnzxPz_c:-Ka_Uw4J167JktFXRLHN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L367)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove for now.
</blockquote></details>

Done.

---

*[gql/parser.go, line 976 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_R8t6slAOibEP_xkq:-Ka_UzpFAQ3SD2GvYM1g:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser.go#L976)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove the comment.
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 38 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_RvkqdodHa5uteokH:-Ka_V3AwKGRu6rVrt1bb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser_test.go#L38)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a task to support `(L, J, K)` or `([L, J, K])`
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_S9E5cgpV89W-U7F8:-Ka_VZSAMEua2KyZD7_I:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/gql/parser_test.go#L94)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove the comments.
</blockquote></details>

Done.

---

*[query/query.go, line 126 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_SRmtOFPNKxSVmE2Z:-Ka_WBx6ZFlEXcNtqnGB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L126)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Var and NeedsVar
</blockquote></details>

Done.

---

*[query/query.go, line 529 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_T6T6Rb6zsTUvG-E9:-Ka_WgU0xXaIHKcQoHZo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L529)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't need this cond check. Move it in the if below.
</blockquote></details>

Done.

---

*[query/query.go, line 530 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_TTjT971CkNvI17Yn:-Ka_WlR1my-DO5ymWKi5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L530)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

doneVars
</blockquote></details>

Done.

---

*[query/query.go, line 535 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_T2AsQtGySWAVRaNx:-Ka_Wm2axbDV2pzQE_Sr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L535)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move this up a block.
</blockquote></details>

Done.

---

*[query/query.go, line 540 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_TZdJ4cbP__f4y4WT:-Ka_WmW5Wo0tul0vQDzs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L540)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---

*[query/query.go, line 541 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Tcf-T89Z26nOAMCT:-Ka_WubMDptlYsLs5e0O:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query.go#L541)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

numQueriesDone
</blockquote></details>

Done.

---

*[query/query_test.go, line 325 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_Tw-5H2u7lfJfUYI3:-Ka_XAK0b1QBNMzVL96X:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query_test.go#L325)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.

---

*[query/query_test.go, line 2012 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-Ka_TydBDcZSvOlDOc9n:-Ka_XO3YfZU77sqQ8DIu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078de6df7adef82294dbb87d5fcb18f90c44eecd/query/query_test.go#L2012)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

formatting.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/490)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 1 of 5 files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/490#-:-KaaHLZerS2AI1pBFgzt:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
