### PR TITLE
fix(worker): fix between filter for non indexed predicates

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
Fixes DGRAPH-2528.
Fixes DGRAPH-2544.

This PR extends the support for `between` filter on non-indexed predicates so that it could be used outside the root also. For example, for the given schema
```
type CarModel {
	make
	model
	year
}
model                          : string @index(term) @lang .
make                           : string @index(term) .
year                           : int .
```
The below query uses between filter on `year` predicate which is non-indexed, should be valid.
```
queryCareModel(func: type(CarModel)) @filter(between(year,2009,2010)){
				make
				model
				year
			}
```
This PR also fixes the `eq` filter for more than one argument on the non-indexed predicate which earlier used to compare with just the first of the given arguments for `eq` filter. For eg the below query was not giving proper results earlier.
```
queryCarModel(func: type(CarModel)) @filter(eq(year,2008,2009)){
				make
				model
				year
			}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6715)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6715)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @manishrjain, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

___
*[query/query0_test.go, line 3295 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWoqGU5IgQelq-ETTg:-MJWoqGU5IgQelq-ETTh:b-c0huqo) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/query/query0_test.go#L3295)):*
> ```Go
> 		`
> 		{
> 			me(func: type(CarModel)) @filter(between(year,2009,2010)){
> ```

Also, add a test where `between` is used in a filter on a child node.

```
{

  me(users) {
    car @filter(between(....)) {
      make
       model
    }
  }

}
```
___
*[worker/task.go, line 463 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWpN4RB39S1s3xrxef:-MJWpN4RB39S1s3xrxeg:b-d25ya0) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/worker/task.go#L463)):*
> ```Go
> 						}
> 					case "between":
> 						if types.CompareVals("ge", val, srcFn.eqTokens[0]) &&
> ```

Can we add a function for this check and use it both here and at the root?
___
*[worker/task.go, line 466 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWqHBS2LSOCJ7Q8Jr_:-MJWqHBS2LSOCJ7Q8Jra:bpp6stj) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/worker/task.go#L466)):*
> ```Go
> 							types.CompareVals("le", val, srcFn.eqTokens[1]) {
> 							uidList.Uids = append(uidList.Uids, q.UidList.Uids[i])
> 							break
> ```

not needed
___
*[worker/task.go, line 471 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWqIVc5U-mif0Yn5j3:-MJWqIVd8vwcThoYTr7J:bpp6stj) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/worker/task.go#L471)):*
> ```Go
> 						if types.CompareVals(srcFn.fname, val, srcFn.eqTokens[0]) {
> 							uidList.Uids = append(uidList.Uids, q.UidList.Uids[i])
> 							break
> ```

not needed

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6715)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[query/query0_test.go, line 3295 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWoqGU5IgQelq-ETTg:-MJXRB7QBrIbn3MTd8OH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/query/query0_test.go#L3295)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Also, add a test where `between` is used in a filter on a child node.

```
{

  me(users) {
    car @filter(between(....)) {
      make
       model
    }
  }

}
```
</blockquote></details>

Done.
___
*[worker/task.go, line 463 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWpN4RB39S1s3xrxef:-MJXRCu45xNtl9XjNUyQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/worker/task.go#L463)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we add a function for this check and use it both here and at the root?
</blockquote></details>

Done.
___
*[worker/task.go, line 466 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWqHBS2LSOCJ7Q8Jr_:-MJXRDGa66lRWiRx8Sxs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/worker/task.go#L466)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[worker/task.go, line 471 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJWqIVc5U-mif0Yn5j3:-MJXRDnR8-AOm9Y-5VRN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e1e184b580661372909b551380752260ca53dfc1/worker/task.go#L471)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6715)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @manishrjain, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

___
*[query/query0_test.go, line 3295 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJ_gPZC44iRY_sgqigY:-MJ_gPZC44iRY_sgqigZ:b922m6a) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8eb4f74d19c1981469086be30bed67e98083545/query/query0_test.go#L3295)):*
> ```Go
> 			`Test Between on Indexed Predicate`,
> 			`{
> 				me(func :has(newname))  @filter(eq(newname,"P1","P3")){
> ```

these queries are not using `between`, did you intend to use `between` instead of `eq`.

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6715)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[query/query0_test.go, line 3295 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6715#-MJ_gPZC44iRY_sgqigY:-MJa-J465QlvZc7Grg88:b-avqk6p) ([raw file](https://github.com/dgraph-io/dgraph/blob/b8eb4f74d19c1981469086be30bed67e98083545/query/query0_test.go#L3295)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

these queries are not using `between`, did you intend to use `between` instead of `eq`. 
</blockquote></details>

Sorry for the mistake, I have corrected it.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6715)* status: all files reviewed, 2 unresolved discussions (waiting on @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

**Pull request merged**
