### PR TITLE
Adding 6th tutorial and other necessary changes

### PR DESCRIPTION
**Pull request by prashant-shahi**
This PR is dependent on https://github.com/dgraph-io/hugo-docs/pull/42.

- Using load-img shortcode for appropriate image versioning
- Using relref for appropriate versioning of other docs link
- Added necessary CSS files for blockquote styling
- Using a consistent size of headers across all tutorials

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4407)

### CODE REVIEW

**Comment by danielmai** [comment]
@zhenniwu I tried on my machine and it worked as expected. Seems like an issue with the Hugo version.

I tried with this version and it worked:
```
Hugo Static Site Generator v0.58.3/extended darwin/amd64 BuildDate: unknown
```

And tried with the latest version and I see exactly what @zhenniwu sees.
```
Hugo Static Site Generator v0.61.0/extended darwin/amd64 BuildDate: unknown
```

**Comment by prashant-shahi** [comment]
@danielmai, are we upgrading Hugo to the latest version for docs site?

I wouldn't recommend that unless we have some solid understanding of what are the things that could potentially break and have their fixes.

**Comment by prashant-shahi** [comment]
There is a small fix for that particular issue. But the code highlighting of markdown has also been altered.

Check out the CHANGELOG of v0.60 from which both of the above changes seem to have occurred:
https://github.com/gohugoio/hugo/releases/tag/v0.60.0

**Comment by prashant-shahi** [comment]
@campoy  @zhenniwu need this PR to be reviewed.

**Comment by prashant-shahi** [comment]
Announcement blog is dependent on this PR so, I will be merging it for now.
Any required changes for these should go along with future changes.

**Pull request merged**
