### PR TITLE
fix(bulk load): panic: z.Buffer max size exceeded

### PR DESCRIPTION
**Pull request by bytzster**
(stack trace from release v21.12.0)
```
panic: z.Buffer max size exceeded: 68719476736 offset: 68719476724 grow: 50

goroutine 12167 [running]:
github.com/dgraph-io/ristretto/z.(*Buffer).Grow(0xc02c4a4000, 0x32)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20210824115121-89e99415887a/z/buffer.go:180 +0x56e
github.com/dgraph-io/ristretto/z.(*Buffer).SliceAllocate(0xc02c4a4000, 0x2e)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20210824115121-89e99415887a/z/buffer.go:266 +0x2e
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapIterator).Next(0xc027cfaf60, 0xc02c4a4000, {0xc00378fd00, 0x1f, 0x20})
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:206 +0x127
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).reduce.func2()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:488 +0x5cd
created by github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).reduce
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:478 +0x465
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/8112)

### CODE REVIEW

**Review by danielmai — DISMISSED** [review]
Thanks for the PR, @JoelWesleyReed. It looks good to me.

Once the CLA is signed it's good to merge.

You must be loading some huge dataset to hit this panic!

**Comment by mangalaman93** [comment]
@JoelWesleyReed if you are still interested in merging this change, could you rebase on latest main please and sign the CLA? Thanks

**Comment by davideaimar** [comment]
I encountered the same problem trying to bulk import a huge dataset and this PR fixed the max size panic. Is it possible to merge it? Otherwise @mangalaman93 I can open a new PR.

**Comment by mangalaman93** [comment]
Yeah, you'll have to cherry pick your changes on main instead of master. You should still be able to force push to the same branch. You are welcome to create another PR too.

**Pull request closed without merging**
