### PR TITLE
Change how facets are set and retrieved

### PR DESCRIPTION
**Pull request by pawanrawal**
New response format is flatter.

```
{
    "data": {
        "me": [
            {
                "friend": [
                    {
                        "name:origin": "french",
                        "name": "Rick Grimes",
                        "friend:since": "2006-01-02T15:04:05Z"
                    },
                    {
                        "name:origin": "french",
                        "name": "Glenn Rhee",
                        "friend:close": true,
                        "friend:family": true,
                        "friend:since": "2004-05-02T15:04:05Z",
                        "friend:tag": "Domain3"
                    },
                    {
                        "name": "Daryl Dixon",
                        "friend:close": false,
                        "friend:family": true,
                        "friend:since": "2007-05-02T15:04:05Z",
                        "friend:tag": 34
                    },
                    {
                        "name": "Andrea",
                        "friend:since": "2006-01-02T15:04:05Z"
                    },
                    {
                        "friend:age": 33,
                        "friend:close": true,
                        "friend:family": false,
                        "friend:since": "2005-05-02T15:04:05Z"
                    }
                ]
            }
        ]
    }
}
```

- [x] Fix other query tests broken by this change.
- [ ] Fix UI.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1730)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[dgraph/server.go, line 445 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-KyJP8EsQ9tKRCc-POsQ:-KyJP8EsQ9tKRCc-POsR:b-omc6cg) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0d4ab08fc4c849c7187f901900bb80d0482014b/dgraph/server.go#L445)):*
> ```Go
> 		}
> 
> 		keys := strings.Split(fname, ":")
> ```

No need to split. Just use len(prefix).

---

*[dgraph/server.go, line 560 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-KyJQa3rVPNBMWYXykJ8:-KyJQa3rVPNBMWYXykJ9:b-rof7ve) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0d4ab08fc4c849c7187f901900bb80d0482014b/dgraph/server.go#L560)):*
> ```Go
> 
> // TODO - Abstract these parameters to a struct.
> func mapToNquads(m map[string]interface{}, idx *int, op int, k string) (mapResponse, error) {
> ```

s/k/pred

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-:-KyJQjjYYSPtkUOEXWC-:bnfp4nl)*

**Comment by peterstace** [comment]
Consider doing `foo + ":" + bar` instead of `fmt.Sprintf("%s:%s", foo, bar)` and `foo + ":"` instead of of `fmt.Sprintf("%s:", foo)`, seems a bit easier to read to me.

:lgtm: 

---

Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[dgraph/server.go, line 560 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-KyJQa3rVPNBMWYXykJ8:-KyJoQMBKLxOiOuJ6I7o:b-xtfyl) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0d4ab08fc4c849c7187f901900bb80d0482014b/dgraph/server.go#L560)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s/k/pred
</blockquote></details>

`pred` could be a bit confusing since it's also used in the main loop over `m` (shadowing variables in such a long function seems like a bad idea). Maybe `s/k/parentPred` since it's the pred that leads into this level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-:-KyJmgyCkheAaZUdJ4zF:buwb6z2)*

**Comment by peterstace** [comment]
Reviewed 5 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730)*

**Comment by pawanrawal** [comment]
Done

---

Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[dgraph/server.go, line 445 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-KyJP8EsQ9tKRCc-POsQ:-KyKFsyRhNJkFd8mpXJ2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0d4ab08fc4c849c7187f901900bb80d0482014b/dgraph/server.go#L445)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to split. Just use len(prefix).
</blockquote></details>

Done.

---

*[dgraph/server.go, line 560 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-KyJQa3rVPNBMWYXykJ8:-KyKFlHqARKkY7Ybei5f:b-gv86bq) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0d4ab08fc4c849c7187f901900bb80d0482014b/dgraph/server.go#L560)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

`pred` could be a bit confusing since it's also used in the main loop over `m` (shadowing variables in such a long function seems like a bad idea). Maybe `s/k/parentPred` since it's the pred that leads into this level.
</blockquote></details>

Right, this is now parentPred.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1730#-:-KyKFu34n4FeV8nW28Oz:bb6un1j)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
