### PR TITLE
Allow sorting only on sortable indices

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/682)

### CODE REVIEW

**Comment by gacharya255** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[worker/sort.go, line 130 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-KepZoF_7Ma8WoJt84iz:-KepZoFacnBXQkwQtKzV:b75hsnv) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b4b6b54e6085f68351098150a166417224db10c/worker/sort.go#L130)):*
> ```Go
> 	for _, t := range tokenizers {
> 		// Get the first sortable index.
> 		if t.IsSortable() {
> ```

Wonder if we should alert the user if we detect more than one sortable index, somewhere say in the schema.

---

*[worker/sort.go, line 147 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-KepZVRDnF59NvHvoWpb:-KepZVRDnF59NvHvoWpc:beirq07) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b4b6b54e6085f68351098150a166417224db10c/worker/sort.go#L147)):*
> ```Go
> 	} else {
> 		// We need to reach the last key of this index type.
> 		seekKey := x.IndexKey(attr, string(tok.Identifier()+'~'))
> ```

Why not the next character / string after tok.Identifier? Otherwise one day there might be some case with some character after "-" in the token?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/682)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[worker/sort.go, line 130 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-KepZoF_7Ma8WoJt84iz:-KepbsnD4A-2A_d-_ZsU:bxwefzy) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b4b6b54e6085f68351098150a166417224db10c/worker/sort.go#L130)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Wonder if we should alert the user if we detect more than one sortable index, somewhere say in the schema.
</blockquote></details>

Would it be a problem? All the sortable indices should return the same results I suppose. They'd provide a total ordering of all the values.

---

*[worker/sort.go, line 147 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-KepZVRDnF59NvHvoWpb:-KepcJkHWYUmRpLUrOzk:b73wb9) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b4b6b54e6085f68351098150a166417224db10c/worker/sort.go#L147)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Why not the next character / string after tok.Identifier? Otherwise one day there might be some case with some character after "-" in the token?
</blockquote></details>

Right. If `tilde` is used in tokens, it'd be a problem. using `+ 1`. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/682)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/sort.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-Kf4jpOf44ub9DsVgGh8:-Kf4jpOf44ub9DsVgGh9:b-jphf0v) ([raw file](https://github.com/dgraph-io/dgraph/blob/2c40e3b214c7a04964fb7be74e7d0c0a7f862908/worker/sort.go#L136)):*
> ```Go
> 	}
> 	if tok == nil {
> 		return nil, x.Errorf("Attribute:%s doesnot have proper index",
> ```

does not

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-:-Kf4k9a6XKYHS3jR3RPJ:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/sort.go, line 130 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-KepZoF_7Ma8WoJt84iz:-Kf4oUBKCiwr2BQHniPS:b32fu) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b4b6b54e6085f68351098150a166417224db10c/worker/sort.go#L130)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Would it be a problem? All the sortable indices should return the same results I suppose. They'd provide a total ordering of all the values.
</blockquote></details>

Very good point. We need to rethink our design here, to ensure that Dgraph's behavior is deterministic.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/682)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/sort.go, line 130 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-KepZoF_7Ma8WoJt84iz:-Kf4t5YK3XvE6np8-5bW:bkbuykq) ([raw file](https://github.com/dgraph-io/dgraph/blob/1b4b6b54e6085f68351098150a166417224db10c/worker/sort.go#L130)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Very good point. We need to rethink our design here, to ensure that Dgraph's behavior is deterministic.
</blockquote></details>

Added a task to look into this issue.

---

*[worker/sort.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/682#-Kf4jpOf44ub9DsVgGh8:-Kf4solNBpwLdNFlcawm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2c40e3b214c7a04964fb7be74e7d0c0a7f862908/worker/sort.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

does not
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/682)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
