### PR TITLE
Somefixes

### LINKED ISSUE #921: varmin not allowed multiple times in same sub-query
```
{
  var(func:allofterms(name, "angelina jolie")) {
    actor.film {
      performance.film {
        B AS genre {
          A as name@en
        }
      }
    }
  }

  genre(id: var(B), orderasc: var(A)) @filter(gt(count(~genre), 30000)){
    var(A)
    ~genre {
      n as name
      m as initial_release_date
    }
    minname: min(var(n))
    maxname: max(var(n))
    mindate: min(var(m))
    maxdate: max(var(m))
  }
}
```

This query returns with an error
```
{"code":"ErrorInvalidRequest","message":"varmin not allowed multiple times in same sub-query."}
```

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #921 and another bug.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/923)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Can we also change the `count(friend)` behaviour to return the result at the same level with `count(friend)` as the key?

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-:-KjoliUcQW7irK_Oitjn:b-gf6uqs)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-:-KjpahCudhiZ6vb6BM5W:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[query/query.go, line 590 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-KjptPoS2KaCnAxHlvrv:-KjptPoUbwryQF0LSNu1:b-id2hi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d7476891c2604926a4548174b3b8035d865f267f/query/query.go#L590)):*
> ```Go
> 	attrsSeen := make(map[string]struct{})
> 
> 	// Lets attach a _uid_ edge so that debug requests of the form
> ```

This seems hacky. Can't we do this in pretraverse?  if the flag is set, then always set the UID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/923)*

**Comment by ashwin95r** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[query/query.go, line 590 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-KjptPoS2KaCnAxHlvrv:-KjptyNUIJJ69NgAjvZU:bo2sil2) ([raw file](https://github.com/dgraph-io/dgraph/blob/d7476891c2604926a4548174b3b8035d865f267f/query/query.go#L590)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This seems hacky. Can't we do this in pretraverse?  if the flag is set, then always set the UID.
</blockquote></details>

This would also add `_uid_` to the name in `me(id: 1) { name }`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/923)*

**Comment by manishrjain** [comment]
Ensure that before you submit, you get an LGTM from Janardhan as well.

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-:-Kjpv-4tllsTwrGf-aWm:bq0c8k9)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 592 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-KjsgliKCY9jn9wAmlI0:-KjsgliKCY9jn9wAmlI1:bx4imtn) ([raw file](https://github.com/dgraph-io/dgraph/blob/d7476891c2604926a4548174b3b8035d865f267f/query/query.go#L592)):*
> ```Go
> 	// Lets attach a _uid_ edge so that debug requests of the form
> 	// me(id: 1) { friend } also return uids of all friends.
> 	if gq.Attr != "_uid_" && len(gq.Children) == 0 && sg.Params.isDebug {
> ```

And btw as per graphql spec if leaf node is non-scalar type, then it's not expanded at all.

---

*[query/query.go, line 594 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-KjsgS7H8uljxV-N5OZY:-KjsgS7H8uljxV-N5OZZ:b-5lupua) ([raw file](https://github.com/dgraph-io/dgraph/blob/d7476891c2604926a4548174b3b8035d865f267f/query/query.go#L594)):*
> ```Go
> 	if gq.Attr != "_uid_" && len(gq.Children) == 0 && sg.Params.isDebug {
> 		gq.Children = append(gq.Children, &gql.GraphQuery{
> 			Attr: "_uid_",
> ```

If _uid_ is already present in children, then we would be adding an duplicate copy. Without it fail the attribute seen check and cause the query to fail ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-:-Kjs8Xj3hph1Pi-By8M-:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 590 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-KjptPoS2KaCnAxHlvrv:-KjtjApzLdM3xrUnCG7A:b1q7c58) ([raw file](https://github.com/dgraph-io/dgraph/blob/d7476891c2604926a4548174b3b8035d865f267f/query/query.go#L590)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This would also add `_uid_` to the name in `me(id: 1) { name }`.
</blockquote></details>

moved to another PR.

---

*[query/query.go, line 592 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-KjsgliKCY9jn9wAmlI0:-KjtjF_iXODHMiyd2qk9:b-rfx3h6) ([raw file](https://github.com/dgraph-io/dgraph/blob/d7476891c2604926a4548174b3b8035d865f267f/query/query.go#L592)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

And btw as per graphql spec if leaf node is non-scalar type, then it's not expanded at all.
</blockquote></details>

I see, but it makes sense in light of https://github.com/dgraph-io/dgraph/issues/912. Should be ok to diverge here I think.

---

*[query/query.go, line 594 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/923#-KjsgS7H8uljxV-N5OZY:-KjtjChhC1PBZkfwYifJ:b4zrvj0) ([raw file](https://github.com/dgraph-io/dgraph/blob/d7476891c2604926a4548174b3b8035d865f267f/query/query.go#L594)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

If _uid_ is already present in children, then we would be adding an duplicate copy. Without it fail the attribute seen check and cause the query to fail ?
</blockquote></details>

Moved to another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/923)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
