### PR TITLE
Make loader load based on group config

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/311)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxiR2yIZdqj5PdpFm2:-KVxiR2yIZdqj5PdpFm3:b-o031g4) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraph/main.go#L57)):*
> ```Go
> 
> var (
> 	conf       = flag.String("gconf", "", "group configuration file")
> ```

why not use conf, just like we did before.

---

*[cmd/dgraphloader/groups.conf, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxiqeCqVf8QcQjtmaK:-KVxiqeCqVf8QcQjtmaL:b-m8vjnw) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/groups.conf#L1)):*
> ```
> default: fp % 2 
> ```

default should be `fp % 1`

---

*[cmd/dgraphloader/main.go, line 43 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxj5TcVzPfSl9BjdW8:-KVxj5TcVzPfSl9BjdW9:b-eilgpg) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/main.go#L43)):*
> ```Go
> 	glog = x.Log("loader_main")
> 
> 	conf     = flag.String("gconf", "", "group configuration file")
> ```

Use conf.

---

*[cmd/dgraphloader/main.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxj9EZe30ody3KV1zy:-KVxj9EZe30ody3KV1zz:b-mca5bd) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/main.go#L46)):*
> ```Go
> 	rdfGzips = flag.String("rdfgzips", "",
> 		"Comma separated gzip files containing RDF data")
> 	groupsList = flag.String("group", "",
> ```

groups, just like in dgraph.main. For both the flag name and var name. Also, set the default to "0".

---

*[loader/loader.go, line 236 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxka62DF2i-E-5h61M:-KVxka62DF2i-E-5h61N:bduk5h0) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/loader/loader.go#L236)):*
> ```Go
> 
> 		// Mark UIDs and XIDs as taken
> 		if s.groupsMap[group.BelongsTo("_uid_")] {
> ```

You can evaluate this once outside the loop, and use it repeatedly. In fact, I've noticed that issue in other PRs as well. Pay extra attention to evaluating expressions within loops.

---

*[loader/loader.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxlhFgxRl9G0Mz5xD9:-KVxlhFgxRl9G0Mz5xDA:b8ckugy) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/loader/loader.go#L247)):*
> ```Go
> 			key := posting.Key(edge.Entity, "_uid_")
> 			plist, decr := posting.GetOrCreate(key)
> 			plist.AddMutationWithIndex(ctx, mu, posting.Set)
> ```

Do we really need `WithIndex` for this? I think we just need `AddMutation`.

---

*[loader/loader.go, line 251 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxmCyHJmENTFWhn0dT:-KVxmCyHJmENTFWhn0dU:bx8obja) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/loader/loader.go#L251)):*
> ```Go
> 			// Mark the Value UID.
> 			if edge.ValueId != 0 {
> 				mu = x.DirectedEdge{
> ```

Move this common code in a function, and call it above and here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/311)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxiR2yIZdqj5PdpFm2:-KVxpxpBaiziIn08QygF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraph/main.go#L57)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> why not use conf, just like we did before.
</details>
Done.

---

*[cmd/dgraphloader/groups.conf, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxiqeCqVf8QcQjtmaK:-KVxnVIgKZh5F7kwvE55:b-6jweou) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/groups.conf#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> default should be `fp % 1`
</details>
This is used by a test function which needs fp%2. Hence.

---

*[cmd/dgraphloader/main.go, line 43 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxj5TcVzPfSl9BjdW8:-KVxoINwDtmr1pqj3x4t:bg5gqmv) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/main.go#L43)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Use conf.
</details>
Done. There was a conf flag in worker package. We don't need it now.

---

*[cmd/dgraphloader/main.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxj9EZe30ody3KV1zy:-KVxoc9PWRnIX0nWBVaw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/main.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> groups, just like in dgraph.main. For both the flag name and var name. Also, set the default to "0".
</details>
Done.

---

*[loader/loader.go, line 236 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxka62DF2i-E-5h61M:-KVxq34vmBhDaoYYiTrU:brgq1k0) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/loader/loader.go#L236)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can evaluate this once outside the loop, and use it repeatedly. In fact, I've noticed that issue in other PRs as well. Pay extra attention to evaluating expressions within loops.
</details>
Sure. Done.

---

*[loader/loader.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxlhFgxRl9G0Mz5xD9:-KVxq5iVTDBQdFxOsHfh:b-fymjsu) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/loader/loader.go#L247)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Do we really need `WithIndex` for this? I think we just need `AddMutation`.
</details>
Yeah, AddMutation would do. Done.

---

*[loader/loader.go, line 251 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxmCyHJmENTFWhn0dT:-KVxpwbIa53qr_g1gRPT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/loader/loader.go#L251)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Move this common code in a function, and call it above and here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/311)*

**Comment by jchiu0** [comment]
Some small comments, otherwise :lgtm

---

Review status: 24 of 28 files reviewed at latest revision, 9 unresolved discussions.

---

*[loader/loader.go, line 201 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxvHXNyfSL9aqPmerr:-KVxvHXNyfSL9aqPmers:b-5bx6y) ([raw file](https://github.com/dgraph-io/dgraph/blob/d66cc9beb70998d15e981132e70ca8393060c387/loader/loader.go#L201)):*
> ```Go
> 		Entity:    uid,
> 		Attribute: "_uid_",
> 		Value:     []byte("_taken_"), // not txid
> ```

Just wondering if we need 7 bytes to mark as taken.

---

*[loader/loader.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxvQVvtGSA7Anuxk0X:-KVxvQVvtGSA7Anuxk0Y:b-de6yiv) ([raw file](https://github.com/dgraph-io/dgraph/blob/d66cc9beb70998d15e981132e70ca8393060c387/loader/loader.go#L223)):*
> ```Go
> 		}
> 		// Only handle this edge if the attribute satisfies the modulo rule
> 		if !s.groupsMap[group.BelongsTo(nq.Predicate)] { // farm.Fingerprint64([]byte(nq.Predicate))%s.numInstances != s.instanceIdx {
> ```

Delete the comment // farm.Fingerprint... or move to another line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-:-KVxvrR52ExqlImlF6-w:bw81r22)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 24 of 28 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-:-KVxw8mWMG56ahHran7C:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 23 of 29 files reviewed at latest revision, 9 unresolved discussions.

---

*[loader/loader.go, line 201 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxvHXNyfSL9aqPmerr:-KVy7MVnZYmdLOP7zjyY:b-8pmedl) ([raw file](https://github.com/dgraph-io/dgraph/blob/d66cc9beb70998d15e981132e70ca8393060c387/loader/loader.go#L201)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Just wondering if we need 7 bytes to mark as taken.
</details>
Yeah, good point. Making it `_` (Since we just use the key and not really the value)

---

*[loader/loader.go, line 223 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxvQVvtGSA7Anuxk0X:-KVy7KrLSkgN71Xu5q3T:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d66cc9beb70998d15e981132e70ca8393060c387/loader/loader.go#L223)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Delete the comment // farm.Fingerprint... or move to another line?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/311)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/dgraphloader/groups.conf, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxiqeCqVf8QcQjtmaK:-KVyjQ30E7G2B6XrKgh8:b-jurtzn) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/groups.conf#L1)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> This is used by a test function which needs fp%2. Hence.
</details>
Shouldn't it then be located in the test folder?

---

*[loader/loader.go, line 201 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxvHXNyfSL9aqPmerr:-KVyje3PqjKUwGfhlKu4:b59121) ([raw file](https://github.com/dgraph-io/dgraph/blob/d66cc9beb70998d15e981132e70ca8393060c387/loader/loader.go#L201)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Yeah, good point. Making it `_` (Since we just use the key and not really the value)
</details>
There're other places where we do this as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-:-KVyqUbqL1WCZ6SvaJG1:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/groups.conf, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxiqeCqVf8QcQjtmaK:-KVyzf_f0MsFs5p-Kiz1:b-c1bynm) ([raw file](https://github.com/dgraph-io/dgraph/blob/bfc810dade13ec1ee7586a09a75237c8290b11c5/cmd/dgraphloader/groups.conf#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Shouldn't it then be located in the test folder?
</details>
Sure, will move these and other related files into a test folder.

---

*[loader/loader.go, line 201 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/311#-KVxvHXNyfSL9aqPmerr:-KVyylGCAoRiH1XqAudN:b-6s7v7p) ([raw file](https://github.com/dgraph-io/dgraph/blob/d66cc9beb70998d15e981132e70ca8393060c387/loader/loader.go#L201)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> There're other places where we do this as well.
</details>
Changed them in all places.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/311)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
