### PR TITLE
chore(worker): Set initial schema and types directly to group-1 nodes.

### PR DESCRIPTION
**Pull request by ahsanbarkati**
All internal predicates belong to group 1. Set the initial schemas/types directly on all the nodes which belong to group 1 rather than making a raft proposal for them.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7324)

### CODE REVIEW

**Review by manishrjain — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7324#-:-MRKnjFm6oKZAy19zLGC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vvbalaji-dgraph)

**Review by manishrjain — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7324)* status: all files reviewed, 1 unresolved discussion (waiting on @ahsanbarkati and @vvbalaji-dgraph)

___
*[worker/groups.go, line 238 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7324#-MRKnuQ612fbb9C4GGDV:-MRKnuQ612fbb9C4GGDW:bmj076) ([raw file](https://github.com/dgraph-io/dgraph/blob/da4aa5beefdacca15754c9d5ec8545ef24849f09/worker/groups.go#L238)):*
> ```Go
> 		} else {
> 			// The schema for this predicate has already been proposed.
> 			glog.V(1).Infof("Skipping initial schema upsert for predicate %s", s.Predicate)
> ```

`Schema found for predicate %s: %+v`, s.Predicate

**Review by pawanrawal — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7324)* status: all files reviewed, 2 unresolved discussions (waiting on @ahsanbarkati and @vvbalaji-dgraph)

___
*[worker/groups.go, line 215 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7324#-MRP6Exr1q-5mb82hx7T:-MRP6Exr1q-5mb82hx7U:b2b9k7n) ([raw file](https://github.com/dgraph-io/dgraph/blob/bcb20a631644287a347686f54d2694c858b53aa0/worker/groups.go#L215)):*
> ```Go
> 	ctx := g.Ctx()
> 
> 	applySchema := func(s *pb.SchemaUpdate) {
> ```

I can see this same piece of code in `worker/draft.go` in `applyMutations` so can we reuse this function at the both the places? The only difference is that there we return the error and here we log it. So we can call the function and log the error here.

**Review by ahsanbarkati — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7324)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[worker/groups.go, line 238 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7324#-MRKnuQ612fbb9C4GGDV:-MRQbFqZ2ZfD5Cyzmpas:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/da4aa5beefdacca15754c9d5ec8545ef24849f09/worker/groups.go#L238)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`Schema found for predicate %s: %+v`, s.Predicate
</blockquote></details>

Done.
___
*[worker/groups.go, line 215 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7324#-MRP6Exr1q-5mb82hx7T:-MRQbETZ9IA7oWq5rBy-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bcb20a631644287a347686f54d2694c858b53aa0/worker/groups.go#L215)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I can see this same piece of code in `worker/draft.go` in `applyMutations` so can we reuse this function at the both the places? The only difference is that there we return the error and here we log it. So we can call the function and log the error here.
</blockquote></details>

Done.

**Pull request merged**
