### PR TITLE
Better error checking when accessing PL

### PR DESCRIPTION
**Pull request by peterstace**
I've confirmed with manual testing that this fixes the problem that I've been seeing (I added some logging to check when the branch is triggered).

Not too sure of a good way to add a test, it's even very difficult to check manually.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1970)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 387 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1opbuReTzw0H61tMZB:-L1opbuReTzw0H61tMZC:b6hxcm8) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ea07e5370c67cd108c4e9edc164c3780e01321a/worker/task.go#L387)):*
> ```Go
> 			return err
> 		}
> ```

Probably have a look if need to do something similar at other places in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-:-L1op_xS4DlWFgGAd4ZZ:bnfp4nl)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 387 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1opbuReTzw0H61tMZB:-L1pGtkfxK1GWS3KfDFW:b-p58e7f) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ea07e5370c67cd108c4e9edc164c3780e01321a/worker/task.go#L387)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Probably have a look if need to do something similar at other places in this file.
</blockquote></details>

Had a quick look, there are a few other places where we don't handle the error correctly (unfortunately not as easy to fix). I'll get these all fixed at the same time though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970)*

**Comment by peterstace** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/task.go, line 387 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1opbuReTzw0H61tMZB:-L1ph328Kl43gKIIgQmT:b-so0ig1) ([raw file](https://github.com/dgraph-io/dgraph/blob/2ea07e5370c67cd108c4e9edc164c3780e01321a/worker/task.go#L387)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Had a quick look, there are a few other places where we don't handle the error correctly (unfortunately not as easy to fix). I'll get these all fixed at the same time though.
</blockquote></details>

I've fixed these now. Got a bit tricky handling errors from the filter function correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 896 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uNh2Y-LjrhgXoSASD:-L1uNh2Y-LjrhgXoSASE:bqusfjr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L896)):*
> ```Go
> 		}
> 	}
> 	return nil
> ```

`return filterErr`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970)*

**Comment by janardhan1993** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 860 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uNv2BMFJpP9kPcHBy:-L1uNv2BMFJpP9kPcHBz:b-3gmdz3) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L860)):*
> ```Go
> 							filterErr = err
> 						}
> 						return false
> ```

The following would be more readable i think.
if err != posting.ErrNoValue {
filterErr = err
return false
} else if err != nil {
return false
}

---

*[worker/task.go, line 913 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uNYcR1KQ_fgjdzoM8:-L1uNYcR1KQ_fgjdzoM9:b-ejdsqt) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L913)):*
> ```Go
> 		} else if err != posting.ErrNoValue {
> 			return err
> 		}
> ```

else if err == posting.ErrNoValue {
newValue.val= x.Nilbyte
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 896 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uNh2Y-LjrhgXoSASD:-L1uO2B20SIs1yDaqGAi:bxw3057) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L896)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`return filterErr`?
</blockquote></details>

Or actually we should check filterErr after each run of the for loop and return if its non-nil.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 860 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uNv2BMFJpP9kPcHBy:-L1uOsF8r4Tx7H3gUZLq:b-pzpcum) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L860)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

The following would be more readable i think.
if err != posting.ErrNoValue {
filterErr = err
return false
} else if err != nil {
return false
}
</blockquote></details>

Then err == nil would fall into the if loop.

---

*[worker/task.go, line 868 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uOxTGxwcOh_1IwdH_:-L1uOxTGxwcOh_1IwdHa:b-ltdkpi) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L868)):*
> ```Go
> 					pl := posting.GetNoStore(x.DataKey(attr, uid))
> 					values, err := pl.AllValues(arg.q.ReadTs)
> 					if err != nil {
> ```

Could add a comment that AllValues doesn't return ErrNoValue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-:-L1uP3v2HCYuhmGs4uT7:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-:-L1uPUlkhFhH4ZGP0ake:bnfp4nl)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 868 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uOxTGxwcOh_1IwdH_:-L1uYDSP8eI8JhHYnu06:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L868)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Could add a comment that AllValues doesn't return ErrNoValue
</blockquote></details>

Done.

---

*[worker/task.go, line 896 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uNh2Y-LjrhgXoSASD:-L1uYmdkl7B2e9ufMwRT:bqm79px) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L896)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Or actually we should check filterErr after each run of the for loop and return if its non-nil.
</blockquote></details>

Ah, yes that's what I was intending to do, but forgot to check the error at the end of the loop. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970)*

**Comment by peterstace** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 913 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970#-L1uNYcR1KQ_fgjdzoM8:-L1uZAPWDOyV4lHbaTQ0:b-nuf6dr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a7c2a4ad43cae5fca255211b0760385921b92da4/worker/task.go#L913)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

else if err == posting.ErrNoValue {
newValue.val= x.Nilbyte
}
</blockquote></details>

I made this change (simplification?) purposefully. Since `Val` is already `nil`, it felt weird to set it to `nil` again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1970)*

**Pull request merged**
