### PR TITLE
Get rid of stateGroup in schema

### PR DESCRIPTION
**Pull request by pawanrawal**
Noticed we could do some cleanup in schema package.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1621)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1621#-:-Kw7wrZr8HrywgvDSqRo:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1621#-:-Kw7x6M71WwdQmBiYZXj:bnfp4nl)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1621#-:-Kw8-ToNKrHBdfLODKwm:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
