### PR TITLE
Add support for facets in Go client

### PR DESCRIPTION
**Pull request by pawanrawal**
AddFacet function to add Facet to an NQuad in Go client.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/888)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-:-KimO576u1-BA6DxPI5n:bnfp4nl)*

**Comment by janardhan1993** [comment]
LG. Please try with string value once, i think the following would fail.
if err := client.AddFacet("alias", `"Steve"`, &nq); err != nil {
		log.Fatal(err)
	}
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/client.go, line 109 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-KimPxzjvrMG_9Dg8Kka:-KimPxzjvrMG_9Dg8Kkb:b-kc5p65) ([raw file](https://github.com/dgraph-io/dgraph/blob/7a0bffd113668a0dd1fec4d416017c051eebc917/client/client.go#L109)):*
> ```Go
> 
> func AddFacet(key string, val string, nq *graphp.NQuad) error {
> 	facet, err := facets.FacetFor(key, val)
> ```

Can you please check how does this behave when you try to add a string value. I think for adding string value we need to have double quotes in the string value explicity or else facets.FacetFor would fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-:-KimQCYYYvNMLeFmcEDq:b-fgik87)*

**Comment by pawanrawal** [comment]
See comment below please.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[client/client.go, line 109 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-KimPxzjvrMG_9Dg8Kka:-KimQj_2ATImG5nT_pbe:b-244v8j) ([raw file](https://github.com/dgraph-io/dgraph/blob/7a0bffd113668a0dd1fec4d416017c051eebc917/client/client.go#L109)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Can you please check how does this behave when you try to add a string value. I think for adding string value we need to have double quotes in the string value explicity or else facets.FacetFor would fail.
</blockquote></details>

Yeah, for string they val either needs to /"Steve/". So
```
if err := client.AddFacet("alias", "\"Steve\"", &nq); err != nil {
	log.Fatal(err)
}
```
Or
```
 // This is the example I have in docs because its cleaner.
if err := client.AddFacet("alias", `Steve`, &nq); err != nil {
	log.Fatal(err)
}
```

Do you think it need more clarification?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-:-KimRUpIhMYCmQlF2Tke:bqaa58i)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/examples_test.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-KimRtv80gm9OfFZhESo:-KimRtv80gm9OfFZhESp:bqfudez) ([raw file](https://github.com/dgraph-io/dgraph/blob/7a0bffd113668a0dd1fec4d416017c051eebc917/client/examples_test.go#L122)):*
> ```Go
> 	}
> 
> 	if err := client.AddFacet("alias", `"Steve"`, &nq); err != nil {
> ```

example here

---

*[wiki/content/clients/index.md, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-KimRw-kdgxHg1uWagzV:-KimRw-kdgxHg1uWagzW:bji28bi) ([raw file](https://github.com/dgraph-io/dgraph/blob/7a0bffd113668a0dd1fec4d416017c051eebc917/wiki/content/clients/index.md#L75)):*
> ```Markdown
> 	}
> 
> 	if err := client.AddFacet("alias", `"Steve"`, &nq); err != nil {
> ```

and here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/888)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/888#-:-KimSQPvw3V0BkMhmfbN:bnfp4nl)*

**Comment by pawanrawal** [comment]
merged

**Pull request closed without merging**
