### PR TITLE
feat(GraphQL): Add GraphQL schema validation Endpoint.

### PR DESCRIPTION
**Pull request by arijitAD**
Fixes: GraphQL-578

Added `admin/schema/validate` endpoint to validate the GraphQL schema.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)

 

Docs Preview: [Dgraph Preview](https://dgraph-2955e69dce-88529.surge.sh)

### CODE REVIEW

**Review by arijitAD — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)* status: 4 of 16 files reviewed, 12 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 504 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFENcmH2_CMTZ6wldma:-MFZX7HFBo9FYfFG-ybT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/dgraph/cmd/alpha/run.go#L504)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

I think sending no input should return a `400 Bad Request`, instead of `200 OK`.
Or, insteadwe can just let the `admin.SchemaValidate` call take care of empty input, because internally `NewHandler` checks that condition and returns a proper error.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 515 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEOl742mxoUSn3npXz:-MF_E3wf82kEGLXKKG8O:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/dgraph/cmd/alpha/run.go#L515)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

We can make the error as an array of strings in response. So, we split here by `\n` and send that array as the value of an `errors` key in the response.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 516 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEPFxIBaXs3LzP7JZJ:-MFZXHFu2lRwLemoEBhf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/dgraph/cmd/alpha/run.go#L516)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

since status is either valid/invalid, i.e., only boolean state, so instead we can send the response as one of:
```
{
  "valid": true
}
```
or
```
{
  "valid": false,
  "errors": ["err1", "err2", ...]
}
```
</blockquote></details>

Done.
___
*[graphql/admin/schema.go, line 59 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFElJ3A0Udpd3GxKhOz:-MF_brU90tZLn1pkyHfU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/admin/schema.go#L59)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> schHandler, err := schema.NewHandler(input.Set.Schema, false)
> 	if err != nil {
> 		return resolve.EmptyResult(m, err), false
> 	}
> 	if _, err = schema.FromString(schHandler.GQLSchema()); err != nil {
> 		return resolve.EmptyResult(m, err), false
> 	}
> ```
This part only validates the schema, it does not set the in-memory schema here. So, `true` should be sent.
Instead, we can just use`admin.SchemaValidate(input.Set.Schema)` here.
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 60 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEigNT95qpf28uuxWt:-MF_ciqd7hhaDOKGvAdy:bxsba38) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/authorization/auth.go#L60)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

We shouldn't be needing this lock here. There is only two places from where in-memory schema can get updated with wanting to set `authMeta`. Both of those are in `admin.go` and they acquire locks there itself. So here we will never receive two concurrent requests to update `authMeta`.

more related comments on `NewHandler`...
</blockquote></details>

This can be accessed from multiple places hence lock is required.
___
*[graphql/authorization/auth.go, line 167 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEib4D30fn_ysAl93c:-MF_PEvM0OrUqj06uu0l:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/authorization/auth.go#L167)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should return a pointer.
</blockquote></details>

Done.
___
*[graphql/authorization/auth.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEidLC9NidTxnKLIUh:-MF_PFdg5SYahJ4YAal5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/authorization/auth.go#L173)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should accept a pointer.
</blockquote></details>

Done.
___
*[graphql/e2e/common/common.go, line 40 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEm02s98_7PIPXP67u:-MF_EpTiAFEhrAsXy6A_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/e2e/common/common.go#L40)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> GraphqlURL      = "http://localhost:8180/graphql"
> 	GraphqlAdminURL = "http://localhost:8180/admin"
> ```
We have `groupOneServer` and `groupOneAdminServer` in `schema_test.go` which are same as these.
We can just use them there, instead of exporting these.
</blockquote></details>

Done.
___
*[graphql/e2e/schema/schema_test.go, line 334 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEoKeJ2KOzUIZmJLGG:-MF_EvZH2h5VXfBvV0oI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/e2e/schema/schema_test.go#L334)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> VerifyEmptySchema
> ```
should be unexported: `verifyEmptySchema`
</blockquote></details>

Done.
___
*[graphql/e2e/schema/schema_test.go, line 398 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEndbi2cjj3CfWtBGK:-MF_FCAc8wA4cRdcAOAa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/e2e/schema/schema_test.go#L398)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

Although it doesn't matter, but `text/plain` sounds better here.
</blockquote></details>

Done.
___
*[graphql/schema/schemagen.go, line 209 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEsnMo7JaK8fDzVJVj:-MF_Q8rh4hywR4NL73wf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/schema/schemagen.go#L209)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should pass `metaInfo` to this function, as this function uses `authMeta` from the authorization package, which won't be set yet.
</blockquote></details>

Done.
___
*[graphql/schema/schemagen.go, line 220 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFEtuyi17fZcy1bRdkN:-MF_eQZO1XP7PoXo0BM6:b-noi2j3) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/schema/schemagen.go#L220)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> handler := &handler{
> 		input:          input,
> 		dgraphSchema:   dgSchema,
> 		completeSchema: sch,
> 		originalDefs:   defns,
> 	}
> 	// Return early since we are only validating the schema.
> 	if validateOnly {
> 		return handler, nil
> 	}
> 	hc.Lock()
> 	hc.allowed = headers
> 	hc.secrets = schemaSecrets
> 	hc.Unlock()
> 	if metaInfo != nil {
> 		authorization.SetAuthMeta(*metaInfo)
> 	}
> 	return handler, nil
> ```
Since, `hc` & `authMeta` is per schema, we should save them as a state variable in `Handler` and have a method called `SetContext()` on `Handler` to set those things once we are sure schema is valid, because the `FromString` call hasn't happened yet.
So, we should put the call to `SetAuthMeta()` and setting `hc` in `SetContext()` and call `SetContex()` in `resetSchema()` in `admin.go`. That is the only place from where we actually want to update the in-memory schema, and it is already protected by locks from the two places it is called.

We can discuss this.
</blockquote></details>

The schema update is a two-step process. 
We first validate it and then update the auth info when we receive an update from the badger. Hence if there is an error we will get it in the validation phase.

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
> Reviewed 13 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)* status: all files reviewed, 6 unresolved discussions (waiting on @arijitAD, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 509 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd7fz96M4VnRK3l9Hs:-MFd7fz96M4VnRK3l9Ht:btqrdd7) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/dgraph/cmd/alpha/run.go#L509)):*
> ```
> "true"
> ```
a boolean `true` not a string `"true"`
___
*[dgraph/cmd/alpha/run.go, line 519 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd7pz95gEUwyggDcl0:-MFd7pz95gEUwyggDcl1:b-9tcjd6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/dgraph/cmd/alpha/run.go#L519)):*
> ```
> "false"
> ```
-> `false`
___
*[graphql/admin/admin.go, line 518 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd4uex5Kn1rGBoyzig:-MFd4ueyDBcHWA1rDoEW:bsthbgv) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/admin/admin.go#L518)):*
> ```
> server.mux.Lock()
> 		defer server.mux.Unlock()
> ```
no need to move these lines up now, because we agreed on having locks inside for the `authMeta` and ` hc`.
___
*[graphql/e2e/common/fragment.go, line 37 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd6JMjDotJRNn3-t9x:-MFd6JMjDotJRNn3-t9y:b-x2cmph) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/e2e/common/fragment.go#L37)):*
> ```
> fmt.Sprintf(
> ```
When you merge master, you will get a merge conflict here because I already removed this DeepSource warning :P
___
*[graphql/e2e/schema/schema_test.go, line 410 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd8BEY9i6t6sOd_hxY:-MFd8BEY9i6t6sOd_hxZ:b-evx300) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/graphql/e2e/schema/schema_test.go#L410)):*
> ```
> "true"
> ```
-> `true`
___
*[graphql/e2e/schema/schema_test.go, line 414 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd8EhB2fsRmsnHaGsW:-MFd8EhB2fsRmsnHaGsX:b-9tcjd6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/graphql/e2e/schema/schema_test.go#L414)):*
> ```
> "false"
> ```
-> `false`
___
*[graphql/schema/wrappers.go, line 224 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd8w9g61BAvvz0MvBt:-MFd8w9hC_UWytlHE8Lh:bd2sqso) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/graphql/schema/wrappers.go#L224)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> //
> 	authMeta *authorization.AuthMeta
> 	//
> 	hc *headersConfig
> ```
</details>

stale code from discussion

**Review by arijitAD — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)* status: 10 of 14 files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 509 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd7fz96M4VnRK3l9Hs:-MFeXbmS--HJm9XDHlDc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/dgraph/cmd/alpha/run.go#L509)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "true"
> ```
a boolean `true` not a string `"true"`
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 519 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd7pz95gEUwyggDcl0:-MFeXckD-pbtAKuuhllM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/dgraph/cmd/alpha/run.go#L519)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "false"
> ```
-> `false`
</blockquote></details>

Done.
___
*[graphql/admin/admin.go, line 518 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd4uex5Kn1rGBoyzig:-MFeXdbxAq1g077MCIBm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d11aa26f81487c6243e3d5fe36c05318a70bafa/graphql/admin/admin.go#L518)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> server.mux.Lock()
> 		defer server.mux.Unlock()
> ```
no need to move these lines up now, because we agreed on having locks inside for the `authMeta` and ` hc`.
</blockquote></details>

Done.
___
*[graphql/e2e/schema/schema_test.go, line 410 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd8BEY9i6t6sOd_hxY:-MFeXfaj0WsQywqaa5pY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/graphql/e2e/schema/schema_test.go#L410)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "true"
> ```
-> `true`
</blockquote></details>

Done.
___
*[graphql/e2e/schema/schema_test.go, line 414 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd8EhB2fsRmsnHaGsW:-MFeXgHg33pZhtxVG2jR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/graphql/e2e/schema/schema_test.go#L414)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "false"
> ```
-> `false`
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 224 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFd8w9g61BAvvz0MvBt:-MFeXh2f4Rr5K69fgPtN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f921ee511ac44484fef0016530620241489dc1b8/graphql/schema/wrappers.go#L224)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> //
> 	authMeta *authorization.AuthMeta
> 	//
> 	hc *headersConfig
> ```
stale code from discussion
</blockquote></details>

Done.

**Review by abhimanyusinghgaur — APPROVED** [review]
:lgtm:

> Reviewed 8 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-:-MFjBv4JEFHyOWDqb8st:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 3 of 18 files at r1, 4 of 17 files at r2, 4 of 12 files at r3, 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)* status: all files reviewed, 3 unresolved discussions (waiting on @arijitAD, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 524 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFjg2Bu962ydqBu60u0:-MFjg2Bu962ydqBu60u1:b5q2h0b) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4c2bc67a840ca41201111ddc471362d53ec4787/dgraph/cmd/alpha/run.go#L524)):*
> ```Go
> 		}
> 
> 		w.WriteHeader(http.StatusBadRequest)
> ```

There is `x.SetStatusWithData` and `x.SetStatus`  which already does quite a bit of this. Can you check if you could use that here? For success, we send `code` as `success` usually.
___
*[graphql/admin/admin.go, line 369 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFjgpFh1NAAOeU2BHrc:-MFjgpFh1NAAOeU2BHrd:b-ok5e9s) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4c2bc67a840ca41201111ddc471362d53ec4787/graphql/admin/admin.go#L369)):*
> ```Go
> 	}
> 
> 	if _, err := schema.FromString(schHandler.GQLSchema()); err != nil {
> ```

can just be `return schema.From....)
___
*[graphql/admin/schema.go, line 52 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFjhmrA3RFxQNTCO4ci:-MFjhmrBE0-OYwNIYrrW:bakfha4) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4c2bc67a840ca41201111ddc471362d53ec4787/graphql/admin/schema.go#L52)):*
> ```Go
> 	}
> 
> 	// We just need to validate the schema. Schema is later set in `resetSchema()` when the schema
> ```

Hope no tests are failing after this because even on this node the schema would be applied after some time now. Do we need to change the flag for this endpoint?

**Review by arijitAD — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 524 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFjg2Bu962ydqBu60u0:-MFka-Yv0CDq5StZJz96:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4c2bc67a840ca41201111ddc471362d53ec4787/dgraph/cmd/alpha/run.go#L524)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

There is `x.SetStatusWithData` and `x.SetStatus`  which already does quite a bit of this. Can you check if you could use that here? For success, we send `code` as `success` usually.
</blockquote></details>

Done.
___
*[graphql/admin/admin.go, line 369 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFjgpFh1NAAOeU2BHrc:-MFkagNO4FlgWU1k-3by:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4c2bc67a840ca41201111ddc471362d53ec4787/graphql/admin/admin.go#L369)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

can just be `return schema.From....)
</blockquote></details>

Done.
___
*[graphql/admin/schema.go, line 52 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MFjhmrA3RFxQNTCO4ci:-MFkai6c6MLYO4szpqNJ:b-2xepst) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4c2bc67a840ca41201111ddc471362d53ec4787/graphql/admin/schema.go#L52)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Hope no tests are failing after this because even on this node the schema would be applied after some time now. Do we need to change the flag for this endpoint?
</blockquote></details>

Yes. Otherwise, we would end up updating the auth meta.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)* status: all files reviewed, 2 unresolved discussions (waiting on @arijitAD, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 519 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MG8nnFxDqzgxFR_V97l:-MG8nnFxDqzgxFR_V97m:b-cyapuj) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b933d09f8887cf09b41cc9235c2fd8ab5c8987d/dgraph/cmd/alpha/run.go#L519)):*
> ```Go
> 		if err == nil {
> 			w.WriteHeader(http.StatusOK)
> 			x.SetStatus(w, "success", "msg")
> ```

So the third argument is supposed to be the message that you want to send. It could be `Schema is valid` or something. 
___
*[x/x.go, line 329 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MG8oDrzEAB4niJhJjXq:-MG8oDrzEAB4niJhJjXr:byq2zec) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b933d09f8887cf09b41cc9235c2fd8ab5c8987d/x/x.go#L329)):*
> ```Go
> }
> 
> func SetStatusWithErrors(w http.ResponseWriter, code string, errs []string) {
> ```

strange there wasn't already something like this there

**Review by arijitAD — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6250)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 519 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MG8nnFxDqzgxFR_V97l:-MG9-V5rB1Y6-JwKTBWY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b933d09f8887cf09b41cc9235c2fd8ab5c8987d/dgraph/cmd/alpha/run.go#L519)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

So the third argument is supposed to be the message that you want to send. It could be `Schema is valid` or something. 
</blockquote></details>

Done.
___
*[x/x.go, line 329 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6250#-MG8oDrzEAB4niJhJjXq:-MG9-XstAD4w8cGaGs_t:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b933d09f8887cf09b41cc9235c2fd8ab5c8987d/x/x.go#L329)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

strange there wasn't already something like this there
</blockquote></details>

Done.

**Pull request merged**
