### PR TITLE
chore (test): unskip chunker

### PR DESCRIPTION
**Pull request by SashaDgraph**
## Problem
 
Chunker was skipped.
## Solution
 
Chunker was unskipped.

### CODE REVIEW

**Review by meghalims — CHANGES_REQUESTED** [review]
Please rebase, resolve conflict and resubmit

**Review by meghalims — CHANGES_REQUESTED** [review]
The merged file had all conflicts.  please re-commit with fixing  it

**Review by meghalims — APPROVED** [review]
Looks good 👍 now

**Review by skrdgraph — CHANGES_REQUESTED** [review]
@SashaDgraph - the PRs should have meaningful description. Please provide a meaningful description

**Comment by skrdgraph** [comment]
@SashaDgraph - also add the correct label to this PR

**Comment by skrdgraph** [comment]
@SashaDgraph - you can also keep your PRs in `draft` mode, till it is ready for review. I would recommend doing this.

**Comment by SashaDgraph** [comment]
> @SashaDgraph - you can also keep your PRs in `draft` mode, till it is ready for review. I would recommend doing this.

Ok. Will keep it in mind for next time

**Comment by SashaDgraph** [comment]
> @SashaDgraph - also add the correct label to this PR

Fixed.

**Comment by SashaDgraph** [comment]
> @SashaDgraph - the PRs should have meaningful description. Please provide a meaningful description

Problem and Solution statement added

**Review by skrdgraph — APPROVED** [review]

**Pull request merged**
