### PR TITLE
Print rocksdb stats under /debug for cmd/dgraph

### PR DESCRIPTION
**Pull request by jchiu0**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/302)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraph/main.go, line 594 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/302#-KV52UKR-OtIAaB55NlY:-KV52UKR-OtIAaB55NlZ:b-fe5oiv) ([raw file](https://github.com/dgraph-io/dgraph/blob/c2eb4f8a6290b03705b1c14ac51f24a91ee3e7eb/cmd/dgraph/main.go#L594)):*
> ```Go
> 
> 	http.HandleFunc("/query", queryHandler)
> 	http.HandleFunc("/debug", debugHandler)
> ```

The /net/http/pprof (https://golang.org/pkg/net/http/pprof/) already uses the /debug endpoint. So can you make sure that functionality is not affected and in that case move it to something else? say `/rdbstat`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/302)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraph/main.go, line 594 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/302#-KV52UKR-OtIAaB55NlY:-KV53fBUfzq-SQ4x83w4:bnk4nui) ([raw file](https://github.com/dgraph-io/dgraph/blob/c2eb4f8a6290b03705b1c14ac51f24a91ee3e7eb/cmd/dgraph/main.go#L594)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> The /net/http/pprof (https://golang.org/pkg/net/http/pprof/) already uses the /debug endpoint. So can you make sure that functionality is not affected and in that case move it to something else? say `/rdbstat`
</details>
Okay /debug/pprof is used. Maybe this can go in /debug/rdb. To be consistent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/302)*

**Comment by jchiu0** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraph/main.go, line 594 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/302#-KV52UKR-OtIAaB55NlY:-KV55WF_Uj7TLeBJZlze:b-52fgqd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c2eb4f8a6290b03705b1c14ac51f24a91ee3e7eb/cmd/dgraph/main.go#L594)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Okay /debug/pprof is used. Maybe this can go in /debug/rdb. To be consistent.
</details>
Can I move it to /debug/store? (just in case we don't use RocksDB one day)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/302)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/302#-:-KV57BmwKhR69LRJB-Y1:bnfp4nl)*

**Comment by jchiu0** [comment]
Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/302#-:-KV57I47wZLFuxgL_0UT:b-ucfknh)*

**Pull request closed without merging**
