### PR TITLE
Add/geoquerytests

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/342)

### CODE REVIEW

**Comment by pawanrawal** [comment]
some comments and then good to go.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query_test.go, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdXgJmQ90WNkxBFCRP:-KXdXgJmQ90WNkxBFCRQ:bahqeqh) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L178)):*
> ```Go
> 	addEdgeToValue(t, ps, "age", 23, "15")
> 
> 	err = coord.UnmarshalText([]byte("{\"Type\":\"Polygon\", \"Coordinates\":[[[0.0,0.0], [2.0,0.0], [2.0, 2.0], [0.0, 2.0]]]}"))
> ```

how about we do this above with the other geo stuff?

---

*[query/query_test.go, line 182 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdYoRfzYLjBxHXHXgR:-KXdYoRfzYLjBxHXHXgS:bs2023) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L182)):*
> ```Go
> 	gData, err = coord.MarshalBinary()
> 	require.NoError(t, err)
> 	addEdgeToTypedValue(t, ps, "loc", 23, types.GeoID, gData)
> ```

We added a coordinate location above already, that's overwritten by this edge. Should this be a  polygon or something?

---

*[query/query_test.go, line 1770 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdYQhAZQUlA7fzzazW:-KXdYQhBKK6HjAEi1inH:bcq7o7w) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L1770)):*
> ```Go
> 
> 	var l Latency
> 	js, err := sg.ToJSON(&l)
> ```

Would be good to abstract out the part from gql.Parse to here in another function, as this is repeated in all tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-:-KXdZ32wLgjAlDARE5x8:bbehbrj)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdaxGmMppxdCROF3Q6:-KXdaxGmMppxdCROF3Q7:bxwaw50) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L178)):*
> ```Go
> 	addEdgeToValue(t, ps, "age", 23, "15")
> 
> 	err = coord.UnmarshalText([]byte("{\"Type\":\"Polygon\", \"Coordinates\":[[[0.0,0.0], [2.0,0.0], [2.0, 2.0], [0.0, 2.0]]]}"))
> ```

Backtildes for raw strings.

---

*[query/query_test.go, line 1770 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdYQhAZQUlA7fzzazW:-KXdaBZyRRL2yDlmbVsU:b-qg6zgu) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L1770)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Would be good to abstract out the part from gql.Parse to here in another function, as this is repeated in all tests.
</blockquote></details>

FYI: At Google, any calls to EXPECT_EQ or other checks, which is equivalent to require.EqualValues, are to be at top-level, not nested inside any functions. The reason is that we want the tests to be simple to read and with as little logic as possible.

I don't agree with everything Google says. For our purpose, I think it is good to nest a bit, but just don't overdo it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-:-KXdbtlpGGiiiSERVbpl:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdaxGmMppxdCROF3Q6:-KXdnoe1nanw--QTWsdI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L178)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Backtildes for raw strings.
</blockquote></details>

Done.

---

*[query/query_test.go, line 178 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdXgJmQ90WNkxBFCRP:-KXdnoy0sFOYFb8PV2fr:b2k68tv) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L178)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

how about we do this above with the other geo stuff?
</blockquote></details>

I think the insertions are done element wise (Per Uid).

---

*[query/query_test.go, line 182 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdYoRfzYLjBxHXHXgR:-KXdnzXmxpAHtgN2vc0b:b4wcx60) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L182)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We added a coordinate location above already, that's overwritten by this edge. Should this be a  polygon or something?
</blockquote></details>

That is for Uid 1. This is for 23.

---

*[query/query_test.go, line 1770 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-KXdYQhAZQUlA7fzzazW:-KXdo_7KDjJBVIUyOWMj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a697c8bdad8ee96130c85c8a2040c97c7f4d4b43/query/query_test.go#L1770)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

FYI: At Google, any calls to EXPECT_EQ or other checks, which is equivalent to require.EqualValues, are to be at top-level, not nested inside any functions. The reason is that we want the tests to be simple to read and with as little logic as possible.

I don't agree with everything Google says. For our purpose, I think it is good to nest a bit, but just don't overdo it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/342)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/342#-:-KXdr2jHW3v5tLn4fbww:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
