### PR TITLE
Fix empty stack bug

### LINKED ISSUE #558: Malformed query crashes the server.
Found this from the debug logs of Dgraph server.
```
 {
  debug(allof("name.en", "steven spielberg")) {
    name.en
    director.film @filter(leq("initial_release_date", "2016-01-01") and) {
      name.en
      initial_release_date
      country {
        name.en
      }
      starring {
        performance.actor {
          name.en
        }
        performance.character {
          name.en
        }
      }
      genre {
        name.en
      }
    }
  }
}
```

This crashes the server with the logs
```
2017/02/01 13:24:47 error.go:75: Trying to pop empty stack
```

### PR DESCRIPTION
**Pull request by ashwin95r**
Fixes #558

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/565)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/565#-:-KbxfBcm0QJMKPYpfNBa:bnfp4nl)*

**Comment by ashishnegi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[gql/parser.go, line 852 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/565#-KbxgayWJiHqvnjnWkds:-KbxgayXg4LpBCfrjecp:b-k1dzwi) ([raw file](https://github.com/dgraph-io/dgraph/blob/452281e1feecc0d38d4fa61fe6653e5f7f4b18a5/gql/parser.go#L852)):*
> ```Go
> 		// "and" and "or" are binary operators, so pop two values.
> 		topVal1, err := valueStack.pop()
> 		if err != nil {
> ```

will it be better to add `size` fn and we check whether it is >= 2 or not ..?
otherwise we have to do `err != nil` again and again..
Or maybe `popN(n int) ([]*FilterTree, error)` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/565)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gql/parser.go, line 852 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/565#-KbxgayWJiHqvnjnWkds:-KbxpDn3bo3MQX1JAE1T:b-jgvmmm) ([raw file](https://github.com/dgraph-io/dgraph/blob/452281e1feecc0d38d4fa61fe6653e5f7f4b18a5/gql/parser.go#L852)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

will it be better to add `size` fn and we check whether it is >= 2 or not ..?
otherwise we have to do `err != nil` again and again..
Or maybe `popN(n int) ([]*FilterTree, error)` ?
</blockquote></details>

Using size function at this place. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/565)*

**Comment by ashishnegi** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/565#-:-Kbxr7rMd7QVhf5-mUk7:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
