### PR TITLE
 Stream oracle delta

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1700)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/client.go, line 165 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjnocFlcwKVT8DBWV-:-KxjnocGKhs8DgytNfQn:b2ngxxo) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/client/client.go#L165)):*
> ```Go
> }
> 
> func (d *Dgraph) commitOrAbort(ctx context.Context, txn *protos.TxnContext) (*protos.TxnContext, error) {
> ```

100

---

*[posting/oracle.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxjr_s4PHZWJj788JRA:-Kxjr_s4PHZWJj788JRB:b22vsol) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/posting/oracle.go#L41)):*
> ```Go
> 	x.SafeMutex
> 	commits    map[uint64]uint64
> 	aborts     map[uint64]struct{}
> ```

Remove aborts from here, as they aren't being used.

---

*[posting/oracle.go, line 69 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjogQEwsmZGOY3jS2C:-KxjogQEwsmZGOY3jS2D:b3k4goc) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/posting/oracle.go#L69)):*
> ```Go
> func (o *oracle) WaitForTs(ctx context.Context, startTs uint64) error {
> 	o.Lock()
> 	if o.maxpending >= startTs {
> ```

Add a function to avoid this lock release issue.

---

*[posting/oracle.go, line 95 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxjp2MAR5zQ1DSKjwoZ:-Kxjp2MAR5zQ1DSKjwo_:b5e4x62) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/posting/oracle.go#L95)):*
> ```Go
> 		return
> 	}
> 	for i := o.maxpending + 1; i <= od.MaxPending; i++ {
> ```

Iterate over the waiters, and then check if the wait is <= maxpending. If so, close and also delete.

---

*[worker/groups.go, line 598 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjpWvZU-YO03irVyE5:-KxjpWvZU-YO03irVyE6:bibpmy4) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/worker/groups.go#L598)):*
> ```Go
> func (g *groupi) processOracleDeltaStream() {
> START:
> 	pl := g.AnyServer(0)
> ```

g.Leader(0)

---

*[worker/groups.go, line 607 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjpgrPgQbO6fdTbx1w:-KxjpgrPgQbO6fdTbx1x:bs5k4y5) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/worker/groups.go#L607)):*
> ```Go
> 
> 	c := protos.NewZeroClient(pl.Get())
> 	ctx, cancel := context.WithCancel(context.Background())
> ```

No need to have this ctx. Just use background.

---

*[worker/groups.go, line 625 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxjr3aofBm80uKle_hc:-Kxjr3aofBm80uKle_hd:b-io2lsn) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/worker/groups.go#L625)):*
> ```Go
> 		for startTs, commitTs := range oracleDelta.Commits {
> 			tctx := &protos.TxnContext{StartTs: startTs, CommitTs: commitTs}
> 			go g.Node.ProposeAndWait(context.Background(), &protos.Proposal{TxnContext: tctx})
> ```

Only leader should propose this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-:-KxjsaGOOX7vRcdl_fQk:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 8 of 15 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/client.go, line 165 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjnocFlcwKVT8DBWV-:-Kxjx0HYkmtSu3VREUZi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/client/client.go#L165)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100
</blockquote></details>

Done.

---

*[posting/oracle.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxjr_s4PHZWJj788JRA:-Kxjx1KVqk2BshGGf5tB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/posting/oracle.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove aborts from here, as they aren't being used.
</blockquote></details>

Done.

---

*[posting/oracle.go, line 69 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjogQEwsmZGOY3jS2C:-KxjwvwjvRTjEFAR0-id:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/posting/oracle.go#L69)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a function to avoid this lock release issue.
</blockquote></details>

Done.

---

*[posting/oracle.go, line 95 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxjp2MAR5zQ1DSKjwoZ:-Kxjwwge-ng7OOVw4ySB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/posting/oracle.go#L95)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Iterate over the waiters, and then check if the wait is <= maxpending. If so, close and also delete.
</blockquote></details>

Done.

---

*[worker/groups.go, line 598 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjpWvZU-YO03irVyE5:-KxjwyoSt6tUbT-yj1Nw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/worker/groups.go#L598)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

g.Leader(0)
</blockquote></details>

Done.

---

*[worker/groups.go, line 607 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxjpgrPgQbO6fdTbx1w:-KxjwzRA7S7Xkjz1nFFJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/worker/groups.go#L607)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to have this ctx. Just use background.
</blockquote></details>

Done.

---

*[worker/groups.go, line 625 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxjr3aofBm80uKle_hc:-Kxjx-DidfRun1haQsgL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cbe1c8b1e3378ada5f90a4626b0f6b0c7195464a/worker/groups.go#L625)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Only leader should propose this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[client/txn.go, line 126 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxkWSbBSDqqCJjeEPBD:-KxkWSbBSDqqCJjeEPBE:b-qlus3e) ([raw file](https://github.com/dgraph-io/dgraph/blob/85b48f0646c02467a749d899fdfd04cde43dbc64/client/txn.go#L126)):*
> ```Go
> 	}
> 	if tctx.Aborted {
> 		return x.Errorf("Transaction aborted")
> ```

Have a variable here so a user can check.

---

*[protos/task.proto, line 395 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxkm-AzND3fPGxsmE7W:-Kxkm-AzND3fPGxsmE7X:b-xcjvni) ([raw file](https://github.com/dgraph-io/dgraph/blob/85b48f0646c02467a749d899fdfd04cde43dbc64/protos/task.proto#L395)):*
> ```protobuf
> }
> 
> message Transactions {
> ```

Timestamps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-:-Kxkm4GO_iR4UfS8RUCj:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 13 of 18 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/txn.go, line 126 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-KxkWSbBSDqqCJjeEPBD:-KxkmMfp0c9Nl3ceri3_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/85b48f0646c02467a749d899fdfd04cde43dbc64/client/txn.go#L126)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Have a variable here so a user can check.
</blockquote></details>

Done.

---

*[protos/task.proto, line 395 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700#-Kxkm-AzND3fPGxsmE7W:-KxkrRPvYY_ETmANPNlZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/85b48f0646c02467a749d899fdfd04cde43dbc64/protos/task.proto#L395)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Timestamps
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1700)*

**Pull request closed without merging**
