### PR TITLE
'.' language handling in functions

### LINKED ISSUE #1337: Assert fails when trying to do fulltext search on language tagged predicate.
```
{ 
  me(func: anyoftext(name@., "Ivan")) { 
    name@. 
  } 
}
```

crashes the server with the error `Tokenizer not found for fulltext.`. It's trying to find a tokenizer corresponding to `.` language which doesn't exist.

### PR DESCRIPTION
**Pull request by tzdybal**
This resolves #1337.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1339)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tok/tokens.go, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1339#-KrkBzrI3fQH1-CGYQAF:-KrkBzrI3fQH1-CGYQAG:bfbikdq) ([raw file](https://github.com/dgraph-io/dgraph/blob/ee3639f2892ca4bbbf068c18a2362adae08b201a/tok/tokens.go#L37)):*
> ```Go
> 	if found {
> 		return tokenize(funcArgs, t)
> 	} else {
> ```

No need for else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1339#-:-KrkCAFMemVqIndfT8J7:bnfp4nl)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1339#-:-KrmnFCLfaFDJsf1HKDz:bnfp4nl)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1339)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1339#-:-KsqzG_ErIchph-qFbDT:bnfp4nl)*

**Pull request merged**
