### PR TITLE
handle delete predicate in snapshots, evict lru for the group which g…

### PR DESCRIPTION
**Pull request by janardhan1993**
Evict lru cache on getting snapshot
handle deleted predicates in snapshot.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1380)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[posting/lists.go, line 409 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-Ksm6dOAL0QlZLeUin4e:-Ksm6dOBuuqc-lwzQS6h:b-h2fqsm) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/posting/lists.go#L409)):*
> ```Go
> // This doesn't sync, so call this only when you don't care about dirty posting lists in
> // memory(for example before populating snapshot) or you know that there are no dirty
> // posting lists(for example after calling waitforsyncmark)
> ```

after calling syncAllMarks?

---

*[posting/lists.go, line 418 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-Ksm8lXQr8tN24G33XqA:-Ksm8lXRMjDiwQ63I4HQ:b-tjqy07) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/posting/lists.go#L418)):*
> ```Go
> 		return false
> 	})
> 	x.Checkf(err, "Error while evicting group %d", gid)
> ```

Can we return the error?

---

*[worker/predicate.go, line 295 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmAluuavkpbLLTcFQp:-KsmAluuavkpbLLTcFQq:b-x3wadq) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L295)):*
> ```Go
> 			// If a key is present in follower but not in leader, send a kv with empty value
> 			// so that the follower can delete it
> 			for bytes.Compare(gkeys.Keys[gidx].Key, k) < 0 {
> ```

Check gidx < len(gKeys)

---

*[worker/predicate.go, line 332 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-Ksm9qTyCTI9MtX7jpmr:-Ksm9qTyCTI9MtX7jpms:b-ynseof) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L332)):*
> ```Go
> 	} // end of iterator
> 
> 	// All these keys are not present in master, so mark them for deletion
> ```

leader?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380)*

**Comment by manishrjain** [comment]
:lgtm: @pawanrawal to make the final call.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-:-KsmDK9lCv0oPvuD4Af6:bhcdcjf)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[worker/predicate.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmGEIsF50vS-JvgCNn:-KsmGEIsF50vS-JvgCNo:bwtpu9l) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L58)):*
> ```Go
> 				tr.LazyPrintf("SNAPSHOT: Doing batch write num: %d", batchWriteNum)
> 			}
> 			pstore.BatchSet(wb)
> ```

need to handle errors here and below.

---

*[worker/predicate.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmF-iTsC1mOKfrERZY:-KsmF-iTsC1mOKfrERZZ:b-vymja0) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L289)):*
> ```Go
> 		// No checksum check for schema keys
> 		v := iterItem.Value()
> 		if !pk.IsSchema() {
> ```

if pk.IsSchema() {
  continue
}
....

---

*[worker/predicate.go, line 303 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmGQWBkqS3VmZocd4V:-KsmGQWBkqS3VmZocd4W:bcxw385) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L303)):*
> ```Go
> 			}
> 
> 			t := gkeys.Keys[gidx]
> ```

check gidx < len before accessing.

Also breakout of the iterator loop if gids >= len

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-:-KsmGfLg05-G6JVC54uC:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 4 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 409 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-Ksm6dOAL0QlZLeUin4e:-KspeRfwNiHjBL_hTKqO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/posting/lists.go#L409)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

after calling syncAllMarks?
</blockquote></details>

Done.

---

*[posting/lists.go, line 418 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-Ksm8lXQr8tN24G33XqA:-KspeUzs6-I0PCa0tadn:b1fx79e) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/posting/lists.go#L418)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we return the error?
</blockquote></details>

We can't handle the returned error, probably we can retry to clear again. Since it's done in background and if we don't clear the cache user would get wrong results.

---

*[worker/predicate.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmGEIsF50vS-JvgCNn:-Kspeo2tWS_mOzWeqw1G:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L58)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

need to handle errors here and below.
</blockquote></details>

Done.

---

*[worker/predicate.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmF-iTsC1mOKfrERZY:-KspeogumBx5THjEpOTG:bmzzavj) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L289)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

if pk.IsSchema() {
  continue
}
....

</blockquote></details>

Can't continue

---

*[worker/predicate.go, line 295 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmAluuavkpbLLTcFQp:-Ksulp4nvzSuirjbOPrR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L295)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Check gidx < len(gKeys)
</blockquote></details>

Done.

---

*[worker/predicate.go, line 303 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-KsmGQWBkqS3VmZocd4V:-KsulqKjz5ip89uSOA-f:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L303)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

check gidx < len before accessing.

Also breakout of the iterator loop if gids >= len
</blockquote></details>

Done.

---

*[worker/predicate.go, line 332 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-Ksm9qTyCTI9MtX7jpmr:-Kspeq0HBOU_E9KPFv9R:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d703bcc83db052618f19125a51460031caca18b/worker/predicate.go#L332)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

leader?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 4 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1380#-:-KsuofUcIoyKmwgc_r5c:bnfp4nl)*

**Pull request merged**
