### PR TITLE
RAFT: Assign UIDs via RAFT.

### PR DESCRIPTION
**Pull request by manishrjain**
Simplify the whole UID assignment logic. Use fingerprint64 for XIDs to generate corresponding UIDs, at the cost of collision probability. We no longer maintain XID -> UID map.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/256)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 16 files reviewed at latest revision, 12 unresolved discussions, some commit checks broke.

---

*[cmd/dgraph/main.go, line 137 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2WflQ0-CXiw7smX63:-KT2WflRqvN2fCDCnnb6:b6as5wg) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/cmd/dgraph/main.go#L137)):*
> ```Go
> 	var edges []x.DirectedEdge
> 	var mr mutationResult
> 	allocatedIds := make(map[string]uint64)
> ```

I think we can get rid of this, since our newToUid would contain this mapping.

---

*[cmd/dgraph/main.go, line 141 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2VkdRBivBjzeU-wDL:-KT2VkdRBivBjzeU-wDM:b7g72ov) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/cmd/dgraph/main.go#L141)):*
> ```Go
> 	// xidToUid is used to store ids which are not uids. It is sent to the instance
> 	// which has the xid <-> uid mapping to get uids.
> 	xidToUid := make(map[string]uint64)
> ```

newToUid? Maybe with a comment that only `_new_` have to be resolved over the network. `_xid_` are directly fingerprinted now.

---

*[query/query.go, line 686 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2VZkhT27Bwv0wVomK:-KT2VZkhT27Bwv0wVomL:bhy2ent) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/query/query.go#L686)):*
> ```Go
> 	// and populate the children for attributes.
> 	if len(exid) > 0 {
> 		x.Assertf(!strings.HasPrefix(exid, "_new_:"), "Query shouldn't contain _new_")
> ```

Wonder if this check should belong upstream?

---

*[rdf/parse.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2cZ25IA3djFj5cvA7:-KT2cZ25IA3djFj5cvA8:b-884wdo) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/rdf/parse.go#L50)):*
> ```Go
> 		return strconv.ParseUint(xid[6:], 0, 64)
> 	}
> 	// Get uid from posting list in UidStore.
> ```

We should remove this.

---

*[uid/assigner.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2fQyjNeI3NOfvVsiO:-KT2fQyjNeI3NOfvVsiP:b-h8l426) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/uid/assigner.go#L41)):*
> ```Go
> }
> 
> func (lm *lockManager) isNew(uid uint64) bool {
> ```

I don't fully understand the role of isNew here, since we already checking the posting list to verify that uid hasn't been assigned before.

---

*[uid/assigner.go, line 108 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2etbjIOBZRfVzv-OW:-KT2etbjIOBZRfVzv-OX:bpywseg) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/uid/assigner.go#L108)):*
> ```Go
> 		}
> 	}
> 	log.Fatalf("This shouldn't be reached.")
> ```

Is it ever possible to reach this :stuck_out_tongue: ?

---

*[worker/assign.go, line 58 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2aisvisD0oEzDLTvw:-KT2aiswxFO_iZ70D1U2:biaxrsa) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/worker/assign.go#L58)):*
> ```Go
> 	xidList *task.XidList) (uidList []byte, rerr error) {
> 	if !GetNode().AmLeader() {
> 		return uidList, x.Errorf("Assigning UIDs is only allowed on leader.")
> ```

Hmm, doesn't RAFT send all proposals to the leader?

---

*[worker/assign.go, line 95 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2Wv1SQx0Mdf1p-tBE:-KT2Wv1SQx0Mdf1p-tBF:b-nz5pcr) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/worker/assign.go#L95)):*
> ```Go
> // GetOrAssignUidsOverNetwork gets or assigns uids corresponding to xids and
> // writes them to the xidToUid map.
> func GetOrAssignUidsOverNetwork(ctx context.Context, xidToUid map[string]uint64) (rerr error) {
> ```

newToUid?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/256)*

**Comment by manishrjain** [comment]
Review status: 0 of 19 files reviewed at latest revision, 12 unresolved discussions.

---

*[cmd/dgraph/main.go, line 137 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2WflQ0-CXiw7smX63:-KT7mBYcQyZ4SpThN45Z:b-376vyo) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/cmd/dgraph/main.go#L137)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I think we can get rid of this, since our newToUid would contain this mapping.
</details>
Done. Good catch!

---

*[cmd/dgraph/main.go, line 141 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2VkdRBivBjzeU-wDL:-KT7mDhtYzqFbdkdb4wA:b-xs9u9n) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/cmd/dgraph/main.go#L141)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> newToUid? Maybe with a comment that only `_new_` have to be resolved over the network. `_xid_` are directly fingerprinted now.
</details>
Done. Called them newUids.

---

*[query/query.go, line 686 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2VZkhT27Bwv0wVomK:-KT7mPB0E-rs-jH_8oKL:b-g0wlkr) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/query/query.go#L686)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Wonder if this check should belong upstream?
</details>
Always good to assert something that should be.

---

*[rdf/parse.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2cZ25IA3djFj5cvA7:-KT7m_1MqySApdAKqpaK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/rdf/parse.go#L50)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We should remove this.
</details>
Done.

---

*[uid/assigner.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2fQyjNeI3NOfvVsiO:-KT7mcrR7z0ILZ1EV-0M:bp4ccd4) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/uid/assigner.go#L41)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I don't fully understand the role of isNew here, since we already checking the posting list to verify that uid hasn't been assigned before.
</details>
Added a comment to explain it's role.

---

*[uid/assigner.go, line 108 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2etbjIOBZRfVzv-OW:-KT7nQSVHXb9mMfl_t5e:bg7f9ms) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/uid/assigner.go#L108)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Is it ever possible to reach this :stuck_out_tongue: ?
</details>
Nope. Unless someone unwittingly changes the logic. I'd guess that's what the condition check is for.

---

*[worker/assign.go, line 58 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2aisvisD0oEzDLTvw:-KT7np6Y7kYvZGCaRLTX:bic83gb) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/worker/assign.go#L58)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, doesn't RAFT send all proposals to the leader?
</details>
Yes, but this is before the proposal is sent. We only want one server to be handing out new ids.

---

*[worker/assign.go, line 95 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT2Wv1SQx0Mdf1p-tBE:-KT7pwebUBRiJytOEZjG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e2d3279c9ce50756650b94e665161fe347e33a6/worker/assign.go#L95)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> newToUid?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/256)*

**Comment by pawanrawal** [comment]
Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/dgraph/main.go, line 170 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT7qVqi9p0SQ4Wocm0c:-KT7qVqi9p0SQ4Wocm0d:b2h1g0t) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f8c3f08f5de68e812d10c4778a326bd13090ad8/cmd/dgraph/main.go#L170)):*
> ```Go
> 	for k, v := range xidToUid {
> 		if strings.HasPrefix(k, "_new_:") {
> 			allocatedIds[k[6:]] = v
> ```

We still should strip `_new_:` from the id's in the map unless we want to change that behavior?

---

*[uid/assigner.go, line 42 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT7r7u_5Yq6eonAxNRK:-KT7r7uasuIFbED8HpoG:bwjtvm7) ([raw file](https://github.com/dgraph-io/dgraph/blob/12de0cf35951e191c98ecc20b7beddae9b5d32b3/uid/assigner.go#L42)):*
> ```Go
> 
> // isNew checks that the passed uid is the first time lockManager has seen it.
> // This avoids collisions where a uid which is proposed but still not pushed to a posting list,
> ```

We can move `a posting list,` to the next line as this line > 80 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/256)*

**Comment by pawanrawal** [comment]
:lgtm: One small change that you might want to make apart from that looks good.

---

Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-:-KT7rqXcUiYyiVefbfPa:bx59wem)*

**Comment by manishrjain** [comment]
Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[cmd/dgraph/main.go, line 170 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT7qVqi9p0SQ4Wocm0c:-KT7uuPtTi3dQU2Ku_ME:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f8c3f08f5de68e812d10c4778a326bd13090ad8/cmd/dgraph/main.go#L170)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We still should strip `_new_:` from the id's in the map unless we want to change that behavior?
</details>
Done.

---

*[uid/assigner.go, line 42 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/256#-KT7r7u_5Yq6eonAxNRK:-KT7uz6i1BphQWfoSaC3:bu9bdei) ([raw file](https://github.com/dgraph-io/dgraph/blob/12de0cf35951e191c98ecc20b7beddae9b5d32b3/uid/assigner.go#L42)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We can move `a posting list,` to the next line as this line > 80 chars.
</details>
Line length can be 100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/256)*

**Pull request closed without merging**
