### PR TITLE
Add features to Set/Delete Object

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Allow `S * *` and `* P *` deletion.
2. Allow setting values for predicates of list type.
3. Allow setting and retrieving `[]byte`.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1580)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/unmarshal.go, line 179 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-Kv_YJnYt6bP4dd4mqiz:-Kv_YJnYt6bP4dd4mqj-:bo2xivc) ([raw file](https://github.com/dgraph-io/dgraph/blob/1402c371c1d0065d5f7fd663e26a930b86df24c9/client/unmarshal.go#L179)):*
> ```Go
> 				// here.
> 				str := value.GetStrVal()
> 				data, err := base64.StdEncoding.DecodeString(str)
> ```

What happens if the user's data happens to be a valid base 64 encoding ?

---

*[dgraph/server.go, line 408 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-Kv_Xmm7IEU0Po1FvEwJ:-Kv_Xmm7IEU0Po1FvEwK:b-mqo074) ([raw file](https://github.com/dgraph-io/dgraph/blob/1402c371c1d0065d5f7fd663e26a930b86df24c9/dgraph/server.go#L408)):*
> ```Go
> 		*idx++
> 	}
> ```

We don't throw error for any empty map with op delete ?

---

*[dgraph/server.go, line 489 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-Kv_X8SAoEwZU4m6-R9z:-Kv_X-G6OyDOPUmOjUuB:bq5e8s3) ([raw file](https://github.com/dgraph-io/dgraph/blob/1402c371c1d0065d5f7fd663e26a930b86df24c9/dgraph/server.go#L489)):*
> ```Go
> 
> 				switch iv := item.(type) {
> 				case string, float64, bool:
> ```

Does list type for bool have any use ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-:-Kv_XtQHghbgm-mRl6Qt:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 3 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/unmarshal.go, line 179 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-Kv_YJnYt6bP4dd4mqiz:-Kv_bqnY_J-uIaHY8pfQ:b-5sbkjd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1402c371c1d0065d5f7fd663e26a930b86df24c9/client/unmarshal.go#L179)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

What happens if the user's data happens to be a valid base 64 encoding ?
</blockquote></details>

json.Marshal would encode it again.

---

*[dgraph/server.go, line 408 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-Kv_Xmm7IEU0Po1FvEwJ:-Kv__2UfCr7lEqgh3cXy:bpqfz11) ([raw file](https://github.com/dgraph-io/dgraph/blob/1402c371c1d0065d5f7fd663e26a930b86df24c9/dgraph/server.go#L408)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We don't throw error for any empty map with op delete ?
</blockquote></details>

It won't end up doing anything I think.

---

*[dgraph/server.go, line 489 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-Kv_X8SAoEwZU4m6-R9z:-Kv_apRWSBR8zWXhwU7F:b-5mekdh) ([raw file](https://github.com/dgraph-io/dgraph/blob/1402c371c1d0065d5f7fd663e26a930b86df24c9/dgraph/server.go#L489)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Does list type for bool have any use ?
</blockquote></details>

Nope removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1580#-:-Kv_p6IMw2YeYMZI-nqY:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master as of 002140840fe4bda19618dfbfa48445446593f832

**Pull request closed without merging**
