### PR TITLE
Update/badger2

### PR DESCRIPTION
**Pull request by pawanrawal**
Use the new `item.Value` API.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1448)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 44 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/predicate.go, line 308 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsEy7OsJuUKt8d-56V:-KtsEy7OsJuUKt8d-56W:b65nz72) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/worker/predicate.go#L308)):*
> ```Go
> 		var v []byte
> 		if err := iterItem.Value(func(val []byte) error {
> 			v = make([]byte, len(val))
> ```

there is a copy here, otherwise, the streaming logic and other stuff has to be put here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448)*

**Comment by manishrjain** [comment]
:lgtm: Comments.

---

Reviewed 47 of 47 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/postingiterator/main.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsdbTfAaH-GhIRb8WG:-KtsdbTgAtpnpphM_yjg:btl5d94) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/cmd/postingiterator/main.go#L48)):*
> ```Go
> 	defer ps.Close()
> 
> 	it := ps.NewIterator(badger.DefaultIteratorOptions)
> ```

Don't fetch value.

---

*[cmd/postingiterator/main.go, line 55 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsdcbX9SOQA4LtU0Rz:-KtsdcbX9SOQA4LtU0S-:b-x9zsbk) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/cmd/postingiterator/main.go#L55)):*
> ```Go
> 		k := iterItem.Key()
> 		pk := x.Parse(k)
> 		iterItem.Value(func(val []byte) error {
> ```

Use EstimateSize for this.

---

*[posting/index.go, line 516 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsdkG9G4KJvtcIbEQN:-KtsdkG9G4KJvtcIbEQO:b6tpcu8) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/posting/index.go#L516)):*
> ```Go
> 		pki := x.Parse(key)
> 		var pl protos.PostingList
> 		if err := iterItem.Value(func(val []byte) error {
> ```

`err := ...`

if err != nil {
}

---

*[worker/predicate.go, line 138 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsfjwfwtRm8xgzCNHW:-KtsfjwfwtRm8xgzCNHX:by5ur0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/worker/predicate.go#L138)):*
> ```Go
> 		var pl protos.PostingList
> 		if err := iterItem.Value(func(val []byte) error {
> 			posting.UnmarshalOrCopy(val, iterItem.UserMeta(), &pl)
> ```

In steam keys can avoid doing unmarsal, by just doing a checksum of the bytes directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-:-KtsftQqtoO-G6arEyd9:b9wrqbv)*

**Comment by pawanrawal** [comment]
Review status: 38 of 44 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/postingiterator/main.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsdbTfAaH-GhIRb8WG:-KtshjkISMZAI5NOgGxN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/cmd/postingiterator/main.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't fetch value.
</blockquote></details>

Done.

---

*[cmd/postingiterator/main.go, line 55 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsdcbX9SOQA4LtU0Rz:-KtshkCJufpzX9XSywkh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/cmd/postingiterator/main.go#L55)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Use EstimateSize for this.
</blockquote></details>

Done.

---

*[posting/index.go, line 516 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsdkG9G4KJvtcIbEQN:-Ktsi6hwCWg1G3vE2ZlT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/posting/index.go#L516)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`err := ...`

if err != nil {
}
</blockquote></details>

Done.

---

*[worker/predicate.go, line 138 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-KtsfjwfwtRm8xgzCNHW:-KtsnJp0eQmy2jINctIE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/worker/predicate.go#L138)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

In steam keys can avoid doing unmarsal, by just doing a checksum of the bytes directly.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 11 of 47 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[dgraph/server.go, line 86 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-Ktsd7fKdagmpo8LHjWX:-Ktsd7fKdagmpo8LHjWY:b-1m4bck) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/dgraph/server.go#L86)):*
> ```Go
> 	case "loadtoram":
> 		opt.TableLoadingMode = options.LoadToRAM
> 	case "nothing":
> ```

Change nothing to fileIO in dgraph options and flag description also.

---

*[worker/predicate.go, line 120 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-Ktt17VuGfsB49a4jiQw:-Ktt17VuGfsB49a4jiQx:b-it1ziu) ([raw file](https://github.com/dgraph-io/dgraph/blob/67685cec2110632c783be9c6b68e8d834f4fa361/worker/predicate.go#L120)):*
> ```Go
> 		err := iterItem.Value(func(val []byte) error {
> 			checksum := md5.Sum(val)
> 			key.Checksum = checksum[:]
> ```

= checksum ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-:-Ktt1tB3_MyvbLHoFksS:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 43 of 45 files reviewed at latest revision, 7 unresolved discussions.

---

*[dgraph/server.go, line 86 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-Ktsd7fKdagmpo8LHjWX:-KttIe_zJjRZjJr_w5DY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e17463466f2ab1268f6096d209ab7d646e5b1ed8/dgraph/server.go#L86)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Change nothing to fileIO in dgraph options and flag description also.
</blockquote></details>

Done.

---

*[worker/predicate.go, line 120 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448#-Ktt17VuGfsB49a4jiQw:-KttIlFMDW9GhYvpfbYj:bu9fpyy) ([raw file](https://github.com/dgraph-io/dgraph/blob/67685cec2110632c783be9c6b68e8d834f4fa361/worker/predicate.go#L120)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

= checksum ?
</blockquote></details>

checksum is array, has to be converted to []byte.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1448)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
