### PR TITLE
Modifying AddMutation and AddLog

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/90)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[commit/log.go, line 469 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/90#-KI7W241NNUfA2iOqHFY:-KI7W241NNUfA2iOqHFZ:-89794163) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e06607e7cf5459c9d8ec39a2681408f9cd23bf7/commit/log.go#L469)):*
> ```Go
> 
> 	ts := time.Now().UnixNano()
> 	if ts < atomic.LoadInt64(&l.lastLogTs) {
> ```

lts := atomic.Load(..)
if ts < lts {
 ts = lts + 1
}

---

*[posting/list.go, line 626 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/90#-KI7WfiYry-ryTpM0Xai:-KI7WfiYry-ryTpM0Xaj:-1243048728) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e06607e7cf5459c9d8ec39a2681408f9cd23bf7/posting/list.go#L626)):*
> ```Go
> 		return nil
> 	}
> 	ts, err := l.clog.AddLog(l.hash, mbuf)
> ```

This should be done before you acquire the lock.

Also, move this within if l.clog != nil { .. } because you've moved this clause upwards in the function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/90)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/list.go, line 626 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/90#-KI7WfiYry-ryTpM0Xai:-KI7Yo31DQfeAzZbvvSa:1212764010) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e06607e7cf5459c9d8ec39a2681408f9cd23bf7/posting/list.go#L626)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should be done before you acquire the lock.
> 
> Also, move this within if l.clog != nil { .. } because you've moved this clause upwards in the function.
</details>
Hmm, but I need mbuf which is only computed after I have acquired the lock.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/90)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/list.go, line 626 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/90#-KI7WfiYry-ryTpM0Xai:-KI7ouhJ6uqWMOaEUNo3:41858723) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e06607e7cf5459c9d8ec39a2681408f9cd23bf7/posting/list.go#L626)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, but I need mbuf which is only computed after I have acquired the lock.
</details>
But it doesn't need the lock. Have a look at the newPosting function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/90)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/list.go, line 626 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/90#-KI7WfiYry-ryTpM0Xai:-KI84etgu-JsX5v1qjYN:1486865723) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e06607e7cf5459c9d8ec39a2681408f9cd23bf7/posting/list.go#L626)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> But it doesn't need the lock. Have a look at the newPosting function.
</details>
Hmm, made these changes. Could you take over this? Having a hard time understanding why are the tests breaking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/90)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[posting/list.go, line 626 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/90#-KI7WfiYry-ryTpM0Xai:-KIA-LVISucERmXqKRMh:640062375) ([raw file](https://github.com/dgraph-io/dgraph/blob/2e06607e7cf5459c9d8ec39a2681408f9cd23bf7/posting/list.go#L626)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, made these changes. Could you take over this? Having a hard time understanding why are the tests breaking.
</details>
We can go through this together today.

---

*[posting/list.go, line 594 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/90#-KIA-BTvmN5voRye4d3x:-KIA-BTvmN5voRye4d3y:1084972443) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9b720ce8ab68515de1ec2edfd57ac92ad685b40/posting/list.go#L594)):*
> ```Go
> 	mbuf := newPosting(t, op)
> 	if l.clog == nil {
> 		return nil
> ```

You can't do this, as I mentioned earlier.  Think about what's happening here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/90)*

**Pull request merged**
