### PR TITLE
Allow only one sortable index per predicate

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/822)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[schema/parse.go, line 185 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/822#-KhKrD7oeydUQk04pMVx:-KhKrD7oeydUQk04pMVy:b-hwgnsa) ([raw file](https://github.com/dgraph-io/dgraph/blob/104a0862bd453330c1426560ae4d87c7746a26b7/schema/parse.go#L185)):*
> ```Go
> 					predicate)
> 			}
> 			seenSortableTok = true
> ```

Need to add similar check in schema mutations which comes via grpc. (In enrichSchema in main.go )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/822#-:-KhKrTWal2xTezlLOfv8:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[schema/parse.go, line 185 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/822#-KhKrD7oeydUQk04pMVx:-KhKtIHpIjbFSPm0-zE_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/104a0862bd453330c1426560ae4d87c7746a26b7/schema/parse.go#L185)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Need to add similar check in schema mutations which comes via grpc. (In enrichSchema in main.go )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/822)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/822#-:-KhKtV9B5U1PAkMpq2Lf:bnfp4nl)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/822#-:-KhKvlVphxr9275vSTug:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
