### PR TITLE
Have endpoint for /query

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/215)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm:  Solution seems a bit hacky, but can't think of a better way. Maybe add a comment there above the sleep.
Also, please make the travis change in this PR only, requires you to remove email and instead add slack for notifications. That way we can test this when its merged to master.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/215#-:-KRc7m3HuneNcTWubKFl:b-qetdxy)*

**Comment by manishrjain** [comment]
Did you check for /debug/requests endpoint?

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/dgraph/main.go, line 98 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/215#-KRd2w-3TTY9ZnJVpfwf:-KRd2w-4b74wH9-wnBuO:b5v57q9) ([raw file](https://github.com/dgraph-io/dgraph/blob/31fea6b9f8d9c0bb843a1964fb8d3c67054a2ce6/cmd/dgraph/main.go#L98)):*
> ```Go
> 	go func() {
> 		time.Sleep(1 * time.Second)
> 		os.Exit(0)
> ```

This looks weird to me. Ideally, the main function should return. This looks more like a kill.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/215#-:-KRd34xsbka1rv-RmQSb:b-2wnikd)*

**Comment by ashwin95r** [comment]
Yeah, /debug/requests works. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/dgraph/main.go, line 98 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/215#-KRd2w-3TTY9ZnJVpfwf:-KRdoy-zWtlYr6oKmKh2:bxl1b4p) ([raw file](https://github.com/dgraph-io/dgraph/blob/31fea6b9f8d9c0bb843a1964fb8d3c67054a2ce6/cmd/dgraph/main.go#L98)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This looks weird to me. Ideally, the main function should return. This looks more like a kill.
</details>
Since we handle the requests in handler functions, I'm not sure that we can exit from main. This is a clean exit that we are doing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/215#-:-KRdotLbCTHXST_4o5qf:b7pll87)*

**Comment by manishrjain** [comment]
I'd suggest looking at this thread, to see what you can pick up about gracefully shutting down the server.
https://github.com/golang/go/issues/4674

Also, if @pawanrawal thinks this is hacky, we should def look deeper to avoid it.

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/215#-:-KS1XpZ59fYX9MKj5hdX:bnfp4nl)*

**Pull request closed without merging**
