### PR TITLE
Parallelize/iteration

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/836)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 347 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-KhWkFEiPIfOkilfwyef:-KhWkFEjkaWnUf0ANtSB:b-zhd7x7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0ae8c17d5c6c44cd1a939befa78772d5252be21/worker/task.go#L347)):*
> ```Go
> 				tlist := &taskp.List{[]uint64{pk.Uid}}
> 				mu.Lock()
> 				out.UidMatrix = append(out.UidMatrix, tlist)
> ```

Doesn't this uidmatrix need to have the uid's in sorted order. I am not familiar with this part of the code. Appending it in a goroutine with locks can cause the values in uid matrix to be in any order. Is it fine ?

---

*[worker/task.go, line 804 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-KhWlFjiIDdLiyw3OHkP:-KhWlFjjWVUYEI3ghxjG:bxzdav6) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0ae8c17d5c6c44cd1a939befa78772d5252be21/worker/task.go#L804)):*
> ```Go
> func iterateParallel(ctx context.Context, q *taskp.Query, f func([]byte, []byte, sync.Mutex)) {
> 	numPart := uint64(32)
> 	grpSize := uint64(math.MaxUint64 / uint64(numPart))
> ```

There would be no benefit of parallel iteration if total number of uid's for that predicate is less than grpsize. It might be better to estimate the total size for that prefix and split based on that.

---

*[worker/task.go, line 821 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-KhWmc51VxDwbYWg5OAX:-KhWmc51VxDwbYWg5OAY:bd13l00) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0ae8c17d5c6c44cd1a939befa78772d5252be21/worker/task.go#L821)):*
> ```Go
> 			startKey := x.DataKey(q.Attr, minUid)
> 			pk := x.Parse(startKey)
> 			dataPrefix := pk.DataPrefix()
> ```

Name it just prefix may be. (Since it can reverseprefix also)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/836)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 347 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-KhWkFEiPIfOkilfwyef:-KhZzyg7pGTSmkVPxYQc:b5jqm9l) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0ae8c17d5c6c44cd1a939befa78772d5252be21/worker/task.go#L347)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Doesn't this uidmatrix need to have the uid's in sorted order. I am not familiar with this part of the code. Appending it in a goroutine with locks can cause the values in uid matrix to be in any order. Is it fine ?
</blockquote></details>

Yeah that should be fine. It's not required to be sorted. If the user specifies some order, then we sort it anyways.

---

*[worker/task.go, line 804 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-KhWlFjiIDdLiyw3OHkP:-Kh_-BjvTTll-Vk0SWJ7:b-wfyw9o) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0ae8c17d5c6c44cd1a939befa78772d5252be21/worker/task.go#L804)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

There would be no benefit of parallel iteration if total number of uid's for that predicate is less than grpsize. It might be better to estimate the total size for that prefix and split based on that.
</blockquote></details>

Is there a easy way to estimate the number of keys? If yes we can do that.

---

*[worker/task.go, line 821 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-KhWmc51VxDwbYWg5OAX:-Kh_BtzgIJssRCTiPKcW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0ae8c17d5c6c44cd1a939befa78772d5252be21/worker/task.go#L821)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Name it just prefix may be. (Since it can reverseprefix also)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/836)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 803 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-Kh_hu0KsQcI5_0TFDFi:-Kh_hu0KsQcI5_0TFDFj:b-3drp11) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd8c456e9de044b4b611e1a6b2ea1b3873829bff/worker/task.go#L803)):*
> ```Go
> 
> func iterateParallel(ctx context.Context, q *taskp.Query, f func([]byte, []byte, sync.Mutex)) {
> 	numPart := uint64(32)
> ```

const outside.

---

*[worker/task.go, line 829 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-Kh_i0xA_AU5bSoZdvtH:-Kh_i0xA_AU5bSoZdvtI:b-cjl81h) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd8c456e9de044b4b611e1a6b2ea1b3873829bff/worker/task.go#L829)):*
> ```Go
> 
> 			for it.Seek(startKey); it.ValidForPrefix(prefix); it.Next() {
> 				pk := x.Parse(it.Key().Data())
> ```

output a trace every 1000 keys, with the key itself, including the goroutine id.

goroutine: %d Processed %d keys, key: %s. Every 1000 keys.

---

*[worker/task.go, line 832 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-Kh_iHl1wSDX1OAbSDlK:-Kh_iHl1wSDX1OAbSDlL:bf46k3c) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd8c456e9de044b4b611e1a6b2ea1b3873829bff/worker/task.go#L832)):*
> ```Go
> 				x.AssertTruef(pk.Attr == q.Attr,
> 					"Invalid key obtained for comparison")
> 				if pk.Uid >= maxUid {
> ```

Seems like there's an off by one error here. maxUid should be included here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-:-Kh_ido-asgkF0K6Dp_a:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 803 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-Kh_hu0KsQcI5_0TFDFi:-Kha8KFZ_K0VDTsSULZM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd8c456e9de044b4b611e1a6b2ea1b3873829bff/worker/task.go#L803)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

const outside.
</blockquote></details>

Done.

---

*[worker/task.go, line 829 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-Kh_i0xA_AU5bSoZdvtH:-Kha7verH7TdE50YNhvr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd8c456e9de044b4b611e1a6b2ea1b3873829bff/worker/task.go#L829)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

output a trace every 1000 keys, with the key itself, including the goroutine id.

goroutine: %d Processed %d keys, key: %s. Every 1000 keys.
</blockquote></details>

Done.

---

*[worker/task.go, line 832 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/836#-Kh_iHl1wSDX1OAbSDlK:-Kha7wzlinf8XQq_D952:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd8c456e9de044b4b611e1a6b2ea1b3873829bff/worker/task.go#L832)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Seems like there's an off by one error here. maxUid should be included here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/836)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
