### PR TITLE
[docs]example on how to turn on/off query logging dynamically

### PR DESCRIPTION
**Pull request by OmarAyo**
explained with examples how to turn on/off query logging via graphql mutation

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7077)

### CODE REVIEW

**Review by MichelDiz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7077)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @danielmai, @MichaelJCompton, @MichelDiz, and @OmarAyo)

*[a discussion](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MOH6-CK3-2c4vEnBANB:-MOH6-CK3-2c4vEnBANC:b43k1ku) (no related file):*
We need to make clear that this flag will start to show logs of queries at the Dgraph instance. And also we need to know if it will reflect in all instances. Not just one.
I see a reference here https://dgraph.io/docs/deploy/log-format/#increase-logging 
Maybe just adding this link in that GraphQL docs should help already. It's up to you.

---

**Review by MichelDiz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-:-MOafYSL-ZYYPwwcfPC8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai, @MichaelJCompton, and @OmarAyo)

**Review by aaroncarey — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7077)* status: all files reviewed, 5 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/deploy/log-format.md, line 57 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObYy3gCEt9F369K0Ze:-MObYy3gCEt9F369K0Zf:bn08z1r) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L57)):*
> ```
> You can also dynamically turn query logging on or off without restarting an Alpha node. To toggle query logging on or off, send the following GraphQL mutation to the `/admin` endpoint of an Alpha node (e.g. `localhost:8080/admin`):
> ```
___
*[wiki/content/deploy/log-format.md, line 69 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObZ7xe4T0Z86cm5e-V:-MObZ7xe4T0Z86cm5e-W:b-odjpq2) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L69)):*
> ```
> The response should look like the following:
> ```
___
*[wiki/content/deploy/log-format.md, line 91 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObZD4ZCGLxWR5q62si:-MObZD4ZCGLxWR5q62sj:bicsbzo) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L91)):*
> ```
> Also, the Alpha node will print the following INFO message to confirm that the mutation has been applied:
> ```
___
*[wiki/content/deploy/log-format.md, line 96 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObZH_z25G4ElxLzKZC:-MObZH_z25G4ElxLzKZD:b1i8ka3) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L96)):*
> ```
> Similarly, you can turn off query logging by setting `logRequest` to `false` in the above mutation.
> ```

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/log-format.md, line 57 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObYy3gCEt9F369K0Ze:-MP5lF-uEDaVZgL1HVgB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L57)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> You can also dynamically turn query logging on or off without restarting an Alpha node. To toggle query logging on or off, send the following GraphQL mutation to the `/admin` endpoint of an Alpha node (e.g. `localhost:8080/admin`):
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/log-format.md, line 69 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObZ7xe4T0Z86cm5e-V:-MP5lFR89xqyc0hGyA8C:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L69)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> The response should look like the following:
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/log-format.md, line 91 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObZD4ZCGLxWR5q62si:-MP5lFvU1oY-4fxVYX-V:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L91)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Also, the Alpha node will print the following INFO message to confirm that the mutation has been applied:
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/log-format.md, line 96 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7077#-MObZH_z25G4ElxLzKZC:-MP5lGFd7CF8xxuwDYvO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea7daba6d5acb5b35cb730f4cca1f12a37612409/wiki/content/deploy/log-format.md#L96)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> Similarly, you can turn off query logging by setting `logRequest` to `false` in the above mutation.
> ```

</blockquote></details>

Done.

**Pull request merged**
