### PR TITLE
fix(cve): resolve cve's in slash

### PR DESCRIPTION
**Pull request by joshua-goldstein**
Similar to https://github.com/dgraph-io/dgraph/pull/8743 but two changes.
- github.com/dgraph-io/graphql-transport-ws did not have any CVE's, see https://github.com/dgraph-io/dgraph/pull/8624:
- Bumping google.golang.org/grpc@v1.27.0 to v1.52.0 caused issues, but this was not a CVE fix.  See https://github.com/dgraph-io/dgraph/pull/8655

We now have parity with main branch (i.e. equal number and same CVE's on main and slash).

### CODE REVIEW

**Comment by joshua-goldstein** [comment]
reverting grpc change causes all CI to pass...  huge list of dependencies change (see below)

go get google.golang.org/grpc@v1.27.0
```
joshua@joshua-local:~/Developer/dgraph$ go get google.golang.org/grpc@v1.27.0
go: downloading github.com/spf13/afero v1.6.0
go: downloading google.golang.org/api v0.22.0
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go: removed cloud.google.com/go/compute v1.15.1
go: downgraded cloud.google.com/go/compute/metadata v0.2.3 => v0.2.0
go: downgraded cloud.google.com/go/firestore v1.9.0 => v1.1.1
go: downgraded cloud.google.com/go/logging v1.6.1 => v1.0.0
go: downgraded cloud.google.com/go/pubsub v1.27.1 => v1.2.0
go: downgraded cloud.google.com/go/spanner v1.41.0 => v1.2.0
go: downgraded github.com/census-instrumentation/opencensus-proto v0.4.0 => v0.3.0
go: downgraded github.com/envoyproxy/go-control-plane v0.10.2-0.20220325020618-49ff273808a1 => v0.9.8
go: downgraded github.com/envoyproxy/protoc-gen-validate v0.9.1 => v0.6.7
go: downgraded github.com/google/martian/v3 v3.2.1 => v3.1.0
go: downgraded github.com/grpc-ecosystem/grpc-gateway v1.16.0 => v1.14.5
go: downgraded github.com/grpc-ecosystem/grpc-gateway/v2 v2.2.0 => v2.0.0-alpha.2
go: downgraded github.com/prometheus/client_golang v1.14.0 => v1.11.1
go: downgraded go.opencensus.io v0.24.0 => v0.22.5
go: removed go.opentelemetry.io/proto/otlp v0.12.0
go: downgraded google.golang.org/api v0.103.0 => v0.22.0
go: downgraded google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f => v0.0.0-20200526211855-cb27e3aa2013
go: downgraded google.golang.org/grpc v1.52.0 => v1.27.0
```

**Comment by skrdgraph** [comment]
@joshua-goldstein thanks for going down this rabbit hole ... this is good to get in. 

Need to validate Trivy run on this (preferably locally) .. I will discuss this with you tomorrow.

**Review by sanjayk-github-dev — APPROVED** [review]

**Comment by joshua-goldstein** [comment]
attempting 
`go get github.com/graph-gophers/graphql-go@v1.3.0`

**Review by skrdgraph — APPROVED** [review]
This PR brings all the CVE fixes from `main` into `v23` branch.

The other `go.mod` changes which was not brought in from main, are coming from cherry-icks OR new code changes & are unrelated to CVE fixes.

**Pull request merged**
