### PR TITLE
Run vlog GC in a more smart manner.

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Run it every 10 mins.
2. Also run it when size of vlog increases by a GB.
---

Before merging
- [x] Get the corresponding change merged to Badger.
- [x] Update version of Badger.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1879)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[edgraph/server.go, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-dNw5iJPdSFlQ48FvJ:-L-dNw5iJPdSFlQ48FvK:b-6ccmhg) ([raw file](https://github.com/dgraph-io/dgraph/blob/f94855d182d7f40286578c4256b82393fd366d5c/edgraph/server.go#L90)):*
> ```Go
> 	counter := 0
> 
> 	for range s.vlogTicker.C {
> ```

Have two tickers.

---

*[edgraph/server.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-dO7cEqfNyecfxGHSh:-L-dO7cEqfNyecfxGHSi:b-uma2dg) ([raw file](https://github.com/dgraph-io/dgraph/blob/f94855d182d7f40286578c4256b82393fd366d5c/edgraph/server.go#L97)):*
> ```Go
> 			continue
> 		}
> ```

If size increased by X GB, run X times. Take a math floor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[edgraph/server.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-djvkHm5DP28uhvPhP:-L-djnbYESy3OcB1y1AB:b-3bi3z0) ([raw file](https://github.com/dgraph-io/dgraph/blob/4a98db573a742e7c023b62a6ba0b6d0b5f180a32/edgraph/server.go#L94)):*
> ```Go
> 		case <-s.vlogTicker.C:
> 			_, currentVlogSize := store.Size()
> 			if currentVlogSize < lastVlogSize+GB {
> ```

skip if lastVlogSize == 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-:-L-djwx5Fx3TAtfTdbHg:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[edgraph/server.go, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-dNw5iJPdSFlQ48FvJ:-L-dkr41y3CvKoUp0l56:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f94855d182d7f40286578c4256b82393fd366d5c/edgraph/server.go#L90)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Have two tickers.
</blockquote></details>

Done.

---

*[edgraph/server.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-dO7cEqfNyecfxGHSh:-L-dkqGnGg1medm97WDS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f94855d182d7f40286578c4256b82393fd366d5c/edgraph/server.go#L97)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If size increased by X GB, run X times. Take a math floor.
</blockquote></details>

Done.

---

*[edgraph/server.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-djvkHm5DP28uhvPhP:-L-dklJJZ3UbolJK6qED:bgvw153) ([raw file](https://github.com/dgraph-io/dgraph/blob/4a98db573a742e7c023b62a6ba0b6d0b5f180a32/edgraph/server.go#L94)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

skip if lastVlogSize == 0
</blockquote></details>

Instead of this, I make sure that badger calculates size on boot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879)*

**Comment by peterstace** [comment]
Review status: 0 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[edgraph/server.go, line 88 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-eX-YnY-cT3HZPTcUm:-L-eX-YnY-cT3HZPTcUn:b-aq0o5h) ([raw file](https://github.com/dgraph-io/dgraph/blob/c5b05f61f88cb5c5ea7de4eab36e4b60d3c2f29a/edgraph/server.go#L88)):*
> ```Go
> 	// Get initial size on start.
> 	_, lastVlogSize := store.Size()
> 	const GB = int64(1 << 30)
> ```

What's the logic behind using 1GB? Even with this algorithm, is it still possible for the GC to be inadequate? (i.e. does this solve the problem, or just make it occur less frequently and with less severity?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[edgraph/server.go, line 88 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-eX-YnY-cT3HZPTcUm:-L-j2zVNoCBw9Mm2R4_m:bd4pmta) ([raw file](https://github.com/dgraph-io/dgraph/blob/c5b05f61f88cb5c5ea7de4eab36e4b60d3c2f29a/edgraph/server.go#L88)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

1 GB is the minimum because Vlog file size is 1GB, so we can be sure that if size increased by that then there is a possibility of doing GC.
Also if say diff is 4.5GB in the interval (1 minute), then we run the GC 4 times.
</blockquote></details>

To address Peter's comment, there's also a time based ticker, which would run GC irrespective; so this system doesn't need to be perfect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-:-L-j3g0_eaUvsc4n2j_j:bnfp4nl)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[edgraph/server.go, line 88 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879#-L-eX-YnY-cT3HZPTcUm:-L-j6-Rs7sHcMSXmWYdK:bd7ydl3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c5b05f61f88cb5c5ea7de4eab36e4b60d3c2f29a/edgraph/server.go#L88)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

To address Peter's comment, there's also a time based ticker, which would run GC irrespective; so this system doesn't need to be perfect.
</blockquote></details>

Yeah, discussed with with Pawan and Jan yesterday, since badger always attempts to GC the vlog with best ratio, this algorithm will work pretty well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1879)*

**Comment by pawanrawal** [comment]
In master as of 27c3ddb6abdb81fc6add6edb28a2a19ef25f1d9c.

**Pull request closed without merging**
