### PR TITLE
Fix errors reported by goreport. Add goreport to README

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/736)

### CODE REVIEW

**Comment by ashwin95r** [comment]
This is cool! :lgtm: 

---

Review status: 0 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/736#-:-Kfso8plPUL7V9jX1VnH:b-kvfgp9)*

**Comment by ashwin95r** [comment]
Review status: 0 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/mutation.go, line 89 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/736#-KfsoKitI6bhFSmB00XF:-KfsoKitI6bhFSmB00XG:bu24g34) ([raw file](https://github.com/dgraph-io/dgraph/blob/372971cbc53c69976e0b183cc5dc901017514cb1/worker/mutation.go#L89)):*
> ```Go
> 	} else if schemaType.IsScalar() && !storageType.IsScalar() {
> 		return x.Errorf("Input for predicate %s of type scalar is uid", edge.Attr)
> 	} else {
> ```

I think this was kept on purpose. So, should we keep it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/736)*

**Comment by manishrjain** [comment]
Agree with @ashwin95r . Super cool! :lgtm_strong: 

---

Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/736#-:-KfuFKqNa07nYVqZjTad:bnuscnw)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/mutation.go, line 89 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/736#-KfsoKitI6bhFSmB00XF:-KfuINsDkcIhqAMMpcu-:b2aio6i) ([raw file](https://github.com/dgraph-io/dgraph/blob/372971cbc53c69976e0b183cc5dc901017514cb1/worker/mutation.go#L89)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I think this was kept on purpose. So, should we keep it?
</blockquote></details>

Ok, brought it back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/736)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
