### PR TITLE
Use `$GOPATH` in installation instructions

### PR DESCRIPTION
**Pull request by avinassh**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1927)

### CODE REVIEW

**Comment by peterstace** [comment]
Thanks!

**Comment by avinassh** [comment]
Awesome! 😄 

Where do development and contribution related discussions happen? I would like to get more involved with the project. I saw python client is not maintained, so I wanted to make an attempt to fix it.

**Comment by peterstace** [comment]
Primarily Slack (dgraph.slack.com), but we also have a discuss as well. https://discuss.dgraph.io/ If you want to help out with the Python client, that would be great!

**Comment by avinassh** [comment]
I signed up on both and checked, didn't see much activity around development discussions, hence I asked 😄 

Also, we forgot one more step in the instructions, generating dgraph binary by doing `go install`

**Comment by avinassh** [comment]
Okay, sent another PR - https://github.com/dgraph-io/dgraph/pull/1930

**Pull request merged**
