### PR TITLE
fix(restore): skip the depreciated predicates and types in restore

### PR DESCRIPTION
**Pull request by NamanJain8**
Some of the internal predicates have been removed in https://github.com/dgraph-io/dgraph/pull/7431 and https://github.com/dgraph-io/dgraph/pull/7451. 
When restoring from a backup taken on a version older than 21.03, we should skip restoring them. 
Else they will lie around with no use and show up through `/state` endpoint. 
Also, its export will fail in data loading(bulk/live load).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7473)

### CODE REVIEW

**Review by NamanJain8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7473)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @manishrjain and @vvbalaji-dgraph)

___
*[worker/restore.go, line 182 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7473#-MUEHjmT3MupaA06kc1O:-MUEHjmT3MupaA06kc1P:b-j9hm37) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0d51a8369bb2632572c52b2a40c3095ddab34f0/worker/restore.go#L182)):*
> ```Go
> 
> 			if in.isOld {
> 				// Skip restoring the data for the depreciated predicates from the backup taken from
> ```

Maybe pass the version instead. Checks like `in.Version < 2103` will make more sense and will be self-explanatory.

**Review by NamanJain8 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7473)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @manishrjain and @vvbalaji-dgraph)

___
*[worker/restore.go, line 182 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7473#-MUEHjmT3MupaA06kc1O:-MUHeWbY2TXc98buHfng:b3osmuj) ([raw file](https://github.com/dgraph-io/dgraph/blob/b0d51a8369bb2632572c52b2a40c3095ddab34f0/worker/restore.go#L182)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Maybe pass the version instead. Checks like `in.Version < 2103` will make more sense and will be self-explanatory.
</blockquote></details>

Or instead, pass a flag `--ignore-preds` a list of predicates to be ignored. That flag/parameter has to be added in graphql API as well then.

**Review by abhimanyusinghgaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7473)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @manishrjain, @NamanJain8, and @vvbalaji-dgraph)

___
*[worker/restore.go, line 104 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7473#-MUHuNGZ6HyTLRjk4ELe:-MUHuNGZ6HyTLRjk4ELf:b-ds2h4s) ([raw file](https://github.com/dgraph-io/dgraph/blob/99a1711e219599f2f3e67847d738d9a17c1f4040/worker/restore.go#L104)):*
> ```
> "dgraph.cors":
> ```
I have doubts about not restoring this now.

In a previous discussion with @aman-bansal, the strategy he mentioned for restoring data for Slash was dependent on this predicate being restored. It was after the restore it would be migrated to the GraphQL schema. So, I think this would be required to be restored. @aman-bansal can confirm this.
___
*[worker/restore.go, line 108 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7473#-MUHrdga5MMW5AzmOWKt:-MUHrdga5MMW5AzmOWKu:b-5wfqhv) ([raw file](https://github.com/dgraph-io/dgraph/blob/99a1711e219599f2f3e67847d738d9a17c1f4040/worker/restore.go#L108)):*
> ```
> "dgraph.type.cors":
> ```
this is a type, not a predicate.

If we also want to skip the types, then these are the two:
```
dgraph.type.cors
dgraph.graphql.history
```

**Review by aman-bansal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7473)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @manishrjain, @NamanJain8, and @vvbalaji-dgraph)

___
*[worker/restore.go, line 104 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7473#-MUHuNGZ6HyTLRjk4ELe:-MUICDxL3o0bD7tO4dWb:b8ea819) ([raw file](https://github.com/dgraph-io/dgraph/blob/99a1711e219599f2f3e67847d738d9a17c1f4040/worker/restore.go#L104)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "dgraph.cors":
> ```
I have doubts about not restoring this now.

In a previous discussion with @aman-bansal, the strategy he mentioned for restoring data for Slash was dependent on this predicate being restored. It was after the restore it would be migrated to the GraphQL schema. So, I think this would be required to be restored. @aman-bansal can confirm this.
</blockquote></details>

oh yes. This is also another problem. @namanjain8 we have to think this though.

**Comment by NamanJain8** [comment]
This is not needed. The issue was resolved in https://github.com/dgraph-io/dgraph/pull/7486.

**Pull request closed without merging**
