### PR TITLE
Improve use of WriteIterator for sorting

### PR DESCRIPTION
**Pull request by gacharya255**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/634)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/634)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-:-KdhRl161dg8Mj5M-sLu:bnfp4nl)*

**Comment by ashishnegi** [comment]
:lgtm: some questions and comments.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[algo/uidlist.go, line 54 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-Kdxt2oRoGozqlzardKO:-Kdxt2oSEViHEwMSxK2Y:b-27lbi) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dadb5a6bc802d92ae99e5aca5164e88e13bfec4/algo/uidlist.go#L54)):*
> ```Go
> func NewWriteIterator(l *task.List) WriteIterator {
> 	var cur *task.Block
> ```

so, the default case will handle `append` case ?

---

*[algo/uidlist_test.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-KdxtFd5689PxS2BNVZi:-KdxtFd5689PxS2BNVZj:b-7p5z8g) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f79b97597ae5f1377944f8b49b01981187b6a18/algo/uidlist_test.go#L286)):*
> ```Go
> }
> 
> func TestWriteAppend1(t *testing.T) {
> ```

Have we removed support for appending ?

---

*[worker/sort.go, line 198 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-Kdxtlq3ttWQvmsr_nKr:-Kdxtlq4x6q3VIw8oAhB:b-6a1ybx) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dadb5a6bc802d92ae99e5aca5164e88e13bfec4/worker/sort.go#L198)):*
> ```Go
> 		il := &out[i]
> 		// Caution: Use ListLen from WriteIterator. Potential cleanup: get rid of indices in
> 		// WriteIterator. Let the slices in the list itself do the counting.
> ```

i think the reason why we will not be able to do `potential cleanup` is :
we preallocate the slices and fill with 0s.. so as to avoid doing a call `append` and just use `arr[idx] = ..`.
@ashwin95r can confirm this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-:-Kdxw2FYKW9ltvIeRN9c:bcjclpd)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[algo/uidlist.go, line 54 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-Kdxt2oRoGozqlzardKO:-Kdxx-nB-10PPYZQLXLa:b-udzm5z) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dadb5a6bc802d92ae99e5aca5164e88e13bfec4/algo/uidlist.go#L54)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

so, the default case will handle `append` case ?
</blockquote></details>

Default would be starting from the start of the list.

---

*[algo/uidlist_test.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-KdxtFd5689PxS2BNVZi:-Kdxx9S6BYIA5v_vjEX8:bb77ufg) ([raw file](https://github.com/dgraph-io/dgraph/blob/0f79b97597ae5f1377944f8b49b01981187b6a18/algo/uidlist_test.go#L286)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Have we removed support for appending ?
</blockquote></details>

Yes.

---

*[worker/sort.go, line 198 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-Kdxtlq3ttWQvmsr_nKr:-KdxxIcrQG65aOmLow3v:b-ht0ukm) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dadb5a6bc802d92ae99e5aca5164e88e13bfec4/worker/sort.go#L198)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

i think the reason why we will not be able to do `potential cleanup` is :
we preallocate the slices and fill with 0s.. so as to avoid doing a call `append` and just use `arr[idx] = ..`.
@ashwin95r can confirm this.
</blockquote></details>

That's right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/634)*

**Comment by gacharya255** [comment]
Thanks. I will submit.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[algo/uidlist.go, line 54 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-Kdxt2oRoGozqlzardKO:-Kdzv-jVsla7F1zGvOmy:b5rxisc) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dadb5a6bc802d92ae99e5aca5164e88e13bfec4/algo/uidlist.go#L54)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Default would be starting from the start of the list.
</blockquote></details>

It might be more appropriate to call this a Builder rather than an iterator. And with that, we can also get rid of bidx, lidx I think and just use len of arrays. But yeah, I am not proposing we do that yet.

---

*[worker/sort.go, line 198 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-Kdxtlq3ttWQvmsr_nKr:-KdzvKkAOdJESxYtIEbq:bvzfxh6) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dadb5a6bc802d92ae99e5aca5164e88e13bfec4/worker/sort.go#L198)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

That's right.
</blockquote></details>

You can allocate an array with a large capacity and zero size. I think that is the right way to do it. I think it is good to maintain as few vars as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/634#-:-KdzvXCATbFprFEk4Qct:b74k4v3)*

**Pull request closed without merging**
