### PR TITLE
Unit test for uidassigner

### PR DESCRIPTION
**Pull request by ashwin95r**
[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/17)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[server/uidassigner/main_test.go, line 19 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fMZz222xZbycbyjum:-K9fMZz222xZbycbyjun:-1214696911) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L19)):*
Remove extra vertical spaces, here and ...

---

*[server/uidassigner/main_test.go, line 21 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fMc0Z63LyXae_Fdak:-K9fMc0Z63LyXae_Fdal:-466193319) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L21)):*
here.

---

*[server/uidassigner/main_test.go, line 22 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fN8RiL2sgDBXiLCtq:-K9fN8RjCUP3gahnbWGP:1282679566) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L22)):*
`mod := math.MaxUint64 / numInstances` No need to do var and type declaration.

---

*[server/uidassigner/main_test.go, line 23 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fNG8W53L5wsiJrrSr:-K9fNG8W53L5wsiJrrSs:-1215721764) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L23)):*
Same here as above `minIdx0 := 0 * mod`

---

*[server/uidassigner/main_test.go, line 24 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fNJCEP-c3HGEBqJ1x:-K9fNJCEP-c3HGEBqJ1y:-2099675312) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L24)):*
and here.

---

*[server/uidassigner/main_test.go, line 27 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fMdep-ulo7SFRlieC:-K9fMdep-ulo7SFRlieD:-2099675312) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L27)):*
and here.

---

*[server/uidassigner/main_test.go, line 33 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fMfmDuEdBomYo5sfk:-K9fMfmDuEdBomYo5sfl:-1030605740) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L33)):*
Add a vertical space after this, to reflect that you're done with the dir creation.

---

*[server/uidassigner/main_test.go, line 39 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fMqWFVq0SJxNXp726:-K9fMqWFVq0SJxNXp727:1455000643) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L39)):*
Unnecessary vertical space.

---

*[server/uidassigner/main_test.go, line 43 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fMuRvA794z5oN6OT6:-K9fMuRvA794z5oN6OT7:1455000643) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L43)):*
Unnecessary vertical space.

---

*[server/uidassigner/main_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fNNVO3QifVz2MG_na:-K9fNNVO3QifVz2MG_nb:258621879) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L50)):*
fmt.Println has no usage in testing.  Remove it, or use t.Log.

---

*[server/uidassigner/main_test.go, line 51 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fMvpoYsYjb8z7tLE2:-K9fMvpoYsYjb8z7tLE3:631648381) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L51)):*
Add a space after this so the `else` is more clear.

---

*[server/uidassigner/main_test.go, line 57 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9fNVf2sSpGkBBRO4FI:-K9fNVf2sSpGkBBRO4FJ:-145472728) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea17e2368a16659353b7ab5453a9e8eba6df625b/server/uidassigner/main_test.go#L57)):*
No need for Println

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/17)*

**Comment by manishrjain** [comment]
Merge after addressing the last 2 comments. Also, please acknowledge all the comments that you fix; so it's easier to figure out whether you addressed them or not.

Otherwise, :lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[server/uidassigner/main_test.go, line 46 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9ihjJW0pPgq832n5Sh:-K9ihjJXo0w4VwTVKZbX:-804251117) ([raw file](https://github.com/dgraph-io/dgraph/blob/7635b2a34121b0d493b9185016f43c8ab97db537/server/uidassigner/main_test.go#L46)):*
Seems unnecessary after the last log. Merge it with above.

---

*[server/uidassigner/main_test.go, line 54 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9ihotC9xM082PeuqyM:-K9ihotC9xM082PeuqyN:-671963360) ([raw file](https://github.com/dgraph-io/dgraph/blob/7635b2a34121b0d493b9185016f43c8ab97db537/server/uidassigner/main_test.go#L54)):*
Unnecessary. Merge with above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-:-K9ihupsnn7FfdU5IyJt:1172615857)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/17)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[server/uidassigner/main_test.go, line 54 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/17#-K9ihotC9xM082PeuqyM:-K9k4E_BsgkMZgFL3DUi:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/7635b2a34121b0d493b9185016f43c8ab97db537/server/uidassigner/main_test.go#L54)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/17)*

**Pull request merged**
