### PR TITLE
Make proposal id a concatenation of node_raft_id and randUint64

### PR DESCRIPTION
**Pull request by pawanrawal**
This should solve #2214

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2309)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[worker/draft.go, line 64 at r1](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2309#-L9IYaO54EDPxJzuEwB4:-L9IYaO54EDPxJzuEwB5:bj9uuqy) ([raw file](https://github.com/dgraph-io/dgraph/blob/3cb1a354d837cd4b3a301d5760ba89777ff39353/worker/draft.go#L64)):*
> ```Go
> }
> 
> func pkey(id uint64) string {
> ```

uniqueKey()

---

*[worker/draft.go, line 65 at r1](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2309#-L9IYdP24xO-nesDCO-q:-L9IYdP24xO-nesDCO-r:blictkp) ([raw file](https://github.com/dgraph-io/dgraph/blob/3cb1a354d837cd4b3a301d5760ba89777ff39353/worker/draft.go#L65)):*
> ```Go
> 
> func pkey(id uint64) string {
> 	b := new(bytes.Buffer)
> ```

b := make([]byte, 16)
copy(b[0:8], raftidbuffer)
rand.ReadBytes(b[8:16]) // this could be more.

---

*[worker/draft.go, line 261 at r1](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2309#-L9IZMFG7sY3dyI1tz_p:-L9IZMFG7sY3dyI1tz_q:b-4b9yad) ([raw file](https://github.com/dgraph-io/dgraph/blob/3cb1a354d837cd4b3a301d5760ba89777ff39353/worker/draft.go#L261)):*
> ```Go
> 		cnt: 1,
> 	}
> 	for {
> ```

Remove the for.

---

*[worker/draft.go, line 263 at r1](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2309#-L9IZOfy1LANylFVtnJH:-L9IZOfz2fYz_HJpSWgy:b-5tt8ds) ([raw file](https://github.com/dgraph-io/dgraph/blob/3cb1a354d837cd4b3a301d5760ba89777ff39353/worker/draft.go#L263)):*
> ```Go
> 	for {
> 		key := pkey(n.rand.Uint64())
> 		if n.props.Store(key, pctx) {
> ```

Assert here, with proper logs.

---

*[worker/draft.go, line 414 at r1](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2309#-L9IZnj57g700CqmokK_:-L9IZnj57g700CqmokKa:b-80bnu5) ([raw file](https://github.com/dgraph-io/dgraph/blob/3cb1a354d837cd4b3a301d5760ba89777ff39353/worker/draft.go#L414)):*
> ```Go
> 			}
> 			// We assert here to make sure that we do add the proposal to the map.
> 			x.AssertTrue(n.props.Store(proposal.Id, pctx))
> ```

Truef

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2309)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2309#-:-L9JOSj--xNZjp4M3AQd:bnfp4nl)*

**Comment by pawanrawal** [comment]
Since this change wouldn't be compatible with pending entries in WAL, and users would need to do a clean shutdown before upgrading, I will wait on merging it.

**Comment by pawanrawal** [comment]
In master as of 9951c98f7c1880743994820263b08a73f943c8e7.

**Pull request closed without merging**
