### PR TITLE
Refactor/worker

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1255)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 298 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1255#-KpwBXlwjs-jRzSqPFvV:-KpwBXlwjs-jRzSqPFvW:b8oi2nf) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fc3b176f44ded57adea58ce354bfddfac03d5cb/worker/task.go#L298)):*
> ```Go
> 	for i := 0; i < srcFn.n; i++ {
> 		if lastDecr != nil {
> 			lastDecr()
> ```

Doing it this way as it avoids calling decr() at every continue in the loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1255)*

**Comment by manishrjain** [comment]
:lgtm: Thanks for the refactor!

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1255#-:-KpwaoSVhd4EYO-108Jr:badwbo1)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[worker/task.go, line 303 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1255#-KpxJYwCPpVOOgF6gKI4:-KpxJYwCPpVOOgF6gKI5:b-lu4egx) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5fe8beba5e736c044f45c5ba290095e49fb651e/worker/task.go#L303)):*
> ```Go
> 			lastDecr = nil
> 			continue
> 		}
> ```

just wondering why do we continue the loop on context timeout ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1255#-:-KpxJTaMYq_cYJ5yhrn1:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/task.go, line 303 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1255#-KpxJYwCPpVOOgF6gKI4:-KpxNDu2sMsQStzxYubn:b-6gh79k) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5fe8beba5e736c044f45c5ba290095e49fb651e/worker/task.go#L303)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

just wondering why do we continue the loop on context timeout ?
</blockquote></details>

Just wanted consistency about not returning inside the loop. Once we set the `lerr` we'd anyway not fetch/process further PLs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1255)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
