### PR TITLE
Improve/schema coercion

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/285)

### CODE REVIEW

**Comment by jchiu0** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 338 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/285#-KUL5-r5S1av9eLtiiOi:-KUL5-r5S1av9eLtiiOj:b-a73l3f) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea36dbb83384dc040594074c78d2e6d5ed7ec568/query/query.go#L338)):*
> ```Go
> 			}
> 		} else if globalType != nil {
> 			// type assertion for optional scalars which aren't part of objects.
> ```

Looks very close to the case above. Wonder if you can merge the two but just use val/lval.

var lval ...
if Case1 {
  lval = schemaType.Convert(val)
} else {
  lval = gt.Convert(val)
}

if sg.params.Alias.......

---

*[query/query.go, line 527 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/285#-KUL599W0CB2rlOifg9t:-KUL599XHt4oxZEas4bN:b9fgbl1) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea36dbb83384dc040594074c78d2e6d5ed7ec568/query/query.go#L527)):*
> ```Go
> 						return x.Errorf("Leaf predicate:'%v' must be a scalar.", pc.Attr)
> 					}
> 					gt := globalType.(types.Scalar)
> ```

Looks very close to the case above. Wonder if you can merge the two, like

sv := v
var p property
if globalType!=nil {
  sv = gt.Convert(v)...
}
p := createProperty(pc.Attr, sv)
properties = append(properties, p)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/285)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 338 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/285#-KUL5-r5S1av9eLtiiOi:-KULFZTnxFmjYj_3IWg3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea36dbb83384dc040594074c78d2e6d5ed7ec568/query/query.go#L338)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Looks very close to the case above. Wonder if you can merge the two but just use val/lval.
> 
> var lval ...
> if Case1 {
>   lval = schemaType.Convert(val)
> } else {
>   lval = gt.Convert(val)
> }
> 
> if sg.params.Alias.......
</details>
Done.

---

*[query/query.go, line 527 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/285#-KUL599W0CB2rlOifg9t:-KULHRy00jaSiPjKsQtR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea36dbb83384dc040594074c78d2e6d5ed7ec568/query/query.go#L527)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Looks very close to the case above. Wonder if you can merge the two, like
> 
> sv := v
> var p property
> if globalType!=nil {
>   sv = gt.Convert(v)...
> }
> p := createProperty(pc.Attr, sv)
> properties = append(properties, p)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/285)*

**Comment by jchiu0** [comment]
:lgtm: (You might want to update your test to use testify like the rest of the code that is just checked in.. Thanks!)

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/285#-:-KULSL0sE5ZYXOucloag:b-qu5ncx)*

**Comment by ashwin95r** [comment]
Merged to master with commit 88f085c07394f49bcb1a9279a789fa7e85fafe29.

**Pull request closed without merging**
