### PR TITLE
Add support on '@filter(gt(count(director.film), 0))'

### PR DESCRIPTION
**Pull request by squalfof**
Now we support query like,
```
{
  director(func:allof(name.en, "Steven Spielberg")) @filter(gt(count(director.film), 0)) {
    name.en
    director.film {
    	name.en
  }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/596)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 2855 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd5UwyMl7B_V6dtVzFS:-Kd5UwyMl7B_V6dtVzFT:bszwcfe) ([raw file](https://github.com/dgraph-io/dgraph/blob/1c6d582890594072975873fc2583e63bcc0fb007/query/query_test.go#L2855)):*
> ```Go
> func TestGeneratorRootFilterOnCountError1(t *testing.T) {
>         populateGraph(t)
> 	// only cmp(count(attr), int) is valid, 'max'/'min'/'sum' not supported
> ```

Indentation issues. Use gofmt. This should be an integral part of your code editor.

Also for GraphQL queries, use spaces instead of tabs.

---

*[worker/compare.go, line 22 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd5Vr5-NjKGrSQYDnuG:-Kd5Vr5-NjKGrSQYDnuH:b-36ez5j) ([raw file](https://github.com/dgraph-io/dgraph/blob/1c6d582890594072975873fc2583e63bcc0fb007/worker/compare.go#L22)):*
> ```Go
> 		return lv == rv, nil
> 	}
> 	return true, x.Errorf("Invalid comparator")
> ```

Shouldn't the compare function's validity be checked earlier? This is something we can probably ensure just after parsing, no?

---

*[worker/task.go, line 244 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd5ViFBGgIq3fi9E95a:-Kd5ViFCEzkvfn3ZpXSn:b-ocfxqw) ([raw file](https://github.com/dgraph-io/dgraph/blob/1c6d582890594072975873fc2583e63bcc0fb007/worker/task.go#L244)):*
> ```Go
> 		}
> 		if fnType == AggregatorFn ||
> 			fnType == CompareScalarFn ||
> ```

These three can fit in one line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-:-Kd5WFv-u7GT2AZC8qvh:bnfp4nl)*

**Comment by squalfof** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 2855 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd5UwyMl7B_V6dtVzFS:-Kd8dE9NwCAzCVortP6P:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1c6d582890594072975873fc2583e63bcc0fb007/query/query_test.go#L2855)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Indentation issues. Use gofmt. This should be an integral part of your code editor.

Also for GraphQL queries, use spaces instead of tabs.
</blockquote></details>

Done.

---

*[worker/compare.go, line 22 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd5Vr5-NjKGrSQYDnuG:-Kd8aRw8psLW8Km9iN7a:b7cq85z) ([raw file](https://github.com/dgraph-io/dgraph/blob/1c6d582890594072975873fc2583e63bcc0fb007/worker/compare.go#L22)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shouldn't the compare function's validity be checked earlier? This is something we can probably ensure just after parsing, no?
</blockquote></details>

Yes, should be checked already.
Done.

---

*[worker/task.go, line 244 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd5ViFBGgIq3fi9E95a:-Kd8YvUY3A2H5BG1c6kk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1c6d582890594072975873fc2583e63bcc0fb007/worker/task.go#L244)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

These three can fit in one line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/596)*

**Comment by ashwin95r** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 996 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd934GG4YNfiKvB247U:-Kd934GH5596ozTlw_xF:b-z2m3dv) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/gql/parser.go#L996)):*
> ```Go
> 					terminated = true
> 					break
> 				} else if itemInFunc.Typ == itemLeftRound {
> ```

This allows count() as second argument as well right? 

---

*[gql/parser_test.go, line 999 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd93DidTeE-TF5Zn335:-Kd93DidTeE-TF5Zn336:b-7ztarg) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/gql/parser_test.go#L999)):*
> ```Go
> 	query := `
> 	query {
> 		me(func:abc(abc)) @filter(gt(count(friends), 10)) {
> ```

Do we allow count as second argument? Please add a test case for that as well.

---

*[query/query_test.go, line 2841 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd93MDsmV53kGGJMhZi:-Kd93MDsmV53kGGJMhZj:b-eemnvm) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/query/query_test.go#L2841)):*
> ```Go
> 	query := `
>                 {
>                         me(func:anyof("name", "Michonne Rick")) @filter(leq(count(friend), 2)) {
> ```

A test case using count and an operator like and/or/not maybe at a non root level.

---

*[worker/compare.go, line 1 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd92Nkm6c5MSoxG_dBx:-Kd92Nkm6c5MSoxG_dBy:bvvm7sz) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/compare.go#L1)):*
> ```Go
> package worker
> ```

Do we need a new file for this? If yes, also add the copyright.

---

*[worker/compare.go, line 7 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd923wJ3chRGjI4xhtI:-Kd923wJ3chRGjI4xhtJ:b3iyjf) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/compare.go#L7)):*
> ```Go
> )
> 
> func Compare(cmp string, lv, rv int64) (bool, error) {
> ```

Can be named `SatisfiesFunction`. We're not using the error, so just return bool?

---

*[worker/task.go, line 195 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd908VZ2e69vc3eL5wD:-Kd908V_YU5bnmzPyQbJ:b6304je) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/task.go#L195)):*
> ```Go
> 		threshold, err = strconv.ParseInt(q.SrcFunc[2], 10, 64)
> 		if err != nil {
> 			return nil, x.Errorf("Compare %v(%v) require digits, but got invalid num",
> ```

Better to use x.Warpf() to append the actual error returned by the strconv package.

---

*[worker/task.go, line 314 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd91tPRvXt3Zf9jpHe8:-Kd91tPRvXt3Zf9jpHe9:b-s4o7u3) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/task.go#L314)):*
> ```Go
> 
> 		if fnType == CompareScalarFn {
> 			cnt := int64(pl.Length(0))
> ```

count?

---

*[worker/task.go, line 316 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd929SaA5uL2wGquJfS:-Kd929SaA5uL2wGquJfT:bb77olb) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/task.go#L316)):*
> ```Go
> 			cnt := int64(pl.Length(0))
> 			ret, _ := Compare(f, cnt, threshold)
> 			if ret {
> ```

If we just return bool
```
if SatisfiesFunction() {
 ...
}
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/596)*

**Comment by squalfof** [comment]
Review status: 2 of 5 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 996 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd934GG4YNfiKvB247U:-Kd93z4k3OVnyaJgTlY6:b-g5v74m) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/gql/parser.go#L996)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This allows count() as second argument as well right? 
</blockquote></details>

Yes, though that's invalid, it will be accepted here.  During processTask() in worker/task.go such error will be spotted.

---

*[gql/parser_test.go, line 999 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd93DidTeE-TF5Zn335:-Kd94TMfTluDEdLrM_tk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/gql/parser_test.go#L999)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Do we allow count as second argument? Please add a test case for that as well.
</blockquote></details>

Done.

---

*[query/query_test.go, line 2841 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd93MDsmV53kGGJMhZi:-Kd9wwmiFeGQXcC-SOx7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/query/query_test.go#L2841)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

A test case using count and an operator like and/or/not maybe at a non root level.
</blockquote></details>

Done.

---

*[worker/compare.go, line 1 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd92Nkm6c5MSoxG_dBx:-Kd98t6OH3NqsusMKiQs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/compare.go#L1)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Do we need a new file for this? If yes, also add the copyright.
</blockquote></details>

Done.

---

*[worker/compare.go, line 7 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd923wJ3chRGjI4xhtI:-Kd95qf3Id_OK3GITzsg:b-51xn0z) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/compare.go#L7)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Can be named `SatisfiesFunction`. We're not using the error, so just return bool?
</blockquote></details>

Cool, just return bool.

 **Satisfies** make sense since first argument is a function.  However this name is a bit of generic.
After all it's used for compare... how about **EvalCompare()** ?

---

*[worker/task.go, line 195 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd908VZ2e69vc3eL5wD:-Kd9yc3VCKBmvDeNiFgq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/task.go#L195)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Better to use x.Warpf() to append the actual error returned by the strconv package.
</blockquote></details>

Done.

---

*[worker/task.go, line 314 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd91tPRvXt3Zf9jpHe8:-Kd95_WmZ1AXjgUk4x0X:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/task.go#L314)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

count?
</blockquote></details>

Done.

---

*[worker/task.go, line 316 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd929SaA5uL2wGquJfS:-Kd9IlgaWakDrmyZYAEx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/task.go#L316)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

If we just return bool
```
if SatisfiesFunction() {
 ...
}
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/596)*
<!-- Sent from Reviewable.io -->

**Comment by ashwin95r** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 996 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd934GG4YNfiKvB247U:-KdA5hAipgv8Rc95I2YI:bvgcav6) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/gql/parser.go#L996)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Yes, though that's invalid, it will be accepted here.  During processTask() in worker/task.go such error will be spotted.
</blockquote></details>

I think it's better to catch invalid syntax earlier. You could maintain a variable which tracks this.

---

*[worker/compare.go, line 7 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-Kd923wJ3chRGjI4xhtI:-KdA5TPFbikfliDULFiI:blpja9k) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b19f3a54e1f9854d9bcf35b922af6925675768e/worker/compare.go#L7)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Cool, just return bool.

 **Satisfies** make sense since first argument is a function.  However this name is a bit of generic.
After all it's used for compare... how about **EvalCompare()** ?


</blockquote></details>

Umm okay, whatever you feel is the best.

---

*[worker/compare.go, line 2 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-KdA5I3_ONgW0dCpvZtW:-KdA5I3_ONgW0dCpvZtX:bb6ht2h) ([raw file](https://github.com/dgraph-io/dgraph/blob/11073711e53f906f1ca2cf03a44fa1ac31fd303d/worker/compare.go#L2)):*
> ```Go
> /*
>  * Copyright 2016 DGraph Labs, Inc.
> ```

2017

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/596)*

**Comment by ashwin95r** [comment]
:lgtm: Just address the one comment.

---

Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/596#-:-KdA7Rx9LiGrWhUczGts:b-5b8nkn)*

**Pull request closed without merging**
