### PR TITLE
Feature/schema-system

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/234)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 14 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 162 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZeEClEUOCehL45pJQ:-KSZeEClEUOCehL45pJR:b-vj4l3z) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L162)):*
> ```Go
> 	// Get results from all children first.
> 	cResult := make(map[uint64]interface{})
> ```

Add a comment here about what constitutes an ignoreUid.

---

*[query/query.go, line 169 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZfXnHmLzdmc6qhjTB:-KSZfXnHmLzdmc6qhjTC:bxuqg5z) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L169)):*
> ```Go
> 			return result, err
> 		}
> ```

Add a comment here explaining this flag, and the need for it. And the scenario where this is applicable.

---

*[query/query.go, line 181 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZhoJJlaCLaq72VMeI:-KSZhoJJlaCLaq72VMeJ:b-1m59ua) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L181)):*
> ```Go
> 			if _, ok := v.(map[string]interface{})["INVALID"]; ok {
> 				if condFlag {
> 					ignoreUids[k] = true
> ```

Have a test case, we have one required field, and one optional field. And test for both present, either present, and none present.

---

*[query/query.go, line 287 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZhya6lYrLoa6ZJcwe:-KSZhya6lYrLoa6ZJcwf:b-dl68xx) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L287)):*
> ```Go
> 			// and the index of the results can remain in sync.
> 			if sg.Params.AttrType != nil && sg.Params.AttrType.IsScalar() {
> 				m["INVALID"] = true
> ```

Call it `_inv_`

---

*[query/query.go, line 318 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZi1FjhvweW0vnKgWh:-KSZi1FjhvweW0vnKgWi:b-ewb02) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L318)):*
> ```Go
> 			if err != nil {
> 				// Mark node as invalid and ignore in results.
> 				m["INVALID"] = true
> ```

`_inv_`

---

*[query/query.go, line 523 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZiOYFLzf-HEE21yVl:-KSZiOYFLzf-HEE21yVm:b-65pvye) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L523)):*
> ```Go
> 	// So, we work on the children, and then recurse for grand children.
> 
> 	scalarMap := make(map[string]bool)
> ```

Instead of using a map, just loop over children.

---

*[query/query.go, line 788 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZjDyYYmI9D9EXnMtm:-KSZjDyZo8OnSxghCLQZ:bx3641y) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L788)):*
> ```Go
> 		}
> 	}
> ```

if leftToProcess is of len zero, then return.

---

*[query/query.go, line 789 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZm15WBBdfHzEYTPMx:-KSZm15WBBdfHzEYTPMy:b-wl8xwb) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L789)):*
> ```Go
> 	}
> 
> 	invalidUids := make(map[uint64]bool)
> ```

See if you can move this out into a separate func.

---

*[query/query.go, line 796 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZjzP5aHXwnbWHnNtU:-KSZjzP5aHXwnbWHnNtV:b-8wnild) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L796)):*
> ```Go
> 		}
> 		var tv task.Value
> 		rNode := x.NewTaskResult(node.Result)
> ```

Add a comment that rNode ValuesLength() == len(sorted).

---

*[query/query.go, line 797 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZk4kahGBw535BTdsH:-KSZk4kahGBw535BTdsI:bsmdald) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L797)):*
> ```Go
> 		var tv task.Value
> 		rNode := x.NewTaskResult(node.Result)
> 		for i := 0; i < rNode.ValuesLength(); i++ {
> ```

Inside the loop, `uid := sorted[i]`

---

*[query/query.go, line 799 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZlSj6NwYXONeF_6mS:-KSZlSj6NwYXONeF_6mT:bixiaku) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L799)):*
> ```Go
> 		for i := 0; i < rNode.ValuesLength(); i++ {
> 			if ok := rNode.Values(&tv, i); !ok {
> 				invalidUids[sorted[i]] = true
> ```

Again, check for required fields vs optional fields. A non-parseable or absent optional field shouldn't make this entity invalid.

---

*[query/query.go, line 802 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZkJ5TplAMD6u8QWiP:-KSZkJ5TplAMD6u8QWiQ:b8kk1ca) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L802)):*
> ```Go
> 			}
> 			val := tv.ValBytes()
> 			if bytes.Equal(val, nil) {
> ```

Check if this is a valid way to ensure nil for ValBytes. I suspect we used to set this to a single byte or something.

---

*[query/query.go, line 822 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZlhMaPMg0O6p8qecw:-KSZlhMaPMg0O6p8qecx:b-mfr4dv) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L822)):*
> ```Go
> 	}
> 
> 	sortedNew := make([]uint64, 0, len(sorted))
> ```

You can just reuse the sorted, instead of a new slice. See filter tricks for slices.

---

*[schema/gru_schema, line 1 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZmC0KD9mfvt8UbChG:-KSZmC0KD9mfvt8UbChH:b-wehxga) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/schema/gru_schema#L1)):*
> ```
> # Dgraph schema file for GRU quiz
> ```

Remove it from here.

---

*[schema/parser.go, line 15 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZnAriDh0ME_DGgZ6d:-KSZnArjDYw4Nlz7i_VW:b-5x3wmw) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/schema/parser.go#L15)):*
> ```Go
> )
> 
> func Parse(schema string) error {
> ```

Use a lexer for this.

---

*[schema/schema.go, line 61 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZo-Mwn_uYIB00MeYF:-KSZo-Mwn_uYIB00MeYG:bxyqx60) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/schema/schema.go#L61)):*
> ```Go
> }
> 
> func GetScalar(typ string) (Type, bool) {
> ```

If this is internal to schema, then make it private.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by ashwin95r** [comment]
Review status: 0 of 14 files reviewed at latest revision, 26 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 287 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZhya6lYrLoa6ZJcwe:-KSZzKF54Xs9_wY-0WU6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L287)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Call it `_inv_`
</details>
Done.

---

*[query/query.go, line 318 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZi1FjhvweW0vnKgWh:-KSZzLnn2CwxsXbCGysh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L318)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> `_inv_`
</details>
Done.

---

*[query/query.go, line 523 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZiOYFLzf-HEE21yVl:-KS_Ed5qAl5WALZPCQgV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L523)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Instead of using a map, just loop over children.
</details>
Done.

---

*[query/query.go, line 788 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZjDyYYmI9D9EXnMtm:-KS_EvcYGBinDc9TF63G:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L788)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> if leftToProcess is of len zero, then return.
</details>
Done.

---

*[query/query.go, line 797 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZk4kahGBw535BTdsH:-KS_FDCeLqkFDsjcHfCC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L797)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Inside the loop, `uid := sorted[i]`
</details>
Done.

---

*[query/query.go, line 822 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZlhMaPMg0O6p8qecw:-KS_GJNDOMqaA7DlHn-a:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L822)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can just reuse the sorted, instead of a new slice. See filter tricks for slices.
</details>
Done.

---

*[schema/schema.go, line 61 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIG-r1-61:-KSZz2lY-twrZ_vSyfln:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/schema.go#L61)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function GetScalar should have comment or be unexported
</details>
Done.

---

*[schema/schema.go, line 61 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZo-Mwn_uYIB00MeYF:-KSZz3cF2MJYJvigV3Wq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/schema/schema.go#L61)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> If this is internal to schema, then make it private.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by ashwin95r** [comment]
Review status: 0 of 14 files reviewed at latest revision, 26 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 162 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZeEClEUOCehL45pJQ:-KS_O3LzM2wxjAa2h1rb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L162)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a comment here about what constitutes an ignoreUid.
</details>
Done.

---

*[query/query.go, line 796 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZjzP5aHXwnbWHnNtU:-KS_NXOj8hv-xXdIXrcD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L796)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a comment that rNode ValuesLength() == len(sorted).
</details>
Done.

---

*[query/query.go, line 532 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDI7-r3-532:-KS_MqgPlC8W9TC2IF4-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/563254b93ef9d512bd6ce58dbbc62645067adb20/query/query.go#L532)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> can probably use "var scalars []string" instead
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by ashwin95r** [comment]
Review status: 0 of 14 files reviewed at latest revision, 26 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 802 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZkJ5TplAMD6u8QWiP:-KSaHbUs6xjwy7qLdCfV:btmmidx) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L802)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Check if this is a valid way to ensure nil for ValBytes. I suspect we used to set this to a single byte or something.
</details>
We declare empty value as `var Nilbyte []byte`. So this would be right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by ashwin95r** [comment]
Review status: 0 of 14 files reviewed at latest revision, 26 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 169 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZfXnHmLzdmc6qhjTB:-KSdnZpLjPXYtvtQ6UFz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L169)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a comment here explaining this flag, and the need for it. And the scenario where this is applicable.
</details>
Done.

---

*[query/query.go, line 789 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZm15WBBdfHzEYTPMx:-KSdnnl07HwiW2YteZjZ:b-hrnkfp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L789)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> See if you can move this out into a separate func.
</details>
I think this is specific to this function and wouldn't be reused at other places. So might be better to have it inline here.

---

*[query/query.go, line 799 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZlSj6NwYXONeF_6mS:-KS_tOgJBDIWt5E_VNno:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/query/query.go#L799)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Again, check for required fields vs optional fields. A non-parseable or absent optional field shouldn't make this entity invalid.
</details>
Done.

---

*[schema/definitions.go, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIA-r1-36:-KSdpDm5mqqm_XRrNLwV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/definitions.go#L36)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported type Object should have comment or be unexported
</details>
Done.

---

*[schema/definitions.go, line 49 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIA-r1-49:-KSdsi52jTK4NCBdF0-P:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/definitions.go#L49)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Scalar.Type should have comment or be unexported
</details>
Done.

---

*[schema/definitions.go, line 54 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIA-r1-54:-KSdsisEsPzAQ_Doh9T6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/definitions.go#L54)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Object.Type should have comment or be unexported
</details>
Done.

---

*[schema/definitions.go, line 62 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIA-r1-62:-KSdtSw1UkKTOHt0Ocas:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/definitions.go#L62)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Object.IsScalar should have comment or be unexported
</details>
Done.

---

*[schema/gru_schema, line 1 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZmC0KD9mfvt8UbChG:-KSdtWpbI773MGZNPBDq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/schema/gru_schema#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove it from here.
</details>
Done.

---

*[schema/parser.go, line 15 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDID-r1-15:-KSdvOpzq6AtmUKk4WPO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/parser.go#L15)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function Parse should have comment or be unexported
</details>
Done.

---

*[schema/schema.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIG-r1-28:-KSdv3EpcVA63LAgOv4o:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/schema.go#L28)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function ScalarList should have comment or be unexported<br>exported func ScalarList returns unexported type []schema.scalar, which can be annoying to use
</details>
Done.

---

*[schema/schema.go, line 42 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIG-r1-42:-KSdv44w7cScJ1qf-i5T:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/schema.go#L42)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function TypeOf should have comment or be unexported
</details>
Done.

---

*[schema/schema.go, line 52 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIG-r1-52:-KSdv4ehK_5TRv0jyzn5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4b83cdc543d8df8a4a25000f7ebfd5305d78191c/schema/schema.go#L52)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function FieldType should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by ashwin95r** [comment]
Review status: 0 of 16 files reviewed at latest revision, 35 unresolved discussions, some commit checks failed.

---

*[schema/definitions.go, line 49 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIA-r5-49:-KSfiQCiFGWJ7YQwsRzv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/19f317c65631407a0e11225f594e35eca484627b/schema/definitions.go#L49)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported method Scalar.IsScalar should be of the form "IsScalar ..."
</details>
Done.

---

*[schema/definitions.go, line 54 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIA-r5-54:-KSfiRHwyohnTzg9JyOT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/19f317c65631407a0e11225f594e35eca484627b/schema/definitions.go#L54)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported method Object.IsScalar should be of the form "IsScalar ..."
</details>
Done.

---

*[schema/parse.go, line 81 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSfEUCEXvSNIVgmVg-3-r6-81:-KSfiSbyAAYCVcHaZVfl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/451ac794bdd6a28f8bb38312f3bb9dfc62de01dd/schema/parse.go#L81)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
</details>
Done.

---

*[schema/parse.go, line 115 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSfEUCEXvSNIVgmVg-3-r6-115:-KSffiqmw6sH_geVT-Wl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/451ac794bdd6a28f8bb38312f3bb9dfc62de01dd/schema/parse.go#L115)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
</details>
Done.

---

*[schema/parse.go, line 135 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSfEUCEXvSNIVgmVg-3-r6-135:-KSffu1Kdm81n9X2ykOG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/451ac794bdd6a28f8bb38312f3bb9dfc62de01dd/schema/parse.go#L135)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
</details>
Done.

---

*[schema/parse.go, line 164 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSfEUCEXvSNIVgmVg-3-r6-164:-KSffzmw5ZQ9Mdjc4lOh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/451ac794bdd6a28f8bb38312f3bb9dfc62de01dd/schema/parse.go#L164)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
</details>
Done.

---

*[schema/parse.go, line 115 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSfEUCEXvSNIVgmVg-3-r7-115:-KSffos94K0IIbvLjc5X:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c356fdbba1069267f741de8ae168feccc36b4a2/schema/parse.go#L115)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
</details>
Done.

---

*[schema/parser.go, line 15 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSZnAriDh0ME_DGgZ6d:-KSfg4bHzWpeXDiij0fC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a718ee14054215f39bc70b2b9cef32d0e2770ded/schema/parser.go#L15)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Use a lexer for this.
</details>
Done.

---

*[schema/schema.go, line 31 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIG-r5-31:-KSfiHeuk2V6whAxbsnY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/19f317c65631407a0e11225f594e35eca484627b/schema/schema.go#L31)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported func ScalarList returns unexported type []schema.scalar, which can be annoying to use
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by ashwin95r** [comment]
Review status: 0 of 15 files reviewed at latest revision, 36 unresolved discussions, some commit checks failed.

---

*[schema/parser.go, line 11 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDID-r6-11:-KSfiwxKcbHXeQGHFKVG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/451ac794bdd6a28f8bb38312f3bb9dfc62de01dd/schema/parser.go#L11)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported function Parse1 should be of the form "Parse1 ..."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by ashwin95r** [comment]
Review status: 0 of 15 files reviewed at latest revision, 37 unresolved discussions, some commit checks failed.

---

*[schema/schema.go, line 19 at r8](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSL6HOqdc0y2rIfNDIG-r8-19:-KSjdzYmCqfcSaSYU-WB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ce59c19399d72b10f605e0a3df233e0aceea7f07/schema/schema.go#L19)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported type Item should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234)*

**Comment by manishrjain** [comment]
:lgtm_strong: Add tests for the cases that we discussed.

---

Review status: 0 of 15 files reviewed at latest revision, 27 unresolved discussions, some commit checks failed.

---

*[query/test_schema, line 1 at r9](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSjkqBuGDXYUWNRWg94:-KSjkqBv0WKBtmfbxLXO:b-vrq6ic) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ff51a9489cdf677b37cfd7aa0f3df11102fe630/query/test_schema#L1)):*
> ```
>  scalar age:int
> ```

Format this.

---

*[types/object_type.go, line 1 at r9](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-KSjlrqCLa2RkfO6oYtY:-KSjlrqDH_9sNJ4ULIXq:br5jmuo) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ff51a9489cdf677b37cfd7aa0f3df11102fe630/types/object_type.go#L1)):*
> ```Go
> package types
> ```

Move this to types/types.go, and also include scalar_types.go inside this new file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/234#-:-KSjmYX197ofd3pu1U7j:bqjo3cs)*

**Comment by ashwin95r** [comment]
Merged to master with commit aaba7d753643d65a57c3d76a40403ccd8b2759c0.

**Pull request closed without merging**
