### PR TITLE
Support recursive queries

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/647)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/query.go, line 233 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7UCGX-BExzBk9gJBn:-Ke7UCGX-BExzBk9gJBo:brdsmxc) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L233)):*
> ```Go
> 	for _, pc := range sg.Children {
> 
> 		if pc.uidMatrix == nil {
> ```

please put a comment that it can happen in `recurse` query.

---

*[query/query.go, line 551 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7V6uM_WGzMuDTIscw:-Ke7V6uNdja3nzc0Pvae:b-nqdzog) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L551)):*
> ```Go
> 		args.AfterUID = uint64(after)
> 	}
> 	if v, ok := gq.Args["depth"]; ok {
> ```

do we call `fill` for only `root` node ?
otherwise should we check, if gq.params.alias or something is `recurse` ?

---

*[query/query.go, line 556 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7UfZN0ILstBalwt2v:-Ke7UfZN0ILstBalwt2w:b6jgas9) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L556)):*
> ```Go
> 			return err
> 		}
> 		args.RecurseDepth = int(from)
> ```

should we use`uint64` ? 
negative values are not allowed in `depth`.. ?
we are not going bottom up.. right ?

---

*[query/query.go, line 986 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7W6ggZjQwQaTb4nQz:-Ke7W6ggZjQwQaTb4nR-:b-nvvw0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L986)):*
> ```Go
> 		algo.Sort(&o)
> 		sg.DestUIDs = &o
> 	} else if parent == nil && len(sg.SrcFunc) == 0 {
> ```

it looks like this was not required ?
was code readability/right flow was reason for this change ?

---

*[query/query_test.go, line 485 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7WaaCjXqzp0RN5Eia:-Ke7WaaCjXqzp0RN5Eib:b5zkm3q) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query_test.go#L485)):*
> ```Go
> 	query := `
> 		{
> 			recurse(id:0x01, depth: 2) {
> ```

i thought, depth `2` will get `friends of friends` ?
what happens at depth 0 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/647)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/query.go, line 233 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7UCGX-BExzBk9gJBn:-Ke7a-Igr19I9vskrmYQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L233)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

please put a comment that it can happen in `recurse` query.
</blockquote></details>

Done.

---

*[query/query.go, line 551 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7V6uM_WGzMuDTIscw:-Ke7azb3u2uADTkYrDZs:b-mop1l) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L551)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

do we call `fill` for only `root` node ?
otherwise should we check, if gq.params.alias or something is `recurse` ?
</blockquote></details>

Fill can be called for any node. Yeah, for stricter handling, we can check the `recurse` keyword.  Done.

---

*[query/query.go, line 556 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7UfZN0ILstBalwt2v:-Ke7c37NukrdCsSCHOD6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L556)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

should we use`uint64` ? 
negative values are not allowed in `depth`.. ?
we are not going bottom up.. right ?

</blockquote></details>

Done.

---

*[query/query.go, line 986 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7W6ggZjQwQaTb4nQz:-Ke7aOeuRVuno77N2BtN:b-nyxt2v) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query.go#L986)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

it looks like this was not required ?
was code readability/right flow was reason for this change ?
</blockquote></details>

This would be the right flow. Currently, It wouldn't make a difference as they do the same thing.

---

*[query/query_test.go, line 485 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7WaaCjXqzp0RN5Eia:-Ke7aq56b71WFkRsT110:bnydy5s) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query_test.go#L485)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

i thought, depth `2` will get `friends of friends` ?
what happens at depth 0 ?
</blockquote></details>

We do get friends of friends, but since we don't fetch the attr, it's empty.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/647)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 485 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-Ke7WaaCjXqzp0RN5Eia:-KeGuX3xZdfjzOKjLDGa:bb2fqag) ([raw file](https://github.com/dgraph-io/dgraph/blob/42a376d7f55b0f76c7649e08cb3d664b13d17944/query/query_test.go#L485)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We do get friends of friends, but since we don't fetch the attr, it's empty.
</blockquote></details>

Went through this. Given we treat everything as an edge away, what we're currently doing makes sense.

---

*[query/recurse.go, line 14 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGo_lhOBC8sAnP-Ree:-KeGo_lhOBC8sAnP-Ref:b-cnm9tz) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L14)):*
> ```Go
> 	next chan bool, rch chan error) {
> 
> 	reachMap := make(map[string]map[uint64]map[uint64]struct{})
> ```

How about just a map[string]struct{}, and use fmt.Sprintf("%s|%d|%d", ...) for key.

---

*[query/recurse.go, line 49 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGv-YnFjJihKUGIu1y:-KeGv-YnFjJihKUGIu1z:b-lbo1s1) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L49)):*
> ```Go
> 		start.Children = append(start.Children, temp)
> 		/*
> 			it := algo.NewListIterator(start.DestUIDs)
> ```

cleanup

---

*[query/recurse.go, line 103 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGw3-1gVu2uDQu7ApW:-KeGw3-2CmGmqJ_QGT0H:b-l6ibnv) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L103)):*
> ```Go
> 		if numEdges > 1000000 {
> 			// If we've seen too many nodes, stop the query.
> 			rch <- ErrTooBig
> ```

return

---

*[query/recurse.go, line 181 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGvJdjYxN7FH4FOib-:-KeGvJdjYxN7FH4FOib0:b-bdxz9n) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L181)):*
> ```Go
> 	// Recurse number of times specified by the user.
> 	for i := uint64(0); i < depth; i++ {
> 		next <- false
> ```

next <- true

---

*[query/recurse.go, line 187 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGv9vkIE5dB90O5TmQ:-KeGv9vkIE5dB90O5TmR:b-o0xe28) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L187)):*
> ```Go
> 				if err == ErrTooBig {
> 					return err
> 				} else if err == ErrStop {
> ```

if err == ... Not else if.

---

*[query/recurse.go, line 189 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGvCcjC-YK_1LSTU4c:-KeGvCcjC-YK_1LSTU4d:bbq1nku) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L189)):*
> ```Go
> 				} else if err == ErrStop {
> 					break L
> 				} else {
> ```

No need for else here.

---

*[query/recurse.go, line 200 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGvMbEKFnB0_ISzTzq:-KeGvMbEKFnB0_ISzTzr:b1xar8c) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L200)):*
> ```Go
> 	}
> 	// Done expanding.
> 	next <- true
> ```

next <- false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-:-KeGwvBMevBQKwNVNSom:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[query/recurse.go, line 14 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGo_lhOBC8sAnP-Ree:-KeHCF-LsY93_Afnc125:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L14)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

How about just a map[string]struct{}, and use fmt.Sprintf("%s|%d|%d", ...) for key.
</blockquote></details>

Done.

---

*[query/recurse.go, line 49 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGv-YnFjJihKUGIu1y:-KeHCFmuLHAUhiQ2CGUB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L49)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

cleanup
</blockquote></details>

Done.

---

*[query/recurse.go, line 103 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGw3-1gVu2uDQu7ApW:-KeHCGBTtIcA3IiCNUWH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L103)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return
</blockquote></details>

Done.

---

*[query/recurse.go, line 181 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGvJdjYxN7FH4FOib-:-KeHCGtcdfFJz6bFmC24:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L181)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

next <- true
</blockquote></details>

Done.

---

*[query/recurse.go, line 187 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGv9vkIE5dB90O5TmQ:-KeHCH7dfcwAoTbBfyUf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L187)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if err == ... Not else if.
</blockquote></details>

Done.

---

*[query/recurse.go, line 189 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGvCcjC-YK_1LSTU4c:-KeHCHarlu2Jguvc_Uo3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L189)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for else here.
</blockquote></details>

Done.

---

*[query/recurse.go, line 200 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeGvMbEKFnB0_ISzTzq:-KeHCIGIKRHuGqWdbuFS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b921d1394208ef4b051be7edb80b96504c15281/query/recurse.go#L200)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

next <- false
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/647)*

**Comment by ashishnegi** [comment]
Review status: 3 of 4 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[query/recurse.go, line 91 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeHs7GYwB5tKJOI385r:-KeHs7GZ0OTSEhHxMj9T:ba1si56) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L91)):*
> sg.DestUIDs = algo.MergeSorted(sg.uidMatrix)
shouldn't this be outside of for loop ?

---

*[query/recurse.go, line 113 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeHseefVqokjhq4risD:-KeHseefVqokjhq4risE:b5ig953) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L113)):*
> ```Go
> 				temp.SrcUIDs = sg.DestUIDs
> 				// If no UIDs are left after filtering, Ignore the node.
> 				if algo.ListLen(temp.SrcUIDs) == 0 {
> ```

`temp.SrcUIDS` is `sg.SrcUIDs` which remain same throughout the loop..
which we checked above as well.. so no need of this check.

---

*[query/recurse.go, line 140 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeI0okZ0ihBdQtABTNc:-KeI0ok_ek16iE5Qn8A1:b-i7ry34) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L140)):*
> ```Go
> 			return
> 		}
> 		rch <- nil
> ```

usually, error channels are there to mark the done of execution..
here we are using it as done of one depth execution.. 
a comment here will be helpful.

---

*[query/recurse.go, line 151 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeI1e6koMl0KR9r5w6a:-KeI1e6koMl0KR9r5w6b:b-u1kps1) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L151)):*
> ```Go
> 	}
> 	expandErr := make(chan error, 2)
> 	next := make(chan bool, 2)
> ```

a comment about `2` will be helpful.
i think we need 2 because first `next <- true` and then ctx.Done() timesout, `next <- false`.
Is there any other reason as well ?
Does `expandErr` needs buffering of 2 ?

---

*[query/shortest.go, line 191 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeI33W0NqMjtjY4m5S4:-KeI33W12N7ZXD5Ln_LA:b32vhw) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/shortest.go#L191)):*
> ```Go
> 		if len(out) == 0 {
> 			rch <- ErrStop
> 		} else {
> ```

:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/647)*

**Comment by ashishnegi** [comment]
:lgtm: just some comments..

---

Review status: 3 of 4 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-:-KeI3oWAKiqWE0mDpHNd:blbbuvv)*

**Comment by ashwin95r** [comment]
Review status: 3 of 4 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[query/recurse.go, line 91 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeHs7GYwB5tKJOI385r:-KeI5RU4-dySGNYV2mrZ:b-k7i1kh) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L91)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

> sg.DestUIDs = algo.MergeSorted(sg.uidMatrix)
shouldn't this be outside of for loop ?
</blockquote></details>

Oops yes. Thanks for the catch.

---

*[query/recurse.go, line 113 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeHseefVqokjhq4risD:-KeI6A9k9jVkSjsPR93o:b83v5zh) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L113)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

`temp.SrcUIDS` is `sg.SrcUIDs` which remain same throughout the loop..
which we checked above as well.. so no need of this check.
</blockquote></details>

Right. Since I moved the filtering step, it doesn't change now.

---

*[query/recurse.go, line 140 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeI0okZ0ihBdQtABTNc:-KeI6OJTj2uw56nmAzPg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L140)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

usually, error channels are there to mark the done of execution..
here we are using it as done of one depth execution.. 
a comment here will be helpful.
</blockquote></details>

Done.

---

*[query/recurse.go, line 151 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeI1e6koMl0KR9r5w6a:-KeI6jHQaQygsp0AwszN:bvweecr) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/recurse.go#L151)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

a comment about `2` will be helpful.
i think we need 2 because first `next <- true` and then ctx.Done() timesout, `next <- false`.
Is there any other reason as well ?
Does `expandErr` needs buffering of 2 ?
</blockquote></details>

No, it actually doesn't but just for safety. Also, I fixed the case where it could have been 2 (In shortest path)

---

*[query/shortest.go, line 191 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/647#-KeI33W0NqMjtjY4m5S4:-KeI6vUN2b2rCL8wgP_C:bca6tvt) ([raw file](https://github.com/dgraph-io/dgraph/blob/443ae1f39f7fa9f5cb588144d76730c5f02ce9f6/query/shortest.go#L191)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

:)
</blockquote></details>

Yeah Here!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/647)*

**Comment by ashwin95r** [comment]
Merged.

**Comment by yinrong** [comment]
no doc?

**Comment by danielmai** [comment]
@yinrong Recurse query docs can be found here: https://docs.dgraph.io/query-language/#recurse-query

**Pull request closed without merging**
