### PR TITLE
Trigram indexing for regular expressions

### PR DESCRIPTION
**Pull request by tzdybal**
Implementation of trigram indexing to avoid scanning/matching of all values with regular expression.
New tokenizer added (`TrigramTokenizer`).
Task processing for `regexp` function changed:

1. Trigram index is used to narrow search space.
1. Only values returned from trigram index lookup are matched with regular expression.
1. If the expression is to "broad" (like `.*` or `[A-Za-z]+`), all values are matched with regular expression.

The last step is performed on values itself (not with `exact` index, like before). There are two advantages of this approach: values in multiple languages can be handled correctly, user doesn't need to specify 2 indices for one purpose.

Note: trigram index and regex can be used also for `exact` matching. Simple literals are a special case in regex library, so matching is not expensive. Of course this approach is not as fast as `exact` indexing, but can eliminate the need to define two index types to enable `regexp` and equality checking.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/845)

### CODE REVIEW

**Comment by tzdybal** [comment]
If you want to see how nice this works, please checkout revision `d2fb658d2315d5ea622f6c9a377be48d35aee5c7`.
Below, I'm pasting some example results generated using `goldendata.rdf.gz`.
Query like (with different actual regular expression):

```
{
  directors(func: regexp(name@en, "P.* Jackson")) {
    name@en
    director.film @filter(regexp(name@en, " ([Hh]obbit)|([Ll]ord.*[Rr]ings?)")) {
      name@en
    }
  }
}
```
| Expression | Number of results from trigram index |
| ---------------|------------------------------------------------|
| `([Hh]obbit)\|([Ll]ord.*[Rr]ings?)` | 155 |
|`Stan[a-z]* K`| 4667 |
|`Steven S.*`|323|
|`S.* Kubrick`|74|

**Comment by manishrjain** [comment]
This is exciting. Eager to take a look.

**Comment by manishrjain** [comment]
Review status: 0 of 21 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 49 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyP0VOceqofZOV-8Z5:-KhyP0VOceqofZOV-8Z6:b-9dttjb) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/posting/index.go#L49)):*
> ```Go
> }
> 
> var tokenMap map[string]int
> ```

remove this.

---

*[query/query_test.go, line 2611 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyJgeaZpSFUFrBxy5f:-KhyJgeaZpSFUFrBxy5g:b-dtd29h) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/query/query_test.go#L2611)):*
> ```Go
>       me(id:0x01) {
>         name
>         friend @filter(regexp(name, "((en)|(xo))n")) {
> ```

regexp(name, /((en)|(xo))n/i)
regexp(name, "((en)|(xo))n", i)

---

*[tok/tok.go, line 272 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyH2FYxBoZUbNbNjiR:-KhyH2FZbh4GIu8Ilf5F:b-11ii1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/tok/tok.go#L272)):*
> ```Go
> 		return nil, x.Errorf("Trigram indices only supported for string types")
> 	}
> 	runes := bytes.Runes([]byte(value))
> ```

Potentially use unicodes instead of runes.

---

*[tok/tok.go, line 278 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyKEVqFxx2wHyFZkHN:-KhyKEVqFxx2wHyFZkHO:b-a6uo0i) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/tok/tok.go#L278)):*
> ```Go
> 		for i := 0; i < l; i++ {
> 			trigram := string(runes[i : i+3])
> 			tokens[i] = encodeToken(trigram, t.Identifier())
> ```

tolowercase(..) as well? We most likely won't need to double the number of tokens here.

---

*[worker/task.go, line 416 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNzFp3YqblZmBy_LI:-KhyNzFp3YqblZmBy_LJ:b-fi1tp8) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/task.go#L416)):*
> ```Go
> 			}
> 		} else {
> 			// Full scan (without index)
> ```

Punt on full scan for now. We do need to clearly document which regexps we don't support. And also give a reference to codesearch library where they mention the regexps that they do support.

---

*[worker/trigram.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNsheoeMfWmPdgKT8:-KhyNsheoeMfWmPdgKT9:by48qmw) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/trigram.go#L65)):*
> ```Go
> 			// current list of result is passed for intersection
> 			results = uidsForRegex(attr, gid, sub, results)
> 			if results.Size() == 0 {
> ```

if result size exceeds 1M, then return back an error.

---

*[worker/trigram.go, line 81 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNwBR4yDgmqX05sHy:-KhyNwBR4yDgmqX05sHz:b-efsisp) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/trigram.go#L81)):*
> ```Go
> 			}
> 			subUids := uidsForRegex(attr, gid, sub, intersect)
> 			results = algo.MergeSorted([]*taskp.List{results, subUids})
> ```

same thing here.

---

*[worker/trigram.go, line 84 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNx-k9LH-ugrrFrQ4:-KhyNx-k9LH-ugrrFrQ5:b-5xuccv) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/trigram.go#L84)):*
> ```Go
> 		}
> 	default:
> 		// do nothing - we're going to return nil to indicate that full scan of values is required
> ```

This would return an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/845)*

**Comment by tzdybal** [comment]
Review status: 0 of 21 files reviewed at latest revision, 8 unresolved discussions.

---

*[posting/index.go, line 49 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyP0VOceqofZOV-8Z5:-KhyXaijbMXFJDLdt3b-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/posting/index.go#L49)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove this.
</blockquote></details>

Done.

---

*[query/query_test.go, line 2611 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyJgeaZpSFUFrBxy5f:-Khyga-QbjUrlyzB95lo:b7msj8c) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/query/query_test.go#L2611)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

regexp(name, /((en)|(xo))n/i)
regexp(name, "((en)|(xo))n", i)
</blockquote></details>

Created an issue for case-insensitive regexp's, I'll commit this separately. 

---

*[tok/tok.go, line 272 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyH2FYxBoZUbNbNjiR:-KhyXtJ5i44PKUVKyoOG:bqa6ccx) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/tok/tok.go#L272)):*
From the docs: 
> Runes returns a slice of runes (Unicode code points) equivalent to s.

So each trigram consists of 3 entire (not partial) Unicode code points. This is also the way it's handled by regex library.

---

*[tok/tok.go, line 278 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyKEVqFxx2wHyFZkHN:-KhygJxrZ9qgXFyw2YJk:b7msj8c) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/tok/tok.go#L278)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

tolowercase(..) as well? We most likely won't need to double the number of tokens here.
</blockquote></details>

Created an issue for case-insensitive regexp's, I'll commit this separately. 

---

*[worker/task.go, line 416 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNzFp3YqblZmBy_LI:-Ki7ADvxd2W0bsAcMbuo:bq7gryj) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/task.go#L416)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Punt on full scan for now. We do need to clearly document which regexps we don't support. And also give a reference to codesearch library where they mention the regexps that they do support.
</blockquote></details>

Created a separated task (asana) for documenting regex. Code change is done.

---

*[worker/trigram.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNsheoeMfWmPdgKT8:-Ki7ATRvMjUOWPj9p1Es:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/trigram.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if result size exceeds 1M, then return back an error.
</blockquote></details>

Done.

---

*[worker/trigram.go, line 81 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNwBR4yDgmqX05sHy:-Ki7ATops1S0YAYq3_2p:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/trigram.go#L81)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same thing here.
</blockquote></details>

Done.

---

*[worker/trigram.go, line 84 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-KhyNx-k9LH-ugrrFrQ4:-Ki7AUdpi_5FO29mf2Le:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/767043129508eae372e63bcc3993586b84803a36/worker/trigram.go#L84)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This would return an error.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/845)*

**Comment by ashwin95r** [comment]
Review status: 0 of 21 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 2580 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7TsWmEHGzA10Shwu-:-Ki7TsWmEHGzA10Shwu0:b1c28yj) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/query/query_test.go#L2580)):*
> ```Go
> 
> 	_, err := processToFastJsonReq(t, query)
> 	require.Error(t, err)
> ```

Error due to?

---

*[query/query_test.go, line 2734 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7U2AYs5ExLwRG5bVM:-Ki7U2AYs5ExLwRG5bVN:b-mdau2s) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/query/query_test.go#L2734)):*
> ```Go
> 		`{"me":[{"pattern":[{"value":"mississippi"}, {"value":"whissle"}]}]}`, js)
> }
> ```

Can we have a test which would trigger `ErrTooBig`? i.e some case that we don't support

---

*[worker/task.go, line 44 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7TMOxNmmStzmaXt1Q:-Ki7TMOxNmmStzmaXt1R:b-fd3mzc) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/worker/task.go#L44)):*
> ```Go
> 
> 	"github.com/google/codesearch/index"
> 	"github.com/google/codesearch/regexp"
> ```

Just a thought, should we name the package cindex and cregexp? to denote it's from codesearch?

---

*[worker/trigram.go, line 36 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7T6TFTA1BFVL_8j0S:-Ki7T6TGJJj2R3A4crjo:bj8qo0f) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/worker/trigram.go#L36)):*
> ```Go
> )
> 
> func uidsForRegex(attr string, gid uint32,
> ```

Some comments on what this function does.

---

*[worker/trigram.go, line 106 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7SkmuG2PTyR0-24C0:-Ki7SkmuG2PTyR0-24C1:b-ur3m1t) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/worker/trigram.go#L106)):*
> ```Go
> 
> func regexToWideError() error {
> 	return errors.New("Regular expression is too wide-ranging and can't be executed efficiently.")
> ```

This can be declared as a const in the package, like `ResultTooBigErr`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/845)*

**Comment by tzdybal** [comment]
Review status: 0 of 21 files reviewed at latest revision, 13 unresolved discussions.

---

*[query/query_test.go, line 2580 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7TsWmEHGzA10Shwu-:-Ki7WumyV5r_0BlVrqCW:bpcc5uc) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/query/query_test.go#L2580)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Error due to?
</blockquote></details>

This is one of the cases, where regexp is to wide-ranging. `[^ao]+` would have to generate too many trigrams, so it's considered as "match all".

---

*[query/query_test.go, line 2734 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7U2AYs5ExLwRG5bVM:-Ki7Xd72f3Ln6zMzEYYb:b-568t5j) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/query/query_test.go#L2734)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Can we have a test which would trigger `ErrTooBig`? i.e some case that we don't support
</blockquote></details>

Actually, we have 2 such cases. I'll think of something less trivial.

---

*[worker/task.go, line 44 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7TMOxNmmStzmaXt1Q:-Ki7Y-7mq5NucFthDOnq:b862w25) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/worker/task.go#L44)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Just a thought, should we name the package cindex and cregexp? to denote it's from codesearch?
</blockquote></details>

This will improve clarity. 

---

*[worker/trigram.go, line 36 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7T6TFTA1BFVL_8j0S:-Ki7YT2S2gx8-PmTCKwH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/worker/trigram.go#L36)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Some comments on what this function does.
</blockquote></details>

Done.

---

*[worker/trigram.go, line 106 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki7SkmuG2PTyR0-24C0:-Ki7dZIXdhdIqyteZnLH:bvm8dm3) ([raw file](https://github.com/dgraph-io/dgraph/blob/b36af1c3dfd88b2a18b7fc615a7849d4fdd931bd/worker/trigram.go#L106)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This can be declared as a const in the package, like `ResultTooBigErr`
</blockquote></details>

I can only make it a variable, not const. But it's still better than function call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/845)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 17 of 21 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-:-Ki80zmdimUMeCAuGoNu:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 17 of 21 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 186 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki8dh-Weg0YUkxMayE9:-Ki8dh-Weg0YUkxMayEA:bn9hfbi) ([raw file](https://github.com/dgraph-io/dgraph/blob/6249abe6752236e4499eb70e36ae48ad9867d878/worker/task.go#L186)):*
> ```Go
> 
> // processTask processes the query, accumulates and returns the result.
> func processTask(ctx context.Context, q *taskp.Query, gid uint32) (*taskp.Result, error) {
> ```

Can you add a TODO here to refactor processTask?

---

*[worker/task.go, line 416 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-Ki8do9XvMxPvMXcgTsq:-Ki8do9XvMxPvMXcgTsr:b5wjcr5) ([raw file](https://github.com/dgraph-io/dgraph/blob/6249abe6752236e4499eb70e36ae48ad9867d878/worker/task.go#L416)):*
> ```Go
> 			}
> 		} else {
> 			return nil, err
> ```

Would this err not be nil?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/845#-:-Ki8e-GVxUjEiP6qSB0C:bnfp4nl)*

**Comment by tzdybal** [comment]
Merged to master (a62fec22a47f6bd310783076881bca9a862f05d9)

**Pull request closed without merging**
