### PR TITLE
Language list handling in orderasc and orderdesc

### PR DESCRIPTION
**Pull request by tzdybal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/761)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm: Just a comment.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[gql/parser.go, line 956 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/761#-KgHheVgYwdzvGAxWseD:-KgHheVhZHFPziDed8Tq:b824805) ([raw file](https://github.com/dgraph-io/dgraph/blob/b7fc538521eb3dbd121720fcf01ca7b6f90bce1e/gql/parser.go#L956)):*
> ```Go
> 			p.Val = p.Val + "@" + strings.Join(langs, ":")
> 		} else {
> 			it.Prev()
> ```

We can use it.Peek() for checking to avoid doing this eles{prev}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/761#-:-KgHjJMr-VqSkjTPDmKx:bishn0z)*

**Comment by ashwin95r** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/761)*

**Comment by manishrjain** [comment]
:lgtm: Looks okay to me. Fix the comment by @ashwin95r  , and feel free to submit.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/761#-:-KgI5RgmFDePf88hZiKB:bz45gzs)*

**Comment by tzdybal** [comment]
Merged to `release/v0.7.4`.

**Pull request closed without merging**
