### PR TITLE
fix(cd): checksum name

### PR DESCRIPTION
**Pull request by skrdgraph**
## Problem
checksum file name is not right

## Solution
 use the correct pattern

### CODE REVIEW

**Comment by skrdgraph** [comment]
@MichelDiz - please review...

cc: @joshua-goldstein

**Comment by MichelDiz** [comment]
@skrdgraph there is more about this. Check the docs channel in Slack.

**Review by MichelDiz — APPROVED** [review]

**Review by joshua-goldstein — APPROVED** [review]
👍

**Comment by skrdgraph** [comment]
@MichelDiz @joshua-goldstein - I think this can go in, right? 

@dshekhar95 - you may hit merge-conflicts, as your next PR will be touching the same file.

**Comment by MichelDiz** [comment]
We could add an extra commit about fixing the folder issue.

This PR is not urgent, we are far from making a new release. So we can add more stuff here.

**Comment by skrdgraph** [comment]
closing this because @dshekhar95 fixed this

**Pull request closed without merging**
