### PR TITLE
fix(Dgraph): Optimize how split lists are written to main DB in bulk loader.

### PR DESCRIPTION
**Pull request by martinmr**
- Use the stream framework to iterate over the tmp DBs.
- Explicitly delete the tmp DBs at the end of the run.

Fixes DGRAPH-2440

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432)

 

Docs Preview: [Dgraph Preview](https://dgraph-11bf868ec1-93660.surge.sh)

### CODE REVIEW

**Review by manishrjain — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/loader.go, line 93 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpG-K83bOLlTX4C32h:-MGpG-K83bOLlTX4C32i:b-4o1ubo) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/loader.go#L93)):*
> ```Go
> 	dbs           []*badger.DB
> 	tmpDbs        []*badger.DB // Temporary DB to write the split lists to avoid ordering issues.
> 	tmpDbDirs     []string     // Location of temporary DBs.
> ```

Can't you get this from tmpDbs options?
___
*[dgraph/cmd/bulk/reduce.go, line 429 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpGHum3rm_uTH0opIB:-MGpGHum3rm_uTH0opIC:b-5mpxe3) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/reduce.go#L429)):*
> ```Go
> 	sync.Mutex
> 	db       *badger.DB
> 	writer   *badger.WriteBatch
> ```

You don't need writeBatch. You can use the stream writer.
___
*[dgraph/cmd/bulk/reduce.go, line 465 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpGSTXDk1D-60FVeEF:-MGpGSTYCkAp_5Wez4XL:b5vpk5f) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/reduce.go#L465)):*
> ```Go
> 		// Randomly pick a writer.
> 		writer := writers[rand.Intn(len(writers))]
> 		writer.Write(kvs)
> ```

Write via streamwriter.

**Review by martinmr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @manishrjain and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/loader.go, line 93 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpG-K83bOLlTX4C32h:-MGpJqsEC9BOD82kezP_:b-ugqw07) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/loader.go#L93)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can't you get this from tmpDbs options?
</blockquote></details>

Badger is not exposing so I cannot do this. Should I expose the options in Badger?
___
*[dgraph/cmd/bulk/reduce.go, line 429 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpGHum3rm_uTH0opIB:-MGpJzcA8wg3dKW3MXWZ:b-iapapj) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/reduce.go#L429)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need writeBatch. You can use the stream writer.
</blockquote></details>

This copies the split keys from the tmpDB to the main db. The stream writer deletes existing data so it cannot be used to copy the contents of tmpDB to the main DB.
___
*[dgraph/cmd/bulk/reduce.go, line 465 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpGSTXDk1D-60FVeEF:-MGpKGxM5zSKoBCmCDtf:b-otilcs) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/reduce.go#L465)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Write via streamwriter.
</blockquote></details>

See comment above.

**Review by martinmr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @manishrjain and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/reduce.go, line 429 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpGHum3rm_uTH0opIB:-MGpTg_tATg27CWpYpNZ:boh99qs) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/reduce.go#L429)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

This copies the split keys from the tmpDB to the main db. The stream writer deletes existing data so it cannot be used to copy the contents of tmpDB to the main DB.
</blockquote></details>

I see what you mean now. Done.

Now the keys are written using the original streamwriter.

**Review by manishrjain — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432)* status: all files reviewed, 3 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/loader.go, line 93 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpG-K83bOLlTX4C32h:-MHHGpacCBFpPlH4AqR4:bb7sa0c) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/loader.go#L93)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

Badger is not exposing so I cannot do this. Should I expose the options in Badger?
</blockquote></details>

yes.
___
*[dgraph/cmd/bulk/reduce.go, line 465 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpGSTXDk1D-60FVeEF:-MHHHDjs-SczcI-jt58x:bmv27u) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/reduce.go#L465)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Load the maxStreamId upfront and just add it to whatever the StreamId is being filled by the stream framework.

**Review by martinmr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/reduce.go, line 465 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MGpGSTXDk1D-60FVeEF:-MHHK3xQ4AAXWIN-D8IQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d025143584f94c46194c63e6e177a180e37efa07/dgraph/cmd/bulk/reduce.go#L465)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Load the maxStreamId upfront and just add it to whatever the StreamId is being filled by the stream framework.
</blockquote></details>

Done.

**Review by manishrjain — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-:-MHHMYJ4-vaqcji5WJoO:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/reduce.go, line 426 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MHHM8RY6Ec8U18plTcL:-MHHM8RY6Ec8U18plTcM:b-t9oafn) ([raw file](https://github.com/dgraph-io/dgraph/blob/11bf868ec139d453ec2cbfcd12d905be761d15ad/dgraph/cmd/bulk/reduce.go#L426)):*
> ```Go
> func (r *reducer) writeSplitLists(db, tmpDb *badger.DB, writer *badger.StreamWriter) {
> 	// baseStreamId is the max ID seen while writing non-split lists.
> 	baseStreamId := atomic.LoadUint32(&r.streamId)
> ```

Do AddUint32(&r.streamId, 1) here as well.

**Review by martinmr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6432)* status: all files reviewed, 3 unresolved discussions (waiting on @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/reduce.go, line 426 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6432#-MHHM8RY6Ec8U18plTcL:-MHHN2_68vQUSYEjDzIp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/11bf868ec139d453ec2cbfcd12d905be761d15ad/dgraph/cmd/bulk/reduce.go#L426)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do AddUint32(&r.streamId, 1) here as well.
</blockquote></details>

Done.

**Pull request merged**
