### PR TITLE
Cleanup/draft: Address various TODOs

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/343)

### CODE REVIEW

**Comment by jchiu0** [comment]
Review status: 0 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[group/conf.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdSk3srjhHJ2Jo1PSv-r1-76:-KXdeG4_itgjAVvKjFpL:b-rll82e) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/group/conf.go#L76)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary><blockquote>

exported function ParseConfig should have comment or be unexported
</blockquote></details>

Please fix.

---

*[worker/draft.go, line 332 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdeNjtC4gxUfSzKXqb:-KXdeNjtC4gxUfSzKXqc:bebj288) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/draft.go#L332)):*
> ```Go
> 
> func (n *node) Run() {
> 	fr := true // first run
> ```

Would prefer a less cryptic variable name like firstRun and you can drop the comment.

---

*[worker/predicate.go, line 102 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdfGJxCQpWeRhDZMMQ:-KXdfGJxCQpWeRhDZMMR:bev25v9) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L102)):*
> ```Go
> 		}
> 		g.Keys = append(g.Keys, key)
> 		k.Free()
> ```

I looked at the code again. Don't think you should free k and v here. The Key and Value function returns slices into the underlying data owned by the iterator. The iterator is already being closed above, but these are already taken care of.

Yes, we should copy the data here. The iterator might reuse key and value over iterations.

---

*[worker/predicate.go, line 191 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXddVAhf5HbPuKTV9ZE:-KXddVAhf5HbPuKTV9ZF:b-176fhi) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L191)):*
> ```Go
> 		if idx := bytes.IndexAny(k.Data(), ":|"); idx == -1 {
> 			continue
> 		} else {
> ```

No need to indent else block?

---

*[worker/predicate.go, line 194 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXddwFmPSIfXWsGjZ4v:-KXddwFmPSIfXWsGjZ4w:b-4syzmn) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L194)):*
> ```Go
> 			pred := string(k.Data()[:idx])
> 			if group.BelongsTo(pred) != gkeys.GroupId {
> 				pred += "~"
> ```

nit: You are copying pred twice here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/343)*

**Comment by manishrjain** [comment]
Review status: 0 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[group/conf.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdSk3srjhHJ2Jo1PSv-r1-76:-KXdidNaq3C-btV-SRXe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/group/conf.go#L76)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Please fix.
</blockquote></details>

Done.

---

*[worker/draft.go, line 332 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdeNjtC4gxUfSzKXqb:-KXdhxFvaD7Lcpsdcooa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/draft.go#L332)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Would prefer a less cryptic variable name like firstRun and you can drop the comment.
</blockquote></details>

Done.

---

*[worker/predicate.go, line 102 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdfGJxCQpWeRhDZMMQ:-KXdi9RjAx1ZbWoVrL1w:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L102)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

I looked at the code again. Don't think you should free k and v here. The Key and Value function returns slices into the underlying data owned by the iterator. The iterator is already being closed above, but these are already taken care of.

Yes, we should copy the data here. The iterator might reuse key and value over iterations.
</blockquote></details>

Done.

---

*[worker/predicate.go, line 191 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXddVAhf5HbPuKTV9ZE:-KXdiF-lUk6ZXPZI2Y8n:b-gew0bl) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L191)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

No need to indent else block?
</blockquote></details>

Need access to idx.

---

*[worker/predicate.go, line 194 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXddwFmPSIfXWsGjZ4v:-KXdiOPJH5Ng_4kwSxJG:bd6z0qi) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L194)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

nit: You are copying pred twice here.
</blockquote></details>

Yup. Can't think of any other way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/343)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[worker/predicate.go, line 194 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXddwFmPSIfXWsGjZ4v:-KXdk6r6A30tw4AcLlwg:b1yft9m) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L194)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Yup. Can't think of any other way.
</blockquote></details>

You can make a byte array with right capacity, copy pred in, append a ~. But yeah, it is many more lines of code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-:-KXdk_ETOj8by5eIwubk:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/predicate.go, line 194 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXddwFmPSIfXWsGjZ4v:-KXdkm1AH1HaDe9TP1a2:b-p0fsbw) ([raw file](https://github.com/dgraph-io/dgraph/blob/6b98796a8bbc7a5e6c372f3233bdd5e3c7b62225/worker/predicate.go#L194)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

You can make a byte array with right capacity, copy pred in, append a ~. But yeah, it is many more lines of code.
</blockquote></details>

Still won't work right. pred is used inside the if condition. You'll have to do a string conversion of this byte array anyway; which defeats the point of optimization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/343)*

**Comment by ashwin95r** [comment]
:lgtm: Just a small suggestion which can be done to avoid it.Prev()

---

Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[worker/predicate.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdlp4BPLJNfkAznkqv:-KXdlp4BPLJNfkAznkqw:bjzvsj3) ([raw file](https://github.com/dgraph-io/dgraph/blob/6972c94ccec0d92480970f4815f4bde95bea5174/worker/predicate.go#L87)):*
> ```Go
> 				pred += "~"
> 				it.Seek([]byte(pred)) // Skip over this predicate entirely.
> 				it.Prev()             // To tackle it.Next() called by default.
> ```

Won't calling it.Next() in the if condition and end of the loop be cleaner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-:-KXdmioBtcTILsUeGjyG:b-e0eg92)*

**Comment by manishrjain** [comment]
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[worker/predicate.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/343#-KXdlp4BPLJNfkAznkqv:-KXdnqAeSM2blaWnwFI3:bhw2ih8) ([raw file](https://github.com/dgraph-io/dgraph/blob/6972c94ccec0d92480970f4815f4bde95bea5174/worker/predicate.go#L87)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Won't calling it.Next() in the if condition and end of the loop be cleaner?
</blockquote></details>

Not really. This isn't so obvious in this function, but very obvious in the other one; which has multiple continue statements spread across the for block. Keep it.Prev next to it.Seek makes it obvious what's going on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/343)*

**Pull request closed without merging**
