### PR TITLE
feat(Apollo): Add support for @provides and @requires directive. 

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
Fixes GRAPHQL-1053.
This PR adds support for @provides and @requires directive for Apollo federation according to the [federation specs](https://www.apollographql.com/docs/federation/federation-spec/).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7503)

### CODE REVIEW

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
Looking good, will review fully when finished.

> Reviewed 7 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-:-MUrqh6R2_i-5Zn6wNf0:bcpk5eh)* status: all files reviewed, 2 unresolved discussions (waiting on @minhaj-shakeel and @pawanrawal)

___
*[graphql/schema/gqlschema.go, line 577 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MUriT6g17AMIlVtdhGY:-MUriT6g17AMIlVtdhGZ:bi8ojvu) ([raw file](https://github.com/dgraph-io/dgraph/blob/88ec06363f0d21bde3cc74bd43bcf879947720a0/graphql/schema/gqlschema.go#L577)):*
> ```
> directiveLocationMap
> ```
also add a `nil` entry for the new directives in this map
___
*[graphql/schema/rules.go, line 2115 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MUropcK4poDPfPAzmWZ:-MUropcLEgy-owjpfX33:bflx0iy) ([raw file](https://github.com/dgraph-io/dgraph/blob/88ec06363f0d21bde3cc74bd43bcf879947720a0/graphql/schema/rules.go#L2115)):*
> ```
> typ.Directives.ForName(apolloKeyDirective)
> ```
stale :)

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7503)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur and @pawanrawal)

___
*[graphql/schema/gqlschema.go, line 577 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MUriT6g17AMIlVtdhGY:-MUsJWnP6i-E4S3IDmof:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88ec06363f0d21bde3cc74bd43bcf879947720a0/graphql/schema/gqlschema.go#L577)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> directiveLocationMap
> ```
also add a `nil` entry for the new directives in this map
</blockquote></details>

Done.
___
*[graphql/schema/rules.go, line 2115 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MUropcK4poDPfPAzmWZ:-MUsJWBt57KDwhcSwL84:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/88ec06363f0d21bde3cc74bd43bcf879947720a0/graphql/schema/rules.go#L2115)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> typ.Directives.ForName(apolloKeyDirective)
> ```
stale :)
</blockquote></details>

Done.

**Review by abhimanyusinghgaur — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pawanrawal)

**Review by pawanrawal — APPROVED** [review]
Please add a detailed commit description explaining what the feature does.

> Reviewed 5 of 7 files at r1, 2 of 3 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-:-MV034AXCo8Rp0aQbDrN:b-w8iqhj)* status: all files reviewed, 2 unresolved discussions (waiting on @minhaj-shakeel)

___
*[graphql/schema/gqlschema.go, line 1611 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MV04qfT3-aO9b4n7_H_:-MV04qfU9ow3Bb_zq9y2:b-xgfwps) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2db887448e023747bbe6db99ed9d93889ae52be/graphql/schema/gqlschema.go#L1611)):*
> ```Go
> // Returns true if the field is of type which can be summed. Eg: int, int64, float
> func isSummable(fld *ast.FieldDefinition, defn *ast.Definition, providesTypeMap map[string]bool) bool {
> 	if hasExternal(fld) && !isKeyField(fld, defn) && !providesTypeMap[fld.Name] {
> ```

can we define an fn for this as it is being used at multiple places
___
*[graphql/schema/gqlschema.go, line 2224 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MV05BZiAMLE6EXx2j5i:-MV05BZiAMLE6EXx2j5j:b-8rj4cl) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2db887448e023747bbe6db99ed9d93889ae52be/graphql/schema/gqlschema.go#L2224)):*
> ```Go
> 		// Ignore Fields with @external directives and excluding those which are present
> 		// as an argument in @key directive
> 		if hasExternal(fld) && !isKeyField(fld, defn) && !providesTypeMap[fld.Name] {
> ```

use the fn defined above

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7503)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur and @pawanrawal)

___
*[graphql/schema/gqlschema.go, line 1611 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MV04qfT3-aO9b4n7_H_:-MVFTqqe0Egm9S6lXP3R:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2db887448e023747bbe6db99ed9d93889ae52be/graphql/schema/gqlschema.go#L1611)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

can we define an fn for this as it is being used at multiple places
</blockquote></details>

Done.
___
*[graphql/schema/gqlschema.go, line 2224 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7503#-MV05BZiAMLE6EXx2j5i:-MVFTrUM3qYNMuvRQybo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2db887448e023747bbe6db99ed9d93889ae52be/graphql/schema/gqlschema.go#L2224)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

use the fn defined above
</blockquote></details>

Done.

**Pull request merged**
