### PR TITLE
Feat(GraphQL): This PR allows to return errors from custom REST endpoint.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes GRAPHQL-359

Returned errors are parsed in` type GqlErrorList []*GqlError` where `GqlError` is

```

type GqlError struct {
        Message     string                   `json:"message"`
	Locations   []Location               `json:"locations,omitempty"`
	Path        []interface{}            `json:"path,omitempty"`
	Extensions  map[string]interface{}   `json:"extensions,omitempty"`
}
```

Example:
`{"errors":[{"message": "Rest API returns Error for myFavoriteMovies query","locations": [ { "line": 5, "column": 4 } ],"path": ["Movies","name"]}]}`
`

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604)

 

Docs Preview: [Dgraph Preview](https://dgraph-6e28054ba0-97552.surge.sh)

### CODE REVIEW

**Review by abhimanyusinghgaur — COMMENTED** [review]
Thinking about it, I feel a REST API when returning correct results, can give one of four kinds of data:
1. Scalar
2. Object
3. List of scalar
4. List of Object

What we are doing at present is, for every case we are expecting error in the following form from the API:
```
{ "errors": [{"message": "some error message"}]}
```
This seems best fit for case 2. For case 4, people may be inclined to give errors for every object in the list, so should we expect something like this for case 4?
```
[{ "errors": [{"message": "obj1 error"}]}, { "errors": [{"message": "obj2 error"}]}]
```
For case 1 and 3, I don't have anything  in mind, other than reusing these formats.

Should we do the above, or should we just continue with the current behaviour?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-:-MISiZWT9eoEhL488pw3:b-4yg5bl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 893 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIShMgM1PVtq4EhPTp8:-MIShMgM1PVtq4EhPTp9:brcga1g) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L893)):*
> ```
> type RESTErr struct{
> 			Errors x.GqlErrorList `json:"errors,omitempty"`
> 		}
> ```
We should declare this type outside of the function, if we are going to use it.

**Comment by JatinDevDG** [comment]
> Thinking about it, I feel a REST API when returning correct results, can give one of four kinds of data:
> 
> 1. Scalar
> 2. Object
> 3. List of scalar
> 4. List of Object
> 
> What we are doing at present is, for every case we are expecting error in the following form from the API:
> 
> ```
> { "errors": [{"message": "some error message"}]}
> ```
> 
> This seems best fit for case 2. For case 4, people may be inclined to give errors for every object in the list, so should we expect something like this for case 4?
> 
> ```
> [{ "errors": [{"message": "obj1 error"}]}, { "errors": [{"message": "obj2 error"}]}]
> ```
> 
> For case 1 and 3, I don't have anything in mind, other than reusing these formats.
> 
> Should we do the above, or should we just continue with the current behaviour?
> 
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-:-MISiZWT9eoEhL488pw3:b-4yg5bl)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)
> 
> _[graphql/resolve/resolver.go, line 893 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIShMgM1PVtq4EhPTp8:-MIShMgM1PVtq4EhPTp9:brcga1g) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L893)):_
> 
> > ```
> > type RESTErr struct{
> > 			Errors x.GqlErrorList `json:"errors,omitempty"`
> > 		}
> > ```
> 
> We should declare this type outside of the function, if we are going to use it.

We are returning an error list for custom mutation/query or field. For the custom field if one field return error then other fields still return the response.

If we want to return multiple errors then we can put them in our error lists as follows
[{ "errors": [{"message": "obj1 error"},{"message": "obj2 error"}]}]

If there are multiple custom fields returning error then it can be in below  format
{[{ "errors": [{"message": "obj1 error field 1"},{"message": "obj2 error field 1"}]}],[{ "errors": [{"message": "obj1 error field2"}]}]}

**Review by pawanrawal — CHANGES_REQUESTED** [review]
I think we should continue with the present behaviour. We have to just decide a format and say that we expect the errors in that format in the docs.

In GraphQL terms, the errors contain paths which are the path of a field. So for us, while resolving a custom field, we should just add the path of the field for which the error is encountered ideally. 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-:-MITB6RJ8GG_c934p-i6:biswzxu)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 892 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT8q7zDrRa7U7eAA8k:-MIT8q7zDrRa7U7eAA8l:bh7pqi8) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L892)):*
> ```Go
> 		var errs error
> 		var result []interface{}
> 		type RESTErr struct{
> ```

restErr because no need for it to be exported 
___
*[graphql/resolve/resolver.go, line 893 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIShMgM1PVtq4EhPTp8:-MIT99y37xtkHf2pFI5I:bxxjo76) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L893)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

We are returning an error list for custom mutation/query or field. For the custom field if one field return error then other fields still return the response.

If we want to return multiple errors then we can put them in our error lists as follows [{ "errors": [{"message": "obj1 error"},{"message": "obj2 error"}]}]

If there are multiple custom fields returning error then it can be in below  format {[{ "errors": [{"message": "obj1 error field 1"},{"message": "obj2 error field 1"}]}],[{ "errors": [{"message": "obj1 error field2"}]}]} 
</blockquote></details>

All the errors should be returned inside an `errors` key` and ideally they should the path as well but skip the path for now. See https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md
___
*[graphql/resolve/resolver.go, line 914 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT8e3943-mjWS5JY4V:-MIT8e3AEqTS6XtQEpEW:bb3l6bi) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L914)):*
> ```Go
> 			}
> 		} else if err := json.Unmarshal(b, &customErr); err == nil && len(customErr.Errors)!=0 {
> 			errCh<-customErr.Errors
> ```

no `gofmt`?
___
*[graphql/resolve/resolver.go, line 1012 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT9sgQ472GNC_bgvvM:-MIT9sgQ472GNC_bgvvN:b7lg2nx) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L1012)):*
> ```Go
> 					return
> 				}
> 			} else if err := json.Unmarshal(b, &customErr); err == nil && len(customErr.Errors)!=0 {
> ```

Actually club this and the condition below into the same else block

if graphql {
} else {
// REST case

// Now unmarshal based on status code
// If response.StatusCode >= 200 && response.StatusCode < 300 
// unmarshal into result
// else into errors

}

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 892 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT8q7zDrRa7U7eAA8k:-MIYyFg38vM0nJBmdwDC:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L892)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

restErr because no need for it to be exported 
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 893 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIShMgM1PVtq4EhPTp8:-MIYyCo85LkZxKC-4Gh8:b2ni9bh) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L893)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

All the errors should be returned inside an `errors` key` and ideally they should the path as well but skip the path for now. See https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md
</blockquote></details>

ok.
___
*[graphql/resolve/resolver.go, line 914 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT8e3943-mjWS5JY4V:-MIYyGr76raPo0zAGJ5L:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L914)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

no `gofmt`?
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 1012 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT9sgQ472GNC_bgvvM:-MIYyIGGEOqX8WIqGGVl:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L1012)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Actually club this and the condition below into the same else block

if graphql {
} else {
// REST case

// Now unmarshal based on status code
// If response.StatusCode >= 200 && response.StatusCode < 300 
// unmarshal into result
// else into errors

}
</blockquote></details>

changed.

**Review by JatinDevDG — COMMENTED** [review]
Path is already available in returned errors because it's of type gqlErrorList. Added it in one of the test. 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-:-MIYyYijCmoG3-57ccRh:b-sfu11i)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

**Review by pawanrawal — CHANGES_REQUESTED** [review]
Looking mostly good, just needs some small formatting changes.

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-:-MIrPysl2KSFDZatixxJ:b5r6wt5)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, and @MichaelJCompton)

___
*[graphql/resolve/resolver.go, line 1012 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT9sgQ472GNC_bgvvM:-MIrPBdxBaqjSQe285gj:bst72p6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L1012)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

changed.
</blockquote></details>

similar comment as above
___
*[graphql/resolve/resolver.go, line 897 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPdHl2qQDIdzGnOnp:-MIrPdHl2qQDIdzGnOnq:baaszj6) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L897)):*
> ```Go
> 		var errs error
> 		var result []interface{}
> 		var customErr restErr
> ```

var rerr restErr
___
*[graphql/resolve/resolver.go, line 915 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrOUslDtJ0gbBQ0-zr:-MIrOUsm7eS3DVMwONI2:btp6luj) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L915)):*
> ```Go
> 				return
> 			}
> 		} else if status >= 200 && status < 300 {
> ```

```
} else {
  // This must be a REST call

  if status >=200 && status < 300 {
  } else {
  }
}
```

Format it like this to make it clear that the status based handling is only for REST.
___
*[graphql/resolve/resolver.go, line 922 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrOqeo5xezpYK-CuvQ:-MIrOqeo5xezpYK-CuvR:b-q3pwpk) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L922)):*
> ```Go
> 		} else {
> 			if err = json.Unmarshal(b, &customErr); err != nil {
> 				err = errors.Errorf("unexpected Error with status code: %v", status)
> ```

unexpected error with
___
*[graphql/resolve/resolver.go, line 998 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPfwF8S_RbtWx5JXj:-MIrPfwF8S_RbtWx5JXk:baaszj6) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L998)):*
> ```Go
> 
> 			var result interface{}
> 			var customErr restErr
> ```

var rerr restErr
___
*[graphql/resolve/resolver.go, line 1024 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrP99a9Sv6mvFRPVOR:-MIrP99a9Sv6mvFRPVOS:b-g4bxqa) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L1024)):*
> ```Go
> 			} else {
> 				if err = json.Unmarshal(b, &customErr); err != nil {
> 					err = errors.Errorf("unexpected Error with status code: %v", status)
> ```

unexpected error
___
*[graphql/resolve/resolver.go, line 1874 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPZhu5tQWs9HLXbNz:-MIrPZhu5tQWs9HLXbO-:baaszj6) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L1874)):*
> ```Go
> 	if hrc.RemoteGqlQueryName == "" {
> 		var result interface{}
> 		var customErr restErr
> ```

var rerr restErr
___
*[graphql/resolve/resolver.go, line 1880 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPWEv8BPVMgAIjQ8j:-MIrPWEv8BPVMgAIjQ8k:b-g4bxqa) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L1880)):*
> ```Go
> 			}
> 		} else if err := json.Unmarshal(b, &customErr); err != nil {
> 			err = errors.Errorf("unexpected Error with status code: %v", status)
> ```

unexpected error

**Review by pawanrawal — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604)* status: all files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, and @MichaelJCompton)

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6604)* status: all files reviewed, 2 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/resolver.go, line 1012 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIT9sgQ472GNC_bgvvM:-MIrtSKNA8jcx7QWetsI:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/f4f7e791fb86ca2f793a5715e2a8b12d05541367/graphql/resolve/resolver.go#L1012)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

similar comment as above
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 897 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPdHl2qQDIdzGnOnp:-MIrt5Qd7PXL3T8H7_C4:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L897)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

var rerr restErr
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 915 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrOUslDtJ0gbBQ0-zr:-MIrt6XrCDnvTPS9dbq7:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L915)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

```
} else {
  // This must be a REST call

  if status >=200 && status < 300 {
  } else {
  }
}
```

Format it like this to make it clear that the status based handling is only for REST.
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 922 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrOqeo5xezpYK-CuvQ:-MIrt9Bj03EqIUFaUfrt:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L922)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

unexpected error with
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 998 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPfwF8S_RbtWx5JXj:-MIrtAPLDvJvZy2T7ZFY:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L998)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

var rerr restErr
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 1024 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrP99a9Sv6mvFRPVOR:-MIrtCHY97n2bOZ_9Xbw:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L1024)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

unexpected error
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 1874 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPZhu5tQWs9HLXbNz:-MIrtDIBC-zcwDRWIdtu:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L1874)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

var rerr restErr
</blockquote></details>

done.
___
*[graphql/resolve/resolver.go, line 1880 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6604#-MIrPWEv8BPVMgAIjQ8j:-MIrtECxEVwla6gqr4YC:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1db35d412e8ff3dbd6dc47a2e3588a9d3652666d/graphql/resolve/resolver.go#L1880)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

unexpected error
</blockquote></details>

done.

**Pull request merged**
