### PR TITLE
Fix cascade when ordering is applied

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/806)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 1082 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/806#-KgxY3n2sR5GZ4zBH6JJ:-KgxY3n3z1QEFdgIfOTb:b-ukwk5w) ([raw file](https://github.com/dgraph-io/dgraph/blob/58c5e15e77c3c49ec54ec8a5d17598f4f27a7329/query/query.go#L1082)):*
> ```Go
> 				included := make([]bool, len(l.Uids))
> 				for _, uid := range l.Uids {
> 					idx := algo.IndexOf(child.DestUIDs, uid) // Binary search.
> ```

No need for included. You can move IndexOf within the ApplyFilter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/806)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 1082 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/806#-KgxY3n2sR5GZ4zBH6JJ:-KgxYo9urRzgO5cXQL6E:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/58c5e15e77c3c49ec54ec8a5d17598f4f27a7329/query/query.go#L1082)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for included. You can move IndexOf within the ApplyFilter.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/806)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/806#-:-KgxeyWTq8TdtcUMooRS:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
