### PR TITLE
Fix #1873

### LINKED ISSUE #1873: Wrong result when doing a SET after S P * deletion
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
`v0.9.4`

- Have you tried reproducing the issue with latest release?
Yes

- Steps to reproduce the issue (command/config used to run Dgraph).

Try doing a `S P *` deletion, then do a `S P O` set and then a query. All should be part of the same transaction.

- Expected behaviour and actual result.

The set doesn't show up when doing a query though it should.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1880)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[contrib/integration/testtxn/main_test.go, line 508 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1880#-L-eEu6JNAMZHi4i-Ut4:-L-eEu6JNAMZHi4i-Ut5:bwxd1u7) ([raw file](https://github.com/dgraph-io/dgraph/blob/6553178416d027ad07afab6bc7d0369921f8ed25/contrib/integration/testtxn/main_test.go#L508)):*
> ```Go
> 	txn := s.dg.NewTxn()
> 	mu := &api.Mutation{}
> 	mu.SetJson = []byte(`{"name": "Manish", "friend": [{"name": "Jan"}]}`)
> ```

Do a set, sp* and then set in test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1880#-:-L-eExL8IbJ19ciW4p0b:b-uwkowd)*

**Comment by peterstace** [comment]
Might be worthwhile adding a test case for 1. add edge, 2. delete SP*, 3. add edge, 4. delete SP*, and then 5. add edge. State via query should be ok at each step.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1880#-:-L-eKAdJyw74d4sdAYES:b-489itp)*

**Comment by pawanrawal** [comment]
Done, good idea! Found a small issue which I fixed.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[contrib/integration/testtxn/main_test.go, line 508 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1880#-L-eEu6JNAMZHi4i-Ut4:-L-ePRVBNx1OMJebzLqx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6553178416d027ad07afab6bc7d0369921f8ed25/contrib/integration/testtxn/main_test.go#L508)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Do a set, sp* and then set in test
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1880#-:-L-ePOvQCQqHsJJ3lx9B:b-skajm9)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1880#-:-L-eR2RVbJCcYry9kP8i:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master as of f06f5a0729a6a000ddab0e0931e46bb5f0cbab24.

**Pull request closed without merging**
