### PR TITLE
Optimization of fastJsonNode

### PR DESCRIPTION
**Pull request by tzdybal**
`fastJsonNode` is strongly refactored and optimized. Code is simpler, consumes less memory and executes faster.

Changes:
 - slices used instead of maps
 - unified `attrs` and `children` containers into one (`attrs`), removed fastJsonAttr type
 - (min-)heap used instead of sorting
 - much simplified processing (because of single container in `fastJsonNode`)

Performance comparison - artificial test (committed to `query/outputnode_test.go`), times measured without profiler. Memory measured (for entire test execution, including all setup) with default profiler configuration (because `-memprofilerate=1` was much too slow).

| Branch                | `master`  | `improve/encode_meomry` | Improvement |
|----------------------|--------------|------------------------------------|-------------------|
| Time:                 | 172.283s | 0.336s                                   | > 512 x          |
| Total memory"   | 43.65GB | 283.30MB                              | > 157 x          |

In fact, memory improvement for encode function is much bigger - encode doesn't allocate memory. `fastJsonNode` creation is also much cheaper (in terms of memory).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1227)

### CODE REVIEW

**Comment by manishrjain** [comment]
I don't totally understand it, but looks like a great change. I've got a few comments. Once @janardhan1993 approves this, feel free to submit.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[query/outputnode.go, line 292 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpbkC2l2WK6cOaqvePX:-KpbkC2l2WK6cOaqvePY:bofh8v7) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L292)):*
> ```Go
> 
> func makeScalarNode(attr string, isChild bool, val []byte) *fastJsonNode {
> 	return &fastJsonNode{attr, 0, isChild, val, nil}
> ```

Please use the field names as well to qualify the variables.

---

*[query/outputnode.go, line 296 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpbkGoymUwbWcdSZ9_I:-KpbkGoymUwbWcdSZ9_J:b97vv47) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L296)):*
> ```Go
> 
> func makeNestedNode(attr string, isChild bool, val *fastJsonNode) *fastJsonNode {
> 	return &fastJsonNode{attr, 0, isChild, nil, []*fastJsonNode{val}}
> ```

Please use the field names to qualify the variables.

---

*[query/outputnode.go, line 427 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-Kpbl2Fq3AwJ32nxmIEK:-Kpbl2Fq3AwJ32nxmIEL:b-gygb3w) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L427)):*
> ```Go
> 	if fj.attrs.Len() > 0 {
> 		out.WriteRune('{')
> 		curr := heap.Pop(&fj.attrs).(*fastJsonNode)
> ```

s/curr/cur

---

*[query/outputnode.go, line 550 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpblbGA9wpWJeYxI7k9:-KpblbGBMg5bMUNuRUWQ:ba3dfna) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L550)):*
> ```Go
> 		// Merging with parent.
> 		parentSlice = merge(parentSlice, childSlice)
> 		//} else {
> ```

Remove?

---

*[query/outputnode_test.go, line 34 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-Kpble2tc6b7Zzx5ew53:-Kpble2tc6b7Zzx5ew54:b-hfpv1m) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode_test.go#L34)):*
> ```Go
> func makeFastJsonNode() *fastJsonNode {
> 	return &fastJsonNode{
> 	// uncoment for master branch
> ```

remove?

---

*[query/outputnode_test.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpblfwT6Ym5xBQsefGD:-KpblfwT6Ym5xBQsefGE:bco1vef) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode_test.go#L41)):*
> ```Go
> 
> func TestEncodeMemory(t *testing.T) {
> ```

Remove blank line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-:-KpblyXegG7E2zcinCJm:b-p9g2af)*

**Comment by tzdybal** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[query/outputnode.go, line 292 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpbkC2l2WK6cOaqvePX:-Kplwmm6X0ilkjYmxpC3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L292)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Please use the field names as well to qualify the variables.
</blockquote></details>

Done.

---

*[query/outputnode.go, line 296 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpbkGoymUwbWcdSZ9_I:-KplwnSbkscSlFWBm1Ue:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L296)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Please use the field names to qualify the variables.
</blockquote></details>

Done.

---

*[query/outputnode.go, line 427 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-Kpbl2Fq3AwJ32nxmIEK:-KplwoZFy-Ji0EqFiVb3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L427)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s/curr/cur
</blockquote></details>

Done.

---

*[query/outputnode.go, line 550 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpblbGA9wpWJeYxI7k9:-KplxA2ywVBGe0hKZccq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode.go#L550)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

---

*[query/outputnode_test.go, line 34 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-Kpble2tc6b7Zzx5ew53:-KplxL02NFikJ9CpvHNx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode_test.go#L34)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.

---

*[query/outputnode_test.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpblfwT6Ym5xBQsefGD:-Kpm1d07CstVx-hxPV4b:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/760c9b079403fe7c563b2f10f69d8275946953b5/query/outputnode_test.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove blank line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[query/outputnode.go, line 350 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpmwQP-mq53enT2m9vG:-KpmwQP-mq53enT2m9vH:b23uq90) ([raw file](https://github.com/dgraph-io/dgraph/blob/ebe3cceae9cfef5ab144470ccc8dfa81802b831f/query/outputnode.go#L350)):*
> ```Go
> 
> func (fj *fastJsonNode) SetUID(uid uint64, attr string) {
> 	fj.attrs = append(fj.attrs, makeScalarNode(attr, false, []byte(fmt.Sprintf("\"%#x\"", uid))))
> ```

I am not that familiar with this code, but if addlistchild, addmapchild or setuid are called twice then we would have the same output twice ?
If we are running it in debug mode and user has also requested for uid, setUid would be called twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-:-Kpn1-d6IZb47fMZJzWn:bnfp4nl)*

**Comment by tzdybal** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[query/outputnode.go, line 350 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227#-KpmwQP-mq53enT2m9vG:-KpnC1kiGBj5nXaSvvs3:b-v4wg77) ([raw file](https://github.com/dgraph-io/dgraph/blob/ebe3cceae9cfef5ab144470ccc8dfa81802b831f/query/outputnode.go#L350)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

I am not that familiar with this code, but if addlistchild, addmapchild or setuid are called twice then we would have the same output twice ?
If we are running it in debug mode and user has also requested for uid, setUid would be called twice.
</blockquote></details>

Special handling in `SetUID` function added (with test supporting this behaviour). Case where user asks for same predicate many times are handled earlier during the processing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1227)*

**Pull request closed without merging**
