### PR TITLE
feat(bulk): Allow encrypted input with unencrypted output in bulk.

### PR DESCRIPTION
**Pull request by parasssh**
Fixes DGRAPH-2135

All UT pass.

This adds a new flag `--encrypted_out` to bulk loader. Now, when bulk loading with encryption input or output, you must set both the `--encrypted` and `--encrypted_out` flags along with the encryption key. Otherwise, it's an error.

For example, to bulk load encrypted input data and output unencrypted data:

    dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file ./enc-key --encrypted=true --encrypted_out=false

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)

### CODE REVIEW

**Review by martinmr — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-:-MHlwIOQ12Mv2B0SDppj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @danielmai, @manishrjain, and @vvbalaji-dgraph)

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: all files reviewed, 1 unresolved discussion (waiting on @manishrjain, @parasssh, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MHlvKps7nW0JUmJWIck:-MHlvKps7nW0JUmJWIcl:b-4v8sii) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a0e3bdf4a149a3b0d4edbc9420087a571c29858/dgraph/cmd/bulk/run.go#L173)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> if len(opt.EncryptionKey) > 0 && !opt.Encrypted && !opt.EncryptedOut {
> 		fmt.Printf("Must use --encrypted/--encrypted_out with --encryption_key_file option.\n")
> 		os.Exit(1)		
> 	}
> ```
</details>

This error message is confusing especially if I set both of these but they're set to false:
```
$ dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file ~/dg/enc_key_file --encrypted=false --encrypted_out=false
...
Must use --encrypted/--encrypted_out with --encryption_key_file option.
```

There's a way in the Cobra flag handling to check if a flag was set/changed by the user (I believe it's this function from Cobra/Viper/pflag: https://godoc.org/github.com/spf13/pflag#FlagSet.Changed). Maybe that'd be useful.

There's a combination of flag values we need to support between these three flags.  Can we make the flags work like this instead?

Input: Encrypted, Output: Encrypted by only specifying `--encryption_key_file` (no need to specify encrypted=true):
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encryption_key_file ./enc-key
```

Input: Encrypted, Output: Unencrypted:
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encrypted_key_file ./enc-key --encrypted_out=false
```

Input: Unencrypted, Output: Encrypted
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encryption_key_file ./enc-key --encrypted=false
```

Input: Unencrypted, Output: Unencrypted (no flags to set, or both set to false, in which case encryption_key_file is effectively ignored):
```
dgraph bulk -f data.rdf.gz -s data.schema.gz
```
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encryption_key_file ./enc-key --encrypted=false --encrypted=false
```

**Review by parasssh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @danielmai, @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MHlvKps7nW0JUmJWIck:-MHmVGRp6p1gMFkC_k9j:budmdrv) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a0e3bdf4a149a3b0d4edbc9420087a571c29858/dgraph/cmd/bulk/run.go#L173)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> if len(opt.EncryptionKey) > 0 && !opt.Encrypted && !opt.EncryptedOut {
> 		fmt.Printf("Must use --encrypted/--encrypted_out with --encryption_key_file option.\n")
> 		os.Exit(1)		
> 	}
> ```
This error message is confusing especially if I set both of these but they're set to false:
```
$ dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file ~/dg/enc_key_file --encrypted=false --encrypted_out=false
...
Must use --encrypted/--encrypted_out with --encryption_key_file option.
```

There's a way in the Cobra flag handling to check if a flag was set/changed by the user (I believe it's this function from Cobra/Viper/pflag: https://godoc.org/github.com/spf13/pflag#FlagSet.Changed). Maybe that'd be useful.

There's a combination of flag values we need to support between these three flags.  Can we make the flags work like this instead?

Input: Encrypted, Output: Encrypted by only specifying `--encryption_key_file` (no need to specify encrypted=true):
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encryption_key_file ./enc-key
```

Input: Encrypted, Output: Unencrypted:
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encrypted_key_file ./enc-key --encrypted_out=false
```

Input: Unencrypted, Output: Encrypted
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encryption_key_file ./enc-key --encrypted=false
```

Input: Unencrypted, Output: Unencrypted (no flags to set, or both set to false, in which case encryption_key_file is effectively ignored):
```
dgraph bulk -f data.rdf.gz -s data.schema.gz
```
```
dgraph bulk -f data.rdf.gz -s data.schema.gz --encryption_key_file ./enc-key --encrypted=false --encrypted=false
```
</blockquote></details>

The last command was in conflict with first one. Here is what I have done:

`dgraph bulk -f g01.rdf.gz -s g01.schema.gz`  => Unenc Input to  Unenc Output
`dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key` => Enc Input to Enc Output
`dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted`  => Enc Input to Unenc Output
`dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted_out`  => Unenc Input to Enc Output

**Review by parasssh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @danielmai, @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MHlvKps7nW0JUmJWIck:-MHmWLhNBbUZI6dnoNfz:bip69pw) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a0e3bdf4a149a3b0d4edbc9420087a571c29858/dgraph/cmd/bulk/run.go#L173)):*
<details><summary><i>Previously, parasssh wrote…</i></summary><blockquote>

The last command was in conflict with first one. Here is what I have done:

`dgraph bulk -f g01.rdf.gz -s g01.schema.gz`  => Unenc Input to  Unenc Output
`dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key` => Enc Input to Enc Output
`dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted`  => Enc Input to Unenc Output
`dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted_out`  => Unenc Input to Enc Output
</blockquote></details>

About the flags, it will be moot after latest patch that implements above.

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @manishrjain, @martinmr, @parasssh, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MHlvKps7nW0JUmJWIck:-MHqr3ki93Wka9AzWjxd:b-mpg4y8) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a0e3bdf4a149a3b0d4edbc9420087a571c29858/dgraph/cmd/bulk/run.go#L173)):*
> dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted  => Enc Input to Unenc Output
> dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted_out  => Unenc Input to Enc Output

Did you mean `--encrypted=false` for the first one?

**Review by parasssh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @danielmai, @manishrjain, @martinmr, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MHlvKps7nW0JUmJWIck:-MHqvMws0Nxb_URYTZWc:b-cc225j) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a0e3bdf4a149a3b0d4edbc9420087a571c29858/dgraph/cmd/bulk/run.go#L173)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted  => Enc Input to Unenc Output
> dgraph bulk -f g01.rdf.gz -s g01.schema.gz --encryption_key_file=./enc_key --encrypted_out  => Unenc Input to Enc Output

Did you mean `--encrypted=false` for the first one?
</blockquote></details>

No. For the first one, input in encrypted and hence --encrypted must be specified which indicate input encrypted.

**Review by danielmai — CHANGES_REQUESTED** [review]
When I run `--encrypted_out=false` it still outputs encrypted data.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-:-MI0yc707-UYpALhnTal:bv1alxv)* status: all files reviewed, 1 unresolved discussion (waiting on @danielmai, @manishrjain, and @vvbalaji-dgraph)

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @danielmai, @manishrjain, @parasssh, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 67 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1KRRXE0tgYD3PXGnZ:-MI1KRRXE0tgYD3PXGn_:bhng3jj) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L67)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> flag.Bool("encrypted", false,
> 		"Flag to indicate whether schema and data files are encrypted." +
> 		"Must be specified with --encryption_key_file or vault options")
> 	flag.Bool("encrypted_out", false,
> 		"Flag to indicate whether to encrypt the output." +
> 		"Must be specified with --encryption_key_file or vault option.")
> ```
</details>

Add spaces between the sentences. The help text is missing those:

<pre>
$ dgraph bulk -h
...
      --encrypted                        Flag to indicate whether schema and data files are <strong>encrypted.Must</strong> be specified with --encryption_key_file or vault options
      --encrypted_out                    Flag to indicate whether to encrypt the <strong>output.Must</strong> be specified with --encryption_key_file or vault option.
</pre>
___
*[dgraph/cmd/bulk/run.go, line 175 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1JcrqBsNzGZQFsts3:-MI1JcrqBsNzGZQFsts4:bmbzg4u) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L175)):*
> ```
> len(opt.EncryptionKey) == 0
> ```
Given the flag help text and error message talk about Vault flags, does this check work if Vault is specified?
___
*[dgraph/cmd/bulk/run.go, line 188 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1JypW3y5qM8QdXLf2:-MI1JypW3y5qM8QdXLf3:byclrt9) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L188)):*
> ```
> Must set --encrypted and/or --encrypted_out to true.
> ```
can we add more detail here? e.g.,

> Must set --encrypted and/or --encrypted_out to true when providing encryption key
___
*[dgraph/cmd/bulk/run.go, line 193 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1J3QX45NdhkhMBstN:-MI1J3QY199yNuNx_leo:b-wmyshp) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L193)):*
> ```
> encrytped
> ```
encrypted (typo)

Actually, this will be clearer if these were statements and not questions:

> Encrypted input: %v. Encrypted output: %v.

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @danielmai, @manishrjain, @parasssh, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 186 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1NTJSBS2Eb5-O3ub5:-MI1NTJSBS2Eb5-O3ub6:b-czodvj) ([raw file](https://github.com/dgraph-io/dgraph/blob/61c2b0f98de3ab08bb123b735023b82d6e60523f/dgraph/cmd/bulk/run.go#L186)):*
> ```
> if !opt.Encrypted || !opt.EncryptedOut
> ```
I tried this:
```
dgraph bulk -f data-enc/alpha1/export/dgraph.r33.u0924.2105/g01.rdf.gz -s data-enc/alpha1/export/dgraph.r33.u0924.2105/g01.schema.gz --badger.compression_level=0 --encryption_key_file ../ee/enc/test-fixtures/enc-key --encrypted=true --encrypted_out=false
```
and it didn't work
```
Must set --encrypted and/or --encrypted_out to true.
```

Should this condition be && instead of ||?  If both flags are set to false, then it's an error since there's no encryption involved in either the input or output.

**Review by parasssh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @danielmai, @manishrjain, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 173 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MHlvKps7nW0JUmJWIck:-MI1PKmZ6_oNgCall0r5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a0e3bdf4a149a3b0d4edbc9420087a571c29858/dgraph/cmd/bulk/run.go#L173)):*
<details><summary><i>Previously, parasssh wrote…</i></summary><blockquote>

No. For the first one, input in encrypted and hence --encrypted must be specified which indicate input encrypted. 
</blockquote></details>

Done.
___
*[dgraph/cmd/bulk/run.go, line 67 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1KRRXE0tgYD3PXGnZ:-MI1P49G2W6Yf_mli-Yu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L67)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> flag.Bool("encrypted", false,
> 		"Flag to indicate whether schema and data files are encrypted." +
> 		"Must be specified with --encryption_key_file or vault options")
> 	flag.Bool("encrypted_out", false,
> 		"Flag to indicate whether to encrypt the output." +
> 		"Must be specified with --encryption_key_file or vault option.")
> ```
Add spaces between the sentences. The help text is missing those:

<pre>
$ dgraph bulk -h
...
      --encrypted                        Flag to indicate whether schema and data files are <strong>encrypted.Must</strong> be specified with --encryption_key_file or vault options
      --encrypted_out                    Flag to indicate whether to encrypt the <strong>output.Must</strong> be specified with --encryption_key_file or vault option.
</pre>
</blockquote></details>

Done.
___
*[dgraph/cmd/bulk/run.go, line 175 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1JcrqBsNzGZQFsts3:-MI1P55N1jFvOVFuDHmq:b-5dnymi) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L175)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> len(opt.EncryptionKey) == 0
> ```
Given the flag help text and error message talk about Vault flags, does this check work if Vault is specified?
</blockquote></details>

Yes. Basically this field will be populated with key bytes from file or vault. So, logic will remain same once key is populated.
___
*[dgraph/cmd/bulk/run.go, line 188 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1JypW3y5qM8QdXLf2:-MI1PO1e4wo9FkIg5fU3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L188)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Must set --encrypted and/or --encrypted_out to true.
> ```
can we add more detail here? e.g.,

> Must set --encrypted and/or --encrypted_out to true when providing encryption key
</blockquote></details>

Done.
___
*[dgraph/cmd/bulk/run.go, line 193 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1J3QX45NdhkhMBstN:-MI1POjs0vUSh7o5VfNl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L193)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> encrytped
> ```
encrypted (typo)

Actually, this will be clearer if these were statements and not questions:

> Encrypted input: %v. Encrypted output: %v.
</blockquote></details>

Done.
___
*[dgraph/cmd/bulk/run.go, line 186 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1NTJSBS2Eb5-O3ub5:-MI1PMUT4FgR841yCzCv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/61c2b0f98de3ab08bb123b735023b82d6e60523f/dgraph/cmd/bulk/run.go#L186)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> if !opt.Encrypted || !opt.EncryptedOut
> ```
I tried this:
```
dgraph bulk -f data-enc/alpha1/export/dgraph.r33.u0924.2105/g01.rdf.gz -s data-enc/alpha1/export/dgraph.r33.u0924.2105/g01.schema.gz --badger.compression_level=0 --encryption_key_file ../ee/enc/test-fixtures/enc-key --encrypted=true --encrypted_out=false
```
and it didn't work
```
Must set --encrypted and/or --encrypted_out to true.
```

Should this condition be && instead of ||?  If both flags are set to false, then it's an error since there's no encryption involved in either the input or output.
</blockquote></details>

Done.

**Review by danielmai — COMMENTED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-:-MI1Q-aJ-2PsStfK-chE:b-uwkowd)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @danielmai, @manishrjain, and @vvbalaji-dgraph)

___
*[dgraph/cmd/bulk/run.go, line 175 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6541#-MI1JcrqBsNzGZQFsts3:-MI1PrIL0QUAMRcDbhBM:b4trpdj) ([raw file](https://github.com/dgraph-io/dgraph/blob/1e238bb6c203c741b95946ab37f31841857f3d14/dgraph/cmd/bulk/run.go#L175)):*
<details><summary><i>Previously, parasssh wrote…</i></summary><blockquote>

Yes. Basically this field will be populated with key bytes from file or vault. So, logic will remain same once key is populated.
</blockquote></details>

Got it. Great.

**Pull request merged**
