### PR TITLE
RAFT Snapshots

### PR DESCRIPTION
**Pull request by manishrjain**
- Use synced watermarks for snapshotting.
- Ensure that snapshots work when node is restarted.
- And also when the leader passes a snapshot to a follower. This would happen if the follower needs to be brought up to the leader's state.
- Fix a bug with UID assignment.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/391)

### CODE REVIEW

**Comment by jchiu0** [comment]
Just some minor comments. :lgtm: 

LG to use watermarks to decide when to snapshot.

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 99 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKTKoOmvLsgesRPgxU:-KZKTKoPW5XLT7THiQ7l:bx5nnp5) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/posting/lists.go#L99)):*
> ```Go
> }
> 
> func WaterMarkFor(group uint32) *x.WaterMark {
> ```

Comment for function.

---

*[worker/draft.go, line 138 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKU6OajjuZZWDDFc8W:-KZKU6ObAsmC5n1usN6t:b-wlex8y) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L138)):*
> ```Go
> func (n *node) Connect(pid uint64, addr string) {
> 	for n == nil {
> 		// Sometimes this function causes a panic. My guess is that n is sometimes still uninitialized.
> ```

Might want to add an issue to track this.

---

*[worker/draft.go, line 362 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKa7SGV-vZeHBmQnZS:-KZKa7SGV-vZeHBmQnZT:b53samy) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L362)):*
> ```Go
> 
> 	for e := range n.commitCh {
> 		if e.Data == nil || len(e.Data) == 0 {
> ```

Just checking len will do. (len of nil array is 0)

---

*[worker/draft.go, line 496 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKdZYSmmDFst5esYQh:-KZKdZYSmmDFst5esYQi:b-gjnmax) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L496)):*
> ```Go
> 
> 	var prev string
> 	ticker := time.NewTicker(time.Minute)
> ```

defer ticker.Close()?

---

*[worker/draft.go, line 674 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKbZS94Eaob7Uw5SrL:-KZKbZS94Eaob7Uw5SrM:bcnivg9) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L674)):*
> ```Go
> 
> 	for idx := 0; idx < len(query.Data); {
> 		if len(query.Data[idx:]) < 4 {
> ```

x.Checkf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-:-KZKe2l5Fuo1WgX2hSmn:b4bn0m)*

**Comment by manishrjain** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 99 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKTKoOmvLsgesRPgxU:-KZL-ia72OkGo9a_rYMp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/posting/lists.go#L99)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Comment for function.
</blockquote></details>

Done.

---

*[worker/draft.go, line 138 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKU6OajjuZZWDDFc8W:-KZL3tlC86uG1wY3a9ep:bmsjoct) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L138)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Might want to add an issue to track this.
</blockquote></details>

The init for nodes is a bit complicated. The sleep fixes the issue; so I think no need for a separate issue.

---

*[worker/draft.go, line 362 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKa7SGV-vZeHBmQnZS:-KZL0gX1g26t5c3GqRLi:b-vnrq05) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L362)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Just checking len will do. (len of nil array is 0)
</blockquote></details>

Ahh.. nice. Didn't know that. Thanks!

---

*[worker/draft.go, line 496 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKdZYSmmDFst5esYQh:-KZL3VASh9i_s7PiJOAA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L496)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

defer ticker.Close()?
</blockquote></details>

Done.

---

*[worker/draft.go, line 674 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZKbZS94Eaob7Uw5SrL:-KZL3sSLqHrjZgHGYZAI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L674)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

x.Checkf
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/391)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[worker/draft.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZL3oGgWYCvFyFe7s4W:-KZL3oGgWYCvFyFe7s4X:bk367zc) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L256)):*
> ```Go
> func (n *node) batchAndSendMessages() {
> 	batches := make(map[uint64]*bytes.Buffer)
> 	ticker := time.NewTicker(10 * time.Millisecond)
> ```

defer ticker.Close()

---

*[worker/draft.go, line 420 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZL3sMDHNtrOALGI1Db:-KZL3sMDHNtrOALGI1Dc:bk367zc) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L420)):*
> ```Go
> func (n *node) Run() {
> 	firstRun := true
> 	ticker := time.NewTicker(time.Second)
> ```

defer ticker.Close()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-:-KZL49mUyJL3bS6LDsQN:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[worker/draft.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZL3oGgWYCvFyFe7s4W:-KZL4Hgq_Qy0OjZHaxw_:b-k7mx7q) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L256)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

defer ticker.Close()
</blockquote></details>

Deleted.

---

*[worker/draft.go, line 420 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/391#-KZL3sMDHNtrOALGI1Db:-KZL4QUZlkTLQpNV4Tlq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e75ddfa9ffa35fd554d3fe536053ad05d32ec9e/worker/draft.go#L420)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

defer ticker.Close()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/391)*

**Pull request closed without merging**
