### PR TITLE
fixes/parser

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1225)

### CODE REVIEW

**Comment by srh** [comment]
I have one comment you should address but otherwise everything else looks good.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lex/lexer.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225#-KpYgTbrDQugU_n_nZKC:-KpYgTbrDQugU_n_nZKD:b97wrv1) ([raw file](https://github.com/dgraph-io/dgraph/blob/aaa5727fca4d45acced4c128241d98f229fa68c5/lex/lexer.go#L58)):*
> ```Go
> 	l       *Lexer
> 	idx     int
> 	savePos int
> ```

I would strongly recommend having Save() return the savePos and having Restore(pos) restore the savePos. The reason is, as the code is written right now, if a function calls Save() ... parseInner() ... Restore() , and if parseInner() also does Save(), then it will restore to the wrong place.  You'd have to know about the implementation of all your parsing functions and that would be difficult.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225#-:-KpYhBuCQYRxGfCQqgLS:bxjrr33)*

**Comment by ashwin95r** [comment]
Thanks!

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lex/lexer.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225#-KpYgTbrDQugU_n_nZKC:-KpYjv7l3XInS7ep-Xoq:bis0m37) ([raw file](https://github.com/dgraph-io/dgraph/blob/aaa5727fca4d45acced4c128241d98f229fa68c5/lex/lexer.go#L58)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

I would strongly recommend having Save() return the savePos and having Restore(pos) restore the savePos. The reason is, as the code is written right now, if a function calls Save() ... parseInner() ... Restore() , and if parseInner() also does Save(), then it will restore to the wrong place.  You'd have to know about the implementation of all your parsing functions and that would be difficult.
</blockquote></details>

Agree. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225#-:-KpYkbIY7-OIwVtOJRY-:b-ucfknh)*

**Comment by srh** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225#-:-KpYmxxMoknZghLWsCzL:bnfp4nl)*

**Comment by srh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lex/lexer.go, line 97 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225#-KpYnHDoj8om-iNmbsta:-KpYnHDoj8om-iNmbstb:blcdtqw) ([raw file](https://github.com/dgraph-io/dgraph/blob/e844aae68e7c4fcb517f23c9d49c68afc8d7ebd4/lex/lexer.go#L97)):*
> ```Go
> func (p *ItemIterator) Restore(pos int) {
> 	p.idx = pos
> 	if p.idx > len(p.l.items) {
> ```

Maybe the right thing here is to just crash, I don't know enough about the parsing code to say definitively, but something to consider.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225)*

**Comment by srh** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[lex/lexer.go, line 97 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225#-KpYnHDoj8om-iNmbsta:-KpYo6fQqAeGyjS0_y2Q:b-elncse) ([raw file](https://github.com/dgraph-io/dgraph/blob/e844aae68e7c4fcb517f23c9d49c68afc8d7ebd4/lex/lexer.go#L97)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Maybe the right thing here is to just crash, I don't know enough about the parsing code to say definitively, but something to consider.
</blockquote></details>

Yeah, I guess as long as we pass the right argument this shouldn't happen (Ans the user can't trigger this any other way). I'll make it an assert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1225)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
