### PR TITLE
Accept commets at different levels of query

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/513)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/513#-:-KatXQAHSov0DD_dS_ht:bnfp4nl)*

**Comment by manishrjain** [comment]
Make it a blue task.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/513#-:-KatXRvRPz_8ErcyD5dF:b-gkqu8m)*

**Comment by ashishnegi** [comment]
:lgtm: I had tested with comment inside the query and thought that comments were working in gql.
Thanks for catching up at all levels.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/513#-:-KatgbAoqWnnLYBWkFp2:b-wpuykd)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
