### PR TITLE
fix/proto1

### PR DESCRIPTION
**Pull request by jchiu0**
1) Switch to protos for sg.result / sg.uidMatrix, sg.Values, sg.Counts.
2) Worker returns taskpb.Result instead of task.Result (flatbuffers)
3) Make tests pass.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/322)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Lot of complicated FB code deleted. Nice!
Is there some stuff that we can delete from task.fbs and the task folder?

---

Review status: 0 of 10 files reviewed at latest revision, 23 unresolved discussions.

---

*[query/query.go, line 442 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlrRpe_M092py3KrEd:-KWlrRpe_M092py3KrEe:bdcwsvb) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/query/query.go#L442)):*
> ```Go
> 	} else {
> 		sg.SrcUIDs = algo.NewUIDList([]uint64{euid})
> 		if euid != 0 {
> ```

Can we please add some comments here to about this special handling of euid? I am not very clear about this.

---

*[query/query.go, line 519 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlnlcdMhZg3crSmLub:-KWlnlcdMhZg3crSmLuc:bhd2th5) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/query/query.go#L519)):*
> ```Go
> 	var err error
> 	if taskQuery != nil {
> 		data, err := worker.ProcessTaskOverNetwork(ctx, taskQuery)
> ```

We didn't check this error.

---

*[query/query.go, line 523 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlnVhoFxTaFNDn01ac:-KWlnVhpAci54mGPe5hT:b1erox4) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/query/query.go#L523)):*
> ```Go
> 		if result.Unmarshal(data) != nil {
> 			x.TraceError(ctx, x.Wrapf(err, "Error while processing task"))
> 			rch <- err
> ```

This error is while unmarshalling. Perhaps we should move this up and do separate handling for unmarshal?

---

*[taskpb/task.proto, line 7 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlico0y9CyFG5kLxr-:-KWlico0y9CyFG5kLxr0:bdne011) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/taskpb/task.proto#L7)):*
> ```protobuf
> 
> message UIDList {
> 	repeated fixed64 uids = 1 [packed=true];
> ```

In proto3, repeated fields are packed by default hence this might not be needed.

---

*[taskpb/task.proto, line 21 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWljHOF5VtQfWClF1QD:-KWljHOGZKum1z4OCf9g:b-5h08bq) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/taskpb/task.proto#L21)):*
> ```protobuf
> message CountList {
> 	// Most counts might be small.
> 	repeated uint32 count = 1 [packed=true];
> ```

same here?

---

*[worker/task.go, line 93 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlqFL7-Wx9qcItt3H0:-KWlqFL9ZrUdhUHfiPEv:bejg8ah) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/worker/task.go#L93)):*
> ```Go
> 
> 	var emptyUIDList *taskpb.UIDList // For handling _count_ only.
> 	if q.GetCount() == 1 {
> ```

It's not clear to me why we have this block, maybe we can add a comment here.

---

*[worker/task.go, line 138 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlppvWMWNHUcY_SJYd:-KWlppvWMWNHUcY_SJYe:b6ntttd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/worker/task.go#L138)):*
> ```Go
> 			opts.Intersect.FromTask(taskList)
> 		}
> 		out.UidMatrix = append(out.UidMatrix, pl.Uids(opts).ToProto())
> ```

I suppose this ToProto is only a temporary thing which would go away once we replace algo.UIDList? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-:-KWlmAgqfMz3Ik9iCUs5:b-qajpfq)*

**Comment by jchiu0** [comment]
Good point. Deleted a bunch of FB files and tests seem to still pass.

---

Review status: 0 of 19 files reviewed at latest revision, 23 unresolved discussions.

---

*[query/query.go, line 442 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlrRpe_M092py3KrEd:-KWluzrTYP4zZ8Rk4C_R:b-ci95ky) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/query/query.go#L442)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Can we please add some comments here to about this special handling of euid? I am not very clear about this.
</details>
Actually the check for euid != 0 doesn't seem necessary. I think Ashwin added it. Will go check with him.

---

*[query/query.go, line 519 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlnlcdMhZg3crSmLub:-KWlvB0BKhlqvsouf2ey:bql5ya3) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/query/query.go#L519)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We didn't check this error.
</details>
Oops and done.

---

*[query/query.go, line 523 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlnVhoFxTaFNDn01ac:-KWlvOBlTSaSubDKrys-:bql5ya3) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/query/query.go#L523)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This error is while unmarshalling. Perhaps we should move this up and do separate handling for unmarshal?
</details>
Oops and done.

---

*[taskpb/task.proto, line 7 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlico0y9CyFG5kLxr-:-KWlvbrT3pudmX0QurMi:b-c5dhj8) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/taskpb/task.proto#L7)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> In proto3, repeated fields are packed by default hence this might not be needed.
</details>
Was trying to be safe but yeah, it is really not needed.

---

*[taskpb/task.proto, line 21 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWljHOF5VtQfWClF1QD:-KWlvifD5kKYDahv113-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/taskpb/task.proto#L21)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> same here?
</details>
Done.

---

*[worker/task.go, line 93 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlqFL7-Wx9qcItt3H0:-KWlvwuA8jp2SE-jfBS0:b-q3fnc9) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/worker/task.go#L93)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> It's not clear to me why we have this block, maybe we can add a comment here.
</details>
Done. It's just for a dummy UID matrix. It might be possible to get rid of this cleanly in the future but I don't want to complicate this PR.

---

*[worker/task.go, line 138 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWlppvWMWNHUcY_SJYd:-KWlwDlG0MaNxdaL3MGS:bj6ie96) ([raw file](https://github.com/dgraph-io/dgraph/blob/d43b452d3a1ad420e87252dc96db59464f07aac0/worker/task.go#L138)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I suppose this ToProto is only a temporary thing which would go away once we replace algo.UIDList? 
</details>
Yes, indeed. All these will go away in the next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-:-KWluR-U7i6-aSgRwPye:bn7jc6o)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 19 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-:-KWm-u92vOg2cLFBLvCf:bnfp4nl)*

**Comment by manishrjain** [comment]
Okay, a few comments. Have a look at them, and address them. Once done, feel free to submit. :lgtm_strong: 

---

Reviewed 5 of 10 files at r1, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 31 unresolved discussions, some commit checks failed.

---

*[algo/uidlist.go, line 18 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp214ZXzz-6CiV6BLR:-KWp214_kW7JZp2rUPLR:b-agmo37) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/algo/uidlist.go#L18)):*
> ```Go
> // UIDList is a list of UIDs that can be stored in different forms.
> type UIDList struct {
> 	// Eventually algo.UIDList will be replaced with taskpb.UIDList. While
> ```

How about not suffixing protos with pb. Insted, just call it task.UIDList, or something else, like node.UidList or some better name.

---

*[algo/uidlist.go, line 20 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp2Kmgg6WRrAfpKoHV:-KWp2Kmh54RgsPl_zN89:b-fi928x) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/algo/uidlist.go#L20)):*
> ```Go
> 	// Eventually algo.UIDList will be replaced with taskpb.UIDList. While
> 	// migrating from flatbuffers to protos, we will keep this around to make
> 	// all tests pass.
> ```

I think it's okay to break the tests, even break the built while we're doing this move. So, might as well get rid of big chunks of code that we no longer need -- we can iterate faster that way.

---

*[algo/uidlist.go, line 323 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp2ZPI6zNfsJi89PGY:-KWp2ZPI6zNfsJi89PGZ:bilul5b) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/algo/uidlist.go#L323)):*
> ```Go
> 
> // ToProto converts UIDList to a proto. It is only temporary.
> // TODO: Get rid of this in the next PR that will remove algo.UIDList.
> ```

I'd suggest doing it now. But, it's up to you if you want to do it later.

---

*[query/geo.go, line 92 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7129qtWWqqbzxT7E:-KWp712AqFzCV1vu13_G:b5212z8) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/geo.go#L92)):*
> ```Go
> }
> 
> func filterUIDs(uids *algo.UIDList, values *taskpb.ValueList, q *geo.QueryData) *algo.UIDList {
> ```

I wonder if we can extend `taskpb.ValueList` struct by adding a function called `Length()`.

---

*[query/query.go, line 201 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp36xA8hHJmoCyf4r7:-KWp36xA8hHJmoCyf4r8:bj77ayc) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/query.go#L201)):*
> ```Go
> 		idx := pc.SrcUIDs.IndexOf(uid)
> 		x.AssertTruef(idx >= 0, "Attribute with uid not found in child Query uids")
> 		ul := pc.uidMatrix[idx]
> ```

How about having a few helper functions, which can give us these lists and counts, like:

List(idx int)
Count(idx int)
Value(idx int)

And of course, if you need to update the underlying structures, you can access them directly. But, doing pc.counts.Count[idx], or pc.values.GetValues()[idx] -- it's a big ugly.

---

*[query/query.go, line 455 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp5vSRJdBFnyeiUPfh:-KWp5vSSzAJ4c_ZwiuFJ:b4x0slg) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/query.go#L455)):*
> ```Go
> 	for i := 0; i < count; i++ {
> 		out.Values[i] = &taskpb.Value{
> 			Val: x.Nilbyte,
> ```

Do we really need to do this now?

---

*[query/query.go, line 518 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp6HOVKI8RYFmq2lFw:-KWp6HOWa4B-QmH6Knth:b-oogn5a) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/query.go#L518)):*
> ```Go
> 	var err error
> 	if taskQuery != nil {
> 		data, err := worker.ProcessTaskOverNetwork(ctx, taskQuery)
> ```

Add a TODO to modify the custom marshal to handle Result directly. Also, modify the endpoint to return result instead of []byte.

---

*[query/query.go, line 524 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp63Yyi-5a4cPxgLzu:-KWp63YzJs235Ig37AQP:bd1xcq8) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/query.go#L524)):*
> ```Go
> 			return
> 		}
> 		result := new(taskpb.Result)
> ```

var result taskpb.Result?

---

*[task/GroupKeys.go, line 44 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7RJaJ0TkOlaV8_9e:-KWp7RJaJ0TkOlaV8_9f:b-w5937) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b98bbd818ba28c105a5370d1d37bba9a50071c/task/GroupKeys.go#L44)):*
> ```Go
> 		x = rcv._tab.Indirect(x)
> 		if obj == nil {
> 			obj = new(KC)
> ```

You seem to have an older version of flatc. Can you revert these changes?

---

*[task/MembershipUpdate.go, line 32 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7U6LeOiU1FrLGk7H:-KWp7U6MMIRqbTPWwxf2:b-1kzc9c) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b98bbd818ba28c105a5370d1d37bba9a50071c/task/MembershipUpdate.go#L32)):*
> ```Go
> 		x = rcv._tab.Indirect(x)
> 		if obj == nil {
> 			obj = new(Membership)
> ```

And here.

---

*[task/Sort.go, line 40 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7VMXfsS4Kfw5Q0Vb:-KWp7VMY01EA_jbhqKuF:b-1kzc9c) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b98bbd818ba28c105a5370d1d37bba9a50071c/task/Sort.go#L40)):*
> ```Go
> 		x = rcv._tab.Indirect(x)
> 		if obj == nil {
> 			obj = new(UidList)
> ```

And here.

---

*[task/SortResult.go, line 32 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7WZYVKkUXIIRBzUf:-KWp7WZYVKkUXIIRBzUg:b-1kzc9c) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b98bbd818ba28c105a5370d1d37bba9a50071c/task/SortResult.go#L32)):*
> ```Go
> 		x = rcv._tab.Indirect(x)
> 		if obj == nil {
> 			obj = new(UidList)
> ```

And here.

---

*[taskpb/task.proto, line 4 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7ctpSlAXVS4mTsHW:-KWp7ctpSlAXVS4mTsHX:b-g86uxl) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/taskpb/task.proto#L4)):*
> ```protobuf
> syntax = "proto3";
> 
> package taskpb;
> ```

I think once we have removed task, we can s/taskpb/task across the entire code base. So, maybe don't worry about finding a better name now.

---

*[worker/task.go, line 70 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp9ADZrKdqcjAo9otv:-KWp9ADZrKdqcjAo9otw:b-zb3ns) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/worker/task.go#L70)):*
> ```Go
> 
> // processTask processes the query, accumulates and returns the result.
> func processTask(query []byte) ([]byte, error) {
> ```

Add a todo to change the input and output types here to protos.

---

*[worker/task.go, line 119 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp8kfR6K0JDrhNbrR4:-KWp8kfR6K0JDrhNbrR5:bhyh5sl) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/worker/task.go#L119)):*
> ```Go
> 			newValue.Val = vbytes
> 		} else {
> 			newValue.Val = x.Nilbyte
> ```

Ah right. We still need a Nilbyte. Nvm my prev comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-:-KWp9SzK-Ye4b2XKrTPR:b-v2ywl2)*

**Comment by jchiu0** [comment]
Review status: 7 of 15 files reviewed at latest revision, 44 unresolved discussions.

---

*[algo/uidlist.go, line 18 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp214ZXzz-6CiV6BLR:-KWpHS76q-J53MSBwnJH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/algo/uidlist.go#L18)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> How about not suffixing protos with pb. Insted, just call it task.UIDList, or something else, like node.UidList or some better name.
</details>
Done.

---

*[algo/uidlist.go, line 323 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp2ZPI6zNfsJi89PGY:-KWpHcrSfd2Lt5JxFAt9:b-dtvkd0) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/algo/uidlist.go#L323)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I'd suggest doing it now. But, it's up to you if you want to do it later.
</details>
Removing algo.UIDList affects other portions of code, e.g., Sort rpc calls etc. Would prefer to do it in a separate PR.

---

*[query/geo.go, line 92 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7129qtWWqqbzxT7E:-KWpHpLZbCF1uDPvdpSK:bbo528f) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/geo.go#L92)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I wonder if we can extend `taskpb.ValueList` struct by adding a function called `Length()`.
</details>
ValueList replaced with simple []*Value. This becomes cleaner now.

---

*[query/query.go, line 518 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp6HOVKI8RYFmq2lFw:-KWpJP6eQll3-xecbo8G:b-hukn99) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/query.go#L518)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a TODO to modify the custom marshal to handle Result directly. Also, modify the endpoint to return result instead of []byte.
</details>
Added TODO.

---

*[query/query.go, line 524 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp63Yyi-5a4cPxgLzu:-KWpIoPCoSyfYlIg_yo4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/query/query.go#L524)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> var result taskpb.Result?
</details>
Done.

---

*[worker/task.go, line 70 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp9ADZrKdqcjAo9otv:-KWpJYvqHE2Tihb9HZq8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/worker/task.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a todo to change the input and output types here to protos.
</details>
Done.

---

*[task/GroupKeys.go, line 44 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7RJaJ0TkOlaV8_9e:-KWpJ_fJvCDhg203WtFC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b98bbd818ba28c105a5370d1d37bba9a50071c/task/GroupKeys.go#L44)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You seem to have an older version of flatc. Can you revert these changes?
</details>
Done.

---

*[task/MembershipUpdate.go, line 32 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7U6LeOiU1FrLGk7H:-KWpJbdbAAa7BpJhxU4r:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b98bbd818ba28c105a5370d1d37bba9a50071c/task/MembershipUpdate.go#L32)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> And here.
</details>
Done.

---

*[taskpb/task.proto, line 4 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-KWp7ctpSlAXVS4mTsHW:-KWpJfmQXEshPorUIQYA:b-72rq9i) ([raw file](https://github.com/dgraph-io/dgraph/blob/5294c0ae50b18e3609a8c2443f4a212875fa1805/taskpb/task.proto#L4)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I think once we have removed task, we can s/taskpb/task across the entire code base. So, maybe don't worry about finding a better name now.
</details>
It is renamed. Was initially worried about name conflict during migration but that turned out not to be an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/322)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 8 of 14 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 42 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/322#-:-KWpL1tl3MLRh6-9rtRV:bnfp4nl)*

**Pull request closed without merging**
