### PR TITLE
Fix(GraphQL): This PR add schema cleaning in GraphQL.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes GRAPHQL-572

This PR adds schema cleaning in GraphQL which will remove empty links and types from generated GraphQL schema recursively. 

For example in the below schema type Y only have reverse edges, we won't generate mutation for this and also delete its references from the generated schema.

```
type X {
    f1: [Y] @dgraph(pred: "f1")
    name: String
    id: ID
}

type Y {
    f2: [Z] @dgraph(pred: "~f2")
    f1: [X] @dgraph(pred: "~f1")
}

type Z {
    f2: [Y] @dgraph(pred: "f2")
} 
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427)

 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-d44888b3e4-93182.surge.sh)

### CODE REVIEW

**Review by pawanrawal — COMMENTED** [review]
I found the code to be a bit complex, hence have modified it to make it cleaner. Let me know if it looks better or not and I have a TODO for you to verify.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-:-MH6Ckuy0Gp6baMfZqBS:b-2n69aq)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @MichaelJCompton and @pawanrawal)

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/admin/schema.go, line 23 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHF1s536__FL70hPdRx:-MHF1s536__FL70hPdRy:b5s1e51) ([raw file](https://github.com/dgraph-io/dgraph/blob/816a08f2749a4298651c26cb7b69ef5e79e1a53b/graphql/admin/schema.go#L23)):*
> ```Go
> 	"context"
> 	"encoding/json"
> ```

`goimports` adds this empty line, let it be.
___
*[graphql/schema/gqlschema.go, line 540 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHF1mHs9pt6si1nutEO:-MHF1mHs9pt6si1nutEP:b-f24yiw) ([raw file](https://github.com/dgraph-io/dgraph/blob/816a08f2749a4298651c26cb7b69ef5e79e1a53b/graphql/schema/gqlschema.go#L540)):*
> ```Go
> 		Fields: make([]*ast.FieldDefinition, 0),
> 	}
> ```

let's not remove this empty line
___
*[graphql/schema/gqlschema.go, line 588 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHF2QU34nGJJFwsYTUd:-MHF2QU45gTFQghZDgog:bd5k7dc) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/gqlschema.go#L588)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> nt := f.Type.NamedType
> 		if nt == "" {
> 			nt = f.Type.Elem.NamedType
> 		}
> ```
</details>

can be replaced with
```
nt := f.Type.Name()
```
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql, line 201 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFBwMG9UIkLh0LdW1g:-MHFBwMG9UIkLh0LdW1h:byw379q) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql#L201)):*
> ```
> queryX(first: Int, offset: Int): [X]
> 	queryY(first: Int, offset: Int): [Y]
> 	queryZ(first: Int, offset: Int): [Z]
> ```
I guess these queries don't have the filter argument even though the filters are generated because of the `hasFilterable` condition check we discussed yesterday @pawanrawal . Now that `has` filter is there, every query should have a filter argument. Will create a separate task for it.
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql, line 260 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFENFw1xLDwYP-COwD:-MHFENFx0jGJ1ImBuMzd:b75zi09) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql#L260)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> type Mutation {
> 	addX(input: [AddXInput!]!): AddXPayload
> 	addY(input: [AddYInput!]!): AddYPayload
> 	addZ(input: [AddZInput!]!): AddZPayload
> }
> ```
</details>

should we generate mutations for this case?
I don't feel like we should. In order to add `X`, I need `Y`, for `Y` I need `Z`, and for `Z` I need `X` again. No one can do anything with such a mutation. Doesn't seem useful.
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql, line 237 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFH0jb7qNj1AfJsBW6:-MHFH0jb7qNj1AfJsBW7:bwiprbv) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql#L237)):*
> ```
> input YFilter {
> 	not: YFilter
> }
> ```
doesn't feel like we should generate this. Can't do anything with it.

**Review by pawanrawal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427)* status: 3 of 13 files reviewed, 3 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql, line 201 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFBwMG9UIkLh0LdW1g:-MHF_VAw3MifIiPezI3d:b-tnfahx) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql#L201)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> queryX(first: Int, offset: Int): [X]
> 	queryY(first: Int, offset: Int): [Y]
> 	queryZ(first: Int, offset: Int): [Z]
> ```
I guess these queries don't have the filter argument even though the filters are generated because of the `hasFilterable` condition check we discussed yesterday @pawanrawal . Now that `has` filter is there, every query should have a filter argument. Will create a separate task for it.
</blockquote></details>

yeah separate ticket for that in next sprint. Are you creating it?
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql, line 260 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFENFw1xLDwYP-COwD:-MHFYemH3JPY0PjNi0y1:b-b306vy) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql#L260)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> type Mutation {
> 	addX(input: [AddXInput!]!): AddXPayload
> 	addY(input: [AddYInput!]!): AddYPayload
> 	addZ(input: [AddZInput!]!): AddZPayload
> }
> ```
should we generate mutations for this case?
I don't feel like we should. In order to add `X`, I need `Y`, for `Y` I need `Z`, and for `Z` I need `X` again. No one can do anything with such a mutation. Doesn't seem useful.
</blockquote></details>

True, not really helpful here even though it's a valid schema. Again Jatin, I recommend tackling it in a separate ticket in the next sprint. Please create one. We have already spent quite a bit of time on this ticket and have achieved the goal of not having invalid schemas anymore.
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql, line 237 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFH0jb7qNj1AfJsBW6:-MHFXTc_586MscX53Rfl:br8kb65) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql#L237)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> input YFilter {
> 	not: YFilter
> }
> ```
doesn't feel like we should generate this. Can't do anything with it.
</blockquote></details>

Yeah, actually I wonder if even the `queryY` is useful anymore. If we have can't add Y and Y is not an interface then we can't even `queryY` can we? In that case we should remove YFilter as well. @jatindevdg please create a separate task to cleanup queries based on the mutations that have been cleaned up as well. In this example even `queryZ` isn't useful.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/admin/schema.go, line 23 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHF1s536__FL70hPdRx:-MHFa1js5Bo0J7bkG5Y2:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/816a08f2749a4298651c26cb7b69ef5e79e1a53b/graphql/admin/schema.go#L23)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

`goimports` adds this empty line, let it be.
</blockquote></details>

done.
___
*[graphql/schema/gqlschema.go, line 540 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHF1mHs9pt6si1nutEO:-MHFa3ByAzgtj3qqepYI:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/816a08f2749a4298651c26cb7b69ef5e79e1a53b/graphql/schema/gqlschema.go#L540)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

let's not remove this empty line
</blockquote></details>

done.
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql, line 201 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFBwMG9UIkLh0LdW1g:-MHFZCRi2e5KYdQ1pfyA:bhz8q71) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql#L201)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> queryX(first: Int, offset: Int): [X]
> 	queryY(first: Int, offset: Int): [Y]
> 	queryZ(first: Int, offset: Int): [Z]
> ```
I guess these queries don't have the filter argument even though the filters are generated because of the `hasFilterable` condition check we discussed yesterday @pawanrawal . Now that `has` filter is there, every query should have a filter argument. Will create a separate task for it.
</blockquote></details>

yes, we don't clean filter arguments.
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql, line 260 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFENFw1xLDwYP-COwD:-MHFWFc_B7aa8EMw4vHx:b2n630e) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql#L260)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> type Mutation {
> 	addX(input: [AddXInput!]!): AddXPayload
> 	addY(input: [AddYInput!]!): AddYPayload
> 	addZ(input: [AddZInput!]!): AddZPayload
> }
> ```
should we generate mutations for this case?
I don't feel like we should. In order to add `X`, I need `Y`, for `Y` I need `Z`, and for `Z` I need `X` again. No one can do anything with such a mutation. Doesn't seem useful.
</blockquote></details>

yeah, cycle case is special. we need to check if the cycle is empty(don't have other fields apart from references) and then delete mutations. We can do that in separate task. And also Above schema is valid because it don't have nill references , so we simply return in this case.
___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql, line 237 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFH0jb7qNj1AfJsBW6:-MHFYCps5UWq0kpBC6XB:b-pmtkxm) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql#L237)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> input YFilter {
> 	not: YFilter
> }
> ```
doesn't feel like we should generate this. Can't do anything with it.
</blockquote></details>

yeah, but we don't clean filters as of now.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427)* status: 2 of 13 files reviewed, 3 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/schema/gqlschema.go, line 588 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHF2QU34nGJJFwsYTUd:-MHFaqZVEhDMe4F3CESt:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/gqlschema.go#L588)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> nt := f.Type.NamedType
> 		if nt == "" {
> 			nt = f.Type.Elem.NamedType
> 		}
> ```
can be replaced with
```
nt := f.Type.Name()
```
</blockquote></details>

done.

**Review by abhimanyusinghgaur — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427)* status: 2 of 13 files reviewed, all discussions resolved (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql, line 201 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6427#-MHFBwMG9UIkLh0LdW1g:-MHFajxG8VQaNJgtdBhe:bx6t78c) ([raw file](https://github.com/dgraph-io/dgraph/blob/d44888b3e42d94e3bda2608e1ebbabb20cb83659/graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql#L201)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

yes, we don't clean filter arguments.
</blockquote></details>

created ticket for this one.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 8 of 9 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6427)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @MichaelJCompton)

**Pull request merged**
