### PR TITLE
fix(Flags): Rename ambiguous TLS flags

### PR DESCRIPTION
**Pull request by karlmcguire**
(DGRAPH-3026)

TLS SuperFlag options will now look like this:

| Old Name | New Name | Changed |
|--------------:|----------------:|:------------:|
| `cacert`   | `ca-cert`       | :green_circle: |
| `internal-port-enabled`  | `internal-port` | :green_circle: |
| `client-auth` | `client-auth-type`  | :green_circle: |
| `cert`  | `client-cert`  | :green_circle: |
| `key` | `client-key` | :green_circle: |
| `node-cert`  | `server-cert`  | :green_circle: |
| `node-key`  | `server-key`  | :green_circle: |
|  `use-system-ca`  | `use-system-ca`  |  |
| `server-name` | `server-name` | |

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7491)

### CODE REVIEW

**Comment by manishrjain** [comment]
Should node-cert be called server-cert?

**Review by manishrjain — COMMENTED** [review]
Rest looks good. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7491#-:-MUj4K6z3Y-cPKs0gldT:b8f96k2)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @vvbalaji-dgraph)

**Comment by karlmcguire** [comment]
> Should node-cert be called server-cert?

Yea, we already have `server-name` so it makes sense to keep it consistent. Also, since `use-system-ca` is a bool, should we just change it to `system-ca`? We don't have any other `use-*` prefixes for bool options, but this might be a special case.

**Review by karlmcguire — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7491#-:-MUj6IMT8izLEV_T8PEP:bnfp4nl)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @vvbalaji-dgraph)

**Pull request merged**
