### PR TITLE
Fetch facets : edge key value pairs

### PR DESCRIPTION
**Pull request by ashishnegi**
1. Gql Parsing. `@facets` `@facets(facetkey1, facetkey2)` supported.
2. For a query :
```
jq . <<< $(curl localhost:8080/query -XPOST -d $'{
   debug(id:eve) {
     name @facets
     friend @facets {
       name @facets
     }
   }
 }')

Result :

{
  "debug": [
    {
      "@facets": {
        "name": {
          "live": "london",
          "origin": "europe"
        }
      },
      "friend": [
        {
          "@facets": {
            "_": {
              "best": false,
              "since": "12-jan-2012"
            },
            "name": {
              "origin": "america"
            }
          },
          "name": "alice"
        },
        {
          "@facets": {
            "_": {
              "best": true,
              "since": "12-jan-2011"
            },
            "name": {
              "live": "Bangalore",
              "origin": "india"
            }
          },
          "name": "ashish"
        }
      ],
      "name": "eve"
    }
  ]
}
```
3. Adds `AddNodeValue` to outputJsonNode.
4. Updates to the edges' facets reflect in query results.

Todo:
1. Add tests for updates on facets.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/579)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 131 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-Kcr02cnP1Ds4BfM-JjE:-Kcr02cnP1Ds4BfM-JjF:b-73zn74) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L131)):*
> ```Go
> 		return false
> 	}
> 	return facets.SameFacets(a.Facets, b.Facets)
> ```

How are we using samePosting?

---

*[posting/list.go, line 600 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrCN08kTumqwTzEhnM:-KcrCN08kTumqwTzEhnN:b9uz3xg) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L600)):*
> ```Go
> 		uid := p.Uid
> 		if opt.Intersect != nil {
> 			for ; it.Valid() && it.Val() < uid; it.Next() {
> ```

it.Seek(uid, 1) (or something like that).

---

*[posting/list.go, line 609 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrCmsE7q0wsEZPdDD0:-KcrCmsE7q0wsEZPdDD1:bri4f8q) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L609)):*
> ```Go
> 		return true
> 	})
> 	postFn(result)
> ```

Call postFn for every posting, don't create a slice of result.

---

*[posting/list.go, line 641 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDBl13PbakW1-_YoR:-KcrDBl13PbakW1-_YoS:b5gidtj) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L641)):*
> ```Go
> 		return nil, err
> 	}
> 	return mkFacetsCopy(p, param), nil
> ```

copyFacets(..)

---

*[posting/list.go, line 647 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrD9P1s2c4BKQAdK1S:-KcrD9P1s2c4BKQAdK1T:bwfar2y) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L647)):*
> ```Go
> func mkFacetsCopy(p *types.Posting, param *facets.Param) (fs []*facets.Facet) {
> 	paramKeyIdx := 0
> 	lParamKeys := len(param.Keys)
> ```

What is this for? Also rename it to numKeys

---

*[posting/list.go, line 654 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDRKxwrLntprOK7DB:-KcrDRKxwrLntprOK7DC:b-5toolj) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L654)):*
> ```Go
> 			copy(fcopy.Value, f.Value)
> 			fs = append(fs, fcopy)
> 			paramKeyIdx++
> ```

What is this paramKeyIdx logic?

---

*[posting/list.go, line 671 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDZIqZnTEs5V_Z0vR:-KcrDZIqZnTEs5V_Z0vS:b-atxxk2) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L671)):*
> ```Go
> 	var found bool
> 	l.iterate(math.MaxUint64-1, func(pi *types.Posting) bool {
> 		if pi.Uid == math.MaxUint64 {
> ```

We can't be sure about this anymore.

---

*[query/outputnode.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDejIVa6ksNydyYen:-KcrDejIVa6ksNydyYeo:bd80u13) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/query/outputnode.go#L76)):*
> ```Go
> type outputNode interface {
> 	AddValue(attr string, v types.Val)
> 	AddNodeValue(attr string, node outputNode)
> ```

I think you mean a ValueNode: AddValueNode? But, why not AddChild?

---

*[query/graph/graphresponse.proto, line 56 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEVgpT2OWKPnPY9eU:-KcrEVgqKXBuzsL8Hq2M:bngt6d9) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/query/graph/graphresponse.proto#L56)):*
> ```protobuf
> message Property {
>     string prop = 1;
>     oneof value {
> ```

This doesn't seem right.

---

*[rdf/parse.go, line 333 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEaoLwsXPzuP64pIM:-KcrEaoLwsXPzuP64pIN:byrpe9d) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/rdf/parse.go#L333)):*
> ```Go
> 		return x.Errorf("Expected '(' but found %v at Facet.", item.Val)
> 	}
> 	defer func() {
> ```

Why do this in defer? You won't save much, it would still consume CPU cycles.

---

*[types/facets/facets.proto, line 22 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEps1bTsw9yvmET9d:-KcrEps1bTsw9yvmET9e:b-134w3a) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/types/facets/facets.proto#L22)):*
> ```protobuf
> 
> message Param {
> 	bool AllKeys = 1;
> ```

bool all_keys = 1;

---

*[types/facets/sort.go, line 23 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEwnjiFp8PqP8laGb:-KcrEwnjiFp8PqP8laGc:bqfofv0) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/types/facets/sort.go#L23)):*
> ```Go
> )
> 
> func (a Facets) Len() int { return len(a.Facets) }
> ```

Do you need a separate file for this, or can you plug this in some other file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 131 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-Kcr02cnP1Ds4BfM-JjE:-KcrJCMa0S4dYECrTSX3:b98geuf) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L131)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

How are we using samePosting?
</blockquote></details>

Ignore this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579)*

**Comment by ashishnegi** [comment]
Review status: 9 of 18 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 600 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrCN08kTumqwTzEhnM:-KcvFWHrldQZxXmKtpP7:b-ia5hqh) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L600)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

it.Seek(uid, 1) (or something like that).
</blockquote></details>

done.. @ashwin95r please have a look.

---

*[posting/list.go, line 609 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrCmsE7q0wsEZPdDD0:-KcvFQUQSayK2YfkiH-_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L609)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Call postFn for every posting, don't create a slice of result.
</blockquote></details>

Done.

---

*[posting/list.go, line 641 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDBl13PbakW1-_YoR:-KcvFRb0UgEaFxRIjZs4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L641)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

copyFacets(..)
</blockquote></details>

Done.

---

*[posting/list.go, line 647 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrD9P1s2c4BKQAdK1S:-KcvFSbWQnKvwAE-JzaR:bj9p6pc) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L647)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What is this for? Also rename it to numKeys
</blockquote></details>

Done. Please see comments.

---

*[posting/list.go, line 654 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDRKxwrLntprOK7DB:-KcvFTCMWhpLuRKFjfwE:b-277h9n) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L654)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What is this paramKeyIdx logic?
</blockquote></details>

Added comments.

---

*[posting/list.go, line 671 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDZIqZnTEs5V_Z0vR:-KcvChD4BtA3roXsMOKk:b-c8tf3g) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L671)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We can't be sure about this anymore.
</blockquote></details>

Sorry, do not understand this comment.
Is this related to ValueTagged type (lang) specific ?
Since, i just re factored code, i will need some context on this.

---

*[query/outputnode.go, line 76 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDejIVa6ksNydyYen:-KcvCXrgO9xZd9R4YEXX:bvhr5h) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/query/outputnode.go#L76)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I think you mean a ValueNode: AddValueNode? But, why not AddChild?
</blockquote></details>

As discussed, AddChild is for adding child to list.
Renaming AddChild to `AddListChild` and `AddNodeValue` to `AddMapChild`.

---

*[rdf/parse.go, line 333 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEaoLwsXPzuP64pIM:-KcvC3t3xwzXTGStvv-m:b-yihttk) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/rdf/parse.go#L333)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why do this in defer? You won't save much, it would still consume CPU cycles.
</blockquote></details>

There are many return statements in this fn. Mostly error.
 I want sort of facet keys to happen at 2 places. 
Since this is parser fn, most probably new fn will be added. 
So, i want to keep sortfacets thing maintenance free.

---

*[types/facets/facets.proto, line 22 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEps1bTsw9yvmET9d:-KcvHCA8yrmPNu4a3LS6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/types/facets/facets.proto#L22)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

bool all_keys = 1;
</blockquote></details>

Done.

---

*[query/graph/graphresponse.proto, line 56 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEVgpT2OWKPnPY9eU:-KcvCUK0KT7GOlRgzTU8:bsk89ss) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/query/graph/graphresponse.proto#L56)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This doesn't seem right.
</blockquote></details>

Done.
Adding facets to children

---

*[types/facets/sort.go, line 23 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEwnjiFp8PqP8laGb:-KcvBfeHdvwX1z7tFW6B:b-ibbltg) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/types/facets/sort.go#L23)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do you need a separate file for this, or can you plug this in some other file?
</blockquote></details>

let me rename this as utils.go ?
Any future functions will go here.
There is one facets_type.go file under `facets/`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579)*

**Comment by ashwin95r** [comment]
Reviewed 9 of 22 files at r1, 8 of 13 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 600 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrCN08kTumqwTzEhnM:-KcvUznbhXD_ZOPX6Goj:b-vs1pr4) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L600)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

done.. @ashwin95r please have a look.
</blockquote></details>

Looks good.

---

*[types/facets/facets.proto, line 31 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcvYm3L-N9gxOleQ85A:-KcvYm3MxUDtKxR3dnkv:b1a15nv) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bf18a7d24106c11e59e55fcd236794ce3c7bc4b/types/facets/facets.proto#L31)):*
> ```protobuf
> 
> message List {
> 	repeated Facets facetsList = 1;
> ```

facet_list

---

*[worker/task.go, line 215 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcvaAeg3IE7MM2TfVT_:-KcvaAehjTyzvhsUnxsB:b3a49r) ([raw file](https://github.com/dgraph-io/dgraph/blob/a181e0d24197c36c1d61f873e46ebb75beb801e2/worker/task.go#L215)):*
> ```Go
> 		// get facets.
> 		if q.FacetParam != nil {
> 			if fs, err := pl.Facets(q.FacetParam); err == nil { // for value node
> ```

Using error to distinguish value node and uid node doesn't look great. Maybe it could be a bool (assuming the function would never error out)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579)*

**Comment by ashishnegi** [comment]
Review status: 15 of 18 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[types/facets/facets.proto, line 31 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcvYm3L-N9gxOleQ85A:-KcvrlMf6CsFQ5LRIgsm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bf18a7d24106c11e59e55fcd236794ce3c7bc4b/types/facets/facets.proto#L31)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

facet_list
</blockquote></details>

Done.

---

*[worker/task.go, line 215 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcvaAeg3IE7MM2TfVT_:-Kcvi4ij6z7McVB0DVx0:bq17ztu) ([raw file](https://github.com/dgraph-io/dgraph/blob/a181e0d24197c36c1d61f873e46ebb75beb801e2/worker/task.go#L215)):*
> // for uid
Now using explicit check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 13 files at r2, 3 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 671 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrDZIqZnTEs5V_Z0vR:-KcwMOw7kvaR2e5iuhxt:b4lo4bl) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/posting/list.go#L671)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Sorry, do not understand this comment.
Is this related to ValueTagged type (lang) specific ?
Since, i just re factored code, i will need some context on this.
</blockquote></details>

yeah, related to multiple values per posting.

---

*[posting/list.go, line 134 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwH1AM3zpAroQStfZH:-KcwH1AM3zpAroQStfZI:b-qnfohs) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/posting/list.go#L134)):*
> ```Go
> 		return false
> 	}
> 	if new.Op == Del {
> ```

Don't name things new. new is a keyword in Go.

---

*[posting/list.go, line 652 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwL_cfsFeRCfHOTl__:-KcwL_cfsFeRCfHOTl_a:b59xxkm) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/posting/list.go#L652)):*
> ```Go
> 	for _, f := range p.Facets {
> 		if param.AllKeys || param.Keys[paramKeyIdx] == f.Key {
> 			fcopy := &facets.Facet{f.Key, nil, f.ValType}
> ```

Always use the field names when setting a struct.

---

*[posting/list.go, line 656 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwLWcmx4rXCUclmkgR:-KcwLWcmx4rXCUclmkgS:b-e2nidg) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/posting/list.go#L656)):*
> ```Go
> 			copy(fcopy.Value, f.Value)
> 			fs = append(fs, fcopy)
> 			paramKeyIdx++
> ```

Call it numCopied.

---

*[query/outputnode.go, line 95 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwMvjIFACUGT-nH2gB:-KcwMvjIFACUGT-nH2gC:b6hn1ph) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/query/outputnode.go#L95)):*
> ```Go
> 
> // AddMapChild adds a node value for protoOutputNode.
> func (p *protoNode) AddMapChild(attr string, v outputNode, topNode bool) {
> ```

s/topNode/isRoot

---

*[query/outputnode.go, line 106 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwNCcwWqU0xepVRgZF:-KcwNCcwWqU0xepVRgZG:b351a5q) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/query/outputnode.go#L106)):*
> ```Go
> 		}
> 	}
> 	if childNode != nil {
> ```

Avoid nested ifs here. Use `else if` instead.

---

*[rdf/parse.go, line 333 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcrEaoLwsXPzuP64pIM:-KcwNcgr5rShf4uH-LjD:b-4oe7u0) ([raw file](https://github.com/dgraph-io/dgraph/blob/23fc1d1c103cf60baf802d0310ab1d2fdfa85a58/rdf/parse.go#L333)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

There are many return statements in this fn. Mostly error.
 I want sort of facet keys to happen at 2 places. 
Since this is parser fn, most probably new fn will be added. 
So, i want to keep sortfacets thing maintenance free.
</blockquote></details>

OK. My bad, I read this as a goroutine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-:-KcwQB7k9jXpsawjbhmD:bnfp4nl)*

**Comment by ashishnegi** [comment]
Review status: 16 of 18 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 134 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwH1AM3zpAroQStfZH:-Kczjy9wUTmC56JxWMWO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/posting/list.go#L134)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't name things new. new is a keyword in Go.
</blockquote></details>

Done.

---

*[posting/list.go, line 652 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwL_cfsFeRCfHOTl__:-KczkReLHxJSP-OdSKds:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/posting/list.go#L652)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Always use the field names when setting a struct.
</blockquote></details>

Done.

---

*[posting/list.go, line 656 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwLWcmx4rXCUclmkgR:-KczkSPWwUB7_Ja5eiQA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/posting/list.go#L656)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Call it numCopied.
</blockquote></details>

Done.

---

*[query/outputnode.go, line 95 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwMvjIFACUGT-nH2gB:-Kczlq01FbzglLi5ZzCL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/query/outputnode.go#L95)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s/topNode/isRoot
</blockquote></details>

Done.

---

*[query/outputnode.go, line 106 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-KcwNCcwWqU0xepVRgZF:-KczlkvAMBnB3nGpbxxE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f38a438f2bfcfb009271a590ee70aec47b82fd/query/outputnode.go#L106)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Avoid nested ifs here. Use `else if` instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/579#-:-Kd-SfiWKTYWYpmK3xHE:bnfp4nl)*

**Pull request closed without merging**
