### PR TITLE
Inequality functions should use sortable indices

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/695)

### CODE REVIEW

**Comment by gacharya255** [comment]
:lgtm: LG to move value conversion logic into getInequalityTokens.
LG to pick first sortable index in getInequalityTokens.
LG for the tests.

Just some minor comments.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 1672 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9b_Z5tZ-r9_iBdn3k:-Kf9b_Z5tZ-r9_iBdn3l:b-pne0rw) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/query/query_test.go#L1672)):*
> ```Go
> 
> 	js := processToFastJSON(t, query)
> 	require.JSONEq(t,
> ```

Maybe add a comment: Ensure Rick Grimes doesn't appear as we use sortable index.

---

*[worker/tokens.go, line 23 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9_uCHLw9iqhzXysFK:-Kf9_uCHLw9iqhzXysFL:bjknu8o) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/worker/tokens.go#L23)):*
> ```Go
> }
> 
> // getInequalityTokens gets tokens geq / leq compared to given token.
> ```

Add a comment here saying that we use first sortable index we found?

---

*[worker/tokens.go, line 45 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9_ChHqfJP-sOxpsYx:-Kf9_ChHqfJP-sOxpsYy:b8yhzpp) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/worker/tokens.go#L45)):*
> ```Go
> 
> 	/*
> 		v := types.ValueForType(types.BinaryID)
> ```

Maybe replace this with a comment saying that we are just getting the value for comparison.

---

*[worker/tokens.go, line 72 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9_QIskdUhpK1Bmouh:-Kf9_QIskdUhpK1Bmoui:bgj9p1) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/worker/tokens.go#L72)):*
> ```Go
> 	idxKey := x.Parse(it.Key().Data())
> 	if f == "eq" {
> 		fmt.Println(ineqToken, idxKey.Term)
> ```

Drop this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-:-Kf9aDV00bPrgkjSBsfj:by8nx5q)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query_test.go, line 1672 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9b_Z5tZ-r9_iBdn3k:-Kf9mP8EXYYRLZjpPVwj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/query/query_test.go#L1672)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Maybe add a comment: Ensure Rick Grimes doesn't appear as we use sortable index.
</blockquote></details>

Done.

---

*[worker/tokens.go, line 23 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9_uCHLw9iqhzXysFK:-Kf9mbHJ70kHiuxb4wRC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/worker/tokens.go#L23)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Add a comment here saying that we use first sortable index we found?
</blockquote></details>

Done.

---

*[worker/tokens.go, line 45 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9_ChHqfJP-sOxpsYx:-Kf9mraLH5fyRalZH2T_:b-7q8fqo) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/worker/tokens.go#L45)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Maybe replace this with a comment saying that we are just getting the value for comparison.
</blockquote></details>

We also return the value.

---

*[worker/tokens.go, line 72 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9_QIskdUhpK1Bmouh:-Kf9mhy6EoCzhr9qYnt_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2b31f16be36b51d4211afa339f3fa1031af6ee3d/worker/tokens.go#L72)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Drop this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/695)*

**Comment by ashishnegi** [comment]
:lgtm: just some questions ?

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[query/query_test.go, line 1646 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9sre8VtFF1hTf_6jH:-Kf9sre9ONPp5otzPX0R:bxgp397) ([raw file](https://github.com/dgraph-io/dgraph/blob/976c124b852eafc5cf4b2c299bf1614181273dab/query/query_test.go#L1646)):*
> Geq
do you think it will be useful to have tests on other types ? `int`, `dates` ?
Or they are already in some other package ?

---

*[worker/tokens.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9rM_JuDhDErEJayNQ:-Kf9rM_K3Z6LQbHQ5zQN:b-ddq4ba) ([raw file](https://github.com/dgraph-io/dgraph/blob/976c124b852eafc5cf4b2c299bf1614181273dab/worker/tokens.go#L51)):*
> ```Go
> 		return nil, "", x.Errorf("Attribute %s doest not have a valid tokenizer.", attr)
> 	}
> 	ineqToken := ineqTokens[0]
> ```

just for my understanding : where is ineqToken used for ?

---

*[worker/tokens.go, line 72 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9rkk8fY3pF5Vtj1de:-Kf9rkk9dRromj_pHXW3:b-20d1hl) ([raw file](https://github.com/dgraph-io/dgraph/blob/976c124b852eafc5cf4b2c299bf1614181273dab/worker/tokens.go#L72)):*
> ```Go
> 
> 	var out []string
> 	indexPrefix := x.IndexKey(attr, string(tok.Identifier())) //x.ParsedKey{Attr: attr}.IndexPrefix()
> ```

any reason to keep the commented code..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-:-Kf9t3_y9kRsyBdbw-St:b2mewf9)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[query/query_test.go, line 1646 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9sre8VtFF1hTf_6jH:-Kf9zwVK8AnCFTohNlf7:b9asyr1) ([raw file](https://github.com/dgraph-io/dgraph/blob/976c124b852eafc5cf4b2c299bf1614181273dab/query/query_test.go#L1646)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

> Geq
do you think it will be useful to have tests on other types ? `int`, `dates` ?
Or they are already in some other package ?
</blockquote></details>

They are already there. Strings were missing which has been added.

---

*[worker/tokens.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9rM_JuDhDErEJayNQ:-Kf9zXP45xO-0ToDVAMf:b-fkk0v2) ([raw file](https://github.com/dgraph-io/dgraph/blob/976c124b852eafc5cf4b2c299bf1614181273dab/worker/tokens.go#L51)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

just for my understanding : where is ineqToken used for ?
</blockquote></details>

it's returned, and used for doing a filter on actual values later, in processTask

---

*[worker/tokens.go, line 72 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/695#-Kf9rkk8fY3pF5Vtj1de:-Kf9zfbzC69FQ3j9Fpz3:bu2j3sr) ([raw file](https://github.com/dgraph-io/dgraph/blob/976c124b852eafc5cf4b2c299bf1614181273dab/worker/tokens.go#L72)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

any reason to keep the commented code..
</blockquote></details>

Nope. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/695)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
