### PR TITLE
fix(export): Escape MySQL column names

### PR DESCRIPTION
**Pull request by andres-lowrie**
Description: This change wraps all the column names with backticks so that MySQL won't complain when a table has columns that are also reserved keywords in MySQL.

### CODE REVIEW

**Comment by mangalaman93** [comment]
Thanks for updating the PR. Please create the PR against the `main` branch and sign the CLA. You will see a button above. Thank you.

**Review by darkn3rd — APPROVED** [review]
LGTM

**Review by mangalaman93 — APPROVED** [review]

**Comment by mangalaman93** [comment]
@andres-lowrie thanks for signing the CLA. The linter is not happy, could you take a look? Happy to help if it is not straight forward for you to figure out.

**Comment by joshua-goldstein** [comment]
@andres-lowrie Thanks for the PR - I think this PR needs to be rebased (or recreated) against our main branch.  Check that you have our latest main and that this PR is branched off from there.  I see that the base branch was changed from master to main but the original commits were presumably against master.  This should resolve the CI issues.  I would do this myself but since this is on your fork it is not possible for me to do.
cc' @mangalaman93

**Comment by mangalaman93** [comment]
Maybe the linter issue is also because this PR does not have latest main.

**Comment by joshua-goldstein** [comment]
> Maybe the linter issue is also because this PR does not have latest main.

Correct - the jobs that are running (and failing) are coming from workflow files checked into the old master branch.  The jobs marked as required are coming from our PR merge requirements on github.  Hence the confusion in CI.  They are not running because the workflow files are presumably not in the the branch `andres-lowrie:master`.

Fortunately this PR has a relatively small surface area, so in the worst case @andres-lowrie can recreate it relatively easily (from our main branch).

**Review by all-seeing-code — APPROVED** [review]

**Comment by andres-lowrie** [comment]
oops yeah I think I get it now. I'll re-do the changes from `main` after updating my fork

**Comment by andres-lowrie** [comment]
let me close this one out

**Comment by andres-lowrie** [comment]
created other pr #8961

**Pull request closed without merging**
