### PR TITLE
Implement upsert

### PR DESCRIPTION
**Pull request by pawanrawal**
Allows doing

```
{
	a as var(func: eq(name, "person")) @upsert
	b as var(func: eq(age, 20)) @upsert
}

mutation {
	set {
		uid(a) <age> "13" .
		uid(a) <friend> <100> .
		<100> <name> "Friend1" .
		uid(b) <name> "person2" .
	}
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1461)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Some nitpicks.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main_test.go, line 1515 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzThsoJOnkt1wNXJYC:-KtzThsoJOnkt1wNXJYD:bo3p68k) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/cmd/dgraph/main_test.go#L1515)):*
> ```Go
> 	mutation {
> 		schema {
> 			name: string @index(exact) .
> ```

Change this to term.

---

*[query/query.go, line 1854 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzU_TjIxb_FsIAWUdr:-KtzU_TjIxb_FsIAWUds:b98fe5h) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/query/query.go#L1854)):*
> ```Go
> 	if sg.IsGroupBy() {
> 		// Add the attrs required by groupby nodes
> 		for _, it := range sg.Params.groupbyAttrs {
> ```

Add a TODO.

---

*[query/query.go, line 2377 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzVFNjQAGk7Bh6gNyI:-KtzVFNjQAGk7Bh6gNyJ:b-p8bc9u) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/query/query.go#L2377)):*
> ```Go
> 					allocatedUids[sg.Params.Var] = uid
> 				} else {
> 					// There can only be one upsert per query, so the key can be
> ```

query block.

---

*[query/query.go, line 2379 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzVRNp5Td-_T6LoB2m:-KtzVRNp5Td-_T6LoB2n:b89p4n6) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/query/query.go#L2379)):*
> ```Go
> 					// There can only be one upsert per query, so the key can be
> 					// upsert-idx
> 					allocatedUids[fmt.Sprintf("upsert-%d", i)] = uid
> ```

`upsert-<blockname>`, or just blockname.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-:-KtzXAcsgXfMBPWb3BEz:b-4xdsaw)*

**Comment by jimanvlad** [comment]
Awesome! Will this capability be added to the dgraphloader too? That should pretty much remove 90% of our blockers.

**Comment by pawanrawal** [comment]
Do you mean the Go client @jimanvlad?

---

Review status: 13 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main_test.go, line 1515 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzThsoJOnkt1wNXJYC:-KtzZHmREIK-b23yLrNR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/cmd/dgraph/main_test.go#L1515)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Change this to term.
</blockquote></details>

Done.

---

*[query/query.go, line 1854 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzU_TjIxb_FsIAWUdr:-KtzZEQN17vD_srJat_K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/query/query.go#L1854)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a TODO.
</blockquote></details>

Done.

---

*[query/query.go, line 2377 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzVFNjQAGk7Bh6gNyI:-KtzZFQE6AqkubdEtG6p:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/query/query.go#L2377)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

query block.
</blockquote></details>

Done.

---

*[query/query.go, line 2379 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-KtzVRNp5Td-_T6LoB2m:-KtzZFrHgXOT0SeduKL4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/18adff069abf018387a20d11c953fc91f5391c19/query/query.go#L2379)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`upsert-<blockname>`, or just blockname.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-:-KtzZJX4v0n8Zg3kzOf2:byll7qt)*

**Comment by jimanvlad** [comment]
Hi,

No, I meant the dgraphloader. A way to make sure the nodes that I am adding are first checked to see if they exist in the graph first before creating them. Effectively the upsert functionality, but in dgraphloader :)

Vlad

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[query/query.go, line 2222 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1o_Wu8sO839U8pHWo:-Ku1o_Wu8sO839U8pHWp:b-od9vd6) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/query/query.go#L2222)):*
> ```Go
> 
> 	che := make(chan error, 1)
> 	ProcessGraph(ctx, sg, nil, che)
> ```

Can't we modify apply mutations to return the uid. We might do extra network call in processGraph.

---

*[query/query.go, line 2369 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1pzPEx-XJY7eC1K3C:-Ku1pzPFjFtyo_mdjPye:bqwb1) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/query/query.go#L2369)):*
> ```Go
> 				}
> 
> 				if len(sg.DestUIDs.Uids) == 0 {
> ```

What is this check for ?

---

*[worker/draft.go, line 552 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1vC4Qycs377wYJ4Ir:-Ku1vC4Qycs377wYJ4Is:b-kz7o9x) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/worker/draft.go#L552)):*
> ```Go
> }
> 
> func (n *node) handleUpsert(task *task) (bool, error) {
> ```

Ideally we should wait for applied watermark to catch up till previous index.(Or atleast mention it in docs when upsert wouldn't work)

---

*[worker/scheduler.go, line 73 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1uwVZsqc6jqoHLgLM:-Ku1uwVZsqc6jqoHLgLN:bnte0fe) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/worker/scheduler.go#L73)):*
> ```Go
> 
> func (t *task) key() uint32 {
> 	if t.upsert != nil && t.upsert.Attr == t.edge.Attr {
> ```

shouldn't the attribute be same on both upsert query and edge always ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-:-Ku1vx19j-Vp8XN-IJP6:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[query/query.go, line 2222 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1o_Wu8sO839U8pHWo:-Ku20saAWO_PzEEC3sxH:b-jys0kr) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/query/query.go#L2222)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Can't we modify apply mutations to return the uid. We might do extra network call in processGraph.
</blockquote></details>

We don't know the `uid` until the scheduler has processed the task because that's where we do another query. 

---

*[query/query.go, line 2369 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1pzPEx-XJY7eC1K3C:-Ku21BMAqIORvXyNg4M2:b5yhx9j) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/query/query.go#L2369)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

What is this check for ?
</blockquote></details>

Actually, we should throw an error here. This means we weren't able to assign a uid.

---

*[worker/draft.go, line 552 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1vC4Qycs377wYJ4Ir:-Ku21JuLN3NQnuGsTedB:b-eur5v2) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/worker/draft.go#L552)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Ideally we should wait for applied watermark to catch up till previous index.(Or atleast mention it in docs when upsert wouldn't work)
</blockquote></details>

Doesn't read linearizability give us that?

---

*[worker/scheduler.go, line 73 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1uwVZsqc6jqoHLgLM:-Ku21SPmSI-HqVQOXSpi:b-lbbdoa) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/worker/scheduler.go#L73)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

shouldn't the attribute be same on both upsert query and edge always ?
</blockquote></details>

upsert mutations are also accompanied by a `_predicate_` mutation. This check is to ignore that edge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[query/query.go, line 2222 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1o_Wu8sO839U8pHWo:-Ku22VlcDRMwgJ-qTi5x:b-qbcf6a) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/query/query.go#L2222)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We don't know the `uid` until the scheduler has processed the task because that's where we do another query. 
</blockquote></details>

Apply mutations doesn't return until the scheduler has processed the task. But we would need to do more changes, probably add a TODO.

---

*[worker/draft.go, line 552 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461#-Ku1vC4Qycs377wYJ4Ir:-Ku22BemFdKgy9hN9jks:bsn8byu) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7e4aecfba7c2f2e6886c85812b49e01c8babef9/worker/draft.go#L552)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Doesn't read linearizability give us that?
</blockquote></details>

yes, missed that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1461)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
