### PR TITLE
feat(GraphQL): Types Should be able to inherit Auth Rules from Interfaces

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
Fixes GRAPHQL-664.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6757)

 

Docs Preview: [Dgraph Preview](https://dgraph-74eaabd6d3-103291.surge.sh)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
Rewriting looks good. We need e2e tests for this.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-:-MK3jQtA90_9DytdyJ8i:b-1e8q65)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/resolve/auth_query_test.yaml, line 1063 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3Ynn351qNttZalif1:-MK3Ynn351qNttZalif2:bu88teb) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1063)):*
> ```YAML
>     }
> 
> - name: "Auth on interfaces"
> ```

Type should apply its own query auth rule along with the rule for the interface that it inherits
___
*[graphql/resolve/auth_query_test.yaml, line 1073 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3YgKB-fybAQETyezj:-MK3YgKB-fybAQETyezk:b-y6hwa2) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1073)):*
> ```YAML
>   jwtvar:
>     ROLE: "ADMIN"
>     TEXT: "post1"
> ```

Role and text are not required for this case.
___
*[graphql/resolve/auth_query_test.yaml, line 1097 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3ZGDa-aNJuGR5h2X3:-MK3ZGDa-aNJuGR5h2X4:bohy1sq) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1097)):*
> ```YAML
>     }
> 
> - name: "Auth on interfaces with Auth rule only on interface"
> ```

Type should apply query auth rule only for the interface when it doesn't have auth rules of its own
___
*[graphql/resolve/auth_query_test.yaml, line 1109 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3hg4z9Zufk3oviSg9:-MK3hg4z9Zufk3oviSgA:b-vnqa6f) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1109)):*
> ```YAML
>     TEXT: "post1"
>     ANS: "true"
>     USER: "Random"
> ```

looks like only `User` is helpful for this one?
___
*[graphql/resolve/auth_query_test.yaml, line 1128 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3hlxzCD32odw3nN-b:-MK3hlxzCD32odw3nN-c:b-8s51e3) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1128)):*
> ```YAML
>     }
> 
> - name: "Auth on interfaces with different Auth rules interfaces"
> ```

Type should apply query auth rules from all the interfaces that it implements.
___
*[graphql/resolve/auth_query_test.yaml, line 1137 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3ictT9OL99sqVpz0m:-MK3ictT9OL99sqVpz0n:b206zrd) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1137)):*
> ```YAML
>     }
>   jwtvar:
>     ROLE: "ADMIN"
> ```

Only User and Role are useful here.
Also, add another test where Role != "ADMIN" and User is the same.
___
*[graphql/schema/schemagen_test.go, line 94 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3jNZt79O-u2EJOjgZ:-MK3jNZt79O-u2EJOjg_:bjnh217) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/schema/schemagen_test.go#L94)):*
> ```Go
> 			require.NoError(t, err)
> 			outputFileName := outputDir + testFile.Name()
> 			ioutil.WriteFile(outputFileName, []byte(newSchemaStr), 0644)
> ```

Should be removed

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6757)* status: 0 of 56 files reviewed, 7 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/resolve/auth_query_test.yaml, line 1063 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3Ynn351qNttZalif1:-MK9tqh77tjvdZg3Q8Nt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1063)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Type should apply its own query auth rule along with the rule for the interface that it inherits
</blockquote></details>

Done.
___
*[graphql/resolve/auth_query_test.yaml, line 1073 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3YgKB-fybAQETyezj:-MK9trlu159apmgwTcOV:ba3dfob) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1073)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Role and text are not required for this case.
</blockquote></details>

Removed
___
*[graphql/resolve/auth_query_test.yaml, line 1097 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3ZGDa-aNJuGR5h2X3:-MK9tuUI5m4NzSAr2ghW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1097)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Type should apply query auth rule only for the interface when it doesn't have auth rules of its own
</blockquote></details>

Done.
___
*[graphql/resolve/auth_query_test.yaml, line 1109 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3hg4z9Zufk3oviSg9:-MK9tuvN4zveWOvRHmQU:b6ewfbc) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1109)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

looks like only `User` is helpful for this one?
</blockquote></details>

Removed others
___
*[graphql/resolve/auth_query_test.yaml, line 1128 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3hlxzCD32odw3nN-b:-MK9twt7DIhob7QLvVNm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1128)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Type should apply query auth rules from all the interfaces that it implements.
</blockquote></details>

Done.
___
*[graphql/resolve/auth_query_test.yaml, line 1137 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3ictT9OL99sqVpz0m:-MK9txNVBH8WvaCK8tj2:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1137)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Only User and Role are useful here.
Also, add another test where Role != "ADMIN" and User is the same.
</blockquote></details>

Done
___
*[graphql/schema/schemagen_test.go, line 94 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3jNZt79O-u2EJOjgZ:-MK9tz7g9DAFKqxJrONv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/schema/schemagen_test.go#L94)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Should be removed
</blockquote></details>

Done.

**Review by pawanrawal — APPROVED** [review]
Nice work, please address comments and feel free to merge!

> Reviewed 2 of 7 files at r1, 55 of 55 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-:-MK9wKB3CWSFE9v3tvn-:b-zeet5u)* status: all files reviewed, 8 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/e2e/auth/auth_test.go, line 390 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9sW_3644_it9fzxQk:-MK9sW_3644_it9fzxQl:bqgyzzu) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/e2e/auth/auth_test.go#L390)):*
> ```Go
> 			}
> 			`,
> 			user:   "user1@dgraph.io",
> ```

What happens when you query with a non-existent user? Add a case for that as well.
___
*[graphql/e2e/auth/auth_test.go, line 394 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9sRi01sfWVH80q-vJ:-MK9sRi01sfWVH80q-vK:b-7km8m9) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/e2e/auth/auth_test.go#L394)):*
> ```Go
> 		},
> 		{
> 			name: "Types inherit auth rules from all the different Interfaces",
> ```

Also, add a case where role != "ADMIN" and that should return an empty result?
___
*[graphql/e2e/common/common.go, line 896 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9t7kO8HhyrGL6mrOy:-MK9t7kO8HhyrGL6mrOz:b-v7ho6n) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/e2e/common/common.go#L896)):*
> ```Go
> }
> 
> func GetJWTForInterfaceAuth(t *testing.T, user, role string, ans bool, metaInfo *testutil.AuthMeta) http.Header {
> ```

Why do we need this? Why not just send the filled in `metaInfo.AuthVars` map to this function instead?
___
*[graphql/resolve/auth_query_test.yaml, line 1128 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK3hlxzCD32odw3nN-b:-MK9tn1mE4i0FsdomaXB:b1laz65) ([raw file](https://github.com/dgraph-io/dgraph/blob/f63bd4cc7c37da6b7363d63711ae441f0aa6026a/graphql/resolve/auth_query_test.yaml#L1128)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Type should apply query auth rules from all the interfaces that it implements.
</blockquote></details>

update the name to the one above, the name is still not clear.
___
*[graphql/resolve/auth_query_test.yaml, line 1152 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9tvqdC-nHhsNP_hQ5:-MK9tvqdC-nHhsNP_hQ6:bfjovtd) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/resolve/auth_query_test.yaml#L1152)):*
> ```YAML
>     }
> 
> - name: "Auth on interfaces with different Auth rules"
> ```

Name things better so that its clear what the case is about by just reading the name.

```
Type which inherits auth rules from interfaces returns no results when auth rules fail.
```
___
*[graphql/schema/auth.go, line 168 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9v2122-6bY2D4ltSf:-MK9v2122-6bY2D4ltSg:b59iytv) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/schema/auth.go#L168)):*
> ```Go
> 	}
> 
> 	for _, typ := range s.Types {
> ```

Add a comment that we are merging auth rules from the interfaces to the implementing type here.
___
*[graphql/schema/auth.go, line 201 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9vTplCy-wshtqnvSr:-MK9vTplCy-wshtqnvSs:bh3fz07) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/schema/auth.go#L201)):*
> ```Go
> 	if objectAuthRules == nil {
> 		return &AuthContainer{
> 			Query:  interfaceAuthRules.Query,
> ```

Are we not returning `interfaceAuthRules` directly here because it would cause issues for other implementing types?
___
*[graphql/schema/testdata/schemagen/input/auth-on-interfaces.graphql, line 36 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9voXg1gMX8Stgttow:-MK9voXg1gMX8Stgttox:b-4vrlq5) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/schema/testdata/schemagen/input/auth-on-interfaces.graphql#L36)):*
> ```GraphQL
> }
> 
> type B implements A{
> ```

This and interface A above are not useful. Are they used anywhere?

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6757)* status: 51 of 56 files reviewed, 8 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/e2e/auth/auth_test.go, line 390 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9sW_3644_it9fzxQk:-MKBCxLP5zar9VDz2flM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/e2e/auth/auth_test.go#L390)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What happens when you query with a non-existent user? Add a case for that as well.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/auth_test.go, line 394 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9sRi01sfWVH80q-vJ:-MKB5pplB9_ycR3YAh_0:b-gouutz) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/e2e/auth/auth_test.go#L394)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Also, add a case where role != "ADMIN" and that should return an empty result?
</blockquote></details>

Have already added.
___
*[graphql/e2e/common/common.go, line 896 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9t7kO8HhyrGL6mrOy:-MKB42gIBRNnStUSP42U:bg9kqrf) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/e2e/common/common.go#L896)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why do we need this? Why not just send the filled in `metaInfo.AuthVars` map to this function instead?
</blockquote></details>

I think it is because of `metaInfo` is a global variable.
___
*[graphql/resolve/auth_query_test.yaml, line 1152 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9tvqdC-nHhsNP_hQ5:-MKAGNBg8LDHryAaQV84:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/resolve/auth_query_test.yaml#L1152)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Name things better so that its clear what the case is about by just reading the name.

```
Type which inherits auth rules from interfaces returns no results when auth rules fail.
```
</blockquote></details>

Done.
___
*[graphql/schema/auth.go, line 168 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9v2122-6bY2D4ltSf:-MKAG4XE8ucAzsf8d0qp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/schema/auth.go#L168)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a comment that we are merging auth rules from the interfaces to the implementing type here.
</blockquote></details>

Done.
___
*[graphql/schema/auth.go, line 201 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9vTplCy-wshtqnvSr:-MKAFn3y5yzwBNXPnQvs:b-p30i90) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/schema/auth.go#L201)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Are we not returning `interfaceAuthRules` directly here because it would cause issues for other implementing types?
</blockquote></details>

returning copy of `InterfaceAuthRules` since it is a pointer and otherwise it will lead to unnecessary errors.
___
*[graphql/schema/testdata/schemagen/input/auth-on-interfaces.graphql, line 36 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6757#-MK9voXg1gMX8Stgttow:-MKAF8mL0IBEy7rOULTy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/50a25820dc691b745b66fc65f1e83c5f4cff7afe/graphql/schema/testdata/schemagen/input/auth-on-interfaces.graphql#L36)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This and interface A above are not useful. Are they used anywhere? 
</blockquote></details>

Done.

**Pull request merged**
