### PR TITLE
docs: This PR adds docs for Auth+Subscriptions.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes GRAPHQL-635 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6470)

 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-7a187c1e79-95769.surge.sh)

### CODE REVIEW

**Review by MichaelJCompton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6470)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @danielmai, @JatinDevDG, and @MichaelJCompton)

___
*[wiki/content/graphql/subscriptions/index.md, line 47 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-MHOO_PFE_sIzX5-I7Bx:-MHOO_PFE_sIzX5-I7By:bmk7nct) ([raw file](https://github.com/dgraph-io/dgraph/blob/2574d6797142d5ac525fdf86b4885d393813e2c2/wiki/content/graphql/subscriptions/index.md#L47)):*
> ```
> given in JWT.
> ```

needs to be 'the JWT' throughout this text
___
*[wiki/content/graphql/subscriptions/index.md, line 67 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-MHOOffx5XufXyhh52Q7:-MHOOffx5XufXyhh52Q8:b-cfottc) ([raw file](https://github.com/dgraph-io/dgraph/blob/2574d6797142d5ac525fdf86b4885d393813e2c2/wiki/content/graphql/subscriptions/index.md#L67)):*
> ```Markdown
> Subscription needs JWT in which $USER , expiry, and other variables are declared. The below example shows generating JWT and then using it with subscriptions.
> 
> Subscription+Auth
> ```

I didn't really get this gif.  It's quite long and if I'm coming in part way through, will I be able to understand what's going on?  It might be better as a couple of shorter clips that show one specific point.

...also I wasn't sure about the timeout because what does `reconnect: true,` do ?
___
*[wiki/content/graphql/subscriptions/index.md, line 69 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-MHOP7sB7uOhXIWbLdWn:-MHOP7sB7uOhXIWbLdWo:b-so8f0g) ([raw file](https://github.com/dgraph-io/dgraph/blob/2574d6797142d5ac525fdf86b4885d393813e2c2/wiki/content/graphql/subscriptions/index.md#L69)):*
> ```Markdown
> Subscription+Auth
> 
> Generally, JWT is passed in a header from graphql client as key-value pair, where the key is Header given in schema and the value is JWT.
> ```

Shouldn't this explicitly say the bits - so for example talk about `connectionParams` ?

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6470)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @danielmai and @MichaelJCompton)

___
*[wiki/content/graphql/subscriptions/index.md, line 47 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-MHOO_PFE_sIzX5-I7Bx:-MHRiYrw2IOX-OMsm8kY:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/2574d6797142d5ac525fdf86b4885d393813e2c2/wiki/content/graphql/subscriptions/index.md#L47)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> given in JWT.
> ```

needs to be 'the JWT' throughout this text
</blockquote></details>

done.
___
*[wiki/content/graphql/subscriptions/index.md, line 67 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-MHOOffx5XufXyhh52Q7:-MHVl0i86HVU4FdMhSlg:b-dzofs0) ([raw file](https://github.com/dgraph-io/dgraph/blob/2574d6797142d5ac525fdf86b4885d393813e2c2/wiki/content/graphql/subscriptions/index.md#L67)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

I didn't really get this gif.  It's quite long and if I'm coming in part way through, will I be able to understand what's going on?  It might be better as a couple of shorter clips that show one specific point.

...also I wasn't sure about the timeout because what does `reconnect: true,` do ?
</blockquote></details>

split the gif into short clips. reconnect: true reconnect when there is an error in connection. But in our case, JWT already expires then it will continue to give errors even if it reconnects.
___
*[wiki/content/graphql/subscriptions/index.md, line 69 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-MHOP7sB7uOhXIWbLdWn:-MHVnXw36gdbNG-iTqRL:b-ws4gxe) ([raw file](https://github.com/dgraph-io/dgraph/blob/2574d6797142d5ac525fdf86b4885d393813e2c2/wiki/content/graphql/subscriptions/index.md#L69)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

Shouldn't this explicitly say the bits - so for example talk about `connectionParams` ?
</blockquote></details>

changed below.

**Review by MichaelJCompton — APPROVED** [review]
Looks good.

Just one thing.  The gif has examples like "Dgraph bugs" and "Dgraph issues".  I think better for it to say something else.  Even just "Hi from Alice" or something.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-:-MHoJWN98Z2iqbQ1S7Os:b-ionbm7)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @danielmai and @MichaelJCompton)

**Comment by JatinDevDG** [comment]
> Looks good.
> 
> Just one thing. The gif has examples like "Dgraph bugs" and "Dgraph issues". I think better for it to say something else. Even just "Hi from Alice" or something.
> 
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6470#-:-MHoJWN98Z2iqbQ1S7Os:b-ionbm7)_ status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @danielmai and @MichaelJCompton)

changed.

**Pull request merged**
