### PR TITLE
Add support for after and afterN

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/139)

### CODE REVIEW

**Comment by manishrjain** [comment]
Also, can you update the wiki with how to build Flatbuffers?

---

Reviewed 1 of 3 files at r2, 15 of 15 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[task.fbs, line 8 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNf9WfSDPfPXDsxdeSP:-KNf9WfSDPfPXDsxdeSQ:-891302742) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/task.fbs#L8)):*
> ```
> 	count:int;
> 	offset:int;
> 	offsetUid:ulong;
> ```

count and offset makes sense. offsetUid should probably be renamed to `afterUid`.

---

*[gql/parser_test.go, line 209 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNfA-e-v1fpRqyeqTlG:-KNfA-e-v1fpRqyeqTlH:-698742259) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/gql/parser_test.go#L209)):*
> ```Go
> 	}
> }
> ```

Also check for `after`.

---

*[posting/list.go, line 678 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNfA75nowsuc96sV5FA:-KNfA75nowsuc96sV5FB:-276896340) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/posting/list.go#L678)):*
> ```Go
> }
> 
> func (l *List) GetUids(offset, count int, offsetUid uint64) []uint64 {
> ```

afterUid. Also, pass in a struct instead. These params would keep on growing. So, pass a struct with an `Options` suffix.

---

*[posting/list.go, line 705 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNfAZchkDG8kRkK09dt:-KNfAZchkDG8kRkK09du:1520467120) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/posting/list.go#L705)):*
> ```Go
> 	var p types.Posting
> 	if offsetUid > 0 {
> 		offset = sort.Search(l.length(), func(i int) bool {
> ```

This should work even if `offsetUid` isn't present in the list, right? If so, can you please add a comment here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-:-KNfEkBhkd1euNWoqW5G:-1621103667)*

**Comment by ashwin95r** [comment]
Added info on how to get and use flatc.

---

Review status: 9 of 16 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[task.fbs, line 8 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNf9WfSDPfPXDsxdeSP:-KNfvBJ0zQrSfCl4MIMK:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/task.fbs#L8)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> count and offset makes sense. offsetUid should probably be renamed to `afterUid`.
</details>
Done.

---

*[gql/parser_test.go, line 209 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNfA-e-v1fpRqyeqTlG:-KNfxWO7EfLL1L2kiYLb:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/gql/parser_test.go#L209)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Also check for `after`.
</details>
Done.

---

*[posting/list.go, line 678 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNfA75nowsuc96sV5FA:-KNg0pzvMR21lIiP1mac:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/posting/list.go#L678)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> afterUid. Also, pass in a struct instead. These params would keep on growing. So, pass a struct with an `Options` suffix.
</details>
Done.

---

*[posting/list.go, line 705 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNfAZchkDG8kRkK09dt:-KNfw3vm9ho67e0AHMKE:1121868467) ([raw file](https://github.com/dgraph-io/dgraph/blob/625cb715747ff3edc0dc66ceef93c6def3ff02f4/posting/list.go#L705)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should work even if `offsetUid` isn't present in the list, right? If so, can you please add a comment here?
</details>
Yes, it returns the index of the first greater element. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-:-KNg0svyoZbymHAZOlcV:2062864209)*

**Comment by pawanrawal** [comment]
Review status: 9 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[posting/list.go, line 84 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjfAyjUS4FikhNCbtt:-KNjfAyjUS4FikhNCbtu:1525511157) ([raw file](https://github.com/dgraph-io/dgraph/blob/66208d2c27ac2ead5addf0dbda3336545ee61a5a/posting/list.go#L84)):*
> ```Go
> }
> 
> type GetUidsOptions struct {
> ```

Getters section here https://golang.org/doc/effective_go.html says that 
`There's nothing wrong with providing getters and setters yourself, and it's often appropriate to do so, but it's neither idiomatic nor necessary to put Get into the getter's name.`

---

*[posting/list.go, line 696 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjhvdeC7p2SExM1Jnu:-KNjhvdfHVKzKqr27Kzj:-2024325136) ([raw file](https://github.com/dgraph-io/dgraph/blob/66208d2c27ac2ead5addf0dbda3336545ee61a5a/posting/list.go#L696)):*
> ```Go
> 	var p types.Posting
> 	if opt.AfterUid > 0 {
> 		// sort.Search returns the index of the first element > AfterUid
> ```

It returns l.length() if AfterUid > last element. I think our for loop handles that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139)*

**Comment by ashwin95r** [comment]
Review status: 9 of 16 files reviewed at latest revision, 6 unresolved discussions.

---

*[posting/list.go, line 84 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjfAyjUS4FikhNCbtt:-KNjoybz4ggSE1k6Jo8S:1178780559) ([raw file](https://github.com/dgraph-io/dgraph/blob/66208d2c27ac2ead5addf0dbda3336545ee61a5a/posting/list.go#L84)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Getters section here https://golang.org/doc/effective_go.html says that 
> `There's nothing wrong with providing getters and setters yourself, and it's often appropriate to do so, but it's neither idiomatic nor necessary to put Get into the getter's name.`
</details>
Changed to Uids() and UidOptions.

---

*[posting/list.go, line 696 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjhvdeC7p2SExM1Jnu:-KNjjbRhVOO59Qn4UzpM:1896747260) ([raw file](https://github.com/dgraph-io/dgraph/blob/66208d2c27ac2ead5addf0dbda3336545ee61a5a/posting/list.go#L696)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> It returns l.length() if AfterUid > last element. I think our for loop handles that?
</details>
Yeah, the for loop takes care of it (Won't execute)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139)*

**Comment by pawanrawal** [comment]
:lgtm: 

---

Review status: 9 of 16 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-:-KNjqDG3LV3T-rCAdJAD:980077423)*

**Comment by manishrjain** [comment]
Reviewed 4 of 7 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[gql/parser_test.go, line 161 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjrbUP--BxSS1Le_3M:-KNjrbUP--BxSS1Le_3N:-718113366) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/gql/parser_test.go#L161)):*
> ```Go
> 		user(_xid_: m.abcd) {
> 			type.object.name
> 			friends (first: 10, after: 3) {
> ```

Also try a case where After = max UID in the list.

---

*[posting/list.go, line 84 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjqrYmMLtOoRYdtn94:-KNjqrYmMLtOoRYdtn95:1632821576) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/posting/list.go#L84)):*
> ```Go
> }
> 
> type UidsOptions struct {
> ```

Call it ListOptions

---

*[posting/list.go, line 696 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjr1N2j8hVzHXYbA1D:-KNjr1N2j8hVzHXYbA1E:619780704) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/posting/list.go#L696)):*
> ```Go
> 	var p types.Posting
> 	if opt.AfterUid > 0 {
> 		// sort.Search returns the index of the first element > AfterUid
> ```

full stop.

---

*[posting/list.go, line 703 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjrAfuFAl3YEvkSaoE:-KNjrAfuFAl3YEvkSaoF:-1869870763) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/posting/list.go#L703)):*
> ```Go
> 	}
> 	if opt.Count < 0 {
> 		opt.Count = 0 - opt.Count
> ```

You could put the logic in one line: opt.Offset = l.length() + opt.Count

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[gql/parser_test.go, line 161 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjrbUP--BxSS1Le_3M:-KNjutjc_b87BR5QMITb:1992252710) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/gql/parser_test.go#L161)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Also try a case where After = max UID in the list.
</details>
Added it in list_test.

---

*[posting/list.go, line 84 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjqrYmMLtOoRYdtn94:-KNju2I9TvqXKp5CIULS:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/posting/list.go#L84)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Call it ListOptions
</details>
Done.

---

*[posting/list.go, line 696 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjr1N2j8hVzHXYbA1D:-KNju9iRy107CjDfJS6n:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/posting/list.go#L696)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> full stop.
</details>
Done.

---

*[posting/list.go, line 703 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-KNjrAfuFAl3YEvkSaoE:-KNjuQ9ZR8PivwVxIsql:-1005903244) ([raw file](https://github.com/dgraph-io/dgraph/blob/65ddb27631b8af4791c9a49cdf4c5155d9f7ae40/posting/list.go#L703)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You could put the logic in one line: opt.Offset = l.length() + opt.Count
</details>
But the sign of opt.Count wouldn't be negated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139)*

**Comment by manishrjain** [comment]
:lgtm: Nice work!

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/139#-:-KNkFdw2Sk6ty8h_6gYT:764048764)*

**Comment by ashwin95r** [comment]
Merged to develop with commit b6052a0dbb7aeb6c4266ae260f21fbf734c788c6

**Pull request closed without merging**
