### PR TITLE
Add support for aggregator(min) - rough version

### PR DESCRIPTION
**Pull request by squalfof**
Though both 'count' and 'min' belong to Aggregator,  the layer of object on which they applied is different.  'count' performs on Parent layer, while 'min' performs on Leaf Node, for example
```
  director(id: m.06pj8) {
    count(film.director.film)
  }

  director(id: m.06pj8) {
    film.director.film {
    	min(film.film.initial_release_date)
    }
  }
```
Since there is the constraint on 'min' that it must performs on scalar-types.

And the Filter-on-min, keep the filter at the Parent layer instead of at the Leaf layer, for example
```
  director(id: m.06pj8) {
    count(film.director.film @filter(gt(init_release_date, "1990")))
  }

  director(id: m.06pj8) {
    film.director.film @filter(gt(init_release_date, "1990")) {
    	min(film.film.initial_release_date)
    }
  }
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/560)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxnXdj4-1tV-tYuLX9:-KbxnXdj4-1tV-tYuLXA:b-tc4g7p) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L47)):*
> ```Go
> 	Children []*GraphQuery
> 	Filter   *FilterTree
> 	Agrtr    *Function
> ```

Does this need to be a separate field? I think you can put this within the Func field above.

---

*[gql/parser.go, line 1181 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-Kbxnt1vr2cqPUu7l220:-Kbxnt1vr2cqPUu7l221:b-hxeyvt) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L1181)):*
> ```Go
> 				}
> 				isAgrtr = 1
> 				agrtr = item.Val
> ```

No need for special logic in this file, I think; if you use Func as the field for aggregator as well.

---

*[query/query.go, line 402 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoFYvgl4-00UXO3eb:-KbxoFYvgl4-00UXO3ec:b-uc3fkp) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/query/query.go#L402)):*
> ```Go
> 			} else {
> 				if len(gq.Children) > 1 {
> 					note := fmt.Sprintf("Node with aggregator %s cannot have sibling",
> ```

Really? Why not? Also, count, min, max, sum -- are all the same right?

---

*[worker/aggregator.go, line 42 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoXUScuGkX3Z203X-:-KbxoXUScuGkX3Z203X0:bptryvo) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/worker/aggregator.go#L42)):*
> ```Go
> 
> // getValue gets the value from the task.
> func getValue(tv *task.Value) (types.Val, error) {
> ```

Didn't we have such a function before? This conversion can be expensive. Do we need it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by squalfof** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 47 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxnXdj4-1tV-tYuLX9:-Kc2q5ZysEVKAvVIvfDx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L47)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Does this need to be a separate field? I think you can put this within the Func field above.
</blockquote></details>

Done.

---

*[gql/parser.go, line 1181 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-Kbxnt1vr2cqPUu7l220:-Kc5vrVRtNy3OdKY-ke6:bllx9gt) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L1181)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for special logic in this file, I think; if you use Func as the field for aggregator as well.
</blockquote></details>

typical function takes the form like
```
Attr(Function)  => first Item is Attr
```
while for aggregator, form like
```
Aggregator(Attr(Function))  => first Item is Func(Aggrgt), second is Attr
```

The order determines the special logic here.  Thought this is what  you mentioned ?

---

*[query/query.go, line 402 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoFYvgl4-00UXO3eb:-Kc2qAmhs3qpcQsT7z0R:b-vkoi1p) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/query/query.go#L402)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Really? Why not? Also, count, min, max, sum -- are all the same right?
</blockquote></details>

Given min(initial_date) has sibling like name.en, as
```
{
  director(id: m.06pj8) {
    director.film {
    	min(initial_release_date)
    	name.en
    }
  }
}
```
the result will be like (in the current implementation),
note that "initial_release_date" messed with "name.en",
which should not be what we want,

```
"director.film": [
        {
          "initial_release_date": [
            {
              "min": "1964-03-24"
            }
          ],
          "name.en": "Indiana Jones and the Temple of Doom"
        },
        {
          "name.en": "Jaws"
        }
]
```
=> Reason is, both min(date) & name.en are treated as child of director.film,
     they will be encoded into the same JsonNode

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by squalfof** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 402 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoFYvgl4-00UXO3eb:-Kc5zCvFsethb_xZRIl9:b-c0qw3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/query/query.go#L402)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Given min(initial_date) has sibling like name.en, as
```
{
  director(id: m.06pj8) {
    director.film {
    	min(initial_release_date)
    	name.en
    }
  }
}
```
the result will be like (in the current implementation),
note that "initial_release_date" messed with "name.en",
which should not be what we want,

```
"director.film": [
        {
          "initial_release_date": [
            {
              "min": "1964-03-24"
            }
          ],
          "name.en": "Indiana Jones and the Temple of Doom"
        },
        {
          "name.en": "Jaws"
        }
]
```
=> Reason is, both min(date) & name.en are treated as child of director.film,
     they will be encoded into the same JsonNode

</blockquote></details>

No-Sibling-Constraint Eliminated, and modified query.preTraverse(), to separate min(date) & name.en into differnt JsonNode.  With following output,
```
"director.film": [
        {
          "initial_release_date": [
            {
              "min": "1964-03-24"
            }
          ]
        },
        {
          "name.en": "Indiana Jones and the Temple of Doom"
        }
]
```

---

*[worker/aggregator.go, line 42 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoXUScuGkX3Z203X-:-Kc6-BcZZTwPQexKq3K2:b-2sr0kj) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/worker/aggregator.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Didn't we have such a function before? This conversion can be expensive. Do we need it?
</blockquote></details>

Yes, under query-package, we also has this function, however the scope of that function is within-package-scope.  Have one here is by converting to types.Value we could take advantage of existing types.Less().

Assumed this is a conversion from Task.Val -> Types.Value, new object created and value copied, without db I/O, why is this expensive ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by ashwin95r** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 325 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGc0LYxzwoaMclEyjg:-KcGc0LYxzwoaMclEyjh:bsvv7vf) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/query/query.go#L325)):*
> ```Go
> 					continue
> 				}*/
> 				sv, conv_err := tryBestEffortConvert(tv, pc.Attr)
> ```

convErr (camel case)

---

*[query/query.go, line 431 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGhRQHEip-UnGb0SvV:-KcGhRQHEip-UnGb0SvW:b-s005ea) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/query/query.go#L431)):*
> ```Go
> 				// embedded filter will cause ambiguous output like following,
> 				// director.film @filter(gt(initial_release_date, "2016")) {
> 				//    min(initial_release_date @filter(gt(initial_release_date, "1986"))
> ```

Filters are not applied at the value level. but on the parent of the value. So, I'm guessing you have added this as an example case which is wrong?

---

*[worker/task.go, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGk3yoazSpIuu8GHXw:-KcGk3yoazSpIuu8GHXx:b-juk9g0) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/worker/task.go#L211)):*
> ```Go
> 				out.Values = append(out.Values, newValue)
> 			} else {
> 				out.Values[0], _ = Aggregate(q.SrcFunc[0], out.Values[0], newValue, typ)
> ```

You can collect all the values in an array and pass it to Aggregate(). It will reduce the number of conversions to and from types.val.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 250 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGkeLuClx2lbdCZRDt:-KcGkeLuClx2lbdCZRDu:b-w3zker) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/query/query.go#L250)):*
> ```Go
> 				uc := outc.New(pc.Attr)
> 				// convert to attr's type
> 				sv, err := tryBestEffortConvert(pc.values[0], pc.Attr)
> ```

could just be `bestEffortConvert(...)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by squalfof** [comment]
Review status: 4 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 250 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGkeLuClx2lbdCZRDt:-KcHMCKzdTwMBRrjeXoJ:b-yzv150) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/query/query.go#L250)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

could just be `bestEffortConvert(...)`
</blockquote></details>

how about convertWithBestEffort() ?
i just want the first word to be a verb, any other name available ?

---

*[query/query.go, line 325 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGc0LYxzwoaMclEyjg:-KcHMaR3uvjbjSecH9Ee:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/query/query.go#L325)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

convErr (camel case)
</blockquote></details>

Done.

---

*[query/query.go, line 431 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGhRQHEip-UnGb0SvV:-KcLE7F8MYEz9BmTvi0i:b-6hvnyg) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/query/query.go#L431)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Filters are not applied at the value level. but on the parent of the value. So, I'm guessing you have added this as an example case which is wrong?
</blockquote></details>

yes, there is the test named TestMaxError

---

*[worker/task.go, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcGk3yoazSpIuu8GHXw:-KcLEM6rCqIVYjxrs1oU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5b5485829c01680559001131fab1a68abf0afc62/worker/task.go#L211)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

You can collect all the values in an array and pass it to Aggregate(). It will reduce the number of conversions to and from types.val.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 4 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[worker/aggregator.go, line 61 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcM9JXZCbmEY_K9Vo5L:-KcM9JXZCbmEY_K9Vo5M:beemygd) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/worker/aggregator.go#L61)):*
> ```Go
> 
> func Aggregate(agrtr string, values []*task.Value, typ types.TypeID) (*task.Value, error) {
> 	if !couldApplyAgrtrOn(agrtr, typ) {
> ```

canApplyAggregator() this check has already been done at the start of `ProcessTask`. Right? 

---

*[worker/task.go, line 112 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcMAEDJkvGjl3OGiKlQ:-KcMAEDJkvGjl3OGiKlR:btxou6l) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/worker/task.go#L112)):*
> ```Go
> 		case isAgrtr:
> 			// confirm agrregator could apply on the attributes
> 			if !CouldApplyAgrtrOn(f, attr) {
> ```

CanApplyAggregator()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-:-KcM9fLrLUsH-41VVPe6:bnfp4nl)*

**Comment by squalfof** [comment]
Review status: 4 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[worker/aggregator.go, line 61 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcM9JXZCbmEY_K9Vo5L:-KcM_9I7gb55zhqZzwJ1:bmap6j8) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/worker/aggregator.go#L61)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

canApplyAggregator() this check has already been done at the start of `ProcessTask`. Right? 
</blockquote></details>

Yes, since Aggregate() could be accessed outside the worker-package, therefore i eliminate the prerequisite that 
"must call canApplyAggregator() before you call Aggregate()"

---

*[worker/task.go, line 112 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcMAEDJkvGjl3OGiKlQ:-KcMeNrct-cqHGFmmjkG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/worker/task.go#L112)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

CanApplyAggregator()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by manishrjain** [comment]
Reviewed 4 of 7 files at r2, 3 of 3 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1181 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-Kbxnt1vr2cqPUu7l220:-KcMc9-87rpk8R6iOMTH:b-6xq8in) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L1181)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

typical function takes the form like
```
Attr(Function)  => first Item is Attr
```
while for aggregator, form like
```
Aggregator(Attr(Function))  => first Item is Func(Aggrgt), second is Attr
```

The order determines the special logic here.  Thought this is what  you mentioned ?
</blockquote></details>

Not sure what you mean. Still think you don't need this special logic.

---

*[gql/parser.go, line 110 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcMbauLAh4qvfR_IXLc:-KcMbauLAh4qvfR_IXLd:b-q428n) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/gql/parser.go#L110)):*
> ```Go
> }
> 
> func (f *Function) IsAgrtr() bool {
> ```

IsAggregator. Use full forms if the short form isn't popular.

---

*[query/query.go, line 402 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoFYvgl4-00UXO3eb:-KcMeJATdeNZfRuS5PJM:btscpqs) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/query/query.go#L402)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

No-Sibling-Constraint Eliminated, and modified query.preTraverse(), to separate min(date) & name.en into differnt JsonNode.  With following output,
```
"director.film": [
        {
          "initial_release_date": [
            {
              "min": "1964-03-24"
            }
          ]
        },
        {
          "name.en": "Indiana Jones and the Temple of Doom"
        }
]
```
</blockquote></details>

None of these look right. Why not do this:

```
"director.film": [
  {
    "min(initial_release_date)": "1964-03-24",
    "name.en": "indiana Jones ..."
  },
]
```

---

*[query/query.go, line 121 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcMd2cndydpF7GHhDOi:-KcMd2cndydpF7GHhDOj:b949guh) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/query/query.go#L121)):*
> ```Go
> 	Offset     int
> 	AfterUID   uint64
> 	Agrtr      string
> ```

Shouldn't this go to SrcFunc?

---

*[worker/aggregator.go, line 42 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoXUScuGkX3Z203X-:-KcMefW9kmd59BbfANBn:b-rdolv) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/worker/aggregator.go#L42)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Yes, under query-package, we also has this function, however the scope of that function is within-package-scope.  Have one here is by converting to types.Value we could take advantage of existing types.Less().

Assumed this is a conversion from Task.Val -> Types.Value, new object created and value copied, without db I/O, why is this expensive ?

</blockquote></details>

This is expensive, because it needs to be done for every value item in all posting lists that we touch. We'll be spending CPU cycles doing blob copies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by squalfof** [comment]
Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1181 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-Kbxnt1vr2cqPUu7l220:-KcNluwdSoixsidJjcXn:b-cc86hs) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L1181)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not sure what you mean. Still think you don't need this special logic.
</blockquote></details>

Sorry i didn't make it clear.  In previous solution,  'count' belongs to aggregator, and it may contain filter, like
```
count(director.film @filter(gt("initial_release_date", "1980")))
```
having @filter involved, i can't just use parseFunction() to parse it.  
In order to support 'count', only that special logic could handle.

---

*[gql/parser.go, line 110 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcMbauLAh4qvfR_IXLc:-KcNT7JxI_AbsnMy5xru:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/gql/parser.go#L110)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

IsAggregator. Use full forms if the short form isn't popular.
</blockquote></details>

Done.

---

*[query/query.go, line 402 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoFYvgl4-00UXO3eb:-KcNRR_amL1DGtwhg0Kd:bl7yc2u) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/query/query.go#L402)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

None of these look right. Why not do this:

```
"director.film": [
  {
    "min(initial_release_date)": "1964-03-24",
    "name.en": "indiana Jones ..."
  },
]
```

</blockquote></details>

I guess what you want is
```
"director.film": [
  {
    "min(initial_release_date)": "1964-03-24"
  },
  {
    "name.en": "indiana Jones ..."
  },
  {
    "name.en": "Jaws"
  },
  ...
]
```
since there is a list of name.en, not only one name.en

---

*[query/query.go, line 121 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcMd2cndydpF7GHhDOi:-KcNrkjHIiBo_oYO571s:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d657479afd6ab0e54f5afcdf89dd960509153da/query/query.go#L121)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Shouldn't this go to SrcFunc?
</blockquote></details>

Done.

---

*[worker/aggregator.go, line 42 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KbxoXUScuGkX3Z203X-:-KcNshbyAjRpO9gnbeWy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/worker/aggregator.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This is expensive, because it needs to be done for every value item in all posting lists that we touch. We'll be spending CPU cycles doing blob copies.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by squalfof** [comment]
Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1181 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-Kbxnt1vr2cqPUu7l220:-KcNtH_d7F5HcUdSyvbO:b-utja71) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L1181)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Sorry i didn't make it clear.  In previous solution,  'count' belongs to aggregator, and it may contain filter, like
```
count(director.film @filter(gt("initial_release_date", "1980")))
```
having @filter involved, i can't just use parseFunction() to parse it.  
In order to support 'count', only that special logic could handle.
</blockquote></details>

Anyway, have separated 'count' with aggregator.  No special logic for aggregator now, just parseFunction()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by squalfof** [comment]
Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1181 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-Kbxnt1vr2cqPUu7l220:-KcNtkMwtvRNYcsLwg8I:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/454cbd67ae7b34b30cc900e5c378db7177021b79/gql/parser.go#L1181)):*
<details><summary><i>Previously, squalfof (KG.Xu) wrote…</i></summary><blockquote>

Anyway, have separated 'count' with aggregator.  No special logic for aggregator now, just parseFunction()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 300 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQp6guWdg9HTtMP65D:-KcQp6guWdg9HTtMP65E:b-qpc1jf) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/query/query.go#L300)):*
> ```Go
> 				// globalType is the best effort type to which we try converting
> 				// and if not possible, we ignore it in the result.
> 				/*globalType, hasType := schema.TypeOf(pc.Attr)
> ```

Don't comment out code. Delete it.

---

*[query/query_test.go, line 751 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQckmLK9Zqb8uJY-_7:-KcQckmLK9Zqb8uJY-_8:bx2fiww) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/query/query_test.go#L751)):*
> ```Go
> 				alive
> 				min(friend) {
>                                     name     
> ```

Identation and extra whitespace at the end.

We should be able to catch this while parsing, no? 

---

*[worker/aggregator.go, line 11 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQdoRh5ca8ySnNPvoT:-KcQdoRh5ca8ySnNPvoU:b-y5wer2) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/aggregator.go#L11)):*
> ```Go
> 
> 
> func CouldApplyAgrtrOn(agrtr string, typ types.TypeID) bool {
> ```

ApplyAggregatorOn(..)

---

*[worker/aggregator.go, line 88 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQkjkofYABWEw3beXD:-KcQkjkofYABWEw3beXE:bydq8d9) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/aggregator.go#L88)):*
> ```Go
> 			result = iter
> 			if lva, err = convertTo(iter, typ); err != nil {
> 				return result, err
> ```

return? Can't we just ignore this value?

---

*[worker/task.go, line 179 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQmqkK4QdAhkz5Vlga:-KcQmqkLf_iBX8P7KkRm:bbl4ww2) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/task.go#L179)):*
> ```Go
> 		var key []byte
> 		if isAgrtr {
> 			key = x.DataKey(attr, q.Uids[i])
> ```

This condition shouldn't be necessary.

---

*[worker/task.go, line 224 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQnEZwcqrMkG4M7ZUq:-KcQnEZx5u6NsJyF0HxT:b-ghy934) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/task.go#L224)):*
> ```Go
> 		var err error
> 		typ, _ := schema.TypeOf(attr)
> 		out.Values[0], err = Aggregate(f, out.Values, typ)
> ```

After this, shouldn't we trim the length of out.Values?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-:-KcQpNu_6gyU9q7-mOzI:bnfp4nl)*

**Comment by squalfof** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 300 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQp6guWdg9HTtMP65D:-KcQuHSI6F9MqPDBRg28:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/query/query.go#L300)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't comment out code. Delete it.
</blockquote></details>

Done.

---

*[query/query_test.go, line 751 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQckmLK9Zqb8uJY-_7:-KcQuU7QA33N3fYakbCI:b9vfwdk) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/query/query_test.go#L751)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Identation and extra whitespace at the end.

We should be able to catch this while parsing, no? 
</blockquote></details>

Didn't realize it. 
Done.

---

*[worker/aggregator.go, line 11 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQdoRh5ca8ySnNPvoT:-KcRRCJ2Cvk514QFuZiE:bq4wdzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/aggregator.go#L11)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ApplyAggregatorOn(..)
</blockquote></details>

Full name.
Done.

---

*[worker/aggregator.go, line 88 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQkjkofYABWEw3beXD:-KcQxYaPzRAwdtsqpMA-:b-4127b8) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/aggregator.go#L88)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return? Can't we just ignore this value?
</blockquote></details>

Much better. Done.

---

*[worker/task.go, line 179 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQmqkK4QdAhkz5Vlga:-KcRPOCsUc-Y2bam4GOB:bklhlij) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/task.go#L179)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This condition shouldn't be necessary.
</blockquote></details>

Without this condition, data flow into branch useFunc, which will take attr as index
```
key = x.IndexKey(attr, tokens[i]
```
while here min/max/sum may be applied on non-index scalar type
```
key = x.DataKey(attr,  q.Uids[i])
```

---

*[worker/task.go, line 224 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/560#-KcQnEZwcqrMkG4M7ZUq:-KcRP1y2RsUqXEqfVuUu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e53ce1899cb6ac6d1ca04a47070f27b8ce7bce77/worker/task.go#L224)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

After this, shouldn't we trim the length of out.Values?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/560)*

**Pull request closed without merging**
