### PR TITLE
Support mathematical functions on value variables

### PR DESCRIPTION
**Pull request by ashwin95r**
Queries like:
```
{
	var(func:allofterms(name, "steven spielberg")) {
		name@en
		films as director.film {
			p as count(starring)
			score as conditional(gt(p, 80), 10, 1)
		}
	}

	TopMovies(id: var(films), orderdesc: var(score), first: 5, offset:10) {
		name@en
                var(p)
		var(score)
	}
}
```

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/799)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[gql/math.go, line 45 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu5sJ0-deWcAiVCdw0:-Kgu5sJ0-deWcAiVCdw1:bk9bjv8) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/gql/math.go#L45)):*
> ```Go
> 		if item.Typ == itemRightRound {
> 			if expectedArg {
> 				return nil, x.Errorf("Missing arg after comma")
> ```

Error msg is confusing for unary function.

---

*[gql/parser.go, line 1756 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu2zpZKWZ9oozMdlFZ:-Kgu2zpZKWZ9oozMdlF_:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/gql/parser.go#L1756)):*
> ```Go
> func isValVarFunc(name string) bool {
> 	return name == "sumvar" || name == "diffvar" || name == "mulvar" || name == "log" || name == "exp" ||
> 		name == "conditional" || name == "maxvar" || name == "minvar" || name == "conditional" ||
> ```

100 chars

---

*[query/aggregator.go, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu8Yc_vyMxuwjwbdV0:-Kgu8Yc_vyMxuwjwbdV1:bpp1odi) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/aggregator.go#L75)):*
> ```Go
> 		if va.Tid == types.IntID {
> 			va.Tid = types.FloatID
> 			va.Value = float64(va.Value.(int64))
> ```

Is this under the assumption that in compare value functions, one of the argument would be always constant float ??

---

*[query/aggregator.go, line 83 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu7qbewjRSCFpMGTJt:-Kgu7qbfjIspD-tmzE_H:b-mlpn74) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/aggregator.go#L83)):*
> ```Go
> 		}
> 	}
> 	isMore, err := types.Less(vb, va)
> ```

Instead of checking for both isLess and isMore, can we refactor our types.less to return whether it's equal, less or greater.

---

*[query/aggregator.go, line 288 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu6xf-9R1GPo9ARzKH:-Kgu6xf-9R1GPo9ARzKI:bx9cpyw) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/aggregator.go#L288)):*
> ```Go
> 	ag.divideByCount()
> 	if ag.result.Tid == types.FloatID {
> 		if math.IsInf(ag.result.Value.(float64), 1) {
> ```

Should we return maxfloat instead of infinity ?  should we  return maxfloat64 for log(0) ?

---

*[query/query.go, line 863 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-KguAthS0nZUL-HwgbrJ:-KguAthT9326mdw4cRWN:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/query.go#L863)):*
> ```Go
> 	aggName := mNode.Fn
> 	if isUnary(aggName) && len(mNode.Child) != 1 {
> 		return x.Errorf("Function %v expects 1 argument. But got: %v", aggName, len(mNode.Child))
> ```

100 chars

---

*[query/query_test.go, line 640 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-KgtM2Pu74d7bQTZykxt:-KgtM2Pu74d7bQTZykxu:b-88zysn) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/query_test.go#L640)):*
> ```Go
> 	js := processToFastJSON(t, query)
> 	require.JSONEq(t,
> 		`{"info":[{"friend":[{"age":15,"friend":[{"count":1}],"var(sum)":16},{"age":15,"friend":[{"count":0}],"var(sum)":15},{"age":17,"friend":[{"count":0}],"var(sum)":17},{"age":19,"friend":[{"count":1}],"var(sum)":20},{"friend":[{"count":0}]}]}],"me":[{"age":19,"friend":[{"count":1}],"name":"Andrea"},{"age":17,"friend":[{"count":0}],"name":"Daryl Dixon"},{"age":15,"friend":[{"count":1}],"name":"Rick Grimes"},{"age":15,"friend":[{"count":0}],"name":"Glenn Rhee"}]}`,
> ```

Why not var[sum] instead of var(sum) ?

---

*[types/sort.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-KgtKOi3j8aMZFn6QPWa:-KgtKOi3j8aMZFn6QPWb:bfch3xz) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/types/sort.go#L48)):*
> ```Go
> func (s byValue) Less(i, j int) bool {
> 	if s.values[i].Tid != s.values[j].Tid {
> 		return false
> ```

We should probably throw an error instead of returning false we don't support  comparing on different value types(like int and float).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/799)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1756 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu2zpZKWZ9oozMdlFZ:-Kh1KwoiG8dms6SqVXdA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/gql/parser.go#L1756)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.

---

*[query/aggregator.go, line 288 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu6xf-9R1GPo9ARzKH:-Kh1L4mbw2BDMjdMwDgG:bwpw0th) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/aggregator.go#L288)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Should we return maxfloat instead of infinity ?  should we  return maxfloat64 for log(0) ?
</blockquote></details>

Yeah we do reutrn MaxFloat for inf.

---

*[query/query.go, line 863 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-KguAthS0nZUL-HwgbrJ:-Kh1LNkKqXIVK3btNGCq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/query.go#L863)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.

---

*[query/query_test.go, line 640 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-KgtM2Pu74d7bQTZykxt:-Kh1LeSARLW55UH6phqn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/query_test.go#L640)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Why not var[sum] instead of var(sum) ?
</blockquote></details>

Done.

---

*[types/sort.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-KgtKOi3j8aMZFn6QPWa:-Kh1LgtGImWcslTiLy4f:b-tuohgc) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/types/sort.go#L48)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We should probably throw an error instead of returning false we don't support  comparing on different value types(like int and float).
</blockquote></details>

We cant do it in sort interface. Maybe we should check before calling the sort.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/799)*

**Comment by ashwin95r** [comment]
Addressing the comments in the other PR.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-:-Kh1LvgtjfihryK6EgLY:b-v3j9ni)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/aggregator.go, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/799#-Kgu8Yc_vyMxuwjwbdV0:-Kh1UvNd6BcIFXi6uAOd:b2dywgl) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a48d3280b92ff2a9bad94a070a339c2d9dff2cb/query/aggregator.go#L75)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Is this under the assumption that in compare value functions, one of the argument would be always constant float ??
</blockquote></details>

Ah nope, if the err was returned, it means the type was different. and the only possible case where we can  still compare is if one of them was int and the oher a float. So, we just convert the int to float.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/799)*

**Comment by ashwin95r** [comment]
Continued in #812

**Pull request closed without merging**
