### PR TITLE
Adding TODO: badge

### PR DESCRIPTION
**Pull request by ghost**
https://dgraph.atlassian.net/browse/OSS-635

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5360)

### CODE REVIEW

**Comment by kath-at-dgraph** [comment]
Related to https://github.com/dgraph-io/dgraph/issues?q=5347

**Review by MichelDiz — APPROVED** [review]

**Comment by MichelDiz** [comment]
@skrdgraph can we squash this? it is a minor thing.
This user was a contractor who deleted her account. So Github calls deleted accounts "Ghost".

We can also delete it and copy paste the content. Or simply ignore it, as it is just a badger.

**Comment by skrdgraph** [comment]
I wanted to get this in as well ... this is a good tool for open source contributors to look at .. and make relevant contributions.

Lets get this in.

**Review by skrdgraph — APPROVED** [review]

**Comment by MichelDiz** [comment]
Just an update, I found a duplicate with a real person https://github.com/dgraph-io/dgraph/pull/5698 But he didn't signed the CLA. And also pointing to Master.

**Pull request closed without merging**
