### PR TITLE
Add checkpoint support for dgraphloader

### PR DESCRIPTION
**Pull request by pawanrawal**
Our each batch request has RDF's from different files and with non-sequential line numbers. So we need watermarks to keep track of the last line number for each file that the server has processed. 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1174)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/mutations.go, line 315 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KokVG9B76N_snORgxx5:-KokVG9C6Q0JmTlYHXHy:buk5ezn) ([raw file](https://github.com/dgraph-io/dgraph/blob/44926ec1918df266bd2ec7f4632df9ea1665d96c/client/mutations.go#L315)):*
> ```Go
> 		entry.mark.Ch <- x.Mark{Index: entry.line, Done: true}
> 	}
> 	req.entries = req.entries[:0]
> ```

move this inside reset

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KokVk3TCU9ks-BFGODZ:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/mutations.go, line 315 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KokVG9B76N_snORgxx5:-KoknszhKrslqxYGtnn3:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/44926ec1918df266bd2ec7f4632df9ea1665d96c/client/mutations.go#L315)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

move this inside reset
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174)*

**Comment by manishrjain** [comment]
Please don't submit, until profiling is done on this change. Sounds expensive CPU wise.

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/checkpoint.go, line 46 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot3EpLnfpCBIRAZ79Q:-Kot3EpMJQWGEDywK_yK:b-cb95gk) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/checkpoint.go#L46)):*
> ```Go
> 
> 		for file, w := range m {
> 			buf := make([]byte, 10)
> ```

var byte[10] buf

---

*[client/checkpoint.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot3n0MlaB395l7zFVA:-Kot3n0MlaB395l7zFVB:b-6ya13m) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/checkpoint.go#L63)):*
> ```Go
> 
> type syncMarks struct {
> 	sync.RWMutex
> ```

Why not create all the entries upfront, and avoid all this locking around this map here?

---

*[client/checkpoint.go, line 98 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot48DYZqHszW-g82BU:-Kot48DZgO0KEtl1_Kgo:b-srs6cs) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/checkpoint.go#L98)):*
> ```Go
> }
> 
> func (g *syncMarks) watermarks() map[string]uint64 {
> ```

You don't really need this map. You can just call DoneUntil() directly when iterating over the files.

---

*[client/mutations.go, line 313 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot5PuFqcZ_MQCvS0e_:-Kot5PuFqcZ_MQCvS0ea:b8sr2r4) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/mutations.go#L313)):*
> ```Go
> 	for _, entry := range req.entries {
> 		// Mark watermarks as done.
> 		entry.mark.Ch <- x.Mark{Index: entry.line, Done: true}
> ```

This might be very slow because it's done per line per file. We should do it at a request level, instead of at a line level. But, that'd require changing how we create a request.

Can you profile how much slower this makes our loader. If it doesn't, then this approach is good. But, I feel this would peg our cpu pretty hard.

---

*[client/mutations.go, line 385 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot6FmX00HXg1COCxVj:-Kot6FmX00HXg1COCxVk:b-cygd3c) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/mutations.go#L385)):*
> ```Go
> 	}
> 	if len(file) > 0 && line != 0 {
> 		sm.Ch <- x.Mark{Index: line}
> ```

Can you check how much slower this makes our loader?

---

*[cmd/dgraphloader/.gitignore, line 2 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot6OlzwAFoBP9lX11F:-Kot6OlzwAFoBP9lX11G:b-7iwvb8) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/cmd/dgraphloader/.gitignore#L2)):*
> ```
> /dgraphloader
> c
> ```

this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-Kot7Xai1hBT9p95R-r6:bmhmsk5)*

**Comment by pawanrawal** [comment]
Benchmarking loader performance on i3 now. Will report the numbers in an hour.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KoyllnaZK2yz5lKUCLo:b-3wefgd)*

**Comment by pawanrawal** [comment]
Tried loading 42 Million RDF's

Before the change it took 15m45s, after the change it took 17m. Will make other changes suggested and see if that improves the performance.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KozF-v2PoS-pay0czSM:b-ooprze)*

**Comment by manishrjain** [comment]
What we could do is to break up rpcs, so that each rpc holds updates from only one file. That way, we can then watermark only one line number per rpc. This would be a lot cheaper operation.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KpIV4BwuAL_pVsG6t0x:bfej9gc)*

**Comment by pawanrawal** [comment]
yeah, that should work. I will make this change, update the numbers and the PR by tomorrow.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/.gitignore, line 2 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot6OlzwAFoBP9lX11F:-KozUXXI3fiQAZ7xSkdA:b-tlv419) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/cmd/dgraphloader/.gitignore#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

this?
</blockquote></details>

It's the directory used by badger.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KpJtMIc6Uz0KPWlQ-u2:b-q3yz1q)*

**Comment by pawanrawal** [comment]
We now batch edges in dgraphloader and send them to the client. This makes sure that a batch only contains edges from one file. Now we can emit just one watermark per request. After this change, the loader doesn't take any more time than it used to previously.

---

Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/checkpoint.go, line 46 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot3EpLnfpCBIRAZ79Q:-KpO_JHDZrQH_eO8ungg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/checkpoint.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

var byte[10] buf
</blockquote></details>

Done.

---

*[client/checkpoint.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot3n0MlaB395l7zFVA:-KpOW_ITs9b32iHuxh7T:b-6oiydf) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/checkpoint.go#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why not create all the entries upfront, and avoid all this locking around this map here?
</blockquote></details>

I do so in NewSyncMarks now.

---

*[client/checkpoint.go, line 98 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot48DYZqHszW-g82BU:-KpO_TYh7rxgydO35tnO:ba3dfob) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/checkpoint.go#L98)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't really need this map. You can just call DoneUntil() directly when iterating over the files.
</blockquote></details>

Removed

---

*[client/mutations.go, line 313 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot5PuFqcZ_MQCvS0e_:-KpO_W8asqkGghHqGDvh:b-q13778) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/mutations.go#L313)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This might be very slow because it's done per line per file. We should do it at a request level, instead of at a line level. But, that'd require changing how we create a request.

Can you profile how much slower this makes our loader. If it doesn't, then this approach is good. But, I feel this would peg our cpu pretty hard.
</blockquote></details>

It doesn't increase the time for the loader anymore. It finishes 5-10s before/after. Doing it per request now.

---

*[client/mutations.go, line 385 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-Kot6FmX00HXg1COCxVj:-KpO_rC0rPJzYo7tAAw0:b6z2se2) ([raw file](https://github.com/dgraph-io/dgraph/blob/71ae5842c47d119d3e19b4e59c65db134346c800/client/mutations.go#L385)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can you check how much slower this makes our loader?
</blockquote></details>

Not slow anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KpOc8BcUh0yU8onr-p8:b-8o6qfw)*

**Comment by manishrjain** [comment]
Some more comments. Will do a final review once you address.

---

Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/checkpoint.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSMyzurod2S34aCqSV:-KpSMyzurod2S34aCqSW:b-tqkz39) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L35)):*
> ```Go
> func (d *Dgraph) NewSyncMarks(files []string) {
> 	for _, file := range files {
> 		bp := filepath.Base(file)
> ```

Don't you need to add an extension? Or, ensure that the filename generated is not going to overwrite the current file.

---

*[client/checkpoint.go, line 45 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNHoeRvxREx_1ZPpG:-KpSNHoeRvxREx_1ZPpH:bc9e5mn) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L45)):*
> ```Go
> }
> 
> // This is called to syncAllMarks. It is useful to find the final line that was processed for each
> ```

"This is called to syncAllMarks" -- not clear what you're saying.

---

*[client/checkpoint.go, line 49 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNF2hMlxvAbkHZFf4:-KpSNF2hMlxvAbkHZFf5:bffhzvc) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L49)):*
> ```Go
> func (d *Dgraph) syncAllMarks() {
> 	for _, mark := range d.marks {
> 		for mark.WaitingFor() {
> ```

Not sure what this loop does.

---

*[client/checkpoint.go, line 60 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNcOtRvB0WHsCh9Mj:-KpSNcOtRvB0WHsCh9Mk:brgufdn) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L60)):*
> ```Go
> 	for file, mark := range d.marks {
> 		w := mark.DoneUntil()
> 		if w == 0 {
> ```

You could also track the last one. If it's the same as the last one, no need to write again.

---

*[client/checkpoint.go, line 83 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSJE9ussGbuMwn1o5b:-KpSJE9ussGbuMwn1o5c:b3ps3jk) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L83)):*
> ```Go
> 	defer ticker.Stop()
> 
> 	for range ticker.C {
> ```

Who will stop this loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KpSO7r7l82WibhqzG16:b-mxqvkk)*

**Comment by pawanrawal** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/checkpoint.go, line 35 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSMyzurod2S34aCqSV:-KpSqBQTTa1sUIN_G99I:b89y1ye) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't you need to add an extension? Or, ensure that the filename generated is not going to overwrite the current file.
</blockquote></details>

I am using absolute path now which is with extension.

---

*[client/checkpoint.go, line 45 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNHoeRvxREx_1ZPpG:-KpSomrqqI2fbUaiOgPG:b3hqk53) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L45)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

"This is called to syncAllMarks" -- not clear what you're saying.
</blockquote></details>

Updated the comment to clarify.

---

*[client/checkpoint.go, line 49 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNF2hMlxvAbkHZFf4:-KpSoht0ALmg1KRTafrp:b-t5s4op) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L49)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not sure what this loop does.
</blockquote></details>

We are waiting for all watermarks to be processed.

---

*[client/checkpoint.go, line 60 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNcOtRvB0WHsCh9Mj:-KpSh-VXW86U_JJVzCPe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L60)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You could also track the last one. If it's the same as the last one, no need to write again.
</blockquote></details>

Done.

---

*[client/checkpoint.go, line 83 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSJE9ussGbuMwn1o5b:-KpSh02S1lpRua-2dMRz:b7dmdm7) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L83)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Who will stop this loop?
</blockquote></details>

I should, doing now in Flush.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174)*

**Comment by manishrjain** [comment]
:lgtm: Few more comments.

---

Reviewed 1 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/checkpoint.go, line 49 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNF2hMlxvAbkHZFf4:-KpVfZYfg31mjaeXDbWn:b-ckhid6) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L49)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We are waiting for all watermarks to be processed.
</blockquote></details>

You probably need to do it exactly once. Just put this logic where you need it directly. It would be more clear there.

---

*[client/checkpoint.go, line 102 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpVgExQbW4QHHYzpfbC:-KpVgExQbW4QHHYzpfbD:bvw0q22) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9388c235ec476d0333ae874105cc56f85ed4555/client/checkpoint.go#L102)):*
> ```Go
> 
> // Used to store checkpoints for various files periodically.
> func (d *Dgraph) storeCheckpoint(ticker *time.Ticker) {
> ```

writeCheckpoinPeriodically. But, this func is so simple, there's no need to have a separate one. Just use func() in the place where you call it directly.

---

*[client/mutations.go, line 333 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpVhaTQ2zJmHR8nujc_:-KpVhaTQ2zJmHR8nujca:b-nnkx76) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9388c235ec476d0333ae874105cc56f85ed4555/client/mutations.go#L333)):*
> ```Go
> 
> func (d *Dgraph) makeSchemaRequests() {
> 	var req Req
> ```

Why this change? This needs to be allocated on heap, because it's crossing function boundaries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-:-KpViQZT4_6SAU_6RmyT:b6epxqe)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/checkpoint.go, line 49 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpSNF2hMlxvAbkHZFf4:-KpXWRQ9-xCFmTzCXUdW:b-4q9e2g) ([raw file](https://github.com/dgraph-io/dgraph/blob/08777ec6c35a5fd9b4f2209d6da9cfa8e18019f1/client/checkpoint.go#L49)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You probably need to do it exactly once. Just put this logic where you need it directly. It would be more clear there.
</blockquote></details>

Right, needs to be only done once.  Calling it BatchFlush.

---

*[client/checkpoint.go, line 102 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpVgExQbW4QHHYzpfbC:-KpXW4wz_QqC-aAnrK_U:b-t76g8u) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9388c235ec476d0333ae874105cc56f85ed4555/client/checkpoint.go#L102)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

writeCheckpoinPeriodically. But, this func is so simple, there's no need to have a separate one. Just use func() in the place where you call it directly.
</blockquote></details>

Removed this and calling it inline.

---

*[client/mutations.go, line 333 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpVhaTQ2zJmHR8nujc_:-KpXZ6TtKo-AZ9MwqBd-:b61xews) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9388c235ec476d0333ae874105cc56f85ed4555/client/mutations.go#L333)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why this change? This needs to be allocated on heap, because it's crossing function boundaries.
</blockquote></details>

I did an escape analysis which showed me it doesn't escape and hence should be allocated on stack.
```
../../client/mutations.go:341: (*Dgraph).makeSchemaRequests req does not escape
../../client/mutations.go:344: (*Dgraph).makeSchemaRequests req does not escape
../../client/mutations.go:355: (*Dgraph).makeSchemaRequests req does not escape
```
As far as I know go passes a copy of the `r` to the channel. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/mutations.go, line 333 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174#-KpVhaTQ2zJmHR8nujc_:-KpXe7IDnOyHvEX06ddo:b-da5pxi) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9388c235ec476d0333ae874105cc56f85ed4555/client/mutations.go#L333)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I did an escape analysis which showed me it doesn't escape and hence should be allocated on stack.
```
../../client/mutations.go:341: (*Dgraph).makeSchemaRequests req does not escape
../../client/mutations.go:344: (*Dgraph).makeSchemaRequests req does not escape
../../client/mutations.go:355: (*Dgraph).makeSchemaRequests req does not escape
```
As far as I know go passes a copy of the `r` to the channel. 
</blockquote></details>

Ok I see it finally escapes to heap while calling `request`.
```
../../client/mutations.go:297: moved to heap: req
```
Reverting this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1174)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
