### PR TITLE
Retain memory info from Alloc, fix pointer issue in merge

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/187)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraphmerge/main.go, line 137 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_MoIO0zzDFr12n7nk:-KQ_MoIP_IF5zA0ABhhT:bj9zmoo) ([raw file](https://github.com/dgraph-io/dgraph/blob/78aa783a2467c55bdb00a4cbf81ec52413143bce/cmd/dgraphmerge/main.go#L137)):*
> ```Go
> 		}
> 		copy(lastKey, top.key)
> ```

Also, lastKey = lastKey[0:len(top.key)]; otherwise, you get extra bytes hanging out towards the end of the slice.

---

*[cmd/dgraphmerge/main.go, line 142 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_MxRjoZzdHZqr4QHI:-KQ_MxRjoZzdHZqr4QHJ:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/78aa783a2467c55bdb00a4cbf81ec52413143bce/cmd/dgraphmerge/main.go#L142)):*
> ```Go
> 		}
> 		copy(lastValue, top.value)
> ```

Same here.

---

*[posting/lists.go, line 184 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_N-eda_D4QbUTOvUH:-KQ_N-eda_D4QbUTOvUI:b4iu8iu) ([raw file](https://github.com/dgraph-io/dgraph/blob/78aa783a2467c55bdb00a4cbf81ec52413143bce/posting/lists.go#L184)):*
> ```Go
> 	megs := ms.Alloc / (1 << 20)
> 	return int(megs)
> ```

Add a TODO, and mark this as a temporary hack. Specify why we're sticking to ms.Alloc for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/dgraphmerge/main.go, line 137 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_MoIO0zzDFr12n7nk:-KQ_ODLDndHRnQyKG7Je:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/78aa783a2467c55bdb00a4cbf81ec52413143bce/cmd/dgraphmerge/main.go#L137)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Also, lastKey = lastKey[0:len(top.key)]; otherwise, you get extra bytes hanging out towards the end of the slice.
</details>
Done.

---

*[cmd/dgraphmerge/main.go, line 142 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_MxRjoZzdHZqr4QHI:-KQ_OE-yGOVmNJsR2TaM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/78aa783a2467c55bdb00a4cbf81ec52413143bce/cmd/dgraphmerge/main.go#L142)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Same here.
</details>
Done.

---

*[posting/lists.go, line 184 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_N-eda_D4QbUTOvUH:-KQ_Phm8-mYFPCY1mm3b:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/78aa783a2467c55bdb00a4cbf81ec52413143bce/posting/lists.go#L184)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a TODO, and mark this as a temporary hack. Specify why we're sticking to ms.Alloc for now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphmerge/main.go, line 133 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_SI2U0psMd-3kgiQv:-KQ_SI2U0psMd-3kgiQw:bnqe23w) ([raw file](https://github.com/dgraph-io/dgraph/blob/ff406c177cb751f3098bb272ea24358259fbd067/cmd/dgraphmerge/main.go#L133)):*
> ```Go
> 		}
> 
> 		if len(lastKey) < len(top.key) {
> ```

check cap of lastKey, instead of len. https://blog.golang.org/go-slices-usage-and-internals

---

*[cmd/dgraphmerge/main.go, line 137 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_SKNDOjOpiKeT5FyV:-KQ_SKNDOjOpiKeT5FyW:b-5up8j4) ([raw file](https://github.com/dgraph-io/dgraph/blob/ff406c177cb751f3098bb272ea24358259fbd067/cmd/dgraphmerge/main.go#L137)):*
> ```Go
> 		}
> 		copy(lastKey, top.key)
> 		lastKey = lastKey[:len(top.key)]
> ```

Move this before copy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphmerge/main.go, line 133 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_SI2U0psMd-3kgiQv:-KQ_TY-ZWHS_g_vi5SlR:b-v37m47) ([raw file](https://github.com/dgraph-io/dgraph/blob/ff406c177cb751f3098bb272ea24358259fbd067/cmd/dgraphmerge/main.go#L133)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> check cap of lastKey, instead of len. https://blog.golang.org/go-slices-usage-and-internals
</details>
I think even if cap of lastKey is 100, but len is 10 and len of top.key is 20, only 10 elements would be copied. 

https://golang.org/pkg/builtin/#copy

---

*[cmd/dgraphmerge/main.go, line 137 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_SKNDOjOpiKeT5FyV:-KQ_UB8XWPa9e-fc2OoZ:bryubw3) ([raw file](https://github.com/dgraph-io/dgraph/blob/ff406c177cb751f3098bb272ea24358259fbd067/cmd/dgraphmerge/main.go#L137)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Move this before copy.
</details>
Is there an advantage to moving it before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphmerge/main.go, line 133 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_SI2U0psMd-3kgiQv:-KQ_e8YiK3JE_yHdsOsy:bsmnlk6) ([raw file](https://github.com/dgraph-io/dgraph/blob/ff406c177cb751f3098bb272ea24358259fbd067/cmd/dgraphmerge/main.go#L133)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> I think even if cap of lastKey is 100, but len is 10 and len of top.key is 20, only 10 elements would be copied. 
> 
> https://golang.org/pkg/builtin/#copy
</details>
I think the point here is that if the cap of lastKey > len(top.key), you don't need to allocate lastKey again because it can store top.Key. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphmerge/main.go, line 133 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_SI2U0psMd-3kgiQv:-KQ_gqdZgbmCSqggB4Wf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ff406c177cb751f3098bb272ea24358259fbd067/cmd/dgraphmerge/main.go#L133)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I think the point here is that if the cap of lastKey > len(top.key), you don't need to allocate lastKey again because it can store top.Key. 
</details>
Done.

---

*[cmd/dgraphmerge/main.go, line 137 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-KQ_SKNDOjOpiKeT5FyV:-KQ_gi15hmJNWP4EI7HR:bigino2) ([raw file](https://github.com/dgraph-io/dgraph/blob/ff406c177cb751f3098bb272ea24358259fbd067/cmd/dgraphmerge/main.go#L137)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Is there an advantage to moving it before?
</details>
Okay the previous and this comment together would work good. Was considering them spearately. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187)*

**Comment by pawanrawal** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-:-KQ_iX-kwJQKEmy_LPUv:bg7igkv)*

**Comment by pawanrawal** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/187#-:-KQ_q7ydt4shR9esRkeU:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master with commit 01bbadc8b1f9f1751a392e898f8028fa9790312f

**Pull request closed without merging**
