### PR TITLE
Refactor srcfunc, change from slice to struct. Allow value variables in functions.

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1404)

### CODE REVIEW

**Comment by janardhan1993** [comment]
I will raise another PR for supporting value variables in functions.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-:-KtFjCmjxqvcnV5bs6s6:b-az7405)*

**Comment by pawanrawal** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[gql/parser.go, line 133 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFm4Y8s-381_j-fN_6:-KtFm4Y8s-381_j-fN_7:b1og7ki) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/gql/parser.go#L133)):*
> ```Go
> }
> 
> type ArgContext struct {
> ```

better name would just be Arg

---

*[gql/parser.go, line 1453 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFnEkczVKw5g7fYnlN:-KtFnEkczVKw5g7fYnlO:b4ts1qm) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/gql/parser.go#L1453)):*
> ```Go
> 					if g.Attr == "val" {
> 						g.Attr = value
> 					} else {
> ```

Not sure what is this else case for?

---

*[protos/task.proto, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFnOuaCykZ7c2GHsvp:-KtFnOuaCykZ7c2GHsvq:b-6alh1i) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/protos/task.proto#L36)):*
> ```protobuf
> message SrcFunction {
>   string name = 1;
>   string lang = 2;
> ```

Query already has `langs`, could we just use that?

---

*[query/groupby.go, line 137 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFnesP0WLL51rivwxr:-KtFnesP0WLL51rivwxs:bbl8ui9) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/groupby.go#L137)):*
> ```Go
> func aggregateGroup(grp *groupResult, child *SubGraph) (types.Val, error) {
> 	ag := aggregator{
> 		name: child.SrcFunc.Name,
> ```

are we sure its not Nil here?

---

*[query/query.go, line 597 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFo0mYHaZroi3MJ6Qp:-KtFo0mYHaZroi3MJ6Qq:byz4nnc) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L597)):*
> ```Go
> 		}
> 
> 		sg.SrcFunc = new(Function)
> ```

Couldn't we just use the `gql.Function`?

---

*[query/query.go, line 757 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFo6opbAuUWn5j_4lv:-KtFo6opbAuUWn5j_4lw:bj8bld6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L757)):*
> ```Go
> 			dst.SrcFunc.Lang = gchild.Func.Lang
> 			dst.SrcFunc.Args = append(dst.SrcFunc.Args, gchild.Func.Args...)
> 			dst.SrcFunc.IsCount = gchild.Func.IsCount
> ```

same as above.

---

*[query/query.go, line 1004 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFoC6uODdEbFD608yP:-KtFoC6uODdEbFD608yQ:baseggk) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L1004)):*
> ```Go
> 			srcFunc.Args = append(srcFunc.Args, arg.Value)
> 			// TODO: Probably don't assert
> 			x.AssertTrue(!arg.IsValueVar)
> ```

yeah return error, should be simple. Also, isn't this something that should have been caught in the parser?

---

*[query/query.go, line 1589 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFofoTouY8U7VCZnnT:-KtFofoTouY8U7VCZnnU:bccpp24) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L1589)):*
> ```Go
> 		break
> 	}
> 	val := sg.SrcFunc.Args[1].Value
> ```

are you sure this is safe to access?

---

*[types/geofilter.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFozJi8UVb2HXrk_Yk:-KtFozJi8UVb2HXrk_Yl:bt58u8k) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/types/geofilter.go#L65)):*
> ```Go
> // of function.
> func GetGeoTokens(srcFunc *protos.SrcFunction) ([]string, *GeoQueryData, error) {
> 	x.AssertTruef(len(srcFunc.Name) > 0, "Invalid function")
> ```

I suppose srcFunc == nil taken care of already?

---

*[worker/task.go, line 228 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFpdwqyI-VwUoS_mG_:-KtFpdwqyI-VwUoS_mGa:b-1qu6es) ([raw file](https://github.com/dgraph-io/dgraph/blob/de64ac267d2a2e1768a667bc5f1f5373152f4284/worker/task.go#L228)):*
> ```Go
> 	switch f {
> 	case "le", "ge", "lt", "gt", "eq":
> 		// gt(release_date, "1990") is 'CompareAttr' which
> ```

why remove comments?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404)*

**Comment by janardhan1993** [comment]
Review status: 8 of 11 files reviewed at latest revision, 10 unresolved discussions.

---

*[gql/parser.go, line 133 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFm4Y8s-381_j-fN_6:-KtFqvI1ldYln5Fjk9Js:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/gql/parser.go#L133)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

better name would just be Arg
</blockquote></details>

Done.

---

*[gql/parser.go, line 1453 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFnEkczVKw5g7fYnlN:-KtFqw7OZOiPWHZI85xn:b-fc6o9) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/gql/parser.go#L1453)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Not sure what is this else case for?
</blockquote></details>

First if is for
1. eq(val(score), 100) // In this case we change attribute.
and else is for
2. eq(name, val(myname)) 
The way our parser works is as soon as it sees a token if attr is empty it updates it or appends to arg. Before function is parsed we would have appened "val" to args so removing that.

---

*[protos/task.proto, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFnOuaCykZ7c2GHsvp:-KtFr_l3Yw6MX1RHruAf:b-nn2zf3) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/protos/task.proto#L36)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Query already has `langs`, could we just use that?
</blockquote></details>

Will need to have a deeper look at code, langs in query is a slice and is not populated in all cases.

---

*[query/groupby.go, line 137 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFnesP0WLL51rivwxr:-KtFqD5h3gccD0Mv8T-o:bbgx2mo) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/groupby.go#L137)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

are we sure its not Nil here?
</blockquote></details>

That was the assumption before, we were accessing 0th index in slice.

---

*[query/query.go, line 597 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFo0mYHaZroi3MJ6Qp:-KtFqJ_8uPTPgCPe4d8B:b-2c12wf) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L597)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Couldn't we just use the `gql.Function`?
</blockquote></details>

gql.Function has extra fields like needsvar and it's less confusing for people to read the code if we have only the fields we need in a struct.

---

*[query/query.go, line 757 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFo6opbAuUWn5j_4lv:-KtFqRwjKHRK1KyMVo_E:b-c1nrtm) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L757)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

There are more fields in gql function.

---

*[query/query.go, line 1004 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFoC6uODdEbFD608yP:-KtFqVTzBPvQdBVeJKw2:bmkikgz) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L1004)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

yeah return error, should be simple. Also, isn't this something that should have been caught in the parser?
</blockquote></details>

Will do in another pr where i am supporting value variables in functions. This is not related to parser we should replace variables with their value before sending to worker. eq(name, val(myname))

---

*[query/query.go, line 1589 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFofoTouY8U7VCZnnT:-KtFsQOO9C3aVqjutmId:bcj3x6y) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/query/query.go#L1589)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

are you sure this is safe to access?
</blockquote></details>

Parser should throw an error if we have ineq function without an argument. We were doing similar thing before.

---

*[types/geofilter.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFozJi8UVb2HXrk_Yk:-KtFs0AxWcLLzjlelHRP:bdacize) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/types/geofilter.go#L65)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I suppose srcFunc == nil taken care of already?
</blockquote></details>

We parse srcFunc to decide if it's geo or not then only this should be called. So nil should have been already taken care. 

---

*[worker/task.go, line 228 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFpdwqyI-VwUoS_mG_:-KtFsDHt3aal6Aphu-WG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/de64ac267d2a2e1768a667bc5f1f5373152f4284/worker/task.go#L228)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

why remove comments?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[protos/task.proto, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtFnOuaCykZ7c2GHsvp:-KtG39vz9caZWalYyBud:b3o3e0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/f2c0f7a121f5428374752ec1ec9bb5c5ba578302/protos/task.proto#L36)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Will need to have a deeper look at code, langs in query is a slice and is not populated in all cases.
</blockquote></details>

Ok, maybe add a TODO?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-:-KtG3S-Pr5Nz-Zdww1I4:bnfp4nl)*

**Comment by janardhan1993** [comment]
added the support for value variables in functions in this pr only.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-:-KtGN5aKS-Qgh-v06M_n:b2sh22f)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 7 of 11 files at r1, 2 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 995 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtJjVo--52zVGf4xKEs:-KtJjVo--52zVGf4xKEt:bbnycav) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L995)):*
> ```Go
> 	var srcFunc *protos.SrcFunction
> 	if sg.SrcFunc != nil {
> 		srcFunc = new(protos.SrcFunction)
> ```

srcFunc := &protos.SrcFunction{ ... }

---

*[query/query.go, line 1591 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtJjdr6Cu856m2bUhp5:-KtJjdr6Cu856m2bUhp6:b-60xgph) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L1591)):*
> ```Go
> 		// Iterate over the args and replace value args with their values
> 		for _, arg := range sg.SrcFunc.Args {
> 			if arg.IsValueVar {
> ```

Do the smaller logic first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-:-KtJju9MwTgK9ESFF5XA:bnfp4nl)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[protos/task.proto, line 36 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtKJrqI5J8H99bHxP8V:-KtKJrqI5J8H99bHxP8W:b-wx0p3d) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/protos/task.proto#L36)):*
> ```protobuf
> message SrcFunction {
>   string name = 1;
> 	// TODO: Try to use the lang in query, avoid this.
> ```

indentation messed up?

---

*[query/query.go, line 1587 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtKKJLEculFkqmH2yQ3:-KtKKJLEculFkqmH2yQ4:b-2xm3h6) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L1587)):*
> ```Go
> func (sg *SubGraph) replaceVarInFunc() error {
> 	// Attr would be set to val if the query is of type eq(val(myscore), 35)
> 	if sg.SrcFunc != nil && sg.Attr != "val" {
> ```

sg.Attr == "val" {
  return nil
}
....
....

---

*[query/query.go, line 1596 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtKLndjc51XU7EoPaic:-KtKLndjc51XU7EoPaid:b-i1rnsw) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L1596)):*
> ```Go
> 				}
> 				// We don't care about uids, just take all the values and put as args.
> 				// There would be only one value var per subgraph as per current assumptions.
> ```

eq(score, val(myscore), val(otherscore)) throws error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-:-KtKMR3uCPfUQap3tari:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 10 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[protos/task.proto, line 36 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtKJrqI5J8H99bHxP8V:-KtKN8oG8kV2N-aO7urH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/protos/task.proto#L36)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

indentation messed up?
</blockquote></details>

Done.

---

*[query/query.go, line 995 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtJjVo--52zVGf4xKEs:-KtKNVp134CwxOa2P8Co:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L995)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

srcFunc := &protos.SrcFunction{ ... }
</blockquote></details>

Done.

---

*[query/query.go, line 1587 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtKKJLEculFkqmH2yQ3:-KtKO-DxbYzf8-r-doFH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L1587)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

sg.Attr == "val" {
  return nil
}
....
....
</blockquote></details>

Done.

---

*[query/query.go, line 1591 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtJjdr6Cu856m2bUhp5:-KtKO-wIXDECN9EQwMPj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L1591)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do the smaller logic first.
</blockquote></details>

Done.

---

*[query/query.go, line 1596 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404#-KtKLndjc51XU7EoPaic:-KtKO0WA41naYCIw6rxp:b-stgqji) ([raw file](https://github.com/dgraph-io/dgraph/blob/277d698b463ea3917280e69ec90a75bfe94cc710/query/query.go#L1596)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

eq(score, val(myscore), val(otherscore)) throws error?
</blockquote></details>

Yeah, we just store one uidToVal in sg.Params so we are restricted to one value var per subgraph.  Parser throws error in this case "Multiple functions as arguments not allowed".
We would need to refactor our code. Have added an TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1404)*

**Pull request merged**
