### PR TITLE
disaster recover

### PR DESCRIPTION
**Pull request by yangxuanjia**
Disaster recover for zero and alpha.
If raft crash more than half of voters, and docker can't not available, it can be usefully for online environment.

Just restart the only alive node of zero or alpha  with --force_new_cluster=true, the cluster will good.
But this method is lossy recovery, you must use this when you have not other method, it's the last resort when you are in disaster.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7465)

### CODE REVIEW

**Review by jarifibrahim — APPROVED** [review]
@yangxuanjia Thanks for raising the PR :tada: I looked at the PR. The changes look good to me.
I see a few `dgraph/yxj_start_*.sh` scripts. I believe they were accidentally added. Can you please remove them?

We'll also need @manishrjain's review one this PR.

**Comment by yangxuanjia** [comment]
> @yangxuanjia Thanks for raising the PR  I looked at the PR. The changes look good to me.
> I see a few `dgraph/yxj_start_*.sh` scripts. I believe they were accidentally added. Can you please remove them?
> 
> We'll also need @manishrjain's review one this PR.

done

**Comment by jarifibrahim** [comment]
@yangxuanjia The review of this PR is pending because we're working on the 21.03 release currently. This PR is a useful change and we'll get this into dgraph after the next release.

Thanks for working on it.

**Comment by jarifibrahim** [comment]
hey @yangxuanjia, I see that there are some conflicts on this PR. Is it okay if I resolve the conflicts and push some changes to this PR?

**Comment by yangxuanjia** [comment]
@jarifibrahim, 
As you wish, it's my pleasure.

**Review by manishrjain — APPROVED** [review]
:lgtm: Thanks, @yangxuanjia for your contribution. We'd merge it to a branch first where I can refactor this change a bit before merging to master.

Btw, happy to chat sometime about your experiences with running Dgraph.

> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7465#-:-M_uzyWMDr1X3xFcMYK5:b2kvrhh)* status: 10 of 18 files reviewed, 5 unresolved discussions (waiting on @jarifibrahim, @vvbalaji-dgraph, and @yangxuanjia)

___
*[dgraph/cmd/zero/raft.go, line 31 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7465#-M_uyMJl2qmdLzvT6kBe:-M_uyMJl2qmdLzvT6kBf:b-18dqmm) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9ba97220c40873f090f3cd231ea1a11ad348aab/dgraph/cmd/zero/raft.go#L31)):*
> ```Go
> 
> 	"github.com/dgraph-io/dgraph/worker"
> 	"go.uber.org/zap"
> ```

Remove this. We don't use it. No point introducing it in this PR.
___
*[dgraph/cmd/zero/raft.go, line 564 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7465#-M_uyzvk4m3ITKlpU-OM:-M_uyzvk4m3ITKlpU-ON:bik4snr) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9ba97220c40873f090f3cd231ea1a11ad348aab/dgraph/cmd/zero/raft.go#L564)):*
> ```Go
> }
> 
> func (n *node) checkForCIDInEntries() (string, bool, error) {
> ```

Why are we returning string here?
___
*[dgraph/cmd/zero/zero.go, line 673 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7465#-M_uzJdg5M9MODwz893p:-M_uzJdg5M9MODwz893q:b-mg195b) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9ba97220c40873f090f3cd231ea1a11ad348aab/dgraph/cmd/zero/zero.go#L673)):*
> ```Go
> }
> 
> func (s *Server) RemoveAlphaNode(ctx context.Context, member *pb.Member) (*pb.Status, error) {
> ```

We already have remove node. Why do this?
___
*[protos/pb.proto, line 564 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7465#-M_uzOJHD2Qmt_Q_faCc:-M_uzOJHD2Qmt_Q_faCd:btts81n) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9ba97220c40873f090f3cd231ea1a11ad348aab/protos/pb.proto#L564)):*
> ```protobuf
>   rpc MoveTablet(MoveTabletRequest) returns (Status) {}
>   rpc ApplyLicense(ApplyLicenseRequest) returns (Status) {}
>   rpc RemoveAlphaNode (Member)       returns (Status) {}
> ```

don't need this.
___
*[worker/disaster_recover_raft.go, line 2 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7465#-M_uzQuq6NKhVzIE_dtS:-M_uzQuq6NKhVzIE_dtT:bb6ht36) ([raw file](https://github.com/dgraph-io/dgraph/blob/b9ba97220c40873f090f3cd231ea1a11ad348aab/worker/disaster_recover_raft.go#L2)):*
> ```Go
> /*
>  * Copyright 2017-2018 Dgraph Labs, Inc. and Contributors
> ```

2021

**Pull request merged**
