### PR TITLE
Clear/struct

### LINKED ISSUE #1216: error updating an edge value (delete/set) in same request
hi,

I'm trying to update an edge value by deleting it and the setting it with a new value, in the same request, using the Go client. 

it seems that the delete is not working.

here is my test code:
[teste2.go.txt](https://github.com/dgraph-io/dgraph/files/1160030/teste2.go.txt)

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Clear out the struct given by user in `Unmarshal`. This is consistent with how `json.Unmarshal` behaves. This fixes #1216. 
2. Also added helper functions to delete a Node and Edge from the client.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1226)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/client.go, line 199 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ9BDzJW30yprIPymQ:-KpZ9BDzJW30yprIPymR:b-uvcwod) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/client.go#L199)):*
> ```Go
> 		e.nq.SubjectVar = n.String()
> 	} else {
> 		e.nq.Subject = n.String()
> ```

What if both Subject and SubjectVar are 0? what would we set for e.nq.Subject? We should make sure the node is valid before sending to server.

---

*[client/unmarshal.go, line 216 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ7DiQqU1EdkA_J-O9:-KpZ7DiQqU1EdkA_J-OA:bcjirtv) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/unmarshal.go#L216)):*
> ```Go
> 	for i := 0; i < v.NumField(); i++ {
> 		f := v.Field(i)
> 		ft := t.Field(i)
> ```

Should we also check that this is accessible?

---

*[client/unmarshal.go, line 222 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ7canrTm1C1UorGpG:-KpZ7canrTm1C1UorGpH:b-h6377w) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/unmarshal.go#L222)):*
> ```Go
> 		switch ft.Type.Kind() {
> 		case reflect.Slice:
> 			f.Set(reflect.MakeSlice(ft.Type, 0, 0))
> ```

Is there a way to just set it to [:0] instead of allocating again? 
`f.Slice(0, 0)`
https://golang.org/pkg/reflect/#Value.Slice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226)*

**Comment by janardhan1993** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/unmarshal.go, line 222 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ7canrTm1C1UorGpG:-KpZC4dzJ-0hUqvBGV75:b-n0sx4e) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/unmarshal.go#L222)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Is there a way to just set it to [:0] instead of allocating again? 
`f.Slice(0, 0)`
https://golang.org/pkg/reflect/#Value.Slice
</blockquote></details>

https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L578
Have a look at jon unmarshal, we need to handle other types like array

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226)*

**Comment by pawanrawal** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/client.go, line 199 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ9BDzJW30yprIPymQ:-Kpn9u9713_gYH68yBmW:bko3n4a) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/client.go#L199)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

What if both Subject and SubjectVar are 0? what would we set for e.nq.Subject? We should make sure the node is valid before sending to server.
</blockquote></details>

handling that in validate now.

---

*[client/unmarshal.go, line 216 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ7DiQqU1EdkA_J-O9:-Kpn9vu3Qi0i5Sn5sogB:b-fqd7qz) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/unmarshal.go#L216)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Should we also check that this is accessible?
</blockquote></details>

At this moment we are sure that v is of type struct and t is the type of struct so it should be ok to iterate over v.NumField and access `t.Field(i)` 

---

*[client/unmarshal.go, line 222 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ7canrTm1C1UorGpG:-KpmWCiXvzWxV0qipe37:b-qgxl7f) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/unmarshal.go#L222)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

https://github.com/golang/go/blob/master/src/encoding/json/decode.go#L578
Have a look at jon unmarshal, we need to handle other types like array
</blockquote></details>

`f.Slice` doesn't work. JSON.Unmarshal also uses MakeSlice.
I don't think we need to support Array for now, I throw an error. They can just a slice. No one has asked for it too. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/unmarshal.go, line 216 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-KpZ7DiQqU1EdkA_J-O9:-KpnKsx9-jzS-j55cJGT:b-ivecdl) ([raw file](https://github.com/dgraph-io/dgraph/blob/7e8fac52c7675db1a4fda685acc3ddf3ba720e27/client/unmarshal.go#L216)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

At this moment we are sure that v is of type struct and t is the type of struct so it should be ok to iterate over v.NumField and access `t.Field(i)` 
</blockquote></details>

Why not just `i < v.NumField() && i < t.NumField()` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-:-KpnKy8I2MTrLpkxqsHt:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1226#-:-Kpnkc-g_UaMdWaA8j93:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
