### PR TITLE
feat(GraphQL): Zero HTTP endpoints are now available at GraphQL admin (GRAPHQL-1118)

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**
Fixes DGRAPH-1072

This PR makes Zero HTTP endpoints available in GraphQL admin. It also adds a flag `--disable_admin_http` in Zero which can be used to disable the administrative HTTP endpoints in Zero. The following are considered as the administrative endpoints for Zero:
* `/state`
* `/removeNode`
* `/moveTablet`
* `/assign`
* `/enterpriseLicense`

RFC: https://discuss.dgraph.io/t/moving-zero-http-endpoints-to-alpha-graphql-admin/10725

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6649)

 

Docs Preview: [Dgraph Preview](https://dgraph-874f4650c0-99418.surge.sh)

### CODE REVIEW

**Review by pawanrawal — COMMENTED** [review]
Looking good till now, will have another look when its done.

> Reviewed 5 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-:-MItQw5L2kIgF5MC46aX:bck3oqw)* status: 5 of 16 files reviewed, all discussions resolved

**Review by pawanrawal — CHANGES_REQUESTED** [review]
Can we move over all the calls in our existing integration tests to the new GraphQL API instead of the HTTP API?

> Reviewed 2 of 16 files at r1, 5 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-:-MJ842Mw49DLvSWdt4ck:bb1q6ts)* status: 10 of 16 files reviewed, 1 unresolved discussion (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[graphql/admin/assign.go, line 63 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MJ83Mk_CAeeL8WlKQVX:-MJ83Mk_CAeeL8WlKQVY:b-6asfvo) ([raw file](https://github.com/dgraph-io/dgraph/blob/874f4650c0a8cfb5f0232cdd6fe45bbdf5d023bb/graphql/admin/assign.go#L63)):*
> ```Go
> 	}
> 
> 	var startId, endId, readOnly interface{}
> ```

Does this not work if these are defined as `int`? Do we have any tests for this endpoint through the new GraphQL API or can we move over existing calls for this?

**Comment by abhimanyusinghgaur** [comment]
Closing. Not required at the moment. Should be reopened later if a need is felt.

**Review by NamanJain8 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6649)* status: 2 of 18 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/admin/admin.go, line 314 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj1ukb3uboYnEoHv5K:-MWj1ukb3uboYnEoHv5L:b5n7axs) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/admin.go#L314)):*
> ```Go
> 		ID of the destination group where the predicate is to be moved.
> 		"""
> 		groupId: UInt64!
> ```

The `namespace` should also be part of the input as moveTablet should be the guardian of galaxy operation.
___
*[graphql/admin/admin.go, line 498 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj10bE6mYqvbKR9iC7:-MWj10bE6mYqvbKR9iC8:b-wfh1xa) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/admin.go#L498)):*
> ```Go
> 		"restore":           guardianOfTheGalaxyMutationMWs,
> 		"shutdown":          guardianOfTheGalaxyMutationMWs,
> 		"removeNode":        commonAdminMutationMWs,
> ```

 guardianOfTheGalaxyMutationMWs
___
*[graphql/admin/assign.go, line 95 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj1HZr8P2yxlIzGffH:-MWj1HZr8P2yxlIzGffI:bvur1zk) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/assign.go#L95)):*
> ```Go
> 
> 	inputRef := &assignInput{}
> 	inputRef.What, ok = inputArg["what"].(string)
> ```

Maybe capitalize the What field, so that uid Uid UID all are accepted?
___
*[graphql/admin/moveTablet.go, line 43 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj27GJ0SEFtdCOm-p_:-MWj27GJ0SEFtdCOm-pa:b-ggoo8c) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/moveTablet.go#L43)):*
> ```Go
> 	}
> 
> 	ns, _ := x.ExtractNamespace(ctx)
> ```

namespace should be part of input
___
*[graphql/admin/removeNode.go, line 44 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj3qZdCW8iD2-J1ztr:-MWj3qZe0ilcju8L-X1_:bhxy8e) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/removeNode.go#L44)):*
> ```Go
> 	}
> 
> 	if _, err = worker.RemoveNodeOverNetwork(ctx, &pb.RemoveNodeRequest{NodeId: input.NodeId,
> ```

What if the alpha that received the request is itself being removed? In that case, the user will not get a failure message, I think.
___
*[graphql/admin/removeNode.go, line 78 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj2ud0AD4xTmj0uCOu:-MWj2ud0AD4xTmj0uCOv:b-dqmju4) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/removeNode.go#L78)):*
> ```Go
> }
> 
> func parseAsUint64(val interface{}) (uint64, error) {
> ```

These functions also lie around in `alpha/http.go`, can these be moved to a common place like x package or they use something different. Please check.
___
*[worker/zero.go, line 54 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj3dJd4rSaEGSzJF-g:-MWj3dJd4rSaEGSzJF-h:b-qsq2s3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/worker/zero.go#L54)):*
> ```Go
> func ApplyLicenseOverNetwork(ctx context.Context, request *pb.ApplyLicenseRequest) (*pb.Status,
> 	error) {
> 	pl := groups().AnyServer(0)
> ```

Why not directly connect to zero leader?

**Review by abhimanyusinghgaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6649)* status: 1 of 22 files reviewed, 8 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @NamanJain8, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/admin/admin.go, line 314 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj1ukb3uboYnEoHv5K:-MX1j6Bo7fHw1Jd2ldg_:boyexb3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/admin.go#L314)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

The `namespace` should also be part of the input as moveTablet should be the guardian of galaxy operation.
</blockquote></details>

Done. Thanks!
___
*[graphql/admin/admin.go, line 498 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj10bE6mYqvbKR9iC7:-MX1j730ElMgM4uhwPD_:boyexb3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/admin.go#L498)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

 guardianOfTheGalaxyMutationMWs
</blockquote></details>

Done. Thanks!
___
*[graphql/admin/assign.go, line 63 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MJ83Mk_CAeeL8WlKQVX:-MX22UTq8kc6jDE1Xw72:b7wlfrq) ([raw file](https://github.com/dgraph-io/dgraph/blob/874f4650c0a8cfb5f0232cdd6fe45bbdf5d023bb/graphql/admin/assign.go#L63)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Does this not work if these are defined as `int`? Do we have any tests for this endpoint through the new GraphQL API or can we move over existing calls for this?
</blockquote></details>

we sometimes need to send `null` for them in response, so need them as `interface{}`.
Added tests.
___
*[graphql/admin/assign.go, line 95 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj1HZr8P2yxlIzGffH:-MX22i_3CPPpOBwNRLfa:b-gmm5h4) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/assign.go#L95)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Maybe capitalize the What field, so that uid Uid UID all are accepted?
</blockquote></details>

no, that is how it is defined in the GraphQL schema, so the user has to send exactly that string, otherwise, it would fail schema validation.
___
*[graphql/admin/moveTablet.go, line 43 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj27GJ0SEFtdCOm-p_:-MX22uzn1pgYdQfPgtyk:boyexb3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/moveTablet.go#L43)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

namespace should be part of input
</blockquote></details>

Done. Thanks!
___
*[graphql/admin/removeNode.go, line 44 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj3qZdCW8iD2-J1ztr:-MX22w-B50w1E0nS0fSO:b-uex4nu) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/removeNode.go#L44)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

What if the alpha that received the request is itself being removed? In that case, the user will not get a failure message, I think.
</blockquote></details>

Nice catch!
I tried this, but in my case, the alpha returned the response back and then logged fatal.
But, I agree that there can be a race condition between the fatal log and returning the response, and any one of them may happen first.
So, in tests, I have specifically set the group ids for each alpha and only removed alpha 2 & 3 using alpha1.

From the user's point of view, I think we can document this.
___
*[graphql/admin/removeNode.go, line 78 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj2ud0AD4xTmj0uCOu:-MX24IRyAuoADz453wRl:bid16j7) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/graphql/admin/removeNode.go#L78)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

These functions also lie around in `alpha/http.go`, can these be moved to a common place like x package or they use something different. Please check.
</blockquote></details>

Yeah! `alpha/http.go` has a `parseUint64` func, but that parses a query variable in an HTTP request.
This one here is very specific to the constraints of the GraphQL admin server, and should only be used by the admin server.
So, can't merge the two funcs or put them in `x`.
___
*[worker/zero.go, line 54 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MWj3dJd4rSaEGSzJF-g:-MX256ug32d5MFW9XtdT:brv4xum) ([raw file](https://github.com/dgraph-io/dgraph/blob/c349ba0f9afe268302568f6cf4998249e21f628f/worker/zero.go#L54)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Why not directly connect to zero leader?
</blockquote></details>

`EnterpriseLicense` and `RemoveNode` don't necessarily require a zero leader. Even in their HTTP API versions, they can process the request on any server of group zero. So, not enforcing that constraint here.

**Review by abhimanyusinghgaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6649)* status: 16 of 23 files reviewed, 14 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @NamanJain8, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/zero/http.go, line 127 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MX2WVYp5nhLhXjvMic-:-MX5uJXx973x-kWyJMFM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/202ec61aa23d462825e365d27b36d75eaecb9f2b/dgraph/cmd/zero/http.go#L127)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move to next line.
</blockquote></details>

Done.
___
*[dgraph/cmd/zero/http.go, line 188 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MX2WY655iD10AKj-iwn:-MX5uMEG81Ecdog6XG4J:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/202ec61aa23d462825e365d27b36d75eaecb9f2b/dgraph/cmd/zero/http.go#L188)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move to next line.
</blockquote></details>

Done.
___
*[graphql/admin/admin.go, line 288 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MX2X9VEDcAUpj7-RrlB:-MX5uQTp1mxbjfBhpty-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/202ec61aa23d462825e365d27b36d75eaecb9f2b/graphql/admin/admin.go#L288)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Try to reduce the vertical spaces.
</blockquote></details>

Done.
___
*[graphql/admin/enterpriseLicense.go, line 51 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MX2Y22q5ZXhqXn4S0Mo:-MX5uaouCjFgU4S4JRV7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/202ec61aa23d462825e365d27b36d75eaecb9f2b/graphql/admin/enterpriseLicense.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

merge to previous line.
</blockquote></details>

Done.
___
*[graphql/admin/moveTablet.go, line 73 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MX2Y7G3A_xCRWw778lN:-MX5uc2679ft43LVrUXW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/202ec61aa23d462825e365d27b36d75eaecb9f2b/graphql/admin/moveTablet.go#L73)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.
___
*[worker/zero.go, line 54 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6649#-MX2YKPj85Ex3cyRWIwn:-MX5uoCy8OLZ-oQtPwBo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/202ec61aa23d462825e365d27b36d75eaecb9f2b/worker/zero.go#L54)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move from `, request..` to next line. s/request/req.
</blockquote></details>

Done.

**Pull request merged**
