### PR TITLE
Extraction of server package, embedded client (start of work)

### PR DESCRIPTION
**Pull request by tzdybal**
I would like to merge the extraction of `server` package to `master` ASAP, because some code was moved away from `cmd/dgraph/main.go` and it's hard to track changes.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1139)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 8 files at r1, 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQQjdP7AatKeQ7jBRS:-KoQQjdP7AatKeQ7jBRT:bplol27) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/cmd/dgraph/main.go#L57)):*
> ```Go
> 	"github.com/dgraph-io/dgraph/query"
> 	"github.com/dgraph-io/dgraph/schema"
> 	"github.com/dgraph-io/dgraph/server"
> ```

Should create a new server state.

---

*[cmd/dgraph/main_orig.go.txt, line 2 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KodsyrIq5ybJrBhG80u:-KodsyrIq5ybJrBhG80v:b-l6mwxj) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/cmd/dgraph/main_orig.go.txt#L2)):*
> ```
> /*
>  * Copyright (C) 2017 Dgraph Labs, Inc. and Contributors
> ```

remove

---

*[embedded/embedded.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoduRiFhlauvXmQuR1B:-KoduRiFhlauvXmQuR1C:b-fa1jdn) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/embedded/embedded.go#L17)):*
> ```Go
>  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
>  */
> package embedded
> ```

Rename the package to dgraph.

---

*[server/config.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Kodu_4C0mitD8V2uA9D:-Kodu_4C0mitD8V2uA9E:b-1n5w95) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/server/config.go#L17)):*
> ```Go
>  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
>  */
> package server
> ```

Move this to dgraph.

---

*[server/config.go, line 24 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KodsHHtyMfADX4_Yqlp:-KodsHHtyMfADX4_Yqlq:b-a7bedo) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/server/config.go#L24)):*
> ```Go
> 
> type ConfigOpts struct {
> 	Gconf        *string
> ```

Don't make them pointers.

Split the flags here in this and main.

---

*[server/server.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQQQk64JKUSqdhAecj:-KoQQQk64JKUSqdhAeck:b6bvhrs) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/server/server.go#L41)):*
> ```Go
> 
> // TODO(tzdybal) - remove global!
> var State ServerState
> ```

state := NewServerState()

---

*[server/server.go, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQQMIeA-6Ij5iM-HpC:-KoQQMIeA-6Ij5iM-HpD:ba3o3qj) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/server/server.go#L50)):*
> ```Go
> 
> // server is used to implement protos.DgraphServer
> type GrpcServer struct{}
> ```

Rename.

---

*[client/embedded/embedded.go, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQR6ffbDZ2l3pLeTdz:-KoQR6ffbDZ2l3pLeTe-:b-1nqz7y) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/client/embedded/embedded.go#L37)):*
> ```Go
> }
> 
> func (i *inmemoryClient) Run(ctx context.Context, in *protos.Request, opts ...grpc.CallOption) (*protos.Response, error) {
> ```

With this, we should force exactly one group. And don't open up Grpc conns for worker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139)*

**Comment by tzdybal** [comment]
Review status: 1 of 6 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 57 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQQjdP7AatKeQ7jBRS:-KoeElfXIgEcil0aEi6y:b-h5njt0) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/cmd/dgraph/main.go#L57)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Should create a new server state.
</blockquote></details>

Now server state created explicitly in main function, after reading configuration

---

*[dgraph/server.go, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQQMIeA-6Ij5iM-HpC:-KoeFbY0MTa1bAEVwZq1:b-brwsog) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/dgraph/server.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Rename.
</blockquote></details>

Renamed from GrpcServer to Server, anything more to do?

---

*[cmd/dgraph/main_orig.go.txt, line 2 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KodsyrIq5ybJrBhG80u:-KodvSSSlpwFi4ia2Con:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/cmd/dgraph/main_orig.go.txt#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[server/config.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Kodu_4C0mitD8V2uA9D:-KodwCFW7D9qND_h7q8t:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/server/config.go#L17)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this to dgraph.
</blockquote></details>

Done.

---

*[server/config.go, line 24 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KodsHHtyMfADX4_Yqlp:-KoeEaLUFyVtkOJKe16A:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/server/config.go#L24)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't make them pointers.

Split the flags here in this and main.
</blockquote></details>

Done.

---

*[embedded/embedded.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoduRiFhlauvXmQuR1B:-KodvfwXWTDP7XLm55tx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/17bffd97f8455db114fa65ee638fc7b6199a21fe/embedded/embedded.go#L17)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Rename the package to dgraph.
</blockquote></details>

Done.

---

*[embedded/impl.go, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQR6ffbDZ2l3pLeTdz:-Kodw-5YO9YyfuVLtxZd:b1ykxv8) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/embedded/impl.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

With this, we should force exactly one group. And don't open up Grpc conns for worker.
</blockquote></details>

I'll force this one in later commits. This is just a stub of the inmemory client.  Comment added.

---

*[server/server.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoQQQk64JKUSqdhAecj:-KodwmaEWN4Xs-I0REt1:b4y9gjx) ([raw file](https://github.com/dgraph-io/dgraph/blob/000076498766371b626f5651a66be6d04b6307c3/server/server.go#L41)):*
> Short variable declarations may appear only inside functions.
See: https://golang.org/ref/spec#Short_variable_declarations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r2, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/mutations.go, line 149 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Koec6wO3P-LY_1jjHTP:-Koec6wO3P-LY_1jjHTQ:bs0e6r9) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/client/mutations.go#L149)):*
> ```Go
> 
> // TODO(tzdybal) - hide this function from users
> func NewGenericClient(client protos.DgraphClient, opts BatchMutationOptions) *Dgraph {
> ```

`func NewClient(..)`

---

*[dgraph/config.go, line 19 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Koea-v818lPD2arollc:-Koea-v818lPD2arolld:b-zatral) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/config.go#L19)):*
> ```Go
> package dgraph
> 
> type ConfigOpts struct {
> ```

type Options struct {

---

*[dgraph/config.go, line 21 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Koe_s9kDieO9-gzsBMT:-Koe_s9ltuaNu4bvfXog:b-yj99ow) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/config.go#L21)):*
> ```Go
> type ConfigOpts struct {
> 	PostingDir  string
> 	WalDir      string
> ```

WALDir

---

*[dgraph/impl.go, line 27 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoedSlOVH8vknkpeo00:-KoedSlOVH8vknkpeo01:bx10fk0) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/impl.go#L27)):*
> ```Go
> )
> 
> type inmemoryClient struct {
> ```

equivalent of protos.DgraphClient

---

*[dgraph/server.go, line 50 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoeeGWTPLsBgfnQEy2A:-KoeeGWTPLsBgfnQEy2B:b-js53jc) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/server.go#L50)):*
> ```Go
> }
> 
> // server is used to implement protos.DgraphServer
> ```

Capital S.

---

*[dgraph/server.go, line 51 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoedtERoTSEMufU_nd-:-KoedtERoTSEMufU_nd0:b-rnc99j) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/server.go#L51)):*
> ```Go
> 
> // server is used to implement protos.DgraphServer
> type InternalServer struct{}
> ```

Server. No change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-:-KoeeMb4ZumWnvrVryTV:bnfp4nl)*

**Comment by tzdybal** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[client/mutations.go, line 149 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Koec6wO3P-LY_1jjHTP:-KoefJAzQyaeuV704KOC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/client/mutations.go#L149)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`func NewClient(..)`
</blockquote></details>

Done.

---

*[dgraph/config.go, line 19 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Koea-v818lPD2arollc:-KoefXdZ3D2HlIB8pVq4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/config.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

type Options struct {
</blockquote></details>

Done.

---

*[dgraph/config.go, line 21 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-Koe_s9kDieO9-gzsBMT:-KoefXzWWjyxAevo1Wnk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/config.go#L21)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

WALDir
</blockquote></details>

Done.

---

*[dgraph/impl.go, line 27 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoedSlOVH8vknkpeo00:-Koef_QNQYt3ILdpllOH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/impl.go#L27)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

equivalent of protos.DgraphClient
</blockquote></details>

Done.

---

*[dgraph/server.go, line 50 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoeeGWTPLsBgfnQEy2A:-KoegSTDqFm2JNjzzTBU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/server.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Capital S.
</blockquote></details>

Done.

---

*[dgraph/server.go, line 51 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139#-KoedtERoTSEMufU_nd-:-KoegSqj5MupLl5LP0QZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8ce220d8e61b72130f34972a51df3b5b965e9ff/dgraph/server.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Server. No change.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1139)*

**Comment by tzdybal** [comment]
Changes merged to master (d3f7048cb18f46564c01ec2af6bcd83e5156f75a).

**Pull request closed without merging**
