### PR TITLE
Get rid of special handling for _nil_

### LINKED ISSUE #1484: Some string values such as "_nil_" have special meaning
As discovered via #1477, some strings may have special meaning to the server, which is usually a very bad idea as it mixes user data with implementation logic in unexpected ways. A string such as `_nil_` for example might very easily be part of the data imported into the system, and it would magically disappear once stored.

As a recommendation, I would make `SetValueString` in the Go code respect the input value _exactly._ Even escaping should be applied internally, instead of expecting developers to escape the value by themselves. If the low-level functionality is necessary for certain tools, I would make that explicit in the API name, such as SetValueRaw or similar, and make the rules there more clear so people can tell what to expect when using it.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1886)

Fixes #1484.

### CODE REVIEW

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/mutation.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-L-ixWf5L-fKSe0CcVH-:-L-ixWf5L-fKSe0CcVH0:br8xv76) ([raw file](https://github.com/dgraph-io/dgraph/blob/cc41cefbbeb3f7a421eb77b84ff0efcc20fb0eb9/gql/mutation.go#L208)):*
> ```Go
> 	}
> 
> 	if sUid == 0 {
> ```

Definitely makes sense that `sUid` and `oUid` should be `!= 0`. Just so I better understand this change, are these checks now required, or just something that made sense to add in?

---

*[query/query.go, line 415 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-L-j06OIBfFzjgpHw_Xf:-L-j06OIBfFzjgpHw_Xg:b-p8hpe0) ([raw file](https://github.com/dgraph-io/dgraph/blob/cc41cefbbeb3f7a421eb77b84ff0efcc20fb0eb9/query/query.go#L415)):*
> ```Go
> 		} else if pc.SrcFunc != nil && pc.SrcFunc.Name == "checkpwd" {
> 			addCheckPwd(pc, pc.valueMatrix[idx].Values, dst)
> 		} else if pc.uidMatrix != nil && idx < len(pc.uidMatrix) && len(pc.uidMatrix[idx].Uids) > 0 {
> ```

`pc.uidMatrix == nil` has already been checked a few lines above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-:-L-j2LwGV8Nxcv7DfwOb:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 342 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-L-izexEaUq9fMuUhb2h:-L-izexEaUq9fMuUhb2i:bk4eukc) ([raw file](https://github.com/dgraph-io/dgraph/blob/cc41cefbbeb3f7a421eb77b84ff0efcc20fb0eb9/posting/list.go#L342)):*
> ```Go
> 
> 	// ValueId can only be 0 when ObjectValue was set.
> 	if t.ValueId == 0 {
> ```

use mpost.postingtype ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-:-L-j332-csVDzvLubPf8:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[gql/mutation.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-L-ixWf5L-fKSe0CcVH-:-L-j2z-fjKn4TG2biPFn:b-tdzx4b) ([raw file](https://github.com/dgraph-io/dgraph/blob/cc41cefbbeb3f7a421eb77b84ff0efcc20fb0eb9/gql/mutation.go#L208)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Definitely makes sense that `sUid` and `oUid` should be `!= 0`. Just so I better understand this change, are these checks now required, or just something that made sense to add in?
</blockquote></details>

They were always required and we were asserting before in `toUid`. I just changed it to return an error.

---

*[posting/list.go, line 342 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-L-izexEaUq9fMuUhb2h:-L-j3cgBGw9w8Okxcxv_:b-5fkfbo) ([raw file](https://github.com/dgraph-io/dgraph/blob/cc41cefbbeb3f7a421eb77b84ff0efcc20fb0eb9/posting/list.go#L342)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

use mpost.postingtype ?
</blockquote></details>

Yeah, that would read better.

---

*[query/query.go, line 415 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886#-L-j06OIBfFzjgpHw_Xf:-L-j3PZCFL3cEwek0RSU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cc41cefbbeb3f7a421eb77b84ff0efcc20fb0eb9/query/query.go#L415)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

`pc.uidMatrix == nil` has already been checked a few lines above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1886)*

**Comment by pawanrawal** [comment]
In master as of 56c99ea6784bfa9f9954e349b314deab9d2243b9.

**Pull request closed without merging**
