### PR TITLE
Improve/geo-func

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/419)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[types/geofilter_test.go, line 91 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/419#-KZspzLjbngxp22VEqCv:-KZspzLjbngxp22VEqCw:b-z1zh91) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c92d10bb2012646ff40866ced1465dce8a677ff/types/geofilter_test.go#L91)):*
> ```Go
> 	}
> }
> ```

Test that the polygons near a big polygon don't show up inside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/419)*

**Comment by ashwin95r** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[types/geofilter_test.go, line 91 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/419#-KZspzLjbngxp22VEqCv:-KZsxFyzn-Iig-1kQDU2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c92d10bb2012646ff40866ced1465dce8a677ff/types/geofilter_test.go#L91)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Test that the polygons near a big polygon don't show up inside.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/419)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/419#-:-KZsxhtOMgQ2WdakqfM2:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
