### PR TITLE
Fix some more tests

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Modify client to accept multiple `protos.DgraphClient`.
2. Fix share handler.
3. Make contrib tests run again.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1726)

### CODE REVIEW

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 24 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[client/client.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1726#-KyEkVpU3SWu2JGqb8o-:-KyEkVpU3SWu2JGqb8o0:bygetj3) ([raw file](https://github.com/dgraph-io/dgraph/blob/fbd9f7220df0812f763cfea6d38a8a0ec42b213d/client/client.go#L48)):*
> ```Go
> //
> // A single client is thread safe for sharing with multiple go routines.
> func NewDgraphClient(clients []protos.DgraphClient) *Dgraph {
> ```

Having variadic argument here would be more user-friendly (passing in just 1 is easier).

---

*[client/example_set_object_test.go, line 88 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1726#-KyEkysHFJKWK6SQscld:-KyEkysHFJKWK6SQscle:byh6zty) ([raw file](https://github.com/dgraph-io/dgraph/blob/fbd9f7220df0812f763cfea6d38a8a0ec42b213d/client/example_set_object_test.go#L88)):*
> ```Go
> 
> 	mu.SetJson = pb
> 	mu.CommitImmediately = true
> ```

`CommitImmediately` has already been set.

---

*[client/example_set_object_test.go, line 115 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1726#-KyElCpTSAiwR8j4XJCO:-KyElCpTSAiwR8j4XJCP:b-b4v1bb) ([raw file](https://github.com/dgraph-io/dgraph/blob/fbd9f7220df0812f763cfea6d38a8a0ec42b213d/client/example_set_object_test.go#L115)):*
> ```Go
> 	}`, puid)
> 
> 	resp, err := dg.NewTxn().Query(context.Background(), q, nil)
> ```

You already have a `ctx`, so could use it here as well (I noticed this in a few other places as well).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1726#-:-KyEnThGCcatDdjA3sL2:bnfp4nl)*

**Comment by manishrjain** [comment]
Will let @janardhan1993 and @peterstace review this.

**Comment by peterstace** [comment]
Reviewed 20 of 24 files at r1, 1 of 2 files at r2, 6 of 7 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1726)*

**Comment by peterstace** [comment]
Reviewed 1 of 6 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1726)*

**Comment by pawanrawal** [comment]
This was merged to master.

**Pull request closed without merging**
