### PR TITLE
Fix panic in posting by using levelClosers

### LINKED ISSUE #1939: Dgraph server panics when shutdown
I saw the following panic when using Ctrl-C:

```
^C2017/12/20 13:07:38 run.go:336: Caught Ctrl-C. Terminating now (this may take a few seconds)...
2017/12/20 13:07:38 admin.go:61: Got clean exit request
2017/12/20 13:07:38 Stopped taking more http(s) requests. Err: accept tcp [::]:8080: use of closed network connection
2017/12/20 13:07:38 gRpc server stopped : accept tcp [::]:9080: use of closed network connection
2017/12/20 13:07:38 All http(s) requests finished.
2017/12/20 13:07:43 wal.go:118: Writing snapshot to WAL, metadata: {ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:177 Term:2 XXX_unrecognized:[]}, len(data): 27
panic: send on closed channel

goroutine 182 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc4200be300, 0xc43960a728, 0x1, 0x1, 0x17, 0x20, 0xc4359248e0)
	/home/petsta/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:609 +0x15f
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).batchSet(0xc4200be300, 0xc43960a728, 0x1, 0x1, 0x0, 0xc43960a728)
	/home/petsta/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:679 +0x4d
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).purgeVersionsBelow(0xc4200be300, 0xc433840a20, 0xc4359248e0, 0x17, 0x20, 0x47, 0x0, 0x0)
	/home/petsta/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:931 +0x453
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*ManagedDB).PurgeVersionsBelow(0xc42008c0c0, 0xc4359248e0, 0x17, 0x20, 0x47, 0x0, 0x0)
	/home/petsta/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/managed_db.go:79 +0x127
github.com/dgraph-io/dgraph/posting.periodicPurgeOldVersions.func1()
	/home/petsta/go/src/github.com/dgraph-io/dgraph/posting/lists.go:244 +0x2a2
github.com/dgraph-io/dgraph/posting.periodicPurgeOldVersions()
	/home/petsta/go/src/github.com/dgraph-io/dgraph/posting/lists.go:254 +0x40
created by github.com/dgraph-io/dgraph/posting.Init
	/home/petsta/go/src/github.com/dgraph-io/dgraph/posting/lists.go:211 +0xe1
```

### PR DESCRIPTION
**Pull request by pawanrawal**
Fix #1939 

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1945)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/lists.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1945#-L0mtAf2soINnW0zxRuX:-L0mtAf2soINnW0zxRuY:b-8ftlje) ([raw file](https://github.com/dgraph-io/dgraph/blob/542e560609e3ea9f37c7f61910e7e8643ba0c05b/posting/lists.go#L208)):*
> ```Go
> type closers struct {
> 	updateStats         *y.Closer
> 	updateMemoryMetrics *y.Closer
> ```

You can use the same closer for all there, just do add(3)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1945)*

**Comment by manishrjain** [comment]
LGTM. once you implement @janardhan1993 's comment.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1945#-:-L0mtXbn19rDcxEeyIif:b-ds5o7k)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1945#-:-L0mtjT13A92Up_bZTQb:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master as of d06e674ede4c23e8d7ea8bb87a1cffbe6a4f6bc1.

**Pull request closed without merging**
