### PR TITLE
Enable continuous profiling

### PR DESCRIPTION
**Pull request by ashwin95r**
Uses [/debug/pprof](https://golang.org/pkg/net/http/pprof/)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/209)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXTybVkDW_T-8_Eu7m:-KRXTybVkDW_T-8_Eu7n:b-jfkqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraph/main.go#L71)):*
> ```Go
> 	cpuprofile  = flag.String("cpuprof", "", "write cpu profile to file")
> 	memprofile  = flag.String("memprof", "", "write memory profile to file")
> 	prof        = flag.Bool("profile", false, "Enable profiling through pprof")
> ```

Take a port number as string instead of bool. Then you can check if it's provided and if so, enable the prof.

---

*[cmd/dgraph/main.go, line 489 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXU45xYcKhkDUUg1N_:-KRXU45xYcKhkDUUg1Na:b62hwao) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraph/main.go#L489)):*
> ```Go
> 	if *prof {
> 		go func() {
> 			log.Println(http.ListenAndServe("localhost:6060", nil))
> ```

This should be provided via flag.

---

*[cmd/dgraphassigner/main.go, line 38 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXU6rfQ1rumIFjdDGT:-KRXU6rfQ1rumIFjdDGU:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraphassigner/main.go#L38)):*
> ```Go
> 	numcpu     = flag.Int("numCpu", runtime.NumCPU(),
> 		"Number of cores to be used by the process")
> 	prof = flag.Bool("profile", false, "Enable profiling through pprof")
> ```

Same here.

---

*[cmd/dgraphloader/main.go, line 55 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXU8WpgrdYzA-scjjk:-KRXU8WpgrdYzA-scjjl:b-1kzc9c) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraphloader/main.go#L55)):*
> ```Go
> 		"Number of cores to be used by the process")
> 	prof = flag.Bool("profile", false, "Enable profiling through pprof")
> )
> ```

And here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/209)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 489 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXU45xYcKhkDUUg1N_:-KRXUFORF-vZCnCeq3iJ:b-u1nzwj) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraph/main.go#L489)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should be provided via flag.
</details>
Actually, we're already getting other /debug endpoints in dgraph because of it's http server. So, you don't need this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/209)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXTybVkDW_T-8_Eu7m:-KRXiY4KeegtDbmGWfEo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraph/main.go#L71)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Take a port number as string instead of bool. Then you can check if it's provided and if so, enable the prof.
</details>
Done.

---

*[cmd/dgraph/main.go, line 489 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXU45xYcKhkDUUg1N_:-KRXixqzXOb4wg5OuNjH:b-pu1hla) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraph/main.go#L489)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Actually, we're already getting other /debug endpoints in dgraph because of it's http server. So, you don't need this.
</details>
Ah okay. Done.

---

*[cmd/dgraphassigner/main.go, line 38 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXU6rfQ1rumIFjdDGT:-KRXiz86XN7WaOfTy8dW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraphassigner/main.go#L38)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Same here.
</details>
Done.

---

*[cmd/dgraphloader/main.go, line 55 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-KRXU8WpgrdYzA-scjjk:-KRXj-GmHjpHLt0wXw4r:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7bc46beca7c20fd71b1aa81f840113b346e321d6/cmd/dgraphloader/main.go#L55)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> And here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/209)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/209#-:-KRbUWG05iqADABkY-mJ:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master with commit 6e5ee64cf2adae2fd0dbf7d660a210131c4d1c03

**Pull request closed without merging**
