### PR TITLE
[BREAKING] feat(zero): Make zero lease out namespace IDs

### PR DESCRIPTION
**Pull request by ahsanbarkati**
This PR makes zero lease out the namespaceIDs. It changes the existing `AssignUids()` API to `AssignIds()`, which can be used to get both UIDs as well as NamespaceIDs. The lease type which is required is passed with the `pb.Num` to `AssignIds()`

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7341)

### CODE REVIEW

**Review by manishrjain — APPROVED** [review]
:lgtm: Bunch of comments.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-:-MRVRtgxBf6miSQYl6gO:b8tfc00)* status: all files reviewed, 8 unresolved discussions (waiting on @ahsanbarkati and @vvbalaji-dgraph)

___
*[dgraph/cmd/zero/assign.go, line 36 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVRi1xAhzaXfsnriQ2:-MRVRi1xAhzaXfsnriQ3:bb7wij4) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/dgraph/cmd/zero/assign.go#L36)):*
> ```Go
> const (
> 	leaseBandwidth           = uint64(10000)
> 	leaseTxnTs     leaseType = iota
> ```

If you make this public, then the worker package can use the int values of these in pb.Num.
___
*[dgraph/cmd/zero/assign.go, line 174 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVR9ifAV7OBTvkA1Ca:-MRVR9ifAV7OBTvkA1Cb:bb69vi5) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/dgraph/cmd/zero/assign.go#L174)):*
> ```Go
> 
> 	} else {
> 		glog.Errorf("Unknown lease type: %v\n", typ)
> ```

return this error.
___
*[dgraph/cmd/zero/assign.go, line 179 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVRHlZ6mjwzmjWqkJj:-MRVRHlZ6mjwzmjWqkJk:b-9dttjb) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/dgraph/cmd/zero/assign.go#L179)):*
> ```Go
> }
> 
> func (s *Server) AssignUids(ctx context.Context, num *pb.Num) (*pb.AssignedIds, error) {
> ```

remove this.
___
*[dgraph/cmd/zero/assign.go, line 183 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVRFOuC7FhMf9z4k7-:-MRVRFOuC7FhMf9z4k70:by7snrr) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/dgraph/cmd/zero/assign.go#L183)):*
> ```Go
> }
> 
> func (s *Server) AssignNsIDs(ctx context.Context, num *pb.Num) (*pb.AssignedIds, error) {
> ```

Don't create this func.
___
*[dgraph/cmd/zero/assign.go, line 189 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVRIdx5tT4MO0uQU-Z:-MRVRIdx5tT4MO0uQU-_:b-dnl0vd) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/dgraph/cmd/zero/assign.go#L189)):*
> ```Go
> // AssignIds is used to assign new ids (UIDs, NsIDs) by communicating with the leader of the
> // RAFT group responsible for handing out ids.
> func (s *Server) AssignIds(ctx context.Context, num *pb.Num, typ leaseType) (*pb.AssignedIds, error) {
> ```

Make AssignUids public func -> AssignIds. And pass the context via pb.Num. pb.Num isn't persisted, so can use the iota's int value.
___
*[protos/pb.proto, line 166 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVRpCeAx2fQtKu1Q3c:-MRVRpCeAx2fQtKu1Q3d:bj7uxyt) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/protos/pb.proto#L166)):*
> ```protobuf
> 	License license = 10;
> 	ZeroSnapshot snapshot = 11; // Used to make Zeros take a snapshot.
> 	uint64 maxLeaseNsID = 12;
> ```

move it next to the other uint64s.
___
*[protos/pb.proto, line 182 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVRqZL6PSlCezcVUgq:-MRVRqZL6PSlCezcVUgr:bfqvfmu) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/protos/pb.proto#L182)):*
> ```protobuf
> 	string cid = 8; // Used to uniquely identify the Dgraph cluster.
> 	License license = 9;
> 	uint64 maxLeaseNsID = 12;
> ```

and here. Use 10.
___
*[protos/pb.proto, line 542 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRVRrbk78hN4xXsnJsI:-MRVRrbk78hN4xXsnJsJ:b-hfpv23) ([raw file](https://github.com/dgraph-io/dgraph/blob/e8b799cee9f6e6d66c20d77db0ea4e12e5c878df/protos/pb.proto#L542)):*
> ```protobuf
> 	rpc ShouldServe (Tablet)           returns (Tablet) {}
> 	rpc AssignUids (Num)               returns (AssignedIds) {}
> 	rpc AssignNsIDs (Num)              returns (AssignedIds) {}
> ```

remove.

**Review by jarifibrahim — COMMENTED** [review]
I haven't looked at the entire PR. I'll review it again in some time.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-:-MRZgVWe8awcsG6-95yc:b-5g0lgf)* status: 0 of 20 files reviewed, 18 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run_test.go, line 1697 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZKLL83z4mhyGrbeVp:-MRZKLL92MG1wloQfsaq:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/dgraph/cmd/alpha/run_test.go#L1697)):*
> ```Go
> 	}
> 	zc := pb.NewZeroClient(conn)
> 	if _, err := zc.AssignIds(context.Background(), &pb.Num{Val: 1e6, Type: pb.Num_UID}); err != nil {
> ```

100 chars
___
*[dgraph/cmd/zero/assign.go, line 40 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZKe-CC1cNYGxPkwFc:-MRZKe-D-HTu7FQp4rQx:b-c3qnho) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/dgraph/cmd/zero/assign.go#L40)):*
> ```Go
> 	s.Lock()
> 	s.nextLease[pb.Num_UID] = s.state.MaxUID + 1
> 	s.nextLease[pb.Num_TXN_TS] = s.state.MaxTxnTs + 1
> ```

Does it have to be `NUM_TXN_TS`? `TXN_TS` should also suffice.
___
*[dgraph/cmd/zero/assign.go, line 44 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZKlsY4ilvVKG-Zwmn:-MRZKlsZ3BQWMTHqPXyo:b-1k0bne) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/dgraph/cmd/zero/assign.go#L44)):*
> ```Go
> 
> 	startTs = s.nextLease[pb.Num_TXN_TS]
> 	glog.Infof("Updated Lease id: %d. Txn Ts: %d. NsID: %d.",
> ```

Updated UID
___
*[dgraph/cmd/zero/assign.go, line 71 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZMUMIEYvH8gY4pyZQ:-MRZMUMIEYvH8gY4pyZR:b-mh73so) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/dgraph/cmd/zero/assign.go#L71)):*
> ```Go
> // so we can tackle any collisions that might happen with the leasemanager
> // In essence, we just want one server to be handing out new uids.
> func (s *Server) lease(ctx context.Context, num *pb.Num, typ pb.NumLeaseType) (*pb.AssignedIds,
> ```

pb.Num already has the type. You don't need to pass the `typ` parameter.
___
*[dgraph/cmd/zero/raft.go, line 416 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZY8125we6SOg-dIwH:-MRZY8125we6SOg-dIwI:b-5zl7jo) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/dgraph/cmd/zero/raft.go#L416)):*
> ```Go
> 	case p.MaxTxnTs > state.MaxTxnTs:
> 		state.MaxTxnTs = p.MaxTxnTs
> 	case p.MaxUID != 0 || p.MaxTxnTs != 0:
> ```

Don't we need to check the NS ID as well?
___
*[graphql/e2e/common/admin.go, line 419 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZODpS61WDJrSS1X6W:-MRZODpS61WDJrSS1X6X:b9q2d4a) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/graphql/e2e/common/admin.go#L419)):*
> ```Go
> 				}
> 				maxUID
> 				maxTxnTs
> ```

Add max namespace ID here too.
___
*[protos/pb.proto, line 166 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZOPOt05o2fhuRppbi:-MRZOPOt05o2fhuRppbj:b-aecogl) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/protos/pb.proto#L166)):*
> ```protobuf
> 	string cid = 9; // Used as unique identifier for the cluster.
> 	License license = 10;
> 	ZeroSnapshot snapshot = 11; // Used to make Zeros take a snapshot.
> ```

Add a comment after this line that 12 is already used.
___
*[protos/pb.proto, line 182 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZOMHx7kKF1Fmum9Uu:-MRZOMHx7kKF1Fmum9Uv:bmkwrfx) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/protos/pb.proto#L182)):*
> ```protobuf
> 	repeated Member removed = 7;
> 	string cid = 8; // Used to uniquely identify the Dgraph cluster.
> 	License license = 9;
> ```

Add a comment after this line that 10 is already used.
___
*[worker/mutation.go, line 509 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZOfO8EyWh-X-SjXZV:-MRZOfO8EyWh-X-SjXZW:b-nzdisv) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/worker/mutation.go#L509)):*
> ```Go
> 	con := pl.Get()
> 	c := pb.NewZeroClient(con)
> 	return c.AssignIds(ctx, num)
> ```

You should set the num.Type here (I know the caller has set it but it's useful to set it near the function call)

**Review by ahsanbarkati — COMMENTED** [review]
Addressed comments.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-:-MRZp5B25duyrR4VzqYJ:benxbfs)* status: 0 of 20 files reviewed, 18 unresolved discussions (waiting on @ahsanbarkati, @jarifibrahim, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/zero/assign.go, line 40 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-MRZKe-CC1cNYGxPkwFc:-MRZoruD4ucQK16PVDNn:belhzyj) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc2f5edbb21046c75221409eb749d0ced95fd60/dgraph/cmd/zero/assign.go#L40)):*
<details><summary><i>Previously, jarifibrahim (Ibrahim Jarif) wrote…</i></summary><blockquote>

Does it have to be `NUM_TXN_TS`? `TXN_TS` should also suffice.
</blockquote></details>

NUM_TXN_TS is auto generated by protobuf. It is because TXN_TS is an enum inside the Num message type.

**Review by jarifibrahim — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7341#-:-MR_UtKr75Hlb6JAtF72:bnfp4nl)* status: 0 of 20 files reviewed, 18 unresolved discussions (waiting on @ahsanbarkati, @jarifibrahim, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

**Pull request merged**
