### PR TITLE
fix(docs): This PR adds docs for parameterized cascade.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes GRAPHQL-659

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6443)

 
 
 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-f14c283fd6-93530.surge.sh)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
Please get it reviewed by @michaeljcompton as well. 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-:-MHBrK9W9IgsrRkENhHK:b-vnda3b)* status: all files reviewed, 5 unresolved discussions (waiting on @danielmai, @JatinDevDG, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/cascade.md, line 47 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBpY1HBh_BB1ORziMc:-MHBpY1HBh_BB1ORziMd:b-rvwx1a) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L47)):*
> ```Markdown
> ### Parameterized Cascade
> 
> cascade is sometimes very strict because for a node to be in response, all its children in the sub-graph must be present. 
> ```

Change all of this initial paragram to something like below.

@cascade can also optionally take a list of fields as an argument. This changes the default behaviour to consider only the supplied fields as mandatory instead of all the fields for a type. 
___
*[wiki/content/graphql/queries/cascade.md, line 52 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqFX22Wk78goO0N91:-MHBqFX22Wk78goO0N92:b-os0nou) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L52)):*
> ```Markdown
> `@cascade(fields:["field1","field2"..])` 
> 
> In the below example argument field "name" is used as an argument to cascade and forwarded to the next query level also. So for author 
> ```

In the example below, `name` is supplied in the fields argument. It would also be automatically cascaded as a required argument to `country` below. So for an author....
___
*[wiki/content/graphql/queries/cascade.md, line 59 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqeqI9vArSkI7aHg8:-MHBqeqJ7yj4W4YZ_TrV:bit1qjw) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L59)):*
> ```Markdown
> 		name
> 		country {
>                 Id
> ```

id

Also not indented properly
___
*[wiki/content/graphql/queries/cascade.md, line 62 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqaIF5G4qUFwspbrz:-MHBqaIG5vhfcqFEDK2q:b-96qwgw) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L62)):*
> ```Markdown
> 				name
> 		}
> 	}
> ```

not indented properly
___
*[wiki/content/graphql/queries/cascade.md, line 64 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqkSHEXqgWAmRp1Ii:-MHBqkSHEXqgWAmRp1Ij:b-1lu468) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L64)):*
> ```Markdown
> 	}
> ```
> Following query ensures authors which has post field should also have text subfield in it.
> ```

The query below would only return those posts which have a non-null text field.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6443)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @pawanrawal)

___
*[wiki/content/graphql/queries/cascade.md, line 47 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBpY1HBh_BB1ORziMc:-MHCR4ls1dubOFD3ZdKc:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L47)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Change all of this initial paragram to something like below.

@cascade can also optionally take a list of fields as an argument. This changes the default behaviour to consider only the supplied fields as mandatory instead of all the fields for a type. 
</blockquote></details>

done.
___
*[wiki/content/graphql/queries/cascade.md, line 52 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqFX22Wk78goO0N91:-MHC_UbDD1C_Hsxuub7C:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L52)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

In the example below, `name` is supplied in the fields argument. It would also be automatically cascaded as a required argument to `country` below. So for an author....
</blockquote></details>

done.
___
*[wiki/content/graphql/queries/cascade.md, line 59 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqeqI9vArSkI7aHg8:-MHCaDx9CLMNL3gJauhM:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L59)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

id

Also not indented properly
</blockquote></details>

done.
___
*[wiki/content/graphql/queries/cascade.md, line 62 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqaIF5G4qUFwspbrz:-MHCaFOI3QsHWzed5imW:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L62)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

not indented properly
</blockquote></details>

done.
___
*[wiki/content/graphql/queries/cascade.md, line 64 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHBqkSHEXqgWAmRp1Ii:-MHCaGeO44h3MljC59O9:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6cca7cdc20b724580578f9539e4f51b51aae6f8/wiki/content/graphql/queries/cascade.md#L64)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The query below would only return those posts which have a non-null text field.
</blockquote></details>

done.

**Review by MichaelJCompton — APPROVED** [review]
Couple of changes

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-:-MHFc_aM1kCWPMOiVS0O:b24kuhh)* status: all files reviewed, 8 unresolved discussions (waiting on @danielmai, @JatinDevDG, and @pawanrawal)

___
*[wiki/content/graphql/queries/cascade.md, line 50 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHFalGOCJ63M_CqObGd:-MHFalGOCJ63M_CqObGe:b-1snr7l) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9aa16b7219ea626517468f4d90efe169de2086c/wiki/content/graphql/queries/cascade.md#L50)):*
> ```
> It would also be automatically cascaded as a required argument to country below. So for author
> to be in query response it should have a name and if has a subfield country then that should also have name.
> ```

Let's remove the 'would' and should

Listed fields are also automatically cascaded as required argument to nested selection sets.  For example, name is supplied in the fields argument below, so for an author to be in the query response it must have a name and if it has a subfield country, then that must also have name.
___
*[wiki/content/graphql/queries/cascade.md, line 63 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHFbjT61QaA_IwvTCvo:-MHFbjT61QaA_IwvTCvp:bvjl5zd) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9aa16b7219ea626517468f4d90efe169de2086c/wiki/content/graphql/queries/cascade.md#L63)):*
> ```
> would only return
> ```

only returns
___
*[wiki/content/graphql/queries/cascade.md, line 78 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHFbpmh2Q7nxjrqwIOC:-MHFbpmh2Q7nxjrqwIOD:b-2fpk2m) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9aa16b7219ea626517468f4d90efe169de2086c/wiki/content/graphql/queries/cascade.md#L78)):*
> ```
> Also, these fields are  forwarded to the next query level unless there is a cascade at the next level,
> in that case, arguments to cascade are overwritten.
> The below query ensures that the author should have field reputation and name. And if it has subfield posts then that should also have field text in it.
> ```

The cascading nature of field selection is overwritten by a nested `@casecade`.  For example, the query below ensures that an author has fields reputation and name, and, if it has subfield posts, then that must have field text.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6443)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @pawanrawal)

___
*[wiki/content/graphql/queries/cascade.md, line 50 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHFalGOCJ63M_CqObGd:-MHFllKI18QXWvuFIWgl:b-rnraql) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9aa16b7219ea626517468f4d90efe169de2086c/wiki/content/graphql/queries/cascade.md#L50)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> It would also be automatically cascaded as a required argument to country below. So for author
> to be in query response it should have a name and if has a subfield country then that should also have name.
> ```

Let's remove the 'would' and should

Listed fields are also automatically cascaded as required argument to nested selection sets.  For example, name is supplied in the fields argument below, so for an author to be in the query response it must have a name and if it has a subfield country, then that must also have name.
</blockquote></details>

done.
___
*[wiki/content/graphql/queries/cascade.md, line 63 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHFbjT61QaA_IwvTCvo:-MHFlqjG0S5F7evLqWK6:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9aa16b7219ea626517468f4d90efe169de2086c/wiki/content/graphql/queries/cascade.md#L63)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> would only return
> ```

only returns
</blockquote></details>

done.
___
*[wiki/content/graphql/queries/cascade.md, line 78 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHFbpmh2Q7nxjrqwIOC:-MHFmF6iBn9qpgIVgusT:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9aa16b7219ea626517468f4d90efe169de2086c/wiki/content/graphql/queries/cascade.md#L78)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

> ```
> Also, these fields are  forwarded to the next query level unless there is a cascade at the next level,
> in that case, arguments to cascade are overwritten.
> The below query ensures that the author should have field reputation and name. And if it has subfield posts then that should also have field text in it.
> ```

The cascading nature of field selection is overwritten by a nested `@casecade`.  For example, the query below ensures that an author has fields reputation and name, and, if it has subfield posts, then that must have field text.

</blockquote></details>

done.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6443)* status: all files reviewed, 4 unresolved discussions (waiting on @danielmai, @JatinDevDG, and @MichaelJCompton)

___
*[wiki/content/graphql/queries/cascade.md, line 76 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6443#-MHKdF4U5Pk14gMun2Pm:-MHKdF4VCXtlkpkzbvcP:b-yxcq1r) ([raw file](https://github.com/dgraph-io/dgraph/blob/f14c283fd693fd8cc711c480f7e41f4eee4cef33/wiki/content/graphql/queries/cascade.md#L76)):*
> ```Markdown
> }
> ```
> The cascading nature of field selection is overwritten by a nested @casecade. 
> ```

spelling is `@cascade`

**Pull request merged**
