### PR TITLE
Feature * P *

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1061)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 169 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXtBq9k2KE5otszBQG:-KnXtBq9k2KE5otszBQH:b-7hrjyy) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L169)):*
> ```Go
> 	for _, nq := range nquads {
> 		// We dont want to assign uids to these.
> 		if nq.Subject == x.DeletePredicate {
> ```

x.All

---

*[cmd/dgraph/main.go, line 210 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXtFEcs4BkPxJ2lkrs:-KnXtFEcs4BkPxJ2lkrt:b-7hrjyy) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L210)):*
> ```Go
> 	var wnq rdf.NQuad
> 	for _, nq := range nquads {
> 		if nq.Subject == x.DeletePredicate {
> ```

x.All

---

*[cmd/dgraph/main.go, line 262 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXt_pv26dvlZmRI1bu:-KnXt_pv26dvlZmRI1bv:b-x740ul) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L262)):*
> ```Go
> 			newEdges = append(newEdges, edge)
> 		} else if mu.Op == protos.DirectedEdge_DEL {
> 			if mu.Attr != x.DeleteAllPredicates {
> ```

x.All / x.Star. Star might be better.

---

*[cmd/dgraph/main.go, line 264 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXuSOEKd2s9R_1jNcR:-KnXuSOEKd2s9R_1jNcS:b-dsje7s) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L264)):*
> ```Go
> 			if mu.Attr != x.DeleteAllPredicates {
> 				// This means we want to delete the predicate.
> 				if mu.Entity == 0 && string(mu.GetValue()) == x.DeleteAllObjects {
> ```

Do this directly via KV iterator. Also, for the index.

---

*[worker/index.go, line 32 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxWzz1ZzoiUgPLydP:-KnXxWzz1ZzoiUgPLydQ:bw5lphw) ([raw file](https://github.com/dgraph-io/dgraph/blob/f86a54bd18a3015fe1d4c0b57a506f0805ccafb1/worker/index.go#L32)):*
> ```Go
> )
> 
> func (n *node) rebuildOrDelIndex(ctx context.Context, attr string, indexed bool) error {
> ```

rebuild bool

---

*[worker/index.go, line 34 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxbqDZ_aUh-TravcA:-KnXxbqDZ_aUh-TravcB:b-454i51) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/worker/index.go#L34)):*
> ```Go
> func (n *node) rebuildOrDelIndex(ctx context.Context, attr string,
> 	dir protos.SchemaUpdate_Directive) error {
> 	indexed := dir == protos.SchemaUpdate_INDEX
> ```

No need for this logic.

---

*[worker/index.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXv81ppzl-WJDfrnSc:-KnXv81ppzl-WJDfrnSd:bdrtwd8) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/worker/index.go#L46)):*
> ```Go
> 
> 	if delIndex {
> 		posting.DeleteIndex(ctx, attr)
> ```

Create a function like this for the predicate. And also call DeleteIndex from that.

---

*[worker/index.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxYCdBb1tCK2PeUxY:-KnXxYCdBb1tCK2PeUxZ:bni6j9j) ([raw file](https://github.com/dgraph-io/dgraph/blob/f86a54bd18a3015fe1d4c0b57a506f0805ccafb1/worker/index.go#L48)):*
> ```Go
> 		// wait for synced watermarks if we delete through mutations, but
> 		// it would use by lhmap
> 		posting.DeleteIndex(ctx, attr)
> ```

This should be out of if.

---

*[worker/index.go, line 51 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXx_CNhslOIZpLyZPF:-KnXx_CNhslOIZpLyZPG:b-79dpp7) ([raw file](https://github.com/dgraph-io/dgraph/blob/f86a54bd18a3015fe1d4c0b57a506f0805ccafb1/worker/index.go#L51)):*
> ```Go
> 		return nil
> 	}
> 	if err := posting.RebuildIndex(ctx, attr); err != nil {
> ```

This should not delete anymore.

---

*[worker/mutation.go, line 190 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxxQhbBnk1sDK2DDo:-KnXxxQhbBnk1sDK2DDp:bnp5h9z) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/worker/mutation.go#L190)):*
> ```Go
> }
> 
> func hasData(attr string) bool {
> ```

numEdges(attr string) int { .. }

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061)*

**Comment by pawanrawal** [comment]
Review status: 2 of 12 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 169 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXtBq9k2KE5otszBQG:-KnXziYxs05vqsdsJi94:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L169)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

x.All
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 210 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXtFEcs4BkPxJ2lkrs:-KnXzjBU51_ReDZa3QC2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L210)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

x.All
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 262 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXt_pv26dvlZmRI1bu:-KnXzji3x-YGUseDs0Y3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L262)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

x.All / x.Star. Star might be better.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 264 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXuSOEKd2s9R_1jNcR:-KnYZ9CX6clHB_hvHR_M:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/cmd/dgraph/main.go#L264)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do this directly via KV iterator. Also, for the index.
</blockquote></details>

Done.

---

*[worker/index.go, line 32 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxWzz1ZzoiUgPLydP:-KnYFbjOQ__jlLHi1swq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f86a54bd18a3015fe1d4c0b57a506f0805ccafb1/worker/index.go#L32)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

rebuild bool
</blockquote></details>

Done.

---

*[worker/index.go, line 34 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxbqDZ_aUh-TravcA:-KnYFciL1wilzckBUF_s:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/worker/index.go#L34)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this logic.
</blockquote></details>

Done.

---

*[worker/index.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXv81ppzl-WJDfrnSc:-KnYGnfp5DFs_n0VHYCq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/worker/index.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a function like this for the predicate. And also call DeleteIndex from that.
</blockquote></details>

Done.

---

*[worker/index.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxYCdBb1tCK2PeUxY:-KnYZFjF697mWxsmRG_w:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f86a54bd18a3015fe1d4c0b57a506f0805ccafb1/worker/index.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should be out of if.
</blockquote></details>

Done.

---

*[worker/index.go, line 51 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXx_CNhslOIZpLyZPF:-KnYZGbl2otAzUDbWeK5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f86a54bd18a3015fe1d4c0b57a506f0805ccafb1/worker/index.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should not delete anymore.
</blockquote></details>

Done.

---

*[worker/mutation.go, line 190 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnXxxQhbBnk1sDK2DDo:-KnY1ZR-lP6y6XkBso88:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/74c0459968d8abba06236bd0b0c883076f0539ac/worker/mutation.go#L190)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

numEdges(attr string) int { .. }
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 10 of 13 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 505 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYcQ1D5r6k4Dd4V67B:-KnYcQ1D5r6k4Dd4V67C:b7u566q) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L505)):*
> ```Go
> 		x.AssertTruef(pk.Attr == attr,
> 			"Invalid key obtained for comparison")
> 		uids = append(uids, pk.Uid)
> ```

Don't do anything here for now. Just add a TODO saying that we'll still have this predicate present for the uid.

---

*[posting/index.go, line 511 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYdEptbl5DOibCDte3:-KnYdEptbl5DOibCDte4:b2qwp0p) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L511)):*
> ```Go
> 
> 		if batchSize >= maxBatchSize {
> 			pstore.BatchSet(wb)
> ```

error check here.

---

*[posting/index.go, line 517 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYdG3wMMiSYuonTr0B:-KnYdG3wMMiSYuonTr0C:b-yq3bu8) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L517)):*
> ```Go
> 	}
> 	if len(wb) > 0 {
> 		pstore.BatchSet(wb)
> ```

and here.

---

*[posting/index.go, line 520 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYdGyUQn7PWVRYq9QL:-KnYdGyUQn7PWVRYq9QM:bns9obi) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L520)):*
> ```Go
> 	}
> 
> 	for _, uid := range uids {
> ```

No need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-:-KnYe-B0afhhWDYfup2d:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 10 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 505 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYcQ1D5r6k4Dd4V67B:-KnYeVMEvaI-ES61z6Rs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L505)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't do anything here for now. Just add a TODO saying that we'll still have this predicate present for the uid.
</blockquote></details>

Done.

---

*[posting/index.go, line 511 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYdEptbl5DOibCDte3:-KnYeVlppX3KZq47m-H_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L511)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

error check here.
</blockquote></details>

Done.

---

*[posting/index.go, line 517 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYdG3wMMiSYuonTr0B:-KnYeWHXEH1arCxt2BxR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L517)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

and here.
</blockquote></details>

Done.

---

*[posting/index.go, line 520 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061#-KnYdGyUQn7PWVRYq9QL:-KnYeWvaOGDtUBYKv11U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3b9af6ea9b2cc2ac745291293b94f825758878d/posting/index.go#L520)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1061)*

**Comment by pawanrawal** [comment]
Merged to master

**Pull request closed without merging**
