### PR TITLE
Simple end to end test for the Dgraph server

### PR DESCRIPTION
**Pull request by pawanrawal**
Dgraph server is booted up, a mutation and subsequent query are run. The values are matched against expected values in the mutation.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/183)

### CODE REVIEW

**Comment by jchiu0** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[contrib/queries.sh, line 29 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/183#-KQQ6chBpbZLQEOIhK9V:-KQQ6chCLFHI71uLX0dz:boyn8jg) ([raw file](https://github.com/dgraph-io/dgraph/blob/72ee20348b817934e4d9a40d43686a7e600109b2/contrib/queries.sh#L29)):*
> ```Shell
> popd &> /dev/null
> 
> killall dgraph
> ```

Just curious: isn't dgraph a child process? You just want to be safe?

---

*[contrib/simple-e2e.sh, line 12 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/183#-KQQ7bfHpVG-BMRmR_ck:-KQQ7bfHpVG-BMRmR_cl:b-3few8q) ([raw file](https://github.com/dgraph-io/dgraph/blob/72ee20348b817934e4d9a40d43686a7e600109b2/contrib/simple-e2e.sh#L12)):*
> ```Shell
> # If build variable is empty then we set it.
> if [ -z "$1" ]; then
>   BUILD=$SRC/build
> ```

nit: indent

---

*[contrib/simple-e2e.sh, line 77 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/183#-KQQ7RDEJTdA4D0L68Q9:-KQQ7RDEJTdA4D0L68QA:b-3few8q) ([raw file](https://github.com/dgraph-io/dgraph/blob/72ee20348b817934e4d9a40d43686a7e600109b2/contrib/simple-e2e.sh#L77)):*
> ```Shell
> check_val() {
> 	expected="$1"
>   actual="$2"
> ```

nit: indent

---

*[contrib/simple-e2e.sh, line 79 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/183#-KQQ7TOb0lwDR3uWNsRq:-KQQ7TOb0lwDR3uWNsRr:b-3few8q) ([raw file](https://github.com/dgraph-io/dgraph/blob/72ee20348b817934e4d9a40d43686a7e600109b2/contrib/simple-e2e.sh#L79)):*
> ```Shell
>   actual="$2"
> 	if [ "$expected" != "$actual" ];then
> 	  echo -e "Expected value: $expected. Got: $actual"
> ```

nit: indent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/183)*

**Comment by jchiu0** [comment]
LGTM

Just some indent and one small question. It is ok to ignore the indent.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/183#-:-KQQ7ve2NJSxhi6vEL7Y:b-d5ep7m)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/183#-:-KQQ8TUSqK_TpSfbvnH-:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master with c894dbbfcaa00ebfd6403159da43f84cd6305e09.

**Pull request closed without merging**
