### PR TITLE
Implement /share endpoint

### PR DESCRIPTION
**Pull request by sungwoncho**
* Implement `/share` endpoint to allow mutations on `_share_` predicate without having to specify extra flags.

* Load and run query from cookie. The cookie is shared between `docs.dgraph.io` and `play.dgraph.io` so that users can click 'Visualize' from documentation to open `play.dgraph.io` and have query and graph result auto-populated.

* Refactoring on frontend

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/853)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[cmd/dgraph/dashboard.go, line 114 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3mFgguOPiUQen2VdZ:-Ki3mFgguOPiUQen2Vd_:b-ombmqe) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/dashboard.go#L114)):*
> ```Go
> // Concretely, it checks that the mutation (1) does not have forbidden predicates
> // (2) specifies both the actual query string and its hash
> func validateSharePred(mutation *graphp.Mutation) error {
> ```

Don't think you need this.

---

*[cmd/dgraph/main.go, line 234 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3oosbBxYTHd-TDU9e:-Ki3oosbBxYTHd-TDU9f:b74jo72) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L234)):*
> ```Go
> 
> // InternalShare is the name of a predicate used to store query strings shared from the UI
> const InternalShare = "_share_"
> ```

If this is used exactly once, which I think it is, then you can remove these consts. And below.

---

*[cmd/dgraph/main.go, line 239 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3payMOlco1GF9l_Xf:-Ki3payMOlco1GF9l_Xg:b47vvn4) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L239)):*
> ```Go
> const InternalShareHash = "_share_hash_"
> 
> func ismutationAllowed(ctx context.Context, mutation *graphp.Mutation) error {
> ```

Make this a bool.

---

*[cmd/dgraph/main.go, line 246 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3pQfkaYpH9_A6-tMe:-Ki3pQfkaYpH9_A6-tMf:bnchovw) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L246)):*
> ```Go
> 		}
> 
> 		if err := validateSharePred(mutation); err != nil {
> ```

You don't need this.

---

*[cmd/dgraph/main.go, line 567 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3moCmNTtCZJ1fXT8t:-Ki3moCmNTtCZJ1fXT8u:bfw0maj) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L567)):*
> ```Go
> 
> 	ctx := context.WithValue(context.Background(), "_share_", true)
> 	ctx = context.WithValue(ctx, "debug", r.URL.Query().Get("debug"))
> ```

Don't need this.

---

*[cmd/dgraph/main.go, line 578 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3mtBdVOBtR0Az_SbD:-Ki3mtBdVOBtR0Az_SbE:b89229z) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L578)):*
> ```Go
> 	}
> 
> 	res, err := parseQueryAndMutation(ctx, gql.Request{
> ```

Don't do this. Parse payload as JSON into a Go struct.

---

*[cmd/dgraph/main.go, line 579 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3nJAdA4XmWNHUyIrq:-Ki3nJAdA4XmWNHUyIrr:bfvjgn2) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L579)):*
> ```Go
> 
> 	res, err := parseQueryAndMutation(ctx, gql.Request{
> 		Str:       q,
> ```

make this query a constant.

---

*[cmd/dgraph/main.go, line 580 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3nLGhoUVKyBymf64_:-Ki3nLGhoUVKyBymf64a:byxqjtg) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L580)):*
> ```Go
> 	res, err := parseQueryAndMutation(ctx, gql.Request{
> 		Str:       q,
> 		Variables: map[string]string{},
> ```

Variables are filled by the payload.

---

*[dashboard/src/actions/index.js, line 210 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3o0-nEZjfdTGPGR49:-Ki3o0-nEZjfdTGPGR4A:b-boh11z) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/dashboard/src/actions/index.js#L210)):*
> ```JavaScript
>     mutation {
>         set {
>             <_:share> <_share_> ${stringifiedQuery} .
> ```

Only pass the stringified query to Dgraph. Probably don't even need JSON.

---

*[dashboard/src/actions/index.js, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3nyTB3cbH4h_oCAWd:-Ki3nyTB3cbH4h_oCAWe:b7o7ggt) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/dashboard/src/actions/index.js#L211)):*
> ```JavaScript
>         set {
>             <_:share> <_share_> ${stringifiedQuery} .
>             <_:share> <_share_hash_> "${md5(stringifiedQuery)}" .
> ```

sha256 in Dgraph.

---

*[dashboard/src/actions/index.js, line 295 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3ocvWJ4Zzj3ZXNztP:-Ki3ocvWJ4Zzj3ZXNztQ:b-i2c3lq) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/dashboard/src/actions/index.js#L295)):*
> ```JavaScript
> {
>     query(func:eq(_share_hash_, ${queryHash})) {
>         _uid_
> ```

Just do `_uid_, _share_`. That way you'll also get the stringqueries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/853)*

**Comment by sungwoncho** [comment]
Review status: 6 of 10 files reviewed at latest revision, 11 unresolved discussions.

---

*[cmd/dgraph/dashboard.go, line 114 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3mFgguOPiUQen2VdZ:-Ki4L8EZR-nSuzk98m4r:bt30z0v) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/dashboard.go#L114)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't think you need this.
</blockquote></details>

Please see comment in `ismutationAllowed`

---

*[cmd/dgraph/main.go, line 234 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3oosbBxYTHd-TDU9e:-Ki42uUVLVOLGNbgU8jy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L234)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If this is used exactly once, which I think it is, then you can remove these consts. And below.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 239 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3payMOlco1GF9l_Xf:-Ki4KYrmiDFfULQBZbuj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L239)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Make this a bool.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 246 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3pQfkaYpH9_A6-tMe:-Ki4KhD_fKe4LTyWrOkC:b-eao0ro) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L246)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need this.
</blockquote></details>

I still need a way to check that mutation does not have predicates other than `_share_` and `_share_hash_`. Implemented `hasOnlySharePred` instead.

---

*[cmd/dgraph/main.go, line 567 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3moCmNTtCZJ1fXT8t:-Ki3qYnMImRiH50H8jXw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L567)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't need this.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 578 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3mtBdVOBtR0Az_SbD:-Ki4KFAPdQQuOmc0UsP_:bk1w557) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L578)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't do this. Parse payload as JSON into a Go struct.
</blockquote></details>

Ok, now creating a mutation manually.

---

*[cmd/dgraph/main.go, line 579 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3nJAdA4XmWNHUyIrq:-Ki4KLVEq4SLKNYRFy8N:bf98zkz) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L579)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

make this query a constant.
</blockquote></details>

Now creating a mutation manually. See above.

---

*[cmd/dgraph/main.go, line 580 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3nLGhoUVKyBymf64_:-Ki4KQof9NvMag6bdOjQ:bf98zkz) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L580)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Variables are filled by the payload.
</blockquote></details>

Now creating a mutation manually. See above.

---

*[dashboard/src/actions/index.js, line 210 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3o0-nEZjfdTGPGR49:-Ki4KSQLe8bCA5wz9skl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/dashboard/src/actions/index.js#L210)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Only pass the stringified query to Dgraph. Probably don't even need JSON.
</blockquote></details>

Done.

---

*[dashboard/src/actions/index.js, line 211 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3nyTB3cbH4h_oCAWd:-Ki4KWlok1rik5HCGRxm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/dashboard/src/actions/index.js#L211)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

sha256 in Dgraph.
</blockquote></details>

Done.

---

*[dashboard/src/actions/index.js, line 295 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3ocvWJ4Zzj3ZXNztP:-Ki3sAvnRm0gX0ufPlxe:bs7wun4) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/dashboard/src/actions/index.js#L295)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just do `_uid_, _share_`. That way you'll also get the stringqueries.
</blockquote></details>

Done.'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/853)*

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dgraph/dashboard.go, line 111 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki4PLb-N4IXzpPTyy-F:-Ki4PLb0fis1GjGrvm-m:bdxnmue) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a562ef86283678896e94cc37a840ada36599dfa/cmd/dgraph/dashboard.go#L111)):*
> ```Go
> }
> 
> func hasOnlySharePred(mutation *graphp.Mutation) bool {
> ```

Still don't need it.

---

*[cmd/dgraph/main.go, line 246 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3pQfkaYpH9_A6-tMe:-Ki4NyPpzISXXNmztTcC:b-81j5vx) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L246)):*
<details><summary><i>Previously, sungwoncho (Sung Won Cho) wrote…</i></summary><blockquote>

I still need a way to check that mutation does not have predicates other than `_share_` and `_share_hash_`. Implemented `hasOnlySharePred` instead.
</blockquote></details>

Okay, we still don't need this.

---

*[cmd/dgraph/main.go, line 577 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki4OXay3Zx2PjRsKAjy:-Ki4OXay3Zx2PjRsKAjz:ba3rccq) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a562ef86283678896e94cc37a840ada36599dfa/cmd/dgraph/main.go#L577)):*
> ```Go
> 	queryHash := sha256.Sum256([]byte(strQuery))
> 	mutation := gql.Mutation{
> 		Set: fmt.Sprintf("<_:share> <_share_> %s .\n<_:share> <_share_hash_> \"%x\" .", strQuery, queryHash),
> ```

%q to put quotes around. Also, if the query has quotes, escape them. I think there's a func to escape a string.

---

*[dashboard/src/actions/index.js, line 275 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki4PEJLKt1t2SSH9GEx:-Ki4PEJLKt1t2SSH9GEy:bksgy0i) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a562ef86283678896e94cc37a840ada36599dfa/dashboard/src/actions/index.js#L275)):*
> ```JavaScript
>                     for (let i = 0; i < matchingQueries.length; i++) {
>                         const q = matchingQueries[i];
>                         if (`"${q._share_}"` === stringifiedQuery) {
> ```

You'll probably have to unescape the query here, because we escaped it before storing in Dgraph.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/853)*

**Comment by sungwoncho** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dgraph/dashboard.go, line 111 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki4PLb-N4IXzpPTyy-F:-Ki7SXB8cU0qH3pvWTC3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a562ef86283678896e94cc37a840ada36599dfa/cmd/dgraph/dashboard.go#L111)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Still don't need it.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 246 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki3pQfkaYpH9_A6-tMe:-Ki7SYEenDYwnkcQuoy4:bcplmqp) ([raw file](https://github.com/dgraph-io/dgraph/blob/4f9cb54cd6fb91da2f033fee63d014f2efeccf56/cmd/dgraph/main.go#L246)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Okay, we still don't need this.
</blockquote></details>

You're right. Removed it.

IDEA: maybe we should rename `_share_` key in context to `allowMutation`. But at the moment we only need to allow mutation for sharing, so it is maybe premature to make that change.

---

*[cmd/dgraph/main.go, line 577 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki4OXay3Zx2PjRsKAjy:-Ki7bk4LW_JN5t8j0nxi:beap6nc) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a562ef86283678896e94cc37a840ada36599dfa/cmd/dgraph/main.go#L577)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

%q to put quotes around. Also, if the query has quotes, escape them. I think there's a func to escape a string.
</blockquote></details>

Done.

Turns out, %q even escapes the quotations for us. (https://golang.org/pkg/fmt/#pkg-overview)
No need to escape things like pointy brackets because they all safely appear within quotation if using %q.

---

*[dashboard/src/actions/index.js, line 275 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-Ki4PEJLKt1t2SSH9GEx:-Ki7qZ4FC6hNu81epApm:b-qrbsd) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a562ef86283678896e94cc37a840ada36599dfa/dashboard/src/actions/index.js#L275)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You'll probably have to unescape the query here, because we escaped it before storing in Dgraph.
</blockquote></details>

No longer needed. Please see the comment above regarding %q.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/853)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/853#-:-Ki8VLSwXSkTZP2mmkQv:bnfp4nl)*

**Pull request merged**
