### PR TITLE
Remove date type

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1017)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm: Could you remove date from docs too?

---

Review status: 0 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017#-:-Klvwku4x5bIWpLI5AJB:bp6b3gf)*

**Comment by manishrjain** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 2276 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017#-Klw0NJB-cAbwYIAfvrL:-Klw0NJB-cAbwYIAfvrM:b9o06xt) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5a3175d4af50358957f49be5145fedfe8446442/query/query_test.go#L2276)):*
> ```Go
> 	js := processToFastJSON(t, query)
> 	require.JSONEq(t,
> 		`{"me":[{"friend":[{"dob":"1910-01-02T00:00:00Z"},{"dob":"1909-05-05T00:00:00Z"},{"dob":"1909-01-10T00:00:00Z"},{"dob":"1901-01-15T00:00:00Z"}],"maxdob":"1910-01-02T00:00:00Z","mindob":"1901-01-15T00:00:00Z","name":"Michonne"},{"friend":[{"dob":"1910-01-01T00:00:00Z"}],"maxdob":"1910-01-01T00:00:00Z","mindob":"1910-01-01T00:00:00Z","name":"Rick Grimes"},{"friend":[{"dob":"1909-05-05T00:00:00Z"}],"maxdob":"1909-05-05T00:00:00Z","mindob":"1909-05-05T00:00:00Z","name":"Andrea"},{"name":"Andrea With no friends"}]}`,
> ```

If it's really 00:00:00Z, then we can just drop it entirely, and just return the date, no?

---

*[rdf/parse.go, line 417 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017#-Klw-QtYTvsrdjjtT70O:-Klw-QtYTvsrdjjtT70P:b-v8wfca) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6ba1687f2d64d202ad660d76b5a36c689c9d322/rdf/parse.go#L417)):*
> ```Go
> 	"xs:string":                                   types.StringID,
> 	"xs:dateTime":                                 types.DateTimeID,
> 	"xs:date":                                     types.DateID,
> ```

This can still be mapped to types.DateTimeID, no? We don't want to lose support for a RDF data type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017)*

**Comment by ashwin95r** [comment]
Done.

---

Review status: 20 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 2276 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017#-Klw0NJB-cAbwYIAfvrL:-Klw1bULwcnuDxJXn9tV:b-7kzwxi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5a3175d4af50358957f49be5145fedfe8446442/query/query_test.go#L2276)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If it's really 00:00:00Z, then we can just drop it entirely, and just return the date, no?
</blockquote></details>

I think keeping it consistent will help in parsing at the client side.

---

*[rdf/parse.go, line 417 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017#-Klw-QtYTvsrdjjtT70O:-Klw1FzkaXArDqn_1cNF:brgq1k0) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6ba1687f2d64d202ad660d76b5a36c689c9d322/rdf/parse.go#L417)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This can still be mapped to types.DateTimeID, no? We don't want to lose support for a RDF data type.
</blockquote></details>

Sure. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017#-:-Klw2NP3HblQFCSyx-aY:b-896fix)*

**Comment by tzdybal** [comment]
:lgtm:

---

Reviewed 20 of 21 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1017#-:-Klw7TqgQB1t5zP_YouX:bnfp4nl)*

**Comment by MichaelJCompton** [comment]
There's a mix here of `"dateTime"` and `"datetime"` strings.  Parser accepts `"datetime"`?  Is that to distinguish the dgraph type from `xs:dateTime` or would it be more consistent to also have `dateTime` as the dgraph type?

Also, if it's `datetime`, should line 74 of scalar_types.go read `return "datetime"`?

**Comment by ashwin95r** [comment]
@MichaelJCompton We have made the schematype to be case insensitive. So any casing of `datetime`  should work now. Merged to master.

**Pull request closed without merging**
