### PR TITLE
Fast tojson

### PR DESCRIPTION
**Pull request by ashishnegi**
1. Moved the `outputnode` code to separate file `outputnode.go`
2. Added byte version of subgraph to json conversion.

`FastToJSON` is around 2 times faster than the current `ToJSON`.

Need to work on testing :
1. Refactoring current tests.
2. Valid json.
3. Right json generation comparing to current `ToJSON`.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/475)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGG6M9uRPt9oXUwltS:-KaGG6M9uRPt9oXUwltT:b-hpyb5h) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L232)):*
> ```Go
> 	case types.Int32ID:
> 		// are we always sure that v.Value is an int ?
> 		return []byte(fmt.Sprintf("\"%d\"", v.Value)), nil
> ```

For int, we shouldn't really have quotes around JSON right?

---

*[query/outputnode.go, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGGA3yH7nO1m5S3v9T:-KaGGA3yH7nO1m5S3v9U:b-vrgf76) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L234)):*
> ```Go
> 		return []byte(fmt.Sprintf("\"%d\"", v.Value)), nil
> 	case types.FloatID:
> 		return []byte(fmt.Sprintf("\"%f\"", v.Value)), nil
> ```

Same for float. We shouldn't really have quotes around it.

---

*[query/outputnode.go, line 237 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGGQXux7hjT4xfXD5h:-KaGGQXux7hjT4xfXD5i:b-7q1ru1) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L237)):*
> ```Go
> 	case types.BoolID:
> 		if v.Value.(bool) == true {
> 			return []byte("\"true\""), nil
> ```

No quotes around bool either.

---

*[query/outputnode.go, line 241 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGGS1ctJWiVJZB8AQW:-KaGGS1ctJWiVJZB8AQX:b6jfgvu) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L241)):*
> ```Go
> 		return []byte("\"false\""), nil
> 	case types.StringID:
> 		return []byte("\"" + v.Value.(string) + "\""), nil
> ```

fmt.Sprintf("%q", v.Value.(string))

---

*[query/outputnode.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGJogro-2z6xj2A7jC:-KaGJogsrdezF9FPrvay:bp3od52) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L247)):*
> ```Go
> 		return []byte("\"Need to figure it out.\""), nil
> 	case types.UidID:
> 		return []byte(fmt.Sprintf("%#x", v.Value)), nil
> ```

This would be a string, so use the quotes around it.

---

*[query/outputnode.go, line 253 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGK0gyJq0UYHf3Sall:-KaGK0gyJq0UYHf3Salm:bnylwlh) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L253)):*
> ```Go
> }
> 
> func (fj *fastJsonNode) fastJsonNodeToJSON() []byte {
> ```

Encode it so that all the attributes are put first, then the children.

Also, call it `encode()`

---

*[query/outputnode.go, line 260 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMbuSoBbdM-0FnlXO:-KaGMbuSoBbdM-0FnlXP:bye0uae) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L260)):*
> ```Go
> 		for _, vi := range v {
> 			if !first {
> 				buf.WriteString(",")
> ```

buf.WriteRune(',')

---

*[query/outputnode.go, line 265 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMdHxoRCS9wM3y_7n:-KaGMdHxoRCS9wM3y_7o:bye1umf) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L265)):*
> ```Go
> 			buf.Write(vi)
> 		}
> 		buf.WriteString("]")
> ```

buf.WriteRune(']')

---

*[query/outputnode.go, line 277 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMOKmf2DI9o5UAz6r:-KaGMOKmf2DI9o5UAz6s:b-b38e4u) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L277)):*
> ```Go
> 		}
> 		first = false
> 		buf.WriteString("\"" + k + "\"")
> ```

buf.WriteRune('"'); buf.WriteString(k); buf.WriteRune('"'); buf.WriteRune(':')

---

*[query/outputnode.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGK7jA_HAxB02yAPOF:-KaGK7jA_HAxB02yAPOG:bp3o81w) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L286)):*
> ```Go
> }
> 
> func (sg *SubGraph) FastToJSON(l *Latency) ([]byte, error) {
> ```

ToFastJSON

---

*[query/query_test.go, line 2482 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMASX0TzZbTnJvuhD:-KaGMASX0TzZbTnJvuhE:bahrr67) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/query_test.go#L2482)):*
> ```Go
> 	var l Latency
> 	js, _ := sg.FastToJSON(&l)
> 	fmt.Println("fasttojson:", string(js))
> ```

For FastJSON testing, ensure that the final output is parseable by JSON (Unmarshal).

---

*[query/query_test.go, line 2505 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMuV_w9EynexA8N3T:-KaGMuVa-5Pk9cQD8D6I:b-97gmwd) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/query_test.go#L2505)):*
> ```Go
> 	`
> 
> 	sgFastJson := makeSubgraph(query, t)
> ```

sg := makeSubgraph(..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/475)*

**Comment by ashishnegi** [comment]
Review status: 1 of 4 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGG6M9uRPt9oXUwltS:-KaM0rvPQKh0fWHbyHu7:b-5xordu) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L232)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

For int, we shouldn't really have quotes around JSON right?
</blockquote></details>

The current json marshal output does have quotes around integer.
`,"friend":[{"_uid_":"0x2","age":"56","name":` one of the output of `ToJSON`.. see `age`.
The standard JSON has int without quotes.

In current PR, if we are keeping the old code for time being, then in the tests i am matching output of `ToJSON` and `FastToJSON`.. So we can fix this int and float quote bugs as separate issue.

---

*[query/outputnode.go, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGGA3yH7nO1m5S3v9T:-KaMabEZkzZlEqmEvZ-1:btohx1z) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L234)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Same for float. We shouldn't really have quotes around it.
</blockquote></details>

current json marshal gives in quotes. same as bool and ints

---

*[query/outputnode.go, line 237 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGGQXux7hjT4xfXD5h:-KaM2YgEZlH146FyYZaH:b-h21v0p) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L237)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No quotes around bool either.
</blockquote></details>

JSON standard does not have quotes around bool. 
current json marshal gives `..."_uid_":"0x1","alive":"true","friend":[{"_uid_":"0x17",...`
so we can keep the quotes for a while.

---

*[query/outputnode.go, line 241 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGGS1ctJWiVJZB8AQW:-KaMaghqr4MI-q7GHQYs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L241)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

fmt.Sprintf("%q", v.Value.(string))
</blockquote></details>

Done.

---

*[query/outputnode.go, line 247 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGJogro-2z6xj2A7jC:-KaM2xMyQGVSf7h4Mpv4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L247)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This would be a string, so use the quotes around it.
</blockquote></details>

Done.

---

*[query/outputnode.go, line 253 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGK0gyJq0UYHf3Sall:-KaMKAi7B5UazUQKXsFu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L253)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Encode it so that all the attributes are put first, then the children.

Also, call it `encode()`
</blockquote></details>

Done.

---

*[query/outputnode.go, line 260 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMbuSoBbdM-0FnlXO:-KaMahu9KLNp8ftaEuFx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L260)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

buf.WriteRune(',')
</blockquote></details>

Done.

---

*[query/outputnode.go, line 265 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMdHxoRCS9wM3y_7n:-KaMaiPPlWDJb8AQzcQ7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L265)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

buf.WriteRune(']')
</blockquote></details>

Done.

---

*[query/outputnode.go, line 277 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMOKmf2DI9o5UAz6r:-KaMaXB9GCFTVUPXJKGC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L277)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

buf.WriteRune('"'); buf.WriteString(k); buf.WriteRune('"'); buf.WriteRune(':')
</blockquote></details>

Done.

---

*[query/outputnode.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGK7jA_HAxB02yAPOF:-KaM5c6aObuIbtIRH06y:b9wi57p) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L286)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ToFastJSON
</blockquote></details>

`FastToJSON` implies `ToJSON`'s faster version..
`ToFastJSON` implies to `faster json`.. 
should it be `FasterTOJSON` ?
 

---

*[query/query_test.go, line 2482 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMASX0TzZbTnJvuhD:-KaMaZPVmNy9ucPnGveV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/query_test.go#L2482)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

For FastJSON testing, ensure that the final output is parseable by JSON (Unmarshal).
</blockquote></details>

Done.

---

*[query/query_test.go, line 2505 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGMuV_w9EynexA8N3T:-KaMa_r8oqRsWSvi7c3P:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/query_test.go#L2505)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

sg := makeSubgraph(..)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/475)*

**Comment by manishrjain** [comment]
:lgtm: Can you put the benchmarks in a comment in the code somewhere? Maybe when you introduce the fastJsonNode struct. Also: One small comment. Address that before submitting.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGK7jA_HAxB02yAPOF:-KaPl2gIK3eigXKJkYtp:bnwtw5e) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L286)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

`FastToJSON` implies `ToJSON`'s faster version..
`ToFastJSON` implies to `faster json`.. 
should it be `FasterTOJSON` ?
 
</blockquote></details>

We have ToProtoBuf, so ToFastJSON makes sense in that respect. Understand your point, but having To in the front makes the API consistent.

---

*[query/outputnode.go, line 257 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaPllx4TxAvIwOnmzwV:-KaPllx4TxAvIwOnmzwW:bz8epoy) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c804ba7a2f91e7bfb436da597ab2ab1f6d89eab/query/outputnode.go#L257)):*
> ```Go
> }
> 
> type stringW []string
> ```

No need for this. There is already a sort.String function that you can use.

---

*[query/outputnode_test.go, line 2 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaPlasS6LFgfTIyJWTZ:-KaPlasS6LFgfTIyJWT_:b-54upmf) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c804ba7a2f91e7bfb436da597ab2ab1f6d89eab/query/outputnode_test.go#L2)):*
> ```Go
> /*
>  * Copyright 2017 DGraph Labs, Inc.
> ```

Dgraph Labs. Small g.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-:-KaPlyY70ppM1FVObcvm:bdj94rj)*

**Comment by ashishnegi** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaGK7jA_HAxB02yAPOF:-KaWHkcAjOnr5FU0l5X3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ce1b2852e56f3f7579166cf16cf6a34d3c25394/query/outputnode.go#L286)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We have ToProtoBuf, so ToFastJSON makes sense in that respect. Understand your point, but having To in the front makes the API consistent.
</blockquote></details>

Done.

---

*[query/outputnode.go, line 257 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaPllx4TxAvIwOnmzwV:-KaWHp2PFvy3hUj6grtr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c804ba7a2f91e7bfb436da597ab2ab1f6d89eab/query/outputnode.go#L257)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this. There is already a sort.String function that you can use.
</blockquote></details>

Done.

---

*[query/outputnode_test.go, line 2 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-KaPlasS6LFgfTIyJWTZ:-KaWHm12VHxDU8EgMLvP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c804ba7a2f91e7bfb436da597ab2ab1f6d89eab/query/outputnode_test.go#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Dgraph Labs. Small g.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/475)*

**Comment by ashishnegi** [comment]
One test failing because of json marshalling of `date` :
```
	-       (string) (len=3) "dob": (string) (len=10) "1909-05-05",
	+       (string) (len=3) "dob": (string) (len=20) "1909-05-05T00:00:00Z",
```
Need to ask about this.

**Comment by manishrjain** [comment]
For the date data type, we only go until the date, not until time on the day. For datetime, we go up to seconds.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-:-KaWSIKJyeSID9a-ziHm:b3khak1)*

**Comment by ashwin95r** [comment]
:lgtm: Some formatting issues in tests which can be fixed.

---

Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/outputnode_test.go, line 282 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-Ka_fuKOFWnbQjtaCAW4:-Ka_fuKOFWnbQjtaCAW5:b9xlrcq) ([raw file](https://github.com/dgraph-io/dgraph/blob/534a51faa61d1c277b338e92c5b6788e4faf8028/query/outputnode_test.go#L282)):*
> ```Go
> 					_uid_
> 					name
>                                         friend {
> ```

Some formatting issue. Tab vs space?

---

*[query/outputnode_test.go, line 325 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-Ka_gC5S1gtGB82pGpBl:-Ka_gC5S1gtGB82pGpBm:bwbxbfo) ([raw file](https://github.com/dgraph-io/dgraph/blob/534a51faa61d1c277b338e92c5b6788e4faf8028/query/outputnode_test.go#L325)):*
> ```Go
> 					_uid_
> 					name
>                                         friend @filter(anyof("name", "Rhee")) {
> ```

Formatting.

---

*[query/outputnode_test.go, line 452 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-Ka_gJfEmLqOmkk7v9T4:-Ka_gJfFRIBvg3P7r8rf:bwbxbfo) ([raw file](https://github.com/dgraph-io/dgraph/blob/534a51faa61d1c277b338e92c5b6788e4faf8028/query/outputnode_test.go#L452)):*
> ```Go
> 					_uid_
> 					name
> 				        friend {
> ```

Formatting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/475#-:-Ka_g2vzT69dSCdNJ3Sn:bn83l76)*

**Pull request closed without merging**
