### PR TITLE
Get nodes from sync.Pool

### PR DESCRIPTION
**Pull request by pawanrawal**
Unfortunately, the change doesn't work as expected because when releasing nodes their content is emptied. Since Node children are also pointers, their content is emptied too. Tests also fail because of this. I wanted to get an idea of whether there something wrong that I am doing here?

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/150)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 294 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciSfgnmPauwiPbPlZ:-KOciSfgnmPauwiPbPl_:b-7o5rva) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L294)):*
> ```Go
> }
> 
> func release(n *graph.Node) {
> ```

This would not be able to retrieve the child nodes. You should do an iterative (not recursive, because cheaper) post-traverse on the child nodes to get all the children and put them in the pool.

---

*[query/query.go, line 332 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciMyuX_CF51S2_zWB:-KOciMyuX_CF51S2_zWC:bnvu790) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L332)):*
> ```Go
> 			for i := 0; i < ul.UidsLength(); i++ {
> 				uid := ul.Uids(i)
> 				uc := newGraphNode()
> ```

Why add a function call for one-liner?

---

*[query/query.go, line 341 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciBLbMx80vqAGa71W:-KOciBLbMx80vqAGa71X:b-pekn8j) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L341)):*
> ```Go
> 				}
> 				children = append(children, uc)
> 				release(uc)
> ```

You can't release them here. You should only release the Node pointer once preTraverse is over and the result is fully used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150)*

**Comment by pawanrawal** [comment]
Can see around 30% less memory consumption while comparing benchmarks. Time seems to have increased a bit. Also found the recursive approach of releasing nodes to be faster than the iterative approach on comparing benchmarks.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 294 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciSfgnmPauwiPbPlZ:-KOdUPM86lYBJWGUSeSB:b-pjewu8) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L294)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This would not be able to retrieve the child nodes. You should do an iterative (not recursive, because cheaper) post-traverse on the child nodes to get all the children and put them in the pool.
</details>
Done now, using a stack to go through the tree here. Did you have something similar in mind?

---

*[query/query.go, line 332 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciMyuX_CF51S2_zWB:-KOdUX0Ywy3Jx7Pwn_B8:bwmtthw) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L332)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why add a function call for one-liner?
</details>
Not a one line function anymore.

---

*[query/query.go, line 341 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciBLbMx80vqAGa71W:-KOdU_27lEnlDuhsiJSV:bj4sbkh) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L341)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can't release them here. You should only release the Node pointer once preTraverse is over and the result is fully used.
</details>
Releasing in `toProtocolBuffer` now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOdUtgk_kEvXOkualIT:b-xcs15d)*

**Comment by manishrjain** [comment]
Numbers? Or this is observational? You can also do memory profiling along with CPU profiling, btw.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 294 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciSfgnmPauwiPbPlZ:-KOdX-DGIMicT9BMlZHs:be57td3) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L294)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Done now, using a stack to go through the tree here. Did you have something similar in mind?
</details>
I did. But, looking at the implementation, I can see why this is inefficient. Let's solve this in Go way.

Create a package wide internal buffered channel (say, ch). Then do this:

ch := make(chan *graph.Node, 1000)

func release() {
  for n := range ch {
    for i := 0; i < len(n.Children); i++ { ch <- n.Children[i] }
    nodePool.Put(n)
  }
}
go release()

Then within your function,​ you can call `select {ch <- root: // pass; default: delete root}`. This should not use up any cycles from the main loop, and you can just allocate the channel memory once, instead of on every call to release.

---

*[query/query.go, line 332 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciMyuX_CF51S2_zWB:-KOdYMG2MHU013eaDmfn:b29mvx8) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L332)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Not a one line function anymore.
</details>
It would be one-liner again, if you address my comment.

---

*[query/query.go, line 292 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYBppCk0UV-X73zB9:-KOdYBpq0n7fpeKd1MuS:b-831x1) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L292)):*
> ```Go
> func newGraphNode() *graph.Node {
> 	n := nodePool.Get().(*graph.Node)
> 	*n = graph.Node{}
> ```

You can do this initialization in the loop mentioned below, before doing the Put to pool. This would avoid a small cycle when allocating memory.

---

*[query/query.go, line 395 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYZeYnGbNMdS1sZI7:-KOdYZeYnGbNMdS1sZI8:b-vethx3) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L395)):*
> ```Go
> 	}
> 
> 	release(n)
> ```

You can't release it here! It is being returned to the caller. Release it once it's job is done. Think of release as a `delete n`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOdVjZ59NJ01oM6Ckhi:b-svrln1)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 310 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYkoB0eZ4KsxkZa8k:-KOdYkoB0eZ4KsxkZa8l:bnijbe2) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L310)):*
> ```Go
> 			nodes = append(nodes, n.Children[i])
> 		}
> 	}
> ```

This could also be done using goroutines and recursion. Similar to the approach in processgraph(), where we start a new goroutine for every child. Not sure if it would improve the performance, but would be something to look at.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 395 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYZeYnGbNMdS1sZI7:-KOddQ3-_BMj7tuSejAz:bkmi20n) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L395)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can't release it here! It is being returned to the caller. Release it once it's job is done. Think of release as a `delete n`.
</details>
Hmm, once its marshalled to a byte slice I can release it, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 395 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYZeYnGbNMdS1sZI7:-KOdhAsOtGulkaDhwZjU:bb7867z) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L395)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, once its marshalled to a byte slice I can release it, right?
</details>
Yup.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150)*

**Comment by pawanrawal** [comment]
On running the benchmarks before and after the change and doing memory profiling, I can see that the `ns/op` seems to have improved by 20-30%. Can see minor improvements(<10%) in bytes allocated. Though when I do the memory profiling then I can see much less memory is allocated to run the test.

---

Review status: 0 of 5 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 294 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciSfgnmPauwiPbPlZ:-KOhesvc9TyJcipENVDE:bvwup2s) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L294)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I did. But, looking at the implementation, I can see why this is inefficient. Let's solve this in Go way.
> 
> Create a package wide internal buffered channel (say, ch). Then do this:
> 
> ch := make(chan *graph.Node, 1000)
> 
> func release() {
>   for n := range ch {
>     for i := 0; i < len(n.Children); i++ { ch <- n.Children[i] }
>     nodePool.Put(n)
>   }
> }
> go release()
> 
> Then within your function,​ you can call `select {ch <- root: // pass; default: delete root}`. This should not use up any cycles from the main loop, and you can just allocate the channel memory once, instead of on every call to release.
</details>
Done. There isn't a delete operator for pointers in Go.

---

*[query/query.go, line 332 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOciMyuX_CF51S2_zWB:-KOhf-iHiie6-9lNvj0Y:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1ad8bd18c84d13889d7dea7a03cf75e9b418eccd/query/query.go#L332)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> It would be one-liner again, if you address my comment.
</details>
Done.

---

*[query/query.go, line 292 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYBppCk0UV-X73zB9:-KOhf5vodJwNvnXULAPM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L292)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can do this initialization in the loop mentioned below, before doing the Put to pool. This would avoid a small cycle when allocating memory.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOhfBqZ17dIJLzADt3T:b-cxbhtd)*

**Comment by manishrjain** [comment]
20-30% improvement? That's great. Can you please add the before and after numbers in a README? It's good to track performance optimizations like these, because at some point later, we're definitely going to wonder why are we using free lists.

---

Reviewed 2 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 389 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhtMSsk5VRjUeWWXNA:-KOhtMSsk5VRjUeWWXNB:b-b5440w) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8cbb3126c6f0baa9cec7d22134540968ec261fd/cmd/dgraph/main.go#L389)):*
> ```Go
> 	// Grpc server runs on (port + 1)
> 	go runGrpcServer(fmt.Sprintf(":%d", *port+1))
> 	go query.InitRelease()
> ```

You don't need to do this here.

---

*[query/codec.go, line 10 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhci4ZYdRi_C1uTnvp-r3-10:-KOhrnjY0mOdwgJXVEMo:b-v17ilp) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/codec.go#L10)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported type Codec should have comment or be unexported
</details>
Please address this.

---

*[query/codec.go, line 12 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhci4ZYdRi_C1uTnvp-r3-12:-KOhrrgJOtWjm4J5P-Gg:b-v17ilp) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/codec.go#L12)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Codec.Marshal should have comment or be unexported
</details>
Please address this.

---

*[query/codec.go, line 32 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhci4ZYdRi_C1uTnvp-r3-32:-KOhru7qZHrqK2RPU6Yd:b-v17ilp) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/codec.go#L32)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Codec.Unmarshal should have comment or be unexported
</details>
Please address this.

---

*[query/query.go, line 310 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYkoB0eZ4KsxkZa8k:-KOhsMft2pFrBNKSVLar:b-69qx0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L310)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> This could also be done using goroutines and recursion. Similar to the approach in processgraph(), where we start a new goroutine for every child. Not sure if it would improve the performance, but would be something to look at.
</details>
Think you can close this comment now.

---

*[query/query.go, line 306 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOcfaAKaxSSZ8NPrenE-r3-306:-KOhsDGoYwp8a2vBeFa2:bj3cacr) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/query.go#L306)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function InitRelease should have comment or be unexported
</details>
Please address.

---

*[query/query.go, line 309 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhsYWoxJDP3JptXaPY:-KOhsYWoxJDP3JptXaPZ:b-zarfkk) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8cbb3126c6f0baa9cec7d22134540968ec261fd/query/query.go#L309)):*
> ```Go
> func InitRelease() {
> 	nodeCh = make(chan *graph.Node, 1000)
> 	release()
> ```

You can just do package level initialization instead. Run this in init() http://stackoverflow.com/questions/17733220/go-package-initialization.

---

*[query/query_test.go, line 475 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOht7Ydg40E8s-0erKc:-KOht7Ydg40E8s-0erKd:b-tkeyr8) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8cbb3126c6f0baa9cec7d22134540968ec261fd/query/query_test.go#L475)):*
> ```Go
> func BenchmarkToJSON_1000_Director(b *testing.B) { benchmarkToJson("benchmark/directors1000.bin", b) }
> 
> func benchmarkToPB(file string, b *testing.B) {
> ```

Can you add the output of this benchmark in a README in query package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOhtQC_ndyn-I74Iz9F:b-d64lrs)*

**Comment by pawanrawal** [comment]
Well, something funny is going on here. Actually ns/op goes up even for ToJSON functions I don't know why. bytes allocated don't change at all. Though, when I run the memory profiling file through pprof, I can see a lot less memory is allocated after the changes. I have attached the files, can we have a look at this together?

---

Review status: 2 of 10 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 389 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhtMSsk5VRjUeWWXNA:-KOi4iBjQf2gHnVwBuyZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8cbb3126c6f0baa9cec7d22134540968ec261fd/cmd/dgraph/main.go#L389)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You don't need to do this here.
</details>
Done.

---

*[query/codec.go, line 10 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhci4ZYdRi_C1uTnvp-r3-10:-KOi4j-eChIxcyBVqa8v:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/codec.go#L10)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Please address this.
</details>
Done.

---

*[query/codec.go, line 12 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhci4ZYdRi_C1uTnvp-r3-12:-KOi4jQB7btlQ_ZS-SCc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/codec.go#L12)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Please address this.
</details>
Done.

---

*[query/codec.go, line 32 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhci4ZYdRi_C1uTnvp-r3-32:-KOi4jy9FQUo5hVcuAHu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/codec.go#L32)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Please address this.
</details>
Done.

---

*[query/query.go, line 310 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOdYkoB0eZ4KsxkZa8k:-KOi4kgy9ooqNywJ2XOG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/39c5117e3f4f38afe2ceb8b2bccfcdb8b66fb0a5/query/query.go#L310)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Think you can close this comment now.
</details>
Done.

---

*[query/query.go, line 306 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOcfaAKaxSSZ8NPrenE-r3-306:-KOi4lKgekBOvb7tQjcO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac967c2df23d9b3214d3062a125e4ea5edc78c/query/query.go#L306)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Please address.
</details>
Done.

---

*[query/query.go, line 309 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOhsYWoxJDP3JptXaPY:-KOi4lxni0LNlKFUXKHc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8cbb3126c6f0baa9cec7d22134540968ec261fd/query/query.go#L309)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can just do package level initialization instead. Run this in init() http://stackoverflow.com/questions/17733220/go-package-initialization.
</details>
Done.

---

*[query/query_test.go, line 475 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-KOht7Ydg40E8s-0erKc:-KOi4o4mrCtCSzC68XZR:b-tyjiab) ([raw file](https://github.com/dgraph-io/dgraph/blob/c8cbb3126c6f0baa9cec7d22134540968ec261fd/query/query_test.go#L475)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Can you add the output of this benchmark in a README in query package.
</details>
Attached the files, doesn't show improvement. I think I messed up the ordering while running benchcmp previously.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOi4-Lr3BKeclaot4P5:b71jo8n)*

**Comment by pawanrawal** [comment]
Checked the benchmarks after this change. There is a 1-2% increase in ns/op. So probably not that good a change. In some cases there is a 4-5% decrease in bytes allocated compared to using sync.Pool.

---

Review status: 1 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOieCmr_2u7WQFwLNb_:b-b72yag)*

**Comment by pawanrawal** [comment]
Added result to README.

---

Review status: 2 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOikBRiA9fxjYYvY7_j:bisoexl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/150#-:-KOilqoBSs9KnfiPOgqB:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to develop with commit 0545396b62445e5c018f1c40cb8d0e8e8b7c0503

**Pull request closed without merging**
