### PR TITLE
Fix query parser

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/275)

### CODE REVIEW

**Comment by pawanrawal** [comment]
I wonder how come it was considered a mutation even though the word mutation wasn't there? Any ideas on that?

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser_test.go, line 53 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/275#-KThuEVMMjFqD2aswxJn:-KThuEVMMjFqD2aswxJo:btwacxl) ([raw file](https://github.com/dgraph-io/dgraph/blob/4501b9f451e16ceb71f68217d5895751d4fa73d7/gql/parser_test.go#L53)):*
> ```Go
> }
> 
> func TestParseiError(t *testing.T) {
> ```

`Parsei` intentional?

---

*[gql/parser_test.go, line 59 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/275#-KThuK8ldvzdS8mF3uJY:-KThuK8ldvzdS8mF3uJZ:behdx2z) ([raw file](https://github.com/dgraph-io/dgraph/blob/4501b9f451e16ceb71f68217d5895751d4fa73d7/gql/parser_test.go#L59)):*
> ```Go
> 				name
> 			}
> 			gender,age
> ```

Is this allowed having a comma?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/275#-:-KThu7aC3oAELlcQuOIV:b-j7qxhu)*

**Comment by ashwin95r** [comment]
It's not really a mutation, both gq and mu are nil and hence this part of the coe is reached: https://github.com/dgraph-io/dgraph/blob/master/cmd/dgraph/main.go#L408. We didn't handle the error before.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser_test.go, line 53 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/275#-KThuEVMMjFqD2aswxJn:-KTiHFFTzk8mbNsgr5jS:b-ss7tb5) ([raw file](https://github.com/dgraph-io/dgraph/blob/4501b9f451e16ceb71f68217d5895751d4fa73d7/gql/parser_test.go#L53)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> `Parsei` intentional?
</details>
Nope. Done.

---

*[gql/parser_test.go, line 59 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/275#-KThuK8ldvzdS8mF3uJY:-KTiHJyJN0PQCk-UvN_Z:bb9fcmg) ([raw file](https://github.com/dgraph-io/dgraph/blob/4501b9f451e16ceb71f68217d5895751d4fa73d7/gql/parser_test.go#L59)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Is this allowed having a comma?
</details>
Yeah, commas are allowed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/275#-:-KTiJ7vi8t7APVNdrZ0q:bmq8rj1)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/275#-:-KTiP5mjP3C8CxyAt6PJ:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master with commit 8e1e2c76bbcbb0447adab85e4366852fddf571fb.

**Pull request closed without merging**
