### PR TITLE
feat(GraphQL): Add support for Geo point type in Graphql.

### PR DESCRIPTION
**Pull request by arijitAD**
Fixes GRAPHQL-682

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6481)

 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-9fe33a88e2-99860.surge.sh)

### CODE REVIEW

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
We should add a rule to mark `Point` as a reserved type name, I guess adding `Point`to `isReservedKeyWord` function in `rules.go` and also to `forbiddenInputTypeNames` inside `inputTypeNameValidation` function should suffice. And test for the same that one can't add a type named `Point` in their schema.

> Reviewed 20 of 63 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-:-MIKvqf75C-gWU6_kNHs:brw25yv)* status: 20 of 63 files reviewed, 7 unresolved discussions (waiting on @arijitAD, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/add_mutation_test.yaml, line 21 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKoXPxEAapdqIhGOd_:-MIKoXPyDbYSjhH2sJPe:ba3eon8) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/resolve/add_mutation_test.yaml#L21)):*
> ```
> A uid and type should get injected and all data transformed to
>     underlying Dgraph edge names
> ```
stale message
___
*[graphql/resolve/resolver.go, line 1252 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKqj3j5o9C_0emYsxT:-MIKqj3j5o9C_0emYsxU:bbpjy0z) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/resolve/resolver.go#L1252)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> if field.ResponseName() == "longitude" {
> 			x.Check2(buf.WriteString(longitude))
> 		} else if field.ResponseName() == "latitude" {
> 			x.Check2(buf.WriteString(latitude))
> 		}
> ```
</details>

we sohuld convert this part to a `switch` case.
___
*[graphql/resolve/resolver.go, line 1255 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKq_BB2vkc_WkF6XWl:-MIKq_BB2vkc_WkF6XWm:b-3d3jr6) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/resolve/resolver.go#L1255)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> else {
> 			return nil, x.GqlErrorList{&x.GqlError{
> 				Message:   "Invalid field for Geo type",
> 				Locations: []x.Location{field.Location()},
> 				Path:      copyPath(path),
> 			}}
> 		}
> ```
</details>

we will never get this else case, because we didn't define any other fields in the schema for `Point` type. If someone tried that, it would fail at parser level validation itself.
___
*[graphql/schema/dgraph_schemagen_test.yml, line 616 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKtel7DX3YELilBHG8:-MIKtel7DX3YELilBHG9:b-8eqlzc) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/dgraph_schemagen_test.yml#L616)):*
> ```YAML
>         id: ID!
>         name: String!
>         location: Point @search
> ```

can we add another `Point` type field without `@search`, so the generated dgraph schema should not have `@index` for that.
___
*[graphql/schema/rules.go, line 965 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKtJMW1FCf3pnfYEr8:-MIKtJMW1FCf3pnfYEr9:bgpdtej) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/rules.go#L965)):*
> ```
> // If there's no arg, then it can be an enum or has to be a scalar that's
> 		// not ID. The schema generation will add the default search
> 		// for that type.
> ```
comment can be updated now
___
*[graphql/schema/wrappers_test.go, line 135 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKugHg9qp-5J8aNHT3:-MIKugHg9qp-5J8aNHT4:b-nhsrtc) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/wrappers_test.go#L135)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> "Point": map[string]string{
> 			"latitude":  "Point.latitude",
> 			"longitude": "Point.longitude",
> 		},
> ```
</details>

We shouldn't need this test, because dgraphPredicate for `Point` doesn't make sense, i.e., we don't use these names to rewrite the point type. So, we shouldn't generate `dgraphPredicate` for `Point` type.
___
*[graphql/schema/wrappers_test.go, line 262 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKv7DP0dP7N3H4vOYE:-MIKv7DP0dP7N3H4vOYF:b-jgew9l) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/wrappers_test.go#L262)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> "Point": map[string]string{
> 			"latitude":  "Point.latitude",
> 			"longitude": "Point.longitude",
> 		},
> ```
</details>

same for this test, it shouldn't be required.

**Review by arijitAD — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6481)* status: 14 of 65 files reviewed, 7 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/resolve/add_mutation_test.yaml, line 21 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKoXPxEAapdqIhGOd_:-MIONOXZ-bNC5vasHpye:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/resolve/add_mutation_test.yaml#L21)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> A uid and type should get injected and all data transformed to
>     underlying Dgraph edge names
> ```
stale message
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 1252 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKqj3j5o9C_0emYsxT:-MIONxdz9SzqfdTPWdKZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/resolve/resolver.go#L1252)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> if field.ResponseName() == "longitude" {
> 			x.Check2(buf.WriteString(longitude))
> 		} else if field.ResponseName() == "latitude" {
> 			x.Check2(buf.WriteString(latitude))
> 		}
> ```
we sohuld convert this part to a `switch` case.
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 1255 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKq_BB2vkc_WkF6XWl:-MIONy5y2F0aGemMVk8L:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/resolve/resolver.go#L1255)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> else {
> 			return nil, x.GqlErrorList{&x.GqlError{
> 				Message:   "Invalid field for Geo type",
> 				Locations: []x.Location{field.Location()},
> 				Path:      copyPath(path),
> 			}}
> 		}
> ```
we will never get this else case, because we didn't define any other fields in the schema for `Point` type. If someone tried that, it would fail at parser level validation itself.
</blockquote></details>

Done.
___
*[graphql/schema/dgraph_schemagen_test.yml, line 616 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKtel7DX3YELilBHG8:-MIOWxkZBN4ER_oNcoFh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/dgraph_schemagen_test.yml#L616)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

can we add another `Point` type field without `@search`, so the generated dgraph schema should not have `@index` for that.
</blockquote></details>

Done.
___
*[graphql/schema/rules.go, line 965 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKtJMW1FCf3pnfYEr8:-MIOWwSyBkKXmROlMnJw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/rules.go#L965)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> // If there's no arg, then it can be an enum or has to be a scalar that's
> 		// not ID. The schema generation will add the default search
> 		// for that type.
> ```
comment can be updated now
</blockquote></details>

Done.
___
*[graphql/schema/wrappers_test.go, line 135 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKugHg9qp-5J8aNHT3:-MIOYi0p0oD58ZWKjH1R:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/wrappers_test.go#L135)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "Point": map[string]string{
> 			"latitude":  "Point.latitude",
> 			"longitude": "Point.longitude",
> 		},
> ```
We shouldn't need this test, because dgraphPredicate for `Point` doesn't make sense, i.e., we don't use these names to rewrite the point type. So, we shouldn't generate `dgraphPredicate` for `Point` type.
</blockquote></details>

Done.
___
*[graphql/schema/wrappers_test.go, line 262 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIKv7DP0dP7N3H4vOYE:-MIOYioa4GORCM79GY1s:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8192fa8e25645bf1c4f1ce66168041255fd09984/graphql/schema/wrappers_test.go#L262)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "Point": map[string]string{
> 			"latitude":  "Point.latitude",
> 			"longitude": "Point.longitude",
> 		},
> ```
same for this test, it shouldn't be required.
</blockquote></details>

Done.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 52 of 63 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6481)* status: all files reviewed, 17 unresolved discussions (waiting on @abhimanyusinghgaur, @arijitAD, and @MichaelJCompton)

___
*[graphql/e2e/common/mutation.go, line 3752 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISWxhT1S6USvGfAY8k:-MISWxhUDFEGEo7PgZWM:b-k10qpq) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/common/mutation.go#L3752)):*
> ```Go
> func mutationGeoType(t *testing.T) {
> 	addHotelParams := &GraphQLParams{
> 		Query: `    
> ```

extra spaces
___
*[graphql/e2e/directives/schema.graphql, line 7 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISXZ-r4CaEmIK73oG7:-MISXZ-r4CaEmIK73oG8:b3d4ro6) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/directives/schema.graphql#L7)):*
> ```GraphQL
>     id: ID!
>     name: String! @search(by: [exact])
>     location: Point @search
> ```

Are we also doing a query to search based on a point? I don't see any e2e test or unit test for a query.
___
*[graphql/e2e/directives/schema_response.json, line 4 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISXI-I67TPtuBO82eJ:-MISXI-I67TPtuBO82eK:b-xf2tfs) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/directives/schema_response.json#L4)):*
> ```JSON
>     "schema": [
>         {
>             "predicate": "dgraph.graphql.schema_history",
> ```

This file has a bit too much changed to see what the actual diff is. How do you get this? I usually print and copy the generated schema and then format it using VSCode editor.
___
*[graphql/e2e/schema/generatedSchema.graphql, line 81 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISY1OICf4i762Y41uq:-MISY1OICf4i762Y41ur:b-kh9ea4) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/schema/generatedSchema.graphql#L81)):*
> ```GraphQL
> }
> 
> input PointRef {
> ```

No different between Point and PointRef. Is there a reason we need both?
___
*[graphql/resolve/add_mutation_test.yaml, line 18 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISYswIAwOnT4vz-0_R:-MISYswIAwOnT4vz-0_S:b-rvet3l) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/add_mutation_test.yaml#L18)):*
> ```YAML
>     { "hotel":
>       { "name": "Taj Hotel",
>         "location": { "latitude": 11.11 , "longitude" : 22.22}
> ```

If only one of long/lat is given, I hope that is an error. Is there a test for the error message returned in that case?
___
*[graphql/resolve/mutation_rewriter.go, line 1214 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZ5jo6AcVs78BAL8V:-MISZ5jp1Go9lDNNTYBH:bhbdxk3) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/mutation_rewriter.go#L1214)):*
> ```Go
> 				// { "title": "...", "author": { "username": "new user", "dob": "...", ... }
> 				//          like here ^^
> 				if fieldDef.Type().IsGeo() {
> ```

Should this be `IsGeo` or `IsPoint`? Later we'll have other things with `IsGeo` as well. 
___
*[graphql/resolve/mutation_rewriter.go, line 1223 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZEK14vdbWcYmZtUg:-MISZEK21SWXupB6j9Q3:b-bspxjj) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/mutation_rewriter.go#L1223)):*
> ```Go
> 							newFragment(
> 								map[string]interface{}{
> 									"type":        "Point",
> ```

I suppose this is required for Dgraph to be able to do the filtering right? Please add a comment if that is the case here.
___
*[graphql/resolve/query_test.go, line 59 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZKbnA2u1MtCo3bBP:-MISZKbnA2u1MtCo3bBQ:bo7c3pd) ([raw file](https://github.com/dgraph-io/dgraph/blob/587c45b9f8a520711d6f32ebd53470243012459a/graphql/resolve/query_test.go#L59)):*
> ```Go
> 	for _, tcase := range tests {
> 		t.Run(tcase.Name, func(t *testing.T) {
> ```

revert please
___
*[graphql/resolve/resolver.go, line 1236 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZthh1w7yBdWn7V00:-MISZthiBhULIOh0zrVj:b-8vaimk) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/resolver.go#L1236)):*
> ```Go
> 	x.Check2(buf.WriteRune('{'))
> 
> 	coordinate, _ := val["coordinates"].([]interface{})
> ```

What if the value returned is null? Should we just return null then? Imagine user running this over an existing Dgraph database in which some values are null for some coordinates?
___
*[graphql/schema/dgraph_schemagen_test.yml, line 616 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIS__oc2TqN4Rl7xNYW:-MIS__oc2TqN4Rl7xNYX:bp9ucqd) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/schema/dgraph_schemagen_test.yml#L616)):*
> ```YAML
>         id: ID!
>         name: String!
>         location: Point @search
> ```

What happens if I have `@search(by: [int])` on a Point type? I hope that fails by the correct error message?

**Review by arijitAD — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6481)* status: 52 of 62 files reviewed, 17 unresolved discussions (waiting on @abhimanyusinghgaur, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/common/mutation.go, line 3752 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISWxhT1S6USvGfAY8k:-MIZ8h189jTiVieNS-lj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/common/mutation.go#L3752)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

Done.
___
*[graphql/e2e/directives/schema.graphql, line 7 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISXZ-r4CaEmIK73oG7:-MIZ8u9K4cUwf2UQ9DvO:b2xbnju) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/directives/schema.graphql#L7)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Are we also doing a query to search based on a point? I don't see any e2e test or unit test for a query.
</blockquote></details>

There is a unit test in query_test.yaml for the location filter.
___
*[graphql/e2e/directives/schema_response.json, line 4 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISXI-I67TPtuBO82eJ:-MIZ97KW5nFKyD6Cly8G:bu4fswe) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/directives/schema_response.json#L4)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This file has a bit too much changed to see what the actual diff is. How do you get this? I usually print and copy the generated schema and then format it using VSCode editor.
</blockquote></details>

I also copied the output and pasted it.
___
*[graphql/e2e/schema/generatedSchema.graphql, line 81 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISY1OICf4i762Y41uq:-MIZ9DpE2gnmVDSeyefE:bjpaeaf) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/e2e/schema/generatedSchema.graphql#L81)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

No different between Point and PointRef. Is there a reason we need both?
</blockquote></details>

Point is `type` and PointRef is `input`
In GraphQL type can only be used in output/result.
___
*[graphql/resolve/add_mutation_test.yaml, line 18 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISYswIAwOnT4vz-0_R:-MIZCqzE60SRr-6y-ek_:bnoqtds) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/add_mutation_test.yaml#L18)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

If only one of long/lat is given, I hope that is an error. Is there a test for the error message returned in that case?
</blockquote></details>

Yes. I have added a test for the same.
___
*[graphql/resolve/mutation_rewriter.go, line 1214 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZ5jo6AcVs78BAL8V:-MIZDDiE8dnRhkCnVOe9:bs7wuoy) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/mutation_rewriter.go#L1214)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Should this be `IsGeo` or `IsPoint`? Later we'll have other things with `IsGeo` as well. 
</blockquote></details>

Done.i
___
*[graphql/resolve/mutation_rewriter.go, line 1223 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZEK14vdbWcYmZtUg:-MIZDV1v8G2MG9PtXI-i:b-8b11j9) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/mutation_rewriter.go#L1223)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I suppose this is required for Dgraph to be able to do the filtering right? Please add a comment if that is the case here.
</blockquote></details>

Added
___
*[graphql/resolve/query_test.go, line 59 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZKbnA2u1MtCo3bBP:-MIZDc87-94Wy8TpER-k:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/587c45b9f8a520711d6f32ebd53470243012459a/graphql/resolve/query_test.go#L59)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

revert please
</blockquote></details>

Done.
___
*[graphql/resolve/resolver.go, line 1236 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MISZthh1w7yBdWn7V00:-MIZDiDX1iUJxsrRu3lt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/resolve/resolver.go#L1236)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What if the value returned is null? Should we just return null then? Imagine user running this over an existing Dgraph database in which some values are null for some coordinates?
</blockquote></details>

Done.
___
*[graphql/schema/dgraph_schemagen_test.yml, line 616 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6481#-MIS__oc2TqN4Rl7xNYW:-MIZEoJT67OIyOSO8q_9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f9ee195e4888c4b758631a35544febe38ac599/graphql/schema/dgraph_schemagen_test.yml#L616)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What happens if I have `@search(by: [int])` on a Point type? I hope that fails by the correct error message?
</blockquote></details>

Done.

**Pull request merged**
