### PR TITLE
Modify errors returned by client. Make code simpler.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1805)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[edgraph/server.go, line 415 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-KzSIt7b7cv6wjiD3Nmi:-KzSIt7b7cv6wjiD3Nmj:b-128qzf) ([raw file](https://github.com/dgraph-io/dgraph/blob/f3cd60237189aeee6b540f52f912cf5dd89ce1d5/edgraph/server.go#L415)):*
> ```Go
> 	commitTs, err := worker.CommitOverNetwork(ctx, tc)
> 	if err == y.ErrAborted {
> 		err = status.Errorf(codes.Aborted, err.Error())
> ```

can't this be done inside commitovernetwork?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-:-KzSIxnJ8Apyz0cpbCgA:bnfp4nl)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/txn.go, line 130 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-KzSKfsFQGTq3YXreySb:-KzSKfsG-MDUW8PrfJoI:b-r7ctg) ([raw file](https://github.com/dgraph-io/dgraph/blob/f3cd60237189aeee6b540f52f912cf5dd89ce1d5/client/txn.go#L130)):*
> ```Go
> 	}
> 	txn.mutated = true
> 	err = txn.mergeContext(ag.Context)
> ```

Is it definitely the case that there's no context to merge when there's a conflict?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-:-KzSKkj5jND8ItUNikHX:bnfp4nl)*

**Comment by deepakjois** [comment]
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/txn.go, line 163 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-KzTXCar-LWIK0DAqI8R:-KzTXCar-LWIK0DAqI8S:bigizb6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9ce69c883ece900cf24dee691c5b9236877b6a3/client/txn.go#L163)):*
> ```Go
> 		return err
> 	}
> 	if tctx.Aborted {
> ```

You do not have to remove the code here.

It might be desirable to return a unique client-specific error in the case of an abort, as opposed to other generic GRPC errors. It should be easy to check the status code and compare it to `codes.Aborted` and return ErrAborted instead of just passing the original error through.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805)*

**Comment by pawanrawal** [comment]
Review status: 9 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[client/txn.go, line 130 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-KzSKfsFQGTq3YXreySb:-KzVrJ3FFZj2QwcCK-LA:bj2ey3n) ([raw file](https://github.com/dgraph-io/dgraph/blob/f3cd60237189aeee6b540f52f912cf5dd89ce1d5/client/txn.go#L130)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Is it definitely the case that there's no context to merge when there's a conflict?
</blockquote></details>

Yeah ag.Context is nil in case of errors.

---

*[client/txn.go, line 163 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-KzTXCar-LWIK0DAqI8R:-KzWkmQjU7gRwlqYu1K7:b-qrnnil) ([raw file](https://github.com/dgraph-io/dgraph/blob/f9ce69c883ece900cf24dee691c5b9236877b6a3/client/txn.go#L163)):*
<details><summary><i>Previously, deepakjois (Deepak Jois) wrote…</i></summary><blockquote>

You do not have to remove the code here.

It might be desirable to return a unique client-specific error in the case of an abort, as opposed to other generic GRPC errors. It should be easy to check the status code and compare it to `codes.Aborted` and return ErrAborted instead of just passing the original error through.
</blockquote></details>

Right doing that now, though checking Message instead of code.

---

*[edgraph/server.go, line 415 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805#-KzSIt7b7cv6wjiD3Nmi:-KzVrWq9S6sU-TzBIyV6:bk2xgx6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f3cd60237189aeee6b540f52f912cf5dd89ce1d5/edgraph/server.go#L415)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

can't this be done inside commitovernetwork?
</blockquote></details>

CommitOverNetwork is also called by http endpoints, so not doing it there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1805)*

**Comment by pawanrawal** [comment]
In master as of a4b2281919d319c747ebfdd37d4d69fc3a50195a

**Pull request closed without merging**
