### PR TITLE
Improve/prepost2

### PR DESCRIPTION
**Pull request by jchiu0**
Use PreTraverse for ToJSON and ToProto. No extra intermediate structures needed.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/315)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm: 

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/query.go, line 1035 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KWGy2tlsPJTdp0KzJbh:-KWGy2tlsPJTdp0KzJbi:b-9viq56) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6cf07f76c5b2e46c2ab63a95a6bdfdce862e7e1/query/query.go#L1035)):*
> ```Go
> 	}
> 
> 	if sg.GeoFilter != nil {
> ```

This part can be removed. We don't need it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-:-KWGyC1QPeSO4JkpsASD:bg7igkv)*

**Comment by jchiu0** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/benchmark_test.go, line 151 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KWGJ0ihkNUQIyBYPNP7-r1-151:-KWMpPCV4CiD7W7hbf55:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6cf07f76c5b2e46c2ab63a95a6bdfdce862e7e1/query/benchmark_test.go#L151)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> can probably use "var r []*algo.UIDList" instead
</details>
Done.

---

*[query/benchmark_test.go, line 164 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KWGJ0ihkNUQIyBYPNP7-r1-164:-KWMpUX2tKwl1F4JSKUL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6cf07f76c5b2e46c2ab63a95a6bdfdce862e7e1/query/benchmark_test.go#L164)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> can probably use "var out []uint64" instead
</details>
Done.

---

*[query/benchmark_test.go, line 172 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KWGJ0ihkNUQIyBYPNP7-r1-172:-KWMpal2blJoewHZBzio:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6cf07f76c5b2e46c2ab63a95a6bdfdce862e7e1/query/benchmark_test.go#L172)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> can probably use "var children []*SubGraph" instead
</details>
Done.

---

*[query/benchmark_test.go, line 189 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KWGJ0ihkNUQIyBYPNP7-r1-189:-KWMpgH59B1ezSrUbzEe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6cf07f76c5b2e46c2ab63a95a6bdfdce862e7e1/query/benchmark_test.go#L189)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> can probably use "var r []*algo.UIDList" instead
</details>
Done.

---

*[query/query.go, line 1035 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KWGy2tlsPJTdp0KzJbh:-KWMqFiU3257M1gKQGdF:b-43o77l) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6cf07f76c5b2e46c2ab63a95a6bdfdce862e7e1/query/query.go#L1035)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> This part can be removed. We don't need it.
</details>
I wrote this hoping to make the geo tests pass. It did make one test there pass. Decided to just delete this block as you suggested and comment out geo_test.go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/315)*

**Comment by manishrjain** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 921 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KW_cJeBiM8eQGXwnyBj:-KW_cJeCv-P_HVjgqY-c:bxx5t7) ([raw file](https://github.com/dgraph-io/dgraph/blob/5e2ad50f3f20a9d78bab0682b8f2fb3f25e33fe6/query/query.go#L921)):*
> ```Go
> 
> // preOutput is the generic output / writer for preTraverse.
> type preOutput interface {
> ```

Maybe call it vertex, which represents how data is arranged. Or, outputNode. pretraverse is just the way we process the output, it shouldn't have an effect on the naming.

---

*[query/query.go, line 926 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KW_fXQWi0Rbe2aaMxVd:-KW_fXQXK0YrY9Ul9Ko4:b-twkn8c) ([raw file](https://github.com/dgraph-io/dgraph/blob/5e2ad50f3f20a9d78bab0682b8f2fb3f25e33fe6/query/query.go#L926)):*
> ```Go
> 	New(attr string) preOutput
> 	SetUID(uid uint64)
> 	SetXID(xid string)
> ```

If you add a Done method here, you could actually do json encoding without the need for a map[string]interface{}; which would be a huge optimization. Each node could build a string rep directly, which can finally be put together. Could be a separate PR.

---

*[query/query.go, line 961 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KW_cfnOKBVJzpE1fEv5:-KW_cfnOKBVJzpE1fEv6:b-8jsqmo) ([raw file](https://github.com/dgraph-io/dgraph/blob/5e2ad50f3f20a9d78bab0682b8f2fb3f25e33fe6/query/query.go#L961)):*
> ```Go
> // most cases.
> func (sg *SubGraph) ToProtocolBuffer(l *Latency) (*graph.Node, error) {
> 	var dummy *protoPreOutput
> ```

dummy is a bad name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/315)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-:-KW_gPmjZ_3D8601NJr5:bnfp4nl)*

**Comment by jchiu0** [comment]
Thanks everyone. Submitting.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 921 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KW_cJeBiM8eQGXwnyBj:-KWaRnBU4_nZLmITgAFI:b-ghhxcs) ([raw file](https://github.com/dgraph-io/dgraph/blob/5e2ad50f3f20a9d78bab0682b8f2fb3f25e33fe6/query/query.go#L921)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Maybe call it vertex, which represents how data is arranged. Or, outputNode. pretraverse is just the way we process the output, it shouldn't have an effect on the naming.
</details>
Good point. Renamed to outputNode.

---

*[query/query.go, line 926 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KW_fXQWi0Rbe2aaMxVd:-KWaRz9TURpZKQWqOMGz:b-9mgtv9) ([raw file](https://github.com/dgraph-io/dgraph/blob/5e2ad50f3f20a9d78bab0682b8f2fb3f25e33fe6/query/query.go#L926)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> If you add a Done method here, you could actually do json encoding without the need for a map[string]interface{}; which would be a huge optimization. Each node could build a string rep directly, which can finally be put together. Could be a separate PR.
</details>
Thanks. I will work on such an optimization next.

---

*[query/query.go, line 961 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-KW_cfnOKBVJzpE1fEv5:-KWaSEQvMZEgQguNY9uf:b-cdfgn9) ([raw file](https://github.com/dgraph-io/dgraph/blob/5e2ad50f3f20a9d78bab0682b8f2fb3f25e33fe6/query/query.go#L961)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> dummy is a bad name.
</details>
Renamed to "seedNode".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/315#-:-KWaWHMftWAA7h8WHR94:b-4up8h3)*

**Pull request closed without merging**
