### PR TITLE
Return error if un-indexed field is used in functions

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/384)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 841 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/384#-KZ-fEUXU-KSwI6_pSh4:-KZ-fEUYm2_d9HL2BuIe:b-gtyqiy) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fe208953a4b9bdfca507f97ba7da63b557dd8b/gql/parser.go#L841)):*
> ```Go
> 		if !schema.IsIndexed(gen.Attr) {
> 			return nil, x.Errorf(
> 				"Field %s is not indexed and cannot be used in fuctions",
> ```

functions

---

*[gql/parser_test.go, line 707 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/384#-KZ-fZDHyzk6qwP6HXtU:-KZ-fZDHyzk6qwP6HXtV:b9orrgr) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fe208953a4b9bdfca507f97ba7da63b557dd8b/gql/parser_test.go#L707)):*
> ```Go
> 
> func TestParseGenerator(t *testing.T) {
> 	schema.ParseBytes([]byte("scalar name:string @index"))
> ```

Did you want to write a test for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/384#-:-KZ-fcSq785Texo7ZtsO:bnfp4nl)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/384#-:-KZ-gxQO9LlW3_JaW1Pw:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser_test.go, line 707 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/384#-KZ-fZDHyzk6qwP6HXtU:-KZ-iFPP-OB4iVOTfmgv:b-cr08rd) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fe208953a4b9bdfca507f97ba7da63b557dd8b/gql/parser_test.go#L707)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Did you want to write a test for it?
</blockquote></details>

This should cover it. Also adding a failing case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/384)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 841 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/384#-KZ-fEUXU-KSwI6_pSh4:-KZ-j5ymoT4BLUGRU9GA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/67fe208953a4b9bdfca507f97ba7da63b557dd8b/gql/parser.go#L841)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

functions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/384)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
