### PR TITLE
Viper (set config via flags, config file, and environ vars)

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1857)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm:  Can you also update the docs here https://docs.dgraph.io/deploy/#config?
Also, there are some tests related to TLS which run on Travis in contrib/tlstest. They would probably need modification.

---

Review status: 0 of 122 files reviewed at latest revision, 1 unresolved discussion.

---

*[x/profile.go, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1857#-L-EJXn1KGSmes9K8MBT:-L-EJXn2Y5uQKhPRHahq:b-3mgeks) ([raw file](https://github.com/dgraph-io/dgraph/blob/4862e40d787e2c4c580dadad23af2b004a3c6989/x/profile.go#L12)):*
> ```Go
> )
> 
> func StartProfile(conf *viper.Viper) interface {
> ```

Cant the return be of type `noOpStopper` here? This syntax looks a bit weird.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1857#-:-L-EKr-Z7mSi_-D2OvB0:b-vurknm)*

**Comment by peterstace** [comment]
Review status: 0 of 122 files reviewed at latest revision, 1 unresolved discussion.

---

*[x/profile.go, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1857#-L-EJXn1KGSmes9K8MBT:-L-EMpHjWgJx6TLRBgKu:bcuq5eo) ([raw file](https://github.com/dgraph-io/dgraph/blob/4862e40d787e2c4c580dadad23af2b004a3c6989/x/profile.go#L12)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Cant the return be of type `noOpStopper` here? This syntax looks a bit weird.
</blockquote></details>

I can't make the return type `noOpStopper` since we have to return proper profile implementations in the normal cases. I took the same approach that the `pgk/profile` does (use an anonymous interface). However, I agree that's it's probably a bit too smart. I've changed to explicitly declare an interface and use that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1857)*

**Comment by pawanrawal** [comment]
Review status: 0 of 122 files reviewed at latest revision, 1 unresolved discussion.

---

*[x/profile.go, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1857#-L-EJXn1KGSmes9K8MBT:-L-EPG185Frb631LXhVZ:b-13g4y2) ([raw file](https://github.com/dgraph-io/dgraph/blob/4862e40d787e2c4c580dadad23af2b004a3c6989/x/profile.go#L12)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

I can't make the return type `noOpStopper` since we have to return proper profile implementations in the normal cases. I took the same approach that the `pgk/profile` does (use an anonymous interface). However, I agree that's it's probably a bit too smart. I've changed to explicitly declare an interface and use that.
</blockquote></details>

Looks good and more readable :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1857)*

**Comment by peterstace** [comment]
Yep, they did need a bit of fixing (done). Docos have been updated now as well.

---

Review status: 0 of 134 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1857#-:-L-EYiJBtMVFJ429NIlq:b-nnrvda)*

**Pull request merged**
