### PR TITLE
Emit commas in lexer

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/698)

### CODE REVIEW

**Comment by tzdybal** [comment]
There are no new tests for `schema` and `facets` parsing. Other changes :lgtm: .

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-:-KfEakGUfhuFmqAkzhN8:bi9f2a7)*

**Comment by ashishnegi** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[gql/parser.go, line 888 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfF-sR_BVPyFAxvPClo:-KfF-sRaNJItTyhfd2gA:bhn01o1) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6f860a06b407475595fe691ebd253e2f8fd86d/gql/parser.go#L888)):*
> ```Go
> 			expectArg = false
> 		} else if item.Typ == itemRightRound {
> 			break
> ```

is `,)` allowed at end ?

---

*[gql/parser.go, line 1020 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfF088gGxKIyv4TKq3o:-KfF088gGxKIyv4TKq3p:b-3r6d5g) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6f860a06b407475595fe691ebd253e2f8fd86d/gql/parser.go#L1020)):*
> ```Go
> func parseFunction(it *lex.ItemIterator) (*Function, error) {
> 	var g *Function
> 	var expectArg bool
> ```

we can use same line for both vars..

---

*[gql/parser.go, line 1076 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfF0HrKZeSnTCNWWGB2:-KfF0HrKZeSnTCNWWGB3:b-cva0t5) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6f860a06b407475595fe691ebd253e2f8fd86d/gql/parser.go#L1076)):*
> ```Go
> 		}
> 	}
> 	_ = expectArg
> ```

why is this required ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/698)*

**Comment by ashwin95r** [comment]
Added tests.

---

Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[gql/parser.go, line 888 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfF-sR_BVPyFAxvPClo:-KfFJVJHy-6cPDlKblcw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6f860a06b407475595fe691ebd253e2f8fd86d/gql/parser.go#L888)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

is `,)` allowed at end ?
</blockquote></details>

Done.

---

*[gql/parser.go, line 1020 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfF088gGxKIyv4TKq3o:-KfFKW3Uj_QlSY4z5CvL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6f860a06b407475595fe691ebd253e2f8fd86d/gql/parser.go#L1020)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

we can use same line for both vars..
</blockquote></details>

Done.

---

*[gql/parser.go, line 1076 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfF0HrKZeSnTCNWWGB2:-KfFL4HNthEJlINQHrUC:b3o2xnd) ([raw file](https://github.com/dgraph-io/dgraph/blob/ab6f860a06b407475595fe691ebd253e2f8fd86d/gql/parser.go#L1076)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

why is this required ?
</blockquote></details>

Ah the compiler was complaining before. Not required. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-:-KfFVqZn46ejHhOw_ZtY:bufim0i)*

**Comment by ashishnegi** [comment]
:lgtm: Just one comment.

---

Review status: 3 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[gql/parser.go, line 906 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfG27HFaoXxRQNJ073r:-KfG27HGYbWPNiHl9GDy:b-gb9n36) ([raw file](https://github.com/dgraph-io/dgraph/blob/dff048b97106968bf3d4640b11417430f92fdba9/gql/parser.go#L906)):*
> ```Go
> 			break
> 		} else if item.Typ == itemComma {
> 			expectArg = true
> ```

what about `,,` two commas without any data inbetween.
I have a failure test for this in facet. If it is passing, you can change the `expectedFailure` variable to see why is it pasing.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-:-KfG2ZVPzdpvQpovg_fj:b-tjkceq)*

**Comment by ashwin95r** [comment]
Review status: 3 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[gql/parser.go, line 906 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/698#-KfG27HFaoXxRQNJ073r:-KfG9mndfbdiMJzFfSHD:bbx1o7c) ([raw file](https://github.com/dgraph-io/dgraph/blob/dff048b97106968bf3d4640b11417430f92fdba9/gql/parser.go#L906)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

what about `,,` two commas without any data inbetween.
I have a failure test for this in facet. If it is passing, you can change the `expectedFailure` variable to see why is it pasing.  
</blockquote></details>

Added a case for the repeated commas. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/698)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
