### PR TITLE
Release/fixes2

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1203)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraph/main.go, line 269 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1203#-KpJJ_HRPwnGDeIkVUs2:-KpJJ_HSsbRdXSSmzOr7:bly3td8) ([raw file](https://github.com/dgraph-io/dgraph/blob/46f6bb26fb4028453355df858754950c269b33e1/cmd/dgraph/main.go#L269)):*
> ```Go
> 
> 	if dgraph.Config.DebugMode {
> 		fmt.Printf("Received query: %+v\n", q)
> ```

fmt or x?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1203#-:-KpJJtpaRB1C5_x9GlNF:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphloader/main.go, line 292 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1203#-KpJJyc8J87OT_hova2L:-KpJJyc95Uf80eeYy_Ix:bxshnwb) ([raw file](https://github.com/dgraph-io/dgraph/blob/46f6bb26fb4028453355df858754950c269b33e1/cmd/dgraphloader/main.go#L292)):*
> ```Go
> 
> 	// Lets call this so that badger is closed properly.
> 	dgraphClient.Close()
> ```

why not close in flush method ? after calling flush we wait for all mutations to finish ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1203#-:-KpJKEFRPdnxJUoDxvIi:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 269 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1203#-KpJJ_HRPwnGDeIkVUs2:-KpJNHKPTNjAmWMYLP1P:b2i51cz) ([raw file](https://github.com/dgraph-io/dgraph/blob/46f6bb26fb4028453355df858754950c269b33e1/cmd/dgraph/main.go#L269)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

fmt or x?
</blockquote></details>

This is main.go, so fmt should be ok.

---

*[cmd/dgraphloader/main.go, line 292 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1203#-KpJJyc8J87OT_hova2L:-KpJN6NQk5JLcI0cuX2x:br7u7n6) ([raw file](https://github.com/dgraph-io/dgraph/blob/46f6bb26fb4028453355df858754950c269b33e1/cmd/dgraphloader/main.go#L292)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

why not close in flush method ? after calling flush we wait for all mutations to finish ?
</blockquote></details>

Flush is specific to batch. We need to close after we are done using dgraphClient which could be used for individual mutations (which need the kv) too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1203)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
