### PR TITLE
Variables in mutations

### LINKED ISSUE #919: Support variables in mutation blocks.
There would be dependency between query and mutation blocks (just like we have among query blocks now).

Eg: 
```
mutation {
 set {
  var(adults) <isadult> "true" .
  <a> <b> <c> .
  . . .
 }

 delete {
  var(adults) <ischild> "true" .
 } 
}
{
 me(id: a) {
   adults as friends @filter(gt(age, 18))
 }
}
```
This would fetch my friends whose age is above 18. Then for each UID in that list perform the mutation.

### PR DESCRIPTION
**Pull request by szymonm**
Resolves #919

@ashwin95r This is the first part that contains changes in lexer and parser. Can you have a look if this is going in the right direction?

Next part, tomorrow!

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/947)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Looks great @szymonm ! Just some comments about small refactoring. Also, I think we should just support the ObjectVars along with SubjectVars since it seems very similar.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNxq6r0uQBfEYtJFrS:-KkNxq6r0uQBfEYtJFrT:bmd1ice) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L2)):*
> ```Go
> /*
> ```

Vertical space?

---

*[gql/parser.go, line 469 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNwmzCPyr6I3V8jAMF:-KkNwmzCPyr6I3V8jAMG:b-qxnsz9) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L469)):*
> ```Go
> 	QueryVars    []*Vars
> 	Mutation     *Mutation
> 	MutationVars []string // mutations don't define vars so we have only needed.
> ```

Please fix comment.

---

*[gql/parser.go, line 578 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNwxQgL8ximGZb6MD9:-KkNwxQgL8ximGZb6MDA:bwvckic) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L578)):*
> ```Go
> }
> 
> func determineNeededVars(m Mutation) []string {
> ```

Do you think we can define this as a method on `res Result`? `res.getMutationVars(m)

---

*[gql/parser.go, line 1004 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNy0vekaM5niB5TyK8:-KkNy0vekaM5niB5TyK9:bcr7q8r) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L1004)):*
> ```Go
> 					}
> 				}
> ```

Remove vertical space.

---

*[gql/parser_test.go, line 2479 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNyEB_1zMHpGu-udLO:-KkNyEB_1zMHpGu-udLP:bcgdgov) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser_test.go#L2479)):*
> ```Go
> //	require.NoError(t, err)
> //}
> ```

Is this temporary?

---

*[protos/graphresponse.proto, line 21 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNyma53laTJ-vg1RAt:-KkNyma53laTJ-vg1RAu:b-uk5e2a) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/protos/graphresponse.proto#L21)):*
> ```protobuf
>     string label = 5;
>     string lang = 7;
>     sint32 objectType = 6;
> ```

Unrealted to this PR. But this should be object_type. Would be great if you can fix that too. Also `object_value`

---

*[rdf/state.go, line 150 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNzufPT6gomrlE1POM:-KkNzufQ1RFxHvOoCcmC:b-e2fu7t) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/rdf/state.go#L150)):*
> ```Go
> 			}
> 			l.Backup()
> 			l.Emit(itemText)
> ```

Just to be sure, do we need this Emit?

---

*[rdf/state.go, line 464 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkO-JHd9xUwIhmIsyw4:-KkO-JHeAS8WDJstHRgq:belm1hu) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/rdf/state.go#L464)):*
> ```Go
> }
> 
> func lexVariable(l *lex.Lexer) lex.StateFn {
> ```

I think that the lexer shouldn't do these checks to see if it's a `var` and then expect a leftRound, etc.
Lexer should just tokenize `var(abc)` as itemName (var), itemLeftRound, itemName(abc), itemRightRound. The parser should check for the context, interpret and stitch them accordingly. Ideally, we shouldn't have this separate function. Also no need for `itemVar` and `itemVarName`, they should just be `itemName`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-:-KkO07RnVlU3OxkkK1jQ:b61w3uo)*

**Comment by szymonm** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 578 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNwxQgL8ximGZb6MD9:-KkP8seqGDc7XHJ7NOZt:b-q7wnb5) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L578)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Do you think we can define this as a method on `res Result`? `res.getMutationVars(m)
</blockquote></details>

Generally, we have a lot of methods in the file that are on Result that is big and deep. That makes it hard to understand the methods and test them. When I look at the header I can only say that the method modifies Result in some way.

When I see the method with a header as above, I know it takes and mutation, does not modify it and returns an array of strings - that helps a lot.

On the other hand, it seems complicated, if we have dozens of functions in a file not connected to any struct, so maybe will change this method to operate on a Mutation like
`func (m Mutation) NeededVars [] string {`. What do you think?

---

*[gql/parser_test.go, line 2479 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNyEB_1zMHpGu-udLO:-KkPAno3C1gTtn5MOxVC:be3z2cq) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser_test.go#L2479)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Is this temporary?
</blockquote></details>

The fact is that is current lexer in rdf, we don't allow a multiline string as an object. Should this test pass?

---

*[rdf/state.go, line 150 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNzufPT6gomrlE1POM:-KkPBENnWcQmGaNN8_u3:bg2jyfw) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/rdf/state.go#L150)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Just to be sure, do we need this Emit?
</blockquote></details>

That is weird to me too, but we do this in every case branch here. I guess we want to emit white spaces read before as an `itemText`.

---

*[rdf/state.go, line 464 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkO-JHd9xUwIhmIsyw4:-KkPBtcYB7BFdPn8HwzQ:blilirh) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/rdf/state.go#L464)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I think that the lexer shouldn't do these checks to see if it's a `var` and then expect a leftRound, etc.
Lexer should just tokenize `var(abc)` as itemName (var), itemLeftRound, itemName(abc), itemRightRound. The parser should check for the context, interpret and stitch them accordingly. Ideally, we shouldn't have this separate function. Also no need for `itemVar` and `itemVarName`, they should just be `itemName`
</blockquote></details>

If we talk about principles, I agree with you. Maybe except the fact that `var` is a language keyword, so it can also be recognized by the lexer and emitted as `itemKeyword` or `itemVar`. Basically, lexer should just split text into tokens and 'delete' whitespaces and comments. It needs some context, but minimal, for instance being inside '"' to distinguish `a - b` from `"a - b"`.

Our lexer is, however, far from that (see how we lex facets for example). See that we have `itemSubject`, `itemPredicate` and so on and we don't even have `itemName`. So the lexer is actually doing also some kind of pre-parsing. I decided to be consistent with this. Will think again about how we could go into the right direction of correct separation between lexer and parser.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 578 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNwxQgL8ximGZb6MD9:-KkPI89ibiztyqbWeVKh:b-f391da) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L578)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

Generally, we have a lot of methods in the file that are on Result that is big and deep. That makes it hard to understand the methods and test them. When I look at the header I can only say that the method modifies Result in some way.

When I see the method with a header as above, I know it takes and mutation, does not modify it and returns an array of strings - that helps a lot.

On the other hand, it seems complicated, if we have dozens of functions in a file not connected to any struct, so maybe will change this method to operate on a Mutation like
`func (m Mutation) NeededVars [] string {`. What do you think?
</blockquote></details>

But this doesn't modify anything on mutation. So yeah, do what you think would be cleaner :)

---

*[gql/parser_test.go, line 2479 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNyEB_1zMHpGu-udLO:-KkPHG50fbHGvmEExJ7c:b1kdk84) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser_test.go#L2479)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

The fact is that is current lexer in rdf, we don't allow a multiline string as an object. Should this test pass?
</blockquote></details>

I thought it was passing before. We can retain the previous behavior.

---

*[rdf/state.go, line 150 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNzufPT6gomrlE1POM:-KkPHq2II3DP08BUTyzm:b-gg0kyd) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/rdf/state.go#L150)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

That is weird to me too, but we do this in every case branch here. I guess we want to emit white spaces read before as an `itemText`.
</blockquote></details>

I see. I think we can get rid of it. If not in this PR, please add an issue.

---

*[rdf/state.go, line 464 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkO-JHd9xUwIhmIsyw4:-KkPHWlpBVfJk6awCNNO:b-z1srxt) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/rdf/state.go#L464)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

If we talk about principles, I agree with you. Maybe except the fact that `var` is a language keyword, so it can also be recognized by the lexer and emitted as `itemKeyword` or `itemVar`. Basically, lexer should just split text into tokens and 'delete' whitespaces and comments. It needs some context, but minimal, for instance being inside '"' to distinguish `a - b` from `"a - b"`.

Our lexer is, however, far from that (see how we lex facets for example). See that we have `itemSubject`, `itemPredicate` and so on and we don't even have `itemName`. So the lexer is actually doing also some kind of pre-parsing. I decided to be consistent with this. Will think again about how we could go into the right direction of correct separation between lexer and parser.
</blockquote></details>

Yeah fair enough. But we just want to follow it as much as possible. So yeah, the more you can move to the parser the better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by szymonm** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 2479 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNyEB_1zMHpGu-udLO:-KkPW_6mKUovqSkivNjD:b-qu18mm) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser_test.go#L2479)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I thought it was passing before. We can retain the previous behavior.
</blockquote></details>

The test was passing, because we haven't parsed the text inside mutation. Now we do and it turns out it's not parsed correctly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by ashwin95r** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 516 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkT0B3m7LzR0_nlfU9i:-KkT0B3n8CwuvabM3us4:b-pz0zfq) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa8775f8e3f9a02b305afca8b7094da28cf6a6d7/cmd/dgraph/main.go#L516)):*
> ```Go
> 	}
> 	if res.Mutation != nil && res.Mutation.HasOps() && mutationsBeforeQuery {
> 		runMutations()
> ```

Even if some mutations have a variable, we can still execute the other mutations that are independent here, before the query.

---

*[cmd/dgraph/main.go, line 555 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkT0OLC75lBMhwqwCaD:-KkT0OLC75lBMhwqwCaE:bqwnyfc) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa8775f8e3f9a02b305afca8b7094da28cf6a6d7/cmd/dgraph/main.go#L555)):*
> ```Go
> 
> 	if !mutationsBeforeQuery {
> 		runMutations()
> ```

Here we should execute the only the dependent mutations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by tzdybal** [comment]
Reviewed 5 of 13 files at r1, 4 of 9 files at r2, 12 of 14 files at r3.
Review status: 19 of 23 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[gql/mutation.go, line 115 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-Kkw-l01KfmENovpX3st:-Kkw-l02bxEmf8E5AciZ:b-qq3hp8) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9f0e9e06fcf7fc0fd015a5e4c6cd2fbf73f8302/gql/mutation.go#L115)):*
> ```Go
> }
> 
> // IsDependent returns true iff given NQuad refers some variable.
> ```

IMHO `HasDependencies` describes better what function does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by szymonm** [comment]
Reviewed 2 of 3 files at r4, 1 of 5 files at r5.
Review status: 18 of 24 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 516 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkT0B3m7LzR0_nlfU9i:-KkziPBiuoP8ebtJMGE0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa8775f8e3f9a02b305afca8b7094da28cf6a6d7/cmd/dgraph/main.go#L516)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Even if some mutations have a variable, we can still execute the other mutations that are independent here, before the query.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 555 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkT0OLC75lBMhwqwCaD:-KkziRJ_TP3iiB0mADkg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/aa8775f8e3f9a02b305afca8b7094da28cf6a6d7/cmd/dgraph/main.go#L555)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Here we should execute the only the dependent mutations.
</blockquote></details>

Done.

---

*[gql/mutation.go, line 115 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-Kkw-l01KfmENovpX3st:-KkziSkwNfWH65U0cOin:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e9f0e9e06fcf7fc0fd015a5e4c6cd2fbf73f8302/gql/mutation.go#L115)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

IMHO `HasDependencies` describes better what function does.
</blockquote></details>

Done.

---

*[gql/parser.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNxq6r0uQBfEYtJFrS:-KkziTdfvB5X2-0XopHt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L2)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Vertical space?
</blockquote></details>

Done.

---

*[gql/parser.go, line 469 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNwmzCPyr6I3V8jAMF:-Kkzid5EJKQyDmLHAEkN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L469)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Please fix comment.
</blockquote></details>

Done.

---

*[gql/parser.go, line 578 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNwxQgL8ximGZb6MD9:-Kkzig-mwxIuvXLmpmgj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L578)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

But this doesn't modify anything on mutation. So yeah, do what you think would be cleaner :)
</blockquote></details>

Done.

---

*[gql/parser.go, line 1004 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNy0vekaM5niB5TyK8:-KkziqPmRjZ6T41KrV_N:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/gql/parser.go#L1004)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Remove vertical space.
</blockquote></details>

Done.

---

*[protos/graphresponse.proto, line 21 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KkNyma53laTJ-vg1RAt:-KkziLuSF3758gARd7sm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/60bcb7fec3d48c28884c2205788e474c8163ab52/protos/graphresponse.proto#L21)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Unrealted to this PR. But this should be object_type. Would be great if you can fix that too. Also `object_value`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by szymonm** [comment]
Reviewed 1 of 3 files at r4, 3 of 5 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by ashwin95r** [comment]
Looks good to me mostly. @mrjn can you please have a look?

---

Reviewed 9 of 14 files at r3, 1 of 3 files at r4, 3 of 5 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[mutation/mutation.go, line 15 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KlHGLgia3dJUugh7bU4:-KlHGLgjPyMIaVv6Zl0c:b-8udxyp) ([raw file](https://github.com/dgraph-io/dgraph/blob/f18454791a613c77b748d491e51803bb9335f0a8/mutation/mutation.go#L15)):*
> ```Go
> )
> 
> type MaterializedMutation struct {
> ```

The naming is not very clear, why `MaterializedMutation`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-:-KlHGZPo53gRlqbjESZG:bttu76o)*

**Comment by szymonm** [comment]
Reviewed 1 of 5 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[mutation/mutation.go, line 15 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/947#-KlHGLgia3dJUugh7bU4:-KlHYjI3T2hmkUuf3sMK:bychwwy) ([raw file](https://github.com/dgraph-io/dgraph/blob/f18454791a613c77b748d491e51803bb9335f0a8/mutation/mutation.go#L15)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

The naming is not very clear, why `MaterializedMutation`? 
</blockquote></details>

I was confused by the number of structs we call `Mutation`. Here, we have edges that will be inserted into the graph and new ids assigned to new nodes. Can you think of a better name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/947)*

**Comment by szymonm** [comment]
Rebased and cleaned the PR, it is now: #999

**Pull request closed without merging**
