### PR TITLE
Fix/proto4

### PR DESCRIPTION
**Pull request by jchiu0**
Use proto for Membership and MembershipUpdate.

(Eventually ProposeAndWait can use only protos. That will come in another PR where we update Mutation as well.)

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/328)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm: Just a small comment.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[worker/draft.go, line 353 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KX9U1tYTdLBAGXKJLCh:-KX9U1tZneYCykebUwm1:b-7l4msu) ([raw file](https://github.com/dgraph-io/dgraph/blob/80f0b6c13dd9f94e51aa5e8cc9afa1f65c47e15b/worker/draft.go#L353)):*
> ```Go
> 			for _, msg := range rd.Messages {
> 				// TODO: Do some optimizations here to drop messages.
> 				rcBytes, err := n.raftContext.Marshal()
> ```

Could this marshaling be done outside the loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-:-KX9UUYHiMEXKZ-qHqv9:b-rcw46s)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[worker/draft.go, line 353 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KX9U1tYTdLBAGXKJLCh:-KXAKh9niWPqwKj1Usyc:bz0q8n6) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7366fa0310c9c87094913792cc37e1f3f6cf2b9/worker/draft.go#L353)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Could this marshaling be done outside the loop?
</details>
Yes, thanks for catching this!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/328)*

**Comment by manishrjain** [comment]
:lgtm_strong: A couple of small comments -- address them, and then feel free to submit.

---

Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[task/task.proto, line 65 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAUYJqRtu4-qrrWDiQ:-KXAUYJqRtu4-qrrWDiR:b-hu3krf) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/task/task.proto#L65)):*
> ```protobuf
> message Membership {
> 	fixed64 id = 1;
> 	uint32 group = 2;
> ```

I think group means something in PBs.

---

*[worker/draft.go, line 108 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAWG1QVX0uShrbLDLE:-KXAWG1QVX0uShrbLDLF:bt7c3ek) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/worker/draft.go#L108)):*
> ```Go
> 	x.AssertTruef(len(addr) > 0, "Unable to find conn pool for peer: %d", pid)
> 
> 	rc := n.raftContext
> ```

You can avoid assigning this one.

---

*[worker/draft.go, line 447 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAWduTIrvbHMZSRb3R:-KXAWduTIrvbHMZSRb3S:b-q4q1ff) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/worker/draft.go#L447)):*
> ```Go
> }
> 
> func createRaftContext(id uint64, gid uint32, addr string) *task.RaftContext {
> ```

We can get rid of this as well.

---

*[worker/groups.go, line 237 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAY49AMFFDQzpPVNKk:-KXAY49BdwYTyBEfNsE0:b754qtu) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/worker/groups.go#L237)):*
> ```Go
> }
> 
> func buildTaskMembership(gid uint32, id uint64, addr string, leader bool) *task.Membership {
> ```

Also, can get rid of this. In general, I think any functions which are essentially constructing structs -- we can get rid of them; unless they have a decent chunk of logic in them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-:-KXAZPuEji_-NQUdnQK2:b-y1vv9b)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[task/task.proto, line 65 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAUYJqRtu4-qrrWDiQ:-KXA_b0L5LQVEspJURpo:bnaudd9) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/task/task.proto#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I think group means something in PBs.
</details>
Group is deprecated and this compiles ok. I think we are fine.

---

*[worker/draft.go, line 108 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAWG1QVX0uShrbLDLE:-KXA_vGmPUuvNNmWkPnp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/worker/draft.go#L108)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You can avoid assigning this one.
</details>
Done.

---

*[worker/draft.go, line 447 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAWduTIrvbHMZSRb3R:-KXAaMEKSz7Lv4Mmr2C7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/worker/draft.go#L447)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> We can get rid of this as well.
</details>
Done.

---

*[worker/groups.go, line 237 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/328#-KXAY49AMFFDQzpPVNKk:-KXAbA76XYu-W-EmC74l:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8d4732ecaeab5c3d87858a9f6cdc5d8898bf489d/worker/groups.go#L237)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Also, can get rid of this. In general, I think any functions which are essentially constructing structs -- we can get rid of them; unless they have a decent chunk of logic in them.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/328)*

**Pull request closed without merging**
