### PR TITLE
Throw errors when expand_edge=false

### LINKED ISSUE #1395: Error in delete with pattern when expand_edge is false
If `expand_edge` is set to `false`, `delete` mutation with predicate pattern doesn't work and there is no error/warning.

For the simple case:
```
mutation{
  set{
    <0x1> <name> "test" .
    <0x1> <alias> "test" .
  }
}
```

After running 
```
mutation {
  delete {
    <0x1> * * .
  }
}
```
data is not deleted, and no error nor warning is returned

Following query returns results (shows that nothing was deleted):
```
{
  me(func:uid(0x1)) {
    name
    alias
  } 
}
```

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #1395

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1398)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 1823 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1398#-KtA6BR74fRo7WUnXqPC:-KtA6BR8FZpWu9OapVpR:b-ix1tgb) ([raw file](https://github.com/dgraph-io/dgraph/blob/b69aab65d18c17b468b53397fba561a6b4eb791c/query/query.go#L1823)):*
> ```Go
> 
> 		if !worker.Config.ExpandEdge {
> 			rch <- x.Errorf("Cannot run expand() query when ExpandEdge(--expand_edge) is false.")
> ```

We need to throw error when users asks for _predicate_ also.
Probably do it at getNodepredicates in worker/task.go, then if a query uses _predicate_ edge then we would throw error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1398#-:-KtA6TC2kdLfC0GbnP5I:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 1823 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1398#-KtA6BR74fRo7WUnXqPC:-KtAAem_HdAQB2HuUxVz:b-5lc486) ([raw file](https://github.com/dgraph-io/dgraph/blob/b69aab65d18c17b468b53397fba561a6b4eb791c/query/query.go#L1823)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We need to throw error when users asks for _predicate_ also.
Probably do it at getNodepredicates in worker/task.go, then if a query uses _predicate_ edge then we would throw error.

</blockquote></details>

Good point,  is there even a function like that? Anyway, I think it's better to throw it in query.go as we avoid the network call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1398)*

**Comment by janardhan1993** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1398)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1398#-:-KtJidxOj9MtZhP_NTA-:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
