### PR TITLE
Don't set _xid_ when empty, also fix how _xid_ was returned when not empty.

### LINKED ISSUE #715: Querying _xid_ returns a malformed JSON that can't be parsed
I have compiled commit 1037adf and installed RocksDB from Arch repositories (I'm sorry, I don't know how to check RocksDB version).

You can check with this simple mutation

```
mutation {
 set {
   <mario> <name> "sayden" .
   <mario> <likes> <tesla> .
   <tesla> <name> "teslunia" .
 }
}
```

And this query

```
{
	me(id: mario){
		name
		likes {
			name
			_xid_
		}
	}
}
```

Returns `Unexpected ','` because, actually, response has the following data:

```
{"me":[{"likes":[{"_xid_":,"name":"teslunia"}],"name":"sayden"}]}
```

Look that `_xid_` returns nothing (not an empty string I mean)

Regards!

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #715.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/718)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-KfdwD7CO5kG5WceH346:-KfdwD7D0-zI3oTzB_sH:bp8wbzr) ([raw file](https://github.com/dgraph-io/dgraph/blob/11396de3807f9b032f4649a3daf80bbe48350a09/query/outputnode.go#L289)):*
> ```Go
> 
> func (fj *fastJsonNode) SetXID(xid string) {
> 	fj.attrs["_xid_"] = makeScalarAttr([]byte(fmt.Sprintf("\"%v\"", xid)))
> ```

Do we allow quotes in xid, if quotes are allowed then we should use %q instead of \"%v\". 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-:-KfdxeROIdhuDfhCp-rC:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-KfdwD7CO5kG5WceH346:-Kfe7vALFwZqPI3llv95:b-5ona0j) ([raw file](https://github.com/dgraph-io/dgraph/blob/11396de3807f9b032f4649a3daf80bbe48350a09/query/outputnode.go#L289)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Do we allow quotes in xid, if quotes are allowed then we should use %q instead of \"%v\". 
</blockquote></details>

Nice catch, updated it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/718)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-:-Kfe8y03BeVLRlSRw_Lw:bnfp4nl)*

**Comment by Motakjuq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-KfdwD7CO5kG5WceH346:-KfeKWjL9d5LXL1YuX6w:bl0kouv) ([raw file](https://github.com/dgraph-io/dgraph/blob/11396de3807f9b032f4649a3daf80bbe48350a09/query/outputnode.go#L289)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Nice catch, updated it.
</blockquote></details>

You should use strconv.Quote instead fmt.Sprintf in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/718)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-KfdwD7CO5kG5WceH346:-KfiBEhnUsZFmPiYxs6P:b-g4jsxh) ([raw file](https://github.com/dgraph-io/dgraph/blob/11396de3807f9b032f4649a3daf80bbe48350a09/query/outputnode.go#L289)):*
<details><summary><i>Previously, Motakjuq wrote…</i></summary><blockquote>

You should use strconv.Quote instead fmt.Sprintf in this case.
</blockquote></details>

I am not sure if there is difference between the two in terms of output? Is strconv.Quote faster?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/718)*

**Comment by Motakjuq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-KfdwD7CO5kG5WceH346:-KfihmVNxhUQtMoH0JT1:blnemch) ([raw file](https://github.com/dgraph-io/dgraph/blob/11396de3807f9b032f4649a3daf80bbe48350a09/query/outputnode.go#L289)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I am not sure if there is difference between the two in terms of output? Is strconv.Quote faster?
</blockquote></details>

In this case, you're only using %q as format, so the output is the same. The strconv.Quote is a little faster than fmt.Sprintf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/718)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 289 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/718#-KfdwD7CO5kG5WceH346:-KfjeH7qYHsh0aNuF_9q:bd9o1bh) ([raw file](https://github.com/dgraph-io/dgraph/blob/11396de3807f9b032f4649a3daf80bbe48350a09/query/outputnode.go#L289)):*
<details><summary><i>Previously, Motakjuq wrote…</i></summary><blockquote>

In this case, you're only using %q as format, so the output is the same. The strconv.Quote is a little faster than fmt.Sprintf
</blockquote></details>

I benchmarked this and strconv.Quote is marginally faster hence moving to it. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/718)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
