### PR TITLE
Switch from channel to slice in lexer, simplify lexer, enable peeking and more.

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/456)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[gql/parser.go, line 478 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0SFzqZh_dxQnymLQm:-Ka0SFzqZh_dxQnymLQn:b1dmijj) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/parser.go#L478)):*
> ```Go
> func getMutation(l *lex.Lexer) (*Mutation, error) {
> 	var mu *Mutation
> 	for item := l.NextTok(); item.Typ != lex.ItemEOF; item = l.NextTok() {
> ```

for itr.Next() {
  item := itr.Val()

  // itr.Prev() -- bool
  // items := itr.Peek(N)
}

---

*[gql/state.go, line 55 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0LoIrvdLGrXQ9ZxJg:-Ka0LoIrvdLGrXQ9ZxJh:bj8ag60) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state.go#L55)):*
> ```Go
> 	itemLeftRound                               // left round bracket
> 	itemRightRound                              // right round bracket
> 	itemCollon                                  // Collon
> ```

itemColon // Colon

---

*[gql/state.go, line 67 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0NqgKfMUjns-CGgBA:-Ka0NqgKfMUjns-CGgBB:baxpfgt) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state.go#L67)):*
> ```Go
> 
> // lexText lexes the input string and calls other lex functions.
> func lexText(l *lex.Lexer) lex.StateFn {
> ```

Split this function into smaller functions which do specific things.

---

*[gql/state_test.go, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0T_Q0ayxp8qpxHgJx:-Ka0T_Q0ayxp8qpxHgJy:b-vp64c0) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state_test.go#L75)):*
> ```Go
> 
> /*
> func TestAbruptMutation(t *testing.T) {
> ```

Why commented out?

---

*[gql/state_test.go, line 143 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0TXrXLlFk7Zdinti3:-Ka0TXrXLlFk7Zdinti4:b-vp64c0) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state_test.go#L143)):*
> ```Go
> 
> /*
> func TestVariablesError(t *testing.T) {
> ```

Why commented out?

---

*[lex/lexer.go, line 63 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0Pv5Z7p2BpH-6LxhT:-Ka0Pv5Z7p2BpH-6LxhU:b-itlzy9) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/lex/lexer.go#L63)):*
> ```Go
> 	Width           int    // width of last rune read from input.
> 	Items           []item // channel of scanned items.
> 	Idx             int    // Index of current token.
> ```

make Items and Idx private. In fact, idx could be part of an ItemIterator, which can be generated from a lexer. Then Next(), Prev() and Peek(n) would be part of that iterator.

---

*[schema/parse.go, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0R06qi_gsSop8oqsh:-Ka0R06qi_gsSop8oqsi:b-z4s266) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/schema/parse.go#L75)):*
> ```Go
> 
> func processScalarBlock(l *lex.Lexer) error {
> 	for item := l.NextTok(); item.Typ != lex.ItemEOF; item = l.NextTok() {
> ```

Parser should only have access to iterator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456)*

**Comment by jchiu0** [comment]
Review status: 5 of 8 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 441 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0gW8Kwi9SXyNvyEtI:-Ka0gW8Kwi9SXyNvyEtJ:b161pkz) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/gql/parser.go#L441)):*
> ```Go
> func getFragment(l *lex.Lexer) (*fragmentNode, error) {
> 	var name string
> 	for {
> ```

Not the usual for item := l.NextTok(); item.Typ != lex.ItemEOF; item = l.NextTok()?

---

*[gql/parser.go, line 604 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0hEA7RZEsWPbuP41a:-Ka0hEA7RZEsWPbuP41b:bkd1gmp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/gql/parser.go#L604)):*
> ```Go
> 			break
> 		} else {
> 			l.GoBack()
> ```

Why move back? Maybe a comment?

---

*[gql/parser.go, line 894 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0i88Py-k4Gm0ofrV8:-Ka0i88Py-k4Gm0ofrV9:b-cykmen) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/gql/parser.go#L894)):*
> ```Go
> 
> 	// Peeks items to see if its an argument or function.
> 	peekItems, err := l.PeekN(2)
> ```

Don't you need to consume these items?

---

*[lex/lexer.go, line 88 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0g3gqAmdiiESgWvJ4:-Ka0g3gqAmdiiESgWvJ5:b-g6zjbv) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/lex/lexer.go#L88)):*
> ```Go
> 		l.Idx--
> 	}
> 	return
> ```

No need for "return". Add comments for exported functions.

---

*[lex/lexer.go, line 91 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0g9_CjmMee1gRUfxZ:-Ka0g9_CjmMee1gRUfx_:bx2e59k) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/lex/lexer.go#L91)):*
> ```Go
> }
> 
> func (l *Lexer) PeekN(num int) ([]item, error) {
> ```

Comments on exported functions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456)*

**Comment by ashwin95r** [comment]
Review status: 2 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[gql/parser.go, line 478 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0SFzqZh_dxQnymLQm:-Ka15irw5KBOsiC5xZ9s:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/parser.go#L478)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

for itr.Next() {
  item := itr.Val()

  // itr.Prev() -- bool
  // items := itr.Peek(N)
}
</blockquote></details>

Done.

---

*[gql/parser.go, line 441 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0gW8Kwi9SXyNvyEtI:-Ka15bgYGN7ag15PzOGT:bz1i9m6) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/gql/parser.go#L441)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Not the usual for item := l.NextTok(); item.Typ != lex.ItemEOF; item = l.NextTok()?
</blockquote></details>

Not at this place.

---

*[gql/parser.go, line 604 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0hEA7RZEsWPbuP41a:-Ka16p60c7_qxpCymgwS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/gql/parser.go#L604)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Why move back? Maybe a comment?
</blockquote></details>

Done.

---

*[gql/parser.go, line 894 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0i88Py-k4Gm0ofrV8:-Ka16q4kiTbQ6AolCkee:b-hcte3l) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/gql/parser.go#L894)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Don't you need to consume these items?
</blockquote></details>

Peek is just to decide the path. The actual items will be consumed later.

---

*[gql/state.go, line 55 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0LoIrvdLGrXQ9ZxJg:-Ka0Xz4Du67o41zp9G_O:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state.go#L55)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

itemColon // Colon
</blockquote></details>

Done.

---

*[gql/state.go, line 67 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0NqgKfMUjns-CGgBA:-Ka0Xzx5dhgp2sXj7TkH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state.go#L67)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Split this function into smaller functions which do specific things.
</blockquote></details>

Done.

---

*[gql/state_test.go, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0T_Q0ayxp8qpxHgJx:-Ka0ZAAzOmHJ9zVe00US:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state_test.go#L75)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why commented out?
</blockquote></details>

Done.

---

*[gql/state_test.go, line 143 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0TXrXLlFk7Zdinti3:-Ka0Z99npceVeoAVWh75:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/gql/state_test.go#L143)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why commented out?
</blockquote></details>

Done.

---

*[lex/lexer.go, line 63 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0Pv5Z7p2BpH-6LxhT:-Ka15pvNSSvUSWFcuOFA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/lex/lexer.go#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

make Items and Idx private. In fact, idx could be part of an ItemIterator, which can be generated from a lexer. Then Next(), Prev() and Peek(n) would be part of that iterator.
</blockquote></details>

Done.

---

*[lex/lexer.go, line 88 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0g3gqAmdiiESgWvJ4:-Ka15w7JIo_wlVb0N78r:b67j85i) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/lex/lexer.go#L88)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

No need for "return". Add comments for exported functions.
</blockquote></details>

Modified the functions a bit.

---

*[lex/lexer.go, line 91 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0g9_CjmMee1gRUfxZ:-Ka16LZrnmh4TBvcqMbf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6ef60077cf8ec556d90c4a71389f59c3a232995/lex/lexer.go#L91)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Comments on exported functions
</blockquote></details>

Done.

---

*[schema/parse.go, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka0R06qi_gsSop8oqsh:-Ka16MOgr57Bf_f5UlI2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a77563e99adeba3c0f57c635c28c30ead53e0b1c/schema/parse.go#L75)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Parser should only have access to iterator.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456)*

**Comment by manishrjain** [comment]
Review status: 2 of 9 files reviewed at latest revision, 11 unresolved discussions.

---

*[gql/parser.go, line 305 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka18Wm6LkCeAH3oDC0I:-Ka18Wm6LkCeAH3oDC0J:b-59dm7e) ([raw file](https://github.com/dgraph-io/dgraph/blob/574a7ed63e267b8fe385a3b6432b6498c4798daa/gql/parser.go#L305)):*
> ```Go
> 	it := l.NewIterator()
> 	fmap := make(fragmentMap)
> 	for it.Valid() {
> ```

for it.Next() { item := it.Val() }

---

*[gql/parser.go, line 358 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1DpyUm-CDKl1FHezt:-Ka1DpyUm-CDKl1FHezu:bmfuaet) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/gql/parser.go#L358)):*
> ```Go
> // vmap. For variable list to be present, the query should have a name which is
> // also checked for. It also calls getQuery to create the GraphQuery object tree.
> func getVariablesAndQuery(it *lex.ParseIterator, vmap varMap) (gq *GraphQuery,
> ```

lex.ItemIterator

---

*[gql/state.go, line 198 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1EQFDMG7kHYV4qG0P:-Ka1EQFDMG7kHYV4qG0Q:b-nx7g21) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/gql/state.go#L198)):*
> ```Go
> 			l.Emit(itemLeftCurl)
> 			if l.Mode == mutationMode {
> 				return lexText
> ```

This if condition is not required given how you're doing things.

---

*[gql/state_test.go, line 40 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1Es5pJETUOr3-Ekjk:-Ka1Es5pJETUOr3-Ekjl:b-jqaf3h) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/gql/state_test.go#L40)):*
> ```Go
> 	}`
> 	l := &lex.Lexer{}
> 	l.Init(input)
> ```

We don't need Init. Something like this would be better

`l := lex.NewLexer(input).Run()`

---

*[lex/lexer.go, line 55 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1FLjCpn9em4YvoW9b:-Ka1FLjCpn9em4YvoW9c:b-2i956n) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/lex/lexer.go#L55)):*
> ```Go
> 
> type ParseIterator struct {
> 	items []item
> ```

might be better to use a pointer to lexer as we discussed. In case lexer needs to be concurrent, we'd still be able to access the items safely that way. But not this way.

---

*[lex/lexer.go, line 107 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1FeH1rUlRGUvuGbLt:-Ka1FeH1rUlRGUvuGbLu:bofgjq3) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/lex/lexer.go#L107)):*
> ```Go
> 	Width           int    // width of last rune read from input.
> 	Items           []item // channel of scanned items.
> 	Depth           int    // nesting of {}
> ```

A lot of these fields can now be private -- if we make Run() part of the lexer struct. Also, remove the ones you're no longer using.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456)*

**Comment by manishrjain** [comment]
Reviewed 2 of 7 files at r3, 5 of 5 files at r4.
Review status: 6 of 9 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456)*

**Comment by ashwin95r** [comment]
Review status: 2 of 9 files reviewed at latest revision, 11 unresolved discussions.

---

*[gql/parser.go, line 305 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka18Wm6LkCeAH3oDC0I:-Ka1G891NfwyLsPLRS7X:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/574a7ed63e267b8fe385a3b6432b6498c4798daa/gql/parser.go#L305)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

for it.Next() { item := it.Val() }
</blockquote></details>

Done.

---

*[gql/parser.go, line 358 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1DpyUm-CDKl1FHezt:-Ka1GA2X9pHcoZDA5GsM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/gql/parser.go#L358)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

lex.ItemIterator
</blockquote></details>

Done.

---

*[gql/state.go, line 198 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1EQFDMG7kHYV4qG0P:-Ka1NU8q9WwPO-4w_1Oi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/gql/state.go#L198)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This if condition is not required given how you're doing things.
</blockquote></details>

Done.

---

*[gql/state_test.go, line 40 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1Es5pJETUOr3-Ekjk:-Ka1LH65eMeOfdmDoJ4l:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/gql/state_test.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We don't need Init. Something like this would be better

`l := lex.NewLexer(input).Run()`
</blockquote></details>

Done.

---

*[lex/lexer.go, line 55 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1FLjCpn9em4YvoW9b:-Ka1LqBfVBsiZjhGBg0f:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/lex/lexer.go#L55)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

might be better to use a pointer to lexer as we discussed. In case lexer needs to be concurrent, we'd still be able to access the items safely that way. But not this way.
</blockquote></details>

Done.

---

*[lex/lexer.go, line 107 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1FeH1rUlRGUvuGbLt:-Ka1HD-_g3HKSNrE9rEJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/633a50bea95e05962fbe2a6f068c86139c46e883/lex/lexer.go#L107)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

A lot of these fields can now be private -- if we make Run() part of the lexer struct. Also, remove the ones you're no longer using.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r5.
Review status: 8 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[lex/lexer.go, line 120 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-Ka1QOcKIyFXM-ts2yEq:-Ka1QOcKIyFXM-ts2yEr:bv46fsx) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6ba73e0a665ae277bc0f6dfb940f27a4cbcc17b/lex/lexer.go#L120)):*
> ```Go
> }
> 
> func (l *Lexer) Run(f StateFn) {
> ```

return l

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-:-Ka1QUAaOo3zZ1a8Ime9:bnfp4nl)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 3 of 9 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/456#-:-Ka5fxP_EEYAPTodSg4Y:bnfp4nl)*

**Comment by ashwin95r** [comment]
Thanks! Merged.

**Pull request closed without merging**
