### PR TITLE
write hardstate after persisting the entries

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1365)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[raftwal/wal.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365#-KsaWGMEQxpRlagqM76Q:-KsaWGMEQxpRlagqM76R:b-k4q391) ([raw file](https://github.com/dgraph-io/dgraph/blob/16f03ac88a004997ff8503e3d14a0cebf6bf3158/raftwal/wal.go#L132)):*
> ```Go
> 	}
> 
> 	if !raft.IsEmptyHardState(h) {
> ```

Create a PR for godoc of Raft as well, so it's clear that hard state should be written only after entries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365#-:-KsaWOBMIrzsXYzU_fsl:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[raftwal/wal.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365#-KsaWGMEQxpRlagqM76Q:-KsaWq_RbBZ-7suW9mQn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16f03ac88a004997ff8503e3d14a0cebf6bf3158/raftwal/wal.go#L132)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a PR for godoc of Raft as well, so it's clear that hard state should be written only after entries.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365)*

**Comment by srh** [comment]
*[raftwal/wal.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365#-KsaWGMEQxpRlagqM76Q:-KsbJR5g-L9fikbKLyta:b-tm0dmd) ([raw file](https://github.com/dgraph-io/dgraph/blob/16f03ac88a004997ff8503e3d14a0cebf6bf3158/raftwal/wal.go#L132)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Or at the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365)*

**Comment by janardhan1993** [comment]
*[raftwal/wal.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365#-KsaWGMEQxpRlagqM76Q:-KsbMe1klnnrfkLMR9Hy:b-x8s9ug) ([raw file](https://github.com/dgraph-io/dgraph/blob/16f03ac88a004997ff8503e3d14a0cebf6bf3158/raftwal/wal.go#L132)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

Or at the same time.
</blockquote></details>

Badger doesn't support at the same time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365)*

**Comment by manishrjain** [comment]
*[raftwal/wal.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365#-KsaWGMEQxpRlagqM76Q:-Ksgyzu9jiLmYm4XV7JP:banvsxf) ([raw file](https://github.com/dgraph-io/dgraph/blob/16f03ac88a004997ff8503e3d14a0cebf6bf3158/raftwal/wal.go#L132)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Badger doesn't support at the same time.
</blockquote></details>

Well, it does. You could do one batched write for both hard state and snapshot. Would be faster than doing one after another.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365)*

**Comment by srh** [comment]
*[raftwal/wal.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365#-KsaWGMEQxpRlagqM76Q:-Kskd8f8fA6rKHRWgX86:bh4ttt8) ([raw file](https://github.com/dgraph-io/dgraph/blob/16f03ac88a004997ff8503e3d14a0cebf6bf3158/raftwal/wal.go#L132)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Well, it does. You could do one batched write for both hard state and snapshot. Would be faster than doing one after another.
</blockquote></details>

Badger doesn't write those in one atomic write to the value log though, so the order still matters for Badger.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1365)*

**Pull request merged**
