### PR TITLE
Vars in mutations -- rebased

### PR DESCRIPTION
**Pull request by szymonm**
@manishrjain Rebased the change and divided into smaller chunks -- commits.

First one is just about the changes in parsing. Also moved parsing of Mutation.Set and Mutation.Del from main.go to gql/parser.go.
Second one does the variable expansion for a subject. And also moves execution of mutation from main.go to query/mutation.go.
Third enables expansion for object as well. Moves execution of query from main.go to query/query.go.
The last one simplifies main.go by unifying httpHandlers, rpcHandler and share endpoint handling.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/999)

### CODE REVIEW

**Comment by szymonm** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/dgraph/main.go, line 127 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlTe2XqkSQwfNIJbSkx:-KlTe2XqkSQwfNIJbSky:b-8ar2vh) ([raw file](https://github.com/dgraph-io/dgraph/blob/fbb1b14a356dbcb5b837b66eaee6c86b3a3d3906/cmd/dgraph/main.go#L127)):*
> ```Go
> }
> 
> func convertToNQuad(ctx context.Context, mutation string) ([]*protos.NQuad, error) {
> ```

This is moved to rdf package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by manishrjain** [comment]
Reviewed 5 of 14 files at r1, 5 of 13 files at r2, 5 of 8 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 624 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXXsMsdGh9K0U4nbMS:-KlXXsMtQJxjUXm6higf:b39nc7x) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/cmd/dgraph/main.go#L624)):*
> ```Go
> 	mutation.Set, err = rdf.ConvertToNQuads(mutationString)
> 	if err != nil {
> 		x.TraceError(ctx, err)
> ```

not return?

---

*[cmd/dgraph/main.go, line 305 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlX_u4Kgv_mBrBQkkmx:-KlX_u4Kgv_mBrBQkkmy:b-nddnyy) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/cmd/dgraph/main.go#L305)):*
> ```Go
> 		return &protos.Value{&protos.Value_DefaultVal{s}}
> 	}
> 	qHash := func() string {
> ```

Why is this a function? why not `qhash := fmt.Sprintf(...)`

---

*[gql/parser.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXXz9emRCsV61VomcD:-KlXXz9emRCsV61VomcE:b-hb6seq) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L2)):*
> ```Go
> /*
> ```

Extra space?

---

*[gql/parser.go, line 473 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXYJcYDD5PbQS47KXP:-KlXYJcYDD5PbQS47KXQ:b-iajtcx) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L473)):*
> ```Go
> 	QueryVars    []*Vars
> 	Mutation     *Mutation
> 	MutationVars []string // mutations don't define vars so we have only needed.
> ```

Not sure what does your comment mean.

---

*[gql/parser.go, line 618 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXYyZhlEPT9QaWzBzW:-KlXYyZhlEPT9QaWzBzX:b3mwrp9) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L618)):*
> ```Go
> 			out = append(out, s[i-1])
> 		}
> 		out = append(out, s[len(s)-1])
> ```

You don't need this last append. If the last element was a duplicate, it would end up copying it over.

---

*[gql/parser_test.go, line 2469 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXZT8IBYgHzpjoNFhM:-KlXZT8IBYgHzpjoNFhN:b-tqrer3) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser_test.go#L2469)):*
> ```Go
> }
> 
> //func TestParseGeoJson(t *testing.T) {
> ```

Uncomment this.

---

*[query/query.go, line 244 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXcm4shisQga0pNeHy:-KlXcm4shisQga0pNeHz:bbf1ea4) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L244)):*
> ```Go
> }
> 
> func enrichSchema(updates []*protos.SchemaUpdate) error {
> ```

Not sure what this function does.

---

*[query/query.go, line 284 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXaQJQvIvfbgwMVJzS:-KlXaQJQvIvfbgwMVJzT:b-8i854z) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L284)):*
> ```Go
> }
> 
> func Execute(ctx context.Context, res gql.Result, l *Latency, mutationAllowed bool) (ExecuteResult, error) {
> ```

More than 3 arguments aren't allowed. 

Encapsulate these in a struct, and then call this function on that struct.

---

*[query/query.go, line 284 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXbCOAjrl3NMl713SY:-KlXbCOAjrl3NMl713SZ:b3bzu2q) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L284)):*
> ```Go
> }
> 
> func Execute(ctx context.Context, res gql.Result, l *Latency, mutationAllowed bool) (ExecuteResult, error) {
> ```

What is this execute for? Mutations? Because we also have query.Process(...)

---

*[query/query.go, line 306 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXajhYxnAkD1FoSbZ_:-KlXajhYxnAkD1FoSbZa:bghm653) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L306)):*
> ```Go
> 		}
> 
> 		depSet, indepSet = gql.WrapNQ(res.Mutation.Set, protos.DirectedEdge_SET).
> ```

Why bother with differentiating between RDFs which need variable, and which don't. If you see any RDF which needs a variable, you can just postpone the execution of all of them. That would result in a simpler code.

---

*[query/query.go, line 1348 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXbULY0X298dvgy_nq:-KlXbULY0X298dvgy_nr:b-kawrwd) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L1348)):*
> ```Go
> }
> 
> func ProcessQuery(ctx context.Context, res gql.Result, l *Latency) ([]*SubGraph, map[string]varValue, error) {
> ```

Again. Create a struct for this request. And have both Execute() and Process() functions attached to this struct. It can also contain the context and latency for e.g. Would result in cleaner code.

---

*[rdf/parse.go, line 80 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXc-mVAXuXqsNECXq7:-KlXc-mVAXuXqsNECXq8:b-pr2zpo) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/rdf/parse.go#L80)):*
> ```Go
> 			}
> 			if len(rnq.SubjectVar) > 0 {
> 				return rnq, x.Errorf("Can't use variable in both subject and object: %s", line)
> ```

Why should we have this restriction? I think we talked about this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by szymonm** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 624 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXXsMsdGh9K0U4nbMS:-KlXeRwnEeXAVcTSyMXG:bw8miwc) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/cmd/dgraph/main.go#L624)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

not return?
</blockquote></details>

need to fix!

---

*[cmd/dgraph/main.go, line 305 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlX_u4Kgv_mBrBQkkmx:-KlXeNBIiHEcMAHjddLT:bdaloh0) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/cmd/dgraph/main.go#L305)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why is this a function? why not `qhash := fmt.Sprintf(...)`
</blockquote></details>

No reason... some failed refactoring probably.

---

*[gql/parser.go, line 2 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXXz9emRCsV61VomcD:-KlXeVC90KvAP9cBcgMM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Extra space?
</blockquote></details>

Done.

---

*[gql/parser.go, line 473 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXYJcYDD5PbQS47KXP:-KlXekc7TgPnUGRtuD10:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L473)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not sure what does your comment mean.
</blockquote></details>

Done.

---

*[gql/parser.go, line 618 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXYyZhlEPT9QaWzBzW:-KlXfRdLlluPOCCeMUHf:b-vdzsw3) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L618)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need this last append. If the last element was a duplicate, it would end up copying it over.
</blockquote></details>

I do. Note that I start the for loop from 1 and append always `s[i-1]`, so when reach last element I do continue and the previous is never appended.

Will add tests for this method including this case.

---

*[gql/parser_test.go, line 2469 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXZT8IBYgHzpjoNFhM:-KlXftgMYWcCuNN5Wlvk:bk1cjit) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser_test.go#L2469)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Uncomment this.
</blockquote></details>

This test is wrong according to our discussion on dev with Janardhan. We don't allow multiline rdf object in rdf. It wasn't failing before, because we didn't parse mutation in Parse function before.

---

*[query/query.go, line 244 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXcm4shisQga0pNeHy:-KlXgEkNBXoWgvaZv3w4:b11vvi2) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L244)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not sure what this function does.
</blockquote></details>

Me too actually... it was only moved in this PR. 
I will do separate PR with some cleanup of it and additional docs.

---

*[query/query.go, line 284 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXbCOAjrl3NMl713SY:-KlXgYH0ROdsPHTPfdwE:b5tezn6) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L284)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What is this execute for? Mutations? Because we also have query.Process(...)
</blockquote></details>

That's a confusion about naming we have to deal with (maybe separate PR?). In some places query includes mutation and schema changes and in some it does not (query block only).
query.Process() is for the query without mutation while query.Execute includes mutation handling.

Any naming ideas?

---

*[query/query.go, line 284 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXaQJQvIvfbgwMVJzS:-KlXib50QGD9gNhmL07p:b-mqob7q) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L284)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

More than 3 arguments aren't allowed. 

Encapsulate these in a struct, and then call this function on that struct.

</blockquote></details>

Yes, I remember will do it everywhere. Didn't wanted to make the change before we have a agreement on the overall PR direction, because it involves a lot of silly refactoring.

---

*[query/query.go, line 306 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXajhYxnAkD1FoSbZ_:-KlXhFnWGQ70ScdsLzUf:b-7ax5cy) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L306)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why bother with differentiating between RDFs which need variable, and which don't. If you see any RDF which needs a variable, you can just postpone the execution of all of them. That would result in a simpler code.
</blockquote></details>

I agree with. @ashwin95r was thinking that it might be handy for users to be able to do something like:
```
		mutation {
			set {
                                <me>          <friend>   <alice> .
                                <me>          <friend>   <bob> .
                                <me>          <friend>   <chris> .
				<me>          <likes>      var(myfriend) .
			}
		}
		{
			me(id: me) {
				myfriend as friend
			}
		}
```
In this case we split the NQuads and have the slightly complicated code.

I would probably opt for allowing to have many mutation blocks and execute blocks together. If a block contains a variable it will be executed after the query block.

WDYT?

---

*[rdf/parse.go, line 80 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXc-mVAXuXqsNECXq7:-KlXj14dvm9voTxMd9Rj:bs7xxwj) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/rdf/parse.go#L80)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why should we have this restriction? I think we talked about this.
</blockquote></details>

Oh, that needs to be fixed here. It's already implemented to allow referencing 2 vars in NQuad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by szymonm** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 624 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXXsMsdGh9K0U4nbMS:-KlY0s-_Vyum2XBJRfO_:b1c3gfx) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/cmd/dgraph/main.go#L624)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

need to fix!
</blockquote></details>

Oh, return here would return from `func fail`, we need to return from `shareHandler` after calling `fail`.

---

*[query/query.go, line 244 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXcm4shisQga0pNeHy:-KlYY3Bz0jeraEEtgTHK:b-mrchki) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L244)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

Me too actually... it was only moved in this PR. 
I will do separate PR with some cleanup of it and additional docs.
</blockquote></details>

Btw. it resolves verifies tokenizer definitions and resolves default ones.

---

*[query/query.go, line 284 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXbCOAjrl3NMl713SY:-KlYK_zbruVoF07CpAoK:bczdk8w) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L284)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

That's a confusion about naming we have to deal with (maybe separate PR?). In some places query includes mutation and schema changes and in some it does not (query block only).
query.Process() is for the query without mutation while query.Execute includes mutation handling.

Any naming ideas?


</blockquote></details>

Ideally I would separate logic of query block and mutation execution into different packages. Maybe create package execution that will have code of executing mutation and subpackage query with contents of current query package?

---

*[query/query.go, line 1348 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXbULY0X298dvgy_nq:-KlYUDI_AvWLGcyaAacl:botx6f9) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L1348)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Again. Create a struct for this request. And have both Execute() and Process() functions attached to this struct. It can also contain the context and latency for e.g. Would result in cleaner code.
</blockquote></details>

Don't think it's gonna be a good abstraction. ProcessQuery uses only 2/5 fields of gql.Result. We should change ProcessQuery to explicitly use only res.Query and res.QueryVars, so maybe introduce another struct for that.

Also what do you think about extending context with latency? We would have something like:
```
type QueryContext struct {
   context.Context
   Latency *Latency
}

type queryResult {
   subgraphs []*SubGraph,
   variables map[string]varValue
}

func processQuery(ctx QueryContext, query []*GraphQuery, vars []*Vars) (QueryResult, error)

func Execute(ctx QueryContext, res gql.Result) (ExecuteResult, error)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by manishrjain** [comment]
Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 618 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXYyZhlEPT9QaWzBzW:-KlrZmana1m9uxnrbMyK:b-7hi4cj) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L618)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

I do. Note that I start the for loop from 1 and append always `s[i-1]`, so when reach last element I do continue and the previous is never appended.

Will add tests for this method including this case.
</blockquote></details>

```
out := s[:0]
for i := range s {
  if i > 0 && s[i] == s[i-1] {
    continue
  }
  out = append(out, s[i])
}
```

---

*[query/query.go, line 306 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXajhYxnAkD1FoSbZ_:-Klr3vhY9xKeqttufFSd:b-bn3s2u) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L306)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

I agree with. @ashwin95r was thinking that it might be handy for users to be able to do something like:
```
		mutation {
			set {
                                <me>          <friend>   <alice> .
                                <me>          <friend>   <bob> .
                                <me>          <friend>   <chris> .
				<me>          <likes>      var(myfriend) .
			}
		}
		{
			me(id: me) {
				myfriend as friend
			}
		}
```
In this case we split the NQuads and have the slightly complicated code.

I would probably opt for allowing to have many mutation blocks and execute blocks together. If a block contains a variable it will be executed after the query block.

WDYT?
</blockquote></details>

Whatever results in simpler code. Yeah. One can have many mutation blocks instead, and just let them be executed earlier.

---

*[query/query.go, line 295 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlrakAqrLsg4caXY-_u:-KlrakArIH2OFdC6A1CW:b-9h41rp) ([raw file](https://github.com/dgraph-io/dgraph/blob/e21d53bd60414428e1556fc2a54991b38cea4f6c/query/query.go#L295)):*
> ```Go
> }
> 
> func Execute(ctx ExecutionContext, res gql.Result) (ExecuteResult, error) {
> ```

ProcessQueryWithMutation

queryRequest.ProcessWithMutation() queryResponse
queryRequest.Process() => this doesn't return queryResponse?

queryState: Subgraphs []*Subgraph, Vars []*Var, ...

queryRequest => {Latency, gqlQuery gql.Result}
qr.ProcessWithMutation(context.Context) => (result, err)

queryRequest => Variables, which qr.Process() would fill.

qr.processQuery(result *result) -- error.
qr.processMutations(result *result) error // has access to variables.

---

*[query/query.go, line 296 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlraomvrJbqBJmf_DJ6:-KlraomvrJbqBJmf_DJ7:b-qb0ehv) ([raw file](https://github.com/dgraph-io/dgraph/blob/e21d53bd60414428e1556fc2a54991b38cea4f6c/query/query.go#L296)):*
> ```Go
> 
> func Execute(ctx ExecutionContext, res gql.Result) (ExecuteResult, error) {
> 	var er ExecuteResult
> ```

`(er ExecuteResult, err error)` in the function itself.

---

*[query/query.go, line 328 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlrfKpMZSFOsDJHNbaP:-KlrfKpMZSFOsDJHNbaQ:b-cxycfp) ([raw file](https://github.com/dgraph-io/dgraph/blob/e21d53bd60414428e1556fc2a54991b38cea4f6c/query/query.go#L328)):*
> ```Go
> 			Partition(gql.HasVariables)
> 
> 		var mr MaterializedMutation
> ```

internalMutation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by szymonm** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 618 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXYyZhlEPT9QaWzBzW:-KmB_B0TRd-lwFRMcjAk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6cc71c7dfcd287ddf9892ea503e89e550c2d3306/gql/parser.go#L618)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

```
out := s[:0]
for i := range s {
  if i > 0 && s[i] == s[i-1] {
    continue
  }
  out = append(out, s[i])
}
```
</blockquote></details>

Done.

---

*[query/query.go, line 295 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlrakAqrLsg4caXY-_u:-KmCXiOIklrC5XG5--r_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e21d53bd60414428e1556fc2a54991b38cea4f6c/query/query.go#L295)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ProcessQueryWithMutation

queryRequest.ProcessWithMutation() queryResponse
queryRequest.Process() => this doesn't return queryResponse?

queryState: Subgraphs []*Subgraph, Vars []*Var, ...

queryRequest => {Latency, gqlQuery gql.Result}
qr.ProcessWithMutation(context.Context) => (result, err)

queryRequest => Variables, which qr.Process() would fill.

qr.processQuery(result *result) -- error.
qr.processMutations(result *result) error // has access to variables.
</blockquote></details>

Done.

---

*[query/query.go, line 296 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlraomvrJbqBJmf_DJ6:-KmCXjA47iW_CJaNKpg2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e21d53bd60414428e1556fc2a54991b38cea4f6c/query/query.go#L296)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`(er ExecuteResult, err error)` in the function itself.
</blockquote></details>

Done.

---

*[query/query.go, line 328 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlrfKpMZSFOsDJHNbaP:-KmCXl9ZduN6l90KyGbn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e21d53bd60414428e1556fc2a54991b38cea4f6c/query/query.go#L328)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

internalMutation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by szymonm** [comment]
Review status: 2 of 24 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 306 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KlXajhYxnAkD1FoSbZ_:-KmCdfBNTWCobcYN_7Zz:b-rzyorw) ([raw file](https://github.com/dgraph-io/dgraph/blob/44c72a8b8522cc1a1bb75783c6cf9501b13c30e6/query/query.go#L306)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Whatever results in simpler code. Yeah. One can have many mutation blocks instead, and just let them be executed earlier.
</blockquote></details>

The code is not that complicated after other simplifications. Please have a look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by szymonm** [comment]
Review status: 2 of 24 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 230 at r10](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KmQXO3jwsyWj_ggpMwL:-KmS_jjJAqUCshiABBGy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/76485677d9f16d23112f5bdf3431ea3c7edd4d19/cmd/dgraph/main.go#L230)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if res, err = 
</blockquote></details>

Done.

---

*[query/query.go, line 2170 at r10](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KmQZ9yO2ubEoBVBf4Vn:-KmSaZh5gyC39UkXsujc:b-6rvegi) ([raw file](https://github.com/dgraph-io/dgraph/blob/76485677d9f16d23112f5bdf3431ea3c7edd4d19/query/query.go#L2170)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't need these.
</blockquote></details>

I want to distinguish two types of errors raised by ProcessWithMutation function.
InternalError should trigger Http response with 500 code.
InvalidRequestError should trigger 400.

---

*[query/query.go, line 2178 at r10](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KmQZFCulRCoEKYQav1M:-KmSbDi_HnxEma6iEj3h:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/76485677d9f16d23112f5bdf3431ea3c7edd4d19/query/query.go#L2178)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't need this.
</blockquote></details>

Done.

---

*[query/query.go, line 2237 at r10](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KmQZI4f4jt2Ib4Y81YQ:-KmStWuVP461V45U_se_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/76485677d9f16d23112f5bdf3431ea3c7edd4d19/query/query.go#L2237)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Comment by szymonm** [comment]
Review status: 2 of 24 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 2025 at r10](https://reviewable.io:443/reviews/dgraph-io/dgraph/999#-KmQYnhM6JuSWS_09DL9:-KmSt_fX8sB3Q5-sTs4g:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/76485677d9f16d23112f5bdf3431ea3c7edd4d19/query/query.go#L2025)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't extend from Latency. Use a variable here. `Latency *Latency`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/999)*

**Pull request merged**
