### PR TITLE
Enable vendoring using GOVENDOR

### PR DESCRIPTION
**Pull request by thezelus**
Resolves - https://discuss.dgraph.io/t/vendoring-dependencies-for-dgraph/177

Pertaining to the discussion referenced above: GLOCKFILE has been removed,
README has been updated, and vendor/vendor.json has been added. At this
point of time we are only adding dependency information file(vendor.json) and
not the actual dependencies. This commit also helps in avoiding
installation of dependencies in $GOPATH if vendor directory is synced
using govendor.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/84)

### CODE REVIEW

**Comment by dan-compton** [comment]
👍 Much appreciated.  Random thought: maybe add .gitignore like:
```
./vendor/*
!./vendor.json
```

**Comment by manishrjain** [comment]
Please update Dockerfile as well.

<details><summary><i>Previously, dan-compton wrote…</i></summary>
> 👍 Much appreciated.  Random thought: maybe add .gitignore like:
> 
> ```
> 
> ./vendor/*
> 
> !./vendor/vendor.json
> 
> ```</details>


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vendor/vendor.json, line 3 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-KHrhVxRQ3LwRjyQgfgZ:-KHrhVxRQ3LwRjyQgfg_:124709992) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dbaf2ea82bacb4a7e94955fbdf13e17e85c8f7e/vendor/vendor.json#L3)):*
> ```JSON
> {
> 	"comment": "",
> 	"ignore": "test",
> ```

What does this mean?

---

*[vendor/vendor.json, line 5 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-KHrhJ1KsJ2Ryeaadtqc:-KHrhJ1KsJ2Ryeaadtqd:-2139678984) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dbaf2ea82bacb4a7e94955fbdf13e17e85c8f7e/vendor/vendor.json#L5)):*
> ```JSON
> 	"ignore": "test",
> 	"package": [
> 		{
> ```

Please use 2 space tabs in the file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-:-KHrhGl-e5hiAO8BkMY2:-1829808336)*

**Comment by thezelus** [comment]
Updated Dockerfile, though I don't really have a way to test out the changes to original one as `govendor sync` fails to find a vendor folder in the master branch.

<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Please update Dockerfile as well.</details>


---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[vendor/vendor.json, line 3 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-KHrhVxRQ3LwRjyQgfgZ:-KHrm2asJ5_s3iLwrTc2:-558748275) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dbaf2ea82bacb4a7e94955fbdf13e17e85c8f7e/vendor/vendor.json#L3)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> What does this mean?</details>
The file is auto-generated by govendor, but setting "test" as an value for ignore (which is the default value too) means that when syncing dependency repositories it will not get the test files for them.

https://github.com/kardianos/govendor#ignoring-build-tags

---

*[vendor/vendor.json, line 5 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-KHrhJ1KsJ2Ryeaadtqc:-KHrmtqz-o7t1p6MOJZF:2002148303) ([raw file](https://github.com/dgraph-io/dgraph/blob/9dbaf2ea82bacb4a7e94955fbdf13e17e85c8f7e/vendor/vendor.json#L5)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Please use 2 space tabs in the file.</details>
It is an auto-generated file, I don't think I can set that as an option anywhere in govendor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-:-KHrrFxGfOh5d0QW8UHI:-1109870199)*

**Comment by manishrjain** [comment]
Looking good. Any opinions on the .gitignore idea by Dan? Would it make sense?

<details><summary><i>Previously, thezelus (Abhishek Sharma) wrote…</i></summary>
> Updated Dockerfile, though I don't really have a way to test out the changes to original one as `govendor sync` fails to find a vendor folder in the master branch.</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-:-KHrzx5w0bO8wtSQMmyG:757631335)*

**Comment by thezelus** [comment]
Personally, I just prefer to have a local gitignore (https://www.gitignore.io/) as people have different preferences for their development environment.

Can we get back to this once I get some time (was tied up with other tasks this weekend) to research Dan's suggestion regarding squashing commits vs submodules (Option #2)?

**Comment by manishrjain** [comment]
OK. I think it looks good for now. I'll merge it.

<details><summary><i>Previously, thezelus (Abhishek Sharma) wrote…</i></summary>
> Personally, I just prefer to have a local gitignore (https://www.gitignore.io/) as people have different preferences for their development environment.
> 
> 
> 
> Can we get back to this once I get some time (was tied up with other tasks this weekend) to research Dan's suggestion regarding squashing commits vs submodules (Option #2)?</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-:-KHs1Gdzh59HQBopBXOo:1154139760)*

**Comment by thezelus** [comment]
Thanks.

**Comment by manishrjain** [comment]
Thanks for taking this on.

<details><summary><i>Previously, thezelus (Abhishek Sharma) wrote…</i></summary>
> Thanks.</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/84#-:-KHs1fRaUIoEwQkpmA3d:-834882944)*

**Pull request merged**
