### PR TITLE
Sort DestUids but retain order in UidMatrix

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/621)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[algo/uidlist.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdV0HCemNXnliIQHSeM:-KdV0HCemNXnliIQHSeN:b-r5ptj4) ([raw file](https://github.com/dgraph-io/dgraph/blob/82a1cfc91629449a887c3648ef6f738e1211e988/algo/uidlist.go#L30)):*
> ```Go
> }
> 
> func Sort(ul *task.List) {
> ```

This seems really inefficient. Why don't we sort the `task.List` directly? Why convert to 1d array first, then sort, then write it back?

---

*[query/query.go, line 640 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdV1PDfbMYknUgWI7Kz:-KdV1PDfbMYknUgWI7L-:b-jzhpxh) ([raw file](https://github.com/dgraph-io/dgraph/blob/82a1cfc91629449a887c3648ef6f738e1211e988/query/query.go#L640)):*
> ```Go
> 	if len(gq.UID) > 0 {
> 		o1 := new(task.List)
> 		o2 := new(task.List)
> ```

sg.SrcUids = new(task.List)

---

*[query/query.go, line 642 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdV1Tcjinb6VurPP-Rq:-KdV1Tcjinb6VurPP-Rr:bujgdq9) ([raw file](https://github.com/dgraph-io/dgraph/blob/82a1cfc91629449a887c3648ef6f738e1211e988/query/query.go#L642)):*
> ```Go
> 		o2 := new(task.List)
> 		it1 := algo.NewWriteIterator(o1, 0)
> 		it2 := algo.NewWriteIterator(o2, 0)
> ```

Don't use digit at the end of var name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/621)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[algo/uidlist.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdV0HCemNXnliIQHSeM:-KdV_rfsquuwaXkhK-Kn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/82a1cfc91629449a887c3648ef6f738e1211e988/algo/uidlist.go#L30)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This seems really inefficient. Why don't we sort the `task.List` directly? Why convert to 1d array first, then sort, then write it back?
</blockquote></details>

Done.

---

*[query/query.go, line 640 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdV1PDfbMYknUgWI7Kz:-KdV_snSeOe3_vf1iaLq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/82a1cfc91629449a887c3648ef6f738e1211e988/query/query.go#L640)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

sg.SrcUids = new(task.List)
</blockquote></details>

Done.

---

*[query/query.go, line 642 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdV1Tcjinb6VurPP-Rq:-KdV_tQNQNfGOtT18hun:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/82a1cfc91629449a887c3648ef6f738e1211e988/query/query.go#L642)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't use digit at the end of var name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/621)*

**Comment by gacharya255** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query.go, line 650 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdY_yN5H9RiUtPZcgGy:-KdY_yN5H9RiUtPZcgGz:b-7jbqan) ([raw file](https://github.com/dgraph-io/dgraph/blob/10baeda6adb0d0fcf3b4bb22b594dde06b57c9a1/query/query.go#L650)):*
> ```Go
> 		itsg.End()
> 		sg.uidMatrix = []*task.List{o}
> 		// User specified list maynot be sorted.
> ```

space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-:-KdYac-7zWSUpifuOUXZ:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[query/query.go, line 650 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/621#-KdY_yN5H9RiUtPZcgGy:-KdYqt4cKZygG_EXsh6x:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/10baeda6adb0d0fcf3b4bb22b594dde06b57c9a1/query/query.go#L650)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/621)*

**Pull request closed without merging**
