### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/134)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Makefile, line 8 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYdVlb1r-iFPHMUhlW:-KMYdVlb1r-iFPHMUhlX:32579370) ([raw file](https://github.com/dgraph-io/dgraph/blob/9b2f9bd6bfa54d7baaf72f71af5e829ce14be66d/Makefile#L8)):*
> ```Makefile
> build: BUILDMODE = build
> build: install
> 	mkdir dgraph;\
> ```

create a var for tmp directory. Possibly point it to /tmp/dgraph-build or something. Delete if it already exists.

Do the tar from within it, because we're no longer doing `dgraph/binary`. Remember to delete it at the end.

---

*[Makefile, line 10 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYdGM1flEbF9jrmKrd:-KMYdGM2Vs6iQ8u6k5ON:184257629) ([raw file](https://github.com/dgraph-io/dgraph/blob/9b2f9bd6bfa54d7baaf72f71af5e829ce14be66d/Makefile#L10)):*
> ```Makefile
> 	mkdir dgraph;\
> 	cd dgraph;\
> 	cp ../cmd/dgraph/dgraph .;\
> ```

This seems relative to current directory.

---

*[Makefile, line 25 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYe3eTQIbL5xLqaPJH:-KMYe3eTQIbL5xLqaPJI:1141121714) ([raw file](https://github.com/dgraph-io/dgraph/blob/9b2f9bd6bfa54d7baaf72f71af5e829ce14be66d/Makefile#L25)):*
> ```Makefile
> dgraph:
> 	cd "./cmd/dgraph" ; \
> 	$(GO) $(BUILDMODE) --tags=embed . ; 
> ```

tags embed should be part of buildmode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/134)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[Makefile, line 8 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYdVlb1r-iFPHMUhlW:-KMYhHITocTbJclfLxDL:1993724483) ([raw file](https://github.com/dgraph-io/dgraph/blob/9b2f9bd6bfa54d7baaf72f71af5e829ce14be66d/Makefile#L8)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> create a var for tmp directory. Possibly point it to /tmp/dgraph-build or something. Delete if it already exists.
> 
> Do the tar from within it, because we're no longer doing `dgraph/binary`. Remember to delete it at the end.
</details>
It creates a directory in the dgraph root folder, copies the binaries into it and creates a tar file without the parent directory and then deletes the parent directory.

---

*[Makefile, line 10 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYdGM1flEbF9jrmKrd:-KMYhVIrCq7fbE6s5VpU:160394146) ([raw file](https://github.com/dgraph-io/dgraph/blob/9b2f9bd6bfa54d7baaf72f71af5e829ce14be66d/Makefile#L10)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This seems relative to current directory.
</details>
Yes

---

*[Makefile, line 25 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYe3eTQIbL5xLqaPJH:-KMYfJ6nMY74WIWPIJV5:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/9b2f9bd6bfa54d7baaf72f71af5e829ce14be66d/Makefile#L25)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> tags embed should be part of buildmode.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/134)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 8 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYdVlb1r-iFPHMUhlW:-KMYlOs_HmQAbuRc-wjK:-156639280) ([raw file](https://github.com/dgraph-io/dgraph/blob/9b2f9bd6bfa54d7baaf72f71af5e829ce14be66d/Makefile#L8)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> It creates a directory in the dgraph root folder, copies the binaries into it and creates a tar file without the parent directory and then deletes the parent directory.
</details>
Yeah, I understood that. My point was to not create a directory in the repo itself. If the build fails, you end up with all these remaining files in your git folder.

---

*[Makefile, line 14 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYl575i5_XCU15cF-u:-KMYl576m8qbaTJAEQ_e:-420310815) ([raw file](https://github.com/dgraph-io/dgraph/blob/e767e4985ac99ced1d5b8569992c0402eff88282/Makefile#L14)):*
> ```Makefile
> 	cp ../cmd/dgraphmerge/dgraphmerge .;\
> 	cd ..;\
> 	tar -zcf dgraph-linux-amd64-v0.4.0.tar.gz -C dgraph-build .;\
> ```

Add a var for version number. And for linux or darwin. Can't this makefile figure out which platform this is and name accordingly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/134)*

**Comment by manishrjain** [comment]
Looks clean and easy to understand. Good work!

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[build.sh, line 11 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1NWEXB-5sRQ5-tca:-KMb1NWEXB-5sRQ5-tcb:1693956041) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L11)):*
> ```Shell
>   rm -rf $tmp_dir
> fi
> ```

Test if `strip` is available.

---

*[build.sh, line 18 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1D50bMj1r1v5Vaqi:-KMb1D50bMj1r1v5Vaqj:-308104502) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L18)):*
> ```Shell
> echo -e "\033[1;33mBuilding binaries\033[0m"
> echo "dgraph"
> cd $dgraph_cmd/dgraph && go build .;
> ```

Use a build flags variable.

---

*[build.sh, line 31 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1XkPXVM3Us_gekP1:-KMb1XkPXVM3Us_gekP2:1299435000) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L31)):*
> ```Shell
> cd $tmp_dir;
> cp $dgraph_cmd/dgraph/dgraph $dgraph_cmd/dgraphassigner/dgraphassigner $dgraph_cmd/dgraphlist/dgraphlist $dgraph_cmd/dgraphmerge/dgraphmerge $dgraph_cmd/dgraphloader/dgraphloader .;
> ```

Strip the binaries here. Report total size after strip.

---

*[build.sh, line 35 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1cYHbTe0Gd3upm23:-KMb1cYHbTe0Gd3upm24:-1935580454) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L35)):*
> ```Shell
> tar_file=dgraph-"$(uname | tr '[:upper:]' '[:lower:]')"-amd64-v$release_version
> tar -zcf $tar_file.tar.gz dgraph dgraphassigner dgraphlist dgraphmerge dgraphloader;
> ```

Report size of tar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-:-KMb1hU9nU2HN_WKe2_i:1936986869)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[build.sh, line 11 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1NWEXB-5sRQ5-tca:-KMbbNO--idABGM39aZ1:2111658358) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L11)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Test if `strip` is available.
</details>
Doing it before stripping the files.

---

*[build.sh, line 18 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1D50bMj1r1v5Vaqi:-KMbbE9ssSo19iC_DExz:-498922205) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L18)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Use a build flags variable.
</details>
Did you mean using `-tags=embed` or a variable for it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/134)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[build.sh, line 11 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1NWEXB-5sRQ5-tca:-KMbl3i4Bka0ke8X3Q7A:676635175) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L11)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Doing it before stripping the files.
</details>
Done

---

*[build.sh, line 18 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1D50bMj1r1v5Vaqi:-KMbl8fjP8GpnpDYjWUP:676635175) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L18)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Did you mean using `-tags=embed` or a variable for it?
</details>
Done

---

*[build.sh, line 31 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1XkPXVM3Us_gekP1:-KMbl9QrYtdBZQDcmTKI:676635175) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Strip the binaries here. Report total size after strip.
</details>
Done

---

*[build.sh, line 35 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMb1cYHbTe0Gd3upm23:-KMblAUTwSVl16HQGx1J:676635175) ([raw file](https://github.com/dgraph-io/dgraph/blob/bbc978d6fb32472361f9996196f4611063a4ac17/build.sh#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Report size of tar.
</details>
Done

---

*[Makefile, line 14 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMYl575i5_XCU15cF-u:-KMblJHeoDi5vQeIarxn:676635175) ([raw file](https://github.com/dgraph-io/dgraph/blob/e767e4985ac99ced1d5b8569992c0402eff88282/Makefile#L14)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Add a var for version number. And for linux or darwin. Can't this makefile figure out which platform this is and name accordingly?
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/134)*

**Comment by manishrjain** [comment]
:lgtm_strong:  One small wording change. Otherwise, LG! Good job!

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[build.sh, line 16 \[r7\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-KMblfQXg3_t2iaO5E9X:-KMblfQXg3_t2iaO5E9Y:1150512007) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0e6a5ba2d1c02e6ae7452522036338fd4eaaeaf/build.sh#L16)):*
> ```Shell
> 
> if ! type strip > /dev/null; then
>   echo -e "\033[0;31mYou don't have strip command line tool available. Download it and try again.\033[0m"
> ```

Install it and try again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/134#-:-KMblpvDkTwmHbyMqhtd:702189327)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
