### PR TITLE
Improve facet key handling

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/645)

### CODE REVIEW

**Comment by ashishnegi** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[gql/parser.go, line 968 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/645#-Ke30IlAbA0NiUpERten:-Ke30IlBu_g7gbpGcK9k:b48d7na) ([raw file](https://github.com/dgraph-io/dgraph/blob/9bf77720af4f4f2748774db0ab48c510d15da70a/gql/parser.go#L968)):*
> ```Go
> 		sort.Strings(facets.Keys)
> 	}
> 	if len(facets.Keys) > 1 {
> ```

may be moving this block after `sort.Strings` is better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/645#-:-Ke30nzDk6aLyIH8dou9:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[gql/parser.go, line 968 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/645#-Ke30IlAbA0NiUpERten:-Ke7IP-e4bVlzY-D4xfZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9bf77720af4f4f2748774db0ab48c510d15da70a/gql/parser.go#L968)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

may be moving this block after `sort.Strings` is better.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/645)*

**Comment by gacharya255** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 978 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/645#-Ke7Ix5IsYG02qIDqZRl:-Ke7Ix5JqeQo7zLwzqIw:bkm1d1t) ([raw file](https://github.com/dgraph-io/dgraph/blob/a384eafc0dd9fcc7b0aa069e23c87c12cb04c22a/gql/parser.go#L978)):*
> ```Go
> 			j++
> 		}
> 		facets.Keys[j] = facets.Keys[i-1]
> ```

You can use "slicetricks" to make this nicer. Like a = facets.Keys[:0]; a=append(a, facets.keys[i-1]). Then after loop, facets.Keys = a.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/645)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 978 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/645#-Ke7Ix5IsYG02qIDqZRl:-Ke7LusDMiH1G6asbuho:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a384eafc0dd9fcc7b0aa069e23c87c12cb04c22a/gql/parser.go#L978)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

You can use "slicetricks" to make this nicer. Like a = facets.Keys[:0]; a=append(a, facets.keys[i-1]). Then after loop, facets.Keys = a.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/645)*

**Comment by gacharya255** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/645#-:-Ke7N0RI5ZzBYprgk7MG:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
