### PR TITLE
chore: Cherry picks for DGRAPH-2446

### PR DESCRIPTION
**Pull request by rahulgurnani**
Post mortem of issue: https://discuss.dgraph.io/t/dgraph-missing-mutations-in-ludicrous-mode-post-mortem/11019

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6797)

 
 

Docs Preview: [Dgraph Preview](https://dgraph-ca6a69e997-105817.surge.sh)

### CODE REVIEW

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6797#-:-MKLlDyH218B4TYJ6P7v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @martinmr, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

**Review by danielmai — APPROVED** [review]
The test doesn't compile in this branch (rahulgurnani/releasev2003):
```
# github.com/dgraph-io/dgraph/systest/ludicrous [github.com/dgraph-io/dgraph/systest/ludicrous.test]
./upsert_test.go:54:39: cannot use &"github.com/dgraph-io/dgo/v200/protos/api".Operation literal (type *"github.com/dgraph-io/dgo/v200/protos/api".Operation) as type *"github.com/dgraph-io/dgo/v2/protos/api".Operation in argument to dg.Alter
./upsert_test.go:72:21: cannot use mu (type *"github.com/dgraph-io/dgo/v200/protos/api".Mutation) as type *"github.com/dgraph-io/dgo/v2/protos/api".Mutation in argument to txn.Mutate
./upsert_test.go:100:27: cannot use req (type *"github.com/dgraph-io/dgo/v200/protos/api".Request) as type *"github.com/dgraph-io/dgo/v2/protos/api".Request in argument to dg.NewTxn().Do
./upsert_test.go:148:27: cannot use req (type *"github.com/dgraph-io/dgo/v200/protos/api".Request) as type *"github.com/dgraph-io/dgo/v2/protos/api".Request in argument to dg.NewTxn().Do
FAIL        github.com/dgraph-io/dgraph/systest/ludicrous [build failed]
```

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6797#-:-MKMSki7EKcfkl8VCy4S:b5fi5s1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @martinmr, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

**Review by danielmai — CHANGES_REQUESTED** [review]
I had fixed the compile-time issue above but the new tests still fails consistently. @rahulgurnani can you see why the tests are failing?

```
=== RUN   TestConcurrentUpdate
    upsert_test.go:124: 
        	Error Trace:	upsert_test.go:124
        	Error:      	Not equal: 
        	            	expected: 10
        	            	actual  : 0
        	Test:       	TestConcurrentUpdate
--- FAIL: TestConcurrentUpdate (4.80s)
=== RUN   TestSequentialUpdate
    upsert_test.go:149: 
        	Error Trace:	upsert_test.go:149
        	            				upsert_test.go:153
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = : Predicate name is not indexed
        	Test:       	TestSequentialUpdate
--- FAIL: TestSequentialUpdate (2.26s)
FAIL
FAIL	github.com/dgraph-io/dgraph/systest/ludicrous	7.094s
FAIL

```

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6797#-:-MKMxSK19CiHO8N3ts2z:b-6pqkl5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @martinmr, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

**Review by jarifibrahim — APPROVED** [review]

**Review by rahulgurnani — COMMENTED** [review]
Fixed the tests

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6797#-:-MLCQvYE59zfJwga-pub:b-rlkgxr)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @danielmai, @manishrjain, @martinmr, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

**Comment by rahulgurnani** [comment]
> I had fixed the compile-time issue above but the new tests still fails consistently. @rahulgurnani can you see why the tests are failing?
> 
> ```
> === RUN   TestConcurrentUpdate
>     upsert_test.go:124: 
>         	Error Trace:	upsert_test.go:124
>         	Error:      	Not equal: 
>         	            	expected: 10
>         	            	actual  : 0
>         	Test:       	TestConcurrentUpdate
> --- FAIL: TestConcurrentUpdate (4.80s)
> === RUN   TestSequentialUpdate
>     upsert_test.go:149: 
>         	Error Trace:	upsert_test.go:149
>         	            				upsert_test.go:153
>         	Error:      	Received unexpected error:
>         	            	rpc error: code = Unknown desc = : Predicate name is not indexed
>         	Test:       	TestSequentialUpdate
> --- FAIL: TestSequentialUpdate (2.26s)
> FAIL
> FAIL	github.com/dgraph-io/dgraph/systest/ludicrous	7.094s
> FAIL
> ```
> 
> > Reviewed 1 of 1 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6797#-:-MKMxSK19CiHO8N3ts2z:b-6pqkl5)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manishrjain, @martinmr, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

Fixed

**Pull request merged**
