### PR TITLE
Increase max message size the client can send and receive

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1237)

### CODE REVIEW

**Comment by srh** [comment]
LGTM
In the long run, it would be good to avoid too-large messages.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-:-KpmrQPhmSZtgMX0TfcD:b-3qzk6y)*

**Comment by srh** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-:-KpmrwYEjApArYveZP4w:bnfp4nl)*

**Comment by srh** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237)*

**Comment by srh** [comment]
LGTM again

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-:-Kpmy7c7oIrk98N5krpU:b-wev5jb)*

**Comment by srh** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-:-KpmyAj6MYYiZlALLPKE:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraphloader/main.go, line 233 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-KpmyC3geFu3AY7tr_oF:-KpmyC3geFu3AY7tr_oG:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/33fae484fa37d73edc2af9985ef29bc40c6a0970/cmd/dgraphloader/main.go#L233)):*
> ```Go
> 
> 	return grpc.Dial(host, grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(x.GrpcMaxSize),
> 		grpc.MaxCallSendMsgSize(x.GrpcMaxSize)), grpc.WithTransportCredentials(credentials.NewTLS(tlsCfg)))
> ```

100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-:-KpmySmvm-Oec7bC9VHq:bnfp4nl)*

**Comment by srh** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphloader/main.go, line 179 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-KpmydB0X2q4MgEtU5ek:-KpmydB0X2q4MgEtU5el:b-1w86e0) ([raw file](https://github.com/dgraph-io/dgraph/blob/33fae484fa37d73edc2af9985ef29bc40c6a0970/cmd/dgraphloader/main.go#L179)):*
> ```Go
> 		nq, err := rdf.Parse(buf.String())
> 		if err == rdf.ErrEmpty { // special case: comment/empty line
> 			batchSize--
> ```

LGTM retracted -- batchSize could just be incremented after these conditional blocks instead of incr/decred.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphloader/main.go, line 179 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-KpmydB0X2q4MgEtU5ek:-KpmzxPB3AI-WBvI7jkT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/33fae484fa37d73edc2af9985ef29bc40c6a0970/cmd/dgraphloader/main.go#L179)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

LGTM retracted -- batchSize could just be incremented after these conditional blocks instead of incr/decred.
</blockquote></details>

Done.

---

*[cmd/dgraphloader/main.go, line 233 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237#-KpmyC3geFu3AY7tr_oF:-KpmzxnnLuKOhz7GovWE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/33fae484fa37d73edc2af9985ef29bc40c6a0970/cmd/dgraphloader/main.go#L233)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1237)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
