### PR TITLE
Improving Deploy documentation.

### PR DESCRIPTION
**Pull request by sboorlagadda**
**Changes**
   * Added a structure & table of contents to ease navigation.
   * Updated instructions to consider standardizing ports across node type.

**Not included**
  * Sample config files in the repo (contrib/config/*) is not updated considering new port defaults.
  * Kubernetes instructions (will be in a different PR).
  * Actual code changes for new defaults.

These changes are part of #2042

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2044)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Nice changes. Thanks for the PR @sboorlagadda. I have some comments.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[wiki/content/deploy/index.md, line 6 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3VymdBqUeApBMFBm7N:-L3VymdBqUeApBMFBm7O:bszjw7q) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L6)):*
> ```Markdown
> +++
> 
> This page talks about running Dgraph in various deployment modes and in a distributed fashion and involves
> ```

modes, in a distributed

Trying to avoid two `and`

---

*[wiki/content/deploy/index.md, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3VysviGsUMUO-PBuAW:-L3VysviGsUMUO-PBuAX:bwnfhgb) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L12)):*
> ```Markdown
> =================
> 
>   * [Install Dgraph](#install-dgraph)
> ```

The docs generate a sidebar with the TOC. This looks like a duplicate of that.

---

*[wiki/content/deploy/index.md, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3VzXIspIPQGSwNV8-y:-L3VzXIspIPQGSwNV8-z:b-1kbffa) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L53)):*
> ```Markdown
> 
> ## Install Dgraph
> #### Docker
> ```

What is the reason behind making this h4 considering Install Dgraph is h2?

---

*[wiki/content/deploy/index.md, line 214 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W-9DtpVLsWnS_QgNT:-L3W-9DtpVLsWnS_QgNU:b-jp8c66) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L214)):*
> ```Markdown
> ### Types of ports
> 
> - **gRPC-internal:** Port that is used between the cluster nodes for internal communication and messaage exchange.
> ```

message

---

*[wiki/content/deploy/index.md, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W-_-sN8k0UBMWtD6I:-L3W-_-sN8k0UBMWtD6J:b-k0we14) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L234)):*
> ```Markdown
> *Eg: When user runs a Dgraph server by setting --port_offset 2, then the server node binds to 7082 (grpc-internal), 8082 (http-external) & 9092 (grpc-external)* respectively.
> 
> **Ratel UI** by default listens on port 8000. You can use the -p flag to configure to listen on any other port.
> ```

We don't have a short command yet I think, its `-port`.

---

*[wiki/content/deploy/index.md, line 243 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W-zMTBwDn6JJ7JZhC:-L3W-zMTBwDn6JJ7JZhD:b5umvx7) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L243)):*
> ```Markdown
> dgraph zero --idx=2 --memory_mb=<typically half the RAM> --port_offset -1999
> ```
> Ratel's default port is 8081, so override it using -p 8000.
> ```

`-port 8000`

---

*[wiki/content/deploy/index.md, line 299 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W05J3BllRdxkvk6VP:-L3W05J3BllRdxkvk6VQ:b-64gg95) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L299)):*
> ```Markdown
> 
> ```sh
> dgraph zero --my=IPADDR:5080 --wal zw
> ```

Don't need to mention `wal` since default is `zw` anyway.

---

*[wiki/content/deploy/index.md, line 309 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W0SUMCouSoeG79pUe:-L3W0SUMCouSoeG79pUf:bxrono) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L309)):*
> ```Markdown
> 
> ```sh
> dgraph server --idx=1 --memory_mb=<typically half the RAM> --my=IPADDR:7080 --zero=localhost:5080
> ```

`--idx`  flag is optional and we can omit it because `Zero` would assign it.

---

*[wiki/content/deploy/index.md, line 310 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W0ZgyrE9mNYgUIwl3:-L3W0ZgyrE9mNYgUIwl4:ba3usab) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L310)):*
> ```Markdown
> ```sh
> dgraph server --idx=1 --memory_mb=<typically half the RAM> --my=IPADDR:7080 --zero=localhost:5080
> dgraph server --idx=2 --memory_mb=<typically half the RAM> --my=IPADDR:7081 --zero=localhost:5080 --port_offset=1
> ```

Can use short form for offset, `-o=1`, also omit `--idx`. We can say below that `-idx` can be specified manually if the user wants to.

---

*[wiki/content/deploy/index.md, line 312 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1-hudwiRBtBgMCpy:-L3W1-hudwiRBtBgMCpz:bpumkcc) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L312)):*
> ```Markdown
> dgraph server --idx=2 --memory_mb=<typically half the RAM> --my=IPADDR:7081 --zero=localhost:5080 --port_offset=1
> ```
> Notice the use of --port_offset for the second server and note that the `--idx` flag can be omitted. Zero would then automatically assign a unique ID to each Dgraph server, which is persisted in the write ahead log (wal) directory. You can use `-p` and `-w` to change the storage location of data and WAL. For all other flags, run
> ```

I think we also need to clarify that `p` and `w` directory need to be separate for different servers. So if running on same instance then that has to made sure.

---

*[wiki/content/deploy/index.md, line 337 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1QCLiQkk46t-iQGU:-L3W1QCLiQkk46t-iQGV:bpc4qol) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L337)):*
> ```Markdown
> mkdir ~/zero # Or any other directory where data should be stored.
> 
> docker run -it -p 5080:5080 -p 6080:6080 -v ~/zero:/dgraph dgraph/dgraph:latest dgraph zero --bindall=true --my=HOSTIPADDR:5080
> ```

Don't need `--bindall`. Its true by default.

---

*[wiki/content/deploy/index.md, line 344 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1HH3i3f5QsLYoX2j:-L3W1HH3i3f5QsLYoX2k:b-cpvw5k) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L344)):*
> ```Markdown
> mkdir ~/sever1 # Or any other directory where data should be stored.
> 
> docker run -it -p 7080:7080 -p 8080:8080 -p 9080:9080 -v ~/server1:/dgraph dgraph/dgraph:latest dgraph server --memory_mb=<typically half the RAM> --zero=HOSTIPADDR:5080 --my=HOSTIPADDR:7080 --idx=<unique-id(integer)>
> ```

again `--idx` can be omitted. I believe lesser the options, easier it is for the user.

---

*[wiki/content/deploy/index.md, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1fvnBAYEqn_cOzJ7:-L3W1fvnBAYEqn_cOzJ8:b-amowe6) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L358)):*
> ```Markdown
> 
> {{% notice "note" %}}
> You can also use the `:master` tag when running docker image to get the nightly build. Though, nightly isn't as thoroughly tested as a release, and we recomemnd not using it.
> ```

Its ok to use the nightly. We don't need to advise them against it. We can just say

... thoroughly tested and could have some bugs.

---

*[wiki/content/deploy/index.md, line 431 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W262kjBh5fpH4U7wD:-L3W262kjBh5fpH4U7wE:bk57ca3) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L431)):*
> ```Markdown
>     image: dgraph/dgraph:latest
>     volumes:
>       - /data:/dgraph
> ```

No need to mount volume for Ratel

---

*[wiki/content/deploy/index.md, line 601 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2RYlyR1Fj51zJ7K3:-L3W2RYlyR1Fj51zJ7K4:b-sixkb4) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L601)):*
> ```Markdown
> services:
>   zero:
>     image: dgraph/dgraph:latest
> ```

Have to add Ratel to this.

---

*[wiki/content/deploy/index.md, line 672 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2ZbydHJyZKjAERxy:-L3W2ZbydHJyZKjAERxz:b3suprf) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L672)):*
> ```Markdown
> 
> {{% notice "note" %}}
> 1. Ratel is not part of the stack. You can run ratel on your local machine and configure to point to remote cluster.
> ```

Why is this so? we could run it on a node with a constraint.

---

*[wiki/content/deploy/index.md, line 735 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W3HcvX2kuMpIqpJKE:-L3W3HcvX2kuMpIqpJKF:b-ndcrxc) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L735)):*
> ```Markdown
>     image: dgraph/dgraph:latest
>     volumes:
>       - data-volume:/dgraph
> ```

ports here too and below?

---

*[wiki/content/get-started/index.md, line 170 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2z4106O6Ceqf77NI:-L3W2z4106O6Ceqf77NJ:b-fltdo8) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/get-started/index.md#L170)):*
> ```Markdown
> 
> # Run Dgraph Zero
> docker run -it -p 5080:5080 -p 6080:6080 -v /tmp/data:/dgraph --name diggy dgraph/dgraph dgraph zero
> ```

8080, 9080, 5080 and 8000 for Ratel?

---

*[wiki/content/get-started/index.md, line 206 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W3A4r6qOyVdUWQG7c:-L3W3A4r6qOyVdUWQG7d:b-s9chos) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/get-started/index.md#L206)):*
> ```Markdown
> dgraph zero --memory_mb=<typically half the RAM> --port_offset -2000
> ```
> Ratel's default port is 8081, so override it using -p 8000.
> ```

We will get this changed to 8000.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-:-L3W3RUv5ogoz-yIyafE:b-mqjsre)*

**Comment by sboorlagadda** [comment]
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[wiki/content/deploy/index.md, line 6 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3VymdBqUeApBMFBm7N:-L3ZO2JeMP99Bcz71SKd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L6)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

modes, in a distributed

Trying to avoid two `and`
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3VysviGsUMUO-PBuAW:-L3ZO4eg4cXLTpcucKA8:bvpeo2n) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L12)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The docs generate a sidebar with the TOC. This looks like a duplicate of that.
</blockquote></details>

Removed. Done.

---

*[wiki/content/deploy/index.md, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3VzXIspIPQGSwNV8-y:-L3ZSQvVeNYq9lhatrMz:b-vpxws2) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L53)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What is the reason behind making this h4 considering Install Dgraph is h2?
</blockquote></details>

It looked like we are showing docker is a way of installing along with automatic, manual & nightly. So made all 4 as h4 under a h2. Otherwise we dont even need to mention docker pull as docker automatically pulls if user tries to run it.

---

*[wiki/content/deploy/index.md, line 214 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W-9DtpVLsWnS_QgNT:-L3ZOD0MR4Esf6Zq18e5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L214)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

message
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W-_-sN8k0UBMWtD6I:-L3ZS6HvcPR9ktAPKXXw:bh9t0o5) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L234)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We don't have a short command yet I think, its `-port`.
</blockquote></details>

I am seeing its `-p`. Are we planning to change to -port?

```
dgraph-ratel -h
Usage of dgraph-ratel:
  -dev
    	Run ratel in dev mode (requires ./cdn/static/ aith all the necessary assets).
  -p int
    	Port on which the ratel server will run. (default 8081)
  -version
    	Prints the version of ratel.
```

---

*[wiki/content/deploy/index.md, line 243 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W-zMTBwDn6JJ7JZhC:-L3ZOMn977rLWT2Vvanu:bh9t0o5) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L243)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`-port 8000`
</blockquote></details>

I am seeing its `-p`. Are we planning to change to -port?

```
dgraph-ratel -h
Usage of dgraph-ratel:
  -dev
    	Run ratel in dev mode (requires ./cdn/static/ aith all the necessary assets).
  -p int
    	Port on which the ratel server will run. (default 8081)
  -version
    	Prints the version of ratel.
```

---

*[wiki/content/deploy/index.md, line 299 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W05J3BllRdxkvk6VP:-L3ZOavHvkGkps-DQ1WJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L299)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't need to mention `wal` since default is `zw` anyway.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 309 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W0SUMCouSoeG79pUe:-L3ZP-prtX-VLzNxyoTY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L309)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`--idx`  flag is optional and we can omit it because `Zero` would assign it.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 310 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W0ZgyrE9mNYgUIwl3:-L3ZP0VVqmxvzu36tpw7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L310)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can use short form for offset, `-o=1`, also omit `--idx`. We can say below that `-idx` can be specified manually if the user wants to.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 312 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1-hudwiRBtBgMCpy:-L3ZPZJpI98DLSgfoRJo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L312)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I think we also need to clarify that `p` and `w` directory need to be separate for different servers. So if running on same instance then that has to made sure.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 337 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1QCLiQkk46t-iQGU:-L3ZPdRchbtdVE0Qy_LA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L337)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't need `--bindall`. Its true by default.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 344 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1HH3i3f5QsLYoX2j:-L3ZSF1NnD_0P7AhvpcQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L344)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

again `--idx` can be omitted. I believe lesser the options, easier it is for the user.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 358 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W1fvnBAYEqn_cOzJ7:-L3ZQSNujZcs0BkP9-uR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L358)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Its ok to use the nightly. We don't need to advise them against it. We can just say

... thoroughly tested and could have some bugs.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 431 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W262kjBh5fpH4U7wD:-L3ZSGLdsC2xHK1LtoLa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L431)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

No need to mount volume for Ratel
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 601 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2RYlyR1Fj51zJ7K3:-L3ZR1qEllRCmMQl_Y2R:b-6i9rg1) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L601)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Have to add Ratel to this.
</blockquote></details>

I haven't added in this guide as you can always run ratel locally and point to remote cluster. This way users can use one local instance and connect to multiple Dgraph clusters. One less port (8000) to be open.

---

*[wiki/content/deploy/index.md, line 672 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2ZbydHJyZKjAERxy:-L3ZRPgVkr6I2ZdjMVpO:bo344pj) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L672)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why is this so? we could run it on a node with a constraint.
</blockquote></details>

I haven't added in this guide as you can always run ratel locally and point to remote cluster. This way users can just run one local instance and connect to multiple Dgraph clusters. One less port (8000) to be open.

---

*[wiki/content/deploy/index.md, line 735 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W3HcvX2kuMpIqpJKE:-L3ZRuRsBpOYDrWDIz09:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L735)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

ports here too and below?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044)*

**Comment by sboorlagadda** [comment]
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[wiki/content/get-started/index.md, line 170 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2z4106O6Ceqf77NI:-L3ZUJRWcqF_D-UrV4qT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/get-started/index.md#L170)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

8080, 9080, 5080 and 8000 for Ratel?
</blockquote></details>

Done.

---

*[wiki/content/get-started/index.md, line 206 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W3A4r6qOyVdUWQG7c:-L3ZT4KLuOkMna_4FbAU:b-mtpcbl) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/get-started/index.md#L206)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We will get this changed to 8000.
</blockquote></details>

This is a note if users use older Dgraph version and looks at latest documentation just to avoid confusion. But the actual usage above the notice considers that its 8000.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044)*

**Comment by sboorlagadda** [comment]
Thanks @pawanrawal for the review. I reworked most of the comments except couple, let me know what you think on my responses.

---

Review status: 3 of 5 files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-:-L3ZUxuxRlLvAUQhyffg:b3c39wa)*

**Comment by sboorlagadda** [comment]
Updated

---

Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[wiki/content/deploy/index.md, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W-_-sN8k0UBMWtD6I:-L3_WsTN5LaIiNkIYJ92:b-4yovxq) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L234)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What version are you on? I see it as `--port`
</blockquote></details>

Done. I was on 1.0.1.

---

*[wiki/content/deploy/index.md, line 601 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2RYlyR1Fj51zJ7K3:-L3_YxmFmLEG4ltpwRY-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L601)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Hmm, I think people would want to deploy Ratel as part of their cluster. They would not want to run it locally as then every user has to do it for themselves.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 672 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3W2ZbydHJyZKjAERxy:-L3_WZVwSL1MjL92WzsC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/36127e9dd60ca82c8ddb3bd3ea4aa874f12e5d39/wiki/content/deploy/index.md#L672)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Same as above. I think opening another port should not be a big issue.
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 700 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3_FfORQKe8ZdK-nNHX:-L3_WYVFecU4SRRXh0Qw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/220892a22cef05c70401cfc8197eb701b096a1df/wiki/content/deploy/index.md#L700)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

5081, 6081
</blockquote></details>

Done.

---

*[wiki/content/deploy/index.md, line 714 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3_FiM_Wym7sNhTMvRM:-L3_YzuAg2amycZ2a9Aa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/220892a22cef05c70401cfc8197eb701b096a1df/wiki/content/deploy/index.md#L714)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

5082, 6082
</blockquote></details>

Done.

---

*[wiki/content/get-started/index.md, line 170 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-L3_FnflM0KRBBLlEEyc:-L3_WIcTcwJXCho0JKRE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/220892a22cef05c70401cfc8197eb701b096a1df/wiki/content/get-started/index.md#L170)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

7080 doesn't need to exposed outside.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2044#-:-L3_eJLxI7Jr0nxuRy-P:b-bu91xm)*

**Pull request merged**
