### PR TITLE
Added support for reading from configuration file.

### PR DESCRIPTION
**Pull request by ankurayadav**
Now configuration parameters can be saved in a yaml file and it can be specified as a command line parameter while launching dgraph using.

./dgraph -conf="<file_path>/<file_name>.yaml"

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/385)

### CODE REVIEW

**Comment by manishrjain** [comment]
Thanks for taking this on. Here's my review.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[x/init.go, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEhi5FGhilvO33aS8S:-KZEhi5FGhilvO33aS8T:be0towb) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L50)):*
> ```Go
> 	}
> 
> 	var confFile = flag.Lookup("conf").Value.(flag.Getter).Get().(string)
> ```

Better to define the flag like elsewhere in the code. So, `--help` would show it properly.

---

*[x/init.go, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEhqb9qI3wTGKniTq7:-KZEhqb9qI3wTGKniTq8:b-w0kzf) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L53)):*
> ```Go
> 
> 	if confFile == "" {
> 		log.Println("No config file specified! Default configuration will be used.")
> ```

No need for this. Only mention if you're going to use the config. Otherwise, don't say anything.

---

*[x/init.go, line 70 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEiDz9dE9EWgMPflzB:-KZEiDz9dE9EWgMPflzC:b-ngr8ap) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L70)):*
> ```Go
> // loadConfigFromYAML reads configurations from specified YAML file.
> func loadConfigFromYAML(confFile string) {
> 	file, err := os.Open(confFile)
> ```

You can use this instead:
https://golang.org/pkg/io/ioutil/#ReadFile

---

*[x/init.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEiKOvTsU4feWEPIWP:-KZEiKOvTsU4feWEPIWQ:bep1ao2) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L97)):*
> ```Go
> 	m := make(map[string]string)
> 
> 	err = yaml.Unmarshal([]byte(bs), &m)
> ```

If we're unable to parse a provided conf file, we should crash.

if err := yaml.Unmarshal(..); err != nil {
  x.Fatalf("Error while parsing config file: %v", err)
}

---

*[x/init.go, line 104 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEibzbGDcyiiRrV0Mz:-KZEibzbGDcyiiRrV0N-:b-rw1b4o) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L104)):*
> ```Go
> 
> 	for k, v := range m {
> 		flag.Set(k, v)
> ```

Can you add an example config file, which would set the default values for the flags?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-:-KZEilWxMt1nEJDZV2df:b-q4jftm)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[x/init.go, line 70 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZOLk4W9BKVQnVZvRIa:-KZOLk4XwdsnDS6iwC_l:b-gvmm99) ([raw file](https://github.com/dgraph-io/dgraph/blob/23b05f0f284ff5feeced1f78032feb9ecdc90131/x/init.go#L70)):*
> ```Go
> func loadConfigFromYAML(confFile string) {
> 	bs, err := ioutil.ReadFile(confFile)
> 	if err != nil {
> ```

Checkf(err, "Can't open ...: %v", confFile)

---

*[x/init.go, line 78 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZOM088mKOFGo5RrfjL:-KZOM088mKOFGo5RrfjM:bqx5zuw) ([raw file](https://github.com/dgraph-io/dgraph/blob/23b05f0f284ff5feeced1f78032feb9ecdc90131/x/init.go#L78)):*
> ```Go
> 	m := make(map[string]string)
> 
> 	err = yaml.Unmarshal([]byte(bs), &m)
> ```

Checkf(yaml.Unmarshal(...), "Error while parsing: ..")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/385)*

**Comment by ankurayadav** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[x/init.go, line 50 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEhi5FGhilvO33aS8S:-KZPHPdcRju9GqEy1zpF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Better to define the flag like elsewhere in the code. So, `--help` would show it properly.
</blockquote></details>

Done.

---

*[x/init.go, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEhqb9qI3wTGKniTq7:-KZN7tekVvh0xzCnrqhb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L53)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this. Only mention if you're going to use the config. Otherwise, don't say anything.
</blockquote></details>

Done.

---

*[x/init.go, line 70 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEiDz9dE9EWgMPflzB:-KZNV-B-PR_riUsLrb8o:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can use this instead:
https://golang.org/pkg/io/ioutil/#ReadFile
</blockquote></details>

Done.

---

*[x/init.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEiKOvTsU4feWEPIWP:-KZNYRAQp-j_mojKvLF2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L97)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If we're unable to parse a provided conf file, we should crash.

if err := yaml.Unmarshal(..); err != nil {
  x.Fatalf("Error while parsing config file: %v", err)
}
</blockquote></details>

Done.

---

*[x/init.go, line 104 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZEibzbGDcyiiRrV0Mz:-KZPHU9HpAm6BHVCAcz6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/283bc9474996108606ef644564abf157f059e9b8/x/init.go#L104)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can you add an example config file, which would set the default values for the flags?
</blockquote></details>

Done.

---

*[x/init.go, line 70 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZOLk4W9BKVQnVZvRIa:-KZPHR-SDF1P7XzqGPwD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/23b05f0f284ff5feeced1f78032feb9ecdc90131/x/init.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Checkf(err, "Can't open ...: %v", confFile)
</blockquote></details>

Done.

---

*[x/init.go, line 78 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZOM088mKOFGo5RrfjL:-KZPHTYKfoZpQ2JqPpQ8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/23b05f0f284ff5feeced1f78032feb9ecdc90131/x/init.go#L78)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Checkf(yaml.Unmarshal(...), "Error while parsing: ..")
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/385)*

**Comment by manishrjain** [comment]
Thanks for the fixes. Few more comments -- we're getting close.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/dgraph/config.yaml, line 6 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMh9MiGNe4rTTw1dv:-KZPMh9MiGNe4rTTw1dw:bf4drka) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L6)):*
> ```YAML
> # Number of cores to be used by the process.
> cores: 4
>       
> ```

extra spaces here and in some lines below.

---

*[cmd/dgraph/config.yaml, line 18 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMfUVW9oMeXq8iSL8:-KZPMfUVW9oMeXq8iSL9:b-66t4la) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L18)):*
> ```YAML
> # Directory to store posting lists.
> p: pp
>       
> ```

remove spaces here.

---

*[cmd/dgraph/config.yaml, line 26 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMrAXHB8LBkRenHOa:-KZPMrAXHB8LBkRenHOb:bi7dnm8) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L26)):*
> ```YAML
> 
> # The ratio of queries to trace.
> trace float: 0.5
> ```

trace is the flag name. Can you pass in this config file to the code and see that it picks up the values correctly?

---

*[cmd/dgraph/config.yaml, line 32 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMRe3s05NZI5gHsYh:-KZPMRe3s05NZI5gHsYi:bs5zyvi) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L32)):*
> ```YAML
> 
> # Port used by worker for internal communication.
> workerport: 12345
> ```

Need a newline here.

---

*[x/init.go, line 32 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPM4vlxc9-AFOmaJWm:-KZPM4vlxc9-AFOmaJWn:bidzqvs) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/x/init.go#L32)):*
> ```Go
> 
> var (
> 	configFile = flag.String("configFile", "", "YAML configuration file containing dgraph settings.")
> ```

line > 100 chars. Please fix.

---

*[x/init.go, line 69 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMCPi4PF-KAGLOFtO:-KZPMCPi4PF-KAGLOFtP:b-isj8hm) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/x/init.go#L69)):*
> ```Go
> func loadConfigFromYAML() {
> 	bs, err := ioutil.ReadFile(*configFile)
> 	Checkf(err, "Can't open ...: %v", configFile)
> ```

With the dots, I meant the message that you had written down. I just didn't type it out in full.

---

*[x/init.go, line 73 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMKnAJvLObgj2rYVG:-KZPMKnAJvLObgj2rYVH:b-6ffgtc) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/x/init.go#L73)):*
> ```Go
> 	m := make(map[string]string)
> 
> 	Checkf(yaml.Unmarshal(bs, &m), "Error while parsing: ..")
> ```

Same here. dots were to represent the line that you had before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-:-KZPMzpQtEmK2UvMsb8f:b-k808ps)*

**Comment by ankurayadav** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/dgraph/config.yaml, line 6 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMh9MiGNe4rTTw1dv:-KZRIAk-MXC8lR-nazpK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L6)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

extra spaces here and in some lines below.
</blockquote></details>

Done.

---

*[cmd/dgraph/config.yaml, line 18 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMfUVW9oMeXq8iSL8:-KZRIC6jpPx0O_yilK1V:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L18)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove spaces here.
</blockquote></details>

Done.

---

*[cmd/dgraph/config.yaml, line 26 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMrAXHB8LBkRenHOa:-KZRIDYk9IsUfpOEJlK-:b8gnxeh) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L26)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

trace is the flag name. Can you pass in this config file to the code and see that it picks up the values correctly?
</blockquote></details>

Yes, corrected that. I have tried passing config file as default flag value and it works fine!

---

*[cmd/dgraph/config.yaml, line 32 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMRe3s05NZI5gHsYh:-KZRIQ_Z_UR0V2iLz5AD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/cmd/dgraph/config.yaml#L32)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Need a newline here.
</blockquote></details>

Done.

---

*[x/init.go, line 32 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPM4vlxc9-AFOmaJWm:-KZRIVQtY7JP7k1RNeqH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/x/init.go#L32)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

line > 100 chars. Please fix.
</blockquote></details>

Done.

---

*[x/init.go, line 69 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMCPi4PF-KAGLOFtO:-KZRIU8OXCyRoH-B-SQN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/x/init.go#L69)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

With the dots, I meant the message that you had written down. I just didn't type it out in full.
</blockquote></details>

Done.

---

*[x/init.go, line 73 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-KZPMKnAJvLObgj2rYVG:-KZRIUV_t7k3Yy9XfSR4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/be64816e00704544df48bd1918cea3632c595646/x/init.go#L73)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Same here. dots were to represent the line that you had before.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/385)*

**Comment by manishrjain** [comment]
:lgtm: Thanks for doing this!

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/385#-:-KZTn_yuvvwOWJTMwGKJ:b-pt8m11)*

**Pull request merged**
