### PR TITLE
Iterate/parallel

### PR DESCRIPTION
**Pull request by pawanrawal**
So that resources are released properly if query timeouts.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1090)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/task.go, line 947 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1090#-KnlE2Rt1ZHOwIxH3R1G:-KnlE2Rt1ZHOwIxH3R1H:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/3839a1a1b866889bbc692650b3f1b26df6e7d0d5/worker/task.go#L947)):*
> ```Go
> }
> 
> func iterateParallel(ctx context.Context, q *protos.Query, f func([]byte, []byte, *sync.Mutex)) error {
> ```

100 chars.

---

*[worker/task.go, line 1008 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1090#-KnlE824iHNaqJkJtBhC:-KnlE824iHNaqJkJtBhD:b1kv3qv) ([raw file](https://github.com/dgraph-io/dgraph/blob/3839a1a1b866889bbc692650b3f1b26df6e7d0d5/worker/task.go#L1008)):*
> ```Go
> 					tr.LazyPrintf("Error while running iterateParallel: %+v", err)
> 				}
> 				return err
> ```

Don't return here. Let all the goroutines finish first, otherwise we get trace panics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1090)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/task.go, line 947 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1090#-KnlE2Rt1ZHOwIxH3R1G:-KnlOUetgpj9jeIrpCab:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3839a1a1b866889bbc692650b3f1b26df6e7d0d5/worker/task.go#L947)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[worker/task.go, line 1008 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1090#-KnlE824iHNaqJkJtBhC:-KnlOWQyGol31rxNzt-F:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3839a1a1b866889bbc692650b3f1b26df6e7d0d5/worker/task.go#L1008)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't return here. Let all the goroutines finish first, otherwise we get trace panics.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1090)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1090#-:-KnmJpTmUnJH7r7KaKi-:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to `release/v0.7.7` and `master`.

**Pull request closed without merging**
