### PR TITLE
Delete cache from commit logs. Fix tests which broke because of it.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/199)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[commit/log.go, line 282 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR2qkww7O5Xs3VAjNoC:-KR2qkww7O5Xs3VAjNoD:bc9mow8) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L282)):*
> ```Go
> 	defer f.Close()
> 
> 	discard := make([]byte, 4096)
> ```

Nice naming.

---

*[commit/log.go, line 312 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR2qstwRFPU1NUValI8:-KR2qstwRFPU1NUValI9:b-gi15bs) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L312)):*
> cap(discard)

---

*[commit/log.go, line 473 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3AV-5djSB6gPBWIYl:-KR3AV-6DZlIQsE5dU1F:b-gi15bs) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L473)):*
> cap(discard)

---

*[commit/log.go, line 482 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3BEnLwBJ3BcPusiMp:-KR3BEnLwBJ3BcPusiMq:b-ife61a) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L482)):*
> ```Go
> }
> 
> func (l *Logger) StreamEntries(afterTs int64, hash uint32,
> ```

You don't need hash anymore. Instead what we need to do is to have one commit log instance per predicate.

---

*[commit/log.go, line 483 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3CLCUx7xzZvBaFhiX:-KR3CLCUx7xzZvBaFhiY:b-ixtyw9) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L483)):*
> ```Go
> 
> func (l *Logger) StreamEntries(afterTs int64, hash uint32,
> 	ch chan []byte, done chan error) {
> ```

I think LogIterator is a better approach. It can be put together with a channel or just used as it is.

---

*[posting/list.go, line 233 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3FB25JVEa9LmpTmis:-KR3FB25JVEa9LmpTmit:b7sz7sk) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/posting/list.go#L233)):*
> ```Go
> 	}
> 
> 	// TODO(pawan) - Decouple commit logs and posting lists. RAFT would supersede
> ```

Maybe just make this part of this change. Remove all deps on commit logger.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/199)*

**Comment by pawanrawal** [comment]
Review status: 3 of 18 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[commit/log.go, line 17 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR2_JOcYvgts96XbJp2-r1-17:-KR3Q07TpPA46hti0Q2w:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/3b0013b0c587ab89132cf6d70e3e94e55b2c0f47/commit/log.go#L17)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> package comment should be of the form "Package commit ..."
</details>
Done

---

*[commit/log.go, line 282 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR2qkww7O5Xs3VAjNoC:-KR3KxzdJtuKEAufCZO2:be97few) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L282)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Nice naming.
</details>
You had it before, I don't want to take undue credit :stuck_out_tongue: .

---

*[commit/log.go, line 312 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR2qstwRFPU1NUValI8:-KR4MjQ1HOgfHb_v3lj9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L312)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> > cap(discard)
</details>
Done.

---

*[commit/log.go, line 473 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3AV-5djSB6gPBWIYl:-KR4MjzxXbMR4HEs0W3G:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L473)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> > cap(discard)
</details>
Done.

---

*[commit/log.go, line 482 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3BEnLwBJ3BcPusiMp:-KR3WfU2mc1Vo_Fk8nQs:b-f0ydai) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L482)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You don't need hash anymore. Instead what we need to do is to have one commit log instance per predicate.
</details>
Not sure if we decided on one log per predicate or a common log. Should I remove it?

---

*[commit/log.go, line 483 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3CLCUx7xzZvBaFhiX:-KR4Ml7_L4sKNja5ipO1:bq1amwx) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L483)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I think LogIterator is a better approach. It can be put together with a channel or just used as it is.
</details>
Right and cleaner too, brought it back.

---

*[posting/list.go, line 233 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3FB25JVEa9LmpTmis:-KR3WeHCVCu2F_dqh6f5:bs7wumx) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/posting/list.go#L233)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Maybe just make this part of this change. Remove all deps on commit logger.
</details>
Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/199)*

**Comment by manishrjain** [comment]
:lgtm_strong: One small comment. Otherwise, looks good!

---

Reviewed 13 of 14 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[commit/log.go, line 282 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR2qkww7O5Xs3VAjNoC:-KR7Ry9EW59C3Y05j0us:bhhzjxc) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L282)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> You had it before, I don't want to take undue credit :stuck_out_tongue: .
</details>
OK oh.. lol!

---

*[commit/log.go, line 482 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR3BEnLwBJ3BcPusiMp:-KR7S7Zpv1FzDwKN1feg:b83jxyu) ([raw file](https://github.com/dgraph-io/dgraph/blob/b97996c57a4e9f6dd6f2b7be241807c872e860b6/commit/log.go#L482)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Not sure if we decided on one log per predicate or a common log. Should I remove it?
</details>
LGTM. Sorry I think my comment was before we decided to have a common log. Ignore it.

---

*[posting/list.go, line 71 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR7SY80vu53eB-pD-uj:-KR7SY80vu53eB-pD-uk:ba3dfna) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac6c4c05c017bbf063143b62248e5e0cf893771e/posting/list.go#L71)):*
> ```Go
> 	mlayer        map[int]types.Posting // stores only replace instructions.
> 	mdelta        int                   // len(plist) + mdelta = final length.
> 	maxMutationTs int64                 // Track maximum mutation ts.
> ```

Remove?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-:-KR7SiKrZ9xEay0LkoIv:b5qkbh7)*

**Comment by pawanrawal** [comment]
Review status: 16 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/list.go, line 71 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR7SY80vu53eB-pD-uj:-KR7q7_R0tmED6K9WMyL:b-o41o7a) ([raw file](https://github.com/dgraph-io/dgraph/blob/ac6c4c05c017bbf063143b62248e5e0cf893771e/posting/list.go#L71)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove?
</details>
Done. I guess we still need the CommitTs in posting list though we won't use it as of now.

---

*[posting/lists.go, line 262 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/199#-KR2_JOcYvgts96XbJp6-r3-262:-KR7q6wZbMpvWeX_eWLb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e3de82d221c52d5eddcb2920dded4830ca6b5340/posting/lists.go#L262)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function Init should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/199)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
