### PR TITLE
docs: New homepage design

### PR DESCRIPTION
**Pull request by bucanero**
Backport the new Docs home design

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6827)

 
 

Docs Preview: [Dgraph Preview](https://dgraph-b85928b208-105825.surge.sh)

### CODE REVIEW

**Review by danielmai — COMMENTED** [review]
Can we put GraphQL, DQL, and Slash GraphQL in the top row? Given the current cards, it should look something like

<table>
<tr><td>Slash GraphQL</td><td>GraphQL</td><td>DQL</td>
<tr><td>Deploy</td><td>Enterprise Features</td><td>FAQ</td>
<tr><td>Badger</td><td></td><td></td>
</table>

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6827#-:-ML97tuZ3rABAd7a94b7:b4dfvg5)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @danielmai and @MichaelJCompton)

**Comment by bucanero** [comment]
> Can we put GraphQL, DQL, and Slash GraphQL in the top row? Given the current cards, it should look something like
> Slash GraphQL	GraphQL	DQL
> Deploy	Enterprise Features	FAQ
> Badger		
> 
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6827#-:-ML97tuZ3rABAd7a94b7:b4dfvg5)_ status: 0 of 6 files reviewed, all discussions resolved (waiting on @danielmai and @MichaelJCompton)

I've re-ordered the cards. 👍

**Review by aaroncarey — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6827)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @aaroncarey, @danielmai, and @MichaelJCompton)

**Review by aaroncarey — APPROVED** [review]

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6827#-:-MLDy7tRAjNIiUEh0EY-:bnfp4nl)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @aaroncarey, @danielmai, and @MichaelJCompton)

**Pull request merged**
