### PR TITLE
Use blanknode for UIDs in backup

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1098)

### CODE REVIEW

**Comment by manishrjain** [comment]
Rename everything to export, because this is equivalent of export. We'll need to have a separate backup API.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1098#-:-Ko6L5Hr1oDB7C_zc56z:bey8deu)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1098#-:-Ko9zGWwojjl6h2w6EFf:bnfp4nl)*

**Comment by ashwin95r** [comment]
Changed to export.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1098#-:-KoAGw_DK1EyAu9tKPjb:b-wg0tsq)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/worker.go, line 42 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1098#-KoGe2Q38f5DTp3GIyO4:-KoGe2Q38f5DTp3GIyO5:b-r1pzwn) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e4adccc134e2a6789d25f16ab7abeedda52ffd0/worker/worker.go#L42)):*
> ```Go
> 	workerPort = flag.Int("workerport", 12345,
> 		"Port used by worker for internal communication.")
> 	exportPath = flag.String("backup", "backup",
> ```

export

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1098#-:-KoGe6nlUc2-yH_3IUkH:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 4 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/worker.go, line 42 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1098#-KoGe2Q38f5DTp3GIyO4:-KoGlOcd_FVK3Hp7lgCc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e4adccc134e2a6789d25f16ab7abeedda52ffd0/worker/worker.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

export
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1098)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
