### PR TITLE
Returning error about query to user.

### LINKED ISSUE #644: Server crashes when requesting same predicate twice
Running 
```
{
  me(id: m.06pj8) {
    name.en
    director.film (first: 10, orderdesc: name.en) {
      name.en
      name.en
      initial_release_date
      genre {
        name.en
      }
    }
  }
}
``` 

crashes the server with error

```
2017/02/28 17:21:04 error.go:75: Setting value twice for same attribute
github.com/dgraph-io/dgraph/x.Errorf
	/home/pawan/work/src/github.com/dgraph-io/dgraph/x/error.go:103
github.com/dgraph-io/dgraph/x.AssertTruef
	/home/pawan/work/src/github.com/dgraph-io/dgraph/x/error.go:75
github.com/dgraph-io/dgraph/query.(*fastJsonNode).AddValue
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:241
github.com/dgraph-io/dgraph/query.(*SubGraph).preTraverse
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/query.go:357
github.com/dgraph-io/dgraph/query.(*SubGraph).preTraverse
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/query.go:287
github.com/dgraph-io/dgraph/query.processNodeUids
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:425
github.com/dgraph-io/dgraph/query.(*SubGraph).ToFastJSON
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:458
github.com/dgraph-io/dgraph/query.ToJson
	/home/pawan/work/src/github.com/dgraph-io/dgraph/query/outputnode.go:69
main.queryHandler
	/home/pawan/work/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:465
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:1942
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2238
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2568
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1825
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197
```

I think we should just return the predicate once and not give an error the server. Thoughts @ashishnegi?

### PR DESCRIPTION
**Pull request by ashishnegi**
fixes #644

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/648)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 443 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-Ke7Sy_juaQYyNw75JuQ:-Ke7Sy_juaQYyNw75JuR:b4p4qam) ([raw file](https://github.com/dgraph-io/dgraph/blob/04c8530420ad93f521078f474e0ee7e4d59979c6/query/query.go#L443)):*
> ```Go
> 	// node, because of the way we're dealing with the root node.
> 	// So, we work on the children, and then recurse for grand children.
> 	attrsSeen := make(map[string]bool, len(gq.Children))
> ```

map[string]struct{} (as empty structs take up no space). 
Also, I think we don't need the len() parameter for a map.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-:-Ke7TaRA1GtMXUo9b0z2:bnfp4nl)*

**Comment by ashwin95r** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-:-Ke7UeWVKpkobMxzhIYE:bnfp4nl)*

**Comment by ashishnegi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 443 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-Ke7Sy_juaQYyNw75JuQ:-Ke8G1Y7kpSmnNZk1klS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/04c8530420ad93f521078f474e0ee7e4d59979c6/query/query.go#L443)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

map[string]struct{} (as empty structs take up no space). 
Also, I think we don't need the len() parameter for a map.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648)*

**Comment by ashishnegi** [comment]
I have followed the pattern of `bufio` where error is stored inside the `outputnode`..
this makes client work simpler as they can just check for error at end.
otherwise a lot of `if err := funccall(); err != nil { return err }` become part of codebase..
in case of error, funciton calls become noOp in outputnode.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-:-Ke8Gf90KA9DFOwGRhV3:bmexnrl)*

**Comment by pawanrawal** [comment]
Nice error handling. Thanks

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 150 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBOsgvyyUq1U9C7Cdx:-KeBOsgvyyUq1U9C7Cdy:bclnbqj) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L150)):*
> ```Go
> 	}
> 	if child.Error() != nil {
> 		p.err = child.Error()
> ```

how about a return here and remove the else?

---

*[query/outputnode.go, line 276 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBPARq_8r114sKN8GC:-KeBPARq_8r114sKN8GD:bv70xl6) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L276)):*
> ```Go
> 		return
> 	}
> 	if bs, err := valToBytes(v); err == nil {
> ```

again, how about 

err != nil {
  fj.err = err
  return
}
// Rest of the logic here. I think it looks good when errors are handled first and then the actual logic isn't indented if possile.

---

*[query/outputnode.go, line 300 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBPZ9LUPPueKrcj0vi:-KeBPZ9LUPPueKrcj0vj:b-m5u0aw) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L300)):*
> ```Go
> 		if nodeAttr.isScalar {
> 			fj.err = x.Errorf("Can not merge scalar and node values for attr : %s.",
> 				attr)
> ```

return here and remove else?

---

*[query/outputnode.go, line 350 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBPpnJcKLYTL4a9Ztt:-KeBPpnKTcPO4dVF-65d:bu7z29i) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L350)):*
> ```Go
> 		if !uidBs.isScalar {
> 			fj.err = x.Errorf(
> 				"Found node value for _uid_ %d. Expected scalar value.", uid)
> ```

same could have a return here. Just a preference, if you think it looks good then do it else feel free to ignore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-:-KeBQ3vqMqEvtFoi6AIB:bflos8m)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 102 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBSmNXTDzFbluwDTAq:-KeBSmNXTDzFbluwDTAr:bkg46mm) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L102)):*
> ```Go
> 		return
> 	}
> 	if v.Error() != nil {
> ```

Instead of having a funcition, I think we can just do `v.err`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[query/outputnode.go, line 222 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBTBl7OHLr-oyf0S9Z:-KeBTBl84jbxlYt7d_vR:bpmkhtg) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L222)):*
> ```Go
> 		}
> 
> 		if rerr := sg.preTraverse(uid, n1, n1); rerr != nil {
> ```

passing same argument twice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648)*

**Comment by ashishnegi** [comment]
Review status: 1 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[query/outputnode.go, line 102 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBSmNXTDzFbluwDTAq:-KeCCfJpRlyHM0boHt77:bwbsljb) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L102)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Instead of having a funcition, I think we can just do `v.err`
</blockquote></details>

not required now.

---

*[query/outputnode.go, line 150 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBOsgvyyUq1U9C7Cdx:-KeCChoAlbGPFxHeLBUo:bwbsljb) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L150)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

how about a return here and remove the else?
</blockquote></details>

not required now.

---

*[query/outputnode.go, line 222 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBTBl7OHLr-oyf0S9Z:-KeC24FX2W4doFKxEPoP:b-pakskf) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L222)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

passing same argument twice?
</blockquote></details>

yeah.. for this call

---

*[query/outputnode.go, line 276 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBPARq_8r114sKN8GC:-KeCClmHMfK4re8h1gDW:bwbsljb) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L276)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

again, how about 

err != nil {
  fj.err = err
  return
}
// Rest of the logic here. I think it looks good when errors are handled first and then the actual logic isn't indented if possile.
</blockquote></details>

not required now.

---

*[query/outputnode.go, line 300 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBPZ9LUPPueKrcj0vi:-KeCCnZYUQn5Wz_9sa8_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L300)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

return here and remove else?
</blockquote></details>

Done.

---

*[query/outputnode.go, line 350 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-KeBPpnJcKLYTL4a9Ztt:-KeCCr-wG_rB0OjHamLj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/bc16e9875a6c66ac286c8189b9847c45d5965653/query/outputnode.go#L350)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

same could have a return here. Just a preference, if you think it looks good then do it else feel free to ignore.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648)*

**Comment by manishrjain** [comment]
Don't remove any assert which asserts a condition, totally within our control. In fact, make it a habit to add more asserts in the code. So, revert this change.

---

Reviewed 1 of 3 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/648#-:-KeCgVyjz4uG1D6vkT6l:b7ra1gy)*

**Pull request closed without merging**
