### PR TITLE
Get memory usage from /proc/

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/178)

### CODE REVIEW

**Comment by manishrjain** [comment]
I love simpler solutions to problems. This is a great example of that!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 181 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2kRCvv9kyqJjhtYa-:-KQ2kRCwnYwKIP6eU4jO:b-zhj458) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L181)):*
> ```Go
> func getMemUsage() int {
> 	pid := os.Getpid()
> 	contents, err := ioutil.ReadFile("/proc/" + strconv.Itoa(pid) + "/stat")
> ```

How about using `/proc/self/stat`? Also, did you check this for Mac?

---

*[posting/lists.go, line 185 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2krhHvMGnOZJwYSaB:-KQ2krhHvMGnOZJwYSaC:b-mh2g00) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L185)):*
> ```Go
> 		log.Println("Can't read the proc file", err)
> 	}
> 	cont := strings.Split(string(contents), " ")
> ```

You must always check the size of this slice before accessing its 24th element.

---

*[posting/lists.go, line 189 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2kaa5wBJjqYUbx85I:-KQ2kaa5wBJjqYUbx85J:b52sulb) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L189)):*
> ```Go
> 	// 24th entry of the file is the RSS which denotes the number of pages
> 	// used by the process. Each page is 4KB in size
> 	a, _ := strconv.Atoi(cont[23])
> ```

Repeat after me: I will always check for errors. I will never ignore errors. Every time I don't check for errors, a Gopher cries.

---

*[posting/lists.go, line 190 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2lSHFzpHV4bHRO5c0:-KQ2lSHFzpHV4bHRO5c1:b-otjsjv) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L190)):*
> ```Go
> 	// used by the process. Each page is 4KB in size
> 	a, _ := strconv.Atoi(cont[23])
> 	return a * 4 / (1 << 10)
> ```

Use https://golang.org/pkg/os/#Getpagesize

---

*[posting/lists.go, line 194 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2l9e5h0oAit25LbEv:-KQ2l9e5h0oAit25LbEw:bf21fpf) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L194)):*
> ```Go
> 
> func CheckMemoryUsage(ps1, ps2 *store.Store) {
> 	MAX_MEMORY = *maxmemory
> ```

You don't need this variable anymore.

---

*[posting/lists.go, line 198 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2lDSIQSB67gBhqPPk:-KQ2lDSIQSB67gBhqPPl:b-3fnx69) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L198)):*
> ```Go
> 	for _ = range time.Tick(5 * time.Second) {
> 		totMemory := getMemUsage()
> 		log.Println("Memory usage (MB): ", totMemory)
> ```

Remove this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-:-KQ2lmFmFOlVtNiRSI_T:bkqfrb4)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[posting/lists.go, line 181 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2kRCvv9kyqJjhtYa-:-KQ4TScjM_d3RRhatqtD:b-kzhvbu) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L181)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> How about using `/proc/self/stat`? Also, did you check this for Mac?
</details>
Switched to `/proc/self/stat`. Great idea! Mac doesn't have a proc fs so this wouldn't work on it. Need to figure some other way for Mac. As of now jsut retaining the older method for non-linux OS.

---

*[posting/lists.go, line 185 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2krhHvMGnOZJwYSaB:-KQ3zgBrndVRpGzX5NTU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L185)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You must always check the size of this slice before accessing its 24th element.
</details>
Done.

---

*[posting/lists.go, line 189 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2kaa5wBJjqYUbx85I:-KQ3zprKquXRrkoPJUIG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L189)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Repeat after me: I will always check for errors. I will never ignore errors. Every time I don't check for errors, a Gopher cries.
</details>
Done.

---

*[posting/lists.go, line 190 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2lSHFzpHV4bHRO5c0:-KQ3zsbJufspaS0-weEZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L190)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Use https://golang.org/pkg/os/#Getpagesize
</details>
Done.

---

*[posting/lists.go, line 194 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2l9e5h0oAit25LbEv:-KQ3zRT_fZnzRbS_-ASE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L194)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You don't need this variable anymore.
</details>
Done.

---

*[posting/lists.go, line 198 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ2lDSIQSB67gBhqPPk:-KQ4TRRigg3kM-0z2W4T:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dbac183ffa94ba4dec99e8a489c208495787f476/posting/lists.go#L198)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove this line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/178)*

**Comment by manishrjain** [comment]
:lgtm_strong: If you see Golint comments, do try to address them wherever possible. So, I've left a comment on one of these comments. Address that before you submit. Also, did you test the change?

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 209 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ0lMdRtM1dCpm9E9V2-r3-209:-KQ8iXJbgkiZvM2LevB8:b-9sm9g6) ([raw file](https://github.com/dgraph-io/dgraph/blob/97ea3e0fcdc22003e2c60e1de4adb091007a08cd/posting/lists.go#L209)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function CheckMemoryUsage should have comment or be unexported
</details>
Does this function need to be exported? If so, comment. Otherwise, make it private.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-:-KQ8icKWul8XO3F9LHzA:b-7jip82)*

**Comment by manishrjain** [comment]
Ping?

**Comment by ashwin95r** [comment]
Yeah, I tested it out in linux and the memory usage matches up with htop. For other OS, we retain the old method.

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/lists.go, line 209 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-KQ0lMdRtM1dCpm9E9V2-r3-209:-KQJLHTrQVfBz7R_iPeo:bu1fdab) ([raw file](https://github.com/dgraph-io/dgraph/blob/97ea3e0fcdc22003e2c60e1de4adb091007a08cd/posting/lists.go#L209)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Does this function need to be exported? If so, comment. Otherwise, make it private.
</details>
Since we don't have to pass the stores now, it could be unexported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-:-KQJLfXUJh2fGLHkgVjF:b-4a3lfi)*

**Comment by manishrjain** [comment]
:lgtm: Love this change! Simplifies stuff and makes it more robust at the same time.

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/178#-:-KQJ_WewVhtBcHJa0xpX:b-3n2igv)*

**Comment by ashwin95r** [comment]
Merged to master with commit ab0a2a8cd498e999a1c39d484a6725750b194593.

**Pull request closed without merging**
