### PR TITLE
[BREAKING] feat: bring dgraph-lambda to dgraph, alpha launches lambda server

### PR DESCRIPTION
**Pull request by NamanJain8**
This PR brings in [dgraph-lambda](https://github.com/dgraph-io/dgraph-lambda) to dgraph repo.
- Adds a new super flag `--lambda`. It has 3 subflags `url` (earlier `--graphql lambda-url`), `cnt` and `port`. `--lambda url` when set, overrides other subflags. 
- Alpha launches lambda servers based on the above flags.
- Updates docker file and build script for necessary changes for nodejs.
- Load balance the lambda requests using round-robin policy.

Note: Users are free to set up their own lambda server and use `--lambda url` flag. That would need changes in the lambda response.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7973)

### CODE REVIEW

**Review by manishrjain — CHANGES_REQUESTED** [review]
Nice work. lambda should be its own flag, so DQL queries can call into lambdas later. And by default, we can set it to 1, so at least one lambda server is always running. I don't think we need `lambda-url`. We'd be forking lambda servers from within Dgraph.

> Reviewed 25 of 36 files at r3, 2 of 3 files at r4, 10 of 16 files at r5, 19 of 19 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-:-MhOCPmbDxT0QhsYKXp6:b-bdr7zj)* status: all files reviewed, 5 unresolved discussions (waiting on @NamanJain8)

___
*[dgraph/cmd/alpha/run.go, line 236 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOAEfl6kiw80lTEqJL:-MhOAEfl6kiw80lTEqJM:b-tqqwg5) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/dgraph/cmd/alpha/run.go#L236)):*
> ```Go
> 				" Use --lambda-cnt to launch official lambda server."+
> 				" This flag if set, overrides the other lambda flags.").
> 		Flag("lambda-cnt",
> ```

lambda should have its own flag. We'd want to run lambda functions via DQL too.
___
*[dgraph/cmd/alpha/run.go, line 747 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOAS803HMx8Fwi7JaH:-MhOAS81AtcuwXJg3Et9:b-ivqu2i) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/dgraph/cmd/alpha/run.go#L747)):*
> ```Go
> 		PollInterval:  graphql.GetDuration("poll-interval"),
> 		LambdaUrl:     graphql.GetString("lambda-url"),
> 		LambdaCnt:     graphql.GetUint32("lambda-cnt"),
> ```

move them to their own flags.x
___
*[graphql/e2e/directives/docker-compose.yml, line 4 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOAf94E9f57OQRclcF:-MhOAf94E9f57OQRclcG:bmer8or) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/graphql/e2e/directives/docker-compose.yml#L4)):*
> ```YAML
> services:
>   zero1:
>     image: namanj1811/dgraph:lambda
> ```

Would this need to be changed?
___
*[lambda/slash-graphql-lambda-types/package.json, line 15 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOBIoyA1A1UFaRHGxh:-MhOBIoyA1A1UFaRHGxi:bgs4isd) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/lambda/slash-graphql-lambda-types/package.json#L15)):*
> ```JSON
>   },
>   "author": "Tejas Dinkar <tejas@gja.in>",
>   "license": "Apache-2.0"
> ```

can you remove the "slash-graphql" name from everywhere?

Also, license should be Dgraph license. Author should be removed. Here and elsewhere.
___
*[x/x.go, line 1480 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOCBwBALJlTtqCszN_:-MhOCBwBALJlTtqCszNa:bwxdqwn) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/x/x.go#L1480)):*
> ```Go
> func LambdaUrl(ns uint64) string {
> 	lambdaUrl := Config.GraphQL.LambdaUrl
> 	if len(lambdaUrl) > 0 {
> ```

Do we need lambdaUrl? We just need the port number, right? Lambdas would be running in the same process.

**Review by NamanJain8 — COMMENTED** [review]
> Dismissed @manishrjain from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7973)* status: 31 of 58 files reviewed, 3 unresolved discussions (waiting on @danielmai and @manishrjain)

___
*[dgraph/cmd/alpha/run.go, line 236 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOAEfl6kiw80lTEqJL:-MhnvpjHAlz4kB1512zp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/dgraph/cmd/alpha/run.go#L236)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

lambda should have its own flag. We'd want to run lambda functions via DQL too.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 747 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOAS803HMx8Fwi7JaH:-MhnvuEW4-hyPohBTYRZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/dgraph/cmd/alpha/run.go#L747)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move them to their own flags.x
</blockquote></details>

Done.
___
*[graphql/e2e/directives/docker-compose.yml, line 4 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOAf94E9f57OQRclcF:-MhnvycY5AcnvEkQEgDA:b-2g80e9) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/graphql/e2e/directives/docker-compose.yml#L4)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Would this need to be changed?
</blockquote></details>

Yes, this needs to be changed. @danielmai can you please push a new image to dockerhub?  
___
*[x/x.go, line 1480 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOCBwBALJlTtqCszN_:-MhnwoK-E99l_6GJd0ER:blj20wb) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/x/x.go#L1480)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do we need lambdaUrl? We just need the port number, right? Lambdas would be running in the same process.
</blockquote></details>

Lambda URL is kept so that community is free to create their own lambda servers in the language of their choice.
___
*[lambda/slash-graphql-lambda-types/package.json, line 15 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOBIoyA1A1UFaRHGxh:-MhnwQgA61DblSJGpLOb:b-cf3zy3) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/lambda/slash-graphql-lambda-types/package.json#L15)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can you remove the "slash-graphql" name from everywhere?

Also, license should be Dgraph license. Author should be removed. Here and elsewhere.
</blockquote></details>

I have replaced the slash-graphql to dgraph-lambda now. 
As discussed, I have kept it under Apache License.

**Review by manishrjain — APPROVED** [review]
:lgtm: Thanks for the work!

> Reviewed 27 of 27 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-:-Mho-R8OEucTshA0jnd0:b-61upr2)* status: all files reviewed, 3 unresolved discussions (waiting on @danielmai and @manishrjain)

___
*[dgraph/cmd/alpha/run.go, line 236 at r6](https://reviewable.io/reviews/dgraph-io/dgraph/7973#-MhOAEfl6kiw80lTEqJL:-Mhnzcm-AC7mVVzRwEqT:b70xro7) ([raw file](https://github.com/dgraph-io/dgraph/blob/e10fc309e41463cf0daba0965e8fbfda7ae21153/dgraph/cmd/alpha/run.go#L236)):*
<details><summary><i>Previously, NamanJain8 (Naman Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't remove vowels. If you want shorter, use `num`.

**Review by manishrjain — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7973)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai and @manishrjain)

**Pull request merged**
