### PR TITLE
Bugfix/leader

### PR DESCRIPTION
**Pull request by manishrjain**
- Fix the bug due to which a restart from valid snapshot would cause node to not participate in election, hence making Dgraph immutable. Started keeping track of conf state, which is now passed when creating a new snapshot.
- Find the variables in node struct, which could be changed after initialization, or are initialized later. Put all accessors to those under mutex locks.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/410)

### CODE REVIEW

**Comment by jchiu0** [comment]
LG to guard node.raft.
LG to track conf state.

:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/draft.go, line 101 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_G5cW6oYBqKjOpZl:-KZV_G5cW6oYBqKjOpZm:bq8afp5) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L101)):*
> ```Go
> }
> 
> func (n *node) SetRaft(r raft.Node) {
> ```

comments

---

*[worker/draft.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_H8B3FAgotGeTxO1:-KZV_H8B3FAgotGeTxO2:bq8afp5) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L107)):*
> ```Go
> }
> 
> func (n *node) Raft() raft.Node {
> ```

comments

---

*[worker/draft.go, line 174 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_cvTGrzruxU66XGA:-KZV_cvTGrzruxU66XGB:bx8y5bt) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L174)):*
> ```Go
> 
> func (n *node) AddToCluster(ctx context.Context, pid uint64) error {
> 	addr := n.peers.Get(pid)
> ```

Wonder if you should check for n == nil like the other methods, due to n not being initialized yet?

---

*[worker/draft.go, line 272 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_vS9d_NMywlF_V8H:-KZV_vS9d_NMywlF_V8I:bdz2ptp) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L272)):*
> ```Go
> 		// pass
> 	default:
> 		log.Fatalf("Unable to push messages to channel in send")
> ```

x.Fatalf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-:-KZVZr_5njNnXai4-IfM:brccvrp)*

**Comment by ashishnegi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[worker/draft.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZVlSL1ZuS1OOIqHf6V:-KZVlSL1ZuS1OOIqHf6W:b-s8p169) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L114)):*
> ```Go
> 	defer n.RUnlock()
> 	return n._raft
> }
> ```

i do not know the domain here, but what should happen to  goroutines working with older raft node ?

---

*[worker/draft.go, line 512 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZVl7893z69eiQFnmiE:-KZVl78A1LF5GLvB02NJ:b-5hglec) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L512)):*
> ```Go
> 			n.Raft().Advance()
> 			if firstRun && n.canCampaign {
> 				go n.Raft().Campaign(n.ctx)
> ```

can n.Raft() value change between two function calls ?

---

*[worker/draft.go, line 687 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZVk8Vm4JG-G3d_rpOH:-KZVk8Vn7XRqjlWNMUQk:b-nu8c7s) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L687)):*
> ```Go
> 		return false
> 	}
> 	r := n.Raft()
> ```

it will be better to initialize `r` first and then check `nil`..
_raft can change between two function calls.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/410)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[worker/draft.go, line 406 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZYpsyUk5zUJX4VHgUI:-KZYpsyUk5zUJX4VHgUJ:bqxgyl7) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L406)):*
> ```Go
> 
> 			n.Lock()
> 			n._confState = n.Raft().ApplyConfChange(cc)
> ```

Could consider moving it to a function called SetConfState?

---

*[worker/draft.go, line 570 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZYq9QnK6HGyPCXB-aB:-KZYq9QnK6HGyPCXB-aC:b9mvn28) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L570)):*
> ```Go
> 
> 			n.RLock()
> 			cf := n._confState
> ```

Here too, could move it to a function which does locking and unlocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-:-KZYqNHyzmlD7X7-nO1j:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[worker/draft.go, line 101 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_G5cW6oYBqKjOpZl:-KZZI3RzuYMHMhK4lmR7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L101)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

comments
</blockquote></details>

Done.

---

*[worker/draft.go, line 107 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_H8B3FAgotGeTxO1:-KZZI3qZr-BN2dZ3Ar-z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L107)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

comments
</blockquote></details>

Done.

---

*[worker/draft.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZVlSL1ZuS1OOIqHf6V:-KZZI4kfnQQkzKjtEAd-:b-vmzna6) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L114)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

i do not know the domain here, but what should happen to  goroutines working with older raft node ?
</blockquote></details>

I just added a check fail, so we never overwrite any previous raft. It should only be set once.

---

*[worker/draft.go, line 174 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_cvTGrzruxU66XGA:-KZZICvXw4j83Tr4mISS:bwo1c6o) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L174)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Wonder if you should check for n == nil like the other methods, due to n not being initialized yet?
</blockquote></details>

hmm.. has never really caused any trouble. We run this later I think.

---

*[worker/draft.go, line 272 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZV_vS9d_NMywlF_V8H:-KZZINbFyIqaMjTHHOqT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L272)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

x.Fatalf
</blockquote></details>

Done.

---

*[worker/draft.go, line 406 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZYpsyUk5zUJX4VHgUI:-KZZIOFOeYrVsN8HzkZr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L406)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Could consider moving it to a function called SetConfState?
</blockquote></details>

Done.

---

*[worker/draft.go, line 512 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZVl7893z69eiQFnmiE:-KZZIOmls-C_dppj39Kd:b-83og3x) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L512)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

can n.Raft() value change between two function calls ?
</blockquote></details>

Nope.

---

*[worker/draft.go, line 570 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZYq9QnK6HGyPCXB-aB:-KZZIS4meIqiKt2i-b2q:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L570)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Here too, could move it to a function which does locking and unlocking.
</blockquote></details>

Done.

---

*[worker/draft.go, line 687 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/410#-KZVk8Vm4JG-G3d_rpOH:-KZZIVfaEqKeB-XfHzpz:bnz66mm) ([raw file](https://github.com/dgraph-io/dgraph/blob/8740fb2d25ee2ce9a37d3bf157da2456f0f38724/worker/draft.go#L687)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

it will be better to initialize `r` first and then check `nil`..
_raft can change between two function calls.
</blockquote></details>

Made it so that if it changes, we'll log fatal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/410)*

**Pull request closed without merging**
