### PR TITLE
Feature/ineq

### PR DESCRIPTION
**Pull request by jchiu0**
Add gt, lt and eq.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/441)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-:-K_XxtBKzUZZyDges1a5:bnfp4nl)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 40 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-K_Y-1TfDvgJvY3x414w:-K_Y-1TlrA3M1Van8r9n:b-falldz) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5e87ef64947703dc92fd663122eac66a04c6e5e/worker/task.go#L40)):*
> ```Go
> const (
> 	ineqNone  = iota
> 	ineqEqual = iota
> ```

Only the first one should be equal to iota. The rest are set to 1+previous. So, you don't need to set them to iota.

---

*[worker/task.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-K_Y-hXn3ai-SNOrmQBj:-K_Y-hXn3ai-SNOrmQBk:b-92fed8) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5e87ef64947703dc92fd663122eac66a04c6e5e/worker/task.go#L114)):*
> ```Go
> 	if useFunc {
> 		f := q.SrcFunc[0]
> 		switch f {
> ```

Seems unnecessary.

---

*[worker/task.go, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-K_Y-IoRFFSBGsQhW6-d:-K_Y-IoRFFSBGsQhW6-e:bear92i) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5e87ef64947703dc92fd663122eac66a04c6e5e/worker/task.go#L234)):*
> ```Go
> 
> 			switch ineqType {
> 			case ineqGeq:
> ```

Why bother with these if you're going to do switch case anyway. Can't you do the switch f { .. } here?

---

*[worker/tokens.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-K_Y-daKy4MNqOXk6ZXZ:-K_Y-daKy4MNqOXk6ZX_:b-hnxgre) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5e87ef64947703dc92fd663122eac66a04c6e5e/worker/tokens.go#L19)):*
> ```Go
> 
> // getInequalityTokens gets tokens geq / leq compared to given token.
> func getInequalityTokens(attr, ineqValueToken string, ineqType int) ([]string, error) {
> ```

You could just pass the function name here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/441)*

**Comment by jchiu0** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[worker/task.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-K_Y-hXn3ai-SNOrmQBj:-K_cLuIccG_tLNSa73qk:bohd3rj) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5e87ef64947703dc92fd663122eac66a04c6e5e/worker/task.go#L114)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Seems unnecessary.
</blockquote></details>

Was hoping to save some string comparisons, but it's not really necessary.

---

*[worker/task.go, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-K_Y-IoRFFSBGsQhW6-d:-K_cM-Z9LbFKo9n06BXj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5e87ef64947703dc92fd663122eac66a04c6e5e/worker/task.go#L234)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why bother with these if you're going to do switch case anyway. Can't you do the switch f { .. } here?
</blockquote></details>

Done.

---

*[worker/tokens.go, line 19 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-K_Y-daKy4MNqOXk6ZXZ:-K_cM0rTxHeXT-Iij2Ex:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5e87ef64947703dc92fd663122eac66a04c6e5e/worker/tokens.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You could just pass the function name here as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/441)*

**Comment by jchiu0** [comment]
Undoing worker/draft.go changes. (dirty)

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-:-K_cMMb65oBF_zDm5Prg:b-osa86t)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-:-K_gF8rtAz557bcd5Y8C:bnfp4nl)*

**Comment by jchiu0** [comment]
Thanks!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/441#-:-K_lsIDmUw8MjpYfrvBK:b-ucfknh)*

**Pull request closed without merging**
