### PR TITLE
fix(GraphQL): handle filters for enum properly

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
Fixes GRAPHQL-817.

This PR is a breaking change for the `eq` filter on the List of `enum` Types.

This PR fixes bugs in the filter generated for enum types. For the given schema:-
```
enum Status {
   ACTIVE
   DEACTIVATED
}

type VerificationFilter {
    status: [Status]! @search
}
```

the `hash` filter generated for `status` was:
```
input Status_hash {
   eq: [Status]!
   in: [Status]
}
```
whereas, it should be:
```
input Status_hash {
    eq: Status
    in: [Status]
}
```

This PR also fixes incorrect filter generated for `exact` index in List of enum types. 
Earlier it was being generated like:
```
input Status_exact {
	eq: [Status]
	in: [Status]
	le: [Status]
	lt: [Status]
	ge: [Status]
	gt: [Status]
	between: Status
}
```
but it should be like:
```
input Status_exact {
	eq: Status
	in: [Status]
	le: Status
	lt: Status
	ge: Status
	gt: Status
	between: Status
}
```

Breaking change lies in the generation of `eq` filters. Earlier it was `eq: [Status]!` but now it is `eq: Status`. Both are syntactically fine but `eq: [Status]!` conflicts with the expected usage of `eq` filter.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6887)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
We need some query rewriting tests in which

1. You pass IN as null
2. You pass an item in the IN array as null
3. You pass eq as null
4. You pass an item in eq array as null
5. You pass both IN and eq as null.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-:-MLw6OplETaZhYAlYttV:b61hw3l)* status: all files reviewed, 4 unresolved discussions (waiting on @MichaelJCompton and @minhaj-shakeel)

___
*[graphql/schema/gqlschema.go, line 1237 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MLw4iAV6vyWkiAUiu5A:-MLw4iAWDTHv2dC9700_:b-cfgilu) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f7ebf80f023b945148ebe60abb7a9aacc4fa4b/graphql/schema/gqlschema.go#L1237)):*
> ```Go
> 					typ = &ast.Type{
> 						NamedType: enumTypeName,
> 						NonNull:   false,
> ```

this is the default value so no need to mention it anywhere
___
*[graphql/schema/testdata/schemagen/input/searchables.graphql, line 23 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MLw5EFIATIy_BYbKifW:-MLw5EFIATIy_BYbKifX:bcppkkw) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f7ebf80f023b945148ebe60abb7a9aacc4fa4b/graphql/schema/testdata/schemagen/input/searchables.graphql#L23)):*
> ```GraphQL
> 
> 	postType: PostType @search
> 		postTypeNonNull: PostType! @search
> ```

something messed up about the indentation here
___
*[graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql, line 510 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MLw5pOt4QcWKFmrkS6V:-MLw5pOt4QcWKFmrkS6W:bt0ydl1) ([raw file](https://github.com/dgraph-io/dgraph/blob/c4d8641b81dd869bf7bee821c54ae293ae96e319/graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql#L510)):*
> ```GraphQL
> 
> input Episode_hash {
> 	eq: [Episode!]!
> ```

It was an array earlier for enums and now is just one value? This would be a breaking change. I do realize that we must remove the outer `!` but we can still keep it as `eq: [Episode!]`
___
*[graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql, line 511 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MLw5YUSAZbpal1b2wvw:-MLw5YUSAZbpal1b2wvx:b-iz1hcz) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f7ebf80f023b945148ebe60abb7a9aacc4fa4b/graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql#L511)):*
> ```GraphQL
> input Episode_hash {
> 	eq: Episode
> 	in: [Episode]
> ```

Should this not be `[Episode!]` if the field was of type `Episode!`because `[null]` is not a valid value in that case?

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6887)* status: 3 of 9 files reviewed, 4 unresolved discussions (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/schema/gqlschema.go, line 1237 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MLw4iAV6vyWkiAUiu5A:-MM0Mkaq3EV3KxA3OkzC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f7ebf80f023b945148ebe60abb7a9aacc4fa4b/graphql/schema/gqlschema.go#L1237)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

this is the default value so no need to mention it anywhere
</blockquote></details>

Done.
___
*[graphql/schema/testdata/schemagen/input/searchables.graphql, line 23 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MLw5EFIATIy_BYbKifW:-MM0MlgCCJxhGRduGaDo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f7ebf80f023b945148ebe60abb7a9aacc4fa4b/graphql/schema/testdata/schemagen/input/searchables.graphql#L23)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

something messed up about the indentation here
</blockquote></details>

Done.
___
*[graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql, line 511 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MLw5YUSAZbpal1b2wvw:-MM0Mnxg5kSOv_pAG3qA:b-xlh43u) ([raw file](https://github.com/dgraph-io/dgraph/blob/b5f7ebf80f023b945148ebe60abb7a9aacc4fa4b/graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql#L511)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Should this not be `[Episode!]` if the field was of type `Episode!`because `[null]` is not a valid value in that case?
</blockquote></details>

Keeping this as it is as dist over the call.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6887)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton, @minhaj-shakeel, and @pawanrawal)

___
*[graphql/schema/testdata/schemagen/output/searchables.graphql, line 27 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MM0S4QX4qrEOIm1NVLh:-MM0S4QX4qrEOIm1NVLi:bl4jo9m) ([raw file](https://github.com/dgraph-io/dgraph/blob/eb83b72e30709f5dc9e7e2a741e878322ae88cee/graphql/schema/testdata/schemagen/output/searchables.graphql#L27)):*
> ```GraphQL
> 	postTypeTrigram: PostType @search(by: [trigram])
> 	postTypeRegexp: PostType @search(by: [regexp])
> 	postTypeExact(first: Int, offset: Int): [PostType] @search(by: [exact])
> ```

Can we do pagination over enums, that shouldn't be allowed.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6887)* status: all files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton and @minhaj-shakeel)

___
*[graphql/schema/gqlschema.go, line 1117 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6887#-MMKTYA47SLIRGrn1S98:-MMKTYA47SLIRGrn1S99:b-yl3qz6) ([raw file](https://github.com/dgraph-io/dgraph/blob/29bcc45c77c1099ee116fb4311b1b12a0a5d3da4/graphql/schema/gqlschema.go#L1117)):*
> ```Go
> 		// Ordering and pagination, however, only makes sense for fields of
> 		// list types (not scalar lists or enum lists).
> 		if isTypeList(fld) && !isEnumList(fld, schema) {
> ```

nice change

**Pull request merged**
