### PR TITLE
Chore (test): unskip protos 

### PR DESCRIPTION
**Pull request by SashaDgraph**
## Problem
 
Protos was skipped.
## Solution
 
Protos was unskipped.

### CODE REVIEW

**Comment by skrdgraph** [comment]
fix photos -> protos, and also look into fixing this auto-correct on your system

**Comment by SashaDgraph** [comment]
> fix photos -> protos, and also look into fixing this auto-correct on your system

Fixed to protos for now. Will look into autocorrect.

**Comment by SashaDgraph** [comment]
> > fix photos -> protos, and also look into fixing this auto-correct on your system
> 
> Fixed to protos for now. Will look into autocorrect.

Fixed autocorrect

**Review by skrdgraph — APPROVED** [review]
Looks good (I marked it for review, and reviewing it now)

**Pull request merged**
