### PR TITLE
Regex match on terms

### PR DESCRIPTION
**Pull request by ashwin95r**
```
# For example: Name of friends starting with "ri" or "gr"
{
   me(id:0x01) {
      name
      friend @filter(regexp(name, "^(ri|gr)")) {
         name
       }
   }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/632)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/task.go, line 342 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-KddEhQqsxzw0b36TS5l:-KddEhQqsxzw0b36TS5m:b-n7uilc) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L342)):*
> ```Go
> 		// the regex matcher.
> 		it := pstore.NewIterator()
> 		for it.SeekToFirst(); it.Valid(); {
> ```

I think better to generate the key for the predicate's index, and seek to that straight away. Also, if we keep the equal values in a different prefix, it would make the regexp much more efficient.

---

*[worker/task.go, line 357 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-KddPyrpBl6Cd6qIBMHd:-KddPyrpBl6Cd6qIBMHe:bwrh4i4) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L357)):*
> ```Go
> 			x.AssertTrue(pk.Attr == q.Attr)
> 			if regex.MatchString(pk.Term) {
> 				// Note: Even is one term in the index passes the matcher, the
> ```

Using full strings as keys would resolve this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/632)*

**Comment by ashwin95r** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 342 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-KddEhQqsxzw0b36TS5l:-Kde-we_qdHPxiNJa5Zi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L342)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I think better to generate the key for the predicate's index, and seek to that straight away. Also, if we keep the equal values in a different prefix, it would make the regexp much more efficient.
</blockquote></details>

Done.

---

*[worker/task.go, line 357 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-KddPyrpBl6Cd6qIBMHd:-Kde-vpWuPT6aOh47wJg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L357)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Using full strings as keys would resolve this issue.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/632)*

**Comment by gacharya255** [comment]
Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 341 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde3CY4Q5RmtKJ519VW:-Kde3CY4Q5RmtKJ519VX:bfvngx3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L341)):*
> ```Go
> 		// Go through the indexkeys for the predicate and match them with
> 		// the regex matcher.
> 		it := pstore.NewIterator()
> ```

defer it.Close is safer.

---

*[worker/task.go, line 347 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde3tqD6oMGT-toqE7x:-Kde3tqEUDedT2QM9THB:b7cu5i9) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L347)):*
> ```Go
> 			if !pk.IsIndex() {
> 				// Non index keys. Skip them.
> 				it.Seek(pk.SkipRangeOfSameType())
> ```

Add a continue here? Otherwise the next type might still not be index?

---

*[worker/task.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde44rxJKJrgB705X_S:-Kde44rxJKJrgB705X_T:bypr605) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L355)):*
> ```Go
> 				continue
> 			}
> 			x.AssertTrue(pk.Attr == q.Attr)
> ```

If we already know q.Attr, couldn't we seek directly to attr+index? You can create a ParsedKey that has attr and is index and seek to that.

---

*[worker/task.go, line 364 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde4TRnkSTqmYTDAnhN:-Kde4TRnkSTqmYTDAnhO:bvzq026) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L364)):*
> ```Go
> 				decr()
> 			}
> 			it.Next()
> ```

In this case, I think you can put it.Next at the top like "for it.SeekToFirst(); it.Valid(); it.Next()".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/632)*

**Comment by manishrjain** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 43 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde53czaxPYMrH_3KGi:-Kde53czaxPYMrH_3KGj:b-27kar0) ([raw file](https://github.com/dgraph-io/dgraph/blob/7dba4a453d6a7863999d4945588fca753cc3ae59/posting/index.go#L43)):*
> ```Go
> }
> 
> func NeedExactIndex(attr string, src types.Val) (string, bool) {
> ```

The function naming could use some work. It's unclear what it's for.

---

*[posting/index.go, line 134 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde5SR7-Ktp88pI--rf:-Kde5SR80E-jujcgKzDi:b-vdwp6t) ([raw file](https://github.com/dgraph-io/dgraph/blob/7dba4a453d6a7863999d4945588fca753cc3ae59/posting/index.go#L134)):*
> ```Go
> 
> func addExactIndexMutation(ctx context.Context, edge *task.DirectedEdge, val string) {
> 	key := x.ExactIndexKey(edge.Attr, val)
> ```

s/ExactIndexKey/FullStringKey

---

*[posting/lists.go, line 389 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde60yJtHeLWm_n7NO6:-Kde60yJtHeLWm_n7NO7:bedhdtw) ([raw file](https://github.com/dgraph-io/dgraph/blob/7dba4a453d6a7863999d4945588fca753cc3ae59/posting/lists.go#L389)):*
> ```Go
> 	// index key to the data store, with essentially an empty value. We just need
> 	// the keys for filtering / sorting.
> 	if l == lp && (pk.IsIndex() || pk.IsExactIndex()) {
> ```

Not a fan of this "ExactIndex" logic. We should fit this into our tokenizer instead. For e.g., we could do a tokenizer union, i.e. allow multiple tokenizers for the same predicate. That way, a user can specify both `token` and `exact` tokenizer for string. Then for regexps, we use the exact index.

To differentiate between these indices, we could embed a unique id per tokenizer in the prefix; so if we need to only iterate over `exact` index, we can do so using that prefix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/632)*

**Comment by ashwin95r** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[worker/task.go, line 341 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde3CY4Q5RmtKJ519VW:-Kde8MVvvam-rj5ete-r:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L341)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

defer it.Close is safer.
</blockquote></details>

Done.

---

*[worker/task.go, line 347 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde3tqD6oMGT-toqE7x:-Kde86qTl4Ic70-nLqR0:bkojojf) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L347)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Add a continue here? Otherwise the next type might still not be index?
</blockquote></details>

Changed the loop format.

---

*[worker/task.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde44rxJKJrgB705X_S:-Kde7u2rXSOMD_H24S4h:bdddb9z) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L355)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

If we already know q.Attr, couldn't we seek directly to attr+index? You can create a ParsedKey that has attr and is index and seek to that.
</blockquote></details>

There is an `it.Seek(startKey)`. Done.

---

*[worker/task.go, line 364 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/632#-Kde4TRnkSTqmYTDAnhN:-Kde81tu_BgydDkbG87_:bd5n3t) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22fdada788fc24f5bd75ff95e75e348f2744b43/worker/task.go#L364)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

In this case, I think you can put it.Next at the top like "for it.SeekToFirst(); it.Valid(); it.Next()".
</blockquote></details>

Changed the loop format a bit. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/632)*

**Comment by ashwin95r** [comment]
Took a different approach in #637

**Pull request closed without merging**
