### PR TITLE
Revert block list. Some optimizations.

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/663)

### CODE REVIEW

**Comment by ashishnegi** [comment]
:lgtm: just one comment.

---

Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 418 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/663#-KeX-nWZEbR9-RdaiwSv:-KeX-nW_hcf25M_NM4fq:bsjy8pf) ([raw file](https://github.com/dgraph-io/dgraph/blob/94886950efd10e5f36bdbefcda70dc992e4088c9/query/outputnode.go#L418)):*
> ```Go
> 	}
> 	lenList := len(sg.uidMatrix[0].Uids)
> 	for i := 0; i < lenList; i++ {
> ```

if we are not using `i` .. may be we can use `for _, uid := range sg.uidMatrix[0].Uids`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/663#-:-KeX3BLTBc09spI2t8sA:b-nngxwy)*

**Comment by ashwin95r** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 418 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/663#-KeX-nWZEbR9-RdaiwSv:-KeXENIrzOg9RMgn5Gs2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/94886950efd10e5f36bdbefcda70dc992e4088c9/query/outputnode.go#L418)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

if we are not using `i` .. may be we can use `for _, uid := range sg.uidMatrix[0].Uids`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/663)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 15 of 16 files at r1, 1 of 1 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[algo/uidlist.go, line 35 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/663#-KeXD9DW7vdjqAe5Huzt:-KeXD9DW7vdjqAe5Huzu:b-4l44br) ([raw file](https://github.com/dgraph-io/dgraph/blob/233224eaaaa96e06622b5d3f10952102a4b50274/algo/uidlist.go#L35)):*
> ```Go
> 	ratio := float64(m) / float64(n+1)
> 	if ratio < 500 {
> 		IntersectWithLin(u, v, wasSwitched)
> ```

No need for wasSwitched.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/663#-:-KeXF0uaqh9e-tJYmTi7:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[algo/uidlist.go, line 35 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/663#-KeXD9DW7vdjqAe5Huzt:-KeXFaVH3uLhlKhwQfXp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/233224eaaaa96e06622b5d3f10952102a4b50274/algo/uidlist.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for wasSwitched.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/663)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
