### PR TITLE
RAFT: Start cluster, join cluster, bring follower up to speed.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/242)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 26 files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

*[task.fbs, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeCqXNIB3BClfs48X0:-KSeCqXNIB3BClfs48X1:b7h7dvf) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/task.fbs#L36)):*
> ```
> }
> 
> table KT {
> ```

We change this to KC as discussed.

---

*[cmd/dgraph/main.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeDfcCFw7eHtdDnFdk:-KSeDfcCFw7eHtdDnFdl:bkb4tek) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L59)):*
> ```Go
> 	numcpu      = flag.Int("cores", runtime.NumCPU(),
> 		"Number of cores to be used by the process")
> 	instanceIdx = flag.Uint64("idx", 0,
> ```

maybe we should change the default value and description here.

---

*[cmd/dgraph/main.go, line 584 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeCzQI4F0vYoDD1djO:-KSeCzQI4F0vYoDD1djP:b-q6y19j) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L584)):*
> ```Go
> 	var ws *worker.State
> 	if groupId != 0 { // HACK: This will currently not run.
> 		ws = worker.NewState(ps, nil, groupId, 1) // TODO: Set number of grous here.
> ```

groups

---

*[cmd/dgraph/main.go, line 600 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeEbRB27FAQsA-481T:-KSeEbRCLvxX2njFMFax:b-k0aq54) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L600)):*
> ```Go
> 	}
> 
> 	my := "localhost" + *workerPort
> ```

So this becomes `localAddr` inside a raft `node`. Since this would be common for all nodes(which are part of different groups), maybe this should be part of worker State?

---

*[cmd/dgraph/main.go, line 601 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeFBe7wS9CQRXGVglY:-KSeFBe7wS9CQRXGVglZ:bb37apb) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L601)):*
> ```Go
> 
> 	my := "localhost" + *workerPort
> 	worker.InitNode(uint64(*instanceIdx), my)
> ```

it's an uint64 already.

---

*[cmd/dgraph/main.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeRl4vDvHezMkWvflO:-KSeRl4vDvHezMkWvflP:bugpawg) ([raw file](https://github.com/dgraph-io/dgraph/blob/14040200df2bfb4c62eece9f348f93af266e4a6f/cmd/dgraph/main.go#L63)):*
> ```Go
> 		"serves only entities whose Fingerprint % numInstance == instanceIdx.")
> 	cluster = flag.String("cluster", "", "List of peers in this format: ID1:URL1,ID2:URL2,...")
> 	peer    = flag.String("peer", "", "Address of any peer.")
> ```

For now wondering if leader would be a better name, because that is what this signifies?

---

*[worker/draft.go, line 229 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeJFGJqG3HV58KaKp9:-KSeJFGJqG3HV58KaKpA:b-lqx04j) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L229)):*
> ```Go
> 	pid, err := strconv.ParseUint(kv[0], 10, 64)
> 	x.Checkf(err, "Invalid peer id: %v", kv[0])
> 	return pid, kv[1]
> ```

We need a way to validate the URL, kv[1] here too because SplitN will just put everything after then first `:` into it.  Maybe add a TODO here?

---

*[worker/draft.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeP8bFHQm-z3tSfdLL:-KSeP8bFHQm-z3tSfdLM:b-59w6u2) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L232)):*
> ```Go
> }
> 
> func (n *node) JoinCluster(any string) {
> ```

should it be leader?

---

*[worker/draft.go, line 268 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeE0A-czHy1moCgJwn:-KSeE0A-czHy1moCgJwo:b-sexlnm) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L268)):*
> ```Go
> 		store: store,
> 		cfg: &raft.Config{
> 			ID:              uint64(id),
> ```

its already a unint64.

---

*[worker/draft.go, line 283 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeGfPweDZZwxUmGU7b:-KSeGfPxyjKqMQXKH9pl:bmk6uys) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L283)):*
> ```Go
> 
> func (n *node) StartNode(cluster string) {
> 	var raftPeers []raft.Peer
> ```

Could just be called peers?

---

*[worker/draft.go, line 288 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeGo56yuHTtyGhE3tY:-KSeGo56yuHTtyGhE3tZ:b-545ht2) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L288)):*
> ```Go
> 
> 		for _, p := range strings.Split(cluster, ",") {
> 			pid, paddr := parsePeer(p)
> ```

For the node which forms the cluster, won't this add it as a raftPeer twice? Wonder if that has some consequences while doing a StartNode.

---

*[worker/draft.go, line 307 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSdrJKjvdRtZx-VuBWN-r1-307:-KSeRaEWASRhXZEbrJ_X:bgl5u3j) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L307)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function GetNode should have comment or be unexported<br>exported func GetNode returns unexported type *worker.node, which can be annoying to use
</details>
We need to fix this, maybe later.

---

*[worker/worker.go, line 202 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSePW7UUmc7ac_gffr2:-KSePW7UUmc7ac_gffr3:bmo0llp) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/worker.go#L202)):*
> ```Go
> 		return reply, x.Errorf("JoinCluster: No data provided")
> 	}
> 	kv := strings.SplitN(string(query.Data), ":", 2)
> ```

I see we are using this in parsePeer too. Maybe we can reuse  that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/242)*

**Comment by manishrjain** [comment]
Review status: 0 of 26 files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

*[task.fbs, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeCqXNIB3BClfs48X0:-KSeUqC6KwsdYu7MNKMU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/task.fbs#L36)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We change this to KC as discussed.
</details>
Done.

---

*[cmd/dgraph/main.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeDfcCFw7eHtdDnFdk:-KSeVELIqi7WQ4GqL2Mv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L59)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> maybe we should change the default value and description here.
</details>
Done.

---

*[cmd/dgraph/main.go, line 584 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeCzQI4F0vYoDD1djO:-KSeVX6oLFblMTX6jMvk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L584)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> groups
</details>
Done.

---

*[cmd/dgraph/main.go, line 600 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeEbRB27FAQsA-481T:-KSeXhVi7gQDsQVNQdFt:b6m5f3k) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L600)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> So this becomes `localAddr` inside a raft `node`. Since this would be common for all nodes(which are part of different groups), maybe this should be part of worker State?
</details>
Right now, it's hard to say. This would change as we introduce groups and stuff -- so maybe will tackle this later.

---

*[cmd/dgraph/main.go, line 601 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeFBe7wS9CQRXGVglY:-KSeXwRFUSsQM_hF94Q1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L601)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> it's an uint64 already.
</details>
Done.

---

*[cmd/dgraph/main.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeRl4vDvHezMkWvflO:-KSeVFbI-oYtCxvS92g-:b-au5ajf) ([raw file](https://github.com/dgraph-io/dgraph/blob/14040200df2bfb4c62eece9f348f93af266e4a6f/cmd/dgraph/main.go#L63)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> For now wondering if leader would be a better name, because that is what this signifies?
</details>
Actually, leaders can change. We just want to connect to any peer. And then that peer can tell us about the leader.

---

*[worker/draft.go, line 229 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeJFGJqG3HV58KaKp9:-KSeY8G_HiIfsl90Sz0W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L229)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We need a way to validate the URL, kv[1] here too because SplitN will just put everything after then first `:` into it.  Maybe add a TODO here?
</details>
Done.

---

*[worker/draft.go, line 232 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeP8bFHQm-z3tSfdLL:-KSeY8u9lgsQeI3JRsMH:b7x6byw) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L232)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> should it be leader?
</details>
Not necessarily. The peer would automatically forward this to the leader. But, yeah, if we have another call before JoinCluster to find the leader, then our shard copy would be better.

---

*[worker/draft.go, line 268 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeE0A-czHy1moCgJwn:-KSeYOaR22XU3vpvwuq3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L268)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> its already a unint64.
</details>
Done.

---

*[worker/draft.go, line 283 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeGfPweDZZwxUmGU7b:-KSeYaksmnf_XYeo4F5r:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L283)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Could just be called peers?
</details>
Done.

---

*[worker/draft.go, line 288 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeGo56yuHTtyGhE3tY:-KSeYbnIl1kI5ARu45YX:b-xsfvr5) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L288)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> For the node which forms the cluster, won't this add it as a raftPeer twice? Wonder if that has some consequences while doing a StartNode.
</details>
Hmm... good catch. We don't need it. Removed it.

---

*[worker/draft.go, line 307 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSdrJKjvdRtZx-VuBWN-r1-307:-KSe_v8AZv0GYyiyxISv:bupuszy) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/draft.go#L307)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We need to fix this, maybe later.
</details>
Yeah, once this stabilizes a bit, will clean it up.

---

*[worker/worker.go, line 202 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSePW7UUmc7ac_gffr2:-KSeaOBRmgr_oatLKw_T:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/worker/worker.go#L202)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I see we are using this in parsePeer too. Maybe we can reuse  that?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/242)*

**Comment by pawanrawal** [comment]
:lgtm:  One small change that I can think of.

---

Review status: 0 of 26 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-KSeDfcCFw7eHtdDnFdk:-KSeccrR1h2nhYUBSMvR:b3aa2ux) ([raw file](https://github.com/dgraph-io/dgraph/blob/9774553b670396e68a992b298fae013b9583b5e4/cmd/dgraph/main.go#L59)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Done.
</details>
Should we change default value to 1? Also we should log.Fatal if this is zero?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/242#-:-KSedDprJKMEqrcvAKDm:b-uzzjd7)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
