### PR TITLE
Improved language lists

### PR DESCRIPTION
**Pull request by tzdybal**
Introduction of `.` in language lists (see #1010).
Small refactoring.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1014)

### CODE REVIEW

**Comment by szymonm** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[gql/state.go, line 290 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-Klryv7fFRrrf5arq0Hz:-Klryv7fFRrrf5arq0I-:b3ndqk2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/gql/state.go#L290)):*
> ```Go
> 		switch r := l.Next(); {
> 		case r == period:
> 			two := l.Next() == period
> ```

shouldn't we check that l is valid after Next()

---

*[gql/state.go, line 366 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-KlrzwcwAJGFPdYHhH7U:-KlrzwcxlsmW-OPKCoPR:b6qv6mp) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/gql/state.go#L366)):*
> ```Go
> 	r := l.Next()
> 	if r == period {
> 		return lexName
> ```

wasn't the period already consumed in 298?

Why do you need to add period in 2 places?

---

*[query/query.go, line 440 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-Kls-yKT4rTtmap3YKed:-Kls-yKT4rTtmap3YKee:b-le1qxd) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/query/query.go#L440)):*
> ```Go
> 			}
> 		} else {
> 			// TODO: tzdybal
> ```

can you add some description of what needs to be done for others

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014)*

**Comment by tzdybal** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[gql/state.go, line 290 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-Klryv7fFRrrf5arq0Hz:-KlsYOnoxec8yDyb2BHO:b-4b6t73) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/gql/state.go#L290)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

shouldn't we check that l is valid after Next()
</blockquote></details>

This would complicate the code. And case when `l` is invalid is a probably very rare error case. Even if we reach `EOF`, code should fail gently in parser. Test added for this case.

---

*[gql/state.go, line 366 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-KlrzwcwAJGFPdYHhH7U:-KlsRQgc20JgveWSq_bU:b-3v393m) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/gql/state.go#L366)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

wasn't the period already consumed in 298?

Why do you need to add period in 2 places?
</blockquote></details>

This is the case of `name@.` - `.` directly after `@` - line 298 is not executed before.

---

*[query/query.go, line 440 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-Kls-yKT4rTtmap3YKed:-KlsN9BuGC4YLxp0IW8y:bc4zor2) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/query/query.go#L440)):*
<details><summary><i>Previously, szymonm (Szymon) wrote…</i></summary><blockquote>

can you add some description of what needs to be done for others
</blockquote></details>

I need to remove this comment. It's not relevant anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014)*

**Comment by manishrjain** [comment]
Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/state.go, line 290 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-Klryv7fFRrrf5arq0Hz:-Klw9rr6tuabS0ShW2lY:b-882p8f) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/gql/state.go#L290)):*
<details><summary><i>Previously, tzdybal (Tomasz Zdybał) wrote…</i></summary><blockquote>

This would complicate the code. And case when `l` is invalid is a probably very rare error case. Even if we reach `EOF`, code should fail gently in parser. Test added for this case.
</blockquote></details>

This sort of checking should be done in parser, not in lexer. For e.g., we can't really backup twice, we don't really store those positions (the only reason it's working right now is because of things being ascii, and only taking 1 byte). In fact, I think we should get rid of the Backup call altogether.

---

*[gql/state.go, line 297 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-KlwA9j-sciZCheSFLzG:-KlwA9j-sciZCheSFLzH:b-83og3x) ([raw file](https://github.com/dgraph-io/dgraph/blob/5c0d28466754750124bf91fd654f5c79cae7c7f5/gql/state.go#L297)):*
> ```Go
> 			} else {
> 				l.Backup()
> 				l.Backup()
> ```

Nope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014)*

**Comment by tzdybal** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[gql/state.go, line 290 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-Klryv7fFRrrf5arq0Hz:-Km9XUChT-z_kjrCNROI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0ccd25cb4ddf07fdafce86235262f777fd19dacd/gql/state.go#L290)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This sort of checking should be done in parser, not in lexer. For e.g., we can't really backup twice, we don't really store those positions (the only reason it's working right now is because of things being ascii, and only taking 1 byte). In fact, I think we should get rid of the Backup call altogether.
</blockquote></details>

Done.

---

*[gql/state.go, line 297 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-KlwA9j-sciZCheSFLzG:-Km9XQBktb0vTrzAgr-e:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5c0d28466754750124bf91fd654f5c79cae7c7f5/gql/state.go#L297)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Nope.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014)*

**Comment by manishrjain** [comment]
:lgtm: One comment for another test. Feel free to submit after that.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 6073 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-Km9ZsCgy5h16Jt2sL3u:-Km9ZsCh1EKYMwaR2Eif:b1aiyc0) ([raw file](https://github.com/dgraph-io/dgraph/blob/22349120a04b9d7b38a87838f20e8493db0bc19c/query/query_test.go#L6073)):*
> ```Go
> 		{
> 			me(id:0x1004) {
> 				name@hi:cn:.
> ```

Can you also check for `name@hi:cn:...`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1014#-:-Km9ZwMsRyWTWjpCZ9xY:bysa9lw)*

**Comment by tzdybal** [comment]
Changes merged to master.

**Pull request closed without merging**
