### PR TITLE
feat(DQL): @groupby on scalar fields and count duplicate 

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
This PR extends support for var inside the @groupby query on a scalar predicate at root.
for example the given query now doesn't result to error:-
```
var(func: ... ) @groupby(age) {
  c as count(uid)
}
```
Now the uid variable `c` contains map of uid to count of uids with the same age.
Suppose for the data :-
```{
        "uid": "0x1",
        "age": 38
      },
      {
        "uid": "0x17",
        "age": 15
      },
      {
        "uid": "0x18",
        "age": 15
      },
      {
        "uid": "0x19",
        "age": 17
      }
```
The following groupby query:-
```
var(func: uid(1, 23, 24, 25)) @groupby(age) {
      c as count(uid)
}
 me(func: uid(c)) {
      uid
      val(c)
}
```
returns the result:-
```
"data": {
    "me": [
      {
        "uid": "0x1",
        "val(c)": 1
      },
      {
        "uid": "0x17",
        "val(c)": 2
      },
      {
        "uid": "0x18",
        "val(c)": 2
      },
      {
        "uid": "0x19",
        "val(c)": 1
      }
    ]
  }
```
The behaviour will be the same if there are multiple predicates and some of them are uid predicates.
However, it is only supported at root currently. Hence the given query will still return error:-
```
var(func: .....) {
   friend @groupby(age) {
       a as count(uid)
   }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7746)

### CODE REVIEW

**Review by pawanrawal — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7746)* status: all files reviewed, 2 unresolved discussions (waiting on @minhaj-shakeel)

___
*[query/groupby.go, line 320 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-MZHIX-13UR77FSrizt1:-MZHIX-26vrJ4jqiZPZd:b-8szhng) ([raw file](https://github.com/dgraph-io/dgraph/blob/159ed5d15d92ef16e61c2f97ab17a063e898ef64/query/groupby.go#L320)):*
> ```Go
> 
> 			// Currently vars are supported only at the root.
> 			// for eg, The following query will result into error:-
> ```

Add a detailed comment about why is this behavior not allowed. 
___
*[query/query0_test.go, line 1480 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-MZHIyN154gquKPygVtv:-MZHIyN154gquKPygVtw:bwe3p3t) ([raw file](https://github.com/dgraph-io/dgraph/blob/159ed5d15d92ef16e61c2f97ab17a063e898ef64/query/query0_test.go#L1480)):*
> ```Go
> 			c as count(uid)
> 		}
> 		me(func: uid(c)) {
> ```

Add an example of doing a filter based on `val(c)` as well. Also check with Anand and see if we are satisfying the requirements of the customers that the request came from.

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7746)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @pawanrawal)

___
*[query/groupby.go, line 320 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-MZHIX-13UR77FSrizt1:-MZQx7RxDQnXkzk9aG__:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/159ed5d15d92ef16e61c2f97ab17a063e898ef64/query/groupby.go#L320)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a detailed comment about why is this behavior not allowed. 
</blockquote></details>

Done.
___
*[query/query0_test.go, line 1480 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-MZHIyN154gquKPygVtv:-MZQx6Dw4kn-z8K1vXSo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/159ed5d15d92ef16e61c2f97ab17a063e898ef64/query/query0_test.go#L1480)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add an example of doing a filter based on `val(c)` as well. Also check with Anand and see if we are satisfying the requirements of the customers that the request came from.
</blockquote></details>

Done.

**Review by pawanrawal — APPROVED** [review]
Should be creating a doc ticket for this as well. 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-:-MZVs_UY2ExKd3NM_cAY:b-uaiwbm)* status: all files reviewed, 1 unresolved discussion (waiting on @minhaj-shakeel)

___
*[query/groupby.go, line 388 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-MZVsFiSAY783LuaYUua:-MZVsFiSAY783LuaYUub:b-g5l8ir) ([raw file](https://github.com/dgraph-io/dgraph/blob/649823894afc3ad1a618bde48a998a365318f924/query/groupby.go#L388)):*
> ```Go
> 				// uid -> count of duplicates. for eg if there are two predicates(u & v) and
> 				// the groupby uids for (u1, v1) pair are (uid1, uid2, uid3) then the variable
> 				// stores (uid1, 3), (uid2, 3) & (uid2, 2) map.
> ```

Maybe a bigger example with something like name and friend would help here.

**Review by minhaj-shakeel — COMMENTED** [review]
Created the ticket.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-:-MZW1A2CApjWxyyJ6ozw:bkzpq46)* status: all files reviewed, 1 unresolved discussion (waiting on @pawanrawal)

___
*[query/groupby.go, line 388 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7746#-MZVsFiSAY783LuaYUua:-MZW17NW52cEGLsfGjxE:b-pfkk3b) ([raw file](https://github.com/dgraph-io/dgraph/blob/649823894afc3ad1a618bde48a998a365318f924/query/groupby.go#L388)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Maybe a bigger example with something like name and friend would help here.
</blockquote></details>

Adding it.

**Comment by benwoodward** [comment]
can this be put into the next release please?

I have a query that doesn't work (using 21.03):

```
  queryDistinctLexicalEntryHeadwords(lexicon: String!, first: Int, offset: Int): GroupedPropertyMap
    @custom(
      dql: """
      query q($lexicon: string, $first: int, $offset: int = 0) {
        var(func: type(Lexicon), first: $first, offset: $offset) @filter(eq(Lexicon.language, $lexicon)) {
          Lexicon.lexicalEntries {
            LE as uid
          }
        }
        queryDistinctLexicalEntryHeadwords(func: uid(LE)) @groupby(headword: LexicalEntry.headword, count) {
          count(uid)
        }
      }
      """
    )

  # this is not possible in 21.03, but fix has been merged into master:
  # https://github.com/dgraph-io/dgraph/pull/7746
  #
  # queryDistinctLexicalEntryHeadwordsMetadata(lexicon: String!, first: Int, offset: Int): Metadata
  #   @custom(
  #     dql: """
  #     query q($lexicon: string, $first: int, $offset: int) {
  #       var(func: type(Lexicon), first: $first, offset: $offset) @filter(eq(Lexicon.language, $lexicon)) {
  #         Lexicon.lexicalEntries {
  #           LE as count(uid)
  #         }
  #       }
  #       queryDistinctLexicalEntryHeadwordsMetadata() @normalize {
  #         totalCount: sum(val(LE))
  #       }
  #     }
  #     """
  #   )
```

the commented query gives me the following error:

`Vars can be assigned only when grouped by UID attribute while executing this query`

relevant: https://discuss.dgraph.io/t/vars-can-be-assigned-only-when-grouped-by-uid-attribute/16996/2

**Pull request merged**
