### PR TITLE
Add snapshot and checkpoint

### PR DESCRIPTION
**Pull request by jchiu0**
Checkpoint is new: it is not found in RocksDB C API or gorocksdb.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/216)

### CODE REVIEW

**Comment by jchiu0** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[rdb/checkpoint.go, line 18 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-KRff63wDG_-wdPy6Tuu-r1-18:-KS-PRJGa4TzbFXZZl2b:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/42b0f51f4e8894c119fc18f9e58a40bbfdc7e9d3/rdb/checkpoint.go#L18)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported method Checkpoint.Destroy should be of the form "Destroy ..."
</details>
Done.

---

*[store/store.go, line 114 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-KS-Ok4Muhi3sXOT8DbZ-r3-114:-KS-PLfHrctkiBlBDYh9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c72bf0710d3c038b92be48611a47e05df5bdec4e/store/store.go#L114)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Store.Close should have comment or be unexported
</details>
Done.

---

*[store/store.go, line 112 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-KS-Ok4Muhi3sXOT8DbZ-r5-112:-KS-PL69Ja9ANnOG365P:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/1d11db07905d0e007b4a62266fa39a6f68cc791f/store/store.go#L112)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported method Store.MemtableSize should be of the form "MemtableSize ..."
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/216)*

**Comment by jchiu0** [comment]
Updated the API. Added some tests to illustrate how to use snapshots and checkpoints. Please see store_test.go.

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-:-KS1QVFA9CgJGI7JquOL:blmkshc)*

**Comment by manishrjain** [comment]
:lgtm: Haven't looked too deep, hope there are no memory leaks.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 1 of 2 files at r5, 2 of 4 files at r6, 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[rdb/snapshot.go, line 15 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-KRfstHbAiSAuCD9_FIR:-KRfstHbAiSAuCD9_FIS:buggqk4) ([raw file](https://github.com/dgraph-io/dgraph/blob/4512cafb5152c4c15914ace031c3682796ef2b03/rdb/snapshot.go#L15)):*
> ```Go
> 
> // NewNativeSnapshot creates a Snapshot object.
> func NewNativeSnapshot(c *C.rdb_snapshot_t, cDb *C.rdb_t) *Snapshot {
> ```

Does Snapshot have any APIs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-:-KRfszUaR4dpUgiNKNAF:b5e2t94)*

**Comment by jchiu0** [comment]
All the memory that is allocated is wrapped by Go objects, e.g., Snapshot, Checkpoint. The user is responsible for calling Close/Destroy/Release methods of these Go objects unless we want to use runtime.SetFinalizer. Right now, we don't use runtime.SetFinalizer for such wrapped C objects and I think we should be consistent about it.

Thanks for the review.

---

Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[rdb/snapshot.go, line 15 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-KRfstHbAiSAuCD9_FIR:-KS1W0YgIeNPRjFOR79q:b-dbpoxl) ([raw file](https://github.com/dgraph-io/dgraph/blob/4512cafb5152c4c15914ace031c3682796ef2b03/rdb/snapshot.go#L15)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Does Snapshot have any APIs?
</details>
The snapshot API is very small: https://github.com/facebook/rocksdb/blob/522de4f59e6314698286cf29d8a325a284d81778/include/rocksdb/snapshot.h

The checkpoint API is also very small: https://github.com/facebook/rocksdb/blob/56887f6cb854fde8e16c1ca65533716976c2e2f3/utilities/checkpoint/checkpoint.cc

I think I have exposed all the major functions. store_test.go also illustrates that we have all we need to save and restore the database using either snapshots or checkpoints.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/216#-:-KS1XbwfPfrYAqomX3f9:b-w7uufy)*

**Pull request closed without merging**
