### PR TITLE
feat(GraphQL): Validate audience in authorization JWT and change `Dgraph.Authorization` format.

### PR DESCRIPTION
**Pull request by arijitAD**
Fixes GRAPHQL-565
1. Upgrades `jwt-go` to v4 to support multiple aud claims in JWT #5750 
2. Makes JWT token expiry field option in GraphQL.
3. Changes `Dgraph.Authorization` format.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/5927)

 
 

Docs Preview: [Dgraph Preview](https://dgraph-80084c8d8a-79233.surge.sh)

### CODE REVIEW

**Comment by arijitAD** [comment]
@dpeek Can you sign CLA so that we can merge this PR.

**Comment by dpeek** [comment]
Hi @pawanrawal, sorry for radio silence – things got busy at work! I though I had signed the CLA already, but signed again. Still says pending though?

**Comment by parasssh** [comment]
> Hi @pawanrawal, sorry for radio silence – things got busy at work! I though I had signed the CLA already, but signed again. Still says pending though?

Yes, it shows pending without which we cannot merge.

**Comment by dpeek** [comment]
Seems like it picked it up now, had to ask it to recheck :)

**Pull request merged**
