### PR TITLE
Integrate sentry for dashboard and return 400 status code in case of errors.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/920)

### CODE REVIEW

**Comment by ashwin95r** [comment]
LG to return a 404 status in the header of the response.

:lgtm: 

---

Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/920#-:-KjuMvGlN7xW6ug9a29X:b2ijfy2)*

**Comment by sungwoncho** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 494 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/920#-KkOraUsAReEQWX-G_Cx:-KkOraUtdvr70AsgXVMt:bkab4py) ([raw file](https://github.com/dgraph-io/dgraph/blob/2632b7c486e519228498fc357c87f2afa2034316/cmd/dgraph/main.go#L494)):*
> ```Go
> 	if r.Method != "POST" {
> 		x.SetStatus(w, x.ErrorInvalidMethod, "Invalid method")
> 		w.WriteHeader(http.StatusBadRequest)
> ```

405 Method Not Allowed? https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

---

*[dashboard/src/actions/index.js, line 168 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/920#-KkOsRfJDhDnCVzHd-P3:-KkOsRfJDhDnCVzHd-P4:bnmva3z) ([raw file](https://github.com/dgraph-io/dgraph/blob/2632b7c486e519228498fc357c87f2afa2034316/dashboard/src/actions/index.js#L168)):*
> ```JavaScript
>                 });
>             } else {
>                 Raven.captureException(error);
> ```

I think `error.response` is null only if there is `404 Not Found`. https://github.com/dgraph-io/dgraph/blob/master/dashboard/src/containers/Helpers.js#L9-L11

Hence this block will only trigger on 404. But we want to catch StatusBadRequest (400) from the server.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/920)*

**Comment by sungwoncho** [comment]
:lgtm:

---

Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[dashboard/src/actions/index.js, line 168 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/920#-KkOsRfJDhDnCVzHd-P3:-KkOzIKj-NmRC83yJuZS:b9m5b7b) ([raw file](https://github.com/dgraph-io/dgraph/blob/2632b7c486e519228498fc357c87f2afa2034316/dashboard/src/actions/index.js#L168)):*
<details><summary><i>Previously, sungwoncho (Sung Won Cho) wrote…</i></summary><blockquote>

I think `error.response` is null only if there is `404 Not Found`. https://github.com/dgraph-io/dgraph/blob/master/dashboard/src/containers/Helpers.js#L9-L11

Hence this block will only trigger on 404. But we want to catch StatusBadRequest (400) from the server.
</blockquote></details>

actually scratch that, we want to catch js runtime error not query execution error from the server

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/920#-:-KkOzG9aaNihx3ezin9b:bnfp4nl)*

**Comment by pawanrawal** [comment]
merged

**Pull request closed without merging**
