### PR TITLE
Add all missing dependencies to govendor.

### PR DESCRIPTION
**Pull request by martinmr**
This PR makes it easier to build the 1.0 releases by adding missing
dependencies via govendor.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4251)

### CODE REVIEW

**Comment by danielmai** [comment]
I thought this was done before in release/v1.0, but I guess it hasn't. Thanks for doing this @martinmr.

Can you make sure that there are no externally referenced dependencies? When I checked `govendor list` I found three:

```
$ govendor list | awk '$1 ~ "e"'
 e  github.com/dgraph-io/dgo/x                                                 
 e  github.com/hashicorp/golang-lru/simplelru                                  
 e  go.opencensus.io/metric/metricexport    
```

**Comment by martinmr** [comment]
Only the first one showed up as external in my machine but just in case I added the three libraries.

**Comment by martinmr** [comment]
I removed the `dgo/x` package because it breaks the build.

**Comment by danielmai** [comment]
This is the build error:
```
[Step 3/6] INFO: Running test for github.com/dgraph-io/dgraph/contrib/integration/acctupsert
[20:44:51][Step 3/6] # github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/dgo/x
[20:44:51][Step 3/6] vendor/github.com/dgraph-io/dgo/x/error.go:28:21: undefined: errors.WithStack
```

To fix it, we should upgrade pkg/errors to v0.8.1. v0.8.0 introduced errors.WithStack.

```
govendor fetch github.com/pkg/errors/...@v0.8.1
```

**Comment by danielmai** [comment]
pkg/errors release notes: https://github.com/pkg/errors/releases

**Pull request merged**
