### PR TITLE
Fix normalize

### PR DESCRIPTION
**Pull request by pawanrawal**
Earlier, normalize used to return all path to leaf nodes. Now it returns all unique results for a subgraph.

For the query
```
{
  director(id: [m.06pj8, 0xc32fe17c28cb528c]) @normalize {
    d: name@en
    director.film (first: 2) @filter(gt(count(country), 2)) {
      film: name@en
      starring (first: 2) {
        performance.actor {
          pa: name@en
        }
        performance.character {
          pc: name@en
        }
      }
      country {
        c : name@en
      }
    }
  }
}
```

The response now is

```
{
    "director": [
        {
            "c": "United States of America",
            "d": "Steven Spielberg",
            "film": "Munich",
            "pa": "Geoffrey Rush",
            "pc": "Ephraim"
        },
        {
            "c": "Canada",
            "d": "Steven Spielberg",
            "film": "Munich",
            "pa": "Geoffrey Rush",
            "pc": "Ephraim"
        },
        {
            "c": "France",
            "d": "Steven Spielberg",
            "film": "Munich",
            "pa": "Geoffrey Rush",
            "pc": "Ephraim"
        },
        {
            "c": "United States of America",
            "d": "Steven Spielberg",
            "film": "Munich",
            "pa": "Valeria Bruni Tedeschi",
            "pc": "Sylvie"
        },
        {
            "c": "Canada",
            "d": "Steven Spielberg",
            "film": "Munich",
            "pa": "Valeria Bruni Tedeschi",
            "pc": "Sylvie"
        },
        {
            "c": "France",
            "d": "Steven Spielberg",
            "film": "Munich",
            "pa": "Valeria Bruni Tedeschi",
            "pc": "Sylvie"
        },
        {
            "c": "India",
            "d": "Steven Spielberg",
            "film": "War Horse",
            "pa": "Patrick Kennedy",
            "pc": "Lt. Charlie Waverly"
        },
        {
            "c": "United States of America",
            "d": "Steven Spielberg",
            "film": "War Horse",
            "pa": "Patrick Kennedy",
            "pc": "Lt. Charlie Waverly"
        },
        {
            "c": "United Kingdom",
            "d": "Steven Spielberg",
            "film": "War Horse",
            "pa": "Patrick Kennedy",
            "pc": "Lt. Charlie Waverly"
        },
        {
            "c": "India",
            "d": "Steven Spielberg",
            "film": "War Horse",
            "pa": "Chris Bowe",
            "pc": "Scottish Highlander at Auction #1"
        },
        {
            "c": "United States of America",
            "d": "Steven Spielberg",
            "film": "War Horse",
            "pa": "Chris Bowe",
            "pc": "Scottish Highlander at Auction #1"
        },
        {
            "c": "United Kingdom",
            "d": "Steven Spielberg",
            "film": "War Horse",
            "pa": "Chris Bowe",
            "pc": "Scottish Highlander at Auction #1"
        },
        {
            "c": "United States of America",
            "d": "Martin Scorsese",
            "film": "No Direction Home"
        },
        {
            "c": "United Kingdom",
            "d": "Martin Scorsese",
            "film": "No Direction Home"
        },
        {
            "c": "Japan",
            "d": "Martin Scorsese",
            "film": "No Direction Home"
        }
    ]
}
```

Response before this change
```
{
    "director": [
        {
            "d@en": "Steven Spielberg",
            "film@en": "Munich",
            "pa@en": "Geoffrey Rush"
        },
        {
            "d@en": "Steven Spielberg",
            "film@en": "Munich",
            "pc@en": "Ephraim"
        },
        {
            "d@en": "Steven Spielberg",
            "film@en": "Munich",
            "pa@en": "Valeria Bruni Tedeschi"
        },
        {
            "d@en": "Steven Spielberg",
            "film@en": "Munich",
            "pc@en": "Sylvie"
        },
        {
            "c@en": "United States of America",
            "d@en": "Steven Spielberg",
            "film@en": "Munich"
        },
        {
            "c@en": "Canada",
            "d@en": "Steven Spielberg",
            "film@en": "Munich"
        },
        {
            "c@en": "France",
            "d@en": "Steven Spielberg",
            "film@en": "Munich"
        },
        {
            "d@en": "Steven Spielberg",
            "film@en": "War Horse",
            "pc@en": "Lt. Charlie Waverly"
        },
        {
            "d@en": "Steven Spielberg",
            "film@en": "War Horse",
            "pa@en": "Patrick Kennedy"
        },
        {
            "d@en": "Steven Spielberg",
            "film@en": "War Horse",
            "pa@en": "Chris Bowe"
        },
        {
            "d@en": "Steven Spielberg",
            "film@en": "War Horse",
            "pc@en": "Scottish Highlander at Auction #1"
        },
        {
            "c@en": "India",
            "d@en": "Steven Spielberg",
            "film@en": "War Horse"
        },
        {
            "c@en": "United States of America",
            "d@en": "Steven Spielberg",
            "film@en": "War Horse"
        },
        {
            "c@en": "United Kingdom",
            "d@en": "Steven Spielberg",
            "film@en": "War Horse"
        },
        {
            "c@en": "United States of America",
            "d@en": "Martin Scorsese",
            "film@en": "No Direction Home"
        },
        {
            "c@en": "United Kingdom",
            "d@en": "Martin Scorsese",
            "film@en": "No Direction Home"
        },
        {
            "c@en": "Japan",
            "d@en": "Martin Scorsese",
            "film@en": "No Direction Home"
        }
    ]
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/873)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 406 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/873#-KiVfyCW2q2biO6dm7Ee:-KiVfyCW2q2biO6dm7Ef:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ca76aa02599768b947f62b2b21323228c16952a/query/outputnode.go#L406)):*
> ```Go
> }
> 
> func merge(parent []map[string]*fastJsonAttr, child []map[string]*fastJsonAttr) []map[string]*fastJsonAttr {
> ```

100 chars

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/873#-:-KiVfjnjE-BTuWrcfhcL:bnfp4nl)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 423 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/873#-KiXNTIuxf8vIqH65o2U:-KiXNTIuxf8vIqH65o2V:bya1blr) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ca76aa02599768b947f62b2b21323228c16952a/query/outputnode.go#L423)):*
> ```Go
> 				mergeMap[k] = v
> 			}
> 			// Add the
> ```

Fix comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/873#-:-KiXW4R4enEh8k-GDepr:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 406 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/873#-KiVfyCW2q2biO6dm7Ee:-KiXkOiv_UCvA--kPLMj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ca76aa02599768b947f62b2b21323228c16952a/query/outputnode.go#L406)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done.

---

*[query/outputnode.go, line 423 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/873#-KiXNTIuxf8vIqH65o2U:-KiXkOR13ffLRFy2_8l6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4ca76aa02599768b947f62b2b21323228c16952a/query/outputnode.go#L423)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Fix comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/873)*

**Comment by pawanrawal** [comment]
Merged to master

**Pull request closed without merging**
