### PR TITLE
feat(multi-tenancy): Add mutation for guardian of galaxy to reset password of users of any namespaces

### PR DESCRIPTION
**Pull request by ahsanbarkati**
This PR adds a new mutation which can be used by the guardians of the galaxy
to reset passwords of any user belonging to any namespace.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7418)

### CODE REVIEW

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7418)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @ahsanbarkati, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 112 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC9GfT2G3CHIcDyuV8:-MTC9GfU0u9t2cfi5Yd5:b-o9exze) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L112)):*
> ```
> ResetPassword
> ```
since this is an enterprise only feature, shouldn't we add it separately in `access.go` and `access_ee.go`?
same for `CreateNamespace` and `DeleteNamespace` too.
___
*[edgraph/server.go, line 119 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC6RnVBt_THjjmvJ4z:-MTC6RnVBt_THjjmvJ5-:b-ax35x7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L119)):*
> ```
> x as updateUser(func: type(dgraph.type.User)) @filter(eq(dgraph.xid, "%s"))
> ```
we should put `eq` as root func and `type` as filter, that is a bit performant query.
___
*[edgraph/server.go, line 144 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC8Hbq675aCSlVMp7R:-MTC8Hbq675aCSlVMp7S:bud4d39) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L144)):*
> ```
> 	ctx = x.AttachNamespace(ctx, ns)
> 	resp, err := (&Server{}).doQuery(ctx, req)
> ```
nice! so this is the way to bypass that namespace addition from JWT, directly use doQuery().
We have two options now :)
___
*[edgraph/server.go, line 146 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC8naJ3hJv-j0ZesZT:-MTC8naJ3hJv-j0ZesZU:b-t4hej5) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L146)):*
> ```
> return errors.Wrapf(err, "while upserting user with id %s", x.GrootId)
> ```
should it be 
```
errors.Wrapf(err, "while resetting password for user with id %s", id)
```
___
*[graphql/admin/admin.go, line 574 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC1KsO6MExjuYPPkkL:-MTC1KsO6MExjuYPPkkM:b-ncamy1) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/admin.go#L574)):*
> ```Go
> 		"export":          resolveExport,
> 		"login":           resolveLogin,
> 		"resetPassword":   resolveResetPassword,
> ```

need to also add the middleware configuration for this, IP and logging middleware should be the required ones, for guardian auth, maybe we will need to create a new middleware, but that we can look later.
___
*[graphql/admin/endpoints_ee.go, line 492 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC1ANy7GVghcaMr9aI:-MTC1ANz0eQzyObVVUgb:bek9nba) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/endpoints_ee.go#L492)):*
> ```
> resetPassword(userId: String, password: String, namespace: Int)
> ```
should each of these parameters be a required parameter?
also let's continue the convention of having only one parameter for the mutation which should be named `input` and that parameter should wrap these 3.

`login`  is the only exception to this rule ATM because of legacy issues but we should follow this convention.
From this, now I think we should also change the `deleteNamespace` signature as well as per the convention.
___
*[graphql/admin/reset_password.go, line 37 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC2KcA6rcuiqgSw1qf:-MTC2KcA6rcuiqgSw1qg:bxwkcl7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/reset_password.go#L37)):*
> ```
> glog.Info("Got reset password request")
> ```
lets remove this because we will anyways add the logging middleware
___
*[graphql/admin/reset_password.go, line 40 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC2ZCWC8aJbwyxgAm9:-MTC2ZCWC8aJbwyxgAmA:b1prfdj) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/reset_password.go#L40)):*
> ```
> err := (&edgraph.Server{}).ResetPassword(ctx, in.Namespace, in.UserID, in.Password)
> ```
should `ResetPassword` directly accept the `ResetPasswordInput` struct instead of passing the parameters one by one?

**Review by ahsanbarkati — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7418)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @ahsanbarkati, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 112 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC9GfT2G3CHIcDyuV8:-MTF2qBT-AJQkWva70G3:b-832nfs) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L112)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> ResetPassword
> ```
since this is an enterprise only feature, shouldn't we add it separately in `access.go` and `access_ee.go`?
same for `CreateNamespace` and `DeleteNamespace` too.
</blockquote></details>

I think `access.go` is primarily for ACLs, so I have created a separate file.
___
*[edgraph/server.go, line 119 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC6RnVBt_THjjmvJ4z:-MTF30lM9BZNe-jU9kbQ:b-enicfl) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L119)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> x as updateUser(func: type(dgraph.type.User)) @filter(eq(dgraph.xid, "%s"))
> ```
we should put `eq` as root func and `type` as filter, that is a bit performant query.
</blockquote></details>

Nice. Thanks. 
___
*[edgraph/server.go, line 144 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC8Hbq675aCSlVMp7R:-MTF34ow4Pl3p4eHSuHC:b-7xteif) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L144)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	ctx = x.AttachNamespace(ctx, ns)
> 	resp, err := (&Server{}).doQuery(ctx, req)
> ```
nice! so this is the way to bypass that namespace addition from JWT, directly use doQuery().
We have two options now :)
</blockquote></details>

Yeah!
___
*[edgraph/server.go, line 146 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC8naJ3hJv-j0ZesZT:-MTF36RSD7xBK-NDYME2:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/edgraph/server.go#L146)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> return errors.Wrapf(err, "while upserting user with id %s", x.GrootId)
> ```
should it be 
```
errors.Wrapf(err, "while resetting password for user with id %s", id)
```
</blockquote></details>

Done
___
*[graphql/admin/admin.go, line 574 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC1KsO6MExjuYPPkkL:-MTF39I83jgB6TYKUaGS:b-i9dx6s) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/admin.go#L574)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

need to also add the middleware configuration for this, IP and logging middleware should be the required ones, for guardian auth, maybe we will need to create a new middleware, but that we can look later.
</blockquote></details>

It is already done in a PR by Naman.
___
*[graphql/admin/endpoints_ee.go, line 492 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC1ANy7GVghcaMr9aI:-MTF3G3D9ubPUsoGzo3s:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/endpoints_ee.go#L492)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> resetPassword(userId: String, password: String, namespace: Int)
> ```
should each of these parameters be a required parameter?
also let's continue the convention of having only one parameter for the mutation which should be named `input` and that parameter should wrap these 3.

`login`  is the only exception to this rule ATM because of legacy issues but we should follow this convention.
From this, now I think we should also change the `deleteNamespace` signature as well as per the convention.
</blockquote></details>

Done
___
*[graphql/admin/reset_password.go, line 37 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC2KcA6rcuiqgSw1qf:-MTF3HDh7Gcse5-ufVKo:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/reset_password.go#L37)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> glog.Info("Got reset password request")
> ```
lets remove this because we will anyways add the logging middleware
</blockquote></details>

Done

**Review by ahsanbarkati — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7418)* status: 0 of 9 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/admin/reset_password.go, line 40 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTC2ZCWC8aJbwyxgAm9:-MTF3SLvAGW9RHDNVuRX:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4c7d1a7520e12b97f12f14cb6b9094dc807102b/graphql/admin/reset_password.go#L40)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> err := (&edgraph.Server{}).ResetPassword(ctx, in.Namespace, in.UserID, in.Password)
> ```
should `ResetPassword` directly accept the `ResetPasswordInput` struct instead of passing the parameters one by one?
</blockquote></details>

Done

**Review by abhimanyusinghgaur — APPROVED** [review]
:lgtm:
just a minor comment

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-:-MTFESgh2kBaKLjfl32j:b-qf499i)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ahsanbarkati, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/multi_tenancy_ee.go, line 70 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7418#-MTFDX94DgY69AthW_s3:-MTFDX94DgY69AthW_s4:bltnlbv) ([raw file](https://github.com/dgraph-io/dgraph/blob/0638bb83ed94f47298bbfb7d9704bf211230c031/edgraph/multi_tenancy_ee.go#L70)):*
> ```
> errors.Wrapf(err, "Reset password for user %s got error", inp.Namespace)
> ```
errors.Wrapf(err, "Reset password for user %s in namespace %d, got error:", inp.UserID, inp.Namespace)

**Pull request merged**
