### PR TITLE
Retry snapshot retrieval indefinitely.

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2125)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: One comment.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/draft.go, line 678 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-L5HDEd-ZuBMHpcjDAyT:-L5HDEd-ZuBMHpcjDAyU:b-drf03j) ([raw file](https://github.com/dgraph-io/dgraph/blob/5895c5f33730a1bd5b82820e0b100a5f5fd9f850/worker/draft.go#L678)):*
> ```Go
> 			// Get snapshot before joining peers as it can take time to retrieve it and we dont
> 			// want the quorum to be inactive when it happens.
> ```

x.Printf("Retrieving snapshot")

Then go into the func explained below, so the func generates generic error messages.

---

*[worker/draft.go, line 679 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-L5HCnSrcgOMRMheZYP9:-L5HCnSrcgOMRMheZYPA:b-53b0e1) ([raw file](https://github.com/dgraph-io/dgraph/blob/5895c5f33730a1bd5b82820e0b100a5f5fd9f850/worker/draft.go#L679)):*
> ```Go
> 			// want the quorum to be inactive when it happens.
> 
> 			n.retrySnapshotRetrieval(time.Second)
> ```

Can instead create a function, which retries a given function indefinitely with a given pause duration.

`func retryIndefinitely(func fn(), pause time.Duration) { for ... fn(); }`

---

*[worker/draft.go, line 682 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-L5HDARWQLtu3atfl6fK:-L5HDARWQLtu3atfl6fL:b-mui81r) ([raw file](https://github.com/dgraph-io/dgraph/blob/5895c5f33730a1bd5b82820e0b100a5f5fd9f850/worker/draft.go#L682)):*
> ```Go
> 			// Retry joinPeers indefinitely.
> 			for {
> 				if err = n.joinPeers(); err == nil {
> ```

Use that func here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-:-L5HD74Uft962HCMv0eq:bpjwta0)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/draft.go, line 679 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-L5HCnSrcgOMRMheZYP9:-L5HDP6C4rXdqA0Kk95v:b-gox0gi) ([raw file](https://github.com/dgraph-io/dgraph/blob/5895c5f33730a1bd5b82820e0b100a5f5fd9f850/worker/draft.go#L679)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can instead create a function, which retries a given function indefinitely with a given pause duration.

`func retryIndefinitely(func fn(), pause time.Duration) { for ... fn(); }`
</blockquote></details>

retryUntilSuccess might be a better name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[worker/draft.go, line 678 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-L5HDEd-ZuBMHpcjDAyT:-L5HFp2tiF3FpkqT8fg0:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/5895c5f33730a1bd5b82820e0b100a5f5fd9f850/worker/draft.go#L678)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

x.Printf("Retrieving snapshot")

Then go into the func explained below, so the func generates generic error messages.
</blockquote></details>

Done

---

*[worker/draft.go, line 679 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-L5HCnSrcgOMRMheZYP9:-L5HFoBVd1J78CalXU4U:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/5895c5f33730a1bd5b82820e0b100a5f5fd9f850/worker/draft.go#L679)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

retryUntilSuccess might be a better name.
</blockquote></details>

Done

---

*[worker/draft.go, line 682 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125#-L5HDARWQLtu3atfl6fK:-L5HFmLduqml55kP8fxZ:b-fznogt) ([raw file](https://github.com/dgraph-io/dgraph/blob/5895c5f33730a1bd5b82820e0b100a5f5fd9f850/worker/draft.go#L682)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Use that func here as well.
</blockquote></details>

Good idea, done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2125)*

**Comment by pawanrawal** [comment]
In master as of aaa1d2fa317c6e31263f27c5b849db7f3153bc99.

**Pull request closed without merging**
