### PR TITLE
feature/regenindex

### PR DESCRIPTION
**Pull request by jchiu0**
Wanted to get some feedback on this, particularly about whether this should be run as a separate main when the dgraph main is not running, or as an endpoint in dgraph main. If we choose the latter, then we need to be more careful about incoming mutations during the index rebuild.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/436)

### CODE REVIEW

**Comment by manishrjain** [comment]
Okay. This is a simple but very expensive approach.

I thought a lot about various ways we could do this -- including storing index deltas generated from mutations (doesn't really help); or possibly making deltas part of the original mutations (not possible); or generating further RAFT mutations for indices from the original RAFT mutations (very hard to get right). So, I can't think of any good way to do this, which is also simple and just works.

I think doing this regeneration of the index is the simplest approach, even though it's going to make our server lame duck for some time. So, I think maybe that's what we should do. Provide a `/regenerate` endpoint, which would put our server into lame duck mode. But, even this approach isn't ideal. Because, given a node in a group, all the mutations in that group would stall until this server comes out of the lame duck mode.

The problem only happens when we restart a node or bring one from scratch. So, maybe we should just rebuild the index then. In draft.go, in func node.Run(), if firstRun -> we can do a rebuildIndex after that. Note that for rebuild index to succeed, the applied index should be at the same watermark as the max raft entry retrieved from WAL. Thus, we'll be able to pick up all applied mutations, when doing the aggressive evicts.

Note that all of this is unnecessary if there are no new RAFT entries after the RAFT snapshot. That means, that the server was able to push everything to rocksdb, without any issues. So, the condition you're looking for in node.Run() is: `if firstRun && len(rd.CommittedEntries) > 0`. Also, no need to run this for group id zero.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/index.go, line 381 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-K_SrOSX6LrnUiIKW06u:-K_SrOSX6LrnUiIKW06v:b-cegkdv) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ed7f8e1b3bf5cc697d49f50395242162d7b46f7/posting/index.go#L381)):*
> ```Go
> 
> 	// Force an aggressive evict. We need to prevent further commits...
> 	CommitLists(10)
> ```

If we do this blockingly via node.Run(), then we wouldn't need to worry about any mutations.

---

*[posting/index.go, line 392 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-K_TIqQsPRSQiLSn87iU:-K_TIqQsPRSQiLSn87iV:b-p9s0qr) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ed7f8e1b3bf5cc697d49f50395242162d7b46f7/posting/index.go#L392)):*
> ```Go
> 	defer idxIt.Close()
> 	for idxIt.Seek(prefix); idxIt.ValidForPrefix(prefix); idxIt.Next() {
> 		if err := pstore.Delete(idxIt.Key().Data()); err != nil {
> ```

use batch write here. Should we also do this for reverses?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-:-K_StIra7QSlVOZpF8ke:b-nuwmya)*

**Comment by manishrjain** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 535 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka51sRvVAwmGt-L9akH:-Ka51sRw1ZMLujcTe59k:bxk7yu2) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/cmd/dgraph/main.go#L535)):*
> ```Go
> 
> 	ip, _, err := net.SplitHostPort(r.RemoteAddr)
> 	if err != nil || !net.ParseIP(ip).IsLoopback() {
> ```

By now, this logic is repeated a bunch of times. So, maybe consolidate that into one function.

---

*[cmd/dgraph/main.go, line 688 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka53UHXimMfdagqufw-:-Ka53UHXimMfdagqufw0:bwx84y0) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/cmd/dgraph/main.go#L688)):*
> ```Go
> 	http.HandleFunc("/health", healthCheck)
> 	http.HandleFunc("/query", queryHandler)
> 	http.HandleFunc("/index", indexHandler)
> ```

/admin/index

---

*[posting/index.go, line 426 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka59aigdOrYxNQkC_W_:-Ka59aigdOrYxNQkC_Wa:b-g0llxc) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/posting/index.go#L426)):*
> ```Go
> 	defer it.Close()
> 	var pl types.PostingList
> 	ctx := context.Background()
> ```

This should ideally be coming from the function. So, the caller can pass it all the way down.

---

*[worker/draft.go, line 23 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka59rLR1g2dxM98Nd8W:-Ka59rLR1g2dxM98Nd8X:b-ko883u) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/draft.go#L23)):*
> ```Go
> 
> const (
> 	proposalNormal = 0
> ```

Probably better to have 3: proposalMutation, proposalConfChange, proposalReindex

---

*[worker/index.go, line 25 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DAzuotKd-_tlqRnr:-Ka5DAzuotKd-_tlqRns:bsgc4e9) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L25)):*
> ```Go
> 	x.AssertTrue(gid == proposal.RebuildIndex.GroupId)
> 
> 	x.Printf("Processing proposal to rebuild index: %v", proposal.RebuildIndex)
> ```

x.Trace(ctx), where ctx = passed to rebuildIndex(ctx, ..)

---

*[worker/index.go, line 35 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5AJufm-eojO-RLVyE:-Ka5AJugAkZHf4yjQWxS:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L35)):*
> ```Go
> 	// Wait for syncing to data store.
> 	for n.applied.WaitingFor() {
> 		// watermark: add function waitingfor that returns an index that it is waiting for, and if it is zero, we can skip the wait
> ```

100 chars.

---

*[worker/index.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DCwPgiFdkzKEkEcg:-Ka5DCwPgiFdkzKEkEch:b-pvka0e) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L37)):*
> ```Go
> 		// watermark: add function waitingfor that returns an index that it is waiting for, and if it is zero, we can skip the wait
> 		doneUntil := n.applied.DoneUntil() // applied until.
> 		x.Printf("RebuildIndex waiting, appliedUntil:%d lastIndex: %d", doneUntil, lastIndex)
> ```

x.Trace(ctx ..)

---

*[worker/index.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DO6dRHAGepAJ9CHw:-Ka5DO6dRHAGepAJ9CHx:b-7iqnq8) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L51)):*
> ```Go
> 	for w.WaitingFor() {
> 		doneUntil := w.DoneUntil() // synced until.
> 		x.Printf("RebuildIndex waiting, syncedUntil:%d lastIndex:%d", doneUntil, lastIndex)
> ```

trace

---

*[worker/index.go, line 61 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DfHr_QGBi8uY9oOx:-Ka5DfHr_QGBi8uY9oOy:bekmloa) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L61)):*
> ```Go
> 	for _, attr := range proposal.RebuildIndex.Attrs {
> 		x.AssertTrue(group.BelongsTo(attr) == gid)
> 		if err = posting.RebuildIndex(attr); err != nil {
> ```

RebuildIndex(ctx, ..)

---

*[worker/index.go, line 121 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5ES_BFmk3gFbvUWR3:-Ka5ES_BFmk3gFbvUWR4:b-996k4b) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L121)):*
> ```Go
> 	n := groups().Node(gid)
> 
> 	if !req.DoBroadcast {
> ```

Why broadcast this?

---

*[worker/index.go, line 134 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5EHTxEQluLm0niSyC:-Ka5EHTyqi9SR5Jba6sH:b-1oc8b1) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L134)):*
> ```Go
> 
> 	// Send jobs to other machines in the group.
> 	for _, addr := range addrs {
> ```

Not sure what you're doing here.

---

*[worker/index.go, line 190 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5EY62Zx2KQRFX08al:-Ka5EY62Zx2KQRFX08am:b-t9an5c) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L190)):*
> ```Go
> }
> 
> func RebuildIndexOverNetwork(ctx context.Context, attrs []string) error {
> ```

To keep things simple, just do one attribute per such request.

---

*[worker/index.go, line 218 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5G74Epml8DQ-GOefz:-Ka5G74FR2tMsEzCveHr:b-c04qm) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L218)):*
> ```Go
> 		}
> 		numJobs++
> 		go func(gid uint32, a []string) {
> ```

all this logic seems complicated and verbose. Because we made it part of the RAFT instructions, this needs to be run like a query or a mutation, not a backup. Look at worker.ProcessTaskOverNetwork to see how to send this to any node in the group.

---

*[worker/payload.proto, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5GmdTA1uShD7qviFy:-Ka5GmdUwWH5EWeczGxL:bwcwy3q) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/payload.proto#L33)):*
> ```protobuf
> 	
> 	// If true, we need to broadcast to other addresses.
> 	bool do_broadcast = 2;
> ```

Still not sure what this is doing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436)*

**Comment by jchiu0** [comment]
Review status: 3 of 12 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 535 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka51sRvVAwmGt-L9akH:-Ka6B6pcdejHgMGUSROp:b-32mtmz) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/cmd/dgraph/main.go#L535)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

By now, this logic is repeated a bunch of times. So, maybe consolidate that into one function.
</blockquote></details>

Let me do that in a follow-up PR. Adding a task in Asana.

---

*[cmd/dgraph/main.go, line 688 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka53UHXimMfdagqufw-:-Ka5o0Vq4C2n54ISnnya:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/cmd/dgraph/main.go#L688)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

/admin/index
</blockquote></details>

Done.

---

*[posting/index.go, line 426 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka59aigdOrYxNQkC_W_:-Ka6B57nl5bhPuZh4Ewi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/posting/index.go#L426)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should ideally be coming from the function. So, the caller can pass it all the way down.
</blockquote></details>

Done.

---

*[worker/draft.go, line 23 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka59rLR1g2dxM98Nd8W:-Ka69KSSVJOe4NpZvV7P:b-cp8blr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/draft.go#L23)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Probably better to have 3: proposalMutation, proposalConfChange, proposalReindex
</blockquote></details>


Renamed to proposalMutation and proposalReindex. (proposalConfChange is not really needed now.)

---

*[worker/index.go, line 25 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DAzuotKd-_tlqRnr:-Ka68jElJo83AJqaG-mu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L25)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

x.Trace(ctx), where ctx = passed to rebuildIndex(ctx, ..)
</blockquote></details>

Done.

---

*[worker/index.go, line 35 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5AJufm-eojO-RLVyE:-Ka68qKVpxq5Y5kzFequ:bsvvqp6) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Scratch remark deleted.

---

*[worker/index.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DCwPgiFdkzKEkEcg:-Ka690kKgbgz02DsQDCU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

x.Trace(ctx ..)
</blockquote></details>

Done.

---

*[worker/index.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DO6dRHAGepAJ9CHw:-Ka691Zx9ZDbH64Ub62c:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

trace
</blockquote></details>

Done.

---

*[worker/index.go, line 61 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5DfHr_QGBi8uY9oOx:-Ka68bJGbINhISoDojNe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L61)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

RebuildIndex(ctx, ..)
</blockquote></details>

Done.

---

*[worker/index.go, line 121 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5ES_BFmk3gFbvUWR3:-Ka68Zu4FEmhsHrXcXaI:b-8c6ifi) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L121)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why broadcast this?
</blockquote></details>

Sorry, please ignore.

---

*[worker/index.go, line 134 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5EHTxEQluLm0niSyC:-Ka68VGwHe1l0M3e5x3K:b2r2kej) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L134)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not sure what you're doing here.
</blockquote></details>

Please ignore.

---

*[worker/index.go, line 190 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5EY62Zx2KQRFX08al:-Ka68M6fhsYVSwQ8NmqW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L190)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

To keep things simple, just do one attribute per such request.
</blockquote></details>

Done.

---

*[worker/index.go, line 218 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5G74Epml8DQ-GOefz:-Ka68MzxcXNCp-zylAcO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/index.go#L218)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

all this logic seems complicated and verbose. Because we made it part of the RAFT instructions, this needs to be run like a query or a mutation, not a backup. Look at worker.ProcessTaskOverNetwork to see how to send this to any node in the group.
</blockquote></details>

Done.

---

*[worker/payload.proto, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka5GmdTA1uShD7qviFy:-Ka68O5h78gKRGExl6Zt:b141y0k) ([raw file](https://github.com/dgraph-io/dgraph/blob/a19ed6023c4df1effd1b00b779079009b1eea6ce/worker/payload.proto#L33)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Still not sure what this is doing.
</blockquote></details>

Please pardon me. I was thinking that we need to broadcast to every machine in the group.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436)*

**Comment by manishrjain** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/dgraph/main.go, line 542 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6Qescp0BX4tMbt-xH:-Ka6Qescp0BX4tMbt-xI:bog2z5e) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/cmd/dgraph/main.go#L542)):*
> ```Go
> 
> 	ctx := context.Background()
> 	err = worker.RebuildIndexOverNetwork(ctx, r.URL.Query().Get("attr"))
> ```

Check somewhere that the attr has some value.

---

*[posting/index.go, line 386 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6R-rDZgGpPFbwOSDL:-Ka6R-rDZgGpPFbwOSDM:b-29icnc) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/posting/index.go#L386)):*
> ```Go
> 
> 	// Force an aggressive evict. We need to prevent further commits...
> 	CommitLists(10)
> ```

Again? We already did this from the caller function right?

---

*[worker/index.go, line 78 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6Pwo00MsvnP-EcwJm:-Ka6Pwo00MsvnP-EcwJn:bq1vyi9) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/worker/index.go#L78)):*
> ```Go
> }
> 
> func processRebuildIndex(ctx context.Context, ri *task.RebuildIndex) error {
> ```

proposeRebuildIndex(..)

---

*[worker/index.go, line 91 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6PoTF2uAOckl9aQbt:-Ka6PoTF2uAOckl9aQbu:b-ye0lab) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/worker/index.go#L91)):*
> ```Go
> // it will rebuild index. Otherwise, it will send a request to a server that
> // serves the attr.
> func RebuildIndexOverNetwork(ctx context.Context, attr string) error {
> ```

Where do you check if you got any value for attr? It might be len zero right?

---

*[x/watermark.go, line 133 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6TKwReO6OJbicylro:-Ka6TKwReO6OJbicylrp:buaeueg) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/x/watermark.go#L133)):*
> ```Go
> 		}
> 		// indices is now empty. Update waitingFor.
> 		atomic.StoreUint32(&w.waitingFor, 0)
> ```

This isn't right. This can break even if len(..) != 0. Look at the done := pending(..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436)*

**Comment by manishrjain** [comment]
:lgtm: Address the comments and feel free to submit.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[posting/index.go, line 427 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6Vk30ansQbKhGMjMQ:-Ka6Vk30ansQbKhGMjMR:bbotqe1) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/posting/index.go#L427)):*
> ```Go
> 	var pl types.PostingList
> 	for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
> 		pki := x.Parse(it.Key().Data())
> ```

Maybe do a check here that it is just the data, and nothing else. No index key etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-:-Ka6X3QUKAVea_r7CgQA:b-5bd77u)*

**Comment by jchiu0** [comment]
Review status: 9 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/dgraph/main.go, line 542 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6Qescp0BX4tMbt-xH:-Ka6V-r477aGKf5Rrtlk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/cmd/dgraph/main.go#L542)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check somewhere that the attr has some value.
</blockquote></details>

Done.

---

*[posting/index.go, line 386 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6R-rDZgGpPFbwOSDL:-Ka6VK29ulF7Sjsob-OE:begqmmv) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/posting/index.go#L386)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Again? We already did this from the caller function right?
</blockquote></details>

Hmm.. I think it was needed earlier when we do it more like a backup instead of using RAFT. Deleted.

---

*[posting/index.go, line 427 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6Vk30ansQbKhGMjMQ:-Ka6Zugt-oIB9AI3fn0B:b-iqf8nn) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/posting/index.go#L427)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe do a check here that it is just the data, and nothing else. No index key etc.
</blockquote></details>

I think we can trust pk.Prefix. It might be clearer to rename that as pk.DataPrefix.

---

*[worker/index.go, line 78 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6Pwo00MsvnP-EcwJm:-Ka6VmH7mIN6GlgST7W9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/worker/index.go#L78)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

proposeRebuildIndex(..)
</blockquote></details>

Done.

---

*[worker/index.go, line 91 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6PoTF2uAOckl9aQbt:-Ka6WNni9Qraivj5Pnpu:b839amu) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/worker/index.go#L91)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Where do you check if you got any value for attr? It might be len zero right?
</blockquote></details>

Added a check for attr to be indexable.

---

*[x/watermark.go, line 133 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6TKwReO6OJbicylro:-Ka6Zc9tVpYfc7dMqKM1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/x/watermark.go#L133)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This isn't right. This can break even if len(..) != 0. Look at the done := pending(..)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 427 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6Vk30ansQbKhGMjMQ:-Ka6_qJIJ2sOmVZ6mdOl:b339mri) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/posting/index.go#L427)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

I think we can trust pk.Prefix. It might be clearer to rename that as pk.DataPrefix.
</blockquote></details>

Yes, it would be. I thought pk.Prefix is for all predicates.

---

*[worker/index.go, line 43 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-Ka6aB4qZ69JLLI72jCY:-Ka6aB4qZ69JLLI72jCZ:b-d1yaii) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c5ceda573cc6a8d74b22f1bb4481487a690b566/worker/index.go#L43)):*
> ```Go
> 
> 	// Aggressive evict.
> 	posting.CommitLists(10)
> ```

This is bad. You need to do aggressive evict here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/436#-:-Ka6cYpuYxdhH0z5We5d:bnfp4nl)*

**Pull request closed without merging**
