### PR TITLE
Feature/schema get

### PR DESCRIPTION
**Pull request by janardhan1993**
1. 
schema(pred : [name, initial_release_date, director.film]) {
type
index
tokenizer
reverse
} 
returns 
{"code":"Success","message":"Done","schema":[{"predicate":"name","type":"string","index":true,"tokenizer":["term"]},{"predicate":"initial_release_date","type":"date","index":true,"tokenizer":["date"]},{"predicate":"director.film","type":"uid","reverse":true}],"uids":null}

schema {
type
}

returns list of all predicates and corresponding type

2. Move schema fetch and all checks to the corresponding nodes where that predicate is served.(index check removed from query, check attribute is indexed or not on appropriate node in worker/index.go)

3. Convert to schema type in task.query

4. Fix Bug(Add index check for functions which are not at root, omit aggregate output on error)

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/696)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 664 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFmu3PaTHPbE6Yao8C:-KfFmu3PaTHPbE6Yao8D:b-2nq83o) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/cmd/dgraph/main.go#L664)):*
> ```Go
> }
> 
> func predicates(w http.ResponseWriter) []string {
> ```

No need to provide this.

---

*[cmd/dgraph/main.go, line 683 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFn9J__YpgpLI9UYWV:-KfFn9Ja5mVoHq7OdZWJ:b-bajkdm) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/cmd/dgraph/main.go#L683)):*
> ```Go
> 	addCorsHeaders(w)
> 	// TODO: Remove this code and replace this
> 	preds := predicates(w)
> ```

This doesn't need to be here. Remove retrieving predicates here. Only return keywords.

---

*[protos/taskp/task.proto, line 6 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFoIhogpqmQmSzgIq4:-KfFoIhogpqmQmSzgIq5:b-vx4z5j) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/protos/taskp/task.proto#L6)):*
> ```protobuf
> syntax = "proto3";
> import "github.com/dgraph-io/dgraph/protos/facetsp/facets.proto";
> import "github.com/dgraph-io/dgraph/protos/graphp/graphresponse.proto";
> ```

Assign a task for Ashish to try and move them to one dir.

---

*[protos/taskp/task.proto, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFpCVVp5L8j0xWKEHV:-KfFpCVVp5L8j0xWKEHW:b-uflak3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/protos/taskp/task.proto#L119)):*
> ```protobuf
> 	uint32 group_id = 1;
> 	repeated string predicates = 2;
> 	repeated string fields = 3; 
> ```

Add a comment about what the fields are.

---

*[query/query.go, line 386 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFqbu_1H6KSlGNzNZy:-KfFqbu_1H6KSlGNzNZz:bsvqrkr) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query.go#L386)):*
> ```Go
> 	}
> 	// creates appropriate type from binary format
> 	sv, err := types.Convert(v, v.Tid)
> ```

Should we assert that err == nil, if value is not empty.

---

*[query/query_test.go, line 187 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFqmNd4ePelQUFXd3L:-KfFqmNd4ePelQUFXd3M:b-hfpv23) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query_test.go#L187)):*
> ```Go
> 	err = types.Marshal(f1, &fData)
> 	require.NoError(t, err)
> 	//addEdgeToTypedValue(t, "survival_rate", 1, types.FloatID, fData.Value.([]byte), nil)
> ```

remove.

---

*[query/query_test.go, line 1034 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFqxUlr1HZNuAVg3U3:-KfFqxUlr1HZNuAVg3U4:b-4eptj8) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query_test.go#L1034)):*
> ```Go
> 	schema.State().SetType("survival_rate", types.Int32ID)
> 	js = processToFastJSON(t, query)
> 	schema.State().SetType("survival_rate", types.FloatID)
> ```

Move it after require.EquvalValues.

---

*[query/query_test.go, line 4018 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFrDDBJbgFLgeM2L26:-KfFrDDBJbgFLgeM2L27:bpey2qw) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query_test.go#L4018)):*
> ```Go
> 	actual := processSchemaQuery(t, query)
> 	expected := []*graphp.SchemaNode{
> 		{Predicate: "age", Type: "int"}}
> ```

Same line as above.

---

*[schema/schema.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFr_ImwrA3TNp8ONA_:-KfFr_ImwrA3TNp8ONAa:b-ympr3j) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/schema/schema.go#L256)):*
> ```Go
> }
> 
> func (s *stateShard) tokenizerNames(pred string) []string {
> ```

sg *stateGroup

---

*[worker/index.go, line 127 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFs250UxqQqigwjgtP:-KfFs251heJeOWl5UqUD:bqrjkj) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/index.go#L127)):*
> ```Go
> 
> 	c := workerp.NewWorkerClient(conn)
> 	_, err = c.RebuildIndex(ctx, &taskp.RebuildIndex{Attr: attr, GroupId: gid})
> ```

Ensure that RebuildIndex would check it.

---

*[worker/schema.go, line 125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFv5DStvvAYgudGodC:-KfFv5DStvvAYgudGodD:b-pgsai) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/schema.go#L125)):*
> ```Go
> // TODO: Janardhan - if read fails try other servers serving same group
> func getSchemaOverNetwork(ctx context.Context, gid uint32, s *taskp.Schema,
> 	results []*taskp.SchemaResult, idx int, che chan error) {
> ```

Just one arg chan resultErr to replace 3 args here.

---

*[worker/schema.go, line 156 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFvKW0Nsv7yJUFudOo:-KfFvKW0Nsv7yJUFudOp:b-793raz) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/schema.go#L156)):*
> ```Go
> 	errors := make(chan error, len(schemaMap))
> 	results := make([]*taskp.SchemaResult, len(schemaMap))
> 	i := 0
> ```

No need to do i.

---

*[worker/task.go, line 220 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFvldRnuXr0qIJQIZu:-KfFvldRnuXr0qIJQIZv:b-pthmse) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/task.go#L220)):*
> ```Go
> 		isValueEdge := err == nil
> 
> 		newValue := &taskp.Value{ValType: int32(val.Tid), Val: x.Nilbyte}
> ```

if isValueEdge {
  if typ, err := ..; err != nil {
  } else {
  }
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696)*

**Comment by janardhan1993** [comment]
Review status: 8 of 16 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 664 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFmu3PaTHPbE6Yao8C:-KfHeDvfGqEA4mJ4MLlU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/cmd/dgraph/main.go#L664)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to provide this.
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 683 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFn9J__YpgpLI9UYWV:-KfHeHHo0peE1TTLPap6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/cmd/dgraph/main.go#L683)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This doesn't need to be here. Remove retrieving predicates here. Only return keywords.
</blockquote></details>

Done.

---

*[protos/taskp/task.proto, line 6 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFoIhogpqmQmSzgIq4:-KfHeJlaYqP0rIppN4rB:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/protos/taskp/task.proto#L6)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Assign a task for Ashish to try and move them to one dir.
</blockquote></details>

Done.

---

*[protos/taskp/task.proto, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFpCVVp5L8j0xWKEHV:-KfHeLGxTwAxaNZ90Pqd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/protos/taskp/task.proto#L119)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment about what the fields are.
</blockquote></details>

Done.

---

*[query/query.go, line 386 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFqbu_1H6KSlGNzNZy:-KfHeNZD_9RJUhxzS9Sz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query.go#L386)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Should we assert that err == nil, if value is not empty.
</blockquote></details>

Done.

---

*[query/query_test.go, line 187 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFqmNd4ePelQUFXd3L:-KfHeOvGaQeefwvEa8hM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query_test.go#L187)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove.
</blockquote></details>

Done.

---

*[query/query_test.go, line 1034 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFqxUlr1HZNuAVg3U3:-KfHeQB5WLHBeirO3I0w:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query_test.go#L1034)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move it after require.EquvalValues.
</blockquote></details>

Done.

---

*[query/query_test.go, line 4018 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFrDDBJbgFLgeM2L26:-KfHeq8D4ES6yRWZTJ8U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/query/query_test.go#L4018)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Same line as above.
</blockquote></details>

Done.

---

*[schema/schema.go, line 256 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFr_ImwrA3TNp8ONA_:-KfHerWZf9_BbpaqDhZI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/schema/schema.go#L256)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

sg *stateGroup
</blockquote></details>

Done.

---

*[worker/index.go, line 127 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFs250UxqQqigwjgtP:-KfHes_EiZs6PEniLxii:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/index.go#L127)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Ensure that RebuildIndex would check it.
</blockquote></details>

Done.

---

*[worker/schema.go, line 125 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFv5DStvvAYgudGodC:-KfHeuBupOGt58-sx27W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/schema.go#L125)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just one arg chan resultErr to replace 3 args here.
</blockquote></details>

Done.

---

*[worker/schema.go, line 156 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFvKW0Nsv7yJUFudOo:-KfHevF3KYuV31kyXMqD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/schema.go#L156)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to do i.
</blockquote></details>

Done.

---

*[worker/task.go, line 220 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfFvldRnuXr0qIJQIZu:-KfHew7qw3fKDl9n4toL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c6197ffe3ed3655a6e666e331d1a1bf7da2e629e/worker/task.go#L220)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if isValueEdge {
  if typ, err := ..; err != nil {
  } else {
  }
}
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696)*

**Comment by ashwin95r** [comment]
Reviewed 8 of 16 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 3971 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfJFiYkriZcwKV13QeH:-KfJFiYkriZcwKV13QeI:baqeh9j) ([raw file](https://github.com/dgraph-io/dgraph/blob/98cef80b2365af7166d5e626ff348ca3a3c4b546/query/query_test.go#L3971)):*
> ```Go
> 	eq := reflect.DeepEqual(expected, actual)
> 	if !eq {
> 		fmt.Printf("Expected: %+v, Received: %+v \n", expected, actual)
> ```

Can be passed in `require.True` no need for this separate check.

---

*[worker/schema.go, line 60 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfJJHxfPkCU_gZUfBIE:-KfJJHxgNEHyZauwuuqz:b-z9zi59) ([raw file](https://github.com/dgraph-io/dgraph/blob/98cef80b2365af7166d5e626ff348ca3a3c4b546/worker/schema.go#L60)):*
> ```Go
> 			result.Schema = append(result.Schema, schemaNode)
> 		}
> ```

unnecessary vertical space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696)*

**Comment by janardhan1993** [comment]
Review status: 14 of 16 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 3971 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfJFiYkriZcwKV13QeH:-KfPF9Bsb741RgxFLQYF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/98cef80b2365af7166d5e626ff348ca3a3c4b546/query/query_test.go#L3971)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Can be passed in `require.True` no need for this separate check.
</blockquote></details>

Done.

---

*[worker/schema.go, line 60 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfJJHxfPkCU_gZUfBIE:-KfPF82uG8wSuDhc_kup:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/98cef80b2365af7166d5e626ff348ca3a3c4b546/worker/schema.go#L60)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

unnecessary vertical space.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 14 of 16 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 3971 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfJFiYkriZcwKV13QeH:-KfPOgr0C1oifSIkj0OC:b-brtskh) ([raw file](https://github.com/dgraph-io/dgraph/blob/98cef80b2365af7166d5e626ff348ca3a3c4b546/query/query_test.go#L3971)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We can still have the String argument as the 3rd argument.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-:-Kfd27qXn1t69qWSPtpC:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 14 of 16 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 3971 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-KfJFiYkriZcwKV13QeH:-Kfdi_C1DPv3lw-8ViFr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/98cef80b2365af7166d5e626ff348ca3a3c4b546/query/query_test.go#L3971)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We can still have the String argument as the 3rd argument.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/schema.go, line 129 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-Kfe-i-4xUV11aBv0Z4Q:-Kfe-i-4xUV11aBv0Z4R:b8egxdm) ([raw file](https://github.com/dgraph-io/dgraph/blob/726114d9101752fc6924685ea95648f749dd7bd1/worker/schema.go#L129)):*
> ```Go
> // TODO: Janardhan - if read fails try other servers serving same group
> func getSchemaOverNetwork(ctx context.Context, gid uint32, s *taskp.Schema,
> 	ch chan *resultErr) {
> ```

Go into prev line.

---

*[worker/schema.go, line 129 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-Kfe-mWAvjD379wlJKXA:-Kfe-mWAvjD379wlJKXB:b-917pti) ([raw file](https://github.com/dgraph-io/dgraph/blob/726114d9101752fc6924685ea95648f749dd7bd1/worker/schema.go#L129)):*
> ```Go
> // TODO: Janardhan - if read fails try other servers serving same group
> func getSchemaOverNetwork(ctx context.Context, gid uint32, s *taskp.Schema,
> 	ch chan *resultErr) {
> ```

Doesn't need to be a pointer. ch chan resultErr.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-:-Kfe03JSP3jgSBISvyPm:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[worker/schema.go, line 129 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-Kfe-i-4xUV11aBv0Z4Q:-KfejU4-YYAXJ_xx3sVg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/726114d9101752fc6924685ea95648f749dd7bd1/worker/schema.go#L129)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Go into prev line.
</blockquote></details>

Done.

---

*[worker/schema.go, line 129 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/696#-Kfe-mWAvjD379wlJKXA:-KfejUzN3dIhUcSwZ6oq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/726114d9101752fc6924685ea95648f749dd7bd1/worker/schema.go#L129)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Doesn't need to be a pointer. ch chan resultErr.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/696)*

**Pull request merged**
