### PR TITLE
docs: GraphQL password type.

### PR DESCRIPTION
**Pull request by OmarAyo**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6369)

 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-8a4f49d5bb-97031.surge.sh)

### CODE REVIEW

**Comment by OmarAyo** [comment]
___
*[wiki/content/graphql/directives/index.md, line 48 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6369#-MGEk4g8779xZxd7Jp4p:-MGFEsBy5SQ__4XkzD_c:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/acdc4dbd0a0176324ef59b5f4ee46af91d68ec40/wiki/content/graphql/directives/index.md#L48)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> `secret`directive used
> ```
Add a space between these two words. And, add "is": `@secret` directive is used.
</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/graphql/schema/types.md, line 135 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6369#-MGEkReBAPsKr4LYLINa:-MGFEspe-KwM23LkdEBq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/acdc4dbd0a0176324ef59b5f4ee46af91d68ec40/wiki/content/graphql/schema/types.md#L135)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> checkAuthorPassword
> ```
Should this be generic? e.g., <code>check<em>Type</em>Password</code>, where <em>`Type`</em> is the name of the node type.
</blockquote></details>

Done.

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6369)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @danielmai, @MichaelJCompton, @OmarAyo, and @pawanrawal)

___
*[wiki/content/graphql/schema/types.md, line 135 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6369#-MGFIe7l5Zg_yRfVRSPO:-MGFIe7mD6KnQsi2Pku4:b5yw3qa) ([raw file](https://github.com/dgraph-io/dgraph/blob/86d2fb0781b47a9107f3d4788bb466a8dc24fe0d/wiki/content/graphql/schema/types.md#L135)):*
> ```
> A password for an entity is set with setting the schema for the attribute to be of type `password`. 
> ```
I just re-read this. The `password` schema type is specific to the Dgraph schema. For GraphQL schema, it's set via `@secret` on the node type (not the field). We should describe how to set password fields via `@secret` in the GraphQL schema in this intro, since this is the GraphQL docs. No need to mention `password` since that's not involved when using GraphQL.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6369)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @danielmai, @MichaelJCompton, and @OmarAyo)

___
*[wiki/content/graphql/directives/index.md, line 48 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6369#-MGEk4g8779xZxd7Jp4p:-MGIt4SU9oG4iQmR1sm6:b-305oxf) ([raw file](https://github.com/dgraph-io/dgraph/blob/acdc4dbd0a0176324ef59b5f4ee46af91d68ec40/wiki/content/graphql/directives/index.md#L48)):*
<details><summary><i>Previously, OmarAyo (OmarAyo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

encrypted and then stored in the database.
___
*[wiki/content/graphql/schema/types.md, line 138 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6369#-MGItM0GCfNiFd5iLmKr:-MGItM0GCfNiFd5iLmKs:b-hvy1nl) ([raw file](https://github.com/dgraph-io/dgraph/blob/86d2fb0781b47a9107f3d4788bb466a8dc24fe0d/wiki/content/graphql/schema/types.md#L138)):*
> ```Markdown
> The passwords are encrypted using [bcrypt](https://en.wikipedia.org/wiki/Bcrypt).
> 
> For example: to set a password, first set schema:
> ```

Agree with Daniel's comment above, we should talk about setting a secret.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6369#-:-MIKw5I33HlDChpDWuWA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MichaelJCompton and @OmarAyo)

**Pull request merged**
