### PR TITLE
Release/fixes

### LINKED ISSUE #764: Setting bool as index crashes Dgraph server
curl localhost:8080/query -XPOST -d 'mutation { schema { initial_release_date: bool @index }}' 

Would crash Dgraph.

### LINKED ISSUE #767: UI doesn't show tokenizers
curl localhost:8080/query -XPOST -d 'schema {                                                                                                             ~
  tokenizer
}'

Won't work in the UI.

### LINKED ISSUE #772: Unicode chars are broken when UI shortens the names
```पल्प ...िक्शन:```

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Returning error when trying to index bool values. Fixes #764 
2. Improving output of Setting schema to print schema type.
3. Displaying tokenizers in UI. Fixes #767 
4. Truncating Scratchpad entries taking Unicode into account. Fixes #772

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/780)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[schema/schema.go, line 104 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgNCTHCbBelr26BfbaP:-KgNCTHCbBelr26BfbaQ:bidubsk) ([raw file](https://github.com/dgraph-io/dgraph/blob/56666c08d4c34c02a6c1f3ffcee8a88075c3dff3/schema/schema.go#L104)):*
> ```Go
> 	syncCh <- se
> 	s.elog.Printf("Setting schema type for attr %s: %v, tokenizer: %v\n", se.Attr,
> 		types.TypeID(se.Schema.ValueType).Name(), se.Schema.Tokenizer)
> ```

May be print directive(reverse or index) also in elog

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-:-KgNExM_-hS8qzcgKLh5:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[schema/parse.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgNK3IAKH50sNULo-td:-KgNK3IAKH50sNULo-te:b-5z9bw) ([raw file](https://github.com/dgraph-io/dgraph/blob/56666c08d4c34c02a6c1f3ffcee8a88075c3dff3/schema/parse.go#L132)):*
> ```Go
> 	}
> 	if typ == types.BoolID {
> 		return tokenizers, x.Errorf("Indexing not allowed on predicate %s of type bool", predicate)
> ```

Add this check in checkSchema function in worker/mutation.go (Schema updates can come through grpc client also).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780)*

**Comment by pawanrawal** [comment]
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[schema/schema.go, line 104 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgNCTHCbBelr26BfbaP:-KgNzYlU0nusxUkusMRl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/56666c08d4c34c02a6c1f3ffcee8a88075c3dff3/schema/schema.go#L104)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

May be print directive(reverse or index) also in elog
</blockquote></details>

Done.

---

*[schema/parse.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgNK3IAKH50sNULo-td:-KgO-23_KVzclbxHy3uu:b-ctmnxi) ([raw file](https://github.com/dgraph-io/dgraph/blob/56666c08d4c34c02a6c1f3ffcee8a88075c3dff3/schema/parse.go#L132)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Add this check in checkSchema function in worker/mutation.go (Schema updates can come through grpc client also).
</blockquote></details>

Removed the check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 7 of 9 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[query/query_test.go, line 4817 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO-eyN8miaMkqtfjMH:-KgO-eyO2aiG_dJoFhuO:b-negr6i) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/query/query_test.go#L4817)):*
> ```Go
> 				name
> 				alive
> 				count(friend)
> ```

No need for count I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-:-KgO2QPGZOGnF1ADXr1o:bnfp4nl)*

**Comment by janardhan1993** [comment]
Reviewed 8 of 10 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 247 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO1-NepYFmmHSM0sPJ:-KgO1-Nf-GSXC8afLcx4:bblei1i) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/tok/tok.go#L247)):*
> ```Go
> func (t BoolTokenizer) Tokens(v types.Val) ([]string, error) {
> 	var b int32
> 	if v.Value.(bool) {
> ```

Random though, In almost all tokenizers we do v.Value.(type). So float tokenizer expects that value type would be float. In general we convert to schema type and call index tokens. So if some one specifies float tokenizer for int type predicate, it wouldn't work right ?
Should be check whether the tokenizer is valid for that type or not in schema parse and inside enrich schema in main.go

---

*[worker/sort.go, line 142 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO2I5GMBbF07n2TQYp:-KgO2I5GMBbF07n2TQYq:bjjbg) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/sort.go#L142)):*
> ```Go
> 		return nil, x.Errorf("Attribute %s not defined in schema", attr)
> 	}
> ```

You could assert here. Schema should be defined already since we derive schema if not defined on first mutation. So we won't get src uid without schema being defined.

---

*[worker/sort.go, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO2pOymR1HFOGLRVlf:-KgO2pP1-FsF-6s8ZhFC:bxxy8af) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/sort.go#L161)):*
> ```Go
> 		// sortable.
> 		if typ == types.StringID {
> 			return nil, x.Errorf("Attribute:%s does not exact index for sorting.",
> ```

does not have

---

*[worker/tokens.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO3WjxOEHHoCev51yy:-KgO3WjxOEHHoCev51yz:b-i1467u) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/tokens.go#L41)):*
> ```Go
> // index that is found for the predicate.
> func getInequalityTokens(attr, f string, ineqValue types.Val) ([]string, string, error) {
> 	typ, err := schema.State().TypeOf(attr)
> ```

Is this function called even if subgraph is empty. If not then we probably don't need this.

---

*[worker/tokens.go, line 64 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO3kvbfw3-66rMGKIR:-KgO3kvbfw3-66rMGKIS:b16ap62) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/tokens.go#L64)):*
> ```Go
> 	// we use the default tokenizer for it.
> 	if typ == types.BoolID {
> 		tokenizer = tok.Default(types.BoolID)
> ```

This is not needed, if attribute is indexed and tokenizer is not specified we set default tokenizer while setting schema.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780)*

**Comment by janardhan1993** [comment]
Reviewed 2 of 10 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780)*

**Comment by ashwin95r** [comment]
Review status: 15 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[worker/tokens.go, line 64 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO3kvbfw3-66rMGKIR:-KgO5T-Q2ircYAuqQRae:b-ug2doc) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/tokens.go#L64)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This is not needed, if attribute is indexed and tokenizer is not specified we set default tokenizer while setting schema.
</blockquote></details>

This is because IsSortable has been set to false for bool I suppose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780)*

**Comment by pawanrawal** [comment]
Review status: 14 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 4817 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO-eyN8miaMkqtfjMH:-KgO4OKhwL_62_wtmSO7:ba3dfob) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/query/query_test.go#L4817)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

No need for count I guess.
</blockquote></details>

Removed

---

*[tok/tok.go, line 247 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO1-NepYFmmHSM0sPJ:-KgO4rhj8sowAgotC4na:bgu2tfd) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/tok/tok.go#L247)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Random though, In almost all tokenizers we do v.Value.(type). So float tokenizer expects that value type would be float. In general we convert to schema type and call index tokens. So if some one specifies float tokenizer for int type predicate, it wouldn't work right ?
Should be check whether the tokenizer is valid for that type or not in schema parse and inside enrich schema in main.go
</blockquote></details>

Thats a good point we should check that.

---

*[worker/sort.go, line 142 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO2I5GMBbF07n2TQYp:-KgO5SpNpEmz1qt7Q34u:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/sort.go#L142)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

You could assert here. Schema should be defined already since we derive schema if not defined on first mutation. So we won't get src uid without schema being defined.
</blockquote></details>

Done.

---

*[worker/sort.go, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO2pOymR1HFOGLRVlf:-KgO5UajmHWPveJyA0gc:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/sort.go#L161)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

does not have
</blockquote></details>

Done

---

*[worker/tokens.go, line 41 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO3WjxOEHHoCev51yy:-KgO5nP5iPTfkUIWsiaJ:bghl16e) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/tokens.go#L41)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Is this function called even if subgraph is empty. If not then we probably don't need this.
</blockquote></details>

Need it to check type below.

---

*[worker/tokens.go, line 64 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO3kvbfw3-66rMGKIR:-KgO5cmi17RbyivbeHFh:b-xqxduk) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/worker/tokens.go#L64)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This is because IsSortable has been set to false for bool I suppose.
</blockquote></details>

Yeah, bool is not sortable. So we don't find a sortable tokenizer (see code above), but bool is comparable (support = ), hence I set default tokenizer for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780)*

**Comment by pawanrawal** [comment]
Review status: 14 of 16 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 247 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-KgO1-NepYFmmHSM0sPJ:-KgO6DkdfKBTKGo1dbb3:bm1jeij) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a97a3ed20e5feed51c1684794842b37a84cc9a/tok/tok.go#L247)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Thats a good point we should check that.
</blockquote></details>

How about I do that in a separate PR which will obviously be part of this release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/780#-:-KgO6VGi1Hr846UYVMvo:bnfp4nl)*

**Comment by pawanrawal** [comment]
merged

**Pull request closed without merging**
