### PR TITLE
Fix reverse

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/732)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/732#-KfkBffIXEewlqU3koUJ:-KfkBffIXEewlqU3koUK:b-iaozli) ([raw file](https://github.com/dgraph-io/dgraph/blob/b4e0ef35f7890f02dc29ff08d45ccad58a141097/worker/task.go#L208)):*
> ```Go
> 			} else {
> 				key = x.DataKey(attr, q.UidList.Uids[i])
> 			}
> ```

q.Reverse is never true and also doesn't make sense for aggregator and passwordfn since they don't operate on uid type.

if srcFn.fnType == AggregatorFn || srFn.fnType == CompareScalarFn {}
else if srcFn.fnType == CompareScalarFn {
if q.reverse {} ...
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/732)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/732#-KfkBffIXEewlqU3koUJ:-KfnL1fVDCxt70deDX0a:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b4e0ef35f7890f02dc29ff08d45ccad58a141097/worker/task.go#L208)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

q.Reverse is never true and also doesn't make sense for aggregator and passwordfn since they don't operate on uid type.

if srcFn.fnType == AggregatorFn || srFn.fnType == CompareScalarFn {}
else if srcFn.fnType == CompareScalarFn {
if q.reverse {} ...
}
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/732)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/732#-KfkBffIXEewlqU3koUJ:-KfnMP7bl84PjbL0Ez8l:b-tlc8bo) ([raw file](https://github.com/dgraph-io/dgraph/blob/b4e0ef35f7890f02dc29ff08d45ccad58a141097/worker/task.go#L208)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The way that its presently written, this if clause `(srcFn.fnType == CompareScalarFn)` is not needed (unless we wan't to do something custom for ScalarFn) because it is handled by the two conditions below. What case are those conditions for anyway?

else if q.Reverse {
} else {
}

Also, is it possible to add a test for this so that we can catch it if it happens in the future?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/732)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/task.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/732#-KfkBffIXEewlqU3koUJ:-KfnNbq0OqBbpQp7Q7ft:b6x7ebw) ([raw file](https://github.com/dgraph-io/dgraph/blob/b4e0ef35f7890f02dc29ff08d45ccad58a141097/worker/task.go#L208)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The way that its presently written, this if clause `(srcFn.fnType == CompareScalarFn)` is not needed (unless we wan't to do something custom for ScalarFn) because it is handled by the two conditions below. What case are those conditions for anyway?

else if q.Reverse {
} else {
}

Also, is it possible to add a test for this so that we can catch it if it happens in the future?
</blockquote></details>

Wait it would fall into != NotFn

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/732)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/task.go, line 208 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/732#-KfkBffIXEewlqU3koUJ:-KfnUFKrLvbNEtdYzbCM:bcai7gb) ([raw file](https://github.com/dgraph-io/dgraph/blob/b4e0ef35f7890f02dc29ff08d45ccad58a141097/worker/task.go#L208)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Wait it would fall into != NotFn
</blockquote></details>

NotAFunction can be combined with the first if.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/732)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/732#-:-KfncH6htrgBmmBqa0lK:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
