### PR TITLE
Add `go install` instruction to generate the dgraph binary

### PR DESCRIPTION
**Pull request by avinassh**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1930)

### CODE REVIEW

**Comment by manishrjain** [comment]
@pawanrawal Can you look at this?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1930#-:-L0hVARbn4co1Nx-nkR3:bvpv79b)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[wiki/content/contribute/index.md, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1930#-L0hn9VGQx-vkUsarXha:-L0hn9VGQx-vkUsarXhb:bmcabb6) ([raw file](https://github.com/dgraph-io/dgraph/blob/98278e9f07cda66e8b45b15b7c6bfdb981fe0645/wiki/content/contribute/index.md#L17)):*
> ```Markdown
> ### Setup Dgraph from source repo
> 
>     $ mkdir -p $GOPATH/src/github.com/dgraph-io/
> ```

I verified that the following command works on a fresh Docker container with golang installed. It also installs the dgraph binary in `$GOPATH/bin`. It does take a bit of time because of the size of the git repo. 
```
go get -u -v github.com/dgraph-io/dgraph/...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1930)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[wiki/content/contribute/index.md, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1930#-L0hn9VGQx-vkUsarXha:-L0hoFpT-FuAsiP1zQau:b-f5urc7) ([raw file](https://github.com/dgraph-io/dgraph/blob/98278e9f07cda66e8b45b15b7c6bfdb981fe0645/wiki/content/contribute/index.md#L17)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I verified that the following command works on a fresh Docker container with golang installed. It also installs the dgraph binary in `$GOPATH/bin`. It does take a bit of time because of the size of the git repo. 
```
go get -u -v github.com/dgraph-io/dgraph/...
```
</blockquote></details>

So we can probably just run the above. Does it not work for you @avinassh?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1930)*

**Comment by avinassh** [comment]
This PR was a follow up from my other PR (https://github.com/dgraph-io/dgraph/pull/1927) (which started from https://github.com/dgraph-io/dgraph/issues/1926). To fix that issue #1926, docs were updated and instruction `go get -v ...` etc was removed and replaced by cloning the repo manually. 

So, if you check the current master - https://github.com/dgraph-io/dgraph/blob/3bf16a4466c5dcc7e60e0c8853a6802ee5d30214/wiki/content/contribute/index.md, we are not doing `go get ...`. And to install the binary, the steps `go install` is necessary.

**Comment by pawanrawal** [comment]
I see. We have deleted the code which was causing issues initially. If you try doing a 
```
go get -u -v -t github.com/dgraph-io/dgraph/...
```
It should work for you. It will also install the `dgraph` binary in `$GOPATH/bin`. If it doesn't work for you, I'd be happy to merge the current PR.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1930#-:-L0hwIwLHWfAuQ1NzVEN:bozhx7l)*

**Comment by avinassh** [comment]
`go get` also works, then we should update the docs to reflect that right? Because with current instructions you don't get the binary 😅

**Comment by pawanrawal** [comment]
Yeah, can you please do that and I'll merge your PR.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1930#-:-L0iWDOQBzeQh-0Irtr7:btqdwjn)*

**Comment by avinassh** [comment]
Updated 😅

**Comment by pawanrawal** [comment]
Thanks @avinassh!

**Comment by peterstace** [comment]
When I tried using `go get -u -v -t github.com/dgraph-io/dgraph/...` on a fresh `GOPATH`, but ran into some problems. It's mainly to do with the plugin examples, because they need to be built with different flags.

E.g.

```
$ GOPATH=`pwd` go get -u -v -t github.com/dgraph-io/dgraph/... 
...
# github.com/dgraph-io/dgraph/systest/customtok/anagram
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"
...
```

Are you guys seeing the same error in a fresh checkout?

**Comment by pawanrawal** [comment]
I will try this again and update here later in the day.

**Comment by avinassh** [comment]
Let me spin up a fresh machine and try

**Comment by avinassh** [comment]
So I spun a fresh Ubuntu 17.04, installed Go and ran the `go get ...` and ran into the same error as @peterstace 

Then I tried the old instructions, and I got following:

```
$ go install ./dgraph/

# github.com/dgraph-io/dgraph/vendor/github.com/tebeka/snowball
exec: "gcc": executable file not found in $PATH
```

Installed gcc and but got:

```
$ go install ./dgraph

# github.com/dgraph-io/dgraph/vendor/github.com/tebeka/snowball
vendor/github.com/tebeka/snowball/snowball.go:15:10: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
          ^~~~~~~~~~
compilation terminated.
```

**Comment by peterstace** [comment]
For the error about `stdlib.h`, you'll need to install some dev packages. Instructions differ per OS, but for ubuntu, `build-essential` is the package you need.

**Pull request merged**
