### PR TITLE
Return value in an array for list type predicate irrespective of length

### LINKED ISSUE #1956: [string] schema, Go client returns string, not []string for single element list
- What version of Dgraph are you using?
0.9.2

- Have you tried reproducing the issue with latest release?
No, haven't had a chance to upgrade yet

- What is the hardware spec (RAM, OS)?
16GB, macOS 10.12.6

- Steps to reproduce the issue (command/config used to run Dgraph).
```
docker run -it -p 8080:8080 -p 9080:9080 -v /tmp/data:/dgraph --name diggy dgraph/dgraph:v0.9.2 dgraph zero --port_offset -2000
docker exec -it diggy dgraph server --memory_mb 2048 --zero localhost:5080
```

- Expected behaviour and actual result.
With a field with a `[string]` schema, the Go client gets a `string` value, not a `[]string` for a single element list. Since the field has a `[]string` type, this results in an error on deserialization for single element lists.

### PR DESCRIPTION
**Pull request by pawanrawal**
We get information(whether it's of list type or not) about the predicate while calling ProcessTaskOverNetwork. Then we pass this down to outputnode and use it while encoding. 

Fixes #1956

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1971)

### CODE REVIEW

**Comment by peterstace** [comment]
:lgtm: This looks like it will work. Did you consider adding an additional method to `outputNode` instead of adding the flag? E.g. `AddListValue`. Hard to say whether or not it would be more readable without actually doing the change though.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/outputnode.go, line 142 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1971#-L1p8G08wJRGSHC5wOnr:-L1p8G08wJRGSHC5wOns:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/17cc830a17e500749e650ab53bf24ce77216d17d/query/outputnode.go#L142)):*
> ```Go
> 		}
> 	}
> 	fj.attrs = append(fj.attrs, makeScalarNode(attr, false, []byte(fmt.Sprintf("\"%#x\"", uid)),
> ```

100 chars

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1971#-:-L1pBepMgqRCV7do9w1d:b-ms3dzf)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[protos/internal.proto, line 76 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1971#-L1pBNog9owCL61c878X:-L1pBNog9owCL61c878Y:bj78zr) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2f0fdda5e9500b6708f21b849c0e106f96d16fc/protos/internal.proto#L76)):*
> ```protobuf
> 	repeated FacetsList facet_matrix = 5;
> 	repeated LangList lang_matrix = 6;
> 	bool list = 7;
> ```

Might make sense to move it inside message ValueList

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1971#-:-L1pCb5eLnZYF2y9SGuq:bnfp4nl)*

**Comment by pawanrawal** [comment]
Good idea Peter. Done!

---

Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[protos/internal.proto, line 76 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1971#-L1pBNog9owCL61c878X:-L1pEPbhlbPKzfBsRk6F:b-qzkwt2) ([raw file](https://github.com/dgraph-io/dgraph/blob/d2f0fdda5e9500b6708f21b849c0e106f96d16fc/protos/internal.proto#L76)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Might make sense to move it inside message ValueList
</blockquote></details>

That would duplicate the information I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1971#-:-L1pETgaJMR8dspq7EHN:bhlnos)*

**Comment by pawanrawal** [comment]
In master as of 99d1acebaedcdb8b3934515a88b9a2d915b07962

**Pull request closed without merging**
