### PR TITLE
GitHub issues

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1838)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Fixes #1839, #1830 , #1829, #1827. Fix bug in lru eviction

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1838#-:-KzwLSRuCkQKtEre2HUK:b-k515w7)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/lru.go, line 147 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1838#-KzziZvuS_-LELWqu4MJ:-KzziZvuS_-LELWqu4MK:bhycvgs) ([raw file](https://github.com/dgraph-io/dgraph/blob/5ef0df5a6f117cb736fbc7f28413a00ebb4d1994/posting/lru.go#L147)):*
> ```Go
> 		}
> 
> 		prev := ele.Prev()
> ```

What does this change achieve?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1838#-:-KzziynHJoYdiomgoDES:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 10 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/lru.go, line 147 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1838#-KzziZvuS_-LELWqu4MJ:-Kzzl0-zdzgNstZW12CZ:b-lbpo12) ([raw file](https://github.com/dgraph-io/dgraph/blob/5ef0df5a6f117cb736fbc7f28413a00ebb4d1994/posting/lru.go#L147)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What does this change achieve?
</blockquote></details>

ele gets Reset once it's passed to list.Remove. have added comment in the code for the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1838)*

**Comment by janardhan1993** [comment]
Merged to master.

**Pull request closed without merging**
