### PR TITLE
Track context information of variables

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/821)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[query/query_test.go, line 432 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/821#-KhL8MREO6ZrMFbRNox_:-KhL8MREO6ZrMFbRNoxa:brhp9d4) ([raw file](https://github.com/dgraph-io/dgraph/blob/9319ac44b85cdb1650054347588078e36c77c7f6/query/query_test.go#L432)):*
> ```Go
> 			}
> 
> 			me(id: var(sum), orderdesc: var(f)) {
> ```

add a few more tests, then submit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/821#-:-KhL8OY_pIvNoQ3cxnOF:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/821#-:-KhL985ZBdUf1Xx8Tvv2:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query_test.go, line 432 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/821#-KhL8MREO6ZrMFbRNox_:-KhL9YVJXQYsjWgfkxpj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9319ac44b85cdb1650054347588078e36c77c7f6/query/query_test.go#L432)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

add a few more tests, then submit.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/821)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
