### PR TITLE
Update: TLS configuration

### PR DESCRIPTION
**Pull request by kdsgambhir**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2460)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 4 unresolved discussions (waiting on @kdsgambhir)

---

*[wiki/content/deploy/index.md, line 1141 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2Jhr4Esmmm1QH_srq:-LG2Jhr5-i_D-uZNgphJ:b39qdsi) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1141)):*
> ```Markdown
> Dgraph loader can be configured with following options:
> 
> If you want to use TLS client authentication you have to set, ```tls_client_auth to true``` and ```set cacertfile, certfied and keyfile ``` to the correct paths
> ```

Can just do one backtick here.

---

*[wiki/content/deploy/index.md, line 1171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2Jp1aDDsXbzrcP4nY:-LG2Jp1aDDsXbzrcP4nZ:b-kwo7gp) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1171)):*
> ```Markdown
> services:
>   zero:
>     image: dgraph/dgraph:v1.0.5
> ```

dgraph/dgraph:latest

---

*[wiki/content/deploy/index.md, line 1184 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2JsCu-Fq2zC6T-NFP:-LG2JsCu-Fq2zC6T-NFQ:bg47kik) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1184)):*
> ```Markdown
>     command: dgraph zero --my=zero:5080
>   server:
>     image: dgraph/dgraph:v1.0.5
> ```

:latest

---

*[wiki/content/deploy/index.md, line 1185 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2K-sRB6sAEVO15Mli:-LG2K-sRB6sAEVO15Mlj:bfu3vx1) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1185)):*
> ```Markdown
>   server:
>     image: dgraph/dgraph:v1.0.5
>     hostname: dgraph-test
> ```

Don't call it `-test`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2460)*

**Comment by kdsgambhir** [comment]
*[wiki/content/deploy/index.md, line 1141 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2Jhr4Esmmm1QH_srq:-LG7xCqCE9LdSk0COoYl:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1141)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can just do one backtick here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2460)*

**Comment by kdsgambhir** [comment]
*[wiki/content/deploy/index.md, line 1184 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2JsCu-Fq2zC6T-NFP:-LG7xqqY3Gk4C2ML9sz6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1184)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

:latest
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2460)*

**Comment by kdsgambhir** [comment]
*[wiki/content/deploy/index.md, line 1185 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2K-sRB6sAEVO15Mli:-LG7xv_Q4IO7bzVuxCJq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1185)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't call it `-test`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2460)*

**Comment by kdsgambhir** [comment]
*[wiki/content/deploy/index.md, line 1171 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/2460#-LG2Jp1aDDsXbzrcP4nY:-LG7xPO9CnhUp2hPhvSr:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb29da84ac98b0ac7331d44e6a49f962d70967d5/wiki/content/deploy/index.md#L1171)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

dgraph/dgraph:latest
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2460)*

**Comment by srfrog** [comment]
can you please revise this against master branch? the TLS stuff got some refactoring. thanks.

**Pull request closed without merging**
