### PR TITLE
Don't store strings escaped

### PR DESCRIPTION
**Pull request by peterstace**
Manual testing with gRPC client (Go), Web UI and cURL have been done fairly thoroughly, so I'm fairly certain I have made all of the changes needed for this to work end to end.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1587)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1160 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587#-KveV98zcHrUKuS5XcRy:-KveV99-7BqOtfZ5Yzkx:bjfrf5v) ([raw file](https://github.com/dgraph-io/dgraph/blob/80db2df86c149923ec942be052a82f5cdaed9736/gql/parser.go#L1160)):*
> ```Go
> // so, it tries to unquote str possibly returning an error. Otherwise, the
> // original value is returned.
> func unquoteIfQuoted(str string) (string, error) {
> ```

This has different behaviour than strings.Trim(it.val, "\""). If someone gives `\"Hello\"` it would be stored with '\' ?   

---

*[rdf/state.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587#-KveWSZkiZ9OPPbHEjMv:-KveWSZkiZ9OPPbHEjMw:be961bf) ([raw file](https://github.com/dgraph-io/dgraph/blob/37a562a78a2124296b7f3e69f30429f07c1118ef/rdf/state.go#L355)):*
> ```Go
> 	if r == quote {
> 		l.Ignore()
> 		return lexLiteral(l)
> ```

I can see that you are unquoting in gql/parser.go, but are you sure you are unquoting everywhere where item type is literal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1160 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587#-KveV98zcHrUKuS5XcRy:-Kvexv9Ma6TZfYwlqDyi:b-kcbevg) ([raw file](https://github.com/dgraph-io/dgraph/blob/80db2df86c149923ec942be052a82f5cdaed9736/gql/parser.go#L1160)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

This has different behaviour than strings.Trim(it.val, "\""). If someone gives `\"Hello\"` it would be stored with '\' ?   
</blockquote></details>

If someone gives the string with content `\"Hello\"`, then it wouldn't be unquoted and would instead be returned as is (since the first character is `\` and the last character is `"`. Is that what you mean?

---

*[rdf/state.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587#-KveWSZkiZ9OPPbHEjMv:-KveyJXaO79hktByHeSy:bm2gxcr) ([raw file](https://github.com/dgraph-io/dgraph/blob/37a562a78a2124296b7f3e69f30429f07c1118ef/rdf/state.go#L355)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

I can see that you are unquoting in gql/parser.go, but are you sure you are unquoting everywhere where item type is literal.
</blockquote></details>

Yeah, pretty sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[rdf/state.go, line 355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587#-KveWSZkiZ9OPPbHEjMv:-Kvf0S908dkUHwH8e8GH:b7mvwb9) ([raw file](https://github.com/dgraph-io/dgraph/blob/37a562a78a2124296b7f3e69f30429f07c1118ef/rdf/state.go#L355)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Yeah, pretty sure.
</blockquote></details>

To elaborate, I'm unquoting for:
- strings as objects in RDFs
- strings in facets in RDFs
- strings in variable blocks
- strings in the default value for variables
There were a few other places that I checked manually, but didn't need to make any changes. E.g. query function `eq(name, "Line1\nLine2")`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1587#-:-KvjUjNcGopaBjkOa-Q4:bnfp4nl)*

**Pull request merged**
