### PR TITLE
Improvements/Refactoring

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Call `pl.Length()` only if attr has `@count` index.
2. Fix inconsistent semantics with uid function. Earlier `uid` function at root didn't have `sg.Attr` as empty but `uid` function in children would have had `sg.Attr` as `uid`. Now `sg.Attr` is empty for uid filter Subgraph.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1219)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Also, Empty `uid()`
```
{
  me(func: uid())
}
```
throws:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb71c37]

goroutine 9486 [running]:
github.com/dgraph-io/dgraph/query.ProcessGraph(0x12f9e20, 0xc42c2a0ba0, 0xc42020d8c0, 0x0, 0xc42c2a0c00)
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/query.go:1594 +0x77
created by github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/query/query.go:2204 +0x4a9
```

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/index.go, line 188 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1219#-KpSNwsaidz9tMOdDyGT:-KpSNwsaidz9tMOdDyGU:b-6h0azf) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f3cde876df0878c4535185e6b83a8fbfe58e875/posting/index.go#L188)):*
> ```Go
> 	x.PredicateStats.Add(fmt.Sprintf("r.%s", edge.Attr), 1)
> 
> 	if countAfter != countBefore && hasCountIndex {
> ```

hasCountIndex && countAfter != countBefore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1219#-:-KpSNHERLSfHlX75z2m3:bg5k326)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1219#-:-KpSVbtRoOIeUv8UBM18:bnfp4nl)*

**Comment by tzdybal** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1219#-:-KpSYfo5PYen4ZFkEiob:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1219#-:-KpVp1MEjwZFosfuxzJc:bnfp4nl)*

**Pull request closed without merging**
