### PR TITLE
Support graphql variable for id

### PR DESCRIPTION
**Pull request by pawanrawal**
Support GraphQL variable for id. Implements #911

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/922)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 393 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/922#-KjkYmWiykGENFFOlaEA:-KjkYmWiykGENFFOlaEB:b-5g23kq) ([raw file](https://github.com/dgraph-io/dgraph/blob/2515f6656e5defa59c13b6e43b1a2678a4feefab/gql/parser.go#L393)):*
> ```Go
> 	}
> 
> 	idVal := gq.Args["id"]
> ```

idVal, ok := gq.Args["id"]

if ok {
 if idVal == "" { return <empty id not allowed?> }
}

---

*[query/query_test.go, line 6190 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/922#-KjkXv03GEoA-gb1Rgmr:-KjkXv04Zn90GDU_CjuN:b-sln4oc) ([raw file](https://github.com/dgraph-io/dgraph/blob/2515f6656e5defa59c13b6e43b1a2678a4feefab/query/query_test.go#L6190)):*
> ```Go
> func TestGraphQLId(t *testing.T) {
> 	populateGraph(t)
> 	q := `{"query": "query test ($a: string = 1) { me(id: $a) { name, gender, friend(first: 1) { name }}}",
> ```

Can you check this case `me(id: $var(a,b,c))`. I guess a slight refactoring of ifs is needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/922)*

**Comment by ashwin95r** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 393 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/922#-KjkYmWiykGENFFOlaEA:-KjkZ6Xbv7Wa2dIAbmgw:b646d1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/2515f6656e5defa59c13b6e43b1a2678a4feefab/gql/parser.go#L393)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

idVal, ok := gq.Args["id"]

if ok {
 if idVal == "" { return <empty id not allowed?> }
}
</blockquote></details>

I think to check for ok would be better than "".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/922)*

**Comment by pawanrawal** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 393 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/922#-KjkYmWiykGENFFOlaEA:-Kjk_Zz47vHmKOGi2o6P:bobs4ye) ([raw file](https://github.com/dgraph-io/dgraph/blob/2515f6656e5defa59c13b6e43b1a2678a4feefab/gql/parser.go#L393)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

I think to check for ok would be better than "".
</blockquote></details>

thats a good idea, done.

---

*[query/query_test.go, line 6190 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/922#-KjkXv03GEoA-gb1Rgmr:-Kjkf9UM1LUB3K5AkaT8:bf475oz) ([raw file](https://github.com/dgraph-io/dgraph/blob/2515f6656e5defa59c13b6e43b1a2678a4feefab/query/query_test.go#L6190)):*
> me(id: $var(a,b,c))
Should throw an error now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/922)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/922#-:-KjkwMDpmQ0OfeV385cv:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/922#-:-Kjs8Tyen_MJW23039aK:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
