### PR TITLE
Remove store and pass it as argument plus mod sharding based on attributes

### PR DESCRIPTION
**Pull request by ashwin95r**
[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/28)

### CODE REVIEW

**Comment by manishrjain** [comment]
Good change, but there's some disconnect here from our discussion.

---

Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/worker.go, line 10 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJuek8iwk7LE2H7WVK:-KAJuek8iwk7LE2H7WVL:277813931) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/posting/worker.go#L10)):*
This should have been moved to a new module, worker/worker.go. And then, we should initialize that worker module with a pstore; just like uid/assigner.go

---

*[uid/assigner.go, line 96 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJu14OTA85dgn1gDaw:-KAJu14OTA85dgn1gDax:1718968733) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/uid/assigner.go#L96)):*
Instead of passing a pointer to every function in uid/assigner.go, we should use an Init() here, and set the store pointer for this module; as we'd discussed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-:-KAJunfgj2x-_yKKWGzB:-748865341)*

**Comment by manishrjain** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by ashwin95r** [comment]
Yeah, I forgot that part while doing this. I'll make the changes

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-:-KAKStRcJhnUsLouIlOC:-509104946)*

**Comment by manishrjain** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[uid/assigner.go, line 96 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJu14OTA85dgn1gDaw:-KAM4ApGMYS6tvjMlu2o:-1591501902) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/uid/assigner.go#L96)):*
You missed this comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by ashwin95r** [comment]
Review status: 4 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[uid/assigner.go, line 96 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJu14OTA85dgn1gDaw:-KAQ892IluDTV4GBrv1u:-675375060) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/uid/assigner.go#L96)):*
I didn't miss it. Just set it apart for a bit later :smiley: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by manishrjain** [comment]
Review status: 4 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[uid/assigner.go, line 96 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJu14OTA85dgn1gDaw:-KAX4eirmi3hCkyMNMpT:1834364758) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/uid/assigner.go#L96)):*
Alright! Then let me know when this change is ready for review.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by manishrjain** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[loader/loader.go, line 38 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYEaR7L-_OnRp5WoT_:-KAYEaR7L-_OnRp5WoTa:432369169) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/loader/loader.go#L38)):*
Call it uidStore, and dataStore

---

*[loader/loader.go, line 147 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYF8saDkmalAXRSj_t:-KAYF8saDkmalAXRSj_u:-374147056) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/loader/loader.go#L147)):*
Is this line within 80 or 100 char limit?

---

*[server/loader/main.go, line 70 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYH5pUT_Y5B8iwILFA:-KAYH5pUT_Y5B8iwILFB:2013077151) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/server/loader/main.go#L70)):*
Call it dataStore

---

*[server/loader/main.go, line 74 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYH2IO-y8jIX1kSvxo:-KAYH2IO-y8jIX1kSvxp:-1639243223) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/server/loader/main.go#L74)):*
Call it uidStore

---

*[server/uidassigner/main.go, line 64 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYHHT7eCjuMV3nfLaD:-KAYHHT7eCjuMV3nfLaE:201568913) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/server/uidassigner/main.go#L64)):*
Should this be nil?

---

*[uid/assigner.go, line 35 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYG9spyyYUb5uAxP-n:-KAYG9spyyYUb5uAxP-o:-1639243223) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/uid/assigner.go#L35)):*
Call it uidStore

---

*[uid/assigner.go, line 149 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYHW6z8osWBOwD8-re:-KAYHW6z8osWBOwD8-rf:-1110187911) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/uid/assigner.go#L149)):*
Is this within the 80 / 100 char limit?

---

*[worker/worker.go, line 11 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYHdRvSxBBqVKvly9I:-KAYHdRvSxBBqVKvly9J:2013077151) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/worker/worker.go#L11)):*
Call it dataStore

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 38 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYEaR7L-_OnRp5WoT_:-KAYNE19RmDxEkMMUDT9:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/loader/loader.go#L38)):*
Done.

---

*[loader/loader.go, line 147 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYF8saDkmalAXRSj_t:-KAYNT9MX0AZRd6FYmk0:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/loader/loader.go#L147)):*
Done.

---

*[server/loader/main.go, line 70 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYH5pUT_Y5B8iwILFA:-KAYNyNvOv3MFn_Q3mJT:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/server/loader/main.go#L70)):*
Done.

---

*[server/loader/main.go, line 74 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYH2IO-y8jIX1kSvxo:-KAYNz7vqR-gZdH3tnAy:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/server/loader/main.go#L74)):*
Done.

---

*[server/uidassigner/main.go, line 64 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYHHT7eCjuMV3nfLaD:-KAYLZ_FjqB79SE-W90T:895258222) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/server/uidassigner/main.go#L64)):*
Yeah, since the uidassigner has only one store

---

*[uid/assigner.go, line 96 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJu14OTA85dgn1gDaw:-KAYM30zZGe33Z03Znx8:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/uid/assigner.go#L96)):*
Done.

---

*[uid/assigner.go, line 35 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYG9spyyYUb5uAxP-n:-KAYM28tO9Jf7NQmPTyO:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/uid/assigner.go#L35)):*
Done.

---

*[uid/assigner.go, line 149 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYHW6z8osWBOwD8-re:-KAYMGuyrRq24H93tM8d:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/uid/assigner.go#L149)):*
Done.

---

*[worker/worker.go, line 10 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJuek8iwk7LE2H7WVK:-KAYMoCTzF00Uz1MCSgr:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/worker/worker.go#L10)):*
Done.

---

*[worker/worker.go, line 11 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYHdRvSxBBqVKvly9I:-KAYMlg6DKAvhK1zTVy6:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/6e4f29a6b815a981f0b4e7d39014953d6f3c7e1f/worker/worker.go#L11)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by manishrjain** [comment]
Reviewed 1 of 8 files at r2, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 55 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQUD3AXQ_1fYgcHKE:-KAYQUD3AXQ_1fYgcHKF:756157485) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/loader/loader.go#L55)):*
Change the names in arguments too.

---

*[loader/loader.go, line 200 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQbsuXIE7_uV_HHV_:-KAYQbsuXIE7_uV_HHVa:437021475) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/loader/loader.go#L200)):*
This looks like a long line. Please run golint.

---

*[loader/loader.go, line 242 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQj0eF5xUroMJOJ0K:-KAYQj0eF5xUroMJOJ0L:-95707344) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/loader/loader.go#L242)):*
And here.

---

*[rdf/parse.go, line 40 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQnit-PrUpei_2IVb:-KAYQnit-PrUpei_2IVc:1243838654) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/rdf/parse.go#L40)):*
And here

---

*[rdf/parse.go, line 47 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQop9yy761q55uB73:-KAYQop9yy761q55uB74:-934446037) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/rdf/parse.go#L47)):*
And here and elsewhere.

---

*[uid/assigner.go, line 96 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJu14OTA85dgn1gDaw:-KAYQ6Sx_VMDwzseDcky:-548879220) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/uid/assigner.go#L96)):*
Is this line also over 80 / 100 chars. Can you run golint once over your code?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[loader/loader.go, line 55 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQUD3AXQ_1fYgcHKE:-KAYT72KFa1f1mW2WcMK:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/loader/loader.go#L55)):*
Done.

---

*[loader/loader.go, line 200 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQbsuXIE7_uV_HHV_:-KAYU3jvYLvqdVS1wCj1:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/loader/loader.go#L200)):*
Done.

---

*[loader/loader.go, line 242 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQj0eF5xUroMJOJ0K:-KAYTEZcCASJWHnNA0PA:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/loader/loader.go#L242)):*
Done.

---

*[rdf/parse.go, line 40 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQnit-PrUpei_2IVb:-KAYU0_59GZyzaymO9V3:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/rdf/parse.go#L40)):*
Done.

---

*[rdf/parse.go, line 47 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYQop9yy761q55uB73:-KAYU1HYP2BwYCTtT_ps:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/4659b14715ba87e02a3598b62aa6e0b03c1a0783/rdf/parse.go#L47)):*
Done.

---

*[uid/assigner.go, line 96 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAJu14OTA85dgn1gDaw:-KAYU2TNvH8cB3Oc0aaY:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/9f50b86493e0b5a8ba419d52945e8e299e3a3e1c/uid/assigner.go#L96)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Comment by manishrjain** [comment]
Good work! :lgtm_strong: 

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/main.go, line 57 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-KAYVYGL6-onDgdt_oR4:-KAYVYGMeTyJO-JUACte:-490100129) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a70965d801202af2029baec9df9e701e199c5e4/server/main.go#L57)):*
Nice!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28#-:-KAYVkFf3ljbxh_Dp7Cd:1307143580)*

**Comment by manishrjain** [comment]
Reviewed 7 of 7 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/28)*

**Pull request merged**
