### PR TITLE
RAFT: Keep track of all membership information across entire cluster.

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/310)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 33 files reviewed at latest revision, 31 unresolved discussions, some commit checks failed.

---

*[worker/conn.go, line 69 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcGldQq0kurB2wskNM:-KVcGldQq0kurB2wskNN:bfqr2vw) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/conn.go#L69)):*
> ```Go
> 	p.RLock()
> 	defer p.RUnlock()
> 	for _, pool := range p.all {
> ```

Could we have it like?
x.AssertTrue(len(p.all) > 0)
return p.all[rand.Intn(len(p.all))]

---

*[worker/conn.go, line 96 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcHuuS-8iWY_AAxgZ8:-KVcHuuT7R4JRfPbGWTa:b-o6t38f) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/conn.go#L96)):*
> ```Go
> 
> 	conn, err := pool.Get()
> 	if err != nil {
> ```

Could use x.Check  here and below.

---

*[worker/groups.go, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcCikyitrXqbZ2Ql8n:-KVcCikz5hkm-6uGccO-:bkk80ap) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L33)):*
> ```Go
> 
> type server struct {
> 	Id      uint64
> ```

Should we call this NodeId to make it clear or maybe add a comment for the same?

---

*[worker/groups.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcEoa1IwK83nZL-1tq:-KVcEoa1IwK83nZL-1tr:b-gpet96) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L87)):*
> ```Go
> 	// Instead, only some servers should contain information about everyone,
> 	// and everyone should ping those servers for updates.
> 	node := groups().newNode(math.MaxUint32, *raftId, my)
> ```

Should we remove this now that groups 0 keeps this information?

---

*[worker/groups.go, line 164 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcDtnt0CaEFOKBHm7E:-KVcDtnt0CaEFOKBHm7F:b-s0grww) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L164)):*
> ```Go
> 
> // duplicate requires at least a read mutex lock to be held by the caller.
> func (g *groupi) duplicate(gid uint32, nid uint64, addr string, leader bool) bool {
> ```

Am I right that duplicate checks whether membership information about the node being served by this instance is already there in the global server map?
Maybe we add this as a comment or change the name to be isMember or something.

---

*[worker/groups.go, line 199 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcFNfH8z4d2NqYi-Zy:-KVcFNfH8z4d2NqYi-Zz:b-ks78e) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L199)):*
> ```Go
> }
> 
> // syncMemberships needs to be called in an periodic loop.
> ```

So we aren't calling it in a periodic loop as of now?

---

*[worker/groups.go, line 200 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcFSWDUWjX0W7jfOE8:-KVcFSWDUWjX0W7jfOE9:b-9u32tb) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L200)):*
> ```Go
> 
> // syncMemberships needs to be called in an periodic loop.
> // How syncMemberships works:
> ```

We should also mention that only nodes serving group zero maintain membership information.

---

*[worker/groups.go, line 266 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcGI5uDXrtB5UNkTNh:-KVcGI5uDXrtB5UNkTNi:b-irlczf) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L266)):*
> ```Go
> 
> 	// Send an update to peer.
> 	var pl *pool
> ```

Looks like pool should be part of Server, but I think plan is to have pool be part of an instance later?

---

*[worker/groups.go, line 273 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcGcXyACxh8bUFQ3ja:-KVcGcXzBbuJEoDm3YVt:b-f30lxo) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L273)):*
> ```Go
> 		pl = pools().get(addr)
> 	} else {
> 		pl = pools().any()
> ```

This can return nil, we don't have an assert anywhere.

---

*[worker/groups.go, line 429 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcJw9cEx3cK-zPdxE3:-KVcJw9dioEwCqvZTkKL:b-kxlj0o) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L429)):*
> ```Go
> 	}
> 
> 	reply := groups().MembershipUpdateAfter(update.LastUpdate())
> ```

No exactly sure about how LastUpdate works here. It denotes a raftId right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/310)*

**Comment by jchiu0** [comment]
Reviewed 31 of 33 files at r1, 1 of 2 files at r2.
Review status: 32 of 33 files reviewed at latest revision, 42 unresolved discussions, some commit checks failed.

---

*[task.fbs, line 77 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcc5JTQ1vBjo7xq9qK:-KVcc5JTQ1vBjo7xq9qL:by373ji) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/task.fbs#L77)):*
> ```
> }
> 
> table MembershipUpdate {
> ```

Maybe we could add one sentence above each "table" to describe what it is used for. We could begin with MembershipUpdate.

---

*[algo/uidlist.go, line 31 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcahh_mntwIbfmARIe:-KVcahh_mntwIbfmARIf:b-bcaloj) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/algo/uidlist.go#L31)):*
> ```Go
> // FromUints initialize UIDList from []uint64.
> func (u *UIDList) FromUints(data []uint64) {
> 	x.AssertTrue(u != nil && u.uints == nil && u.list == nil)
> ```

I think it is better to move refactoring that affects a lot of files to a separate PR next time. It is easier to review and revert.

---

*[worker/conn.go, line 69 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcGldQq0kurB2wskNM:-KVceIz95l0haQAIrSSB:b-d0fh4o) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/conn.go#L69)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Could we have it like?
> x.AssertTrue(len(p.all) > 0)
> return p.all[rand.Intn(len(p.all))]
</details>
p.all is a map keyed by strings.. a bit tricky.

---

*[worker/groups.go, line 28 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVZz3U9y7aMBh-sMR08-r2-28:-KVccmY15WkRlyK5stOf:b-rll82e) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L28)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> var raftId should be raftID
</details>
Please fix.

---

*[worker/groups.go, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcfFi0GLVOJdlb0iml:-KVcfFi0GLVOJdlb0imm:b1ybgny) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L33)):*
> ```Go
> 
> type server struct {
> 	Id      uint64
> ```

Can add more comments about this struct and its more critical fields?

---

*[worker/groups.go, line 227 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchR4_lNCbcdwVDwdK:-KVchR4_lNCbcdwVDwdL:b3zm0dz) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L227)):*
> ```Go
> 				uo := buildTaskMembership(b, rc.Group(), rc.Id(), rc.Addr(), amleader)
> 				b.Finish(uo)
> 				data := b.Bytes[b.Head():]
> ```

b.FinishedBytes?

---

*[worker/groups.go, line 269 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchnUnNGrgQIDB2b8t:-KVchnUnNGrgQIDB2b8u:byvn8bt) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L269)):*
> ```Go
> 	addr := g.AnyServer(0)
> 
> UPDATEMEMBERSHIP:
> ```

Put in a loop and break out of loop later.

---

*[worker/groups.go, line 277 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchvvY4IB4wuGuSJOI:-KVchvvY4IB4wuGuSJOJ:b-4f6qcn) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L277)):*
> ```Go
> 	conn, err := pl.Get()
> 	x.Check(err)
> 	defer pl.Put(conn)
> ```

If the loop repeats, many pls might be waiting to be closed. Maybe put everything inside the loop in a function.

---

*[worker/groups.go, line 286 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchsw20mL_b_ppAcss:-KVchsw20mL_b_ppAcst:b-vmhxjb) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L286)):*
> ```Go
> 		addr = string(out.Data)
> 		pools().connect(addr)
> 		goto UPDATEMEMBERSHIP
> ```

If put in a loop, this is just a "continue".

---

*[worker/groups.go, line 354 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVciAqHxFZNSdSt5soI:-KVciAqHxFZNSdSt5soJ:b-c0npa) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L354)):*
> ```Go
> }
> 
> func (g *groupi) MembershipUpdateAfter(ridx uint64) []byte {
> ```

Comments for exported functions.

---

*[worker/groups.go, line 364 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcle4YnNda_J01W3TS:-KVcle4YnNda_J01W3TT:btv0375) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L364)):*
> ```Go
> 		for _, s := range peers.list {
> 			if s.RaftIdx <= ridx {
> 				continue
> ```

If all raftIdx is <= ridx, then maxIdx=0. Can this happen? Is that ok?

Maybe rename lastUpdate as something else that suggests that it is related to raftIdx, as Pawan suggested.

---

*[worker/payload.proto, line 11 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcd9ge6-KMdMZAG_O_:-KVcd9gfTLSr3uS4B-dc:buketqp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/payload.proto#L11)):*
> ```protobuf
> 
> service Worker {
> 	rpc Echo (Payload)         returns (Payload) {}
> ```

Indent

---

*[worker/payload.proto, line 20 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcdBu_FVxx6NJ5VLGK:-KVcdBu_FVxx6NJ5VLGL:buketqp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/payload.proto#L20)):*
> ```protobuf
> 	rpc RaftMessage (Payload) returns (Payload) {}
> 	rpc JoinCluster (Payload) returns (Payload) {}
> 	rpc UpdateMembership (Payload) returns (Payload) {}
> ```

Indent

---

*[x/error.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVZz3U9y7aMBh-sMR0G-r2-55:-KVcbEX9PNKvig8r_rxv:b-9zrtqi) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/x/error.go#L55)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported function Check2 should have comment or be unexported
</details>
Please fix comments. Nice idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/310)*

**Comment by manishrjain** [comment]
Review status: 26 of 34 files reviewed at latest revision, 43 unresolved discussions, some commit checks failed.

---

*[task.fbs, line 77 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcc5JTQ1vBjo7xq9qK:-KVdA5UCn8C_hr7yRlx7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/task.fbs#L77)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Maybe we could add one sentence above each "table" to describe what it is used for. We could begin with MembershipUpdate.
</details>
Done.

---

*[algo/uidlist.go, line 31 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcahh_mntwIbfmARIe:-KVdKHGLWL8rSDSug0m4:btzgqzh) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/algo/uidlist.go#L31)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> I think it is better to move refactoring that affects a lot of files to a separate PR next time. It is easier to review and revert.
</details>
Done. Agreed.

---

*[worker/conn.go, line 69 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcGldQq0kurB2wskNM:-KVdKXNIQOPD9jEDrrV1:b-88hbdy) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/conn.go#L69)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> p.all is a map keyed by strings.. a bit tricky.
</details>
Yeah. Can't do that. Also, Go maps are programmatically randomized, so this is like random.

---

*[worker/conn.go, line 96 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcHuuS-8iWY_AAxgZ8:-KVdKq4NGFEQUs086UKZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/conn.go#L96)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Could use x.Check  here and below.
</details>
Done.

---

*[worker/groups.go, line 28 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVZz3U9y7aMBh-sMR08-r2-28:-KVdKrTx90DEu3lj7gCw:bgdcb4c) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L28)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Please fix.
</details>
I don't buy Go's caps ID thing.

---

*[worker/groups.go, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcCikyitrXqbZ2Ql8n:-KVdKwWkCaU-r_yjKmpk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L33)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Should we call this NodeId to make it clear or maybe add a comment for the same?
</details>
Done.

---

*[worker/groups.go, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcfFi0GLVOJdlb0iml:-KVdKxHe50syShlWzbu1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L33)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Can add more comments about this struct and its more critical fields?
</details>
Done.

---

*[worker/groups.go, line 87 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcEoa1IwK83nZL-1tq:-KVdKyg5oeOjz0I6z7Al:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L87)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Should we remove this now that groups 0 keeps this information?
</details>
Done.

---

*[worker/groups.go, line 164 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcDtnt0CaEFOKBHm7E:-KVdL0n9ZVtWVjgjbZpq:b-2dzkh0) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L164)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Am I right that duplicate checks whether membership information about the node being served by this instance is already there in the global server map?
> Maybe we add this as a comment or change the name to be isMember or something.
</details>
It's more than isMember. It's checking for exact duplicates in the list. I added a comment to clarify it.

---

*[worker/groups.go, line 199 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcFNfH8z4d2NqYi-Zy:-KVdL6dQRikk29oBKUHV:b-ne1zaj) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L199)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> So we aren't calling it in a periodic loop as of now?
</details>
Now we are, after the testing today.

---

*[worker/groups.go, line 200 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcFSWDUWjX0W7jfOE8:-KVdL91j5z3su1xezvlO:bi40tk1) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L200)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We should also mention that only nodes serving group zero maintain membership information.
</details>
The second pointer says that. Any particular wording you'd like to use?

---

*[worker/groups.go, line 227 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchR4_lNCbcdwVDwdK:-KVdLDjBgL7w3oIjOXhj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L227)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> b.FinishedBytes?
</details>
Done.

---

*[worker/groups.go, line 266 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcGI5uDXrtB5UNkTNh:-KVdLFb0_TOJBoFSR1Up:bdcbfih) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L266)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Looks like pool should be part of Server, but I think plan is to have pool be part of an instance later?
</details>
No. I deliberately kept them different. Multiple `server`s can have the same Addr, but we don't need to open up a different pool for each of them. So, instead, I kept the connection pools separate from server. You retrieve the address of the node you need to talk to, them ask the pool to give you the connections.

---

*[worker/groups.go, line 269 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchnUnNGrgQIDB2b8t:-KVdLjqMfjuNMHkW65g2:bywel79) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L269)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Put in a loop and break out of loop later.
</details>
Emm... Not convinced why. goto is a first class member of Go language.

---

*[worker/groups.go, line 273 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcGcXyACxh8bUFQ3ja:-KVdLsrIqPutGFkzbTVp:bf9zxg0) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L273)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This can return nil, we don't have an assert anywhere.
</details>
Done. errNoConnection checks for that.

---

*[worker/groups.go, line 277 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchvvY4IB4wuGuSJOI:-KVdLwXf86MAV_YOSIuw:bc2pw69) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L277)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> If the loop repeats, many pls might be waiting to be closed. Maybe put everything inside the loop in a function.
</details>
True. The loop won't repeat more than 2 times anyway. So, it won't be too bad.

---

*[worker/groups.go, line 286 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVchsw20mL_b_ppAcss:-KVdM1JLqeeyXWum0ne2:b-vx72b5) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L286)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> If put in a loop, this is just a "continue".
</details>
Otherwise, it's goto :-).

---

*[worker/groups.go, line 354 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVciAqHxFZNSdSt5soI:-KVdM4kfWHMEQpXmGMPd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L354)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Comments for exported functions.
</details>
Done.

---

*[worker/groups.go, line 364 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcle4YnNda_J01W3TS:-KVdM61qp7p58IwB8C0-:b-376vyo) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L364)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> If all raftIdx is <= ridx, then maxIdx=0. Can this happen? Is that ok?
> 
> Maybe rename lastUpdate as something else that suggests that it is related to raftIdx, as Pawan suggested.
</details>
Done. Good catch!

---

*[worker/groups.go, line 429 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcJw9cEx3cK-zPdxE3:-KVdM8UvHjUG5RTXoFQo:bkj2wue) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L429)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> No exactly sure about how LastUpdate works here. It denotes a raftId right?
</details>
LastUpdate denotes a raft index (not a raft id). Raft Index is the index for any update applied to a raft cluster. It's monotonically increasing, so we're going to use it in place of timestamps.

---

*[worker/payload.proto, line 11 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcd9ge6-KMdMZAG_O_:-KVdAWKZth3nbIJnCOFI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/payload.proto#L11)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Indent
</details>
Done.

---

*[worker/payload.proto, line 20 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcdBu_FVxx6NJ5VLGK:-KVdAWnWpn8yCY3vAXJu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/payload.proto#L20)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Indent
</details>
Done.

---

*[x/error.go, line 55 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVZz3U9y7aMBh-sMR0G-r2-55:-KVdB581a9zfDcHPwHSx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/x/error.go#L55)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Please fix comments. Nice idea.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/310)*

**Comment by jchiu0** [comment]
:lgtm: Good progress!

---

Review status: 26 of 34 files reviewed at latest revision, 36 unresolved discussions, some commit checks failed.

---

*[x/error.go, line 60 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVZz3U9y7aMBh-sMR0G-r4-60:-KVdOJc_APiKv9C6IJv9:bya1blr) ([raw file](https://github.com/dgraph-io/dgraph/blob/b1bf743dfdebee4c7d7dad5d2d10893e833bf648/x/error.go#L60)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported function Check2f should be of the form "Check2f ..."
</details>
Fix comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-:-KVdOMW-6Ha9RC0KwmAN:b-wmbf0g)*

**Comment by pawanrawal** [comment]
:lgtm_strong: Nice work!

---

Review status: 26 of 34 files reviewed at latest revision, 35 unresolved discussions, some commit checks failed.

---

*[worker/groups.go, line 200 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-KVcFSWDUWjX0W7jfOE8:-KVdNjxtuaKVO7Yk4R5z:b-7oniug) ([raw file](https://github.com/dgraph-io/dgraph/blob/a0a25e58fe75ac81456a43f901210086e5706e4d/worker/groups.go#L200)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> The second pointer says that. Any particular wording you'd like to use?
</details>
Actually, that was a general design principal and the second point is part of the implementation. But then general design principal could go to Wiki.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-:-KVdPRyal3h96k8UIMJU:b-8m3k00)*

**Comment by manishrjain** [comment]
Thanks for the review, guys!

---

Review status: 26 of 34 files reviewed at latest revision, 35 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/310#-:-KVdQECqeNEvukndHJLy:blxbm51)*

**Pull request closed without merging**
