### PR TITLE
docs(Query): Update docs to note that only typed data can be deleted using `S * *`(Docs)

### PR DESCRIPTION
**Pull request by aaroncarey**
Customers are confused by what happens when they try to delete data that they haven't typed. This fix adds a note about this requirement and links to information on how customers can type their data.

Fixes GRAPHQL-669

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)

 
 
 
 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-1db8db5d87-101011.surge.sh)

### CODE REVIEW

**Comment by aaroncarey** [comment]
Here's the link directly to the page with the change on the preview site:

https://dgraph-76b6db82fc-99471.surge.sh/mutations/delete/

**Review by MichaelJCompton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/mutations/delete.md, line 43 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvPrxs3q1r40HXmFue:-MIvPrxs3q1r40HXmFuf:bqsedih) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md#L43)):*
> ```Markdown
> edges on that node and their corresponding definitions in the schema). 
> 
> **Note**: If the type information
> ```

Should this use this kind of note? 

{{% notice "note" %}}
___
*[wiki/content/mutations/delete.md, line 44 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvQFQu90Zt-F8flp1H:-MIvQFQu90Zt-F8flp1I:b-qz53e8) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md#L44)):*
> ```Markdown
> 
> **Note**: If the type information
> for the node `S` is missing then the delete operation will not work. For more information on how to set the type
> ```

Let's explicitly call out that it's `S * *` mutations that need types (the `S P *` ones will still work).

So maybe we should make this note like "The `S * *` mutation pattern ..."
___
*[wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvQ8fA3AEPyYYfsB6g:-MIvQ8fA3AEPyYYfsB6h:bd7wmwc) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo#L1)):*
> ```
> +++
> ```

What's this file?

**Comment by aaroncarey** [comment]
> Let's explicitly call out that it's `S * *` mutations that need types (the `S P *` ones will still work).
> 
> So maybe we should make this note like "The `S * *` mutation pattern ..."

This is a great clarification, I will work it into the docs! Stay tuned for a new commit.

**Comment by aaroncarey** [comment]
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)_ status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)
> 
> _[wiki/content/mutations/delete.md, line 43 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvPrxs3q1r40HXmFue:-MIvPrxs3q1r40HXmFuf:bqsedih) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md#L43)):_
> 
> > ```gfm
> > edges on that node and their corresponding definitions in the schema). 
> > 
> > **Note**: If the type information
> > ```
> 
> Should this use this kind of note?
> 
> {{% notice "note" %}}
> 
> _[wiki/content/mutations/delete.md, line 44 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvQFQu90Zt-F8flp1H:-MIvQFQu90Zt-F8flp1I:b-qz53e8) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md#L44)):_
> 
> > ```gfm
> > **Note**: If the type information
> > for the node `S` is missing then the delete operation will not work. For more information on how to set the type
> > ```
> 
> Let's explicitly call out that it's `S * *` mutations that need types (the `S P *` ones will still work).
> 
> So maybe we should make this note like "The `S * *` mutation pattern ..."
> 
> _[wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvQ8fA3AEPyYYfsB6g:-MIvQ8fA3AEPyYYfsB6h:bd7wmwc) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo#L1)):_
> 
> > ```
> > +++
> > ```
> 
> What's this file?

Garbage from my text editor, now removed. Thanks!

**Review by MichelDiz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/mutations/delete.md, line 9 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwLdj90z_T6gdh9N6l:-MIwLdj90z_T6gdh9N6m:b-xkp8be) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md#L9)):*
> ```
> removes predicates
> ```
I think triples suits better. As fundamentally the delete operation is removing 3 information from the DB. 
___
*[wiki/content/mutations/delete.md, line 43 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwO9L03GH-7rA1tYxo:-MIwO9L03GH-7rA1tYxp:b-70276m) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6ddcbf4d6c353d58f5e7ff9be16e8097196067f/wiki/content/mutations/delete.md#L43)):*
> ```Markdown
> edges and any indexing for the removed data. The predicates to delete are
> derived from the type information for that node (the value of the `dgraph.type`
> edges on that node and their corresponding definitions in the schema). If the type information
> ```

why remove this?
___
*[wiki/content/mutations/delete.md, line 67 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwOpWZ9Cr89EbxRkKC:-MIwOpWZ9Cr89EbxRkKD:bi6iwac) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md#L67)):*
> ```
> 'wildcard delete'
> ```
“Star notation” also is fine.
___
*[wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvQ8fA3AEPyYYfsB6g:-MIwUdPO4APr6jU-V0cf:b-qdy7rl) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo#L1)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

What's this file?
</blockquote></details>

Yeah, this file is a bit odd. Feels like a copy of the delete.md.
___
*[wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo, line 11 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwRel1EuWhnaOQl-RF:-MIwRel1EuWhnaOQl-RG:b-nmo4r7) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo#L11)):*
> ```
> A delete mutation, signified with the `delete` keyword, removes triples from the store. Note that you can only delete nodes if your data is typed using the `dgraph.type`predicate. For more imformation on setting the type of a node, see [Setting the type of a node](https://dgraph.io/docs/query-language/type-system/#setting-the-type-of-a-node).
> 
> For example, if the store contained the following:
> ```

add a space between the text and the code block.

**Review by bucanero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, @MichelDiz, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/mutations/delete.md, line 67 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwOpWZ9Cr89EbxRkKC:-MJ4Of7i-3n7zDbGQvzC:b-yjqysj) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md#L67)):*
<details><summary><i>Previously, MichelDiz (Michel Diz) wrote…</i></summary><blockquote>

> ```
> 'wildcard delete'
> ```
“Star notation” also is fine.
</blockquote></details>

if you keep "wildcard delete", I'd suggest linking it to the previous heading. Something like:

```
Using a [wildcard delete](#wildcard-delete) star notation mentioned...
```
___
*[wiki/content/mutations/delete.md, line 9 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MJ4O4Tn7BqRllftLuBw:-MJ4O4To0_CHZ-kl5FmP:bbzzoti) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6ddcbf4d6c353d58f5e7ff9be16e8097196067f/wiki/content/mutations/delete.md#L9)):*
> ```
> signified
> ```

Just a suggestion, I'd go with "identified" instead of signified

**Review by aaroncarey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, @MichelDiz, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/mutations/delete.md, line 43 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvPrxs3q1r40HXmFue:-MJTQyl_BpZkzs0Uzh9T:bkc2ng) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md#L43)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

Should this use this kind of note? 

{{% notice "note" %}}

</blockquote></details>

I moved this into a note, thanks!
___
*[wiki/content/mutations/delete.md, line 44 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvQFQu90Zt-F8flp1H:-MJTUR1t7PeG3lXIYlMq:bcz20i3) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md#L44)):*
<details><summary><i>Previously, MichaelJCompton (Michael Compton) wrote…</i></summary><blockquote>

Let's explicitly call out that it's `S * *` mutations that need types (the `S P *` ones will still work).

So maybe we should make this note like "The `S * *` mutation pattern ..."
</blockquote></details>

Done. Lines 45-47 call this out.
___
*[wiki/content/mutations/delete.md, line 9 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwLdj90z_T6gdh9N6l:-MJ5jYMH5H8iqW7SKg2j:btayxhi) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md#L9)):*
> ```
> predicates
> ```

Thanks for raising this, I definitely want to use the right word, here. I'd like to settle on the most widely-understood term that works for our users. I don't see the term "triple" used this way in the latest GraphQL spec (http://spec.graphql.org/June2018/#sec-Language.Fields). That spec makes me wonder if "Block String" or "Object" isn't really the term we are looking for. 

+++

After looking at this more closely, I'd like to avoid using the term "triple" here, as "predicate" or "field" seem to be the most widely-understood terms for the data contained within a node. 
___
*[wiki/content/mutations/delete.md, line 43 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwO9L03GH-7rA1tYxo:-MJTR-az9U501gJkXzkM:brdsluq) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6ddcbf4d6c353d58f5e7ff9be16e8097196067f/wiki/content/mutations/delete.md#L43)):*
<details><summary><i>Previously, MichelDiz (Michel Diz) wrote…</i></summary><blockquote>

why remove this?
</blockquote></details>

I reworked this material, nothing should be missing at this point
___
*[wiki/content/mutations/delete.md, line 67 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwOpWZ9Cr89EbxRkKC:-MJTQhCi6ZfAtDSyT132:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md#L67)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

if you keep "wildcard delete", I'd suggest linking it to the previous heading. Something like:

```
Using a [wildcard delete](#wildcard-delete) star notation mentioned...
```
</blockquote></details>

Done.
___
*[wiki/content/mutations/delete.md, line 9 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MJ4O4Tn7BqRllftLuBw:-MJT0JamDtXbBIzClFMI:bpx1ec7) ([raw file](https://github.com/dgraph-io/dgraph/blob/f6ddcbf4d6c353d58f5e7ff9be16e8097196067f/wiki/content/mutations/delete.md#L9)):*
<details><summary><i>Previously, bucanero (Damián Parrino) wrote…</i></summary><blockquote>

> ```
> signified
> ```

Just a suggestion, I'd go with "identified" instead of signified
</blockquote></details>

OK, done
___
*[wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo, line 1 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIvQ8fA3AEPyYYfsB6g:-MJTQlDS7qDcvdSQze1b:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/76b6db82fca2327abf94a88dc129bf2bfa1e6267/wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo#L1)):*
<details><summary><i>Previously, MichelDiz (Michel Diz) wrote…</i></summary><blockquote>

Yeah, this file is a bit odd. Feels like a copy of the delete.md.
</blockquote></details>

Done.
___
*[wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo, line 11 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwRel1EuWhnaOQl-RF:-MJTQmmfAFtYY6w7knc9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md.sb-e9c19abf-QiH8oo#L11)):*
<details><summary><i>Previously, MichelDiz (Michel Diz) wrote…</i></summary><blockquote>

add a space between the text and the code block.
</blockquote></details>

Done.

**Comment by aaroncarey** [comment]
https://dgraph-dc27d1337c-100924.surge.sh/mutations/delete/ Shows the current state of this document.

**Review by MichelDiz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, @MichelDiz, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/mutations/delete.md, line 9 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwLdj90z_T6gdh9N6l:-MJTb2p974wRxEjPPAGE:b7103ru) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md#L9)):*
<details><summary><i>Previously, aaroncarey (Aaron Carey) wrote…</i></summary><blockquote>

> ```
> predicates
> ```

Thanks for raising this, I definitely want to use the right word, here. I'd like to settle on the most widely-understood term that works for our users. I don't see the term "triple" used this way in the latest GraphQL spec (http://spec.graphql.org/June2018/#sec-Language.Fields). That spec makes me wonder if "Block String" or "Object" isn't really the term we are looking for. 

+++

After looking at this more closely, I'd like to avoid using the term "triple" here, as "predicate" or "field" seem to be the most widely-understood terms for the data contained within a node. 
</blockquote></details>

I think you didn't understand. This docs isn't GraphQL related. DQL is a totally different thing, and we use terms that define what Dgraph is. As you can see https://dgraph.io/docs/mutations/triples/  https://dgraph.io/docs/deploy/dgraph-administration/#deleting-database triples is a common thing in Dgraph. There are more references. This term comes from RDF standard. And it is a fundamental thing in Dgraph.

When you delete something, you are fundamentally deleting 3 information on the DB. It is like KV, when you delete a value from a KV, you are the Key and the Value. Another example. When you delete a whole node in Dgraph. You are actually deleting all triples, not just the values.

"Predicate" is just the "name of the key". In Dgraph when you say you are deleting a predicate, it is understood that you did not delete other information. 

Check this conversation a bit https://dgraphlabs.slack.com/archives/CSEFVTFQU/p1594243043106000?thread_ts=1594222913.084400&cid=CSEFVTFQU

**Review by aaroncarey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, @MichelDiz, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/mutations/delete.md, line 9 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-MIwLdj90z_T6gdh9N6l:-MJTw6nu3-ktoai24opt:b2puoxx) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bcdfadd01e0818a93feeadfc49ea542bef64aac/wiki/content/mutations/delete.md#L9)):*
<details><summary><i>Previously, MichelDiz (Michel Diz) wrote…</i></summary><blockquote>

I think you didn't understand. This docs isn't GraphQL related. DQL is a totally different thing, and we use terms that define what Dgraph is. As you can see https://dgraph.io/docs/mutations/triples/  https://dgraph.io/docs/deploy/dgraph-administration/#deleting-database triples is a common thing in Dgraph. There are more references. This term comes from RDF standard. And it is a fundamental thing in Dgraph.

When you delete something, you are fundamentally deleting 3 information on the DB. It is like KV, when you delete a value from a KV, you are the Key and the Value. Another example. When you delete a whole node in Dgraph. You are actually deleting all triples, not just the values.

"Predicate" is just the "name of the key". In Dgraph when you say you are deleting a predicate, it is understood that you did not delete other information. 

Check this conversation a bit https://dgraphlabs.slack.com/archives/CSEFVTFQU/p1594243043106000?thread_ts=1594222913.084400&cid=CSEFVTFQU
</blockquote></details>

Thanks for the clarification! I reviewed the links you provided and I have updated references back to "triple" where appropriate. Please take another look.

**Review by MichelDiz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-:-MJTyPFq49dldBaPzTEn:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, @MichelDiz, @pawanrawal, and @vvbalaji-dgraph)

**Review by aaroncarey — COMMENTED** [review]
I think I have all of your feedback addressed, let me know if I missed anything :)

**Review by bucanero — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-:-MJU9kFL7ivq0SUeNAbf:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, @MichelDiz, @pawanrawal, and @vvbalaji-dgraph)

**Review by aaroncarey — COMMENTED** [review]
Doc updated per your feedback!

**Review by aaroncarey — COMMENTED** [review]
Extra file deleted, now using a better markdown editor 👍

**Review by aaroncarey — COMMENTED** [review]
Feedback addressed, thanks!

**Review by aaroncarey — COMMENTED** [review]
Requested fixes implemented

**Review by MichaelJCompton — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6657#-:-MJV-dH6AWILLYJ07MGB:bg7igkv)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, @MichelDiz, @pawanrawal, and @vvbalaji-dgraph)

**Pull request merged**
