### PR TITLE
Reorganize the dgraph --help output

### PR DESCRIPTION
**Pull request by OmarAyo**
- Organize dgraph commands into categories
- Add custom templates
- move out decrypt tool from tool command and remove tool command

Current output of help:
```
[Decoder]: Using assembly version of decoder
Page Size: 4096
Dgraph is a horizontally scalable and distributed graph database,
providing ACID transactions, consistent replication and linearizable reads.
It's built from the ground up to perform for a rich set of queries. Being a native
graph database, it tightly controls how the data is arranged on disk to optimize
for query performance and throughput, reducing disk seeks and network calls in a
cluster.
Dgraph version   : v20.11.0-rc1-272-gf20a20621
Dgraph codename  : unnamed-mod
Dgraph SHA-256   : 995da770831afdbf5d666a2a31439246d0b00b72e50ef05e5dd701da30352866
Commit SHA-1     : f20a20621
Commit timestamp : 2021-01-13 18:23:22 +0530
Branch           : omar/custom-help
Go version       : go1.14.3
jemalloc enabled : true

For Dgraph official documentation, visit https://dgraph.io/docs/.
For discussions about Dgraph     , visit https://discuss.dgraph.io.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2020 Dgraph Labs, Inc.

Usage:
  dgraph [command] 

Generic:            
 help          Help about any command        
 version       Prints the dgraph version details 

Available Commands:

Dgraph Core:   
  alpha         Run Dgraph Alpha database server                  
  zero          Run Dgraph Zero management server 

Data Loading:    
  bulk          Run Dgraph Bulk Loader          
  live          Run Dgraph Live Loader    
  restore       Restore backup from Dgraph Enterprise Edition   

Dgraph Security:  
  acl           Run the Dgraph Enterprise Edition ACL tool   
  cert          Dgraph TLS certificate management                

Dgraph Debug:        
  debug         Debug Dgraph instance 
  debuginfo     Generate debug info on the current node            

Dgraph Tools:      
  completion    Generates shell completion scripts for bash or zsh 
  conv          Dgraph Geo file converter   
  decrypt       Run the Dgraph decryption tool 
  export_backup Export data inside single full or incremental backup.  
  increment     Increment a counter transactionally  
  lsbackup      List information on backups in a given location 
  migrate       Run the Dgraph migration tool 
  raftmigrate   Run the Raft migration tool  
  upgrade       Run the Dgraph upgrade tool  

Flags:
      --alsologtostderr                  log to standard error as well as files
      --bindall                          Use 0.0.0.0 instead of localhost to bind to all addresses on local machine. (default true)
      --block_rate int                   Block profiling rate. Must be used along with block profile_mode
      --config string                    Configuration file. Takes precedence over default values, but is overridden to values set with environment variables and flags.
      --cwd string                       Change working directory to the path specified. The parent must exist.
      --expose_trace                     Allow trace endpoint to be accessible from remote
  -h, --help                             help for dgraph
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
      --profile_mode string              Enable profiling mode, one of [cpu, mem, mutex, block]
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "dgraph [command] --help" for more information about a command.

``` 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7287)

### CODE REVIEW

**Comment by aaroncarey** [comment]
Suggested edits:
"It's built from ground up to perform for a rich set of queries." -> "It's built from the ground up to perform for a rich set of queries." [add "the"]

For the category labels:

Please add a row of whitespace between "Available Commands:" and "Dgraph Core"

"Dgraph Core" is probably OK - nothing better occurs to me that isn't excessively wordy; but, this isn't a section name that we can use in the docs, which need to clarify that you use Dgraph Alpha and Dgraph Zero for deployment, but you also need to use them for admin tasks post-deployment.  So while we want to make our categories here align with our doc structure as much as possible, we will need to allow some variation because `dgraph alpha` and `dgraph zero` aren't used just for deployment, or just for post-deployment admin - they are used in both situations. Anyway, we can clarify what these commands do by enhancing their descriptions a bit (below).

"Run Dgraph Alpha" -> "Run Dgraph Alpha database server" ["database server" is the shortest accurate description I can come up with for the Dgraph Alpha server that houses and serves data. If we want to reflect the /admin endpoint here, we could call it a "database and /admin endpoint server".]

"Run Dgraph Zero" -> "Run Dgraph Zero management server" [We could go with "Run Dgraph Zero cluster management server", but I worry that readers would read "cluster management" as not applicable if they are doing single-server evaluation setup - "management server" is the shortest way I can think to accurately describe a Dgraph Zero server's purpose.]

"live loader" -> "Live Loader"
"bulk loader" -> "Bulk Loader"
(both per usage at https://dgraph.io/docs/deploy/fast-data-loading/overview/)

"Run Dgraph (EE) Restore backup" -> "Restore backup from Dgraph Enterprise Edition" [If this is too verbose, we could go with "Run Dgraph (EE) backup restore"]

"Run the Dgraph acl tool" -> "Run the Dgraph Enterprise Edition ACL tool" [capitalize the ACL acronym - if this is too long, we could go with simply "Run the Dgraph (EE) ACL tool"]

"Generate debug info on the current node." -> "Generate debug info on the current node" [cut the period]

"Run Decrypt tool " -> "Run the Dgraph decryption tool" [This is parallel to the usage shown for other tools below. Also, we probably don't want to make this a proper noun, since the term is so generic.]

"Export data inside single full or incremental backup. " -> "Export data inside a single full or incremental backup" [cut the period, add "a"]

"List info on backups in given location" -> "List information about backups in a given location" [add "a"]

"Run the raft migrate tool" -> "Run the Raft migrate tool" (proper noun usage of "Raft" per first paragraph shown here: https://raft.github.io/)

Here is an edit of the command listing with all of these changes:

```
Available Commands:

Dgraph Core:   
  alpha         Run Dgraph Alpha database server                  
  zero          Run Dgraph Zero management server

Data Loading:    
  bulk          Run Dgraph Bulk Loader          
  live           Run Dgraph Live Loader    
  restore     Restore backup from Dgraph Enterprise Edition   

Dgraph Security:  
  acl           Run the Dgraph Enterprise Edition ACL tool   
  cert         Dgraph TLS certificate management                

Dgraph Debug:        
  debug       Debug Dgraph instance 
  debuginfo     Generate debug info on the current node.            

Dgraph Tools:       
  conv          Dgraph Geo file converter   
  decrypt       Run the Dgraph decryption tool 
  export_backup    Export data inside a single full or incremental backup  
  increment       Increment a counter transactionally  
  lsbackup      List information on backups in a given location 
  migrate       Run the Dgraph migrate tool 
  raftmigrate   Run the Raft migrate tool  
  upgrade       Run the Dgraph upgrade tool  
```

My only other feedback (not reflected above) is: If we moved `completion` out of the "Miscellaneous" category, and into "Dgraph Tools", we could rename "Miscellaneous" to "Help" (with just `help` under it). This is cleaner, and lets us avoid "Miscellaneous" a term that is best avoided when possible.

**Comment by OmarAyo** [comment]
@aaroncarey thanks, I've addressed your comments, please have a look a the current output (shown in the description of this PR)

**Comment by aaroncarey** [comment]
Thanks for these updates! 

It looks like you missed this one:
"Export data inside single full or incremental backup. " -> "Export data inside a single full or incremental backup" [cut the period, add "a"]

Also, I missed a small change in my initial review:
"Generate debug info on the current node" -> "Generate debug information on the current node" [info -> information]

**Comment by OmarAyo** [comment]
@aaroncarey thanks, done

**Comment by manishrjain** [comment]
Very nice. LGTM.

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 21 files at r3, 15 of 19 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7287)* status: all files reviewed, 1 unresolved discussion (waiting on @aaroncarey, @bucanero, @manishrjain, @NamanJain8, @OmarAyo, and @vvbalaji-dgraph)

___
*[x/x.go, line 1260 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/7287#-MR1lk0C7lUZhvGuw7Wa:-MR1lk0D5lVGZpeEvmMm:b-67gudh) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c2f0bc1c7e9176c5a6cd85d5c5c67e8d1195aec/x/x.go#L1260)):*
> ```
> Additional help topics:{{range .Commands}}{{if .IsAdditionalHelpTopicCommand}}
>   {{rpad .CommandPath .CommandPathPadding}} {{.Short}}{{end}}{{end}}{{end}}{{if .HasAvailableSubCommands}}
> ```
Does any command populate "Additional help topics"? I see it as empty when running `dgraph alpha --help` or `dgraph live --help`.

If nothing uses this, then we can hide this section header.

What prevents it from showing up for the root command `dgraph --help`?

**Comment by OmarAyo** [comment]
___
*[x/x.go, line 1260 at r8](https://reviewable.io/reviews/dgraph-io/dgraph/7287#-MR1lk0C7lUZhvGuw7Wa:-MR5EKAcEgFDFlINEOzy:b17yecc) ([raw file](https://github.com/dgraph-io/dgraph/blob/9c2f0bc1c7e9176c5a6cd85d5c5c67e8d1195aec/x/x.go#L1260)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Additional help topics:{{range .Commands}}{{if .IsAdditionalHelpTopicCommand}}
>   {{rpad .CommandPath .CommandPathPadding}} {{.Short}}{{end}}{{end}}{{end}}{{if .HasAvailableSubCommands}}
> ```
Does any command populate "Additional help topics"? I see it as empty when running `dgraph alpha --help` or `dgraph live --help`.

If nothing uses this, then we can hide this section header.

What prevents it from showing up for the root command `dgraph --help`?
</blockquote></details>

Nope, nothing is populating "Additional help topics" hence I've removed it. I've added a section called "Additional Commands" that will print all new commands that do not have `.AnnotationGroup` defined - this is the case when we add a new command and who add it forget to `AnnotationGroup` to it. 

As of now, is commented out in order to avoid printing it empty for `dgraph --help`. As soon as we have new commands, I will uncomment it to show the new available commands

**Review by aaroncarey — APPROVED** [review]
> Reviewed 2 of 21 files at r3, 15 of 19 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7287)* status: all files reviewed, 1 unresolved discussion (waiting on @bucanero, @danielmai, @manishrjain, @NamanJain8, and @vvbalaji-dgraph)

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7287#-:-MRzNrPiEu7d4HrjYj7J:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bucanero, @danielmai, @manishrjain, @NamanJain8, and @vvbalaji-dgraph)

**Pull request merged**
