### PR TITLE
[Breaking] Consolidate multiple flags into a few SuperFlags

### PR DESCRIPTION
**Pull request by karlmcguire**
(This is related to DGRAPH-3026.)

| Old Name | Old Type | New Name | New Type | `Al` | `Ze` | `Bu` | `Ba` | `Li` | `De` |
|---------:|:---------|---------:|:---------|:----:|:----:|:----:|:----:|:----:|:----:|
| | | **`--badger`** | | |
| `badger.compression` | string | `compression` | string | :green_circle: | | :green_circle: | :green_circle: | | |
| | | (new) `goroutines` | int | :green_circle: | | :green_circle: | :green_circle: | | |
| `badger.cache_mb` | string | `cache-mb` | string | | | :green_circle: | | | |
| `badger.cache_percentage` | string | `cache-percentage` | string | | | :green_circle: | | | |
| | | **`--acl`** | |
| `acl_secret_file` | string | `secret-file` | string | :green_circle: | | | | | |
| `acl_access_ttl` | time.Duration | `access-ttl` | [string](https://github.com/dgraph-io/ristretto/blob/master/z/flags.go#L80-L98) | :green_circle: | | | | | |
| `acl_refresh_ttl` | time.Duration | `refresh-ttl` | [string](https://github.com/dgraph-io/ristretto/blob/master/z/flags.go#L80-L98) | :green_circle: | | | | | | 
| | | **`--ludicrous`** | | 
| `ludicrous_mode` | bool | `enabled` | bool | :green_circle: | | | | | |
| `ludicrous_concurrency` | int | `concurrency` | int | :green_circle: | | | | | |
| | | **`--graphql`** | |
| `graphql_introspection` | bool | `introspection` | bool | :green_circle: | | | | | |
| `graphql_debug` | bool | `debug` | bool | :green_circle: | | | | | |
| `graphql_extensions` | bool | `extensions` | bool | :green_circle: | | | | | |
| `graphql_poll_interval` | time.Duration | `poll-interval` | [string](https://github.com/dgraph-io/ristretto/blob/master/z/flags.go#L80-L98) | :green_circle: | | | | | |
| `graphql_lambda_url` | string | `lambda-url` | string | :green_circle: | | | | | |
| | | **`--raft`** | |
| `pending_proposals` | int | `pending-proposals` | int | :green_circle: | | | | | |
| `idx` | int | `idx` | int | :green_circle: | :green_circle: | | | | |
| `group` | int | `group` | int | :green_circle: | | | | | |
| `learner` | bool | `learner` | bool | :green_circle: | :green_circle: | | | | |
| `snapshot-after` | int | `snapshot-after` | bool | :green_circle: | | | | | |
| | | **`--security`** | | 
| `auth_token` | string | `token` | string | :green_circle: | | | | | |
| `whitelist` | string | `whitelist` | string | :green_circle: | | | | | |
| | | **`--limit`** | | 
| `query_edge_limit` | uint64 | `query-edge` | uint64 | :green_circle: | | | | | |
| `normalize_node_limit` | int | `normalize-node` | int | :green_circle: | | | | | |
| `mutations_nquad_limit` | int | `mutations-nquad` | int | :green_circle: | | | | | |
| | | **`--tls`** | |
| `tls_cacert` | string | `cacert` | string | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | |
| `tls_use_system_ca` | bool | `use-system-ca` | bool | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle:| |
| `tls_server_name` | string | `server-name` | string | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | |
| `tls_client_auth` | string | `client-auth` | string | :green_circle: | :green_circle: | | | | |
| `tls_node_cert` | string | `node-cert` | string | :green_circle: | :green_circle: | | | | |
| `tls_node_key` | string | `node-key` | string | :green_circle: | :green_circle: | | | | |
| `tls_internal_port_enabled` | bool | `internal-port-enabled` | bool | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | |
| `tls_cert` | string | `cert` | string | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | |
| `tls_key` | string | `key` | string | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | |
| | | **`--trace`** | |
| `trace` | float64 | `ratio` | float64 | :green_circle: | :green_circle: | | | | |
| `jaeger.collector` | string | `jaeger` | string | :green_circle: | :green_circle: | | | | |
| `datadog.collector` | string | `datadog` | string | :green_circle: | :green_circle: | | | | |
| | | **`--vault`** | |
| `vault_addr` | string | `addr` | string | :green_circle: | | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| `vault_roleid_file` | string | `role-id-file` | string | :green_circle: | | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| `vault_secretid_file` | string | `secret-id-file` | string | :green_circle: | | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
| `vault_path` | string | `path` | string | :green_circle: | | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
| `vault_field` | string | `field` | string | :green_circle: | | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| `vault_format` | string | `format` | string | :green_circle: | | :green_circle: | :green_circle: | :green_circle: | :green_circle: |

**GC** stands for Grep Check which is when I run `grep -r -- "--old_flag_name" .` from Dgraph root directory to find (and replace) every instance of the old flag within test scripts, docker-compose files, docs, etc. 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7436)

### CODE REVIEW

**Review by manishrjain — CHANGES_REQUESTED** [review]
> Reviewed 5 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7436)* status: 5 of 30 files reviewed, 8 unresolved discussions (waiting on @danielmai, @karlmcguire, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 666 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl-xNM1iY5q4eiagFh:-MTl-xNM1iY5q4eiagFi:b-xrhi5y) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/dgraph/cmd/alpha/run.go#L666)):*
> ```Go
> 	}
> 
> 	acl := z.NewSuperFlag(Alpha.Conf.GetString("acl")).MergeAndCheckDefault(worker.AclDefaults)
> ```

ideally, this can just be parsed in the right package instead of here. 
___
*[dgraph/cmd/alpha/run.go, line 714 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl00ClAX7qfHcMTN09:-MTl00ClAX7qfHcMTN0A:b-9yq2b8) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/dgraph/cmd/alpha/run.go#L714)):*
> ```Go
> 		worker.LudicrousDefaults)
> 	raft := z.NewSuperFlag(Alpha.Conf.GetString("raft")).MergeAndCheckDefault(worker.RaftDefaults)
> 	x.WorkerConfig = x.WorkerOptions{
> ```

Ideally, worker options only contains the SuperFlags, and lets the modules do what they need to with them.
___
*[edgraph/server.go, line 578 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl0G7gAbF7rYWWfMXR:-MTl0G7gAbF7rYWWfMXS:b-y41elg) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/edgraph/server.go#L578)):*
> ```Go
> 	qc.span.Annotatef(nil, "Txn Context: %+v. Err=%v", resp.Txn, err)
> 
> 	if x.WorkerConfig.Ludicrous.GetBool("enabled") {
> ```

this happens on every mutate, so we should store the bool result instead of parsing it every time.
___
*[edgraph/server.go, line 838 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl0RUq7e4vF8CUQoxI:-MTl0RUq7e4vF8CUQoxJ:b-dfn7f0) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/edgraph/server.go#L838)):*
> ```Go
> 	gmu.Del = updateValInNQuads(gmu.Del, qc, false)
> 	gmu.Set = updateValInNQuads(gmu.Set, qc, true)
> 	if qc.nquadsCount > int(x.Config.Limit.GetInt64("mutations-nquad")) {
> ```

if this is happening in the query or mutate path, we should parse once and use repeatedly.
___
*[ee/enc/vault_ee.go, line 62 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl0ny8Ao6QTisDE26O:-MTl0ny8Ao6QTisDE26P:b-yppwm6) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/ee/enc/vault_ee.go#L62)):*
> ```Go
> }
> 
> func newVaultKeyReader(vaultFlag *z.SuperFlag, cfg *viper.Viper) (*vaultKeyReader, error) {
> ```

do we need cfg anymore?
___
*[graphql/schema/response.go, line 78 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl17u_4tc1bu28Ggry:-MTl17ua6E6neh9KEFJ_:bgs4fu8) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/graphql/schema/response.go#L78)):*
> ```Go
> 	}
> 
> 	if !x.Config.GraphQL.GetBool("debug") && strings.Contains(err.Error(), "authorization failed") {
> ```

same thing here. If this is the critical path, parse once and use repeatedly.
___
*[x/flags.go, line 36 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl1mdO9R3s-DuU7LYB:-MTl1mdO9R3s-DuU7LYC:b-p8epzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/x/flags.go#L36)):*
> ```Go
> 	// datadog: See https://github.com/DataDog/opencensus-go-exporter-datadog/issues/34
> 	//          about the status of supporting annotation logs through the datadog exporter
> 	flag.String("trace", "",
> ```

You can put the TraceDefaults string here.
___
*[x/flags.go, line 38 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl1kia5HHB-YHnvBXa:-MTl1kia5HHB-YHnvBXb:b-2htd5s) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/x/flags.go#L38)):*
> ```Go
> 	flag.String("trace", "",
> 		`Trace options (defaults shown):
> 	ratio=0.01; The ratio of queries to trace.
> ```

Don't hard code the default here, if you have a variable for it.

**Review by karlmcguire — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7436)* status: 5 of 30 files reviewed, 8 unresolved discussions (waiting on @danielmai, @karlmcguire, @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/server.go, line 578 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl0G7gAbF7rYWWfMXR:-MTm-KMlC_qUv1FdldZ4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/edgraph/server.go#L578)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

this happens on every mutate, so we should store the bool result instead of parsing it every time.
</blockquote></details>

Done.
___
*[edgraph/server.go, line 838 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl0RUq7e4vF8CUQoxI:-MTm-LPX5YQBaPNYad-3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/edgraph/server.go#L838)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if this is happening in the query or mutate path, we should parse once and use repeatedly.
</blockquote></details>

Done.
___
*[ee/enc/vault_ee.go, line 62 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl0ny8Ao6QTisDE26O:-MTm-MUH7HmTwerV--8K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/ee/enc/vault_ee.go#L62)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

do we need cfg anymore?
</blockquote></details>

Done.
___
*[graphql/schema/response.go, line 78 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl17u_4tc1bu28Ggry:-MTm-NMn5zg7jDTkDpMD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/graphql/schema/response.go#L78)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same thing here. If this is the critical path, parse once and use repeatedly.
</blockquote></details>

Done.
___
*[x/flags.go, line 36 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl1mdO9R3s-DuU7LYB:-MTm-Pd0DiaaQil3hjRn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/x/flags.go#L36)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can put the TraceDefaults string here.
</blockquote></details>

Done.

**Review by manishrjain — CHANGES_REQUESTED** [review]
> Reviewed 4 of 91 files at r2, 3 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7436)* status: 7 of 104 files reviewed, 11 unresolved discussions (waiting on @danielmai, @karlmcguire, @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 235 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MU9QslMDqvVZKPrmZY0:-MU9QslMDqvVZKPrmZY1:b-7tllta) ([raw file](https://github.com/dgraph-io/dgraph/blob/9328bb073c557771ab719153096ac624e0655529/dgraph/cmd/alpha/run.go#L235)):*
> ```Go
> 			`The SASL password for Kafka.`).
> 		Flag("ca-cert",
> 			`The path to CA cert file for TLS encryption.`).
> ```

no need to use backticks if it fits in one line.
___
*[edgraph/server.go, line 922 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MU9RbKbBeiywbjQq_UN:-MU9RbKbBeiywbjQq_UO:b-ykn7cq) ([raw file](https://github.com/dgraph-io/dgraph/blob/9328bb073c557771ab719153096ac624e0655529/edgraph/server.go#L922)):*
> ```Go
> 
> 		qc.nquadsCount += len(newSubs) * len(newObs)
> 		if qc.nquadsCount > int(x.Config.Limit.GetInt64("query-edge")) {
> ```

I think you could use a sync.Once , and put these limits in a local variable, or a local struct. SEe below.

Or, this package should have its own struct, which is holding the relevant options.

`map[string]interface{}`
When we say GetInt64 -> put that into the map (or maybe via an init or something).

i := m[query-edge]
return i.(int64) # I think that should be cheap??

Either this, or create a struct upfront per package.
___
*[edgraph/server.go, line 1197 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MU9SS1aEvMUA9S6SDX-:-MU9SS1aEvMUA9S6SDX0:b-p1ltyo) ([raw file](https://github.com/dgraph-io/dgraph/blob/9328bb073c557771ab719153096ac624e0655529/edgraph/server.go#L1197)):*
> ```Go
> 	// For mutations, we update the startTs if necessary.
> 	if isMutation && req.req.StartTs == 0 {
> 		if x.WorkerConfig.Ludicrous.GetBool("enabled") {
> ```

Just ensure that we're not doing this parsing in the critical path.

**Review by jarifibrahim — APPROVED** [review]

**Review by karlmcguire — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7436)* status: 5 of 103 files reviewed, 11 unresolved discussions (waiting on @danielmai, @karlmcguire, @manishrjain, @martinmr, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 666 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl-xNM1iY5q4eiagFh:-MUAcuxzDROBYbfUfnr1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/dgraph/cmd/alpha/run.go#L666)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ideally, this can just be parsed in the right package instead of here. 
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 714 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MTl00ClAX7qfHcMTN09:-MUAcw0c1AKvGXjLCRuj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/63b5dfdec3cb15c37b71c5ee4364207ba44554cc/dgraph/cmd/alpha/run.go#L714)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Ideally, worker options only contains the SuperFlags, and lets the modules do what they need to with them.
</blockquote></details>

Done.
___
*[dgraph/cmd/alpha/run.go, line 235 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MU9QslMDqvVZKPrmZY0:-MUAct_gAVq9YOqmrtNz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9328bb073c557771ab719153096ac624e0655529/dgraph/cmd/alpha/run.go#L235)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

no need to use backticks if it fits in one line.
</blockquote></details>

Done.
___
*[edgraph/server.go, line 1197 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7436#-MU9SS1aEvMUA9S6SDX-:-MUAcyZ351kEsOr3-iMG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9328bb073c557771ab719153096ac624e0655529/edgraph/server.go#L1197)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just ensure that we're not doing this parsing in the critical path.
</blockquote></details>

Done.

**Pull request merged**
