### PR TITLE
Add script to redeploy dgraph

### PR DESCRIPTION
**Pull request by pawanrawal**
We will have a server to which docs on master branch would point to. This script would run every night on this server, rebuild dgraph and reload all the data.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/877)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/reload/reload.sh, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/877#-KiYC_EuAoWfEq8U6sEE:-KiYC_Ev6HKUhU-_TheQ:b9t5nel) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1bfac4580ad1dbbed768f5cae8ba17b6233a05e/contrib/reload/reload.sh#L75)):*
> ```Shell
> mkdir -p ~/dgraph/$latestCommit && cd ~/dgraph/$latestCommit
> # Starting Dgraph in background and outputting log to file.
> $dgraphRepo/cmd/dgraph/dgraph --port 8082 --workerport 12346 > dgraph.log 2>&1 &
> ```

Can you check how would the script behave if latestcommit remains same. 

Should be fine mostly, the script would due to non-zero exit code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/877#-:-KiYFJ5OdIkl2D1MVH0f:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/reload/reload.sh, line 75 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/877#-KiYC_EuAoWfEq8U6sEE:-KiYtzHMF-sbxcz1qdIv:byrzp22) ([raw file](https://github.com/dgraph-io/dgraph/blob/f1bfac4580ad1dbbed768f5cae8ba17b6233a05e/contrib/reload/reload.sh#L75)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Can you check how would the script behave if latestcommit remains same. 

Should be fine mostly, the script would due to non-zero exit code.
</blockquote></details>

Actually changed it so that folder name has current ts also. It would run everyday this way (would also work in case there are any changes in dataset or schema).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/877)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/877#-:-KiYwSre7lo9MJypNiba:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/877#-:-KiZJM8LpNCkIOXiib28:bnfp4nl)*

**Comment by pawanrawal** [comment]
merged

**Pull request closed without merging**
