### PR TITLE
dropall mutation

### PR DESCRIPTION
**Pull request by peterstace**
We can now drop all edges and schema using:

```
mutation {
    dropall {}
}
```

Or by setting the `DropAll` flag in `Mutation` via gRPC. I also added a helper function to the Go client.

There's an integration test that uses a `mutation { dropall {} }` query. Testing for the gRPC flag was manual (most of the code is common).

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1547)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/examples_test.go, line 522 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1547#-Kv0x7o8-xRd1xdyDV-e:-Kv0x7o9hSR1geBKf-Ts:b-dqyxyv) ([raw file](https://github.com/dgraph-io/dgraph/blob/82eaf6ad38572b9c4ce7a157246f4dd154c4ae8d/client/examples_test.go#L522)):*
> ```Go
> 	defer os.RemoveAll(clientDir)
> 
> 	dgraphClient := client.NewDgraphClient([]*grpc.ClientConn{conn}, client.DefaultOptions, clientDir)
> ```

100 chars

---

*[client/mutations.go, line 549 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1547#-Kv0xTPKdVRMm9Hfw-05:-Kv0xTPKdVRMm9Hfw-06:b-5js522) ([raw file](https://github.com/dgraph-io/dgraph/blob/82eaf6ad38572b9c4ce7a157246f4dd154c4ae8d/client/mutations.go#L549)):*
> ```Go
> 
> // DropAll deletes all edges and schema from Dgraph.
> func (d *Dgraph) DropAll() error {
> ```

Add a similar batch to non-batching interface of client. It should be present in client/client.go

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1547#-:-Kv0yhBAZ-j-WSKPLLn-:bnfp4nl)*

**Comment by peterstace** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[client/examples_test.go, line 522 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1547#-Kv0x7o8-xRd1xdyDV-e:-Kv1-rHJ1ie3kLm4tfdC:b-b70n3r) ([raw file](https://github.com/dgraph-io/dgraph/blob/82eaf6ad38572b9c4ce7a157246f4dd154c4ae8d/client/examples_test.go#L522)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

100 chars
</blockquote></details>

Done. Fixed the other instances in this file as well.

---

*[client/mutations.go, line 549 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1547#-Kv0xTPKdVRMm9Hfw-05:-Kv11w3XVXDgiKD78oby:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/82eaf6ad38572b9c4ce7a157246f4dd154c4ae8d/client/mutations.go#L549)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Add a similar batch to non-batching interface of client. It should be present in client/client.go
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1547)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1547#-:-KvPBWi-_7c4mtZlwqef:bnfp4nl)*

**Comment by jimanvlad** [comment]
Can we have this in the HTTP client as well? It's useful when rapidly prototyping.

**Comment by pawanrawal** [comment]
@jimanvlad It is already there in the HTTP client https://docs.dgraph.io/clients/#alter-the-database-1.

**Comment by uuyuu** [comment]
> @jimanvlad It is already there in the HTTP client https://docs.dgraph.io/clients/#alter-the-database-1.
I do this， but get an error：
{
    "errors": [
        {
            "message": "truncate p\\000000.vlog: The requested operation cannot be performed on a file with a user-mapped section open.",
            "extensions": {
                "code": "Error"
            }
        }
    ]
}

**Pull request merged**
