### PR TITLE
Modify/health check and transfer leadership on shutdown

### PR DESCRIPTION
**Pull request by janardhan1993**
Remaining changes like failing health check if we don't receive hearbeats for a longer time could be done as part of cluster management.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/738)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/dgraph/main.go, line 586 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftViIMRy3hOQfcUKsm:-KftViIMRy3hOQfcUKsn:b-i1xatf) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/cmd/dgraph/main.go#L586)):*
> ```Go
> // This method is used to execute the query and return the response to the
> // client as a protocol buffer message.
> func (s *grpcServer) Run(ctx context.Context,
> ```

Put health check in `/query` as well. Just check for other endpoints as well.

---

*[worker/draft.go, line 283 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftWA0FoCER9c7M5mOQ:-KftWA0FoCER9c7M5mOR:b-ff874f) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/draft.go#L283)):*
> ```Go
> 	} else if proposal.Membership != nil {
> 		proposalData[0] = proposalMembership
> 	}
> ```

else { log.Fatalf(..) }

---

*[worker/draft.go, line 543 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftWir7y3VrOLIgn1Hw:-KftWir7y3VrOLIgn1Hx:bfqy7pc) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/draft.go#L543)):*
> ```Go
> 	defer ticker.Stop()
> 	rcBytes, err := n.raftContext.Marshal()
> 	x.Check(err)
> ```

var leader bool  // local variable.

---

*[worker/groups.go, line 30 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftUElp6W5pADyS944a:-KftUElqJnhvJHtltphI:bdb3l73) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/groups.go#L30)):*
> ```Go
> 	raftId      = flag.Uint64("idx", 1, "RAFT ID that this server will use to join RAFT groups.")
> 	schemaFile  = flag.String("schema", "", "Path to schema file")
> 	healthCheck bool
> ```

use int so, you can use atomics.

---

*[worker/groups.go, line 128 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftUGaypV3ZUA-ejFZv:-KftUGaypV3ZUA-ejFZw:b-d3hsos) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/groups.go#L128)):*
> ```Go
> 	// create split brain for same group id
> 	gr.syncMemberships()
> 	healthCheck = true
> ```

use atomics.

---

*[worker/groups.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftUHY2XkQd1wcE8YEF:-KftUHY2XkQd1wcE8YEG:b-s3xks5) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/groups.go#L136)):*
> ```Go
> // returning true
> func HealthCheck() bool {
> 	return healthCheck
> ```

atomics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-:-KftXFYOR7uFlybticmH:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 586 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftViIMRy3hOQfcUKsm:-Kg03r1DyghFzdwRKcsh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/cmd/dgraph/main.go#L586)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Put health check in `/query` as well. Just check for other endpoints as well.
</blockquote></details>

Done.

---

*[worker/draft.go, line 283 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftWA0FoCER9c7M5mOQ:-Kg03sPk12iAtt5-fKxa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/draft.go#L283)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

else { log.Fatalf(..) }
</blockquote></details>

Done.

---

*[worker/draft.go, line 543 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftWir7y3VrOLIgn1Hw:-Kg03tYhGBILmUt1VQwb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/draft.go#L543)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

var leader bool  // local variable.
</blockquote></details>

Done.

---

*[worker/groups.go, line 30 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftUElp6W5pADyS944a:-Kg03yMPdmHgEQjxlBaN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/groups.go#L30)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

use int so, you can use atomics.
</blockquote></details>

Done.

---

*[worker/groups.go, line 128 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftUGaypV3ZUA-ejFZv:-Kg04BgolJiieKod7Itv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/groups.go#L128)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

use atomics.
</blockquote></details>

Done.

---

*[worker/groups.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KftUHY2XkQd1wcE8YEF:-Kg04Dk4VccG5_T_B04z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/16b81f506dd938448aa1703f862a2d59c9315e4c/worker/groups.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

atomics.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/738)*

**Comment by gacharya255** [comment]
:lgtm:

---

Review status: 3 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[worker/backup.go, line 328 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KgSEsYfBV0Uvp30mW2U:-KgSEsYfBV0Uvp30mW2V:brg9v15) ([raw file](https://github.com/dgraph-io/dgraph/blob/7eb6845accabaa782bb62f980bd38781f32fa171/worker/backup.go#L328)):*
> ```Go
> func BackupOverNetwork(ctx context.Context) error {
> 	// If we haven't even had a single membership update, don't run backup.
> 	if !HealthCheck() {
> ```

Wonder if you need this for RebuildIndex as well?

---

*[worker/groups.go, line 107 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KgSDlbNnLPkXMThzZsi:-KgSDlbOfyyquTfKXyv7:b-g5s3br) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc5f6d2b20903bba0d2c3ed4b9dd4443a897c420/worker/groups.go#L107)):*
> ```Go
> 		node := gr.newNode(uint32(gid), *raftId, *myAddr)
> 		schema.ReloadData(*schemaFile, uint32(gid))
> 		go node.InitAndStartNode(gr.wal)
> ```

Might be better to do the defer wg.Done here. Reads a bit clearer and InitAndStartNode can care less.

go func() {
  defer wg.Done()
  node.Init(...)
}()

---

*[worker/groups.go, line 202 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KgSERLFc9UQn3t3JztC:-KgSERLFc9UQn3t3JztD:bo0okr3) ([raw file](https://github.com/dgraph-io/dgraph/blob/7eb6845accabaa782bb62f980bd38781f32fa171/worker/groups.go#L202)):*
> ```Go
> }
> 
> // Servers return addresses of all servers in group.
> ```

Fix comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-:-KgSF4pAY3h_zRjLcwhW:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: 3 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[worker/backup.go, line 328 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KgSEsYfBV0Uvp30mW2U:-KgSI6fBEK1fmE5uVtc8:baks3d9) ([raw file](https://github.com/dgraph-io/dgraph/blob/7eb6845accabaa782bb62f980bd38781f32fa171/worker/backup.go#L328)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Wonder if you need this for RebuildIndex as well?
</blockquote></details>

This branch is little old, index handler(rebuild index) endpoint has been removed. We do schema changes through gql now.

---

*[worker/groups.go, line 107 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KgSDlbNnLPkXMThzZsi:-KgSKCjX5GoI7saCn_iT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fc5f6d2b20903bba0d2c3ed4b9dd4443a897c420/worker/groups.go#L107)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Might be better to do the defer wg.Done here. Reads a bit clearer and InitAndStartNode can care less.

go func() {
  defer wg.Done()
  node.Init(...)
}()
</blockquote></details>

Done.

---

*[worker/groups.go, line 202 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/738#-KgSERLFc9UQn3t3JztC:-KgSIcWJRBCjSB8_PODP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7eb6845accabaa782bb62f980bd38781f32fa171/worker/groups.go#L202)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Fix comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/738)*

**Comment by janardhan1993** [comment]
Merged

**Pull request closed without merging**
