### PR TITLE
Mark supplied uids and xids in mutation as _taken_

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/308)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 130 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYIcsbRKv757_wDo1j:-KVYIcscEoYOnv57T70x:b-saj9wq) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L130)):*
> ```Go
> 	var mr mutationResult
> 
> 	markUids := make(map[uint64]bool)
> ```

Why do this here? newUids are already written out to Rocksdb under `_uid_`.

---

*[rdf/parse.go, line 52 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYImmFvFPENVKpAR7r:-KVYImmFvFPENVKpAR7s:btp6kx9) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/rdf/parse.go#L52)):*
> ```Go
> 	return farm.Fingerprint64([]byte(xid)), nil
> }
> ```

You deleted comment?

---

*[worker/assign.go, line 42 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYIz8bUO-F29QmFdnw:-KVYIz8bUO-F29QmFdnx:b-ifncc0) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/worker/assign.go#L42)):*
> ```Go
> }
> 
> func createMarkListQuery(group uint32, umap map[uint64]bool) []byte {
> ```

I don't think you need this MarkList.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/308)*

**Comment by manishrjain** [comment]
Modify task.Num to pass in a list of uint64s, which could be proposed. And then you could modify assignUids to generate the right mutations. That an easy piggybacking of a system that we already have in place.

---

Review status: all files reviewed at latest revision, 23 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 133 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYKVWLiA6nRZfJCCbU:-KVYKVWLiA6nRZfJCCbV:b-52lvkc) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L133)):*
> ```Go
> 	newUids := make(map[string]uint64)
> 	for _, nq := range nquads {
> 		if strings.HasPrefix(nq.Subject, "_new_:") {
> ```

If you're given _xid_:, pass it down as well, just like we used to do before.

---

*[cmd/dgraph/main.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYK2XvVXimD48JvLO2:-KVYK2XwLiI1eLD62_q2:bveml3c) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L136)):*
> ```Go
> 			newUids[nq.Subject] = 0
> 		} else {
> 			uid, err := rdf.GetUid(nq.Subject)
> ```

What this is going to do is even if the user is specifying `_uid_:`, you'd still send out an update mark. And because every mutation needs to convert edges, every one of them will send out a network call to uid assigner server before we can apply that mutation. That is bad design.

---

*[cmd/dgraph/main.go, line 153 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYKSpHmmGvjjxBZkuc:-KVYKSpHmmGvjjxBZkud:b-4fcjyq) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L153)):*
> ```Go
> 
> 	if len(markUids) > 0 {
> 		if err := worker.MarkUidsOverNetwork(ctx, markUids); err != nil {
> ```

You don't need MarkUids at all. Remove all that.

---

*[worker/assign.go, line 96 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYKfabviA0ktvtSQY5:-KVYKfabviA0ktvtSQY6:bd7dsii) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/worker/assign.go#L96)):*
> ```Go
> }
> 
> func markUids(ctx context.Context, mlist *task.MarkList) (rerr error) {
> ```

Remove all this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-:-KVYMRNlQ3ds-tdxnQ4t:b-fnjy0h)*

**Comment by ashwin95r** [comment]
Review status: 3 of 8 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 130 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYIcsbRKv757_wDo1j:-KVYp9abEJWEkQOoN17O:b-o1caj8) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L130)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why do this here? newUids are already written out to Rocksdb under `_uid_`.
</details>
This is to collect all the UIDs (that we get through XID fp) and send them for marking.

---

*[cmd/dgraph/main.go, line 133 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYKVWLiA6nRZfJCCbU:-KVYpQbTodT2NcECS8TT:bs1ewvy) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L133)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> If you're given _xid_:, pass it down as well, just like we used to do before.
</details>
Passing the fp UIDs using the mark list. For new, we pass the number of UIDs needed and get back N UIDs. But for XIDs we know the UID and we need to send them to be marked. Am I missing something?

---

*[cmd/dgraph/main.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYK2XvVXimD48JvLO2:-KVYoXJKPhFMAmFWuF3J:b-i7m6s4) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> What this is going to do is even if the user is specifying `_uid_:`, you'd still send out an update mark. And because every mutation needs to convert edges, every one of them will send out a network call to uid assigner server before we can apply that mutation. That is bad design.
</details>
Initially, I thought we'd be marking _uid_ as well. Changed it to marking only XIDs.

---

*[cmd/dgraph/main.go, line 153 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYKSpHmmGvjjxBZkuc:-KVYof2XddUflS9uRJaf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L153)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You don't need MarkUids at all. Remove all that.
</details>
Done.

---

*[rdf/parse.go, line 52 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYImmFvFPENVKpAR7r:-KVYojmX0OfFjTOtfqn7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/rdf/parse.go#L52)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You deleted comment?
</details>
Done.

---

*[worker/assign.go, line 42 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYIz8bUO-F29QmFdnw:-KVYp5KLBvz7ICpTQ-p8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/worker/assign.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I don't think you need this MarkList.
</details>
Done.

---

*[worker/assign.go, line 96 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYKfabviA0ktvtSQY5:-KVYp4FouR_YlmlynzaG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/worker/assign.go#L96)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove all this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/308)*

**Comment by ashwin95r** [comment]
Review status: 2 of 8 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 133 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVYKVWLiA6nRZfJCCbU:-KVZH_PdxVSYbq0xm7iA:bf4zgsu) ([raw file](https://github.com/dgraph-io/dgraph/blob/356550e2e689da0dafcbaffc694b917b7ff8c85f/cmd/dgraph/main.go#L133)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Passing the fp UIDs using the mark list. For new, we pass the number of UIDs needed and get back N UIDs. But for XIDs we know the UID and we need to send them to be marked. Am I missing something?
</details>
Okay, I have used the single map for both assigning and marking. Please do let me know if this looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/308)*

**Comment by manishrjain** [comment]
Reviewed 3 of 6 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[task/MarkList.go, line 2 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZfq6QqY3_eU1FcRER:-KVZfq6QqY3_eU1FcRES:b-ze0b7k) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/task/MarkList.go#L2)):*
> ```Go
> // automatically generated by the FlatBuffers compiler, do not modify
> ```

Delete this file.

---

*[uid/assigner.go, line 126 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZfvPOIfcGwaY11MaG:-KVZfvPOIfcGwaY11MaH:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/uid/assigner.go#L126)):*
> ```Go
> }
> 
> func MarkUsed(uid uint64) {
> ```

Remove this.

---

*[worker/assign.go, line 35 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZg8tm9DGGdja7jMDU:-KVZg8tm9DGGdja7jMDV:b-g3vr0h) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/worker/assign.go#L35)):*
> ```Go
> 	b := flatbuffers.NewBuilder(0)
> 
> 	count1, count2 := 0, 0
> ```

Give a better variable name. s/count1/newids s/count2/xids

---

*[worker/assign.go, line 81 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZga1lA3I72zaCQQjk:-KVZga1maEBXazmmpw_Z:b-xobvyw) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/worker/assign.go#L81)):*
> ```Go
> 	for i := 0; i < markNum; i++ {
> 		uid := num.Uids(i)
> 		mut := x.DirectedEdge{
> ```

I think we've used the variable name `m`, or `mu` for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/308)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 22 unresolved discussions, some commit checks failed.

---

*[task/MarkList.go, line 2 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZfq6QqY3_eU1FcRER:-KVZyiwCamezTBIM7dvD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/task/MarkList.go#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Delete this file.
</details>
Done.

---

*[uid/assigner.go, line 126 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZfvPOIfcGwaY11MaG:-KVZz2Uu7zibEe7NSO5j:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/uid/assigner.go#L126)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove this.
</details>
Done.

---

*[worker/assign.go, line 35 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZg8tm9DGGdja7jMDU:-KVZzO6_3A_JiO3fr-0U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/worker/assign.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Give a better variable name. s/count1/newids s/count2/xids
</details>
Done.

---

*[worker/assign.go, line 81 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-KVZga1lA3I72zaCQQjk:-KVZzVfRqSNhtJyUYQIc:bfb6990) ([raw file](https://github.com/dgraph-io/dgraph/blob/dd4dca877b611d3a0a7d8c91dec012b03cac8a7c/worker/assign.go#L81)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I think we've used the variable name `m`, or `mu` for this.
</details>
Done. Renamed to mu.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/308)*

**Comment by manishrjain** [comment]
:lgtm: Feel free to submit.

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/308#-:-KV_-ulWGBFdfarFpZtZ:b-vq34jq)*

**Comment by ashwin95r** [comment]
Thanks for the review. Merged.

**Pull request closed without merging**
