### PR TITLE
Call RunValueLogGC every 10 minutes from Dgraph

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1563)

### CODE REVIEW

**Comment by peterstace** [comment]
While we're making this change, I think it would be worthwhile reducing the GC interval from 10 minutes down to something lower, at least until we implement some smarter logic. See discussion here: https://github.com/dgraph-io/badger/issues/173

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1563#-:-KvUYFbZO-6uOLOKzINl:b9b77pn)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1563#-:-KvUYdmavsxNSE3JnOrZ:bnfp4nl)*

**Comment by pawanrawal** [comment]
Not sure what is a good interval here. Let's keep it at this for this release and figure out a better way to do this in next release. Value log is also going to change with the upcoming changes in Badger.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1563#-:-KvV42le8ia-Zo7b7dcK:b-19h3b7)*

**Comment by pawanrawal** [comment]
In master as of 7b64e51b2ca2a3c9e9a58db638b1d96ae9479f9b

**Pull request closed without merging**
