### PR TITLE
Fix tls and make the test suite pass again

### LINKED ISSUE #1691: dgraph doesn't start with tls on
I found this issue while looking at [this stackoverflow question](https://stackoverflow.com/questions/46836434/trouble-starting-dgraph-with-tls).
While checking the problem I discovered that this is a bug, which can be reproduced this way:

1. Run `dgraphzero -w zw`
2. Run `dgraph --config ~/web/dgraph-test/dgraph-min.yml`

It fails with `open : no such file or directory` error.

And the `dgraph-min.yml`:

    memory_mb: 4096
    peer: localhost:8888
    tls.on: true
    tls.cert: /home/seb/web/dgraph-test/test2.crt
    tls.cert_key: /home/seb/web/dgraph-test/test2.key

This can also be confirmed with the [tls test suite](https://github.com/dgraph-io/dgraph/tree/master/contrib/tlstest).
Running it confirmed the error, shell files to start the server required small adjustments (add ` --memory_mb 2048`) and then it fails with same error:

    $ cd contrib/tlstest 
    $ make
    -e 

    TESTING...

    Basic TLS communication, unencrypted keys
    ./server_nopass.sh <-> ./client_nocert.sh: 127 (expected: 0)
    Makefile:8: recipe for target 'test' failed
    make: *** [test] Error 1

    $ ./server_nopass.sh 
    ./server_nopass.sh: line 3: ../../cmd/dgraph/dgraph: No such file or directory

The issue seems to be in the [main.go](https://github.com/dgraph-io/dgraph/blob/master/cmd/dgraph/main.go#L438-L447).
Here the tls config is created, but not all the parameters are passed, for example, `tlsKey` and `tlsKeyPath` are missing.

Later, in the [tls_helper.go](https://github.com/dgraph-io/dgraph/blob/master/x/tls_helper.go#L187) there is an attempt to use these parameters and pass them over to the [parseCertificate](https://github.com/dgraph-io/dgraph/blob/master/x/tls_helper.go#L82), which fails on reading the certificate file because the path is empty.

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #1691

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1704)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraph/main.go, line 442 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1704#-KxkQza25l3Y5SQhiZoP:-KxkQza25l3Y5SQhiZoQ:bg6f8l7) ([raw file](https://github.com/dgraph-io/dgraph/blob/81ed5282b97a9043192e2751f6b9ed25e1be18a7/cmd/dgraph/main.go#L442)):*
> ```Go
> 			CertRequired:           tlsEnabled,
> 			Cert:                   tlsCert,
> 			Key:                    tlsKey,
> ```

Key and Pass were not being passed here.

---

*[cmd/dgraph-live-loader/main.go, line 311 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1704#-KxkR2wnO4uNuaoa41rj:-KxkR2wnO4uNuaoa41rk:bc7gb12) ([raw file](https://github.com/dgraph-io/dgraph/blob/81ed5282b97a9043192e2751f6b9ed25e1be18a7/cmd/dgraph-live-loader/main.go#L311)):*
> ```Go
> 	defer conn.Close()
> 
> 	connzero, err := setupConnection(*zero, true)
> ```

Zero doesn't support tls yet so we open an insecure connection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1704)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1704#-:-KxkSc1_1Lr0yqScEDVT:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1704#-:-KxkxLrrpjz-GeNprKDS:bnfp4nl)*

**Comment by pawanrawal** [comment]
Fix merged to `release/v0.8.3` and `master`.

**Pull request closed without merging**
