### PR TITLE
Add --maxroutines flag.

### PR DESCRIPTION
**Pull request by kostub**
Added the numGoroutines flag to dgraphassigner and dgraphloader. This
flag is used in the cases when too many concurrent goroutines can cause
the command to fail by exceeding the number of threads allowed on the
platform.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/188)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphassigner/main.go, line 35 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/188#-KQci1-1tKI-d6rHS--w:-KQci1-28HxO7lOmNZ-K:b-fpcbeo) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c7eb266a28942f5fbb6298d2d4e6cd0e5cab76f/cmd/dgraphassigner/main.go#L35)):*
> ```Go
> var numcpu = flag.Int("numCpu", runtime.NumCPU(),
> 	"Number of cores to be used by the process")
> var numGoroutines = flag.Int("numGoroutines", 3000,
> ```

flag name should not be camelcase. Maybe call it "maxroutines". Also, move this to where it's needed, i.e. loader/loader.go.

---

*[cmd/dgraphassigner/main.go, line 100 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/188#-KQcjx6GU-sqgcUpEER9:-KQcjx6GU-sqgcUpEERA:b-blz0uj) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c7eb266a28942f5fbb6298d2d4e6cd0e5cab76f/cmd/dgraphassigner/main.go#L100)):*
> ```Go
> 		}
> 
> 		count, err := loader.AssignUids(r, *instanceIdx, *numInstances, *numGoroutines)
> ```

You wouldn't need to pass this if the flag is defined in loader/loader.go.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/188)*

**Comment by kostub** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphassigner/main.go, line 35 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/188#-KQci1-1tKI-d6rHS--w:-KQdnbAR04d7P3RqL1rV:b-mm0s2v) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c7eb266a28942f5fbb6298d2d4e6cd0e5cab76f/cmd/dgraphassigner/main.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> flag name should not be camelcase. Maybe call it "maxroutines". Also, move this to where it's needed, i.e. loader/loader.go.
</details>
Most other flags are camel case. Though I like the maxroutines name better so I changed it.

---

*[cmd/dgraphassigner/main.go, line 100 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/188#-KQcjx6GU-sqgcUpEER9:-KQdo0YNHvMJcgcXRaeS:b-loh2ry) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c7eb266a28942f5fbb6298d2d4e6cd0e5cab76f/cmd/dgraphassigner/main.go#L100)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You wouldn't need to pass this if the flag is defined in loader/loader.go.
</details>
The flag shouldn't be defined in loader.go. Two reasons: Consistency and testability.
1. All the other flags are defined in the main file. Having flags scattered around the codebase can be quite confusing.
2. More importantly, the loader or any interface shouldn't read the environment directly. Everything that it needs should be passed in, either as parameters or interfaces. Otherwise you end up with a whole lot of untestable code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/188)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphassigner/main.go, line 35 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/188#-KQci1-1tKI-d6rHS--w:-KQj4PwYYbA8IgfoAhA5:b-jvrt17) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c7eb266a28942f5fbb6298d2d4e6cd0e5cab76f/cmd/dgraphassigner/main.go#L35)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Most other flags are camel case. Though I like the maxroutines name better so I changed it.
</details>
I meant the name of the flag which is shown to the user. Internally the variable name can be camelcase, that's alright. For e.g., you could have written:

`maxRoutines = flag.Int("maxroutines", 3000, ...)`

---

*[cmd/dgraphassigner/main.go, line 100 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/188#-KQcjx6GU-sqgcUpEER9:-KQj50RLTUcfpEfs86Td:b-8d1tmn) ([raw file](https://github.com/dgraph-io/dgraph/blob/7c7eb266a28942f5fbb6298d2d4e6cd0e5cab76f/cmd/dgraphassigner/main.go#L100)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> The flag shouldn't be defined in loader.go. Two reasons: Consistency and testability.
> 1. All the other flags are defined in the main file. Having flags scattered around the codebase can be quite confusing.
> 2. More importantly, the loader or any interface shouldn't read the environment directly. Everything that it needs should be passed in, either as parameters or interfaces. Otherwise you end up with a whole lot of untestable code.
</details>
We have defined other flags in non-main files. Running ack for `flag\.`
```
x/init.go:30:13:	version  = flag.Bool("version", false, "Prints the version of Dgraph")
posting/lists.go:44:17:var maxmemory = flag.Int("stw_ram_mb", 4096,
```

2. The thing I don't like with being strict about only defining flags in main, is that you need to duplicate the code, which is ugly, and then ensure that the naming is consistent across this duplication. Go treats flags, just like module level global variables. And variables should be defined closest to where they're being used. I think in this particular case, we're not going to test based on the number of goroutines in unit tests -- so I doubt there's any downside here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/188)*

**Comment by manishrjain** [comment]
:lgtm: Congrats on your first PR! :-)

---

Reviewed 1 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/188#-:-KR0txS4iCuxTcxFCyD5:b-tv6hb9)*

**Pull request closed without merging**
