### PR TITLE
Make dgraphloader remove LOCK upon interrupt

### PR DESCRIPTION
**Pull request by srh**
Make us handle interrupts ourselves, not in a particularly completionist way, so that if you Ctrl+C a dgraphloader run (and it's not hanging on a network connection or anything like that), the badger store gets cleanly Close()d.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1221)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/dgraphloader/main.go, line 266 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-KpTmGgA8SnsbbaOOcxp:-KpTmGgA8SnsbbaOOcxq:ba97t6z) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd298e29e58abd86581c66abd91fdf8d83a0a23b/cmd/dgraphloader/main.go#L266)):*
> ```Go
> 
> 	{
> 		vcCtx, vcCancel := context.WithTimeout(ctx, 1*time.Minute)
> ```

why not `ctx, cancel`? They're local scoped anyway, the naming looks better.

---

*[cmd/dgraphloader/main.go, line 333 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-KpTma906cX7RFp7aJ7E:-KpTma906cX7RFp7aJ7F:b-slp0p) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd298e29e58abd86581c66abd91fdf8d83a0a23b/cmd/dgraphloader/main.go#L333)):*
> ```Go
> 	fmt.Printf("Time spent                : %v\n", c.Elapsed)
> 
> 	fmt.Printf("RDFs processed per second : %d\n", rate)
> ```

No need to close client?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221)*

**Comment by manishrjain** [comment]
This can be reverted now?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-:-KpbiMDle_ctNoO7kc18:b2ic8ly)*

**Comment by srh** [comment]
I think we would still want to cleanly close the KV store (and write all the data in it) upon interruption.  Right now I don't know what the client uses a badger store for, so I'm saying this with a bit incomplete knowledge.  However, on Windows users still have to manually cleanup the LOCK file upon process exit, and apparently right now Badger isn't happy if there are partially written .sst files in the directory (going by https://github.com/dgraph-io/dgraph/issues/1231) so I think we should still catch Ctrl+C and cleanly close.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/main.go, line 266 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-KpTmGgA8SnsbbaOOcxp:-Kpl701PVf2YM_Ud2llG:buklequ) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd298e29e58abd86581c66abd91fdf8d83a0a23b/cmd/dgraphloader/main.go#L266)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

why not `ctx, cancel`? They're local scoped anyway, the naming looks better.
</blockquote></details>

It shadows other variables in the function, so it'd be higher risk.  For example if we somehow removed that line but forgot to remove cancel()

---

*[cmd/dgraphloader/main.go, line 333 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-KpTma906cX7RFp7aJ7E:-Kpl7CUmIT9SkLsq-q4H:b-uad249) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd298e29e58abd86581c66abd91fdf8d83a0a23b/cmd/dgraphloader/main.go#L333)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need to close client?
</blockquote></details>

That's moved to a defer statement at the top.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-:-Kpl62ARrNg_DicrJyVi:byik3oj)*

**Comment by janardhan1993** [comment]
The badger instance in client writes to disk in async mode. So i guess we would need to cleanly close kv store.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-:-Kpmr_4DrvlQtUwox-em:b-zh9eom)*

**Comment by manishrjain** [comment]
I think @pawanrawal 's change to add checkpointing changed that, so Badger instance uses sync writes in client.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/dgraphloader/main.go, line 266 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-KpTmGgA8SnsbbaOOcxp:-Kpn0HLnealmO60YJNAD:b-mgtp8y) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd298e29e58abd86581c66abd91fdf8d83a0a23b/cmd/dgraphloader/main.go#L266)):*
<details><summary><i>Previously, srh (Sam Hughes) wrote…</i></summary><blockquote>

It shadows other variables in the function, so it'd be higher risk.  For example if we somehow removed that line but forgot to remove cancel()
</blockquote></details>

For such a small change, I won't be so worried. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-:-KpnI9_OpLhc5g65pKU_:b-ot5jdc)*

**Comment by manishrjain** [comment]
:lgtm: Some comments.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-:-Kpn_WL7ylc4USgGOiQS:b-xkzuoz)*

**Comment by srh** [comment]
*[cmd/dgraphloader/main.go, line 266 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221#-KpTmGgA8SnsbbaOOcxp:-KpqYFz7auclKjf2tZoQ:b-ftlqv7) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd298e29e58abd86581c66abd91fdf8d83a0a23b/cmd/dgraphloader/main.go#L266)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

For such a small change, I won't be so worried. 
</blockquote></details>

On a second look today, I have to agree they were gross and distastefully named.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1221)*

**Pull request closed without merging**
