### PR TITLE
Add different indexes for datetime

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1160)

### CODE REVIEW

**Comment by manishrjain** [comment]
Where's the code to parse this off the schema?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 179 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIrye9UfcVuob_w1W:-KofIrye9UfcVuob_w1X:b-o5p7nl) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L179)):*
> ```Go
> func (t MonthTokenizer) Type() types.TypeID { return types.DateTimeID }
> func (t MonthTokenizer) Tokens(sv types.Val) ([]string, error) {
> 	return []string{encodeToken(encodeInt(int64(sv.Value.(time.Time).Month())), t.Identifier())}, nil
> ```

Not just the month. This should have the year and month.

---

*[tok/tok.go, line 190 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofItlYCrZTHHZ08p1R:-KofItlYCrZTHHZ08p1S:bq7ir71) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L190)):*
> ```Go
> func (t DayTokenizer) Type() types.TypeID { return types.DateTimeID }
> func (t DayTokenizer) Tokens(sv types.Val) ([]string, error) {
> 	return []string{encodeToken(encodeInt(int64(sv.Value.(time.Time).Day())), t.Identifier())}, nil
> ```

This should have year, month, day.

---

*[tok/tok.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIvVx5Uzq7efteCFD:-KofIvVx5Uzq7efteCFE:bsg4yp2) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L201)):*
> ```Go
> func (t HourTokenizer) Type() types.TypeID { return types.DateTimeID }
> func (t HourTokenizer) Tokens(sv types.Val) ([]string, error) {
> 	return []string{encodeToken(encodeInt(int64(sv.Value.(time.Time).Hour())), t.Identifier())}, nil
> ```

y-m-d-hour

---

*[tok/tok.go, line 212 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIwgeRJuaqdUkiCD5:-KofIwgeRJuaqdUkiCD6:b-i9x71v) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L212)):*
> ```Go
> func (t UnixTokenizer) Type() types.TypeID { return types.DateTimeID }
> func (t UnixTokenizer) Tokens(sv types.Val) ([]string, error) {
> 	return []string{encodeToken(encodeInt(int64(sv.Value.(time.Time).Unix())), t.Identifier())}, nil
> ```

what for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-:-KofIyZGkXQptA1nQ_j-:b-b92qp0)*

**Comment by ashwin95r** [comment]
Parsing for the new types are no different than existing index types. So we don't need any special code for this.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 179 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIrye9UfcVuob_w1W:-KofaF6H0MspP-Mi1OH0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L179)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not just the month. This should have the year and month.
</blockquote></details>

Done.

---

*[tok/tok.go, line 190 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofItlYCrZTHHZ08p1R:-KofaFX1Z1qtGnjX9HxM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L190)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should have year, month, day.
</blockquote></details>

Done.

---

*[tok/tok.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIvVx5Uzq7efteCFD:-KofaFrdZj1c3JrHmtHb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L201)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

y-m-d-hour
</blockquote></details>

Done.

---

*[tok/tok.go, line 212 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIwgeRJuaqdUkiCD5:-KofaGYPhg6lKKnUnuPH:bx4frsl) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L212)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

what for?
</blockquote></details>

Removing this as we decided to have upto hour granularity.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-:-KofaN8SWyfX-aFK9pZ6:b-p3lygy)*

**Comment by pawanrawal** [comment]
Can we have some tests in query for this?

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIvVx5Uzq7efteCFD:-KojFLnvdmfaQhdzyuuL:b-q755m3) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L201)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again two returns?

---

*[tok/tok.go, line 169 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KojGt9h6BBZHA9hs3xr:-KojGt9h6BBZHA9hs3xs:b-rexgdm) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad2b4d162dc7977a1af2ab61f1f26be3207d470/tok/tok.go#L169)):*
> ```Go
> 	var l []uint32
> 	tval := sv.Value.(time.Time)
> 	l = append(l, uint32(tval.Year()))
> ```

Doesn't need to be a list. You could just have it as uint16, do a PutUint16 and convert to string.

---

*[tok/tok.go, line 202 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KojFC_XmNTLRbzdFPi1:-KojFC_YDmvCFHuSoYT-:b-xmporv) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad2b4d162dc7977a1af2ab61f1f26be3207d470/tok/tok.go#L202)):*
> ```Go
> 	l = append(l, uint32(tval.Day()))
> 	return []string{encodeToken(encodeUintList(l), t.Identifier())}, nil
> 	return []string{encodeToken(encodeInt(int64(sv.Value.(time.Time).Day())), t.Identifier())}, nil
> ```

Two returns?

---

*[tok/tok.go, line 280 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KojFgc9MaGRPrHq09n0:-KojFgc9MaGRPrHq09n1:buzqy7r) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad2b4d162dc7977a1af2ab61f1f26be3207d470/tok/tok.go#L280)):*
> ```Go
> }
> 
> func encodeUintList(l []uint32) string {
> ```

Only year needs to be uint16. Hour, month and day can be uint8? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-:-KojHACQK3tEaG-KO92S:b-sn6yh)*

**Comment by ashwin95r** [comment]
Added test for day index.

---

Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[tok/tok.go, line 201 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KofIvVx5Uzq7efteCFD:-KojI6KIl9ELkIKp7zuy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c7bc17a293844fa14e05594382b3d1a338e42a05/tok/tok.go#L201)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Again two returns?
</blockquote></details>

Done.

---

*[tok/tok.go, line 169 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KojGt9h6BBZHA9hs3xr:-KojKMtVvZMd8TO6lMq5:b-mby7ri) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad2b4d162dc7977a1af2ab61f1f26be3207d470/tok/tok.go#L169)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Doesn't need to be a list. You could just have it as uint16, do a PutUint16 and convert to string.
</blockquote></details>

Wanted to keep it consistent across different tokenizers for datetime by calling encodeUintList.

---

*[tok/tok.go, line 202 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KojFC_XmNTLRbzdFPi1:-KojI5hCIOuWNBejvntt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad2b4d162dc7977a1af2ab61f1f26be3207d470/tok/tok.go#L202)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Two returns?
</blockquote></details>

Done.

---

*[tok/tok.go, line 280 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-KojFgc9MaGRPrHq09n0:-KojJ1iiSWqjzC7MYWMJ:bcwmx5j) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad2b4d162dc7977a1af2ab61f1f26be3207d470/tok/tok.go#L280)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Only year needs to be uint16. Hour, month and day can be uint8? 
</blockquote></details>

Thought it keeps it cleaner if we use uint16 throughout. Should I make h, m, d uint8 @mrjn?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-:-KojLs0XNrjh5RFDFbaC:b-kllfy8)*

**Comment by pawanrawal** [comment]
:lgtm: Maybe add a test with `ge` as order could be executed without index too.

---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-:-KojOXPEcwmyUMZOK3L-:b-exyi3e)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 213 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-Koje1WcohZZZ8jUq1FP:-Koje1WcohZZZ8jUq1FQ:b-ph9nqe) ([raw file](https://github.com/dgraph-io/dgraph/blob/e30476de33209cd363798a09ce509567df624179/tok/tok.go#L213)):*
> ```Go
> 	var l []uint16
> 	tval := sv.Value.(time.Time)
> 	l = append(l, uint16(tval.Year()))
> ```

Instead of doing these appends, and then creating the buffer, you might as well just create the bytes here. Would avoid creating a slice, allocating memory on heap etc.

```
var [8]byte
binary.BigEndian.PutUint16(...)
and so on.
```

In fact, get rid of encodeUintList.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160)*

**Comment by ashwin95r** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 213 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-Koje1WcohZZZ8jUq1FP:-Kojtr5ffqM7ID5XueDK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e30476de33209cd363798a09ce509567df624179/tok/tok.go#L213)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Instead of doing these appends, and then creating the buffer, you might as well just create the bytes here. Would avoid creating a slice, allocating memory on heap etc.

```
var [8]byte
binary.BigEndian.PutUint16(...)
and so on.
```

In fact, get rid of encodeUintList.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1160#-:-KokEQnx-IRsuj0LVKuz:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
