### PR TITLE
Correction to execution instruction and reference to headers

### PR DESCRIPTION
**Pull request by hackintoshrao**
1. Correction to the execution instruction of merge.cc and merge_heap.cc
2. Adding reference to rocksdb headers

[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/26)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/merge/merge.cc, line 25 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KADU8B9UGB6CqZdoYO1:-KADU8B9UGB6CqZdoYO2:1899039436) ([raw file](https://github.com/dgraph-io/dgraph/blob/49bc8fdfa91296d3c053f08c4732d187e1c784a7/tools/merge/merge.cc#L25)):*
This is probably not the right place to explain the dependency. Make it above in the comments, or just explain how to install RocksDB -- but we do that already.

---

*[tools/merge/merge_heap.cc, line 27 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KADUR8oqTq2y_9cCEwE:-KADUR8oqTq2y_9cCEwF:-330895159) ([raw file](https://github.com/dgraph-io/dgraph/blob/49bc8fdfa91296d3c053f08c4732d187e1c784a7/tools/merge/merge_heap.cc#L27)):*
same here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by hackintoshrao** [comment]
*[tools/merge/merge.cc, line 25 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KADU8B9UGB6CqZdoYO1:-KAIX2WyCK0Octf3vp9M:6180935) ([raw file](https://github.com/dgraph-io/dgraph/blob/49bc8fdfa91296d3c053f08c4732d187e1c784a7/tools/merge/merge.cc#L25)):*

Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by hackintoshrao** [comment]
*[tools/merge/merge_heap.cc, line 27 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KADUR8oqTq2y_9cCEwE:-KAIXTh6g0R0p5je0vG-:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/49bc8fdfa91296d3c053f08c4732d187e1c784a7/tools/merge/merge_heap.cc#L27)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by manishrjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/merge/merge.cc, line 20 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KAIXRjPodtD3GCfTVpq:-KAIXRjPodtD3GCfTVpr:-1085555803) ([raw file](https://github.com/dgraph-io/dgraph/blob/f51c4c82b2f0a12eede1ed92435f09422f484df5/tools/merge/merge.cc#L20)):*
Remove extra trailing spaces here and elsewhere. Doesn't gofmt pick these?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by hackintoshrao** [comment]
*[tools/merge/merge.cc, line 20 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KAIXRjPodtD3GCfTVpq:-KAIXtMHptfaWE0HqIty:-2078246117) ([raw file](https://github.com/dgraph-io/dgraph/blob/f51c4c82b2f0a12eede1ed92435f09422f484df5/tools/merge/merge.cc#L20)):*
Not sure whether go fmt picks from C++ code., I'll configure a C++ formatter. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/merge/merge.cc, line 20 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KAIXRjPodtD3GCfTVpq:-KAI_a06mVdeS2YfQKiw:-1945681921) ([raw file](https://github.com/dgraph-io/dgraph/blob/f51c4c82b2f0a12eede1ed92435f09422f484df5/tools/merge/merge.cc#L20)):*
Ah.. right! It's afternoon, I'm half sleepy.

Just remove all the trailing spaces, here and elsewhere. No need for a c++ formatter, your editor can show you all these spaces.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by hackintoshrao** [comment]
*[tools/merge/merge.cc, line 20 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-KAIXRjPodtD3GCfTVpq:-KAIaVOcrqQ9Z5F0eP_U:634587243) ([raw file](https://github.com/dgraph-io/dgraph/blob/f51c4c82b2f0a12eede1ed92435f09422f484df5/tools/merge/merge.cc#L20)):*
Sure :) 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26)*

**Comment by manishrjain** [comment]
:lgtm: I'll pull it in!

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/26#-:-KAIjmw_-iwZDxKLu9mg:890351791)*

**Pull request merged**
