### PR TITLE
docker configuration files to reflect the new default ports.

### PR DESCRIPTION
**Pull request by sboorlagadda**
contrib/config has docker-compose files that are oftern referred by users.
   Updated these compose files to reflect the new default ports.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2064)

### CODE REVIEW

**Comment by sboorlagadda** [comment]
These changes are part of #2042

**Comment by pawanrawal** [comment]
We'd also need to update the files on deploy/index.md. Or are you thinking of referring these files from the deploy page? The reason I didn't do it was because docker stack deploy command doesn't take an url as input.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/config/docker/docker-compose-ha.yml, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2064#-L44ZHt8IuDKK9J518uC:-L44ZHt8IuDKK9J518uD:bjdlar8) ([raw file](https://github.com/dgraph-io/dgraph/blob/656c4c1e3f8037ae5cb9d3f3d7c27f5fbb1cb955/contrib/config/docker/docker-compose-ha.yml#L17)):*
> ```YAML
> services:
>   zero_1:
>     image: dgraph/dgraph:master
> ```

Can just be latest. We'll do a release by Thursday/Friday.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2064#-:-L44YzJpb4D-QrTSXko7:brgz50c)*

**Comment by sboorlagadda** [comment]
@pawanrawal deploy/index.md is already updated with latest configs for docker-compose & swarm guides.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[contrib/config/docker/docker-compose-ha.yml, line 17 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2064#-L44ZHt8IuDKK9J518uC:-L47G5BWZp0QN55Hhdyl:b-ina5n9) ([raw file](https://github.com/dgraph-io/dgraph/blob/656c4c1e3f8037ae5cb9d3f3d7c27f5fbb1cb955/contrib/config/docker/docker-compose-ha.yml#L17)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can just be latest. We'll do a release by Thursday/Friday.
</blockquote></details>

Done changed to latest instead of master.  I used master as some users may want early access on some fixes, but for most users who follow deploy/index.md the configs already show 'latest'.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2064#-:-L47GEhNYkceUdNkYjN7:b-h3zngo)*

**Comment by pawanrawal** [comment]
Ah, I missed that.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2064#-:-L489jL-OG4oTjMXgRPO:bxh2rvd)*

**Pull request merged**
