### PR TITLE
fix(Mutation): Deeply-nested uid facets

### PR DESCRIPTION
**Pull request by nelsonpecora**
Between v20.03 and v20.11 (with https://github.com/dgraph-io/dgraph/pull/5424), dgraph lost the ability to handle deeply-nested uid facets. A JSON mutation with non-nested uid facets looks like this:

```json
{
  "set": [{
  	"title": "parent",
  	"children": [{
  		"title": "child",
  		"children|position": 1
		}]
	}]
}
```

A mutation with deeply-nested uid facets looks like this:

```json
{
  "set": [{
  	"title": "parent",
  	"children": [{
  		"title": "child",
  		"children|position": 1,
  		"children": [{
  			"title": "grandchild",
  			"children|position": 1
			}]
		}]
	}]
}
```

There's something about trying to set both `children` and `children|position` on the same JSON object that's causing it to error. The equivalent mutation in RDF succeeds:

```
{
  set {
    <_:parent> <title> "parent" .
    <_:parent> <children> <_:child> (position=1) .
    <_:child> <title> "child" .
    <_:child> <children> <_:grandchild> (position=1) .
    <_:grandchild> <title> "grandchild" .
  }
}
```

---

**Fix(karl):** The short explanation is there was an [old TODO](https://github.com/dgraph-io/dgraph/blob/160e922ef927335aea7ddb4a02a10502c1d21349/chunker/json_parser.go#L567-L568) mentioning that we should only run `parseMapFacets` if we are within a JSON scalar array, but we were running it from within JSON object arrays as well. [Only running it from within JSON scalar arrays](https://github.com/dgraph-io/dgraph/blob/93d8b0a4d7efed1f6764a23e304ffe5506b65599/chunker/json_parser.go#L568-L581) fixed the issue. 

Longer explanation: By calling `parseMapFacets` from within a JSON object array, the `"friend|close": true` facet was correctly assumed to have an object (map) value rather than its scalar value, and [this error](https://github.com/dgraph-io/dgraph/blob/93d8b0a4d7efed1f6764a23e304ffe5506b65599/chunker/json_parser.go#L137-L141) was returned. 

The reason [`"another_friend|close": true`](https://github.com/dgraph-io/dgraph/pull/7455#issuecomment-781522963) worked despite this is because `parseScalarMap` looks for facets on the same level as the predicate. For example, here's how map facets should look:

```json
{
    "nickname": ["alice", "bob", "josh"],
    "nickname|kind": {
        "0": "friends",
        "2": "official"
    }
}
```

So in the working `another_friend` example, `parseMapFacets` is called two times (once for each named JSON array declaration):

1. `parseMapFacets(map[string]interface{}{}, "friend|")`
    * `mapToNquads` encounters `"friend": [` on the current level and calls `parseMapFacets` with all facets found on the current level (none) and `"friend" + "|"` as the `prefix` parameter.
    * This works because [`m` is empty](https://github.com/dgraph-io/dgraph/blob/93d8b0a4d7efed1f6764a23e304ffe5506b65599/chunker/json_parser.go#L129) and `parseMapFacets` returns `nil`.
2. `parseMapFacets(map[string]interface{}{"friend|close": true}, "another_friend|")`
    * `mapToNquads` encounters `"another_friend": [` on the current level and calls `parseMapFacets` with all facets found on the current level and `"another_friend" + "|"` as the `prefix` parameter.
    * This works because [we check](https://github.com/dgraph-io/dgraph/blob/93d8b0a4d7efed1f6764a23e304ffe5506b65599/chunker/json_parser.go#L133-L135) if `prefix` (in this case, `another_friend|`) is in the facet name (in this case, `friend|close`) and `parseMapFacets` returns `nil`.

So `parseMapFacets` is only called two times, both times returning `nil`, and we pick up the facets with `parseScalarFacets` later. 

With this PR fix, we only call `parseMapFacets` for JSON scalar arrays and avoid everything mentioned above.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7455)

### CODE REVIEW

**Comment by karlmcguire** [comment]
Hello, I'm looking into this. Just leaving some notes here. 

1. scalar facet (doesn't work)

```
[
    {
        "name": "Alice",
        "friend": [
            {
                "name": "Dave",
                "friend|close": "true",
                "friend": [
                    {
                        "name": "Emily",
                        "friend|close": true
                    }
                ]
            }
        ]
    }
]

Parse:
([]*api.NQuad) (len=2 cap=1000) {
 (*api.NQuad)(0xc000448000)(subject:"_:dg.3392663716.1" predicate:"name" object_value:<str_val:"Alice" > ),
 (*api.NQuad)(0xc000448150)(subject:"_:dg.3392663716.2" predicate:"name" object_value:<str_val:"Dave" > )
}
(*errors.fundamental)(0xc00050e100)(facets format should be of type map for scalarlist predicates, found: true for facet: friend|close)

FastParse:
([]*api.NQuad) (len=2 cap=1000) {
 (*api.NQuad)(0xc000362000)(subject:"_:dg.3392663716.3" predicate:"name" object_value:<str_val:"Alice" > ),
 (*api.NQuad)(0xc000362540)(subject:"_:dg.3392663716.4" predicate:"name" object_value:<str_val:"Dave" > )
}
(*errors.fundamental)(0xc0004360c0)(facets format should be of type map for scalarlist predicates, found: true for facet: friend|close)
```

2. map facet (doesn't work)

```
[
    {
        "name": "Alice",
        "friend": [
            {
                "name": "Dave",
                "friend": [
	            {
	                "name": "Emily"
	            }
	        ],
	        "friend|close": {
	            "0": true
	        }
	    }
	],
	"friend|close": {
	    "0": true
	}
    }
]`

Parse:
([]*api.NQuad) (len=4 cap=1000) {
 (*api.NQuad)(0xc0007a6150)(subject:"_:dg.2339138906.1" predicate:"name" object_value:<str_val:"Alice" > ),
 (*api.NQuad)(0xc0007a62a0)(subject:"_:dg.2339138906.2" predicate:"name" object_value:<str_val:"Dave" > ),
 (*api.NQuad)(0xc0007a63f0)(subject:"_:dg.2339138906.3" predicate:"name" object_value:<str_val:"Emily" > ),
 (*api.NQuad)(0xc0007a6380)(subject:"_:dg.2339138906.2" predicate:"friend" object_id:"_:dg.2339138906.3" )
}
(*errors.withStack)(0xc0005021a0)(facet: friend|close: facet value can only be string/number/bool.)

FastParse:
([]*api.NQuad) (len=4 cap=1000) {
 (*api.NQuad)(0xc0003aa0e0)(subject:"_:dg.2339138906.4" predicate:"name" object_value:<str_val:"Alice" > ),
 (*api.NQuad)(0xc0003aa230)(subject:"_:dg.2339138906.5" predicate:"name" object_value:<str_val:"Dave" > ),
 (*api.NQuad)(0xc0003aa380)(subject:"_:dg.2339138906.6" predicate:"name" object_value:<str_val:"Emily" > ),
 (*api.NQuad)(0xc0003aa310)(subject:"_:dg.2339138906.5" predicate:"friend" object_id:"_:dg.2339138906.6" )
}
(*errors.withStack)(0xc0007981c0)(facet: friend|close: facet value can only be string/number/bool.)
```

**Comment by karlmcguire** [comment]
2. nested scalar facet (working now)

```
[
    {
        "name": "Alice",
        "friend": [
            {
                "name": "Dave",
                "friend|close": "true",
                "friend": [
                    {
                        "name": "Emily",
                        "friend|close": true
                    }
                ]
            }
        ]
    }
]

(*api.NQuad)(0xc0004f2310)(subject:"_:dg.737395009.2" predicate:"name" object_value:<str_val:"Dave" > )
(*api.NQuad)(0xc0004f2460)(subject:"_:dg.737395009.3" predicate:"name" object_value:<str_val:"Emily" > )
(*api.NQuad)(0xc0004f23f0)(subject:"_:dg.737395009.2" predicate:"friend" object_id:"_:dg.737395009.3" facets:<key:"close" value:"\001" val_type:BOOL > )
(*api.NQuad)(0xc0004f22a0)(subject:"_:dg.737395009.1" predicate:"friend" object_id:"_:dg.737395009.2" facets:<key:"close" value:"true" tokens:"\001true" > )
(*api.NQuad)(0xc0004f24d0)(subject:"_:dg.737395009.1" predicate:"name" object_value:<str_val:"Alice" > )
```

**Review by danielmai — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7455)* status: all files reviewed, 1 unresolved discussion (waiting on @karlmcguire and @nelsonpecora)

___
*[go.mod, line 17 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7455#-MTr5Ush5EwIE-yid67G:-MTr5Ush5EwIE-yid67H:b-ul024r) ([raw file](https://github.com/dgraph-io/dgraph/blob/95a93c435f83e9f2b22639e8c4f3e637ed645898/go.mod#L17)):*
> ```XML
> 	github.com/blevesearch/bleve v1.0.13
> 	github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd
> 	github.com/davecgh/go-spew v1.1.1
> ```

What's go-spew? I don't see it used in this PR, so why is this dependency added?

**Review by danielmai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7455)* status: all files reviewed, 1 unresolved discussion (waiting on @karlmcguire and @nelsonpecora)

___
*[go.mod, line 17 at r4](https://reviewable.io/reviews/dgraph-io/dgraph/7455#-MTr5Ush5EwIE-yid67G:-MTr6ntz6TkZ1vjwKSat:b-dnx1gk) ([raw file](https://github.com/dgraph-io/dgraph/blob/95a93c435f83e9f2b22639e8c4f3e637ed645898/go.mod#L17)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

What's go-spew? I don't see it used in this PR, so why is this dependency added?
</blockquote></details>

Nevermind, I see you're using it for debugging.

**Review by danielmai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7455#-:-MTrBDbiBEqzHUDkQpVH:bg7igkv)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @danielmai and @karlmcguire)

**Pull request merged**
