### PR TITLE
fix(GraphQL): Added support for parameterized cascade with variables.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes: GRAPHQL-1007

We haven't added support to pass arguments of parameterized cascade through variables when we added parameterized cascade.
In this PR we have added it and also some tests and validation checks.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7477)

### CODE REVIEW

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7477)* status: 9 of 12 files reviewed, 9 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/resolve/query_test.go, line 41 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN0oKpD5M_zCjRRKMV:-MUN0oKpD5M_zCjRRKMW:b-kpk18k) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/resolve/query_test.go#L41)):*
> ```
> GQLVariables string
> ```
Nice catch!
___
*[graphql/resolve/query_test.yaml, line 1963 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN13ZK8JkZXltWusMH:-MUN13ZK8JkZXltWusMI:b-5lb7rd) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/resolve/query_test.yaml#L1963)):*
<details><summary><i alt="summary">Quoted 33 lines of code…</i></summary>

> ```
> -
>   name: "Parameterized Cascade directive on root field using variables"
>   gqlquery: |
>     query($fieldsRoot:[String]) {
>       queryAuthor @cascade(fields: $fieldsRoot) {
>         dob
>         reputation
>         posts {
>           text
>           title
>         }
>       }
>     }
>   gqlvariables: |
>     {
>         "fieldsRoot": [
>             "dob",
>             "reputation"
>         ]
>     }
>   dgquery: |-
>     query {
>       queryAuthor(func: type(Author)) @cascade(Author.dob, Author.reputation) {
>         Author.dob : Author.dob
>         Author.reputation : Author.reputation
>         Author.posts : Author.posts {
>           Post.text : Post.text
>           Post.title : Post.title
>           dgraph.uid : uid
>         }
>         dgraph.uid : uid
>       }
>     }
> ```
</details>

I think we shouldn't need this as the next test covers it already.
___
*[graphql/schema/validation_rules.go, line 101 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN21Q_29DzYvNccmac:-MUN21Qa2sF1bMSBV8ab:b5u2q44) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L101)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			if directive.Arguments.ForName(cascadeArg) == nil {
> 				return
> 			}
> 			fieldArg := directive.Arguments.ForName(cascadeArg)
> ```
</details>

```
fieldArg := directive.Arguments.ForName(cascadeArg)
if fieldArg == nil {
  return
}
```
___
*[graphql/schema/validation_rules.go, line 106 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN2He3Dy5PDTOReY6N:-MUN2He3Dy5PDTOReY6O:b-ydxy61) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L106)):*
> ```
> isVariable := strings.HasPrefix(fieldArg.Value.String(), "$")
> ```
a better check is:
```
isVariable := fieldArg.Value.Kind == ast.Variable
```
___
*[graphql/schema/validation_rules.go, line 107 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN3xQl30veKIQOqWe2:-MUN3xQm9EdSVTJifksr:b-sm29iz) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L107)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			if directive.ArgumentMap(walker.Variables)[cascadeArg] == nil {
> 				return
> 			}
> 			var variableVal []interface{}
> ```
</details>

```
fields, ok := directive.ArgumentMap(walker.Variables)[cascadeArg].([]interface{})
if !ok || val == nil {
  return
}
```
here `fields` should have the value for the `fields` arg, irrespective of whether it came from a variable or it was in the query itself.
So, we don't need to consider variable values separately and hence shouldn't need the `GqlFields` function.
___
*[graphql/schema/validation_rules.go, line 113 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN2cU344zWEICWAPAX:-MUN2cU344zWEICWAPAY:bkkzws2) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L113)):*
> ```
> variable
> ```
should be `variables`
___
*[graphql/schema/validation_rules.go, line 127 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN5SKG-Eup4Zkju7Qi:-MUN5SKG-Eup4Zkju7Qj:b-ra1o96) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L127)):*
> ```
> 						addError(validator.Message(gqlerror.ErrorPathf(validatorPath, err).Error()), validator.At(directive.Position))
> 						return
> ```
let's just correctly format the error here instead of doing `addError`. It feels redundant. The `addError` below should take care of adding the error.
```
err = gqlerror.ErrorPathf(validatorPath, err).Error()
```
___
*[graphql/schema/wrappers.go, line 1095 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN89fS59DhRwQyILnl:-MUN89fTA23gRZB9FoP8:b-wlzwx6) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/wrappers.go#L1095)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
> 	arg := dir.Arguments.ForName(cascadeArg)
> 	// check valid arg
> 	if arg == nil || arg.Value == nil {
> 		return []string{"__all__"}
> 	}
> 	val := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
> 	isVariable := strings.HasPrefix(arg.Value.String(), "$")
> 	// check length of arg
> 	if isVariable {
> 		if len(val) == 0 {
> 			return []string{"__all__"}
> 		}
> 	} else if len(arg.Value.Children) == 0 {
> 		return []string{"__all__"}
> 	}
> ```
</details>

we can just find `val` first and then just check it's length, no need for separate cases for variable and raw cases:
```
val := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
if len(val) == 0 {
  return []string{"__all__"}
}
```
___
*[graphql/schema/wrappers.go, line 1118 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN8Kcy1aNB9ETTAObF:-MUN8Kcy1aNB9ETTAObG:b5kvez9) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/wrappers.go#L1118)):*
> ```Go
> }
> 
> func GqlFields(val []interface{}, arg *ast.Argument, varFlag bool) []string {
> ```

shouldn't be required now

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7477)* status: 9 of 12 files reviewed, 9 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/schema/wrappers.go, line 1095 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN89fS59DhRwQyILnl:-MUN8_4d5IrD59IaTweZ:bsu93w0) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/wrappers.go#L1095)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	arg := dir.Arguments.ForName(cascadeArg)
> 	// check valid arg
> 	if arg == nil || arg.Value == nil {
> 		return []string{"__all__"}
> 	}
> 	val := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
> 	isVariable := strings.HasPrefix(arg.Value.String(), "$")
> 	// check length of arg
> 	if isVariable {
> 		if len(val) == 0 {
> 			return []string{"__all__"}
> 		}
> 	} else if len(arg.Value.Children) == 0 {
> 		return []string{"__all__"}
> 	}
> ```
we can just find `val` first and then just check it's length, no need for separate cases for variable and raw cases:
```
val := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
if len(val) == 0 {
  return []string{"__all__"}
}
```
</blockquote></details>

```
val, _ := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
if len(val) == 0 {
  return []string{"__all__"}
}
```

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7477)* status: 5 of 12 files reviewed, 9 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/resolve/query_test.yaml, line 1963 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN13ZK8JkZXltWusMH:-MUNY0Ja5JNsGRDlMWAY:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/resolve/query_test.yaml#L1963)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> -
>   name: "Parameterized Cascade directive on root field using variables"
>   gqlquery: |
>     query($fieldsRoot:[String]) {
>       queryAuthor @cascade(fields: $fieldsRoot) {
>         dob
>         reputation
>         posts {
>           text
>           title
>         }
>       }
>     }
>   gqlvariables: |
>     {
>         "fieldsRoot": [
>             "dob",
>             "reputation"
>         ]
>     }
>   dgquery: |-
>     query {
>       queryAuthor(func: type(Author)) @cascade(Author.dob, Author.reputation) {
>         Author.dob : Author.dob
>         Author.reputation : Author.reputation
>         Author.posts : Author.posts {
>           Post.text : Post.text
>           Post.title : Post.title
>           dgraph.uid : uid
>         }
>         dgraph.uid : uid
>       }
>     }
> ```
I think we shouldn't need this as the next test covers it already.
</blockquote></details>

removed.
___
*[graphql/schema/validation_rules.go, line 101 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN21Q_29DzYvNccmac:-MUNY2Bm6y-EOGVSpYr_:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L101)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 			if directive.Arguments.ForName(cascadeArg) == nil {
> 				return
> 			}
> 			fieldArg := directive.Arguments.ForName(cascadeArg)
> ```
```
fieldArg := directive.Arguments.ForName(cascadeArg)
if fieldArg == nil {
  return
}
```
</blockquote></details>

added.
___
*[graphql/schema/validation_rules.go, line 106 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN2He3Dy5PDTOReY6N:-MUNYOjX-XBc1f54b-J7:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L106)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> isVariable := strings.HasPrefix(fieldArg.Value.String(), "$")
> ```
a better check is:
```
isVariable := fieldArg.Value.Kind == ast.Variable
```
</blockquote></details>

added.
___
*[graphql/schema/validation_rules.go, line 107 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN3xQl30veKIQOqWe2:-MUNYQyn9kOrRzI-y7S8:b-8tb27c) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L107)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 			if directive.ArgumentMap(walker.Variables)[cascadeArg] == nil {
> 				return
> 			}
> 			var variableVal []interface{}
> ```
```
fields, ok := directive.ArgumentMap(walker.Variables)[cascadeArg].([]interface{})
if !ok || val == nil {
  return
}
```
here `fields` should have the value for the `fields` arg, irrespective of whether it came from a variable or it was in the query itself.
So, we don't need to consider variable values separately and hence shouldn't need the `GqlFields` function.
</blockquote></details>

removed GQLFields.
___
*[graphql/schema/validation_rules.go, line 113 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN2cU344zWEICWAPAX:-MUNYV3kEfpV-9KFPYVd:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L113)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> variable
> ```
should be `variables`
</blockquote></details>

done.
___
*[graphql/schema/validation_rules.go, line 127 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN5SKG-Eup4Zkju7Qi:-MUNYW7iAOvzv69VYEEy:bfgalrn) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/validation_rules.go#L127)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 						addError(validator.Message(gqlerror.ErrorPathf(validatorPath, err).Error()), validator.At(directive.Position))
> 						return
> ```
let's just correctly format the error here instead of doing `addError`. It feels redundant. The `addError` below should take care of adding the error.
```
err = gqlerror.ErrorPathf(validatorPath, err).Error()
```
</blockquote></details>

formated.
___
*[graphql/schema/wrappers.go, line 1095 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN89fS59DhRwQyILnl:-MUNYbvUE9oUEMrs3BOs:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/wrappers.go#L1095)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

```
val, _ := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
if len(val) == 0 {
  return []string{"__all__"}
}
```
</blockquote></details>

done.
___
*[graphql/schema/wrappers.go, line 1118 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUN8Kcy1aNB9ETTAObF:-MUNYdQGDNDdy8tq9UuU:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c3b01c73df92a5d970a7e09194788b82404fb5a/graphql/schema/wrappers.go#L1118)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

shouldn't be required now
</blockquote></details>

removed.

**Review by abhimanyusinghgaur — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-:-MUNk1k_DVPKBKAexycN:bnfp4nl)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/schema/validation_rules.go, line 105 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUNiql17ebrDcDnUstK:-MUNiql17ebrDcDnUstL:b-1z7fo6) ([raw file](https://github.com/dgraph-io/dgraph/blob/fddd58e487da0fa8315acd866139166484fda93f/graphql/schema/validation_rules.go#L105)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			fieldsVal, ok := directive.ArgumentMap(walker.Variables)[cascadeArg].([]interface{})
> 			if !ok || fieldsVal == nil {
> 				return
> 			}
> ```
</details>

we can make it more simpler:
```
fieldsVal, _ := directive.ArgumentMap(walker.Variables)[cascadeArg].([]interface{})
if len(fieldsVal) == 0 {
  return
}
```
its better to use `len() == 0` checks for slices that to use `slice == nil`
___
*[graphql/schema/wrappers.go, line 1086 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUNjN07D3dgAhhvG3BJ:-MUNjN07D3dgAhhvG3BK:b89u2ql) ([raw file](https://github.com/dgraph-io/dgraph/blob/fddd58e487da0fa8315acd866139166484fda93f/graphql/schema/wrappers.go#L1086)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	fieldArg := dir.Arguments.ForName(cascadeArg)
> 	if fieldArg == nil {
> 		return []string{"__all__"}
> 	}
> ```
</details>

this shouldn't be needed too.
This case would be taken care of by the next few lines where `ArgumentMap()[cascadeArg]` will return an empty slice if there were no `fields` arg.
___
*[graphql/schema/wrappers.go, line 1091 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUNjkK20Bhn_9ZHqYxf:-MUNjkK3CE6UahOG97gG:b-5mtepn) ([raw file](https://github.com/dgraph-io/dgraph/blob/fddd58e487da0fa8315acd866139166484fda93f/graphql/schema/wrappers.go#L1091)):*
> ```
> 	fieldsVal, ok := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
> 	if !ok || fieldsVal == nil {
> ```
can simplify this too to just use `len(slice) == 0` and replace `ok` with `_`.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7477)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/schema/validation_rules.go, line 105 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUNiql17ebrDcDnUstK:-MUOghPMBb8UEGWKEDNA:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/fddd58e487da0fa8315acd866139166484fda93f/graphql/schema/validation_rules.go#L105)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 			fieldsVal, ok := directive.ArgumentMap(walker.Variables)[cascadeArg].([]interface{})
> 			if !ok || fieldsVal == nil {
> 				return
> 			}
> ```
we can make it more simpler:
```
fieldsVal, _ := directive.ArgumentMap(walker.Variables)[cascadeArg].([]interface{})
if len(fieldsVal) == 0 {
  return
}
```
its better to use `len() == 0` checks for slices that to use `slice == nil`
</blockquote></details>

done.
___
*[graphql/schema/wrappers.go, line 1086 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUNjN07D3dgAhhvG3BJ:-MUOgedH3231FdfmmyCg:brpmqc3) ([raw file](https://github.com/dgraph-io/dgraph/blob/fddd58e487da0fa8315acd866139166484fda93f/graphql/schema/wrappers.go#L1086)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	fieldArg := dir.Arguments.ForName(cascadeArg)
> 	if fieldArg == nil {
> 		return []string{"__all__"}
> 	}
> ```
this shouldn't be needed too.
This case would be taken care of by the next few lines where `ArgumentMap()[cascadeArg]` will return an empty slice if there were no `fields` arg.
</blockquote></details>

removed.
___
*[graphql/schema/wrappers.go, line 1091 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7477#-MUNjkK20Bhn_9ZHqYxf:-MUOgdVF1YhBvBxip2p7:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/fddd58e487da0fa8315acd866139166484fda93f/graphql/schema/wrappers.go#L1091)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> 	fieldsVal, ok := dir.ArgumentMap(f.op.vars)[cascadeArg].([]interface{})
> 	if !ok || fieldsVal == nil {
> ```
can simplify this too to just use `len(slice) == 0` and replace `ok` with `_`.
</blockquote></details>

done.

**Pull request merged**
