### PR TITLE
Change key formation, code to get list of predicates in a given store

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/66)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cluster/cluster.go, line 20 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0N6SZJA8m34Y7F5VC:-KE0N6SZJA8m34Y7F5VD:106013875) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/cluster.go#L20)):*
There's nothing here, might as well make it part of the next changelist, and remove from here.

---

*[cluster/doc.go, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MmUB1V9fwHNJO4O0:-KE0MmUB1V9fwHNJO4O1:-492522172) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/doc.go#L1)):*
Actually add the doc.

---

*[cluster/predicateList.go, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0M1z3wVuHmEv3ddg_:-KE0M1z3wVuHmEv3ddga:-2066155839) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/predicateList.go#L1)):*
File name shouldn't have Camelcase. Just call it predicates.go

---

*[cluster/predicateList.go, line 28 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MIJ6DY-Wy4Q60WKP:-KE0MIJ6DY-Wy4Q60WKQ:635695409) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/predicateList.go#L28)):*
Deal with error.

---

*[cluster/predicateList_test.go, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MhzHNsgJN7HqWZDM:-KE0MhzHNsgJN7HqWZDN:676036456) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/predicateList_test.go#L2)):*
2016

---

*[posting/list.go, line 108 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MXbFC105vAaWpZfd:-KE0MXbFC105vAaWpZfe:1677669982) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/posting/list.go#L108)):*
Instead of creating a new string here (which is what the add will do), do:
buf.WriteRune('|')

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/66)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cluster/cluster.go, line 20 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0N6SZJA8m34Y7F5VC:-KE1e5AxXXcwq3pOlrtx:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/cluster.go#L20)):*
Done.

---

*[cluster/doc.go, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MmUB1V9fwHNJO4O0:-KE1e-n8jfrPgkAf8yFU:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/doc.go#L1)):*
Done.

---

*[cluster/predicateList.go, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0M1z3wVuHmEv3ddg_:-KE1aUo3QCjtBvUf4Rpa:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/predicateList.go#L1)):*
Done.

---

*[cluster/predicateList.go, line 28 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MIJ6DY-Wy4Q60WKP:-KE1e1WVh09GBLEJx7cs:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/predicateList.go#L28)):*
Done.

---

*[cluster/predicateList_test.go, line 2 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MhzHNsgJN7HqWZDM:-KE1agB5mOe60rl-SZyh:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/cluster/predicateList_test.go#L2)):*
Done.

---

*[posting/list.go, line 108 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE0MXbFC105vAaWpZfd:-KE1cvIgNE6tcZIZGDpc:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/8bd1b18097be9bff9d6710746f9616dced7b2e53/posting/list.go#L108)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/66)*

**Comment by manishrjain** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cluster/doc.go, line 24 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE4-GJOL_Fx5w2jPKnq:-KE4-GJPbhsm_xTjtnkb:-1681721728) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb4854b7b23675ca43e657b03ae2d92accc59da2/cluster/doc.go#L24)):*
Full stop.

---

*[cluster/iplist.go, line 3 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE4-wZSO0W62AJ4jsje:-KE4-wZSO0W62AJ4jsjf:1040398737) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb4854b7b23675ca43e657b03ae2d92accc59da2/cluster/iplist.go#L3)):*
Call it node, or server. ipList sounds like a list, but isn't.

---

*[cluster/predicates.go, line 33 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE4-O6dpTEDbRAVkd20:-KE4-O6dpTEDbRAVkd21:-1620335427) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb4854b7b23675ca43e657b03ae2d92accc59da2/cluster/predicates.go#L33)):*
This would be the case for keys which are xid -> uid. So, don't log fatal. Just skip.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/66)*

**Comment by ashwin95r** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[cluster/doc.go, line 24 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE4-GJOL_Fx5w2jPKnq:-KE5G5TeDHJOUqJg4leH:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb4854b7b23675ca43e657b03ae2d92accc59da2/cluster/doc.go#L24)):*
Done.

---

*[cluster/predicates.go, line 33 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE4-O6dpTEDbRAVkd20:-KE5G3wixH19CbmcfP9e:1556966570) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb4854b7b23675ca43e657b03ae2d92accc59da2/cluster/predicates.go#L33)):*
'|' is being used there to, so it wont be a problem

---

*[cluster/iplist.go, line 3 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-KE4-wZSO0W62AJ4jsje:-KE5G6nMvcSmAp3PM9tE:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/cb4854b7b23675ca43e657b03ae2d92accc59da2/cluster/iplist.go#L3)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/66)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/66#-:-KEG-yx5MYNRxnhYarmP:1417088721)*

**Pull request merged**
