### PR TITLE
Displaying error incase graph label isn't a blank node or IRI

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/140)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Fixes https://github.com/dgraph-io/dgraph/issues/117.

**Comment by manishrjain** [comment]
I assume this would throw error if label is a _uid_? Can you confirm that with a test case?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/140#-:-KNkFD3mI9SlrLQs_pGU:-1681958060)*

**Comment by pawanrawal** [comment]
It wasn't earlier. It does now.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/140#-:-KNkKVWR0OfSd6NGHuDj:-1248323394)*

**Comment by manishrjain** [comment]
:lgtm: Alright. I'm not sure what the right usage for label is going to be. So, let's just keep it like so.

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/140#-:-KNkMbKpwXP_ax2Hp5RC:-1996622504)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
