### PR TITLE
Shutdown : clean shutdown of dgraph

### PR DESCRIPTION
**Pull request by ashishnegi**
Wait for 
1. Closing client connections (except http . waiting for 1.8)
2. Closing worker listeners connections.
3. Watermarks to sync.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/535)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/index.go, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbNpkyJecoWkSwqeKX_:-KbNpkyKnxvUiQHU-rVU:bqf5v8k) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/worker/index.go#L26)):*
> ```Go
> 	x.Trace(ctx, "Processing proposal to rebuild index: %v", proposal.RebuildIndex)
> 
> 	if err := n.syncAllMarks(ctx); err != nil {
> ```

refactored code out to new fn : syncAllMarks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535)*

**Comment by jchiu0** [comment]
:lgtm:
LG for shutdown handler to send to shutdownCh which is listened by all the servers.
LG for shutdown waitgroup to make sure that everything is cleaned up
LG for sync watermarks

Some minor comments.

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 687 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbTmt2qzwthfPEIGJlL:-KbTmt2qzwthfPEIGJlM:bhdfdzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/cmd/dgraph/main.go#L687)):*
> ```Go
> }
> 
> func serveGRPC(l net.Listener, sdWg *sync.WaitGroup) {
> ```

Thought you already made sdWg a global? Maybe you prefer to make it not global?

---

*[x/error.go, line 193 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbTgXGplWRiGlNAMg99:-KbTgXGplWRiGlNAMg9A:bxvrymt) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/x/error.go#L193)):*
> ```Go
> }
> 
> func StringifyErrors(errs []error) string {
> ```

Add comment for exported func

---

*[x/error.go, line 197 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbTgfVlRuZUPKUpuPpc:-KbTgfVlRuZUPKUpuPpd:bcrqx3a) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/x/error.go#L197)):*
> ```Go
> 	// error returned by buf.Write* are always nil : by doc
> 	for i, err := range errs {
> 		buf.WriteString(strconv.FormatInt(int64(i), 10))
> ```

Might want to consider fmt.sprintf as this is not time critical.
buf.WriteString(fmt.Sprintf(...))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-:-KbTkRXABRcJPV88OnVE:bz2w36m)*

**Comment by ashishnegi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dgraph/main.go, line 687 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbTmt2qzwthfPEIGJlL:-KbToaccd-WpnzH42EFK:b-w58pnm) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/cmd/dgraph/main.go#L687)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Thought you already made sdWg a global? Maybe you prefer to make it not global?
</blockquote></details>

The only place i am not able to pass it directly is `shutdownHandler` of http endpoint ; 
otherwise i have tried to keep it local.

Now, i think that i can create a fn closure and in `http.HandleFunc("/shutdown", mkShutdownHandler(waitgroup)) ` where `mkShutdownHandler` returns `fn`..
Will that be better ? Or using global variable `shutdownWg` in all fns ? Or keeping it as it is..
I will have to do the same for `isShuttingDown` variable as well..

---

*[x/error.go, line 193 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbTgXGplWRiGlNAMg99:-KbTq8Fhnwhk6A9iIzzz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/x/error.go#L193)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Add comment for exported func
</blockquote></details>

Done.

---

*[x/error.go, line 197 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbTgfVlRuZUPKUpuPpc:-KbTq9Y9AOclBL5OTLvV:b-ptlx4g) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/x/error.go#L197)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Might want to consider fmt.sprintf as this is not time critical.
buf.WriteString(fmt.Sprintf(...))
</blockquote></details>

strconv is more type safe.. so i prefer that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535)*

**Comment by manishrjain** [comment]
Let's have a chat today about this PR. Ping me when you see this.

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[cmd/dgraph/main.go, line 582 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgtLdDjGW1DxQsjd3E:-KbgtLdDjGW1DxQsjd3F:bix47jn) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L582)):*
> ```Go
> }
> 
> func shutdownServer() []error {
> ```

Just return one error, instead of a list of errors.

---

*[cmd/dgraph/main.go, line 700 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgtZYnGlFyAQOY4AzD:-KbgtZYnGlFyAQOY4AzE:b-5auo0o) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L700)):*
> ```Go
> 	graph.RegisterDgraphServer(s, &grpcServer{})
> 	err := s.Serve(l)
> 	if !isShuttingDown {
> ```

This variable is not being protected by mutex. You can use it as an atomic instead.

---

*[cmd/dgraph/main.go, line 703 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbguEZAzVqczmTWIovm:-KbguEZAzVqczmTWIovn:bxri4ac) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L703)):*
> ```Go
> 		x.Checkf(err, "Error while serving gRpc request")
> 	} else {
> 		s.GracefulStop()
> ```

serveGRPC function gets called pretty early on and never again, right? Do we really need to check here?

---

*[cmd/dgraph/main.go, line 716 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-Kbguct7ngo4UwTCz1j7:-Kbguct7ngo4UwTCz1j8:b-tg3c88) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L716)):*
> ```Go
> 	}
> 
> 	err := srv.Serve(l)
> ```

Wouldn't this block forever?

---

*[worker/index.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-Kbgv6TxQ-i9qO7_zRGG:-Kbgv6TxQ-i9qO7_zRGH:bk9gv1u) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/worker/index.go#L50)):*
> ```Go
> 	for n.applied.WaitingFor() {
> 		doneUntil := n.applied.DoneUntil() // applied until.
> 		x.Trace(ctx, "RebuildIndex waiting, appliedUntil:%d lastIndex: %d",
> ```

Remove RebuildIndex word.

---

*[worker/index.go, line 65 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgvCT8_XXbd27ieAXz:-KbgvCT8_XXbd27ieAY-:bk9gv1u) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/worker/index.go#L65)):*
> ```Go
> 	for w.WaitingFor() {
> 		doneUntil := w.DoneUntil() // synced until.
> 		x.Trace(ctx, "RebuildIndex waiting, syncedUntil:%d lastIndex:%d",
> ```

Remove RebuildIndex word.

---

*[x/error.go, line 195 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgvStiLuv3yVidtEcd:-KbgvStjWlEqbPZPR7hS:b-jomycu) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/x/error.go#L195)):*
> ```Go
> // StrinfifyErrors returns all errors combined in string form.
> // Format : 1. <first error msg> \n 2. <second error msg> ...so on..
> func StringifyErrors(errs []error) string {
> ```

This is not idiomatic Go. In Go, you just return the first error that you encounter, not accumulate them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-:-KbgvZVGr1i40Dj-DWlT:b-1e9l2t)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[cmd/dgraph/main.go, line 716 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-Kbguct7ngo4UwTCz1j7:-KbhTl7dUzgaUcqi5_wV:b-qvvz2k) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L716)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Wouldn't this block forever?
</blockquote></details>

if err := srv.Serve(l); err != nil {
  x.Printf(..)
}

---

*[cmd/dgraph/main.go, line 717 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbhTFEpvb36zKF1br0q:-KbhTFEpvb36zKF1br0r:b-1tdwx7) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L717)):*
> ```Go
> 
> 	err := srv.Serve(l)
> 	if !isShuttingDown {
> ```

You don't need this var.

---

*[worker/index.go, line 59 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbhWuhUnkSFQy-rOjui:-KbhWuhUnkSFQy-rOjuj:b2ngra3) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/worker/index.go#L59)):*
> ```Go
> 
> 	// Force an aggressive evict.
> 	posting.CommitLists(10)
> ```

(1)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535)*

**Comment by ashishnegi** [comment]
Review status: 0 of 5 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 582 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgtLdDjGW1DxQsjd3E:-KbjC3foNmunOBpY9V5V:b-lk971r) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L582)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just return one error, instead of a list of errors.
</blockquote></details>

Not needed now.

---

*[cmd/dgraph/main.go, line 700 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgtZYnGlFyAQOY4AzD:-KbjBuP0AS8stt5dRu7W:b-9xrkc9) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L700)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This variable is not being protected by mutex. You can use it as an atomic instead.
</blockquote></details>

Not needed. removed.

---

*[cmd/dgraph/main.go, line 703 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbguEZAzVqczmTWIovm:-KbjBxRhZVp5po7RJU38:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L703)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

serveGRPC function gets called pretty early on and never again, right? Do we really need to check here?
</blockquote></details>

Done.

---

*[cmd/dgraph/main.go, line 716 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-Kbguct7ngo4UwTCz1j7:-KbjCRzgcGU4IVJz3QaT:bdv5rwr) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L716)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if err := srv.Serve(l); err != nil {
  x.Printf(..)
}
</blockquote></details>

err is always non nil.

---

*[cmd/dgraph/main.go, line 717 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbhTFEpvb36zKF1br0q:-KbjC7cdq7ulj11nZNM7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/cmd/dgraph/main.go#L717)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need this var.
</blockquote></details>

Done.

---

*[worker/index.go, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbNpkyJecoWkSwqeKX_:-KbjCBjbRaTrjqmMGr-o:b-b859nl) ([raw file](https://github.com/dgraph-io/dgraph/blob/cd2f28935c2fcf96b2327af314ea2f4a7f2476ae/worker/index.go#L26)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

refactored code out to new fn : syncAllMarks
</blockquote></details>

Passing no of goroutines to run as from rebuildIndex, we passed 10.
from SyncAllMarks we pass 1.

---

*[worker/index.go, line 50 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-Kbgv6TxQ-i9qO7_zRGG:-KbjCLkFTKiA-UgFT_g5:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/worker/index.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove RebuildIndex word.
</blockquote></details>

Done.

---

*[worker/index.go, line 59 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbhWuhUnkSFQy-rOjui:-KbjCMQyJahhG_6tY9yo:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/worker/index.go#L59)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

(1)
</blockquote></details>

Done.

---

*[worker/index.go, line 65 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgvCT8_XXbd27ieAXz:-KbjCNFxQbr1BG4E7R-q:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/worker/index.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove RebuildIndex word.
</blockquote></details>

Done.

---

*[x/error.go, line 195 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbgvStiLuv3yVidtEcd:-KbjCP24oM0P5iSS5nUf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/72216fc4ab8e0672afbeca0a2af388544f74fde9/x/error.go#L195)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This is not idiomatic Go. In Go, you just return the first error that you encounter, not accumulate them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535)*

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 569 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbmVvltxyqUIXM1NUy_:-KbmVvltxyqUIXM1NUya:bu5rwng) ([raw file](https://github.com/dgraph-io/dgraph/blob/35b3c9b36131aa2d3ae6b1cb611b9742499288bc/cmd/dgraph/main.go#L569)):*
> ```Go
> 
> 	shutdownServer()
> 	x.SetStatus(w, x.Success, "Server has been shutdown")
> ```

Server is shutting down.

---

*[worker/index.go, line 39 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbmYn_eGBgeWopDubXB:-KbmYn_eGBgeWopDubXC:bu3oe6z) ([raw file](https://github.com/dgraph-io/dgraph/blob/35b3c9b36131aa2d3ae6b1cb611b9742499288bc/worker/index.go#L39)):*
> ```Go
> }
> 
> func (n *node) syncAllMarks(ctx context.Context, numCommitRoutines int) error {
> ```

Don't have arguments.

---

*[worker/worker.go, line 76 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbmYzKwfp-Z_cTatKjV:-KbmYzKwfp-Z_cTatKjW:b-15vu3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/35b3c9b36131aa2d3ae6b1cb611b9742499288bc/worker/worker.go#L76)):*
> ```Go
> // other workers for internal communication.
> // Sends on the finishCh when it finishes.
> func RunServer(bindall bool, finishCh chan<- struct{}) {
> ```

No finishCh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535)*

**Comment by ashishnegi** [comment]
Review status: 1 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/dgraph/main.go, line 569 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbmVvltxyqUIXM1NUy_:-KbmchyKdlxaZLlU1EEi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/35b3c9b36131aa2d3ae6b1cb611b9742499288bc/cmd/dgraph/main.go#L569)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Server is shutting down.
</blockquote></details>

Done.

---

*[worker/index.go, line 39 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbmYn_eGBgeWopDubXB:-Kbmcf0VeXDMgT_DHJ22:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/35b3c9b36131aa2d3ae6b1cb611b9742499288bc/worker/index.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't have arguments.
</blockquote></details>

Done.

---

*[worker/worker.go, line 76 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-KbmYzKwfp-Z_cTatKjV:-KbmcgP8D7zkDosAeLQA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/35b3c9b36131aa2d3ae6b1cb611b9742499288bc/worker/worker.go#L76)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No finishCh.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535)*

**Comment by manishrjain** [comment]
:lgtm: nice  work!

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[worker/index.go, line 59 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-Kbmhi5PkuoCOLpgpJHy:-Kbmhi5PkuoCOLpgpJHz:bh5h0sj) ([raw file](https://github.com/dgraph-io/dgraph/blob/3378d830e35ec45bbaf3bc70c8d74f0931767603/worker/index.go#L59)):*
> ```Go
> 
> 	// Force an aggressive evict.
> 	posting.CommitLists(1)
> ```

You can use 10 here. I think 10 makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-:-KbmhzwauLpX4vK9l7Zi:b-w3e9b0)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/535#-:-KbnH3rleUM1ZOQQXrG4:bnfp4nl)*

**Pull request closed without merging**
