### PR TITLE
Query/invalid keywords

### PR DESCRIPTION
**Pull request by ashishnegi**
check for valid function names.
check for valid argument names.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/538)

### CODE REVIEW

**Comment by jchiu0** [comment]
Just fix some comments. Thanks. :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 969 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-KbTAvaYucME5G0Jrq0N:-KbTAvaYucME5G0Jrq0O:b-t6votn) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5653862868bd1c809a7cab1541ff89a3de11b11/query/query.go#L969)):*
> ```Go
> 
> // Check valid argument keyword.
> func isValidArg(a string) bool {
> ```

Begin function comments with "isValidArg checks ..."

---

*[query/query.go, line 994 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-KbTB4y75EP7EmMFCXoq:-KbTB4y8OpDn_TzIgzsk:b-zbcwo7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5653862868bd1c809a7cab1541ff89a3de11b11/query/query.go#L994)):*
> ```Go
> }
> 
> func isEqualityFn(f string) bool {
> ```

maybe isCompareFn?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-:-KbTBEBJ5J0XLNIkvWRM:blmni8x)*

**Comment by ashishnegi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query.go, line 338 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-KbTYywipUnxjmlFVNQS:-KbTYywj84HNRdfPte6d:b-gpcw44) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5653862868bd1c809a7cab1541ff89a3de11b11/query/query.go#L338)):*
> ```Go
> 		}
> 		sg.SrcFunc = append(sg.SrcFunc, ft.Func.Name)
> 		sg.SrcFunc = append(sg.SrcFunc, ft.Func.Args...)
> ```

since we are adding `args` to `SrcFunc` , there is no very clean way to just check for valid fn keyword at one place in `ToSubGraph`..
Is there something better we can do ?

---

*[query/query.go, line 969 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-KbTAvaYucME5G0Jrq0N:-KbTZWg4EelUHAqE5is-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5653862868bd1c809a7cab1541ff89a3de11b11/query/query.go#L969)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Begin function comments with "isValidArg checks ..."
</blockquote></details>

Done.

---

*[query/query.go, line 994 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-KbTB4y75EP7EmMFCXoq:-KbTZXMnNSmyJpAAfzY8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5653862868bd1c809a7cab1541ff89a3de11b11/query/query.go#L994)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

maybe isCompareFn?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/538)*

**Comment by ashishnegi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query.go, line 338 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-KbTYywipUnxjmlFVNQS:-KbTtId8BtEHc6aJnVgW:b-6jfxd5) ([raw file](https://github.com/dgraph-io/dgraph/blob/d5653862868bd1c809a7cab1541ff89a3de11b11/query/query.go#L338)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

since we are adding `args` to `SrcFunc` , there is no very clean way to just check for valid fn keyword at one place in `ToSubGraph`..
Is there something better we can do ?
</blockquote></details>

talked with Ashwin, 
since SrcFunc will have only one function and rest as its args, this is by design.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/538)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/538#-:-KbU5hMw4bY5ESdvJkvH:bnfp4nl)*

**Pull request closed without merging**
