### PR TITLE
Docs(DQL)Document the `between` function

### PR DESCRIPTION
**Pull request by aaroncarey**
Updates to functions.md to document the `between` function:

- Noted the usage and types supported
- Provided a syntax example that should be correct (but that causes errors on the site in the "runnable" context because `between` is not yet available in production)

@pawanrawal and @minhaj-shakeel , please let me know if we need to add any caveats or other notes.

fixes DGRAPH-2538

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6711)

 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-9ed67ab392-101324.surge.sh)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6711)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @aaroncarey, @bucanero, @danielmai, @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/query-language/functions.md, line 403 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6711#-MJW7WdV-ATko-mrvYUl:-MJW7WdV-ATko-mrvYUm:bp78hp6) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a80cdb29ff29b3f5b455e197243a92ad0f1e91c/wiki/content/query-language/functions.md#L403)):*
> ```Markdown
> Syntax Example: `between(predicate, startDateValue, endDateValue)`
> 
> Schema Types: `dateTime`
> ```

This filter should work for other scalar types as well like `int`, `float`, `string` etc.
___
*[wiki/content/query-language/functions.md, line 417 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6711#-MJW7dSv5f6jD7v5mNuH:-MJW7dSwC4V1lfzZh0yD:b-6ui2ik) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a80cdb29ff29b3f5b455e197243a92ad0f1e91c/wiki/content/query-language/functions.md#L417)):*
> ```Markdown
>   me(func: eq(name@en, "Ridley Scott")) {
>     name@en
>     director.film @filter(between(initial_release_date, "1976-01-01", "1983-01-01"))  {
> ```

I think it only works at the root right now and not inside a filter so we should only add an example for a root query. Something like below.

```
{
  me(func: between(initial_release_date, <start>, <end>)) {
    name@en
    genre {
      name@en
    }
  }
}
```

**Review by aaroncarey — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6711)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @bucanero, @danielmai, @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/query-language/functions.md, line 403 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6711#-MJW7WdV-ATko-mrvYUl:-MJXz1tn3o5xw2ZCCRHZ:b9dxjww) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a80cdb29ff29b3f5b455e197243a92ad0f1e91c/wiki/content/query-language/functions.md#L403)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This filter should work for other scalar types as well like `int`, `float`, `string` etc.
</blockquote></details>

Done. Great feedback!
___
*[wiki/content/query-language/functions.md, line 417 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6711#-MJW7dSv5f6jD7v5mNuH:-MJXzsk3C2t774yr7x6j:b-ydtmza) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a80cdb29ff29b3f5b455e197243a92ad0f1e91c/wiki/content/query-language/functions.md#L417)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I think it only works at the root right now and not inside a filter so we should only add an example for a root query. Something like below.

```
{
  me(func: between(initial_release_date, <start>, <end>)) {
    name@en
    genre {
      name@en
    }
  }
}
```
</blockquote></details>

Great! I went with the following:
+++
Query Example: Movies released between 1976 and 1983, listed by genre.


{
  me(func: between(initial_release_date, "1976-01-01", "1983-01-01")) {
    name@en
    genre {
      name@en
    }
  }
}
+++

**Review by aaroncarey — COMMENTED** [review]
Feedback incorporated.

**Review by aaroncarey — COMMENTED** [review]
Changes implemented

**Comment by aaroncarey** [comment]
FYI, it is staged here: https://dgraph-04dd924ae0-101287.surge.sh/query-language/functions/#between

**Review by bucanero — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6711)* status: all files reviewed, 2 unresolved discussions (waiting on @danielmai, @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

**Pull request merged**
