### PR TITLE
Update/rocksdb5

### PR DESCRIPTION
**Pull request by gacharya255**
Some new functions of RocksDB might be useful, e.g., SeekForPrev.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/646)

### CODE REVIEW

**Comment by pawanrawal** [comment]
I think you committed `cmd/p` and `cmd/w` by mistake? Apart from that looks ok.

---

Reviewed 840 of 840 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/646#-:-Ke69UlTdRL-dHaeM9w3:b6czj70)*

**Comment by pawanrawal** [comment]
Also, please update Wiki too.

**Comment by ashwin95r** [comment]
:lgtm:  please remove the cmd/. Also, we can use the SeekForPrev in the place discussed yesterday.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/646#-:-Ke6DVRQo4s_-OdqW8Vk:b-x2rdou)*

**Comment by gacharya255** [comment]
Thanks @pawan @ashwin for noticing the cmd. I should really add those gitignore.. Yes I have tested these binaries and they seem ok.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/646#-:-Ke7UCvhNEZBiE83sNcQ:bh4vkbt)*

**Comment by gacharya255** [comment]
@pawan The wiki has been updated.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/646#-:-Ke7vs85xD6F2xm4IQRo:b-vyd2uw)*

**Pull request closed without merging**
