### PR TITLE
Bulkloader performance enhancements

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1433)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/bulkloader/loader.go, line 41 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiX-KQNslqN6xhov99:-KtiX-KQNslqN6xhov9A:b-honewp) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/loader.go#L41)):*
> ```Go
> 	rdfCh      chan string
> 	postingsCh chan *protos.FlatPosting
> 	mapId      uint32
> ```

Add a comment about this id. rename to `mapFileId`. Say that it's accessed via atomic functions to name the files output by mapper.

---

*[cmd/bulkloader/loader.go, line 121 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXJmIp-YC6LtyR5-D:-KtiXJmIp-YC6LtyR5-E:bw6erd0) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/loader.go#L121)):*
> ```Go
> 
> func (ld *loader) reduceStage() {
> 	atomic.AddInt32(&ld.prog.reducePhase, 1)
> ```

Have some enums. So, have a NOTHING, MAP_PHASE, REDUCE_PHASE, and set and check accordingly.

---

*[cmd/bulkloader/main.go, line 28 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXngYVemV_qanyVtN:-KtiXngYVemV_qanyVtO:bqv81v4) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/main.go#L28)):*
> ```Go
> 	flag.StringVar(&opt.rdfFiles, "r", "", "Location of rdf files to load (comma separated)")
> 	flag.StringVar(&opt.schemaFile, "s", "", "Location of schema file to load")
> 	flag.StringVar(&opt.badgerDir, "p", "", "Location of the final Dgraph directory")
> ```

We should clear up the Badger directory before starting.

---

*[cmd/bulkloader/main.go, line 46 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXYonIN2fG2GfB226:-KtiXYonIN2fG2GfB227:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/main.go#L46)):*
> ```Go
> 	}
> 
> 	x.AssertTruef(opt.mapBufSize > 0, "Please specify how much memory is available for this program.")
> ```

100 chars.

---

*[cmd/bulkloader/main.go, line 52 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXaqYxUNfigPue8is:-KtiXaqYxUNfigPue8it:bhueohe) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/main.go#L52)):*
> ```Go
> 		log.Fatal(http.ListenAndServe(*httpAddr, nil))
> 	}()
> 	runtime.SetBlockProfileRate(*blockRate)
> ```

if *blockRate > 0 { then set }

---

*[posting/list.go, line 259 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiYmyjVNJK1V7QOvXx:-KtiYmyjVNJK1V7QOvXy:b-jsd12s) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/posting/list.go#L259)):*
> ```Go
> 	}
> 
> 	p.Uid = t.ValueId
> ```

`*p = protos.Posting { Uid: ...,\n Value: ..., }`

---

*[protos/bulkloader.proto, line 7 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiZlkq9FRWuqM_8I5P:-KtiZlkq9FRWuqM_8I5Q:bn4hdm8) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/protos/bulkloader.proto#L7)):*
> ```protobuf
> package protos;
> 
> message FlatPosting {
> ```

`Mapoutput, MapOut, MapData, ...`

---

*[protos/bulkloader.proto, line 11 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiZJu-uScnYqWF5fuW:-KtiZJu-uScnYqWF5fuX:b-gv9rcz) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/protos/bulkloader.proto#L11)):*
> ```protobuf
> 
> 	// Only one should be set.
> 	fixed64 uid_only = 2;
> ```

fixed64 uid

---

*[protos/bulkloader.proto, line 12 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiZLMhbMZgy0JfWgYf:-KtiZLMhbMZgy0JfWgYg:b-sc93s1) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/protos/bulkloader.proto#L12)):*
> ```protobuf
> 	// Only one should be set.
> 	fixed64 uid_only = 2;
> 	Posting full = 3;
> ```

Posting posting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433)*

**Comment by manishrjain** [comment]
Review status: 0 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[protos/bulkloader.proto, line 7 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiZlkq9FRWuqM_8I5P:-Kti_E-ObU01Wl7znZ_W:bq5kx47) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/protos/bulkloader.proto#L7)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`Mapoutput, MapOut, MapData, ...`
</blockquote></details>

Maybe `MapEntry`, because `LogEntry`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433)*

**Comment by peterstace** [comment]
Review status: 0 of 12 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/bulkloader/loader.go, line 41 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiX-KQNslqN6xhov99:-KtilTHV6OJ2NdxkSWmg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/loader.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment about this id. rename to `mapFileId`. Say that it's accessed via atomic functions to name the files output by mapper.
</blockquote></details>

Done.

---

*[cmd/bulkloader/loader.go, line 121 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXJmIp-YC6LtyR5-D:-Ktj6-GoIqwASwvgRf6l:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/loader.go#L121)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Have some enums. So, have a NOTHING, MAP_PHASE, REDUCE_PHASE, and set and check accordingly.
</blockquote></details>

Done.

---

*[cmd/bulkloader/main.go, line 28 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXngYVemV_qanyVtN:-KtimQ9pdu9eTRJQVpkE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/main.go#L28)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We should clear up the Badger directory before starting.
</blockquote></details>

Done.

---

*[cmd/bulkloader/main.go, line 46 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXYonIN2fG2GfB226:-KtimYjZ8kL44rmA9a9_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/main.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[cmd/bulkloader/main.go, line 52 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiXaqYxUNfigPue8is:-Ktiml-gy-T-bjWiQCXZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/cmd/bulkloader/main.go#L52)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

if *blockRate > 0 { then set }
</blockquote></details>

Done.

---

*[posting/list.go, line 259 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiYmyjVNJK1V7QOvXx:-KtinS4urJ7Y_Of6HCHs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/posting/list.go#L259)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`*p = protos.Posting { Uid: ...,\n Value: ..., }`
</blockquote></details>

Done.

---

*[protos/bulkloader.proto, line 7 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiZlkq9FRWuqM_8I5P:-Ktit6qMXs0OmU44iAQU:b-o85wgf) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/protos/bulkloader.proto#L7)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe `MapEntry`, because `LogEntry`.
</blockquote></details>

Went with `MapEntry`.

---

*[protos/bulkloader.proto, line 11 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiZJu-uScnYqWF5fuW:-KtitAG2XPeLkUt0tJ2k:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/protos/bulkloader.proto#L11)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

fixed64 uid
</blockquote></details>

Done.

---

*[protos/bulkloader.proto, line 12 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtiZLMhbMZgy0JfWgYf:-KtitB1iWNHWri9ReHzX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7d0127746d1f2c6f17b5e76846a073b03fb3b071/protos/bulkloader.proto#L12)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Posting posting
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433)*

**Comment by manishrjain** [comment]
:lgtm: Comments.

---

Reviewed 2 of 6 files at r1, 1 of 5 files at r5, 9 of 9 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/bulkloader/loader.go, line 73 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtjPuBMokzVhVmZjoBv:-KtjPuBMokzVhVmZjoBw:b4195l6) ([raw file](https://github.com/dgraph-io/dgraph/blob/32fc3ad954f73bb01389a5840b328427f4566b5b/cmd/bulkloader/loader.go#L73)):*
> ```Go
> 
> func (ld *loader) mapStage() {
> 	ld.prog.setPhase(MAP_PHASE)
> ```

Change the name. Go has a different style.

---

*[cmd/bulkloader/mapper.go, line 45 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtjQYT8nfdS1ICEAk-N:-KtjQYT8nfdS1ICEAk-O:b4slyhx) ([raw file](https://github.com/dgraph-io/dgraph/blob/32fc3ad954f73bb01389a5840b328427f4566b5b/cmd/bulkloader/mapper.go#L45)):*
> ```Go
> }
> 
> func (m *mapper) writeMapEntries() {
> ```

writeMapEntiesToFile

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-:-KtjQvClwSQ5-UR0FxgQ:b9wrqbv)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cmd/bulkloader/loader.go, line 73 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtjPuBMokzVhVmZjoBv:-KtjX13fIAcQhY8xOaGe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/32fc3ad954f73bb01389a5840b328427f4566b5b/cmd/bulkloader/loader.go#L73)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Change the name. Go has a different style.
</blockquote></details>

Done.

---

*[cmd/bulkloader/mapper.go, line 45 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433#-KtjQYT8nfdS1ICEAk-N:-KtjXDzwIE13gU8oD4wC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/32fc3ad954f73bb01389a5840b328427f4566b5b/cmd/bulkloader/mapper.go#L45)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

writeMapEntiesToFile
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1433)*

**Pull request merged**
