### PR TITLE
Pass Values instead of bytes for indexing

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/281)

### CODE REVIEW

**Comment by kostub** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[geo/s2index.go, line 33 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx39dwZqfdRIGvhqec:-KTx39dwZqfdRIGvhqed:b-77nmz8) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/geo/s2index.go#L33)):*
> ```Go
> func IndexKeys(val *types.Geo) ([][]byte, error) {
> 	// Try to parse the data as geo type.
> 	return IndexKeysFromGeo(*val)
> ```

We don't need a wrapper function any more. Just call IndexKeysFromGeo directly. You also don't need the "FromGeo" in the name of the function.

---

*[posting/index.go, line 60 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx3w4ImygOLlw8Zip9:-KTx3w4ImygOLlw8ZipA:b-lujtbh) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/posting/index.go#L60)):*
> ```Go
> 		return nil, err
> 	}
> 	switch s.ID() {
> ```

Instead of doing this why do don't you create an interface Indexer and then do
ind, ok := s.(Indexer)
if ok {
    return ind.IndexKeys()
}

---

*[types/date.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx5C9SAKOKfFh-35t8:-KTx5C9SAKOKfFh-35t9:bpcoxnf) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/types/date.go#L30)):*
> ```Go
> // attached.
> type Date struct {
> 	Time time.Time
> ```

If Index is a function on values, then you don't need to export this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/281)*

**Comment by kostub** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[types/conversion.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx65dZsvEyAGq9k5e-:-KTx65dZsvEyAGq9k5e0:b7nky0l) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/types/conversion.go#L27)):*
> ```Go
> // Convert converts the value to given scalar type.
> func (to Scalar) Convert(value Value) (Value, error) {
> 	if to.ID() == value.Type().ID() {
> ```

Can you add some tests to conversion_test.go that check this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/281)*

**Comment by ashwin95r** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[geo/s2index.go, line 33 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx39dwZqfdRIGvhqec:-KTxHuwo8Az3LDzScb7q:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/geo/s2index.go#L33)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> We don't need a wrapper function any more. Just call IndexKeysFromGeo directly. You also don't need the "FromGeo" in the name of the function.
</details>
Done.

---

*[posting/index.go, line 60 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx3w4ImygOLlw8Zip9:-KTxUzEnUru5sYJRyk9e:bjdplsi) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/posting/index.go#L60)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Instead of doing this why do don't you create an interface Indexer and then do
> ind, ok := s.(Indexer)
> if ok {
>     return ind.IndexKeys()
> }
</details>
Not sure if we want to do this now. We have a separate package for geo. We could also be moving the partial match to some package (tok). Maybe we could do it as and when its clear I feel.

---

*[types/conversion.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx65dZsvEyAGq9k5e-:-KTxJR68-oYCgqbe3TEi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/types/conversion.go#L27)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Can you add some tests to conversion_test.go that check this.
</details>
Done.

---

*[types/date.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx5C9SAKOKfFh-35t8:-KTxTzglLcuAdc4ctPV6:bukmjdr) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/types/date.go#L30)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> If Index is a function on values, then you don't need to export this.
</details>
The Time value has this exported, so I thought we could export this as well. Also, moving it based on the type would require moving all other types as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/281)*

**Comment by kostub** [comment]
One small style comment.

:lgtm:

---

Reviewed 4 of 8 files at r1, 3 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 60 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx3w4ImygOLlw8Zip9:-KTzSfFqkI9dE-9mttUH:b2jwgkm) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/posting/index.go#L60)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Not sure if we want to do this now. We have a separate package for geo. We could also be moving the partial match to some package (tok). Maybe we could do it as and when its clear I feel.
</details>
Makes sense. At least do this

`switch v := switch(schemaVal.(type)`

Then you can get rid of all the unsightly conversions and replace it by something like:
```
case *stype.Int32:
         return stype.IntIndex(attr, v)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-:-KTzTbYGg36abX9Qjth2:b43sc82)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 60 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/281#-KTx3w4ImygOLlw8Zip9:-KU0GpmjmWN6Kh-8JWyB:bs7wumx) ([raw file](https://github.com/dgraph-io/dgraph/blob/c22165dff80c2a6a53ea824c532fe15162e8775f/posting/index.go#L60)):*
<details><summary><i>Previously, kostub (Kostub Deshmukh) wrote…</i></summary>
> Makes sense. At least do this
> 
> `switch v := switch(schemaVal.(type)`
> 
> Then you can get rid of all the unsightly conversions and replace it by something like:
> ```
> case *stype.Int32:
>          return stype.IntIndex(attr, v)
> ```
</details>
Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/281)*

**Comment by ashwin95r** [comment]
Merged to master with commit e56fc7fe3e55d42139f4c989e9033abb70d9ca24.

**Pull request closed without merging**
