### PR TITLE
Speedup rebuild index

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/759)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/index.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/759#-KgDmsDdJURflYBnvBgu:-KgDmsDdJURflYBnvBgv:bf2c6sv) ([raw file](https://github.com/dgraph-io/dgraph/blob/29e9585b2aeb1d9f51cb92d98a54210f9f02687b/posting/index.go#L363)):*
> ```Go
> 		}
> 	}
> 	close(ch)
> ```

We should wait till the indexing goroutines have returned.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/759)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/index.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/759#-KgDmsDdJURflYBnvBgu:-KgDnzd4fvOe_tV5j1VR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/29e9585b2aeb1d9f51cb92d98a54210f9f02687b/posting/index.go#L363)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We should wait till the indexing goroutines have returned.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/759)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/759#-:-KgDojvWi-sj9xdy1Yrn:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/759#-:-KgDqCQrCauk6aYEyv2x:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to release.

**Pull request closed without merging**
