### PR TITLE
fix(GraphQL): This PR fixes subscriptions flakey tests.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes GRAPHQL-816
Subscriptions tests were flakey because the badger sends multiple schema updates which cause subscriptions to terminate.
Fixed this by not updating the schema if we have the same schema previously.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6921)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6921)* status: all files reviewed, 6 unresolved discussions (waiting on @JatinDevDG and @MichaelJCompton)

___
*[graphql/admin/admin.go, line 536 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZePGK88L4WGbFLl3p:-MMZePGK88L4WGbFLl3q:b-rtvnpj) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/admin/admin.go#L536)):*
> ```Go
> 		server.mux.Lock()
> 		if newSchema.Schema == server.schema.Schema {
> 			glog.Infof("Skipping Schema Update: Already have this schema")
> ```

Skipping GraphQL schema update as the new schema is the same as the current schema.
___
*[graphql/e2e/subscription/subscription_test.go, line 74 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZeiiaC3JmEZMooijz:-MMZeiiaC3JmEZMooik-:b-78vmnm) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L74)):*
> ```Go
> )
> 
> var subExp = 3 * time.Second
> ```

const subExp = 3 * time.Second
___
*[graphql/e2e/subscription/subscription_test.go, line 75 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZemDp2Mpu6mPac4e6:-MMZemDp2Mpu6mPac4e7:bw0pn0g) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L75)):*
> ```Go
> 
> var subExp = 3 * time.Second
> var subscriptionResp common.GraphQLResponse
> ```

Don't use global variables. Define it in whichever test it is needed.
___
*[graphql/e2e/subscription/subscription_test.go, line 161 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZf7Dy3OynswQa7K3f:-MMZf7Dy3OynswQa7K3g:bgci9n6) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L161)):*
> ```Go
> 
> 	// Change schema to terminate subscription..
> 	add = &common.GraphQLParams{
> ```

Don't remove this but instead change the schema so that we can verify that the subscription is terminated on a schema update.
___
*[graphql/e2e/subscription/subscription_test.go, line 365 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZfNOZ6An_KhUpIzT7:-MMZfNOZ6An_KhUpIzT8:b-c5lxet) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L365)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	subscriptionResp = common.GraphQLResponse{}
> ```

No need to change to subscriptionResp from resp here.
___
*[graphql/e2e/subscription/subscription_test.go, line 469 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZfSKwCETMj5xNaW8v:-MMZfSKwCETMj5xNaW8w:bogmw6m) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L469)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	subscriptionResp = common.GraphQLResponse{}
> ```

revert name change

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6921)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @MichaelJCompton and @pawanrawal)

___
*[graphql/admin/admin.go, line 536 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZePGK88L4WGbFLl3p:-MM_AcTr0lIvCAfzgKk-:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/admin/admin.go#L536)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Skipping GraphQL schema update as the new schema is the same as the current schema.
</blockquote></details>

changed.
___
*[graphql/e2e/subscription/subscription_test.go, line 74 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZeiiaC3JmEZMooijz:-MM_AdmC4qVHfqtUiY5q:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L74)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

const subExp = 3 * time.Second
</blockquote></details>

changed.
___
*[graphql/e2e/subscription/subscription_test.go, line 75 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZemDp2Mpu6mPac4e6:-MM_AfDM5m338LBmmldx:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L75)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't use global variables. Define it in whichever test it is needed.
</blockquote></details>

changed.
___
*[graphql/e2e/subscription/subscription_test.go, line 161 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZf7Dy3OynswQa7K3f:-MM_Ajfg1E60xxCdq0WO:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L161)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't remove this but instead change the schema so that we can verify that the subscription is terminated on a schema update.
</blockquote></details>

changed.
___
*[graphql/e2e/subscription/subscription_test.go, line 365 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZfNOZ6An_KhUpIzT7:-MM_AmKS6F82NLI9d-xX:b-81taoq) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L365)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

No need to change to subscriptionResp from resp here.
</blockquote></details>

reverted.
___
*[graphql/e2e/subscription/subscription_test.go, line 469 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZfSKwCETMj5xNaW8v:-MM_Ao1Z2dHhQY7hiI-8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/e2e/subscription/subscription_test.go#L469)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

revert name change
</blockquote></details>

Done.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6921)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/admin/admin.go, line 536 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MMZePGK88L4WGbFLl3p:-MM_FqLjEV4LJ6yTBS7w:b-jae17i) ([raw file](https://github.com/dgraph-io/dgraph/blob/50ecf9087818f821dbf77651166947005a021d2f/graphql/admin/admin.go#L536)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

changed.
</blockquote></details>

You updated it at the wrong place
___
*[graphql/e2e/subscription/subscription_test.go, line 927 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MM_GVGDBgkCy1CJ7Uxt:-MM_GVGE2nY2-RpGzuqP:bjgxht4) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L927)):*
> ```Go
> 	require.Nil(t, addResult.Errors)
> 
> 	jwtToken, err := metaInfo.GetSignedToken("secret", 10*time.Second)
> ```

Why have this change?
___
*[graphql/e2e/subscription/subscription_test.go, line 984 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MM_GXTe8Qah0TlaEMJl:-MM_GXTe8Qah0TlaEMJm:bof5wou) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L984)):*
> ```Go
> 	}
> 
> 	jwtToken, err := metaInfo.GetSignedToken("secret", 5*time.Second)
> ```

Why do you need this change?
___
*[graphql/e2e/subscription/subscription_test.go, line 1013 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MM_GcYlEw3o2TuqmE2H:-MM_GcYlEw3o2TuqmE2I:b-8cnzbm) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L1013)):*
> ```Go
> 	time.Sleep(time.Second)
> 
> 	jwtToken1, err := metaInfo.GetSignedToken("secret", 5*time.Second)
> ```

Why change this?

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6921)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @JatinDevDG, @MichaelJCompton, and @pawanrawal)

___
*[graphql/e2e/subscription/subscription_test.go, line 927 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MM_GVGDBgkCy1CJ7Uxt:-MM_Hd-v6RY0WITCTy8L:b-vd7pu) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L927)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why have this change?
</blockquote></details>

Because in this test, we are not checking for subscription expiry. Just start the subscription and terminate it at the end.
___
*[graphql/e2e/subscription/subscription_test.go, line 984 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MM_GXTe8Qah0TlaEMJl:-MM_HrnZ9yYELANh-JZd:b1jet0p) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L984)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why do you need this change?
</blockquote></details>

same comment as above.
___
*[graphql/e2e/subscription/subscription_test.go, line 1013 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6921#-MM_GcYlEw3o2TuqmE2H:-MM_Hwj7DoL1B7hqz_Rv:b-1lcdxf) ([raw file](https://github.com/dgraph-io/dgraph/blob/daac8cefaa7e11afdb4f605b42700956ec1b46d9/graphql/e2e/subscription/subscription_test.go#L1013)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Why change this?
</blockquote></details>

I reduced this time because below when we are waiting for the second update from the subscription it waits till the end of the subscription or an update. since we are not sending any update to it waits till 3 sec or whatever we put here.

**Review by pawanrawal — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6921)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @MichaelJCompton and @pawanrawal)

**Pull request merged**
