### PR TITLE
Geo spatial indexing using s2

### PR DESCRIPTION
**Pull request by kostub**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/264)

### CODE REVIEW

**Comment by kostub** [comment]
This change is now ready for review.

**Comment by ashwin95r** [comment]
Reviewed 1 of 33 files at r1, 1 of 6 files at r4.
Review status: 2 of 37 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 74 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTTIOVKZjkNUNEa2Uby:-KTTIOVKZjkNUNEa2Ubz:bpbedum) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/posting/index.go#L74)):*
> ```Go
> }
> 
> func indexKeys(attr string, data []byte) ([]string, error) {
> ```

Could be renamed to tokenizedIndexKeys() I think (as there is already an IndexKey).

---

*[posting/index.go, line 75 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTTIxYAkzyWnNWK7xP9:-KTTIxYBoOFcD8kBXiwe:b-52s56x) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/posting/index.go#L75)):*
> ```Go
> 
> func indexKeys(attr string, data []byte) ([]string, error) {
> 	t := schema.TypeOf(attr)
> ```

Could be an object type as well. So, a check to ensure that it's a scalar type here would be good. or we could handle it in switch case.

---

*[posting/index.go, line 93 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTTIfT9OcPu9pwUrqjP:-KTTIfT9OcPu9pwUrqjQ:bcovltm) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/posting/index.go#L93)):*
> ```Go
> 	}
> 	for _, key := range keys {
> 		edge := x.DirectedEdge{
> ```

This declaration could go out of the loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/264)*

**Comment by ashwin95r** [comment]
Reviewed 1 of 5 files at r2, 2 of 6 files at r4.
Review status: 5 of 37 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/264)*

**Comment by jchiu0** [comment]
Review status: 5 of 37 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[geo/earth.go, line 28 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTmWK9snuLqAYvzvnqR:-KTmWK9tLVeZhbvTsQ6s:b1rzbip) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/geo/earth.go#L28)):*
> ```Go
> 
> // EarthRadiusMeters is the radius of the earth in meters (in a spherical earth model).
> const EarthRadiusMeters = 1000 * 6371
> ```

Could be more precise in meters?

---

*[geo/earth.go, line 43 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTmYHMMqXU8yjFToXE4:-KTmYHMMqXU8yjFToXE5:b-3p9izo) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/geo/earth.go#L43)):*
> ```Go
> // EarthArea converts an area on the unit square to an area on earth in sq. meters.
> func EarthArea(a float64) Area {
> 	return Area(a * EarthRadiusMeters * EarthRadiusMeters)
> ```

Should this be a * 4*pi*R^2?

---

*[geo/earth.go, line 59 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTmVXqvnURKXKwY1lng:-KTmVXqvnURKXKwY1lnh:b-v0355s) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/geo/earth.go#L59)):*
> ```Go
> const cm2 = 100 * 100
> 
> func (a Area) String() string {
> ```

Add comment for String().

---

*[geo/s2index.go, line 231 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTmb4p2RqDmxxiANxeg:-KTmb4p2RqDmxxiANxeh:bmph4lt) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/geo/s2index.go#L231)):*
> ```Go
> }
> 
> func coverLoop(l *s2.Loop, minLevel int, maxLevel int, maxCells int) s2.CellUnion {
> ```

If used in only one location, might want to just inline it.

---

*[posting/index.go, line 70 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTmZ8r5pgizBDjpIvnN:-KTmZ8r5pgizBDjpIvnO:bo3efp9) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/posting/index.go#L70)):*
> ```Go
> }
> 
> func exactMatchIndexKeys(attr string, data []byte) []string {
> ```

When this is written, I have in mind the use of []byte instead of string. The reason is that the data is given to us as a []byte and when I use ICU, I can pass []byte directly to be tokenized and I was trying to save a copy from []byte to string. The second reason is that when we build this stuff, we usually use a bytes.Buffer (as you did in s2index.go) and we can use the bytes buffer directly instead of converting to string.

BUT, I totally understand that strings are nicer to work with. So I am torn about this.

If you are ok with using []byte instead of strings, then s2index.go should return []byte and we can use []byte throughout. Otherwise, do you mind merging exactMatchIndexKeys and IndexKeys and just return buf.String() instead of buf.Bytes()?

---

*[posting/index.go, line 109 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTmbbIj7ll6GAj1Rkak:-KTmbbIj7ll6GAj1Rkal:b-h244xj) ([raw file](https://github.com/dgraph-io/dgraph/blob/42f1a66649bcf8188464f96fecd0792938d566df/posting/index.go#L109)):*
> ```Go
> 					string(key), edge.Attribute, edge.Entity))
> 			}
> 			indexLog.Printf("DEL [%s] [%d] OldTerm [%s]", edge.Attribute, edge.Entity, string(key))
> ```

If key is already a string, no need to convert. We should probably just use strings..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/264)*

**Comment by ashwin95r** [comment]
:lgtm: Jiawei had a few comments. Feel free to merge once those are addressed.

---

Review status: 2 of 37 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-:-KTmidXL_Z2u2oimwCno:b-cqk2tc)*

**Comment by jchiu0** [comment]
:lgtm: Just one minor comment.

---

Review status: 0 of 37 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[posting/index.go, line 104 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-KTmowpRbmy1ofZB42DN:-KTmowpS3NdvIwyv7PJv:b-6lbaly) ([raw file](https://github.com/dgraph-io/dgraph/blob/0a8a42af2198a564f412ab2b9f929e20fe96cf6b/posting/index.go#L104)):*
> ```Go
> 
> 	for _, key := range keys {
> 		plist, decr := GetOrCreate([]byte(key), indexStore)
> ```

No need to cast to []byte anymore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/264#-:-KTmp39mF66NXBvz6rwN:b-srex3b)*

**Pull request closed without merging**
