### PR TITLE
Bulkloader: add count indexing

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1431)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[cmd/bulkloader/count_index.go, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiSehLKPAFGedKy7Le:-KtiSehLKPAFGedKy7Lf:beciym6) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L12)):*
> ```Go
> 	"github.com/dgraph-io/dgraph/x"
> )
> ```

type current struct {
pred string
rev bool
schema *protos.SchemaUpdate
}

---

*[cmd/bulkloader/count_index.go, line 13 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiSqNc7d7TnJo2W7nM:-KtiSqNc7d7TnJo2W7nN:bvly6ww) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L13)):*
> ```Go
> )
> 
> type countIndexer struct {
> ```

Consider making it child of state.

---

*[cmd/bulkloader/count_index.go, line 23 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiTEnXV_d34Mns5COT:-KtiTEnXV_d34Mns5COU:b-pe8awz) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L23)):*
> ```Go
> }
> 
> func (c *countIndexer) add(rawKey []byte, count int) {
> ```

addUid(rawKey []byte, count int)

Add comments.

---

*[cmd/bulkloader/count_index.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiWgofHsuJ9QCUnBJ9:-KtiWgofHsuJ9QCUnBJA:b69iy5t) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L27)):*
> ```Go
> 	if !key.IsData() && !key.IsReverse() {
> 		return
> 	}
> ```

All the returns should be done asap.

if key.IsReverse() == c.rev ..  && dont' track this{ return }

---

*[cmd/bulkloader/count_index.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiTgtMCY5cKGJ05iSd:-KtiTgtMCY5cKGJ05iSe:bozy446) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L28)):*
> ```Go
> 		return
> 	}
> 	if key.IsReverse() != c.rev || key.Attr != c.pred {
> ```

Add comments here.

---

*[cmd/bulkloader/count_index.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiWI04GphRavsHo1Ir:-KtiWI04GphRavsHo1Is:ba05rzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L31)):*
> ```Go
> 		if len(c.counts) > 0 {
> 			c.wg.Add(1)
> 			go c.writeIndex(c.pred, c.rev, c.counts)
> ```

`c.counts = make(map..)`

---

*[cmd/bulkloader/count_index.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiW9ZzmV9AGN5Q8S-6:-KtiW9ZzmV9AGN5Q8S-7:b-aqyrko) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L35)):*
> ```Go
> 		c.pred = key.Attr
> 		c.rev = key.IsReverse()
> 		c.counts = make(map[int][]uint64)
> ```

This would be expensive, particularly given it won't be used most of the time. Do it within the if.

---

*[cmd/bulkloader/count_index.go, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiUzml5YlG4rQInYmO:-KtiUzml5YlG4rQInYmP:b-p6bzd8) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L36)):*
> ```Go
> 		c.rev = key.IsReverse()
> 		c.counts = make(map[int][]uint64)
> 		c.schema = c.ss.getSchema(key.Attr)
> ```

You don't really need the schema. Just keep track of whether this predicate has a count index or not.

---

*[cmd/bulkloader/count_index.go, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiVA-vkinX23RzoYjc:-KtiVA-vkinX23RzoYjd:b-aycqiv) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L37)):*
> ```Go
> 		c.counts = make(map[int][]uint64)
> 		c.schema = c.ss.getSchema(key.Attr)
> 	}
> ```

else if !c.cur.track { // if equal
  return
}

// Do what needs to be done.

---

*[cmd/bulkloader/loader.go, line 142 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiU8SMZCuuKPp5yrPY:-KtiU8SMZCuuKPp5yrPZ:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/loader.go#L142)):*
> ```Go
> 	// Shuffle concurrently with reduce.
> 	ci := &countIndexer{ss: ld.ss, kv: ld.kv}
> 	reduceCh := make(chan []*protos.FlatPosting, 3) // Small buffer size since each element has a lot of data.
> ```

100 chars.

---

*[cmd/bulkloader/write_flat.go, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiULXSuPTwV3QL1tc-:-KtiULXSuPTwV3QL1tc0:b-dyijkp) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/write_flat.go#L119)):*
> ```Go
> 	batch := make([]*protos.FlatPosting, 0, batchAlloc)
> 	var prevKey []byte
> 	var edgesInPL int
> ```

var plistLen int
Add a comment. See if you can get rid of this var.

---

*[cmd/bulkloader/write_flat.go, line 144 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiUcjwwAAHaf_P54ge:-KtiUcjx_IQ9N6bkYnP7:b-i9abez) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/write_flat.go#L144)):*
> ```Go
> 		batch = append(batch, p)
> 		edgesInPL++
> 	}
> ```

Call it again after for loop here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[cmd/bulkloader/count_index.go, line 12 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiSehLKPAFGedKy7Le:-Ktiacf6CbMX7O75fJWL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L12)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

type current struct {
pred string
rev bool
schema *protos.SchemaUpdate
}
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 13 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiSqNc7d7TnJo2W7nM:-KtibVcbM8vuwpYVRzZR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L13)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Consider making it child of state.
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 23 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiTEnXV_d34Mns5COT:-Ktidy0-RL3SkrHly-zf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L23)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

addUid(rawKey []byte, count int)

Add comments.
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiWgofHsuJ9QCUnBJ9:-KtihIVHSm3tlXPIekiL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L27)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

All the returns should be done asap.

if key.IsReverse() == c.rev ..  && dont' track this{ return }
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 28 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiTgtMCY5cKGJ05iSd:-KtihPtbRNAWoL0yOfdf:b-x5blqy) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L28)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add comments here.
</blockquote></details>

The way I restructured the code introduces a variable called `sameIndexKey` which I think makes the code clear enough that we don't need a comment.

---

*[cmd/bulkloader/count_index.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiWI04GphRavsHo1Ir:-KtihphM2bIgB5sqzodc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`c.counts = make(map..)`
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiW9ZzmV9AGN5Q8S-6:-Ktihr_AglUj6xZntIPE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This would be expensive, particularly given it won't be used most of the time. Do it within the if.
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 36 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiUzml5YlG4rQInYmO:-Ktiht1NGNpxH7yRas8q:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L36)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't really need the schema. Just keep track of whether this predicate has a count index or not.
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 37 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiVA-vkinX23RzoYjc:-KtiiVmyn4bKlbp1Fnkq:b-pdpfzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/count_index.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

else if !c.cur.track { // if equal
  return
}

// Do what needs to be done.
</blockquote></details>

Restructured in a different way -- return for `!c.curr.track` already done.

---

*[cmd/bulkloader/loader.go, line 142 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiU8SMZCuuKPp5yrPY:-Ktij5B4NL4v8kAaXhBz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/loader.go#L142)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[cmd/bulkloader/write_flat.go, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiULXSuPTwV3QL1tc-:-KtijVbIOcrxlYSykEcy:bh0xwqn) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/write_flat.go#L119)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

var plistLen int
Add a comment. See if you can get rid of this var.
</blockquote></details>

Renamed to `plistLen`. When I mentioned possibility to  remove var, I was thinking of a different part of the code.

---

*[cmd/bulkloader/write_flat.go, line 144 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtiUcjwwAAHaf_P54ge:-KtijxGWmzaKU0Qtdj1z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/38099c4c0e77dcaacf0a07a7924aa5e8f3e94ad1/cmd/bulkloader/write_flat.go#L144)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Call it again after for loop here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431)*

**Comment by manishrjain** [comment]
:lgtm: Comments.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/bulkloader/count_index.go, line 19 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtjOo_ptOnCOfTPuIjv:-KtjOo_ptOnCOfTPuIjw:b2ni0pn) ([raw file](https://github.com/dgraph-io/dgraph/blob/26249b1cccce663fd11923130f3d93f9ef51275b/cmd/bulkloader/count_index.go#L19)):*
> ```Go
> 
> type countIndexer struct {
> 	curr   current
> ```

cur

---

*[cmd/bulkloader/count_index.go, line 22 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtjOhUF1kVa_nb18mli:-KtjOhUF1kVa_nb18mlj:b-sa7awz) ([raw file](https://github.com/dgraph-io/dgraph/blob/26249b1cccce663fd11923130f3d93f9ef51275b/cmd/bulkloader/count_index.go#L22)):*
> ```Go
> 	counts map[int][]uint64
> 	wg     sync.WaitGroup
> 	*state
> ```

Move this at the top.

---

*[cmd/bulkloader/count_index.go, line 47 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtjP8dEG-hELIw-l6m_:-KtjP8dEG-hELIw-l6ma:bpzxl5a) ([raw file](https://github.com/dgraph-io/dgraph/blob/26249b1cccce663fd11923130f3d93f9ef51275b/cmd/bulkloader/count_index.go#L47)):*
> ```Go
> 		c.curr.rev = key.IsReverse()
> 		c.curr.track = c.ss.getSchema(key.Attr).GetCount()
> 	}
> ```

`if c.cur.track { append }`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-:-KtjPiC9Bp9aV0BCNkh3:b9wrqbv)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[cmd/bulkloader/count_index.go, line 19 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtjOo_ptOnCOfTPuIjv:-KtjULw8S6V-5AkOqPhX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/26249b1cccce663fd11923130f3d93f9ef51275b/cmd/bulkloader/count_index.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

cur
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 22 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtjOhUF1kVa_nb18mli:-KtjUPXEhbR2dn45lOkq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/26249b1cccce663fd11923130f3d93f9ef51275b/cmd/bulkloader/count_index.go#L22)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this at the top.
</blockquote></details>

Done.

---

*[cmd/bulkloader/count_index.go, line 47 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431#-KtjP8dEG-hELIw-l6m_:-KtjVq1URSjlGv4iy9SS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/26249b1cccce663fd11923130f3d93f9ef51275b/cmd/bulkloader/count_index.go#L47)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

`if c.cur.track { append }`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1431)*

**Pull request merged**
