### PR TITLE
Modify/postinglist

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1105)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[posting/index.go, line 492 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6nTWtRT7fENYVG6KO:-Ko6nTWtRT7fENYVG6KP:bb06rif) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/index.go#L492)):*
> ```Go
> 	// Helper function - Add reverse entries for values in posting list
> 	addReversePostings := func(uid uint64, pl *protos.PostingList) error {
> 		postingsLen := len(pl.Uids)
> ```

Let's use iterator here as well.

---

*[posting/list.go, line 276 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6i2TxXUmyfoN2SuwV:-Ko6i2TxXUmyfoN2SuwW:bxpf1nn) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L276)):*
> ```Go
> 	pl := l.plist
> 	uidx := sort.Search(len(pl.Uids) /*Postings)*/, func(idx int) bool {
> 		//p := pl.Postings[idx]
> ```

remove comments.

---

*[posting/list.go, line 472 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6jrhywnm0phzDEyyF:-Ko6jrhywnm0phzDEyyG:b-bbgj57) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L472)):*
> ```Go
> 	l.AssertRLock()
> 	uidx, pidx, midx := 0, 0, 0
> 	pl := l.plist
> ```

uidPosting := &protos.Posting{}

Create an iterator instead to iterate over uids and postings together.

```
itr := NewIterator(uid uint64)
itr.Next()                                  // itr.Valid()
itr.Posting() *protos.Posting // => nil
```

---

*[posting/list.go, line 495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6lFxRnY67bNgNgIro:-Ko6lFxRnY67bNgNgIrp:bu28tap) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L495)):*
> ```Go
> 	for cont {
> 		if uidx < uidsLen && pidx < postingLen {
> 			pp = pl.Postings[pidx]
> ```

for pl.Uids[uidx] > pl.Postings[pidx].Uid {
  pidx++
  if pidx >= len(pl.Postings) break
}

if equals { .. }. This allows dealing with pidx only here, and below you only deal with uidx.

---

*[posting/list.go, line 497 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6kfbtCL7DOvT5nH14:-Ko6kfbtCL7DOvT5nH15:brrnrc5) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L497)):*
> ```Go
> 			pp = pl.Postings[pidx]
> 			if pl.Uids[uidx] == pp.Uid {
> 				pidx++
> ```

Can't increment here.

---

*[posting/list.go, line 499 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6j_6DoGTMiIA9rh5P:-Ko6j_6EDL9hvWFGfbml:bew2f5i) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L499)):*
> ```Go
> 				pidx++
> 			} else {
> 				pp = &protos.Posting{}
> ```

So, define `*protos.Posting` above, and reuse it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[posting/index.go, line 492 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6nTWtRT7fENYVG6KO:-KoA63IZt8uhE8qWNcqu:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/index.go#L492)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Let's use iterator here as well.
</blockquote></details>

Done.

---

*[posting/list.go, line 276 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6i2TxXUmyfoN2SuwV:-KoA645u7CknoB7ndCxm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L276)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove comments.
</blockquote></details>

Done.

---

*[posting/list.go, line 472 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6jrhywnm0phzDEyyF:-KoA65LK2wHMZA0RTadA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L472)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

uidPosting := &protos.Posting{}

Create an iterator instead to iterate over uids and postings together.

```
itr := NewIterator(uid uint64)
itr.Next()                                  // itr.Valid()
itr.Posting() *protos.Posting // => nil
```
</blockquote></details>

Done.

---

*[posting/list.go, line 495 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6lFxRnY67bNgNgIro:-KoA66PUbPD7DM2Tp8jU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L495)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

for pl.Uids[uidx] > pl.Postings[pidx].Uid {
  pidx++
  if pidx >= len(pl.Postings) break
}

if equals { .. }. This allows dealing with pidx only here, and below you only deal with uidx.
</blockquote></details>

Done.

---

*[posting/list.go, line 497 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6kfbtCL7DOvT5nH14:-KoA67aqGBm44UBmz_cV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L497)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can't increment here.
</blockquote></details>

Done.

---

*[posting/list.go, line 499 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-Ko6j_6DoGTMiIA9rh5P:-KoA68Dg6GarKB9NFxjN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ca4aa1c273d5ebf153ca87e8ef957b3de4e9537/posting/list.go#L499)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

So, define `*protos.Posting` above, and reuse it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[posting/index.go, line 491 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoACUTA_1fX3WuoAq-A:-KoACUTA_1fX3WuoAq-B:bis7dwv) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/index.go#L491)):*
> ```Go
> 	// Helper function - Add reverse entries for values in posting list
> 	addReversePostings := func(uid uint64, pl *protos.PostingList) error {
> 		pit := &Piterator{}
> ```

var pitr PIterator{List: pl}

`pitr.Valid()`

---

*[posting/list.go, line 101 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADGkxLNXbUsjGl9fl:-KoADGkxLNXbUsjGl9fm:b-j3k11b) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L101)):*
> ```Go
> }
> 
> type Piterator struct {
> ```

PIterator

var pitr PIterator
pitr.Init(pl, afterUid)

---

*[posting/list.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADRSj5IczeLu-1fHV:-KoADRSj5IczeLu-1fHW:bf20hns) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L111)):*
> ```Go
> }
> 
> func (it *Piterator) NewPlIterator(pl *protos.PostingList, afterUid uint64) *Piterator {
> ```

func Init(..)

---

*[posting/list.go, line 114 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoACmEscHCrtOzewAEX:-KoACmEscHCrtOzewAEY:bfjoq95) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L114)):*
> ```Go
> 	it.pl = pl
> 	it.uidPosting = &protos.Posting{}
> 	it.uidx, it.pidx = 0, 0
> ```

No need for this.

---

*[posting/list.go, line 328 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADgdIMIIxd8LgjRon:-KoADgdIMIIxd8LgjRoo:bv68poz) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L328)):*
> ```Go
> 	// Didn't find it in mutable layer. Now check the immutable layer.
> 	var uidFound, psame bool
> 	pit := &Piterator{}
> ```

var pitr PIterator

---

*[posting/list.go, line 331 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADpIFmbsrzcZ8SjbN:-KoADpIFmbsrzcZ8SjbO:b-l6mwxj) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L331)):*
> ```Go
> 	pit.NewPlIterator(l.plist, mpost.Uid-1)
> 	if pit.Valid() {
> 		//if uidx < len(pl.Uids) {
> ```

remove

---

*[posting/list.go, line 558 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoAG2qhWJ9gj9eBy6KA:-KoAG2qhWJ9gj9eBy6KB:b8lf26c) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L558)):*
> ```Go
> 	}
> }
> ```

Optimize the Uids function to avoid iterating over postings, if mutation layer is empty.

---

*[worker/backup.go, line 73 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoAGEuEkAMtjc52caFC:-KoAGEuEkAMtjc52caFD:b-nprbig) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/worker/backup.go#L73)):*
> ```Go
> func toRDF(buf *bytes.Buffer, item kv) {
> 	pl := item.list
> 	pit := &posting.Piterator{}
> ```

same thing as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105)*

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[posting/list.go, line 672 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoALO54d0c1zuXMxzS3:-KoALO54d0c1zuXMxzS4:bbnlkph) ([raw file](https://github.com/dgraph-io/dgraph/blob/0007f29215c0b249e74cc4f15f9f1d54ffee3754/posting/list.go#L672)):*
> ```Go
> 			return opt.AfterUID < pl.Uids[idx]
> 		})
> 		copy(res, pl.Uids[uidx:])
> ```

Move the res make just above this. Because you already know the length.

---

*[posting/list.go, line 673 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoALRbvkLEnaGJBPsE3:-KoALRbvkLEnaGJBPsE4:b-qh96pb) ([raw file](https://github.com/dgraph-io/dgraph/blob/0007f29215c0b249e74cc4f15f9f1d54ffee3754/posting/list.go#L673)):*
> ```Go
> 		})
> 		copy(res, pl.Uids[uidx:])
> 	} else {
> ```

Another res make here, using the length. But, not the external version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105)*

**Comment by ashwin95r** [comment]
Review status: 7 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[posting/index.go, line 491 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoACUTA_1fX3WuoAq-A:-KoAIxUyFoeF-qw9HMwy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/index.go#L491)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

var pitr PIterator{List: pl}

`pitr.Valid()`
</blockquote></details>

Done.

---

*[posting/list.go, line 101 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADGkxLNXbUsjGl9fl:-KoAIyUeyk0wKKygua6g:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L101)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

PIterator

var pitr PIterator
pitr.Init(pl, afterUid)
</blockquote></details>

Done.

---

*[posting/list.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADRSj5IczeLu-1fHV:-KoAIysdMYm14DQv1I32:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L111)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

func Init(..)
</blockquote></details>

Done.

---

*[posting/list.go, line 114 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoACmEscHCrtOzewAEX:-KoAMR-nb1-Bnz1-aA-_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L114)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this.
</blockquote></details>

Done.

---

*[posting/list.go, line 328 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADgdIMIIxd8LgjRon:-KoAJ29TwOGw-Yqmf_FQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L328)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

var pitr PIterator
</blockquote></details>

Done.

---

*[posting/list.go, line 331 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoADpIFmbsrzcZ8SjbN:-KoAJ5fsIYjG2SX1gjaH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L331)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[posting/list.go, line 558 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoAG2qhWJ9gj9eBy6KA:-KoAMPeMHGPID-NAWuA8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/posting/list.go#L558)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Optimize the Uids function to avoid iterating over postings, if mutation layer is empty.
</blockquote></details>

Done.

---

*[posting/list.go, line 672 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoALO54d0c1zuXMxzS3:-KoAMPydO2mkr-YVosRq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0007f29215c0b249e74cc4f15f9f1d54ffee3754/posting/list.go#L672)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move the res make just above this. Because you already know the length.
</blockquote></details>

Done.

---

*[posting/list.go, line 673 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoALRbvkLEnaGJBPsE3:-KoAMQMBVgDZAsCQQsNn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0007f29215c0b249e74cc4f15f9f1d54ffee3754/posting/list.go#L673)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Another res make here, using the length. But, not the external version.
</blockquote></details>

Done.

---

*[worker/backup.go, line 73 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoAGEuEkAMtjc52caFC:-KoAJ6p2NtZ2Yl-Z75fd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b524aaf7c5d5a20fe099a18c810284d8046089a0/worker/backup.go#L73)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same thing as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[posting/list.go, line 677 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoAOIBL8aZ0XcIIIU73:-KoAOIBL8aZ0XcIIIU74:baw0bdb) ([raw file](https://github.com/dgraph-io/dgraph/blob/4bf1b01637bfb0e5109e97a8d63913a8a76b3b63/posting/list.go#L677)):*
> ```Go
> 		res = make([]uint64, 0, l.length(opt.AfterUID))
> 		l.iterate(opt.AfterUID, func(p *protos.Posting) bool {
> 			if postingType(p) != x.ValueUid {
> ```

== x.ValueUid { res = append ..}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-:-KoAONLPzFxezkWjzj_U:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/list.go, line 677 at r4](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105#-KoAOIBL8aZ0XcIIIU73:-KoAS1OozO-tRMXqM69C:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4bf1b01637bfb0e5109e97a8d63913a8a76b3b63/posting/list.go#L677)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

== x.ValueUid { res = append ..}
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1105)*

**Comment by ashwin95r** [comment]
Merged to master.

**Pull request closed without merging**
