### PR TITLE
Support multiple tokenizers per predicate. Use exact match index for regex.

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/637)

### CODE REVIEW

**Comment by tzdybal** [comment]
I'm going to use this for full text search 👍

**Comment by manishrjain** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[schema/schema.go, line 92 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeClKM808hzQjJvzaD1:-KeClKM9agvtsWNrNjtD:b-aex6z2) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/schema/schema.go#L92)):*
> ```Go
> 
> // AddIndex adds the tokenizer for given predicate
> func (s *state) AddIndex(pred string, tokenizer string) {
> ```

Check for duplicates.

---

*[schema/testfiles/test_schema_index4, line 7 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeClDwdftFlFtMyo5Qa:-KeClDwe_mI2YKQXQbe1:b2nicts) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/schema/testfiles/test_schema_index4#L7)):*
> ```
>   address: string @index(term)
>   age: int
> 	id: id @index(exact, term)
> ```

tab

---

*[tok/tok.go, line 42 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCiDIWZnXJ-qi8Ripm:-KeCiDIWZnXJ-qi8Ripn:b8jc3pn) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L42)):*
> ```Go
> 	// Tokens return tokens for a given value.
> 	Tokens(sv types.Val) ([]string, error)
> ```

Identifier() [2]byte {
}

---

*[tok/tok.go, line 44 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCidPNzoZxW6UUCexB:-KeCidPNzoZxW6UUCexC:brh9w91) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L44)):*
> ```Go
> 
> 	// Prefix returns the prefix for this token type.
> 	Prefix(attr string) []byte
> ```

Maybe create a helper function outside.

---

*[tok/tok.go, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeChyT9aXX7vKiD1Yqw:-KeChyT9aXX7vKiD1Yqx:bmypiqo) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L53)):*
> ```Go
> 
> const (
> 	byteTerm  = 0x1
> ```

Don't store it here. Use x.IndexKey(..)

---

*[tok/tok.go, line 219 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCjc5jjjD1q5ATIo5M:-KeCjc5jjjD1q5ATIo5N:bw5dfl3) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L219)):*
> ```Go
> }
> 
> func encodeToken(tok string, typ byte) string {
> ```

return fmt.Sprintf("%b%s", typ, tok)

---

*[worker/task.go, line 345 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCjym5QthisGhkAvNE:-KeCjym5QthisGhkAvNF:b4mcg8g) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L345)):*
> ```Go
> 		it := pstore.NewIterator()
> 		defer it.Close()
> 		startKey := tok.ExactTokenizer{}.Prefix(q.Attr)
> ```

create a var of ExactTokenizer, and reuse it.

---

*[worker/task.go, line 346 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCkgoXLPEoP8zsUDZN:-KeCkgoYafR7IRuu56z_:b-va5vn2) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L346)):*
> ```Go
> 		defer it.Close()
> 		startKey := tok.ExactTokenizer{}.Prefix(q.Attr)
> 		it.Seek(startKey)
> ```

Try and do a range seek.

---

*[worker/task.go, line 347 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCkD2x7nN4WAmeb5g9:-KeCkD2yTPyF6W8O3lDW:b-eoi9ob) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L347)):*
> ```Go
> 		startKey := tok.ExactTokenizer{}.Prefix(q.Attr)
> 		it.Seek(startKey)
> 		key := it.Key().Data()
> ```

Inside the for loop.

---

*[worker/task.go, line 351 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCkL-cNQjCysqcfr8k:-KeCkL-cNQjCysqcfr8l:b91qf7b) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L351)):*
> ```Go
> 		for it.Valid() && pk.Attr == q.Attr && tok.IsExact(pk.Term) {
> 			x.AssertTrue(pk.IsIndex())
> 			x.AssertTrue(pk.Attr == q.Attr)
> ```

These are useless asserts. both of them.

---

*[worker/task.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCktNiGlkO48fVlHDH:-KeCktNjOKhYoTzSb8NK:b-lw8k4) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L363)):*
> ```Go
> 			}
> 			it.Next()
> 			key = it.Key().Data()
> ```

this is wrong. This should be done after checking validity.xx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637)*

**Comment by ashwin95r** [comment]
Sure, will push it in soon. After addressing the PR comments.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-:-KeCmLhiMsUpd5j4bEmm:b-2dqu3k)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[schema/schema.go, line 92 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeClKM808hzQjJvzaD1:-KeCmwvMc8Mvf4bud4HV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/schema/schema.go#L92)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check for duplicates.
</blockquote></details>

Done.

---

*[schema/testfiles/test_schema_index4, line 7 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeClDwdftFlFtMyo5Qa:-KeCp_SberVZGIrwP6AI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/schema/testfiles/test_schema_index4#L7)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done.

---

*[tok/tok.go, line 42 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCiDIWZnXJ-qi8Ripm:-KeCpaGd8wcUAw2TMw_W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L42)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Identifier() [2]byte {
}
</blockquote></details>

Done.

---

*[tok/tok.go, line 44 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCidPNzoZxW6UUCexB:-KeCw9NezfQRyjr0F4x3:b-ntm48h) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L44)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Maybe create a helper function outside.
</blockquote></details>

We might not need it. We already have x.Indexkeys()

---

*[tok/tok.go, line 53 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeChyT9aXX7vKiD1Yqw:-KeCpbgqEArfk15SUBta:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L53)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't store it here. Use x.IndexKey(..)
</blockquote></details>

Done.

---

*[tok/tok.go, line 219 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCjc5jjjD1q5ATIo5M:-KeCppmCaTWTQL0v2Adh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L219)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return fmt.Sprintf("%b%s", typ, tok)
</blockquote></details>

Done.

---

*[worker/task.go, line 345 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCjym5QthisGhkAvNE:-KeCprP4koKgj_5AjkrZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L345)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

create a var of ExactTokenizer, and reuse it.
</blockquote></details>

Done.

---

*[worker/task.go, line 346 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCkgoXLPEoP8zsUDZN:-KeCqnypxubYUj3O_v0_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L346)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Try and do a range seek.
</blockquote></details>

Done.

---

*[worker/task.go, line 347 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCkD2x7nN4WAmeb5g9:-KeCqpLyrxqMwbuT4gxe:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L347)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Inside the for loop.
</blockquote></details>

Done.

---

*[worker/task.go, line 351 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCkL-cNQjCysqcfr8k:-KeCqqjauSzI6D-soR6I:b-7gpp13) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L351)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

These are useless asserts. both of them.
</blockquote></details>

Changed the loop structure a bit.

---

*[worker/task.go, line 363 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCktNiGlkO48fVlHDH:-KeCqwDDBwmQVqmnjToP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/worker/task.go#L363)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

this is wrong. This should be done after checking validity.xx
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637)*

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 219 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCjc5jjjD1q5ATIo5M:-KeDI2eNQJvNDhIMCOwq:bxskwak) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L219)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

fmt.Sprintf("%q%s", typ, tok)

---

*[tok/tok.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDHZNczJi567FAr1VN:-KeDHZNdaLxu4zT7yKYJ:btfxpa5) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/tok/tok.go#L51)):*
> ```Go
> )
> 
> func IsExact(term string) bool {
> ```

Don't need this func.

---

*[tok/tok.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDHrB3aSVUlMoKlLKk:-KeDHrB3aSVUlMoKlLKl:b-nauq40) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/tok/tok.go#L136)):*
> ```Go
> 	return []string{encodeToken(encodeInt(int32(sv.Value.(float64))), 0x3)}, nil
> }
> func (t FloatTokenizer) Identifier() byte { return 0x3 }
> ```

Each tokenizer should have a unique id. Do a check at the beginning, iterate over all tokenizers and ensure that the id doesn't repeat.

---

*[worker/task.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDIFk58-aRioRODq4S:-KeDIFk58-aRioRODq4T:b-2y0ld6) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/worker/task.go#L40)):*
> ```Go
> 	emptyUIDList   task.List
> 	emptyResult    task.Result
> 	ExactTokenizer tok.ExactTokenizer
> ```

exactTok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637)*

**Comment by gacharya255** [comment]
Review status: 13 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[schema/parse.go, line 154 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDMxgqx7tBUSGVfkJ3:-KeDMxgqx7tBUSGVfkJ4:b-2qninr) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/schema/parse.go#L154)):*
> ```Go
> func processIndexDirective(it *lex.ItemIterator, predicate string, typ types.TypeID) error {
> 	if !it.Next() {
> 		// Nothing to read.
> ```

Should there be a "State().AddIndex(predicate, tok.Default(typ).Name())" here as well?

---

*[tok/tok.go, line 179 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDKP2L0hHWr4S5zS6D:-KeDKP2L0hHWr4S5zS6E:bnjkq8t) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/tok/tok.go#L179)):*
> ```Go
> 				break
> 			}
> 			tokens = append(tokens, encodeToken(string(s), 0x1))
> ```

Try not to hardcode these constants?  Maybe encodeToken(..., t.Identifier()). I expect that to be inlined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637)*

**Comment by ashwin95r** [comment]
Review status: 13 of 16 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[schema/parse.go, line 154 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDMxgqx7tBUSGVfkJ3:-KeDOikG7EusWufuK_yX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/schema/parse.go#L154)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Should there be a "State().AddIndex(predicate, tok.Default(typ).Name())" here as well?
</blockquote></details>

Done.

---

*[tok/tok.go, line 219 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeCjc5jjjD1q5ATIo5M:-KeDO7WhhW7KbpC1URQM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/678e5a22a64853f62d98a01d3882aaa5f72b1ab7/tok/tok.go#L219)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

fmt.Sprintf("%q%s", typ, tok)
</blockquote></details>

Done.

---

*[tok/tok.go, line 51 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDHZNczJi567FAr1VN:-KeDJJPShrmRq4XwfRtY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/tok/tok.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't need this func.
</blockquote></details>

Done.

---

*[tok/tok.go, line 136 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDHrB3aSVUlMoKlLKk:-KeDLFvYmVlVGMLaSXqC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/tok/tok.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Each tokenizer should have a unique id. Do a check at the beginning, iterate over all tokenizers and ensure that the id doesn't repeat.
</blockquote></details>

Done.

---

*[tok/tok.go, line 179 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDKP2L0hHWr4S5zS6D:-KeDOHfu5G1QTMAsc45P:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/tok/tok.go#L179)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Try not to hardcode these constants?  Maybe encodeToken(..., t.Identifier()). I expect that to be inlined.
</blockquote></details>

Done.

---

*[worker/task.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDIFk58-aRioRODq4S:-KeDJTaEaPYqOWARBnoH:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f38e273a7dad82c5c5941ed542b57c13266b9f3e/worker/task.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

exactTok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637)*

**Comment by gacharya255** [comment]
:lgtm:

---

Review status: 12 of 16 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 42 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDT0XrC3Kg9F2Ew69g:-KeDT0XrC3Kg9F2Ew69h:brerv5r) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f6a8c6c1322b87ba4277490561493e38846b908/tok/tok.go#L42)):*
> ```Go
> 	Tokens(sv types.Val) ([]string, error)
> 
> 	// Prefix returns the prefix byte for this token type.
> ```

Identifier returns ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-:-KeDT976HWcDIEhhixXf:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 12 of 16 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 42 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-KeDT0XrC3Kg9F2Ew69g:-KeGO6MHgjL6iUWSfIK0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f6a8c6c1322b87ba4277490561493e38846b908/tok/tok.go#L42)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Identifier returns ...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/637#-:-KeGo0Kf7k6XMlR7hFXw:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged. @tzdybal you can use this now!

**Comment by RXminuS** [comment]
Does this work correctly with root level func?

**Comment by ashwin95r** [comment]
This is an indexing change. If you're referring to `eq` function at root, that still has to be fixed @RXminuS.

**Comment by RXminuS** [comment]
so I'm not able to use something like this yet?
```graphql
query{
   me(func:regexp("name", "[0-9]")){
      name
   }
}
```

**Comment by ashwin95r** [comment]
Lets continue here #661. Can you please share your schema file and the mutations there

**Pull request closed without merging**
