### PR TITLE
Doc - adds the JS HTTP Client and links to repos for the supported versions

### LINKED ISSUE #4650: dgraph-js-http not cited in the doc
Doc page: https://docs.dgraph.io/clients/
Repo page: https://github.com/dgraph-io/dgraph-js-http

Please could we add a quick section / link?

Another possible improvement:

- dgraph-js-http is cited in the dgraph-js page (https://github.com/dgraph-io/dgraph-js)
- should we also cite dgraph-js in the dgraph-js-http page (https://github.com/dgraph-io/dgraph-js-http)?

FYI @prashant-shahi 

Thanks,

### PR DESCRIPTION
**Pull request by prashant-shahi**
Fixes #4650 

Signed-off-by: Prashant Shahi <prashant@dgraph.io>

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4735)

 
 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-aea6681984-43073.surge.sh)

### CODE REVIEW

**Comment by sleto-it** [comment]
Hi @prashant-shahi , thanks for opening this

I am a bit concerned about the fact that we write "fully supports Dgraph v1.0.x" as 1.0 is old. I believe (and I understand this is another issue) we can do this way:

- we add a section "Supported Version" in each Readme file of the driver repos, where we create a table similar to what we have here https://github.com/dgraph-io/dgraph-js#quickstart
- then we add a link to those tables and remove those "fully supports Dgraph v1.0.x"

This will allow us to change the supportability info in the repos, and not need to touch the this doc every time. WDYT?

We can do it in another PR if needed

Hope this helps,

**Comment by sleto-it** [comment]
PRs for the driver repos (partial):
- https://github.com/dgraph-io/dgraph-js/pull/106
- https://github.com/dgraph-io/dgo/pull/116

**Comment by prashant-shahi** [comment]
Hello @sleto-it , your raised PRs looks good.

The client versions 2.X.Y of `dgraph-js` and `dgo` should work well with Dgraph version >= 1.1.X

**Comment by sleto-it** [comment]
@martinmr thanks for the review - yes, and we can do the changes in the PR where we cite dot net as official driver (https://github.com/dgraph-io/dgraph/pull/4568) - there will be some conflicts there when we merge this, but can be resolved

thanks,

**Comment by prashant-shahi** [comment]
@sleto-it Thanks for all of the work on creating multiple PRs in each of the clients.

Just have a query on the PR raised for the C# client.
I believed that we were planning on officially maintaining the [repo in Dgraph](https://github.com/dgraph-io/Dgraph-dotnet) instead of the [main repo present in MichaelJCompton](https://github.com/MichaelJCompton/Dgraph-dotnet).

Just wanted to know if it was intentional to create PR in the latter.

**Comment by sleto-it** [comment]
Thanks - yeah, opened the PR in the wrong repo by mistake, but the changes are in a branch in the correct repo - https://github.com/dgraph-io/Dgraph-dotnet/tree/santo/supported-versions

We will need to open a new PR in the correct repo

**Comment by sleto-it** [comment]
@prashant-shahi the dot-net PR has now been opened in the correct repo and merged (https://github.com/dgraph-io/Dgraph-dotnet/pull/2)

**Comment by sleto-it** [comment]
**Status:** all related PRs merged but the java one, which needs some more internal discussion / work

**Comment by sleto-it** [comment]
@prashant-shahi I have talked with Aman today. He has been very busy so far. We agreed the following:
- let's give him a few more days to try to finish and merge https://github.com/dgraph-io/dgraph4j/pull/128
- If that PR is not merged by this Thursday, we should unblock this PR (4735) and merge it. Then when the java PR is merged we can create a new PR in the dgraph repo to link the java section in the doc

To unblock this PR we can just remove the following sentence from the dgraph4j section: "More details on the supported versions can be found at [this link](https://github.com/dgraph-io/dgraph4j#supported-versions)."

Thanks,

**Comment by sleto-it** [comment]
can be merged now

**Pull request merged**
