### PR TITLE
Filter count

### PR DESCRIPTION
**Pull request by jchiu0**
Support count of filtered results.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/336)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/336#-:-KXP7n4MaMgougsO_pc3:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[query/query.go, line 625 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/336#-KXPQUXpUG1NDSx5JLyZ:-KXPQUXpUG1NDSx5JLy_:b-5x2njm) ([raw file](https://github.com/dgraph-io/dgraph/blob/4fc4b0225be7655c706657a0ce50e3db913ce492/query/query.go#L625)):*
> ```Go
> 
> 	if sg.Params.DoCount {
> 		x.AssertTrue(len(sg.Filters) > 0)
> ```

Couldn't we make this part of the if len(sg.Filters) > 0 block above? We probably don't need to do ordering and pagination first, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/336)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/336#-:-KXPUeFxa0RHIsNQ_4ag:bnfp4nl)*

**Comment by manishrjain** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 637 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/336#-KXPVCxrVc_mhHaP9d5J:-KXPVCxrVc_mhHaP9d5K:b-i02tm8) ([raw file](https://github.com/dgraph-io/dgraph/blob/11a15ead70a7e2effcd4523becf92d44f2dfdfc2/query/query.go#L637)):*
> ```Go
> 			algo.IntersectWith(ul, sg.DestUIDs)
> 			sg.counts[i] = uint32(len(ul.Uids))
> 		}
> ```

Don't you need to return here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/336)*

**Comment by jchiu0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 625 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/336#-KXPQUXpUG1NDSx5JLyZ:-KXPa0L3GtGegMIh9L3K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4fc4b0225be7655c706657a0ce50e3db913ce492/query/query.go#L625)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Couldn't we make this part of the if len(sg.Filters) > 0 block above? We probably don't need to do ordering and pagination first, right?
</details>
Done.

---

*[query/query.go, line 637 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/336#-KXPVCxrVc_mhHaP9d5J:-KXPa0uP474es7NddIS8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/11a15ead70a7e2effcd4523becf92d44f2dfdfc2/query/query.go#L637)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Don't you need to return here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/336)*

**Pull request closed without merging**
