### PR TITLE
Fix/proto3

### PR DESCRIPTION
**Pull request by jchiu0**
Use proto for DirectedEdge, Mutations.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/332)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm: Nice cleanup!

---

Review status: 0 of 21 files reviewed at latest revision, 18 unresolved discussions.

---

*[posting/list_test.go, line 875 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEGTykKwn9tQXywyXJ:-KXEGTylh6pLScCZ-vvi:b-l932ib) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/list_test.go#L875)):*
> ```Go
> 	b.ResetTimer()
> 
> 	//ts := x.CurrentTime()
> ```

maybe remove.

---

*[x/x.go, line 120 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEFOBaxJRm6-RIwi26:-KXEFOBb64z06KvauC71:bcgltxk) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/x/x.go#L120)):*
> ```Go
> // CurrentTime returns the current time encoded.
> func CurrentTime() []byte {
> 	data, err := time.Now().MarshalBinary()
> ```

Would it make sense to store `time.Now().UTC()` so that its the same time on different machines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-:-KXEI17LtW78gia08hfu:b-d43tfz)*

**Comment by manishrjain** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 27 unresolved discussions.

---

*[posting/index.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEU2UEn64oeev_KPnN:-KXEU2UEn64oeev_KPnO:b-1vnjff) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/index.go#L122)):*
> ```Go
> 	}
> 	edge := &task.DirectedEdge{
> 		Timestamp: x.CurrentTime(),
> ```

Actually, we don't need a timestamp here. You can just skip this field. We don't use it in any way.

---

*[posting/list.go, line 175 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEUEVf6dg8WnbbqSnF:-KXEUEVf6dg8WnbbqSnG:bz2ud70) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/list.go#L175)):*
> ```Go
> 
> 	var timestamp time.Time
> 	x.Check(timestamp.UnmarshalBinary(t.Timestamp))
> ```

Yup, don't need it.

---

*[posting/list_test.go, line 343 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEV1-QRaGX6kFh7en2:-KXEV1-Ry8xtYAUQHa66:bmjmj9a) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/list_test.go#L343)):*
> ```Go
> 		Value:     []byte("othercars"),
> 		Source:    "jchiu",
> 		Timestamp: x.CurrentTime(),
> ```

Unnecessary indirection: Why is x.CurrentTime better than time.Now?

---

*[task/task.proto, line 89 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVSzJWtKy3xZfSpmJ:-KXEVSzJWtKy3xZfSpmK:bluaic2) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L89)):*
> ```protobuf
> 	uint32 valueType = 4;  // The type of the value
> 	fixed64 valueId = 5;   // Object or destination node / UID.
> 	string source = 6;
> ```

call it label.

---

*[task/task.proto, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVV0Y7C1EoASdk76m:-KXEVV0Y7C1EoASdk76n:b-et26je) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L90)):*
> ```protobuf
> 	fixed64 valueId = 5;   // Object or destination node / UID.
> 	string source = 6;
> 	bytes timestamp = 7;
> ```

Remove for now.

---

*[task/task.proto, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVcxpkgcURl5bgPYs:-KXEVcxpkgcURl5bgPYt:bhy50qt) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L94)):*
> ```protobuf
> 
> message Mutations {
> 	uint32 groupId = 1;
> ```

uint32 group_id = 1;  // I think proto uses snakecase.

---

*[task/task.proto, line 100 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVimV5pljGpshSkOY:-KXEVimV5pljGpshSkOZ:bbg3p3l) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L100)):*
> ```protobuf
> 
> message Proposal {
> 	uint32 proposalId = 1;
> ```

Call it `id`.

---

*[worker/assign.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEW8RSCflS_FKZsRSI:-KXEW8RSCflS_FKZsRSJ:b-n0xfr2) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/worker/assign.go#L65)):*
> ```Go
> 			Attr:      "_uid_",
> 			Value:     []byte("_"), // not txid
> 			Source:    "_XIDorUSER_",
> ```

If we're saving bytes in value, it would make sense to save bytes in Source (/label) as well.

---

*[worker/draft.go, line 139 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEXA3LS_fUmLmXbT4w:-KXEXA3LS_fUmLmXbT4x:b3e666s) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/worker/draft.go#L139)):*
> ```Go
> 
> func (n *node) ProposeAndWait(ctx context.Context, proposal *task.Proposal) error {
> 	proposal.ProposalId = rand.Uint32()
> ```

Call it just Id. So, it reads, `proposal.Id`

---

*[x/x.go, line 120 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEFOBaxJRm6-RIwi26:-KXEYF5Axjz83R8thLLC:b-d4wdfw) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/x/x.go#L120)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Would it make sense to store `time.Now().UTC()` so that its the same time on different machines?
</details>
Actually, we don't need this, because the field itself isn't required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/332)*

**Comment by jchiu0** [comment]
Review status: 4 of 21 files reviewed at latest revision, 27 unresolved discussions, some commit checks failed.

---

*[posting/index.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEU2UEn64oeev_KPnN:-KXGiuzmqk5TtbrZVx4R:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/index.go#L122)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Actually, we don't need a timestamp here. You can just skip this field. We don't use it in any way.
</details>
Done.

---

*[posting/list.go, line 175 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEUEVf6dg8WnbbqSnF:-KXGjc5RSPJrakRAAoGw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/list.go#L175)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Yup, don't need it.
</details>
Done.

---

*[posting/list_test.go, line 343 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEV1-QRaGX6kFh7en2:-KXGjdZ8eQuV0hdVQDAe:b-9kkeyn) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/list_test.go#L343)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Unnecessary indirection: Why is x.CurrentTime better than time.Now?
</details>
Previously it is because Timestamp appears at a LOT of places and I need to call MarshalBinary and check errors.

This is no longer applicable.

---

*[posting/list_test.go, line 875 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEGTykKwn9tQXywyXJ:-KXGjsDgh3jg4aDQlGKP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/posting/list_test.go#L875)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> maybe remove.
</details>
Done.

---

*[task/task.proto, line 89 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVSzJWtKy3xZfSpmJ:-KXGjuBBZK7YMFvXOk66:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L89)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> call it label.
</details>
Done.

---

*[task/task.proto, line 90 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVV0Y7C1EoASdk76m:-KXGjvA2E_Y89mnnhZiE:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L90)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Remove for now.
</details>
Done.

---

*[task/task.proto, line 94 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVcxpkgcURl5bgPYs:-KXGjw0GAAhZ9HQWDXU1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L94)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> uint32 group_id = 1;  // I think proto uses snakecase.
</details>
Done.

---

*[task/task.proto, line 100 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEVimV5pljGpshSkOY:-KXGjwOZ2uh-Q4qYWTzt:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/task/task.proto#L100)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Call it `id`.
</details>
Done.

---

*[worker/assign.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEW8RSCflS_FKZsRSI:-KXGk1BDKagdFlwsy6DS:b-toio4b) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/worker/assign.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> If we're saving bytes in value, it would make sense to save bytes in Source (/label) as well.
</details>
I don't like to introduce bytes when a string would do, and it has always been strings here. Value could be very long but I would expect the label to be short.

---

*[worker/draft.go, line 139 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEXA3LS_fUmLmXbT4w:-KXGkI5PGKCxU05bnHdO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/worker/draft.go#L139)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Call it just Id. So, it reads, `proposal.Id`
</details>
Done.

---

*[x/x.go, line 120 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEFOBaxJRm6-RIwi26:-KXGkL8GKSm-pHftyCmT:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/x/x.go#L120)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Actually, we don't need this, because the field itself isn't required.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/332)*

**Comment by manishrjain** [comment]
:lgtm: one small comment. Have a look and then feel free to submit.

---

Review status: 4 of 21 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[task/task.proto, line 68 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXIIRoZWWxm8flsjbq7:-KXIIRoZWWxm8flsjbq8:bkqg0du) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a25c33f7c3316893f5d7cbfe5b46930a2b12cc/task/task.proto#L68)):*
> ```protobuf
> 	string addr = 3;
> 	bool leader = 4;
> 	bool amDead = 5;
> ```

am_dead

---

*[worker/assign.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEW8RSCflS_FKZsRSI:-KXIIfk-fthtmYATeu_z:bsli8y4) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/worker/assign.go#L65)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> I don't like to introduce bytes when a string would do, and it has always been strings here. Value could be very long but I would expect the label to be short.
</details>
I didn't mean switch the type to bytes. I meant, the size of label is 11 bytes. We could decrease that to one, just like we did for Value (it used to be longer before).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-:-KXIJ57jjaKyuf5zMDvt:b-24cudw)*

**Comment by jchiu0** [comment]
Thanks for the reviews!

---

Review status: 4 of 21 files reviewed at latest revision, 29 unresolved discussions.

---

*[task/task.proto, line 68 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXIIRoZWWxm8flsjbq7:-KXIUzgbOQnimtFdhayS:b-x0fphz) ([raw file](https://github.com/dgraph-io/dgraph/blob/39a25c33f7c3316893f5d7cbfe5b46930a2b12cc/task/task.proto#L68)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> am_dead
</details>
Missed this one.. thanks.

---

*[worker/assign.go, line 65 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-KXEW8RSCflS_FKZsRSI:-KXIVWL75UnSrX65Czpe:b4bwl0n) ([raw file](https://github.com/dgraph-io/dgraph/blob/87325e96cf6bf8d4ecd462093c6e3921eeaf2e00/worker/assign.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I didn't mean switch the type to bytes. I meant, the size of label is 11 bytes. We could decrease that to one, just like we did for Value (it used to be longer before).
</details>
Ah, I see. I changed the label to "A" for assigner. Saving bytes here is great.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/332#-:-KXIWEldGnbbayG8x9CC:b-hlc8bm)*

**Pull request closed without merging**
