### PR TITLE
Allow defining and using variable in same query block.

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/523)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9gN7YuflaTe17y6yp:-Kb9gN7Z21MkOndvfPt3:b8opp41) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L114)):*
> VarL
Do not see VarL being used in PR.

---

*[query/query.go, line 594 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iEWOQgAsFseneCDP:-Kb9iEWPCOALSikVCRRI:b-3eyw3d) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L594)):*
> Defines
We can break out of inner and outer loops when noCascade is true.

---

*[query/query.go, line 627 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iPOXlB5tleL1FpWp:-Kb9iPOYb2SLy3o6p7kT:by4fc2h) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L627)):*
> ```Go
> 
> 	if noCascade {
> 		goto L
> ```

can we have a name for L ?

---

*[query/query.go, line 664 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9l36QhdV4WP2NgYiJ:-Kb9l36QhdV4WP2NgYiK:b-myet45) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L664)):*
> FillVariable
Is this public fn ? Can not find its usage outside of file..

---

*[query/query.go, line 683 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9lRKCOJ7be0LKAohB:-Kb9lRKDH6cJ8vQ32p71:baewe06) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L683)):*
> ```Go
> 	var err error
> 	if len(sg.Params.NeedsVar) != 0 && len(sg.SrcFunc) == 0 {
> 		// Do nothing as the list has already been populated.
> ```

we should remove this comment .. ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9gN7YuflaTe17y6yp:-KbCfSGdVKXKTEuyxhcn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L114)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

> VarL
Do not see VarL being used in PR.

</blockquote></details>

Done.

---

*[query/query.go, line 594 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iEWOQgAsFseneCDP:-KbCfj5WYhklKnuQBIJd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L594)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

> Defines
We can break out of inner and outer loops when noCascade is true.
</blockquote></details>

Done.

---

*[query/query.go, line 627 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iPOXlB5tleL1FpWp:-KbCh9DpLTS0ApDm7Ysf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L627)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

can we have a name for L ?
</blockquote></details>

Done.

---

*[query/query.go, line 664 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9l36QhdV4WP2NgYiJ:-KbChLPQ2JV-swaZzHPs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L664)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

> FillVariable
Is this public fn ? Can not find its usage outside of file..
</blockquote></details>

Done.

---

*[query/query.go, line 683 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9lRKCOJ7be0LKAohB:-KbChLzR4kwDKKgS-QHw:b-pm8jwb) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L683)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

we should remove this comment .. ?
</blockquote></details>

Actually, we still don't have to do this. Could add it later if required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523)*

**Comment by ashishnegi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/query.go, line 627 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iPOXlB5tleL1FpWp:-KbDHuK7fQW3NJoUb0bW:b-gdgcum) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L627)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why the next steps of `removing from uid matrix and destuids` not required even if one of the QueryVars defines is same as needs (i.e. noCascade is true) ?

---

*[query/query_test.go, line 392 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDIehYK--pLhuam_Dx:-KbDIehYK--pLhuam_Dy:bp95tis) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query_test.go#L392)):*
> ```Go
> }
> 
> func TestUseVarsFilterVarReuse2(t *testing.T) {
> ```

Can we have a test with combination of `nested var` and `var outside of main query` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523)*

**Comment by manishrjain** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[query/query.go, line 594 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iEWOQgAsFseneCDP:-KbDJv6MQL5Figls8rAS:bre9n38) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L594)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can move it out into a function.

---

*[query/query.go, line 664 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9l36QhdV4WP2NgYiJ:-KbDItV-Uwy7XPSEgaZe:blef0fz) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L664)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

fillVar

---

*[query/query.go, line 611 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDIMSP-MAwwH-lKixZ:-KbDIMSP-MAwwH-lKix_:b-x3yvi2) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L611)):*
> ```Go
> 
> // TODO(Ashwin): Benchmark this function. Map implementation might be slow.
> func populateVarMap(sg *SubGraph, noCascade bool, doneVars map[string]*task.List) {
> ```

Move the bool to the end. I remember 

---

*[query/query.go, line 651 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDIgEj8whX_Tx2_-Dg:-KbDIgEj8whX_Tx2_-Dh:b-5chbrb) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L651)):*
> ```Go
> }
> 
> func fillUpVariables(sg *SubGraph, doneVars map[string]*task.List) {
> ```

This could be a func of sg. Also, call it recursiveFillVars / fillVarsForAllNodes

---

*[query/query.go, line 662 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDJCgZFzbUcK2Z3JRK:-KbDJCgZFzbUcK2Z3JRL:b-s37la2) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L662)):*
> ```Go
> 
> func (sg *SubGraph) fillVariable(mp map[string]*task.List) {
> 	lists := make([]*task.List, 0)
> ```

lists := make([]*task.List, 0, 10)

---

*[query/query.go, line 672 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDJTlEcwpGEfM8TFXm:-KbDJTlEcwpGEfM8TFXn:bbph7ui) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L672)):*
> ```Go
> 	}
> 	sg.DestUIDs = algo.MergeSorted(lists)
> ```

Empty vertical space.

---

*[query/query_test.go, line 392 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDIehYK--pLhuam_Dx:-KbDJfLnJ3lykm1ApMcl:bjb8gzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query_test.go#L392)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

Can we have a test with combination of `nested var` and `var outside of main query` ?
</blockquote></details>

Yeah, seems like a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[query/query.go, line 594 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iEWOQgAsFseneCDP:-KbDP04zpeLMh4_1vF3x:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L594)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can move it out into a function.
</blockquote></details>

Done.

---

*[query/query.go, line 627 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9iPOXlB5tleL1FpWp:-KbDPt1KvhVNy88iE5cb:b-f1exq8) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L627)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

why the next steps of `removing from uid matrix and destuids` not required even if one of the QueryVars defines is same as needs (i.e. noCascade is true) ?
</blockquote></details>

As of now, we want to keep the design simple by not cascading if a given block defines and uses the same Var as it would lead to a feedback loop which would recursively affect the levels that define and use the Var. So we just avoid cascading for the entire block.

---

*[query/query.go, line 664 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-Kb9l36QhdV4WP2NgYiJ:-KbDKvyIIbw4PvGexAv9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0429ee3d250d92cb259c4ba687b70a6c59ccac1d/query/query.go#L664)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

fillVar
</blockquote></details>

Done.

---

*[query/query.go, line 611 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDIMSP-MAwwH-lKixZ:-KbDPn5EQeYumfsSzIV4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L611)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move the bool to the end. I remember 
</blockquote></details>

Done.

---

*[query/query.go, line 651 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDIgEj8whX_Tx2_-Dg:-KbDQOsDQJgienxaEz4K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L651)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This could be a func of sg. Also, call it recursiveFillVars / fillVarsForAllNodes
</blockquote></details>

Done.

---

*[query/query.go, line 662 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDJCgZFzbUcK2Z3JRK:-KbDL25IzkS3IEKw0qZR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L662)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

lists := make([]*task.List, 0, 10)
</blockquote></details>

Done.

---

*[query/query.go, line 672 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDJTlEcwpGEfM8TFXm:-KbDL8UbLvXKGQD5Q9A-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query.go#L672)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Empty vertical space.
</blockquote></details>

Done.

---

*[query/query_test.go, line 392 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDIehYK--pLhuam_Dx:-KbDNSnIx2xW6K5MMf6X:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/078c7b3135dd7e1f32ecdb2df772b455f892f285/query/query_test.go#L392)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Yeah, seems like a good idea.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523)*

**Comment by ashishnegi** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-:-KbDT2j180RkgeAaNYt6:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[query/query.go, line 525 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSTVBFVnN5Go37q4Q:-KbDSTVBFVnN5Go37q4R:bsllaas) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L525)):*
> ```Go
> 	numQueriesDone := 0
> 
> 	canExecute := func(idx int) bool {
> ```

Comment about what this function is doing.

---

*[query/query.go, line 527 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSR0GHUga7_yd2AVA:-KbDSR0GHUga7_yd2AVB:b-97vfaj) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L527)):*
> ```Go
> 	canExecute := func(idx int) bool {
> 		for _, v := range res.QueryVars[idx].Needs {
> 			var selfDep bool
> ```

Add a comment about what you're doing here.

---

*[query/query.go, line 600 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSXxivOoVtbXNyi2l:-KbDSXxivOoVtbXNyi2m:b7vyxbs) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L600)):*
> ```Go
> 	return sgl, nil
> }
> func shouldCascade(res gql.Result, idx int) bool {
> ```

Comment here.

---

*[query/query.go, line 620 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSxCi4uci6STReG4K:-KbDSxCjEi0FjeV17tEF:b-g83npf) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L620)):*
> ```Go
> 			continue
> 		}
> 		for i := 0; i < len(child.uidMatrix); i++ {
> ```

Comment about what this following logic is doing.

---

*[query/query.go, line 801 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDT7y_YOC72XEHamCw:-KbDT7y_YOC72XEHamCx:b-24l1lu) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L801)):*
> ```Go
> 		}
> 	}
> ```

Add a comment here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-:-KbDTGbmtKGSXeib8arF:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[query/query.go, line 525 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSTVBFVnN5Go37q4Q:-KbDXQQq8FkkVkG6_WWy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L525)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Comment about what this function is doing.
</blockquote></details>

Done.

---

*[query/query.go, line 527 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSR0GHUga7_yd2AVA:-KbDXQmk7EvMK3jL1KMO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L527)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment about what you're doing here.
</blockquote></details>

Done.

---

*[query/query.go, line 600 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSXxivOoVtbXNyi2l:-KbDY69SZzNaOYfRC1Vx:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L600)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Comment here.
</blockquote></details>

Done.

---

*[query/query.go, line 620 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDSxCi4uci6STReG4K:-KbDY79afcDRqkE1d5qA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L620)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Comment about what this following logic is doing.
</blockquote></details>

Done.

---

*[query/query.go, line 801 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/523#-KbDT7y_YOC72XEHamCw:-KbDYkctJDFC94tRq4Wi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/482d708fd8404ed777b323d803b336e04c577e90/query/query.go#L801)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment here as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/523)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
