### PR TITLE
Minor improvements in the client

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Add a small helper function to delete edges.

Other small changes

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1794)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[dgraph/cmd/live/run.go, line 70 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-O0pI-aE1g_4ZWkE:-KzM-O0pI-aE1g_4ZWkF:bcq0qt5) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/dgraph/cmd/live/run.go#L70)):*
> ```Go
> 	flag.StringVarP(&opt.schemaFile, "schema", "s", "", "Location of schema file")
> 	flag.StringVarP(&opt.dgraph, "dgraph", "d", "127.0.0.1:9080", "Dgraph gRPC server address")
> 	flag.StringVarP(&opt.zero, "zero", "z", "127.0.0.1:5080", "Dgraphzero gRPC server address")
> ```

Revert this.

---

*[dgraph/cmd/live/run.go, line 217 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-TWAd4pUNvshxzqX:-KzM-TWAd4pUNvshxzqY:b-fpobz8) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/dgraph/cmd/live/run.go#L217)):*
> ```Go
> 			grpc.WithInsecure(),
> 			grpc.WithBlock(),
> 			grpc.WithTimeout(5*time.Second))
> ```

10 seconds?

---

*[query/mutation.go, line 145 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-pPRTdJ28zOAzubP:-KzM-pPRTdJ28zOAzubQ:b-7s9jbc) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/query/mutation.go#L145)):*
> ```Go
> 			}
> 			if uid > maxLeaseId {
> 				return newUids, fmt.Errorf("Uid: [%d] cannot be greater than lease: [%d]", uid, maxLeaseId)
> ```

chars

---

*[query/mutation.go, line 157 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-qU9DiG8wuyo91BD:-KzM-qU9DiG8wuyo91BE:b-s8vgsq) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/query/mutation.go#L157)):*
> ```Go
> 			}
> 			if uid > maxLeaseId {
> 				return newUids, fmt.Errorf("Uid: [%d] cannot be greater than lease: [%d]", uid, maxLeaseId)
> ```

chars.

---

*[types/conversion.go, line 134 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-tMOy-_CJkfCTBZ4:-KzM-tMOy-_CJkfCTBZ5:b-288efv) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/types/conversion.go#L134)):*
> ```Go
> 				text := bytes.Replace([]byte(vc), []byte("'"), []byte("\""), -1)
> 				if err := geojson.Unmarshal(text, &g); err != nil {
> 					return to, errors.Wrapf(err, "Error while unmarshalling: [%s] as geojson",
> ```

errors.Wrapf move to next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-:-KzM-vMSphRz9K1rGd2j:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 6 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[dgraph/cmd/live/run.go, line 70 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-O0pI-aE1g_4ZWkE:-KzM2fcgShnSWcvTwPlc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/dgraph/cmd/live/run.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Revert this.
</blockquote></details>

Done.

---

*[dgraph/cmd/live/run.go, line 217 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-TWAd4pUNvshxzqX:-KzM2gGP9u46gntNITZm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/dgraph/cmd/live/run.go#L217)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

10 seconds?
</blockquote></details>

Done.

---

*[query/mutation.go, line 145 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-pPRTdJ28zOAzubP:-KzM2kGpyOfo0K6-J0Vi:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/query/mutation.go#L145)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

chars
</blockquote></details>

Done.

---

*[query/mutation.go, line 157 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-qU9DiG8wuyo91BD:-KzM2kjsY8QESaV5krfa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/query/mutation.go#L157)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

chars.
</blockquote></details>

Done.

---

*[types/conversion.go, line 134 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzM-tMOy-_CJkfCTBZ4:-KzM2mogKZNqh1dW6pfa:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/96275b78307543175da3589a10e0ac0be92926f7/types/conversion.go#L134)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

errors.Wrapf move to next line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 6 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[client/client.go, line 82 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-KzMD_isHyZawkhyBeaa:-KzMD_isHyZawkhyBeab:b-jqfdbg) ([raw file](https://github.com/dgraph-io/dgraph/blob/99362ea417d03fc7a07b63c11d9f27dc1dd0c706/client/client.go#L82)):*
> ```Go
> }
> 
> func DeleteEdges(mu *protos.Mutation, uid string, preds ...string) {
> ```

Don't forget a doc comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-:-KzMEiQvk5mxlvwiTjjI:bnfp4nl)*

**Comment by peterstace** [comment]
Also, remember to add a change to the changelog

---

Review status: 6 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794#-:-KzMEngt4fBj6LDo1dl9:b-wd3zkw)*

**Comment by peterstace** [comment]
Reviewed 6 of 12 files at r1, 6 of 7 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1794)*

**Comment by pawanrawal** [comment]
In master as of 209a8dc7d06ad649c32eb2ff54eec82232ae9a5e

**Pull request closed without merging**
