### PR TITLE
don't remove group on zero members

### PR DESCRIPTION
**Pull request by balajijinnah**
#3326 
Signed-off-by: பாலாஜி <rbalajis25@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3443)

### CODE REVIEW

**Comment by martinmr** [comment]
Can you explain (here is good enough, no need to change the PR) how deleting the group was leading to new groups being created with a higher id instead of the id of the group that was deleted?

What we really need here to be confident of this change is a test. This is one idea of how it could be structured.

- Start with three groups, each with three alphas.
- Remove all endpoints from group 1.
- Re-add them, they should be be added to do group 1.
- (Optionally) Repeat the same process for group 2.

Also, you need to merge from master to make the tests work again.

**Comment by sch00lb0y** [comment]
@martinmr If we delete the group. zero is not able to find a group with less replication factor(https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/zero/zero.go#L432), so zero is incrementing it's group id and assigning a new one for the membership proposal

>Also, you need to merge from master to make the tests work again.

I don't have permission

**Comment by danielmai** [comment]
@sch00lb0y You can merge the dgraph master branch into the `schoolboy/group` branch in your fork. See GitHub's help page on ["Merging an upstream repository into your fork"](https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork).

**Comment by sch00lb0y** [comment]
Opps, I didn't read the comment properly. I thought to merge from dgraph to dgraph :(

I'll update the branch and test case :)

**Comment by sch00lb0y** [comment]
@martinmr Sorry for late reply. didn't have my laptop.

I've updated the test, please have a look.

In my machine test are passing `./test.sh`

But, CI is not triggering for this PR.

**Comment by campoy** [comment]
Hey @balajijinnah , could you give an update on this?

**Pull request closed without merging**
