### PR TITLE
chore(test): unskip schema test suite

### PR DESCRIPTION
**Pull request by kevinmingtarja**
### Problem
We were skipping schema suite. Tests pass.

### Solution
Unskip schema suite.

### CODE REVIEW

**Comment by skrdgraph** [comment]
@kevinmingtarja - could you click on the `license/cla` and review/sign the required paperwork

**Comment by kevinmingtarja** [comment]
Rebase done. All tests run and succeed in this package.

**Comment by kevinmingtarja** [comment]
> @kevinmingtarja - could you click on the `license/cla` and review/sign the required paperwork

Yeah I did that yesterday, but somehow it isn't reflected here on github. @skrdgraph 

Screenshot from 2022-08-31 12-37-01

**Review by meghalims — APPROVED** [review]
Looks good 👍. Go ahead and merge it

**Comment by skrdgraph** [comment]
(leaving a note to myself) verified this one - looks good 👍

**Pull request merged**
