### PR TITLE
Add benchmarks for IntersectWith

### PR DESCRIPTION
**Pull request by ashishnegi**
Benchmarks for IntersectWith
different data :
1. random data : u and v having data within range [0,limit] where limit = N * sizeof-list
~~2. uniformly distributed : u : 0,1,2.. and v : 0,100,200..~~
~~3. non-uniformly distributed : u : 0,1,2,..99,100,1001,1002,..2000 and v : 0,1,2,3..,999,1000~~
     ~~- matches at start/middle/end.~~

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/380)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[algo/uidlist_test.go, line 227 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulEisf7ga4AYQkq92:-KYulEisf7ga4AYQkq93:b64xgu3) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L227)):*
> ```Go
> // 3. non-uniformly distributed : u : 0,1,2,..100,1001,1002,..2000 and v : 0,1,2,3..1000
> 
> func uintsFromInts(ints []int) []uint64 {
> ```

Why do you need this? Why not store the data directly in uint64, instead of int first?

---

*[algo/uidlist_test.go, line 246 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulYb5aBFBKGxMRxWT:-KYulYb5aBFBKGxMRxWU:b4wf31u) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L246)):*
> ```Go
> 
> 	for i := 0; i < arrSz; i++ {
> 		u1[i] = abs(r.Int()) % limit
> ```

You can use r.Int63() and conver that to uint64.

---

*[algo/uidlist_test.go, line 249 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYuljAw7buJ_2CAIUsG:-KYuljAxvuUPKJ_yhfbk:b-mkoiua) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L249)):*
> ```Go
> 		v1[i] = abs(r.Int()) % limit
> 	}
> 	sort.Ints(u1)
> ```

I think we might have the sort.Interface defined in the code base for uint64s. If not, feel free to define one here.

---

*[algo/uidlist_test.go, line 254 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulpVm495xScnC5UqW:-KYulpVm495xScnC5UqX:b8a05a8) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L254)):*
> ```Go
> 	v := newList(uintsFromInts(v1))
> 
> 	b.Run(":curr:" + strconv.Itoa(arrSz), func(b *testing.B) {
> ```

Use full name, so it's clear what "curr" means.

---

*[algo/uidlist_test.go, line 264 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulsbJe7eoKnyVOEsI:-KYulsbJe7eoKnyVOEsJ:bmphhr2) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L264)):*
> ```Go
> 		}
> 	})
> 	b.Run(":curr:ordChg:" + strconv.Itoa(arrSz), func(b *testing.B) {
> ```

And here as well. Full name.

---

*[algo/uidlist_test.go, line 281 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYum6nDVLYy03NS1QUO:-KYum6nDVLYy03NS1QUP:b-iftw3u) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L281)):*
> ```Go
> 
> 	randomTests := func(factor int) {
> 		b.Run(strconv.Itoa(factor) + ":random:size=500", func (b *testing.B) { benchmarkListIntersectRandom(500, 500*factor, r, b) })
> ```

Over 100 lines?

---

*[algo/uidlist_test.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumEzJp8BxqsLHgHUA:-KYumEzJp8BxqsLHgHUB:b-gs3t42) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L286)):*
> ```Go
> 	}
> 
> 	randomTests(3);
> ```

Why not make the size variable as well? So, randomTests(3, 500); randomTests(3, 10000), etc.

---

*[algo/uidlist_test.go, line 304 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumgEYH0cJT_SMhQIP:-KYumgEYH0cJT_SMhQIQ:babkj1s) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L304)):*
> ```Go
> }
> 
> func benchmarkListIntersectFn(sz int, f1 func(int, int) int, f2 func(int, int) int, intersectF func(u, v *task.List), b *testing.B) {
> ```

This function signature is crazy. Find a way to refactor it, so you don't have more than 3 input arguments, and avoid passing functions as args, if possible.

---

*[algo/uidlist_test.go, line 316 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumtjZHG5OAvXxsVkK:-KYumtjZHG5OAvXxsVkL:brhumzt) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L316)):*
> ```Go
> }
> 
> func benchmarkListIntersectAll(name string, ignoreBelowSz int, f1 func(int, int) int, f2 func(int, int) int, b *testing.B) {
> ```

Same here.

---

*[algo/uidlist_test.go, line 361 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYun0WNPV_5fiUIx6JD:-KYun0WNPV_5fiUIx6JE:b-5ypmuj) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L361)):*
> ```Go
> 
> 	// 20 % of list matches at start
> 	benchmarkListIntersectAll("Same20%atStart:1", 0, matchNPercAtStart(20), naturalNums, b)
> ```

I think we don't really need to benchmark such specific cases. Just create random lists with unique elements, and run the benchmarks on them. This would make understanding the benchmarking a lot easier, and also would be closer to being realistic. In other words, doing a benchmark for first N% equal things, isn't something we can base anything on -- because that's not something we see often. So, I'd say remove all these cases and simplify the whole benchmarking code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by manishrjain** [comment]
Hey Ashish, can you remember to assign the PRs to me, so it would show up in my reviewable.io. We use that for code reviews.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-:-KYuo6v8vNZA-F0MtaST:b-hpedn6)*

**Comment by ashishnegi** [comment]
yaa.. sure; i am able to do it now, i did not had permissions earlier..

---

Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions.

---

*[algo/uidlist_test.go, line 227 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulEisf7ga4AYQkq92:-KYw2ZB7ZfnqYThaV-zE:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L227)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why do you need this? Why not store the data directly in uint64, instead of int first?
</blockquote></details>

done.

---

*[algo/uidlist_test.go, line 246 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulYb5aBFBKGxMRxWT:-KYw2b2R0DsgLE9OLS-W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L246)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can use r.Int63() and conver that to uint64.
</blockquote></details>

Done.

---

*[algo/uidlist_test.go, line 249 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYuljAw7buJ_2CAIUsG:-KYw2P2nQrqqwFcrbd7c:b-3vw4mc) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L249)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I think we might have the sort.Interface defined in the code base for uint64s. If not, feel free to define one here.
</blockquote></details>

I could not find one, talked with Ashwin and defined myself.

---

*[algo/uidlist_test.go, line 254 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulpVm495xScnC5UqW:-KYw2jdkAuDOjcnHfaIu:b-oa57h1) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L254)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Use full name, so it's clear what "curr" means.
</blockquote></details>

will `2forLoops` be better ?

---

*[algo/uidlist_test.go, line 264 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulsbJe7eoKnyVOEsI:-KYw2nxjL-eGKCkqTXwS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L264)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

And here as well. Full name.
</blockquote></details>

Done.

---

*[algo/uidlist_test.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumEzJp8BxqsLHgHUA:-KYw4Asovf3Udjs_Ln_x:b-of3z7v) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L286)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why not make the size variable as well? So, randomTests(3, 500); randomTests(3, 10000), etc.
</blockquote></details>

1. factor determines the similarity in two lists ; factor of 3 leads to higher similarity in two lists than factor of 10. Idea is that : if somebody wants to test on different data size, then one should do it for all similarity levels.. 

so for say size : 100, it will be like putting this line in fn : randomTests
`b.Run(strconv.Itoa(factor) + ":random:size=100", func (b *testing.B) { benchmarkListIntersectRandom(100, 100*factor, r, b) })`

otherwise see if below code makes more sense than current one..
```
	randomTests := func(sz int, factor int) {
		sizeStr := strconv.Itoa(sz)
		facStr := strconv.Itoa(factor)
		b.Run("factor:"+facStr+":random:size="+sizeStr, func(b *testing.B) { benchmarkListIntersectRandom(sz, sz*factor, r, b) })
	}

	randomTests(500, 3)
	randomTests(10000, 3)
	randomTests(1000000, 3)
	randomTests(500, 10)
	randomTests(10000, 10)
	randomTests(1000000, 10)
	randomTests(500, 100)
	randomTests(10000, 100)
	randomTests(1000000, 100)
```

2. I think we do not need benchmarks for arguments order change. i.e. for (u,v) pair test with (v,u) as well. That is solved. 

---

*[algo/uidlist_test.go, line 304 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumgEYH0cJT_SMhQIP:-KYwB093DrRc7KWktWtM:b-60mugs) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L304)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This function signature is crazy. Find a way to refactor it, so you don't have more than 3 input arguments, and avoid passing functions as args, if possible.
</blockquote></details>

Done. Removed these.

---

*[algo/uidlist_test.go, line 316 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumtjZHG5OAvXxsVkK:-KYwB3gCviyiJIuREdFU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L316)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

---

*[algo/uidlist_test.go, line 361 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYun0WNPV_5fiUIx6JD:-KYwB5q1O5cX3uS4oO3s:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L361)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I think we don't really need to benchmark such specific cases. Just create random lists with unique elements, and run the benchmarks on them. This would make understanding the benchmarking a lot easier, and also would be closer to being realistic. In other words, doing a benchmark for first N% equal things, isn't something we can base anything on -- because that's not something we see often. So, I'd say remove all these cases and simplify the whole benchmarking code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-:-KYv8iUOvkcpn3x0FD4b:bh796mu)*

**Comment by ashishnegi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[algo/uidlist_test.go, line 281 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYum6nDVLYy03NS1QUO:-KYwCdZ9U7w8-CfOFkoX:bapavlj) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L281)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Over 100 lines?
</blockquote></details>

reduced to 60 lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[algo/uidlist_test.go, line 254 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulpVm495xScnC5UqW:-KYyzWcy73b2Y-lDmXc1:b-xir062) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L254)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

will `2forLoops` be better ?
</blockquote></details>

I think you're trying to do a comparison benchmark between different intersection logics. That's good when trying out variations; but that's only useful short term and doesn't need to be checked in. Instead, focus on benchmarking the current code over a bunch of cases. That has a long-term value.

So, later if someone has new ideas, they can just do a before and after run, and determine if there's any improvement.

---

*[algo/uidlist_test.go, line 281 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYum6nDVLYy03NS1QUO:-KYz0EJuILE12zGxpUJN:bi2mkwt) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L281)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

reduced to 60 lines.
</blockquote></details>

Sorry, I meant over 100 chars. Just go over the code, and keep all lines to within 100 chars, not over.

---

*[algo/uidlist_test.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumEzJp8BxqsLHgHUA:-KYz1scIgTm8jtkKW6wY:b5ajwj2) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L286)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

1. factor determines the similarity in two lists ; factor of 3 leads to higher similarity in two lists than factor of 10. Idea is that : if somebody wants to test on different data size, then one should do it for all similarity levels.. 

so for say size : 100, it will be like putting this line in fn : randomTests
`b.Run(strconv.Itoa(factor) + ":random:size=100", func (b *testing.B) { benchmarkListIntersectRandom(100, 100*factor, r, b) })`

otherwise see if below code makes more sense than current one..
```
	randomTests := func(sz int, factor int) {
		sizeStr := strconv.Itoa(sz)
		facStr := strconv.Itoa(factor)
		b.Run("factor:"+facStr+":random:size="+sizeStr, func(b *testing.B) { benchmarkListIntersectRandom(sz, sz*factor, r, b) })
	}

	randomTests(500, 3)
	randomTests(10000, 3)
	randomTests(1000000, 3)
	randomTests(500, 10)
	randomTests(10000, 10)
	randomTests(1000000, 10)
	randomTests(500, 100)
	randomTests(10000, 100)
	randomTests(1000000, 100)
```

2. I think we do not need benchmarks for arguments order change. i.e. for (u,v) pair test with (v,u) as well. That is solved. 
</blockquote></details>

Yeah, I think the code you mention here is easier to follow. Though, its counter-intuitive that a higher number leads to lesser overlap.

Having said that, weren't we just going to do it based on rand and modulo N. It would be cleaner, simpler and easier to follow.

---

*[algo/uidlist_test.go, line 222 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYyz39P4305Njy3y-TY:-KYyz39P4305Njy3y-TZ:b3a4xkk) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ef5f672777370bf33fafdd1a669f33d8e545c09/algo/uidlist_test.go#L222)):*
> ```Go
> 
> // sort interface for []uint64
> type Uint64Slice []uint64
> ```

start with small case, so it's not exposed.

---

*[algo/uidlist_test.go, line 236 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYyzIyWy1elIlme_8im:-KYyzIyWy1elIlme_8in:b-jkyk6k) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ef5f672777370bf33fafdd1a669f33d8e545c09/algo/uidlist_test.go#L236)):*
> ```Go
> // Benchmarks for IntersectWith
> // random data : u and v having data within range [0,limit] where limit = N * sizeof-list
> func benchmarkListIntersectRandom(arrSz int, limit int64, r *rand.Rand, b *testing.B) {
> ```

You don't really need to pass in a rand object. Just use `rand.Int63n()`.

Also, possibly change the name here to runIntersect or something, so it's clear that this is just a helper function.

---

*[algo/uidlist_test.go, line 264 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYz1jT7BwfCIb2to_DR:-KYz1jT80bLFwExCLeui:bxdkcpa) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ef5f672777370bf33fafdd1a669f33d8e545c09/algo/uidlist_test.go#L264)):*
> ```Go
> 		sizeStr := strconv.Itoa(sz)
> 		facStr := strconv.Itoa(factor)
> 		b.Run(":random:factor="+facStr+":size="+sizeStr, func(b *testing.B) { benchmarkListIntersectRandom(sz, int64(sz*factor), r, b) })
> ```

use fmt.Sprintf.
b.Run(fmt.Sprintf(":random:factor=%d:size=%d", factor, sz), ..)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[algo/uidlist_test.go, line 254 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYulpVm495xScnC5UqW:-KYz3NSlUb1eaAoEtdjb:bs1iqyg) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L254)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I think you're trying to do a comparison benchmark between different intersection logics. That's good when trying out variations; but that's only useful short term and doesn't need to be checked in. Instead, focus on benchmarking the current code over a bunch of cases. That has a long-term value.

So, later if someone has new ideas, they can just do a before and after run, and determine if there's any improvement.
</blockquote></details>

Having a look via Github, so I can see the file in it's current form a lot clearly, looks like you already have removed all the variations in code logic. In that case, you don't need to add "2forloops" or anything else, which represents the logic. Just mentioning the array size and the modulo is sufficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[algo/uidlist_test.go, line 264 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYz1jT7BwfCIb2to_DR:-KYz47hNVlN5vNaq75eM:bqkpjko) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ef5f672777370bf33fafdd1a669f33d8e545c09/algo/uidlist_test.go#L264)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

use fmt.Sprintf.
b.Run(fmt.Sprintf(":random:factor=%d:size=%d", factor, sz), ..)
</blockquote></details>

Btw, nice job with sz*factor. Maybe do `factor/sz`, so we can use ratios to represent overlap. lower means lower overlap, and higher means higher overlap.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by ashishnegi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[algo/uidlist_test.go, line 281 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYum6nDVLYy03NS1QUO:-KZ-auC56P0muv0k_Njb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L281)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Sorry, I meant over 100 chars. Just go over the code, and keep all lines to within 100 chars, not over.
</blockquote></details>

Done.

---

*[algo/uidlist_test.go, line 286 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYumEzJp8BxqsLHgHUA:-KZ-bAl2yHb1a72gmhJJ:b-gffjoq) ([raw file](https://github.com/dgraph-io/dgraph/blob/6178fe19d30df6197f923de756c29bbd873cc714/algo/uidlist_test.go#L286)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Yeah, I think the code you mention here is easier to follow. Though, its counter-intuitive that a higher number leads to lesser overlap.

Having said that, weren't we just going to do it based on rand and modulo N. It would be cleaner, simpler and easier to follow.
</blockquote></details>

Followed advice on above comment.

---

*[algo/uidlist_test.go, line 222 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYyz39P4305Njy3y-TY:-KZ-bEi30Xz91iR5onUp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ef5f672777370bf33fafdd1a669f33d8e545c09/algo/uidlist_test.go#L222)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

start with small case, so it's not exposed.
</blockquote></details>

Done.

---

*[algo/uidlist_test.go, line 236 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYyzIyWy1elIlme_8im:-KZ-bGmrsLvGH9SfchSf:b-y5bwei) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ef5f672777370bf33fafdd1a669f33d8e545c09/algo/uidlist_test.go#L236)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't really need to pass in a rand object. Just use `rand.Int63n()`.

Also, possibly change the name here to runIntersect or something, so it's clear that this is just a helper function.
</blockquote></details>

using `runIntersectRandom` Done.

---

*[algo/uidlist_test.go, line 264 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KYz1jT7BwfCIb2to_DR:-KZ-awCKIHnu4xi-_xal:b-m4h6h9) ([raw file](https://github.com/dgraph-io/dgraph/blob/8ef5f672777370bf33fafdd1a669f33d8e545c09/algo/uidlist_test.go#L264)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Btw, nice job with sz*factor. Maybe do `factor/sz`, so we can use ratios to represent overlap. lower means lower overlap, and higher means higher overlap.
</blockquote></details>

Done. I am using overlap now. Passing limit explicitly now. `runRandomTests(500,1500)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[algo/uidlist_test.go, line 259 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-KZ0ZYUnrTbAYAfw8CHl:-KZ0ZYUnrTbAYAfw8CHm:bp4hjxr) ([raw file](https://github.com/dgraph-io/dgraph/blob/3e8bc927e2832f49637d8b0fb5393e099d3fcaba/algo/uidlist_test.go#L259)):*
> ```Go
> 
> func BenchmarkListIntersectRandom(b *testing.B) {
> 	randomTests := func(sz int, limit int) {
> ```

func(sz int, overlap float)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/380#-:-KZ0dRWeHCPO_qywDdKn:bnfp4nl)*

**Pull request closed without merging**
