### PR TITLE
Bugs/GitHub issues

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1176)

### CODE REVIEW

**Comment by janardhan1993** [comment]
1. We write snapshot first before deleting entries.
2. We are incrementing posting.list inside lcache to avoid the race condition: list being evicted before we call l.incr() after putifmissing.
3. Set minimum size of lru cache to 50mb.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-:-KoknZkS5XwxT5-M4yay:bbshgqs)*

**Comment by manishrjain** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[posting/list.go, line 530 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotBhZPi2FJw0Cwmik_:-KotBhZPi2FJw0Cwmika:b-3wo8bc) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/posting/list.go#L530)):*
> ```Go
> func (l *List) delete(ctx context.Context, attr string) error {
> 	l.AssertLock()
> 	for _, p := range l.plist.Postings {
> ```

shouldn't it go into the empty list if. I know it's the same thing, but moving it inside is cleaner. Infact, move it just before zero'ing out the Postings slice.

---

*[posting/lru.go, line 67 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotC9EGXkkf0S8q51MM:-KotC9EGXkkf0S8q51MN:b-ae6o8m) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/posting/lru.go#L67)):*
> ```Go
> 	c.Lock()
> 	defer c.Unlock()
> 	if c.curSize < (50 << 20) {
> ```

Add a fmt.Printf for warning that cur size is being set to 50MB.

---

*[raftwal/wal.go, line 83 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotE08TVJZBWWab0iqJ:-KotE08TVJZBWWab0iqK:bss6qgz) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/raftwal/wal.go#L83)):*
> ```Go
> 	}
> 	wb = badger.EntriesSet(wb, w.snapshotKey(gid), data)
> ```

This should be written out to KV, not just appended. Then the entries should be deleted. in fact, the deletions could happen in a goroutine.

---

*[x/metrics.go, line 74 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotERka_LWQoBf6NqKE:-KotERka_LWQoBf6NqKF:b6yubsj) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/x/metrics.go#L74)):*
> ```Go
> 	LCacheSize = expvar.NewInt("lcacheSize")
> 	LCacheLen = expvar.NewInt("lcacheLen")
> 	LCacheCapacity = expvar.NewInt("lCacheCapacity")
> ```

Focus. This is named l small 'c' above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176)*

**Comment by janardhan1993** [comment]
Review status: 7 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[posting/list.go, line 530 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotBhZPi2FJw0Cwmik_:-KotQjNzGdE4aUK0xse-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/posting/list.go#L530)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

shouldn't it go into the empty list if. I know it's the same thing, but moving it inside is cleaner. Infact, move it just before zero'ing out the Postings slice.
</blockquote></details>

Done.

---

*[posting/lru.go, line 67 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotC9EGXkkf0S8q51MM:-KotQpt5GW5GV3JJcG10:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/posting/lru.go#L67)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a fmt.Printf for warning that cur size is being set to 50MB.
</blockquote></details>

Done.

---

*[raftwal/wal.go, line 83 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotE08TVJZBWWab0iqJ:-KotSTygWPBzXAHq9FEK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/raftwal/wal.go#L83)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should be written out to KV, not just appended. Then the entries should be deleted. in fact, the deletions could happen in a goroutine.
</blockquote></details>

Done.

---

*[x/metrics.go, line 74 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KotERka_LWQoBf6NqKE:-KotR-ii0_9X2_TPR3J9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/146bd66f3b272096662e8ef0620d0efee2fdbc61/x/metrics.go#L74)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Focus. This is named l small 'c' above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176)*

**Comment by manishrjain** [comment]
:lgtm: Some comments.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/lru.go, line 75 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KozVWKlRq00G8zwrqYM:-KozVWKlRq00G8zwrqYN:bkpaer0) ([raw file](https://github.com/dgraph-io/dgraph/blob/fa1f9b55dd6ff0e4b5e8dd45841773725e45ff96/posting/lru.go#L75)):*
> ```Go
> 		return
> 	}
> 	x.LcacheCapacity.Set(int64(50 << 0))
> ```

What is this? This seems wrong.

---

*[raftwal/wal.go, line 90 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KozVnIAyA5ssjj7MqyY:-KozVnIAyA5ssjj7MqyZ:b-kcwnm9) ([raw file](https://github.com/dgraph-io/dgraph/blob/fa1f9b55dd6ff0e4b5e8dd45841773725e45ff96/raftwal/wal.go#L90)):*
>  s.Metadata.Term, s.Metadata.Index)
Would probably be safer to pass term and index to the goroutine as arg.

---

*[raftwal/wal.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KozVs8ndPSBSQwVpplN:-KozVs8ndPSBSQwVpplO:b-a7mh6b) ([raw file](https://github.com/dgraph-io/dgraph/blob/fa1f9b55dd6ff0e4b5e8dd45841773725e45ff96/raftwal/wal.go#L94)):*
> ```Go
> 		opt.FetchValues = false
> 		itr := w.wals.NewIterator(opt)
> 		defer itr.Close()
> ```

vertical space after this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-:-KozWml74832GfupiDDD:b-xkzuoz)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[posting/lru.go, line 75 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KozVWKlRq00G8zwrqYM:-Kozf73NPRMnlGMOv3h-:b-1fxgsm) ([raw file](https://github.com/dgraph-io/dgraph/blob/fa1f9b55dd6ff0e4b5e8dd45841773725e45ff96/posting/lru.go#L75)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What is this? This seems wrong.
</blockquote></details>

changed it to set(c.cursize)

---

*[raftwal/wal.go, line 90 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KozVnIAyA5ssjj7MqyY:-KozfFJB3uodxl8qFlih:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fa1f9b55dd6ff0e4b5e8dd45841773725e45ff96/raftwal/wal.go#L90)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

>  s.Metadata.Term, s.Metadata.Index)
Would probably be safer to pass term and index to the goroutine as arg.
</blockquote></details>

Done.

---

*[raftwal/wal.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176#-KozVs8ndPSBSQwVpplN:-KozfAnGxxdnPtq4NcO_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/fa1f9b55dd6ff0e4b5e8dd45841773725e45ff96/raftwal/wal.go#L94)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

vertical space after this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1176)*

**Comment by janardhan1993** [comment]
merged to master

**Pull request closed without merging**
