### PR TITLE
Rdf : Adds support for edge key value

### PR DESCRIPTION
**Pull request by ashishnegi**
grammar of rdf statement is changed to :
```
statement ::= subject predicate object label? edge-key-vals? .
edge-key-vals ::= '(' (key=val?) (',' key=val?)* ')'
```
We are still compatible with n-quad as `edge-key-vals` is optional.

values can not have comma `','` and right-round brancket `')'` as these are separating chars.

Also, we deduce the type of val ourselves and it can be :
`bool, string, int, float, datetime`

datetime can be of format : `2006-01-02` OR `2006-01-02T15:04:05`

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/568)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[types/facets/facet_types.go, line 62 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcGx8AndYzVvX4kRxBS:-KcGx8AndYzVvX4kRxBT:b-9h8o8x) ([raw file](https://github.com/dgraph-io/dgraph/blob/a683607a6e615ec6d84f76bd9b961549a05eb7d2/types/facets/facet_types.go#L62)):*
> ```Go
> 		return FloatID
> 	}
> 	if _, err := time.Parse(dateTimeFormat, val); err != nil {
> ```

For dateTime we might be better off using https://golang.org/pkg/time/#Time.UnmarshalText as it accepts RFC3339 format. (With timezone info)

---

*[types/facets/facets.proto, line 14 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcGwQKe2fi5MFE0pcbb:-KcGwQKfBu0Eve_DYgEL:b-li4ts0) ([raw file](https://github.com/dgraph-io/dgraph/blob/a683607a6e615ec6d84f76bd9b961549a05eb7d2/types/facets/facets.proto#L14)):*
> ```protobuf
> 	     BOOL = 3;
> 	     DATETIME = 4;
> 	}
> ```

@manishrjain : Do we need to have separate TypeIDs for the KVs or should we use the ones we already have in types package?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568)*

**Comment by ashishnegi** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[types/facets/facet_types.go, line 62 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcGx8AndYzVvX4kRxBS:-KcQlIiC2YuvqW9PDWHX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/a683607a6e615ec6d84f76bd9b961549a05eb7d2/types/facets/facet_types.go#L62)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

For dateTime we might be better off using https://golang.org/pkg/time/#Time.UnmarshalText as it accepts RFC3339 format. (With timezone info)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568)*

**Comment by manishrjain** [comment]
This PR doesn't use facets yet, right? Also, needs refactoring of the parsing logic.

---

Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[rdf/state.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcRYNMUohk7TPpPM5LH:-KcRYNMVmVjv0a3tl2BW:b-j1v1xa) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad9a9a3666588e311e5c0b0de0eb174a06441af/rdf/state.go#L40)):*
> ```Go
> 	itemValidEnd                           // end with dot, 13
> 	itemComment                            // comment, 14
> 	itemFacetKey                           // facet key, 15
> ```

This should be done in parse. Not state. State should be simple.

---

*[rdf/state.go, line 369 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcRYU3ySMEq4uX3ZlmM:-KcRYU3ySMEq4uX3ZlmN:bcenojm) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad9a9a3666588e311e5c0b0de0eb174a06441af/rdf/state.go#L369)):*
> ```Go
> // ( key1 = "value1", key2=13, key3=, key4 =2.4, key5=2006-01-02T15:04:05,
> //   key6=2006-01-02 )
> func lexFacets(l *lex.Lexer) lex.StateFn {
> ```

This should only output left bracket, something, equal sign, something else, comma, something, etc. The parser should make sense of it.

---

*[types/facets/facet_types.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcRYnLXOCt-cTQzA-mn:-KcRYnLXOCt-cTQzA-mo:bl2fmpf) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad9a9a3666588e311e5c0b0de0eb174a06441af/types/facets/facet_types.go#L63)):*
> ```Go
> 	}
> 	var t time.Time
> 	if err := t.UnmarshalText([]byte(val)); err != nil {
> ```

Move time parsing to a function, and use returns instead of nesting here.

---

*[types/facets/facets.proto, line 14 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcGwQKe2fi5MFE0pcbb:-KcRYulP4_mUiQwSP-Me:b-w6cxt5) ([raw file](https://github.com/dgraph-io/dgraph/blob/a683607a6e615ec6d84f76bd9b961549a05eb7d2/types/facets/facets.proto#L14)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

@manishrjain : Do we need to have separate TypeIDs for the KVs or should we use the ones we already have in types package?
</blockquote></details>

These are a small subset of all the ones that we support in values. So, okay to keep it separate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-:-KcRZ87MRcNyxZqW9BM7:b-mrhxv)*

**Comment by ashishnegi** [comment]
yes.. this does not use facets yet.. 
that comes after gql parsing, we can retrieve the facets.

---

Review status: 3 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[rdf/state.go, line 40 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcRYNMUohk7TPpPM5LH:-KcRzv6IUJUFuIX7lmD4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad9a9a3666588e311e5c0b0de0eb174a06441af/rdf/state.go#L40)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should be done in parse. Not state. State should be simple.
</blockquote></details>

Done.

---

*[rdf/state.go, line 369 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcRYU3ySMEq4uX3ZlmM:-KcRu8wcbMU-iuhNrQno:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad9a9a3666588e311e5c0b0de0eb174a06441af/rdf/state.go#L369)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This should only output left bracket, something, equal sign, something else, comma, something, etc. The parser should make sense of it.
</blockquote></details>

Done.

---

*[types/facets/facet_types.go, line 63 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcRYnLXOCt-cTQzA-mn:-KcRzs82LnMUETZR9dMX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/dad9a9a3666588e311e5c0b0de0eb174a06441af/types/facets/facet_types.go#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move time parsing to a function, and use returns instead of nesting here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-:-KcR_-D85tDnfpwq2ZRN:b-pl6epa)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[rdf/parse.go, line 370 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcW0GRuMZ3faqKw9sHS:-KcW0GRuMZ3faqKw9sHT:bgkslh9) ([raw file](https://github.com/dgraph-io/dgraph/blob/af94aed224932fbd4fdf29393e208b9d3e629c1e/rdf/parse.go#L370)):*
> ```Go
> 			continue
> 		}
> ```

Extra vertical space.

---

*[rdf/parse.go, line 387 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcW0Xtr6r9LfDLH4Gxh:-KcW0Xtr6r9LfDLH4Gxi:bgkslh9) ([raw file](https://github.com/dgraph-io/dgraph/blob/af94aed224932fbd4fdf29393e208b9d3e629c1e/rdf/parse.go#L387)):*
> ```Go
> 		return x.Errorf("Expected , or ) after facet. Received %s", item.Val)
> 	}
> ```

Extra vertical space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-:-KcW27uBU5RfBMrDi2cW:bnfp4nl)*

**Comment by ashishnegi** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[rdf/parse.go, line 370 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcW0GRuMZ3faqKw9sHS:-KcW38riINPxeTUfGz-4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/af94aed224932fbd4fdf29393e208b9d3e629c1e/rdf/parse.go#L370)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Extra vertical space.
</blockquote></details>

Done.

---

*[rdf/parse.go, line 387 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-KcW0Xtr6r9LfDLH4Gxh:-KcW39lriU7cH78OqNba:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/af94aed224932fbd4fdf29393e208b9d3e629c1e/rdf/parse.go#L387)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Extra vertical space.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568#-:-KcWCcYFYWOI4GCsk6su:bnfp4nl)*

**Comment by ashwin95r** [comment]
Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/568)*

**Pull request closed without merging**
