### PR TITLE
Move some fields into a struct

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/220)

### CODE REVIEW

**Comment by manishrjain** [comment]
One small change.  Ping after implementing.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/220#-KS1c4rGSWiPlzwOvKKE:-KS1c4rGSWiPlzwOvKKF:b9pt0iw) ([raw file](https://github.com/dgraph-io/dgraph/blob/532027a78271d3d375334d922b8f02cb5b112824/query/query.go#L114)):*
> ```Go
> }
> 
> type sgArgs struct {
> ```

just call them Params?

---

*[query/query.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/220#-KS1cA4wq_lYjkCLoxlJ:-KS1cA4wq_lYjkCLoxlK:b-9zenm1) ([raw file](https://github.com/dgraph-io/dgraph/blob/532027a78271d3d375334d922b8f02cb5b112824/query/query.go#L132)):*
> ```Go
> 	Attr     string
> 	Children []*SubGraph
> 	Args     sgArgs
> ```

Params Params // yes you can do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/220#-:-KS1cRHLHqKquStEfsTf:bofrtz7)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 114 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/220#-KS1c4rGSWiPlzwOvKKE:-KS1eETbS04CoMzlH-cz:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/532027a78271d3d375334d922b8f02cb5b112824/query/query.go#L114)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> just call them Params?
</details>
Done.

---

*[query/query.go, line 132 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/220#-KS1cA4wq_lYjkCLoxlJ:-KS1eF0VpypxA0IOIpfy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/532027a78271d3d375334d922b8f02cb5b112824/query/query.go#L132)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Params Params // yes you can do that.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/220)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 114 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/220#-KRmv7B3YOjB0pNbBFB--r2-114:-KS1exT0voUTNHjENbcX:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4140be9c35c4114e44e20de5549933920385f103/query/query.go#L114)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported type Params should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/220)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/220#-:-KS6pSHGvQTMboK4bcdH:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged to master

**Pull request closed without merging**
