### PR TITLE
Add support for predicate group map

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/262)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 6 of 9 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[cmd/dgraph/group.conf, line 2 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDVTr9fM0Z3moOf2OK:-KTDVTrAdzuSNjYiAUE2:bmbg4f7) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/cmd/dgraph/group.conf#L2)):*
> ```
> // Default formula for getting group.
> default: attribute % 10 + 3
> ```

This doesn't generate group ids 0 to 2. I think we should check that the group ids are continuous and from zero onwards.

Maybe call it pred. Handle the case where + is not there.

---

*[cmd/dgraph/main.go, line 617 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDcJCRb7blyMsWt4yE:-KTDcJCRb7blyMsWt4yF:b-2ncxad) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/cmd/dgraph/main.go#L617)):*
> ```Go
> 	posting.InitIndex(ps)
> 	posting.Init()
> 	worker.ParseGroupConfig("group.conf")
> ```

Make it a flag.

---

*[worker/group.go, line 54 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDe34tSpJa1Wwh7Zj_:-KTDe34tSpJa1Wwh7Zja:b-s3iulr) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L54)):*
> ```Go
> 		x.Check(fmt.Errorf("Default config format isn't correct: %v", l))
> 	}
> 	if conf[1] != "%" || conf[3] != "+" {
> ```

Handle the case where + is not there. Maybe check that they say fp.

---

*[worker/group.go, line 65 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDd58eBiBNmRzKO9q-:-KTDd58eBiBNmRzKO9q0:b-8uhawg) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L65)):*
> ```Go
> }
> 
> func parsePredicateConfig(gid string, preds string) {
> ```

This doesn't need to be a function.

---

*[worker/group.go, line 89 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDdAAPlNXxdlts7bMT:-KTDdAAPlNXxdlts7bMU:bcdi5vc) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L89)):*
> ```Go
> 			parsePredicateConfig(c[0], preds)
> 		}
> 	}
> ```

Check that the schema would geneate groupids from zero to a max number, and determine that number.

---

*[worker/group.go, line 105 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDdgQVfPvLRWo9bDcF:-KTDdgQWBqqrgItKZMzF:b8pf4cn) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L105)):*
> ```Go
> }
> 
> func group(pred string) uint64 {
> ```

group id should be a uint32.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/262)*

**Comment by pawanrawal** [comment]
Should there be a limit to the N in %N? Or maybe we should decide the N and k, we already know the groups that user has given, maybe we can have N as double of that. I feel this would reduce a complication for the user to define the modulo formula.

---

Review status: 0 of 13 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main.go, line 617 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDcJCRb7blyMsWt4yE:-KTEWaHoZJ4ORVoP2Ry8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/cmd/dgraph/main.go#L617)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Make it a flag.
</details>
Done.

---

*[cmd/dgraph/group.conf, line 2 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDVTr9fM0Z3moOf2OK:-KTEb9T7MTDIqv7tJuBK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/cmd/dgraph/group.conf#L2)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This doesn't generate group ids 0 to 2. I think we should check that the group ids are continuous and from zero onwards.
> 
> Maybe call it pred. Handle the case where + is not there.
</details>
Done.

---

*[worker/group.go, line 54 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDe34tSpJa1Wwh7Zj_:-KTEbBRMc_BcjP2HTY4U:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L54)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Handle the case where + is not there. Maybe check that they say fp.
</details>
Done.

---

*[worker/group.go, line 65 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDd58eBiBNmRzKO9q-:-KTEWcuDE5B-YobmGZEd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L65)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This doesn't need to be a function.
</details>
Done.

---

*[worker/group.go, line 89 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDdAAPlNXxdlts7bMT:-KTEWeU5vCaOsPoH8324:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L89)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Check that the schema would geneate groupids from zero to a max number, and determine that number.
</details>
Done.

---

*[worker/group.go, line 105 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTDdgQVfPvLRWo9bDcF:-KTEbCUzB98Vz11YS4pc:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/eeb30256c3de179db774fa294aef2b78e8e13587/worker/group.go#L105)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> group id should be a uint32.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-:-KTEXYbQCLZ1lSfocCBK:b-jipmza)*

**Comment by manishrjain** [comment]
:lgtm: Nice work! I think the limit for N is uint32, by definition. We don't really need to have any other restriction, unless for a particular cause. In fact, one more thing that might make sense is in the absence of a specified `groups.conf`, we just use N = 1.

---

Reviewed 15 of 18 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[worker/conf.go, line 75 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTHuxH1uQHdLOwvK8XW:-KTHuxH2U1J4BwwZVe4y:bo40o7h) ([raw file](https://github.com/dgraph-io/dgraph/blob/a402c665319f16d512107b01f9832265c25c57ef/worker/conf.go#L75)):*
> ```Go
> 	// To keep track of last groupId seen across lines. If we the groups ids are
> 	// not sequential, we log.Fatal.
> 	var currGroupId uint64
> ```

var curGroupId, just a single r.

---

*[worker/conf.go, line 143 at r5](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-KTHvQucpdsSGB0om72r:-KTHvQucpdsSGB0om72s:bpgwka) ([raw file](https://github.com/dgraph-io/dgraph/blob/a402c665319f16d512107b01f9832265c25c57ef/worker/conf.go#L143)):*
> ```Go
> }
> 
> func group(pred string) uint32 {
> ```

Call it BelongsTo, so my code would work just right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/262#-:-KTHvdyWXDIxVL1OELeR:blvll19)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
