### PR TITLE
Sort/facets

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1166)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Syntax:
```
{
	me(func: uid(1)) {
		friend @facets(orderasc:since) {
			name
		}
	}
}
```

**Comment by pawanrawal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 1890 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopJ2bIJD6DyprAkieY:-KopJ2bIJD6DyprAkieZ:b-mr6j97) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/query/query.go#L1890)):*
> ```Go
> 
> 	if sg.Params.Count == 0 {
> 		// Only retrieve up to 1000 results by default.
> ```

Shouldn't this still be up and passed down to sortUsingFacet?

---

*[query/query.go, line 1932 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopFSEC7YW6owUAsV58:-KopFSEC7YW6owUAsV59:bghgqf5) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/query/query.go#L1932)):*
> ```Go
> }
> 
> func (sg *SubGraph) sortUsingFacet(ctx context.Context) error {
> ```

sortAndPaginateUsingFacet?

---

*[query/query.go, line 1942 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopIYccid6owQb1FYpk:-KopIYcdQ20UsMjV88GQ:b-tsswh9) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/query/query.go#L1942)):*
> ```Go
> 		uids := make([]uint64, 0, len(ul.Uids))
> 		values := make([]types.Val, 0, len(ul.Uids))
> 		facetList := make([]*protos.Facets, 0, len(fl.FacetsList))
> ```

We could avoid creating copies for facetList and uids by filtering those within the Subgraph and passing those down to sort.

---

*[types/sort.go, line 69 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopH-gRoUT503TGPMph:-KopH-gRoUT503TGPMpi:b-442pop) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/types/sort.go#L69)):*
> ```Go
> 
> // Sort sorts the given array in-place.
> func SortWithFacet(v []Val, ul *protos.List, l []*protos.Facets, desc bool) error {
> ```

We could merge this with the method below and pass nil when we dont have protos.Facets?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166)*

**Comment by ashwin95r** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query.go, line 1890 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopJ2bIJD6DyprAkieY:-KopoNGCGes1VV4YrGx6:b-mbp7x2) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/query/query.go#L1890)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Shouldn't this still be up and passed down to sortUsingFacet?
</blockquote></details>

For facets, we've already fetched all the values, so no need to limit the number of results. The limit is useful only when we want to sortwithindex where we can stop iterating once we reach the limit.

---

*[query/query.go, line 1932 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopFSEC7YW6owUAsV58:-KopohR8FbwCiOJxTzO9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/query/query.go#L1932)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

sortAndPaginateUsingFacet?
</blockquote></details>

Done.

---

*[query/query.go, line 1942 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopIYccid6owQb1FYpk:-KopqbrGUtLJJF9bAEEL:bkuw9dg) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/query/query.go#L1942)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We could avoid creating copies for facetList and uids by filtering those within the Subgraph and passing those down to sort.
</blockquote></details>

Reusing the slice instead of creating new ones.

---

*[types/sort.go, line 69 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-KopH-gRoUT503TGPMph:-KoppL6l3SO65Prbq2iy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/072a3e91a724b51079568c6b70e89bc7d388127f/types/sort.go#L69)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We could merge this with the method below and pass nil when we dont have protos.Facets?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166)*

**Comment by pawanrawal** [comment]
:lgtm: 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-:-KoznCh4HeiMUnSeuh58:bg7igkv)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1166#-:-KpTxwTD7DKgSvwagv_o:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
