### PR TITLE
Improve/password

### PR DESCRIPTION
**Pull request by squalfof**
1. add password type, with rdf format like
```
<alice> <password> "123456"^^<pwd:password>
```
2. password is not fetchable;

3. user could verify password as
```
me(id:x) {
     checkpwd("123456")
}
```
with response
```
{"checkpwd": 1}  // if password correct
{"checkpwd": 0}  // incorrect
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/577)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 118 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrWwz2eilbU-shGzn2:-KcrWwz2eilbU-shGzn3:b-32avxr) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L118)):*
> ```Go
> }
> 
> func (f *Function) IsPasswordVerifier() bool {
> ```

You don't need to strings.ToLower this. We should just do the tolower once when parsing.

---

*[gql/parser.go, line 1273 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXM3R-Ai6TKbhj15L:-KcrXM3R-Ai6TKbhj15M:b80sa62) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L1273)):*
> ```Go
> 			}
> 
> 			if isAggregator(item.Val) || isPasswordVerifier(item.Val) {
> ```

We can just `strings.ToLower` item.Val here, and directly check for their name.

---

*[gql/parser.go, line 1281 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXXgzWN4KabJaltRL:-KcrXXgzWN4KabJaltRM:b-d9amah) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L1281)):*
> ```Go
> 					return err
> 				}
> 				if isPasswordVerifier(item.Val) {
> ```

No need for function. Use const if you need. `if item.Val == "checkpwd"`

---

*[gql/parser.go, line 1364 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrWfcQ67WJ9UkMJKIE:-KcrWfcQ67WJ9UkMJKIF:b-nr63xn) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L1364)):*
> ```Go
> }
> 
> func isPasswordVerifier(f string) bool {
> ```

We don't need this func.

---

*[gql/parser_test.go, line 1355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXfa25nzFhsUBwn5D:-KcrXfa25nzFhsUBwn5E:buodxcr) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser_test.go#L1355)):*
> ```Go
> 		me(id:1) {
> 			checkpwd("123456")
> 			hometown
> ```

If someone asks for password, what do we do?

---

*[gql/parser_test.go, line 1559 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXnPWpgxtMtTKrikx:-KcrXnPWpgxtMtTKriky:b-y7zouw) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser_test.go#L1559)):*
> ```Go
> 	mutation {
> 		set {
> 			<alice> <password> "PenAndPencil"^^<pwd:password>
> ```

How about <xs:pwd> or <xs:password>?

---

*[types/password.go, line 18 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-Kcrm7QaobbkToKhxcjB:-Kcrm7QaobbkToKhxcjC:b-povo8) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L18)):*
> ```Go
> )
> 
> func GenerateFromPassword(password string) (string, error) {
> ```

func Encrypt(plain string)

---

*[types/password.go, line 21 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrlfQ16u3qN0EW9LWF:-KcrlfQ2IvUvmIG4-2La:b-4mdqd8) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L21)):*
> ```Go
> 	var result string
> 	var byt []byte
> 	var err error
> ```

You don't need to define these vars in advance.

---

*[types/password.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrliWcnYTN1Ga4uQKB:-KcrliWcnYTN1Ga4uQKC:bf1yc8o) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L27)):*
> ```Go
> 	// no need to generate salt outselves since salt is incorporated in the result as well
> 	// check wiki https://en.wikipedia.org/wiki/Bcrypt
> 	byt, err = bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
> ```

byt, err := ...

---

*[types/password.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrmAdYGOsx15Uzw7vq:-KcrmAdYGOsx15Uzw7vr:bs1k59a) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L39)):*
> ```Go
> }
> 
> func VerifyPassword(password, crypted string) error {
> ```

func VerifyPassword(plain, encrypted string) error {

---

*[types/password.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrmSIELr1LALO2vWDE:-KcrmSIELr1LALO2vWDF:bli93dp) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L46)):*
> ```Go
> 	arr := strings.Split(strings.Trim(crypted, "$"), "$")
> 	x.AssertTruef(len(arr) == 3, "Password is corrupted")
> 	target := arr[2]
> ```

You're not using cost, i.e. argument 1. Also, what does "$2a" mean?

---

*[worker/task.go, line 245 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrmzJ4wo_QAUR0YBnW:-KcrmzJ4wo_QAUR0YBnX:bfyz4qc) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/worker/task.go#L245)):*
> ```Go
> 			lastPos := len(out.Values) - 1
> 			if len(newValue.Val) == 0 {
> 				out.Values[lastPos] = task.FromInt(0)
> ```

You can create vars for task.FromInt(0) and task.FromInt(1) and use them here and elsewhere. Though, I think you should be using booleans instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/577)*

**Comment by manishrjain** [comment]
:lgtm: Address the comments, and then feel free to submit.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-:-KcrnXszSgGj9g7w_LjG:b-fou0d)*

**Comment by squalfof** [comment]
Review status: 11 of 18 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 118 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrWwz2eilbU-shGzn2:-KcuCjkpLpF_fyMGUi2M:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L118)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need to strings.ToLower this. We should just do the tolower once when parsing.
</blockquote></details>

Done.

---

*[gql/parser.go, line 1273 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXM3R-Ai6TKbhj15L:-KcuYGyzoFBa7Vdp4HA8:b-20p3dc) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L1273)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We can just `strings.ToLower` item.Val here, and directly check for their name.
</blockquote></details>

Concern is item here may represent an attribute, string.ToLower(item.Val)
will change the name of attribute, like from **count(FILM)** to **count(film)**. 

If we confirmed that item is Aggregator/Password, then do the ToLower().
Done.

---

*[gql/parser.go, line 1281 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXXgzWN4KabJaltRL:-KcuXZSiKShPJ0p6Ez7w:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L1281)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for function. Use const if you need. `if item.Val == "checkpwd"`
</blockquote></details>

Done.

---

*[gql/parser.go, line 1364 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrWfcQ67WJ9UkMJKIE:-KcuDSVQGknUdb4_fNHM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser.go#L1364)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We don't need this func.
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 1355 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXfa25nzFhsUBwn5D:-KcuR0UoxcLxAE_hEzX7:bm85iu8) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser_test.go#L1355)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If someone asks for password, what do we do?
</blockquote></details>

Response as,

```
{"code":"ErrorInvalidRequest","message":"Password is not fetchable"}
```

---

*[gql/parser_test.go, line 1559 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrXnPWpgxtMtTKrikx:-KcuRlZU6nkx4M7KSIuq:bo2xtr3) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/gql/parser_test.go#L1559)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

How about <xs:pwd> or <xs:password>?
</blockquote></details>

Thought about it before. Since element prefixed with **'xs:'** seems belong to XML standard,
like **'xs:string'**, **'xs:int'**. I'm not sure if we could use **'xs:password'** this way as it's not part of the standard.

Besides, i found we've already provide specific type **'geo:geojson'**,
so i followed it, using **'pwd:password'**

---

*[types/password.go, line 18 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-Kcrm7QaobbkToKhxcjB:-KcuEH0LnVMNebdPM899:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L18)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

func Encrypt(plain string)
</blockquote></details>

Done.

---

*[types/password.go, line 21 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrlfQ16u3qN0EW9LWF:-KcuEIl7d7xElNjDOFR6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L21)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You don't need to define these vars in advance.
</blockquote></details>

Done.

---

*[types/password.go, line 27 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrliWcnYTN1Ga4uQKB:-KcuEJQmjcbmablohR9b:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L27)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

byt, err := ...
</blockquote></details>

Done.

---

*[types/password.go, line 39 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrmAdYGOsx15Uzw7vq:-KcuEzaOkXiyOjDEzEVC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L39)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

func VerifyPassword(plain, encrypted string) error {
</blockquote></details>

Done.

---

*[types/password.go, line 46 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrmSIELr1LALO2vWDE:-KcuFMteyJ2QM4O9ZueA:b-208jvx) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/types/password.go#L46)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You're not using cost, i.e. argument 1. Also, what does "$2a" mean?
</blockquote></details>

Actually, I just follow the format introduced from wiki https://en.wikipedia.org/wiki/Bcrypt
```
$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
```
The prefix "$2a$" or "$2b$" (or "$2y$") in a hash string in a shadow password file indicates that hash string is a bcrypt hash in modular crypt format.

---

*[worker/task.go, line 245 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-KcrmzJ4wo_QAUR0YBnW:-KcuPkW7Ky4wiiwlERti:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/71b21fa50f43cc1370ed5f982280fe481122559a/worker/task.go#L245)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can create vars for task.FromInt(0) and task.FromInt(1) and use them here and elsewhere. Though, I think you should be using booleans instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/577)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 11 of 18 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/577#-:-KcuntASvpoUbEEsEZQy:bnfp4nl)*

**Pull request closed without merging**
