### PR TITLE
perf(GraphQL): JSON Part-7: JSON is generated by Dgraph for custom HTTP fields  (GRAPHQL-878)

### PR DESCRIPTION
**Pull request by abhimanyusinghgaur**
This PR moves the resolution and GraphQL JSON generation for `@custom(http: {...})` fields inside Dgraph.
It also fixes following existing bugs with `@custom` field resolution:
* https://discuss.dgraph.io/t/slash-graphql-lambda-bug/12233 (GRAPHQL-967)
* race condition in custom logic with repeated fields in implementing types (GRAPHQL-860)
* GRAPHQL-639

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7361)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 16 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7361)* status: 16 of 18 files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, and @vvbalaji-dgraph)

___
*[graphql/e2e/custom_logic/custom_logic_test.go, line 2640 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsKGNC4NwXaqgUFfhe:-MRsKGNC4NwXaqgUFfhf:b-8tykxa) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/e2e/custom_logic/custom_logic_test.go#L2640)):*
> ```Go
> 			}
> 			queryUserTweetCounts(func: uid(tc), orderdesc: val(tc)) {
> 				UserTweetCount.screen_name: User.screen_name
> ```

This can be done dynamically so that it's backward compatible for now. Later we can make this easier by doing improvements to custom DQL.
___
*[graphql/schema/custom_http.go, line 78 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsLZmo4tRQrIyNouV-:-MRsLZmo4tRQrIyNouV0:b5c81sk) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/custom_http.go#L78)):*
> ```Go
> // MakeAndDecodeHTTPRequest sends an HTTP request using the given url and body and then decodes the
> // response correctly based on whether it was a GraphQL or REST request.
> // It returns the decoded response along with one of soft and hard errors.
> ```

soft or hard errors
___
*[graphql/schema/custom_http.go, line 81 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsMHRpC3aIwwyXhFFJ:-MRsMHRpC3aIwwyXhFFK:bobexab) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/custom_http.go#L81)):*
> ```Go
> // Soft error means one can assume that the response is valid and continue the normal execution.
> // Hard error means there will be no response returned and one must stop the normal execution flow.
> func (fconf *FieldHTTPConfig) MakeAndDecodeHTTPRequest(client *http.Client, url string,
> ```

Can we add a comment that what is considered as a hard error for GraphQL and REST?
___
*[graphql/schema/wrappers.go, line 302 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsMkU4CkIX5M_uPbvR:-MRsMkU4CkIX5M_uPbvS:bidbhhx) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/wrappers.go#L302)):*
> ```Go
> 	// this flag has already been calculated or not. If not calculated, it would be nil.
> 	// Otherwise, it would always contain a boolean value.
> 	hasCustomHTTPChild interface{}
> ```

We can keep it as `*bool`
___
*[graphql/schema/wrappers.go, line 1209 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsO6Am-OXCiAScvmWt:-MRsO6Am-OXCiAScvmWu:bxwr138) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/wrappers.go#L1209)):*
> ```Go
> 		// defined in the schema being served. Resolving such a query would report that no
> 		// suitable resolver was found.
> 		// TODO: Ideally, this case shouldn't happen as the query isn't defined in the schema,
> ```

Can we create a ticket mentioning the test case that fails without this and assign it to Jatin?
___
*[query/outputnode_graphql.go, line 583 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsSy9m1sYa1Jb6oz89:-MRsSy9m1sYa1Jb6oz8A:b-dnq8ma) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/query/outputnode_graphql.go#L583)):*
> ```Go
> // For fields without custom directive we recursively call resolveCustomFields and let it do the
> // work.
> func (gqlCtx *graphQLEncodingCtx) resolveCustomFields(ctx context.Context, enc *encoder,
> ```

I'll have another look at this and leave any comments that I have.

**Review by pawanrawal — COMMENTED** [review]
> Reviewed 2 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7361)* status: all files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, and @vvbalaji-dgraph)

**Review by abhimanyusinghgaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7361)* status: 12 of 29 files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/e2e/custom_logic/custom_logic_test.go, line 2640 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsKGNC4NwXaqgUFfhe:-MS2VnXWE8j8R3qT_RkB:benq2l8) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/e2e/custom_logic/custom_logic_test.go#L2640)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This can be done dynamically so that it's backward compatible for now. Later we can make this easier by doing improvements to custom DQL.
</blockquote></details>

Will do this in a later PR, skipping this test for now.
___
*[graphql/schema/custom_http.go, line 78 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsLZmo4tRQrIyNouV-:-MS2Vs-Z-4wjkvvamN-N:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/custom_http.go#L78)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

soft or hard errors
</blockquote></details>

Done.
___
*[graphql/schema/custom_http.go, line 81 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsMHRpC3aIwwyXhFFJ:-MS2VtQL6WsJGtboBhuK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/custom_http.go#L81)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we add a comment that what is considered as a hard error for GraphQL and REST?
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 302 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsMkU4CkIX5M_uPbvR:-MS2VuxdB1EB6dLJvMaw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/wrappers.go#L302)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We can keep it as `*bool`
</blockquote></details>

Done.
___
*[graphql/schema/wrappers.go, line 1209 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsO6Am-OXCiAScvmWt:-MS2VwHu0R4rRXhZsFu8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/graphql/schema/wrappers.go#L1209)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can we create a ticket mentioning the test case that fails without this and assign it to Jatin?
</blockquote></details>

Done.
___
*[query/outputnode_graphql.go, line 583 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7361#-MRsSy9m1sYa1Jb6oz89:-MS2VyDHAm9dwhboAPKC:b32w0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/06655a9615544ddbca2eca2898e9bba6c2799541/query/outputnode_graphql.go#L583)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I'll have another look at this and leave any comments that I have.
</blockquote></details>

OK

**Review by pawanrawal — APPROVED** [review]
> Reviewed 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7361)* status: all files reviewed, 1 unresolved discussion (waiting on @abhimanyusinghgaur, @manishrjain, and @vvbalaji-dgraph)

**Pull request merged**
