### PR TITLE
chore: apply go vet improvements

### PR DESCRIPTION
**Pull request by mangalaman93**

### CODE REVIEW

**Comment by skrdgraph** [comment]
Could you add a description to the PR? There is a PR template that guides certain standards, the description goes into the commit message.

Regarding `go vet`:
- We have a golint pipeline https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/ci-golang-lint.yml (this just tells you how we run golints)
- The main configuration to `go vet` in golint happens in this file https://github.com/dgraph-io/dgraph/blob/main/.golangci.yml#L28

We punted on making these changes because it had turned out to be too much work then. Now that you are making these changes w/ `go vet` ... it would be best to uncomment this section to see if everything passes correctly. And if it finds any failures you would know right away.

There are other code simplification linters we should start looking into enabling as well.

**Comment by skrdgraph** [comment]
re-ran the ci-dgraph-tests, because I am seeing some ACL test failures.

**Comment by mangalaman93** [comment]
I have enabled them in this change. Let me see if we can fix all of them. I had only fixed some of them to begin with. For the PR description, I think there is nothing more that I could describe. The changes are not significant either yet.

**Review by sanjayk-github-dev — DISMISSED** [review]
Mostly cosmetic changes.

Were the files under contrib/teamcity deleted because teamcity is not being used?

**Comment by mangalaman93** [comment]
yes, I am hoping that is fine. If not, I can undo that change.

**Review by skrdgraph — APPROVED** [review]
This looks good 👍

**Review by sanjayk-github-dev — APPROVED** [review]
Assume that the teamcity related files are not needed any more.

**Pull request merged**
