### PR TITLE
fix(Chunker): JSON parsing performance

### PR DESCRIPTION
**Pull request by karlmcguire**
Fixes DGRAPH-2860.

About a 90% performance increase in NQuads/sec on the data used in the `BenchmarkNoFacets()` function.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7171)

### CODE REVIEW

**Review by manishrjain — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7171)* status: all files reviewed, 4 unresolved discussions (waiting on @karlmcguire and @vvbalaji-dgraph)

___
*[go.mod, line 19 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsGwJ66BtcxS1bLWZG:-MOsGwJ66BtcxS1bLWZH:b-hfpv1m) ([raw file](https://github.com/dgraph-io/dgraph/blob/79b20c640b684ad5695e809642f1b1e808d96f13/go.mod#L19)):*
> ```XML
> 	github.com/blevesearch/bleve v1.0.13
> 	github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd
> 	github.com/davecgh/go-spew v1.1.1
> ```

remove?
___
*[go.mod, line 48 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsGvQy4807bRZjZlus:-MOsGvQy4807bRZjZlut:b-hfpv1m) ([raw file](https://github.com/dgraph-io/dgraph/blob/79b20c640b684ad5695e809642f1b1e808d96f13/go.mod#L48)):*
> ```XML
> 	github.com/hashicorp/vault/api v1.0.4
> 	github.com/minio/minio-go/v6 v6.0.55
> 	github.com/minio/simdjson-go v0.1.5
> ```

remove?
___
*[go.mod, line 52 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsaSbj-uUVxUwZ94B_:-MOsaSbj-uUVxUwZ94Ba:b-q3mj8o) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1d3411633b452e7025a5d084007543b84119f2/go.mod#L52)):*
> ```XML
> 	github.com/pkg/profile v1.2.1
> 	github.com/prometheus/client_golang v0.9.3
> 	github.com/prometheus/common v0.4.1 // indirect
> ```

revert go.mod. And then run go mod tidy.
___
*[chunker/json_parser.go, line 385 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsaKYlBlHnzhDCIL-2:-MOsaKYlBlHnzhDCIL-3:b9r8k98) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1d3411633b452e7025a5d084007543b84119f2/chunker/json_parser.go#L385)):*
> ```Go
> 	for k, v := range m {
> 		if strings.Contains(k, x.FacetDelimeter) {
> 			mf[k] = v
> ```

I'd also delete them from m, so the iteration over m is faster.

**Review by manishrjain — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7171)* status: all files reviewed, 5 unresolved discussions (waiting on @karlmcguire and @vvbalaji-dgraph)

___
*[chunker/json_parser.go, line 433 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsahwvDOi9bboidRbC:-MOsahwvDOi9bboidRbD:b-7lv37g) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1d3411633b452e7025a5d084007543b84119f2/chunker/json_parser.go#L433)):*
> ```Go
> 		// option.
> 		// We also skip facets here because we parse them with the corresponding predicate.
> 		if pred == "uid" || strings.Index(pred, x.FacetDelimeter) > 0 {
> ```

If m doesn't have facets, then you can save on the strings.Index search.

**Review by karlmcguire — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7171)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @manishrjain and @vvbalaji-dgraph)

___
*[go.mod, line 19 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsGwJ66BtcxS1bLWZG:-MOscKDu-_6MmVWvj2I8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/79b20c640b684ad5695e809642f1b1e808d96f13/go.mod#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[go.mod, line 48 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsGvQy4807bRZjZlus:-MOscMes09fdBBbd6FSJ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/79b20c640b684ad5695e809642f1b1e808d96f13/go.mod#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

remove?
</blockquote></details>

Done.
___
*[go.mod, line 52 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsaSbj-uUVxUwZ94B_:-MOscPDw10zb7d22s3qn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1d3411633b452e7025a5d084007543b84119f2/go.mod#L52)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

revert go.mod. And then run go mod tidy.
</blockquote></details>

Done.
___
*[chunker/json_parser.go, line 385 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsaKYlBlHnzhDCIL-2:-MOscQjqAaEpgoMhS2y9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1d3411633b452e7025a5d084007543b84119f2/chunker/json_parser.go#L385)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I'd also delete them from m, so the iteration over m is faster.
</blockquote></details>

Done.
___
*[chunker/json_parser.go, line 433 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-MOsahwvDOi9bboidRbC:-MOscRSjBp3sTDk9OZEZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1d3411633b452e7025a5d084007543b84119f2/chunker/json_parser.go#L433)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

If m doesn't have facets, then you can save on the strings.Index search.
</blockquote></details>

Done.

**Review by manishrjain — APPROVED** [review]
:lgtm: Nice! Feel free to squash and merge.

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7171#-:-MOtjTwhEglXLRtMCfCN:bue6t5s)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @manishrjain and @vvbalaji-dgraph)

**Pull request merged**
