### PR TITLE
Count groupby/fix

### PR DESCRIPTION
**Pull request by pawanrawal**
Make changes so that `count()` and `@groupby` is rendered.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/967)

### CODE REVIEW

**Comment by sungwoncho** [comment]
:lgtm:

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/967#-:-Kkj6D8yvUl9b_YmSInf:bnfp4nl)*

**Comment by sungwoncho** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 238 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/967#-Kkj8EgL63An7FuCipaK:-Kkj8EgL63An7FuCipaL:b-rx293k) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea9aa7395ee3874c234d026855a29fdc8b102196/query/outputnode.go#L238)):*
> ```Go
> 		g.AddListChild("@groupby", uc)
> 	}
> 	n.AddListChild(fname, g)
> ```

Briefly, how does this fix the UI?

---

*[query/query.go, line 296 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/967#-Kkj8--VGo0aOEua3E6A:-Kkj8--VGo0aOEua3E6B:bacs6pb) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea9aa7395ee3874c234d026855a29fdc8b102196/query/query.go#L296)):*
> ```Go
> 	if sg.Params.GetUid {
> 		// If we are asked for count() and there are no other children,
> 		// then we dont return the uids at this level so that UI doesn't render
> ```

When users query `count()`, what will be rendred?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/967)*

**Comment by pawanrawal** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 238 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/967#-Kkj8EgL63An7FuCipaK:-Kkj8vW-3nYNVZ94tGex:bkin2h8) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea9aa7395ee3874c234d026855a29fdc8b102196/query/outputnode.go#L238)):*
<details><summary><i>Previously, sungwoncho (Sung Won Cho) wrote…</i></summary><blockquote>

Briefly, how does this fix the UI?
</blockquote></details>

ProcessGraph assumes predicates to have an array in response. This change makes `@groupby` return an array instead of an object and hence its rendered properly.

---

*[query/query.go, line 296 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/967#-Kkj8--VGo0aOEua3E6A:-Kkj91B8V8H8FMBbDJ1h:b-dfktmi) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea9aa7395ee3874c234d026855a29fdc8b102196/query/query.go#L296)):*
<details><summary><i>Previously, sungwoncho (Sung Won Cho) wrote…</i></summary><blockquote>

When users query `count()`, what will be rendred?
</blockquote></details>

A node with the count will be rendered alongside other nodes if any at that level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/967)*

**Comment by sungwoncho** [comment]
Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 238 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/967#-Kkj8EgL63An7FuCipaK:-Kkj9sf5oOtaYud0ecSc:b-9j4w7o) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea9aa7395ee3874c234d026855a29fdc8b102196/query/outputnode.go#L238)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

ProcessGraph assumes predicates to have an array in response. This change makes `@groupby` return an array instead of an object and hence its rendered properly.
</blockquote></details>

Does that mean we can never use `AddMapChild` and return object in response in order for the UI to work?

---

*[query/query.go, line 296 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/967#-Kkj8--VGo0aOEua3E6A:-KkjA7QNR9h1J38htfax:byyt9yz) ([raw file](https://github.com/dgraph-io/dgraph/blob/ea9aa7395ee3874c234d026855a29fdc8b102196/query/query.go#L296)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

A node with the count will be rendered alongside other nodes if any at that level.
</blockquote></details>

Briefly, how does not returning a UID solve the problem? From what I've seen, we simply generate and set `id` of nodes, if blank. https://github.com/dgraph-io/dgraph/blob/master/dashboard/src/containers/Helpers.js#L402

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/967)*

**Comment by pawanrawal** [comment]
Merged to release/v0.7.7

**Pull request closed without merging**
