### PR TITLE
Dgraph as library - MVP

### PR DESCRIPTION
**Pull request by tzdybal**
Following PR contains example usage of Dgraph as library/embedded client&server.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1186)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/inmemory.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1186#-Kou2NM-R8nFiX82SVf5:-Kou2NM-R8nFiX82SVf6:bxb699c) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc0a79362c7ef0d1056cfee93c370ddecde06ec/worker/inmemory.go#L41)):*
> ```Go
> }
> 
> func (i *inmemoryWorker) AssignUids(ctx context.Context, in *protos.Num,
> ```

Are these needed? These endpoints aren't called right, because this server is serving all the groups. So, no need to call Grpc methods.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1186)*

**Comment by tzdybal** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/inmemory.go, line 41 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1186#-Kou2NM-R8nFiX82SVf5:-KoyWFk0YlbTcUc75ZiK:b3c42hq) ([raw file](https://github.com/dgraph-io/dgraph/blob/adc0a79362c7ef0d1056cfee93c370ddecde06ec/worker/inmemory.go#L41)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Are these needed? These endpoints aren't called right, because this server is serving all the groups. So, no need to call Grpc methods.
</blockquote></details>

You're right. inmemoryWorker is not required at all. Removed it, and rolled back all changes related to it .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1186)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 9 of 15 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1186#-:-KozrXkeY9XoLICOhYtw:bnfp4nl)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1186#-:-KozvZwGcbPx1ZQKWQE5:bnfp4nl)*

**Comment by tzdybal** [comment]
Merged to master (09a4e50ee37aad34b318108f86241e47b001ecb3).

**Pull request closed without merging**
