### PR TITLE
fix(GraphQL): Nested Auth Rules not working properly. (#7915) (#8084)

### PR DESCRIPTION
**Pull request by anurags92**
Improves nested auth rule implementation in graphql.

(cherry picked from commit e7a19317a16214761e0db1f838ba48a0a382f0df)

Co-authored-by: minhaj-shakeel <minhaj@dgraph.io>
(cherry picked from commit 26845c431df5cc8cb3a1f0242b52a09aa4058840)

### CODE REVIEW

**Comment by mangalaman93** [comment]
@anurags92 could you add more explanation to the commit for what is going on?

**Comment by amaster507** [comment]
@mangalaman93 I have context on this, iirc, this was related to an issue I reported via DM on Discuss. Let me see if I can find you and add you to the conversation.

**Comment by mangalaman93** [comment]
That helps, thank you so much.

**Review by matthewmcneely — APPROVED** [review]

**Review by skrdgraph — APPROVED** [review]

**Comment by jdgamble555** [comment]
What is this exactly? That link is dead. is this related to https://discuss.dgraph.io/t/bug-auth-rules-of-parent-not-respected-when-child-with-hasinverse-is-added/12955

?

J

**Pull request merged**
