### PR TITLE
Modify int encoding

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/405)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-:-KZUQUirdC3_TbgM6kwP:bnfp4nl)*

**Comment by manishrjain** [comment]
Only submit once you have created a test for the sorting function.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-:-KZUQerso6XC-empLQKp:b-ad3ucy)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[types/sort_test.go, line 125 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUXNYmkQVSc4u4BJpd:-KZUXNYnIYmY7TqvI-2g:bb7i8yx) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L125)):*
> ```Go
> 
> type encL struct {
> 	intList   []int32
> ```

ints

---

*[types/sort_test.go, line 126 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUXOyqsY5QYlMrcaIt:-KZUXOyqsY5QYlMrcaIu:b-k337s1) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L126)):*
> ```Go
> type encL struct {
> 	intList   []int32
> 	tokenList []string
> ```

tokens

---

*[types/sort_test.go, line 156 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUXH26UecT3pUHBK8t:-KZUXH26UecT3pUHBK8u:bunqnhn) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L156)):*
> ```Go
> 	var toBeSorted sort.Interface
> 	toBeSorted = enc
> 	sort.Sort(toBeSorted)
> ```

sort.Sort(byInt(enc))

---

*[types/sort_test.go, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUX_Nj6DK6Ojvi-kxG:-KZUX_Nj6DK6Ojvi-kxH:bl4dbwj) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L161)):*
> ```Go
> 	for i := 1; i < len(enc.tokenList); i++ {
> 		// The corresponding string tokens should be greater.
> 		require.True(t, cur < enc.tokenList[i])
> ```

enc.tokenList[i-1] < enc.tokenList[i]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-:-KZUXfcd5aU5k6IsJDjb:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[types/sort_test.go, line 125 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUXNYmkQVSc4u4BJpd:-KZUY-w7OR1busuaiw5C:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L125)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ints
</blockquote></details>

Done.

---

*[types/sort_test.go, line 126 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUXOyqsY5QYlMrcaIt:-KZUY0NRqLO5VoliYuos:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L126)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

tokens
</blockquote></details>

Done.

---

*[types/sort_test.go, line 156 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUXH26UecT3pUHBK8t:-KZUYylIVtsa2ePD3UFZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L156)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

sort.Sort(byInt(enc))
</blockquote></details>

Done.

---

*[types/sort_test.go, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-KZUX_Nj6DK6Ojvi-kxG:-KZUYzIX6JAyFqRkf8ae:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e4a435a759e822daaabe65795f6e0a19916dc175/types/sort_test.go#L161)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

enc.tokenList[i-1] < enc.tokenList[i]
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/405)*

**Comment by jchiu0** [comment]
:lgtm:

---

Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/405#-:-KZUrv2qksnlsTOlXVlD:bnfp4nl)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
