### PR TITLE
Query attributes with empty strings.

### LINKED ISSUE #2108: Query graph with empty string values.
As per this [discussion](https://discuss.dgraph.io/t/how-do-i-query-for-an-empty-string/2198) there could be some use cases where attribute values are empty strings. Dgraph should allow querying in such cases.
 
Data
```
{
  "data": {
    "rooms": [
      {
        "name": "room 1"
      },
      {
        "name": "room 2"
      },
      {
        "name": ""
      }
    ]
  }
}
```

Query
```
{
  rooms(func: has(room)) {
    count(room @filter(eq(room, "")))
  }
}
```

### PR DESCRIPTION
**Pull request by sboorlagadda**
Accept empty strings in queries for inequality functions.

this closes #2108

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2116)

### CODE REVIEW

**Comment by sboorlagadda** [comment]
Looks like `@filter` yet to be fixed.

**Comment by sboorlagadda** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 1464 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L57bciM8eNU-IAg0xCV:-L582KaFBHtEONCrL_qf:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/84194be1c19c465596d68786a07af2200ba4eb70/gql/parser.go#L1464)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We should probably still throw error if its not inequality operation.
</blockquote></details>

Done.

---

*[worker/task.go, line 988 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L57b4Q3-sDQBC8uHrZF:-L582MjcKmWEHJytyY-j:boh4g8w) ([raw file](https://github.com/dgraph-io/dgraph/blob/7202ca21888b549c1c9b3430a47f5aa917280260/worker/task.go#L988)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Wow, was that a bug?
</blockquote></details>

Yes. matchStrings should receive only filtered uid list (as was done in previous case)> .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116)*

**Comment by sboorlagadda** [comment]
Reviewed 1 of 6 files at r3.
Review status: 1 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/query_test.go, line 6089 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L5GTIpoK7_awawMSuBT:-L5H-joPFja4Dl2uJ_w-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/269a0d923fdeef7edb79a5546a75ef655b8f981a/query/query_test.go#L6089)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

recheck if you need all these indexes?
</blockquote></details>

Done.

---

*[rdf/parse_test.go, line 587 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L5GSTBbYp5Shk3WvQE8:-L5H3CyQUb5JSc-j9Aj7:b-tbuu2x) ([raw file](https://github.com/dgraph-io/dgraph/blob/269a0d923fdeef7edb79a5546a75ef655b8f981a/rdf/parse_test.go#L587)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

what changed here?
</blockquote></details>

This is due to allowing empty string in posting/index.go.

---

*[systest/mutations_test.go, line 864 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L5GSWriVcSK6G4I_M3l:-L5H-fvNrCsDuEjRD5KQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/269a0d923fdeef7edb79a5546a75ef655b8f981a/systest/mutations_test.go#L864)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

you don't need `@count`. Its only needed for `gt(count(name), x))`.
</blockquote></details>

Done.

---

*[systest/mutations_test.go, line 896 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L5GSiEMSDqvG7w0dMi-:-L5H-gRn-v16Q6I0FRer:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/269a0d923fdeef7edb79a5546a75ef655b8f981a/systest/mutations_test.go#L896)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

no count or reverse needed. Don't need `hash` on office.
</blockquote></details>

Done.

---

*[tok/tok.go, line 275 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L5GT-KwLMr0q-vlgtDq:-L5H2m1ZMpr34XNmNpfD:bcadoup) ([raw file](https://github.com/dgraph-io/dgraph/blob/269a0d923fdeef7edb79a5546a75ef655b8f981a/tok/tok.go#L275)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

this looks like it's for `fulltext`. Do we support `eq` for fulltext?
</blockquote></details>

Good catch. Updated the condition to be `if name == "term" && str == ""`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116)*

**Comment by pawanrawal** [comment]
one more comment, then feel free to squash and merge :lgtm: 

---

Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query_test.go, line 6089 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L5GTIpoK7_awawMSuBT:-L5HDZg3pjqizmAncUUS:bcwkkdv) ([raw file](https://github.com/dgraph-io/dgraph/blob/269a0d923fdeef7edb79a5546a75ef655b8f981a/query/query_test.go#L6089)):*
<details><summary><i>Previously, sboorlagadda (Sai Boorlagadda) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Uhmm, I don't see `@count` index being used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-:-L5HE6lOmO26rgQYmcv_:b-fvq1pr)*

**Comment by sboorlagadda** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[query/query_test.go, line 6089 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-L5GTIpoK7_awawMSuBT:-L5HISBu4-cPrbCxagTH:bavth50) ([raw file](https://github.com/dgraph-io/dgraph/blob/269a0d923fdeef7edb79a5546a75ef655b8f981a/query/query_test.go#L6089)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Uhmm, I don't see `@count` index being used.
</blockquote></details>

Done. That was an oversight. Removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116)*

**Comment by sboorlagadda** [comment]
taken care of the last comment. Will be merging it.

---

Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2116#-:-L5Ho-9XCdu75aKwfw6U:bmy8ty3)*

**Pull request merged**
