### PR TITLE
Basic full text search functionality

### PR DESCRIPTION
**Pull request by tzdybal**
ICU replaced with Bleve.
Bleve used as full text search engine.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/657)

### CODE REVIEW

**Comment by joeblew99** [comment]
can you add the range terms also ? 90% of actual projects need to search by ranges as a facet. Plenty of examples on bleve.

**Comment by manishrjain** [comment]
Reviewed 91 of 96 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tok/tok.go, line 167 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWURcOXDNx_JV_j6v6:-KeWURcPCJrzrpkWZBG5:bc4gzwx) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L167)):*
> ```Go
> func (t TermTokenizer) Type() types.TypeID { return types.StringID }
> func (t TermTokenizer) Tokens(sv types.Val) ([]string, error) {
> 	tokenizer := unicode.NewUnicodeTokenizer()
> ```

Can we reuse this tokenizer? If so, maybe we can create it just once?

---

*[tok/tok.go, line 169 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWU_UlXvER_heoK6Tl:-KeWU_UlXvER_heoK6Tm:bu9irub) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L169)):*
> ```Go
> 	tokenizer := unicode.NewUnicodeTokenizer()
> 	toLowerFilter := lowercase.NewLowerCaseFilter()
> 	normalizeFilter, err := unicodenorm.NewUnicodeNormalizeFilter("nfkc")
> ```

What does nfkc mean? Add link to relevant documentation.

---

*[tok/tok.go, line 205 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWUygoM1NirqQJb6sK:-KeWUygoM1NirqQJb6sL:b-j1picw) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L205)):*
> ```Go
> func (t FullTextTokenizer) Name() string       { return "fulltext" }
> func (t FullTextTokenizer) Type() types.TypeID { return types.StringID }
> func (t FullTextTokenizer) Tokens(sv types.Val) ([]string, error) {
> ```

Which languages does this work for? Add a comment.

---

*[tok/tok.go, line 212 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWV0Sjo8lg7wfDzM9d:-KeWV0Sjo8lg7wfDzM9e:b-vqtjba) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L212)):*
> ```Go
> 		return nil, err
> 	}
> 	porterFilter := porter.NewPorterStemmer()
> ```

Also, which languages does this support? Add a comment.

---

*[tok/tok.go, line 224 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWUtsRhAtRzQVhZHmM:-KeWUtsRhAtRzQVhZHmN:b-c08g63) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L224)):*
> ```Go
> 
> 	tokenStream := analyzer.Analyze([]byte(sv.Value.(string)))
> ```

extra vertical line.

---

*[worker/tokens.go, line 13 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWVXakbLwsW4UNOZ-A:-KeWVXakbLwsW4UNOZ-B:b-an92oi) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/worker/tokens.go#L13)):*
> ```Go
> var fullTextTokenizer tok.FullTextTokenizer
> 
> func getStringTokens(funcArgs []string, funcType FuncType) ([]string, error) {
> ```

Can this be called for exact tokenizer? Should it be handled here? Add a comment.x

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/657)*

**Comment by gacharya255** [comment]
LG to replace ICU with Bleve.
LG to add FullTextTokenizer.

Just two comments.

:lgtm: 

---

Reviewed 4 of 96 files at r6, 1 of 3 files at r7.
Review status: 90 of 92 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 423 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeXrZVCimt35CK5PeyD:-KeXrZVCimt35CK5PeyE:b-mqk5b9) ([raw file](https://github.com/dgraph-io/dgraph/blob/17fa5a3ff8f17fdf4a777d3632159eb8a2b069ff/query/query_test.go#L423)):*
> ```Go
> 	query := `
> 		{
> 			friend(func:anyofterms(name, "Michonne Andrea Glenn")) {
> ```

Is there any test to demonstrate anyoftext?

---

*[tok/tok.go, line 233 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeXpxNz6EiN1Uz4iPDt:-KeXpxO-RGoFK54JTUnB:bva0t3o) ([raw file](https://github.com/dgraph-io/dgraph/blob/17fa5a3ff8f17fdf4a777d3632159eb8a2b069ff/tok/tok.go#L233)):*
> ```Go
> }
> 
> func extractTerms(tokenStream analysis.TokenStream, prefix byte) []string {
> ```

IF extractTerms is used only by getBleveTokens, we can consider merging these two functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-:-KeXrbTFOLX4IOcTMmyK:bak6f1q)*

**Comment by tzdybal** [comment]
@joeblew99 could you create an issue for the range terms, describe the functionality and provide some links? 

Quick googling shows only results about [numeric range](http://www.blevesearch.com/docs/Query/#numeric-range:8f767fbc41af8ff1ddcf4c60ed8c0fe9) and [date range](http://www.blevesearch.com/docs/Query/#date-range:8f767fbc41af8ff1ddcf4c60ed8c0fe9).

---

Review status: 88 of 93 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 423 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeXrZVCimt35CK5PeyD:-Ke_IJe81qsFZTu2Qx0u:bxe81sr) ([raw file](https://github.com/dgraph-io/dgraph/blob/17fa5a3ff8f17fdf4a777d3632159eb8a2b069ff/query/query_test.go#L423)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Is there any test to demonstrate anyoftext?
</blockquote></details>

Good point. Test added. More coming soon with next functionalities (stop words, etc). 

---

*[tok/tok.go, line 167 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWURcOXDNx_JV_j6v6:-KeWXeqCZsJIqrrjq7CR:b-ola82w) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L167)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can we reuse this tokenizer? If so, maybe we can create it just once?
</blockquote></details>

Yes, we can. Used object cache from Bleve.

---

*[tok/tok.go, line 169 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWU_UlXvER_heoK6Tl:-Ke_NJIFeA-ufRETeaMM:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L169)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What does nfkc mean? Add link to relevant documentation.
</blockquote></details>

Done.

---

*[tok/tok.go, line 205 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWUygoM1NirqQJb6sK:-Ke_gUhO11M3f8WsK47B:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L205)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Which languages does this work for? Add a comment.
</blockquote></details>

Done.

---

*[tok/tok.go, line 212 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWV0Sjo8lg7wfDzM9d:-Ke_Ofco1Q8EhtjF2Et4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L212)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Also, which languages does this support? Add a comment.
</blockquote></details>

Done.

---

*[tok/tok.go, line 224 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWUtsRhAtRzQVhZHmM:-Ke_gb7y4j2y1988yLMd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/tok/tok.go#L224)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

extra vertical line.
</blockquote></details>

Done.

---

*[tok/tok.go, line 233 at r7](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeXpxNz6EiN1Uz4iPDt:-Ke_d0Sn0YQw9carStXn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/17fa5a3ff8f17fdf4a777d3632159eb8a2b069ff/tok/tok.go#L233)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

IF extractTerms is used only by getBleveTokens, we can consider merging these two functions.
</blockquote></details>

Done.

---

*[worker/tokens.go, line 13 at r6](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeWVXakbLwsW4UNOZ-A:-Ke_g-1aN9J-BEN0t7P2:bqah9r1) ([raw file](https://github.com/dgraph-io/dgraph/blob/d1e1b63f4f6d3f1d9b450d204fae5a0b7ae0f1f0/worker/tokens.go#L13)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can this be called for exact tokenizer? Should it be handled here? Add a comment.x
</blockquote></details>

Comment added in the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-:-KeZZH7g0ejFmffYeJFr:b-qo306d)*

**Comment by manishrjain** [comment]
:lgtm: Nice work!

---

Reviewed 2 of 3 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[tok/tok.go, line 236 at r8](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-KeeycrkrtlT7gLO7NGN:-KeeycrlVPTUjeFmSSQ0:b-9bhpvc) ([raw file](https://github.com/dgraph-io/dgraph/blob/9a0a1a4c0e49f7b0a8107fda38012f69d6c0946e/tok/tok.go#L236)):*
> ```Go
> 
> func getBleveTokens(name string, identifier byte, sv types.Val) ([]string, error) {
> 	analyzer, err := bleveCache.AnalyzerNamed(name)
> ```

Ensure that bleveCache is thread-safe.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/657#-:-KeeyuFOOGwjrb7WCKwa:bcmw7ss)*

**Comment by tzdybal** [comment]
Merged to master.

**Pull request closed without merging**
