### PR TITLE
Gathering all predicates from query

### PR DESCRIPTION
**Pull request by tzdybal**
Implementation of function to gather all predicates used in a query.

This is a partial change required by subscription feature.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/957)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Does this also work with groupby directive? It should ig the getAllPredicates is called after executing the query. But won't work if it's called before.

**Comment by tzdybal** [comment]
@ashwin95r good point. Committed a change.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/957#-:-KkTOudz0-Dr3p_oxB2p:b-cl3ofj)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[query/query.go, line 2028 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/957#-KlRFdP3nUdK43KnGs15:-KlRFdP3nUdK43KnGs16:b-ys6ffu) ([raw file](https://github.com/dgraph-io/dgraph/blob/a069805ced6f56e3cab5ed8aa104d5df96244863/query/query.go#L2028)):*
> ```Go
> 		predicates[sg.Attr] = true
> 	}
> ```

Remove the vert spaces between the if blocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/957#-:-KlRG1lfIYGpsFOLoYTv:bnfp4nl)*

**Comment by tzdybal** [comment]
Merged to master (2a59cffe0e102a86bd833c43ca24b6e6c70a7102).

**Pull request closed without merging**
