### PR TITLE
Mutationsdir

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/94)

### CODE REVIEW

**Comment by pawanrawal** [comment]
This change takes care of the Panic.`filepath.Walk` resulted in a Panic if the directory didn't exist. I am checking if it exists now. 
It might be better if `Init()` method returned an error and then we could display a more meaningful error as to which directory(mutations in this case) didn't exist.
or
We could create the directory.

<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> #### Mutationsdir
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/94#-:-KIz_bOYEPmWssGSA7Hw:-417887254)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[commit/log.go, line 314 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/94#-KIznqZ5yhTi9_sAvs8d:-KIznqZ5yhTi9_sAvs8e:837999892) ([raw file](https://github.com/dgraph-io/dgraph/blob/e139bfd02236d7aa9bae0346ca4e692207df8d86/commit/log.go#L314)):*
> ```Go
> 	}
> 
> 	if _, err := os.Stat(l.dir); err != nil {
> ```

Shouldn't this be up at the top, just before going through and checking for files?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/94)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[commit/log.go, line 314 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/94#-KIznqZ5yhTi9_sAvs8d:-KJ8EjXBVK4PV5QSZf4l:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/e139bfd02236d7aa9bae0346ca4e692207df8d86/commit/log.go#L314)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Shouldn't this be up at the top, just before going through and checking for files?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/94)*

**Comment by manishrjain** [comment]
:lgtm:

<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This change takes care of the Panic.`filepath.Walk` resulted in a Panic if the directory didn't exist. I am checking if it exists now. 
> It might be better if `Init()` method returned an error and then we could display a more meaningful error as to which directory(mutations in this case) didn't exist.
> or
> We could create the directory.
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[commit/log.go, line 288 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/94#-KJ8hkIKN-ywlFvmC3zf:-KJ8hkILyGswM2csCDMW:-1657029708) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d98ddbb83fe66f6264050db9b789963dc00110e/commit/log.go#L288)):*
> ```Go
> 		if _, err := os.Stat(l.dir); err != nil {
> 			if os.IsNotExist(err) {
> 				glog.WithError(err).Fatal("Unable to find dir.")
> ```

glog.WithField("dir", l.dir).WithError(..).Fatal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/94#-:-KJ8hqphektQPfQUW4RK:1417088721)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
