### PR TITLE
Return error if user tries to reuse idx

### PR DESCRIPTION
**Pull request by pawanrawal**
Solves #2248.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2306)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

*[dgraph/cmd/zero/raft.go, line 240 at r1](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9EHRS-3eFVHjfTA_eT:-L9EHRS-3eFVHjfTA_eU:b-npoyig) ([raw file](https://github.com/dgraph-io/dgraph/blob/e050b90bfb4290a93afbffd33d01fc1799e6913d/dgraph/cmd/zero/raft.go#L240)):*
> ```Go
> 	}
> 
> 	if err := ValidateMemberId(n.server.state, pmember); err != nil {
> ```

I have added this small check here, apart from that there is nothing new in this function. It has just been moved here from applyProposal.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306)*

**Comment by janardhan1993** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---

*[dgraph/cmd/zero/raft.go, line 399 at r2](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9EMk9fD5AQ8LFRnqln:-L9EMk9fD5AQ8LFRnqlo:btcfx0l) ([raw file](https://github.com/dgraph-io/dgraph/blob/96739bceea316f84a5e66239f9a8aeaeaefdf271/dgraph/cmd/zero/raft.go#L399)):*
> ```Go
> 		m := &intern.Member{Id: rc.Id, Addr: rc.Addr, GroupId: 0}
> 		if err := ValidateMemberId(n.server.membershipState(), m); err != nil {
> 			n.DoneConfChange(cc.ID, err)
> ```

What is this for ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306)*

**Comment by manishrjain** [comment]
:lgtm: Comments.

---

Reviewed 2 of 4 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[wiki/content/contribute/index.md, line 104 at r3](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9EdnyY3a5zn4Lz_2ei:-L9EdnyY3a5zn4Lz_2ej:bb6ht2i) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f87a0d048098299b4107e34dcd64b9a5d7ee9c1/wiki/content/contribute/index.md#L104)):*
> ```Markdown
> 
>     /*
>      * Copyright 2016-2017 Dgraph Labs, Inc. and Contributors
> ```

2018

---

*[worker/groups.go, line 108 at r3](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9EeczJ1C8zS2AvGOis:-L9EeczJ1C8zS2AvGOit:b-nxtds4) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f87a0d048098299b4107e34dcd64b9a5d7ee9c1/worker/groups.go#L108)):*
> ```Go
> 		delay *= 2
> 	}
> 	x.AssertTruefNoTrace(err == nil, fmt.Sprintf("Unable to join cluster via dgraph zero: %v", err))
> ```

Use checkf

---

*[x/x.go, line 66 at r3](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9Eefhg-XReq0v0xkyi:-L9Eefhh5yecwpc-GI6z:bwhp0ap) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f87a0d048098299b4107e34dcd64b9a5d7ee9c1/x/x.go#L66)):*
> ```Go
> 	// Useful for running multiple servers on the same machine.
> 	regExpHostName    = regexp.MustCompile(ValidHostnameRegex)
> 	ErrReuseRemovedId = errors.New("Invalid idx, can't be same as that of a removed node.")
> ```

Reusing raft index of a removed node.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-:-L9Ef1zK5esOBjJ9bUp-:b9wrqbv)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-:-L9EfVKg09-4pvcnLmqG:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[wiki/content/contribute/index.md, line 104 at r3](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9EdnyY3a5zn4Lz_2ei:-L9EkIFhAHByxyZoeciD:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f87a0d048098299b4107e34dcd64b9a5d7ee9c1/wiki/content/contribute/index.md#L104)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

2018
</blockquote></details>

Done.

---

*[worker/groups.go, line 108 at r3](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9EeczJ1C8zS2AvGOis:-L9EkHWYBgLH86gdGxd9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f87a0d048098299b4107e34dcd64b9a5d7ee9c1/worker/groups.go#L108)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Use checkf
</blockquote></details>

Done.

---

*[x/x.go, line 66 at r3](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306#-L9Eefhg-XReq0v0xkyi:-L9EkGjj6do060SXm_Be:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/7f87a0d048098299b4107e34dcd64b9a5d7ee9c1/x/x.go#L66)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Reusing raft index of a removed node.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/dgraph-io/dgraph/2306)*

**Comment by pawanrawal** [comment]
Merged to master with 2bfa4bbd139fa7fac10d612e32f61f3d2c05ba28.

**Pull request closed without merging**
