### PR TITLE
Introduce geo filters and generators and fix tests.

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/319)

### CODE REVIEW

**Comment by jchiu0** [comment]
Nothing major. Changes here seem fine. Will LGTM in the next round. Thanks Ashwin.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/schema_scalar, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeaEGxF52aDPrZ3xER:-KWeaEGxF52aDPrZ3xES:b-ulaiq6) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/cmd/dgraph/schema_scalar#L5)):*
> ```
>   age: int @index
>   health: float @index
> 	name: string @index
> ```

Fix indent.

---

*[query/generator.go, line 61 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWebzVr7pkdrKzAUFfP:-KWebzVr7pkdrKzAUFfQ:b-1egsym) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L61)):*
> ```Go
> 	maxD, err := strconv.ParseFloat(dist, 64)
> 	if err != nil {
> 		return nil, err
> ```

Can add x.Wrap on errors coming from external libs.

---

*[query/generator.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWedTEV9QQUPGG3Emci:-KWedTEWGEnK96-X9nmJ:b-61xwyx) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L64)):*
> ```Go
> 	}
> 	var g types.Geo
> 	geoD := strings.Replace(point, "'", "\"", -1)
> ```

geoD: what does D stand for here? Seems like just a point?

---

*[query/generator.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWec61TSYlVoGDeXpkc:-KWec61TSYlVoGDeXpkd:bbaj3z0) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L71)):*
> ```Go
> 	gb, err := g.MarshalBinary()
> 	if err != nil {
> 		return nil, err
> ```

x.Wrap (same for the other lines below)

---

*[query/geo.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWec_FvRMZYdUsMLKjK:-KWec_FvRMZYdUsMLKjL:b-is39bp) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/geo.go#L30)):*
> ```Go
> )
> 
> func filterGeo(ctx context.Context, attr string, qt geo.QueryType, g []byte,
> ```

Can add some comments above filterGeo? I think it is good to know what "g" is for example. And for maxDist, could mention that if zero, it just means restricted to cell pointing point or something.

---

*[query/geo_test.go, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWedvI05Pp891jXYSGG:-KWedvI05Pp891jXYSGH:b-v0q4ze) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/geo_test.go#L119)):*
> ```Go
> 	gq := &gql.GraphQuery{
> 		Attr:     "me",
> 		Gen:      &gql.Generator{FuncName: "near", FuncArgs: []string{"geometry", "{\"Type\":\"Point\", \"Coordinates\":[-122.082506, 37.4249518]}", "1"}},
> ```

Back tilde for raw strings. Same for the other test cases below. Thanks.

---

*[query/geo_test.go, line 173 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeO8PfAFg7aE_ybUN:-KWeeO8PfAFg7aE_ybUO:bb6w042) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/geo_test.go#L173)):*
> ```Go
> 	require.Equal(t, 2, len(mp.([]interface{})))
> 	require.Contains(t, expected,
> 		mp.([]interface{})[0].(map[string]interface{})["me"].([]interface{})[0].(map[string]interface{})["name"].(string))
> ```

Could consider using require.JSONEq.

---

*[query/query.go, line 715 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeZr6FNuyroNU8auF:-KWeeZr6FNuyroNU8auG:byfor2e) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query.go#L715)):*
> ```Go
> 	} else {
> 		sg.SrcUIDs = algo.NewUIDList([]uint64{euid})
> 		{
> ```

Actually can remove this extra { } now.

---

*[query/query.go, line 1011 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeee2rtPUsWv9t7f1N:-KWeee2rtPUsWv9t7f1O:bl8eqfu) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query.go#L1011)):*
> ```Go
> 		case "near":
> 			if len(gen.FuncArgs) != 3 {
> 				return nil, fmt.Errorf("near generator requires 3 arguments")
> ```

x.Errorf. Same for the other lines below in this function.

---

*[query/query.go, line 1088 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeek16iRsQhKuSD9XU:-KWeek16iRsQhKuSD9XV:bdrcm2h) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query.go#L1088)):*
> ```Go
> 			return intersects(ctx, destUIDs, filter.FuncArgs[0], filter.FuncArgs[1])
> 		default:
> 			return nil, fmt.Errorf("Invalid filter")
> ```

x.Errorf

---

*[query/query_test.go, line 161 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeoi0gJyK6fSaW8kG:-KWeeoi0gJyK6fSaW8kH:b-h7armh) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query_test.go#L161)):*
> ```Go
> 	addEdgeToValue(t, ps, "gender", 1, "female")
> 	var coord types.Geo
> 	err = coord.UnmarshalText([]byte("{\"Type\":\"Point\", \"Coordinates\":[1.1,2.0]}"))
> ```

Backtildes..

---

*[query/query_test.go, line 1558 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeu6C8jPy0KV5opf8:-KWeeu6C8jPy0KV5opf9:b-p7p0qp) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query_test.go#L1558)):*
> ```Go
> 	js, err := sg.ToJSON(&l)
> 	require.NoError(t, err)
> 	require.EqualValues(t, `{"me":[{"gender":"female","name":"Michonne"}]}`, string(js))
> ```

Yeah, let's switch to jsonEq as it will make the test less fragile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-:-KWef-KRuXp5LPr8H1Fn:b-d8lwo2)*

**Comment by ashwin95r** [comment]
Review status: 1 of 4 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[query/generator.go, line 61 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWebzVr7pkdrKzAUFfP:-KWkq8s8YVovflBxn-P1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L61)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Can add x.Wrap on errors coming from external libs.
</details>
Done.

---

*[query/generator.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWedTEV9QQUPGG3Emci:-KWgr7Ex00C-l57BbYVW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L64)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> geoD: what does D stand for here? Seems like just a point?
</details>
Done.

---

*[query/generator.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWec61TSYlVoGDeXpkc:-KWkqYuWgqgiUNV6vCd3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L71)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> x.Wrap (same for the other lines below)
</details>
Done.

---

*[query/geo_test.go, line 119 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWedvI05Pp891jXYSGG:-KWlChHPBw_AG9axF10K:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/geo_test.go#L119)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Back tilde for raw strings. Same for the other test cases below. Thanks.
</details>
Done.

---

*[query/query.go, line 715 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeZr6FNuyroNU8auF:-KWgrDyBEkE4KWFLt6bS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query.go#L715)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Actually can remove this extra { } now.
</details>
Done.

---

*[query/query.go, line 1011 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeee2rtPUsWv9t7f1N:-KWlAqTsVgG4BkuutiFq:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query.go#L1011)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> x.Errorf. Same for the other lines below in this function.
</details>
Done.

---

*[query/query.go, line 1088 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeek16iRsQhKuSD9XU:-KWlAr0-GubWanKv8SnO:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query.go#L1088)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> x.Errorf
</details>
Done.

---

*[cmd/dgraph/schema_scalar, line 5 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeaEGxF52aDPrZ3xER:-KWgpX77OhYW36zR5rh3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/cmd/dgraph/schema_scalar#L5)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Fix indent.
</details>
Done.

---

*[query/query_test.go, line 161 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeoi0gJyK6fSaW8kG:-KWlCj3SffJFWNWIEf8z:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query_test.go#L161)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Backtildes..
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/319)*

**Comment by jchiu0** [comment]
Maybe you forgot to push? Some of the changes seem to be missing.

---

Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/generator.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWedTEV9QQUPGG3Emci:-KWouh68JSDKlxFos_cr:b-dd7kyz) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L64)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Done.
</details>
Don't see any change here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-:-KWouu472XSQYHExVaj7:b-pogabo)*

**Comment by ashwin95r** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/generator.go, line 64 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWedTEV9QQUPGG3Emci:-KWpR4kIxA8_Ju2lElRJ:bx82st8) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/generator.go#L64)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Don't see any change here?
</details>
Sorry, Didn't push.

---

*[query/geo.go, line 30 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWec_FvRMZYdUsMLKjK:-KWpQ_ykzpEldE0HDEfp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/geo.go#L30)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Can add some comments above filterGeo? I think it is good to know what "g" is for example. And for maxDist, could mention that if zero, it just means restricted to cell pointing point or something.
</details>
Done.

---

*[query/geo_test.go, line 173 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeO8PfAFg7aE_ybUN:-KWpQdOJV4ivaoqqXeBf:bbwn9il) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/geo_test.go#L173)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Could consider using require.JSONEq.
</details>
Actually, after the preTravese change, we allow only one root. So these tests will break. Will wait till I introduce Muti-root support and fix these at that time.

---

*[query/query_test.go, line 1558 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/319#-KWeeu6C8jPy0KV5opf8:-KWpR-5fH_8wfTlKo0F3:bjcq0i9) ([raw file](https://github.com/dgraph-io/dgraph/blob/604910f5c1bc32f5427e2525b044f44dbab59c54/query/query_test.go#L1558)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Yeah, let's switch to jsonEq as it will make the test less fragile.
</details>
Same, will fix along with multi-root change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/319)*

**Comment by ashwin95r** [comment]
Handled in #335.

**Pull request closed without merging**
