### PR TITLE
Var => uid/val

### PR DESCRIPTION
**Pull request by pawanrawal**
Change `var(x)` to `uid(x)` || `val(x)`.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1110)

### CODE REVIEW

**Comment by manishrjain** [comment]
one small comment. :lgtm_strong: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/query.go, line 1592 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAZzWxM2rHoxRuwOfu:-KoAZzWxM2rHoxRuwOfv:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/query/query.go#L1592)):*
> ```Go
> 		filterChan := make(chan error, len(sg.Filters))
> 		for _, filter := range sg.Filters {
> 			isUidFunc := len(filter.SrcFunc) > 0 && filter.SrcFunc[0] == "uid" && len(filter.Params.NeedsVar) == 0
> ```

100 chars.

---

*[rdf/state.go, line 143 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoA_4kzWlgkY1zcLRjn:-KoA_4kzWlgkY1zcLRjo:b-w32g4y) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/rdf/state.go#L143)):*
> ```Go
> 		case r == 'u':
> 			if l.Depth != atSubject && l.Depth != atObject {
> 				return l.Errorf("Unexpected char 'v'")
> ```

unexpected char u, not v.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-:-KoA_8pYyyruQIhSFdGl:b-d5ijqx)*

**Comment by ashwin95r** [comment]
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/dgraph/main_test.go, line 1146 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAx035JKQO4RA02G9m:-KoAx035JKQO4RA02G9n:ba0b09i) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/cmd/dgraph/main_test.go#L1146)):*
> ```Go
>                 <0x600>    <friend>   <0x502> .
>                 <0x600>    <friend>   <0x503> .
> 				<0x600>    <likes>    uid(myfriend) .
> ```

We can add a test case where we use val() instead of uid() in mutations

---

*[gql/parser.go, line 1904 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAxF71YN6rGQ30kCFO:-KoAxF71YN6rGQ30kCFP:b-m3cw6r) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/gql/parser.go#L1904)):*
> ```Go
> 	}
> 	item := it.Item()
> 	if item.Val == "uid" {
> ```

"uid" -> UID?

---

*[gql/parser_test.go, line 550 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAxWj0lBWpvZ4Bd0r5:-KoAxWj0lBWpvZ4Bd0r6:b-b7jjf1) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/gql/parser_test.go#L550)):*
> ```Go
> 	query := `
> 	{
> 		me(id: uid(L), orderasc: val(n) ) {
> ```

A test case to check what happens if we flip the val with uid and vice versa?  We only check for the right behaviour here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110)*

**Comment by pawanrawal** [comment]
Review status: 3 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/dgraph/main_test.go, line 1146 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAx035JKQO4RA02G9m:-KoB-PdxVz5Kp1Vz4nZj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/cmd/dgraph/main_test.go#L1146)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We can add a test case where we use val() instead of uid() in mutations
</blockquote></details>

Done.

---

*[gql/parser.go, line 1904 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAxF71YN6rGQ30kCFO:-KoB-X_-KsAo__CsiDh3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/gql/parser.go#L1904)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

"uid" -> UID?
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 550 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAxWj0lBWpvZ4Bd0r5:-KoB34IOQ2WK9zoqafMS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/gql/parser_test.go#L550)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

A test case to check what happens if we flip the val with uid and vice versa?  We only check for the right behaviour here.
</blockquote></details>

Done.

---

*[query/query.go, line 1592 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoAZzWxM2rHoxRuwOfu:-KoB35vgJYVDr3gPt3y4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/query/query.go#L1592)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[rdf/state.go, line 143 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoA_4kzWlgkY1zcLRjn:-KoB35LJ6UByukc0sxIG:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/28a0dc82f99f375de3a031d239f969d64aec5862/rdf/state.go#L143)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

unexpected char u, not v.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110)*

**Comment by ashwin95r** [comment]
Review status: 3 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/dgraph/main_test.go, line 1184 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoB3vmrIV0qLjOE0Ibl:-KoB3vmrIV0qLjOE0Ibm:bn1jx8n) ([raw file](https://github.com/dgraph-io/dgraph/blob/5df1b43ead108ccc4248bf94c53f19d9c13b6faf/cmd/dgraph/main_test.go#L1184)):*
> ```Go
>                 <0x600>    <friend>   <0x502> .
>                 <0x600>    <friend>   <0x503> .
> 				<0x600>    <likes>    var(myfriend) .
> ```

s/var/val?

---

*[gql/parser.go, line 2078 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoB6C6GOoYdYbqVDMgx:-KoB6C6HpOmZUMOUJNWH:b-hc08cu) ([raw file](https://github.com/dgraph-io/dgraph/blob/5df1b43ead108ccc4248bf94c53f19d9c13b6faf/gql/parser.go#L2078)):*
> ```Go
> 				}
> 				// Modify the NeedsVar context here.
> 				gq.NeedsVar[len(gq.NeedsVar)-1].Typ = VALUE_VAR
> ```

This should be set based on VALUE or UID. And then while executing we should make sure of the context I think. Should parsing treat val and uid the same way?

---

*[gql/parser.go, line 2084 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoB5qo6sE09UDWZxsxl:-KoB5qo6sE09UDWZxsxm:b-l5ljdo) ([raw file](https://github.com/dgraph-io/dgraph/blob/5df1b43ead108ccc4248bf94c53f19d9c13b6faf/gql/parser.go#L2084)):*
> ```Go
> 				items, err := it.Peek(1)
> 				if err == nil && items[0].Typ == itemLeftRound {
> 					if (key == "orderasc" || key == "orderdesc") && val != "val" {
> ```

"val" -> VALUE

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110)*

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 3 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-:-KoBAYWH5KqaPndnapiE:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/dgraph/main_test.go, line 1184 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoB3vmrIV0qLjOE0Ibl:-KoBApCQoNJ7r2goAN--:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5df1b43ead108ccc4248bf94c53f19d9c13b6faf/cmd/dgraph/main_test.go#L1184)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

s/var/val?
</blockquote></details>

Done.

---

*[gql/parser.go, line 2078 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoB6C6GOoYdYbqVDMgx:-KoBBg4rEcb3rGTjME0F:bikwo6e) ([raw file](https://github.com/dgraph-io/dgraph/blob/5df1b43ead108ccc4248bf94c53f19d9c13b6faf/gql/parser.go#L2078)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

This should be set based on VALUE or UID. And then while executing we should make sure of the context I think. Should parsing treat val and uid the same way?
</blockquote></details>

Yeah, the if has a check item.val == VALUE

---

*[gql/parser.go, line 2084 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoB5qo6sE09UDWZxsxl:-KoBBjfzQ9_fOOJZADfd:bb6un1j) ([raw file](https://github.com/dgraph-io/dgraph/blob/5df1b43ead108ccc4248bf94c53f19d9c13b6faf/gql/parser.go#L2084)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

"val" -> VALUE
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[gql/parser.go, line 2078 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110#-KoB6C6GOoYdYbqVDMgx:-KoBC_ndiEv_Iit3VxzC:b7qq2yo) ([raw file](https://github.com/dgraph-io/dgraph/blob/5df1b43ead108ccc4248bf94c53f19d9c13b6faf/gql/parser.go#L2078)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Yeah, the if has a check item.val == VALUE
</blockquote></details>

We check the context in parser so I dont think we should check it again in query"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1110)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
