### PR TITLE
Initial commit to use badger instead of RocksDB

### PR DESCRIPTION
**Pull request by gacharya255**
Not committing until we are more sure and do more tests. Just sending out for review first.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/932)

### CODE REVIEW

**Comment by ashwin95r** [comment]
On loading golden data, killing and restarting the server, I'm seeing this error:
```
2017/05/12 17:47:37 error.go:75: Arena too small, toWrite:72879 newTotal:77667241 limit:77594624
github.com/dgraph-io/badger/y.Errorf
	/home/ashwin/go/src/github.com/dgraph-io/badger/y/error.go:103
github.com/dgraph-io/badger/y.AssertTruef
	/home/ashwin/go/src/github.com/dgraph-io/badger/y/error.go:75
github.com/dgraph-io/badger/skl.(*Arena).PutVal
	/home/ashwin/go/src/github.com/dgraph-io/badger/skl/arena.go:41
github.com/dgraph-io/badger/skl.newNode
	/home/ashwin/go/src/github.com/dgraph-io/badger/skl/skl.go:122
github.com/dgraph-io/badger/skl.(*Skiplist).Put
	/home/ashwin/go/src/github.com/dgraph-io/badger/skl/skl.go:306
github.com/dgraph-io/badger/badger.NewKV.func1
	/home/ashwin/go/src/github.com/dgraph-io/badger/badger/kv.go:174
github.com/dgraph-io/badger/badger.(*logFile).iterate
	/home/ashwin/go/src/github.com/dgraph-io/badger/badger/value.go:170
github.com/dgraph-io/badger/badger.(*valueLog).Replay
	/home/ashwin/go/src/github.com/dgraph-io/badger/badger/value.go:512
github.com/dgraph-io/badger/badger.NewKV
	/home/ashwin/go/src/github.com/dgraph-io/badger/badger/kv.go:177
github.com/dgraph-io/dgraph/worker.StartRaftNodes
	/home/ashwin/go/src/github.com/dgraph-io/dgraph/worker/groups.go:127
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2197
```

**Comment by manishrjain** [comment]
Change looks good. Let's keep this in a branch until we have ironed out all the issues.

We'll push this out to our demo, and play etc., so it would live tested. Also, I'll try loading the entire Freebase dataset with this branch; and launch freebase.dgraph.io. That should also help test this thing.

---

Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/backup.go, line 258 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/932#-Kjy3nW0q0o9Yje6veKk:-Kjy3nW1nMQBXTwQ7YMJ:b-8pb7hp) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1ae17da5b4f77c646ce8a9c6e04dbf18c058e0/worker/backup.go#L258)):*
> ```Go
> 		if pk.IsIndex() {
> 			// Seek to the end of index keys.
> 			it = pstore.NewIterator(badger.DefaultIteratorOptions) // TODO: Remove this.
> ```

why can't we just do it.Seek? Why did you create another iterator?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/932#-:-Kjy5wSSx9J1KaaXZtfI:b-ciwjg5)*

**Comment by pawanrawal** [comment]
Review status: 32 of 1335 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[worker/backup.go, line 258 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/932#-Kjy3nW0q0o9Yje6veKk:-KkmVkvvhUXs2P3huz_s:btxe8ex) ([raw file](https://github.com/dgraph-io/dgraph/blob/0d1ae17da5b4f77c646ce8a9c6e04dbf18c058e0/worker/backup.go#L258)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

why can't we just do it.Seek? Why did you create another iterator?
</blockquote></details>

We do it now, I suppose the hack was put in place because of the bug in it.Seek

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/932)*

**Comment by pawanrawal** [comment]
Merged to master

**Pull request closed without merging**
