### PR TITLE
Don't return filtered UIDs. Return error on `0` UID

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/720)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/720#-:-KferJRI-lnNPQIfQent:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[query/outputnode.go, line 188 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/720#-KfiFPP-yJSW2oxy-4GN:-KfiFPP0uuWSzM_CsTZW:bps6eij) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b971e4830e530ef55d9006603870d374b6b2ead/query/outputnode.go#L188)):*
> ```Go
> 	for _, uid := range sg.uidMatrix[0].Uids {
> 		// For the root, the name is stored in Alias, not Attr.
> 		if algo.IndexOf(sg.DestUIDs, uid) < 0 {
> ```

Won't it be better to remove these in processGraph, if we don't remove them there then their children would also be evaluated, no?

I am not sure about the code that does filtering hence, curious. Could we isolate this in a test case?

---

*[rdf/parse.go, line 49 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/720#-KfiF5-g-2mSkOHW5bmP:-KfiF5-hVta9EO6YVqtC:bsk76fh) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b971e4830e530ef55d9006603870d374b6b2ead/rdf/parse.go#L49)):*
> ```Go
> 		return farm.Fingerprint64([]byte(xid)), nil
> 	}
> 	if uid == 0 {
> ```

How about adding a test case and verifying the error?
`<    0> <name> "Alice" .`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/720)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 188 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/720#-KfiFPP-yJSW2oxy-4GN:-KfiGCttm2sHBiSH-bim:b-5o9c7y) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b971e4830e530ef55d9006603870d374b6b2ead/query/outputnode.go#L188)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Won't it be better to remove these in processGraph, if we don't remove them there then their children would also be evaluated, no?

I am not sure about the code that does filtering hence, curious. Could we isolate this in a test case?
</blockquote></details>

No, we wouldn't evaluate the children as it'd be filtered in the DestUids.

---

*[rdf/parse.go, line 49 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/720#-KfiF5-g-2mSkOHW5bmP:-KfiGUh0ur_yATdY7zwh:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b971e4830e530ef55d9006603870d374b6b2ead/rdf/parse.go#L49)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

How about adding a test case and verifying the error?
`<    0> <name> "Alice" .`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/720)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 188 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/720#-KfiFPP-yJSW2oxy-4GN:-KfiMSu1BTEjPS-BXDm3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/0b971e4830e530ef55d9006603870d374b6b2ead/query/outputnode.go#L188)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

No, we wouldn't evaluate the children as it'd be filtered in the DestUids.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/720)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
