### PR TITLE
Fix race condition in IsPeer.

### PR DESCRIPTION
**Pull request by martinmr**
IsPeer is unsafely accessing the _confstate field. This PR fixes this
race condition as well as making the node field in Raft unexported and
providing a safe method to update it.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/3432)

### CODE REVIEW

**Comment by mangalaman93** [comment]
@martinmr let me know when you want me to run flock on this change.
Related to #3411

**Comment by mangalaman93** [comment]
Flock is running but I can't reliably reproduce this on master. Let me know if you have ideas around how to reproduce it.

**Comment by martinmr** [comment]
No ideas but I think it's clear that the reads and writes on the confstate were not lock-protected so the race condition should be gone. I'll let Manish decide.

**Comment by mangalaman93** [comment]
Makes sense, as long as PR logically looks good, should merge it. We will run more tests and keep an eye.

**Pull request merged**
