### PR TITLE
disallow count(), use count(uid) instead

### PR DESCRIPTION
**Pull request by janardhan1993**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1762)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Add a test case from the groupby json.Marshal error we were seeing.
Also fix docs for count at root.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-:-KymvvML1rnNurTMK5Bn:bficlqu)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[gql/parser.go, line 2477 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-KymxysyGk7I4D3QzLvh:-KymxysyGk7I4D3QzLvi:b-b5fu6p) ([raw file](https://github.com/dgraph-io/dgraph/blob/07ae43ee6d15aa8cc6924688f22d34b0e6b4e3d4/gql/parser.go#L2477)):*
> ```Go
> 						val = uid
> 						// Skip uid)
> 						it.Next()
> ```

We should check this, and return error otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-:-Kymy4BUFkq_8ZkJVJ5P:bnfp4nl)*

**Comment by janardhan1993** [comment]
That test case would fail at parse level itself now.

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[gql/parser.go, line 2477 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-KymxysyGk7I4D3QzLvh:-KynYP_zXPUzvKas4CHR:b7zgow6) ([raw file](https://github.com/dgraph-io/dgraph/blob/07ae43ee6d15aa8cc6924688f22d34b0e6b4e3d4/gql/parser.go#L2477)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We should check this, and return error otherwise.
</blockquote></details>

This is already tested in the if loop above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-:-KynYS5xoqOdxRiIJhSj:bus4jn0)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 375 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-KynbhxYmL9Gyv8tX5BB:-KynbhxZU38FVomYeVTT:bsvn0hg) ([raw file](https://github.com/dgraph-io/dgraph/blob/d97f57a4972b28a359bfedfae46cf92dbe7f1321/query/outputnode.go#L375)):*
> ```Go
> func (n *fastJsonNode) addGroupby(sg *SubGraph, fname string) {
> 	// Don't add empty groupby
> 	if len(sg.GroupbyRes.group) == 0 {
> ```

I suppose https://discuss.dgraph.io/t/error-dgraph-groupby-query-while-returning-zero-results/1950/2 doesn't return errors anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-:-Kynbs8YU42y-ZhDXURT:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[query/outputnode.go, line 375 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762#-KynbhxYmL9Gyv8tX5BB:-KynlM0B34DCtSsDsExX:b7t85yt) ([raw file](https://github.com/dgraph-io/dgraph/blob/d97f57a4972b28a359bfedfae46cf92dbe7f1321/query/outputnode.go#L375)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I suppose https://discuss.dgraph.io/t/error-dgraph-groupby-query-while-returning-zero-results/1950/2 doesn't return errors anymore?
</blockquote></details>

Yeah, no error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1762)*

**Pull request closed without merging**
