### PR TITLE
feat(Monitoring): Adding Monitoring for Disk Space and Number of Backups

### PR DESCRIPTION
**Pull request by gja**
---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7404)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7404)* status: all files reviewed, 3 unresolved discussions (waiting on @gja, @manishrjain, and @vvbalaji-dgraph)

___
*[x/disk_metrics_others.go, line 12 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyUlaj-6qtqgiYJdAj:-MSyUlak-DvsyC-xx-r7:b-la9b3u) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/disk_metrics_others.go#L12)):*
> ```
> "File System Metrics are not currently supported on non-linux platforms"
> ```

> File system metrics are not currently supported on non-Linux platforms

Suggestion: change the capitalization.
___
*[x/metrics.go, line 66 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyTv8i-Kv-FGAwv3Gx:-MSyTv8jCLFEiRKfe-yi:b-m1zh95) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/metrics.go#L66)):*
> ```
> 	// NumBackupsSuccess is the number of backups successfully completed
> 	NumBackupsSuccess = stats.Int64("num_backups_success",
> 		"Total number of backups completed", stats.UnitDimensionless)
> ```
We should add a metric for backup failures too so we can set up alerts for when backups fail. It can happen for whatever reason (context timeouts, EOF errors). Backup failures can't be caught on the client-side if the backup request takes too long, causing the client request to timeout while the backup is still pending on the Dgraph side.
___
*[x/metrics.go, line 440 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyUN59DS6YTh_cxGL7:-MSyUN59DS6YTh_cxGL8:b-odqfvn) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/metrics.go#L440)):*
> ```Go
> 	// Exposing metrics at /metrics, which is the usual standard, as well as at the old endpoint
> 	http.Handle("/metrics", pe)
> 	http.Handle("/debug/prometheus_metrics", pe)
> ```

Should `/debug/prometheus_metrics` be a 301 redirect to `/metrics`? Would a redirect still work for existing Prometheus configs that refer to `/debug/prometheus_metrics`?

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7404)* status: all files reviewed, 4 unresolved discussions (waiting on @gja, @manishrjain, and @vvbalaji-dgraph)

___
*[x/metrics.go, line 66 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyXCEF2vpUWe7U3Xfl:-MSyXCEF2vpUWe7U3Xfm:b-ofb8lh) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/metrics.go#L66)):*
> ```Go
> 		"Total number of backups requested", stats.UnitDimensionless)
> 	// NumBackupsSuccess is the number of backups successfully completed
> 	NumBackupsSuccess = stats.Int64("num_backups_success",
> ```

The suffix for this metric should be `_total` to follow [Prometheus's naming convention](https://prometheus.io/docs/practices/naming/).

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7404)* status: all files reviewed, 10 unresolved discussions (waiting on @gja, @manishrjain, and @vvbalaji-dgraph)

___
*[dgraph/cmd/zero/run.go, line 346 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyXw_V9dmI-y_jhqKt:-MSyXw_W1ZDNeoyR-acS:b2yf5mk) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/dgraph/cmd/zero/run.go#L346)):*
> ```
> zero_wal_dir
> ```
We can call this `wal`. It's already known to be Zero's wal directory since this metric is coming from Zero.
___
*[worker/server_state.go, line 136 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyY6in7NqadDDGAeVh:-MSyY6in7NqadDDGAeVi:b5nfq0s) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/worker/server_state.go#L136)):*
> ```Go
> 	// Commenting this out because Badger is doing its own cache checks.
> 	go x.MonitorCacheHealth(s.Pstore, s.gcCloser)
> 	go x.MonitorDiskMetrics("posting_dir", Config.PostingDir, s.gcCloser)
> ```

`posting_dir` can be renamed to `postings`. This follows the long-form flag name for setting the p directory ("postings").
___
*[x/metrics.go, line 96 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyXQnPALOAnHXj8mFa:-MSyXQnPALOAnHXj8mFb:buoxjne) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/metrics.go#L96)):*
> ```
> disk_free
> ```
This should be called `disk_free_bytes`
___
*[x/metrics.go, line 99 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyXSCeBeejwdXnrqOL:-MSyXSCeBeejwdXnrqOM:bsp3gey) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/metrics.go#L99)):*
> ```
> disk_used
> ```
This should be called `disk_used_bytes`
___
*[x/metrics.go, line 102 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyXTn70yGRO-s4UN9x:-MSyXTn8ACP0X-HE7EF9:buqa2ec) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/metrics.go#L102)):*
> ```
> disk_total
> ```
This should be called `disk_bytes_total`
___
*[x/metrics.go, line 163 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyYIcC9r8OUIi9rl4u:-MSyYIcC9r8OUIi9rl4v:b-w96zey) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/x/metrics.go#L163)):*
> ```
> dir_type
> ```
This can be `dir`. This is the same naming scheme used in Badger metrics. e.g., https://github.com/dgraph-io/dgraph/blob/d79d3797bf90d9bb5a57b434a741302962ea5d84/x/metrics.go#L424-L428

**Review by manishrjain — APPROVED** [review]
:lgtm: Defer to @danielmai for final approval.

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-:-MT1WG67CJOtEeiBy67o:b-yeuv14)* status: all files reviewed, 10 unresolved discussions (waiting on @danielmai, @gja, and @vvbalaji-dgraph)

___
*[worker/server_state.go, line 136 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7404#-MSyY6in7NqadDDGAeVh:-MT1W-hfCh9XSpINeCxR:bgubd92) ([raw file](https://github.com/dgraph-io/dgraph/blob/265bdcacec4c289ad5357899b14cb2389b9e4ce7/worker/server_state.go#L136)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

`posting_dir` can be renamed to `postings`. This follows the long-form flag name for setting the p directory ("postings").
</blockquote></details>

`postings-fs` so it's clear it's at a filesystem level.

**Pull request merged**
