### PR TITLE
Simplify schema and types

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/412)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm: Address the small comments, before submitting. Also, wait for Jiawei to review.

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cmd/dgraph/main.go, line 377 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZX0aJg2JkbxWX6Zjm:-KZZX0aJg2JkbxWX6Zjn:ba3dfmt) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/cmd/dgraph/main.go#L377)):*
> ```Go
> 				src := types.ValueForType(typeID)
> 				src.Value = nquad.ObjectValue
> 				fmt.Println("****")
> ```

Remove.

---

*[cmd/dgraph/test_schema, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZX6ALDsRNl27thn2x:-KZZX6AMs_79GMl2ia8e:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/cmd/dgraph/test_schema#L1)):*
> ```
> type person {
> ```

Remove this.

---

*[query/query.go, line 282 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZXCX7W5_qXaD40vHc:-KZZXCX8lIJoZqiIBKbB:b-vfv9q2) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/query/query.go#L282)):*
> ```Go
> 				// schemaType refers to the type we should convert the value
> 				// compulsorily and if not possible we ignore the parent object
> 				// as it wouldn't comply with the schema.
> ```

Remove comment.

---

*[query/query_test.go, line 1825 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZXqmXKQnWiKWrsp-h:-KZZXqmXKQnWiKWrsp-i:b-92wdn1) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/query/query_test.go#L1825)):*
> ```Go
> 				alive
> 				survival_rate
> 				friend
> ```

Add the fields inside friend block.

---

*[types/scalar_types.go, line 93 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZYH31GlPg41EJ7KsI:-KZZYH31GlPg41EJ7KsJ:bhpok66) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/types/scalar_types.go#L93)):*
> ```Go
> }
> 
> func (t TypeID) IsScalar() bool {
> ```

return t != UidID

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-:-KZZZ-SGvhmqYtVNH2kA:b8niepr)*

**Comment by jchiu0** [comment]
:lgtm: Love the simplification here.

---

Review status: 9 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[schema/schema.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZeiJvLUnaVoRX-F4E:-KZZeiJvLUnaVoRX-F4F:b-dwpgdz) ([raw file](https://github.com/dgraph-io/dgraph/blob/46a0c31f8fad342b74bcaa860a11f1e1a6139251/schema/schema.go#L54)):*
> ```Go
> 		return typ, nil
> 	}
> 	return types.TypeID(100), x.Errorf("Undefined predicate")
> ```

Can't just use nil to indicate no type? (can also return one less var) IsScalar can return x!=nil && x!=uidType.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-:-KZZfO2Urp8p4_SLZKbN:b-g8pfmx)*

**Comment by ashwin95r** [comment]
Thanks for the review!

---

Review status: 9 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/dgraph/main.go, line 377 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZX0aJg2JkbxWX6Zjm:-KZZZfe7CWdOgRF6gtI-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/cmd/dgraph/main.go#L377)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---

*[query/query.go, line 282 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZXCX7W5_qXaD40vHc:-KZZ_1ZjyhLo3wnF-JKS:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/query/query.go#L282)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove comment.
</blockquote></details>

Done.

---

*[query/query_test.go, line 1825 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZXqmXKQnWiKWrsp-h:-KZZ_rxolaRPv1HDA_Ew:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/query/query_test.go#L1825)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add the fields inside friend block.
</blockquote></details>

Done.

---

*[schema/schema.go, line 54 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZeiJvLUnaVoRX-F4E:-KZZg5_-5Ae4WrF4Vfty:b13sh46) ([raw file](https://github.com/dgraph-io/dgraph/blob/46a0c31f8fad342b74bcaa860a11f1e1a6139251/schema/schema.go#L54)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Can't just use nil to indicate no type? (can also return one less var) IsScalar can return x!=nil && x!=uidType.
</blockquote></details>

types.TypeID can't be nil, hence returning an error as well.

---

*[types/scalar_types.go, line 93 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZYH31GlPg41EJ7KsI:-KZZ_z34nbNHXU8_nT6O:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/types/scalar_types.go#L93)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return t != UidID
</blockquote></details>

Done.

---

*[cmd/dgraph/test_schema, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-KZZX6ALDsRNl27thn2x:-KZZaXXCy1gb-jFEY5pd:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5f64ed06fdcbd825398f3addf220abc73d4ed586/cmd/dgraph/test_schema#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/412#-:-KZZgAedXonk5ke3w9Ap:b-9qdoz3)*

**Comment by ashwin95r** [comment]
Merged 6df77e5eb3275f0a02f0a4f251b6e802c552432b.

**Pull request closed without merging**
