### PR TITLE
Feature/test pred rpc

### PR DESCRIPTION
**Pull request by pawanrawal**
I have written tests for PopulateShard method. To do so I had to encapsulate some of the globals in the worker package. If it seems an overkill we can drop this though this seemed the only way to write tests for this feature.

Have also replaced `golang.org/x/net/context` with `context` except in `dgraph/main.go` and `worker\worker.go`. We can move to `context` package in these files after gogoprotobuf generates `.pb.go` files which import `context` package.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/180)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/dgraph/main.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKkDPZRdWJefqUjO1x:-KQKkDPZRdWJefqUjO1y:b-y77yxr) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/cmd/dgraph/main.go#L61)):*
> ```Go
> 	workers = flag.String("workers", "",
> 		"Comma separated list of IP addresses of workers")
> 	workerPort = flag.String("workerport", ":12345",
> ```

Couldn't you use port + 1 for workerPort?

---

*[worker/worker.go, line 48 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKmcKJmsO7oj8Xtw7H:-KQKmcKJmsO7oj8Xtw7I:b2nqwrg) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L48)):*
> ```Go
> 
> // wo is a pointer to the Worker object.
> var wo *Worker
> ```

This probably doesn't need to exist. If you're creating a worker instance, then all the struct fields will get encapslated within it.

---

*[worker/worker.go, line 79 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKmKAzrDxNzhgeGsOO:-KQKmKAzrDxNzhgeGsOP:b-mg3imk) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L79)):*
> ```Go
> }
> 
> type worker struct{}
> ```

Instead of creating another struct called Worker, you could just add all those variables here, no?

---

*[worker/worker.go, line 100 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKm6SxNLyT-NcoamSd:-KQKm6SxNLyT-NcoamSe:b3rfp6i) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L100)):*
> ```Go
> 	xids.Init(query.Data, uo)
> 
> 	if wo.instanceIdx != 0 {
> ```

You have access to w, why use wo? In fact, using wo here is bad.

---

*[worker/worker.go, line 135 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKmURtEFfd_seHEbL-:-KQKmURtEFfd_seHEbL0:b-p6hvqo) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L135)):*
> ```Go
> 	attr := string(q.Attr())
> 	x.Trace(ctx, "Attribute: %v NumUids: %v InstanceIdx: %v ServeTask",
> 		attr, q.UidsLength(), wo.instanceIdx)
> ```

Same here and elsewhere. You are operating on a worker instance already. Don't access another worker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/180)*

**Comment by pawanrawal** [comment]
Review status: 19 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[cmd/dgraph/main.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKkDPZRdWJefqUjO1x:-KQKpZQTitCTT6w1BeoR:balvn41) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/cmd/dgraph/main.go#L61)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Couldn't you use port + 1 for workerPort?
</details>
Hmm, we already use that for client communication. Also, this has to be one of the ports out of those supplied in workers above. Actually, we have the instanceId and the workers, so we could just get the correct index from the slice obtained by splitting workers.

---

*[worker/worker.go, line 48 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKmcKJmsO7oj8Xtw7H:-KQKpu_ItRpxgXj0h91P:bvn3idt) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This probably doesn't need to exist. If you're creating a worker instance, then all the struct fields will get encapslated within it.
</details>
Hmm, its used as a global to be accessed by other functions in the worker package which otherwise need to be passed the worker or become a method of the Worker. If we do that we can get rid of this global variable. 

---

*[worker/worker.go, line 79 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKmKAzrDxNzhgeGsOO:-KQKq5VSwNHYfiB0jdOD:btzbnta) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L79)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Instead of creating another struct called Worker, you could just add all those variables here, no?
</details>
Yeah removed this. Should have occurred​ to me.

---

*[worker/worker.go, line 100 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKm6SxNLyT-NcoamSd:-KQKq9X0rt8T9_XlcMH4:b-x4w95r) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L100)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You have access to w, why use wo? In fact, using wo here is bad.
</details>
Argh, should have seen this.

---

*[worker/worker.go, line 135 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKmURtEFfd_seHEbL-:-KQKqCfLadFh5qsDx__8:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5a89f306d6e0ee21703e7d8b8539cb01eb0af870/worker/worker.go#L135)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Same here and elsewhere. You are operating on a worker instance already. Don't access another worker.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/180)*

**Comment by pawanrawal** [comment]
Review status: 13 of 20 files reviewed at latest revision, 8 unresolved discussions.

---

*[worker/predicate.go, line 69 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQOXbO0UVs0vXO63PrI:-KQOXbO0UVs0vXO63PrJ:b-ls0pu9) ([raw file](https://github.com/dgraph-io/dgraph/blob/2a0ec08c6e8e34a7cd294c48e68e373d3a703994/worker/predicate.go#L69)):*
> ```Go
> // PopulateShard gets data for predicate pred from server with id serverId and
> // writes it to RocksDB.
> func (ws *State) PopulateShard(ctx context.Context, pred string,
> ```

Although `ws` is available as a global, this is a method of State only for the purposes of testing. In tests I can call this with the state of the appropriate worker, while the server method PredicateData can access the global state.  Another option is to pass `ws` as an argument to this function. 

---

*[worker/predicate_test.go, line 86 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQOY87LrepMR5bnNDeY:-KQOY87LrepMR5bnNDeZ:b-7jjdvk) ([raw file](https://github.com/dgraph-io/dgraph/blob/2a0ec08c6e8e34a7cd294c48e68e373d3a703994/worker/predicate_test.go#L86)):*
> ```Go
> 
> 	// Wait for workers to be initialized and connected.
> 	time.Sleep(5 * time.Second)
> ```

This is a bad way, another way would be to pass a channel to `Connect` which calls done when it finishes. Though that might be an overkill given we call it synchronously in our code.

---

*[worker/worker.go, line 51 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKcRm12xh5jMVADGSy-r3-51:-KQOYb__aAzr6t5CP5ja:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d35d6962bb1b3055c7d178f573879bff5a235686/worker/worker.go#L51)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported func New returns unexported type *worker.state, which can be annoying to use
</details>
Done.

---

*[worker/worker.go, line 36 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQKcRm12xh5jMVADGSy-r4-36:-KQOYaE1ph23TDqmV4CI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/831953b22094c41e585fea9b30c97b4767fc77f0/worker/worker.go#L36)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported type State should be of the form "State ..." (with optional leading article)
</details>
Done.

---

*[worker/worker.go, line 37 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQOXFRCA3YzxFBdLPG3:-KQOXFRCA3YzxFBdLPG4:bqyrbrk) ([raw file](https://github.com/dgraph-io/dgraph/blob/2a0ec08c6e8e34a7cd294c48e68e373d3a703994/worker/worker.go#L37)):*
> ```Go
> 
> // State stores the worker state.
> type State struct {
> ```

This has been exported because for the purpose of tests I have to have access to the state for different instances which I then pass to `PopulateShard`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/180)*

**Comment by manishrjain** [comment]
almost there!

---

Reviewed 5 of 7 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[worker/worker.go, line 50 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQL8txsmgHBpDPe31ES:-KQL8txtInytrx6AEC_v:b-77htae) ([raw file](https://github.com/dgraph-io/dgraph/blob/5aaf1eb305f5a85c0660a57a7cf7b377a20fe1ec/worker/worker.go#L50)):*
> ```Go
> 
> // New initializes a worker on an instance with a data and a uid store.
> func New(ps, uStore *store.Store, idx, numInst uint64) *Worker {
> ```

NewWorker(..)

---

*[worker/worker.go, line 37 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQOXFRCA3YzxFBdLPG3:-KQOe_GuESY8DWeuaDud:b-rmhc4m) ([raw file](https://github.com/dgraph-io/dgraph/blob/2a0ec08c6e8e34a7cd294c48e68e373d3a703994/worker/worker.go#L37)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This has been exported because for the purpose of tests I have to have access to the state for different instances which I then pass to `PopulateShard`.
</details>
Use State() function. Make this internal, because the init is local and this is a singleton.

---

*[worker/worker.go, line 51 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQOdfIcIkfnrISY11Tk:-KQOdfIcIkfnrISY11Tl:bhtru4z) ([raw file](https://github.com/dgraph-io/dgraph/blob/2a0ec08c6e8e34a7cd294c48e68e373d3a703994/worker/worker.go#L51)):*
> ```Go
> 
> // New initializes a worker on an instance with a data and a uid store.
> func New(ps, uStore *store.Store, idx, numInst uint64) *State {
> ```

InitState(), without doing any returns, because that's how you're using it. Then add another function, State() which can return the state, if needed.

also, use sync.Once() for init. But, looks like you're calling it multiple times in test. If so, then ignore sync.once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-:-KQOf7qUD_H6zYk3hs2N:b-qm09yu)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[worker/worker.go, line 37 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQOXFRCA3YzxFBdLPG3:-KQOnNn80J9bYuDhQs9o:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2a0ec08c6e8e34a7cd294c48e68e373d3a703994/worker/worker.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Use State() function. Make this internal, because the init is local and this is a singleton.
</details>
Done.

---

*[worker/worker.go, line 51 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-KQOdfIcIkfnrISY11Tk:-KQOjecvP8svveCjLvku:bnuccd6) ([raw file](https://github.com/dgraph-io/dgraph/blob/2a0ec08c6e8e34a7cd294c48e68e373d3a703994/worker/worker.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> InitState(), without doing any returns, because that's how you're using it. Then add another function, State() which can return the state, if needed.
> 
> also, use sync.Once() for init. But, looks like you're calling it multiple times in test. If so, then ignore sync.once.
</details>
Yeah sync.Once() fails the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/180)*

**Comment by manishrjain** [comment]
:lgtm_strong:  One last change as discussed -- sorry came to me just now after looking at the lint warning, that state should in fact be exported. Once changed, feel free to submit.

---

Reviewed 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/180#-:-KQQ1rLWK5KGF1UvtpLX:b-x7frus)*

**Comment by pawanrawal** [comment]
Merged to master with e0a8433141a6bf623f16657e1c587bf2ef6df892.

**Pull request closed without merging**
