### PR TITLE
Functionality to find first N results

### PR DESCRIPTION
**Pull request by manishrjain**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/77)

### CODE REVIEW

**Comment by manishrjain** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tpe7A7Kl&#x2F;18-support-for-limitby"> Support for LimitBy</a>

**Comment by pawanrawal** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[gql/parser.go, line 159 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpYIlGYsKKt4F9XDiB:-KGpYIlHvnobb6z-uva6:-1044670645) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/gql/parser.go#L159)):*
Is this space intentional ?

---

*[gql/parser.go, line 162 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpYMqjk6cFS_K8ilvw:-KGpYMqjk6cFS_K8ilvx:-1044670645) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/gql/parser.go#L162)):*
Is this space intentional ?

---

*[posting/list.go, line 743 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpiL7FgQdaR6l7jH5m:-KGpiL7FgQdaR6l7jH5n:-1684852321) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/posting/list.go#L743)):*
Is this space needed ?

---

*[posting/list.go, line 744 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpj-VLGeuNBkiCkqQ6:-KGpj-VLGeuNBkiCkqQ7:-1086172443) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/posting/list.go#L744)):*
Would it be a good idea to combine the if and else if blocks here?

---

*[query/query.go, line 114 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGphbyqkbLlsJwFhTmX:-KGphbyroBA5Phb3l2xf:-1553806943) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/query/query.go#L114)):*
Are we using this anywhere?  I suppose this is for later when we provide the user​ option to set an offset?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/77)*

**Comment by manishrjain** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[gql/parser.go, line 159 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpYIlGYsKKt4F9XDiB:-KGpmB65DHr5rM2oVpKg:113155850) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/gql/parser.go#L159)):*
I typically do it just before an else statement, to make the conditions clear.

---

*[gql/parser.go, line 162 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpYMqjk6cFS_K8ilvw:-KGpmG4ToxGLTLQt2SZz:-1849621849) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/gql/parser.go#L162)):*
Yes, same reason as above.

---

*[posting/list.go, line 743 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpiL7FgQdaR6l7jH5m:-KGpmY8NfRbWB4srz0Yi:-136375241) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/posting/list.go#L743)):*
Removed if else.

---

*[posting/list.go, line 744 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGpj-VLGeuNBkiCkqQ6:-KGpmX4rKe6eCFRps6Xb:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/posting/list.go#L744)):*
Done.

---

*[query/query.go, line 114 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGphbyqkbLlsJwFhTmX:-KGpm_wy0x07q69xIprp:-328628843) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/query/query.go#L114)):*
Yeah -- It's not required right ​now, but the code is set up to use it readily.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/77)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[query/query.go, line 114 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-KGphbyqkbLlsJwFhTmX:-KGpnNAuk8wp9qDXaLKF:676605422) ([raw file](https://github.com/dgraph-io/dgraph/blob/337b2fce06eb6a39b5cf4591232f87f5c817f0bd/query/query.go#L114)):*
Cool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-:-KGpnPyLPtCCu8qB-aoQ:1417088721)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/77#-:-KGpofYllHZLRTSH3aZJ:1417088721)*

**Comment by pawanrawal** [comment]
Reviewed 6 of 8 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/77)*

**Pull request merged**
