### PR TITLE
algo package and add Dave Cheney's errors pkg and use it

### PR DESCRIPTION
**Pull request by jchiu0**
This comes from feature/index branch which is hard to merge (not sure why some tests keep failing) and getting very messy. Would like to start from master and merge in changes from feature/index instead.

This PR includes
(1) algo package;
(2) Dave Cheney's errors package brought in and used in x/error.go.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/189)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[algo/sorted.go, line 32 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcnCqgYJk8ynF4Tmsb:-KQcnCqgYJk8ynF4Tmsc:b8oq1xo) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L32)):*
> ```Go
> // Uint64List is a list of uint64s.
> type Uint64List interface {
> 	Get(int) uint64
> ```

Following up on my comment before, would this work with types.UidList? Or, does this need a conversion to work?

---

*[algo/sorted.go, line 37 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcsVcRkuBKcvv36kAm:-KQcsVcRkuBKcvv36kAn:biphod) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L37)):*
> ```Go
> 
> // PlainUintLists is the simplest possible Uint64Lists.
> type PlainUintLists []PlainUintList
> ```

I don't see this being used anywhere in the code. This is used only for testing. In that case, it should be defined in tests, and not here.

---

*[algo/sorted.go, line 70 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcoTamHxxQX6las7cg:-KQcoTamHxxQX6las7ch:b56x56v) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L70)):*
> ```Go
> 			heap.Push(h, elem{
> 				Val: l.Get(0),
> 				Idx: i,
> ```

Call it listIdx.

---

*[algo/sorted.go, line 79 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQco5hDXSAdCk8BcxVC:-KQco5hDXSAdCk8BcxVD:bf9dpw0) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L79)):*
> ```Go
> 
> 	// ptr[i] is the element we are looking at for lists[i].
> 	ptr := make([]int, n)
> ```

idx or pos is a better term for this, because you're comparing it against size below.

---

*[algo/sorted.go, line 88 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcocyzDBxtMdQE4zc8:-KQcocyzDBxtMdQE4zc9:b-7ob0cw) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L88)):*
> ```Go
> 			last = me.Val
> 		}
> 		l := lists.Get(me.Idx)
> ```

l := lists.Get(me.listIdx)

that would make things clearer.

---

*[algo/sorted.go, line 129 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcpHxddsDwJqnXEMGs:-KQcpHxddsDwJqnXEMGt:b6cxjni) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L129)):*
> ```Go
> 
> 	// ptr[i] is the element we are looking at for lists[i].
> 	ptr := make([]int, n)
> ```

idx or pos here as well. Also, remove the extra vertical spaces between these 3 var assign statements.

---

*[algo/sorted.go, line 147 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcpgggM3ZDnADjNk0T:-KQcpgggM3ZDnADjNk0U:b7w6hi9) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L147)):*
> ```Go
> 			k := ptr[j]
> 			for ; k < l.Size() && l.Get(k) < val; k++ {
> 			}
> ```

Move this to the line above.

---

*[algo/sorted_test.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcqE7LokUIGM8Cfzs5:-KQcqE7LokUIGM8Cfzs6:b-vie370) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted_test.go#L174)):*
> ```Go
> }
> 
> type uidList struct {
> ```

When you define plainuint stuff, this can also be a definition. In fact, you already need this in one place, where we're doing this merging with UidList.

---

*[query/query.go, line 586 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrFDJrCGvpDYjEY5k:-KQcrFDKpMgM2XfNAdOX:b-75hdwf) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/query/query.go#L586)):*
> ```Go
> 
> // ListChannel contains our results, a list of UIDs.
> type ListChannel struct {
> ```

You could just declare such a struct in the algo itself. And avoid it here.

---

*[query/query.go, line 602 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrWpBh3eenbdpsANe:-KQcrWpBh3eenbdpsANf:b-c6ner0) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/query/query.go#L602)):*
> ```Go
> // ListChannels is a list of ListChannel, a UID matrix. Not using a pointer to
> // ListChannel because it contains only one pointer.
> type ListChannels []ListChannel
> ```

Same for this. Because in terms of usage, these are more important than plainuint64s.

---

*[vendor/github.com/pkg/errors/appveyor.yml, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrqabYxfN2PnExF2J:-KQcrqabYxfN2PnExF2K:bv4youp) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/vendor/github.com/pkg/errors/appveyor.yml#L1)):*
> ```YAML
> version: build-{build}.{branch}
> ```

Windows? We don't officially support it. Is the point to do so?

---

*[x/error.go, line 66 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcsMzXB3FRB3SnLDB2:-KQcsMzXB3FRB3SnLDB3:bm9613m) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/x/error.go#L66)):*
> ```Go
> 
> // Wrap wraps errors from external lib.
> func Wrap(err error) error {
> ```

There is no usage for wrap so far, so it's hard to judge the utility of this import.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/189)*

**Comment by jchiu0** [comment]
Review status: 10 of 14 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[algo/sorted.go, line 32 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcnCqgYJk8ynF4Tmsb:-KQdumOXhauapZ0wp-ME:bs7n1te) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L32)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Following up on my comment before, would this work with types.UidList? Or, does this need a conversion to work?
</details>
Yes, it does work. No copying needed.

---

*[algo/sorted.go, line 37 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcsVcRkuBKcvv36kAm:-KQduuEaFP_CQmz9ap1W:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I don't see this being used anywhere in the code. This is used only for testing. In that case, it should be defined in tests, and not here.
</details>
Done.

---

*[algo/sorted.go, line 70 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcoTamHxxQX6las7cg:-KQdwzrmX9NGOO0cHjve:b63zuc6) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L70)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Call it listIdx.
</details>
Done. Also renamed Val to val and make everything very internal.

---

*[algo/sorted.go, line 79 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQco5hDXSAdCk8BcxVC:-KQdxG_4ji_7ZPZbRgre:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L79)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> idx or pos is a better term for this, because you're comparing it against size below.
</details>
Done.

---

*[algo/sorted.go, line 88 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcocyzDBxtMdQE4zc8:-KQdxSt1oyR2zFyZ1ddw:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L88)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> l := lists.Get(me.listIdx)
> 
> that would make things clearer.
</details>
Done.

---

*[algo/sorted.go, line 129 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcpHxddsDwJqnXEMGs:-KQdxUXKDscABRybSbl9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L129)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> idx or pos here as well. Also, remove the extra vertical spaces between these 3 var assign statements.
</details>
Done.

---

*[algo/sorted.go, line 147 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcpgggM3ZDnADjNk0T:-KQdxjpduklyFykjXIEc:bgl3x1z) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted.go#L147)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Move this to the line above.
</details>
I moved it up but gofmt moves it back down.

---

*[algo/sorted_test.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcqE7LokUIGM8Cfzs5:-KQepYTZT-4gBC9YRn83:b-klnwy) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted_test.go#L174)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> When you define plainuint stuff, this can also be a definition. In fact, you already need this in one place, where we're doing this merging with UidList.
</details>
Good point. Replaced plainuint stuff with UIDList. (I am very tempted to create a new package called taskwrap to contain UIDList which will make working UidList nicer. But let's leave that out for now.)

---

*[query/query.go, line 586 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrFDJrCGvpDYjEY5k:-KQepoWAARLSXJViyH0v:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/query/query.go#L586)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> You could just declare such a struct in the algo itself. And avoid it here.
</details>
Done.

---

*[query/query.go, line 602 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrWpBh3eenbdpsANe:-KQepqXY6R5FL2UvuQSU:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/query/query.go#L602)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Same for this. Because in terms of usage, these are more important than plainuint64s.
</details>
Done.

---

*[vendor/github.com/pkg/errors/appveyor.yml, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrqabYxfN2PnExF2J:-KQeqLlqD1Il0q2BmIgc:bio6h7r) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/vendor/github.com/pkg/errors/appveyor.yml#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Windows? We don't officially support it. Is the point to do so?
</details>
It was autogenerated. I didn't know what to delete. Removed.

---

*[x/error.go, line 66 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcsMzXB3FRB3SnLDB2:-KQe-rYNukhEo7EFtwGM:b-4kplg5) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/x/error.go#L66)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> There is no usage for wrap so far, so it's hard to judge the utility of this import.
</details>
Everytime we receive an error from an external package, we should wrap it to give it more context. I updated store.go to reflect this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/189)*

**Comment by jchiu0** [comment]
Review status: 8 of 13 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[algo/sorted.go, line 54 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcINBlUFlgBMZnLJR7-r3-54:-KQeqxyokUmhA5EI80e3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3a6def5b84209671324c799d22b78522462c69fe/algo/sorted.go#L54)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> comment on exported type UIDLists should be of the form "UIDLists ..." (with optional leading article)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/189)*

**Comment by jchiu0** [comment]
Review status: 8 of 14 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 81 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQesPDzU1L0P-I52aiD-r5-81:-KQes_u-Vq-pR4e3ePQR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d63680390ef6b6609ae33d8ea99a978950463dc5/store/store.go#L81)):*
<details><summary><i>Previously, houndci-bot (Hound) wrote…</i></summary>
> exported method Store.Get should have comment or be unexported
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/189)*

**Comment by manishrjain** [comment]
Reviewed 2 of 16 files at r1, 2 of 4 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[algo/sorted.go, line 38 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjJvosTjialaCXR37t:-KQjJvosTjialaCXR37u:b-spxrbp) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/algo/sorted.go#L38)):*
> ```Go
> }
> 
> // UIDList is a list of UIDs. We might consider moving this to another package
> ```

I think the comment about moving doesn't belong to the struct doc.

---

*[algo/sorted_test.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcqE7LokUIGM8Cfzs5:-KQj6xpQNphC6X0MOw31:bwhfs2q) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/algo/sorted_test.go#L174)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> Good point. Replaced plainuint stuff with UIDList. (I am very tempted to create a new package called taskwrap to contain UIDList which will make working UidList nicer. But let's leave that out for now.)
</details>
Don't be so eager to create new packages :-). Ideally, each package should contain a significant chunk of code and logic. If something can be a struct, it doesn't need to be a package.

---

*[store/store.go, line 85 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjLB93ecL_37gqMr0N:-KQjLB93ecL_37gqMr0O:b-cae45s) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/store/store.go#L85)):*
> ```Go
> 	valSlice, err := s.db.Get(s.ropt, key)
> 	if err != nil {
> 		return []byte(""), x.Wrap(err)
> ```

Without any context message, what's the point of wrapping?

---

*[store/store.go, line 138 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjLEuBFj_FZQIMo87r:-KQjLEuBFj_FZQIMo87s:blr8h6l) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/store/store.go#L138)):*
> ```Go
> func (s *Store) WriteBatch(wb *rocksdb.WriteBatch) error {
> 	if err := s.db.Write(s.wopt, wb); err != nil {
> 		return x.Wrap(err)
> ```

same here. Note that Wrap requires a corresponding Cause() to actually be useful. How do you plan to use Cause()?

---

*[x/error.go, line 67 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjKti9ZIYCu2CTjndZ:-KQjKtiAQinvL1Zc20f0:b-yo228h) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/x/error.go#L67)):*
> ```Go
> // Wrap wraps errors from external lib.
> func Wrap(err error) error {
> 	return errors.Wrap(err, "")
> ```

Looks like the point of Wrap was to add context. If you just send empty messages, then I wonder what's the added value here?

---

*[vendor/github.com/pkg/errors/appveyor.yml, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrqabYxfN2PnExF2J:-KQjJLipRnBNfV56TKD8:b-mxb32o) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/vendor/github.com/pkg/errors/appveyor.yml#L1)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> It was autogenerated. I didn't know what to delete. Removed.
</details>
Oh.. just realized that it was in the vendor directory. I wonder if a future govendor sync would bring this back. So, there was probably no need to delete it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/189)*

**Comment by jchiu0** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[algo/sorted.go, line 38 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjJvosTjialaCXR37t:-KQjUw8lwGKHZ4F-1yxj:b-wnfmk9) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/algo/sorted.go#L38)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> I think the comment about moving doesn't belong to the struct doc.
</details>
Done. Removed.

---

*[store/store.go, line 85 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjLB93ecL_37gqMr0N:-KQjVZzEbHvbwyWfjM_c:b-m0k3wz) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/store/store.go#L85)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Without any context message, what's the point of wrapping?
</details>
It is to add the stack trace. As far as i know, when you log the error, it only reports the error and it often takes me a while to figure out what led to that function. (A panic would have been more useful for debugging..)

When you eventually log the error, say with x.Trace, you want to do a x.Trace("%+v", err) to print the stack trace. We could add another x.TraceError() to do that.

There is not always a big need to add context. For example, IO errors would by default include the filename, which is often all we need.

---

*[store/store.go, line 138 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjLEuBFj_FZQIMo87r:-KQjWn3sKXPYohXs4CFq:b-ewe7vq) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/store/store.go#L138)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> same here. Note that Wrap requires a corresponding Cause() to actually be useful. How do you plan to use Cause()?
</details>
As mentioned above. I find the stack trace very useful for debugging.

---

*[x/error.go, line 67 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjKti9ZIYCu2CTjndZ:-KQjWraIhXx0NbiuA2Dj:b-m9zaz2) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/x/error.go#L67)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Looks like the point of Wrap was to add context. If you just send empty messages, then I wonder what's the added value here?
</details>
Same as above. Just after the stack trace.

---

*[vendor/github.com/pkg/errors/appveyor.yml, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQcrqabYxfN2PnExF2J:-KQjWxlYtPzHg60bM12z:budzqax) ([raw file](https://github.com/dgraph-io/dgraph/blob/54152779877c50d97d6d0a59a2cda79e39554717/vendor/github.com/pkg/errors/appveyor.yml#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Oh.. just realized that it was in the vendor directory. I wonder if a future govendor sync would bring this back. So, there was probably no need to delete it.
</details>
It is deleted. It is ok. The other govendor directories didn't have it, so let's leave it deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/189)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[store/store.go, line 85 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-KQjLB93ecL_37gqMr0N:-KQjd4P6x2-HBhiA1WHj:bb6ywmx) ([raw file](https://github.com/dgraph-io/dgraph/blob/7ddd1ca0b1aced8acea4a51464bd744613586141/store/store.go#L85)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary>
> It is to add the stack trace. As far as i know, when you log the error, it only reports the error and it often takes me a while to figure out what led to that function. (A panic would have been more useful for debugging..)
> 
> When you eventually log the error, say with x.Trace, you want to do a x.Trace("%+v", err) to print the stack trace. We could add another x.TraceError() to do that.
> 
> There is not always a big need to add context. For example, IO errors would by default include the filename, which is often all we need.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/189#-:-KQjltMhfDK9zkGj5ZKi:bnfp4nl)*

**Pull request closed without merging**
