### PR TITLE
Distributed mutations from DirectedEdges

### PR DESCRIPTION
**Pull request by manishrjain**
Provide a function `MutateOverNetwork`, which would divide DirectedEdges across workers, based on fingerprint of `Attribute`, and execute them via goroutines.

The goroutine would run the mutation locally, if instanceIdx is the same as idx generated from Attribute. Otherwise, it would make network calls to send it to the right instances.

[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/41)

### CODE REVIEW

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/main.go, line 77 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/41#-KBfK416uOyDugSkKzwN:-KBfK4175RE_TJDF3zpK:2047223750) ([raw file](https://github.com/dgraph-io/dgraph/blob/da0e9e19b4aad9113bdbf7dd328807f394e25ae6/server/main.go#L77)):*
Why is this needed? the underscore can be shifted 5 lines above right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41)*

**Comment by ashwin95r** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41)*

**Comment by manishrjain** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/main.go, line 77 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/41#-KBfK416uOyDugSkKzwN:-KBfNcPPmtvmZRPidqpq:1318467899) ([raw file](https://github.com/dgraph-io/dgraph/blob/da0e9e19b4aad9113bdbf7dd328807f394e25ae6/server/main.go#L77)):*
Yeah, I was going to use this, when I realized that this requires all the uids allocated for the xids. So, this got left behind. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41)*

**Comment by ashwin95r** [comment]
Reviewed 2 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/mutation.go, line 62 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/41#-KBfXWatW0l3dbrd2afd:-KBfXWauW3nqgjLEbvDl:1377350481) ([raw file](https://github.com/dgraph-io/dgraph/blob/da0e9e19b4aad9113bdbf7dd328807f394e25ae6/worker/mutation.go#L62)):*
Where is idx defined?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41)*

**Comment by ashwin95r** [comment]
:lgtm: 

---

Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/mutation.go, line 62 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/41#-KBfXWatW0l3dbrd2afd:-KBfXxPUgdISSxEprr7h:1766876755) ([raw file](https://github.com/dgraph-io/dgraph/blob/da0e9e19b4aad9113bdbf7dd328807f394e25ae6/worker/mutation.go#L62)):*
Ah I missed it. Looks alright!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41#-:-KBfY3Iw_JnAdD_QpcJv:980077423)*

**Comment by manishrjain** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/mutation.go, line 62 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/41#-KBfXWatW0l3dbrd2afd:-KBfY8yadn-UfZmAtZ2D:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/da0e9e19b4aad9113bdbf7dd328807f394e25ae6/worker/mutation.go#L62)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41)*

**Comment by ashwin95r** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41)*

**Comment by manishrjain** [comment]
Thanks Ashwin!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/41#-:-KBfYFHMPLGcYPCNCwdJ:-1848703703)*

**Pull request merged**
