### PR TITLE
Make recurse a directive

### PR DESCRIPTION
**Pull request by pawanrawal**
So that it can also be used as a var block if need be.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1754)

### CODE REVIEW

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1754#-:-KyYSKUFQ9TV5X5qCMzE:bnfp4nl)*

**Comment by peterstace** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1754)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1754#-:-KyYl98mVgpR9daDGEEV:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master as of be5a11bc03601d94bf3c94944d65509f379a562d.

**Pull request closed without merging**
