### PR TITLE
Fix count with facets filter

### PR DESCRIPTION
**Pull request by ashish-goswami**
Fixes: https://github.com/dgraph-io/dgraph/issues/4659

Currently `count` with `facets filter` is not returning correct result. This is because, while calculating count we use `pl.Length()` function, which returns length of posting list. This will return correct result
if there are no `facets filter`. But if there are `facets filter`, we need to filter posting from the posting list which satisfy `facets filter`.

This PR fixes above issue.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/4751)

### CODE REVIEW

**Comment by MiLeung** [comment]
I still get this issue on v1.2.1 and I also get this issue when I `docker pull dgraph/dgraph:master`. How do I get this to work? Screen Shot 2020-03-08 at 12 46 40 AM

**Comment by ashish-goswami** [comment]
Hey @MiLeung, can you provide us the sample data on which it is returning incorrect result?

**Comment by MiLeung** [comment]
How do I do that? Can I use [dgo](https://pkg.go.dev/github.com/dgraph-io/dgo/v2)?

**Comment by ashish-goswami** [comment]
Yes. You can use dgo to run mutation with data and run above query to see count.
You can also use ratel to run mutation and query.

**Comment by MiLeung** [comment]
@ashish-goswami  I thought you wanted me to send a exported db, but here's a simple query and response

```
{
  q(func: uid(0x1d7fa)) {
    totalUnreadPings: count(pings (orderdesc: date) @facets(eq(unread, true)) @normalize)
    pings (orderdesc: date) @facets(unread) @normalize {
      text: text
      author {
        settings {
          account {
            username: username
          }
        }
      }
    }
  }
}
```

```
"data": {
    "q": [
      {
        "totalUnreadPings": 2,
        "pings": [
          {
            "text": "sdf",
            "username": "7BA5414DAEEE170180ADE1E27A1BA8A9"
          },
          {
            "text": "sdf",
            "username": "7BA5414DAEEE170180ADE1E27A1BA8A9"
          }
        ],
        "pings|unread": {
          "0": true
        }
      }
    ]
  }
```

**Comment by ashish-goswami** [comment]
Hey @MiLeung, please help me reproduce this issue. I ran following mutation:
```
{
  set {
    _:1 <text> "sdf" .
    _:1 <date> "2019-01-01" .
    _:1 <author> _:3 .

    _:2 <text> "sdf" .
    _:2 <date> "2020-01-01" .
    _:2 <author> _:4 .

    _:3 <username> "7BA5414DAEEE170180ADE1E27A1BA8A9" .
    _:4 <username> "7BA5414DAEEE170180ADE1E27A1BA8A9" .

    _:5 <pings> _:1 .
    _:5 <pings> _:2 (unread=true) .
  }
}
```
and got the expected response.
```
{
  "data": {
    "q": [
      {
        "totalUnreadPings": 1,
        "pings": [
          {
            "date": "2020-01-01",
            "text": "sdf",
            "username": "7BA5414DAEEE170180ADE1E27A1BA8A9"
          },
          {
            "date": "2019-01-01",
            "text": "sdf",
            "username": "7BA5414DAEEE170180ADE1E27A1BA8A9"
          }
        ],
        "pings|unread": {
          "0": true
        }
      }
    ]
  },
```

**Comment by MiLeung** [comment]
I still have the issue.  try making the mutation with JSON notation?

**Comment by ashish-goswami** [comment]
Hi @MiLeung, I tried json mutation:
```
{
    "set": {
        "uid": "_:5",
        "pings": [
            {
                "uid": "_:1",
                "text": "sdf",
                "date": "2019-01-01",
                "author": {
                    "uid": "_:3",
                    "username": "7BA5414DAEEE170180ADE1E27A1BA8A9"
                }
            },
            {
                "uid": "_:2",
                "text": "sdf",
                "date": "2020-01-01",
                "author": {
                    "uid": "_:4",
                    "username": "7BA5414DAEEE170180ADE1E27A1BA8A9"
                },
                "pings|unread": "true"
            }
        ]
    }
}
```
Still getting the correct response.

**Comment by MiLeung** [comment]
I'm stumped then
Screen Shot 2020-03-17 at 11 14 14 AM

**Comment by ashish-goswami** [comment]
Hey @MiLeung, can you share the raw rdf/json data inserted in DB?

**Comment by MiLeung** [comment]
```
{
  "set": {
    "uid": "0x20120",
    "pings": {
      "uid": "0x20150",
      "pings|unread": "true"
    }
  }
}
```

For me, setting `pings|unread` to true or false doesn't matter - it will still be counted in the `totalUnreadPings` query

**Comment by ashish-goswami** [comment]
Hi @MiLeung, I tried following mutation and query as suggested by you:
Mutation:
```
{
  "set": {
    "uid": "_:1",
    "pings": {
      "uid": "_:2",
      "pings|unread": "true"
    }
  }
}
```

Query:
```
{
  q(func: uid(0x1)) {
    totalUnreadPings: count(pings @facets(eq(unread, false)) @normalize)
    pings @facets(unread) @normalize {
      uid
    }
  }
}
```

Got the following result:
```
{
  "data": {
    "q": [
      {
        "totalUnreadPings": 0,
        "pings": [
          {
            "uid": "0x2"
          }
        ],
        "pings|unread": "true"
      }
    ]
  }
```

I think, this is the expected result.

**Comment by MiLeung** [comment]
My bad, the `unread` facet should be set to true, but either way, I am still getting the wrong result.  The commented out query in the image below yields the correct result, but is a bit more complicated. 

Screen Shot 2020-03-20 at 11 06 40 AM


On `http://localhost:8080/health`,  I get `{"version":"v1.2.1","instance":"alpha","uptime":592040}`.  We are running the same version right?

**Comment by MichelDiz** [comment]
hey guys,

There is confusion here. This PR is not in version v1.2.1 @MiLeung . The only version this PR is in is version v20.03.0-beta.20200320.

If you read the changelog you will see that there is no such commit there. And if you analyze the dates, this PR joined the master 25 days ago. And version v1.2.1 was built +24 days (February 6th, 46 days ago). At most this would be in version v1.2.2 which was 2 days ago. But it's not there.

If you need this fix, I suggest you wait for a stable version or use the recently released beta. Also, you could try to ask a cherry-pick for v1.x.x. I'm not sure if we gonna have more releases for  v1.x.x. Need to check it.

The second point to note, the use of facet no count is wrong.
It is not like this:
``
totalUnreadPings: count(pings (orderdesc: date) @facets(eq(unread, true)) @normalize)
``

The correct form is like this:
```
totalUnreadPings: count(pings) @facets(eq(unread, true)) @normalize
```

The facet and filters and any other directive must be outside the parenthesis of the count. And there's no need to use ` (orderdesc: date)`. As it just does a count.

Cheers.

**Pull request merged**
