### PR TITLE
Bench/gensubgraph

### PR DESCRIPTION
**Pull request by jchiu0**
1) We move benchmarks from query_test into benchmark_test as query_test.go is getting long.
2) We refactor benchmarking code a bit to make it more concise.
3) We make UIDList, task.ValueList, task.CountList serializable.
4) We export SrcUIDs and DestUIDs in SubGraph so that gob will encode/decode them.
5) We add a flag in cmd/dgraph to output subgraphs into a directory, if the flag is specified.
6) We regenerate these binaries.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/307)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-:-KVY_SduaPZolDc6wV1y:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 0 of 22 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/benchmark_test.go, line 36 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVY_oTIo5DrZBd3qEJc:-KVY_oTJqBg1qJd0CvOM:bleflv) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark_test.go#L36)):*
> ```Go
> 			label := fmt.Sprintf("%s_%d", s, i)
> 			filename := fmt.Sprintf("benchmark/%s.%d.gob", s, i)
> 			b.Run(label, func(b *testing.B) {
> ```

We might wan't to check for failures? Nice using the Run method.

---

*[query/benchmark/README.md, line 15 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVYZ6VBKNlUy_8au_OX:-KVYZ6VChTkbJsB51kqa:b-sfng71) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark/README.md#L15)):*
> ```Markdown
> 
> for NUM in $NUMS; do
> 	curl localhost:8912/query -XPOST -d "{
> ```

Sorry, I think this wasn't clear earlier. The 10, 100 and 1000 referred to the number of entities in the response of the queries. That is they corresponded to different `_xid_` in the root query.
So I wasn't using the first argument. If you wan't I can share the corresponding _xid_s with you.

---

*[query/benchmark/README.md, line 30 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVYZUu7dgIql2ToS3zY:-KVYZUu7dgIql2ToS3zZ:b13fwxw) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark/README.md#L30)):*
> ```Markdown
> for S in dumpsg/*.gob; do
>   echo $S
> 	cp -f $S /tmp/actor.${n}.gob
> ```

Space versus tabs issue.

---

*[query/benchmark/README.md, line 46 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVYZa0nATSZ20uDPqVb:-KVYZa0nATSZ20uDPqVc:bmqazo1) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark/README.md#L46)):*
> ```Markdown
> for NUM in $NUMS; do
> 	curl localhost:8912/query -XPOST -d "{
>         me(_xid_:m.05dxl_) {
> ```

Similarly here.

---

*[query/benchmark/README.md, line 68 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVYZhiA5rqqcwS6ZoeZ:-KVYZhiA5rqqcwS6Zoe_:b-wm885j) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark/README.md#L68)):*
> ```Markdown
> 
> ```shell
> cp -vf /tmp/*.gob ./
> ```

How about we actually check in an actual shell-script which does all this? Also might be good to put the files in a folder and copy that folder over. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/307)*

**Comment by jchiu0** [comment]
Review status: 0 of 23 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[query/benchmark_test.go, line 36 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVY_oTIo5DrZBd3qEJc:-KVdCfrqlVT12VDcytgE:bzayvlc) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark_test.go#L36)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We might wan't to check for failures? Nice using the Run method.
</details>
Added a check and calls FailNow once anything fails.

---

*[query/benchmark/README.md, line 15 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVYZ6VBKNlUy_8au_OX:-KVdThTOHYoMu5im5KwQ:b-up9mct) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark/README.md#L15)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Sorry, I think this wasn't clear earlier. The 10, 100 and 1000 referred to the number of entities in the response of the queries. That is they corresponded to different `_xid_` in the root query.
> So I wasn't using the first argument. If you wan't I can share the corresponding _xid_s with you.
</details>
Now using the 6 xids you supplied.

---

*[query/benchmark/README.md, line 68 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-KVYZhiA5rqqcwS6ZoeZ:-KVdTyYTWeb-yHKgbd5K:b-9tl0mk) ([raw file](https://github.com/dgraph-io/dgraph/blob/2dcd1343dce46ee9cc4d392c89dfaa1b4cf1200f/query/benchmark/README.md#L68)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> How about we actually check in an actual shell-script which does all this? Also might be good to put the files in a folder and copy that folder over. What do you think?
</details>
Done. (The temp folder is "dumpsg" inside ~/dgraph where we run dgraph. User can change this by modifying DATADIR in run.sh.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/307)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 10 of 21 files at r1, 4 of 5 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/307#-:-KVdYNZBHudp33nAo07K:bnfp4nl)*

**Pull request closed without merging**
