### PR TITLE
Add rocksDB merging code

### PR DESCRIPTION
**Pull request by ashwin95r**
[Review on Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/19)

### CODE REVIEW

**Comment by manishrjain** [comment]
Call it tools/merge/merge.cc

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/rocksDB_merger/rocksDB_merger.cc, line 5 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q5tHRLIS0CBWf1XUC:-K9q5tHRLIS0CBWf1XUD:-1748768109) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/rocksDB_merger/rocksDB_merger.cc#L5)):*
Spelling mistake. Should be `destination`

---

*[tools/rocksDB_merger/rocksDB_merger.cc, line 24 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q5g9oFs7HD1O2rPiF:-K9q5g9oFs7HD1O2rPiG:72818309) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/rocksDB_merger/rocksDB_merger.cc#L24)):*
Replace all tabs with 2 spaces. Here and everywhere else.

---

*[tools/rocksDB_merger/rocksDB_merger.cc, line 54 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q64ltb12YDouLFLu4:-K9q64ltb12YDouLFLu5:-181790817) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/rocksDB_merger/rocksDB_merger.cc#L54)):*
There should be a check somewhere which ensures that if the same key occurs multiple times, it has the same value. Otherwise, log fatal.

---

*[tools/rocksDB_merger/rocksDB_merger.cc, line 66 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q62jUf7kj92N_QCYG:-K9q62jUf7kj92N_QCYH:1262831688) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/rocksDB_merger/rocksDB_merger.cc#L66)):*
Remove commented code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-:-K9q5Hts4-FVuneIhfwZ:1809597497)*

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/rocksDB_merger/rocksDB_merger.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q6HRLHGL-CqrAMHxO:-K9q6HRLHGL-CqrAMHxP:2040128247) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/rocksDB_merger/rocksDB_merger.cc#L1)):*
Did you copy this code from somewhere? If so, copy that license as well. Otherwise, if you wrote this code yourself, then add the standard DGraph license here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/rocksDB_merger/rocksDB_merger.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q6HRLHGL-CqrAMHxO:-K9q8rDyiGpEnTn5-K3m:-1332335233) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/rocksDB_merger/rocksDB_merger.cc#L1)):*
I referred to some files and this link https://github.com/facebook/rocksdb/wiki/Basic-Operations

So I'm not sure

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by manishrjain** [comment]
Btw, make your commit logs messages specific -- say what you really did, not just "changed ... code"

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/merge/.gitignore, line 1 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9shJhYXsolUT7S4NmP:-K9shJhYXsolUT7S4NmQ:-502844304) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/.gitignore#L1)):*
Also add line `/merge`

---

*[tools/merge/merge.cc, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q6HRLHGL-CqrAMHxO:-K9sf0vAfYbecCPoq4nv:-141275918) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/merge/merge.cc#L1)):*
Ah.. that's okay. As long as you didn't copy the whole file from somewhere. Then add our license to the top.

---

*[tools/merge/merge.cc, line 29 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sg0fslIEt89KJNQJJ:-K9sg0fslIEt89KJNQJK:1939115382) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L29)):*
Having a map like this can cause memory blow up -- if we're dealing with millions of such uids. In a way, the reason the uid creation was done on multiple machines was because doing it on one machine would be too slow, right. So, don't use a map. Rocksdb automatically keeps all keys sorted, so the same repeated key would occur multiple times together.

Also, try and keep this generic so we can also use this to merge the data, not just the uids.

---

*[tools/merge/merge.cc, line 58 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sfHp62y86mx5ISH-A:-K9sfHp62y86mx5ISH-B:1850714250) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L58)):*
Break the line to not more than 80 chars. So, break it after the `&&`

Also, no need for a map. Iterator would give you repeated keys together.

---

*[tools/merge/merge.cc, line 59 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sfMjLq8Slzo78nmpZ:-K9sfMjLq8Slzo78nmp_:2110890762) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L59)):*
This line still has a tab I think.

---

*[tools/merge/merge.cc, line 60 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sgxCk7Y3jPoVB8VxL:-K9sgxCl9lU5YeKpXpBl:-96202557) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L60)):*
exit(0) is clean exit. This isn't clean exit. Call assert(false)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-:-K9shOg2BR8M75W9Pk24:894377125)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/merge/merge.cc, line 29 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sg0fslIEt89KJNQJJ:-K9u4hnUPFvG263y-3Wn:746493437) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L29)):*
The thing is I'm creating a new rocksDB object and adding all the key, value from the sharded rocksDB. So if a single XID was assigned different UID by different instances (though it shouldn't happen), the repeated key wont be consecutive as I'm iterating within a single instance's store. If a single XID was assigned different UID by the same instance, that would've already been overwritten while assigning. So the repeated key will not be consecutive the way i'm iterating through them

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/merge/merge.cc, line 54 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q64ltb12YDouLFLu4:-K9u6s92iO1VHVGFkJ8Q:-1581028164) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/merge/merge.cc#L54)):*
One possible way would be to try and get the key from the rocksDB itself, that way there wont be an extra map, though it would increase the number of reads and might affect the performance by a bit

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/merge/merge.cc, line 54 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9q64ltb12YDouLFLu4:-K9uDmxz4BWloMOkOa-0:-1817251084) ([raw file](https://github.com/dgraph-io/dgraph/blob/671284a841373fbe4e88888896cde9a97198b660/tools/merge/merge.cc#L54)):*
I doubt you need to do lookups, if you consider these sorted streams. See above.

---

*[tools/merge/merge.cc, line 29 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sg0fslIEt89KJNQJJ:-K9uDTIy5e5xSC4RpbGd:-1493148239) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L29)):*
Think it should be possible to iterate over all the shards together, in the same way as you'd merge a list of sorted streams; using a heap. That should take O(N log K), where K = size of heap, and N = length of all streams put together.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tools/merge/merge.cc, line 29 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sg0fslIEt89KJNQJJ:-K9uEep3pSxRryZ4AcwY:-1755235789) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L29)):*
I think that would be quite complex compared to the current one. Even if we read from the store, it would be O(N logN) and even is N is few billions, the factor would still be small. I feel if we use heaps it would add unnecessary complexity to the code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[tools/merge/merge.cc, line 29 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sg0fslIEt89KJNQJJ:-K9uG04Z5w2Glzd8Vioi:172514585) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L29)):*
Should we first try reading from the store and if its too slow change to the heap approach?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[tools/merge/merge.cc, line 29 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9sg0fslIEt89KJNQJJ:-K9vLz219cP8FWBRI73d:-1292678841) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L29)):*
N Random seeks over all shards isn't going to be faster compared to reading K shards in serial order. Let's discuss on Gitter.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by manishrjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[tools/merge/merge_heap.cc, line 36 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vQC8BdgelVaK3-wPd:-K9vQC8BdgelVaK3-wPe:900495497) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L36)):*
Following from below, technically even key doesn't need to be string. Is there some reason it is?

---

*[tools/merge/merge_heap.cc, line 37 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vQ2_DNjbmxix-lSDJ:-K9vQ2_EZFQgrKDliQCc:-1545429875) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L37)):*
Value doesn't need to be string; it is a byte array; so should be treated like such.

---

*[tools/merge/merge_heap.cc, line 56 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vQMDC8dz08tPvOJ-X:-K9vQMDC8dz08tPvOJ-Y:-408057576) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L56)):*
Align it to 4 spaces after the start of the previous line:
std:cerr
    <folder...

---

*[tools/merge/merge_heap.cc, line 94 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vQWabCRi9dAeqk3Av:-K9vQWacyQJW6Amtgcgl:1498649614) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L94)):*
Be wary of string conversions.

---

*[tools/merge/merge_heap.cc, line 102 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vPjN_Ugm0GKE3dyZF:-K9vPjNaYGFcoRIz2YPw:-1899100257) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L102)):*
const struct node& top = pq.top();

---

*[tools/merge/merge_heap.cc, line 118 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vQd-lr4uBQB02UUoP:-K9vQd-lr4uBQB02UUoQ:-2099675312) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L118)):*
and here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[tools/merge/merge_heap.cc, line 36 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vQC8BdgelVaK3-wPd:-K9wAcMIQfs4JBiaCjQV:-704625769) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L36)):*
The db->Get method doesnt allow value other than string as far as I've searched. Ive made the key and value generic in the merge_heap.cc but not able to do it at one place in merge.cc

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by manishrjain** [comment]
Looking forward to the comparison results.

---

Reviewed 1 of 3 files at r2, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[tools/merge/merge.cc, line 2 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xL37_ADxAF8emuq6B:-K9xL37asfG8lvhoUuYp:-1765301969) ([raw file](https://github.com/dgraph-io/dgraph/blob/b37e6c1bd6baf3ee7df09182d1d27d5bb3e8be8f/tools/merge/merge.cc#L2)):*
Please add the copyright notice here as it is in all the other files. I'll soon take one pass and reassign it to DGraph (instead of myself).

---

*[tools/merge/merge_heap.cc, line 56 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9vQMDC8dz08tPvOJ-X:-K9xLkJbwQuZxSK7tTvg:-1376347932) ([raw file](https://github.com/dgraph-io/dgraph/blob/0e23e858e7b12494bed81225d1a52c38384ce805/tools/merge/merge_heap.cc#L56)):*
I meant after the previous line. For some reason reviewable.io trimmed my spaces. It's meant to be like this:
line1
....line1 continued

or, if line1 is already indented, as it is in this case:
....line1
........line1 continued

---

*[tools/merge/merge_heap.cc, line 1 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xLE6115Ywg6Qu-6mu:-K9xLE62xFMkfP4bYNaf:241797332) ([raw file](https://github.com/dgraph-io/dgraph/blob/70859515efd460686dd9ae34b0c8617f9fc330d2/tools/merge/merge_heap.cc#L1)):*
And here as well.

---

*[tools/merge/merge_heap.cc, line 71 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xM_kN5Zzv84lviT1R:-K9xM_kO11Ho7X4R_PjQ:-1242518158) ([raw file](https://github.com/dgraph-io/dgraph/blob/70859515efd460686dd9ae34b0c8617f9fc330d2/tools/merge/merge_heap.cc#L71)):*
spaces

---

*[tools/merge/merge_heap.cc, line 84 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xMbnS-ExUAhkQvRkc:-K9xMbnS-ExUAhkQvRkd:-626045664) ([raw file](https://github.com/dgraph-io/dgraph/blob/70859515efd460686dd9ae34b0c8617f9fc330d2/tools/merge/merge_heap.cc#L84)):*
Extra spaces. Remove here and elsewhere below.

---

*[tools/merge/merge_heap.cc, line 115 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xMslSzK_xO78WA4UG:-K9xMslSzK_xO78WA4UH:974164672) ([raw file](https://github.com/dgraph-io/dgraph/blob/70859515efd460686dd9ae34b0c8617f9fc330d2/tools/merge/merge_heap.cc#L115)):*
spaces here as well and above.

---

*[tools/merge/merge_heap.cc, line 122 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xMhGCRhTvsZDzFbdQ:-K9xMhGCRhTvsZDzFbdR:-1147860770) ([raw file](https://github.com/dgraph-io/dgraph/blob/70859515efd460686dd9ae34b0c8617f9fc330d2/tools/merge/merge_heap.cc#L122)):*
Spaces after the line, remove. It's amazing how much such effort `gofmt` saves, just like that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-:-K9xMxAYAi0W939WJw0t:-2140246568)*

**Comment by manishrjain** [comment]
Btw, for C++ style guide, follow this: https://google.github.io/styleguide/cppguide.html

---

Review status: all files reviewed at latest revision, 18 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-:-K9xOMuBlJteGbKWmw6R:268716070)*

**Comment by hackintoshrao** [comment]
*[tools/merge/merge_heap.cc, line 122 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xMhGCRhTvsZDzFbdQ:-K9yqCXWp4A42EVckHzE:-244094181) ([raw file](https://github.com/dgraph-io/dgraph/blob/70859515efd460686dd9ae34b0c8617f9fc330d2/tools/merge/merge_heap.cc#L122)):*
I agree ! 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[tools/merge/merge_heap.cc, line 122 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-K9xMhGCRhTvsZDzFbdQ:-K9yqztm_ZLIzPKgSsxc:1082584368) ([raw file](https://github.com/dgraph-io/dgraph/blob/70859515efd460686dd9ae34b0c8617f9fc330d2/tools/merge/merge_heap.cc#L122)):*
Yeah, Its hard to find spaces in the code, I'll search for a similar tool for c++ I guess

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19)*

**Comment by hackintoshrao** [comment]
@ashwin95r : What formatting tool have you used in your last commit ?

**Comment by ashwin95r** [comment]
I didn't use any tool. I just searched using `/\s\+$` in vim

---

Review status: 1 of 3 files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-:-K9yxy_D5j6VTf3P0hpX:-1986646953)*

**Comment by manishrjain** [comment]
All checks out, good work exploring both the approaches! :lgtm_strong: 

---

Reviewed 1 of 3 files at r2, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/dgraph-io/dgraph/19#-:-K9zAhx_ZFRKL5WjzngS:-814378332)*

**Comment by hackintoshrao** [comment]
This has both versions of Rocksdb merge right ?

**Comment by ashwin95r** [comment]
Yeah, merge.cc and merge_heap.cc

**Pull request merged**
