### PR TITLE
Upgrade Bleve to the latest

### PR DESCRIPTION
**Pull request by chewxy**
Upgraded Bleve to the latest version. 

https://discuss.dgraph.io/t/can-upgrade-bleve-version-to-the-latest/11673/4

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7040)

### CODE REVIEW

**Review by danielmai — COMMENTED** [review]
What changes are we bringing in here by upgrading bleve?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7040#-:-MNVNc9kE3Yt734v6bhO:bapw2vm)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ajeetdsouza, @danielmai, and @vvbalaji-dgraph)

**Comment by chewxy** [comment]
some tokenizers were updated (language tokenizers)

**Review by danielmai — COMMENTED** [review]
Do we need to document any user-facing changes?

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7040#-:-MNVVZ6bAam6eABgq3pt:bboo3zw)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ajeetdsouza, @danielmai, and @vvbalaji-dgraph)

**Comment by chewxy** [comment]
nope. Chinese works better now I think

**Comment by chewxy** [comment]
but fundamentally the functions are the same.

**Review by danielmai — APPROVED** [review]
It sounds like updating bleve generates different tokens, then? I'm ok bringing this into v20.11. Is it right that this changes the index tokens that require a re-index to create the proper tokens for language full-text indices? So, it should not be cherry-picked as patches to the current releases.

:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7040#-:-MNW07583t1X8EEChtro:b-qod2kj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ajeetdsouza and @vvbalaji-dgraph)

**Comment by chewxy** [comment]
tbqh, I've checked out some chinese tokens... it looks exactly the same to me. But the algorithms look to be less probabilistic than before. (the issue with Chinese tokenization of course, is that Chinese doesn't use spaces to delimit words, so to guess "words" as tokens you need to guess, hence probabilistic).

**Comment by chewxy** [comment]
I think we should bring this to 20.11. The current tagged Bleve is 2 years old, and in 2 years there are A LOT of advancements to tokenization tech.

**Pull request merged**
