### PR TITLE
[docs] Suggestion for disk IOPS 

### PR DESCRIPTION
**Pull request by OmarAyo**
- suggested disk IOPS (1k min and 3k for medium-large dataset)
- added info about the new aws [gp3](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/?nc1=h_ls) disk
- changed bare minimum cpu and memory to 8cpu and 16GiB mem

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7187)

### CODE REVIEW

**Review by aaroncarey — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7187)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @danielmai, @MichaelJCompton, @OmarAyo, and @slotlocker2)

___
*[wiki/content/deploy/production-checklist.md, line 28 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAXN0P8_Xnp32yoqXE:-MPAXN0P8_Xnp32yoqXF:b-klinse) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L28)):*
> ```
> should **not** run
> ```
___
*[wiki/content/deploy/production-checklist.md, line 30 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAXZpC6S627tiD9sno:-MPAXZpC6S627tiD9snp:bv0xd5i) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L30)):*
> ```
> To ensure that Dgraph can take full advantage of machine resources, we recommend that each Dgraph instance is deployed to a single dedicated machine.
> ```
___
*[wiki/content/deploy/production-checklist.md, line 34 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAXpK60g1XauEdjt-4:-MPAXpK60g1XauEdjt-5:bho69ra) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L34)):*
> ```
> shared resource issues and reduce availability
> ```
___
*[wiki/content/deploy/production-checklist.md, line 43 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAY6UcBbUluqtJxOzS:-MPAY6UcBbUluqtJxOzT:b-h20erc) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L43)):*
> ```
> a
> ```
___
*[wiki/content/deploy/production-checklist.md, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAY5kCBAubewjskDlX:-MPAY5kCBAubewjskDlY:bma3qw5) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L45)):*
> ```
> You'll want a ensure that your CPU and memory resources are sufficient for your production workload
> ```
___
*[wiki/content/deploy/production-checklist.md, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAYLbt1E456YkmJYcp:-MPAYLbu5Zsszxl4f2YP:b-al8raw) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L45)):*
> ```
> A common configuration for Dgraph
> ```
___
*[wiki/content/deploy/production-checklist.md, line 51 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAYRLb266MAobnzy3N:-MPAYRLb266MAobnzy3O:bcy509u) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L51)):*
> ```
> use
> ```

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/production-checklist.md, line 28 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAXN0P8_Xnp32yoqXE:-MPAyHkD3zdRiRZxcpDm:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L28)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> should **not** run
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/production-checklist.md, line 30 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAXZpC6S627tiD9sno:-MPAyI8-Aj8HzTHH3fBb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L30)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> To ensure that Dgraph can take full advantage of machine resources, we recommend that each Dgraph instance is deployed to a single dedicated machine.
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/production-checklist.md, line 34 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAXpK60g1XauEdjt-4:-MPAyK5k5D1-MT0qvvcA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L34)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> shared resource issues and reduce availability
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/production-checklist.md, line 43 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAY6UcBbUluqtJxOzS:-MPAyKeN38ahOH4nv9bn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L43)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> a
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/production-checklist.md, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAY5kCBAubewjskDlX:-MPAyLCK-4iRodWMQMIs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L45)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> You'll want a ensure that your CPU and memory resources are sufficient for your production workload
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/production-checklist.md, line 45 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAYLbt1E456YkmJYcp:-MPAyLYDA-ksuP6MKRE6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L45)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> A common configuration for Dgraph
> ```

</blockquote></details>

Done.

**Comment by OmarAyo** [comment]
___
*[wiki/content/deploy/production-checklist.md, line 51 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-MPAYRLb266MAobnzy3N:-MPAyM2H-2YFa4zNHlZ7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/3887f353ad087dc823e721c13a77558865b6381f/wiki/content/deploy/production-checklist.md#L51)):*
<details><summary><i>Previously, aaroncarey (aaroncarey) wrote…</i></summary><blockquote>

> ```
> use
> ```

</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7187#-:-MPBQFNs-V3Q5seeSuoU:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @aaroncarey, @MichaelJCompton, and @slotlocker2)

**Pull request merged**
