### PR TITLE
fix(GraphQL): Remove auth error from mutation.

### PR DESCRIPTION
**Pull request by arijitAD**
Fixes GRAPHQL-595
[Discuss Issue](https://discuss.dgraph.io/t/auth-errors-are-not-consistent/8870/5)
- Auth errors are only returned in debug mode which is turned off by default.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6329)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
There should be a way to set this flag through an API ideally because otherwise Slash users can't make use of it. 

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-:-MG8mK7dCvhGzravMRKS:bwbvuav)* status: all files reviewed, 4 unresolved discussions (waiting on @arijitAD, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 203 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8ls7X6aCrYhHOLoD_:-MG8ls7YCUIWG8XpCDGW:b-1eohns) ([raw file](https://github.com/dgraph-io/dgraph/blob/69f2097688b229dbf7aa83910f0d6c961634303d/dgraph/cmd/alpha/run.go#L203)):*
> ```Go
> 
> 	flag.Bool("graphql_introspection", true, "Set to false for no GraphQL schema introspection")
> 	flag.Bool("graphql_debug", false, "Enable debug_off mode in GraphQL")
> ```

Enable debug mode in GraphQL. This returns auth errors to clients. We do not reccomend turning it on for production.
___
*[graphql/e2e/auth/add_mutation_test.go, line 29 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8mVNsDViAZjq_5-H9:-MG8mVNtDNDqCNOY7GXf:b23jckm) ([raw file](https://github.com/dgraph-io/dgraph/blob/2de4675be0ba627e2b6475897b972ba2dfb4e1ba/graphql/e2e/auth/add_mutation_test.go#L29)):*
> ```Go
> )
> 
> func (us *UserSecret) delete(t *testing.T, user, role string) {
> ```

Any tests which show the behavior when `graphql_debug` is false?
___
*[graphql/e2e/auth/add_mutation_test.go, line 192 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8lZt-5xigvZqIrAtD:-MG8lZt-5xigvZqIrAtE:b9kllad) ([raw file](https://github.com/dgraph-io/dgraph/blob/69f2097688b229dbf7aa83910f0d6c961634303d/graphql/e2e/auth/add_mutation_test.go#L192)):*
> ```Go
> 		if tcase.result == "" {
> 			require.Equal(t, len(gqlResponse.Errors), 1)
> 			require.Contains(t, gqlResponse.Errors[0].Message, "authorization failed")
> ```

So we still get this error if `graphql_debug` is set to true?
___
*[x/config.go, line 37 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8mFLH16uQIRq2l-ca:-MG8mFLH16uQIRq2l-cb:bm9qtw2) ([raw file](https://github.com/dgraph-io/dgraph/blob/69f2097688b229dbf7aa83910f0d6c961634303d/x/config.go#L37)):*
> ```Go
> 	// GraphqlExtension will be set to see extensions in graphql results
> 	GraphqlExtension bool
> 	// GraphqlDebug will enable debug_off mode in GraphQL
> ```

whats debug_off mode? Shouldn't it be `debug` mode?

**Review by arijitAD — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6329)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[dgraph/cmd/alpha/run.go, line 203 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8ls7X6aCrYhHOLoD_:-MGDMrGL85yaqko1VNeb:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/69f2097688b229dbf7aa83910f0d6c961634303d/dgraph/cmd/alpha/run.go#L203)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Enable debug mode in GraphQL. This returns auth errors to clients. We do not reccomend turning it on for production.
</blockquote></details>

Done.
___
*[graphql/e2e/auth/add_mutation_test.go, line 29 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8mVNsDViAZjq_5-H9:-MGDMsoS3Ut4a7eA0sJv:b1qy1qw) ([raw file](https://github.com/dgraph-io/dgraph/blob/2de4675be0ba627e2b6475897b972ba2dfb4e1ba/graphql/e2e/auth/add_mutation_test.go#L29)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Any tests which show the behavior when `graphql_debug` is false?
</blockquote></details>

I have added E2E test here with debug mode off.
graphql/e2e/auth/debug_off/debugoff_test.go 
___
*[graphql/e2e/auth/add_mutation_test.go, line 192 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8lZt-5xigvZqIrAtD:-MGDMxhA5pQExy9vNDhe:b-vi9u8r) ([raw file](https://github.com/dgraph-io/dgraph/blob/69f2097688b229dbf7aa83910f0d6c961634303d/graphql/e2e/auth/add_mutation_test.go#L192)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

So we still get this error if `graphql_debug` is set to true?
</blockquote></details>

Yes.  If`graphql_debug`is set to true it will throw auth errors.
___
*[x/config.go, line 37 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-MG8mFLH16uQIRq2l-ca:-MGDN4fL79xkA2AHCoY7:bjc434b) ([raw file](https://github.com/dgraph-io/dgraph/blob/69f2097688b229dbf7aa83910f0d6c961634303d/x/config.go#L37)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

whats debug_off mode? Shouldn't it be `debug` mode?
</blockquote></details>

Yes. Changed it. `debug` was changed to `debug_off` when I was refactoring code in IDE.

**Review by pawanrawal — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6329)* status: all files reviewed, 1 unresolved discussion (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

**Review by arijitAD — COMMENTED** [review]
> There should be a way to set this flag through an API ideally because otherwise Slash users can't make use of it.
I will create a JIRA ticket so that we would be able to change flags using API. 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6329#-:-MGDVLecAevaAvOG-khB:b-9tesuc)* status: all files reviewed, 1 unresolved discussion (waiting on @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

**Review by pawanrawal — APPROVED** [review]

**Pull request merged**
