### PR TITLE
Expand(_all_) also expands reverse edges

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1817)

### CODE REVIEW

**Comment by pawanrawal** [comment]
:lgtm: Nice cleanup in expandEdges function.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[query/mutation.go, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXVqBRVobLNguvDU99:-KzXVqBRVobLNguvDU9A:bywd3dv) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L26)):*
> ```Go
> 			return nil, x.Wrapf(err, "While adding internal edges")
> 		}
> 		m.Edges = edges
> ```

Couldn't this have been done in expandEdges? Did you move it here to make it more explicit?

---

*[query/mutation.go, line 49 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXTLHOkywJfEtR5k5m:-KzXTLHOkywJfEtR5k5n:b8ynqsb) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L49)):*
> ```Go
> func expandEdges(ctx context.Context, m *protos.Mutations) ([]*protos.DirectedEdge, error) {
> 	edges := make([]*protos.DirectedEdge, 0, 2*len(m.Edges))
> 	for _, mu := range m.Edges {
> ```

How about calling this `edge` instead of `mu`?

---

*[query/mutation.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXUmv6pq7xYPvhVUv0:-KzXUmv6pq7xYPvhVUv1:b-texe0i) ([raw file](https://github.com/dgraph-io/dgraph/blob/4cf3a1bc434450156f9f6d4db270b84531fcb695/query/mutation.go#L58)):*
> ```Go
> 			newEdges = append(newEdges, mu)
> 			newEdges = append(newEdges, edge)
> 		} else if mu.Op == protos.DirectedEdge_DEL {
> ```

I hope rdf parser throws error when we have set operation with `S P *` and `S * *` because we don't have explicit checks here anymore. 

---

*[query/mutation.go, line 86 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXTR5WkLiE6nC5bRnz:-KzXTR5WkLiE6nC5bRo-:bvhnt12) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L86)):*
> ```Go
> 			edges = append(edges, &muCopy)
> 
> 			edge := &protos.DirectedEdge{
> ```

You can call this `e` then.

---

*[query/mutation.go, line 103 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXTwwRIN41lfmHb4mE:-KzXTwwRIN41lfmHb4mF:bubfblp) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L103)):*
> ```Go
> 			} else {
> 				plist := posting.Get(x.DataKey(pred, mu.GetEntity()))
> 				if err := plist.Iterate(m.StartTs, 0, func(p *protos.Posting) bool {
> ```

Could use `plist.Uids(opts)` here to get these uids. We use it in `worker/task.go:578`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-:-KzXXmEwxzp7bd73ZLje:b-39a3cp)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[query/mutation.go, line 26 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXVqBRVobLNguvDU99:-KzXcMff6xxnTJeG7ESh:b25z40j) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L26)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Couldn't this have been done in expandEdges? Did you move it here to make it more explicit?
</blockquote></details>

Yeah, I moved this out to make it more explicit.

---

*[query/mutation.go, line 49 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXTLHOkywJfEtR5k5m:-KzXctBJzURAUaEc5DHQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L49)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

How about calling this `edge` instead of `mu`?
</blockquote></details>

Done.

---

*[query/mutation.go, line 86 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXTR5WkLiE6nC5bRnz:-KzXcxHXqRUpe3xALJcg:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L86)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

You can call this `e` then.
</blockquote></details>

Done.

---

*[query/mutation.go, line 103 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXTwwRIN41lfmHb4mE:-KzXfqlhc5vObxZh7eA2:bu6lg2o) ([raw file](https://github.com/dgraph-io/dgraph/blob/048a8b21501fb0dc0f1256a761515faa49a70ba3/query/mutation.go#L103)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Could use `plist.Uids(opts)` here to get these uids. We use it in `worker/task.go:578`
</blockquote></details>

Done. Nice suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817)*

**Comment by peterstace** [comment]
Review status: 7 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[query/mutation.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXUmv6pq7xYPvhVUv0:-KzXgkR-U29YEPmLrqxF:bp6atpy) ([raw file](https://github.com/dgraph-io/dgraph/blob/4cf3a1bc434450156f9f6d4db270b84531fcb695/query/mutation.go#L58)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I hope rdf parser throws error when we have set operation with `S P *` and `S * *` because we don't have explicit checks here anymore. 
</blockquote></details>

Ah, yes we have lost that, I had assumed it was checked earlier. I'll add some checks to the RDF parser. Probably makes sense to check `* P *` for deletes as well so it's all in the same place?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817)*

**Comment by pawanrawal** [comment]
Review status: 7 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/mutation.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXUmv6pq7xYPvhVUv0:-KzXiOv6KRLW5Ec_zdpG:btio0ro) ([raw file](https://github.com/dgraph-io/dgraph/blob/4cf3a1bc434450156f9f6d4db270b84531fcb695/query/mutation.go#L58)):*
<details><summary><i>Previously, peterstace (Peter Stace) wrote…</i></summary><blockquote>

Ah, yes we have lost that, I had assumed it was checked earlier. I'll add some checks to the RDF parser. Probably makes sense to check `* P *` for deletes as well so it's all in the same place?
</blockquote></details>

Yeah `* P *` for delete can just return an error from parser ideally.

---

*[query/mutation.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXizT5W1G19z0hUdDh:-KzXizT6blCVJhfu-AK0:bgvx8d6) ([raw file](https://github.com/dgraph-io/dgraph/blob/262956d693c3c8f75502d697d30d4de366f32558/query/mutation.go#L94)):*
> ```Go
> 			edges = append(edges, e)
> 
> 			if !schema.State().IsReversed(pred) {
> ```

Slight issue here, schema for all predicates isn't stored on all nodes. A server only stores schema for predicates belonging to groups served by it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817)*

**Comment by peterstace** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/mutation.go, line 58 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXUmv6pq7xYPvhVUv0:-Kza6QO5_0TqE1azv0dX:b4dvsni) ([raw file](https://github.com/dgraph-io/dgraph/blob/4cf3a1bc434450156f9f6d4db270b84531fcb695/query/mutation.go#L58)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Yeah `* P *` for delete can just return an error from parser ideally.
</blockquote></details>

Done. Added some checking just after we get the RPC call. We can't check directly in the parser, since we don't know del vs set there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817)*

**Comment by peterstace** [comment]
Review status: 7 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/mutation.go, line 94 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzXizT5W1G19z0hUdDh:-KzaTu6lEGB_-APt0r41:b-gi7hxy) ([raw file](https://github.com/dgraph-io/dgraph/blob/262956d693c3c8f75502d697d30d4de366f32558/query/mutation.go#L94)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Slight issue here, schema for all predicates isn't stored on all nodes. A server only stores schema for predicates belonging to groups served by it.
</blockquote></details>

Summary of discussion we had about this: there were two obvious solutions to work around this. 1. share schema across all groups. This has difficulties to do with consistency since only groups are internally consistent. 2. Do the reverse `_predicate_` maintenance is in the group that servers the predicate. This has the drawback that additional network hops will be required for all mutations.

Instead of these, I'm going to attempt to expand the reverse edges directly from within the query. If they don't exist, then they won't show up in the result. This will slow down expand(_all_), but since this operation is mainly used for exploring data rather than in a production setup, this won't matter as much.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817)*

**Comment by pawanrawal** [comment]
:lgtm: 

---

Review status: 2 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[edgraph/server.go, line 834 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzbPPnGXex7ooHWS4HP:-KzbPPnGXex7ooHWS4HQ:b-989eiy) ([raw file](https://github.com/dgraph-io/dgraph/blob/20cd971a2ceb6cad3b2af2f2e06ce4d78bc81491/edgraph/server.go#L834)):*
> ```Go
> 			ostar = o.DefaultVal == x.Star
> 		}
> 		if nq.Subject == x.Star || nq.Predicate == x.Star || ostar {
> ```

Could do `nq.ObjectValue.DefaultVal == x.Star` here I suppose.

---

*[query/query.go, line 1745 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzbRh0CYB4K9ThM4V6F:-KzbRh0D_ckplnSTke3T:b-j4l3hr) ([raw file](https://github.com/dgraph-io/dgraph/blob/20cd971a2ceb6cad3b2af2f2e06ce4d78bc81491/query/query.go#L1745)):*
> ```Go
> 				return out, err
> 			}
> 			rpreds, err := getReversePredicatesOverNetwork(ctx)
> ```

can be renamed to getReversePredicates because we don't directly fetch reverse predicates over network. We fetch schema and filter reverse predicates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-:-KzbS0DTKAn4uJPVjBj7:bg7igkv)*

**Comment by peterstace** [comment]
Review status: 1 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[edgraph/server.go, line 834 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzbPPnGXex7ooHWS4HP:-KzbVFyoXTwk25dKy4Vb:b-snmm6u) ([raw file](https://github.com/dgraph-io/dgraph/blob/20cd971a2ceb6cad3b2af2f2e06ce4d78bc81491/edgraph/server.go#L834)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Could do `nq.ObjectValue.DefaultVal == x.Star` here I suppose.
</blockquote></details>

We can't really do that because we use `oneof`, so we end up with an interface that we have to do an assertion on.

---

*[query/query.go, line 1745 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817#-KzbRh0CYB4K9ThM4V6F:-KzbUwNokMOuMTci6Ds4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/20cd971a2ceb6cad3b2af2f2e06ce4d78bc81491/query/query.go#L1745)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

can be renamed to getReversePredicates because we don't directly fetch reverse predicates over network. We fetch schema and filter reverse predicates.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1817)*

**Pull request merged**
