### PR TITLE
fix #826

### LINKED ISSUE #826: Could not parse the facet value : [DOMAIN]
```
func CreateStringFacet(key string, val string) *facets.Facet {
    fVal := &types.Val{Tid: types.BinaryID}
    if err := types.Marshal(types.Val{Tid: types.StringID, Value: val}, fVal); err != nil {
        log.Println(err)
    }

    fval, ok := fVal.Value.([]byte)
    if !ok {
        log.Println("Error while marshalling types.Val into binary.")
    }
    v := &facets.Facet{Key: key, Value: fval, ValType: facets.Facet_STRING}
    return v
}

edgeProperties := []*facets.Facet{}
    v := helper_traits.CreateStringFacet("CONNECTION_scope", entity.Type.String())
    edgeProperties = append(edgeProperties, v)

nq := graph.NQuad{
            Subject:   entity.Id,
            Predicate: "ENTITY_withProfileContext",
            ObjectId:  c.Profile.Id,
            Facets:    edgeProperties,
        }
        req.AddMutation(nq, client.SET)

        nq = graph.NQuad{
            Subject:   c.Profile.Id,
            Predicate: "PROFILE_withEntityContext",
            ObjectId:  entity.Id,
            Facets:    edgeProperties,
        }
        req.AddMutation(nq, client.SET)

{  var(id: 9fd35c4bca335b24) { EP as ENTITY_withProfileContext (first: 1000) {  A as PROFILE_withEntityContext @facets(eq(CONNECTION_scope, "DOMAIN")) ...
```

### PR DESCRIPTION
**Pull request by janardhan1993**
Facet is converted to appropriate type based on stored facet(since we don't have schema for facets and function arguments are string in gql query).

@facet(tag,"34") - used to match only int 34 earlier. Now it will match both int 34 and String 34(based on stored facet).

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/875)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[types/facets/utils.go, line 158 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/875#-KiUVVTpFLKgcymCQoPA:-KiUVVTqJGhvlcxUjCAM:b-roqltn) ([raw file](https://github.com/dgraph-io/dgraph/blob/e22a289f400f6ac6bb8e1f65e593291b9133d68e/types/facets/utils.go#L158)):*
> ```Go
> 		return t, err
> 	}
> 	if t, err := time.Parse(dateTimeFormat, val); err == nil {
> ```

We shouldn't allow storing "2016-05-03" as facet values, because they are being stored as date time.

Now on querying for @facet(eq(since,"2016-05-03")), we will try to parse "2016-05-03" as date time which would fail since underlying value is stored as date time. 

I think we should either add dateId type to facets, so modify our types.conversion to parse "2016-05-03" as date time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/875)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[rdf/parse_test.go, line 663 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/875#-KihbfOimv24lLG1_iLd:-KihbfOimv24lLG1_iLe:bxgq9et) ([raw file](https://github.com/dgraph-io/dgraph/blob/07480709a68faf5272383cbfdcdbfc7288b3d049/rdf/parse_test.go#L663)):*
> ```Go
> 	// Should parse dates
> 	{
> 		input: `_:alice <knows> "stuff" (key1=2002-10-02T15:00:00.05Z, key2=2006-01-02T15:04:05, key3=2006-01-02T00:00:00Z) .`,
> ```

Even the predicate data types would only have one type for dates, i.e. DateTime.

"2006-11" == "2006-11-24T02:09:03".

---

*[types/facets/utils.go, line 158 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/875#-KiUVVTpFLKgcymCQoPA:-KihcHVLynOTQXya9I5H:b-9h05xi) ([raw file](https://github.com/dgraph-io/dgraph/blob/e22a289f400f6ac6bb8e1f65e593291b9133d68e/types/facets/utils.go#L158)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We shouldn't allow storing "2016-05-03" as facet values, because they are being stored as date time.

Now on querying for @facet(eq(since,"2016-05-03")), we will try to parse "2016-05-03" as date time which would fail since underlying value is stored as date time. 

I think we should either add dateId type to facets, so modify our types.conversion to parse "2016-05-03" as date time.
</blockquote></details>

We should allow storing "2016-05-03" as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/875#-:-KihcMW7SSnauHLXXa1S:bnfp4nl)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[rdf/parse_test.go, line 663 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/875#-KihbfOimv24lLG1_iLd:-KihsWf8Y7NBQHAUbTaB:b-j5j6b4) ([raw file](https://github.com/dgraph-io/dgraph/blob/07480709a68faf5272383cbfdcdbfc7288b3d049/rdf/parse_test.go#L663)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Even the predicate data types would only have one type for dates, i.e. DateTime.

"2006-11" == "2006-11-24T02:09:03".
</blockquote></details>

Will Do in separate PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/875)*

**Comment by janardhan1993** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[types/facets/utils.go, line 158 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/875#-KiUVVTpFLKgcymCQoPA:-KihuDr84unlpUX5GUsV:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/e22a289f400f6ac6bb8e1f65e593291b9133d68e/types/facets/utils.go#L158)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

We should allow storing "2016-05-03" as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/875)*

**Pull request merged**
