### PR TITLE
Chore(Other|contrib): Fix Ratel refs.

### LINKED ISSUE #8386: [BUG]: Deployment with dgraph-single on Kubernetes is broken
### What version of Dgraph are you using?

Latest

### Tell us a little more about your go-environment?

Not relevant

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Not relevant

### What steps will reproduce the bug?

1. Follow the instruction here: https://dgraph.io/docs/deploy/kubernetes/#deploy-single-server
2. Run

    ```
    kubectl create --filename https://raw.githubusercontent.com/dgraph-io/dgraph/main/contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
    ```
 
 3. See the error: `kubectl get pods`

     ```
    $ kubectl get pods 
    NAME       READY   STATUS             RESTARTS     AGE
    dgraph-0   2/3     CrashLoopBackOff   1 (6s ago)   39s
    ```

### Expected behavior and actual result.

Expected behavior: The pod should be running.
Actual result: CrashLoopBackOff

```
  Normal   Created    13s (x2 over 14s)  kubelet            Created container ratel
  Warning  Failed     13s (x2 over 14s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dgraph-ratel": executable file not found in $PATH: unknown
  Normal   Pulled     13s                kubelet            Container image "dgraph/dgraph:latest" already present on machine
  Warning  BackOff    11s (x2 over 12s)  kubelet            Back-off restarting failed container

```

The problem seems to be that dgraph-ratel is not found. It's not included in `dgraph/dgraph:latest` image. Instead, it should probably use `dgraph/ratel` instead.

### Additional information

If you agree that this should be fixed, I'm interested to open a PR. If this is not the appropriate place to report this, please let me know the correct one.

### PR DESCRIPTION
**Pull request by MichelDiz**
## Problem

Users are having trouble starting some YML created in our documentation. Where a dgraph/dgraph:$Version container starts, which no longer has the Ratel binary.

## Solution

I'm correctly arranging the tag images for Ratel.

Fix #8386

### CODE REVIEW

**Comment by skrdgraph** [comment]
@MichelDiz https://github.com/dgraph-io/dgraph/issues/8386#issuecomment-1295768114 <- I left this as a comment here. 

I think we should align the deployments into k8s correctly in a standardized approach. The current methods are slightly broken. This fix really doesn't address the core problem the user is reporting.

The users issue is because `dgraph-ratel` is not packaged into the docker image*. It was NEVER packaged by the last team for last few releases they made. 

I vote to close this PR. I think I have a decent understanding of this issue, and I can explain this over a quick sync call (if you are up for it). The fix for this is a little more involved, but it will need to get reflected in our code & docs correctly. Do you want to find some time for this on my calendar?

**Comment by MichelDiz** [comment]
I think there are two separate issues. You are plaining solving another problem and I am solving another. Align K8s the deployments is one thing, and modifying the image of what Ratel refers to is quite another. Note that I'm just changing the image tag. From `dgraph/dgraph:latest` to `dgraph/ratel:latest`.

I faithfully believe that PR addresses the issue. I'm gonna explain.

dgraph-ratel binary, has been completely removed from the main binary build process(pipeline). It was built and embedded in tar in the past. And consequently installed together in /bin - be it in the docker image or via script.

There's a PR that does almost the exact same thing I'm doing in this PR here. But as we go back to 03.21, this PR did not enter, as it was merged later.

>It was NEVER packaged by the last team

This is a misinterpretation. I've seen this change happen and these same problems appear back then. See https://github.com/dgraph-io/dgraph/pull/7738

**Comment by joshua-goldstein** [comment]
@MichelDiz 

> I think there are two separate issues. You are plaining solving another problem and I am solving another. Align K8s the deployments is one thing, and modifying the image of what Ratel refers to is quite another. Note that I'm just changing the image tag. From `dgraph/dgraph:latest` to `dgraph/ratel:latest`.
> 
> I faithfully believe that PR addresses the issue. I'm gonna explain.
> 
> dgraph-ratel binary, has been completely removed from the main binary build process(pipeline). It was built and embedded in tar in the past. And consequently installed together in /bin - be it in the docker image or via script.
> 
> There's a PR that does almost the exact same thing I'm doing in this PR here. But as we go back to v21.03, this PR did not enter, as it was merged later.
> 
> > It was NEVER packaged by the last team
> 
> This is a misinterpretation. I've seen this change happen and these same problems appear back then. See #7738

@MichelDiz They are two separate but related issues - the changes made in this PR also affect k8s deployments, which are currently being worked on.  As a side effect of that work, this will get cleaned up.  Instead of racing to get this functional (and push something untested) we should configure everything the right way.  Otherwise other issues may come up.

The [PR you referenced](https://github.com/dgraph-io/dgraph/pull/7738/files#diff-b62228be34189e02924dc34af788cc86127956b6e45ecb526117d46d202eb2a8) is interesting because in that PR they totally removed ratel from the k8s deployments, which is different from what this PR is doing.

**Comment by MichelDiz** [comment]
>in that PR they totally removed ratel from the k8s deployments, which is different from what this PR is doing.

Exactly. The old team's intention was to abandon Ratel and they don't have a dashboard console. I'm holding on until someone says "let's abandon it or not". The user is using a yaml that this change has not been applied. However, we are not building Ratel so it fails into that issue. That's the problem with this issue. There is no other.


@joshua-goldstein Well I don't know what you guys are working on. But the issue with issue #8386 is exactly what I'm dealing with. What you guys are doing can be dealt with in another PR. Right? It makes no sense to keep a blocker here because you have other plans. Unless you guys also made the decision not to use Ratel Dashboard.

The issue says in the logs "`container process: exec: "dgraph-ratel": executable file not found in $PATH:`" - This is due to the missing binary that was removed months ago from the main binary. The solution to this is just to change the image used in Ratel.

>and push something untested

I have tested. It is easy to test. Just have K8s. And run

```
kubectl create --filename https://raw.githubusercontent.com/dgraph-io/dgraph/micheldiz/fixRatelRefs/contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
````

If you need to run a k8s cluster you can use this one via docker https://github.com/k3s-io/k3s/blob/master/docker-compose.yml

It is working just fine.

**Review by skrdgraph — APPROVED** [review]
Looks good. thanks for the discussion!

**Review by joshua-goldstein — APPROVED** [review]
Looks good!  In the future we will review how we are suggesting people deploy clusters.

**Pull request merged**
