### PR TITLE
Feat(GraphQL): This PR adds parameterised cascade in graphql.

### PR DESCRIPTION
**Pull request by JatinDevDG**
This PR adds parameterised cascade in graphql. We can now specify individual fields in @cascade.
```
query {
  queryperson @cascade(fields: ["name"]){
    id 
    name
    Friends @cascade(fields: ["name1"]) {
      id
      name1
    }
  }
} 
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)

 
 

Docs Preview: [Dgraph Preview](https://dgraph-5faeb57275-87893.surge.sh)

### CODE REVIEW

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: 2 of 44 files reviewed, 10 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/dgraph/graphquery.go, line 77 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFEqnH860XIr0SVuyeB:-MFFf5i4BwmeKQMpQGGF:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/dgraph/graphquery.go#L77)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Can you add a space after the comma so that the rewritten queries look better.

```
x.Check2(b.WriteString(strings.Join(query.Cascade,", ")))
```
</blockquote></details>

done.
___
*[graphql/e2e/common/query.go, line 1845 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFErdBACgZx5JLTJ3Nv:-MFFgeT73u7X_r9KzriC:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/e2e/common/query.go#L1845)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

this isn't well indented
</blockquote></details>

done.
___
*[graphql/e2e/common/query.go, line 1927 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFErLcsBhUFrhKqA2CH:-MFFh8NP4YiA1hVQIw71:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/e2e/common/query.go#L1927)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

extra spaces, remove please. Also format the JSON properly.
</blockquote></details>

done.
___
*[graphql/resolve/query_test.yaml, line 747 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFF13j_DLMcSkpCStj8:-MFGL4kn0bOdIxTbiGs2:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/resolve/query_test.yaml#L747)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

we should also add similar tests in `mutation_query_test.yml`, so we are sure that mutation queries are also rewritten properly.
</blockquote></details>

done.
___
*[graphql/resolve/query_test.yaml, line 750 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFEsq9a3E7kYntT36x8:-MFUZyJDC35UWYz3Kxwz:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/resolve/query_test.yaml#L750)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add these test cases.
1. Add a case where you have cascade with one of the fields being of `ID` type. 
2. Add a case where one of the fields within cascade belongs to an inteface that the type implements
3. Add a case where you query for an interface and then use cascade
</blockquote></details>

done.
___
*[graphql/schema/gqlschema.go, line 135 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFErjXtB6uKXzVbS10b:-MFUZwkGAGpzM0eNT8DM:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/schema/gqlschema.go#L135)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`fields:  [String]` space after `:` not before
</blockquote></details>

done
___
*[graphql/schema/validation_rules.go, line 70 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFF-QV57ospO30u0vfi:-MFU_17R195J8VzkjJyg:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/schema/validation_rules.go#L70)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "cascade"
> ```
we have a const in schema package called `cascadeDirective` which can be reused instead of creating this string here.
</blockquote></details>

changed.
___
*[graphql/schema/validation_rules.go, line 71 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFF0aDw8pmbNJ-C-7zt:-MFU_2l0A3G-3TAy_VaS:b-b5c35t) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/schema/validation_rules.go#L71)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "fields"
> ```
the `fields` argument should also be declared as a constant like `cascadeDirective` and then reused everywhere it is needed.
</blockquote></details>

changed.
___
*[graphql/schema/wrappers.go, line 682 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFEsGRPDF_I4dQ5qb6I:-MFU_4OU84_nW8tzaLO0:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/schema/wrappers.go#L682)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Pre allocate slice of correct length to avoid multiple allocations
```
fields := make([]string, 0, len(arg.Value.Children)
```
</blockquote></details>

done.
___
*[graphql/schema/wrappers.go, line 683 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFEs5iV6bNXjzjOxIAe:-MFU_DRZ4YjfClPb2MH6:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/schema/wrappers.go#L683)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This code isn't formatted properly. Please run `gofmt` on it and your editor should be setup to run it automatically on save.
</blockquote></details>

done.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 42 of 43 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: all files reviewed, 12 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[graphql/e2e/common/error_test.yaml, line 119 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZVwqZAl68mq7ED8Rw:-MFZVwq_-MNcFeRU9QZt:b-keaf3y) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/error_test.yaml#L119)):*
> ```YAML
> 
> -
>   name: "@cascade only accepts numUids or given type name as arguments for add or update payload "
> ```

Ok, so it also accepts numUids? Is there a test for that?
___
*[graphql/e2e/common/error_test.yaml, line 125 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZVu164KmbDlFvTVWS:-MFZVu164KmbDlFvTVWT:biqinsc) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/error_test.yaml#L125)):*
> ```YAML
>         author {
>           name
>             }
> ```

fix the formatting here
___
*[graphql/e2e/common/query.go, line 1845 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFErdBACgZx5JLTJ3Nv:-MFZYe9yEfqbTXWkqfQz:bg3uw7) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/e2e/common/query.go#L1845)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

done.
</blockquote></details>

still not very well intended, do you do it manually?
___
*[graphql/e2e/common/query.go, line 1911 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZYcpH1Yr7L2xzoXZg:-MFZYcpH1Yr7L2xzoXZh:b2nicjn) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L1911)):*
> ```Go
> 								 "name":"Kramer",
>                                  "reputation": null,
> 								"country": {
> ```

sti
___
*[graphql/e2e/common/query.go, line 2003 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZWG2VCQcEBZF72iPx:-MFZWG2VCQcEBZF72iPy:bdvlsrp) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L2003)):*
> ```Go
>                                  "dob": null
> 							}, {
>                                   "dob": null,
> ```

JSON is badly formatted here
___
*[graphql/e2e/common/query.go, line 2013 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZYFwwBVL6_JVbgGuC:-MFZYFwwBVL6_JVbgGuD:b-puogol) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L2013)):*
> ```Go
> 			query: `query  {
> 					  queryHuman() @cascade(fields:["name"]) {
>                       name
> ```

bad formatting, name and total credits are not indented
___
*[graphql/e2e/common/query.go, line 2031 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZWPDe17MlG-sEC8hH:-MFZWPDe17MlG-sEC8hI:b-l2xbg7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L2031)):*
> ```Go
>                         	name
>                             appearsIn
>                			} 
> ```

again badly formatted
___
*[graphql/resolve/query_test.yaml, line 750 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFEsq9a3E7kYntT36x8:-MFZYYiVDfh8jWcT4Zsb:b-sjidlz) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/resolve/query_test.yaml#L750)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

done.
</blockquote></details>

I don't see the interface queries here
___
*[graphql/resolve/query_test.yaml, line 964 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZY4BW3NeGp3RZykds:-MFZY4BX1Aa5xHmVqZlJ:b4gituc) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/resolve/query_test.yaml#L964)):*
> ```YAML
>         dob
>         reputation
>         posts @cascade(fields:["text","title"]) {
> ```

What if you add `id` here, does it work then?
___
*[graphql/schema/wrappers.go, line 760 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZXmM-EUUp-Fp6qQft:-MFZXmM-EUUp-Fp6qQfu:bp5eu1w) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/schema/wrappers.go#L760)):*
> ```Go
> 	typ := f.Type()
> 	var idField string
> 	if f.field.ObjectDefinition.Name == "Query" {
> ```

Is this if blocked needed?

**Review by abhimanyusinghgaur — CHANGES_REQUESTED** [review]
> Reviewed 1 of 43 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: all files reviewed, 13 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[graphql/e2e/common/query.go, line 1972 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZYd0vBiDh6fzaIH9z:-MFZYd0w86MXBgjY_Wv3:btr7xrl) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L1972)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> "reputation": 4.5,
> 								 "name":"George",
>                                  "dob": null,
> 								"posts": [{
> 									"title": "A show about nothing",
> 									"text": "Got ya!"
> 								}]
> ```
</details>


still unaligned it seems

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: 43 of 45 files reviewed, 13 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/e2e/common/error_test.yaml, line 119 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZVwqZAl68mq7ED8Rw:-MFZdGTS-5vG8Bi-pICz:bk0yz46) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/error_test.yaml#L119)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Ok, so it also accepts numUids? Is there a test for that?
</blockquote></details>

yeah, if you give typename or numUids, cascade without parameters is forwarded to query field of mutaton. There is unit test for it.
___
*[graphql/e2e/common/error_test.yaml, line 125 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZVu164KmbDlFvTVWS:-MFZvO_-0om8rRZMPDq9:b-dbvzxr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/error_test.yaml#L125)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

fix the formatting here
</blockquote></details>

fixed the formatting of all the e2e tests.
___
*[graphql/e2e/common/query.go, line 1845 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFErdBACgZx5JLTJ3Nv:-MFZvUKsC2MRYXXGvTAG:b-e1gbym) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/e2e/common/query.go#L1845)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

still not very well intended, do you do it manually?
</blockquote></details>

yeah, i got confused because in IDE it was properly formated.
___
*[graphql/resolve/query_test.yaml, line 750 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFEsq9a3E7kYntT36x8:-MFZctmwEHGemZi9NKtM:b-ui6vlq) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/resolve/query_test.yaml#L750)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

I don't see the interface queries here
</blockquote></details>

ohh, i added them in e2e. i will add those here also.
___
*[graphql/resolve/query_test.yaml, line 964 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZY4BW3NeGp3RZykds:-MFZcNLcBoVPfeagl73S:brwnki1) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/resolve/query_test.yaml#L964)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What if you add `id` here, does it work then?
</blockquote></details>

no, post doesn't have id field, so it will give error. PostID will work.
___
*[graphql/schema/wrappers.go, line 760 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZXmM-EUUp-Fp6qQft:-MFZbVs52YeMMxTQgbKj:b-yw0u7d) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/schema/wrappers.go#L760)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Is this if blocked needed?
</blockquote></details>

yes it is needed, because  for add or update payload ,we don't have id field.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: 42 of 45 files reviewed, 13 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/resolve/query_test.yaml, line 750 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFEsq9a3E7kYntT36x8:-MF_MuN_8reLIWSUQ27Z:b9frves) ([raw file](https://github.com/dgraph-io/dgraph/blob/db9f3008f92bddd8625a2b58c01e546cdd0b1349/graphql/resolve/query_test.yaml#L750)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

ohh, i added them in e2e. i will add those here also.
</blockquote></details>

added unit tests.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: 40 of 45 files reviewed, 13 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/schema/wrappers.go, line 760 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZXmM-EUUp-Fp6qQft:-MF_eDTwDbZHwy4te2eE:b-bfgqn1) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/schema/wrappers.go#L760)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

yes it is needed, because  for add or update payload ,we don't have id field.
</blockquote></details>

yeah, you were right, we don't need this if block. if id is not present  idField will be empty.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: 40 of 45 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/schema/wrappers.go, line 760 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZXmM-EUUp-Fp6qQft:-MF_qVTA6TablQTcK7G0:b163zf7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/schema/wrappers.go#L760)):*
<details><summary><i>Previously, JatinDevDG (Jatin Dev) wrote…</i></summary><blockquote>

yeah, you were right, we don't need this if block. if id is not present  idField will be empty.
</blockquote></details>

do you have a test for a case where you have cascade and id field is not present on the type?

**Comment by JatinDevDG** [comment]
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)_ status: 40 of 45 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)
> 
> _[graphql/schema/wrappers.go, line 760 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZXmM-EUUp-Fp6qQft:-MF_qVTA6TablQTcK7G0:b163zf7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/schema/wrappers.go#L760)):_
> 
> Previously, JatinDevDG (Jatin Dev) wrote…
> do you have a test for a case where you have cascade and id field is not present on the type?

Not for id,  but we have test which checks that field in cascade argument should be present in given type.This check is done at validation time.

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: 40 of 47 files reviewed, 8 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/e2e/common/query.go, line 1911 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZYcpH1Yr7L2xzoXZg:-MFe5HSVCwTAwHUazKql:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L1911)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

sti
</blockquote></details>

done.
___
*[graphql/e2e/common/query.go, line 1972 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZYd0vBiDh6fzaIH9z:-MFe5ImsDPCBV9_ZaSlF:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L1972)):*
<details><summary><i>Previously, abhimanyusinghgaur (Abhimanyu Singh Gaur) wrote…</i></summary><blockquote>

> ```
> "reputation": 4.5,
> 								 "name":"George",
>                                  "dob": null,
> 								"posts": [{
> 									"title": "A show about nothing",
> 									"text": "Got ya!"
> 								}]
> ```

still unaligned it seems
</blockquote></details>

done.
___
*[graphql/e2e/common/query.go, line 2003 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZWG2VCQcEBZF72iPx:-MFe5JkC4Zef7awDoT_k:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L2003)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

JSON is badly formatted here
</blockquote></details>

done.
___
*[graphql/e2e/common/query.go, line 2013 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZYFwwBVL6_JVbgGuC:-MFe5Khf2VXfgfOsGkhA:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L2013)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

bad formatting, name and total credits are not indented
</blockquote></details>

done.
___
*[graphql/e2e/common/query.go, line 2031 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFZWPDe17MlG-sEC8hH:-MFe5LYr2uDZHYjoAXo6:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a4110afe0b6914f6d5b2256955666fa3a88cb112/graphql/e2e/common/query.go#L2031)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

again badly formatted
</blockquote></details>

done.

**Review by pawanrawal — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 5 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-:-MFe6QtT8J8SvLaCxhWj:bg7igkv)* status: all files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @JatinDevDG, @manishrjain, @MichaelJCompton, and @vvbalaji-dgraph)

___
*[graphql/resolve/mutation_query_test.yaml, line 302 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFe4xhp1rdKqKbw4-bz:-MFe4xhp1rdKqKbw4-c-:bcj58ki) ([raw file](https://github.com/dgraph-io/dgraph/blob/6d3b461c9cf8aa522c8970d24ed5f9db8a947a66/graphql/resolve/mutation_query_test.yaml#L302)):*
> ```YAML
>     gqlquery: |
>       mutation {
>         ADD_UPDATE_MUTATION {
> ```

What happens if you apply @cascade here with `id` field, would that be an error?
___
*[graphql/schema/validation_rules.go, line 78 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFe5pgY5ERjXuqw6avM:-MFe5pgZ0UCC-YZx9-ft:b-r9fy4i) ([raw file](https://github.com/dgraph-io/dgraph/blob/6d3b461c9cf8aa522c8970d24ed5f9db8a947a66/graphql/schema/validation_rules.go#L78)):*
> ```Go
> 				return
> 			}
> 			dir := directive.ParentDefinition.Fields
> ```

```
fields := directive.
```
dir is not the right name

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6251)* status: 46 of 47 files reviewed, 6 unresolved discussions (waiting on @abhimanyusinghgaur, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[graphql/resolve/mutation_query_test.yaml, line 302 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFe4xhp1rdKqKbw4-bz:-MFe7I1R3Ps4ezYNrYWg:b92s1kn) ([raw file](https://github.com/dgraph-io/dgraph/blob/6d3b461c9cf8aa522c8970d24ed5f9db8a947a66/graphql/resolve/mutation_query_test.yaml#L302)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

What happens if you apply @cascade here with `id` field, would that be an error?
</blockquote></details>

yes.Anything apart from "numUids" and "post" in this case will return error.
___
*[graphql/schema/validation_rules.go, line 78 at r5](https://reviewable.io/reviews/dgraph-io/dgraph/6251#-MFe5pgY5ERjXuqw6avM:-MFe9vJ55U5oOtNRivx1:bcbh3b2) ([raw file](https://github.com/dgraph-io/dgraph/blob/6d3b461c9cf8aa522c8970d24ed5f9db8a947a66/graphql/schema/validation_rules.go#L78)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

```
fields := directive.
```
dir is not the right name
</blockquote></details>

changed to typFields.

**Pull request merged**
