### PR TITLE
Fix(GraphQL): This PR fix multi cors and multi schema nodes issue by selecting one of the latest added nodes, and add dgraph type to cors.

### PR DESCRIPTION
**Pull request by JatinDevDG**
Fixes GRAPHQL-948
We already fixed the issue which causes dgraph to have multiple schema or cores nodes. But there are some cases in which this bug can occur again, for example, someone restored a backup that was taken before the fix. This bug continuously fill the logs on alpha and blocks graphql layer. Then we can't do mutate/query or add schema.

Now, we are changing this behavior, if we have multiple schema or cores nodes then we will select the one which was added last.
In addition to it, we are adding `dgraph.type.cors type` to to the `dgraph.cors` node, which allow us to use `delete (S * *)` type mutation on it, in case we want to delete extra node manually.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7270)

### CODE REVIEW

**Review by abhimanyusinghgaur — COMMENTED** [review]
Let's discuss with @pawanrawal if we should use the max node in case we encounter more than one node.

> Reviewed 10 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-:-MQq1b4M7znz44YP98_x:ba863yk)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/graphql.go, line 150 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq0wYeAVtkk-1dGDhk:-MQq0wYfAPSEeBJCMdFr:bqnpiq7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/graphql.go#L150)):*
> ```
> glog.Infof("
> ```
`Errorf`
and again I don't feel we should do this. If this happens that means there is some other issue, which we should fix. Or if it happens due to older backups we should have a way to migrate from those which we already have. So, this feels like it should still return an error if we get either 0 or more than 1 node.
___
*[edgraph/server.go, line 177 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq-VSSCA1m_Qjal8vl:-MQq-VSSCA1m_Qjal8vm:b-l6zetr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/server.go#L177)):*
> ```
> if uidMax < schNode.Uid {
> ```
uid here is a string. Shouldn't we first convert it to int and then compare?
Because, even the difference of `A` and `a` can make it go wrong right now.
___
*[edgraph/server.go, line 182 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq-vnA4jm24jKiibKu:-MQq-vnA4jm24jKiibKv:bkb07ql) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/server.go#L182)):*
> ```Go
> 		}
> 	}
> 	glog.Infof("Multiple schema node found,returning last added node")
> ```

This is supposed to be an error state, so we should use `glog.Errorf`.

But, it doesn't feel like we should make it return the max node instead of giving an error. Such states should never be achieved and we also haven't seen any evidence for GraphQL schema case where two nodes have been seen after the fixes done long back.
So, I believe that we should still return an error because we need to know if such thing happens, instead of just ignoring it.

**Comment by JatinDevDG** [comment]
> Let's discuss with @pawanrawal if we should use the max node in case we encounter more than one node.
> 
> > Reviewed 10 of 15 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-:-MQq1b4M7znz44YP98_x:ba863yk)_ status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)
> 
> _[edgraph/graphql.go, line 150 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq0wYeAVtkk-1dGDhk:-MQq0wYfAPSEeBJCMdFr:bqnpiq7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/graphql.go#L150)):_
> 
> > ```
> > glog.Infof("
> > ```
> 
> `Errorf`
changed.
> and again I don't feel we should do this. If this happens that means there is some other issue, which we should fix. Or if it happens due to older backups we should have a way to migrate from those which we already have. So, this feels like it should still return an error if we get either 0 or more than 1 node.
> 
> _[edgraph/server.go, line 177 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq-VSSCA1m_Qjal8vl:-MQq-VSSCA1m_Qjal8vm:b-l6zetr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/server.go#L177)):_
> 
> > ```
> > if uidMax < schNode.Uid {
> > ```
> 
> uid here is a string. Shouldn't we first convert it to int and then compare?
> Because, even the difference of `A` and `a` can make it go wrong right now.
> 
> _[edgraph/server.go, line 182 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq-vnA4jm24jKiibKu:-MQq-vnA4jm24jKiibKv:bkb07ql) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/server.go#L182)):_
> 
> > ```go
> > 		}
> > 	}
> > 	glog.Infof("Multiple schema node found,returning last added node")
> > ```
> 
> This is supposed to be an error state, so we should use `glog.Errorf`.
changed.
> But, it doesn't feel like we should make it return the max node instead of giving an error. Such states should never be achieved and we also haven't seen any evidence for GraphQL schema case where two nodes have been seen after the fixes done long back.
> So, I believe that we should still return an error because we need to know if such thing happens, instead of just ignoring it.

**Comment by JatinDevDG** [comment]
> Let's discuss with @pawanrawal if we should use the max node in case we encounter more than one node.
> 
> > Reviewed 10 of 15 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-:-MQq1b4M7znz44YP98_x:ba863yk)_ status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)
> 
> _[edgraph/graphql.go, line 150 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq0wYeAVtkk-1dGDhk:-MQq0wYfAPSEeBJCMdFr:bqnpiq7) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/graphql.go#L150)):_
> 
> > ```
> > glog.Infof("
> > ```
> 
> `Errorf`
> and again I don't feel we should do this. If this happens that means there is some other issue, which we should fix. Or if it happens due to older backups we should have a way to migrate from those which we already have. So, this feels like it should still return an error if we get either 0 or more than 1 node.
> 
> _[edgraph/server.go, line 177 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq-VSSCA1m_Qjal8vl:-MQq-VSSCA1m_Qjal8vm:b-l6zetr) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/server.go#L177)):_
> 
> > ```
> > if uidMax < schNode.Uid {
> > ```
> 
> uid here is a string. Shouldn't we first convert it to int and then compare?
> Because, even the difference of `A` and `a` can make it go wrong right now.
> 
> _[edgraph/server.go, line 182 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq-vnA4jm24jKiibKu:-MQq-vnA4jm24jKiibKv:bkb07ql) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/server.go#L182)):_
> 
> > ```go
> > 		}
> > 	}
> > 	glog.Infof("Multiple schema node found,returning last added node")
> > ```
> 
> This is supposed to be an error state, so we should use `glog.Errorf`.
> 
> But, it doesn't feel like we should make it return the max node instead of giving an error. Such states should never be achieved and we also haven't seen any evidence for GraphQL schema case where two nodes have been seen after the fixes done long back.
> So, I believe that we should still return an error because we need to know if such thing happens, instead of just ignoring it.

changed uid comparison.
Also log errors using Errorf.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7270)* status: 0 of 15 files reviewed, 8 unresolved discussions (waiting on @JatinDevDG, @manishrjain, and @vvbalaji-dgraph)

___
*[edgraph/graphql.go, line 150 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq0oyy63ibuKczSLXw:-MQq0oyy63ibuKczSLXx:bnudqhk) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/graphql.go#L150)):*
> ```Go
> 		}
> 	}
> 	glog.Infof("Multiple nodes of type dgraph.type.cors found,returning last added node")
> ```

space after `,`

Multiple nodes of type dgraph.type.cors found, using the latest one.
___
*[edgraph/graphql.go, line 143 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuUMaH1-rM8IiU9Uol:-MQuUMaH1-rM8IiU9Uom:bgnm1pu) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L143)):*
> ```Go
> 		return corsRes.Me[0].Uid, corsRes.Me[0].DgraphCors, nil
> 	}
> 	cors := corsRes.Me[0].DgraphCors
> ```

Add a comment here that if there are multiple nodes for cors we pick the one with the max uid.
___
*[edgraph/graphql.go, line 144 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuTucv6wn8hWguqND0:-MQuTucv6wn8hWguqND1:b-nlvq0f) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L144)):*
> ```Go
> 	}
> 	cors := corsRes.Me[0].DgraphCors
> 	uidMax := corsRes.Me[0].Uid
> ```

maxUid
___
*[edgraph/graphql.go, line 145 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuTy7zE2ZW-3tjqTDE:-MQuTy7zE2ZW-3tjqTDF:b-j74zrc) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L145)):*
> ```Go
> 	cors := corsRes.Me[0].DgraphCors
> 	uidMax := corsRes.Me[0].Uid
> 	uidMaxInt, err := gql.ParseUid(uidMax)
> ```

`maxUidInt`
___
*[edgraph/graphql.go, line 150 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuU2189o200ur-NwwY:-MQuU2189o200ur-NwwZ:b-tf7507) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L150)):*
> ```Go
> 	}
> 	for _, me := range corsRes.Me[1:] {
> 		cUidInt, err := gql.ParseUid(me.Uid)
> ```

```
sort.Slice(corsRes.Me, func(i, j int) bool {
  // parse the uids into integer and then compare
  return corsRes.Me[i].uidInt < corsResMe[j].uidInt 
})
```
___
*[edgraph/graphql.go, line 155 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuV0m64ud8vIAQNVJx:-MQuV0m71R7nx_BNw_JM:b-wwgm7r) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L155)):*
> ```Go
> 		}
> 		if uidMaxInt < cUidInt {
> 			uidMaxInt = cUidInt
> ```

instead of doing all this why not sort them and then pick the last value?
___
*[edgraph/server.go, line 187 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuVRIADlQbUu7RvazG:-MQuVRIADlQbUu7RvazH:bnioj5g) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/server.go#L187)):*
> ```Go
> 		if uidMaxInt < cUidInt {
> 			uidMaxInt = cUidInt
> 			uidMax = schNode.Uid
> ```

use sort here
___
*[worker/graphql_schema.go, line 109 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuVfqw3DajWY4zpQ09:-MQuVfqw3DajWY4zpQ0A:b-f037qo) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/worker/graphql_schema.go#L109)):*
> ```Go
> 		// there seems to be multiple nodes for GraphQL schema,Ideally we should never reach here
> 		// But if by any bug we reach here then return the schema node which is added last
> 		uidMax := res.GetUidMatrix()[0].GetUids()[0]
> ```

the list should already be sorted but you can anyways sort and just pick last value

**Review by JatinDevDG — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7270)* status: 0 of 15 files reviewed, 8 unresolved discussions (waiting on @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/graphql.go, line 150 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQq0oyy63ibuKczSLXw:-MQuwWUTEH2uUuKDFxio:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/a6719ad900f7f7bb3422274da5ee113c63124e2d/edgraph/graphql.go#L150)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

space after `,`

Multiple nodes of type dgraph.type.cors found, using the latest one.
</blockquote></details>

done.
___
*[edgraph/graphql.go, line 143 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuUMaH1-rM8IiU9Uol:-MQuvkbT8s5njO11uXsk:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L143)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Add a comment here that if there are multiple nodes for cors we pick the one with the max uid.
</blockquote></details>

added.
___
*[edgraph/graphql.go, line 144 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuTucv6wn8hWguqND0:-MQuvnn7AA6lAw-veV2_:b-52nnbj) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L144)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

maxUid
</blockquote></details>

not needed now.
___
*[edgraph/graphql.go, line 145 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuTy7zE2ZW-3tjqTDE:-MQuvpeV3XVcpypcD2gM:b-52nnbj) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L145)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

`maxUidInt`
</blockquote></details>

not needed now.
___
*[edgraph/graphql.go, line 150 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuU2189o200ur-NwwY:-MQuvrLtEcUCn5oJO3yj:b-t948zx) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L150)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

```
sort.Slice(corsRes.Me, func(i, j int) bool {
  // parse the uids into integer and then compare
  return corsRes.Me[i].uidInt < corsResMe[j].uidInt 
})
```
</blockquote></details>

added.
___
*[edgraph/graphql.go, line 155 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuV0m64ud8vIAQNVJx:-MQuvtFJ7AkSVwZFw7WJ:b-4zpve9) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/graphql.go#L155)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

instead of doing all this why not sort them and then pick the last value?
</blockquote></details>

sort was costly in terms of performance and we need an extra loop for parsing of values also. But after having with abhimanyu that this case will occur in rare scenarios and we should focus on code readability, i changed this to sort.
___
*[edgraph/server.go, line 187 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuVRIADlQbUu7RvazG:-MQuwXxI-nJQlRZaclKe:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/edgraph/server.go#L187)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

use sort here
</blockquote></details>

done.
___
*[worker/graphql_schema.go, line 109 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQuVfqw3DajWY4zpQ09:-MQuwZTKEaGc6e87loOK:b-7rl0jd) ([raw file](https://github.com/dgraph-io/dgraph/blob/1fe69194353fe53a444165bcb69567a786099fc4/worker/graphql_schema.go#L109)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

the list should already be sorted but you can anyways sort and just pick last value
</blockquote></details>

done.

**Review by pawanrawal — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/7270)* status: 3 of 15 files reviewed, 8 unresolved discussions (waiting on @JatinDevDG, @manishrjain, @pawanrawal, and @vvbalaji-dgraph)

___
*[edgraph/graphql.go, line 131 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQzprCjEedKcKfbMRId:-MQzprCjEedKcKfbMRIe:b2nidrf) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c02b886da92409ee6e2a48fcaa3ee53ee6c60f5/edgraph/graphql.go#L131)):*
> ```Go
> 	type corsResponse struct {
> 		Me []struct {
> 			Uid        string `json:"uid"`
> ```

uid
___
*[edgraph/graphql.go, line 147 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQzpjZo7mMYdSzbqJrz:-MQzpjZo7mMYdSzbqJs-:bb7idvw) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c02b886da92409ee6e2a48fcaa3ee53ee6c60f5/edgraph/graphql.go#L147)):*
> ```Go
> 	// Multiple nodes for cors found, returning the one that is added last
> 	for i, _ := range corsRes.Me {
> 		UidInt, err := gql.ParseUid(corsRes.Me[i].Uid)
> ```

iuid
___
*[edgraph/server.go, line 176 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQzqBdWCuY5yfp0D-Jg:-MQzqBdWCuY5yfp0D-Jh:bb7idvw) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c02b886da92409ee6e2a48fcaa3ee53ee6c60f5/edgraph/server.go#L176)):*
> ```Go
> 	// returning the schema node which is added last
> 	for i, _ := range result.ExistingGQLSchema {
> 		UidInt, err := gql.ParseUid(result.ExistingGQLSchema[i].Uid)
> ```

iuid
___
*[edgraph/server.go, line 187 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQzqEj8-F8oI9Na3Ylu:-MQzqEj8-F8oI9Na3Ylv:bh7df0m) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c02b886da92409ee6e2a48fcaa3ee53ee6c60f5/edgraph/server.go#L187)):*
> ```Go
> 	})
> 	glog.Errorf("Multiple schema node found, using the last one")
> 	lastIndex := len(result.ExistingGQLSchema) - 1
> ```

res := result.ExistingGQLSchema[len(result.ExistingGQLSchema)-1]
___
*[edgraph/server.go, line 188 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQzqISnCCwQtkCIby6-:-MQzqISnCCwQtkCIby60:b-6ku00t) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c02b886da92409ee6e2a48fcaa3ee53ee6c60f5/edgraph/server.go#L188)):*
> ```Go
> 	glog.Errorf("Multiple schema node found, using the last one")
> 	lastIndex := len(result.ExistingGQLSchema) - 1
> 	return result.ExistingGQLSchema[lastIndex].Uid, result.ExistingGQLSchema[lastIndex].Schema, nil
> ```

return res.Uid, res.Schema, nil
___
*[worker/graphql_schema.go, line 110 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/7270#-MQzqctZ3isdwVNBjho-:-MQzqctZ3isdwVNBjho0:bmypo58) ([raw file](https://github.com/dgraph-io/dgraph/blob/6c02b886da92409ee6e2a48fcaa3ee53ee6c60f5/worker/graphql_schema.go#L110)):*
> ```Go
> 		// there seems to be multiple nodes for GraphQL schema,Ideally we should never reach here
> 		// But if by any bug we reach here then return the schema node which is added last
> 		sort.Slice(res.GetUidMatrix()[0].GetUids(), func(i, j int) bool {
> ```

uidList := res.GetUidMatrix()[0].GetUids()

and then use the uidList everywhere

**Pull request merged**
