### PR TITLE
Removing duplicates after tokenization

### PR DESCRIPTION
**Pull request by tzdybal**
This is PR for issue #1183.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1189)

### CODE REVIEW

**Comment by ashwin95r** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[x/x.go, line 198 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-Kouo0QvfotAIonsKxp3:-Kouo0QwgHq8ygbb5E4D:b-gr6k3b) ([raw file](https://github.com/dgraph-io/dgraph/blob/db14930f18c9f0f026687fb6f108da16ad64e854/x/x.go#L198)):*
> ```Go
> 
> // removes duplicates from a sorted slice of strings. Changes underylying array.
> func RemoveDuplicates(s []string) (out []string) {
> ```

We could move the sort to this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-:-Kouo6oJeL6x9VtfLpn5:bnfp4nl)*

**Comment by manishrjain** [comment]
:lgtm: Address comments before submitting.

---

Reviewed 2 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tok/tok.go, line 337 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-KoysuK94LS7St22JMsy:-KoysuK94LS7St22JMsz:b-1e9d0g) ([raw file](https://github.com/dgraph-io/dgraph/blob/5263706f5d390b90c5a7be60578ff2a2aa87c567/tok/tok.go#L337)):*
> ```Go
> 			tokens[i] = encodeToken(trigram, t.Identifier())
> 		}
> 		x.RemoveDuplicates(tokens)
> ```

tokens = x.RemoveDuplicates(tokens) ?? Just like you've done above: terms = x.RemoveDuplicates(terms)

---

*[tok/tok_test.go, line 204 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-Koyt5-TnkFINvDx2JsO:-Koyt5-TnkFINvDx2JsP:b-xpfg0i) ([raw file](https://github.com/dgraph-io/dgraph/blob/5263706f5d390b90c5a7be60578ff2a2aa87c567/tok/tok_test.go#L204)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	expected := []string{" chief", " weapon", " surpris", " fear", " ruthless", " effici"}
> ```

Are we actually adding spaces in our tokens?

---

*[x/x.go, line 198 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-Kouo0QvfotAIonsKxp3:-KoytE94jAIqzhcb6WQd:b1qsbzq) ([raw file](https://github.com/dgraph-io/dgraph/blob/db14930f18c9f0f026687fb6f108da16ad64e854/x/x.go#L198)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

We could move the sort to this function.
</blockquote></details>

So, out is using the same array as s. And that causes confusion in the usage (as witnessed above). Just don't return out in that case. At least it would be clear that it's modifying the passed slice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-:-KoytR7GRykGxHkCv7Dq:b533za0)*

**Comment by tzdybal** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[tok/tok.go, line 337 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-KoysuK94LS7St22JMsy:-Koyw2fWrcLXZMK5TaZs:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/5263706f5d390b90c5a7be60578ff2a2aa87c567/tok/tok.go#L337)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

tokens = x.RemoveDuplicates(tokens) ?? Just like you've done above: terms = x.RemoveDuplicates(terms)
</blockquote></details>

Done.

---

*[tok/tok_test.go, line 204 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-Koyt5-TnkFINvDx2JsO:-KoyvgD7qHEUG0mjiU4I:bdmw524) ([raw file](https://github.com/dgraph-io/dgraph/blob/5263706f5d390b90c5a7be60578ff2a2aa87c567/tok/tok_test.go#L204)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Are we actually adding spaces in our tokens?
</blockquote></details>

No, we're using per-tokenizer prefix. For the simplicity of test I used space instead of real tokenizer-identifier (it's much easier to type expected values that way).

---

*[x/x.go, line 198 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189#-Kouo0QvfotAIonsKxp3:-Koyvyco5UszhP_R7giY:b-4zqved) ([raw file](https://github.com/dgraph-io/dgraph/blob/db14930f18c9f0f026687fb6f108da16ad64e854/x/x.go#L198)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

So, out is using the same array as s. And that causes confusion in the usage (as witnessed above). Just don't return out in that case. At least it would be clear that it's modifying the passed slice.
</blockquote></details>

Actually we have to return new slice, because the slice size may change.  Added comment about the usage of this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1189)*

**Comment by tzdybal** [comment]
Merged to master (8e412fd37c42af776165b92cb398b9f20d52a0d8).

**Pull request closed without merging**
