### PR TITLE
Support sorting, pagination at root

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/552)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[gql/parser.go, line 1086 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmotHtqSOc68JP089L:-KbmotHtqSOc68JP089M:bt6u6p3) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/gql/parser.go#L1086)):*
> ```Go
> 	// Parse in KV fashion. Depending on the value of key, decide the path.
> 	for it.Next() {
> 		var key string
> ```

Do you deal with EOF somewhere?

---

*[query/query.go, line 461 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmoC2lP4Exv_l3yQQW:-KbmoC2lP4Exv_l3yQQX:b4xwrsw) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L461)):*
> ```Go
> 	}
> 
> 	if v, ok := gq.Args["offset"]; ok {
> ```

This is repeated code. Refactor.

---

*[query/query.go, line 758 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-Kbmnggrq9mp7GLZZ7T8:-Kbmnggrq9mp7GLZZ7T9:by1kbot) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L758)):*
> ```Go
> 		// I am root. I don't have any function to execute, and my
> 		// result has been prepared for me already.
> 		sg.DestUIDs = algo.MergeSorted(sg.uidMatrix) // Could also be = sg.SrcUIDs
> ```

Set this to srcuids.

---

*[query/query.go, line 799 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmnnZhTmhrAQgpNxXZ:-KbmnnZhTmhrAQgpNxX_:b-1gm2zt) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L799)):*
> ```Go
> 		}
> 
> 		if parent == nil {
> ```

I'm root comment and how did I reach here.

---

*[query/query.go, line 954 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-Kbmnug6koiRyQUlwZpV:-Kbmnug6koiRyQUlwZpW:ba3dfmt) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L954)):*
> ```Go
> 		return nil
> 	}
> 	//x.AssertTrue(len(sg.SrcUIDs.Uids) == len(sg.uidMatrix))
> ```

Remove.

---

*[query/query_test.go, line 2437 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmmppnkuWN5_rznDY_:-KbmmppnkuWN5_rznDYa:bqza0gi) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query_test.go#L2437)):*
> ```Go
> 	require.JSONEq(t, `{"me":[{"name":"Rick Grimes"}]}`, js)
> }
> ```

Add an example for using variable. And another test for sorting it as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/552)*

**Comment by ashwin95r** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[gql/parser.go, line 1086 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmotHtqSOc68JP089L:-Kbmy8-4qLVdm8H4GRtH:b-9lq67a) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/gql/parser.go#L1086)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Do you deal with EOF somewhere?
</blockquote></details>

we check for specific items that we need and return error if it doesn't match. That should catch EOF here.

---

*[query/query.go, line 461 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmoC2lP4Exv_l3yQQW:-KbmwZ55ToqfpxVG26DZ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L461)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This is repeated code. Refactor.
</blockquote></details>

Done.

---

*[query/query.go, line 758 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-Kbmnggrq9mp7GLZZ7T8:-KbmvbdoPonQnriEfo9H:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L758)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Set this to srcuids.
</blockquote></details>

Done.

---

*[query/query.go, line 799 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmnnZhTmhrAQgpNxXZ:-KbmvbJbiysZ0ux6rj0-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L799)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I'm root comment and how did I reach here.
</blockquote></details>

Done.

---

*[query/query.go, line 954 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-Kbmnug6koiRyQUlwZpV:-KbmrC1dcxqEWoZT1Jk6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query.go#L954)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.

---

*[query/query_test.go, line 2437 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbmmppnkuWN5_rznDY_:-Kbn-JtG9inshE8_CBG9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/981f41bf211e6e1026331828eeead6674a556ee5/query/query_test.go#L2437)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add an example for using variable. And another test for sorting it as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/552)*

**Comment by manishrjain** [comment]
:lgtm: Feel free to submit. I think it's a blue task.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-:-Kbn0ibHWlGWdkPge0-D:bm5r21s)*

**Comment by jchiu0** [comment]
LG to parse args in root node and "fill them" in query.go. :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[query/query.go, line 473 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbnIPL2hYcQxFsE9wNA:-KbnIPL2hYcQxFsE9wNB:b46415) ([raw file](https://github.com/dgraph-io/dgraph/blob/89be3a53969fe3f64d61dae240371d7cc0a61aba/query/query.go#L473)):*
> ```Go
> 		}
> 	}
> 	err := args.fill(gq)
> ```

maybe: if err:=..; err != nil {
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-:-KbnIdLV4mZdOXb4s8Dx:b-u0i49r)*

**Comment by ashwin95r** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[query/query.go, line 473 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/552#-KbnIPL2hYcQxFsE9wNA:-KbnNaMHVd39rM6dZVxQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/89be3a53969fe3f64d61dae240371d7cc0a61aba/query/query.go#L473)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

maybe: if err:=..; err != nil {
}
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/552)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
