### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/399)

### CODE REVIEW

**Comment by ashishnegi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraphloader/main.go, line 169 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/399#-KZPhieKSnJtqF4FS6sO:-KZPhieKSnJtqF4FS6sP:b-8c62ye) ([raw file](https://github.com/dgraph-io/dgraph/blob/2cf416b3642a841806a316312bf4b429a9bf196c/cmd/dgraphloader/main.go#L169)):*
> ```Go
> 	numSec := uint64(time.Since(s.start).Seconds())
> 	if numSec == 0 {
> 		numSec = 1
> ```

can't we always add 1 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/399)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/399#-:-KZPpptoz5UfmWu8yzhg:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/dgraphloader/main.go, line 169 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/399#-KZPhieKSnJtqF4FS6sO:-KZPvgpF_vOONZ4tD3y0:b-bty3v8) ([raw file](https://github.com/dgraph-io/dgraph/blob/2cf416b3642a841806a316312bf4b429a9bf196c/cmd/dgraphloader/main.go#L169)):*
<details><summary><i>Previously, ashishnegi (Ashish Negi) wrote…</i></summary><blockquote>

can't we always add 1 ?
</blockquote></details>

Sure. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/399)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
