### PR TITLE
Show config vars in /debug/vars

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1432)

### CODE REVIEW

**Comment by janardhan1993** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dgraph/config.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-KtiQi_wcyxzKJPLbPjA:-KtiQi_wcyxzKJPLbPjB:b-ediebi) ([raw file](https://github.com/dgraph-io/dgraph/blob/e40e73728e96a94f9d35de0cb7ceb08df60fc79e/dgraph/config.go#L122)):*
> ```Go
> 	x.Conf.Set("max_pending_count", getNewInt(int(conf.MaxPendingCount)))
> 	x.Conf.Set("num_pending_proposals", getNewInt(conf.NumPendingProposals))
> 	x.Conf.Set("expand_edge", getIntFromBool(conf.ExpandEdge))
> ```

We could marshal the conf(Options) to json and set it as string variable directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-:-KtiQsrWxQHvmEfoDfR9:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dgraph/config.go, line 122 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-KtiQi_wcyxzKJPLbPjA:-KtiTFxIen7-BA7O2qHT:b8c3wex) ([raw file](https://github.com/dgraph-io/dgraph/blob/e40e73728e96a94f9d35de0cb7ceb08df60fc79e/dgraph/config.go#L122)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We could marshal the conf(Options) to json and set it as string variable directly.
</blockquote></details>

Problem with that is that it won't be very readable. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432)*

**Comment by manishrjain** [comment]
:lgtm: some comments.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[dgraph/config.go, line 85 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-KtjrnQi0XaAvhkObwFZ:-KtjrnQi0XaAvhkObwF_:b-n2nlfu) ([raw file](https://github.com/dgraph-io/dgraph/blob/e40e73728e96a94f9d35de0cb7ceb08df60fc79e/dgraph/config.go#L85)):*
> ```Go
> // value of the flags. Hence we dump conf options we care about to the conf map.
> func setConfVar(conf Options) {
> 	getNewStr := func(s string) *expvar.String {
> ```

newStr

---

*[dgraph/config.go, line 91 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-Ktjro7AvyoZ8Eipnh1K:-Ktjro7AvyoZ8Eipnh1L:b-cg0msf) ([raw file](https://github.com/dgraph-io/dgraph/blob/e40e73728e96a94f9d35de0cb7ceb08df60fc79e/dgraph/config.go#L91)):*
> ```Go
> 	}
> 
> 	getNewFloat := func(f float64) *expvar.Float {
> ```

newFloat

---

*[dgraph/config.go, line 97 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-KtjrokpKVNf-arYCa59:-KtjrokpKVNf-arYCa5A:b-n2nszw) ([raw file](https://github.com/dgraph-io/dgraph/blob/e40e73728e96a94f9d35de0cb7ceb08df60fc79e/dgraph/config.go#L97)):*
> ```Go
> 	}
> 
> 	getNewInt := func(i int) *expvar.Int {
> ```

newInt

---

*[dgraph/config.go, line 104 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-KtjrpUv9bTyssdVF1_K:-KtjrpUv9bTyssdVF1_L:b-d1lneg) ([raw file](https://github.com/dgraph-io/dgraph/blob/e40e73728e96a94f9d35de0cb7ceb08df60fc79e/dgraph/config.go#L104)):*
> ```Go
> 
> 	// Expvar doesn't have bool type so we use an int.
> 	getIntFromBool := func(b bool) *expvar.Int {
> ```

newIntFromBool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1432#-:-KtjrvgDqavNEVjwcPhS:b-h0fnsz)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
