### PR TITLE
Add an endpoint in Zero to move a tablet to a group.

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Refactored code and moved http handlers to `http.go`.

2. Added a `/moveTablet?tablet=<tablet>&group=<gid>` http endpoint.

3. Refactored some code around context cancellation in case of leadership change. The current code looked like it won't work. 

4. Changed the `membershipUpdate` interval to `time.Minute`. 

---
TODO 
- [x] Test whether predicate move is cancelled properly by simulating a leadership change.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2093)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[dgraph/cmd/zero/http.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddXRoJC0txVm5jike:-L4ddXRoJC0txVm5jikf:bhfp1k7) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L31)):*
> ```Go
> }
> 
> func (st *state) removeNode(w http.ResponseWriter, r *http.Request) {
> ```

What does this method do? Add comment.

---

*[dgraph/cmd/zero/http.go, line 44 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddHQdBCLqkg6m52VO:-L4ddHQdBCLqkg6m52VP:b-aib9a1) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L44)):*
> ```Go
> 	nodeId, ok := intFromQueryParam(w, r, "id")
> 	if !ok {
> 		return
> ```

Have to write what the issue was if the request returned without doing anything.

---

*[dgraph/cmd/zero/http.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddN2lquWVOuHJJ8EF:-L4ddN2lquWVOuHJJ8EG:b-5h08c7) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L48)):*
> ```Go
> 	groupId, ok := intFromQueryParam(w, r, "group")
> 	if !ok {
> 		return
> ```

same here.

---

*[dgraph/cmd/zero/http.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4dda2B3p009lY441oI:-L4dda2B3p009lY441oJ:b-72utxq) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L59)):*
> ```Go
> }
> 
> func (st *state) moveTablet(w http.ResponseWriter, r *http.Request) {
> ```

Add a comment for this method too.

---

*[dgraph/cmd/zero/http.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddjrnKIj-HY78X0Os:-L4ddjrnKIj-HY78X0Ot:b-4cerwe) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L79)):*
> ```Go
> 	groupId, ok := intFromQueryParam(w, r, "group")
> 	if !ok {
> 		return
> ```

return error?

---

*[dgraph/cmd/zero/tablet.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4dkHUgIQUvW3xYFDeb:-L4dk2zX8qMMT6-XxMAL:b-eregzm) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/tablet.go#L59)):*
> ```Go
> 		select {
> 		case <-ticker.C:
> 			predicate, srcGroup, dstGroup := s.chooseTablet()
> ```

What about leaderChange logic?

---

*[worker/groups.go, line 425 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4djR6Mu-K74tcIhXxU:-L4djR6Mu-K74tcIhXxV:btxmviq) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/worker/groups.go#L425)):*
> ```Go
> 
> func (g *groupi) periodicMembershipUpdate() {
> 	ticker := time.NewTicker(time.Minute * 1)
> ```

Keep this to 5.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093)*

**Comment by pawanrawal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[dgraph/cmd/zero/http.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddXRoJC0txVm5jike:-L4dls7nBC_mRgIfRt1R:b32w1t) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What does this method do? Add comment.
</blockquote></details>

Ok

---

*[dgraph/cmd/zero/http.go, line 44 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddHQdBCLqkg6m52VO:-L4dlJuhq72hmEeFbC8R:b-tukodh) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L44)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Have to write what the issue was if the request returned without doing anything.
</blockquote></details>

`initFromQueryParam' does that

---

*[dgraph/cmd/zero/http.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4dda2B3p009lY441oI:-L4dlUv1JBjAm3eZzxQB:b32w1t) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L59)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment for this method too.
</blockquote></details>

Ok

---

*[dgraph/cmd/zero/http.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddjrnKIj-HY78X0Os:-L4dlWUq3p74g4dle7sY:btsnevs) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L79)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

return error?
</blockquote></details>

The function writes a error message

---

*[dgraph/cmd/zero/tablet.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4dkHUgIQUvW3xYFDeb:-L4dldb8fK0np3_hWD00:bs3casl) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/tablet.go#L59)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

What about leaderChange logic?
</blockquote></details>

It needs to happen in a goroutine. Doing that in movePredicate function now. 

---

*[worker/groups.go, line 425 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4djR6Mu-K74tcIhXxU:-L4dlopqm7MIKtq6Dzhg:b32w1t) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/worker/groups.go#L425)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Keep this to 5.
</blockquote></details>

Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093)*

**Comment by pawanrawal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[dgraph/cmd/zero/http.go, line 31 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddXRoJC0txVm5jike:-L4eQyXyUw3b2tMAx6n4:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L31)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

Done.

---

*[dgraph/cmd/zero/http.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddN2lquWVOuHJJ8EF:-L4eRg5pptiUP9pcm7uc:b-299cbg) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

`intFromQueryParam` would write the error.

---

*[dgraph/cmd/zero/http.go, line 59 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4dda2B3p009lY441oI:-L4eRjd2Ui5Ca3jCr9OQ:bb7f2mf) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L59)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

done

---

*[dgraph/cmd/zero/http.go, line 79 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4ddjrnKIj-HY78X0Os:-L4eRkSY16-4nyLnUXTJ:bnj7hl0) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/dgraph/cmd/zero/http.go#L79)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

The function writes a error message
</blockquote></details>

same as above

---

*[worker/groups.go, line 425 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4djR6Mu-K74tcIhXxU:-L4eRrwNITbH3aa8B109:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/worker/groups.go#L425)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093)*

**Comment by manishrjain** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[dgraph/cmd/zero/http.go, line 100 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4i81bcF1zcFruHzG_S:-L4i81bcF1zcFruHzG_T:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/ecc974a901096cba5f71c41b74a0738307a28146/dgraph/cmd/zero/http.go#L100)):*
> ```Go
> 	if !isKnown {
> 		w.WriteHeader(http.StatusBadRequest)
> 		x.SetStatus(w, x.ErrorInvalidRequest, fmt.Sprintf("Group: [%d] is not a known group.", dstGroup))
> ```

100 chars.

---

*[dgraph/cmd/zero/tablet.go, line 74 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4i8GTIWXuEOXRi2XRf:-L4i8GTIWXuEOXRi2XRg:bpd3aja) ([raw file](https://github.com/dgraph-io/dgraph/blob/ecc974a901096cba5f71c41b74a0738307a28146/dgraph/cmd/zero/tablet.go#L74)):*
> ```Go
> 	ctx, cancel := context.WithTimeout(context.Background(), time.Minute*20)
> 
> 	go func(cancel context.CancelFunc) {
> ```

This goroutine is being run on every call to movePredicate. Previously, it was run just once. Is this the right behavior?

---

*[worker/groups.go, line 425 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4djR6Mu-K74tcIhXxU:-L4i8PesyDfmh-_ZO9JR:b-orxgfe) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/worker/groups.go#L425)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can add a comment here that recalculating tablet sizes can be expensive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093)*

**Comment by pawanrawal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[dgraph/cmd/zero/http.go, line 100 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4i81bcF1zcFruHzG_S:-L4iKPaDYd9R2kLdsgAY:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/ecc974a901096cba5f71c41b74a0738307a28146/dgraph/cmd/zero/http.go#L100)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---

*[dgraph/cmd/zero/tablet.go, line 74 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4i8GTIWXuEOXRi2XRf:-L4iBa387paHweURxpV0:b-jbejoh) ([raw file](https://github.com/dgraph-io/dgraph/blob/ecc974a901096cba5f71c41b74a0738307a28146/dgraph/cmd/zero/tablet.go#L74)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

This goroutine is being run on every call to movePredicate. Previously, it was run just once. Is this the right behavior?
</blockquote></details>

Have a behavior for the goroutine to exit now. moveTablet checks if its not the leader.

---

*[worker/groups.go, line 425 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4djR6Mu-K74tcIhXxU:-L4iK5Kbyje6ApQ4fFyI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/f49fd2722012e4e2f8794b0aeae4f58698ce7faf/worker/groups.go#L425)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You can add a comment here that recalculating tablet sizes can be expensive.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dgraph/cmd/zero/tablet.go, line 73 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4if78lk03VWarO7uzn:-L4if78lk03VWarO7uzo:b-xsp254) ([raw file](https://github.com/dgraph-io/dgraph/blob/180d0a08e5456e6fd6455704c842437831e00b65/dgraph/cmd/zero/tablet.go#L73)):*
> ```Go
> 	x.Printf("Going to move predicate %v from %d to %d\n", predicate, srcGroup, dstGroup)
> 	ctx, cancel := context.WithTimeout(context.Background(), time.Minute*20)
> 	done := make(chan struct{}, 1)
> ```

Can be an unbuffered channel.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-:-L4ifcsoLwSbqRzAHBbW:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dgraph/cmd/zero/tablet.go, line 73 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093#-L4if78lk03VWarO7uzn:-L4igZ-hhrBpAKE10a53:b-w5y4xg) ([raw file](https://github.com/dgraph-io/dgraph/blob/180d0a08e5456e6fd6455704c842437831e00b65/dgraph/cmd/zero/tablet.go#L73)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Can be an unbuffered channel.
</blockquote></details>

Uhmm, if leader change happened and the goroutine exited, then send to the channel would block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/2093)*

**Comment by pawanrawal** [comment]
In master as of 23f803c27946d12677e9dd802d74f97e63ca5c12.

**Pull request closed without merging**
