### PR TITLE
Make max trigram UID flag.

### PR DESCRIPTION
**Pull request by BlakeMScurr**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2429)

### CODE REVIEW

**Comment by manishrjain** [comment]
How about just removing the limit altogether? Let the user run their queries as they deem fit.

**Comment by manishrjain** [comment]
There would be a compilation error here. Can you try building this and running the tests? (test.sh at root folder -- might move it to contrib today).

---

Review status: 0 of 1 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/2429#-:-LG178f2-OrQgBiDiMJC:bp3eoi1)*

**Comment by BlakeMScurr** [comment]
@manishrjain Sorry, forgot to ping you about my changes.

**Comment by manishrjain** [comment]
LGTM. Thanks for the fix.

**Pull request merged**
