### PR TITLE
Change the rocksDB library used and support read-only

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/95)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dgraph/dgraphloader/main_test.go, line 121 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEsUqx77P0odmj0hp4:-KJEsUqx77P0odmj0hp5:1455000643) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/dgraph/dgraphloader/main_test.go#L121)):*
> ```Go
> 	defer f.Close()
> 	scanner := bufio.NewScanner(f)
> ```

Unnecessary vertical space.

---

*[store/gorocksdb, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEtlnOg74EoITxLgjy:-KJEtlnOg74EoITxLgjz:-645305400) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/store/gorocksdb#L1)):*
> ```
> Subproject commit 59ab8def01399fb7ded1c3bff5e3e4cbd14b6348
> ```

Don't you want to delete `rocksdb` directory?

---

*[store/store.go, line 66 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEtbMjwjXkdLrCYSBm:-KJEtbMkErKupPgmpsEm:-1041340058) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/store/store.go#L66)):*
> ```Go
> 	s.wopt = rocksdb.NewDefaultWriteOptions()
> 	s.wopt.SetSync(false) // We don't need to do synchronous writes.
> ```

Move the above logic to a common function: getOptions or something.

---

*[store/store.go, line 68 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEtMAqH-fNG9e-o8Su:-KJEtMArPJe_XxTFdAVD:-94686628) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/store/store.go#L68)):*
> ```Go
> 
> 	var err error
> 	s.db, err = rocksdb.OpenDbForReadOnly(s.opt, filepath, false) //TODO(Ashwin):When will it be true
> ```

Line too long. Move the comment up or down. Also, add one space after `//`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/95)*

**Comment by ashwin95r** [comment]
Review status: 4 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[dgraph/dgraphloader/main_test.go, line 121 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEsUqx77P0odmj0hp4:-KJF0GTzRiJbDbF9yWDU:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/dgraph/dgraphloader/main_test.go#L121)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Unnecessary vertical space.
</details>
Done.

---

*[store/store.go, line 66 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEtbMjwjXkdLrCYSBm:-KJF02LRl-rxQM_rp_iJ:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/store/store.go#L66)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Move the above logic to a common function: getOptions or something.
</details>
Done.

---

*[store/store.go, line 68 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEtMAqH-fNG9e-o8Su:-KJF09-gldzjXjV26ldW:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/store/store.go#L68)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Line too long. Move the comment up or down. Also, add one space after `//`
</details>
Done.

---

*[store/gorocksdb, line 1 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJEtlnOg74EoITxLgjy:-KJF1wpemOtu_JGRJrl-:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0bc034cf347c8ddf88439d4d165c219fd2705fe/store/gorocksdb#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Don't you want to delete `rocksdb` directory?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/95)*

**Comment by manishrjain** [comment]
:lgtm_strong: Looks good!

<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> #### Change the rocksDB library used and support read\-only
</details>


---

Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[store/store.go, line 63 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJZHMmvUg9EO7L2JdOj:-KJZHMmvUg9EO7L2JdOk:-996154269) ([raw file](https://github.com/dgraph-io/dgraph/blob/b1fb2ef091a342ef04e62b70bb455f10009e8061/store/store.go#L63)):*
> ```Go
> 	var err error
> 	s.db, err = rocksdb.OpenDbForReadOnly(s.opt, filepath, false)
> 	//TODO(Ashwin):When will it be true
> ```

Space after `//`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-:-KJZHbHkB8hGS0b3fYow:-1044064603)*

**Comment by ashwin95r** [comment]
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[store/store.go, line 63 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/95#-KJZHMmvUg9EO7L2JdOj:-KJZJ2O5yC0rPHL63wdQ:-499146009) ([raw file](https://github.com/dgraph-io/dgraph/blob/b1fb2ef091a342ef04e62b70bb455f10009e8061/store/store.go#L63)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Space after `//`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/95)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
