### PR TITLE
Default/tok

### LINKED ISSUE #1265: Change schema parsing to ask for type of tokenizer
String and dateTime types can have multiple type of tokenizers. Users should explicitly specify what type of index they want on their values for these types. If they don't we should return an error.

### PR DESCRIPTION
**Pull request by pawanrawal**
1. Remove default tokenizer for all types. Return an error to user if he doesn't specify what tokenizer to use.
2. Rename `DateTime` tokenizer to `Year` tokenizer.

Fixes #1265 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1274)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[schema/parse.go, line 165 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1274#-Kq6qtyJv3ouYRDx8WRd:-Kq6qtyJv3ouYRDx8WRe:b-igdq8d) ([raw file](https://github.com/dgraph-io/dgraph/blob/ed21c3baf87551bb6119c287699586c9291052e1/schema/parse.go#L165)):*
> ```Go
> 		def := tok.Default(typ)
> 		// For string, datatime we don't have default tokenizer so user should specify one.
> 		if def == nil {
> ```

handle the smaller case first.

if def != nil {
  return ...
}
return ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1274#-:-Kq6rZ3ZL425Nt1FmpcT:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[schema/parse.go, line 165 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1274#-Kq6qtyJv3ouYRDx8WRd:-Kq71isxvC6seN65PFuI:b-hnu0e2) ([raw file](https://github.com/dgraph-io/dgraph/blob/ed21c3baf87551bb6119c287699586c9291052e1/schema/parse.go#L165)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

handle the smaller case first.

if def != nil {
  return ...
}
return ...
</blockquote></details>

Noted, though we dont need it anymore because we removed default tokenizers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1274)*

**Comment by janardhan1993** [comment]
:lgtm:

---

Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1274#-:-Kq72-Y53Pi_AVlW_3S7:bnfp4nl)*

**Comment by pawanrawal** [comment]
Merged to master.

**Pull request closed without merging**
