### PR TITLE
Bulkloader: sharded map and shuffle

### PR DESCRIPTION
**Pull request by peterstace**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1480)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks broke.

---

*[cmd/bulkloader/loader.go, line 227 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIWIKps6DEm0vx-lqN:-KuIWIKps6DEm0vx-lqO:bgdusau) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L227)):*
> ```Go
> 		pendingShufflers := make(chan struct{}, ld.opt.NumShufflers)
> 		for i := 0; i < ld.opt.ReduceShards; i++ {
> 			pendingShufflers <- struct{}{}
> ```

Add a comment here saying that this would block. Because ...

---

*[cmd/bulkloader/loader.go, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIWWXH3GXyqniwRQMy:-KuIWWXH3GXyqniwRQMz:bbdgh4x) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L234)):*
> ```Go
> 			opt.ValueGCRunInterval = time.Hour * 100
> 			opt.SyncWrites = false
> 			opt.TableLoadingMode = bo.LoadToRAM
> ```

Why change it?

---

*[cmd/bulkloader/loader.go, line 248 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIU0PeDugKh66xp7Ey:-KuIU0PeDugKh66xp7Ez:ba2mvc9) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L248)):*
> ```Go
> 			go func() {
> 				ci := &countIndexer{state: ld.state, kv: kv}
> 				shufflePostings(shuffleOutputCh, shuffleInputChs, kv, ci, ld.prog)
> ```

Reduce the number of arguments. Might make sense to have an internal state.

---

*[cmd/bulkloader/loader.go, line 258 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIX5uSFXkLifJsqXUF:-KuIX5uSFXkLifJsqXUG:b6x0k1s) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L258)):*
> ```Go
> 	// Run reducers.
> 	var badgerWg sync.WaitGroup
> 	pendingReducers := make(chan struct{}, ld.opt.NumGoroutines)
> ```

Create a Throttle struct which can give you this in a nice way.

---

*[cmd/bulkloader/loader.go, line 265 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIW_9Fx_fiOWKct6ZB:-KuIW_9Fx_fiOWKct6ZC:b-5j2gwi) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L265)):*
> ```Go
> 		badgerWg.Add(1)
> 		go func(job shuffleOutput) {
> 			reduce(job.entries, job.kv, ld.prog, badgerWg.Done)
> ```

Reduce the number of arguments.

---

*[cmd/bulkloader/loader.go, line 296 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIX_B6_q1Pkyg2LsS-:-KuIX_B6_q1Pkyg2LsS0:bxkw701) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L296)):*
> ```Go
> 		if !fi.IsDir() {
> 			fnames = append(fnames, path)
> 		}
> ```

Just check that it has a map suffix.

---

*[cmd/bulkloader/loader.go, line 325 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIXz6qPH0D3C8c9cLp:-KuIXz6qPH0D3C8c9cLq:b-aayd3) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L325)):*
> ```Go
> }
> 
> func sortBySize(dirs []string, ascending bool) {
> ```

No need for this bool.

---

*[cmd/bulkloader/main.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIYaVWZcJpGl8fbcH0:-KuIYaVWZcJpGl8fbcH1:bpo21ym) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/main.go#L48)):*
> ```Go
> 		"Maximum number of pending badger writes allowed at any time.")
> 	flag.IntVar(&opt.NumShufflers, "shufflers", 1, "Number of shufflers to run concurrently.")
> 	flag.IntVar(&opt.MapShards, "map_shards", 1, "Number of map output shards.")
> ```

Check that map shards > reduce shards. Or, num shufflers < reduce shards.

---

*[cmd/bulkloader/mapper.go, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIYupYbMkDsGkIXCZy:-KuIYupYbMkDsGkIXCZz:b-cw65cj) ([raw file](https://github.com/dgraph-io/dgraph/blob/2699ca5a3ebf6191a1a815ae527765b83a9eebdb/cmd/bulkloader/mapper.go#L29)):*
> ```Go
> type mapper struct {
> 	*state
> 	mapEntries []*protos.MapEntry
> ```

Put these both into a struct, and use an array of that struct.

---

*[cmd/bulkloader/mapper.go, line 34 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIZmZvpT_r-Ph06HRT:-KuIZmZvpT_r-Ph06HRU:b3r7ndw) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/mapper.go#L34)):*
> ```Go
> 
> 	mu  sync.Mutex
> 	buf bytes.Buffer
> ```

Add a comment about why buf, and why shardMapEntries and how this whole thing works. In fact, we don't need buf here. `buf.Grow(..)` to about the right size + small overhead.

---

*[cmd/bulkloader/metrics.go, line 6 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI_OStfDPeWIPrWUsC:-KuI_OStfDPeWIPrWUsD:bjhe3he) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/metrics.go#L6)):*
> ```Go
> 
> var (
> 	NumBadgerWrites     = expvar.NewInt("bulkloader_pending_badger_writes")
> ```

_badger_writes_pending

---

*[cmd/bulkloader/metrics.go, line 7 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI_Jx-kfwtXfoE_ktJ:-KuI_Jx-kfwtXfoE_ktK:bftb6gv) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/metrics.go#L7)):*
> ```Go
> var (
> 	NumBadgerWrites     = expvar.NewInt("bulkloader_pending_badger_writes")
> 	NumReducers         = expvar.NewInt("bulkloader_reducers")
> ```

_num_reducers_total

---

*[cmd/bulkloader/metrics.go, line 8 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI__ZhVrOf5ivQa083:-KuI__ZhVrOf5ivQa084:bb2qotq) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/metrics.go#L8)):*
> ```Go
> 	NumBadgerWrites     = expvar.NewInt("bulkloader_pending_badger_writes")
> 	NumReducers         = expvar.NewInt("bulkloader_reducers")
> 	NumQueuedReduceJobs = expvar.NewInt("bulkloader_queued_reduce_jobs")
> ```

_reduce_queue_size

---

*[cmd/bulkloader/shard_map.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI_zAiBu0dtqTmwqv8:-KuI_zAiBu0dtqTmwqv9:bf8azh6) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/shard_map.go#L35)):*
> ```Go
> 
> 	shard = m.nextShard
> 	m.nextShard = (m.nextShard + 1) % m.numShards
> ```

move this to next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks broke.

---

*[cmd/bulkloader/loader.go, line 227 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIWIKps6DEm0vx-lqN:-KuIbsCPaIQYBRYLsAot:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L227)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment here saying that this would block. Because ...
</blockquote></details>

Done.

---

*[cmd/bulkloader/loader.go, line 234 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIWWXH3GXyqniwRQMy:-KuIbvcTMX3LTzHYfqiT:b-25rm25) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L234)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Why change it?
</blockquote></details>

Was from some experimentation. Reverted.

---

*[cmd/bulkloader/loader.go, line 248 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIU0PeDugKh66xp7Ey:-KuIjEMmi7k6N8USma8I:b-16ok4j) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L248)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Reduce the number of arguments. Might make sense to have an internal state.
</blockquote></details>

Ended up pulling all of the shuffle code into its own file/struct. It was split between here (`loader.go`) and `reduce.go`, so good to get it into its own spot. `shufflePostings` is now a method with two args.

---

*[cmd/bulkloader/loader.go, line 258 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIX5uSFXkLifJsqXUF:-KuJ5bdoMQ7OSEyL5XcC:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L258)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Create a Throttle struct which can give you this in a nice way.
</blockquote></details>

Done.

---

*[cmd/bulkloader/loader.go, line 265 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIW_9Fx_fiOWKct6ZB:-KuInCvR8SBA8TwAkp0j:b-hhoh2k) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L265)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Reduce the number of arguments.
</blockquote></details>

Done. Refactored into a `reducer` struct.

---

*[cmd/bulkloader/loader.go, line 296 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIX_B6_q1Pkyg2LsS-:-KuInnycXKG0UyFK70bp:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L296)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Just check that it has a map suffix.
</blockquote></details>

Done.

---

*[cmd/bulkloader/loader.go, line 325 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIXz6qPH0D3C8c9cLp:-KuIoUj8X8LFUPpSWXNk:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/loader.go#L325)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

No need for this bool.
</blockquote></details>

Done.

---

*[cmd/bulkloader/main.go, line 48 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIYaVWZcJpGl8fbcH0:-KuIqUt1sk40QVAgrpD-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/main.go#L48)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check that map shards > reduce shards. Or, num shufflers < reduce shards.
</blockquote></details>

Done.

---

*[cmd/bulkloader/mapper.go, line 29 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIYupYbMkDsGkIXCZy:-KuJ03xQtr_8FbmKK0EF:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/2699ca5a3ebf6191a1a815ae527765b83a9eebdb/cmd/bulkloader/mapper.go#L29)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Put these both into a struct, and use an array of that struct.
</blockquote></details>

Done.

---

*[cmd/bulkloader/mapper.go, line 34 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuIZmZvpT_r-Ph06HRT:-KuIwyEzEw7V7fxjHaVu:bz73tsj) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/mapper.go#L34)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a comment about why buf, and why shardMapEntries and how this whole thing works. In fact, we don't need buf here. `buf.Grow(..)` to about the right size + small overhead.
</blockquote></details>

Done. Removed the bytes buffer entirely. We can predict (to the exact byte) how much space we need, so can just marshal directly into a byte slice to save the mem copy.

---

*[cmd/bulkloader/metrics.go, line 6 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI_OStfDPeWIPrWUsC:-KuJ0WUkckUjd-pzxKiP:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/metrics.go#L6)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

_badger_writes_pending
</blockquote></details>

Done.

---

*[cmd/bulkloader/metrics.go, line 7 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI_Jx-kfwtXfoE_ktJ:-KuJ0WHMw5Egmr6dmPFN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/metrics.go#L7)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

_num_reducers_total
</blockquote></details>

Done.

---

*[cmd/bulkloader/metrics.go, line 8 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI__ZhVrOf5ivQa083:-KuJ0W1hzQTqcCasIONW:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/metrics.go#L8)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

_reduce_queue_size
</blockquote></details>

Done.

---

*[cmd/bulkloader/shard_map.go, line 35 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuI_zAiBu0dtqTmwqv8:-KuJ0ifud6zh5466avA1:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/296f34b24a9dba56663561bded38135cab437a0e/cmd/bulkloader/shard_map.go#L35)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

move this to next line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[cmd/bulkloader/loader.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ8K0IreRTXdbc7wzx:-KuJ8K0IreRTXdbc7wzy:b-ayfdco) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/loader.go#L173)):*
> ```Go
> 				ld.rdfChunkCh <- chunkBuf
> 			}
> 			thr.Done()
> ```

defer thr.Done() right at top.

---

*[cmd/bulkloader/reduce.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJB1O6Me6VOMX58YJo:-KuJB1O6Me6VOMX58YJp:b5nmfe1) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/reduce.go#L17)):*
> ```Go
> 	*state
> 	input <-chan shuffleOutput
> 	wg    sync.WaitGroup
> ```

writesWg

---

*[cmd/bulkloader/reduce.go, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJB2eXHgkMwpzM5ugE:-KuJB2eXHgkMwpzM5ugF:b-dkxbez) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/reduce.go#L33)):*
> ```Go
> 		}(reduceJob)
> 	}
> 	r.wg.Wait()
> ```

thr.Wait(), probably before r.wg.Wait()

---

*[cmd/bulkloader/shuffle.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ9P5J3NQzIyGDntj9:-KuJ9P5J3NQzIyGDntjA:bfgapcv) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/shuffle.go#L37)):*
> ```Go
> 	thr := x.NewThrottle(s.opt.NumShufflers)
> 	for i := 0; i < s.opt.ReduceShards; i++ {
> 		thr.Start()
> ```

Move this all within the goroutine.

---

*[cmd/bulkloader/shuffle.go, line 61 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ9SUPWnTwGuSveebT:-KuJ9SUPWnTwGuSveebU:bi51iea) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/shuffle.go#L61)):*
> ```Go
> 			ci.wait()
> 			thr.Done()
> 		}()
> ```

Pass the i to the goroutine func.

---

*[cmd/bulkloader/shuffle.go, line 112 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ9_TBsKqYTUy6MsUs:-KuJ9_TBsKqYTUy6MsUt:b-1ex4r) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/shuffle.go#L112)):*
> ```Go
> 	for _, shard := range mapShards {
> 		sortBySize(reduceShards)
> 		x.Check(os.Rename(shard, filepath.Join(reduceShards[len(reduceShards)-1], filepath.Base(shard))))
> ```

100 chars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-:-KuJC1ZR2Wep84h0LFDl:bnfp4nl)*

**Comment by peterstace** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[cmd/bulkloader/loader.go, line 173 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ8K0IreRTXdbc7wzx:-KuJCoR4rjP8tbS-EJzR:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/loader.go#L173)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

defer thr.Done() right at top.
</blockquote></details>

Done.

---

*[cmd/bulkloader/reduce.go, line 17 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJB1O6Me6VOMX58YJo:-KuJEn_d6ymb0T91C9jN:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/reduce.go#L17)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

writesWg
</blockquote></details>

Done.

---

*[cmd/bulkloader/reduce.go, line 33 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJB2eXHgkMwpzM5ugE:-KuJD-QgNLIknRNG3po0:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/reduce.go#L33)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

thr.Wait(), probably before r.wg.Wait()
</blockquote></details>

Done.

---

*[cmd/bulkloader/shuffle.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ9P5J3NQzIyGDntj9:-KuJE_Ol5KggbYM_G2Pn:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/shuffle.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move this all within the goroutine.
</blockquote></details>

Done.

---

*[cmd/bulkloader/shuffle.go, line 61 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ9SUPWnTwGuSveebT:-KuJEaAUIahA1GGI5heL:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/shuffle.go#L61)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Pass the i to the goroutine func.
</blockquote></details>

Done.

---

*[cmd/bulkloader/shuffle.go, line 112 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480#-KuJ9_TBsKqYTUy6MsUs:-KuJEm9FK9kOGtRBN4VI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/cf0df0867f54c620464f06b8a0f077912c936b9b/cmd/bulkloader/shuffle.go#L112)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

100 chars.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1480)*

**Pull request merged**
