### PR TITLE
Add a docker_compose.yml

### PR DESCRIPTION
**Pull request by pawanrawal**
This allows users do just do `docker compose up` which will start both Dgraph and Dgraph Zero exposing the correct ports.

More work needs to be done to start multiple Dgraph nodes. I am working on that and will raise a separate PR. 

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1814)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[contrib/config/docker/docker-compose.yml, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-KzXMGx_5hRp4bRRtK1V:-KzXMGxay1fvgPjaDhEF:bwyfhfk) ([raw file](https://github.com/dgraph-io/dgraph/blob/35c2ca0f784b5952dbd723e97688f8a532d16f75/contrib/config/docker/docker-compose.yml#L1)):*
> ```YAML
> version: "3"
> ```

Not 1?

---

*[worker/groups.go, line 111 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-KzXMe1ma9TE-ZgESEb-:-KzXMe1ma9TE-ZgESEb0:bdevbor) ([raw file](https://github.com/dgraph-io/dgraph/blob/35c2ca0f784b5952dbd723e97688f8a532d16f75/worker/groups.go#L111)):*
> ```Go
> 		x.Printf("Error while connecting with group zero: %v", err)
> 		time.Sleep(delay)
> 		delay *= 2
> ```

But, cap it at 15-30s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-:-KzXMoQpkW6Uh23Se1h3:bnfp4nl)*

**Comment by pawanrawal** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[contrib/config/docker/docker-compose.yml, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-KzXMGx_5hRp4bRRtK1V:-KzXOH7JJRpc3cYYYvjE:b5qkntj) ([raw file](https://github.com/dgraph-io/dgraph/blob/35c2ca0f784b5952dbd723e97688f8a532d16f75/contrib/config/docker/docker-compose.yml#L1)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Not 1?
</blockquote></details>

This is docker_compose config version. Current latest version is 3.

---

*[worker/groups.go, line 111 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-KzXMe1ma9TE-ZgESEb-:-KzXOOZTSOH2-2t8iDD0:bvk3avv) ([raw file](https://github.com/dgraph-io/dgraph/blob/35c2ca0f784b5952dbd723e97688f8a532d16f75/worker/groups.go#L111)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

But, cap it at 15-30s.
</blockquote></details>

Done capped to 30s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814)*

**Comment by peterstace** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[contrib/config/docker/docker-compose.yml, line 1 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-KzXMGx_5hRp4bRRtK1V:-KzXO_mq6SnQJ6plj8Zb:b-sowa3) ([raw file](https://github.com/dgraph-io/dgraph/blob/35c2ca0f784b5952dbd723e97688f8a532d16f75/contrib/config/docker/docker-compose.yml#L1)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

This is docker_compose config version. Current latest version is 3.
</blockquote></details>

I haven't used docker compose before - but this looks pretty reasonable.

---

*[worker/groups.go, line 111 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-KzXMe1ma9TE-ZgESEb-:-KzXNlRY7ojvbsX7x5UB:b-ucdhsp) ([raw file](https://github.com/dgraph-io/dgraph/blob/35c2ca0f784b5952dbd723e97688f8a532d16f75/worker/groups.go#L111)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

But, cap it at 15-30s.
</blockquote></details>

I just added the same thing in another branch, looks like we ran into the same problem. For what it's worth, I've observed that it always takes less than 1 second to reconnect. So maybe `delay` should start a bit lower.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1814#-:-KzXOowW2btqiwu2C227:bnfp4nl)*

**Comment by pawanrawal** [comment]
In master as of 4cf3a1bc434450156f9f6d4db270b84531fcb695.

**Pull request closed without merging**
