### PR TITLE
Fix/posting race

### LINKED ISSUE #603: Race condition while running go test with -race flag
Starting commit routine.
[   1] Writing batch of size: 1
==================
WARNING: DATA RACE
Write at 0x0000010ee978 by goroutine 61:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:331 +0x156
  github.com/dgraph-io/dgraph/posting.populateGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/index_test.go:164 +0x180
  github.com/dgraph-io/dgraph/posting.TestRebuildIndex()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/index_test.go:172 +0x6e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Previous read at 0x0000010ee978 by goroutine 50:
  github.com/dgraph-io/dgraph/posting.periodicCommit()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:221 +0x18f

Goroutine 61 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/go/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:743 +0x12f
  github.com/dgraph-io/dgraph/posting.TestMain()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list_test.go:793 +0x3d
  main.main()
      github.com/dgraph-io/dgraph/posting/_test/_testmain.go:102 +0x1b5

Goroutine 50 (running) created at:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:335 +0x277
  github.com/dgraph-io/dgraph/posting.TestTokensTable()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/index_test.go:86 +0x219
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================
Starting commit routine.
==================
WARNING: DATA RACE
Write at 0x0000010ee9a8 by goroutine 61:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:333 +0x249
  github.com/dgraph-io/dgraph/posting.populateGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/index_test.go:164 +0x180
  github.com/dgraph-io/dgraph/posting.TestRebuildIndex()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/index_test.go:172 +0x6e
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Previous read at 0x0000010ee9a8 by goroutine 51:
  github.com/dgraph-io/dgraph/posting.batchSync()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:469 +0x10a

Goroutine 61 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/go/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:743 +0x12f
  github.com/dgraph-io/dgraph/posting.TestMain()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list_test.go:793 +0x3d
  main.main()
      github.com/dgraph-io/dgraph/posting/_test/_testmain.go:102 +0x1b5

Goroutine 51 (running) created at:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:336 +0x28f
  github.com/dgraph-io/dgraph/posting.TestTokensTable()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/index_test.go:86 +0x219
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================

==================
WARNING: DATA RACE
Write at 0x00c4209e6e00 by goroutine 40:
  github.com/dgraph-io/dgraph/algo.Difference()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/algo/uidlist.go:334 +0x5de
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:1004 +0x1845

Previous read at 0x00c4209e6e00 by goroutine 76:
  github.com/dgraph-io/dgraph/algo.(*ListIterator).Seek()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/algo/uidlist.go:128 +0x134
  github.com/dgraph-io/dgraph/posting.(*List).intersectingPostings.func1()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:615 +0x107
  github.com/dgraph-io/dgraph/posting.(*List).iterate()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:469 +0x22e
  github.com/dgraph-io/dgraph/posting.(*List).intersectingPostings()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:622 +0x22c
  github.com/dgraph-io/dgraph/posting.(*List).Uids()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:583 +0xf6
  github.com/dgraph-io/dgraph/worker.processTask()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/task.go:292 +0x23cc
  github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/task.go:48 +0x2ae
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:927 +0x136

Goroutine 40 (running) created at:
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:976 +0x12a0

Goroutine 76 (finished) created at:
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:976 +0x12a0
==================
==================
WARNING: DATA RACE
Write at 0x00c420872440 by goroutine 40:
  github.com/dgraph-io/dgraph/algo.Difference()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/algo/uidlist.go:340 +0x12e0
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:1004 +0x1845

Previous read at 0x00c420872440 by goroutine 76:
  github.com/dgraph-io/dgraph/posting.(*List).intersectingPostings()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:603 +0x2ce
  github.com/dgraph-io/dgraph/posting.(*List).Uids()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:583 +0xf6
  github.com/dgraph-io/dgraph/worker.processTask()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/task.go:292 +0x23cc
  github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/task.go:48 +0x2ae
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:927 +0x136

Goroutine 40 (running) created at:
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:976 +0x12a0

Goroutine 76 (finished) created at:
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:976 +0x12a0
==================
==================
WARNING: DATA RACE
Write at 0x00c420872488 by goroutine 40:
  github.com/dgraph-io/dgraph/algo.Difference()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/algo/uidlist.go:340 +0x142d
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:1004 +0x1845

Previous read at 0x00c420872488 by goroutine 76:
  github.com/dgraph-io/dgraph/algo.(*ListIterator).Seek()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/algo/uidlist.go:128 +0x87
  github.com/dgraph-io/dgraph/posting.(*List).intersectingPostings.func1()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:615 +0x107
  github.com/dgraph-io/dgraph/posting.(*List).iterate()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:469 +0x22e
  github.com/dgraph-io/dgraph/posting.(*List).intersectingPostings()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:622 +0x22c
  github.com/dgraph-io/dgraph/posting.(*List).Uids()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/list.go:583 +0xf6
  github.com/dgraph-io/dgraph/worker.processTask()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/task.go:292 +0x23cc
  github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/task.go:48 +0x2ae
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:927 +0x136

Goroutine 40 (running) created at:
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:976 +0x12a0

Goroutine 76 (finished) created at:
  github.com/dgraph-io/dgraph/query.ProcessGraph()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/query/query.go:976 +0x12a0
==================

==================
WARNING: DATA RACE
Write at 0x0000011841b8 by goroutine 58:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:331 +0x156
  github.com/dgraph-io/dgraph/worker.initTest()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/worker_test.go:108 +0x185
  github.com/dgraph-io/dgraph/worker.TestProcessTask()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/worker_test.go:116 +0x65
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Previous read at 0x0000011841b8 by goroutine 9:
  github.com/dgraph-io/dgraph/posting.periodicCommit()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:221 +0x18f

Goroutine 58 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/go/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:743 +0x12f
  github.com/dgraph-io/dgraph/worker.TestMain()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/worker_test.go:609 +0x3d
  main.main()
      github.com/dgraph-io/dgraph/worker/_test/_testmain.go:64 +0x1b5

Goroutine 9 (running) created at:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:335 +0x277
  github.com/dgraph-io/dgraph/worker.initTestBackup()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/backup_test.go:63 +0x19e
  github.com/dgraph-io/dgraph/worker.TestBackup()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/backup_test.go:73 +0xa5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================
Starting commit routine.
==================
WARNING: DATA RACE
Write at 0x0000011841e8 by goroutine 58:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:333 +0x249
  github.com/dgraph-io/dgraph/worker.initTest()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/worker_test.go:108 +0x185
  github.com/dgraph-io/dgraph/worker.TestProcessTask()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/worker_test.go:116 +0x65
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Previous read at 0x0000011841e8 by goroutine 10:
  github.com/dgraph-io/dgraph/posting.batchSync()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:469 +0x10a

Goroutine 58 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/go/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:743 +0x12f
  github.com/dgraph-io/dgraph/worker.TestMain()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/worker_test.go:609 +0x3d
  main.main()
      github.com/dgraph-io/dgraph/worker/_test/_testmain.go:64 +0x1b5

Goroutine 10 (running) created at:
  github.com/dgraph-io/dgraph/posting.Init()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/posting/lists.go:336 +0x28f
  github.com/dgraph-io/dgraph/worker.initTestBackup()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/backup_test.go:63 +0x19e
  github.com/dgraph-io/dgraph/worker.TestBackup()
      /home/janardhan/go/src/github.com/dgraph-io/dgraph/worker/backup_test.go:73 +0xa5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================

### PR DESCRIPTION
**Pull request by pawanrawal**
Fixes #603 

1. Move initialization to TestMain()
2. Delete posting list from RocksDB, also clear out lhmap at the end of the test, so that other tests start out with a clean slate.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/721)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/list.go, line 521 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-Kff5IQO7GM87dxRF4OW:-Kff5IQO7GM87dxRF4OX:by1nxqn) ([raw file](https://github.com/dgraph-io/dgraph/blob/71bbb2ed74a77be4d22548bf051e3029f0093152/posting/list.go#L521)):*
> ```Go
> 	defer l.Unlock()
> 
> 	if atomic.LoadInt32(&l.deleteMe) == 1 {
> ```

we shouldn't be deleting  the value if deleteMe is set.  deleteMe name is little confusing, it is actually set before we remove the pl from lhmap, so that when we try to add mutation to that pl it would fail.

---

*[posting/list_test.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-Kff67F4Z44VTU9064MW:-Kff67F4Z44VTU9064MX:b58e1gn) ([raw file](https://github.com/dgraph-io/dgraph/blob/71bbb2ed74a77be4d22548bf051e3029f0093152/posting/list_test.go#L140)):*
> ```Go
> // It also clears the lhmap so that calls to GetOrCreate return a new list.
> func delPosting(t *testing.T, ol *List) {
> 	ol.SetForDeletion()
> ```

SyncIfDirty shouldn't be deleting the value from rocksdb. The SetForDeletion is actually used to mark a pl before deletion from lhmap, not rocksdb. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/721)*

**Comment by pawanrawal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[posting/list.go, line 521 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-Kff5IQO7GM87dxRF4OW:-KffFZ6m8D1CEEiOpTwj:b32n8ta) ([raw file](https://github.com/dgraph-io/dgraph/blob/71bbb2ed74a77be4d22548bf051e3029f0093152/posting/list.go#L521)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

we shouldn't be deleting  the value if deleteMe is set.  deleteMe name is little confusing, it is actually set before we remove the pl from lhmap, so that when we try to add mutation to that pl it would fail.
</blockquote></details>

Removed it.

---

*[posting/list_test.go, line 140 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-Kff67F4Z44VTU9064MW:-KffFQnu9sEx1XSv7y3p:b-rp50vi) ([raw file](https://github.com/dgraph-io/dgraph/blob/71bbb2ed74a77be4d22548bf051e3029f0093152/posting/list_test.go#L140)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

SyncIfDirty shouldn't be deleting the value from rocksdb. The SetForDeletion is actually used to mark a pl before deletion from lhmap, not rocksdb. 
</blockquote></details>

I see I have moved stuff to a new `Delete()` function in `list.go`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/721)*

**Comment by manishrjain** [comment]
:lgtm: Make the changes required, then submit.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[posting/hash.go, line 111 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-KfiKntgL2RIgPyWhov5:-KfiKntgL2RIgPyWhov6:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/e7baac575bfdbf231e351652846475c27221d371/posting/hash.go#L111)):*
> ```Go
> }
> 
> func (s *listMapShard) delete(key uint64) {
> ```

Remove this.

---

*[posting/index_test.go, line 74 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-KfiKMOD6Lg-9JHNcPmi:-KfiKMOD6Lg-9JHNcPmj:b-h1dfol) ([raw file](https://github.com/dgraph-io/dgraph/blob/e7baac575bfdbf231e351652846475c27221d371/posting/index_test.go#L74)):*
> ```Go
> }
> 
> const schemaStrAlt = `
> ```

schemaVal

---

*[posting/list.go, line 733 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-KfiKmPdEvZVAKUAobJW:-KfiKmPdEvZVAKUAobJX:b-6nzv6v) ([raw file](https://github.com/dgraph-io/dgraph/blob/e7baac575bfdbf231e351652846475c27221d371/posting/list.go#L733)):*
> ```Go
> }
> 
> func (l *List) Delete() error {
> ```

Remove this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/721#-:-KfiL1-08IX_ivHsml23:b-z8vlhn)*

**Comment by pawanrawal** [comment]
Merged

**Pull request closed without merging**
