### PR TITLE
doc: update /admin endpoint documentation.

### PR DESCRIPTION
**Pull request by minhaj-shakeel**
Fixes GRAPHQL-618.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6415)

 
 
 
 
 
 
 
 
 

Docs Preview: [Dgraph Preview](https://dgraph-e10961d177-93397.surge.sh)

### CODE REVIEW

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6415)* status: all files reviewed, 4 unresolved discussions (waiting on @danielmai, @manishrjain, @MichaelJCompton, @minhaj-shakeel, and @vvbalaji-dgraph)

___
*[p/000000.vlog, line 0 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5ZSMb9cFnL4KSmTfM:-MH5ZSMc4yHKnYR27h6v:b-nitdxc) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/p/000000.vlog#L0)):*
Dont commit p and `w` directories please.
___
*[wiki/content/graphql/admin/index.md, line 81 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5ZkG14e1N2ENbQCxe:-MH5ZkG14e1N2ENbQCxf:bx88xfc) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/wiki/content/graphql/admin/index.md#L81)):*
> ```Markdown
> 
> 	"""
> 	A NodeState is the state of an individual node in the Dgraph cluster.
> ```

an individual Alpha or Zero node
___
*[wiki/content/graphql/admin/index.md, line 187 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5ZvOn4FgD78w-0MvT:-MH5ZvOn4FgD78w-0MvU:bdn9bl7) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/wiki/content/graphql/admin/index.md#L187)):*
> ```Markdown
> 	directive @dgraph(type: String, pred: String) on OBJECT | INTERFACE | FIELD_DEFINITION
> 	directive @id on FIELD_DEFINITION
> 	directive @secret(field: String!, pred: String) on OBJECT | INTERFACE
> ```

Is this directive used in the admin schema? If not, then it shouldn't be here.
___
*[wiki/content/graphql/admin/index.md, line 331 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5_kYp7V7oitf_y8a0:-MH5_kYp7V7oitf_y8a1:b-dbi8xf) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/wiki/content/graphql/admin/index.md#L331)):*
> ```Markdown
> * [ACL](https://dgraph.io/docs/enterprise-features/access-control-lists/#using-graphql-admin-api).
> * [Backups](https://dgraph.io/docs/enterprise-features/binary-backups/#create-a-backup).
> * [Restore](https://dgraph.io/docs/enterprise-features/binary-backups/#restore-from-backup).
> ```

We should also modify the restore page to show the GraphQL API for doing restore.

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6415)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @danielmai, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[p/000000.vlog, line  at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5ZSMb9cFnL4KSmTfM:-MHAs3Tu6K4xPR88-8jE:b-hrsqj6) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/p/000000.vlog#L)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Dont commit p and `w` directories please.
</blockquote></details>

That was by mistake.
___
*[wiki/content/graphql/admin/index.md, line 81 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5ZkG14e1N2ENbQCxe:-MHAs9Yu8bas2ySfeWxk:bs7wumb) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/wiki/content/graphql/admin/index.md#L81)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

an individual Alpha or Zero node
</blockquote></details>

Done.
___
*[wiki/content/graphql/admin/index.md, line 187 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5ZvOn4FgD78w-0MvT:-MHAsB4O3gv5YCE-eOAN:bfk5dhy) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/wiki/content/graphql/admin/index.md#L187)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Is this directive used in the admin schema? If not, then it shouldn't be here.
</blockquote></details>

Not used in the schema described here, removing it for now.
___
*[wiki/content/graphql/admin/index.md, line 331 at r1](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MH5_kYp7V7oitf_y8a0:-MHAsGPd9ZCIIkBNSZPG:b-qzmapv) ([raw file](https://github.com/dgraph-io/dgraph/blob/9d45421f1f2f5d0e551fb1b1ee87fb28b75b88f6/wiki/content/graphql/admin/index.md#L331)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

We should also modify the restore page to show the GraphQL API for doing restore.
</blockquote></details>

Modified it, please have a look.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6415)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @danielmai, @manishrjain, @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/enterprise-features/binary-backups.md, line 266 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MHBH0wUDkrhnDCaG0oM:-MHBH0wUDkrhnDCaG0oN:b-ltq3re) ([raw file](https://github.com/dgraph-io/dgraph/blob/985d6a6b281a633cd26d887e3d8fb77224d8f172/wiki/content/enterprise-features/binary-backups.md#L266)):*
> ```Markdown
>   }){
>     message
>     code    
> ```

extra spaces at the end can be removed
___
*[wiki/content/enterprise-features/binary-backups.md, line 346 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MHBH7or68pXLHM6XWGC:-MHBH7or68pXLHM6XWGD:b4ycr5w) ([raw file](https://github.com/dgraph-io/dgraph/blob/985d6a6b281a633cd26d887e3d8fb77224d8f172/wiki/content/enterprise-features/binary-backups.md#L346)):*
> ```Markdown
> ```
> {{% notice "note" %}}
> `dgraph restore` is being deprecated, please use GraphQL api for Restoring from Backup.
> ```

Don't remove introduction to `dgraph restore` yet, just mention its deprecated/

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6415)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @danielmai, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/enterprise-features/binary-backups.md, line 266 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MHBH0wUDkrhnDCaG0oM:-MHBMHNsEaonp8iXPhTy:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/985d6a6b281a633cd26d887e3d8fb77224d8f172/wiki/content/enterprise-features/binary-backups.md#L266)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

extra spaces at the end can be removed
</blockquote></details>

Done.
___
*[wiki/content/enterprise-features/binary-backups.md, line 346 at r2](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MHBH7or68pXLHM6XWGC:-MHBMHtfBD2-AY7kXy7t:b-iw8gl0) ([raw file](https://github.com/dgraph-io/dgraph/blob/985d6a6b281a633cd26d887e3d8fb77224d8f172/wiki/content/enterprise-features/binary-backups.md#L346)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

Don't remove introduction to `dgraph restore` yet, just mention its deprecated/
</blockquote></details>

Added it.

**Review by pawanrawal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6415)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @danielmai, @manishrjain, @MichaelJCompton, @minhaj-shakeel, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/enterprise-features/binary-backups.md, line 273 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MHBnpn-DidmeJpweh42:-MHBnpn-DidmeJpweh43:b-oh3mwy) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0a8897fa66e21ef2f15a6cbd63a4d561f2a718a/wiki/content/enterprise-features/binary-backups.md#L273)):*
> ```Markdown
> Restore can be performed from Amazon S3 / Minio or from Local Directory. Below is the `RestoreInput` to be passed into the mutation. 
> ```graphql
> input RestoreInput {
> ```

No need for all this input type. You can just mention that you can look at `RestoreInput` from the docs for all possible input options.

**Review by minhaj-shakeel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/6415)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @danielmai, @manishrjain, @MichaelJCompton, @pawanrawal, and @vvbalaji-dgraph)

___
*[wiki/content/enterprise-features/binary-backups.md, line 273 at r3](https://reviewable.io/reviews/dgraph-io/dgraph/6415#-MHBnpn-DidmeJpweh42:-MHBt6UdEJaEipHeztHr:brulh2f) ([raw file](https://github.com/dgraph-io/dgraph/blob/c0a8897fa66e21ef2f15a6cbd63a4d561f2a718a/wiki/content/enterprise-features/binary-backups.md#L273)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary><blockquote>

No need for all this input type. You can just mention that you can look at `RestoreInput` from the docs for all possible input options.
</blockquote></details>

`RestoreInput` is not present in the code. I have added `BackupInput` in the backup section also.

**Review by pawanrawal — APPROVED** [review]

**Pull request merged**
