### PR TITLE
Check validity of iterator

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/643)

### CODE REVIEW

**Comment by gacharya255** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[worker/tokens.go, line 25 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/643#-Ke2NnkG8BvjQf6KQ4wE:-Ke2NnkG8BvjQf6KQ4wF:ba6xhbf) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf859ab7c0e8a2d501c79435614a6452df434257/worker/tokens.go#L25)):*
> ```Go
> 	it := pstore.NewIterator()
> 	defer it.Close()
> 	it.Seek(x.IndexKey(attr, ineqValueToken))
> ```

Thanks for fixing this. For lt and leq, I think we also should do a SeekForPrev so that the first token received is what we want.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/643)*

**Comment by gacharya255** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/643#-:-Ke2VvC6q9YaL7-l4H8X:bnfp4nl)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[worker/tokens.go, line 25 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/643#-Ke2NnkG8BvjQf6KQ4wE:-Ke2VpvdYcdgo6x6a8iX:bl38h0s) ([raw file](https://github.com/dgraph-io/dgraph/blob/bf859ab7c0e8a2d501c79435614a6452df434257/worker/tokens.go#L25)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Thanks for fixing this. For lt and leq, I think we also should do a SeekForPrev so that the first token received is what we want.
</blockquote></details>

As discussed. We need to update rocksDB to support `SeekForPrev`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/643)*

**Comment by gacharya255** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/tokens.go, line 40 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/643#-Ke2YjQXTqohV41YMUgO:-Ke2YjQXTqohV41YMUgP:b-1x9ge9) ([raw file](https://github.com/dgraph-io/dgraph/blob/78d8c94e711224a778d643643ae10d7b230b67ad/worker/tokens.go#L40)):*
> ```Go
> 	isGeqOrGt := f == "geq" || f == "gt"
> 
> 	if f == "lt" || (f == "leq" && idxKey.Term != ineqValueToken) {
> ```

For both lt and leq, you want to include ineqValueToken if it is equal. The tokenizing is only bucketing. You might have some hits even in the same bucket.

For example, filter by date < 2015-01-05, the token would be 2015. You still need to inspect it for "lt".

It should be if (f=="lt" || f=="leq") && idxKey.Term != ineqValueToken or maybe even just if !isGeqOrGt && idxKey.Term != ineqValueToken, do Prev.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/643)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[worker/tokens.go, line 40 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/643#-Ke2YjQXTqohV41YMUgO:-Ke2Zz7441NeZjw0xG3C:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/78d8c94e711224a778d643643ae10d7b230b67ad/worker/tokens.go#L40)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

For both lt and leq, you want to include ineqValueToken if it is equal. The tokenizing is only bucketing. You might have some hits even in the same bucket.

For example, filter by date < 2015-01-05, the token would be 2015. You still need to inspect it for "lt".

It should be if (f=="lt" || f=="leq") && idxKey.Term != ineqValueToken or maybe even just if !isGeqOrGt && idxKey.Term != ineqValueToken, do Prev.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/643)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
