### PR TITLE
Support multiple scalar values.

### PR DESCRIPTION
**Pull request by pawanrawal**
Initial support for supporting multiple values. The PR is getting big so better to get this part reviewed.

TODO 
- [ ] Return item in array if schema type is list type and even if it has just one value.
- [x] Disallow change from [int] => int if data is present for a predicate.
- [ ] Handle deletion of indexes. Don't delete mapping (token => uid) if some other value than the one being deleted has the same token.
- [x] Handle list type with lang.
- [x] Check UI still works.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/1363)

### CODE REVIEW

**Comment by janardhan1993** [comment]
Reviewed 14 of 23 files at r1.
Review status: 11 of 22 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main_test.go, line 292 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaJRIPfzB7c9soVR6z:-KsaJRIPfzB7c9soVR7-:b-i2yn91) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/cmd/dgraph/main_test.go#L292)):*
> ```Go
> 	output, err = runQuery(q4)
> 	require.NoError(t, err)
> 	require.JSONEq(t, `{"data": {"user":[{"_predicate_":["name","age"]}]}}`, output)
> ```

Why have the number of predicates changed ?

---

*[posting/index.go, line 369 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaP2ygG8B5iYhnWAb_:-KsaP2ygG8B5iYhnWAba:b3n5h0x) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/posting/index.go#L369)):*
> ```Go
> 		// Exact matches.
> 		if found && val.Value != nil {
> 			if err := addIndexMutations(ctx, t, val, protos.DirectedEdge_DEL); err != nil {
> ```

We need to handle the case when multiple values within the list have same tokens.

---

*[posting/list.go, line 455 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaJwLQ7ghRMBUI33hq:-KsaJwLQ7ghRMBUI33hr:bj78skj) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/posting/list.go#L455)):*
> ```Go
> 		if len(t.Lang) > 0 {
> 			t.ValueId = farm.Fingerprint64([]byte(t.Lang))
> 		} else if schema.State().IsList(t.Attr) {
> ```

What if it's lang in list ?

---

*[posting/list.go, line 814 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaK8aTy8PjkFhKQuMy:-KsaK8aTy8PjkFhKQuMz:btcfx0l) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/posting/list.go#L814)):*
> ```Go
> 	l.iterate(0, func(p *protos.Posting) bool {
> 		if len(p.Value) == 0 {
> 			return true
> ```

What is this for ?

---

*[query/groupby.go, line 218 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaKmrjKXM_xrDQCe6-:-KsaKmrjKXM_xrDQCe60:b-lyzee3) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/query/groupby.go#L218)):*
> ```Go
> 			for i, v := range child.valueMatrix {
> 				srcUid := child.SrcUIDs.Uids[i]
> 				val, err := convertTo(v.Values[0])
> ```

Don't we want to group by all the values ?

---

*[query/query.go, line 947 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaLiNKqvzsybtO3bju:-KsaLiNKqvzsybtO3bjv:b43zc73) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/query/query.go#L947)):*
> ```Go
> 	}
> 	for i := 0; i < count; i++ {
> 		out[i] = emptyList
> ```

If out[i] is not going to be modified, we can create empty list once outside the function and reuse it.

---

*[worker/task.go, line 294 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaNh2a7oRiHoNSczAE:-KsaNh2a7oRiHoNSczAF:b1eun3r) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/worker/task.go#L294)):*
> ```Go
> 
> 		var valTid types.TypeID
> 		if len(vals) > 0 {
> ```

len(vals) > 0 here, we checked it already earlier.

---

*[worker/task.go, line 302 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaOAEhY7ytq_SiEglQ:-KsaOAEhY7ytq_SiEglR:bf5r9qx) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/worker/task.go#L302)):*
> ```Go
> 		var vl protos.ValuesList
> 		for _, val := range vals {
> 			if attrTyp, err = schema.State().TypeOf(attr); err == nil {
> ```

I guess we can move it outside for loop, decide the type before and convert it inside for loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363)*

**Comment by manishrjain** [comment]
Looks good to me. I'll let @janardhan1993 make the final call.

---

Reviewed 19 of 23 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[protos/task.proto, line 58 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaQ0lyCUGWZDp41rPo:-KsaQ0lyCUGWZDp41rPp:b5ytbmy) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3ff1db7b3015e261b5c6851ad447ec6db61e555/protos/task.proto#L58)):*
> ```protobuf
> message Result {
> 	repeated List uid_matrix = 1;
> 	repeated ValuesList value_matrix = 2;
> ```

ValueList

---

*[worker/task.go, line 281 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaQj1_O3mTiF3XpfLo:-KsaQj1_O3mTiF3XpfLp:bar64c7) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3ff1db7b3015e261b5c6851ad447ec6db61e555/worker/task.go#L281)):*
> ```Go
> 			var val types.Val
> 			val, err = pl.ValueFor(q.Langs)
> 			if val.Tid == types.PasswordID && srcFn.fnType != PasswordFn {
> ```

Ensure that passwords can't be set as a list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-:-KsaQzprI_GoBoXirHQx:b-n7mz6o)*

**Comment by pawanrawal** [comment]
Review status: 11 of 26 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[cmd/dgraph/main_test.go, line 292 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaJRIPfzB7c9soVR6z:-KsgB4jnwXzQ5ysrRk6G:bfmzagb) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/cmd/dgraph/main_test.go#L292)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Why have the number of predicates changed ?
</blockquote></details>

Uhmm, they didn't. It was `age` and `name` earlier too.

---

*[posting/index.go, line 369 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaP2ygG8B5iYhnWAb_:-KsgvgOdTaILG6ngwV6E:b-w49sw7) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/posting/index.go#L369)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

We need to handle the case when multiple values within the list have same tokens.
</blockquote></details>

Yes, thats still pending.

---

*[posting/list.go, line 455 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaJwLQ7ghRMBUI33hq:-KsgCqee6mRKbBLgP04i:blqcprp) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/posting/list.go#L455)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

What if it's lang in list ?
</blockquote></details>

Then that gets handled above. We fingerprint lang.

---

*[posting/list.go, line 814 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaK8aTy8PjkFhKQuMy:-KsgCxfcTXB6XJ_TH6fa:bblcdds) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/posting/list.go#L814)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

What is this for ?
</blockquote></details>

Wasn't needed, removed.

---

*[protos/task.proto, line 58 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaQ0lyCUGWZDp41rPo:-KsgD945Gucvb5eLeT26:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3ff1db7b3015e261b5c6851ad447ec6db61e555/protos/task.proto#L58)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

ValueList
</blockquote></details>

Done.

---

*[query/groupby.go, line 218 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaKmrjKXM_xrDQCe6-:-KsgvkmxbNpEoqqhtJzC:b-ollmkq) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/query/groupby.go#L218)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

Don't we want to group by all the values ?
</blockquote></details>

I disallowed grouping by predicate of list type. Sorting is also not allowed.

---

*[query/query.go, line 947 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaLiNKqvzsybtO3bju:-KsgEESuvKPVrIBpXPdd:b-b8pyav) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/query/query.go#L947)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

If out[i] is not going to be modified, we can create empty list once outside the function and reuse it.
</blockquote></details>

Actually, I am not sure why we even need createNilValuesList in newGraph. This is something that worker/task.go is supposed to do. Removing it.

---

*[worker/task.go, line 294 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaNh2a7oRiHoNSczAE:-KsgKuObP8EsAEFGyWTS:bcgacfy) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/worker/task.go#L294)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

len(vals) > 0 here, we checked it already earlier.
</blockquote></details>

good one, done

---

*[worker/task.go, line 302 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaOAEhY7ytq_SiEglQ:-KsgNoK4Pne-pXzguO6e:bdybgth) ([raw file](https://github.com/dgraph-io/dgraph/blob/45a828e0c6d4d339651944f11f8c81211e289563/worker/task.go#L302)):*
<details><summary><i>Previously, janardhan1993 (Janardhan Reddy) wrote…</i></summary><blockquote>

I guess we can move it outside for loop, decide the type before and convert it inside for loop.
</blockquote></details>

Yup, doing that now.

---

*[worker/task.go, line 281 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363#-KsaQj1_O3mTiF3XpfLo:-KsgKZI097dt8xF2CYgh:b-h7xeel) ([raw file](https://github.com/dgraph-io/dgraph/blob/b3ff1db7b3015e261b5c6851ad447ec6db61e555/worker/task.go#L281)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Ensure that passwords can't be set as a list.
</blockquote></details>

Done in schema parsing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/1363)*

**Comment by pawanrawal** [comment]
In master via 1728afa703813e66ff620c5cc4bd4a5783e843bd.

**Comment by pawanrawal** [comment]
Merged to master

**Pull request closed without merging**
