### PR TITLE
Make geo queries easier

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/443)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 5 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[gql/parser_test.go, line 696 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aoSa6UVSqCAlZq1g4:-K_aoSa7mNSveoPVW0wH:bjior9v) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/gql/parser_test.go#L696)):*
> ```Go
> 	query {
> 		me(_uid_:0x0a) {
> 			friends @filter(near(loc, [1 , 2 ] )) {
> ```

near(loc, [-1.35, 2.00], 1000)

---

*[gql/parser_test.go, line 712 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aoqHY5ywySlzNy-JJ:-K_aoqHY5ywySlzNy-JK:b-qobngs) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/gql/parser_test.go#L712)):*
> ```Go
> 	query {
> 		me(_uid_:0x0a) {
> 			friends @filter(near(loc, [[1 , 2 ], [3, 4] , [5, 6]] )) {
> ```

@filter(within(loc, [[-2.0, 1.0], ..],))

---

*[gql/state.go, line 195 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_apHMFYZU1jfm4XC_v:-K_apHMGrrfq7BzNVDW2:bw49906) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/gql/state.go#L195)):*
> ```Go
> 			depth := 1
> 			for {
> 				r := l.Next()
> ```

Check for lex.EOF, and also for right round bracket.

---

*[query/query_test.go, line 1984 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqIg79iUN367YIgmX:-K_aqIg79iUN367YIgmY:b-ftlj23) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L1984)):*
> ```Go
> 	defer os.RemoveAll(dir2)
> 	query := `{
> 		me(near(loc, [1.1,2.0], 5)) {
> ```

Add a test case where near doesn't have the distance. Also, use float for the "correct" case.

Try to pass a negative float for distance.

---

*[query/query_test.go, line 2000 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqdPimL62336JMeja:-K_aqdPimL62336JMejb:bkp11v9) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L2000)):*
> ```Go
> 	defer os.RemoveAll(dir2)
> 	query := `{
> 		me(within(loc,  [[0.0,0.0], [2.0,0.0], [1.5, 3.0], [0.0, 2.0], [0.0, 0.0]])) {
> ```

Check if you pass a third argument here. It should error out.

---

*[query/query_test.go, line 2015 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqi8H0rhmLEkwz7L-:-K_aqi8H0rhmLEkwz7L0:bbb23c5) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L2015)):*
> ```Go
> 	defer os.RemoveAll(dir2)
> 	query := `{
> 		me(contains(loc,  [2.0, 0.0])) {
> ```

Also check for passing a polygon.

---

*[query/query_test.go, line 2030 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqkk8-_JWeIQNnkaX:-K_aqkk8-_JWeIQNnkaY:byy4ft5) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L2030)):*
> ```Go
> 	defer os.RemoveAll(dir2)
> 	query := `{
> 		me(intersects(loc, [[0.0,0.0], [2.0,0.0], [1.5, 3.0], [0.0, 2.0], [0.0, 0.0]])) {
> ```

Check passing of a point -- this should error out. 

---

*[types/s2.go, line 133 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_bxNbNDpKgScQlb2L0:-K_bxNbNDpKgScQlb2L1:btfs05t) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L133)):*
> ```Go
> }
> 
> func ConvertToGeoJson(str string) (geom.T, error) {
> ```

can be private fn. Also, convertToGeom(..)

---

*[types/s2.go, line 142 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_bxZSfbn7wDhg92hbv:-K_bxZSfbn7wDhg92hbw:b-hx27yx) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L142)):*
> ```Go
> 	var err error
> 	fmt.Println(s)
> 	if s[0] == '[' && s[1] != '[' {
> ```

s[0:2] == "[[" { .. } else if s[0] == '[' { .. } else ...

---

*[types/s2.go, line 151 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_byjFvpva3dth3Hufe:-K_byjFwLy1hFRaPRynV:b7qdqg7) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L151)):*
> ```Go
> 	} else if s[0] == '[' && s[1] == '[' {
> 		g.Type = "Polygon"
> 		err = m.UnmarshalJSON([]byte("[" + s + "]"))
> ```

fmt.Sprintf(..)

---

*[types/s2.go, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_byyheQ6PkYEk66hrC:-K_byyheQ6PkYEk66hrD:b-ydj8ll) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L161)):*
> ```Go
> 		}
> 		coords := g1.(*geom.Polygon).Coords()
> 		if !reflect.DeepEqual(coords[0][0], coords[0][len(coords[0])-1]) {
> ```

Don't import reflect.

---

*[types/s2_test.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_bz0i8wOXDTJq76R69:-K_bz0i8wOXDTJq76R6A:bhb2fpx) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2_test.go#L37)):*
> ```Go
> 
> func TestConvertToGeoJson_PolyError2(t *testing.T) {
> 	s := `[[1, 2], [3, 4], [4, 6], [1, 2], []]`
> ```

Use some real world coordinates.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/443)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[gql/parser_test.go, line 696 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aoSa6UVSqCAlZq1g4:-K_c-mMLE4-OyRBLvqqA:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/gql/parser_test.go#L696)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

near(loc, [-1.35, 2.00], 1000)
</blockquote></details>

Done.

---

*[gql/parser_test.go, line 712 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aoqHY5ywySlzNy-JJ:-K_c-xenzuSDkfZhtSD3:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/gql/parser_test.go#L712)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

@filter(within(loc, [[-2.0, 1.0], ..],))
</blockquote></details>

Done.

---

*[gql/state.go, line 195 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_apHMFYZU1jfm4XC_v:-K_c01fhmkflIx3wCkSK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/gql/state.go#L195)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check for lex.EOF, and also for right round bracket.
</blockquote></details>

Done.

---

*[query/query_test.go, line 1984 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqIg79iUN367YIgmX:-K_c0XKXGQ6OidpOzI0B:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L1984)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a test case where near doesn't have the distance. Also, use float for the "correct" case.

Try to pass a negative float for distance.
</blockquote></details>

Done.

---

*[query/query_test.go, line 2000 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqdPimL62336JMeja:-K_c1yheYvUBiQrfIXV2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L2000)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check if you pass a third argument here. It should error out.
</blockquote></details>

Done.

---

*[query/query_test.go, line 2015 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqi8H0rhmLEkwz7L-:-K_c3TV48A28T0Zlhqy9:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L2015)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Also check for passing a polygon.
</blockquote></details>

Done.

---

*[query/query_test.go, line 2030 at r1](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_aqkk8-_JWeIQNnkaX:-K_c3lNIb093ihsjifaQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/363bea38c963edea2057893d375ee72ab8008310/query/query_test.go#L2030)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Check passing of a point -- this should error out. 
</blockquote></details>

Done.

---

*[types/s2.go, line 133 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_bxNbNDpKgScQlb2L0:-K_c3w-obGBVDLw-rV-6:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L133)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

can be private fn. Also, convertToGeom(..)
</blockquote></details>

Done.

---

*[types/s2.go, line 142 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_bxZSfbn7wDhg92hbv:-K_c4MJbpFrR4BcwzaYj:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L142)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

s[0:2] == "[[" { .. } else if s[0] == '[' { .. } else ...
</blockquote></details>

Done.

---

*[types/s2.go, line 151 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_byjFvpva3dth3Hufe:-K_c4MqpP8E5F1y2bcaK:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L151)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

fmt.Sprintf(..)
</blockquote></details>

Done.

---

*[types/s2.go, line 161 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_byyheQ6PkYEk66hrC:-K_c4YX9Qy9SAruo5hH2:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2.go#L161)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Don't import reflect.
</blockquote></details>

Done.

---

*[types/s2_test.go, line 37 at r2](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_bz0i8wOXDTJq76R69:-K_c5esqTiT6BtQ4U1l7:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/d9dd0ecb3e4f4e9345f76e501fdd7b657f24b93e/types/s2_test.go#L37)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Use some real world coordinates.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/443)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-:-K_cAxv88GCwf4XohPhi:bnfp4nl)*

**Comment by jchiu0** [comment]
:lgtm: Some small remarks.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[query/query_test.go, line 1984 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cBQSrQpW190i7kTOd:-K_cBQSrQpW190i7kTOe:bxeeryn) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/query/query_test.go#L1984)):*
> ```Go
> 	defer os.RemoveAll(dir2)
> 	query := `{
> 		me(near(loc, [1.1,2.0], 5.001)) {
> ```

Does it work with just "5"?

Looking at the test case, I wonder if we can add coordinates for one or two other persons. Maybe one that is far away and one that is also within the radius.

---

*[types/geofilter.go, line 127 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cDE7mhP4vYJteICc4:-K_cDE7mhP4vYJteICc5:blpg8lv) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/types/geofilter.go#L127)):*
> 
Function comments? This is just used for test now? If so, move it into geofilter_test?

---

*[types/geofilter.go, line 142 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cD8X65zx1Hu6BjwHr:-K_cD8X65zx1Hu6BjwHs:b-1uxk21) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/types/geofilter.go#L142)):*
> ```Go
> }
> 
> // queryTokens returns the tokens to be used to look up the geo index for a given filter.
> ```

queryTokensGeo returns...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-:-K_cEC6pUbYSMO1d2WjH:b-hka4rz)*

**Comment by ashwin95r** [comment]
Review status: 5 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[query/query_test.go, line 1984 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cBQSrQpW190i7kTOd:-K_cIaA_6E8SEX9E8kkJ:blaazqt) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/query/query_test.go#L1984)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Does it work with just "5"?

Looking at the test case, I wonder if we can add coordinates for one or two other persons. Maybe one that is far away and one that is also within the radius.
</blockquote></details>

Yes it does. Added two more and modified the tests.

---

*[types/geofilter.go, line 127 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cDE7mhP4vYJteICc4:-K_cGYSoSZ4NmMqg3_pd:bs2hnv9) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/types/geofilter.go#L127)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

> 
Function comments? This is just used for test now? If so, move it into geofilter_test?
</blockquote></details>

Moved to test. Done.

---

*[types/geofilter.go, line 142 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cD8X65zx1Hu6BjwHr:-K_cGeIFvII6kz_XEcMv:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/types/geofilter.go#L142)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

queryTokensGeo returns...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/443)*

**Comment by jchiu0** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 1984 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cBQSrQpW190i7kTOd:-K_cLhhyCkxfKuaAUXz_:b-q1ahhn) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/query/query_test.go#L1984)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary><blockquote>

Yes it does. Added two more and modified the tests.
</blockquote></details>

Andrea seems pretty near to (1.1, 2.0) but is not within radius of 5?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/443)*

**Comment by ashwin95r** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[query/query_test.go, line 1984 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/443#-K_cBQSrQpW190i7kTOd:-K_cOZtIvdJvTbti476C:bnphkrf) ([raw file](https://github.com/dgraph-io/dgraph/blob/9027984de45443fec45c866de5259ee809d5daea/query/query_test.go#L1984)):*
<details><summary><i>Previously, jchiu0 (Jay Chiu) wrote…</i></summary><blockquote>

Andrea seems pretty near to (1.1, 2.0) but is not within radius of 5?
</blockquote></details>

It's 5 meters and these lat longs tend to be quite far.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/443)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
