### PR TITLE
Language specific stemmers and stop words lists

### PR DESCRIPTION
**Pull request by tzdybal**
Added support for language specific stemmers and stop words lists.

All per-language tokenizers supported by Bleve (underlying library is: https://github.com/tebeka/snowball) are supported. Stop words lists are also provided for all of those languages.

List of supported languages: danish, dutch, english, finnish, french, german, hungarian, italian, norwegian, portuguese, romanian, russian, spanish, swedish, turkish.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/704)

### CODE REVIEW

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 97 of 98 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-:-KfL3iQRGJrlzFP6XSUL:bnfp4nl)*

**Comment by gacharya255** [comment]
LG for per language tokenizer.
LG for refactoring into fts.go.
LG for stop words and other bleve related improvements.

:lgtm: 

Just some minor comments.

---

Reviewed 15 of 98 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[gql/parser_test.go, line 1248 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMLfLSU_FXp6TKV23w:-KfMLfLSU_FXp6TKV23x:b-vn19iu) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/gql/parser_test.go#L1248)):*
> ```Go
> 		me(id:0x0a) {
> 			friends @filter(a(a, "a") or b(b, "a")
> 			and c(c, "a")) {
> ```

Might be clearer and a better test if we use a different argument? Example: a(aa, "aaa")

---

*[tok/fts.go, line 56 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMKWcV25a17XMvniiE:-KfMKWcV25a17XMvniiF:b-bqq4nq) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/fts.go#L56)):*
> ```Go
> 		defineStopWordsList(lang)
> 		defineAnalyzer(lang)
> 		RegisterTokenizer(NewFullTextTokenizer(countryCode(lang)))
> ```

Could remove NewFullTextTokenizer? and just create the tokenizer here?

---

*[tok/fts.go, line 166 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMJrjSEtFJAq0rts_d:-KfMJrjSEtFJAq0rts_e:b2xov3w) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/fts.go#L166)):*
> ```Go
> 	// List based on https://godoc.org/golang.org/x/text/language#Tag
> 	// It contains more languages than supported by Bleve, to enable seamless addition of new langs.
> 	mapping := map[string]string{
> ```

Might be better to just move this initialization inside init(), though Go might be doing this optimization anyway.

---

*[tok/fts.go, line 252 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMJapH6SNxBL60SW_h:-KfMJapH6SNxBL60SW_i:bijzqhf) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/fts.go#L252)):*
> ```Go
> 		return code
> 	} else {
> 		panic("Unsupported language: " + lang)
> ```

Actually a panic is fine but we have been doing x.AssertTruef(ok, "...") for the rest of the codebase.. Could be:

x.AssertTruef(...)
return code

---

*[tok/tok_test.go, line 84 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMKHgsWAg3I_pbqDXO:-KfMKHgsWAg3I_pbqDXP:b-rnxd9f) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/tok_test.go#L84)):*
> ```Go
> 
> 	tokens, err := tokenizer.Tokens(val)
> 	require.Nil(t, err)
> ```

require.NoError(t, err)

---

*[worker/tokens.go, line 10 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMMZv88FV3S9sHp0FQ:-KfMMZv88FV3S9sHp0FR:b4xwtct) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/worker/tokens.go#L10)):*
> ```Go
> )
> 
> // Return string tokens from function arguments. It maps funcion type to correct tokenizer.
> ```

function type

---

*[worker/tokens.go, line 15 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMMc3FosGyPWNbY69L:-KfMMc3FosGyPWNbY69M:bt77mag) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/worker/tokens.go#L15)):*
> ```Go
> 	switch funcType {
> 	case FullTextSearchFn:
> 		return tok.GetTextTokens(funcArgs, lang)
> ```

No action required. Find it a bit messy when a tokenizer can be used in two different ways.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-:-KfMMsEuWo1pM5BumynT:b-gr8nb3)*

**Comment by tzdybal** [comment]
Review status: 82 of 89 files reviewed at latest revision, 7 unresolved discussions.

---

*[gql/parser_test.go, line 1248 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMLfLSU_FXp6TKV23w:-KfPIFK5R9FDKKBBrk7k:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/gql/parser_test.go#L1248)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Might be clearer and a better test if we use a different argument? Example: a(aa, "aaa")
</blockquote></details>

Done.

---

*[tok/fts.go, line 56 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMKWcV25a17XMvniiE:-KfPJ1Wnj_CO8wVeG4b-:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/fts.go#L56)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Could remove NewFullTextTokenizer? and just create the tokenizer here?
</blockquote></details>

Done.

---

*[tok/fts.go, line 166 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMJrjSEtFJAq0rts_d:-KfPLMYVOTbEPRUAGC8C:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/fts.go#L166)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Might be better to just move this initialization inside init(), though Go might be doing this optimization anyway.
</blockquote></details>

Done.

---

*[tok/fts.go, line 252 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMJapH6SNxBL60SW_h:-KfPLNxbmU6tADH9Gz8A:b6rjjyc) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/fts.go#L252)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

Actually a panic is fine but we have been doing x.AssertTruef(ok, "...") for the rest of the codebase.. Could be:

x.AssertTruef(...)
return code
</blockquote></details>

Done. All other direct invocations of `panic` replaced with `x.Check(err)`

---

*[tok/tok_test.go, line 84 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMKHgsWAg3I_pbqDXO:-KfPLJ1N5pC5sYZCD0MI:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/tok/tok_test.go#L84)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

require.NoError(t, err)
</blockquote></details>

Done.

---

*[worker/tokens.go, line 10 at r3](https://reviewable.io:443/reviews/dgraph-io/dgraph/704#-KfMMZv88FV3S9sHp0FQ:-KfPFYdQhBTRhUSYbqf4:byslss1) ([raw file](https://github.com/dgraph-io/dgraph/blob/4710218ac64829ada707d9d158905d2f8f24d7ac/worker/tokens.go#L10)):*
<details><summary><i>Previously, gacharya255 (Ganesh Acharya) wrote…</i></summary><blockquote>

function type
</blockquote></details>

My keyboard has problems with 't' ;) Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/704)*

**Comment by tzdybal** [comment]
Merged to master.

**Pull request closed without merging**
