### PR TITLE
Add memory usage by RocksDB in checkMemoryUsage

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph/137)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/lists.go, line 175 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/137#-KNae7lvv0_5oLkJasQ8:-KNae7lwwyAiJwgIfP85:131548132) ([raw file](https://github.com/dgraph-io/dgraph/blob/12b3a6128daf69151c5505a77d0bc20f2429bdf3/posting/lists.go#L175)):*
> ```Go
> }
> 
> func checkMemoryUsage(stores []*store.Store) {
> ```

This feels a bit ugly approach. Try to avoid having to generate a list of store pointers.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/137)*

**Comment by ashwin95r** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[posting/lists.go, line 175 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/dgraph/137#-KNae7lvv0_5oLkJasQ8:-KO5-XEspYwTSdBhPQ4T:1011252294) ([raw file](https://github.com/dgraph-io/dgraph/blob/12b3a6128daf69151c5505a77d0bc20f2429bdf3/posting/lists.go#L175)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This feels a bit ugly approach. Try to avoid having to generate a list of store pointers.
</details>
Modified the way the stores are passed as discussed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/137)*

**Comment by manishrjain** [comment]
Looks much better now! :lgtm: 

---

Reviewed 5 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/137#-:-KOAOU3YrqRnv3YoveFT:-923272211)*

**Comment by manishrjain** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/dgraph/137#-:-KOE-WNBv9ZpAw3fqBls:1417088721)*

**Comment by ashwin95r** [comment]
Merged to develop with commit 487420a859d2c02feb6b67a825075f851c6b5c88

**Pull request closed without merging**
